### ISSUE TITLE
Cannot run Set-AzKeyVaultAccessPolicy as a service principal

### ISSUE THREAD

**Issue by sasanmcp** [Azure/azure-powershell#10029]
I am running a PowerShell script as part of an Azure DevOps pipeline; through an Azure PowerShell Task. naturally the script is run within the context of the service principal under which the pipeline is configured to talk to the subscription.

when I run Set-AzKeyVaultAccessPolicy, I get 

##[error]Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.

error.

I can confirm that it is not a keyvault access policy issue because the lines right before this line have Set-AzKeyVaultSecret and Import-AzKeyVaultCertificate commands which go through successfully.

just as another piece of information, the pipeline service principal is inheriting "Contribute" permission from the resource group. I tried running the same script (having Set-AzKeyVaultAccessPolicy) with a "user" with the same "contribute" IAM inherited, and it does go through successfully; which means "contribute" is enough to be able to manipulate Access Policies. I just don't know why a "user" can do it but a "service principal" with exact same permissions can't.

just the error being not descriptive enough resembles like a bug to me, but I leave it up to the community to decide.

**Comment by coolnishantthakur** [comment]
I am having similar issue. There is similar issue discussed in https://github.com/Azure/azure-powershell/issues/8416 but no final outcome.

Are we missing any configuration ?

**Comment by sasanmcp** [comment]
right now as a workaround I created one of these, and deploy this arm; but it shouldn't be like this:
https://docs.microsoft.com/en-us/azure/templates/microsoft.keyvault/2018-02-14/vaults/accesspolicies

**Comment by kgehmlich** [comment]
I'm encountering the same issue as @sasanmcp. Is there an ETA on this?

**Comment by eanest** [comment]
i am unabl eto add accesspolciy toAKV using SPN used for service connection in Azure Devops, but using the same SPN i am able to add access policy through ARM, very strange

**Comment by dee3sync** [comment]
Ran into this issue today as well 
![image](https://user-images.githubusercontent.com/14794837/73485907-00faf180-4372-11ea-8ea7-d18c0258d7bb.png)

**Comment by ratnakarsinha** [comment]
Manage to make it work by using parameter -BypassObjectIdValidation

**Comment by CharlesAtDCube** [comment]
> Manage to make it work by using parameter -BypassObjectIdValidation

Thank you sooooo much !

**Comment by anderseide** [comment]
Had a similar issue when I tried to use New-AzRoleAssignment to set an RBAC role one Data Lake v2 container.

After reading the tip from@ratnakarsinha, I tried to add https://graph.microsoft.com/Application.Read.All permissions to the service principals application object, which worked for the New-AzRoleAssignment, but it seems like it doesn't work the same way for the Set-AzKeyVaultAccessPolicy

**Comment by ratnakarsinha** [comment]
This command worked for me -

Set-AzKeyVaultAccessPolicy -VaultName 'xxxx-xxxx' -ObjectId $(PrincipalId) -PermissionsToSecrets get -BypassObjectIdValidation

**Comment by kaushikgayal** [comment]
> Manage to make it work by using parameter -BypassObjectIdValidation

You are a gem :)

**Comment by KasperHoldum** [comment]
I had this problem as well. I tried the -ByPassObjectIdValidation, which allowed the code to run. It did, however, not fix the issue since the desired object did still not have desired permissions.

In my case I had used the wrong object ID. In the enterprise application page in Azure there is a link on the overview page labeled 'Managed application in local directory'. When using the object ID from this page the error went away without bypassing validation and the service principal got assigned the correct permissions in the key vault.

**Comment by rudfoss** [comment]
Just chiming in with the same issue. I'm running a DevOps pipeline using task `AzurePowerShell@4` with `azurePowerShellVersion: LatestVersion` on `windows-latest` hosted agent.

The script fails on this command (name and object id omitted):
```ps
Set-AzKeyVaultAccessPolicy -VaultName "***" -ObjectId "***" -PermissionsToSecrets @("get")
```

yet works fine running on my local machine. Adding `-ByPassObjectIdValidation` solves the issue when running on the build agent.

The error I'm getting is incredibly vague:

```
2020-05-11T09:08:04.6294007Z ##[command]Disconnect-AzAccount -Scope Process -ErrorAction Stop
2020-05-11T09:08:05.3741886Z ##[command]Clear-AzContext -Scope Process -ErrorAction Stop
2020-05-11T09:08:05.7726915Z ##[debug]Caught exception from task script.
2020-05-11T09:08:05.7827258Z ##[debug]Error record:
2020-05-11T09:08:06.1524470Z ##[debug]Set-AzKeyVaultAccessPolicy : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
2020-05-11T09:08:06.1554149Z ##[debug]At D:\a\_temp\2bacdf46-9dcf-412b-8509-6d1fa9c80238.ps1:3 char:1
2020-05-11T09:08:06.1585477Z ##[debug]+ Set-AzKeyVaultAccessPolicy -VaultName "UDIFormInfra-KEY-pr" -ObjectId ...
2020-05-11T09:08:06.1712672Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-05-11T09:08:06.1749268Z ##[debug]    + CategoryInfo          : CloseError: (:) [Set-AzKeyVaultAccessPolicy], CloudException
2020-05-11T09:08:06.1818999Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy
2020-05-11T09:08:06.1841328Z ##[debug] 
2020-05-11T09:08:06.1875475Z ##[debug]Script stack trace:
2020-05-11T09:08:06.1950041Z ##[debug]at <ScriptBlock>, D:\a\_temp\2bacdf46-9dcf-412b-8509-6d1fa9c80238.ps1: line 3
2020-05-11T09:08:06.1975029Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-05-11T09:08:06.2048737Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.168.0\azurepowershell.ps1: line 229
2020-05-11T09:08:06.2070827Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.168.0\azurepowershell.ps1: line 225
2020-05-11T09:08:06.2097922Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-05-11T09:08:06.2134103Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-05-11T09:08:06.2173624Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-05-11T09:08:06.2202796Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-05-11T09:08:06.2283292Z ##[debug]Exception:
2020-05-11T09:08:06.2429521Z ##[debug]Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
2020-05-11T09:08:06.2456512Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperations.<GetObjectsByObjectIdsWithHttpMessagesAsync>d__6.MoveNext()
2020-05-11T09:08:06.2496257Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2020-05-11T09:08:06.2556605Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2020-05-11T09:08:06.2612723Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-05-11T09:08:06.2638936Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.<GetObjectsByObjectIdsAsync>d__3.MoveNext()
2020-05-11T09:08:06.2663757Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2020-05-11T09:08:06.2686955Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2020-05-11T09:08:06.2711728Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-05-11T09:08:06.2825743Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.GetObjectsByObjectIds(IObjectsOperations operations, GetObjectsParameters parameters)
2020-05-11T09:08:06.2869527Z ##[debug]   at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryClient.GetObjectsByObjectId(List`1 objectIds)
2020-05-11T09:08:06.2980677Z ##[debug]   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.ValidateObjectId(String objId)
2020-05-11T09:08:06.3055677Z ##[debug]   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.GetObjectId(String objectId, String upn, String email, String spn)
2020-05-11T09:08:06.3056900Z ##[debug]   at Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy.ExecuteCmdlet()
2020-05-11T09:08:06.3093680Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2020-05-11T09:08:06.3355095Z ##[error]Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
2020-05-11T09:08:06.3422475Z ##[debug]Processed: ##vso[task.logissue type=error]Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
2020-05-11T09:08:06.3440021Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-05-11T09:08:06.4131012Z ##[section]Finishing: AzurePowerShell
```

**Comment by ShaneBala-keyvault** [comment]
This is a known product limitation. When using a service principal to grant access policy permissions, you must use the bypass object id validation parameter. (-BypassObjectIdValidation)

**Comment by dee3sync** [comment]
@ShaneBala-keyvault The doc's for Set-AzKeyVaultAccessPolicy https://docs.microsoft.com/en-us/powershell/module/az.keyvault/set-azkeyvaultaccesspolicy?view=azps-4.4.0 don't clearly state "When using a service principal to grant access policy permissions, you must use the bypass object id validation parameter."

**Comment by spaelling** [comment]
> 
> 
> This is a known product limitation. When using a service principal to grant access policy permissions, you must use the bypass object id validation parameter. (-BypassObjectIdValidation)

This is absolutely not a known product limitation. This is a first for me to hear this, and I am sure also a first for most others. Please reopen issue.

**Comment by M0ns1gn0r** [comment]
This is not a known product limitation, this is a mockery of your users.
