### ISSUE TITLE
Get-AzDataLakeStoreDeletedItem fails with notimplemented

### ISSUE THREAD

**Issue by jaws615** [Azure/azure-powershell#10052]
## Description
We are trying to recover a deleted item from an AZdatalake gen 1. 
we get the following when attempting to recover.

## Steps to reproduce

```powershell

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.15.0-1057-azure #62-Ubuntu SMP Thu Sep 5 18:25:30 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

## Module versions

```powershell
Script     1.0.1      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, R…
Script     1.2.2      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider,…
Script     1.0.1      Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, …
```

## Debug output

```
DEBUG: AzureQoSEvent: CommandName - Get-AzDataLakeStoreDeletedItem; IsSuccess - False; Duration - 00:00:01.3898064; Exception - Microsoft.Azure.DataLake.Store.AdlsException: Error in EnumerateDeletedItemsAsync hint:adl://kaminolakegen1.azuredatalakestore.net/Data/Etactics837Clearinghouse, listAfter:, numResults:100.
Operation: ENUMERATEDELETEDITEMS failed with HttpStatus:NotImplemented  RemoteException: RuntimeException Operation ENUMERATEDELETEDITEMS is not enabled.[2019-09-17T14:02:18.6341672-07:00] JavaClassName: java.lang.RuntimeException.
Last encountered exception thrown after 1 tries. [HTTP NotImplemented ( RuntimeException  Operation ENUMERATEDELETEDITEMS is not enabled.[2019-09-17T14:02:18.6341672-07:00] JavaClassName: java.lang.RuntimeException ]
[ServerRequestId:cf87d3c9-f574-45a1-b890-df22eed412d3]
   at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.TrackTaskProgress(Task task, Cmdlet commandToUpdateProgressFor, ProgressRecord taskProgress, CancellationToken token)
   at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.EnumerateDeletedItems(String accountName, String filter, Int32 count, Cmdlet cmdlet, CancellationToken cmdletCancellationToken)
   at Microsoft.Azure.Commands.DataLakeStore.GetAzureDataLakeStoreDeletedItem.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 9:02:19 PM - GetAzureDataLakeStoreDeletedItem end processing.
DEBUG: 9:02:19 PM - GetAzureDataLakeStoreDeletedItem end processing.

```

## Error output

```
DEBUG: >> MakePath([Az.Accounts, Resolve-AzError])
DEBUG: << MakePath([Az.Accounts, Resolve-AzError])
DEBUG: 9:02:59 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 9:02:59 PM - using account id 'MSI@50342'...


   HistoryId: 5
Message        : Error in EnumerateDeletedItemsAsync hint:adl://kaminolakegen1.azuredatalakestore.net/Data/Etactics837Clearinghouse, listAfter:,
                 numResults:100.
                 Operation: ENUMERATEDELETEDITEMS failed with HttpStatus:NotImplemented  RemoteException: RuntimeException Operation
                 ENUMERATEDELETEDITEMS is not enabled.[2019-09-17T14:02:18.6341672-07:00] JavaClassName: java.lang.RuntimeException.
                 Last encountered exception thrown after 1 tries. [HTTP NotImplemented ( RuntimeException  Operation ENUMERATEDELETEDITEMS is not
                 enabled.[2019-09-17T14:02:18.6341672-07:00] JavaClassName: java.lang.RuntimeException ]
                 [ServerRequestId:cf87d3c9-f574-45a1-b890-df22eed412d3]
StackTrace     :    at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.TrackTaskProgress(Task task, Cmdlet
                 commandToUpdateProgressFor, ProgressRecord taskProgress, CancellationToken token)
                    at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.EnumerateDeletedItems(String accountName, String
                 filter, Int32 count, Cmdlet cmdlet, CancellationToken cmdletCancellationToken)
                    at Microsoft.Azure.Commands.DataLakeStore.GetAzureDataLakeStoreDeletedItem.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.DataLake.Store.AdlsException
InvocationInfo : {Get-AzDataLakeStoreDeletedItem}
Line           : Get-AzDataLakeStoreDeletedItem -Account kaminolakegen1 -Filter
                 adl://kaminolakegen1.azuredatalakestore.net/Data/Etactics837Clearinghouse
Position       : At line:1 char:1
                 + Get-AzDataLakeStoreDeletedItem -Account kaminolakegen1 -Filter adl:// ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5


   HistoryId: 3
Message        : Cannot perform operation because operation "ReportWrongProviderType" is not valid. Remove operation "ReportWrongProviderType", or
                 investigate why it is not valid.
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Out-File}
Line           : Get-Module  -ListAvailable >> modules-shell
Position       : At line:1 char:1
                 + Get-Module  -ListAvailable >> modules-shell
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.0251547; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 9:02:59 PM - ResolveError end processing.
DEBUG: 9:02:59 PM - ResolveError end processing.

```

**Comment by marc-gmail-towersap** [comment]
been also experimenting with a gen2 datalake seeing if it works there, I get a different error.
Here, I have a gen2 datalake named marcdlsgen2sa.  I have set up my context (just to prove it works with a gen2 datalake).
via 
$storacct = Get-AzStorageAccount -ResourceGroupName marc-play-rg -AccountName marcdlsgen2sa
$ctx = $storacct.Context
I can run 
Get-AzDataLakeGen2ChildItem -Context $ctx -FileSystem marctplay -Path /notroot/mysub/ successfully, I see folders and files.
but when I delete a file in notroot/mysub, then go looking for it, 
Get-AzDataLakeStoreDeletedItem -Account marcdlsgen2sa -Filter /notroot/mysub/

I get 
Error in EnumerateDeletedItemsAsync hint:/notroot/mysub/ fails.

Get-AzDataLakeStoreDeletedItem : Error in EnumerateDeletedItemsAsync hint:marctplay/notroot/mysub/, listAfter:,
numResults:100.
Operation: ENUMERATEDELETEDITEMS failed with   Unknown Error: An error occurred while sending the request. Source:
mscorlib StackTrace:    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.DataLake.Store.WebTransport.<MakeSingleCallAsync>d__19.MoveNext().
.
Last encountered exception thrown after 5 tries. [An error occurred while sending the request.,An error occurred while
sending the request.,An error occurred while sending the request.,An error occurred while sending the request.,An
error occurred while sending the request.]
[ServerRequestId:]
At line:1 char:1
+ Get-AzDataLakeStoreDeletedItem -Account marcdlsgen2sa -Filter marctpl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzDataLakeStoreDeletedItem], AdlsException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataLakeStore.GetAzureDataLakeStoreDeletedItem

I get same error if I add the container name
/marctplay/notroot/mysub
and
marctplay/notroot/mysub
and 
notroot/mysub
