### ISSUE TITLE
Get-AzConsumptionUsageDetail

### ISSUE THREAD

**Issue by g-pearl** [Azure/azure-powershell#10203]
## Description
When trying to get consumptionusagedetail I get an error:

```
Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'BadGateway'

At line:1 char:1
+ Get-AzConsumptionUsageDetail
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzConsumptionUsageDetail], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail
```

## Steps to reproduce
````
connect using connect-azaccount
run Get-AzConsumptionUsageDetail
````

## Environment data
````
Multiple subscriptions under 1 tenant.
account running this is in a group that has Billing account as well as owner privilege to every subscription
````

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
## Module versions

```
Get-Module  -ListAvailable | Where name -like *az* | Select name, version

Name                   Version
----                   -------
Az.Accounts            1.6.2
Az.Advisor             1.0.1
Az.Aks                 1.0.2
Az.AnalysisServices    1.1.1
Az.ApiManagement       1.3.1
Az.ApplicationInsights 1.0.2
Az.Automation          1.3.3
Az.Batch               1.1.1
Az.Billing             1.0.1
Az.Cdn                 1.3.1
Az.CognitiveServices   1.2.1
Az.Compute             2.6.0
Az.ContainerInstance   1.0.1
Az.ContainerRegistry   1.1.0
Az.DataFactory         1.3.0
Az.DataLakeAnalytics   1.0.1
Az.DataLakeStore       1.2.2
Az.DeploymentManager   1.0.1
Az.DevTestLabs         1.0.0
Az.Dns                 1.1.1
Az.EventGrid           1.2.2
Az.EventHub            1.4.0
Az.FrontDoor           1.1.1
Az.HDInsight           2.0.2
Az.IotHub              1.3.0
Az.KeyVault            1.3.1
Az.LogicApp            1.3.1
Az.MachineLearning     1.1.1
Az.ManagedServices     1.0.1
Az.MarketplaceOrdering 1.0.1
Az.Media               1.1.0
Az.Monitor             1.3.0
Az.Network             1.14.0
Az.NotificationHubs    1.1.0
Az.OperationalInsights 1.3.3
Az.PolicyInsights      1.1.3
Az.PowerBIEmbedded     1.1.0
Az.RecoveryServices    1.4.5
Az.RedisCache          1.1.0
Az.Relay               1.0.2
Az.Resources           1.7.0
Az.ServiceBus          1.4.0
Az.ServiceFabric       1.2.0
Az.SignalR             1.1.0
Az.Sql                 1.14.2
Az.Storage             1.7.0
Az.StorageSync         1.2.0
Az.StreamAnalytics     1.0.0
Az.TrafficManager      1.0.2
Az.Websites            1.4.2
`
```

## Error output

```
Resolve-AzError
DEBUG: 1:24:25 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 1:24:25 PM - using account id 'Remove from output - but username is correct'...


   HistoryId: 24


Message        : Operation returned an invalid status code 'BadGateway'
StackTrace     :    at Microsoft.Azure.Management.Consumption.UsageDetailsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Consumption.UsageDetailsOperationsExtensions.<ListAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Consumption.Models.ErrorResponseException
InvocationInfo : {Get-AzConsumptionUsageDetail}
Line           : Get-AzConsumptionUsageDetail
Position       : At line:1 char:1
                 + Get-AzConsumptionUsageDetail
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 24



   HistoryId: 19


Message        : Operation returned an invalid status code 'BadGateway'
StackTrace     :    at Microsoft.Azure.Management.Consumption.UsageDetailsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Consumption.UsageDetailsOperationsExtensions.<ListAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Consumption.Models.ErrorResponseException
InvocationInfo : {Get-AzConsumptionUsageDetail}
Line           : Get-AzConsumptionUsageDetail
Position       : At line:1 char:1
                 + Get-AzConsumptionUsageDetail
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 19



   HistoryId: 12


Message        : Property "properties" cannot be found.
StackTrace     :
Exception      : System.Management.Automation.PSArgumentException
InvocationInfo : {Select-Object}
Line           : $usageData | select -ExpandProperty properties
Position       : At line:1 char:14
                 + $usageData | select -ExpandProperty properties
                 +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.0262397; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 1:24:25 PM - ResolveError end processing.
DEBUG: 1:24:25 PM - ResolveError end processing.
```

**Comment by darrellenns** [comment]
I am getting similar errors, but the status code changes semi-randomly. So far I've seen 'BadRequest", '422', and 'UnprocessableEntity'.

Local powershell session:
```
> Get-AzConsumptionUsageDetail
Get-AzConsumptionUsageDetail : Operation returned an invalid status code '422'
At line:1 char:1
+ Get-AzConsumptionUsageDetail
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzConsumptionUsageDetail], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail

> Get-AzConsumptionUsageDetail
Get-AzConsumptionUsageDetail : Operation returned an invalid status code '422'
At line:1 char:1
+ Get-AzConsumptionUsageDetail
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzConsumptionUsageDetail], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail

> Get-AzConsumptionUsageDetail
Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ Get-AzConsumptionUsageDetail
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzConsumptionUsageDetail], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail
```

Cloud shell:
```
> Get-AzConsumptionUsageDetail
Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'UnprocessableEntity'
At line:1 char:1
+ Get-AzConsumptionUsageDetail
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzConsumptionUsageDetail], ErrorResponseException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.UsageDetails.GetAzureRmConsumptionUsageDetail
```

**Comment by ms-premp** [comment]
@addesai looks like a timeout issue with Usage Details.

**Comment by addesai** [comment]
We have made significant reliability improvements in the last couple of months. Please let us know if you are still seeing this.

**Comment by Evogelpohl** [comment]
Same error:
Pseudo PowerShell script:  w/ Az Module 3.4.0
```
$x = Get-AzContexts -ListAvailable (i have 5 of them)
ForEach ($i in $x) {
   Set-AzContext blah
   Get-AzConsumptionUsageDetail -Top 10
}
```

The first runs fine. I get back the top 10.  Runs 2-5 fail w/ error: 
> Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'BadGateway'"

BTW - I ran the exact same process using AZ CLI CONSUMPTION USAGE LIST (get a similar, "max retries exceeded" error.

**Comment by PcChip** [comment]
still getting:  
Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'BadRequest'

**Comment by PcChip** [comment]
Hello, this is still not working 

I cannot pull a list of costs with Get-AzConsumptionUsageDetail  or with Az consumption usage list

I either get:
Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01

or:
Get-AzConsumptionUsageDetail : Operation returned an invalid status code 'BadRequest'

Can we please get an update on this?

**Comment by andymcadam** [comment]
I'm getting different results returned when rerunning the command for the same subscription. No errors showing at all. But a huge variation in results returned.

**Comment by PcChip** [comment]
Hello, is there any update on this?

**Comment by ArmaanMcleod** [comment]
I am also getting `Get-AzConsumptionUsageDetail: Operation returned an invalid status code 'BadRequest'`.

If I run in debug mode it gives me this return body:

```
Body:
{
  "error": {
    "code": "400",
    "message": "Cost Management supports only Enterprise Agreement, Web direct and Microsoft Customer Agreement offer types. Subscription xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx is not associated with a valid offer type. (Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)"
  }
}
```

Which seems to indicate that my subscription is not supported.

**Comment by tomasrudh** [comment]
I also have this problem, it makes it a lot harder to get cost for me. I can confirm that it seems as if the Powershell command Get-AzConsumptionUsageDetail is using an old version of the API.

Running these commands:
$DebugPreference="Continue"
$vm = Get-AzVM -ResourceGroupName <resource group> -Name <vm name>
Get-AzConsumptionUsageDetail -StartDate (Get-Date).AddDays(-30) -EndDate (Get-Date) -InstanceId $vm.Id
gives this error:

Body:
{
  "error": {
    "code": "400",
    "message": "Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01 (Request ID: 728b27a3-b5c6-41cc-9834-acd8373305be)"
  }
}
and
Get-AzConsumptionUsageDetail: Operation returned an invalid status code 'BadRequest'

According to MS support is this due to the fact that we are using 'modern subscription', not sure what that is. They don't have an estimate when it will be fixed.

I want to emphasize that this is a big problem. Is anyone working on it? Is there an ETA?

Thanks!

**Comment by dalihendaoui** [comment]
@tomasrudh 
> I also have this problem, it makes it a lot harder to get cost for me. I can confirm that it seems as if the Powershell command Get-AzConsumptionUsageDetail is using an old version of the API.
> 
> Running these commands: $DebugPreference="Continue" $vm = Get-AzVM -ResourceGroupName -Name Get-AzConsumptionUsageDetail -StartDate (Get-Date).AddDays(-30) -EndDate (Get-Date) -InstanceId $vm.Id gives this error:
> 
> Body: { "error": { "code": "400", "message": "Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01 (Request ID: 728b27a3-b5c6-41cc-9834-acd8373305be)" } } and Get-AzConsumptionUsageDetail: Operation returned an invalid status code 'BadRequest'
> 
> According to MS support is this due to the fact that we are using 'modern subscription', not sure what that is. They don't have an estimate when it will be fixed.
> 
> I want to emphasize that this is a big problem. Is anyone working on it? Is there an ETA?
> 
> Thanks!

I totally agree with you, this is a big issue for a lot of users obv and it has to be looked into, can we have an ETA on this issue ? anyone ?

**Comment by dalihendaoui** [comment]
@tomasrudh  did you find any workaround ? anyone ?

**Comment by g-pearl** [comment]
Only recently have I been able to get around this by calling an API directly: - Spent last 3 weeks on this actually

https://learn.microsoft.com/en-us/rest/api/cost-management/generate-cost-details-report/create-operation?tabs=HTTP

This allows you to set the API version specifically.  I am also under the modern subscription so I have had to fight all sort of issues.


```
##Get billing Info
$Billing_Account_URI =  "https://management.azure.com/providers/Microsoft.Billing/billingAccounts?api-version=2020-05-01"
$Billing_Account_Results = Invoke-RestMethod $Billing_Account_URI -Headers $headers -ContentType "application/json"
```


```
##Loop Subscriptions  and get usage results
foreach ($subscription in $subscriptions) {
 Write-Host "Querying Azure Usage API for subscription $($subscription.id) with name $($subscription.name) [$i of $($subscriptions.count)]"
    $I++

    do {
        Write-Host "."
        $usageResult = Invoke-RestMethod $usageUri -Headers $headers -ContentType "application/json"
        
        $max_retry = 0
        if ($? -eq $false)
          {
            do {
              write-host "`tPausing Script for 60 Seconds - due to an error" -BackgroundColor Gray -foregroundcolor red
              start-sleep -Seconds 60
              $usageResult = Invoke-RestMethod $usageUri -Headers $headers -ContentType "application/json"
              $max_retry++
              #may want to put maximum retry limit on this...
            } while ($? -eq $false -or $max_retry -le 3)
          }



        foreach ($usageRow in $usageResult.value) {
            $usageRows.Add($usageRow) > $null
        }

        $usageUri = $usageResult.nextLink

        # If there's a continuation, then call API again
    } while ($usageUri)

```


This does not get tax and reservation information - additional API calls get that info.
There is a bug in the latest API version for reservation I had to use only version for this

**Comment by g-pearl** [comment]
I can not post all code. 

What is it that you are having issues with?

This may be the parts that is tripping you up.

```
$token = Get-AzAccessToken  #may have to use connect-azaccount beforehand
$authorization = $token.type + ' ' + $token.token

$headers = @{
    authorization = $authorization
}

$subscriptions = Get-AzSubscription 


```

**Comment by g-pearl** [comment]
The **$Billing_Account_Results** is just another API endpoint that you can call to get you billing details (Account ID etc...)  To see the info in that variable just do $Billing_Account_Results | OGV.


If the script rans you should now have a variable "$usageRows" that contains all the costs.  Again pipe that to OGV (out-gridview) to see.  

I am personally pushing the results to excel using the importexcel module.  With that I am creating pivot tables and charts based on my requirements.

**Comment by g-pearl** [comment]
```
$startdate = "2023-04-01"
$enddate = "2023-04-30"
$apiVersion = "2023-03-01"

#this would go in the foreach loop
$usageUri = "https://management.azure.com/subscriptions/$($subscription.id)/providers/Microsoft.Consumption/usageDetails?startDate=$startDate&endDate=$endDate&api-version=$apiVersion"


```
