### ISSUE TITLE
One test case of DataLakeStore module constantly fails randomly at linux environment only.

### ISSUE THREAD

**Issue by VeryEarly** [Azure/azure-powershell#10667]
## Description
This single test case `Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests.TestAdlsFileSystem`, fails randomly time and time again. This affects our efficiency to review PRs.

Need to investigate.

Sample PR: https://github.com/Azure/azure-powershell/pull/10755
CI job: https://dev.azure.com/azure-sdk/public/_build/results?buildId=231953
Log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=231953&view=logs&j=ad07b744-5a1a-5d54-7693-fcb02e666633&t=b0841cae-a6b1-5a5c-4ebd-3cc6b3d3163d&l=704

Log snippet:
```
  [xUnit.net 00:00:15.65]     Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests.TestAdlsFileSystem [FAIL]
    X Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests.TestAdlsFileSystem [2s 950ms]
EXEC : error Message:  [/home/vsts/work/1/s/build.proj]
     System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
    Stack Trace:
       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
     at System.Management.Automation.Runspaces.Pipeline.Invoke()
     at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
     at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
     at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.Invoke()
     at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 571
     at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTestsBase.RunPsTestWorkflow(Func`1 scriptBuilder, Action cleanup, String callingClassType, String mockName) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs:line 115
     at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTestsBase.RunPsTest(XunitTracingInterceptor logger, String[] scripts) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs:line 66
     at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests.TestAdlsFileSystem() in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.cs:line 76
    Standard Output Messages:
   $ProgressPreference="SilentlyContinue"
   Test-DataLakeStoreFileSystem -fileToCopy '/home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/bin/Debug/netcoreapp2.2/ScenarioTests/AdlsAliasTests.ps1' -location 'westus'
   Caught Exception: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
      at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
      at System.Management.Automation.Runspaces.Pipeline.Invoke()
      at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
      at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
      at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.Invoke()
      at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 571
   Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
EXEC : PowerShell error Record: Object reference not set to an instance of an object. [/home/vsts/work/1/s/build.proj]
   Exception:System.NullReferenceException: Object reference not set to an instance of an object.
      at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.TrackTaskProgress(Task task, Cmdlet commandToUpdateProgressFor, ProgressRecord taskProgress, CancellationToken token) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs:line 886
      at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.GetFileProperties(String accountName, String path, Boolean getAclUsage, String dumpFileName, Boolean getDiskUsage, Boolean saveToLocal, Int32 numThreads, Boolean displayFiles, Boolean hideConsistentAcl, Int64 maxDepth, Cmdlet cmdlet, CancellationToken cmdletCancellationToken) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs:line 762
      at Microsoft.Azure.Commands.DataLakeStore.ExportAzureRmDataLakeStoreChildItemProperties.ExecuteCmdlet() in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneCommands/ExportAzureRmDataLakeStoreChildItemProperties.cs:line 93
      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
   Details:
   Script Stack Trace: at Test-DataLakeStoreFileSystem, /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/bin/Debug/netcoreapp2.2/ScenarioTests/AdlsAliasTests.ps1: line 705
```

**Comment by isra-fel** [comment]
@dingmeng-xue could we re-triage this issue? Because it's slowing down our PR reviews. Thanks

**Comment by dingmeng-xue** [comment]
sure. if we meet it again, please provide logs and link of pipeline.

**Comment by isra-fel** [comment]
Again in https://github.com/Azure/azure-powershell/pull/10894

**Comment by dingmeng-xue** [comment]
Upload another incident.
[_fv-az767_2020-02-10_17_03_31.log](https://github.com/Azure/azure-powershell/files/4217129/_fv-az767_2020-02-10_17_03_31.log)

**Comment by msJinLei** [comment]
Failure still occurs

```
2020-11-16T07:38:23.5919227Z   [xUnit.net 00:00:14.86]     Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests.TestAdlsFileSystem [FAIL]
2020-11-16T07:38:23.8484235Z     X Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests.TestAdlsFileSystem [3s 280ms]
2020-11-16T07:38:23.8620932Z EXEC : error Message:  [/home/vsts/work/1/s/build.proj]
2020-11-16T07:38:23.8622633Z      System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
2020-11-16T07:38:23.8623719Z     Stack Trace:
2020-11-16T07:38:23.8624860Z        at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2020-11-16T07:38:23.8626333Z      at System.Management.Automation.Runspaces.Pipeline.Invoke()
2020-11-16T07:38:23.8634096Z      at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2020-11-16T07:38:23.8634886Z      at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2020-11-16T07:38:23.8635510Z      at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2020-11-16T07:38:23.8636228Z      at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2020-11-16T07:38:23.8636881Z      at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2020-11-16T07:38:23.8637633Z      at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2020-11-16T07:38:23.8638051Z      at System.Management.Automation.PowerShell.Invoke()
2020-11-16T07:38:23.8638648Z      at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 573
2020-11-16T07:38:23.8639601Z      at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTestsBase.RunPsTestWorkflow(Func`1 scriptBuilder, Action cleanup, String callingClassType, String mockName) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs:line 116
2020-11-16T07:38:23.8640614Z      at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTestsBase.RunPsTest(XunitTracingInterceptor logger, String[] scripts) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs:line 67
2020-11-16T07:38:23.8651157Z      at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTests.TestAdlsFileSystem() in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTests.cs:line 75
2020-11-16T07:38:23.8654108Z     Standard Output Messages:
2020-11-16T07:38:23.8655837Z    $ProgressPreference="SilentlyContinue"
2020-11-16T07:38:23.8657899Z    Test-DataLakeStoreFileSystem -fileToCopy '/home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/bin/Debug/netcoreapp2.1/ScenarioTests/AdlsTests.ps1' -location 'eastus2'
2020-11-16T07:38:23.8660164Z    Caught Exception: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
2020-11-16T07:38:23.8662984Z       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2020-11-16T07:38:23.8664235Z       at System.Management.Automation.Runspaces.Pipeline.Invoke()
2020-11-16T07:38:23.8665511Z       at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2020-11-16T07:38:23.8666918Z       at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2020-11-16T07:38:23.8668108Z       at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2020-11-16T07:38:23.8669744Z       at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2020-11-16T07:38:23.8670894Z       at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2020-11-16T07:38:23.8671537Z       at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2020-11-16T07:38:23.8672050Z       at System.Management.Automation.PowerShell.Invoke()
2020-11-16T07:38:23.8672724Z       at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 573
2020-11-16T07:38:23.8673779Z    Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
2020-11-16T07:38:23.8674615Z EXEC : PowerShell error Record: Object reference not set to an instance of an object. [/home/vsts/work/1/s/build.proj]
2020-11-16T07:38:23.8675246Z    Exception:System.NullReferenceException: Object reference not set to an instance of an object.
2020-11-16T07:38:23.8676173Z       at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.TrackTaskProgress(Task task, Cmdlet commandToUpdateProgressFor, ProgressRecord taskProgress, CancellationToken token) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs:line 886
2020-11-16T07:38:23.8677799Z       at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.GetFileProperties(String accountName, String path, Boolean getAclUsage, String dumpFileName, Boolean getDiskUsage, Boolean saveToLocal, Int32 numThreads, Boolean displayFiles, Boolean hideConsistentAcl, Int64 maxDepth, Cmdlet cmdlet, CancellationToken cmdletCancellationToken) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs:line 762
2020-11-16T07:38:23.8679220Z       at Microsoft.Azure.Commands.DataLakeStore.ExportAzureRmDataLakeStoreChildItemProperties.ExecuteCmdlet() in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneCommands/ExportAzureRmDataLakeStoreChildItemProperties.cs:line 93
2020-11-16T07:38:23.8680018Z       at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2020-11-16T07:38:23.8680469Z    Details:
2020-11-16T07:38:23.8717057Z    Script Stack Trace: at Test-DataLakeStoreFileSystem, /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/bin/Debug/netcoreapp2.1/ScenarioTests/AdlsTests.ps1: line 710
2020-11-16T07:38:23.8717852Z    at <ScriptBlock>, <No file>: line 1
2020-11-16T07:38:24.5935479Z    : Target: 
2020-11-16T07:38:24.5936153Z    
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=618431&view=logs&j=c13f50be-40fa-55ea-9864-e9bc7c81964b&t=2e4a7a65-6e62-5c9c-6df6-25e0a9fb7a74

**Comment by msJinLei** [comment]
Another failed test case
```
  [xUnit.net 00:00:18.19]     Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests.TestAdlsFileSystemPermissions [FAIL]
    X Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests.TestAdlsFileSystemPermissions [2s 298ms]
EXEC : error Message:  [/home/vsts/work/1/s/build.proj]
     System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
    Stack Trace:
       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
     at System.Management.Automation.Runspaces.Pipeline.Invoke()
     at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
     at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
     at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.Invoke()
     at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 573
     at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTestsBase.RunPsTestWorkflow(Func`1 scriptBuilder, Action cleanup, String callingClassType, String mockName) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs:line 116
     at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsTestsBase.RunPsTest(XunitTracingInterceptor logger, String[] scripts) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsTestsBase.cs:line 67
     at Microsoft.Azure.Commands.DataLakeStore.Test.ScenarioTests.AdlsAliasTests.TestAdlsFileSystemPermissions() in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/ScenarioTests/AdlsAliasTests.cs:line 83
    Standard Output Messages:
   $ProgressPreference="SilentlyContinue"
   Test-DataLakeStoreFileSystemPermissions -location 'westus'
   Caught Exception: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
      at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
      at System.Management.Automation.Runspaces.Pipeline.Invoke()
      at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
      at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
      at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.Invoke()
      at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 573
   Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Object reference not set to an instance of an object.
EXEC : PowerShell error Record: Object reference not set to an instance of an object. [/home/vsts/work/1/s/build.proj]
   Exception:System.NullReferenceException: Object reference not set to an instance of an object.
      at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.TrackTaskProgress(Task task, Cmdlet commandToUpdateProgressFor, ProgressRecord taskProgress, CancellationToken token) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs:line 886
      at Microsoft.Azure.Commands.DataLakeStore.Models.DataLakeStoreFileSystemClient.GetFileProperties(String accountName, String path, Boolean getAclUsage, String dumpFileName, Boolean getDiskUsage, Boolean saveToLocal, Int32 numThreads, Boolean displayFiles, Boolean hideConsistentAcl, Int64 maxDepth, Cmdlet cmdlet, CancellationToken cmdletCancellationToken) in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneModels/DataLakeStoreFileSystemClient.cs:line 762
      at Microsoft.Azure.Commands.DataLakeStore.ExportAzureRmDataLakeStoreChildItemProperties.ExecuteCmdlet() in /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore/DataPlaneCommands/ExportAzureRmDataLakeStoreChildItemProperties.cs:line 93
      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
   Details:
   Script Stack Trace: at Test-DataLakeStoreFileSystemPermissions, /home/vsts/work/1/s/src/DataLakeStore/DataLakeStore.Test/bin/Debug/netcoreapp2.1/ScenarioTests/AdlsAliasTests.ps1: line 867
   at <ScriptBlock>, <No file>: line 1
   : Target: 
   
```

**Comment by rahuldutta90** [comment]
@msJinLei  Ack. For now i will send out a pr to disable the specific tests related to GetFileProperties to reduce the getfileproperties failure
