### ISSUE TITLE
ObjectDisposedException thrown with New-AzFunctionAppPlan

### ISSUE THREAD

**Issue by tcsdmaic** [Azure/azure-powershell#10756]
## Description
I tried creating a new app service plan to use for my function app like so:

```powershell
New-AzFunctionAppPlan -Name $ASPName -ResourceGroupName $RGName -Sku "EP1" -WorkerType "Windows" -Location $Location
```

But I get this error:

> Az.Functions.internal\New-AzFunctionAppPlan : Cannot access a disposed object.
> Object name: 'System.Net.Http.StringContent'.
> At C:\Program Files\WindowsPowerShell\Modules\Az.Functions\0.0.1\custom\New-AzFunctionAppPlan.ps1:219 char:21
> + ...             $createdPlan = Az.Functions.internal\New-AzFunctionAppPla ...

I stepped through it and see that actually that line, line 219 in New-AzFunctionAppPlan.ps1, steps into line 2646 in ProxyCmdletDefinitions.ps1.  That will step through until getting to line 2673 `$steppablePipeline.Process($_)` - that is what throws the System.ObjectDisposedException.

## Steps to reproduce

Try using New-AzFunctionAppPlan as in the example above.

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.6.4      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.6.2      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.0.1      Az.Advisor                          {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, Get-AzAdvisorConfiguration...}
Script     1.0.2      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.1.1      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}
Script     1.3.1      Az.ApiManagement                    {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzApiManagementUserToGroup...}
Script     1.0.2      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan...}
Script     1.3.3      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...}
Script     1.1.1      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount...}
Script     1.0.1      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}
Script     1.3.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.2.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSku, Get-AzCognitiveServicesAccountType...}
Script     2.6.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.0.1      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.1.0      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}
Script     1.3.0      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.1      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCata...
Script     1.2.2      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvid...
Script     1.0.1      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-AzDeploymentManagerArtifactSource, Remove-AzDeploymentManagerArtifa...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}
Script     1.1.1      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}
Script     1.2.2      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}
Script     1.4.0      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.1.1      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor...}
Script     0.0.1      Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan, New-AzFunctionApp...}
Script     2.0.2      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition...}
Script     1.3.0      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}
Script     1.3.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}
Script     1.3.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl...}
Script     1.1.1      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan...}
Script     1.0.1      Az.ManagedServices                  {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedServicesAssignment, Get-AzManagedServicesDefinition...}
Script     1.0.1      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.0      Az.Media                            {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzMediaServiceNameAvailability...}
Script     1.3.0      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     1.14.0     Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertifica...
Script     1.1.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Get-AzNotificationHubPNSCredential...}
Script     1.3.3      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollect...
Script     1.1.3      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}
Script     1.1.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKey, Get-AzPowerBIWorkspace...}
Script     1.4.5      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}
Script     1.1.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule...}
Script     1.0.2      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}
Script     1.7.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.4.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}
Script     1.2.0      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}
Script     1.1.0      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     1.14.2     Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSql...
Script     1.7.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.2.0      Az.StorageSync                      {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncService, Remove-AzStorageSyncService...}
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction...}
Script     1.0.2      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTraf...
Script     1.4.2      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
Binary     2.0.2.61   AzureAD                             {Add-AzureADApplicationOwner, Get-AzureADApplication, Get-AzureADApplicationExtensionProperty, Get-AzureADApplicationOwner...}
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}
Script     1.4.5      PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     3.4.0      Pester                              {Describe, Context, It, Should...}
Script     2.2.1      PowerShellGet                       {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption...}
```

## Debug output

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/[my sub]/resourceGroups/[my RG]/providers/Microsoft.Web/serverfarms/[my plan]?api-version=2018-02-01

Headers:

Body:
{
  "location": "West US",
  "properties": {
    "reserved": false
  },
  "sku": {
    "name": "EP1",
    "tier": "ElasticPremium"
  }
}


DEBUG: BeforeCall: 
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8695489Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8695489Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8695489Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: === Token Acquisition started: 
        CacheType: null
        Authentication Target: User
        , Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8695489Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: === Token Acquisition started:
        Authority: https://login.microsoftonline.com/5b268d57-2a6f-4e04-b0de-6938583d5ebc/
        Resource: https://management.core.windows.net/
        ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
        CacheType: null
        Authentication Target: User

DEBUG: [ADAL]: Verbose: 2019-12-20T18:56:56.8695489Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2019-12-20T18:56:56.8695489Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.
DEBUG: [ADAL]: Verbose: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: An item matching the requested resource was
found in the cache
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: An item matching the requested resource was
found in the cache
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: 59.92254052 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: 59.92254052 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 12/20/2019 7:56:52 PM +00:00
DEBUG: [ADAL]: Information: 2019-12-20T18:56:56.8705688Z: b1357627-bd54-42a8-a739-2a00f64e625c - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 12/20/2019 7:56:52 PM +00:00Access Token Hash: [hash]
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 8bd7deec-6f4a-4d43-8e66-f8cfd3d06637
x-ms-correlation-request-id   : 8bd7deec-6f4a-4d43-8e66-f8cfd3d06637
x-ms-routing-request-id       : CANADAEAST:20191220T185657Z:8bd7deec-6f4a-4d43-8e66-f8cfd3d06637
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Fri, 20 Dec 2019 18:56:56 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "Code": "BadRequest",
  "Message": "Requested feature is not available in resource group [My RG]. Please try using a different resource group or create a new one.",
  "Target": null,
  "Details": [
    {
      "Message": "Requested feature is not available in resource group [My RG]. Please try using a different resource group or create a new one."
    },
    {
      "Code": "BadRequest"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "59324",
        "MessageTemplate": "Requested feature is not available in resource group {0}. Please try using a different resource group or create a new one.",
        "Parameters": [
          "[My RG]"
        ],
        "Code": "BadRequest",
        "Message": "Requested feature is not available in resource group [My RG]. Please try using a different resource group or create a new one."
      }
    }
  ],
  "Innererror": null
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
DEBUG: Finally: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'New-AzFunctionAppPlan_Create': AzureQoSEvent: CommandName - New-AzFunctionAppPlan_Create; IsSuccess - True; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: [CmdletException]: Received Exception with message 'ObjectDisposedException - Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'. :    at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at Microsoft.Azure.PowerShell.Cmdlets.Functions.Runtime.Extensions.<CloneWithContent>d__51.MoveNext()'
DEBUG: CmdletException: ObjectDisposedException - Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'. :    at System.Net.Http.HttpContent.CheckDisposed()
   at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
   at Microsoft.Azure.PowerShell.Cmdlets.Functions.Runtime.Extensions.<CloneWithContent>d__51.MoveNext()
DEBUG: CmdletProcessRecordEnd: 
Error creating new function app: Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
At [my script]
+         Throw "Error creating new function app: $($_.Exception.Messag ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Error creating ...StringContent'.:String) [], RuntimeException
    + FullyQualifiedErrorId : Error creating new function app: Cannot access a disposed object.
Object name: 'System.Net.Http.StringContent'.
```

## Error output

```
Message        : Cannot access a disposed object.
                 Object name: 'System.Net.Http.StringContent'.
StackTrace     :    at System.Net.Http.HttpContent.CheckDisposed()
                    at System.Net.Http.HttpContent.CopyToAsync(Stream stream, TransportContext context)
                    at Microsoft.Azure.PowerShell.Cmdlets.Functions.Runtime.Extensions.<CloneWithContent>d__51.MoveNext()
Exception      : System.ObjectDisposedException
InvocationInfo : {New-AzFunctionAppPlan_Create}
Line           :                     $createdPlan = Az.Functions.internal\New-AzFunctionAppPlan @PSBoundParameters

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Functions\0.0.1\custom\New-AzFunctionAppPlan.ps1:219 char:21
                 + ...             $createdPlan = Az.Functions.internal\New-AzFunctionAppPla ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dingmeng-xue** [comment]
We need Functions team's help to look into it at first.

**Comment by Francisco-Gamino** [comment]
Hello @tcsdmaic,

Thanks for reporting this issue. I will followup with @dingmeng-xue to get this fixed in PowerShell 5.1. In the meantime, could you please try using the Az.Functions cmdlets in `pwsh` 6.2 or greater. You can download it from https://github.com/PowerShell/PowerShell/releases. Please let me know if you run into any issues.

Thanks,
Francisco

**Comment by Francisco-Gamino** [comment]
Hello @dingmeng-xue -- this issue is in the infrastructure from the generated code. Could you please take a look? This only repros on Windows PowerShell 5.1.

**Comment by dingmeng-xue** [comment]
@dolauli , please look into this issue.

**Comment by Francisco-Gamino** [comment]
cc: @stefanushinardi @anirudhgarg

**Comment by Francisco-Gamino** [comment]
Hello @dingmeng-xue and @dolauli -- Is there an update on this investigation? Let us know if you need if you need anything from our side. Thanks.

**Comment by Francisco-Gamino** [comment]
Adding work item to enable validating Az modules from the generation branch against PowerShell 5.1. For more information, please see https://github.com/Azure/azure-powershell/issues/16265
