### ISSUE TITLE
Error in Set-AzActionGroup while using -InputObject

### ISSUE THREAD

**Issue by durayakar** [Azure/azure-powershell#10868]
## Description
I want to update my existing  ActionGroups in order to add an Azure Function receiver. 
I manually add the Function Receiver on the portal to one Action Group.
I am trying to use Set-AzActionGroup to add it to all other existing Action Groups.
Set-AzActionGroup throws an exception while piping in an object retrieved by Get-AzActionGroup.
The repro below is simplified to isolate the issue, as the command fails even without any updates
It looks like the AZ code is calling AzureRm code and the object type conversions are not done there...

## Steps to reproduce
1. Open CloudShell
2. Retrieve all ActionGroup objects using Get-AzActionGroup command
4. Ensure there are objects
3. Pipe one ActionGroup object to Set-AzActionGroup Command
```powershell
$aGroups = Get-AzActionGroup
$aGroups.Count 
# 2 
$aGroups[0] | Set-AzActionGroup
```

## Environment data

```
PS Azure:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.15.0-1066-azure #71-Ubuntu SMP Thu Dec 12 20:35:32 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

## Module versions

```powershell
PS Azure:\> get-module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.6.5      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     3.2.0      Az.Compute                          {Add-AzContainerServiceAgentPoolProfile, Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent…}
Script     2.2.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplic…
Script     1.9.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication…}
Script     1.10.0     Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkR…
Script     0.0.0.10   AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureAD…
Script     0.9.3      AzurePSDrive
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty…}
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object…}
Script     0.9.3      PSCloudShellUtility                 {Disable-AzVMPSRemoting, Dismount-CloudDrive, Enable-AzVMPSRemoting, Enter-AzVM…}
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PSReadLineKeyHandler, Set-PSReadLineKeyHandler…}
Binary     0.8.1      SHiPS
```

## Debug output

```
PS Azure:\> $aGroups[0] | Set-AzActionGroup -Debug
DEBUG: 3:53:00 AM - SetAzureRmActionGroupCommand begin processing with ParameterSet 'ByPropertyName'.
DEBUG: 3:53:00 AM - using account id 'MSI@50342'...
WARNING: 3:53:00 AM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
WARNING: 3:53:05 AM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.

Confirm
Are you sure you want to perform this action?
Performing the operation "Add/update action group" on target "Add/update action group:  from resource group: ".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: '7a4ca4e9-b298-490f-9b99-f31298c713d5'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
Set-AzActionGroup : Exception type: ValidationException, Message: Microsoft.Rest.ValidationException: 'actionGroupName' cannot be null.
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdateAsync(IActionGroupsOperations operations, String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdate(IActionGroupsOperations operations, String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup)
   at Microsoft.Azure.Commands.Insights.ActionGroups.SetAzureRmActionGroupCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
At line:1 char:15
+ $aGroups[0] | Set-AzActionGroup -Debug
+               ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzActionGroup], PSInvalidOperationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.ActionGroups.SetAzureRmActionGroupCommand

DEBUG: AzureQoSEvent: CommandName - Set-AzActionGroup; IsSuccess - False; Duration - 00:00:07.5784331; Exception - System.Management.Automation.PSInvalidOperationException: Exception type: ValidationException, Message: Microsoft.Rest.ValidationException: 'actionGroupName' cannot be null.
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdateAsync(IActionGroupsOperations operations, String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdate(IActionGroupsOperations operations, String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup)
   at Microsoft.Azure.Commands.Insights.ActionGroups.SetAzureRmActionGroupCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null ---> Microsoft.Rest.ValidationException: 'actionGroupName' cannot be null.
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdateAsync(IActionGroupsOperations operations, String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdate(IActionGroupsOperations operations, String resourceGroupName, String actionGroupName, ActionGroupResource actionGroup)
   at Microsoft.Azure.Commands.Insights.ActionGroups.SetAzureRmActionGroupCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 3:53:07 AM - SetAzureRmActionGroupCommand end processing.
DEBUG: 3:53:07 AM - SetAzureRmActionGroupCommand end processing.
```

## Error output

```
Message        : Exception type: ValidationException, Message: Microsoft.Rest.ValidationException: 'actionGroupName' cannot be null.
                    at Microsoft.Azure.Management.Monitor.ActionGroupsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String actionGroupName,
                 ActionGroupResource actionGroup, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdateAsync(IActionGroupsOperations operations, String
                 resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdate(IActionGroupsOperations operations, String
                 resourceGroupName, String actionGroupName, ActionGroupResource actionGroup)
                    at Microsoft.Azure.Commands.Insights.ActionGroups.SetAzureRmActionGroupCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Set-AzActionGroup}
Line           : $aGroups[0] | Set-AzActionGroup
Position       : At line:1 char:15
                 + $aGroups[0] | Set-AzActionGroup
                 +               ~~~~~~~~~~~~~~~~~
HistoryId      : 6

Message        : 'actionGroupName' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Monitor.ActionGroupsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String actionGroupName,
                 ActionGroupResource actionGroup, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdateAsync(IActionGroupsOperations operations, String
                 resourceGroupName, String actionGroupName, ActionGroupResource actionGroup, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Monitor.ActionGroupsOperationsExtensions.CreateOrUpdate(IActionGroupsOperations operations, String
                 resourceGroupName, String actionGroupName, ActionGroupResource actionGroup)
                    at Microsoft.Azure.Commands.Insights.ActionGroups.SetAzureRmActionGroupCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Set-AzActionGroup}
Line           : $aGroups[0] | Set-AzActionGroup
Position       : At line:1 char:15
                 + $aGroups[0] | Set-AzActionGroup
                 +               ~~~~~~~~~~~~~~~~~
HistoryId      : 6
```

**Comment by durayakar** [comment]
At first look, in the code, "Name" assignment is missing inside the ByInputObject block
Adding below may resolve the issue
```
this.Name = this.InputObject.Name;
```                 


```
 if (ParameterSetName == ByInputObject)
                {
                    this.ResourceGroupName = this.InputObject.ResourceGroupName;
                    if (this.ShortName == null)
                    {
                        this.ShortName = this.InputObject.GroupShortName;
                    }
                    if (!this.DisableGroup.IsPresent)
                    {
                        this.DisableGroup = !this.InputObject.Enabled;
                    }
                    if (this.Tag == null)
                    {
                        this.Tag = this.InputObject.Tags;
                    }
```

**Comment by dingmeng-xue** [comment]
Monitor team, when input object is ActionGroup, the name is not set into current class. 
https://github.com/Azure/azure-powershell/blob/ad439f07bc007f3736e378bd28a33a0be7a3d3c4/src/Monitor/Monitor/ActionGroups/SetAzureRmActionGroupCommand.cs#L114
As the result, name is empty when PSActionGroupResource is constructed.
https://github.com/Azure/azure-powershell/blob/ad439f07bc007f3736e378bd28a33a0be7a3d3c4/src/Monitor/Monitor/ActionGroups/SetAzureRmActionGroupCommand.cs#L238
