### ISSUE TITLE
New-AzADServicePrincipal does not work with ApplicationObject param

### ISSUE THREAD

**Issue by bgawale** [Azure/azure-powershell#10954]
## Description

New-AzADServicePrincipal does not seem to be working when the parameter ApplicationObject is passed to it. 
It errors out in the message: _Parameter set cannot be resolved using the specified named parameters._

## Steps to reproduce
```powershell
 $Application = Get-AzADApplication -IdentifierUri "urn:some-existing-app-uri"
 New-AzADServicePrincipal -ApplicationObject $Application
```
Note that the $Application is not null and is the correct object whose service principal needs to be provisioned. Command below also fails 

```powershell
  Get-AzADApplication -ApplicationObject $Application | New-AzADServicePrincipal
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.9.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
```

## Debug output

```

```

## Error output

```
Message        : Parameter set cannot be resolved using the specified named parameters.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException(UInt32 parameterSetFlags, MergedCommandParameterMetadata bindableParameters)
                    at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean prePipelineInput, Boolean setDefault)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections,
                 FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           : New-AzADServicePrincipal -ApplicationObject $Application
Position       : At line:1 char:1
                 + New-AzADServicePrincipal -ApplicationObject $Application
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 15
```

**Comment by dingmeng-xue** [comment]
parameter set of New-AzADServicePrincipal has confusion when there is only ApplicationObject
```
New-AzADServicePrincipal
   -ApplicationObject <PSADApplication>
   [-DefaultProfile <IAzureContextContainer>]
   [-WhatIf]
   [-Confirm]
   [<CommonParameters>]
```
```
New-AzADServicePrincipal
   -ApplicationObject <PSADApplication>
   [-StartDate <DateTime>]
   [-EndDate <DateTime>]
   [-DefaultProfile <IAzureContextContainer>]
   [-WhatIf]
   [-Confirm]
   [<CommonParameters>]
```

**Comment by markcowl** [comment]
Yes, that is precisely the issue.  Seems like we can remove the first parameter set and resolve the issue without breakign changes

**Comment by msJinLei** [comment]
@dingmeng-xue @markcowl hello, I have a question for this issue. why not such an issue for the following parameters. The problem seems to exist only for input object parameter sets?

### ApplicationWithoutCredentialParameterSet
```
New-AzADServicePrincipal -ApplicationId <Guid> [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm]
 [<CommonParameters>]
```

### ApplicationWithPasswordPlainParameterSet
```
New-AzADServicePrincipal -ApplicationId <Guid> [-StartDate <DateTime>] [-EndDate <DateTime>]
 [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
```


### DisplayNameWithPasswordCredentialParameterSet
```
New-AzADServicePrincipal -DisplayName <String> -PasswordCredential <PSADPasswordCredential[]>
 [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

### DisplayNameWithKeyPlainParameterSet
```
New-AzADServicePrincipal -DisplayName <String> -CertValue <String> [-StartDate <DateTime>]
 [-EndDate <DateTime>] [-DefaultProfile <IAzureContextContainer>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

**Comment by dingmeng-xue** [comment]
I only checked parameter sets according to issue description and didn't review all other parameter sets. If they have the similar issue, please resolve them too.

**Comment by msJinLei** [comment]
> I only checked parameter sets according to issue description and didn't review all other parameter sets. If they have the similar issue, please resolve them too.

Other ones don't have such an issue. We only need to fix ApplicationObject parameterset.

**Comment by msJinLei** [comment]
Fixed by https://github.com/Azure/azure-powershell/pull/11035
