### ISSUE TITLE
new-AZConsumptionBudget throws an error against an MSDN subscription

### ISSUE THREAD

**Issue by frehnejc** [Azure/azure-powershell#10995]
## Description
On attempting to create a new Consumption Budget an error is thrown against an MSDN subscription.

## Steps to reproduce

```powershell
New-AzConsumptionBudget -Amount 60 -ResourceGroup <ResGrpName> -Name TSTBudget -Category Cost -StartDate 2020-01-01 -TimeGrain Monthly -Debug

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
Script     1.0.2      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAcc...
Script     1.0.1      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAcc...

```

## Debug output

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
session-id                    : ee7a4301-c1ae-4676-bb99-1efa75d16aeb
x-ms-request-id               : b598b5bf-2c61-454c-8a9a-bf766f345718
x-ms-correlation-request-id   : 98eb0303-2e4b-4ace-9295-6508f71429c3
x-ms-client-request-id        : 3a4b755b-11e6-4105-bc02-75d6c4d35ac8
Access-Control-Allow-Origin   : *
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-routing-request-id       : AUSTRALIAEAST:20200130T041145Z:98eb0303-2e4b-4ace-9295-6508f71429c3
Cache-Control                 : no-cache
Date                          : Thu, 30 Jan 2020 04:11:45 GMT

Body:
{
  "error": {
    "code": "400",
    "message": "Subscription xx is not associated with EA offer type (Request ID: xx)"
  }
}
```

## Error output

```
HistoryId: 141


Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Consumption.BudgetsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.Mo 
                 veNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        
                    at
                 Microsoft.Azure.Management.Consumption.BudgetsOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)        
                    at Microsoft.Azure.Management.Consumption.BudgetsOperationsExtensions.CreateOrUpdate(IBudgetsOperations  
                 operations, String budgetName, Budget parameters)
                    at Microsoft.Azure.Commands.Consumption.Cmdlets.Budget.NewAzureRmConsumptionBudget.ExecuteCmdlet()       
Exception      : Microsoft.Azure.Management.Consumption.Models.ErrorResponseException
InvocationInfo : {New-AzConsumptionBudget}
Line           : New-AzConsumptionBudget -Amount 60 -Name TSTBudget -Category Cost -StartDate 2020-01-01 -TimeGrain Monthly  
                 -Debug
Position       : At line:1 char:1
                 + New-AzConsumptionBudget -Amount 60 -Name TSTBudget -Category Cost -St ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 141
```

**Comment by dingmeng-xue** [comment]
We need Billing team to look into this issue.

**Comment by frehnejc** [comment]
if I enter the correct start date for the MSDN subscription I get the error. Looks like the offer type that's supported is an EA Offer type. Does this mean it will not work for other Offer types eg PAYG?

**Comment by ms-premp** [comment]
This SDK uses an old version of API. This will be addressed in newer version later this year.

**Comment by ramaganesan-rg** [comment]
Closing as per Prem's comments

**Comment by rshnkmr10** [comment]
This is still an issue? >1 year closed and I am still receiving the error:
```
New-AzConsumptionBudget : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ New-AzConsumptionBudget -ResourceGroupName 'test-budget-rg' -Name ' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzConsumptionBudget], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Consumption.Cmdlets.Budget.NewAzureRmConsumptionBudget
```

Command I used:
```
New-AzConsumptionBudget -ResourceGroupName ''test-budget-rg' -Name ''test-budget-rg' -Amount 100 -Category Cost -TimeGrain Monthly -StartDate 2021-10-01 -EndDate 2022-10-01
```

**Comment by mmisztal1980** [comment]
is this still an issue? it's Jan 2023
