### ISSUE TITLE
Get-AzAutomationScheduledRunbook using JobScheduleId fails with "Invalid JSON primitive"

### ISSUE THREAD

**Issue by wolfgoe** [Azure/azure-powershell#11009]
Powershell version:
```
Name                           Value                                                                                                                   
----                           -----                                                                                                                   
PSVersion                      5.1.18362.145                                                                                                           
PSEdition                      Desktop                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                 
BuildVersion                   10.0.18362.145                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                         
WSManStackVersion              3.0                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                     
SerializationVersion           1.1.0.1  
```

Script     1.3.5      Az.Automation

```
Get-AzAutomationScheduledRunbook : Invalid JSON primitive: Start.
At line:1 char:1
+ Get-AzAutomationScheduledRunbook -JobScheduleId $schedRB.JobScheduleI ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomationScheduledRunbook], CmdletInvocationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationScheduledRunbook
 

PS C:\WINDOWS\system32> $DebugPreference="Continue"

PS C:\WINDOWS\system32> Get-AzAutomationScheduledRunbook -JobScheduleId a82b689b-f44e-4d4a-abb5-79d35bb9fed7 -ResourceGroupName xxx -AutomationAccountName xxx
DEBUG: 8:38:43 PM - GetAzureAutomationScheduledRunbook begin processing with ParameterSet 'ByJobScheduleId'.
DEBUG: 8:38:43 PM - using account id 'xxx'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx', environment: 'AzureCloud', tenant: 'df24b10d-fcba-48d2-9c24-89829
e0ac077'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'df24b10d-fcba-48d2-9c24-89829e0ac077', Endpoint: 'https://login.micr
osoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management
.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/df24b10d-fcba-48d2-9c24-89829e0ac077/', 
CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'df24b10d-fcba-48d2-9c24-89829e0ac077', AdEndpoint: 'https://login.
microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9931442Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: ADAL PCL.Desktop with assembly version '
3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9931442Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: ADAL PCL.Desktop with assembly version '
3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9931442Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9931442Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/df24b10d-fcba-48d2-9c24-89829e0ac077/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Verbose: 2020-01-31T23:38:43.9931442Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2020-01-31T23:38:43.9931442Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9961371Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.

DEBUG: [ADAL]: Verbose: 2020-01-31T23:38:43.9961371Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: An item matching the requested resource 
was found in the cache

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: An item matching the requested resource 
was found in the cache

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: 14.9810977633333 minutes left until toke
n in cache expires

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: 14.9810977633333 minutes left until toke
n in cache expires

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: A matching item (access token or refresh
 token or both) was found in the cache

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: A matching item (access token or refresh
 token or both) was found in the cache

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: === Token Acquisition finished successfu
lly. An access token was returned: Expiration Time: 1/31/2020 11:53:42 PM +00:00

DEBUG: [ADAL]: Information: 2020-01-31T23:38:43.9971342Z: c16e4dcb-5768-448c-80c1-58c802426a2c - LoggerBase.cs: === Token Acquisition finished successfu
lly. An access token was returned: Expiration Time: 1/31/2020 11:53:42 PM +00:00Access Token Hash: VsMl5rRYQOpkQAV+p0txf9v0BcdVvZj0zdRhjehHQpg=
	 User id: 8fdccfe8-05d1-43c1-9cd8-3538ee587ab5

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '01/31/2020 23:53:42 +00:00', MultipleResource? 'True', Tenant: 'df24b10d-fc
ba-48d2-9c24-89829e0ac077', UserId: 'xxx'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'xxx', Name: xxx, IdProvider: 'https://sts.windows.net/df24b10d
-fcba-48d2-9c24-89829e0ac077/', Uid: '8fdccfe8-05d1-43c1-9cd8-3538ee587ab5'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '01/31/2020 23:53:42 +00:00' Comparing to '01/31/2020 23:38:43 +00:00' With thr
eshold '00:05:00', calculated time until token expiry: '00:14:58.8658658'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/03fb9145-ab0a-4c48-9299-23c21346a35a/resourceGroups/XXX/providers/Microsoft.Automation/automa
tionAccounts/XXX/jobSchedules/a82b689b-f44e-4d4a-abb5-79d35bb9fed7?api-version=2015-10-31

Headers:
x-ms-client-request-id        : 3390bde2-558d-40fa-ab6b-a94b66ec1279
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : bc25c632-4425-44fc-83f0-56d294a6ac2f
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11982
x-ms-correlation-request-id   : 365a96d3-059c-4cd8-94b7-59d94a75a28b
x-ms-routing-request-id       : BRAZILSOUTH:20200131T233844Z:365a96d3-059c-4cd8-94b7-59d94a75a28b
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Fri, 31 Jan 2020 23:38:43 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/03fb9145-ab0a-4c48-9299-23c21346a35a/resourceGroups/xxx/providers/Microsoft.Automation/automationAccounts/xxx
/jobSchedules/a82b689b-f44e-4d4a-abb5-79d35bb9fed7",
  "type": "Microsoft.Automation/AutomationAccounts/JobSchedules",
  "properties": {
    "jobScheduleId": "a82b689b-f44e-4d4a-abb5-79d35bb9fed7",
    "runbook": {
      "name": "ScheduledStartStop_Parent"
    },
    "schedule": {
      "name": "Scheduled-StartVM"
    },
    "runOn": null,
    "parameters": {
      "Action": "Start"
    }
  }
}


Get-AzAutomationScheduledRunbook : Invalid JSON primitive: Start.
At line:1 char:1
+ Get-AzAutomationScheduledRunbook -JobScheduleId a82b689b-f44e-4d4a-ab ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomationScheduledRunbook], CmdletInvocationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationScheduledRunbook
 
DEBUG: AzureQoSEvent: CommandName - Get-AzAutomationScheduledRunbook; IsSuccess - False; Duration - 00:00:00.4435637; Exception - System.Management.Auto
mation.CmdletInvocationException: Invalid JSON primitive: Start. ---> System.ArgumentException: Invalid JSON primitive: Start.
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
   at System.Management.Automation.CommandProcessorBase.Complete()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings
 settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings setti
ngs)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.InvokeScript(String scriptName, Hashtable parameters)
   at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.Deserialize(String json)
   at Microsoft.Azure.Commands.Automation.Model.JobSchedule..ctor(String resourceGroupName, String automationAccountName, JobSchedule jobSchedule)
   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.CreateJobScheduleFromJobScheduleModel(String resourceGroupName, String automationAcc
ountName, JobSchedule jobSchedule)
   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetJobSchedule(String resourceGroupName, String automationAccountName, Guid jobSched
uleId)
   at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationScheduledRunbook.AutomationProcessRecord()
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 8:38:45 PM - GetAzureAutomationScheduledRunbook end processing.
DEBUG: 8:38:45 PM - GetAzureAutomationScheduledRunbook end processing.
```

**Comment by dingmeng-xue** [comment]
@wolfgoe , could you share me how parameter "Action" was created?

**Comment by wolfgoe** [comment]
Hi, @dingmeng-xue!

Parameters names were defined in the powershell script:

Param(
[Parameter(Mandatory=$true,HelpMessage="Enter the value for Action. Values can be either stop or start")][String]$Action,
[Parameter(Mandatory=$false,HelpMessage="Enter the value for WhatIf. Values can be either true or false")][bool]$WhatIf = $false,
[Parameter(Mandatory=$false,HelpMessage="Enter the VMs separated by comma(,)")][string]$VMList
)

And defined when creating the schedule:
![image](https://user-images.githubusercontent.com/41308575/73593703-b1d5cd80-44e5-11ea-94f7-7e807fbc9836.png)

**Comment by dingmeng-xue** [comment]
@wolfgoe, thanks for your example. I tried the most similar thing according to your instruction. I found a little difference. The string value is wrapped by double quote. 
```
Body:
{
  "id": "/subscriptions/<sub>/resourceGroups/dixue/providers/Microsoft.Automation/automationAccounts/auto-test/jobSchedules/e8d1458e-f94c-43a7-8170-e06bdc00531c",
  "type": "Microsoft.Automation/AutomationAccounts/JobSchedules",
  "properties": {
    "jobScheduleId": "e8d1458e-f94c-43a7-8170-e06bdc00531c",
    "runbook": {
      "name": "Start"
    },
    "schedule": {
      "name": "start"
    },
    "runOn": null,
    "parameters": {
      "Action": "\"Start\""
    }
  }
}
```
If you create it schedule via Azure Portal, the value should be wrapped by quote too. Please check whether it is incorrect when you create schedule.
![image](https://user-images.githubusercontent.com/56333063/73722395-5a439600-4761-11ea-92f7-1b0b80f10c58.png)

**Comment by wolfgoe** [comment]
@dingmeng-xue  Sorry for the delay answering. You're right! Although the script runs OK, the reason for it throwing the error is the absence of the double quotes. I assume that, from the users point of view, this should be enforced on screen, for string parameters, even if without the quotes the powershell script will run without an error.
Thanks again!

**Comment by dingmeng-xue** [comment]
@wolfgoe , thanks for confirmation. I understand your suggestion in this case. But from Azure PowerShell's perspective, we cannot hard code that logic because the value should be in JSON according to its API spec. It's the reason why I hope to understand where this wrong format comes from. Technically, value setting should conform to JSON format too. If it is fixed,  GET won't have problem.

**Comment by dingmeng-xue** [comment]
@wolfgoe , if there is no further question, we will close the issue soon due to inactivity.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. If there is any further issue, please raise a new issue.
