### ISSUE TITLE
Login-AzureRmAccount : parsing_wstrust_response_failed: Parsing WS-Trust response failed

### ISSUE THREAD

**Issue by Ashish-Jovial** [Azure/azure-powershell#11015]
Dear All,

I am getting error when i am running following powershell in azure devops powershell task into my release pipeline for getting service principal id. I am pasting my powershell and error log.

**Script:**
```
$pass = 'Ashish12345%'
$password = ConvertTo-SecureString -String $Pass -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential('ashish.jain@myorg.com',$password)
Login-AzureRmAccount -Credential $cred -Force

Select-AzureRmSubscription -SubscriptionId '47u8u7eu-of98-3e5r-j987-ie78u986yu7y

$servicePrincipalID = Get-AzureRmADServicePrincipal -SearchString 'myorg-prod-serviceprincipal' | Select-Object -ExpandProperty ApplicationId | Select-Object -ExpandProperty Guid

Write-Host "Service Principal ID: $servicePrincipalID"
Write-Host "##vso[task.setvariable variable=servicePrincipalID]$servicePrincipalID"
```
```
**Error:**
2020-02-03T04:33:25.1035220Z VERBOSE: Importing function 'CmdletHasMember'.
2020-02-03T04:33:25.1044043Z VERBOSE: Importing function 'Disconnect-AzureAndClearContext'.
2020-02-03T04:33:25.1053389Z VERBOSE: Importing function 'Initialize-AzModule'.
2020-02-03T04:33:25.1062654Z VERBOSE: Importing function 'Initialize-Azure'.
2020-02-03T04:33:25.1071045Z VERBOSE: Importing function 'Initialize-AzureRMModule'.
2020-02-03T04:33:25.1083463Z VERBOSE: Importing function 'Remove-EndpointSecrets'.
2020-02-03T04:33:25.1189246Z VERBOSE: Trying to disconnect from Azure and clear context at process scope
2020-02-03T04:33:25.1464760Z ##[command]Disconnect-AzureRmAccount -Scope Process -ErrorAction Stop
2020-02-03T04:33:25.3189417Z ##[command]Clear-AzureRmContext -Scope Process -ErrorAction Stop
2020-02-03T04:33:25.5351517Z ##[debug]Caught exception from task script.
2020-02-03T04:33:25.5384618Z ##[debug]Error record:
2020-02-03T04:33:25.5813073Z ##[debug]Login-AzureRmAccount : parsing_wstrust_response_failed: Parsing WS-Trust response failed
2020-02-03T04:33:25.5822990Z ##[debug]At D:\a\r1\a\_myorg-CI\myorg_Analytics\ServicePrincipal\Get-ServicePrincipal.ps1:19 char:1
2020-02-03T04:33:25.5832973Z ##[debug]+ Login-AzureRmAccount -Credential $cred
2020-02-03T04:33:25.5842916Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2020-02-03T04:33:25.5853563Z ##[debug]    + CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], AadAuthenticationFailedException
2020-02-03T04:33:25.5863457Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
2020-02-03T04:33:25.5873849Z ##[debug] 
2020-02-03T04:33:25.5889113Z ##[debug]Script stack trace:
2020-02-03T04:33:25.5916917Z ##[debug]at <ScriptBlock>, D:\a\r1\a\_myorg-CI\myorg_Analytics\ServicePrincipal\Get-ServicePrincipal.ps1: line 19
2020-02-03T04:33:25.5928663Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-03T04:33:25.5938480Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.153.2\AzurePowerShell.ps1: line 128
2020-02-03T04:33:25.5948147Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\3.153.2\AzurePowerShell.ps1: line 124
2020-02-03T04:33:25.5957853Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-03T04:33:25.5967411Z ##[debug]at <ScriptBlock>, <No file>: line 22
2020-02-03T04:33:25.5977239Z ##[debug]at <ScriptBlock>, <No file>: line 18
2020-02-03T04:33:25.5987548Z ##[debug]at <ScriptBlock>, <No file>: line 1
2020-02-03T04:33:25.6004056Z ##[debug]Exception:
2020-02-03T04:33:25.6042145Z ##[debug]Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedException: parsing_wstrust_response_failed: Parsing WS-Trust response failed ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: parsing_wstrust_response_failed: Parsing WS-Trust response failed
2020-02-03T04:33:25.6053328Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
2020-02-03T04:33:25.6065011Z ##[debug]   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.DoAcquireToken(AdalConfiguration config, PromptBehavior promptBehavior, Action`1 promptAction, String userId, SecureString password)
2020-02-03T04:33:25.6077175Z ##[debug]   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.SafeAquireToken(AdalConfiguration config, String showDialog, Action`1 promptAction, String userId, SecureString password, Exception& ex)
2020-02-03T04:33:25.6089648Z ##[debug]   --- End of inner exception stack trace ---
2020-02-03T04:33:25.6100018Z ##[debug]   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.AcquireToken(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String userId, SecureString password)
2020-02-03T04:33:25.6110212Z ##[debug]   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.GetAccessToken(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String userId, SecureString password, String credentialType)
2020-02-03T04:33:25.6121322Z ##[debug]   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
2020-02-03T04:33:25.6133449Z ##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)
2020-02-03T04:33:25.6143312Z ##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
2020-02-03T04:33:25.6153640Z ##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
2020-02-03T04:33:25.6164145Z ##[debug]   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass87_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
2020-02-03T04:33:25.6173621Z ##[debug]   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
2020-02-03T04:33:25.6183278Z ##[debug]   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
2020-02-03T04:33:25.6192907Z ##[debug]   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
2020-02-03T04:33:25.6203278Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2020-02-03T04:33:25.6398204Z ##[error]parsing_wstrust_response_failed: Parsing WS-Trust response failed
2020-02-03T04:33:25.6404343Z ##[debug]Processed: ##vso[task.logissue type=error]parsing_wstrust_response_failed: Parsing WS-Trust response failed
2020-02-03T04:33:25.6405062Z ##[debug]Processed: ##vso[task.complete result=Failed]
2020-02-03T04:33:25.6857577Z ##[section]Finishing: Get Service Principal ID
```

**Comment by dingmeng-xue** [comment]
@Ashish-Jovial, Login-AzureRmAccount is old version cmdlet. Could you try the latest cmdlet according to example on https://docs.microsoft.com/en-us/powershell/azure/authenticate-azureps?view=azps-3.3.0

**Comment by stiurin** [comment]
Having same issue.
Cannot authenticate to the tenant using ADFS credentials from an automation runbook job.
Get an error during Connect-AzAccount execution:

> parsing_wstrust_response_failed: Parsing WS-Trust response failed

Script example

```
$Cred = Get-AutomationPSCredential -Name "my.test.user"

$secpasswd = ConvertTo-SecureString $Cred.GetNetworkCredential().Password -AsPlainText -Force
$pscredential = New-Object System.Management.Automation.PSCredential($Cred.UserName, $secpasswd)

Disable-AzContextAutosave -Scope Process | Out-Null
Connect-AzAccount -Credential $pscredential -Tenant $AzTenantId -Force | Out-Null
```

I am deliberately not using the automation RunAS principal.

**Comment by dingmeng-xue** [comment]
@stiurin, ADFS is not supported yet.

**Comment by dingmeng-xue** [comment]
@Ashish-Jovial, do you have chance to try Connect-AzAccount. If you are trying to connect to ADFS, it is not supported.

**Comment by dingmeng-xue** [comment]
Using user name and password is not incorrect in automation environment. If you meet further issue, please create new one.
