### ISSUE TITLE
New-AzNatGateway results in ErrorCode: InvalidResourceType...

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-powershell#11022]
Using Azure powershell v3.3.0 

Trying to use New-AzNatGateway cmdlet, almost verbatim as shown in the following example:

[https://docs.microsoft.com/en-us/powershell/module/Az.Network/New-AzVirtualNetworkSubnetConfig?view=azps-3.3.0#examples](https://docs.microsoft.com/en-us/powershell/module/Az.Network/New-AzVirtualNetworkSubnetConfig?view=azps-3.3.0#examples)

However, when the New-AzNatGateway cmdlet is invoked it results in:

```
Microsoft.Azure.Commands.Network.Common.NetworkCloudException: The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'.
StatusCode: 404
ReasonPhrase: Not Found
ErrorCode: InvalidResourceType
ErrorMessage: The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'.
OperationID : 078ae346-d2ad-43a4-a78a-54fdbc7407b0 ---> Microsoft.Rest.Azure.CloudException: The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'.
   at Microsoft.Azure.Management.Network.NatGatewaysOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Network.NatGatewaysOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Network.NatGatewaysOperationsExtensions.<CreateOrUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Network.NatGatewaysOperationsExtensions.CreateOrUpdate(INatGatewaysOperations operations, String resourceGroupName, String natGatewayName, NatGateway parameters)
   at Microsoft.Azure.Commands.Network.NewAzureRmNatGateway.<>c__DisplayClass44_0.<Execute>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
   at Microsoft.Azure.Commands.Network.NewAzureRmNatGateway.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

Why?

And for those not born with the knowledge - Where does one find documentation with regard to WHAT a "NAT" gateway is and what it does?

Thanks in advance.

**Comment by dingmeng-xue** [comment]
@bdcoder2 , please enable debug information using `$DebugPreference = "Continue"` and share output to us? We need to know which API URL is being called.

**Comment by bdcoder2** [comment]
@dingmeng-xue - below is the debug output immediately after the call to New-AzNatGateway:
```
DEBUG: 6:11:52 AM - NewAzureRmNatGateway begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 6:11:52 AM - using account id 'redacted'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'redacted', environment: 'AzureCloud', tenant: 'cb1a4d3b-3e54-48ca-bbc2-6424dd371c81'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'cb1a4d3b-3e54-48ca-bbc2-6424dd371c81', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.
0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/cb1a4d3b-3e54-48ca-bbc2-6424dd371c81/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'cb1a4d3b-3e54-48ca-bbc2-6424dd371c81', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oa
uth:2.0:oob
DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2
605056' is running...

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2
605056' is running...

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/cb1a4d3b-3e54-48ca-bbc2-6424dd371c81/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Verbose: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 2 items to token cache.

DEBUG: [ADAL]: Verbose: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: 59.2226518783333 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: 59.2226518783333 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 04-Feb-20 2:11:05 PM +00:00

DEBUG: [ADAL]: Information: 2020-02-04T13:11:52.2728873Z: c80ff9da-7a9c-4540-9965-1b60ce2e0e7a - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 04-Feb-20 2:11:05 PM +00:00Access Token Hash: DnYmLbnV
FTOd/w7uTSnGxa8TrdmEYa9SGjzm3XIx9Xc=
	 User id: 417cf721-63e0-4e54-be0f-be99ab2f927b

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '02/04/2020 14:11:05 +00:00', MultipleResource? 'True', Tenant: 'cb1a4d3b-3e54-48ca-bbc2-6424dd371c81', UserId: 'redacted'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'redacted', Name: redacted, IdProvider: 'live.com', Uid: '417cf721-63e0-4e54-be0f-be99ab2f927b'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '02/04/2020 14:11:05 +00:00' Comparing to '02/04/2020 13:11:52 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:59:13.3591127'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/aec9ffdb-35fb-454e-97ab-94cb32328d7f/resourceGroups/rrca_test/providers/Microsoft.Network/natGateways/rrca_website_nat_gateway?api-version=2019-09-01

Headers:
x-ms-client-request-id        : 41d39820-2754-4a3f-9064-70f120deea09
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 80684879-9798-4027-875f-44a1f56ecf50
x-ms-correlation-request-id   : 80684879-9798-4027-875f-44a1f56ecf50
x-ms-routing-request-id       : WESTUS2:20200204T131155Z:80684879-9798-4027-875f-44a1f56ecf50
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 04 Feb 2020 13:11:55 GMT

Body:
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'."
  }
}


DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '02/04/2020 14:11:05 +00:00', MultipleResource? 'True', Tenant: 'cb1a4d3b-3e54-48ca-bbc2-6424dd371c81', UserId: 'redacted'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'redacted', Name: redacted, IdProvider: 'live.com', Uid: '417cf721-63e0-4e54-be0f-be99ab2f927b'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '02/04/2020 14:11:05 +00:00' Comparing to '02/04/2020 13:11:52 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:59:12.9684987'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/aec9ffdb-35fb-454e-97ab-94cb32328d7f/resourceGroups/rrca_test/providers/Microsoft.Network/natGateways/rrca_website_nat_gateway?api-version=2019-09-01

Headers:
x-ms-client-request-id        : cff18360-6ccd-4178-934a-4376cba1a6cd
accept-language               : en-US

Body:
{
  "sku": {
    "name": "Standard"
  },
  "properties": {
    "idleTimeoutInMinutes": 4,
    "publicIpAddresses": [
      {
        "id": "/subscriptions/aec9ffdb-35fb-454e-97ab-94cb32328d7f/resourceGroups/rrca_test/providers/Microsoft.Network/publicIPAddresses/RRCAWEB1_public_ip"
      }
    ],
    "publicIpPrefixes": []
  },
  "zones": [],
  "location": "Canada Central"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : c3903d2e-008e-40e7-af6d-3a7b75d2b39c
x-ms-correlation-request-id   : c3903d2e-008e-40e7-af6d-3a7b75d2b39c
x-ms-routing-request-id       : WESTUS2:20200204T131156Z:c3903d2e-008e-40e7-af6d-3a7b75d2b39c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 04 Feb 2020 13:11:55 GMT

Body:
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'."
  }
}


* ERROR: Microsoft.Azure.Commands.Network.Common.NetworkCloudException: The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'.
StatusCode: 404
ReasonPhrase: Not Found
ErrorCode: InvalidResourceType
ErrorMessage: The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'.
OperationID : c3903d2e-008e-40e7-af6d-3a7b75d2b39c ---> Microsoft.Rest.Azure.CloudException: The resource type could not be found in the namespace 'Microsoft.Network' for api version '2019-09-01'.
   at Microsoft.Azure.Management.Network.NatGatewaysOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Network.NatGatewaysOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Network.NatGatewaysOperationsExtensions.<CreateOrUpdateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Network.NatGatewaysOperationsExtensions.CreateOrUpdate(INatGatewaysOperations operations, String resourceGroupName, String natGatewayName, NatGateway parameters)
   at Microsoft.Azure.Commands.Network.NewAzureRmNatGateway.<>c__DisplayClass44_0.<Execute>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
   at Microsoft.Azure.Commands.Network.NewAzureRmNatGateway.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by dingmeng-xue** [comment]
Please use script to get version of Az.Network `Get-InstalledModule Az.Network`. The network API version doesn't have 2019-09-01

**Comment by bdcoder2** [comment]
@dingmeng-xue - Below is output from Get-InstalledModule Az.Network 

```
Version    Name                                Repository           Description                                                                                                                                                                                  
-------    ----                                ----------           -----------                                                                                                                                                                                  
2.2.1      Az.Network                          PSGallery            Microsoft Azure PowerShell - Networking service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core....                                                             

```

Sorry - what exactly needs to be done so the New-AzNatGateway cmdlet is recognized?  Do I need to to install a specific version?

Thanks again.

**Comment by dingmeng-xue** [comment]
Thanks for your report. I tried `Get-AzNatGateway` in Az.Network 2.2.0. It has the same problem. I will forward it to Network team.

**Comment by christiankuhtz** [comment]
service is not released.  please wait for official comms.

#please-close

**Comment by bdcoder2** [comment]
@christiankuhtz -? But why is it mentioned in the official docs / examples?  See:

[https://docs.microsoft.com/en-us/powershell/module/Az.Network/New-AzVirtualNetworkSubnetConfig?view=azps-3.3.0#examples](https://docs.microsoft.com/en-us/powershell/module/Az.Network/New-AzVirtualNetworkSubnetConfig?view=azps-3.3.0#examples)

.. as per original post

**Comment by christiankuhtz** [comment]
because it had to be for some private preview customers.
