### ISSUE TITLE
Get-AzResource for Front Door and Front Door WAF policy use no supported API version

### ISSUE THREAD

**Issue by BernieWhite** [Azure/azure-powershell#11265]
## Description

When calling `Get-AzResource` with the `-ExpandProperties` switch on Front Door or Front Door WAF policy resources the API version selected is _not supported_. The call fails with an error.

## Steps to reproduce

```powershell
Get-AzResource -Name '<removed>' -ExpandProperties;
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.7.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.11.0     Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication…}
```

## Error output

```
   HistoryId: 2
Message        : InvalidVersion : The API version '2020-03-01' is not supported. Supported version(s): 2018-08-01, 2019-03-01, 2019-04-01, 2019-05-01, 2019-08-01, 2019-10-01, 2019-11-01, 2020-01-01
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.SendRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.SendRequestAsync(HttpMethod httpMethod, Uri requestUri, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.RestClients.ResourceManagerRestClientBase.SendRequestAsync[TResponseType](HttpMethod httpMethod, Uri requestUri, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet.GetPopulatedResource(Resource`1 resource)
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Get-AzResource}
Line           : Get-AzResource -Name '<removed>' -ExpandProperties
Position       : At line:1 char:1
                 + Get-AzResource -Name '<removed>' -ExpandProperties
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by dingmeng-xue** [comment]
Front Door team,  please check the version from ARM.

**Comment by KarenHammons** [comment]
@BernieWhite thanks for reporting this issue.  This issue was fixed in a release late March.  Please let us know if you're still experiencing the issue.  Thank you!
