### ISSUE TITLE
Get-AzSubscriptionDeployment returns Encountered internal server error

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#11291]
## Description
On one of the subscriptions we have Get-AzSubscriptionDeployment  returns:

```
Get-AzDeployment: Encountered internal server error. Diagnostic information: timestamp '20200310T111055Z', subscription id '<subscription id >', tracking id '135c8729-b471-4654-b41f-637e65d98538', request correlation id '135c8729-b471-4654-b41f-637e65d98538'.
```

The steps to reproduce it is just to run the command but seems it does not happen on every subscription. Seems it is somehow related to what kind of deployments you have. I can share more details in private as I do not want to expose important information.

Also parameter -ApiVersion does not work. If I specify version like 2020-01-01 still 2019-10-01 is used.

## Steps to reproduce

```powershell

```

## Environment data

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
Script     1.7.3                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.12.0                Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment…}

```

## Debug output

```
DEBUG: AzureQoSEvent: CommandName - Get-AzDeployment; IsSuccess - False; Duration - 00:00:32.6097240;; Exception - Microsoft.Rest.Azure.CloudException: Encountered internal server error. Diagnostic information: timestamp '20200310T111055Z', subscription id '<subscription ID>', tracking id '135c8729-b471-4654-b41f-637e65d98538', request correlation id '135c8729-b471-4654-b41f-637e65d98538'.          at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.ListAtSubscriptionScopeWithHttpMessagesAsync(ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)       at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.ListAtSubscriptionScopeAsync(IDeploymentsOperations operations, ODataQuery`1 odataQuery, CancellationToken cancellationToken)      at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.ListAtSubscriptionScope(IDeploymentsOperations operations, ODataQuery`1 odataQuery)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ListDeploymentsAtSubscription(String deploymentName)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ListDeployments(FilterDeploymentOptions options)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.FilterDeployments(FilterDeploymentOptions options)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureSubscriptionDeploymentCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
```

## Error output

```
   HistoryId: 7

RequestId      : 4872dc9f-7451-433d-bb82-98332db1012c
Message        : Encountered internal server error. Diagnostic information: timestamp '20200310T105624Z', subscription id '<subscription ID>', tracking id '4872dc9f-7451-433d-bb82-98332db10                  12c', request correlation id '4872dc9f-7451-433d-bb82-98332db1012c'.
ServerMessage  : InternalServerError: Encountered internal server error. Diagnostic information: timestamp '20200310T105624Z', subscription id '<subscription id>', tracking id '4872dc9f-745                  1-433d-bb82-98332db1012c', request correlation id '4872dc9f-7451-433d-bb82-98332db1012c'. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {InternalServerError}
RequestMessage : {GET https://management.azure.com/subscriptions/<subscription id>/providers/Microsoft.Resources/deployments/?api-version=2019-10-01}
InvocationInfo : {Get-AzDeployment}
Line           : (Get-AzSubscriptionDeployment).Count
Position       : At line:1 char:2
                 + (Get-AzSubscriptionDeployment).Count
                 +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.ListAtSubscriptionScopeWithHttpMessagesAsync(ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken canc                  ellationToken)
                    at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.ListAtSubscriptionScopeAsync(IDeploymentsOperations operations, ODataQuery`1 odataQuery, CancellationToken can                  cellationToken)
                    at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.ListAtSubscriptionScope(IDeploymentsOperations operations, ODataQuery`1 odataQuery)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ListDeploymentsAtSubscription(String deploymentName)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ListDeployments(FilterDeploymentOptions options)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.FilterDeployments(FilterDeploymentOptions options)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureSubscriptionDeploymentCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 7


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=FEEDBACK.
```

**Comment by slavizh** [comment]
As far as I could test it does not happen in Az.Resources 1.11.0

**Comment by dingmeng-xue** [comment]
API version is changed from 2019-07-01 to 2019-10-01. It needs Resource team's check.

**Comment by alex-frankel** [comment]
We are taking a look

cc @Tiano2017

**Comment by alex-frankel** [comment]
The fix for this has been checked in, but we are waiting for this to get deployed. It should be deployed in 2-3 weeks.
