### ISSUE TITLE
Set-AzureRMWebApp (and Set-AzWebApp also) returns "BadRequest" when setting AppSettings

### ISSUE THREAD

**Issue by zeeshan-aym** [Azure/azure-powershell#11374]
## Description
Set-AzureRMWebApp -ResourceGroupName [ResourceGroup] -Name [AppServiceName] -AppSettings [AppSettingsHash] results in

Set-AzureRMWebApp : Operation returned an invalid status code 'BadRequest'
At D:\a\_tasks\[ExtentionID]\2.0.2\Set-AppServiceApplicationSettings.ps1:99 char:13

```
Set-AzureRMWebApp -ResourceGroupName $resourceGroupName - ...
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   + CategoryInfo          : CloseError: (:) [Set-AzureRmWebApp], DefaultErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet

Script stack trace:
at <ScriptBlock>, D:\a\_tasks\aymcommerce-set-appservice-applicationsettings_1f555627-fc30-4468-a443-5bb561fcf9fb\2.0.2\Set-AppServiceApplicationSettings.ps1: line 99
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1
Exception:
Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.WebSites.WebAppsOperations.<UpdateConfigurationWithHttpMessagesAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.<UpdateConfigurationAsync>d__83.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.UpdateConfiguration(IWebAppsOperations operations, String resourceGroupName, String name, SiteConfigResource siteConfig)
  at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.UpdateWebAppConfiguration(String resourceGroupName, String location, String webSiteName, String slotName, SiteConfig siteConfig, IDictionary`2 appSettings, IDictionary`2 connectionStrings)
   at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Operation returned an invalid status code 'BadRequest'
Processed: ##vso[task.logissue type=error]Operation returned an invalid status code 'BadRequest'
```

Our project is based on the **AzurePowerShellV3** task in https://github.com/Microsoft/azure-pipelines-tasks
Everything was working fine till Feb 27, 2020 and now our release is failing at Setting **AppService task**.

This error message appears when i use AzureRM.Websites between version 5.0.0 and 5.2.0.

It shows me **IpSecurityRestriction is invalid. Etiher IpAddress or VnetSubnetResourceId property must be specified.** in Activity Log.
Please be noted that this app service is restricted through VNET/SN where no changes made in last 1 month.

I've tried [this](https://github.com/Azure/azure-powershell/issues/10100) issue but it didn't help.

Can I please request to have any location where I can share script file.

**Comment by dingmeng-xue** [comment]
Involve Service team to look into it.

**Comment by panchagnula** [comment]
@zeeshan-aym  thanks for sharing the details - IP restrictions support needs a specific min api-version and AzureRM doesn't have this support. In General we recommend moving the AZ module since new features and bug fixes only go to Az Module. See this for more details https://docs.microsoft.com/en-us/powershell/azure/new-azureps-module-az?view=azps-3.6.1

**Comment by zeeshan-aym** [comment]
@panchagnula thank you for response. I will definitely look at moving the AZ module but I am interested to know if any changes been made recently in powershell modules which I missed to know because as I mentioned earlier that everything was working till 27th Feb without any changes in custom tasks.

I would appreciate also if you can specify the supported min api-version for IP restrictions.

**Comment by panchagnula** [comment]
@zeeshan-aym no we haven't made any updates/ changes to AzureRM Module. IP restrictions was never supported with AzureRM module.

**Comment by panchagnula** [comment]
closing this since to use IPRestrictions or any new properties using Az CLI is the way to go.
