### ISSUE TITLE
Get-AzBatchApplication doesn't returnt ApplicationPackages

### ISSUE THREAD

**Issue by Aleksanderis** [Azure/azure-powershell#11658]
## Description
We had a script to apply retention policy for Batch application packages (to solve quota limitations). We were using AzureRM module for that - `Get-AzureRmBatchApplication` and it was working good. Lately we migrated to Az PowerShell modules and there are issues with - it works a bit differently.

## Steps to reproduce

```powershell
Get-AzBatchApplication -AccountName "vonjobsstag" -ResourceGroupName "vonjobs-stag" -ApplicationId "visma-online-jobs-azurebatch"
```
`ApplicationPackages` property is null/empty in the response (which is not empty if I call `Get-AzureRmBatchApplication`).

Also if I run:
```powershell
Get-AzBatchApplicationPackage -AccountName "vonjobsstag" -ResourceGroupName "vonjobs-stag" -ApplicationId "visma-online-jobs-azurebatch"
```
It throws an error: `Get-AzBatchApplicationPackage : Nullable object must have a value.`

## Environment data

```
❯ $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions
Not sure about other modules, but I checked Az.Batch - and it's 2.0.2, which is latest at time of writing.

```powershell
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.7.3      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable...
Script     1.1.1      Az.Advisor                          {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecomm...
Script     1.0.3      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.1.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisSer...
Script     1.4.0      Az.ApiManagement                    {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagem...
Script     1.0.3      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, ...
Script     1.3.6      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutom...
Script     2.0.2      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount...
Script     1.0.2      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptio...
Script     1.4.2      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.2.3      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveSe...
Script     3.5.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAva...
Script     1.0.3      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainer...
Script     1.1.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove...
Script     1.1.0      Az.DataBoxEdge                      {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeDevice, New-AzDat...
Script     1.6.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFacto...
Script     1.0.2      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-...
Script     1.2.7      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remov...
Script     1.1.0      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-Az...
Script     1.0.2      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy...
Script     1.1.2      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...
Script     1.2.3      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTop...
Script     1.4.3      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-Az...
Script     1.4.0      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor...}
Script     3.0.3      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHD...
Script     1.0.1      Az.HealthcareApis                   {New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-AzHealthcareApisSer...
Script     2.2.0      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Ge...
Script     1.5.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateO...
Script     1.3.2      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrati...
Script     1.1.3      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPla...
Script     1.0.2      Az.ManagedServices                  {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedSe...
Script     1.0.2      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1      Az.Media                            {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzM...
Script     1.6.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     2.3.2      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthentic...
Script     1.1.1      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHub...
Script     1.3.4      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustom...
Script     1.2.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediat...
Script     1.1.1      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBI...
Script     1.0.2      Az.PrivateDns                       {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone, New-AzPrivateDn...
Script     2.7.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoverySer...
Script     1.2.1      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePat...
Script     1.0.3      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayName...
Script     1.12.0     Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAs...
Script     1.4.1      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Rem...
Script     2.0.1      Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzS...
Script     1.1.1      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     2.4.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncrypti...
Script     1.1.0      Az.SqlVirtualMachine                {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM...}
Script     1.13.0     Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAc...
Script     1.2.3      Az.StorageSync                      {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncS...
Script     1.0.1      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-A...
Script     1.0.3      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromE...
Script     1.7.0      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServic...
```

## Debug output

```
❯ Get-AzBatchApplication -AccountName "xxx" -ResourceGroupName "xxx" -ApplicationId "xxx"
DEBUG: 08:52:44 - GetBatchApplicationCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 08:52:44 - using account id 'xxxxxx@xxxxxx'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxxx@xxxxxx', environment: 'AzureCloud', tenant: 'XXXXXXXXXXXXXXXXXXX'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'XXXXXXXXXXXXXXXXXXX', Endpoint: 'https://login.microsoftonline.com/', ClientId: 'XXXXXXXXXXXXXXXXXXX', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXX/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'XXXXXXXXXXXXXXXXXXX', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: 'XXXXXXXXXXXXXXXXXXX', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3042195Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3042195Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3042195Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: === Token Acquisition started:
 CacheType: null
 Authentication Target: User
 , Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3042195Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXX/
 Resource: https://management.core.windows.net/
 ClientId: XXXXXXXXXXXXXXXXXXX
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3042195Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3042195Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3052171Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.
DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: 54,0377630633333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: 54,0377630633333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 2020-04-22 06:46:46 +00:00
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 9a52ac06-0b7d-4392-adb6-626aa5179211 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 2020-04-22 06:46:46 +00:00Access Token Hash:
rTHOJNeqf6sxW3UE0A41ghnzyna6sH4Gy7wg0/PqFqQ=
  User id: 3023ba33-2e4b-4b55-9bef-c1b02d0c147b
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxxx@xxxxxx', environment: 'AzureCloud', tenant: 'XXXXXXXXXXXXXXXXXXX'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'XXXXXXXXXXXXXXXXXXX', Endpoint: 'https://login.microsoftonline.com/', ClientId: 'XXXXXXXXXXXXXXXXXXX', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXX/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'XXXXXXXXXXXXXXXXXXX', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: 'XXXXXXXXXXXXXXXXXXX', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: === Token Acquisition started:
 CacheType: null
 Authentication Target: User
 , Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3062162Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/XXXXXXXXXXXXXXXXXXX/
 Resource: https://management.core.windows.net/
 ClientId: XXXXXXXXXXXXXXXXXXX
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3072125Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3072125Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.
DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: 54,0377298483333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: 54,0377298483333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 2020-04-22 06:46:46 +00:00
DEBUG: [ADAL]: Information: 2020-04-22T05:52:44.3082091Z: 385a7e03-cbe5-405b-b41e-759182e96bc3 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 2020-04-22 06:46:46 +00:00Access Token Hash:
rTHOJNeqf6sxW3UE0A41ghnzyna6sH4Gy7wg0/PqFqQ=
  User id: 3023ba33-2e4b-4b55-9bef-c1b02d0c147b
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '04/22/2020 06:46:46 +00:00', MultipleResource? 'True', Tenant: 'XXXXXXXXXXXXXXXXXXX', UserId: 'xxxxxx@xxxxxx'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'xxxxxx@xxxxxx', Name: XXXXX, IdProvider: 'https://sts.windows.net/XXXXXXXXXXXXXXXXXXX/', Uid: '3023ba33-2e4b-4b55-9bef-c1b02d0c147b'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '04/22/2020 06:46:46 +00:00' Comparing to '04/22/2020 05:52:44 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:54:02.2627589'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.Batch/batchAccounts/xxx/applications/xxx?api-version=2019-08-01

Headers:
x-ms-client-request-id        : 198258e6-627b-4bb0-93ce-e97397e973b9
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id               : 063586c7-f73c-425f-a963-1688bc021c9e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
x-ms-correlation-request-id   : b290d320-2931-41af-8a20-9cdda5963390
x-ms-routing-request-id       : WESTUS:20200422T055245Z:b290d320-2931-41af-8a20-9cdda5963390
Cache-Control                 : no-cache
Date                          : Wed, 22 Apr 2020 05:52:45 GMT
ETag                          : W/"0x8D7E51AE459314B"
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "type": "Microsoft.Batch/batchAccounts/applications",
  "id": "/subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.Batch/batchAccounts/xxx/applications/xxx",
  "name": "xxx",
  "etag": "W/\"0x8D7E51AE459314B\"",
  "properties": {
    "allowUpdates": true,
    "defaultVersion": "2020.4.22"
  }
}

DEBUG: AzureQoSEvent: CommandName - Get-AzBatchApplication; IsSuccess - True; Duration - 00:00:01.5855416;
DEBUG: Finish sending metric.
DEBUG: 08:52:46 - GetBatchApplicationCommand end processing.


AllowUpdates        : True
ApplicationPackages :
Id                  : /subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.Batch/batchAccounts/xxx/applications/xxx
Name                : xxx
DefaultVersion      : 2020.4.22
DisplayName         :


```

## Error output
There is no error in `Get-AzBatchApplication`, it just doesn't return what is expected.

**Comment by dingmeng-xue** [comment]
@Aleksanderis , could you share debug message output of `Get-AzureRmBatchApplication`?

**Comment by Aleksanderis** [comment]
> @Aleksanderis , could you share debug message output of `Get-AzureRmBatchApplication`?

Hmm, it seems I included, or do you need something more?
Actually it should be really easily reproducible, just with one command call with any Azure Batch application. If it's not reproducible, then I try provide more details.

**Comment by bgklein** [comment]
Hi @Aleksanderis,

The form of the underlying Application object changed as you correctly observed in one of the past breaking change updates. Get-AzBatchApplication no longer has application packages as a sub-object so you must use the Get-AzBatchApplicationPackage to retrieve applicationPackages. 

This also had a change at the same time where -ApplicationId became -ApplicationName in the Get-AzBatchApplicationPackage module.
https://docs.microsoft.com/en-us/powershell/module/az.batch/get-azbatchapplicationpackage?view=azps-3.8.0

You can view the full list of associated changes in any version at https://github.com/Azure/azure-powershell/blob/master/src/Batch/Batch/ChangeLog.md#version-201

**Comment by bgklein** [comment]
@Aleksanderis if you have any further questions let me know, otherwise I am closing the issue as it appears to be working as designed

**Comment by Aleksanderis** [comment]
Ok, thank you.

However I tried to execute (with changed `-ApplicationName` parameter):
```powershell
Get-AzBatchApplicationPackage -AccountName "jobsaccount" -ResourceGroupName "jobs-test" -ApplicationName "jobsappname"
```
And still gettins same error: `Nullable object must have a value.`

##Rezolve-AzError output
```
Message        : Nullable object must have a value.
StackTrace     :    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
                    at Microsoft.Azure.Commands.Batch.Models.BatchClient.ConvertGetApplicationPackageResponseToApplicationPackage(ApplicationPacka
                 ge response)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
                    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
                    at Microsoft.Azure.Commands.Batch.Models.BatchClient.ListApplicationPackages(String resourceGroupName, String accountName, Str
                 ing applicationName)
                    at Microsoft.Azure.Commands.Batch.GetBatchApplicationPackageCommand.ExecuteCmdletImpl()
                    at Microsoft.Azure.Commands.Batch.BatchCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.InvalidOperationException
InvocationInfo : {Get-AzBatchApplicationPackage}
Line           : (Get-AzBatchApplicationPackage -AccountName "jobsaccount" -ResourceGroupName "jobs-test" -ApplicationName "jobsappname")
Position       : At line:1 char:2
                 + (Get-AzBatchApplicationPackage -AccountName "jobsaccount" -ResourceGr ...
                 +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by matthchr** [comment]
> It's still a bit confusing, that Get-AzBatchApplication returns ApplicationPackages object (it's visible), but it's just empty.. Looks like this:

That's a bug which we will fix in the next release - it's not supposed to return ApplicationPacakges anymore.
