### ISSUE TITLE
Set-AzCosmosDBSqlContainer throwing exception

### ISSUE THREAD

**Issue by mvasisht** [Azure/azure-powershell#11662]
Set-AzCosmosDBSqlContainer gives below error even though container is created in CosmosDB. It fails after around 50 seconds.
CloseError: (:) [Set-AzCosmosDBSqlContainer], HttpRequestException
All other CosmosDB az scripts work fine.

PSVersion                      5.1.14393.3053

## Steps to reproduce
```
Set-AzCosmosDBSqlContainer `
    -ResourceGroupName $resourceGroupName `
    -AccountName $accountName `
    -DatabaseName $databaseName `
    -Name $collectionName `
    -PartitionKeyKind Hash `
    -PartitionKeyPath $partitionKey `
    -Throughput 4000
```

## Module versions
```
ModuleType Version    Name                                                                                                                                          
---------- -------    ----                                                                                                                                     
Script     0.1.0      Az.CosmosDB   

```

## Debug output
```
Set-AzCosmosDBSqlContainer : An error occurred while sending the request.
At line:1 char:1
+ Set-AzCosmosDBSqlContainer `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzCosmosDBSqlContainer], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.CosmosDB.SetAzCosmosDBSqlContainer

```

## Error output
```
  HistoryId: 11


Message        : An error occurred while sending the request.
StackTrace     :    at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Common.Authentication.Models.RPRegistrationDelegatingHandler.<SendAsync>d__9.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.CancelRetryHandler.<SendAsync>d__12.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<GetRawAsync>d__49.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.<UpdateResourceFromPollingUri>d__47.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Rest.ClientRuntime.Azure.LRO.PutLRO`2.<PostPollingAsync>d__4.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.<BeginLROAsync>d__15.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__5`1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                    at Microsoft.Azure.Management.CosmosDB.SqlResourcesOperations.<CreateUpdateSqlContainerWithHttpMessagesAsync>d__13.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.CosmosDB.SetAzCosmosDBSqlContainer.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Net.Http.HttpRequestException
InvocationInfo : {Set-AzCosmosDBSqlContainer}
Line           : Set-AzCosmosDBSqlContainer `
                 
Position       : At line:1 char:1
                 + Set-AzCosmosDBSqlContainer `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11

Message        : Unable to connect to the remote server
StackTrace     :    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
                    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Exception      : System.Net.WebException
InvocationInfo : {Set-AzCosmosDBSqlContainer}
Line           : Set-AzCosmosDBSqlContainer `
                 
Position       : At line:1 char:1
                 + Set-AzCosmosDBSqlContainer `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11

Message        : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host 
                 has failed to respond 1x1.xxx.xx.xxx:450
StackTrace     :    at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
                    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
                    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, 
                 IAsyncResult asyncResult, Exception& exception)
Exception      : System.Net.Sockets.SocketException
InvocationInfo : {Set-AzCosmosDBSqlContainer}
Line           : Set-AzCosmosDBSqlContainer `
                 
Position       : At line:1 char:1
                 + Set-AzCosmosDBSqlContainer `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11
```

**Comment by dingmeng-xue** [comment]
@mvasisht , Could you share more information about debug log after you enable `$DebugPreference="Continue"`?

**Comment by mvasisht** [comment]
@dingmeng-xue :  Debug Log is already pasted on my initial request under sub heading - Error Output

**Comment by dingmeng-xue** [comment]
CosmosDB team, please help to look into this issue.

**Comment by MehaKaushik** [comment]
Hey @mvasisht and @dingmeng-xue apologies for the delay in our side. 
@mvasisht  we have deprecated the Set-AzCosmosDB* cmdlets entirely, please use New-AzCosmosDBSqlContainer, going forward. 

Are you still facing the issue?? From the stack it looks like it was an network issue, please verify if you still facing the issue and we can proceed with the further investigation.

**Comment by rnagpal** [comment]
@mvasisht : Please let us know if you have started using New-AzCosmosDBSqlContainer and this might potentially help avoid this in future(if there are any improvements made around that).
