### ISSUE TITLE
Get-AzureSubscription Error

### ISSUE THREAD

**Issue by donovan-dd** [Azure/azure-powershell#11757]
## Description

I am able to login to Azure using Connect-AzAccount.  My account is tied to multiple subscriptions.  When I run Get-AzureSubscription I get:
Get-AzureSubscription: Object reference not set to an instance of an object.

I went ahead and updated from v7.0.0-preview-rc1 to the stable release 7 version and reinstalled the Az module from PSGallery, updating from 3.3.0 to 3.8.0, but am still getting the error.

## Steps to reproduce

Login to azure via PS, run Get-AzureSubscription

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0
PSEdition                      Core
GitCommitId                    7.0.0
OS                             Microsoft Windows 6.3.9600
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0.}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```
    Directory: C:\Program Files\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     3.8.0                 Az                                  Core,Desk
Script     3.3.0                 Az                                  Core,Desk
Script     1.7.5                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutos.
Script     1.7.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutos.
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRec.
Script     1.0.3                 Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAks.
Script     1.1.2                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnaly.
Script     1.4.1                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManage.
Script     1.3.3                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManage.
Script     1.0.3                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsi.
Script     1.3.6                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAuto.
Script     1.3.5                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAuto.
Script     2.0.2                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-A.
Script     1.0.2                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-A.
Script     1.4.3                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-Az.
Script     1.4.2                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-Az.
Script     1.3.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveS.
Script     1.2.2                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveS.
Script     3.7.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet,.
Script     3.3.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet,.
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remo.
Script     1.1.1                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry.
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, I.
Script     1.7.0                 Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get.
Script     1.6.0                 Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get.
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLak.
Script     1.2.8                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzD.
Script     1.2.6                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzD.
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDep.
Script     1.0.2                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDep.
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShut.
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remov.
Script     1.2.3                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-.
Script     1.4.3                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace.
Script     1.4.0                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoo.
Script     1.3.0                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoo.
Script     3.1.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefin.
Script     3.0.2                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefin.
Script     1.0.1                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-AzHealthcare.
Script     2.4.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGro.
Script     2.0.1                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGro.
Script     1.6.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCert.
Script     1.4.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCert.
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegra.
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitme.
Script     1.0.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment.
Script     1.0.2                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedSe.
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServic.
Script     1.7.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzL.
Script     1.5.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzL.
Script     2.5.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificat.
Script     2.2.1                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificat.
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuth.
Script     1.3.4                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSou.
Script     1.3.0                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPoli.
Script     1.1.4                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPoli.
Script     1.1.1                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPower.
Script     1.0.2                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, S.
Script     2.8.0                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzReco.
Script     2.4.0                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzReco.
Script     1.2.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCac.
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-.
Script     1.13.0                Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment.
Script     1.9.1                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment.
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNames.
Script     2.0.2                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServ.
Script     2.0.1                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServ.
Script     1.1.1                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, .
Script     2.6.0                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-.
Script     2.1.2                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-.
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove.
Script     1.0.2                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove.
Script     1.14.0                Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, N.
Script     1.11.0                Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, N.
Script     1.2.3                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzSt.
Script     1.2.2                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzSt.
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnaly.
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassi.
Script     1.0.3                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remo.
Script     1.8.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-.
Script     1.5.1                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-.
```

## Debug output

```
Not sure about this step, no output being produced
```

## Error output

```
   HistoryId: 16

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzureSMCmdlet.InitializeProfile()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzureSMCmdlet.BeginProcessing()
                    at Microsoft.WindowsAzure.Commands.Utilities.Profile.SubscriptionCmdletBase.BeginProcessing()
                    at System.Management.Automation.Cmdlet.DoBeginProcessing()
                    at System.Management.Automation.CommandProcessorBase.DoBegin()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzureSubscription}
Line           : get-azuresubscription
Position       : At line:1 char:1
                 + get-azuresubscription
                 + ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 16
```

I also tried Add-AzureAccount and got this error:

```
   HistoryId: 3

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzureSMCmdlet.InitializeProfile()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzureSMCmdlet.BeginProcessing()
                    at Microsoft.WindowsAzure.Commands.Utilities.Profile.SubscriptionCmdletBase.BeginProcessing()
                    at System.Management.Automation.Cmdlet.DoBeginProcessing()
                    at System.Management.Automation.CommandProcessorBase.DoBegin()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzureSubscription}
Line           : get-azuresubscription
Position       : At line:1 char:1
                 + get-azuresubscription
                 + ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

Message        : Could not load type 'System.Management.Automation.PSSnapIn' from assembly 'System.Management.Automation,
                 Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
StackTrace     :    at System.Reflection.RuntimeAssembly.GetExportedTypes()
                    at System.Reflection.Assembly.get_ExportedTypes()
                    at System.Management.Automation.Runspaces.PSSnapInHelpers.GetAssemblyTypes(Assembly assembly, String name)
                    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly
                 assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2&
                 cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
                    at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String
                 name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases,
                 Dictionary`2& providers, String& helpFile)
                    at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly,
                 PSModuleInfo module)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean
                 trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss,
                 ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes,
                 Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName,
                 String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options,
                 ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
                    at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions
                 importModuleOptions, String name)
                    at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
                    at System.Management.Automation.Cmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.TypeLoadException
InvocationInfo : {Import-Module}
Line           : Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Sql\Microsoft.WindowsAzure.Commands.SqlDatabase.dll)

Position       : At C:\Program Files\WindowsPowerShell\Modules\Azure\5.1.2\Azure.psm1:28 char:1
                 + Import-Module (Join-Path -Path $PSScriptRoot -ChildPath Sql\Microsoft .
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

Message        : The specified module 'Azure.Storage' with version '4.2.1' was not loaded because no valid module file was found
                 in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :     Import-Module Azure.Storage -MinimumVersion 4.2.1 -Scope Global

Position       : At C:\Program Files\WindowsPowerShell\Modules\Azure\5.1.2\Azure.psm1:19 char:5
                 +     Import-Module Azure.Storage -MinimumVersion 4.2.1 -Scope Global
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3
```

**Comment by dingmeng-xue** [comment]
@donavan-dd, Once you have installed Az, please try cmdlet `Get-AzSubscription` once you login via `Connect-AzAccount`.
For debug message, you can execute `$DebugPreference="Continue"` and then execute `Get-AzSubscription`. You will see debug message including HTTP communication.

**Comment by donovan-dd** [comment]
Okay, using Get-AzSubscription instead of GetAzureSubscription seems to work.  

Issue resolved, thanks.

**Comment by dingmeng-xue** [comment]
Great. Thanks for your feedback. Closing this issue now.
