### ISSUE TITLE
Update-AzVmss: Changing property 'imageReference.sku' is not allowed.

### ISSUE THREAD

**Issue by amergey** [Azure/azure-powershell#11911]
## Description

I'd like to "upgrade" an imageReference of a scale set.
According to https://docs.microsoft.com/en-us/powershell/module/az.compute/update-azvmss?view=azps-3.8.0 and some other documentations I found, it should be possible to change imageReference sku of a scale set.

When I run following powershell

```powershell
Update-AzVmss -ResourceGroupName "dev-nono-sandbox" -VMScaleSetName "xdm-ss" -ImageReferenceSku "5_2"
```

I get following error:

> Changing property 'imageReference.sku' is not allowed. ErrorCode: PropertyChangeNotAllowed ErrorMessage: Changing property
>      | 'imageReference.sku' is not allowed. ErrorTarget: imageReference.sku StatusCode: 409 ReasonPhrase: Conflict OperationID :
>      | aa02cd99-4814-488e-8a6c-fab1397778be
> 

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Linux 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     3.8.0                 Az                                  Core,Desk 
Script     1.7.5                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataColl…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-A…
Script     1.0.3                 Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential…}
Script     1.1.2                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get…
Script     1.4.1                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Ad…
Script     1.0.3                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplica…
Script     1.3.6                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGrou…
Script     2.0.2                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-…
Script     1.0.2                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Ge…
Script     1.4.3                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzC…
Script     1.3.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get…
Script     3.7.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet…
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, G…
Script     1.1.1                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRe…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeDev…
Script     1.7.0                 Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remo…
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCrede…
Script     1.2.8                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdP…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifact…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlA…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-…
Script     1.2.3                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-…
Script     1.4.3                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamesp…
Script     1.4.0                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     3.1.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsigh…
Script     1.0.1                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-AzHea…
Script     2.4.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnec…
Script     1.6.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVau…
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, G…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzM…
Script     1.0.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceCon…
Script     1.0.2                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remo…
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServi…
Script     1.7.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogPr…
Script     2.5.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGa…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzN…
Script     1.3.4                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperational…
Script     1.3.0                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-Az…
Script     1.1.1                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection,…
Script     1.0.2                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone, N…
Script     2.8.0                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get…
Script     1.2.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-A…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remo…
Script     1.13.0                Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment…
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBus…
Script     2.0.2                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertif…
Script     1.1.1                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     2.6.0                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTranspare…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM…}
Script     1.14.0                Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, N…
Script     1.2.3                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-…
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDef…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSuppor…
Script     1.0.3                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCus…
Script     1.8.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remo…

    Directory: /snap/powershell/129/opt/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionPolicy, ConvertFrom-…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Script     1.4.6                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.2.4                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-DscResource, Invoke-DscResource}
Script     2.0.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineK…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob

    Directory: /home/arnaud-mergey/.vscode/extensions/ms-vscode.powershell-2020.4.0/modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.1.3                 Plaster                             Desk      {Invoke-Plaster, New-PlasterManifest, Get-PlasterTemplate, Test-Plaster…
Binary     2.0.0                 PowerShellEditorServices            Desk      Start-EditorServices
Binary     0.2.0                 PowerShellEditorServices.VSCode     Desk      {New-VSCodeHtmlContentView, Show-VSCodeHtmlContentView, Close-VSCodeHtm…
Script     2.1.0      beta1      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineK…
Script     1.18.3                PSScriptAnalyzer                    Desk      {Get-ScriptAnalyzerRule, Invoke-ScriptAnalyzer, Invoke-Formatter}
```

## Debug output

```
DEBUG: 6:44:02 PM - UpdateAzureRmVmss begin processing with ParameterSet 'DefaultParameter'.
DEBUG: 6:44:02 PM - using account id 'arnaud.mergey@semarchy.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'arnaud.mergey@semarchy.com', environment: 'AzureCloud', tenant: '758077ec-66b9-441c-9537-b0939ca2dfe8'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '758077ec-66b9-441c-9537-b0939ca2dfe8', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/758077ec-66b9-441c-9537-b0939ca2dfe8/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '758077ec-66b9-441c-9537-b0939ca2dfe8', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2155200Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: ADAL PCL.CoreCLR with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2155676Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: ADAL PCL.CoreCLR with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2156136Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: === Token Acquisition started: 
        CacheType: null
        Authentication Target: User
        , Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2156313Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: === Token Acquisition started:
        Authority: https://login.microsoftonline.com/758077ec-66b9-441c-9537-b0939ca2dfe8/
        Resource: https://management.core.windows.net/
        ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
        CacheType: null
        Authentication Target: User


DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.2157657Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.2157869Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2162416Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 3 items to token cache.

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.2163201Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.2163358Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2163893Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2164068Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2165053Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: An expired or near expiry token was found in the cache

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2165196Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: An expired or near expiry token was found in the cache

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2165317Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.2165446Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.2165680Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.2165828Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.8117039Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.8118225Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.8127696Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Verbose: 2020-05-15T16:44:02.8128636Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.8131336Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 5/15/2020 5:44:01 PM +00:00

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.8131959Z: dde3fd28-a7eb-47df-b6fa-99c2c5ec2859 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 5/15/2020 5:44:01 PM +00:00Access Token Hash: X7Jzi/EjsO1gjyDajo8ayN8pFcO74mQUEqLRT6/miUs=
         User id: c640acde-4c25-4273-a147-eeddaf23c109

DEBUG: [ADAL]: Information: 2020-05-15T16:44:02.8132848Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Serializing token cache with 3 items.

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '05/15/2020 17:44:01 +00:00', MultipleResource? 'True', Tenant: '758077ec-66b9-441c-9537-b0939ca2dfe8', UserId: 'arnaud.mergey@semarchy.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'arnaud.mergey@semarchy.com', Name: Arnaud Mergey, IdProvider: 'https://sts.windows.net/758077ec-66b9-441c-9537-b0939ca2dfe8/', Uid: 'c640acde-4c25-4273-a147-eeddaf23c109'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '05/15/2020 17:44:01 +00:00' Comparing to '05/15/2020 16:44:02 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:59:58.9863735'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/455bcbcc-ea8c-4b64-b04b-c908dcfce527/resourceGroups/dev-nono-sandbox/providers/Microsoft.Compute/virtualMachineScaleSets/xdm-ss?api-version=2019-12-01

Headers:
x-ms-client-request-id        : 2b7fe9b5-2f49-4ea6-b986-fc9ec23f48b8
Accept-Language               : en-US

Body:
{
  "properties": {
    "virtualMachineProfile": {
      "storageProfile": {
        "imageReference": {
          "sku": "5_2"
        }
      }
    }
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/VMScaleSetActions3Min;239,Microsoft.Compute/VMScaleSetActions30Min;1197
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : cb46c8d3-3161-4134-b664-5ace26e6ee71
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : f77ad894-391e-49fd-8e05-8330e0ea107b
x-ms-routing-request-id       : FRANCECENTRAL:20200515T164403Z:f77ad894-391e-49fd-8e05-8330e0ea107b
X-Content-Type-Options        : nosniff
Date                          : Fri, 15 May 2020 16:44:02 GMT

Body:
{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "message": "Changing property 'imageReference.sku' is not allowed.",
    "target": "imageReference.sku"
  }
}


DEBUG: AzureQoSEvent: CommandName - Update-AzVmss; IsSuccess - True; Duration - 00:00:01.0955191;
DEBUG: Finish sending metric.
DEBUG: 6:44:03 PM - UpdateAzureRmVmss end processing.
Update-AzVmss: /home/arnaud-mergey/git/dev-tools/cloud-xdm-solution/upgrade.ps1:1:1
Line |
   1 |  Update-AzVmss -ResourceGroupName "dev-nono-sandbox" -VMScaleSetName " …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Changing property 'imageReference.sku' is not allowed. ErrorCode: PropertyChangeNotAllowed ErrorMessage: Changing property
     | 'imageReference.sku' is not allowed. ErrorTarget: imageReference.sku StatusCode: 409 ReasonPhrase: Conflict OperationID :
     | cb46c8d3-3161-4134-b664-5ace26e6ee71

DEBUG: AzureQoSEvent: CommandName - Update-AzVmss; IsSuccess - False; Duration - 00:00:01.0955191;; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: Changing property 'imageReference.sku' is not allowed.
ErrorCode: PropertyChangeNotAllowed
ErrorMessage: Changing property 'imageReference.sku' is not allowed.
ErrorTarget: imageReference.sku
StatusCode: 409
ReasonPhrase: Conflict
OperationID : cb46c8d3-3161-4134-b664-5ace26e6ee71
 ---> Microsoft.Rest.Azure.CloudException: Changing property 'imageReference.sku' is not allowed.
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.BeginUpdateWithHttpMessagesAsync(String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSetUpdate parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.UpdateWithHttpMessagesAsync(String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSetUpdate parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.UpdateAsync(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSetUpdate parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.Update(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSetUpdate parameters)
   at Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss.<ExecuteCmdlet>b__0_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 6:44:04 PM - UpdateAzureRmVmss end processing.
```

## Error output

```
   HistoryId: 28

RequestId      : 
Message        : Changing property 'imageReference.sku' is not allowed.
                 ErrorCode: PropertyChangeNotAllowed
                 ErrorMessage: Changing property 'imageReference.sku' is not allowed.
                 ErrorTarget: imageReference.sku
                 StatusCode: 409
                 ReasonPhrase: Conflict
                 OperationID : cb46c8d3-3161-4134-b664-5ace26e6ee71
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Update-AzVmss}
Line           : Update-AzVmss -ResourceGroupName "dev-nono-sandbox" -VMScaleSetName "xdm-ss" -ImageReferenceSku "5_2"
Position       : At /home/arnaud-mergey/git/dev-tools/cloud-xdm-solution/upgrade.ps1:1 char:1
                 + Update-AzVmss -ResourceGroupName "dev-nono-sandbox" -VMScaleSetName " …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 28
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. I involve Compute team to look into this issue.

**Comment by Drewm3** [comment]
@avirishuv, could you look into this please.

**Comment by amergey** [comment]
The image I am using requires a plan 
```
 "virtualMachineProfile": {
          
            "imageReference": {
                    "publisher": "imagePublisher",
                     "offer": "imageOffer",
                     "sku": "imageSku",
                     "version": "latest"
            }
          },
```
requires plan info otherwise creation of the scale set fails

 ```
"plan": {
        "name": "imageSku",
        "product": "imageOffer",
        "publisher": "imagePublisher"
      },
```
It may be the plan that is preventing sku to be changed.

**Comment by avirishuv** [comment]
@amergey updating the imageReference.sku for a VMSS should be allowed, as I was able to repro with another image (Ubuntu). We are still investigating the reason its getting blocked in this case and will provide an update, whether it is getting blocked due to image properties or some other reason.

**Comment by avirishuv** [comment]
@amergey In this specific case, changing the imageReference.sku is attempting to change the image from a Gen 1 to Gen 2, which is why it is not allowed. We will be updating the error message to appropriately reflect this and provide more accurate reason for blocking the imageReference.sku update.

**Comment by amergey** [comment]
@avirishuv Are you sure ? it seems to me I never can change sku even from same gen images, but changing version in same sku is always working so my guess is all my images are from same gen

**Comment by amergey** [comment]
Hello I deploy the very same image in 2 different sku to do the test.

Both below are the same 
_publisher: semarchy
offer: xdm-solution-vm
sku/plan: 5_1 
version: 5.1.9_ 

_publisher: semarchy
offer: xdm-solution-vm
sku/plan: 5_3_preview
version: 0.0.1_

I did a tested starting from image
_publisher: semarchy
offer: xdm-solution-vm
sku/plan: 5_1 
version: 5.1.7_ 

trying to move scaleset to sku 5_3_preview and version 0.0.1 fails with **Changing property 'imageReference.sku' is not allowed.**
trying to move scaleset to version 5.1.9 in same sku is working

So it seems to confirm this is related to sku/plan

**Comment by avirishuv** [comment]
@amergey thanks for sharing this example, we are looking into this and will share the reason why this works for certain cases while not for others. We'll also update the documentation to reflect the considerations for imageReference.sku updates.

**Comment by avirishuv** [comment]
hi @amergey the images that you have mentioned here involve a publisher that have a plan info. Updating image reference sku in vmss where the new sku has a plan info is not supported.

**Comment by amergey** [comment]
hi @avirishuv thanks for the reply. Is it possible to publish images in marketplace without plan info ? or is it something required when publishing images to marketplace ? This is unfortunate for us to discover this limitation so late as it was advised to us by Microsoft to use custom marketplace images to ease upgrade of our solution in a scaleset.

**Comment by github-2407** [comment]
Hi @amergey - Marketplace images are always published with a plan info

**Comment by amergey** [comment]
Hi @github-2407 sorry to come back with this, but ubuntu marketplace image seems to be published without plan info, as for a scale set pointing to marketplace ubuntu images it is possible to change sku

**Comment by github-2407** [comment]
Hi @amergey, yes it's possible to change SKU for Ubuntu as there is no plan information.

The[ endorsed Linux distros ](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/endorsed-distros) don't require plan information and hence their SKUs can be updated

**Comment by avirishuv** [comment]
hi @amergey please let us know if any other questions on this topic. If not, then are we good to close the issue ?

**Comment by amergey** [comment]
Hello @avirishuv no other questions just some remarks, this scaleset limitation should be clearly documented, it would avoid others to make same mistake we did. 
Pushing our images through marketplace was supposed to ease scale set upgrade and we choose to do that because it was advised to us by Microsoft people, it is really unfortunate to discover this limitation after almost a year between this issue and https://github.com/MicrosoftDocs/azure-docs/issues/50063

**Comment by avirishuv** [comment]
Hi @amergey agree, the documentation was updated with this clarification here: https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-upgrade-scale-set#create-time-properties
Appreciate your inputs. I'll go ahead and close this issue, feel free to reopen if any other comments/questions.
