### ISSUE TITLE
Az.Subscription PowerShell Module API Mismatch Azure Government

### ISSUE THREAD

**Issue by JustinBacaAIS** [Azure/azure-powershell#11952]
## Description
Receiving the following error when trying to create a subscription programmatically. In powershell with Az.Subscription module version 0.7.2, 0.7.2-preview, and 0.7.1-preview.

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-ratelimit-remaining-tenant-resource-requests: 499
x-ms-request-id               : bdd24330-2b84-43e9-97ec-08f0beb36a18
x-ms-correlation-request-id   : bdd24330-2b84-43e9-97ec-08f0beb36a18
x-ms-routing-request-id       : USDODEAST:20200519T155002Z:bdd24330-2b84-43e9-97ec-08f0beb36a18
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 19 May 2020 15:50:02 GMT

Body:
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'createSubscription' could not be found in the namespace 'Microsoft.Subscription' for api version '2018-03-01-preview'. The supported api-versions are '2019-10-01-preview'."
  }
}


New-AzSubscription: Operation returned an invalid status code 'NotFound'
DEBUG: AzureQoSEvent: CommandName - New-AzSubscription; IsSuccess - False; Duration - 00:00:02.2652596;; Exception - Microsoft.Azure.Management.Subscription.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound'
```

## Steps to reproduce

```powershell
New-AzSubscription -OfferType MS-AZR-USGOV-0017P -Name "DEMO-SUB-01" -EnrollmentAccountObjectId $eAcct.ObjectId -OwnerObjectId $acctOwnerObjectId -Debug
```

## Environment data

```text
Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.0.2                 Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzConsumptionBudget, Get-AzConsumptionMarketplace…}
Script     2.0.1                 Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Get-AzADAppCredential, Get-AzADApplication…}
Script     0.7.2                 Az.Subscription                     New-AzSubscription
```

## Debug output

```

```

## Error output

```
   HistoryId: 8

Message        : Operation returned an invalid status code 'NotFound'
StackTrace     :    at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperations.BeginCreateSubscriptionInEnrollmentAccountWithHttpMessagesAsync(String enrollmentAccountName, SubscriptionCreationParameters body,
                 Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperations.CreateSubscriptionInEnrollmentAccountWithHttpMessagesAsync(String enrollmentAccountName, SubscriptionCreationParameters body, Dictionary`2
                 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperationsExtensions.CreateSubscriptionInEnrollmentAccountAsync(ISubscriptionFactoryOperations operations, String enrollmentAccountName,
                 SubscriptionCreationParameters body, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperationsExtensions.CreateSubscriptionInEnrollmentAccount(ISubscriptionFactoryOperations operations, String enrollmentAccountName,
                 SubscriptionCreationParameters body)
                    at Microsoft.Azure.Commands.Subscription.Cmdlets.NewAzureRmSubscription.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.Subscription.Models.ErrorResponseException
InvocationInfo : {New-AzSubscription}
Line           : New-AzSubscription -OfferType MS-AZR-USGOV-0017P -Name "DEMO-SUB-01" -EnrollmentAccountObjectId $eAcct.ObjectId -OwnerObjectId $acctOwnerObjectId -Debug
Position       : At line:1 char:1
                 + New-AzSubscription -OfferType MS-AZR-USGOV-0017P -Name "DEMO-SUB …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8
```

**Comment by JustinBacaAIS** [comment]
Also tracking an issue with Azure CLI and the Offer Type support for Azure Government MS-AZR-USGOV-0017P

[#1733](https://github.com/Azure/azure-cli-extensions/issues/1733)

**Comment by dingmeng-xue** [comment]
Subscription team, please consider to upgrade API version because some government cloud doesn't support older version such as current 2018-03-01-preview.

**Comment by anuragdalmia** [comment]
Investigating.

**Comment by anuragdalmia** [comment]
We are in the process of updating our latest version of powershell SDK to fix this. The current target for this is end of July. We will keep this thread updated.

**Comment by anuragdalmia** [comment]
@JustinBacaAIS  - we have updated the powershell support for this. Please use the latest version where this issue is fixed. Thank you for your patience. I will be closing this issue. Please re-activate if you see any other issues.
