### ISSUE TITLE
Add-AzApplicationGatewayBackendAddressPool : "BackendIPConfigurationIds" is not implemented.

### ISSUE THREAD

**Issue by znrk** [Azure/azure-powershell#12033]
"Example 3" is an example of "BackendIPConfigurationId" option, but isn't this option implemented?
I think you should remove "Exapmle 3" in this document or link to the content of "Set-AzNetwork InterfaceIpConfig".

## Steps to reproduce

```powershell
*coud you run like a "Example 3".
```

## Environment data

$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0```

```

## Module versions

<!-- Please run (Get-Module  -ListAvailable) and paste the output in the below code block -->

```powershell
Get-InstalledModule az.network -AllVersions

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.4.0                Az.Network                          PSGallery            Microsoft Azure PowerShell - Networking …

```

## Debug output

```

```

## Error output

```
   HistoryId: 100

Message        : A parameter cannot be found that matches parameter name 'BackendIPConfigurationIds'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterB
                 indingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidati
                 on(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collectio
                 n`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues
                 )
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input
                 )
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input
                 )
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, Comma
                 ndParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] command
                 Redirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame fr
                 ame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Add-AzApplicationGatewayBackendAddressPool}
Line           : Add-AzApplicationGatewayBackendAddressPool -ApplicationGateway $APPGW -Name "pool" -BackendIPConfigura
                 tionIds $VM1NIC.IpConfigurations[0].Id, $VM2NIC.IpConfigurations[0].Id
Position       : At line:1 char:84
                 + … icationGateway $APPGW -Name "pool" -BackendIPConfigurationIds $VM1NIC …
                 +                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 100```

**Comment by dingmeng-xue** [comment]
Network team, please help to review this question on reference example.

**Comment by KarenHammons** [comment]
@surajmb can you assist?

**Comment by surajmb** [comment]
@znrk , thanks for reporting this. NICs can't be added to Application Gateway backend pool using IP configuration, it has to be added at the NIC properties and back referencing Application Gateway's backend pool. Like,

$nic=Get-AzNetworkInterface -Name nic123 -ResourceGroupName rgOne
$gw = Get-AzApplicationGateway -Name appgwv2 -ResourceGroupName rgOne
$appgwbepool = Get-AzApplicationGatewayBackendAddressPool -Name bepool1 -ApplicationGateway $gw
Set-AzNetworkInterfaceIpConfig -Name ipconfig1 -NetworkInterface $nic -PrivateIpAddressVersion IPv4 -PrivateIpAddress "10.1.1.4" -ApplicationGatewayBackendAddressPool $appgwbepool
Set-AzNetworkInterface -NetworkInterface $nic

We'll make appropriate changes to the document.
