### ISSUE TITLE
Get-AzApplyUpdate ResourceType not found

### ISSUE THREAD

**Issue by balauppaloori** [Azure/azure-powershell#12059]
## Description
Running Get-AzApplyUpdate throws error 'Resource Type' is invalid. This is a text value that's being passed, taken straight from docs. It appears the module expects parameters in a particular order, but it isnt mentioned anywhere. the docs order is not working.

Get-AzApplyUpdate : The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2018-06-01-preview'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 98977a60-daa1-45bc-8ac3-5a82e1f9daa9
At line:1 char:3
+   Get-AzApplyUpdate -ResourceGroupName $ResourceGroupName -ResourceTy ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzApplyUpdate], MaintenanceCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Maintenance.GetAzureRmApplyUpdate

## Steps to reproduce
Command:
```powershell
Get-AzApplyUpdate -ResourceGroupName $ResourceGroupName -ResourceType hosts -ResourceName $HostName -ResourceParentType hostGroups   -ResourceParentName $ResourceParentName  -ProviderName Microsoft.Compute -ApplyUpdateName default 
```
All values ($ResourceGroupName, $HostName, $Resourceparentname) are valid and logged into my subscription to get my dedicated hosts info.

## Environment data
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
## Module versions

```powershell
get-module Az.maintenance -listavailable

Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.0      Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzM...
```
## Debug output
```powershell
Get-AzApplyUpdate -ResourceGroupName $ResourceGroupName  -ResourceParentType hostGroups   -ResourceParentName $ResourceParentName -ResourceType hosts  -ResourceName $HostName  -ProviderName Microsoft.Compute   -ApplyUpdateName default

Get-AzApplyUpdate : The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2018-06-01-preview'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : 96cdda38-b7ea-47d1-a31c-d83eb6dfd75f
At line:6 char:1
+ Get-AzApplyUpdate -ResourceGroupName $ResourceGroupName  -ResourcePar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzApplyUpdate], MaintenanceCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Maintenance.GetAzureRmApplyUpdate

```
## Error output

```
Resolve-AzError
WARNING: Breaking changes in the cmdlet 'Resolve-AzError' :
WARNING:  - The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.

WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.


   HistoryId: 23


RequestId      :
Message        : The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2018-06-01-preview'.
                 StatusCode: 404
                 ReasonPhrase: Not Found
                 OperationID : e09536ed-0e17-4bcb-9931-bb18ec4c5bf3
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {Get-AzApplyUpdate}
Line           : Get-AzApplyUpdate -ResourceGroupName $ResourceGroupName  -ResourceParentType hostGroups   -ResourceParentName $ResourceParentName -ResourceType hosts  -ResourceName $HostName  -ProviderName Microsoft.Compute   -ApplyUpdateName default

Position       : At line:6 char:1
                 + Get-AzApplyUpdate -ResourceGroupName $ResourceGroupName  -ResourcePar ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Maintenance.MaintenanceClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 23


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

```

**Comment by balauppaloori** [comment]
I have noticed in the source [here](src/Maintenance/Maintenance/ApplyUpdate/ApplyUpdateGetMethod.cs) that some parameters are positioned, and some not. Supplying in this order also fails.
```c#
  [Parameter(
            ParameterSetName = "DefaultParameter",
            Position = 0,
            Mandatory = true,
            HelpMessage = "The resource Group Name.",
            ValueFromPipelineByPropertyName = true)]
        [ResourceGroupCompleter]
        public string ResourceGroupName { get; set; }

        [Parameter(
            ParameterSetName = "DefaultParameter",
            Position = 1,
            Mandatory = true,
            HelpMessage = "The resource provider Name.",
            ValueFromPipelineByPropertyName = true)]
        public string ProviderName { get; set; }

        [Parameter(
            ParameterSetName = "DefaultParameter",
            Mandatory = false,
            HelpMessage = "The parent resource type.",
            ValueFromPipelineByPropertyName = true)]
        public string ResourceParentType { get; set; }

        [Parameter(
            ParameterSetName = "DefaultParameter",
            Mandatory = false,
            HelpMessage = "The parent resource name.",
            ValueFromPipelineByPropertyName = true)]
        public string ResourceParentName { get; set; }

        [Parameter(
            ParameterSetName = "DefaultParameter",
            Position = 2,
            Mandatory = true,
            HelpMessage = "The resource type.",
            ValueFromPipelineByPropertyName = true)]
        public string ResourceType { get; set; }

        [Parameter(
            ParameterSetName = "DefaultParameter",
            Position = 3,
            Mandatory = true,
            HelpMessage = "The resource name.",
            ValueFromPipelineByPropertyName = true)]
        public string ResourceName { get; set; }

        [Parameter(
            ParameterSetName = "DefaultParameter",
            Mandatory = true,
            HelpMessage = "The apply update resource name.",
            ValueFromPipelineByPropertyName = true)]
        public string ApplyUpdateName { get; set; }
    }
}
```

**Comment by dingmeng-xue** [comment]
@balauppaloori , could you share debug message after you enable `$DebugPreference="Continue"`?

Basing on error message, it seems cmdlet is trying to fetching a VM named as hosts. Please check if VM is accessible.

**Comment by balauppaloori** [comment]
Hi @dingmeng-xue, No the command isnt looking for a VM called hosts. We are specifying -ResourceType as hosts (this is directly from documentation [here](https://docs.microsoft.com/en-us/powershell/module/az.maintenance/get-azapplyupdate?view=azps-3.8.0). ) We are trying to get the last update applied on a dedicated host. 
Below is the debug output. i have removed all subscripiton, tenant and other identifiable info:
Command used:
```powershell
Get-AzApplyUpdate -ResourceGroupName $ResourceGroupName -ResourceParentType hostGroups -ResourceParentName $ResourceParentName -ResourceType hosts -ResourceName $HostName -ProviderName Microsoft.Compute -ApplyUpdateName default -ErrorAction SilentlyContinue

Result:
DEBUG: Sought all Az modules and got latest version 0.0.0
DEBUG: 7:25:55 PM - GetAzureRmApplyUpdate begin processing with ParameterSet 'DefaultParameter'.

DEBUG: [ADAL]: Information: 2020-06-04T02:25:55.8005891Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2
605056' is running...

DEBUG: [ADAL]: Information: 2020-06-04T02:25:55.8005891Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2
605056' is running...

DEBUG: [ADAL]: Information: 2020-06-04T02:25:55.8005891Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: 

DEBUG: [ADAL]: Information: 2020-06-04T02:25:55.8005891Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: === Token Acquisition started:
	Authority: 
	Resource: 
	ClientId: 
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.0515459Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.0515459Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.0545132Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 4 items to token cache.

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.0634261Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.0634261Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.0674452Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.0674452Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.0694841Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: An expired or near expiry token was found in the cache

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.0694841Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: An expired or near expiry token was found in the cache

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.0694841Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.0694841Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.0714769Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.0714769Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Refreshing access token...

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.3970285Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.3970285Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: Storing token in the cache...

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.3970285Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Verbose: 2020-06-04T02:25:56.3970285Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: An item was stored in the cache

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.4010288Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/4/2020 3:25:55 AM +00:00

DEBUG: [ADAL]: Information: 2020-06-04T02:25:56.4010288Z: 6400a043-b925-443d-bd33-8a03abde0d87 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 6/4/2020 3:25:55 AM +00:00Access 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<SubscriptionId>/resourcegroups/<ResourceGroupHere>/providers/Microsoft.Compute/hosts/<hostnamehere>/providers/Microsoft.Maintenance/applyUpdates/default?api-version=2018-06-01-preview

Headers:
x-ms-client-request-id        : 49cd5409-f5af-4fc7-a6df-e27a3f405836
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : eba783bc-8ebc-4d5d-a774-03f27320734c
x-ms-correlation-request-id   : eba783bc-8ebc-4d5d-a774-03f27320734c
x-ms-routing-request-id       : WESTUS2:20200604T022556Z:eba783bc-8ebc-4d5d-a774-03f27320734c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 04 Jun 2020 02:25:56 GMT

Body:
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2018-06-01-preview'."
  }
}


DEBUG: AzureQoSEvent: CommandName - Get-AzApplyUpdate; IsSuccess - True; Duration - 00:00:00.9818876;
DEBUG: Finish sending metric.
DEBUG: 7:25:57 PM - GetAzureRmApplyUpdate end processing.
DEBUG: AzureQoSEvent: CommandName - Get-AzApplyUpdate; IsSuccess - False; Duration - 00:00:00.9818876;; Exception - Microsoft.Azure.Commands.Maintenance.Common.MaintenanceCloudException: The resource type could not be found in the namespace 'Microsoft.Comput
e' for api version '2018-06-01-preview'.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : eba783bc-8ebc-4d5d-a774-03f27320734c ---> Microsoft.Rest.Azure.CloudException: The resource type could not be found in the namespace 'Microsoft.Compute' for api version '2018-06-01-preview'.
   at Microsoft.Azure.Management.Maintenance.ApplyUpdatesOperations.<GetWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Maintenance.ApplyUpdatesOperationsExtensions.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Maintenance.ApplyUpdatesOperationsExtensions.Get(IApplyUpdatesOperations operations, String resourceGroupName, String providerName, String resourceType, String resourceName, String applyUpdateName)
   at Microsoft.Azure.Commands.Maintenance.GetAzureRmApplyUpdate.<ExecuteCmdlet>b__0_0()
   at Microsoft.Azure.Commands.Maintenance.MaintenanceClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Maintenance.MaintenanceClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 7:25:57 PM - GetAzureRmApplyUpdate end processing.
```

**Comment by dingmeng-xue** [comment]
@gautamd-ms, Please help to look into this issue.

**Comment by sotaneja** [comment]
@balauppaloori  in the debug trace you provided, the URI (copied below) should have the hostgroups parameter but it missing from your output. Is this because of the edits you made to the text or was it not in the URI originally? because I see you have correctly passed in the parameter -ResourceParentType hostGroups

Absolute Uri:
https://management.azure.com/subscriptions/<SubscriptionId>/resourcegroups/<ResourceGroupHere>/providers/Microsoft.Compute/**hostGroups/<inserthostGroupName>/**hosts/<hostnamehere>/providers/Microsoft.Maintenance/applyUpdates/default?api-version=2018-06-01-preview

Currently, I don't see anything wrong with the parameters you have provided or the ordering. Is it possible for you to provide us with the  exact parameters you have passed in inlcuding the ResourceGroupName ResourceParentName and ResourceName. Thanks.

**Comment by balauppaloori** [comment]
Turns out, it was my issue after all. I passed in a wrong parameter in the original. Thanks for the resolution.

**Comment by balauppaloori** [comment]
Turns out, it was my issue after all. I passed in a wrong parameter in the original. Thanks for the resolution.
