### ISSUE TITLE
AzCopy command not working in azure function

### ISSUE THREAD

**Issue by dqureshi515** [Azure/azure-powershell#12097]
I am trying to run an AzCopy command in azure function. The command works perfectly fine in local powershell as well as in azure cli but gives error in the azure function. 

**Error:**
2020-06-09T10:35:59.587 [Error] ERROR: azcopy : The term 'azcopy' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\home\site\wwwroot\HttpTrigger1\run.ps1:30 char:1
+ azcopy copy 'https://testaccount.blob.core.windows.net/barcon ...
+ ~~~~~~
+ CategoryInfo          : ObjectNotFound: (azcopy:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
 
Script stack trace:
   at <ScriptBlock>, D:\home\site\wwwroot\HttpTrigger1\run.ps1: line 30

System.Management.Automation.CommandNotFoundException: The term 'azcopy' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException : Result: ERROR: azcopy : The term 'azcopy' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At D:\home\site\wwwroot\HttpTrigger1\run.ps1:30 char:1
+ azcopy copy 'https://testaccount.blob.core.windows.net/barcon ...
+ ~~~~~~
+ CategoryInfo          : ObjectNotFound: (azcopy:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

**Comment by dingmeng-xue** [comment]
All Azure PowerShell cmdlets are following pattern {Verb}-Az{Noun}. We have no idea about AzCopy.

If you have an environment which supports AzCopy, please share us the result of below script. It can help to identify its module.
```
Get-Command -Name AzCopy
```

**Comment by dingmeng-xue** [comment]
@dqureshi515 , I am closing this issue now because AzCopy is not cmdlet from Azure PowerShell. Please create new issue if you have further update.
