### ISSUE TITLE
Type cast error in Site Recovery cmdlets when setting -DefaultProfile

### ISSUE THREAD

**Issue by sean-nixon** [Azure/azure-powershell#12121]
## Description

The Azure Site Recovery cmdlets do not seem to support passing in `-DefaultProfile` in the same manner that every other cmdlet allows. It results in a type cast error:

```
Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'
```

I am trying to use the context object that is returned from the `Set-AzContext` or `Select-AzSubscription` cmdlets. This seems to work for every other cmdlet that I've tested except Site Recovery cmdlets. The steps to reproduce below demonstrate the issue with `Set-AzRecoveryServicesAsrVaultContext` and `Get-AzRecoveryServicesAsrFabric`, but the issue appears to be on every cmdlet related to ASR.

This causes a lot of issues for us because we are using these cmdlets within an Azure Automation account that interacts with multiple subscriptions. Calling `Set-AzContext` can affect other jobs running in the same account and change the current context, so we are explicitly passing `-DefaultProfile` on all commands to ensure that we are interacting with the expected subscription. If there's a better way to achieve the result achieving this isolation, I'm all ears, but regardless it seems like the Site Recovery cmdlets should still support `-DefaultProfile` in the same way as other cmdlets.

## Steps to reproduce

```powershell
PS /> $context = Set-AzContext -SubscriptionId "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
PS /> $vault = Get-AzRecoveryServicesVault -Name example-vault -DefaultProfile $context
PS /> Set-AzRecoveryServicesAsrVaultContext -Vault $vault -DefaultProfile $context
WARNING: Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
Set-AzRecoveryServicesAsrVaultContext: Operation failed.
Download vault credential file using cmdlet Get-AzRecoveryServicesVaultSettingsFile and Import-AzRecoveryServicesAsrVaultSettingsFile

PS /> Set-AzRecoveryServicesAsrVaultContext -Vault $vault

ResourceName                     ResourceGroupName                ResourceNamespace          ResouceType
------------                     -----------------                -----------------          -----------
example-vault example-rg Microsoft.RecoveryServices vaults

PS /> Get-AzRecoveryServicesAsrFabric

Name                  : asr-a2a-default-eastus2
FriendlyName          : East US 2
ID                    : /Subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/resourceGroups/example-rg/providers/Microsoft.RecoveryServices/vaults/example-vault/replicationFabrics/asr-a2a-default
                        -eastus2
Type                  : Microsoft.RecoveryServices/vaults/replicationFabrics
FabricType            : Azure
SiteIdentifier        : xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx
FabricSpecificDetails : Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.ASRAzureFabricSpecificDetails

Name                  : asr-a2a-default-centralus
FriendlyName          : Central US
ID                    : /Subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/example-rg/providers/Microsoft.RecoveryServices/vaults/example-vault/replicationFabrics/asr-a2a-default
                        -centralus
Type                  : Microsoft.RecoveryServices/vaults/replicationFabrics
FabricType            : Azure
SiteIdentifier        : xxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxx
FabricSpecificDetails : Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.ASRAzureFabricSpecificDetails


PS /> Get-AzRecoveryServicesAsrFabric -DefaultProfile $context
Get-AzRecoveryServicesAsrFabric: Operation failed.
Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'
```

## Environment data

```
PS /> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.1
PSEdition                      Core
GitCommitId                    7.0.1
OS                             Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.2.0                 Az                                  Core,Desk
Script     1.8.1                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.6.6                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, Get-AzAdvisorConfiguration…}
Script     1.1.1                 Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential…}
Script     1.1.3                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer…}
Script     2.0.1                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion, Add-AzApiManagementUserToGroup…}
Script     1.1.0                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Update-AzApplicationInsights…}
Script     1.3.6                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration…}
Script     3.0.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount…}
Script     1.0.3                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget…}
Script     1.4.3                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile…}
Script     1.4.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSku, Get-AzCognitiveServicesAccountType…}
Script     4.1.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet…}
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.1.1                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry…}
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeDevice, New-AzDataBoxEdgeDevice…}
Script     1.8.1                 Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2…}
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCr…
Script     1.2.8                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider…}
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzDataShareAccount, New-AzDataShare…}
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-AzDeploymentManagerArtifactSource, Remove-AzDeploymentManagerArtifactSou…
Script     1.0.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Get-AzWvdApplication, Get-AzWvdApplicationGroup, Get-AzWvdDesktop…}
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy…}
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet…}
Script     1.2.3                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey…}
Script     1.4.3                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace…}
Script     1.5.0                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     1.0.0                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan, Get-AzFunctionAppSetting…}
Script     3.2.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition…}
Script     1.0.2                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-AzHealthcareApisService, Get-AzHealthcareApisService}
Script     2.5.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob…}
Script     2.0.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation…}
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl…}
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan…}
Script     1.0.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfiguration, Get-AzMaintenanceUpdate…}
Script     1.0.2                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedServicesAssignment, Get-AzManagedServicesDefinition…}
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzMediaServiceNameAvailability…}
Script     2.0.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile…}
Script     3.0.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, R…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Get-AzNotificationHubPNSCredential…}
Script     2.1.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, …
Script     1.3.1                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation…}
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKey, Get-AzPowerBIWorkspace…}
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone, New-AzPrivateDnsZone…}
Script     2.9.1                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault…}
Script     1.2.1                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule…}
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace…}
Script     2.1.0                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment…}
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace…}
Script     2.1.0                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode, Add-AzServiceFabricNodeType…}
Script     1.1.1                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     2.7.0                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatab…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM…}
Script     2.1.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey…}
Script     1.2.3                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncService, Remove-AzStorageSyncService…}
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction…}
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupportTicket, Get-AzSupportTicketCommunication…}
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficMa…
Script     1.9.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan…}



ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionPolicy, ConvertFrom-SecureString…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Script     1.4.6                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.2.4                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-DscResource, Invoke-DscResource}
Script     2.0.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption…}
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob
```

## Debug output

```
PS /> Get-AzRecoveryServicesAsrFabric -DefaultProfile $context -Debug
DEBUG: 10:38:01 PM - GetAzureRmRecoveryServicesAsrFabric begin processing with ParameterSet 'Default'.
DEBUG: 10:38:01 PM - using account id 'me@example.com'...
DEBUG: [ADAL]: Information: 2020-06-11T03:38:01.0587970Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Serializing token cache with 9 items.

Get-AzRecoveryServicesAsrFabric: Operation failed.
Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
DEBUG: AzureQoSEvent: CommandName - Get-AzRecoveryServicesAsrFabric; IsSuccess - False; Duration - 00:00:00.0294099;; Exception - System.Exception: Operation failed.
Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.PSRecoveryServicesClient..ctor(IAzureContextContainer azureProfile)
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.get_RecoveryServicesClient()
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrFabric.GetAll()
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrFabric.ExecuteSiteRecoveryCmdlet()
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.HandleException(Exception ex)
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:38:01 PM - GetAzureRmRecoveryServicesAsrFabric end processing.
```

## Error output

```
   HistoryId: 28

Message        : Operation failed.
                 Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.HandleException(Exception ex)
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Get-AzRecoveryServicesAsrFabric}
Line           : Get-AzRecoveryServicesAsrFabric -DefaultProfile $context
Position       : At line:1 char:1
                 + Get-AzRecoveryServicesAsrFabric -DefaultProfile $context
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 28

Message        : Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.PSRecoveryServicesClient..ctor(IAzureContextContainer azureProfile)
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.get_RecoveryServicesClient()
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrFabric.GetAll()
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrFabric.ExecuteSiteRecoveryCmdlet()
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
Exception      : System.InvalidCastException
InvocationInfo : {Get-AzRecoveryServicesAsrFabric}
Line           : Get-AzRecoveryServicesAsrFabric -DefaultProfile $context
Position       : At line:1 char:1
                 + Get-AzRecoveryServicesAsrFabric -DefaultProfile $context
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 28
```

**Comment by dingmeng-xue** [comment]
@sean-nixon , could you uninstall Az.Accounts 1.6.6, restart powershell and try again?

**Comment by sean-nixon** [comment]
@dingmeng-xue I uninstalled Az.Accounts 1.6.6 and retried. Same results.

```powershell

PS /> Get-Module -ListAvailable | Where-Object { $_.Name -eq "Az.Accounts" }

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.8.1                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}

PS /> $context = Select-AzSubscription 'xxxxxxx-xxxx-xxxx-xxxxxxxxxx'
PS /> Get-ASRFabric -DefaultProfile $context
Get-AzRecoveryServicesAsrFabric: Operation failed.
Unable to cast object of type 'Microsoft.Azure.Commands.Profile.Models.Core.PSAzureContext' to type 'Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureContext'.
```

**Comment by sean-nixon** [comment]
@dingmeng-xue I see that the "More Info" label is still on this issue. Was there more information you needed from me?

**Comment by dingmeng-xue** [comment]
Service team, the root cause should be related to below code that default context should use interface because the type may be different during pipe

https://github.com/Azure/azure-powershell/blob/c9e93a70ab4a34251f3f0be9a901162453511767/src/RecoveryServices/RecoveryServices.SiteRecovery/Common/PSAsrComputeManagementClient.cs#L61

**Comment by Rajeswari-Mamilla** [comment]
@dingmeng-xue , thank you for sharing additional details. We will review the issue & will get back soon on the next steps.

**Comment by Sharmistha-Rai** [comment]
We are tracking this in our backlog items and have logged a bug for this. Bug:
https://msazure.visualstudio.com/One/_workitems/edit/7904775

**Comment by Sharmistha-Rai** [comment]
Please feel free to reopen for any additional queries.

**Comment by KlutzyBubbles** [comment]
Is there an update on the status of this, i am running Az.Accounts 2.8.0 and Az.RecoveryServices 5.4.0 and it still seems to be an issue.

**Comment by Antonyo** [comment]
Exactly same issue here.  Did anyone find any workaround?

Calling these commands from an automation account runbook in parallel affect each other context if executed under the same sandbox process.
