### ISSUE TITLE
Set-AzActionRule : The term 'Set-AzActionRule' is not recognized as the name of a cmdlet, function, script file, or operable program

### ISSUE THREAD

**Issue by dbehnood** [Azure/azure-powershell#12208]
## Description
Regardless of the parameters, and how they are passed (even inserting static values), I get the following when trying to execute Set-AzActionRule in 4.2.0. I have even tried using the basic [examples here](https://docs.microsoft.com/en-us/powershell/module/az.alertsmanagement/set-azactionrule?view=azps-3.8.0#code-try-6) and still get the same result.

## Steps to reproduce
Run the Set-AzActionRule in any format you like.
```
Set-AzActionRule : The term 'Set-AzActionRule' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ Set-AzActionRule
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Set-AzActionRule:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

## Environment data

```
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.752
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.752
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
PS C:\WINDOWS\system32> Get-InstalledModule -Name Az  -AllVersions

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
4.1.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage
4.2.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage
3.3.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage
```

## Error output

```
Message        : The term 'Set-AzActionRule' is not recognized as the name of a cmdlet, function, script file, or
                 operable program. Check the spelling of the name, or if a path was included, verify that the path is
                 correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName,
                 CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName,
                 CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe,
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[]
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Set-AzActionRule
Position       : At line:1 char:1
                 + Set-AzActionRule
                 + ~~~~~~~~~~~~~~~~
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It will be forwarded to service team.

**Comment by vinhent** [comment]
I'm having the same issue with the `Set-AzActionRule` cmdlet. Same Az module version and PowerShell version.

**Comment by dingmeng-xue** [comment]
@dbehnood  and @vinhent , I suspect it is due to the module is not installed. Az.AlertsManagement is still in preview which version is leading with zero. You need to install it with below cmdlet.
```
Install-Module -Name Az.AlertsManagement
```

**Comment by dingmeng-xue** [comment]
Hi all, do you have chance to try my suggestion?

**Comment by dingmeng-xue** [comment]
Close this issue due to no further update. Please let us know if you need further help.
