### ISSUE TITLE
Get-AzNetworkServiceTag does not return IP ranges for Azure DevOps MS-Hosted Agents

### ISSUE THREAD

**Issue by theonesuperdave** [Azure/azure-powershell#12312]
## Description
I'm using `Get-AzNetworkServiceTag` to get the list of well-known IP ranges for **Azure DevOps agents** rather than downloading the "[weekly file](https://www.microsoft.com/en-us/download/confirmation.aspx?id=56519)" manually. The module is full of valid content, but is **missing the IP addresses coming from `Azure DevOps MS-Hosted agents`**. I have tried several times, but each time **the address is not from one retrieved from `Get-AzNetworkServiceTag`**.

#### IP at the time of this writing
AzDO Agent Public IP Address: 168.61.181.147

#### Previously observed IP Addresses
23.101.122.52
23.99.201.43
40.77.107.72
23.99.183.158
52.173.141.223

## Steps to reproduce

```
(Get-AzNetworkServiceTag -Location northcentralus).Values).Properties.AddressPrefixes
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.14393.3471
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.3471
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```
Script     3.0.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificat...
```

## Debug output

Very Large Data set. No relevant details observed.

```
DEBUG: AzureQoSEvent: CommandName - Get-AzNetworkServiceTag; IsSuccess - True; Duration - 00:00:03.4133132;
DEBUG: Finish sending metric.
DEBUG: 12:59:14 PM - GetAzureNetworkServiceTagCommand end processing.
```

## Error output

```
Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                 Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.8.0\Az.Accounts.psm1:68 char:17
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                 Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.8.0\Az.Accounts.psm1:68 char:17
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                 Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\1.8.0\Az.Accounts.psm1:68 char:17
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.1761527;
DEBUG: Finish sending metric.
DEBUG: 1:01:15 PM - ResolveError end processing.
```

**Comment by theonesuperdave** [comment]
Just noting that I did not find the following `Azure DevOps` agent IP in the "weekly file" either.

AzDO Agent Public IP Address: `168.61.181.147`

**Comment by dingmeng-xue** [comment]
@theonesuperdave , could share the Absolute Uri in the debug message and its response? It will help service team to look into it.

**Comment by theonesuperdave** [comment]
Thank you. Here is the `AbsoluteUri` as requested:

```
Absolute Uri:
https://management.azure.com/subscriptions/e8e8df1e-3282-4598-b527-d9f200188398/providers/Microsoft.Network/locations/northcentr
alus/serviceTags?api-version=2020-04-01
```

In trying other `-Location` values, `northcentralus` is the only one that has values; the others provide an "empty" response.

**Comment by theonesuperdave** [comment]
@dingmeng-xue - Any update on this one?

**Comment by dingmeng-xue** [comment]
@theonesuperdave , this issue has been added service attention label. Network team will look into it. Ping @aznetsuppgithub

**Comment by allegradomel** [comment]
Hi @theonesuperdave, following up on this - which tag did you expect to see the this IP under?

**Comment by theonesuperdave** [comment]
Hello @allegradomel, according to the docs I read, it looks like `AzDO` agents can come from anywhere in the geography for my Azure subscription, so I would think it would be something like, "AzureCloud.northcentralus" or similar. It has been forever since I looked at this, but the end result was the IP range was not found using IP address displayed from the `AzDO` cloud-hosted agent.

**Comment by allegradomel** [comment]
Hi @theonesuperdave, thanks for responding. Let me talk to a contact from the DevOps team and get back to you

**Comment by allegradomel** [comment]
@justhchung from DevOps team is looking into this currently

**Comment by justhchung** [comment]
@theonesuperdave, Azure DevOps Mac IP ranges are not included in the Azure IPs above. Could these be Mac IPs?

**Comment by theonesuperdave** [comment]
@justhchung - the release currently targets MS-Hosted Agents using the `vs2017-win2016` "Agent Specifiation" so these should all be Windows OS.

**Comment by justhchung** [comment]
@theonesuperdave thank you for confirming. We will further investigate.

**Comment by arvindabes** [comment]
Hi @justhchung @aznetsuppgithub This is not working yet . 

Get-AzNetworkServiceTag does not return any IP ranges, its empty. Please check this.

**Comment by eriktacknoaignite** [comment]
The service tags returned from this call is incorrect. It will include a global list in _Values.AzureDevOps_, but this list does not include azure hosted agents. Here is the list as of today (I used westeurope as reference):
20.37.158.0/23
20.37.194.0/24
20.39.13.0/26
20.41.6.0/23
20.41.194.0/24
20.42.5.0/24
20.42.134.0/23
20.42.226.0/24
20.45.196.64/26
20.91.148.128/25
20.125.155.0/24
20.166.41.0/24
20.189.107.0/24
20.195.68.0/24
20.204.197.192/26
20.233.130.0/25
40.74.28.0/23
40.80.187.0/24
40.82.252.0/24
40.119.10.0/24
51.104.26.0/24
52.150.138.0/24
52.228.82.0/24
191.235.226.0/24
2603:1030:a07:15::3d2/127
2603:1030:a07:15::3d8/125

Two runs I did today in a job in our devops environment located in west europe (which shouldnt matter as the list above is supposed to be global) had these IP addresses:
4.212.8.40
108.142.227.114
