### ISSUE TITLE
Connect-AzAccount in AA throws missing mandatory parameters: ServicePrincipal Tenant

### ISSUE THREAD

**Issue by igomat** [Azure/azure-powershell#12663]
##  Description

The Connect-AzAccount throws: 
"Cannot process command because of one or more missing mandatory parameters: ServicePrincipal Tenant."
after a few times of the cmdlets' execution. The first times with the same pscredential parameter succeed. 

## Steps to reproduce

```powershell
 [pscredential] $Credential ##### supplied from Azure Automation Credentials
$args = @{Credential=$Credential} 
Connect-AzAccount @args 

```

## Environment data

Azure Automation
Get-AzContext before the faulty execution of the Connect-AzAccount returns no Context. 
Disable-AzureRmAlias just before the cmdlet didn’t help
Used only Az cmdlets in the Runbook. 

## Module versions

Az.Accounts returns version 1.9.1 before each time execution of the cmdlet

## Debug output

-Debug provide no more info. 

## Error output

```
Resolve-AzError:

InnerException   : False
Exception        : System.Management.Automation.ParameterBindingException: Cannot process command because of one or 
                   more missing mandatory parameters: ServicePrincipal Tenant.
                      at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                   funcContext, Exception exception)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
Message          : Cannot process command because of one or more missing mandatory parameters: ServicePrincipal Tenant.
StackTrace       :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                   funcContext, Exception exception)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : InvalidArgument: (:) [Connect-AzAccount], ParameterBindingException
InvocationInfo   : System.Management.Automation.InvocationInfo
```

**Comment by igomat** [comment]
Problem solved. The issue was due to imported Az.Profile in old version.
