### ISSUE TITLE
Invoke-AzRestMethod not in Az.Accounts version 2.0.1-preview

### ISSUE THREAD

**Issue by J0F3** [Azure/azure-powershell#13000]
## Description
When Condition Access is configured on the AzureAD Tenant `Connect-AzAccount` does not work when using the stable version (1.9.3) of the Az.Accounts Module. You have to install the 2.0.1 preview version to be able to login. 
See #9427 (and numbers of other issues). 

Now the Problem is that the preview version seems not anymore feature par with the stable version of the module and the `Invoke-AzRestMethod` Cmdlet is missing completely in the preview module.

So please fix that by either (finally) release the new 2.0 version of the Az.Accounts module or by releasing a new preview module which is feature par with the 1.9.3 module.

Thx

## Steps to reproduce

```powershell
Connect-AzAccount
Invoke-AzRestMethod
Invoke-AzRestMethod: The 'Invoke-AzRestMethod' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'
```

## Environment data

Name                           Value
----                           -----
PSVersion                      7.0.3
PSEdition                      Core
GitCommitId                    7.0.3
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.0.1      preview    Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
Script     1.9.3                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave…}
```

## Debug output

N/A

```

```

## Error output

   HistoryId: 2

Message        : The 'Invoke-AzRestMethod' command was found in the module 'Az.Accounts', but the module could not be loaded. For more information, run 'Import-Module Az.Accounts'.
StackTrace     :    at System.Management.Automation.CommandDiscovery.TryModuleAutoDiscovery(String commandName, ExecutionContext context, String originalCommandName, CommandOrigin commandOrigin, SearchResolutionOptions searchResolutionOptions, CommandTypes commandTypes, Exception& lastError)
                    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Invoke-AzRestMethod
Position       : At line:1 char:1
                 + Invoke-AzRestMethod
                 + ~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Assembly with same name is already loaded
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke[T]()
                    at System.Management.Automation.CommandDiscovery.AutoloadSpecifiedModule(String moduleName, ExecutionContext context, SessionStateEntryVisibility visibility, Exception& exception)
Exception      : System.Management.Automation.CmdletInvocationException
InvocationInfo : {}
Line           : Invoke-AzRestMethod
Position       : At line:1 char:1
                 + Invoke-AzRestMethod
                 + ~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Assembly with same name is already loaded
StackTrace     :    at System.Management.Automation.Runspaces.InitialSessionState.Bind_LoadAssemblies(ExecutionContext context)
                    at System.Management.Automation.Runspaces.InitialSessionState.Bind(ExecutionContext context, Boolean updateOnly, PSModuleInfo module, Boolean noClobber, Boolean local, Boolean setLocation)
                    at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo manifestScriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
Exception      : System.IO.FileLoadException
InvocationInfo : {}
Line           : Invoke-AzRestMethod
Position       : At line:1 char:1
                 + Invoke-AzRestMethod
                 + ~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

```

```

**Comment by dingmeng-xue** [comment]
Az.Accounts 2.0.x-preview is preview version for MSAL integration. We implemented Invoke-AzRestMethod after 2.0.x-preview. We didn't backport feature because we will support MSAL in stable version soon within 1 or 2 months, and team is very busy now.

Sorry for this inconvenience.

**Comment by J0F3** [comment]
I can understand that you do not want to backport it. But then please keep in mind that a lot of customers (everywhere where conditional access is in place) have to use the preview version because otherwise the Azure PowerShell does not work at all. Now this means also that all these customers can not use Invoke-AzRestMethod.

Furthermore the preview version is, as you can see now, not a solution for the initial issue (#9427 ) which was now somehow suddenly closed. It is now not even a fully working workaround. 

So how can we sure that the release is now really in 1 or 2 month and the problem get finally fixed? As you can see in the issue that your (Az PowerShell Team) says that for over a year and it is still not fixed/released today! This is not just inconvenient but very annoying... ☹

**Comment by dingmeng-xue** [comment]
@J0F3 , we have released Az.Accounts 2.1.2 recently. This one is included. Sorry for inconvenience.

I'm closing this one. Please contact us if you have further question.

**Comment by J0F3** [comment]
@dingmeng-xue Makes sense. I am happy about the release of the version 2.1.2. Since then the Az PowerShell works fine for me, again. 😊Thanks!
