### ISSUE TITLE
Unable to create SSL/TLS secure channel when deploying from pipelines to Azure Cloud Services.

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/azure-powershell#13035]
## Description
We have couple of inline powershell scripts as part of our Cloud Service deployments that use the Move-AzureDeployment cmdlet to swap.

Since couple of days we are facing the below issue and the pipelines have been working fine for almost a year now.

2020-09-22T08:46:44.6783498Z ##[debug]Exception:
2020-09-22T08:46:44.6853132Z ##[debug]System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
2020-09-22T08:46:44.6874402Z ##[debug]   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2020-09-22T08:46:44.6896129Z ##[debug]   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2020-09-22T08:46:44.6919124Z ##[debug]   --- End of inner exception stack trace ---
2020-09-22T08:46:44.7044705Z ##[debug]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2020-09-22T08:46:44.7046729Z ##[debug]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
2020-09-22T08:46:44.7063955Z ##[debug]   at Microsoft.WindowsAzure.Management.Compute.DeploymentOperationsExtensions.GetBySlot(IDeploymentOperations operations, String serviceName, DeploymentSlot deploymentSlot)
2020-09-22T08:46:44.7088418Z ##[debug]   at Microsoft.WindowsAzure.Commands.ServiceManagement.HostedServices.MoveAzureDeploymentCommand.<>c__DisplayClass6.<GetDeploymentBySlot>b__4() in d:\workspace\powershell-sign\src\ServiceManagement\Compute\Commands.ServiceManagement\HostedServices\MoveAzureDeployment.cs:line 88
2020-09-22T08:46:44.7109061Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.CloudBaseCmdlet`1.InvokeInOperationContext(Action action) in d:\workspace\powershell-sign\src\ServiceManagement\Common\Commands.ServiceManagement.Common\CloudBaseCmdlet.cs:line 224
2020-09-22T08:46:44.7131026Z ##[debug]   at Microsoft.WindowsAzure.Commands.ServiceManagement.HostedServices.MoveAzureDeploymentCommand.GetDeploymentBySlot(String slot) in d:\workspace\powershell-sign\src\ServiceManagement\Compute\Commands.ServiceManagement\HostedServices\MoveAzureDeployment.cs:line 89
2020-09-22T08:46:44.7171067Z ##[debug]   at Microsoft.WindowsAzure.Commands.ServiceManagement.HostedServices.MoveAzureDeploymentCommand.ExecuteCommand() in d:\workspace\powershell-sign\src\ServiceManagement\Compute\Commands.ServiceManagement\HostedServices\MoveAzureDeployment.cs:line 48
2020-09-22T08:46:44.7191814Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by VeryEarly** [comment]
Hi @sourabhkrishna ,
Thanks for reporting this issue.

Hi @nitinjainms can you please take a look?

**Comment by renepronk** [comment]
We're also having this issue when deploying classic Cloud Services. We've been upgraded to Azure DevOps sprint 175 today, so it might be related to that.

Also possibly related: https://stackoverflow.com/questions/63940041/azure-devops-powershell-script-could-not-create-ssl-tls-secure-channel

```
2020-09-24T09:32:12.0200905Z ##[debug]9:32:12 AM - Begin Operation: Get-AzureService
2020-09-24T09:32:13.1781686Z ##[debug]9:32:13 AM - Completed Operation: Get-AzureService
2020-09-24T09:32:14.1426508Z ##[debug]System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
2020-09-24T09:32:14.1463377Z ##[debug]   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2020-09-24T09:32:14.1508293Z ##[debug]   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2020-09-24T09:32:14.1539130Z ##[debug]   --- End of inner exception stack trace ---
2020-09-24T09:32:14.1574959Z ##[debug]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2020-09-24T09:32:14.1640534Z ##[debug]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
2020-09-24T09:32:14.1687623Z ##[debug]   at Microsoft.WindowsAzure.Management.Compute.HostedServiceOperationsExtensions.Get(IHostedServiceOperations operations, String serviceName)
2020-09-24T09:32:14.1815088Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.ServiceManagementBaseCmdlet.ExecuteClientActionNewSM[TResult](Object input, String operationDescription, Func`1 action, Func`3 contextFactory) in d:\workspace\powershell-sign\src\ServiceManagement\Services\Commands.Utilities\Common\ServiceManagementBaseCmdlet.cs:line 152

```

**Comment by mschmeller** [comment]
We're also having this issue when deploying classic Cloud Services. We use TFS 2018. We can reproduce it by execute a powershell script from command line.

**Comment by wyunchi-ms** [comment]
Hi @mschmeller , this script works right before and you didn't change anything, right?

**Comment by mschmeller** [comment]
> 
> 
> Hi @mschmeller , this script works right before and you didn't change anything, right?

Yes, thats right. It stopped working "over night". At first I thought it was due to an Microsoft patch day update.
Last successul run was on 9th September 2020. First definitily broken run was 15th September 2020, 12:01 am

**Comment by BredStik** [comment]
​We've been having issues using the management api from one cloud service to another lately.  Turns out our deployment configuration was set to use the latest windows image and the latest one released a few days ago seems to cause the issue.  We forced using the previous windows image version and it worked flawlessly!  Your problem might be related to something similar.

**Comment by mschmeller** [comment]
Hello, 
there has been no status change for 5 days. 
Is the issue being worked on? 
We're still getting the error message:

Starting: Swap Cloud Service
Task : Azure PowerShell
Description : Run a PowerShell script within an Azure environment
Version : 2.0.2

Import-Module -Name C:\Program Files\WindowsPowerShell\Modules\Azure\5.1.2\Azure.psd1 -Global
Set-AzureSubscription -SubscriptionName Development -SubscriptionId ******** -Certificate ******** -Environment AzureCloud
Select-AzureSubscription -SubscriptionId ********
...
DEBUG: 11:54:01 - GetAzureDeploymentCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 11:54:09 - using account id '342410BAF64B417126EC43D2E017B6E63F74A29C'...
VERBOSE: 11:54:10 - Begin Operation: Get-AzureDeployment
DEBUG: ============================ HTTP REQUEST ============================
HTTP Method:
GET
Absolute Uri:
https://management.core.windows.net/72e1cd4c-f043-4a01-b96a-a1c5017af458/services/hostedservices/x-zwo/deploymentslots/Staging
Headers:
x-ms-version                  : 2017-01-01
Body:
VERBOSE: 11:54:15 - Completed Operation: Get-AzureDeployment
DEBUG: AzureQoSEvent: CommandName - Get-AzureDeployment; IsSuccess - False; Duration - 00:00:13.8689949; Exception - System.Net.Http.HttpRequestException: An error occurr
ed while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.WindowsAzure.Management.Compute.DeploymentOperationsExtensions.GetBySlot(IDeploymentOperations operations, String serviceName, DeploymentSlot deploymentSl
ot)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.ServiceManagementBaseCmdlet.ExecuteClientActionNewSM[TResult](Object input, String operationDescription, Func`1 act
ion, Func`3 contextFactory);
DEBUG: Finish sending metric.
DEBUG: 11:54:16 - GetAzureDeploymentCommand end processing.

**Comment by dingmeng-xue** [comment]
Please reference to #13117

**Comment by dingmeng-xue** [comment]
@sourabhkrishna , let's use #13117 to track this issue. We will contact AzureRM and Portal team to understand what happened.
