### ISSUE TITLE
WebApp:Publish-AzWebapp doesn't handle relative paths properly

### ISSUE THREAD

**Issue by arnoschuring** [Azure/azure-powershell#13158]
## Description
Publish-AzWebapp seems to interpret relative paths as being relative to the user's home dir, rather than the current working directory.

## Steps to reproduce

```powershell
PS D:\arno\do-pipeline-templates\scripts\azure> Publish-AzWebapp -Force -ResourceGroupName $rgName -Name $fappName -ArchivePath ..\webhook.zip
Publish-AzWebapp : Could not find file 'C:\Users\webhook.zip'.
At line:1 char:1
+ Publish-AzWebapp -Force -ResourceGroupName $rgName -Name $fappName -A ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzWebApp], FileNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet

PS D:\arno\do-pipeline-templates\scripts\azure> Get-Item ..\webhook.zip

    Directory: D:\arno\do-pipeline-templates\scripts

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        07/10/2020     12:02        5542304 webhook.zip
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
Name             Version
----             -------
Az.Accounts      1.9.3
Az.Accounts      1.9.0
Az.Accounts      1.7.1
Az.Accounts      1.6.3
Az.Accounts      1.5.3
Az.Accounts      1.5.2
Az.ApiManagement 2.1.0
Az.Automation    1.3.6
Az.Automation    1.3.3
Az.DataFactory   1.8.2
Az.DataFactory   1.3.0
Az.DataFactory   1.1.1
Az.KeyVault      2.0.0
Az.KeyVault      1.5.0
Az.Monitor       2.0.1
Az.Monitor       1.3.0
Az.Monitor       1.2.1
Az.Resources     2.2.0
Az.Resources     1.7.0
Az.Resources     1.5.0
Az.ServiceBus    1.4.1
Az.Sql           2.8.0
Az.Sql           1.14.2
Az.Sql           1.12.0
Az.Websites      1.11.0
Az.Websites      1.10.0
Az.Websites      1.6.0
```

## Debug output

I'm omitting the debug output because this is a local error, and the local trace is the same as what's in the error log.

## Error output

```
   HistoryId: 20


Message        : Could not find file 'C:\Users\webhook.zip'.
StackTrace     :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean
                 useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs,
                 String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
                    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet.<>c__DisplayClass13_0.
                 <ExecuteCmdlet>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force,
                 String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
                    at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.ConfirmAction(Boolean force,
                 String continueMessage, String processMessage, String target, Action action)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Publish-AzWebApp}
Line           : Publish-AzWebapp -Force -ResourceGroupName $rgName -Name $fappName -ArchivePath ..\webhook.zip
Position       : At line:1 char:1
                 + Publish-AzWebapp -Force -ResourceGroupName $rgName -Name $fappName -A ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 20
```

**Comment by Kotasudhakarreddy** [comment]
@arnoschuring - relative path points to the location where the `Az.Websites ` is installed. Preferred way of using the `-ArchivePath`  is to provide full path rather than relative path. if we want to use relative path then our **.zip** file should be located at the `Az.Websites` module location.

**Comment by arnoschuring** [comment]
> relative path points to the location where the Az.Websites is installed

I don't think this is accurate, as the used path isn't where the module is installed:

```
> Get-Module az.websites -ListAvailable | select Name,Version,Path

Name        Version Path
----        ------- ----
Az.Websites 1.11.0  C:\Program Files\WindowsPowerShell\Modules\Az.Websites\1.11.0\Az.Websites.psd1
Az.Websites 1.10.0  C:\Program Files\WindowsPowerShell\Modules\Az.Websites\1.10.0\Az.Websites.psd1
Az.Websites 1.6.0   C:\Program Files\WindowsPowerShell\Modules\Az.Websites\1.6.0\Az.Websites.psd1
```

**Comment by cpdohert** [comment]
Still occurs in PowerShell 7.2.1 and Az.Websites 2.8.3

**Comment by Kotasudhakarreddy** [comment]
@mmaitre314 here `-ArchivePath` refers to the path of the archive file.  please refer to the [documentation](https://docs.microsoft.com/en-us/powershell/module/az.websites/publish-azwebapp?view=azps-7.3.2) for more details.

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.
