### ISSUE TITLE
Get-AzDelegation returns an error when null

### ISSUE THREAD

**Issue by anwather** [Azure/azure-powershell#13180]
```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-AzDelegation                                   3.3.0      Az.Network
```

When I run the command as below an error is returned (the delegation does not exist) :-
```
Get-AzDelegation -Name nmeFunction -Subnet $subnet
Get-AzDelegation : Sequence contains no matching element
At line:1 char:1
+ Get-AzDelegation -Name nmeFunction -Subnet $subnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzDelegation], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureDelegation
```
Would it be better if ```$null``` is returned instead when an object doesn't exist?

**Comment by dingmeng-xue** [comment]
@anwather , thanks for reporting. The return message is not good. Could you share debug message via setting `$DebugPreference="Continue"`?

**Comment by anwather** [comment]
```
DEBUG: 1:54:38 PM - GetAzureDelegation begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 1:54:38 PM - using account id 'xxxxxxxx'...
Get-AzDelegation : Sequence contains no matching element
At line:1 char:1
+ Get-AzDelegation -Name nmeFunction -Subnet $subnet
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzDelegation], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureDelegation

DEBUG: AzureQoSEvent: CommandName - Get-AzDelegation; IsSuccess - False; Duration - 00:00:00.4209335;; Exception - System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Azure.Commands.Network.GetAzureDelegation.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:54:40 PM - GetAzureDelegation end processing.
```
