### ISSUE TITLE
Get-AzDataFactoryV2Trigger command failed to serialize result

### ISSUE THREAD

**Issue by nivohavi** [Azure/azure-powershell#13319]
Hi,

It looks like there is an issue with Get-**Az**DataFactoryV2Trigger command:

`Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.DataFactory.TriggersOperations.<ListByFactoryWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
                    at Microsoft.Azure.Management.DataFactory.TriggersOperationsExtensions.<ListByFactoryAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
                    at Microsoft.Azure.Management.DataFactory.TriggersOperationsExtensions.ListByFactory(ITriggersOperations operations, String resourceGroupName, String
                 factoryName)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.ListTriggers(AdfEntityFilterOptions filterOptions)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.FilterPSTriggers(AdfEntityFilterOptions filterOptions)
                    at Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryTriggerCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzDataFactoryV2Trigger}
Line           : Get-AzDataFactoryV2Trigger -ResourceGroupName "Cosmos-ADF-RG" -DataFactoryName "detection-cosmos-adf-prd"
Position       : At line:1 char:1
                 + Get-AzDataFactoryV2Trigger -ResourceGroupName "Cosmos-ADF-RG" -DataFa ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8

Message        : Could not convert string to integer: if(equals(variables('currentEnvSettings'), 'Stg'), 2, 6. Path 'typeProperties.recurrence.interval', line 1, position 7007.
StackTrace     :    at Newtonsoft.Json.JsonReader.ReadInt32String(String s)
                    at Newtonsoft.Json.JsonReader.ReadAsInt32()
                    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty
                 member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member,
                 JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
                    at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer
                 serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object
                 existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter,
                 JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty
                 member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member,
                 JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty
                 containerProperty, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member,
                 Object existingValue, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter,
                 JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty
                 member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member,
                 JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.DataFactory.TriggersOperations.<ListByFactoryWithHttpMessagesAsync>d__5.MoveNext()
Exception      : Newtonsoft.Json.JsonReaderException
InvocationInfo : {Get-AzDataFactoryV2Trigger}
Line           : Get-AzDataFactoryV2Trigger -ResourceGroupName "Cosmos-ADF-RG" -DataFactoryName "detection-cosmos-adf-prd"
Position       : At line:1 char:1
                 + Get-AzDataFactoryV2Trigger -ResourceGroupName "Cosmos-ADF-RG" -DataFa ...`

**Comment by dingmeng-xue** [comment]
Data Factory team, please help to look into this question.

**Comment by nivohavi** [comment]
issue persist also when using "Get-**AzureRm**DataFactoryV2Trigger"

**Comment by shawnxzq** [comment]
@nivohavi This is usually some of the triggers include some invalid properties, could you please try to get the triggers one by one, and share the json code of the problematic one? you can get the json code for the problematic one in UX, thanks a lot!

**Comment by shawnxzq** [comment]
@nivohavi any update on this? From the error, it is caused by the property "typeProperties.recurrence.interval", it has a string value, while it is required to be an integer value. If possible, please check what the value is used at moment, thanks! 

@LijuanZ Not sure whether parameterize "typeProperties.recurrence.interval" caused the issue, if so, please consider change the type from int to object, thanks!

**Comment by LijuanZ** [comment]
@shawnxzq Parameterization for "typeProperties.recurrence.interval" is not supported so we cannot change the type to object. It's required to be an int

**Comment by shawnxzq** [comment]
@nivohavi As @LijuanZ mentioned, it is by design, we don't support parameterization for "interval", thanks!
