### ISSUE TITLE
Az.Accounts 2.1.2 fails to import in Azure Function App

### ISSUE THREAD

**Issue by JohnRoos** [Azure/azure-powershell#13444]
## Description

Version 2.1.2 of Az.Accounts cannot be imported in an Azure Function App when using WEBSITE_RUN_FROM_PACKAGE=1.
It seems like the import is trying to create a folder called .IdentityService in the wwwroot, which is read-only.

Since Az is using MinimumVersion when importing Az.Accounts, this affects both Az 5 and 4 (only verified 4.8.0).

## Steps to reproduce

Deploy a function app from VSCode where you put the module in the requirements file.

```powershell
#requirements.ps1
@{
    'Az.Accounts' = '2.1.2'
}
```
Import the module in the profile.

```powershell
#profile.ps1
Write-Host "Importing Az.Accounts"
Import-Module Az.Accounts -Verbose
```

Trigger any function so that the profile will load.

The following error is produced:

```text
2020-11-06T09:39:53.166 [Information] INFORMATION: Importing Az.Accounts
2020-11-06T09:39:59.245 [Error] ERROR: Could not find file 'C:\home\site\wwwroot\.IdentityService'.

Exception             : 
    Type       : System.IO.FileNotFoundException
    Message    : Could not find file 'C:\home\site\wwwroot\.IdentityService'.
    FileName   : C:\home\site\wwwroot\.IdentityService
    TargetSite : 
        Name          : CreateDirectory
        DeclaringType : System.IO.FileSystem, System.IO.FileSystem, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        MemberType    : Method
        Module        : System.IO.FileSystem.dll
    StackTrace : 
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Microsoft.Identity.Client.Extensions.Msal.CrossPlatLock..ctor(String lockfilePath, Int32 lockFileRetryDelay, Int32 lockFileRetryCount)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateCrossPlatLock(StorageCreationProperties storageCreationProperties)
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.CreateAsync(StorageCreationProperties storageCreationProperties, TraceSource logger)
   at Microsoft.Azure.Commands.Common.Authentication.MsalCacheHelperProvider.GetCacheHelper()
   at Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheProvider.CreateCacheHelper()
   at Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheProvider.GetCacheHelper()
   at Microsoft.Azure.Commands.Common.Authentication.SharedTokenCacheProvider.SupportCachePersistence(String& message)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.OnImport()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.ExecuteModuleInitializer(Assembly assembly, IEnumerable`1 assemblyTypes)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzeModuleAssemblyWithReflection(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, String helpFile, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(String fileName, String moduleBase, String prefix, SessionState ss, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
    Source     : System.IO.FileSystem
    HResult    : -2147024894
```

## Environment data

Function App runtime version 3. 

From Kudu console:

```
Name                           Value                                           
----                           -----                                           
PSVersion                      5.1.14393.3866                                  
PSEdition                      Desktop                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                         
BuildVersion                   10.0.14393.3866                                 
CLRVersion                     4.0.30319.42000                                 
WSManStackVersion              3.0                                             
PSRemotingProtocolVersion      2.3                                             
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
PS C:\home> Get-Module  -ListAvailable
Get-Module  -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationVali...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get...
Script     3.4.0      Pester                              {Describe, Context...
Script     1.0.0.1    PowerShellGet                       {Install-Module, F...
Script     1.2        PSReadline                          {Get-PSReadlineKey...


    Directory: C:\Program Files (x86)\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationVali...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get...
Script     3.4.0      Pester                              {Describe, Context...
Script     1.0.0.1    PowerShellGet                       {Install-Module, F...


    Directory: C:\windows\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Manifest   2.0.0.0    AppLocker                           {Get-AppLockerFile...
Manifest   1.0.0.0    AppvClient                          {Add-AppvClientCon...
Manifest   2.0.0.0    Appx                                {Add-AppxPackage, ...
Manifest   2.0.0.0    BitsTransfer                        {Add-BitsFile, Com...
Manifest   1.0.0.0    BranchCache                         {Add-BCDataCacheEx...
Manifest   1.0.0.0    CimCmdlets                          {Get-CimAssociated...
Manifest   1.0.0.0    DirectAccessClientComponents        {Disable-DAManualE...
Script     3.0        Dism                                {Add-AppxProvision...
Manifest   1.0.0.0    DnsClient                           {Resolve-DnsName, ...
Manifest   1.0.0.0    EventTracingManagement              {New-EtwTraceSessi...
Manifest   2.0.0.0    FileServerResourceManager           {New-FSRMAction, G...
Script     1.0.0.0    IISAdministration                   {Get-IISAppPool, S...
Manifest   2.0.0.0    International                       {Get-WinDefaultInp...
Manifest   1.0.0.0    iSCSI                               {Get-IscsiTargetPo...
Manifest   2.0.0.0    IscsiTarget                         {Add-ClusteriSCSIT...
Script     1.0.0.0    ISE                                 {New-IseSnippet, I...
Manifest   1.0.0.0    Kds                                 {Add-KdsRootKey, G...
Manifest   1.0.1.0    Microsoft.PowerShell.Archive        {Compress-Archive,...
Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics    {Get-WinEvent, Get...
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript,...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clea...
Script     1.0        Microsoft.PowerShell.ODataUtils     Export-ODataEndpoi...
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {Get-Acl, Set-Acl,...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Format-List, Form...
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Disable-WSManCred...
Manifest   1.0.0.0    MsDtc                               {New-DtcDiagnostic...
Manifest   2.0.0.0    NetAdapter                          {Disable-NetAdapte...
Manifest   1.0.0.0    NetConnection                       {Get-NetConnection...
Manifest   1.0.0.0    NetEventPacketCapture               {New-NetEventSessi...
Manifest   2.0.0.0    NetLbfo                             {Add-NetLbfoTeamMe...
Manifest   1.0.0.0    NetNat                              {Get-NetNat, Get-N...
Manifest   2.0.0.0    NetQos                              {Get-NetQosPolicy,...
Manifest   2.0.0.0    NetSecurity                         {Get-DAPolicyChang...
Manifest   1.0.0.0    NetSwitchTeam                       {New-NetSwitchTeam...
Manifest   1.0.0.0    NetTCPIP                            {Get-NetIPAddress,...
Manifest   1.0.0.0    NetworkConnectivityStatus           {Get-DAConnectionS...
Manifest   1.0.0.0    NetworkTransition                   {Add-NetIPHttpsCer...
Manifest   1.0.0.0    PKI                                 {Add-CertificateEn...
Manifest   1.0.0.0    PnpDevice                           {Get-PnpDevice, Ge...
Manifest   1.1        PrintManagement                     {Add-Printer, Add-...
Manifest   1.1        PSDesiredStateConfiguration         {Set-DscLocalConfi...
Script     1.0.0.0    PSDiagnostics                       {Disable-PSTrace, ...
Binary     1.1.0.0    PSScheduledJob                      {New-JobTrigger, A...
Manifest   1.0.0.0    ScheduledTasks                      {Get-ScheduledTask...
Manifest   2.0.0.0    SecureBoot                          {Confirm-SecureBoo...
Manifest   1.0.0.0    SecurityCmdlets                     {Backup-SecurityPo...
Manifest   2.0.0.0    SmbShare                            {Get-SmbShare, Rem...
Manifest   2.0.0.0    Storage                             {Add-InitiatorIdTo...
Manifest   2.0.0.0    TLS                                 {New-TlsSessionTic...
Manifest   1.0.0.0    TroubleshootingPack                 {Get-Troubleshooti...
Manifest   2.0.0.0    TrustedPlatformModule               {Get-Tpm, Initiali...
Binary     2.1.639.0  UEV                                 {Clear-UevConfigur...
Manifest   2.0.0.0    VpnClient                           {Add-VpnConnection...
Manifest   1.0.0.0    Wdac                                {Get-OdbcDriver, S...
Manifest   1.0.0.0    WebAdministration                   {Start-WebCommitDe...
Manifest   2.0.0.0    Whea                                {Get-WheaMemoryPol...
Manifest   1.0.0.0    WindowsDeveloperLicense             {Get-WindowsDevelo...
Script     1.0        WindowsErrorReporting               {Enable-WindowsErr...
Manifest   1.0.0.0    WindowsUpdate                       Get-WindowsUpdateLog 


    Directory: C:\Program Files (x86)\Microsoft 
    SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Manifest   1.1.0      AzureRM.ApiManagement               {Add-AzureRmApiMan...
Manifest   1.0.8      AzureRM.Automation                  {Get-AzureRmAutoma...
Binary     0.9.5      AzureRM.AzureStackAdmin             {Get-AzureRMManage...
Manifest   0.9.6      AzureRM.AzureStackStorage           {Add-ACSFarm, Get-...
Manifest   1.0.8      AzureRM.Backup                      {Backup-AzureRmBac...
Manifest   1.1.0      AzureRM.Batch                       {Remove-AzureRmBat...
Manifest   1.0.2      AzureRM.Cdn                         {Get-AzureRmCdnCus...
Manifest   1.3.0      AzureRM.Compute                     {Remove-AzureRmAva...
Manifest   1.0.8      AzureRM.DataFactories               {Remove-AzureRmDat...
Manifest   1.1.0      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLa...
Manifest   1.0.8      AzureRM.DataLakeStore               {Add-AzureRmDataLa...
Manifest   1.0.8      AzureRM.Dns                         {Get-AzureRmDnsRec...
Manifest   1.1.0      AzureRM.HDInsight                   {Get-AzureRmHDInsi...
Manifest   1.0.8      AzureRM.Insights                    {Add-AzureRmMetric...
Manifest   1.1.7      AzureRM.KeyVault                    {Get-AzureRmKeyVau...
Manifest   1.0.4      AzureRM.LogicApp                    {Stop-AzureRmLogic...
Manifest   1.0.9      AzureRM.Network                     {Add-AzureRmApplic...
Manifest   1.0.8      AzureRM.NotificationHubs            {Get-AzureRmNotifi...
Manifest   1.0.8      AzureRM.OperationalInsights         {Get-AzureRmOperat...
Manifest   1.0.8      AzureRM.Profile                     {Enable-AzureRmDat...
Manifest   1.1.0      AzureRM.RecoveryServices            {Get-AzureRmRecove...
Manifest   1.0.0      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRec...
Manifest   1.1.6      AzureRM.RedisCache                  {Remove-AzureRmRed...
Manifest   1.1.0      AzureRM.Resources                   {Get-AzureRmADAppl...
Manifest   1.1.7      AzureRM.SiteRecovery                {Stop-AzureRmSiteR...
Manifest   1.0.8      AzureRM.Sql                         {Get-AzureRmSqlDat...
Manifest   1.1.0      AzureRM.Storage                     {Get-AzureRmStorag...
Manifest   1.0.8      AzureRM.StreamAnalytics             {Get-AzureRmStream...
Manifest   1.0.8      AzureRM.Tags                        {Remove-AzureRmTag...
Manifest   1.0.8      AzureRM.TrafficManager              {Disable-AzureRmTr...
Manifest   1.0.8      AzureRM.UsageAggregates             Get-UsageAggregates  
Manifest   1.1.0      AzureRM.Websites                    {Get-AzureRmAppSer...


    Directory: C:\Program Files (x86)\Microsoft 
    SDKs\Azure\PowerShell\ServiceManagement


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Manifest   1.4.0      Azure                               {Get-AzureAutomati...


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Manifest   1.1.2      Azure.Storage                       {Get-AzureStorageB...


    Directory: C:\Program Files\Microsoft Message Analyzer\PowerShell


ModuleType Version    Name                                ExportedCommands     
---------- -------    ----                                ----------------     
Script     1.1.0.0    PEF                                 {Invoke-PefCustomA...
```

**Comment by JohnRoos** [comment]
I noticed that this problem is mentioned in this comment: https://github.com/Azure/azure-powershell/issues/13376#issuecomment-720424281

Feel free to close this issue if this is being resolved in that issue.

**Comment by dingmeng-xue** [comment]
Thanks. Close this one as duplicated with #13376
