### ISSUE TITLE
Failed to login if specifying tenant domain name instead of tenant id

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-powershell#13505]
## Description
This should be legacy issue, could reproduce on Az.Accounts 1.9.5

If there're more than one tenants associated with your account, you may get error if using tenant name instead of tenant id.

## Steps to reproduce

```powershell
Connect-AzAccount -Tenant AzureSDKTeam.onmicrosoft.com -Subscription AzureSDKTest
```

## Environment data

```

```

## Module versions

```powershell

```

## Debug output

```

```

## Error output

DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:26.7545652;; Exception -
System.AggregateException: One or more errors occurred. ---> System.Management.Automation.PSInvalidOperationException: The
provided account ***@microsoft.com does not have access to subscription name "AzureSDKTest". Please try logging in with
different credentials or a different subscription name.
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment
environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation,
Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass107_1.<ExecuteCmdlet>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass107_0.<ExecuteCmdlet>b__0(AzureRmProfile
localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
---> (Inner Exception #0) System.Management.Automation.PSInvalidOperationException: The provided account eriwan@microsoft.com
does not have access to subscription name "AzureSDKTest". Please try logging in with different credentials or a different
subscription name.
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment
environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation,
Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass107_1.<ExecuteCmdlet>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

```

**Comment by erich-wang** [comment]
Close as it is duplicate with #13400
