### ISSUE TITLE
Unable to login with Connect-AzAccount

### ISSUE THREAD

**Issue by mcurko** [Azure/azure-powershell#13517]
I installed the latest Az modules, and can't log in to Azure.

(this issue is in reference to https://github.com/Azure/azure-powershell/issues/13419)

```
PS C:\> Connect-AzAccount
DEBUG: Sought all Az modules and got latest version 0.0.0
DEBUG: 13:57:48 - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 13:57:48 - Autosave setting from startup session: 'CurrentUser'
DEBUG: 13:57:48 - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 13:57:48 - Using Autosave scope 'CurrentUser'
DEBUG: InteractiveBrowserCredential.Authenticate invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: Request [9c587542-5b3a-40c8-853e-1c5bcbafb640] GET
https://login.microsoftonline.com/common/discovery/instance?api-version=REDACTED&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:9c587542-5b3a-40c8-853e-1c5bcbafb640
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0-beta.1 (.NET Framework 4.8.4250.0; Microsoft Windows 10.0.18363 )
client assembly: Azure.Identity
DEBUG: Response [9c587542-5b3a-40c8-853e-1c5bcbafb640] 200 OK (00.4s)
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Allow-Methods:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
Cache-Control:max-age=86400, private
Content-Type:application/json; charset=utf-8
P3P:REDACTED
Set-Cookie:REDACTED
Date:Mon, 16 Nov 2020 12:57:48 GMT
Content-Length:957
DEBUG: Request [44ebf4a0-368c-4b7a-9374-e8632f8b222e] POST
https://login.microsoftonline.com/organizations/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:44ebf4a0-368c-4b7a-9374-e8632f8b222e
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0-beta.1 (.NET Framework 4.8.4250.0; Microsoft Windows 10.0.18363 )
client assembly: Azure.Identity
DEBUG: Response [44ebf4a0-368c-4b7a-9374-e8632f8b222e] 200 OK (00.4s)
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Content-Length:4836
Cache-Control:no-store, no-cache
Content-Type:application/json; charset=utf-8
Expires:-1
P3P:REDACTED
Set-Cookie:REDACTED
Date:Mon, 16 Nov 2020 12:57:53 GMT
DEBUG: InteractiveBrowserCredential.Authenticate succeeded. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:  ExpiresOn: 2020-11-16T13:57:52.0000000+00:00
DEBUG: InteractiveBrowserCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: InteractiveBrowserCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:  ExpiresOn: 2020-11-16T13:57:52.0000000+00:00
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/tenants?api-version=2019-06-01

Headers:
x-ms-client-request-id        : 11c5cf1c-c97a-42a2-9231-ca8a5bd44501
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-tenant-reads: 11999
x-ms-request-id               : d1f3206d-7eda-42e0-8151-575246b7d144
x-ms-correlation-request-id   : d1f3206d-7eda-42e0-8151-575246b7d144
x-ms-routing-request-id       : SWITZERLANDNORTH:20201116T125754Z:d1f3206d-7eda-42e0-8151-575246b7d144
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 16 Nov 2020 12:57:53 GMT

Body:
{
  "value": [
    {
      "id": "/tenants/..................................................",
      "tenantId": "..................................................",
      "countryCode": "HR",
      "displayName": "Default Directory",
      "domains": [
        "REDACTED.onmicrosoft.com",
        "REDACTED.mail.onmicrosoft.com",
        "REDACTED.hr"
      ],
      "tenantCategory": "Home"
    }
  ]
}

DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken was unable to retrieve an access token. Scopes: [
https://management.core.windows.net//.default ] ParentRequestId:  Exception:
Azure.Identity.CredentialUnavailableException (0x80131500): SharedTokenCacheCredential authentication unavailable. No
account matching the specified username: markocurko@yahoo.com tenantId: .................................................. was found
in the cache.
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken was unable to retrieve an access token. Scopes: [
https://management.core.windows.net//.default ] ParentRequestId:  Exception:
Azure.Identity.CredentialUnavailableException (0x80131500): SharedTokenCacheCredential authentication unavailable. No
account matching the specified username: markocurko@yahoo.com tenantId: .................................................. was found
in the cache.
WARNING: Unable to acquire token for tenant '..................................................'
Connect-AzAccount : The default context can no longer be found; please run 'Get-AzContext -ListAvailable' to see all av
ailable contexts, 'Select-AzContext' to select a new default context, or 'Connect-AzAccount' to login with a new accoun
t.
At line:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:06.9222777;; Exception -
System.Management.Automation.PSInvalidOperationException: The default context can no longer be found; please run
'Get-AzContext -ListAvailable' to see all available contexts, 'Select-AzContext' to select a new default context, or
'Connect-AzAccount' to login with a new account.
   at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.get_DefaultContext()
   at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.TrySetDefaultContext(IAzureContext context)
   at
Microsoft.Azure.Commands.Common.Authentication.ResourceManager.AzureRmAutosaveProfile.TrySetDefaultContext(IAzureContex
t context)
   at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.AzureRmAutosaveProfile.TrySetDefaultContext(String
 name, IAzureContext context)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment
environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean
skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass106_1.<ExecuteCmdlet>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass106_0.<ExecuteCmdlet>b__0(AzureRmProfile
 localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3
setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 13:57:56 - ConnectAzureRmAccountCommand end processing.
```

**Comment by erich-wang** [comment]
@mcurko , could you please first run `Clear-AzContext` and try `Connect-AzAccount`?

If the issue remains, please manually delete files .Azure\AzureRmContext.json and .Azure\AzureRmContextSettings.json under your user profile folder, normally your profile folder would be:

Windows: c:\users\yourname\
Linux: /home/yourname/

**Comment by mcurko** [comment]
After Clear-AzContext it worked. Very interesting, I haven't changed anything and now it workes.

**Comment by erich-wang** [comment]
One guess is token cache is broken somehow, we'll investigate if we could reproduce it.

**Comment by dingmeng-xue** [comment]
I'm closing this issue. @mcurko , please contact us if you have further asks.
