### ISSUE TITLE
Get-AzAccessToken fails when specifying resource url for ARM

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#13527]
## Description & Steps to reproduce

Using Az.Accounts v2.2.0.

```Get-AzAccessToken``` gives me a access token to resource ```https://management.azure.com/```, no problem. I decoded the access token from base64 to see the resource.

```Get-AzAccessToken -ResourceUrl 'https://management.azure.com/'``` however fails.

```powershell
Get-AzAccessToken : Cannot retrieve access token for resource 'https://management.azure.com';. Please ensure that you have provided the appropriate access tokens when using access token login.
At line:1 char:1
+ Get-AzAccessToken -ResourceUrl 'https://management.azure.com'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAccessToken], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.GetAzureRmAccessTokenCommand
```

Which is a bit odd?

## Environment data

```powershell
Name                           Value                                                                                                                                                            
----                           -----                                                                                                                                                            
PSVersion                      5.1.19041.610                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                          
BuildVersion                   10.0.19041.610                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                  
WSManStackVersion              3.0                                                                                                                                                              
PSRemotingProtocolVersion      2.3                                                                                                                                                              
SerializationVersion           1.1.0.1                                                                                                                                                          
```

## Module versions

```powershell
ModuleType Version   Name                           
---------- -------   ----                           
    Script 2.2.0     Az.Accounts                    
    Script 1.4.0     Az.Automation                  
    Script 2.0.0     Az.ManagedServices             
    Script 3.0.1     Az.Resources                   
    Binary 2.0.2.118 AzureAD                        
    Script 1.0.0.0   ISE                            
  Manifest 3.1.0.0   Microsoft.PowerShell.Management
  Manifest 3.0.0.0   Microsoft.PowerShell.Security  
  Manifest 3.1.0.0   Microsoft.PowerShell.Utility   
  Manifest 3.0.0.0   Microsoft.WSMan.Management     
    Script 3.0.10    PartnerCenter                  
```

## Debug output

```
DEBUG: 10:05:05 - GetAzureRmAccessTokenCommand begin processing with ParameterSet 'ResourceUrl'.
DEBUG: 10:05:06 - using account id '<removed>'...
Get-AzAccessToken : Cannot retrieve access token for resource 'https://management.azure.com/';. Please ensure that you have provided the appropriate access tokens when using access token login
.
At line:1 char:1
+ Get-AzAccessToken -ResourceUrl 'https://management.azure.com/'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAccessToken], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.GetAzureRmAccessTokenCommand
 
DEBUG: AzureQoSEvent: CommandName - Get-AzAccessToken; IsSuccess - False; Duration - 00:00:00.0368652;; Exception - System.InvalidOperationException: Cannot retrieve access token for resource '
https://management.azure.com/';. Please ensure that you have provided the appropriate access tokens when using access token login.
   at Microsoft.Azure.PowerShell.Authenticators.AccessTokenAuthenticator.Authenticate(AuthenticationParameters parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, Str
ing promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.Profile.GetAzureRmAccessTokenCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:05:06 - GetAzureRmAccessTokenCommand end processing.
```

## Error output

```
Message        : Cannot retrieve access token for resource 'https://management.azure.com/';. Please ensure that you have provided the appropriate access tokens when using access token login.
StackTrace     :    at Microsoft.Azure.PowerShell.Authenticators.AccessTokenAuthenticator.Authenticate(AuthenticationParameters parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& 
                 token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& 
                 token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& 
                 token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& 
                 token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& 
                 token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& 
                 token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& 
                 token)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureSt
                 ring password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.Profile.GetAzureRmAccessTokenCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.InvalidOperationException
InvocationInfo : {Get-AzAccessToken}
Line           : Get-AzAccessToken -ResourceUrl 'https://management.azure.com/'
Position       : At line:1 char:1
                 + Get-AzAccessToken -ResourceUrl 'https://management.azure.com/'
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 20
```

**Comment by o-l-a-v** [comment]
Also, the ExpiresOn property doesn't seem to work correctly.

![image](https://user-images.githubusercontent.com/6450056/99389993-34464700-28d8-11eb-8611-bdb4aa60cd96.png)

**Comment by alexandair** [comment]
The following commands return the token for me (with a proper ExpiresOn property value) after DeviceCode authentication using an account that has access permissions at the subscription level.

```powershell
Get-AzAccessToken -ResourceUrl https://management.core.windows.net/
Get-AzAccessToken -ResourceUrl https://management.azure.com/
```

**Comment by o-l-a-v** [comment]
Alright, so it only seems to happen when I use Azure PowerShell with GUID ```1950a258-227b-4e31-a9cf-717495945fc2``` to authenticate, where I first use a refreshtoken to create access tokens to various APIs.

```powershell
# Assets
$AzApplicationId = [string] '1950a258-227b-4e31-a9cf-717495945fc2'
    
# Create Partner refresh token to generate access tokens
if ([string]::IsNullOrEmpty($PartnerToken.'RefreshToken')) {
    $Global:PartnerToken = New-PartnerAccessToken -Tenant $ProviderTenantId -ApplicationId $AzApplicationId -Scopes 'https://api.partnercenter.microsoft.com/user_impersonation'
}
    
# Create provider access tokens
$PartnerAadToken = New-PartnerAccessToken -Tenant $ProviderTenantId -RefreshToken $PartnerToken.'RefreshToken' -ApplicationId $AzApplicationId -Scopes 'https://graph.windows.net/.default' 
$PartnerArmToken = New-PartnerAccessToken -Tenant $ProviderTenantId -RefreshToken $PartnerToken.'RefreshToken' -ApplicationId $AzApplicationId -Scopes 'https://management.azure.com/.default'
$PartnerMsgToken = New-PartnerAccessToken -Tenant $ProviderTenantId -RefreshToken $PartnerToken.'RefreshToken' -ApplicationId $AzApplicationId -Scopes 'https://graph.microsoft.com/.default'

# Connect
$null = Connect-AzAccount -Scope 'Process' -Tenant $ProviderTenantId -Subscription $ProviderSubscriptionId -AccountId $PartnerToken.'Account'.'Username' -AccessToken $PartnerArmToken.'AccessToken' -GraphAccessToken $PartnerAadToken.'AccessToken'
```

After that, the problems appear.

This however seems to work as expected.

```powershell
# Connect
$null = Clear-AzContext -Force
$null = Connect-AzAccount -Scope 'Process' -Tenant $TenantId -Subscription $SubscriptionId



# Get token
Get-AzAccessToken
Get-AzAccessToken -ResourceUrl 'https://graph.windows.net/'
Get-AzAccessToken -ResourceUrl 'https://management.azure.com/'
```

**Comment by erich-wang** [comment]
@o-l-a-v, thanks for raising the question.

1. Please use `Get-AzAccessToken -ResourceUrl "https://management.core.windows.net/"`, current version doesn't support url alias yet, it only respects url from (Get-AzEnvironment).ActiveDirectoryServiceEndpointResourceId, we may do some enhancement later.
2. If using access token to connect-azaccount, get-azaccesstoken will simply return the token without parsing expiration in token, that is why you see incorrect expiration info.

Is it typical scenario that retrieving access token after using access token to connect-azaccount?

**Comment by o-l-a-v** [comment]
> @o-l-a-v, thanks for raising the question.
> 
> 1. Please use `Get-AzAccessToken -ResourceUrl "https://management.core.windows.net/"`, current version doesn't support url alias yet, it only respects url from (Get-AzEnvironment).ActiveDirectoryServiceEndpointResourceId, we may do some enhancement later.
> 2. If using access token to connect-azaccount, get-azaccesstoken will simply return the token without parsing expiration in token, that is why you see incorrect expiration info.

"management.core.windows.net" worked, thanks.

> Is it typical scenario that retrieving access token after using access token to connect-azaccount?

Was looking for the simplest way of finding out if a access token was expired, other than hitting an error when making a new request. Would be great if you could decode the jwt and find ExpiresOn if it's null.

**Comment by erich-wang** [comment]
#13594 is to decode ExpiresOn if it is null. The bits will be released on Dec 8 release.
