### ISSUE TITLE
One Issue for Az.DeploymentManager

### ISSUE THREAD

**Issue by Youri970410** [Azure/azure-powershell#13522]
## Description

Install the 'Az.DeploymentManager' module and test the Cmdlet 'Get-AzDeploymentManagerArtifactSource'.But the error message shows that the service failed when deserializing the response.

## Steps to reproduce

```powershell
Get-AzDeploymentManagerArtifactSource -ResourceGroupName 'testResourceGroupName'

```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0-preview.1
PSEdition                      Core
GitCommitId                    7.1.0-preview.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.0.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppService…

```

## Error output

```
 Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[Microsoft.Azure.Management.DeploymentManager.Models.ArtifactSource]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
```

**Comment by dingmeng-xue** [comment]
Debug output
```
PS C:\dev\dingmeng-xue\azure-docs-powershell> Get-AzDeploymentManagerArtifactSource -ResourceGroupName nancyc-hn1
DEBUG: 11:14:43 AM - GetArtifactSource begin processing with ParameterSet 'Interactive'.
DEBUG: 11:14:43 AM - using account id 'dixue@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'dixue@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2020-11-17T04:13:14.0000000+00:00
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2020-11-17T04:13:14.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47', UserId: 'dixue@microsoft.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/9e223dbe-3399-4e19-88eb-0975f02ac87f/resourceGroups/nancyc-hn1/providers/Microsoft.DeploymentManager/artifactSources?api-version=2019-11-01-preview

Headers:
x-ms-client-request-id        : 567ee22c-92a2-42b3-bce4-35ce91b7a878
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11997
x-ms-request-id               : a48ae178-1cd3-4f1a-aad1-874a9ae09387
x-ms-correlation-request-id   : a48ae178-1cd3-4f1a-aad1-874a9ae09387
x-ms-routing-request-id       : SOUTHEASTASIA:20201117T031444Z:a48ae178-1cd3-4f1a-aad1-874a9ae09387
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 17 Nov 2020 03:14:43 GMT

Body:
{
  "value": []
}


Get-AzDeploymentManagerArtifactSource : Unable to deserialize the response.
At line:1 char:1
+ Get-AzDeploymentManagerArtifactSource -ResourceGroupName nancyc-hn1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzDeploymentManagerArtifactSource], SerializationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.DeploymentManager.Commands.GetArtifactSource

DEBUG: AzureQoSEvent: CommandName - Get-AzDeploymentManagerArtifactSource; IsSuccess - False; Duration - 00:00:00.5980190;; Exception - Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.IList`1[Microsoft.Azure.Management.DeploymentManager.Models.ArtifactSource]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'value', line 1, position 9.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.DeploymentManager.ArtifactSourcesOperations.ListWithHttpMessagesAsync(String resourceGroupName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.DeploymentManager.ArtifactSourcesOperations.ListWithHttpMessagesAsync(String resourceGroupName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.DeploymentManager.ArtifactSourcesOperationsExtensions.ListAsync(IArtifactSourcesOperations operations, String resourceGroupName, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.DeploymentManager.ArtifactSourcesOperationsExtensions.List(IArtifactSourcesOperations operations, String resourceGroupName)
   at Microsoft.Azure.Commands.DeploymentManager.Client.DeploymentManagerClient.ListArtifactSources(String resourceGroupName)
   at Microsoft.Azure.Commands.DeploymentManager.Commands.GetArtifactSource.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:14:45 AM - GetArtifactSource end processing.
```

**Comment by dingmeng-xue** [comment]
Service team, please help to look into this problem.
