### ISSUE TITLE
Unable to get ErrorAction parameter to work w/o calling on the extension library System.Management.Automation.ActionPreference

### ISSUE THREAD

**Issue by uceimmp** [Azure/azure-powershell#13709]
## Description
Unable to get -ErrorAction parameter working without calling on System.Management.Automation.ActionPreference

## Steps to reproduce

```

**Code that does not work**
$storageaccounts = Get-AzStorageAccount

foreach($storageaccount in $storageaccounts){
$storageKey = (Get-AzStorageAccountKey -ResourceGroupName $storageaccount.ResourceGroupName -Name $storageaccount.StorageAccountName -ErrorAction SilentlyContinue)[0].Value
}

**Code that does work**
$storageaccounts = Get-AzStorageAccount
$ErrorActionPreference = [System.Management.Automation.ActionPreference]::SilentlyContinue 

foreach($storageaccount in $storageaccounts){
$storageKey = (Get-AzStorageAccountKey -ResourceGroupName $storageaccount.ResourceGroupName -Name $storageaccount.StorageAccountName -ErrorAction $ErrorActionPreference)[0].Value
}


```

## Environment data

```
Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1      

```

## Module versions

```

ModuleType Version    Name                                  ExportedCommands
--
----------   -------    ----                                  ----------------
Script     2.2.1      Az.Accounts                           {Disable-AzDataCollection, Disable-AzContextAutosave, Enabl...
Script     3.0.1      Az.Resources                          {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRo...
Script     3.0.0      Az.Storage                            {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStora...
Script     4.6.1      Azure.Storage                         {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-...
Binary     2.0.2.128  AzureAD                               {Add-AzureADApplicationOwner, Get-AzureADApplication, Get-A...
Script     6.1.1      AzureRM.Automation                    {Get-AzureRMAutomationHybridWorkerGroup, Remove-AzureRmAuto...
Script     5.9.1      AzureRM.Compute                       {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet,...
Script     5.8.3      AzureRM.Profile                       {Disable-AzureRmDataCollection, Disable-AzureRmContextAutos...
Script     6.7.3      AzureRM.Resources                     {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment...
Script     4.12.1     AzureRM.Sql                           {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-Azure...
Script     5.2.0      AzureRM.Storage                       {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, N...
Manifest   1.1.0.0      AuditPolicyDsc
Manifest   5.0.0.0      ComputerManagementDsc
Script     0.2        GPRegistryPolicyParser              {Parse-PolFile,   Read-RegistryPolicies, Create-RegistrySetti...
Script     0.0        Microsoft.PowerShell.Core
Script     0.0        Microsoft.PowerShell.Diagnostics
Script     0.0        Microsoft.PowerShell.Management
Script     0.0        Microsoft.PowerShell.Security
Script     0.0        Microsoft.PowerShell.Utility
Script     0.0        Microsoft.WSMan.Management
Binary     1.0        Orchestrator.AssetManagement.Cmd...   {Get-AutomationCertificate, Get-AutomationConnection, Get-S...
Manifest   2.9.0.0      PSDscResources
Manifest   2.1.0.0      SecurityPolicyDsc
Manifest   1.0          StateConfigCompositeResources
Manifest   1.1          xDSCDomainjoin
Manifest   1.1.0.0      xPowerShellExecutionPolicy            {Get-TargetResource, Test-TargetResource, Set-TargetResource}
Manifest   1.1.0.0      xRemoteDesktopAdmin
Script     1.0.1      Microsoft.PowerShell.Operation.V...   {Get-OperationValidation, Invoke-OperationValidation}
Binary     1.0.0.1    PackageManagement                   {Find-Package,   Get-Package, Get-PackageProvider, Get-Packag...
Script     3.4.0      Pester                              {Describe,   Context, It, Should...}
Script     1.0.0.1    PowerShellGet                       {Install-Module,   Find-Module, Save-Module, Update-Module...}
Script     1.2        PSReadline                            {Get-PSReadlineKeyHandler, Set-PSReadlineKeyHandler, Remove...
Manifest   1.0.0.0      AppBackgroundTask                     {Disable-AppBackgroundTaskDiagnosticLog, Enable-AppBackgrou...
Manifest   2.0.0.0      Appx                                  {Add-AppxPackage, Get-AppxPackage, Get-AppxPackageManifest,...
Manifest   2.0.0.0      BitsTransfer                          {Add-BitsFile, Complete-BitsTransfer, Get-BitsTransfer, Rem...
Manifest   1.0.0.0      CimCmdlets                            {Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, ...
Manifest   1.0          Defender                              {Get-MpPreference, Set-MpPreference, Add-MpPreference, Remo...
Manifest   1.0.0.0      DeliveryOptimization                  {Get-DeliveryOptimizationStatus, Get-DeliveryOptimizationPe...
Manifest   1.0.0.0      DirectAccessClientComponents          {Disable-DAManualEntryPointSelection, Enable-DAManualEntryP...
Script     3.0        Dism                                  {Add-AppxProvisionedPackage, Add-WindowsDriver, Add-Windows...
Manifest   1.0.0.0      DnsClient                             {Resolve-DnsName, Clear-DnsClientCache, Get-DnsClient, Get-...
Manifest   1.0.0.0      EventTracingManagement                {Start-EtwTraceSession, New-EtwTraceSession, Get-EtwTraceSe...
Manifest   2.0.0.0      International                         {Get-WinDefaultInputMethodOverride, Set-WinDefaultInputMeth...
Manifest   1.0.0.0      iSCSI                                 {Get-IscsiTargetPortal, New-IscsiTargetPortal, Remove-Iscsi...
Script     1.0.0.0    ISE                                   {New-IseSnippet, Import-IseSnippet, Get-IseSnippet}
Manifest   1.0.0.0      Kds                                   {Add-KdsRootKey, Get-KdsRootKey, Test-KdsRootKey, Set-KdsCo...
Manifest   1.0.1.0      Microsoft.PowerShell.Archive          {Compress-Archive, Expand-Archive}
Manifest   3.0.0.0      Microsoft.PowerShell.Diagnostics      {Get-WinEvent, Get-Counter, Import-Counter, Export-Counter...}
Manifest   3.0.0.0      Microsoft.PowerShell.Host             {Start-Transcript, Stop-Transcript}
Manifest   1.0.0.0      Microsoft.PowerShell.LocalAccounts    {Add-LocalGroupMember, Disable-LocalUser, Enable-LocalUser,...
Manifest   3.1.0.0      Microsoft.PowerShell.Management       {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path...}
Script     1.0        Microsoft.PowerShell.ODataUtils     Export-ODataEndpointProxy
Manifest   3.0.0.0      Microsoft.PowerShell.Security         {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Credential...}
Manifest   3.1.0.0      Microsoft.PowerShell.Utility          {Format-List, Format-Custom, Format-Table, Format-Wide...}
Manifest   3.0.0.0      Microsoft.WSMan.Management            {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-WSManCredSS...
Manifest   1.0          MMAgent                               {Disable-MMAgent, Enable-MMAgent, Set-MMAgent, Get-MMAgent...}
Manifest   1.0.0.0      MsDtc                                 {New-DtcDiagnosticTransaction, Complete-DtcDiagnosticTransa...
Manifest   2.0.0.0      NetAdapter                            {Disable-NetAdapter, Disable-NetAdapterBinding, Disable-Net...
Manifest   1.0.0.0      NetConnection                         {Get-NetConnectionProfile, Set-NetConnectionProfile}
Manifest   1.0.0.0      NetEventPacketCapture                 {New-NetEventSession, Remove-NetEventSession, Get-NetEventS...
Manifest   2.0.0.0      NetLbfo                               {Add-NetLbfoTeamMember, Add-NetLbfoTeamNic, Get-NetLbfoTeam...
Manifest   1.0.0.0      NetNat                                {Get-NetNat, Get-NetNatExternalAddress, Get-NetNatStaticMap...
Manifest   2.0.0.0      NetQos                                {Get-NetQosPolicy, Set-NetQosPolicy, Remove-NetQosPolicy, N...
Manifest   2.0.0.0      NetSecurity                           {Get-DAPolicyChange, New-NetIPsecAuthProposal, New-NetIPsec...
Manifest   1.0.0.0      NetSwitchTeam                         {New-NetSwitchTeam, Remove-NetSwitchTeam, Get-NetSwitchTeam...
Manifest   1.0.0.0      NetTCPIP                              {Get-NetIPAddress, Get-NetIPInterface, Get-NetIPv4Protocol,...
Manifest   1.0.0.0      NetworkConnectivityStatus             {Get-DAConnectionStatus, Get-NCSIPolicyConfiguration, Reset...
Manifest   1.0.0.0      NetworkSwitchManager                  {Disable-NetworkSwitchEthernetPort, Enable-NetworkSwitchEth...
Manifest   1.0.0.0      NetworkTransition                     {Add-NetIPHttpsCertBinding, Disable-NetDnsTransitionConfigu...
Manifest   1.0.0.0      PcsvDevice                            {Get-PcsvDevice, Start-PcsvDevice, Stop-PcsvDevice, Restart...
Manifest   1.0.0.0      PKI                                   {Add-CertificateEnrollmentPolicyServer, Export-Certificate,...
Manifest   1.0.0.0      PnpDevice                             {Get-PnpDevice, Get-PnpDeviceProperty, Enable-PnpDevice, Di...
Manifest   1.1          PrintManagement                       {Add-Printer, Add-PrinterDriver, Add-PrinterPort, Get-Print...
Script     3.0        Provisioning                          {Install-ProvisioningPackage, Export-ProvisioningPackage, I...
Manifest   1.1          PSDesiredStateConfiguration           {Set-DscLocalConfigurationManager, Start-DscConfiguration, ...
Script     1.0.0.0    PSDiagnostics                       {Disable-PSTrace,   Disable-PSWSManCombinedTrace, Disable-WSM...
Binary     1.1.0.0    PSScheduledJob                      {New-JobTrigger,   Add-JobTrigger, Remove-JobTrigger, Get-Job...
Manifest   2.0.0.0      PSWorkflow                            {New-PSWorkflowExecutionOption, New-PSWorkflowSession, nwsn}
Manifest   1.0.0.0      PSWorkflowUtility                     Invoke-AsWorkflow
Manifest   1.0.0.0      ScheduledTasks                        {Get-ScheduledTask, Set-ScheduledTask, Register-ScheduledTa...
Manifest   2.0.0.0      SecureBoot                            {Confirm-SecureBootUEFI, Set-SecureBootUEFI, Get-SecureBoot...
Manifest   2.0.0.0      SmbShare                              {Get-SmbShare, Remove-SmbShare, Set-SmbShare, Block-SmbShar...
Manifest   2.0.0.0      SmbWitness                            {Get-SmbWitnessClient, Move-SmbWitnessClient, gsmbw, msmbw...}
Manifest   1.0.0.0      StartLayout                           {Export-StartLayout, Import-StartLayout, Export-StartLayout...
Manifest   2.0.0.0      Storage                               {Add-InitiatorIdToMaskingSet, Add-PartitionAccessPath, Add-...
Manifest   2.0.0.0      TLS                                   {New-TlsSessionTicketKey, Enable-TlsSessionTicketKey, Disab...
Manifest   1.0.0.0      TroubleshootingPack                   {Get-TroubleshootingPack, Invoke-TroubleshootingPack}
Manifest   2.0.0.0      TrustedPlatformModule                 {Get-Tpm, Initialize-Tpm, Clear-Tpm, Unblock-Tpm...}
Manifest   2.0.0.0      VpnClient                             {Add-VpnConnection, Set-VpnConnection, Remove-VpnConnection...
Manifest   1.0.0.0      Wdac                                  {Get-OdbcDriver, Set-OdbcDriver, Get-OdbcDsn, Add-OdbcDsn...}
Manifest   1.0.0.0      WindowsDeveloperLicense               {Get-WindowsDeveloperLicense, Unregister-WindowsDeveloperLi...
Script     1.0        WindowsErrorReporting               {Enable-WindowsErrorReporting,   Disable-WindowsErrorReportin...
Manifest   1.0.0.0      WindowsSearch                         {Get-WindowsSearchSetting, Set-WindowsSearchSetting}
Manifest   1.0.0.0      WindowsUpdate                         Get-WindowsUpdateLog
Manifest   1.0.0.0      PSWorkflowUtility                     Invoke-AsWorkflow
Manifest   1.0.0.0      ScheduledTasks                        {Get-ScheduledTask, Set-ScheduledTask, Register-ScheduledTa...
Manifest   2.0.0.0      SecureBoot                            {Confirm-SecureBootUEFI, Set-SecureBootUEFI, Get-SecureBoot...
Manifest   2.0.0.0      SmbShare                              {Get-SmbShare, Remove-SmbShare, Set-SmbShare, Block-SmbShar...
Manifest   2.0.0.0      SmbWitness                            {Get-SmbWitnessClient, Move-SmbWitnessClient, gsmbw, msmbw...}
Manifest   1.0.0.0      StartLayout                           {Export-StartLayout, Import-StartLayout, Export-StartLayout...
Manifest   2.0.0.0      Storage                               {Add-InitiatorIdToMaskingSet, Add-PartitionAccessPath, Add-...
Manifest   2.0.0.0      TLS                                   {New-TlsSessionTicketKey, Enable-TlsSessionTicketKey, Disab...
Manifest   1.0.0.0      TroubleshootingPack                   {Get-TroubleshootingPack, Invoke-TroubleshootingPack}
Manifest   2.0.0.0      TrustedPlatformModule                 {Get-Tpm, Initialize-Tpm, Clear-Tpm, Unblock-Tpm...}
Manifest   2.0.0.0      VpnClient                             {Add-VpnConnection, Set-VpnConnection, Remove-VpnConnection...
Manifest   1.0.0.0      Wdac                                  {Get-OdbcDriver, Set-OdbcDriver, Get-OdbcDsn, Add-OdbcDsn...}
Manifest   1.0.0.0      WindowsDeveloperLicense               {Get-WindowsDeveloperLicense, Unregister-WindowsDeveloperLi...
Script     1.0        WindowsErrorReporting               {Enable-WindowsErrorReporting,   Disable-WindowsErrorReportin...
Manifest   1.0.0.0      WindowsSearch                         {Get-WindowsSearchSetting, Set-WindowsSearchSetting}
Manifest   1.0.0.0      WindowsUpdate                         Get-WindowsUpdateLog

```

## Debug output

```
Get-AzStorageAccountKey : A positional parameter cannot be found that accepts argument 'SilentlyContinue=Continue'.
At line:128 char:20
+ ... orageKey = (Get-AzStorageAccountKey -ResourceGroupName $storageaccoun ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

## Error output

```
Message          : A positional parameter cannot be found that accepts argument 'SilentlyContinue=Continue'.
StackTrace       :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(Parameter
                   BindingException originalBindingException)
                      at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidat
                   ion(Collection`1 arguments)
                      at 
                   System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 
                   arguments)
                      at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                      at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary 
                   psDefaultParameterValues)
                      at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                      at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object 
                   input)
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object 
                   input)
                      at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, 
                   CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] 
                   commandRedirections, FunctionContext funcContext)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : InvalidArgument: (:) [Get-AzStorageAccountKey], ParameterBindingException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, <No file>: line 128

```

**Comment by dingmeng-xue** [comment]
Hi @uceimmp, this issue cannot be reproduce in our environment. 

Could you remove AzureRM modules and try again after you start windows powershell?

My environment is:
```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.610
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.610
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1


PS C:\> Get-AzStorageAccountKey -ResourceGroupName test -AccountName test -ErrorAction SilentlyContinue
PS C:\>
```
