### ISSUE TITLE
[Storage] Update-AzDataLakeGen2Item with "-Owner"  but no "-Permission" will report "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#13753]
## Description
Run `Update-AzDataLakeGen2Item` with "-Owner"  but no "-Permission" will report "Object reference not set to an instance of an object."

## Steps to reproduce

```powershell
$dirchild = Get-AzDataLakeGen2Item -Context $ctx -FileSystem $filesystemName -Path $dirname| Update-AzDataLakeGen2Item -Owner "xxx@microsoft.com" -Context $ctx
```

## Environment data

Az.Storage 3.1.0 

## Debug output

```
PS C:\> $dirchild = Get-AzDataLakeGen2Item -Context $ctx -FileSystem $filesystemName -Path $dirname| Update-AzDataLakeGen2Item -Owner "xxx@microsoft.com" -Context $ctx
Update-AzDataLakeGen2Item : Object reference not set to an instance of an object.
At line:2 char:94
+ ... h $dirname| Update-AzDataLakeGen2Item -Owner "xxx@microsoft.com"  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzDataLakeGen2Item], NullReferenceException
    + FullyQualifiedErrorId : NullReferenceException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.SetAzDataLakeGen2ItemCommand

PS C:\> $Error[0].Exception.ToString()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Storage.Files.DataLake.DataLakePathClient.<SetPermissionsInternal>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Files.DataLake.DataLakePathClient.SetPermissions(PathPermissions permissions, String owner, String group, DataLakeRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeDirectoryClient.SetPermissions(PathPermissions permissions, String owner, String group, DataLakeRequestConditions conditions, CancellationToken cancellationToken)
   at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.SetAzDataLakeGen2ItemComman
```

**Comment by blueww** [comment]
The error is from .net SDK (Powershell based on .net SDK).

- .net SDK API "DataLakeDirectoryClient.SetPermissions()" can't update only "owner"  without "permissions". 
- Anyway, per rest API doc, "x-ms-permissions"," x-ms-owner", "x-ms-group" are all optional for update datalake items, so they should can be set separately.

I have filed an issue for SDK: https://github.com/Azure/azure-sdk-for-net/issues/17575

If .net SDK fix this issue, Powershell can fix this issue by upgrade to latest SDK.

 
Workaround: 
Before the issue is fixed in Powershell, User can workaround this issue by set permission together with owner, the script change is:

change :
```
$dirchild = Update-AzDataLakeGen2Item -FileSystem $filesystemName -Path $dirname -Owner "xxx@microsoft.com" -Context $ctx
```
To
```
$dirchild = Get-AzDataLakeGen2Item -Context $ctx -FileSystem $filesystemName -Path $dirname 
$dirchild =  $dirchild | Update-AzDataLakeGen2Item -Permission $dirchild.Permissions.ToSymbolicPermissions().Substring(0,9) -Owner "xxx@microsoft.com" -Context $ctx 
```

**Comment by blueww** [comment]
The SDK issue Azure/azure-sdk-for-net#17575 is fixed in SDK code, will upgrade to next SDK release (might be mid of Jan) to fix the issue in PSH.

**Comment by blueww** [comment]
This is already fixed in Az.Storage 3.3.0.
