### ISSUE TITLE
Backup policy name regex validation error

### ISSUE THREAD

**Issue by andrebossi** [Azure/azure-powershell#13869]
## Description

Regex to validate name of backup item policy not accept _ in policy name, but portal.azure.com support _ in policy names

Now: ^[A-Za-z][-A-Za-z0-9]*[A-Za-z0-9]$
After: ^[A-Za-z][-A-Za_-z0-9]*[A-Za_-z0-9]$

azure-powershell\src\RecoveryServices\RecoveryServices.Backup\Cmdlets\ProtectionPolicy\PolicyCmdletHelpers.cs on method ValidateProtectionPolicyName

## Steps to reproduce

```powershell
Set-AzRecoveryServicesBackupProtectionPolicy -Policy 'teste_teste' -SchedulePolicy $SchPol -RetentionPolicy $RetPol -VaultId $Vault_ID
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
5.3.0                Az                                  PSGallery            
```

## Debug output

```
[log.txt](https://github.com/Azure/azure-powershell/files/5766455/log.txt)
```

## Error output

```
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 2171

Message        : Backup policy name should contain alphanumeric characters and cannot start with a number
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.PolicyCmdletHelpers.ValidateProtectionPolicyName(String policyName)
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.SetAzureRmRecoveryServicesBackupProtectionPolicy.<ExecuteCmdlet>b__18_0()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RecoveryServicesBackupCmdletBase.ExecutionBlock(Action action, Boolean shouldProcess)
Exception      : System.ArgumentException
InvocationInfo : {Set-AzRecoveryServicesBackupProtectionPolicy}
Line           :     Set-AzRecoveryServicesBackupProtectionPolicy -Policy $BackupPolicy -SchedulePolicy $SchPol -RetentionPolicy $RetPol -VaultId $Vault_ID

Position       : At E:\source\repos\linx_pwsh_scripts\Azure\Update-Policy\Set-BackupPolicyVMApp.ps1:47 char:5
                 +     Set-AzRecoveryServicesBackupProtectionPolicy -Policy $BackupPolic …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2171


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.



Set-AzRecoveryServicesBackupProtectionPolicy: E:\source\Azure\Update-Policy\Set-BackupPolicyVMApp.ps1:47:5
Line |
  47 |      Set-AzRecoveryServicesBackupProtectionPolicy -Policy $BackupPolic …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Backup policy name should contain alphanumeric characters and cannot start with a number
```

**Comment by dingmeng-xue** [comment]
Recovery Services team, please check which client is correct, Portal or PowerShell?

**Comment by pvrk** [comment]
Acknowledged. Will check and update the thread.

**Comment by mepand** [comment]
@andrebossi I tried creating a policy with name 'teste_teste" from the portal but it gave a warning that "Backup policy name should contain alphanumeric characters and cannot start with a number". Could you please confirm for which workload were you able to create a policy with _ from portal and if possible could you please share a screenshot?

**Comment by andrebossi** [comment]
Please close Issue!

Sorry this is a incorrect name setting backup_policy name i change thist for _ to -

**Comment by dingmeng-xue** [comment]
Thanks. Close it now.
