### ISSUE TITLE
New-AZServiceFabricCluster throws error after successfully creating cluster: Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by JapNolt** [Azure/azure-powershell#13887]
## Description
I run New-AZServiceFabricCluster and provide the template and secret. The ARM deployment is successful. All the Azure resources are created successfully. But the final result is always an exception.

Operation returned an invalid status code 'NotFound'

Note: This is being run as part of an Azure Devops Release pipeline using the Azure Powershell task. But this also happens when run locally.

## Steps to reproduce

```powershell
New-AzServiceFabricCluster `
  -ResourceGroupName $resourceGroupName `
  -SecretIdentifier $secretId `
  -TemplateFile $templateFilePath `
  -ParameterFile $parameterFilePath
```

## Environment data

```
Name                           Value                   
----                           -----                   
PSVersion                      5.1.14393.3866          
PSEdition                      Desktop                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...} 
BuildVersion                   10.0.14393.3866         
CLRVersion                     4.0.30319.42000         
WSManStackVersion              3.0                     
PSRemotingProtocolVersion      2.3                     
SerializationVersion           1.1.0.1                 
```

## Module versions
There are more modules in the session but here's the relevant one.

```powershell
 Name              : Az.ServiceFabric
 Path              : C:\Modules\az_4.7.0\Az.ServiceFabric\2.2.0\Az.ServiceFabric.psd1
 Description       : Microsoft Azure PowerShell - Service Fabric cmdlets for Azure Resource Manager in Windows 
                     PowerShell and PowerShell Core.
                     
                     For more information on Service Fabric, please visit the following: 
                     https://docs.microsoft.com/azure/service-fabric/
 Guid              : f98e4fc9-6247-4e59-99a1-7b8ba13b3d1e
 Version           : 2.2.0
 ModuleBase        : C:\Modules\az_4.7.0\Az.ServiceFabric\2.2.0
 ModuleType        : Script
 PrivateData       : {PSData}
 AccessMode        : ReadWrite
 ExportedAliases   : {}
 ExportedCmdlets   : {[Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClientCertificate], 
                     [Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricClusterCertificate], 
                     [Add-AzServiceFabricNode, Add-AzServiceFabricNode], [Add-AzServiceFabricNodeType, 
                     Add-AzServiceFabricNodeType]...}
 ExportedFunctions : {}
 ExportedVariables : {}
 NestedModules     : {}

```

## Debug output
There were more details but this is the relevant one.

```
2021-01-06T15:16:46.4286239Z DEBUG: ============================ HTTP REQUEST ============================
2021-01-06T15:16:46.4291495Z 
2021-01-06T15:16:46.4296032Z 
2021-01-06T15:16:46.4301125Z 
2021-01-06T15:16:46.4320050Z HTTP Method:
2021-01-06T15:16:46.4325751Z 
2021-01-06T15:16:46.4343685Z GET
2021-01-06T15:16:46.4348788Z 
2021-01-06T15:16:46.4354608Z 
2021-01-06T15:16:46.4358206Z 
2021-01-06T15:16:46.4377063Z Absolute Uri:
2021-01-06T15:16:46.4385701Z 
2021-01-06T15:16:46.4407797Z https://management.azure.com/subscriptions/<id removed>/resourceGroups/<rg name removed>/provi
2021-01-06T15:16:46.4476328Z ders/Microsoft.ServiceFabric/clusters/variables?api-version=2020-03-01
2021-01-06T15:16:46.4482419Z 
2021-01-06T15:16:46.4488549Z 
2021-01-06T15:16:46.4495057Z 
2021-01-06T15:16:46.4516465Z Headers:
2021-01-06T15:16:46.4525108Z 
2021-01-06T15:16:46.4561065Z x-ms-client-request-id        : c05a1955-81b7-4044-b0b7-b754f98ba5ce
2021-01-06T15:16:46.4596244Z 
2021-01-06T15:16:46.4598051Z accept-language               : en-US
2021-01-06T15:16:46.4598703Z 
2021-01-06T15:16:46.4605672Z 
2021-01-06T15:16:46.4611958Z 
2021-01-06T15:16:46.4632070Z Body:
2021-01-06T15:16:46.4634462Z 
2021-01-06T15:16:46.4642135Z 
2021-01-06T15:16:46.4644881Z 
2021-01-06T15:16:46.4682437Z 
2021-01-06T15:16:46.4706995Z DEBUG: ============================ HTTP RESPONSE ============================
2021-01-06T15:16:46.4713437Z 
2021-01-06T15:16:46.4721638Z 
2021-01-06T15:16:46.4728433Z 
2021-01-06T15:16:46.4750858Z Status Code:
2021-01-06T15:16:46.4755940Z 
2021-01-06T15:16:46.4777469Z NotFound
2021-01-06T15:16:46.4782005Z 
2021-01-06T15:16:46.4786668Z 
2021-01-06T15:16:46.4791591Z 
2021-01-06T15:16:46.4812038Z Headers:
2021-01-06T15:16:46.4817935Z 
2021-01-06T15:16:46.4842133Z Pragma                        : no-cache
2021-01-06T15:16:46.4845434Z 
2021-01-06T15:16:46.4875521Z x-ms-failure-cause            : gateway
2021-01-06T15:16:46.4882498Z 
2021-01-06T15:16:46.4913991Z x-ms-request-id               : 4faa8776-38f6-4896-ac01-c5a8c46ca220
2021-01-06T15:16:46.4924414Z 
2021-01-06T15:16:46.4952891Z x-ms-correlation-request-id   : 4faa8776-38f6-4896-ac01-c5a8c46ca220
2021-01-06T15:16:46.4962869Z 
2021-01-06T15:16:46.4978860Z x-ms-routing-request-id       : EASTUS:20210106T151644Z:4faa8776-38f6-4896-ac01-c5a8c46ca220
2021-01-06T15:16:46.4988783Z 
2021-01-06T15:16:46.5016973Z Strict-Transport-Security     : max-age=31536000; includeSubDomains
2021-01-06T15:16:46.5022089Z 
2021-01-06T15:16:46.5037641Z X-Content-Type-Options        : nosniff
2021-01-06T15:16:46.5041970Z 
2021-01-06T15:16:46.5106324Z Cache-Control                 : no-cache
2021-01-06T15:16:46.5112074Z 
2021-01-06T15:16:46.5129583Z Date                          : Wed, 06 Jan 2021 15:16:44 GMT
2021-01-06T15:16:46.5163970Z 
2021-01-06T15:16:46.5167144Z 
2021-01-06T15:16:46.5206843Z 
2021-01-06T15:16:46.5317334Z Body:
2021-01-06T15:16:46.5332728Z 
2021-01-06T15:16:46.5341686Z {
2021-01-06T15:16:46.5348620Z 
2021-01-06T15:16:46.5368139Z   "error": {
2021-01-06T15:16:46.5375728Z 
2021-01-06T15:16:46.5396606Z     "code": "ResourceNotFound",
2021-01-06T15:16:46.5402981Z 
2021-01-06T15:16:46.5422475Z     "message": "The Resource 'Microsoft.ServiceFabric/clusters/variables' under resource group 'ContactCenter-Test' was
2021-01-06T15:16:46.5444201Z  not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
2021-01-06T15:16:46.5449650Z 
2021-01-06T15:16:46.5474066Z   }
2021-01-06T15:16:46.5479201Z 
2021-01-06T15:16:46.5499889Z }

```

## Error output

```
2021-01-06T16:17:41.8574236Z New-AzServiceFabricCluster : Operation returned an invalid status code 'NotFound'
2021-01-06T16:17:41.8574930Z At <path removed>\ARM_Deployment\DeployServiceFabric_FromReleasePipeline.ps1:31 char:1
2021-01-06T16:17:41.8576347Z + New-AzServiceFabricCluster `
2021-01-06T16:17:41.8576772Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-01-06T16:17:41.8577319Z     + CategoryInfo          : CloseError: (:) [New-AzServiceFabricCluster], ErrorModelException
2021-01-06T16:17:41.8578105Z     + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster
2021-01-06T16:17:41.8578567Z  
2021-01-06T16:17:41.8763168Z DEBUG: AzureQoSEvent: CommandName - New-AzServiceFabricCluster; IsSuccess - False; Duration - 00:05:06.3718233;; 
2021-01-06T16:17:41.8764433Z Exception - Microsoft.Azure.Management.ServiceFabric.Models.ErrorModelException: Operation returned an invalid status 
2021-01-06T16:17:41.8765434Z code 'NotFound'
2021-01-06T16:17:41.8765947Z 
2021-01-06T16:17:41.8766511Z    at Microsoft.Azure.Commands.ServiceFabric.Commands.ServiceFabricClusterCmdlet.GetCurrentCluster()
2021-01-06T16:17:41.8768221Z 
2021-01-06T16:17:41.8769009Z    at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.WaitForDeployment(Deployment 
2021-01-06T16:17:41.8769819Z deployment, List`1 certInformations)
2021-01-06T16:17:41.8770363Z 
2021-01-06T16:17:41.8770956Z    at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.DeployWithoutDefaultTemplate()
2021-01-06T16:17:41.8771310Z 
2021-01-06T16:17:41.8771608Z    at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.ExecuteCmdlet()
2021-01-06T16:17:41.8771884Z 
2021-01-06T16:17:41.8855882Z    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
2021-01-06T16:17:42.2495245Z DEBUG: Finish sending metric.
2021-01-06T16:17:42.2522992Z DEBUG: 4:17:42 PM - NewAzureRmServiceFabricCluster end processing.
2021-01-06T16:17:42.2595757Z DEBUG: 4:17:42 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
2021-01-06T16:17:42.2664954Z DEBUG: 4:17:42 PM - using account id '***'...
2021-01-06T16:17:42.2999874Z WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
2021-01-06T16:17:42.3000499Z 
2021-01-06T16:17:42.3000870Z The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use 
2021-01-06T16:17:42.3001266Z `Resolve-AzError` instead.
2021-01-06T16:17:42.3001412Z 
2021-01-06T16:17:42.3001737Z Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other 
2021-01-06T16:17:42.3002769Z information on breaking changes in Azure PowerShell.
2021-01-06T16:17:42.3133762Z 
2021-01-06T16:17:42.3151907Z InnerException   : False
2021-01-06T16:17:42.3163675Z Exception        : Microsoft.Azure.Management.ServiceFabric.Models.ErrorModelException: Operation returned an invalid 
2021-01-06T16:17:42.3164441Z                    status code 'NotFound'
2021-01-06T16:17:42.3165073Z                       at Microsoft.Azure.Commands.ServiceFabric.Commands.ServiceFabricClusterCmdlet.GetCurrentCluster()
2021-01-06T16:17:42.3337927Z                       at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.WaitForDeployme
2021-01-06T16:17:42.3338813Z                    nt(Deployment deployment, List`1 certInformations)
2021-01-06T16:17:42.3600731Z                       at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.DeployWithoutDe
2021-01-06T16:17:42.3601498Z                    faultTemplate()
2021-01-06T16:17:42.3602070Z                       at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.ExecuteCmdlet()
2021-01-06T16:17:42.3604350Z                       at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2021-01-06T16:17:42.3605189Z Message          : Operation returned an invalid status code 'NotFound'
2021-01-06T16:17:42.3612371Z StackTrace       :    at Microsoft.Azure.Commands.ServiceFabric.Commands.ServiceFabricClusterCmdlet.GetCurrentCluster()
2021-01-06T16:17:42.3779931Z                       at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.WaitForDeployme
2021-01-06T16:17:42.3780968Z                    nt(Deployment deployment, List`1 certInformations)
2021-01-06T16:17:42.3938829Z                       at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.DeployWithoutDe
2021-01-06T16:17:42.3939579Z                    faultTemplate()
2021-01-06T16:17:42.3940665Z                       at Microsoft.Azure.Commands.ServiceFabric.Commands.NewAzureRmServiceFabricCluster.ExecuteCmdlet()
2021-01-06T16:17:42.3941491Z                       at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2021-01-06T16:17:42.3942141Z HelpLink         : 
2021-01-06T16:17:42.3942525Z ErrorDetails     : 
2021-01-06T16:17:42.3943633Z ErrorCategory    : CloseError: (:) [New-AzServiceFabricCluster], ErrorModelException
2021-01-06T16:17:42.3944181Z InvocationInfo   : System.Management.Automation.InvocationInfo
2021-01-06T16:17:42.4075667Z ScriptStackTrace : at <ScriptBlock>, <path removed>\ARM_Deploym
2021-01-06T16:17:42.4076639Z                    ent\DeployServiceFabric_FromReleasePipeline.ps1: line 31
2021-01-06T16:17:42.4077335Z                    at <ScriptBlock>,<path removed>\_temp\33cbabd2-6721-491d-b05d-dcf14ed4001f.ps1: line 48
2021-01-06T16:17:42.4078115Z                    at <ScriptBlock>, <No file>: line 1
2021-01-06T16:17:42.4078432Z 
2021-01-06T16:17:42.4090721Z 
2021-01-06T16:17:42.4091589Z The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
2021-01-06T16:17:42.4091933Z 
2021-01-06T16:17:42.4169479Z DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.1547894;
2021-01-06T16:17:42.8113236Z DEBUG: Finish sending metric.
2021-01-06T16:17:42.8145537Z DEBUG: 4:17:42 PM - ResolveError end processing.
```

**Comment by JapNolt** [comment]
This issue can probably be closed. It's been so long ago that I can't remember but I vaguely remember that the deployments just magically started working again.
