### ISSUE TITLE
New-AzCdnDeliveryRuleCondition fails due to mandatory MatchValue when Operator is Any

### ISSUE THREAD

**Issue by richardhauer** [Azure/azure-powershell#13989]
## Description
Attempting to create a CDN rule using:
`New-AzCdnDeliveryRuleCondition -MatchVariable RequestHeader -Selector "x-my-header" -Operator Any`

This works fine in the portal UI but there is a problem with the PS Module:

- The parameter `MatchValue` is required
- It does not accept `$null`
- It does not accept `@()` an empty array
- It does not accept `""` an empty string
- When later calling `Set-AzCdnEndpoint` to store the new policy, any value supplied with `MatchValue` causes a failure:

`Set-AzCdnEndpoint : Long running operation failed with status 'Failed'. Additional Info:'{"ErrorMessage":"Invalid RulesEngineConfig: (Match value(s) must not be provided for Operator 
'Any')."}'`

So it is both required to be set (by the PS module) and required to be blank (by the Azure fabric controller)... nice.

## Environment data
```
Name                           Value                                                                                                                                                     
----                           -----                                                                                                                                                     
PSVersion                      5.1.19041.610                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                   
BuildVersion                   10.0.19041.610                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                       
SerializationVersion           1.1.0.1
```

## Module versions
```powershell
ModuleType Version    Name                                     
---------- -------    ----                                     
    Script 2.2.4      Az.Accounts                              
    Script 1.1.1      Az.Advisor                               
    Script 2.0.1      Az.Aks                                   
    Script 1.1.4      Az.AnalysisServices                      
    Script 2.2.0      Az.ApiManagement                         
    Script 1.0.0      Az.AppConfiguration                      
    Script 1.1.0      Az.ApplicationInsights                   
    Script 1.4.2      Az.Automation                            
    Script 3.1.0      Az.Batch                                 
    Script 2.0.0      Az.Billing                               
    Script 1.6.0      Az.Cdn                                   
    Script 1.8.0      Az.CognitiveServices                     
    Script 4.8.0      Az.Compute                               
    Script 1.0.3      Az.ContainerInstance                     
    Script 2.1.0      Az.ContainerRegistry                     
    Script 1.0.0      Az.CosmosDB                              
    Script 1.1.0      Az.DataBoxEdge                           
    Script 1.0.2      Az.Databricks                            
    Script 1.11.3     Az.DataFactory                           
    Script 1.0.2      Az.DataLakeAnalytics                     
    Script 1.3.0      Az.DataLakeStore                         
    Script 1.0.0      Az.DataShare                             
    Script 1.1.0      Az.DeploymentManager                     
    Script 2.1.1      Az.DesktopVirtualization                 
    Script 1.0.2      Az.DevTestLabs                           
    Script 1.1.2      Az.Dns                                   
    Script 1.3.0      Az.EventGrid                             
    Script 1.7.1      Az.EventHub                              
    Script 1.6.1      Az.FrontDoor                             
    Script 2.0.0      Az.Functions                             
    Script 4.1.1      Az.HDInsight                             
    Script 1.2.0      Az.HealthcareApis                        
    Script 2.7.2      Az.IotHub                                
    Script 3.3.1      Az.KeyVault                              
    Script 1.0.1      Az.Kusto                                 
    Script 1.5.0      Az.LogicApp                              
    Script 1.1.3      Az.MachineLearning                       
    Script 1.1.0      Az.Maintenance                           
    Script 2.0.0      Az.ManagedServices                       
    Script 1.0.2      Az.MarketplaceOrdering                   
    Script 1.1.1      Az.Media                                 
    Script 2.4.0      Az.Monitor                               
    Script 4.5.0      Az.Network                               
    Script 1.1.1      Az.NotificationHubs                      
    Script 2.3.0      Az.OperationalInsights                   
    Script 1.4.0      Az.PolicyInsights                        
    Script 1.1.2      Az.PowerBIEmbedded                       
    Script 1.0.3      Az.PrivateDns                            
    Script 3.3.0      Az.RecoveryServices                      
    Script 1.4.0      Az.RedisCache                            
    Script 1.0.3      Az.Relay                                 
    Script 3.2.0      Az.Resources                             
    Script 1.4.1      Az.ServiceBus                            
    Script 2.2.2      Az.ServiceFabric                         
    Script 1.2.0      Az.SignalR                               
    Script 2.15.0     Az.Sql                                   
    Script 1.1.0      Az.SqlVirtualMachine                     
    Script 3.2.1      Az.Storage                               
    Script 1.4.0      Az.StorageSync                           
    Script 1.0.1      Az.StreamAnalytics                       
    Script 1.0.0      Az.Support                               
    Script 1.0.4      Az.TrafficManager                        
    Script 2.2.0      Az.Websites                              
    Script 1.0.3      OneDrive                                 
    Script 5.1.1      PowerShellISE-preview                    
  Manifest 1.7.0.4    PSFTP                                    
    Script 21.1.18080 SqlServer                                
    Binary 2.0.2.119  AzureADPreview                           
    Script 2.0.3      ExchangeOnlineManagement                 
    Script 1.0.1      Microsoft.PowerShell.Operation.Validation
    Binary 1.0.0.1    PackageManagement                        
    Script 3.4.0      Pester                                   
    Script 1.0.0.1    PowerShellGet                            
    Script 2.0.0      PSReadline                               
  Manifest 1.0.0.0    AppBackgroundTask                        
  Manifest 2.0.0.0    AppLocker                                
  Manifest 1.0.0.0    AppvClient                               
  Manifest 2.0.1.0    Appx                                     
    Script 1.0.0.0    AssignedAccess                           
  Manifest 1.0.0.0    BitLocker                                
  Manifest 2.0.0.0    BitsTransfer                             
  Manifest 1.0.0.0    BranchCache                              
  Manifest 1.0.0.0    CimCmdlets                               
  Manifest 1.0        ConfigCI                                 
  Manifest 1.0        ConfigDefender                           
  Manifest 1.0        Defender                                 
  Manifest 1.0.2.0    DeliveryOptimization                     
  Manifest 1.0.0.0    DirectAccessClientComponents             
    Script 3.0        Dism                                     
  Manifest 1.0.0.0    DnsClient                                
  Manifest 1.0.0.0    EventTracingManagement                   
    Binary 1.0.0.0    HostComputeService                       
  Manifest 1.0.0.1    HostNetworkingService                    
    Script 1.1.0.0    IISAdministration                        
  Manifest 2.0.0.0    International                            
  Manifest 1.0.0.0    iSCSI                                    
    Script 1.0.0.0    ISE                                      
  Manifest 1.0.0.0    Kds                                      
  Manifest 1.0.1.0    Microsoft.PowerShell.Archive             
  Manifest 3.0.0.0    Microsoft.PowerShell.Diagnostics         
  Manifest 3.0.0.0    Microsoft.PowerShell.Host                
  Manifest 1.0.0.0    Microsoft.PowerShell.LocalAccounts       
  Manifest 3.1.0.0    Microsoft.PowerShell.Management          
    Script 1.0        Microsoft.PowerShell.ODataUtils          
  Manifest 3.0.0.0    Microsoft.PowerShell.Security            
  Manifest 3.1.0.0    Microsoft.PowerShell.Utility             
  Manifest 3.0.0.0    Microsoft.WSMan.Management               
  Manifest 1.0        MMAgent                                  
  Manifest 1.0.0.0    MsDtc                                    
  Manifest 2.0.0.0    NetAdapter                               
  Manifest 1.0.0.0    NetConnection                            
  Manifest 1.0.0.0    NetEventPacketCapture                    
  Manifest 2.0.0.0    NetLbfo                                  
  Manifest 1.0.0.0    NetNat                                   
  Manifest 2.0.0.0    NetQos                                   
  Manifest 2.0.0.0    NetSecurity                              
  Manifest 1.0.0.0    NetSwitchTeam                            
  Manifest 1.0.0.0    NetTCPIP                                 
  Manifest 1.0.0.0    NetworkConnectivityStatus                
  Manifest 1.0.0.0    NetworkSwitchManager                     
  Manifest 1.0.0.0    NetworkTransition                        
  Manifest 1.0.0.0    PcsvDevice                               
    Binary 1.0.0.0    PersistentMemory                         
  Manifest 1.0.0.0    PKI                                      
  Manifest 1.0.0.0    PnpDevice                                
  Manifest 1.1        PrintManagement                          
    Binary 1.0.12     ProcessMitigations                       
    Script 3.0        Provisioning                             
  Manifest 1.1        PSDesiredStateConfiguration              
    Script 1.0.0.0    PSDiagnostics                            
    Binary 1.1.0.0    PSScheduledJob                           
  Manifest 2.0.0.0    PSWorkflow                               
  Manifest 1.0.0.0    PSWorkflowUtility                        
  Manifest 1.0.0.0    ScheduledTasks                           
  Manifest 2.0.0.0    SecureBoot                               
  Manifest 2.0.0.0    SmbShare                                 
  Manifest 2.0.0.0    SmbWitness                               
  Manifest 1.0.0.0    StartLayout                              
  Manifest 2.0.0.0    Storage                                  
  Manifest 1.0.0.0    StorageBusCache                          
  Manifest 2.0.0.0    TLS                                      
  Manifest 1.0.0.0    TroubleshootingPack                      
  Manifest 2.0.0.0    TrustedPlatformModule                    
    Binary 2.1.639.0  UEV                                      
  Manifest 2.0.0.0    VpnClient                                
  Manifest 1.0.0.0    Wdac                                     
  Manifest 1.0.0.0    WebAdministration                        
  Manifest 2.0.0.0    Whea                                     
  Manifest 1.0.0.0    WindowsDeveloperLicense                  
    Script 1.0        WindowsErrorReporting                    
  Manifest 1.0.0.0    WindowsSearch                            
  Manifest 1.0.0.0    WindowsUpdate                            
  Manifest 1.0.0.2    WindowsUpdateProvider                    
  Manifest 15.0       SQLPS
```

## Error output
```
   HistoryId: 21


Message        : Cannot bind argument to parameter 'MatchValue' because it is null.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type 
                 argumentType, Object parameterValue, Boolean recurseIntoCollections)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, 
                 ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, 
                 ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, 
                 MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] 
                 pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {New-AzCdnDeliveryRuleCondition}
Line           :                 -Condition (New-AzCdnDeliveryRuleCondition -MatchVariable RequestHeader -Selector "x-header" -Operator Any -MatchValue $null) `
                 
Position       : At C:\Users\...\PowerShell\MyScript.ps1:165 char:140
                 + ... estHeader -Selector "x-header" -Operator Any -MatchValue $null) `
                 +                                                                  ~~~~~
HistoryId      : 21

   HistoryId: 20


Message        : Cannot bind argument to parameter 'MatchValue' because it is an empty array.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.ValidateNullOrEmptyArgument(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, Type 
                 argumentType, Object parameterValue, Boolean recurseIntoCollections)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, 
                 ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, 
                 ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, 
                 MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] 
                 pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {New-AzCdnDeliveryRuleCondition}
Line           :                 -Condition (New-AzCdnDeliveryRuleCondition -MatchVariable RequestHeader -Selector "x-header" -Operator Any -MatchValue @()) `
                 
Position       : At C:\Users\...\PowerShell\MyScript.ps1:165 char:140
                 + ... questHeader -Selector "x-header" -Operator Any -MatchValue @()) `
                 +                                                                    ~~~
HistoryId      : 20

Resolve-AzError : Input string was not in a correct format.
At line:1 char:1
+ Resolve-AzError
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Resolve-AzError], FormatException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.Errors.ResolveError
```

**Comment by dingmeng-xue** [comment]
CDN team, the doc should describe the supported operator. In addition, how can it support isNull? It will be great if there is example on reference doc.

**Comment by SaurabhSharma-MSFT** [comment]
@richardhauer Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by richardhauer** [comment]
@SaurabhSharma-MSFT 
I don't know if there has been any updates to the API in the preceding 10 months to address this issue, probably not but worth a look.

We worked around the issue by using the HTTP API directly and bypassing the PowerShell commandlet.  That's painful, so not really a "fix" insofar as "it doesn't work so we fixed it by not using it".

**Comment by navba-MSFT** [comment]
@richardhauer Thanks for your reply. You can try the test using the [CLI command ](https://docs.microsoft.com/en-us/cli/azure/cdn/endpoint/rule/condition?view=azure-cli-latest#az-cdn-endpoint-rule-condition-add) and check if that helps. Since this github thread is idle, we will proceed with closure. If this issue is a blocker and causing an impact feel free to reopen this thread. We would be happy to investigate further on this.
