### ISSUE TITLE
Connect-AzAccount Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'

### ISSUE THREAD

**Issue by YuriySamorodov** [Azure/azure-powershell#14004]
## Description

`Connect-AzAccount` produces an error:
```
WARNING: Unable to acquire token for tenant 'organizations'
Connect-AzAccount: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.
```
![image](https://user-images.githubusercontent.com/5260172/105555499-924d3b80-5d1a-11eb-8f5c-e95acb415127.png)

## Steps to reproduce

```powershell
Connect-AzAccount --UseDeviceAuthentication
Connect-AzAccount -CertificateThumbprint $cert.Thumbprint -ApplicationId $clientid -Tenant $tenantid
```

## Environment data

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.2
PSEdition                      Core
GitCommitId                    7.2.0-preview.2
OS                             Microsoft Windows 10.0.21292
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell

Name              : Az.Accounts
Path              : C:\Program Files\PowerShell\Modules\Az.Accounts\2.2.4\Az.Accounts.psm1
Description       : Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.
                    
                    For more information on account credential management, please visit the following: https://docs.microsoft.com/powershell/azure/authenticate-azureps
ModuleType        : Script
Version           : 2.2.4
PreRelease        : 
NestedModules     : {Microsoft.Azure.PowerShell.Cmdlets.Accounts}
ExportedFunctions : 
ExportedCmdlets   : {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
ExportedVariables : 
ExportedAliases   : {Add-AzAccount, Get-AzDomain, Invoke-AzRest, Login-AzAccount…}
```

## Debug output
```
Connect-AzAccount -UseDeviceAuthentication
DEBUG: 1:34:24 AM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 1:34:24 AM - Autosave setting from startup session: 'Process'
DEBUG: 1:34:24 AM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 1:34:24 AM - Using Autosave scope 'Process'
WARNING: Unable to acquire token for tenant 'organizations'
Connect-AzAccount: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.
DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:00.0191882; Exception - System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.
File name: 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.IsTransientException(Exception e)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_2.<ExecuteCmdlet>b__4()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass111_0.<ExecuteCmdlet>b__1(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass118_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:34:24 AM - ConnectAzureRmAccountCommand end processing.
```

## Error output

```
WARNING: INITIALIZATION: Fallback context save mode to process because of error during checking token cache persistence: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Could not find or load a specific file. (0x80131621).
Connect-AzAccount: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. The system cannot find the file specified.
```

**Comment by dingmeng-xue** [comment]
@YuriySamorodov , Thanks for reporting. This issue cannot be reproduced on a clean installed PowerShell 7.2.0-preview.2. 

Please share loaded assemblies via below code before executing `Connect-AzAccount`
```
[System.AppDomain]::CurrentDomain.GetAssemblies()
```

**Comment by YuriySamorodov** [comment]
```

GAC    Version        Location
---    -------        --------
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Private.CoreLib.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\pwsh.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Runtime.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Microsoft.PowerShell.ConsoleHost.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Management.Automation.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Threading.Thread.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Runtime.InteropServices.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Threading.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Diagnostics.Process.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Microsoft.Win32.Primitives.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.ComponentModel.Primitives.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Collections.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Collections.NonGeneric.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Xml.ReaderWriter.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Private.Xml.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.Cryptography.X509Certificates.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.Cryptography.Encoding.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Net.Primitives.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Net.Mail.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Linq.Expressions.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Text.Encoding.Extensions.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Collections.Concurrent.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Microsoft.Management.Infrastructure.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Runtime.Numerics.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Text.RegularExpressions.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Private.Uri.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Diagnostics.FileVersionInfo.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Management.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.IO.FileSystem.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.DirectoryServices.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.AccessControl.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Microsoft.Win32.Registry.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Net.NetworkInformation.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.Cryptography.Primitives.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Newtonsoft.Json.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\netstandard.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.ComponentModel.TypeConverter.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.ObjectModel.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Runtime.Serialization.Formatters.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Diagnostics.TraceSource.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Linq.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Runtime.Serialization.Primitives.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Data.Common.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.ComponentModel.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Reflection.Emit.ILGeneration.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Reflection.Primitives.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Reflection.Emit.Lightweight.dll
False  v4.0.30319     
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Microsoft.PowerShell.CoreCLR.Eventing.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Memory.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Collections.Specialized.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Runtime.InteropServices.RuntimeInformation.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Microsoft.ApplicationInsights.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Diagnostics.DiagnosticSource.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Diagnostics.Tracing.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Xml.XDocument.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Private.Xml.Linq.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Net.NameResolution.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Console.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.Principal.Windows.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.Claims.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.IO.Pipes.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\Microsoft.PowerShell.Security.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Threading.Tasks.Parallel.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.IO.FileSystem.DriveInfo.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.IO.FileSystem.AccessControl.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Text.Encoding.CodePages.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.Permissions.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Security.Cryptography.Algorithms.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Threading.Overlapped.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Runtime.Loader.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Threading.ThreadPool.dll
False  v4.0.30319     C:\Program Files\PowerShell\Modules\PSReadLine\2.1.0\Microsoft.PowerShell.PSReadLine2.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\mscorlib.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Core.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Net.Http.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Net.Security.dll
False  v4.0.30319     C:\Program Files\PowerShell\7-preview\System.Net.Sockets.dll
```

**Comment by dingmeng-xue** [comment]
We cannot reproduce this issue. Please remove Az.Accounts and install it again.
```
PS C:\Dev\PowerShell-7.2.0-preview.2-win-x64> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0-preview.2
PSEdition                      Core
GitCommitId                    7.2.0-preview.2
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS C:\Dev\PowerShell-7.2.0-preview.2-win-x64> Connect-AzAccount -UseDeviceAuthentication
WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ****** to authenticate.
......

PS C:\Dev\PowerShell-7.2.0-preview.2-win-x64> get-module az.accounts

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.4                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…

```

**Comment by StefanSchoof** [comment]
I have the same error. But only if I load the [PartnerCenter](https://www.powershellgallery.com/packages/PartnerCenter/3.0.10) powershell module.
```powershell
PS > Import-Module PartnerCenter
PS > Login-AzAccount
WARNING: INITIALIZATION: Fallback context save mode to process because of error during checking token cache persistence: Could not load file or assembly 'Microsoft.Identity.Client.Extensions.Msal, Version=2.16.2.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Das System kann die angegebene Datei nicht finden..
Connect-AzAccount: Could not load file or assembly 'Microsoft.Identity.Client, Version=4.21.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'. Das System kann die angegebene Datei nicht finden.
```
In a new session:

```powershell
PS >Login-AzAccount

Account                        SubscriptionName    TenantId                             Environment
-------                        ----------------    --------                             -----------
myname@domain.ext name <guid> AzureCloud

PS > Import-Module PartnerCenter
Import-Module: Assembly with same name is already loaded
```

**Comment by StefanSchoof** [comment]
I downgraded to `Az.Accounts` below 2 (1.9.5) and I am able to load both modules. A downgrade of `PartnerCenter` did not help.

**Comment by YuriySamorodov** [comment]
It's working without me doing anything

**Comment by pmsousa** [comment]
@dingmeng-xue 
I have the exact same issue. Only when module PartnerCenter is loaded, the Connect-AzAccount fails with that error message. If the module is not loaded, it works fine.
@StefanSchoof, what version of Az.Accounts did you have prior to the downgrade? do you remember?

**Comment by madsaune** [comment]
I'm having the same issue. If i run `Connect-AzAccount` before importing PartnerCenter, the Az module works, but then I cannot import PartnerCenter. But if I import PartnerCenter module first I get no import error, but now the `Connect-AzAccount` wont work. I have testet with `Get-AzContext` too and its the same result.

Running Az first:
```powershell
PS > Connect-AzAccount

Account             SubscriptionName TenantId                             Environment
-------             ---------------- --------                             -----------
john.doe@contoso.com subscription 1      xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx AzureCloud
PS > Import-Module PartnerCenter -Force
Import-Module: Assembly with same name is already loaded
```

Importing PartnerCenter first:
```powershell
```
