### ISSUE TITLE
"Add Resource" to environment script fails "SSL connection could not be established"

### ISSUE THREAD

**Issue by PatrickGrub** [Azure/azure-powershell#14097]
## Description

When I execute the script for adding a new Resource (virtual machine) to my environment the script fails:

![image](https://user-images.githubusercontent.com/36075173/106582635-81839d80-6544-11eb-8b66-a1d630af30de.png)

Log file

```
[2021-02-02 09:54:22Z INFO Terminal] WRITE LINE: 
  ___                      ______ _            _ _
 / _ \                     | ___ (_)          | (_)
/ /_\ \_____   _ _ __ ___  | |_/ /_ _ __   ___| |_ _ __   ___  ___
|  _  |_  / | | | '__/ _ \ |  __/| | '_ \ / _ \ | | '_ \ / _ \/ __|
| | | |/ /| |_| | | |  __/ | |   | | |_) |  __/ | | | | |  __/\__ \
\_| |_/___|\__,_|_|  \___| \_|   |_| .__/ \___|_|_|_| |_|\___||___/
                                   | |
        agent v2.181.1             |_|          (commit 612c962)

[2021-02-02 09:54:22Z INFO ConfigurationManager] CheckAgentRootDirectorySecure
[2021-02-02 09:54:22Z INFO HostContext] Well known directory 'Bin': 'C:\azagent\A3\bin'
[2021-02-02 09:54:22Z INFO HostContext] Well known directory 'Root': 'C:\azagent\A3'
[2021-02-02 09:54:22Z INFO ConfigurationManager] ConfigureAsync
[2021-02-02 09:54:22Z INFO ConfigurationStore] IsConfigured()
[2021-02-02 09:54:22Z INFO ConfigurationStore] IsConfigured: False
[2021-02-02 09:54:22Z INFO ConfigurationManager] Is configured: False
[2021-02-02 09:54:22Z INFO CommandSettings] Flag 'sslskipcertvalidation': 'False'
[2021-02-02 09:54:22Z INFO ConfigurationManager] Testing for min NET Framework version: '4.6'
[2021-02-02 09:54:22Z INFO CommandSettings] Flag 'deploymentgroup': 'False'
[2021-02-02 09:54:22Z INFO CommandSettings] Flag 'deploymentpool': 'False'
[2021-02-02 09:54:22Z INFO CommandSettings] Flag 'environment': 'True'
[2021-02-02 09:54:22Z INFO ExtensionManager] Getting extensions for interface: 'Microsoft.VisualStudio.Services.Agent.Listener.Configuration.IConfigurationProvider'
[2021-02-02 09:54:22Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.BuildReleasesAgentConfigProvider, Agent.Listener
[2021-02-02 09:54:22Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.DeploymentGroupAgentConfigProvider, Agent.Listener
[2021-02-02 09:54:22Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.SharedDeploymentAgentConfigProvider, Agent.Listener
[2021-02-02 09:54:22Z INFO ExtensionManager] Creating instance: Microsoft.VisualStudio.Services.Agent.Listener.Configuration.EnvironmentVMResourceConfigProvider, Agent.Listener
[2021-02-02 09:54:22Z INFO Terminal] WRITE LINE: 
[2021-02-02 09:54:22Z INFO Terminal] WRITE LINE: >> Connect:
[2021-02-02 09:54:22Z INFO Terminal] WRITE LINE: 
[2021-02-02 09:54:22Z INFO CommandSettings] Arg 'url': 'https://dev.azure.com/CoolOrange/'
[2021-02-02 09:54:22Z INFO EnvironmentVMResourceConfigProvider] url - https://dev.azure.com/CoolOrange/
[2021-02-02 09:54:22Z INFO ConfigurationManager] GetCredentialProvider
[2021-02-02 09:54:22Z INFO CommandSettings] Arg 'auth': 'PAT'
[2021-02-02 09:54:22Z INFO ConfigurationManager] Creating credential for auth: PAT
[2021-02-02 09:54:22Z INFO CredentialManager] GetCredentialProvider
[2021-02-02 09:54:22Z INFO CredentialManager] Creating type PAT
[2021-02-02 09:54:22Z INFO CredentialManager] Creating credential type: PAT
[2021-02-02 09:54:22Z INFO PersonalAccessToken] EnsureCredential
[2021-02-02 09:54:22Z INFO CommandSettings] Arg 'token': '***'
[2021-02-02 09:54:22Z INFO PersonalAccessToken] GetVssCredentials
[2021-02-02 09:54:22Z INFO PersonalAccessToken] token retrieved: 52 chars
[2021-02-02 09:54:22Z INFO PersonalAccessToken] cred created
[2021-02-02 09:54:22Z INFO ConfigurationManager] cred retrieved
[2021-02-02 09:54:22Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2021-02-02 09:54:23Z ERR  VisualStudioServices] GET request to https://dev.azure.com/CoolOrange/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1 failed. System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Common.VssHttpRetryMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

## Environment data

![image](https://user-images.githubusercontent.com/36075173/106585667-dc6ac400-6547-11eb-9aa6-65d0fd668cd5.png)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It seems the issue is not related to Azure PowerShell. We will try to find the correct place and get back to you.

**Comment by dingmeng-xue** [comment]
@PatrickGrub , the correct place is https://github.com/microsoft/azure-pipelines-agent. Since it is in the different org from Azure, I cannot move this issue. Please close this one and create new one on Azure Pipelines Agent. Sorry for the inconvenience.

**Comment by PatrickGrub** [comment]
Thanks for the quick response, I have created https://github.com/microsoft/azure-pipelines-agent/issues/3236
