### ISSUE TITLE
Get-AzVirtualNetwork: $expand query option value is invalid.

### ISSUE THREAD

**Issue by SadokLadhari** [Azure/azure-powershell#14169]
## Description

Executing  _Get-AzVirtualNetwork_ **directly after** _Get-AzBlueprint_ generates this error:

Get-AzVirtualNetwork: $expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidExpandQueryOptionValue
ErrorMessage: $expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.
OperationID : 576a926e-3b2c-4cbe-98f2-2113c33e158a

For information: 

- Executing the two commands in a separate sessions is working fine
- We can reproduce the issue in the cloudshell version also

## Steps to reproduce

```powershell
Get-AzBlueprint -SubscriptionId "XXXXX"  -Name "ABC"
Get-AzVirtualNetwork -Name "VNET-NAMZ"  -ResourceGroupName "RG-NAME" 
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 202…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.0.0                 Az                                  Core,Desk 
Script     2.2.4                 Az.Accounts                         Core,Desk {Disable-AzDataCollecti…
Script     2.1.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollecti…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommend…
Script     2.0.0                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-…
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServi…
Script     2.1.0                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApi…
Script     1.1.0                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsig…
Script     1.4.0                 Az.Automation                       Core,Desk {Get-AzAutomationHybrid…
Script     3.1.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount,…
Script     2.0.0                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, …
Script     0.2.13                Az.Blueprint                        Core,Desk {Get-AzBlueprint, Get-A…
Script     1.6.0                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-…
Script     1.8.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveService…
Script     4.6.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilityS…
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, …
Script     2.0.0                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistr…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, …
Script     1.0.1                 Az.Databricks                       Core,Desk {Get-AzDatabricksVNetPe…
Script     1.11.0                Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, U…
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalytic…
Script     1.2.8                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTru…
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManage…
Script     2.0.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSe…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSize…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, Ne…
Script     1.3.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, …
Script     1.7.0                 Az.EventHub                         Core,Desk {New-AzEventHubNamespac…
Script     1.6.1                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-A…
Script     2.0.0                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get…
Script     4.0.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, Ne…
Script     1.1.0                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisSe…
Script     2.6.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-A…
Script     3.0.0                 Az.KeyVault                         Core,Desk {Add-AzManagedHsmKey, G…
Script     1.0.0                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLang…
Script     1.3.2                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccou…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAss…
Script     1.1.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get…
Script     2.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesA…
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms…
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceSto…
Script     2.2.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition…
Script     4.1.0                 Az.Network                          Core,Desk {Add-AzApplicationGatew…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub,…
Script     2.3.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsig…
Script     1.3.1                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get…
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorksp…
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, …
Script     3.0.0                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServices…
Script     1.4.0                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePat…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, …
Script     3.0.0                 Az.Resources                        Core,Desk {Get-AzProviderOperatio…
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamesp…
Script     2.2.0                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricCli…
Script     1.2.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzS…
Script     2.11.1                Az.Sql                              Core,Desk {Get-AzSqlDatabaseTrans…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSql…
Script     3.0.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, …
Script     1.3.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCo…
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsF…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, …
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCu…
Script     2.0.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, …
Script     5.1.1                 Pester                              Desk      {Invoke-Pester, Describ…

    Directory: /usr/local/microsoft/powershell/7/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expa…
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Con…
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-Ex…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alia…
Script     1.4.7                 PackageManagement                   Desk      {Find-Package, Get-Pack…
Script     2.2.5                 PowerShellGet                       Desk      {Find-Command, Find-DSC…
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-Dsc…
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandl…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob
```

## Debug output

```
DEBUG: 23:27:19 - GetAzureVirtualNetworkCommand begin processing with ParameterSet 'NoExpand'.
DEBUG: 23:27:19 - using account id 'xxxxx'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxx', environment: 'AzureCloud', tenant: 'xxxxx'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: Request [f4a4deda-7cf6-44df-8235-109e9a30fc7e] POST https://login.microsoftonline.com/xxxxx/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:f4a4deda-7cf6-44df-8235-109e9a30fc7e
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0-beta.1,(.NET 5.0.0; Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64)
client assembly: Azure.Identity
DEBUG: Response [f4a4deda-7cf6-44df-8235-109e9a30fc7e] 200 OK (00.6s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Set-Cookie:REDACTED
Date:Tue, 09 Feb 2021 22:27:19 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1360

DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-02-09T23:27:18.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxx', UserId: 'xxxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/ec0ed866-3ff1-407e-8171-9037ec6600b4/resourceGroups/RESERVED-FOR-IT-SRE-DEMO/providers/Microsoft.Network/virtualNetworks/mvp-main-vnet?api-version=2020-06-01

Headers:
x-ms-client-request-id        : 8438d158-a6c6-4f07-a6d7-0f00966e37db
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : W/"b65517ea-3a8a-411d-843e-fac109327606"
x-ms-request-id               : e9baf47a-3d8d-4092-992c-31209b4a91d0
x-ms-correlation-request-id   : f72b3686-d175-4e79-8e1f-c400219aa3fd
x-ms-arm-service-request-id   : 83783899-550a-4bec-88f5-5593f96a5198
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11997
x-ms-routing-request-id       : SWITZERLANDNORTH:20210209T222720Z:f72b3686-d175-4e79-8e1f-c400219aa3fd
X-Content-Type-Options        : nosniff
Date                          : Tue, 09 Feb 2021 22:27:20 GMT

Body:
{
  "error": {
    "code": "InvalidExpandQueryOptionValue",
    "message": "$expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.",
    "details": []
  }
}


Get-AzVirtualNetwork: $expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidExpandQueryOptionValue
ErrorMessage: $expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.
OperationID : e9baf47a-3d8d-4092-992c-31209b4a91d0
DEBUG: AzureQoSEvent: CommandName - Get-AzVirtualNetwork; IsSuccess - False; Duration - 00:00:01.7616227; Exception - Microsoft.Azure.Commands.Network.Common.NetworkCloudException: $expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidExpandQueryOptionValue
ErrorMessage: $expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.
OperationID : e9baf47a-3d8d-4092-992c-31209b4a91d0
 ---> Microsoft.Rest.Azure.CloudException: $expand query option value is invalid. The resource does not have property versions or the property does not represent a reference to another resource.
   at Microsoft.Azure.Management.Network.VirtualNetworksOperations.GetWithHttpMessagesAsync(String resourceGroupName, String virtualNetworkName, String expand, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.VirtualNetworksOperationsExtensions.GetAsync(IVirtualNetworksOperations operations, String resourceGroupName, String virtualNetworkName, String expand, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.VirtualNetworksOperationsExtensions.Get(IVirtualNetworksOperations operations, String resourceGroupName, String virtualNetworkName, String expand)
   at Microsoft.Azure.Commands.Network.VirtualNetworkBaseCmdlet.GetVirtualNetwork(String resourceGroupName, String name, String expandResource)
   at Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkCommand.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 23:27:22 - GetAzureVirtualNetworkCommand end processing.
```

## Error output

```
PS /Users/sadoklaadhari> Resolve-AzError
DEBUG: 23:30:48 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 23:30:48 - using account id 'xxxxx'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 13

RequestId      : 
Message        : $expand query option value is invalid. The resource does not have property versions 
                 or the property does not represent a reference to another resource.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: InvalidExpandQueryOptionValue
                 ErrorMessage: $expand query option value is invalid. The resource does not have 
                 property versions or the property does not represent a reference to another resource.
                 OperationID : e9baf47a-3d8d-4092-992c-31209b4a91d0
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Get-AzVirtualNetwork}
Line           : Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName 
                 "xxxxx" 
Position       : At line:1 char:1
                 + Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName "RESER …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<Exec
                 uteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 13


   HistoryId: 9

RequestId      : 
Message        : $expand query option value is invalid. The resource does not have property versions 
                 or the property does not represent a reference to another resource.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: InvalidExpandQueryOptionValue
                 ErrorMessage: $expand query option value is invalid. The resource does not have 
                 property versions or the property does not represent a reference to another resource.
                 OperationID : 576a926e-3b2c-4cbe-98f2-2113c33e158a
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Get-AzVirtualNetwork}
Line           : Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName 
                 "xxxxx" 
Position       : At line:1 char:1
                 + Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName "RESER …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<Exec
                 uteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 9


   HistoryId: 6

RequestId      : 
Message        : $expand query option value is invalid. The resource does not have property versions 
                 or the property does not represent a reference to another resource.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: InvalidExpandQueryOptionValue
                 ErrorMessage: $expand query option value is invalid. The resource does not have 
                 property versions or the property does not represent a reference to another resource.
                 OperationID : 5c7e2c6d-27b6-42a5-a884-5616be7053c5
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Get-AzVirtualNetwork}
Line           : Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName 
                 "xxxxx" -ExpandResource 'subnets/ipConfigurations'
Position       : At line:1 char:1
                 + Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName "RESER …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<Exec
                 uteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 6


   HistoryId: 3

RequestId      : 
Message        : $expand query option value is invalid. The resource does not have property versions 
                 or the property does not represent a reference to another resource.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: InvalidExpandQueryOptionValue
                 ErrorMessage: $expand query option value is invalid. The resource does not have 
                 property versions or the property does not represent a reference to another resource.
                 OperationID : 683b338e-57a5-479a-91f7-d931a89acb92
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Get-AzVirtualNetwork}
Line           : Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName 
                 "xxxxx" -ExpandResource 'subnets/ipConfigurations'
Position       : At line:1 char:1
                 + Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName "RESER …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<Exec
                 uteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 3


   HistoryId: 2

RequestId      : 
Message        : $expand query option value is invalid. The resource does not have property versions 
                 or the property does not represent a reference to another resource.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: InvalidExpandQueryOptionValue
                 ErrorMessage: $expand query option value is invalid. The resource does not have 
                 property versions or the property does not represent a reference to another resource.
                 OperationID : 178ccd14-de08-4ee6-9046-03ea1094ab7c
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Get-AzVirtualNetwork}
Line           : Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName 
                 "xxxxx" -ExpandResource 'subnets/ipConfigurations'
Position       : At line:1 char:1
                 + Get-AzVirtualNetwork -Name "xxxxx"  -ResourceGroupName "RESER …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<Exec
                 uteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchro
                 nouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 2


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.0256541
DEBUG: Finish sending metric.
DEBUG: 23:30:49 - ResolveError end processing.
```

**Comment by SadokLadhari** [comment]
Any news about this please ?
