### ISSUE TITLE
PowerShell 7.2.0-preview.3 MSIX - crashes Az.Tools.Predictor

### ISSUE THREAD

**Issue by brwilkinson** [Azure/azure-powershell#14259]
## Description

This was working great until the upgrade.

After having the store update my powershell preview version to preview 3 . .  az.tool.predictor breaks .. as below.

**Method 'StartEarlyProcessing' in type 'Microsoft.Azure.PowerShell.Tools.AzPredictor.AzPredictor' from assembly 'Microsoft.Azure.PowerShell.Tools.AzPredictor, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.**

```powershell
Import-Module: D:\OneDrive\profile.ps1:51
Line |
  51 |          Import-Module -Name Az.Tools.Predictor
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method 'StartEarlyProcessing' in type 'Microsoft.Azure.PowerShell.Tools.AzPredictor.AzPredictor' from
     | assembly 'Microsoft.Azure.PowerShell.Tools.AzPredictor, Version=0.1.0.0, Culture=neutral,
     | PublicKeyToken=null' does not have an implementation.
```

## Steps to reproduce

```powershell

Import-Module -Name Az.Tools.Predictor

```

```powershell
Name                       : Az.Tools.Predictor
Version                    : 0.1.0

PowerShell 7.2.0-preview.3 MSIX (store install)

Script     2.2.0      beta1      PSReadLine
```

after that psreadline cannot run

```powershell
Oops, something went wrong.
Please report this bug with ALL the details below, including both the 'Environment' and 'Exception' sections.
Please report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
Thank you!

### Environment
PSReadLine: 2.2.0-beta1
PowerShell: 7.2.0-preview.3
OS: Microsoft Windows 10.0.21301
BufferWidth: 203
BufferHeight: 56


### Exception

System.MissingMethodException: Method not found: 'Void System.Management.Automation.Subsystem.CommandPrediction.OnCommandLineAccepted(System.Collections.Generic.IReadOnlyList`1<System.String>)'.
   at Microsoft.PowerShell.PSConsoleReadLine.Microsoft.PowerShell.Internal.IPSConsoleReadLineMockableMethods.OnCommandLineAccepted(IReadOnlyList`1 history)
   at Microsoft.PowerShell.PSConsoleReadLine.PredictionViewBase.OnCommandLineAccepted(String commandLine)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

**Comment by dingmeng-xue** [comment]
@kceiw , please help to evaluate this question.

**Comment by kceiw** [comment]
Hi @brwilkinson. Thanks for reporting the issue. The API we're using is in preview and it's changed in PowerShell 7.2.0 preview.3. The new API helps us in improve user experience. We would like to avoid this kind of interruption as much as possible. This issue will be fixed when we release Az.Tools.Predictor 0.2.0 with this [PR](https://github.com/Azure/azure-powershell/pull/14041).

**Comment by kceiw** [comment]
The fix is released https://www.powershellgallery.com/packages/Az.Tools.Predictor/0.2.0.
I'll close this issue.
