### ISSUE TITLE
Unable to deserialize the reponse with Get-AzAutomationSoftwareUpdateConfiguration

### ISSUE THREAD

**Issue by bwarren18** [Azure/azure-powershell#14604]
## Description
I am upgraded to Az 5.6.0 from 5.5.0 and get an error now with Get-AzAutomationSoftwareUpdateConfiguration in one of my automation accounts.  It only happens with one of out Automation Accounts, the rest work fine.  

## Steps to reproduce
```powershell
Get-AzAutomationSoftwareUpdateConfiguration -ResourceGroupName $rgname-AutomationAccountName $aaName
```

## Environment data
```powershell
Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.19041.610                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.19041.610                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1    
```

## Module versions

```powershell

    Directory: C:\Users\username\OneDrive\myfiles\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Script     2.2.6      Az.Accounts                         {Disable-AzDataCollection, Disab...
Script     1.1.1      Az.Advisor                          {Get-AzAdvisorRecommendation, En...
Script     2.0.2      Az.Aks                              {Get-AzAksCluster, New-AzAksClus...
Script     1.1.4      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer...
Script     2.2.0      Az.ApiManagement                    {Add-AzApiManagementApiToGateway...
Script     1.0.0      Az.AppConfiguration                 {Get-AzAppConfigurationStore, Ge...
Script     1.1.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-...
Script     1.5.0      Az.Automation                       {Get-AzAutomationHybridWorkerGro...
Script     3.1.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBa...
Script     2.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBil...
Script     1.6.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProf...
Script     1.8.0      Az.CognitiveServices                {Get-AzCognitiveServicesAccount,...
Script     4.10.0     Az.Compute                          {Remove-AzAvailabilitySet, Get-A...
Script     1.0.3      Az.ContainerInstance                {New-AzContainerGroup, Get-AzCon...
Script     2.2.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-Az...
Script     1.1.0      Az.CosmosDB                         {Get-AzCosmosDBSqlContainer, Get...
Script     1.1.0      Az.DataBoxEdge                      {Get-AzDataBoxEdgeJob, Get-AzDat...
Script     1.1.0      Az.Databricks                       {Get-AzDatabricksVNetPeering, Ge...
Script     1.11.4     Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzD...
Script     1.0.2      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSour...
Script     1.3.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdPro...
Script     1.0.0      Az.DataShare                        {New-AzDataShareAccount, Get-AzD...
Script     1.1.0      Az.DeploymentManager                {Get-AzDeploymentManagerArtifact...
Script     2.1.1      Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Ex...
Script     1.0.2      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, ...
Script     1.1.2      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRe...
Script     1.3.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEve...
Script     1.7.1      Az.EventHub                         {New-AzEventHubNamespace, Get-Az...
Script     1.7.0      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFrontDoo...
Script     2.0.0      Az.Functions                        {Get-AzFunctionApp, Get-AzFuncti...
Script     4.2.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDIns...
Script     1.2.0      Az.HealthcareApis                   {New-AzHealthcareApisService, Re...
Script     2.7.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEv...
Script     3.4.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Upda...
Script     1.0.1      Az.Kusto                            {Add-AzKustoClusterLanguageExten...
Script     1.5.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreeme...
Script     1.1.3      Az.MachineLearning                  {Move-AzMlCommitmentAssociation,...
Script     1.1.0      Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfig...
Script     2.0.0      Az.ManagedServices                  {Get-AzManagedServicesAssignment...
Script     1.0.2      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzM...
Script     1.1.1      Az.Media                            {Sync-AzMediaServiceStorageKey, ...
Script     1.0.0      Az.Migrate                          {Get-AzMigrateDiscoveredServer, ...
Script     2.4.0      Az.Monitor                          {Get-AzMetricDefinition, Get-AzM...
Script     4.6.0      Az.Network                          {Add-AzApplicationGatewayAuthent...
Script     1.1.1      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNo...
Script     2.3.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureA...
Script     1.4.1      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicy...
Script     1.1.2      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollec...
Script     1.0.3      Az.PrivateDns                       {Get-AzPrivateDnsZone, Remove-Az...
Script     3.4.1      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupPro...
Script     1.4.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedul...
Script     1.0.3      Az.Relay                            {New-AzRelayNamespace, Get-AzRel...
Script     3.3.0      Az.Resources                        {Get-AzProviderOperation, Remove...
Script     1.4.1      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-...
Script     2.2.2      Az.ServiceFabric                    {Add-AzServiceFabricClientCertif...
Script     1.2.0      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, G...
Script     2.16.0     Az.Sql                              {Get-AzSqlDatabaseTransparentDat...
Script     1.1.0      Az.SqlVirtualMachine                {New-AzSqlVM, Get-AzSqlVM, Updat...
Script     3.4.0      Az.Storage                          {Get-AzStorageAccount, Get-AzSto...
Script     1.4.0      Az.StorageSync                      {Invoke-AzStorageSyncCompatibili...
Script     1.0.1      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, ...
Script     1.0.0      Az.Support                          {Get-AzSupportService, Get-AzSup...
Script     1.0.4      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeade...
Script     2.4.0      Az.Websites                         {Get-AzAppServicePlan, Set-AzApp...
Binary     2.0.2.130  AzureAD                             {Add-AzureADApplicationOwner, Ge...
Script     1.0.113    dbatools                            {Select-DbaObject, Set-DbatoolsC...
Script     7.1.1      ImportExcel                         {Add-ConditionalFormatting, Add-...
Script     1.4.7      PackageManagement                   {Find-Package, Get-Package, Get-...
Script     4.0.0      Selenium                            {Clear-SeAlert, Clear-SeSelectVa...


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke...
Script     1.0.0.0    Microsoft.SME.CredSspPolicy                                            
Script     1.3.1      PackageManagement                   {Find-Package, Get-Package, Get-...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-...
Script     4.7.3      Pester                              {Describe, Context, It, Should...} 
Script     3.4.0      Pester                              {Describe, Context, It, Should...} 
Script     2.1.2      PowerShellGet                       {Find-Command, Find-DSCResource,...
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Sa...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Set-P...
Script     2.31.0     PuppetBolt                          {bolt, Add-BoltModule, Convert-B...
Script     1.18.1     PuppetDevelopmentKit                pdk                                
Script     1.0        RemoteDesktopManager.PowerShellM...                                    
Script     1.0.12     SpeculationControl                  Get-SpeculationControlSettings     


    Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Manifest   1.0.1.0    ActiveDirectory                     {Add-ADCentralAccessPolicyMember...
Manifest   1.0.0.0    AppBackgroundTask                   {Disable-AppBackgroundTaskDiagno...
Manifest   2.0.0.0    AppLocker                           {Get-AppLockerFileInformation, G...
Manifest   1.0.0.0    AppvClient                          {Add-AppvClientConnectionGroup, ...
Manifest   2.0.1.0    Appx                                {Add-AppxPackage, Get-AppxPackag...
Script     1.0.0.0    AssignedAccess                      {Clear-AssignedAccess, Get-Assig...
Manifest   1.0        BestPractices                       {Get-BpaModel, Get-BpaResult, In...
Manifest   1.0.0.0    BitLocker                           {Unlock-BitLocker, Suspend-BitLo...
Manifest   2.0.0.0    BitsTransfer                        {Add-BitsFile, Complete-BitsTran...
Manifest   1.0.0.0    BranchCache                         {Add-BCDataCacheExtension, Clear...
Manifest   1.0.0.0    CimCmdlets                          {Get-CimAssociatedInstance, Get-...
Manifest   1.0        ConfigCI                            {Get-SystemDriver, New-CIPolicyR...
Manifest   1.0        ConfigDefender                      {Get-MpPreference, Set-MpPrefere...
Manifest   1.0        Defender                            {Get-MpPreference, Set-MpPrefere...
Manifest   1.0.2.0    DeliveryOptimization                {Delete-DeliveryOptimizationCach...
Manifest   1.0.0.0    DirectAccessClientComponents        {Disable-DAManualEntryPointSelec...
Script     3.0        Dism                                {Add-AppxProvisionedPackage, Add...
Manifest   1.0.0.0    DnsClient                           {Resolve-DnsName, Clear-DnsClien...
Manifest   1.0.0.0    EventTracingManagement              {Start-EtwTraceSession, New-EtwT...
Manifest   2.0.0.0    International                       {Get-WinDefaultInputMethodOverri...
Manifest   1.0.0.0    iSCSI                               {Get-IscsiTargetPortal, New-Iscs...
Manifest   2.0.0.0    IscsiTarget                         {Add-ClusteriSCSITargetServerRol...
Script     1.0.0.0    ISE                                 {New-IseSnippet, Import-IseSnipp...
Manifest   1.0.0.0    Kds                                 {Add-KdsRootKey, Get-KdsRootKey,...
Manifest   1.0.1.0    Microsoft.PowerShell.Archive        {Compress-Archive, Expand-Archive} 
Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics    {Get-WinEvent, Get-Counter, Impo...
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript, Stop-Transcript}
Manifest   1.0.0.0    Microsoft.PowerShell.LocalAccounts  {Add-LocalGroupMember, Disable-L...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Cle...
Script     1.0        Microsoft.PowerShell.ODataUtils     Export-ODataEndpointProxy          
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {Get-Acl, Set-Acl, Get-PfxCertif...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Format-List, Format-Custom, For...
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Disable-WSManCredSSP, Enable-WS...
Manifest   1.0        MMAgent                             {Disable-MMAgent, Enable-MMAgent...
Manifest   1.0.0.0    MsDtc                               {New-DtcDiagnosticTransaction, C...
Binary     1.0.0.0    MSMQ                                {Clear-MsmqOutgoingQueue, Clear-...
Manifest   2.0.0.0    NetAdapter                          {Disable-NetAdapter, Disable-Net...
Manifest   1.0.0.0    NetConnection                       {Get-NetConnectionProfile, Set-N...
Manifest   1.0.0.0    NetDiagnostics                      Get-NetView                        
Manifest   1.0.0.0    NetEventPacketCapture               {New-NetEventSession, Remove-Net...
Manifest   2.0.0.0    NetLbfo                             {Add-NetLbfoTeamMember, Add-NetL...
Manifest   1.0        NetLldpAgent                        {Enable-NetLldpAgent, Disable-Ne...
Manifest   1.0.0.0    NetNat                              {Get-NetNat, Get-NetNatExternalA...
Manifest   2.0.0.0    NetQos                              {Get-NetQosPolicy, Set-NetQosPol...
Manifest   2.0.0.0    NetSecurity                         {Get-DAPolicyChange, New-NetIPse...
Manifest   1.0.0.0    NetSwitchTeam                       {New-NetSwitchTeam, Remove-NetSw...
Manifest   1.0.0.0    NetTCPIP                            {Get-NetIPAddress, Get-NetIPInte...
Manifest   1.0.0.0    NetworkConnectivityStatus           {Get-DAConnectionStatus, Get-NCS...
Manifest   1.0.0.0    NetworkControllerDiagnostics        {Get-NetworkControllerDeployment...
Manifest   1.0.0.0    NetworkSwitchManager                {Disable-NetworkSwitchEthernetPo...
Manifest   1.0.0.0    NetworkTransition                   {Add-NetIPHttpsCertBinding, Disa...
Manifest   1.0        NFS                                 {Get-NfsMappedIdentity, Get-NfsN...
Manifest   1.0.0.0    PcsvDevice                          {Get-PcsvDevice, Start-PcsvDevic...
Binary     1.0.0.0    PersistentMemory                    {Get-PmemDisk, Get-PmemPhysicalD...
Manifest   1.0.0.0    PKI                                 {Add-CertificateEnrollmentPolicy...
Manifest   1.0.0.0    PnpDevice                           {Get-PnpDevice, Get-PnpDevicePro...
Manifest   1.1        PrintManagement                     {Add-Printer, Add-PrinterDriver,...
Binary     1.0.12     ProcessMitigations                  {Get-ProcessMitigation, Set-Proc...
Script     3.0        Provisioning                        {Install-ProvisioningPackage, Ex...
Manifest   1.1        PSDesiredStateConfiguration         {Set-DscLocalConfigurationManage...
Script     1.0.0.0    PSDiagnostics                       {Disable-PSTrace, Disable-PSWSMa...
Binary     1.1.0.0    PSScheduledJob                      {New-JobTrigger, Add-JobTrigger,...
Manifest   2.0.0.0    PSWorkflow                          {New-PSWorkflowExecutionOption, ...
Manifest   1.0.0.0    PSWorkflowUtility                   Invoke-AsWorkflow                  
Manifest   2.0.0.0    RemoteDesktop                       {Get-RDCertificate, Set-RDCertif...
Manifest   1.0.0.0    ScheduledTasks                      {Get-ScheduledTask, Set-Schedule...
Manifest   2.0.0.0    SecureBoot                          {Confirm-SecureBootUEFI, Set-Sec...
Script     2.0.0.0    ServerManager                       {Get-WindowsFeature, Install-Win...
Cim        1.0.0.0    ServerManagerTasks                  {Get-SMCounterSample, Get-SMPerf...
Manifest   2.0.0.0    SmbShare                            {Get-SmbShare, Remove-SmbShare, ...
Manifest   2.0.0.0    SmbWitness                          {Get-SmbWitnessClient, Move-SmbW...
Manifest   1.0.0.0    StartLayout                         {Export-StartLayout, Import-Star...
Manifest   2.0.0.0    Storage                             {Add-InitiatorIdToMaskingSet, Ad...
Manifest   1.0.0.0    StorageBusCache                     {Clear-StorageBusDisk, Disable-S...
Manifest   2.0.0.0    TLS                                 {New-TlsSessionTicketKey, Enable...
Manifest   1.0.0.0    TroubleshootingPack                 {Get-TroubleshootingPack, Invoke...
Manifest   2.0.0.0    TrustedPlatformModule               {Get-Tpm, Initialize-Tpm, Clear-...
Binary     2.1.639.0  UEV                                 {Clear-UevConfiguration, Clear-U...
Manifest   2.0.0.0    VpnClient                           {Add-VpnConnection, Set-VpnConne...
Manifest   1.0.0.0    Wdac                                {Get-OdbcDriver, Set-OdbcDriver,...
Manifest   2.0.0.0    Whea                                {Get-WheaMemoryPolicy, Set-WheaM...
Manifest   1.0.0.0    WindowsDeveloperLicense             {Get-WindowsDeveloperLicense, Un...
Script     1.0        WindowsErrorReporting               {Enable-WindowsErrorReporting, D...
Manifest   1.0.0.0    WindowsSearch                       {Get-WindowsSearchSetting, Set-W...
Manifest   1.0.0.0    WindowsUpdate                       Get-WindowsUpdateLog               
Manifest   1.0.0.2    WindowsUpdateProvider               {Get-WUAVersion, Get-WULastInsta...


    Directory: C:\Program Files (x86)\Microsoft SQL Server\130\Tools\PowerShell\Modules


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Manifest   2.0        SQLASCMDLETS                        {Add-RoleMember, Backup-ASDataba...
Manifest   1.0        SQLPS                               {Backup-SqlDatabase, Save-SqlMig...


    Directory: C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\7.3.702.0


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Binary     1.0        HybridRegistration                  {Add-HybridRunbookWorker, Remove...


    Directory: C:\Program Files\Microsoft Monitoring 
    Agent\Agent\AzureAutomation\7.3.702.0\HybridAgent\Modules


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Binary     1.0        Orchestrator.AssetManagement.Cmd... {Get-AutomationCertificate, Get-...


    Directory: C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Binary     1.54.59.0  AzureInformationProtection          {Clear-RMSAuthentication, Get-RM...


    Directory: C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell


ModuleType Version    Name                                ExportedCommands                   
---------- -------    ----                                ----------------                   
Script     3.8        Microsoft.Assessments.AADApplica... {Clear-MicrosoftAssessmentsAppli...
Binary     1.0.0.0    Microsoft.MonitoringAgent.PowerS... {Checkpoint-WebApplicationMonito...
Binary     8.0.1.882  Microsoft.PowerShell.Oms.Assessm... {Start-ADAssessment, Start-ADSec...

```

## Debug output

```
I don't want to include the debug output since that shows a lot of details about our vms and schedules.
```

## Error output

```powershell
$aaName = $aa.AutomationAccountName
$rgname = $aa.ResourceGroupName
$Error.Clear()
Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $aaName -ResourceGroupName $rgname
Resolve-AzError
Get-AzAutomationSoftwareUpdateConfiguration : Unable to deserialize the response.
At line:5 char:1
+ Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $a ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomatio...teConfiguration], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationSoftwareUpdateConfiguration
 
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.


   HistoryId: 12


Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.Automation.SoftwareUpdateConfigurationsOperations.<ListWithHttpMessagesAsync>d__8.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.SoftwareUpdateConfigurationsOperationsExtensions.<ListAsync>d__11.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.SoftwareUpdateConfigurationsOperationsExtensions.List(ISoftwareUpdateConfigurationsOperations operations, String resourceGroupName, 
                 String automationAccountName, String clientRequestId, String filter)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.ListSoftwareUpdateConfigurations(String resourceGroupName, String automationAccountName, String 
                 azureVirtualMachineId)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationSoftwareUpdateConfiguration.AutomationProcessRecord()
                    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzAutomationSoftwareUpdateConfiguration}
Line           : Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $aaName -ResourceGroupName $rgname
                 
Position       : At line:5 char:1
                 + Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $a ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

Message        : Error converting value {null} to type 'System.DateTimeOffset'. Path 'properties.startTime', line 1, position 14475.
StackTrace     :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
                    at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String 
                 id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object 
                 existingValue, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract 
                 containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, 
                 JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.Automation.SoftwareUpdateConfigurationsOperations.<ListWithHttpMessagesAsync>d__8.MoveNext()
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {Get-AzAutomationSoftwareUpdateConfiguration}
Line           : Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $aaName -ResourceGroupName $rgname
                 
Position       : At line:5 char:1
                 + Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $a ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

Message        : Could not cast or convert from {null} to System.DateTimeOffset.
StackTrace     :    at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
                    at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
Exception      : System.ArgumentException
InvocationInfo : {Get-AzAutomationSoftwareUpdateConfiguration}
Line           : Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $aaName -ResourceGroupName $rgname
                 
Position       : At line:5 char:1
                 + Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $a ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by bwarren18** [comment]
Small update: I downgraded to Az 5.5.0 and still got the same error.  So it appears to be a problem with the StartTime in one of our schedules. 
I also tried using the equivalent REST API query and that works and returns all the schedules without error.

**Comment by dingmeng-xue** [comment]
@bwarren18 , could you share the debug output when you executes `Get-AzAutomationSoftwareUpdateConfiguration -AutomationAccountName $aaName -ResourceGroupName $rgname`? You can turn on it via `$DebugPreference="Continue"`

**Comment by bwarren18** [comment]
Hello, we have a lot of schedules in the deployment with the issue.  The debug produces around 9,100 lines of output total, the http response is about 8000 lines.  The problem appears to be the StartTime returned in the schedules is null and the cmdlet then fails to convert that to a DateTime object.

```powershell
DEBUG: AzureQoSEvent: CommandName - Get-AzAutomationSoftwareUpdateConfiguration; IsSuccess - False; Duration - 00:00:01.8588224; Exception - Microsoft.Rest.SerializationException: Unable to deserialize the 
response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.DateTimeOffset'. Path 'properties.startTime', line 1, position 14475. ---> System.ArgumentException: 
Could not cast or convert from {null} to System.DateTimeOffset.`

If you really need the full debug output, let me know and I will edit out the thousands of identifying values.
Thanks.

**Comment by dingmeng-xue** [comment]
@bwarren18 , I believe you can just simply call `Get-AzAutomationSoftwareUpdateConfiguration` on any machine and reproduce the issue around it. Do you know which software update configuration has problem? If yes, could you check what value it is via Portal? We need to confirm whether the value is empty on service side or it is empty just in response.

**Comment by bwarren18** [comment]
Hello, I copied the names from the Azure Portal since the command without the name parameter just fails. I then edited the list in notepad and made it into an array in powershell, I then ran a foreach loop checking all the names individually.  What I found is on the update configurations it fails to read the schedules were deleted.  So I will have that cleaned up on our end.  Ideally there would be a way to return the update config object with a null schedule.  Thank you.

![image](https://user-images.githubusercontent.com/44654426/112144822-063b8100-8bb0-11eb-8ed3-7d006634c9f7.png)

**Comment by dingmeng-xue** [comment]
Thanks for the information. I added "Service attention" label and service team should look into this question.

**Comment by jaspkaur28** [comment]
Adding @msvijayn

**Comment by jaspkaur28** [comment]
closing due to no activity.

**Comment by seb-bartholomew-amcs** [comment]
I have the same issue.
It is exactly as @msvijayn has described, we have dangling SoftwareUpdateConfigurations records that are missing a corresponding schedule.
Wanted to use powershell to clean these up but is failing with same error above. 
Any suggestions on a workaround for removing these orphaned SoftwareUpdateConfigurations?
Thanks

**Comment by seb-bartholomew-amcs** [comment]
To answer my own question,
To run a **complete clear down** of the existing softwareUpdateConfigurations (they were almost all orphaned) in our Automation Account - I ended up relying on the REST API to get a full list of applicable resource Ids. 
Could then revert to Az PowerShell to remove the resources;

```
$subscriptionId = "<Azure Subscription Id>"
$resourceGroupName = "<Automation Account Resource Group Name>"
$automationAccountName = "<Automation Account Name>"
$authHeaders = @{
     'Content-Type'  = 'application/json'
     'Authorization' = 'Bearer ' + (Get-AzAccessToken).Token
 }
$result = Invoke-RestMethod -Uri https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroupName/providers/Microsoft.Automation/automationAccounts/$automationAccountName/softwareUpdateConfigurations?api-version=2017-05-15-preview -Headers $authHeaders
$result.value.id | ForEach-Object { Remove-AzResource -ResourceId $_ -Force }
```

Hope this saves someone else the trouble of trying to do this through the UI!
Would be nice if Get-AzAutomationSoftwareUpdateConfiguration was made a bit more flexible so it could handle orphaned records.

**Comment by jaspkaur28** [comment]
Adding @riva-yadav for UM

**Comment by KranthiPakala-MSFT** [comment]
@riva-yadav , @jaspkaur28 Following up to see if there is any update on this issue? - Thank you

**Comment by bwarren18** [comment]
Also beginning in Az 5.8.0 the command only returns 100 objects whereas the REST API returns all objects.
So Get-AzAutomationSoftwareUpdateConfiguration and '[Software Update Configurations - Get By Name](https://docs.microsoft.com/en-us/rest/api/automation/software-update-configurations/list)' are not equivalent.
