### ISSUE TITLE
Remove-AzSqlDatabaseSecondary Throws Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jdanton** [Azure/azure-powershell#14618]
## Description
 
Cmdlet fails with both parameters and literals.

## Steps to reproduce

```powershell

 Remove-AzSqlDatabaseSecondary -PartnerResourceGroupName $svr.ResourceGroupName  -PartnerServerName $svr.ServerName -DatabaseName $drdbname -servername $targetSvr  -ResourceGroupName $targetRG
```

## Environment data

```

```

## Module versions

```powershell
This is failing the same way on both Az.SQL 2.12.0 and 2.16.0

PS /Users/joey> $PsVersionTable


Name                           Value
----                           -----
PSVersion                      7.1.2
PSEdition                      Core
GitCommitId                    7.1.2
OS                             Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

and cloud shell

```

## Debug output

```

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Sql.ReplicationLink.Services.AzureSqlDatabaseReplicationAdapter.RemoveLink(String resourceGroupName, String serverName, String databaseName, String partnerResourceGroupName, String 
                 partnerServerName)
                    at Microsoft.Azure.Commands.Sql.Replication.Cmdlet.RemoveAzureSqlDatabaseSecondary.PersistChanges(IEnumerable`1 entity)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Remove-AzSqlDatabaseSecondary}
Line           : Remove-AzSqlDatabaseSecondary -PartnerResourceGroupName 'sqldb-demo'  -PartnerServerName 'dcac-demo'  -DatabaseName 'adventureworks2017-dr' -servername 'dcac-demo-dr'  -ResourceGroupName 'dcac-sqldr'  -verbose -debug
Position       : At line:1 char:1
                 + Remove-AzSqlDatabaseSecondary -PartnerResourceGroupName 'sqldb-demo'  …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 33


   HistoryId: 32

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Sql.ReplicationLink.Services.AzureSqlDatabaseReplicationAdapter.RemoveLink(String resourceGroupName, String serverName, String databaseName, String partnerResourceGroupName, String 
                 partnerServerName)
                    at Microsoft.Azure.Commands.Sql.Replication.Cmdlet.RemoveAzureSqlDatabaseSecondary.PersistChanges(IEnumerable`1 entity)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Remove-AzSqlDatabaseSecondary}
Line           : Remove-AzSqlDatabaseSecondary -PartnerResourceGroupName sqldb-demo  -PartnerServerName dcac-demo  -DatabaseName adventureworks2017-dr -servername dcac-demo-dr  -ResourceGroupName dcac-sqldr  -verbose -debug
Position       : At line:1 char:1
                 + Remove-AzSqlDatabaseSecondary -PartnerResourceGroupName sqldb-demo  - …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 32


   HistoryId: 30

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Sql.ReplicationLink.Services.AzureSqlDatabaseReplicationAdapter.RemoveLink(String resourceGroupName, String serverName, String databaseName, String partnerResourceGroupName, String 
                 partnerServerName)
                    at Microsoft.Azure.Commands.Sql.Replication.Cmdlet.RemoveAzureSqlDatabaseSecondary.PersistChanges(IEnumerable`1 entity)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Remove-AzSqlDatabaseSecondary}
Line           : Remove-AzSqlDatabaseSecondary -PartnerResourceGroupName sqldb-demo  -PartnerServerName dcac-demo  -DatabaseName adventureworks2017-dr -servername dcac-demo-dr  -ResourceGroupName dcac-sqldr  -verbose -debug
Position       : At line:1 char:1
                 + Remove-AzSqlDatabaseSecondary -PartnerResourceGroupName sqldb-demo  - …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 30
```

## Error output

```


Remove-AzSqlDatabaseSecondary: Object reference not set to an instance of an object.
DEBUG: AzureQoSEvent: CommandName - Remove-AzSqlDatabaseSecondary; IsSuccess - False; Duration - 00:00:00.8716089;; Exception - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Commands.Sql.ReplicationLink.Services.AzureSqlDatabaseReplicationAdapter.RemoveLink(String resourceGroupName, String serverName, String databaseName, String partnerResourceGroupName, String partnerServerName)
   at Microsoft.Azure.Commands.Sql.Replication.Cmdlet.RemoveAzureSqlDatabaseSecondary.PersistChanges(IEnumerable`1 entity)
   at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
   at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:43:03 PM - RemoveAzureSqlDatabaseSecondary end processing.
```

**Comment by jdanton** [comment]
Debug output 

Remove-AzSqlDatabaseSecondary: Object reference not set to an instance of an object.
DEBUG: AzureQoSEvent: CommandName - Remove-AzSqlDatabaseSecondary; IsSuccess - False; Duration - 00:00:00.8716089;; Exception - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Commands.Sql.ReplicationLink.Services.AzureSqlDatabaseReplicationAdapter.RemoveLink(String resourceGroupName, String serverName, String databaseName, String partnerResourceGroupName, String partnerServerName)
   at Microsoft.Azure.Commands.Sql.Replication.Cmdlet.RemoveAzureSqlDatabaseSecondary.PersistChanges(IEnumerable`1 entity)
   at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
   at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:43:03 PM - RemoveAzureSqlDatabaseSecondary end processing.
