### ISSUE TITLE
Get-AzMigrateDiscoveredServer fails to return results with only Agent Based machines.

### ISSUE THREAD

**Issue by russellds** [Azure/azure-powershell#14647]
## Description

When attempting to get discovered servers, only Agent-Based, `Get-AzMigrateDiscoveredServer` throws an error.

## Steps to reproduce

Setup Azure Migrate Project with only Agent Based servers being discovered.

```powershell
Get-AzMigrateDiscoveredServer -ProjectName <projectname> -ResourceGroupName <resourcegroupname>
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versionscle

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.3.0                 Az                                  Core,Desk
Script     2.2.7                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     2.2.5                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     2.2.4                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     2.2.3                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-Az…
Script     2.0.1                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-AzAksCluster, Re…
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspe…
Script     2.2.0                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add-A…
Script     1.0.0                 Az.AppConfiguration                 Core,Desk {Get-AzAppConfigurationStore, Get-AzApp…
Script     1.1.0                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzAppli…
Script     1.4.1                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Rem…
Script     3.1.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAcco…
Script     2.0.0                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPer…
Script     1.6.0                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoU…
Script     1.8.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-Az…
Script     4.8.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvaila…
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerG…
Script     2.1.0                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContain…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdg…
Script     1.0.2                 Az.Databricks                       Core,Desk {Get-AzDatabricksVNetPeering, Get-AzDat…
Script     1.11.3                Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFact…
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New…
Script     1.3.0                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, …
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShar…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource,…
Script     2.1.1                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-Az…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzD…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordCon…
Script     1.3.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridT…
Script     1.7.1                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHu…
Script     1.6.1                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-…
Script     2.0.0                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAv…
Script     4.1.1                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqo…
Script     1.2.0                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-Az…
Script     2.7.1                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubC…
Script     3.3.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKe…
Script     1.0.1                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension, A…
Script     1.4.0                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-Az…
Script     1.1.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfiguration…
Script     2.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-A…
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketpl…
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzM…
Script     1.0.0                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzM…
Script     0.2.0                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzM…
Script     0.1.1                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzM…
Script     2.3.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, …
Script     4.4.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthentication…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificat…
Script     2.3.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivity…
Script     1.4.0                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, …
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, G…
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivate…
Script     3.2.0                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, …
Script     1.4.0                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNames…
Script     3.1.1                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRole…
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServi…
Script     2.2.2                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, …
Script     1.2.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSi…
Script     2.14.0                Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryp…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSql…
Script     3.2.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAcc…
Script     1.4.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck…
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzS…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportPro…
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndp…
Script     2.1.1                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppService…
```

## Debug output

```
DEBUG: 5:56:47 PM - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzMigrateSolution_Get': AzureQoSEvent: CommandName - Get-AzMigrateSolution_Get; IsSuccess - False; Duration - 00:00:00
DEBUG: CmdletProcessRecordAsyncStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/9827517a-36a9-439c-9290-040b91b32853/resourceGroups/rg-azm-project/providers/Microsoft.Migrate/migrateProjects/mpj-eastus/solutions/Servers-Discovery-ServerDiscovery?api-version=2018-09-01-preview
DEBUG: RequestCreated: /subscriptions/9827517a-36a9-439c-9290-040b91b32853/resourceGroups/rg-azm-project/providers/Microsoft.Migrate/migrateProjects/mpj-eastus/solutions/Servers-Discovery-ServerDiscovery?api-version=2018-09-01-preview
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/9827517a-36a9-439c-9290-040b91b32853/resourceGroups/rg-azm-project/providers/Microsoft.Migrate/migrateProjects/mpj-eastus/solutions/Servers-Discovery-ServerDiscovery?api-version=2018-09-01-preview

Headers:
x-ms-unique-id                : 2
x-ms-client-request-id        : 8075e69c-b0c1-4cd3-8252-247dca62827c
CommandName                   : Get-AzMigrateSolution
FullCommandName               : Get-AzMigrateSolution_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/Az4.0.0-preview

Body:



DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : 4892fe49-cce1-47ea-8a32-471eae4985c3
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : 041632ec-3e7f-4c45-a48c-1b10cf6e0ca6
x-ms-routing-request-id       : CANADACENTRAL:20210328T215648Z:041632ec-3e7f-4c45-a48c-1b10cf6e0ca6
Date                          : Sun, 28 Mar 2021 21:56:48 GMT

Body:
{
  "id": "/subscriptions/****/resourceGroups/****/providers/Microsoft.Migrate/MigrateProjects/****/Solutions/Servers-Discovery-ServerDiscovery",
  "name": "Servers-Discovery-ServerDiscovery",
  "type": "Microsoft.Migrate/MigrateProjects/Solutions",
  "etag": "\"0a00746d-0000-0300-0000-605b39e20000\"",
  "properties": {
    "tool": "ServerDiscovery",
    "purpose": "Discovery",
    "goal": "Servers",
    "status": "Inactive",
    "cleanupState": "None",
    "summary": {
      "instanceType": "Servers",
      "discoveredCount": 0,
      "assessedCount": 0,
      "replicatingCount": 0,
      "testMigratedCount": 0,
      "migratedCount": 0
    },
    "details": {
      "groupCount": 0,
      "assessmentCount": 0,
      "extendedDetails": {
        "serversOnWindows": "0",
        "serversOnLinux": "0",
        "serversOnOther": "0",
        "dependencyEnabledMachines": "0",
        "machinesHavingSqlServers": "0"
      }
    }
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: [CmdletEndProcessing]: Sending new QosEvent for command 'Get-AzMigrateSolution_Get': AzureQoSEvent: CommandName - Get-AzMigrateSolution_Get; IsSuccess - True; Duration - 00:00:00
DEBUG: CmdletEndProcessing:
ConvertFrom-Json: C:\****\Documents\PowerShell\Modules\Az.Migrate\1.0.0\custom\Get-AzMigrateDiscoveredServer.ps1:79
Line |
  79 |  … DetailExtendedDetail["applianceNameToSiteIdMapV2"] | ConvertFrom-Json
     |                                                         ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.

ConvertFrom-Json: C:\****\Documents\PowerShell\Modules\Az.Migrate\1.0.0\custom\Get-AzMigrateDiscoveredServer.ps1:80
Line |
  80 |  … DetailExtendedDetail["applianceNameToSiteIdMapV3"] | ConvertFrom-Json
     |                                                         ~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'InputObject' because it is null.
```

## Error output

```
DEBUG: 5:58:44 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 5:58:44 PM - using account id '****'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 14

Message        : Cannot bind argument to parameter 'InputObject' because it is null.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject
                 inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 eInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32
                 validParameterSets)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 e(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CommandProcessor.Read()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {ConvertFrom-Json}
Line           :         $appMapV3 = $discoverySolution.DetailExtendedDetail["applianceNameToSiteIdMapV3"] |
                 ConvertFrom-Json

Position       : At C:\****\Documents\PowerShell\Modules\Az.Migrate\1.0.0\custom\Get-AzMigrateDiscoveredServer.ps1:80
                 char:93
                 + … DetailExtendedDetail["applianceNameToSiteIdMapV3"] | ConvertFrom-Json
                 +                                                        ~~~~~~~~~~~~~~~~
HistoryId      : 14

Message        : Cannot bind argument to parameter 'InputObject' because it is null.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject
                 inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 eInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32
                 validParameterSets)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 e(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CommandProcessor.Read()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {ConvertFrom-Json}
Line           :         $appMapV2 = $discoverySolution.DetailExtendedDetail["applianceNameToSiteIdMapV2"] |
                 ConvertFrom-Json

Position       : At C:\****\Documents\PowerShell\Modules\Az.Migrate\1.0.0\custom\Get-AzMigrateDiscoveredServer.ps1:79
                 char:93
                 + … DetailExtendedDetail["applianceNameToSiteIdMapV2"] | ConvertFrom-Json
                 +                                                        ~~~~~~~~~~~~~~~~
HistoryId      : 14


   HistoryId: 5

Message        : Cannot bind argument to parameter 'InputObject' because it is null.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject
                 inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 eInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32
                 validParameterSets)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 e(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CommandProcessor.Read()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {ConvertFrom-Json}
Line           :         $appMapV3 = $discoverySolution.DetailExtendedDetail["applianceNameToSiteIdMapV3"] |
                 ConvertFrom-Json

Position       : At C:\****\Documents\PowerShell\Modules\Az.Migrate\1.0.0\custom\Get-AzMigrateDiscoveredServer.ps1:80
                 char:93
                 + … DetailExtendedDetail["applianceNameToSiteIdMapV3"] | ConvertFrom-Json
                 +                                                        ~~~~~~~~~~~~~~~~
HistoryId      : 5

Message        : Cannot bind argument to parameter 'InputObject' because it is null.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.BindValueFromPipeline(PSObject
                 inputToOperateOn, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 eInParameterSet(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32
                 validParameterSets)
                    at System.Management.Automation.CmdletParameterBinderController.BindUnboundParametersForBindingStat
                 e(PSObject inputToOperateOn, CurrentlyBinding currentlyBinding, UInt32 validParameterSets)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindPipelineParametersPrivate(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CmdletParameterBinderController.BindPipelineParameters(PSObject
                 inputToOperateOn)
                    at System.Management.Automation.CommandProcessor.Read()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {ConvertFrom-Json}
Line           :         $appMapV2 = $discoverySolution.DetailExtendedDetail["applianceNameToSiteIdMapV2"] |
                 ConvertFrom-Json

Position       : At C:\****\Documents\PowerShell\Modules\Az.Migrate\1.0.0\custom\Get-AzMigrateDiscoveredServer.ps1:79
                 char:93
                 + … DetailExtendedDetail["applianceNameToSiteIdMapV2"] | ConvertFrom-Json
                 +                                                        ~~~~~~~~~~~~~~~~
HistoryId      : 5


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.1292284
DEBUG: Finish sending metric.
DEBUG: 5:58:45 PM - ResolveError end processing.
```

**Comment by kuchatur-ms** [comment]
Hi. The response received for the get-azmigratesolution is incorrect as it doesnt list any appliances for this project.
Can you try calling the rest api (https://management.azure.com/subscriptions/9827517a-36a9-439c-9290-040b91b32853/resourceGroups/rg-azm-project/providers/Microsoft.Migrate/migrateProjects/mpj-eastus/solutions/Servers-Discovery-ServerDiscovery?api-version=2018-09-01-preview) to confirm this?

Also, do consider updating to Az.Migrate module version 1.0.1. That wouldnt fix this issue, but it will spit out the right error here, saying something like "No appliances found".

**Comment by KranthiPakala-MSFT** [comment]
@shijojoy Following up to see if there is any update on this issue? - Thank you

**Comment by SaurabhSharma-MSFT** [comment]
@russellds Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .
