### ISSUE TITLE
Get-AzDataFactoryV2LinkedService : Unable to deserialize the response.

### ISSUE THREAD

**Issue by Moutushi1990** [Azure/azure-powershell#14760]
## Description
I'm running Azure Powershell Script  from Azure DevOps and so far it was running file .This script is used to activate trigger after the ADF ARM template deployment . When I run Get-AzDataFactoryV2LinkedService against my ADF, I am getting an error due to the linked service :
Also just want to mention and I have configured to use the latest script version for this particular task in release Pipeline.
Let me know if you need more information

Error details:

**2021-04-14T14:05:05.7158966Z ##[command]Disconnect-AzAccount -Scope Process -ErrorAction Stop
2021-04-14T14:05:06.3189806Z ##[command]Clear-AzContext -Scope Process -ErrorAction Stop
2021-04-14T14:05:06.7231630Z ##[debug]Caught exception from task script.
2021-04-14T14:05:06.7304211Z ##[debug]Error record:
2021-04-14T14:05:06.8883715Z ##[debug]Get-AzDataFactoryV2LinkedService : Unable to deserialize the response.
2021-04-14T14:05:06.8930002Z ##[debug]At D:\a\r1\a\_cdo-dp-scripts\cicd\cicd.ps1:109 char:5
2021-04-14T14:05:06.8985360Z ##[debug]+     Get-AzDataFactoryV2LinkedService -ResourceGroupName $ResourceGrou ...
2021-04-14T14:05:06.9011863Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2021-04-14T14:05:06.9065771Z ##[debug]    + CategoryInfo          : CloseError: (:) [Get-AzDataFactoryV2LinkedService], SerializationException
2021-04-14T14:05:06.9096324Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryLinkedServiceCommand
2021-04-14T14:05:06.9147250Z ##[debug] 
2021-04-14T14:05:06.9203745Z ##[debug]Script stack trace:
2021-04-14T14:05:06.9286011Z ##[debug]at Get-SortedLinkedServices, D:\a\r1\a\_cdo-dp-scripts\cicd\cicd.ps1: line 109
2021-04-14T14:05:06.9345492Z ##[debug]at <ScriptBlock>, D:\a\r1\a\_cdo-dp-scripts\cicd\cicd.ps1: line 203
2021-04-14T14:05:06.9385489Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-04-14T14:05:06.9423352Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.184.1\azurepowershell.ps1: line 232
2021-04-14T14:05:06.9449629Z ##[debug]at <ScriptBlock>, D:\a\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\4.184.1\azurepowershell.ps1: line 228
2021-04-14T14:05:06.9479486Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-04-14T14:05:06.9510944Z ##[debug]at <ScriptBlock>, <No file>: line 22
2021-04-14T14:05:06.9620322Z ##[debug]at <ScriptBlock>, <No file>: line 18
2021-04-14T14:05:06.9655466Z ##[debug]at <ScriptBlock>, <No file>: line 1
2021-04-14T14:05:06.9769951Z ##[debug]Exception:
2021-04-14T14:05:06.9884090Z ##[debug]Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path 'typeProperties.authenticationType', line 1, position 23693.
2021-04-14T14:05:06.9932097Z ##[debug]   at Newtonsoft.Json.JsonReader.ReadAsString()
2021-04-14T14:05:06.9959833Z ##[debug]   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
2021-04-14T14:05:07.0004713Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2021-04-14T14:05:07.0039359Z ##[debug]   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
2021-04-14T14:05:07.0088282Z ##[debug]   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
2021-04-14T14:05:07.0144139Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
2021-04-14T14:05:07.0168558Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2021-04-14T14:05:07.0207398Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2021-04-14T14:05:07.0233172Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2021-04-14T14:05:07.0287048Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
2021-04-14T14:05:07.0345172Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
2021-04-14T14:05:07.0380830Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
2021-04-14T14:05:07.0412408Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
2021-04-14T14:05:07.0456392Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
2021-04-14T14:05:07.0479959Z ##[debug]   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
2021-04-14T14:05:07.0552332Z ##[debug]   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
2021-04-14T14:05:07.0591613Z ##[debug]   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
2021-04-14T14:05:07.0617325Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperations.<ListByFactoryWithHttpMessagesAsync>d__5.MoveNext()
2021-04-14T14:05:07.0648610Z ##[debug]   --- End of inner exception stack trace ---
2021-04-14T14:05:07.0677799Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperations.<ListByFactoryWithHttpMessagesAsync>d__5.MoveNext()
2021-04-14T14:05:07.0701893Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-04-14T14:05:07.0748534Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-04-14T14:05:07.0793093Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-04-14T14:05:07.0844336Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.<ListByFactoryAsync>d__1.MoveNext()
2021-04-14T14:05:07.0877206Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2021-04-14T14:05:07.0944181Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-04-14T14:05:07.1057487Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-04-14T14:05:07.1124856Z ##[debug]   at Microsoft.Azure.Management.DataFactory.LinkedServicesOperationsExtensions.ListByFactory(ILinkedServicesOperations operations, String resourceGroupName, String factoryName)
2021-04-14T14:05:07.1166408Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.ListLinkedServices(AdfEntityFilterOptions filterOptions)
2021-04-14T14:05:07.1225679Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.FilterPSLinkedServices(AdfEntityFilterOptions filterOptions)
2021-04-14T14:05:07.1262558Z ##[debug]   at Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryLinkedServiceCommand.ExecuteCmdlet()
2021-04-14T14:05:07.1295514Z ##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2021-04-14T14:05:07.1626911Z ##[error]Unable to deserialize the response.
2021-04-14T14:05:07.1641919Z ##[debug]Processed: ##vso[task.logissue type=error]Unable to deserialize the response.
2021-04-14T14:05:07.1644633Z ##[debug]Processed: ##vso[task.complete result=Failed]**

**Comment by shawnxzq** [comment]
@Moutushi1990 What linked service are you trying to get through PowerShell? From the error, it's because the "authenticationType" property has some issue, could you please share the json code of the linked service from UX? Thanks!

**Comment by Moutushi1990** [comment]
@shawnxzq  Thanks for your response. Let me share a little background we have  built multiple Pipelines in ADF And data coming from heterogeneous source like SFTP, ftp ,http etc. We are doing an ARM template deployment for ADF using azure Dev-ops Release process unable to track which particular LS  is causing this authentication problem as and the list is very long  ,also until last week it was working absolutely fine. Is there any way to check that, like tweaking the PowerShell code which I am running and get the name of LS which is causing trouble ? Also wanted to know this 'authentication type' property issue occurs due to what reason? 

I am copying the  Linked service  code section from arm template here to show the structure if this helps you.
Note that values (which are not to be exposed) i have removed as some of them are hardcoded and not kept in Keyvault.

**{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "factoryName": {
            "type": "string",
            "metadata": "Data Factory name",
            "defaultValue": ""
        },
        "ADLSGen2Prod_accountKey": {
            "type": "secureString",
            "metadata": ""
        },
        "ADLSGen2Stage_accountKey": {
            "type": "secureString",
            "metadata": ""
        },
        "AzureSQLGenConfig_connectionString": {
            "type": "secureString",
            "metadata": ""
        },
        "AzureSQLGenStaging_connectionString": {
            "type": "secureString",
            "metadata": ""
        },
        "AzureSQLSrc020_connectionString": {
            "type": "secureString",
            "metadata": ""
        },
        "LS_AzureSql_Audit_Analytics_Sink_connectionString": {
            "type": "secureString",
            "metadata": "”        },
        "LS_AzureSql_SnlEnergy_Src_connectionString": {
            "type": "secureString",
            "metadata": ""
        },
        "POCDB_connectionString": {
            "type": "secureString",
            "metadata": ""
        },
        "SQLServerSrcGDC_connectionString": {
            "type": "secureString",
            "metadata": ""
        },
        "ADLSGen2Prod_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": ""
        },
        "ADLSGen2Stage_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": ""
        },
        "ADLSGen2TrustedStorage_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": ""
        },
        "ASQL_HealthCareAlmanac_properties_typeProperties_connectionString_secretName": {
            "type": "string",
            "defaultValue": "HealthCareAlmanacSQLConnString"
        },
        "AzureKeyVault1_properties_typeProperties_baseUrl": {
            "type": "string",
            "defaultValue": "        },
        "BlobTrustedStorage_properties_typeProperties_connectionString_secretName": {
            "type": "string",
            "defaultValue": "TrustedBlob"
        },
        "FannieMaeCAS_Http_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": "@{linkedService().URL}"
        },
        "Ferderal_Reserve_PSPF_HTTP_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": "@{linkedService().URL}"
        },
        "FredSrcHttpGet_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": "@linkedService().BaseURL"
        },
        "FtpSrcRefinitiv_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "FtpSrcRefinitiv_properties_typeProperties_userName": {
            "type": "string",
            "defaultValue": ""
        },
        "LS_AuditAnalytics_FTP_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "LS_AuditAnalytics_FTP_properties_typeProperties_userName": {
            "type": "string",
            "defaultValue": ""
        },
        "LS_FTP_MEDALIA_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "LS_FTP_MEDALIA_properties_typeProperties_username": {
            "type": "object",
            "defaultValue": {
                "type": "AzureKeyVaultSecret",
                "secretName": "MedaliaFTPUsername",
                "store": {
                    "referenceName": "",
                    "type": "LinkedServiceReference"
                }
            }
        },
        "LS_SFTP_Definitive_Healthcare_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "LS_SFTP_Definitive_Healthcare_properties_typeProperties_username": {
            "type": "object",
            "defaultValue": {
                "type": "AzureKeyVaultSecret",
                "secretName": "DefinitiveHealthcareSFTPUID",
                "store": {
                    "referenceName": "AzureKeyVault1",
                    "type": "LinkedServiceReference"
                }
            }
        },
        "LS_SFTP_IHS_MARKIT_TRADE_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "LS_SFTP_IHS_MARKIT_TRADE_properties_typeProperties_username": {
            "type": "object",
            "defaultValue": {
                "type": "AzureKeyVaultSecret",
                "secretName": "IHSMarkitSFTPusername",
                "store": {
                    "referenceName": "AzureKeyVault1",
                    "type": "LinkedServiceReference"
                }
            }
        },
        "LS_SFTP_TREPP_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "LS_SFTP_TREPP_properties_typeProperties_username": {
            "type": "object",
            "defaultValue": {
                "type": "AzureKeyVaultSecret",
                "secretName": "TreppSFTPusername",
                "store": {
                    "referenceName": "AzureKeyVault1",
                    "type": "LinkedServiceReference"
                }
            }
        },
        "LS_UNDP_HTTP_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": "
        },
        "MFTSrcEquifax_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "MFTSrcEquifax_properties_typeProperties_hostKeyFingerprint": {
            "type": "string",
            "defaultValue": ""
        },
        "MFTSrcEquifax_properties_typeProperties_userName": {
            "type": "string",
            "defaultValue": ""
        },
        "Rest_AzADFlog_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": "https://management.azure.com/subscriptions/@{linkedService().azSubID}/resourceGroups/@{linkedService().azRGname}/providers/Microsoft.DataFactory/factories/@{linkedService().azADFname}/queryPipelineRuns?api-version=2018-06-01"
        },
        "Rest_AzADFlog_properties_typeProperties_servicePrincipalId": {
            "type": "string",
            "defaultValue": ""
        },
        "Rest_AzADFlog_properties_typeProperties_tenant": {
            "type": "string",
            "defaultValue": ""
        },
        "Rest_AzADFlog_properties_typeProperties_aadResourceId": {
            "type": "string",
            "defaultValue": "https://management.azure.com"
        },
        "SFTP_BlackKnight_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "SFTP_BlackKnight_properties_typeProperties_username": {
            "type": "object",
            "defaultValue": {
                "type": "AzureKeyVaultSecret",
                "secretName": "BlackKnight-Username",
                "store": {
                    "referenceName": "AzureKeyVault1",
                    "type": "LinkedServiceReference"
                }
            }
        },
        "SFTP_IHS_CECL_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "SFTP_IHS_CECL_properties_typeProperties_username": {
            "type": "object",
            "defaultValue": {
                "type": "AzureKeyVaultSecret",
                "secretName": "IHS-CECL-Username",
                "store": {
                    "referenceName": "AzureKeyVault1",
                    "type": "LinkedServiceReference"
                }
            }
        },
        "SNL_FTP_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "SNL_FTP_properties_typeProperties_userName": {
            "type": "string",
            "defaultValue": ""
        },
        "TpdBatch_properties_typeProperties_accountName": {
            "type": "string",
            "defaultValue": ""
        },
        "TpdBatch_properties_typeProperties_batchUri": {
            "type": "string",
            "defaultValue": "
        },
        "TpdBatch_properties_typeProperties_poolName": {
            "type": "string",
            "defaultValue": ""
        },
        "USCenus_Http_Get_properties_typeProperties_url": {
            "type": "string",
            "defaultValue": "@linkedService().BaseURL"
        },
        "ZipCodesSrcFTP_properties_typeProperties_host": {
            "type": "string",
            "defaultValue": ""
        },
        "ZipCodesSrcFTP_properties_typeProperties_userName": {
            "type": "string",
            "defaultValue": ""
        },**

**Comment by Moutushi1990** [comment]
Any Updates \suggestion on how to trouble shoot  this error

**Comment by shawnxzq** [comment]
@Moutushi1990 You can check the rest linked service from the UX, it might be easier to get the json code the problematic linked service, the arm template you shared above doesn't include it, thanks!

**Comment by shawnxzq** [comment]
@Moutushi1990  Any update on this？Feel free to let us know if you have any issues to get the json code, thanks!

**Comment by shawnxzq** [comment]
Close it for now since no more response.
