### ISSUE TITLE
'An error occurred while sending the request' for command Get-AzureRmDataLakeAnalyticsJob

### ISSUE THREAD

**Issue by karthiga2** [Azure/azure-powershell#14811]
I am trying to fetch azure data lake job details through Azure runbook in Azure automation account. But it's throwing error ''An error occurred while sending the request'.
Gone through many blogs but, could not able to find any solution pertaining to this.

code used as shown below:
$adlaAccountName="<accname>"
$connectionName = "AzureRunAsConnection"
try
{
    # Get the connection "AzureRunAsConnection "
    $servicePrincipalConnection = Get-AutomationConnection -Name $connectionName      
    "Logging in to Azure..."
    $account = Add-AzureRmAccount `
        -ServicePrincipal `
        -TenantId $servicePrincipalConnection.TenantId `
        -ApplicationId $servicePrincipalConnection.ApplicationId `
        -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint 
}
catch {
    if (!$servicePrincipalConnection)
    {
        $ErrorMessage = "Connection $connectionName not found."
        throw $ErrorMessage
    } else{
        Write-Error -Message $_.Exception
        throw $_.Exception
    }
}
Write-Output $account

$account

#Connect to the Azure Subscription in which your ADLA Catalog exists 
Set-AzureRMContext -SubscriptionId $subid

Get-AzureRmDataLakeAnalyticsJob -Account $adlaAccountName

**Comment by karthiga2** [comment]
**Debug Response for the DatalakeJob command:**


Body:


An error occurred while sending the request.
AzureQoSEvent: CommandName - Get-AzureRmDataLakeAnalyticsJob; IsSuccess - False; Duration - 00:00:27.2933994; Exception - System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 40.90.138.209:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.Authentication.Models.RPRegistrationDelegatingHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.Authentication.Models.RPRegistrationDelegatingHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.Common.Authentication.Factories.CancelRetryHandler.<SendAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.DataLake.Analytics.JobOperations.<ListWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.DataLake.Analytics.JobOperationsExtensions.<ListAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.DataLake.Analytics.JobOperationsExtensions.List(IJobOperations operations, String accountName, ODataQuery`1 odataQuery, String select, Nullable`1 count)
   at Microsoft.Azure.Commands.DataLakeAnalytics.Models.DataLakeAnalyticsClient.ListJobs(String accountName, String filter, Nullable`1 top, Nullable`1 skip, String orderBy, Boolean& moreJobs)
   at Microsoft.Azure.Commands.DataLakeAnalytics.GetAzureDataLakeAnalyticsJob.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
Finish sending metric.
12:29:12 PM - GetAzureDataLakeAnalyticsJob end processing.
12:29:12 PM - GetAzureDataLakeAnalyticsJob end processing.
