### ISSUE TITLE
Get-AzSynapsePipeline fails when Wait activity has Dynamic Content

### ISSUE THREAD

**Issue by garfunkalow** [Azure/azure-powershell#14860]
## Description
Get-AzSynapsePipeline fails with "The requested operation requires an element of type 'Number', but the target element has type 'Object' " when the Wait activity has a 'dynamic expression'

## Steps to reproduce

```powershell


Create a pipeline with a wait activity with dynamic content, 
{
    "name": "Wait for 60 to 90 seconds",
    "type": "Wait",
    "dependsOn": [],
    "userProperties": [],
    "typeProperties": {
        "waitTimeInSeconds": {
            "value": "@rand(60,90)",
	    "type": "Expression"
	}
    }
}


Publish then run
Get-AzSynapsePipeline -WorkspaceName workspacename -Name pipelineWithWaitActivityWithDynamicExpression

Seems Get-AzSynapsePipeline is only expecting a number value and not the object.
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 4.15.0-1113-azure #126~16.04.1-Ubuntu SMP Tue Apr 13 16:55:24 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     0.10.0                Az.Synapse                          Core,Desk {Get-AzSynapseSparkJob, Stop-AzSynapseSparkJob, Submit-AzSynapseSparkJob, Wait-AzSynapseSparkJob…}
```

```powershell



```

```

```

## Error output
```
Message        : The requested operation requires an element of type 'Number', but the target element has type 'Object'.
StackTrace     :    at System.Text.Json.JsonDocument.TryGetValue(Int32 index, Int32& value)
                    at System.Text.Json.JsonElement.GetInt32()
                    at Azure.Analytics.Synapse.Artifacts.Models.WaitActivity.DeserializeWaitActivity(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.Models.Activity.DeserializeActivity(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.Models.ForEachActivity.DeserializeForEachActivity(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.Models.Activity.DeserializeActivity(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.Models.PipelineResource.DeserializePipelineResource(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.PipelineRestClient.GetPipeline(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
                    at Azure.Analytics.Synapse.Artifacts.PipelineClient.GetPipeline(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.GetPipeline(String pipelineName)
                    at Microsoft.Azure.Commands.Synapse.GetAzureSynapsePipeline.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.InvalidOperationException
InvocationInfo : {Get-AzSynapsePipeline}
Line           : Get-AzSynapsePipeline -WorkspaceName location3-dev -Name GoogleAnalytics_GetReportingFiles
Position       : At line:1 char:1
                 + Get-AzSynapsePipeline -WorkspaceName location3-dev -Name GoogleAnalyt …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 17




```

**Comment by idear1203** [comment]
Thanks for the reporting. This is a known issue. We have a PR to fix the issue by upgrading the SDK version: https://github.com/Azure/azure-powershell/pull/14697 . We are targeting S187 (2021-05-25) to fix the issue

**Comment by jbarrancos** [comment]
Any update on this?

Get-AzSynapsePipeline -WorkspaceName "synapseworkspacename"

Get-AzSynapsePipeline : The requested operation requires an element of type 'String', but the target element has type
'Object'. At line:1 char:1

Current version:  Az.Synapse 0.12.0  from a day ago. 

Some issue on the Azure DevOps agents.

**Comment by idear1203** [comment]
Verified the issue has been fixed in the latest Synapse PowerShell release.

@jbarrancos , I believe the issue that you are facing is a different issue. If so, could you please create a new GitHub issue with minimal reproduce steps and other necessary infos so that we can check from our side?

CC @wonner

**Comment by ssisjoost** [comment]
@jbarrancos You will get the error when there are only private endpoints in Synapse (instead of public endpoints).

**Comment by Himanshu-ms** [comment]
Hello Team,
I am also facing the same issue:

Get-AzSynapsePipeline: /home/ubuntu/actions-runner/_work/udf-platform/udf-platform/code/Scripts/SynapseRolloutPreprocessing.ps1:89
Line |
  89 |  $pipelines = Get-AzSynapsePipeline `
     |               ~~~~~~~~~~~~~~~~~~~~~~~
     | The requested operation requires an element of type 'Number', but the
     | target element has type 'Object'.
Error: Process completed with exit code 1.

Please assist.
