### ISSUE TITLE
Set-AzSynapseNotebook : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MikeyBronowski** [Azure/azure-powershell#15061]
## Description
When creating a new Synapse Notebook with Set-AzSynapseNotebook I am getting the error. I even exported the notebook with the Export-* command and opened it locally (looks ok), but I am getting this error when using it to create the new one.

Tried examples from the function but the error is still the same. Am I missing something obvious?

## Steps to reproduce

```powershell
# export existing Synapse Notebook to at file
$export = Export-AzSynapseNotebook -WorkspaceName WSName -Name "Notebook  -OutputFolder "C:\Temp\"

# create a new notebook
Set-AzSynapseNotebook -WorkspaceName WSName  -DefinitionFile $export -Verbose

# or 

Set-AzSynapseNotebook -WorkspaceName WSName  -DefinitionFile "C:\Temp\Notebook.ipynb" -Verbose
```

## Environment data

```
Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
PSVersion                      5.1.19041.906                                                                                                                          
PSEdition                      Desktop                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                
BuildVersion                   10.0.19041.906                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                        
WSManStackVersion              3.0                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                    
SerializationVersion           1.1.0.1      
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands                                                                                            
---------- -------    ----                                ----------------                                                                                            
Script     0.11.0     Az.Synapse                          {Get-AzSynapseSparkJob, Stop-AzSynapseSparkJob, Submit-AzSynapseSparkJob, Wait-AzSynapseSparkJob...}      
```

## Debug output

```
DEBUG: 23:24:36 - SetAzureSynapseNotebook begin processing with ParameterSet 'SetByName'.
DEBUG: 23:24:36 - using account id 'xxx@xxx.xx'...
VERBOSE: Performing the operation "Setting notebook 'Notebook 1' in workspace 'xxxxxxxx'." on target "xxxxxxxx".
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:36 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
DEBUG: 23:24:37 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx-xxx-xxx', Scopes:'https://dev.azuresy
napse.net/.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.xx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId: 
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net/.default ] ParentRequestId:  ExpiresOn: 2021-05-19T22:36:48.0000000+00:00
Set-AzSynapseNotebook : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-AzSynapseNotebook -WorkspaceName $asworkspace.Name -DefinitionFil ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzSynapseNotebook], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Synapse.SetAzureSynapseNotebook
 
DEBUG: AzureQoSEvent: CommandName - Set-AzSynapseNotebook; IsSuccess - False; Duration - 00:00:00.1955276; Exception - Object reference not set to an instance of an ob
ject.;
DEBUG: Finish sending metric.
DEBUG: 23:24:37 - SetAzureSynapseNotebook end processing.
```

## Error output

```
  HistoryId: 111


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Azure.Analytics.Synapse.Artifacts.Models.Notebook.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
                    at Azure.Analytics.Synapse.Artifacts.Models.NotebookResource.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
                    at Azure.Analytics.Synapse.Artifacts.NotebookRestClient.CreateCreateOrUpdateNotebookRequest(String notebookName, NotebookResource notebook, 
                 String ifMatch)
                    at Azure.Analytics.Synapse.Artifacts.NotebookRestClient.CreateOrUpdateNotebook(String notebookName, NotebookResource notebook, String ifMatch, 
                 CancellationToken cancellationToken)
                    at Azure.Analytics.Synapse.Artifacts.NotebookClient.StartCreateOrUpdateNotebook(String notebookName, NotebookResource notebook, String ifMatch, 
                 CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.CreateOrUpdateNotebook(String notebookName, NotebookResource notebook)
                    at Microsoft.Azure.Commands.Synapse.SetAzureSynapseNotebook.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Set-AzSynapseNotebook}
Line           : Set-AzSynapseNotebook -WorkspaceName WSName  -DefinitionFile $export -Verbose
Position       : At line:1 char:1
                 + Set-AzSynapseNotebook -WorkspaceName WSName  -DefinitionFil ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 111
```

**Comment by MikeyBronowski** [comment]
> Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @aim-for-better, @idear1203.
> 
> Issue Details

Is there any update on this?

**Comment by MikeyBronowski** [comment]
This still seems to be an issue even with the latest version of the module. @aim-for-better @idear1203

**Comment by idear1203** [comment]
@MikeyBronowski sorry I missed the thread. Could you please provide me with a minimal definition file that can reproduce the issue?

**Comment by MikeyBronowski** [comment]
I've created the Notebook via Azure Synapse Studio, a simple one with one line of Markdown, published and exported it with PowerShell.

Then tried to import the same file without success. Would that be enough to reproduce?

**Comment by MikeyBronowski** [comment]
I've looked again and seems to be an issue with the Export command.

When I've exported the notebook with PowerShell, I could not import it via Synapse studio (error about incorrect format).

When I've exported the notebook using the studio, I could import it with PowerShell. 

I will do some comparison between the contents of the files.
