### ISSUE TITLE
Invoke-AzResourceAction: Length cannot be less than zero. (Parameter 'length')

### ISSUE THREAD

**Issue by brettmillerb** [Azure/azure-powershell#15170]
## Description
Attempting to use `Invoke-AzResourceAction` throws a parameter error for a length parameter which must be an internal parameter as there are no parameters for length that are being used.

This worked previously but has stopped working recently. I have updated the `Az.Resources` module on my machine but this newer version has the same issue.

```
Invoke-AzResourceAction: Length cannot be less than zero. (Parameter 'length')
```

## Steps to reproduce
I have a wrapper function that I am utilising:

```powershell
function Set-AzClassicVM {
    [CmdletBinding(SupportsShouldProcess,
        ConfirmImpact = 'Medium')]
    param (
        [Parameter(Mandatory)]
        [Alias('ResourceName')]
        [string]
        $Name,

        [Parameter(Mandatory)]
        [string]
        $ResourceGroupName,

        [parameter(Mandatory)]
        [ValidateSet('Stop', 'Start')]
        [string]$Action,

        [string]
        $ApiVersion = '2017-04-01',

        [switch]
        $Force
    )

    if ($PSCmdlet.ShouldProcess("$Name", ("{0}ing virtual machine" -f $Action))) {
        $invokeResourceActionSplat = @{
            ResourceType      = 'Microsoft.ClassicCompute/virtualMachines'
            ResourceName      = $Name
            ResourceGroupName = $ResourceGroupName
            Action            = $Action
            ApiVersion        = $ApiVersion
        }

        if ($Force) {
            $invokeResourceActionSplat.Force = $true
        }

        Invoke-AzResourceAction @invokeResourceActionSplat
    }
}
```
However just using the base cmdlet throws the same error.
```powershell
Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtualMachines'
-ResourceName 'auuzlzo3a1' -ResourceGroupName 't9yjs5cslt' -Action Stop
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.5
PSEdition                      Core
GitCommitId                    7.2.0-preview.5
OS                             Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-71…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
Directory: /Users/brett.miller/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     5.1.0                 Az                                  Core,Desk
Script     2.3.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-Az…
Script     2.2.6                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-Az…
Script     2.2.1                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-Az…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-…
Script     2.0.1                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-AzAksCluster, …
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Sus…
Script     2.1.0                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add…
Script     1.0.0                 Az.AppConfiguration                 Core,Desk {Get-AzAppConfigurationStore, Get-AzA…
Script     1.1.0                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApp…
Script     1.4.0                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, R…
Script     3.1.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAc…
Script     2.0.0                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingP…
Script     1.6.0                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSs…
Script     1.8.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-…
Script     4.6.0                 Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvai…
Script     1.0.3                 Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContaine…
Script     2.0.0                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzConta…
Script     1.1.0                 Az.CosmosDB                         Core,Desk {Get-AzCosmosDBSqlContainer, Get-AzCo…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxE…
Script     1.0.1                 Az.Databricks                       Core,Desk {Get-AzDatabricksVNetPeering, Get-AzD…
Script     1.11.1                Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFa…
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, N…
Script     1.3.0                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider…
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataSh…
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSourc…
Script     2.0.1                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-A…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordC…
Script     1.3.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGri…
Script     1.7.1                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEvent…
Script     1.6.1                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Se…
Script     2.0.0                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionApp…
Script     4.1.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightS…
Script     1.1.0                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-…
Script     2.7.0                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHu…
Script     3.1.0                 Az.KeyVault                         Core,Desk {Add-AzManagedHsmKey, Get-AzManagedHs…
Script     1.0.0                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension,…
Script     1.4.0                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, G…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-…
Script     1.1.0                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurati…
Script     2.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New…
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarket…
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-A…
Script     2.2.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric…
Script     4.3.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticati…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotific…
Script     2.3.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivi…
Script     1.3.1                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState…
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection,…
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPriva…
Script     3.0.1                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty…
Script     1.4.0                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, Ne…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNam…
Script     0.8.0                 Az.ResourceGraph                    Core,Desk {Search-AzGraph, Get-AzResourceGraphQ…
Script     4.1.1                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRo…
Script     3.3.0                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRo…
Script     3.0.1                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRo…
Script     1.4.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzSer…
Script     2.2.0                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate…
Script     1.2.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-Az…
Script     2.12.0                Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncr…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzS…
Script     3.0.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageA…
Script     1.3.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityChe…
Script     1.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-A…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportP…
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEn…
Script     2.1.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServi…
Script     4.4.3                 CosmosDB                            Core,Desk {Get-CosmosDbAccount, Get-CosmosDbAcc…
Script     1.0.0      beta3      EditorServicesCommandSuite          Desk      {Get-CommandSuiteSetting, Set-Command…
Binary     0.1.1                 Microsoft.PowerShell.UnixCompleters Core      {Import-UnixCompleters, Remove-UnixCo…
Script     2.0.487               oh-my-posh                          Desk      {Write-ColorPreview, Show-Colors, Sho…
Script     0.7.3                 posh-git                            Desk      {Invoke-NullCoalescing, Add-PoshGitTo…
Script     0.2.0                 PSStringTemplate                    Desk      {New-StringTemplateGroup, Invoke-Stri…
Script     0.5.0                 Terminal-Icons                      Desk      {Add-TerminalIconsColorTheme, Add-Ter…
Script     1.0                   Toolbox                             Desk      {Backup-Profile, Export-AzKeyVaultCer…

    Directory: /usr/local/microsoft/powershell/7-preview/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy,…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alia…
Script     1.4.7                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-Packa…
Script     2.2.5                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find…
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-…
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSRead…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob
```

## Debug output

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/<SubId>/resourceGroups/t9yjs5cslt/providers/Microsoft.ClassicCompute/virtualMachines/auuzlzo3a1/Stop?api-version=2017-04-01

Headers:
User-Agent                    : PSVersion/v7.2.0,AzurePowershell/v5.1.0
ParameterSetName              : BySubscriptionLevel
CommandName                   : Invoke-AzResourceAction

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Location                      : https://management.azure.com/subscriptions/<SubId>/resourceGroups/t9yjs5cslt/providers/Microsoft.ClassicCompute/virtualMachines/auuzlzo3a1/operationStatuses/9087cd54dac7a253b616848a7ac11968?api-version=2017-04-01&return-path=
Retry-After                   : 15
x-ms-request-id               : northcentralus:4862b67e-58c9-4dba-9539-7cf8401fe346
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : ee6f3237-3d1c-494a-8c7a-dfbac3ea84dd
x-ms-routing-request-id       : NORTHEUROPE:20210603T110455Z:ee6f3237-3d1c-494a-8c7a-dfbac3ea84dd
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 03 Jun 2021 11:04:54 GMT

Body:



DEBUG: [Common.Authentication]: Authenticating using Account: 'Brett.Miller@<CompanyEmail>.com', environment: 'AzureCloud', tenant: '<TenantID>'
DEBUG: 12:04:55 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'<TenantId>', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'Brett.Miller@sage.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(d1380160-6099-4cfe-9fe2-7d4b791c28ae)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - d1380160-6099-4cfe-9fe2-7d4b791c28ae

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] === Token Acquisition (SilentRequest) started:

	Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] Access token is not expired. Returning the found cache entry. [Current time (06/03/2021 11:04:55) - Expiration Time (06/03/2021 11:40:30 +00:00) - Extended Expiration Time (06/03/2021 11:40:30 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 [06/03/2021 11:04:55 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/03/2021 11:40:30 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-06-03T11:40:30.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<TenantId>', UserId: 'Brett.Miller@sage.com'
Invoke-AzResourceAction: Length cannot be less than zero. (Parameter 'length')
DEBUG: AzureQoSEvent: CommandName - Invoke-AzResourceAction; IsSuccess - False; Duration - 00:00:03.5327407; Exception - Length cannot be less than zero. (Parameter 'length');
DEBUG: Finish sending metric.
DEBUG: 12:04:55 - InvokAzureResourceActionCmdlet end processing.
```

## Error output

```powershell
Exception             :
    Type       : System.ArgumentOutOfRangeException
    Message    : Length cannot be less than zero. (Parameter 'length')
    ParamName  : length
    TargetSite :
        Name          : HandleException
        DeclaringType : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase
        MemberType    : Method
        Module        : Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll
    StackTrace :
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(Excep
tionDispatchInfo capturedException)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
   at
Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet,
Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
    Source     : Microsoft.Azure.PowerShell.Cmdlets.ResourceManager
    HResult    : -2146233086
CategoryInfo          : CloseError: (:) [Invoke-AzResourceAction], ArgumentOutOfRangeException
FullyQualifiedErrorId :
Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
InvocationInfo        :
    MyCommand        : Invoke-AzResourceAction
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 7
    Line             : Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtualMachines'
-ResourceName 'auuzlzo3a1' -ResourceGroupName 't9yjs5cslt' -Action Stop -Force -Debug
    PositionMessage  : At line:1 char:1
                       + Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtu …
                       + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Invoke-AzResourceAction
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

```
HistoryId: 7

Message        : Length cannot be less than zero. (Parameter 'length')
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.Hand
                 leException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.Exec
                 uteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronous
                 lyOrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentOutOfRangeException
InvocationInfo : {Invoke-AzResourceAction}
Line           : Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtualMachines' -ResourceName
                 'auuzlzo3a1' -ResourceGroupName 't9yjs5cslt' -Action Stop -Force -Debug
Position       : At line:1 char:1
                 + Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtu …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7


   HistoryId: 6

Message        : Length cannot be less than zero. (Parameter 'length')
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.Hand
                 leException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.Exec
                 uteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronous
                 lyOrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentOutOfRangeException
InvocationInfo : {Invoke-AzResourceAction}
Line           : Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtualMachines' -ResourceName
                 'auuzlzo3a1' -ResourceGroupName 't9yjs5cslt' -Action Stop -Force -Verbose
Position       : At line:1 char:1
                 + Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtu …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6


   HistoryId: 4

Message        : Length cannot be less than zero. (Parameter 'length')
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.Hand
                 leException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.Exec
                 uteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronous
                 lyOrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentOutOfRangeException
InvocationInfo : {Invoke-AzResourceAction}
Line           : Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtualMachines' -ResourceName
                 'auuzlzo3a1' -ResourceGroupName 't9yjs5cslt' -Action Stop
Position       : At line:1 char:1
                 + Invoke-AzResourceAction -ResourceType 'Microsoft.ClassicCompute/virtu …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4
```

**Comment by brettmillerb** [comment]
So doing some further testing it appears that the API call is actually successful and stops the VM but the error is still thrown when running the command.

I can see if I can handle the error in my code for the time being to workaround the issue by adding checks for the powerState once the command is issued

```json
{
    "authorization": {
        "action": "Microsoft.ClassicCompute/virtualMachines/Stop/action",
        "scope": "/subscriptions/<SubID>/resourceGroups/t9yjs5cslt/providers/Microsoft.ClassicCompute/virtualMachines/auuzlzo3a1"
    },
    "caller": "brett.miller@domain.com",
    "channels": "Operation",
    "claims": {
        "somestuffhere": "Claims"
    },
    "correlationId": "bed22529-f2e1-4439-b5de-a6e8be52be1e",
    "description": "",
    "eventDataId": "5be7053d-12af-49c6-9819-9503421d928c",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2021-06-03T12:04:11.3800144Z",
    "id": "/subscriptions/<SubID>/resourceGroups/t9yjs5cslt/providers/Microsoft.ClassicCompute/virtualMachines/auuzlzo3a1/events/5be7053d-12af-49c6-9819-9503421d928c/ticks/637583186513800144",
    "level": "Informational",
    "operationId": "ac48abdc-63f5-47dd-ac08-b8ce4a915d30",
    "operationName": {
        "value": "Microsoft.ClassicCompute/virtualMachines/Stop/action",
        "localizedValue": "Stop Virtual Machine"
    },
    "resourceGroupName": "t9yjs5cslt",
    "resourceProviderName": {
        "value": "Microsoft.ClassicCompute",
        "localizedValue": "Microsoft.ClassicCompute"
    },
    "resourceType": {
        "value": "Microsoft.ClassicCompute/virtualMachines",
        "localizedValue": "Microsoft.ClassicCompute/virtualMachines"
    },
    "resourceId": "/subscriptions/<SubID>/resourceGroups/t9yjs5cslt/providers/Microsoft.ClassicCompute/virtualMachines/auuzlzo3a1",
    "status": {
        "value": "Succeeded",
        "localizedValue": "Succeeded"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "submissionTimestamp": "2021-06-03T12:05:21.2217421Z",
    "subscriptionId": "<SubID>",
    "tenantId": "<tenantID>",
    "properties": {
        "eventCategory": "Administrative",
        "entity": "/subscriptions/<SubID>/resourceGroups/t9yjs5cslt/providers/Microsoft.ClassicCompute/virtualMachines/auuzlzo3a1",
        "message": "Microsoft.ClassicCompute/virtualMachines/Stop/action",
        "hierarchy": "<tenantID>/<SubID>"
    },
    "relatedEvents": []
}
```

**Comment by brettmillerb** [comment]
I experienced this same issue with Move-AzResource  when run in the same environment on MacOs.
