### ISSUE TITLE
connect-azaccount Azure.RequestFailedException: The SSL connection could not be established on linux

### ISSUE THREAD

**Issue by bryanklewis** [Azure/azure-powershell#15383]
## Description

Attempting to login to Azure using a service principal on Red Hat Enterprise Linux 7 results in a failure due to SSL. Host is behind a proxy server and either powerhsell or the Az module does not appear to be honoring the http_proxy environment variables. This issue is almost identical to issue #13647 dealing with this issue on windows. However its not clear if the fix provided for windows was validated on linux and it appears to remain. No issue running login from a windows based host on the same network.

Environment variables in both UPPER and lower case as well as with and without "http://" was attempted. Only after setting the proxy server manually via "[System.Net.Http.HttpClient]::DefaultProxy" was the login successful.

## Steps to reproduce

```powershell
...
PS /> Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $TenantId -Subscription $SubscriptionId -ServicePrincipal
Connect-AzAccount: The SSL connection could not be established, see inner exception.

PS /> $env:HTTP_PROXY = 'proxy...:80'
PS /> $env:HTTPS_PROXY = 'proxy...:80'
PS /> $env:http_proxy = 'proxy...:80'
PS /> $env:https_proxy = 'proxy...:80'
PS /> Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $TenantId -Subscription $SubscriptionId -ServicePrincipal
Connect-AzAccount: The SSL connection could not be established, see inner exception.

S /> $env:http_proxy = 'http://proxy...:80'
PS /> $env:https_proxy = 'http://proxy...:80'
PS /> $env:HTTP_PROXY = 'http://proxy...:80'
PS /> $env:HTTPS_PROXY = 'http://proxy...:80'
PS /> Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $TenantId -Subscription $SubscriptionId -ServicePrincipal
Connect-AzAccount: The SSL connection could not be established, see inner exception.

PS /> [System.Net.Http.HttpClient]::DefaultProxy = New-Object System.Net.WebProxy('http://proxy...', $true)
PS /> [System.Net.Http.HttpClient]::DefaultProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
PS /> Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $TenantId -Subscription $SubscriptionId -ServicePrincipal

Account                              SubscriptionName  TenantId                             Environment
-------                              ----------------  --------                             -----------
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx MySubscription    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx AzureCloud
```

## Environment data

```
$ env --ignore-environment /bin/ksh
$ export TERM=ansi
$ export HOME=/home/myuser
$ env
_=*3210*/usr/bin/env
HOME=/home/myuser
PWD=/
SHLVL=1
TERM=ansi
A__z="*SHLVL

PS /> cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)


PS /> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
    Directory: /usr/local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     6.1.0                 Az                                  Core,Desk
Script     2.4.0                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContext…
Script     1.1.1                 Az.Advisor                          Core,Desk {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable-AzAdvisorRecommendation, …
Script     2.1.1                 Az.Aks                              Core,Desk {Get-AzAksCluster, New-AzAksCluster, Remove-AzAksCluster, Import-AzAksCredential…}
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServe…
Script     2.2.0                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductTo…
Script     1.0.0                 Az.AppConfiguration                 Core,Desk {Get-AzAppConfigurationStore, Get-AzAppConfigurationStoreKey, New-AzAppConfigurationStore, New-…
Script     1.1.1                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Update-AzA…
Script     1.7.0                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOu…
Script     3.1.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, New-AzBatchAccount…}
Script     2.0.0                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget…}
Script     1.7.1                 Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile…}
Script     1.8.0                 Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAcco…
Script     4.14.0                Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilityS…
Script     2.1.0                 Az.ContainerInstance                Core,Desk {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-AzContainerInstanceCachedImage, Get-A…
Script     2.2.3                 Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContain…
Script     1.2.0                 Az.CosmosDB                         Core,Desk {Get-AzCosmosDBSqlContainer, Get-AzCosmosDBSqlContainerThroughput, Get-AzCosmosDBSqlDatabase, G…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeDevice, New-AzDataBoxEdgeDe…
Script     1.1.0                 Az.Databricks                       Core,Desk {Get-AzDatabricksVNetPeering, Get-AzDatabricksWorkspace, New-AzDatabricksVNetPeering, New-AzDat…
Script     1.12.1                Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2…}
Script     1.0.2                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLake…
Script     1.3.0                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLa…
Script     1.0.0                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzDataShareAccount, New-AzDataShare…}
Script     1.1.0                 Az.DeploymentManager                Core,Desk {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifactSource, Set-AzDeployment…
Script     3.0.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-AzWvdApplication, Get-AzWvdApplication…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDt…
Script     1.1.2                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet…}
Script     1.3.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey…}
Script     1.8.0                 Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNa…
Script     1.8.0                 Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoor…}
Script     3.0.0                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan, Get-AzFunctionAp…
Script     4.3.0                 Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStr…
Script     1.3.1                 Az.HealthcareApis                   Core,Desk {New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-AzHealthcareApisService, Get-…
Script     2.7.3                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHub…
Script     3.4.5                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, …
Script     2.0.0                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabasePrincipal, Get-AzKustoAttachedDatabase…
Script     1.5.0                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountB…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHist…
Script     1.1.1                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfiguration, Get-AzMainte…
Script     2.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, New-AzManagedServicesAssignment, Remove-AzManagedServicesAssi…
Script     1.0.2                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaServiceKey, Get-AzMediaServic…
Script     1.0.2                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMigrateProject, Get-AzMigrateReplicatio…
Script     2.5.0                 Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile…}
Script     4.9.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCerti…
Script     1.1.1                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, G…
Script     2.3.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSou…
Script     1.4.1                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation…}
Script     1.1.2                 Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceC…
Script     1.0.3                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone, New-AzPrivateDnsZone…}
Script     4.2.0                 Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVault…
Script     1.4.0                 Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule…
Script     1.0.0                 Az.RedisEnterpriseCache             Core,Desk {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCacheDatabase,…
Script     1.0.3                 Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace…}
Script     1.0.0                 Az.ResourceMover                    Core,Desk {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveCollection, Get-AzResourceMoverMoveRes…
Script     4.2.0                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment…}
Script     1.0.0                 Az.SecurityInsights                 Core,Desk {Get-AzSentinelAlertRuleAction, New-AzSentinelAlertRuleAction, Remove-AzSentinelAlertRuleAction…
Script     1.5.0                 Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServ…
Script     3.0.0                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricNode, Add-AzServiceFabricNodeType, Ge…
Script     1.3.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey…}
Script     3.2.0                 Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity…
Script     1.1.0                 Az.SqlVirtualMachine                Core,Desk {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM…}
Script     3.8.0                 Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey…}
Script     1.5.0                 Az.StorageSync                      Core,Desk {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Get-AzStorageSyncService, Se…
Script     2.0.0                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsClusterStreamingJob, Get-AzStreamAnalyticsD…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupportTicket, Get-AzSupportTi…
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, A…
Script     2.7.0                 Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan…}
Binary     1.0.0                 Microsoft.PowerShell.SecretManagem… Core      {Register-SecretVault, Unregister-SecretVault, Get-SecretVault, Set-SecretVaultDefault…}
Binary     1.0.2                 Microsoft.PowerShell.SecretStore    Core      {Unlock-SecretStore, Set-SecretStorePassword, Get-SecretStoreConfiguration, Set-SecretStoreConf…

    Directory: /opt/microsoft/powershell/7/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.2.5                 Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   7.0.0.0               Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   7.0.0.0               Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path…}
Manifest   7.0.0.0               Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionPolicy, ConvertFrom-SecureString…}
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        Core      {Export-Alias, Get-Alias, Import-Alias, New-Alias…}
Script     1.4.7                 PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource…}
Script     2.2.5                 PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability…}
Script     2.0.5                 PSDesiredStateConfiguration         Core      {Configuration, New-DscChecksum, Get-DscResource, Invoke-DscResource}
Script     2.1.0                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLin…
Binary     2.0.3                 ThreadJob                           Desk      Start-ThreadJob

```

## Debug output

```
DEBUG: Sought all Az modules and got latest version 6.1.0
DEBUG: 1:58:10 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ServicePrincipalWithSubscriptionId'.
DEBUG: 1:58:10 PM - Autosave setting from startup session: 'Process'
DEBUG: 1:58:10 PM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 1:58:10 PM - Using Autosave scope 'Process'
DEBUG: 1:58:10 PM - Autosave setting from startup session: 'Process'
DEBUG: 1:58:10 PM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 1:58:10 PM - Using Autosave scope 'Process'
DEBUG: 1:58:10 PM - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'...', TenantId:'...', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: Request [eaa9576b-3de9-40e3-963a-a5e9fbdc37e8] GET https://login.microsoftonline.com/common/discovery/instance?api-version=REDACTED&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:eaa9576b-3de9-40e3-963a-a5e9fbdc37e8
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 5.0.4; Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018)
client assembly: Azure.Identity
DEBUG: Response [eaa9576b-3de9-40e3-963a-a5e9fbdc37e8] 200 OK (00.4s)
Cache-Control:max-age=86400, private
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Allow-Methods:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:9cf2c397-ccf6-4471-af11-52e4bc041d01
x-ms-ests-server:REDACTED
Set-Cookie:REDACTED
Date:Wed, 30 Jun 2021 19:58:10 GMT
Content-Type:application/json; charset=utf-8
Content-Length:980

DEBUG: Request [2de06ea1-f6b4-4f11-a29d-c73fa79cc36d] POST https://login.microsoftonline.com/f38a5ecd-2813-4862-b11b-ac1d563c806f/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:2de06ea1-f6b4-4f11-a29d-c73fa79cc36d
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 5.0.4; Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [2de06ea1-f6b4-4f11-a29d-c73fa79cc36d] 200 OK (00.1s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:d9c678af-59f6-4437-96ef-788214f13700
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Set-Cookie:REDACTED
Date:Wed, 30 Jun 2021 19:58:10 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1427

DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-06-30T20:58:09.0000000+00:00
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/....?api-version=2019-06-01

Headers:
x-ms-client-request-id        : 3474dc50-d3db-4683-b2be-885150316775
Accept-Language               : en-US

Body:



Connect-AzAccount: The SSL connection could not be established, see inner exception.
DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:00.8901000; Exception - The SSL connection could not be established, see inner exception.;
DEBUG: Finish sending metric.
DEBUG: 1:58:11 PM - ConnectAzureRmAccountCommand end processing.
```

## Error output
```
Message        : The SSL connection could not be established, see inner exception.
StackTrace     :    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken
                  cancellationToken)
                    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationTo
                 ken)
                    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
                    at Microsoft.Rest.RetryAfterDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                    at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendAsync>b__0>d.MoveNext()
                 --- End of stack trace from previous location ---
                    at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.CancelRetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
                    at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartSto
                 p, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ResourceManager.Version2019_06_01.SubscriptionsOperations.GetWithHttpMessagesAsync(String subscriptionId, Dictionary`2 custom
                 Headers, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ResourceManager.Version2019_06_01.SubscriptionsOperationsExtensions.GetAsync(ISubscriptionsOperations operations, String subs
                 criptionId, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ResourceManager.Version2019_06_01.SubscriptionsOperationsExtensions.Get(ISubscriptionsOperations operations, String subscript
                 ionId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.Utilities.Version2019_06_01.SubscriptionClientWrapper.GetSubscriptionById(String subscriptionId, IAccess
                 Token accessToken, IAzureAccount account, IAzureEnvironment environment)
                    at Microsoft.Azure.Commands.Profile.Models.SubscriptionClientProxy.<>c__DisplayClass6_0.<GetSubscriptionById>b__0(ISubscriptionClientWrapper client)
                    at Microsoft.Azure.Commands.Profile.Models.SubscriptionClientProxy.<>c.<.ctor>b__2_0(Action`1 subscriptionClientAction, LoggerWriter warning)
                    at Microsoft.Azure.Commands.Profile.Models.SubscriptionClientProxy.GetSubscriptionById(String subscriptionId, IAccessToken accessToken, IAzureAccount accou
                 nt, IAzureEnvironment environment)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.TryGetTenantSubscription(IAccessToken accessToken, IAzureAccount account, IAzureEnvironm
                 ent environment, String subscriptionId, String subscriptionName, Boolean isTenantPresent, IAzureSubscription& subscription, IAzureTenant& tenant)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subs
                 criptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int
                 32 maxContextPopulation, String authScope)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass118_2.<ExecuteCmdlet>b__5()
                    at System.Threading.Tasks.Task`1.InnerInvoke()
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Ob
                 ject state)
                 --- End of stack trace from previous location ---
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass118_0.<ExecuteCmdlet>b__1(AzureRmProfile localProfile, RMProfileClient pr
                 ofileClient, String name)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass126_0.<SetContextWithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileC
                 lient client)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Net.Http.HttpRequestException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $TenantId -Subscription $SubscriptionId -ServicePrincipal
Position       : At line:1 char:1
                 + Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $Te …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 16

Message        : Unable to read data from the transport connection: Connection reset by peer.
StackTrace     :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
                    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
                    at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 m
                 inSize)
                    at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
                    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
                    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken
                  cancellationToken)
Exception      : System.IO.IOException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $TenantId -Subscription $SubscriptionId -ServicePrincipal
Position       : At line:1 char:1
                 + Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $Te …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 16

Message        : Connection reset by peer
StackTrace     :
Exception      : System.Net.Sockets.SocketException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $TenantId -Subscription $SubscriptionId -ServicePrincipal
Position       : At line:1 char:1
                 + Connect-AzAccount -Credential $ServicePrincipalCredential -Tenant $Te …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 16
```

**Comment by dingmeng-xue** [comment]
Thanks, we will look into it.

**Comment by erich-wang** [comment]
@bryanklewis, as HttpClient.DefaultProxy is singleton object and lazy initialized, we must make sure the following two environment variables be set before running any cmdlets from Azure PowerShell:
```powershell
PS /> $env:HTTP_PROXY = 'http://proxy...:80'
PS /> $env:HTTPS_PROXY = 'http://proxy...:80'
```
You may verify whether proxy is respected after setting proxy environment variables:
```powershell
[System.Net.Http.HttpClient]::DefaultProxy.GetProxy("https://google.com")  #it returns nothing if proxy is not respected
```

I would suggest you set the two environment variables before starting pwsh, or set them right after starting pwsh and verify using `[System.Net.Http.HttpClient]::DefaultProxy.GetProxy("https://google.com")`.

**Comment by bryanklewis** [comment]
@erich-wang. As suggested, I tested providing proxy settings BEFORE launching pwsh and AFTER launching pwsh. PowerShell successfully creates the proxy singleton _only_ if the variables are provided BEFORE launching pwsh. Providing the variables after launching pwsh has no effect and the proxy values are not respected.

**BEFORE** pwsh
```powershell
$ export HTTP_PROXY='http://proxy-web...'
$ export HTTPS_PROXY='http://proxy-web...'
$ pwsh
PowerShell 7.1.3
…
PS /oracle> [System.Net.Http.HttpClient]::DefaultProxy.GetProxy('https://www.google.com')
AbsolutePath   : /
AbsoluteUri    : http://proxy-web.../
LocalPath      : /
Authority      : proxy-web…
# Success!
```

**AFTER** pwsh
```shell
PS /> $env:HTTP_PROXY = 'http://proxy-web…'
PS /> $env:HTTPS_PROXY = 'http://proxy-web…'
PS /> [System.Net.Http.HttpClient]::DefaultProxy.GetProxy('https://www.google.com')
# Failure, no result.
```

Setting the environment before launching powershell gives me a workaround. If the intended behavior is that the proxy should be observed when launching powershell and setting the environment via $env:HTTP_PROXY then there is still an issue.

**Comment by erich-wang** [comment]
@bryanklewis, please set environment variables before starting pwsh. During staring pwsh, pwsh itself may (not always) call HttpClient which results in HttpClient.DefaultClient singleton instance be created, then the environment variables set after starting pwsh won't be respected.

**Comment by bryanklewis** [comment]
Sounds like setting the proxy env vars before launching pwsh is the best method.
