### ISSUE TITLE
Microsoft.KeyVault/vaults/secrets does not support Update-AzTag

### ISSUE THREAD

**Issue by woter1832** [Azure/azure-powershell#15426]
## Description
When trying to add a tag to a secret using `Update-AzTag` or `New-AzTag`, I receive the error:
`Operation returned an invalid status code 'NotImplemented'`

If I use `Set-AzKeyVaultSecret -Tag $Tags`, it prompts me to enter the `SecretValue` which I don't want to change, and shouldn't be a mandatory parameter.

## Steps to reproduce

```powershell
$Tags = @{
    "spn" = "aadsp-z03-terraform"
    "tf_attribute" = $tf_attribute
  }
$oContext = Get-AzContext
  $ResourceId = "/subscriptions/{0}/resourceGroups/{1}/providers/Microsoft.KeyVault/vaults/{2}/secrets/{3}" -f $oContext.Subscription.Id, $ResourceGroupName, $KeyVaultName, $secret.Name

Update-AzTag -ResourceId $ResourceId -Tag $Tags -Operation Replace -Verbose
```

## Environment data

```
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
PS C:\> Get-Command Update-AzTag


CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Update-AzTag                                       4.2.0      Az.Resources

PS C:\> Get-Command Set-AzKeyVaultSecret


CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Set-AzKeyVaultSecret                               3.4.5      Az.KeyVault
```

## Debug output

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com//subscriptions/blah/resourceGroups/rgpz02share01/providers/Microsoft.KeyVault/vaults/kvtz02share0102/secrets/CLIENT-ID/providers/Microsoft.Resources/tags/default?api-version=2020-10-01

Headers:
x-ms-client-request-id        : 30111102-83b9-4064-8bef-49d364cb0384
Accept-Language               : en-US

Body:
{
  "operation": "Replace",
  "properties": {
    "tags": {
      "spn": "aadsp-z03-terraform",
      "tf_attribute": "client_id"
    }
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotImplemented

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 9a6a4d3b-f271-461a-814f-c561c83a12d4
x-ms-correlation-request-id   : 9a6a4d3d-f271-461a-814f-c561c83a12d4
x-ms-failure-cause            : gateway
x-ms-routing-request-id       : UKSOUTH:20210707T105920Z:9a6a4d3b-f271-461a-814f-c561c83a12d4
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Wed, 07 Jul 2021 10:59:20 GMT
Connection                    : close

Body:



Update-AzTag: C:\scripts\Set-KVSecretTags.ps1:30:3
Line |
  30 |    Update-AzTag -ResourceId $ResourceId -Tag $Tags -Operation Replace  …
     |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation returned an invalid status code 'NotImplemented'

DEBUG: AzureQoSEvent: CommandName - Update-AzTag; IsSuccess - False; Duration - 00:00:00.1685179; Exception - Operation returned an invalid status code 'NotImplemented';
DEBUG: Finish sending metric.
DEBUG: 11:59:21 - UpdateAzureTagCommand end processing.
```

## Error output

```
PS C:\> Resolve-AzError -Last          

DEBUG: 12:02:47 - ResolveError begin processing with ParameterSet 'LastErrorParameterSet'.
DEBUG: 12:02:47 - using account id 'john@domain.com'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 315

RequestId      : 9c6a4d3b-f271-461c-814f-c561c83a12d4
Message        : Operation returned an invalid status code 'NotImplemented'
ServerMessage  :
ServerResponse : {NotImplemented}
RequestMessage : {PATCH https://management.azure.com//subscriptions/blah/resourceGroups/rgpz02share01/providers/Microsoft.KeyVault/vaults/kvtz02share0102/secrets/CLIENT-ID/providers/Microsoft.Resources/tags/default?api-version=2020-10-01}
InvocationInfo : {Update-AzTag}
Line           :   Update-AzTag -ResourceId $ResourceId -Tag $Tags -Operation Replace -Verbose

Position       : At C:\scripts\Set-KVSecretTags.ps1:30 char:3
                 +   Update-AzTag -ResourceId $ResourceId -Tag $Tags -Operation Replace  …
                 +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.ResourceManager.TagsOperations.UpdateAtScopeWithHttpMessagesAsync(String scope, TagsPatchResource parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ResourceManager.TagsOperationsExtensions.UpdateAtScopeAsync(ITagsOperations operations, String scope, TagsPatchResource parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ResourceManager.TagsOperationsExtensions.UpdateAtScope(ITagsOperations operations, String scope, TagsPatchResource parameters)
                    at Microsoft.Azure.Commands.Tags.Client.TagsClient.UpdateTagAtScope(String scope, TagPatchOperation operation, IDictionary`2 parameters)
                    at Microsoft.Azure.Commands.Tags.Tag.UpdateAzureTagCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 315


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.0345418
DEBUG: Finish sending metric.
DEBUG: 12:02:48 - ResolveError end processing.
```

**Comment by rthorn17** [comment]
Hi @woter1832, Thanks for submitting the issue.  Currently Azure Key Vault doesn't support Tags on secrets, so this is not an option.  I will tag this for Azure Key Vault team so they be aware of the ask.  The current list of Tag supported resources can be viewed at [https://docs.microsoft.com/azure/azure-resource-manager/management/tag-support#microsoftkeyvault](url)
