### ISSUE TITLE
Using the DefaultProfile parameter raises an error on Az 6.2.0

### ISSUE THREAD

**Issue by OmriAvissar** [Azure/azure-powershell#15425]
## Description

Multiple Az cmdlets raise the following error while specifying the DefaultProfile parameter:
Error getting value from 'Tags' on 'Microsoft.Azure.Commands.Profile.Models.PSAzureSubscription'.

Using the same cmdlets with the same account, without specifying DefaultProfile works as expected.

Happens with a user principal/service principal/system-assigned managed identity (I've tried with Azure Functions).

Note that the following is true:
```
$null -eq (Connect-AzAccount).Context.Subscription.Tags
```

maybe related to the following entry in the changelog:

Az.Accounts
Added Tags, AuthorizationSource to PSAzureSusbscripiton and added TenantType, DefaultDomain, TenantBrandingLogoUrl, CountryCode to PSAzureTenant [#15220]

## Steps to reproduce

```
$UserName = '...'
$UserPassword = '...'
$UserPasswordSecureString = ConvertTo-SecureString $UserPassword -AsPlainText -Force
$UserPsCredential = [System.Management.Automation.PSCredential]::New($UserName, $UserPasswordSecureString)

$AzureProfile = Connect-AzAccount -Subscription '...' -Credential $UserPsCredential
$AzureContext = $AzureProfile.Context

$SetAzSqlDatabaseParameters = @{
    'ResourceGroupName'             = '...'
    'ServerName'                    = '...'
    'DatabaseName'                  = '...'
    'RequestedServiceObjectiveName' = 'S0'
    'ComputeModel'                  = 'Provisioned'
}

Set-AzSqlDatabase @SetAzSqlDatabaseParameters -DefaultProfile $AzureContext
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     6.2.0                 Az                                  Core,Desk
Script     6.1.0                 Az                                  Core,Desk
Script     5.1.0                 Az                                  Core,Desk
```

## Debug output

```
OperationStopped: Error getting value from 'Tags' on 'Microsoft.Azure.Commands.Profile.Models.PSAzureSubscription'.
```

## Error output

```
   HistoryId: -1

Message        : Error getting value from 'Tags' on 'Microsoft.Azure.Commands.Profile.Models.PSAzureSubscription'.
StackTrace     :    at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property,
                 JsonContract& memberContract, Object& memberValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract,     
                 JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract,     
                 JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract
                 collectionContract, JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract,     
                 JsonProperty containerProperty)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
                    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
                    at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
                    at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Formatting formatting, JsonConverter[] converters)
                    at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.ToString(Boolean serializeCache)
                    at Microsoft.Azure.Commands.Common.Authentication.Models.AzureRmProfile.ToString()
                    at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object     
                 currentValue)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)  
                    at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
                    at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {}
Line           : Set-AzSqlDatabase @SetAzSqlDatabaseParameters -DefaultProfile $AzureContext
Position       : At line:1 char:1
                 + Set-AzSqlDatabase @SetAzSqlDatabaseParameters -DefaultProfile $AzureC …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Value cannot be null. (Parameter 'value')
StackTrace     :    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.AzureSubscriptionExtensions.GetTags(IAzureSubscription subscription)
                    at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
Exception      : System.ArgumentNullException
InvocationInfo : {}
Line           : Set-AzSqlDatabase @SetAzSqlDatabaseParameters -DefaultProfile $AzureContext
Position       : At line:1 char:1
                 + Set-AzSqlDatabase @SetAzSqlDatabaseParameters -DefaultProfile $AzureC …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by OmriAvissar** [comment]
I've tried using Az.Accounts version 2.4.0 instead of 2.5.0.

It seems to work fine.

**Comment by dingmeng-xue** [comment]
Thanks @OmriAvissar . We will look into this issue with high priority.

**Comment by dingmeng-xue** [comment]
Root cause may be related to this code https://github.com/Azure/azure-powershell-common/pull/270/files#diff-56de635b77f61434ff858843b19475648f8aad178ab9159bb81ec0a28b1e1577R203

**Comment by misterfoo** [comment]
This is affecting us too. A short-term workaround seems to be adding at least one tag on the subscription, but this definitely seems like a bug.

**Comment by dcaro** [comment]
We will release Az 6.2.1 early next week to address this issue.

**Comment by dingmeng-xue** [comment]
Az 6.2.1 and Az.Accounts 2.5.1 have been released.
