### ISSUE TITLE
WebApp:Get-AzWebAppSnapshot cmdlet Issue

### ISSUE THREAD

**Issue by MayankBargali-MSFT** [Azure/azure-powershell#15422]
## Description
One of our customer observed below error while executing the below command. I have collected the -debug output from the customer and I can see that the issue is while parsing the field (propertiestime) to DateTime on the response we get from List snapshot REST API (not sure for all json object or only one-two json object)
Get-AzWebAppSnapshot -ResourceGroupName $AppServicePlanResourceGroup -Name $WebAppName

Error: 
[2021-07-02T08:43:45.157Z] ERROR: String '06/13/2021 14:32:13' was not recognized as a valid DateTime.
[2021-07-02T08:43:45.157Z] 
[2021-07-02T08:43:45.157Z] Exception             : 
[2021-07-02T08:43:45.157Z]     Type       : System.FormatException
[2021-07-02T08:43:45.157Z]     TargetSite : 
[2021-07-02T08:43:45.157Z]         Name          : Parse
[2021-07-02T08:43:45.157Z]         DeclaringType : System.DateTimeParse, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
[2021-07-02T08:43:45.157Z]         MemberType    : Method
[2021-07-02T08:43:45.157Z]         Module        : System.Private.CoreLib.dll
[2021-07-02T08:43:45.157Z]     StackTrace : 
[2021-07-02T08:43:45.157Z]    at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
[2021-07-02T08:43:45.157Z]    at System.DateTime.Parse(String s)
[2021-07-02T08:43:45.157Z]    at Microsoft.Azure.Commands.WebApps.Cmdlets.BackupRestore.GetAzureWebAppSnapshot.<ExecuteCmdlet>b__4_0(Snapshot s)
[2021-07-02T08:43:45.157Z]    at System.Linq.Enumerable.SelectListIterator`2.ToArray()
[2021-07-02T08:43:45.157Z]    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
[2021-07-02T08:43:45.157Z]    at System.Linq.OrderedEnumerable`1.ToArray()
[2021-07-02T08:43:45.157Z]    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
[2021-07-02T08:43:45.157Z]    at Microsoft.Azure.Commands.WebApps.Cmdlets.BackupRestore.GetAzureWebAppSnapshot.ExecuteCmdlet()
[2021-07-02T08:43:45.158Z]    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
[2021-07-02T08:43:45.158Z]    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
[2021-07-02T08:43:45.158Z]    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
[2021-07-02T08:43:45.158Z]    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

Name                           Value
----                           -----
PSVersion                      7.0.6
PSEdition                      Core
GitCommitId                    7.0.6
OS                             Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu …
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Interestingly the issue is only observed while executing it VS Code for function and we see the same exception:
<img width="1324" alt="test" src="https://user-images.githubusercontent.com/67255909/124639042-4e558980-dea9-11eb-8686-0290724be611.png">

<img width="1309" alt="cap1" src="https://user-images.githubusercontent.com/67255909/124639129-6a592b00-dea9-11eb-9b7f-3e5e14589984.png">

But when running the command from terminal it works fine at customer end and we see the az and az.websites modules are same.

<img width="1612" alt="cap2" src="https://user-images.githubusercontent.com/67255909/124639248-92488e80-dea9-11eb-8249-b80e94d04763.png">

I can share the Get-AZSnapshot_DebugOutput and Response_from_list-snapshots_REST_API offline for more details.

**Comment by Kotasudhakarreddy** [comment]
Unable to repro in the latest Az.Websites module (2.8.0). Update to latest module using `Update-Module -Name Az.Websites` should resolve the issue.
