### ISSUE TITLE
Get-AzAutomationJob (Az.Automation 1.7.0): Conversion from JSON failed with error: Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by RylandDeGregory** [Azure/azure-powershell#15707]
## Description

`Get-AzAutomationJob` fails on the latest version of Az.Automation with an error about JSON parsing. This error is identical to #7977 but on a different cmdlet...

## Steps to reproduce

```powershell
Get-AzAutomationJob -Id 'MYJOBID' -AutomationAccountName 'MYAA' -ResourceGroupName 'MYAARESOURCEGROUP'
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEA…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.5.2                 Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave,…
Script     1.7.0                 Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomati…
Script     4.16.0                Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New…
Script     3.4.5                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertific…
Script     0.11.0                Az.ResourceGraph                    Core,Desk {Search-AzGraph, Get-AzResourceGraphQuery, New-AzReso…
Script     4.3.0                 Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Ge…
Script     3.10.0                Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-A…
Script     1.0.4                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-A…
Manifest   2.1.0                 AzTable                             Desk      {Add-AzTableRow, Get-AzTableRow, Get-AzTableRowAll, G…
```

## Debug output

```
DEBUG: 5:34:11 PM - GetAzureAutomationJob begin processing with ParameterSet 'ByJobId'.
DEBUG: 5:34:11 PM - using account id 'xxxx'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx', environment: 'AzureCloud', tenant: 'xxx'
DEBUG: 5:34:11 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxx', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11] Found 2 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11] Returning 2 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(4bd15149-f790-4f1c-8f3c-b61f07715c46)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - xxx

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] === Token Acquisition (SilentRequest) started:

	Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] Access token is not expired. Returning the found cache entry. [Current time (08/18/2021 21:34:11) - Expiration Time (08/18/2021 22:16:31 +00:00) - Extended Expiration Time (08/18/2021 22:16:31 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 [08/18/2021 21:34:11 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 08/18/2021 22:16:31 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-08-18T22:16:31.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxx', UserId: 'xxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Automation/automationAccounts/xxx/jobs/xxx?api-version=2019-06-01

Headers:
x-ms-client-request-id        : xxx
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : xxx
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-resource-requests: 599
x-ms-correlation-request-id   : xxx
x-ms-routing-request-id       : CENTRALUS:20210818T213412Z:xxx
X-Content-Type-Options        : nosniff
Date                          : Wed, 18 Aug 2021 21:34:11 GMT

Body:
{
  "id": "/subscriptions/xxx/resourceGroups/rg-automation/providers/Microsoft.Automation/automationAccounts/xxx/jobs/xxx",
  "name": "xxx",
  "type": "Microsoft.Automation/AutomationAccounts/Jobs",
  "properties": {
    "jobId": "xxx",
    "creationTime": "2021-08-17T16:36:20.1116066-04:00",
    "provisioningState": "Succeeded",
    "status": "Completed",
    "statusDetails": "None",
    "startedBy": "{scrubbed}",
    "startTime": "2021-08-17T16:36:30.2306952-04:00",
    "endTime": "2021-08-17T16:51:13.3996749-04:00",
    "lastModifiedTime": "2021-08-17T16:51:13.3996749-04:00",
    "lastStatusModifiedTime": "2021-08-17T16:51:13.3996749-04:00",
    "exception": null,
    "parameters": {
      "xxx": "xxx"
    },
    "runOn": "xxx",
    "runbook": {
      "name": "xxx"
    }
  }
}


Get-AzAutomationJob: Conversion from JSON failed with error: Unexpected character encountered while parsing value: A. Path '', line 0, position 0.
DEBUG: AzureQoSEvent: Module: Az.Automation:1.7.0; CommandName: Get-AzAutomationJob; PSVersion: 7.1.4; IsSuccess: False; Duration: 00:00:00.7494416; Exception: Conversion from JSON failed with error: Unexpected character encountered while parsing value: A. Path '', line 0, position 0.;
DEBUG: Finish sending metric.
DEBUG: 5:34:12 PM - GetAzureAutomationJob end processing.
```

## Error output

```
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 1

Message        : Conversion from JSON failed with error: Unexpected character encountered while parsing value: A. Path '', line 0, position 0.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.Runspaces.Pipeline.Invoke()
                    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke()
                    at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.InvokeScript(String scriptName, Hashtable parameters)
                    at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.Deserialize(String json)
                    at Microsoft.Azure.Commands.Automation.Model.Job..ctor(String resourceGroupName, String accountName, Job job)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetJob(String resourceGroupName, String automationAccountName, Guid Id)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationJob.AutomationProcessRecord()
                    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.CmdletInvocationException
InvocationInfo : {Get-AzAutomationJob}
Line           : Get-AzAutomationJob -Id 'xxx' -AutomationAccountName 'xxx' -ResourceGroupName 'xxx'
Position       : At line:1 char:1
                 + Get-AzAutomationJob -Id 'xxx' -Autom …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Conversion from JSON failed with error: Unexpected character encountered while parsing value: A. Path '', line 0, position 0.
StackTrace     :    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing()
                    at System.Management.Automation.Cmdlet.DoEndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzAutomationJob}
Line           : Get-AzAutomationJob -Id 'xxx' -AutomationAccountName 'xxx' -ResourceGroupName 'xxx'
Position       : At line:1 char:1
                 + Get-AzAutomationJob -Id 'xxx' -Autom …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Unexpected character encountered while parsing value: A. Path '', line 0, position 0.
StackTrace     :    at Newtonsoft.Json.JsonTextReader.ParseValue()
                    at Newtonsoft.Json.JsonTextReader.Read()
                    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings)
                    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
Exception      : Newtonsoft.Json.JsonReaderException
InvocationInfo : {Get-AzAutomationJob}
Line           : Get-AzAutomationJob -Id 'xxx' -AutomationAccountName 'xxx' -ResourceGroupName 'xxx'
Position       : At line:1 char:1
                 + Get-AzAutomationJob -Id 'xxx' -Autom …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by RylandDeGregory** [comment]
Following up, I tested on Windows PowerShell, and the cmdlet worked as expected, so this must be an issue with PS7 (or maybe MacOS):

```
PS> Get-AzAutomationJob -Id 'xxx' -AutomationAccountName 'xxx' -ResourceGroupName 'xxx'


ResourceGroupName      : xxx
AutomationAccountName  : xxx
JobId                  : xxx
CreationTime           : 8/17/2021 4:36:20 PM -04:00
Status                 : Completed
StatusDetails          : None
StartTime              : 8/17/2021 4:36:30 PM -04:00
EndTime                : 8/17/2021 4:51:13 PM -04:00
Exception              :
LastModifiedTime       : 8/17/2021 4:51:13 PM -04:00
LastStatusModifiedTime : 8/17/2021 4:51:13 PM -04:00
JobParameters          : {xxx}
RunbookName            : xxx
HybridWorker           : xxx
StartedBy              : {scrubbed}
```

Output of `$PSVersionTable`:

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1971
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1971
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Output of `Get-Module -ListAvailable | Where { $_.Name -like 'Az*' }`:

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.4      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     1.4.2      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationR...
```

**Comment by RylandDeGregory** [comment]
Hi @jaspkaur28 do you have any information to provide regarding this issue?

**Comment by mahakjain314** [comment]
@RylandDeGregory  Is it only happening for a certain Linux distro?

**Comment by RylandDeGregory** [comment]
> @RylandDeGregory Is it only happening for a certain Linux distro?

@mahakjain314, I use MacOS Big Sur 11.5.2 on an M1 MacBook Air.

**Comment by mahakjain314** [comment]
@RylandDeGregory Would it be possible for you to share the job parameters from the debug response?

**Comment by RylandDeGregory** [comment]
Hey @mahakjain314 it looks like I am no longer able to reproduce the issue...? I haven't changed anything about my environment, so I'm not sure why it works now...
![Screen Shot 2021-09-03 at 9 18 25 AM](https://user-images.githubusercontent.com/18073815/132011826-90f4347c-d89b-4dc5-add8-17c2a19b0114.png)

**Comment by mahakjain314** [comment]
Excellent. Good to hear that. 

Maybe try with the same job id once for which you originally raised the issue? It had some parameters. 
It would be very helpful if you can share the job parameters next time you see the issue!

**Comment by RylandDeGregory** [comment]
I tried again with the original job and it is also now working.

The job parameters contain resource names and IDs that are private in nature, so unfortunately I cannot share the specific values in a public forum.

Thank you for your assistance!
