### ISSUE TITLE
Error occurred while creating Log Alert rule ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'

### ISSUE THREAD

**Issue by csharpdocs** [Azure/azure-powershell#15800]
## Description

**What I'm Trying to DO?**
I am trying to create azure virtual machine alert for low diskspace using powershell and i'm running that powershell from my azure pipeline. Once i run the task i encountered with error "Error occurred while creating Log Alert rule ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'"

**Azure DevOps Pipeline Task?**

- task: AzurePowerShell@5
    displayName: Alert - VM Low Disk Space
    inputs:
      azureSubscription: myazurergconnection
      ScriptType: InlineScript
      Inline: |
$actionId=(Get-AzActionGroup -ResourceGroupName 'abcd-devops-d-rg' -Name 'myactionname').Id
               $actionGroup = New-AzScheduledQueryRuleAznsActionGroup -ActionGroup $actionId

                $source = New-AzScheduledQueryRuleSource -Query 'Perf | where ObjectName == "LogicalDisk" or ObjectName == "Logical Disk" | where TimeGenerated > ago(5m) | where CounterName == "Free Megabytes" | where InstanceName == "C:"and computer startswith "abcd-01-wvm" | summarize arg_max TimeGenerated, *) by InstanceName | project TimeGenerated, InstanceName, CounterValue, Computer, _ResourceId' -DataSourceId "/subscriptions/$(SubscriptionId)/resourceGroups/abcd-devops-d-rg/providers/microsoft.insights/scheduledqueryrules/abcd-01-wvm-lowdiskspace"

		$schedule = New-AzScheduledQueryRuleSchedule -FrequencyInMinutes 15 -TimeWindowInMinutes 15

		$triggerCondition = New-AzScheduledQueryRuleTriggerCondition -ThresholdOperator "LessThan" -Threshold 7000 

		$aznsActionGroup = New-AzScheduledQueryRuleAznsActionGroup -ActionGroup "/subscriptions/$(SubscriptionId)/resourceGroups/abcd-devops-d-rg/providers/microsoft.insights/actiongroups/abcd-monitor-ag" -CustomWebhookPayload "{ `"alert`":`"abcd-01-wvm-lowdiskspace`", `"IncludeSearchResults`":true }"

		$alertingAction = New-AzScheduledQueryRuleAlertingAction -AznsAction $aznsActionGroup -Severity "3" -Trigger $triggerCondition

		New-AzScheduledQueryRule -ResourceGroupName "abcd-devops-d-rg" -Location "West Europe" -Action $alertingAction -Enabled $true -Description "CI00XXXXX" -Schedule $schedule -Source $source -Name "abcd-01-wvm-lowdiskspace"
      azurePowerShellVersion: 'LatestVersion'

**I also tried below but wont work**

- task: AzurePowerShell@5
    displayName: Alert - VM Low Disk Space
    inputs:
      azureSubscription: myazurergconnection
      ScriptType: InlineScript
      Inline: |
        $actionId=(Get-AzActionGroup -ResourceGroupName 'abcd-devops-d-rg' -Name 'myactionname').Id
        $actionGroup = New-AzScheduledQueryRuleAznsActionGroup -ActionGroup $actionId

        $source = New-AzScheduledQueryRuleSource -DataSourceId "/subscriptions/$(SubscriptionId)/resourceGroups/'abcd-devops-d-rg'/providers/microsoft.insights/scheduledqueryrules/abcd-01-wvm-lowdiskspace"  -Query 'Perf | where ObjectName == "LogicalDisk" or ObjectName == "Logical Disk" | where TimeGenerated > ago(5m) | where CounterName == "Free Megabytes" | where InstanceName == "C:"and Computer startswith "abcd-01-wvm" | summarize arg_max TimeGenerated, *) by InstanceName | project TimeGenerated, InstanceName, CounterValue, Computer, _ResourceId'
        $schedule = New-AzScheduledQueryRuleSchedule -FrequencyInMinutes 15 -TimeWindowInMinutes 15          
        $triggerCondition = New-AzScheduledQueryRuleTriggerCondition -ThresholdOperator "LessThan" -Threshold 7000  
        $alertingAction = New-AzScheduledQueryRuleAlertingAction -AznsAction $actionGroup -Severity "4" -Trigger $triggerCondition
        New-AzScheduledQueryRule -Location "West Europe" -Action $alertingAction -Enabled $true -Description 'CI00XXXXX' -Schedule $schedule -Source $source -Name abcd-01-wvm-lowdiskspace -ResourceGroupName 'abcd-devops-d-rg'
      azurePowerShellVersion: 'LatestVersion'

**What is exactly error?**

2021-09-01T15:56:16.2051520Z ##[error]Exception type: Exception, Message: System.Exception: Error occurred while creating Log Alert rule ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.ScheduledQueryRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
2021-09-01T15:56:16.2075590Z ##[debug]Processed: ##vso[task.logissue type=error]Exception type: Exception, Message: System.Exception: Error occurred while creating Log Alert rule ---> System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'%0D%0A   at Microsoft.Azure.Management.Monitor.ScheduledQueryRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()%0D%0A   --- End of inner exception stack trace ---%0D%0A   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)%0D%0A   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()%0D%0A   --- End of inner exception stack trace ---%0D%0A   at Microsoft.Azure.Commands.Insights.ScheduledQueryRules.NewScheduledQueryRuleCommand.ProcessRecordInternal()%0D%0A   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
2021-09-01T15:56:16.2688988Z ##[debug]Exit code: 1
2021-09-01T15:56:16.2818600Z ##[debug]Leaving Invoke-VstsTool.
2021-09-01T15:56:16.3138305Z ##[error]PowerShell exited with code '1'.

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We need to understand the issue according to request and response payload. Could you provide debug message of issue cmdlet execution? You can turn on it via `$DebugPreference = "Continue"`.
