### ISSUE TITLE
Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'.

### ISSUE THREAD

**Issue by YogiPanchanathan** [Azure/azure-powershell#16353]
### Description

Recently we are getting this error 

"Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'."

More details step on reproducing this issues  is Given in the below link
https://developercommunity.visualstudio.com/t/PowerShell-script-with-workflow-stopped/1564277?space=21&entry=problem&q=PowerShell+workflow+&moreInfo=true&viewtype=all

Basically this issue occurs in a script where  we use powershell workflow and azure powershell module. Please lets know if more information is needed.

### Issue script & Debug output

```PowerShell
S C:\ACRGUI\Code> $DebugPreference = 'Continue'

PS C:\ACRGUI\Code> C:\ACRGUI\Code\Add-CUAOnExistingResources.ps1
Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'.
Execution completed
UI Closing
UI Closed
DEBUG: 2:30:48 PM - ClearAzureRmContext begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 2:30:48 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 2:30:48 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 2:30:48 PM - Using Autosave scope 'CurrentUser'
DEBUG: 2:30:48 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 2:30:48 PM - No autosave setting detected in environment variable 'AzContextAutoSave'. 
DEBUG: 2:30:48 PM - Using Autosave scope 'CurrentUser'
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.6.1; CommandName: Clear-AzContext; PSVersion: 5.1.14393.4583; IsSuccess: True; Duration: 00:00:00.0341465
DEBUG: Finish sending metric.
DEBUG: 2:30:49 PM - ClearAzureRmContext end processing.
Execution completed
UI Closing
UI Closed
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                 
----                           -----                                                                                                                                                 
PSVersion                      5.1.14393.4583                                                                                                                                        
PSEdition                      Desktop                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                               
BuildVersion                   10.0.14393.4583                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                   
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                                           
---------- -------    ----                                ----------------                                                                                                           
Script     2.6.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                                
Script     4.4.1      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential...}
```

### Error output

```PowerShell
DEBUG: 3:13:42 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.


   HistoryId: 9


Message        : The term 'resovle-azerror' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
                 included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions 
                 searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, 
                 CommandRedirection[] redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] 
                 pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : resovle-azerror
Position       : At line:1 char:1
                 + resovle-azerror
                 + ~~~~~~~~~~~~~~~
HistoryId      : 9



   HistoryId: -1


Message        : Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'.
StackTrace     :    at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String 
                 targetName, IAddLineInfo lineInfo)
                    at System.Xaml.XamlObjectWriter.Logic_CreatePropertyValueFromValue(ObjectWriterContext ctx)
                    at System.Xaml.XamlObjectWriter.WriteEndMember()
                    at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
                    at System.Xaml.XamlServices.Load(XamlReader xamlReader)
                    at System.Activities.XamlIntegration.ActivityXamlServices.Load(XamlReader xamlReader, ActivityXamlServicesSettings settings)
                    at System.Activities.XamlIntegration.ActivityXamlServices.Load(XmlReader xmlReader, ActivityXamlServicesSettings settings)
                    at System.Activities.XamlIntegration.ActivityXamlServices.Load(TextReader textReader, ActivityXamlServicesSettings settings)
                    at Microsoft.PowerShell.Commands.ImportWorkflowCommand.ConvertXamlToActivity(String xaml)
                    at Microsoft.PowerShell.Workflow.DefinitionCache.CompileActivityAndSaveInCache(WorkflowJobDefinition definition, Activity activityTree, Dictionary`2 
                 requiredAssemblies, Boolean& windowsWorkflow, String rootWorkflowName)
                    at Microsoft.PowerShell.Commands.ImportWorkflowCommand.CreateFunctionFromXaml(String name, String xaml, Dictionary`2 requiredAssemblies, String[] 
                 dependentWorkflows, String dependentAssemblyPath, Dictionary`2 parameterValidation, String modulePath, Boolean scriptWorkflow, String workflowAttributes, String 
                 scriptContent, String fullScript, String rootWorkflowName, Nullable`1 sourceLanguageMode, ReadOnlyCollection`1 attributeAstCollection)
                    at Microsoft.PowerShell.Workflow.AstToWorkflowConverter.CompileSingleWorkflow(Scope scope, FunctionDefinitionAst func, Dictionary`2 scriptBlockTokenCache, 
                 PSModuleInfo definingModule, IEnumerable`1 assemblyList, Dictionary`2 activityMap, HashSet`1 processedActivityLibraries, PowerShell invoker, Nullable`1 
                 sourceLanguageMode, String rootWorkflowName)
                    at Microsoft.PowerShell.Workflow.AstToWorkflowConverter.CompileWorkflowsImpl(ScriptBlockAst ast, PSModuleInfo definingModule, InitialSessionState 
                 initialSessionState, Nullable`1 sourceLanguageMode, ParseException& parsingErrors, String rootWorkflowName)
                    at Microsoft.PowerShell.Workflow.AstToWorkflowConverter.CompileWorkflows(ScriptBlockAst ast, PSModuleInfo definingModule, InitialSessionState 
                 initialSessionState, Nullable`1 sourceLanguageMode, ParseException& parsingErrors)
                    at System.Management.Automation.FunctionOps.DefineWorkflows(ExecutionContext context, ScriptBlockAst scriptBlockAst)
Exception      : System.Xaml.XamlObjectWriterException
InvocationInfo : {}
Line           : <#****************************DISCLAIMER****************************
                 
Position       : At C:\ACRGUI\Code\Add-CUAOnExistingResources.ps1:1 char:1
                 + <#****************************DISCLAIMER****************************
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot 
                 find the file specified.
StackTrace     :    at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 
                 methodInstCount, ObjectHandleOnStack type)
                    at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] 
                 methodInstantiationContext)
                    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
                    at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, 
                 RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList 
                 derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
                    at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, 
                 Int32 attributeCtorToken, Boolean mustBeInheritable)
                    at System.Reflection.CustomAttribute.IsDefined(RuntimeAssembly assembly, RuntimeType caType)
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicExpressionConverter.AssemblyCache.EnsureInitialized()
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicExpressionConverter.WrapCachedMapping(NamespaceDeclaration prefix, ReadOnlyXmlnsMapping& 
                 readOnlyMapping)
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicExpressionConverter.CollectXmlNamespacesAndAssemblies(ITypeDescriptorContext context)
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
                    at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value)
                    at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String 
                 targetName, IAddLineInfo lineInfo)
Exception      : System.IO.FileNotFoundException
InvocationInfo : {}
Line           : <#****************************DISCLAIMER****************************
                 
Position       : At C:\ACRGUI\Code\Add-CUAOnExistingResources.ps1:1 char:1
                 + <#****************************DISCLAIMER****************************
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'.
StackTrace     :    at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String 
                 targetName, IAddLineInfo lineInfo)
                    at System.Xaml.XamlObjectWriter.Logic_CreatePropertyValueFromValue(ObjectWriterContext ctx)
                    at System.Xaml.XamlObjectWriter.WriteEndMember()
                    at System.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
                    at System.Xaml.XamlServices.Load(XamlReader xamlReader)
                    at System.Activities.XamlIntegration.ActivityXamlServices.Load(XamlReader xamlReader, ActivityXamlServicesSettings settings)
                    at System.Activities.XamlIntegration.ActivityXamlServices.Load(XmlReader xmlReader, ActivityXamlServicesSettings settings)
                    at System.Activities.XamlIntegration.ActivityXamlServices.Load(TextReader textReader, ActivityXamlServicesSettings settings)
                    at Microsoft.PowerShell.Commands.ImportWorkflowCommand.ConvertXamlToActivity(String xaml)
                    at Microsoft.PowerShell.Workflow.DefinitionCache.CompileActivityAndSaveInCache(WorkflowJobDefinition definition, Activity activityTree, Dictionary`2 
                 requiredAssemblies, Boolean& windowsWorkflow, String rootWorkflowName)
                    at Microsoft.PowerShell.Commands.ImportWorkflowCommand.CreateFunctionFromXaml(String name, String xaml, Dictionary`2 requiredAssemblies, String[] 
                 dependentWorkflows, String dependentAssemblyPath, Dictionary`2 parameterValidation, String modulePath, Boolean scriptWorkflow, String workflowAttributes, String 
                 scriptContent, String fullScript, String rootWorkflowName, Nullable`1 sourceLanguageMode, ReadOnlyCollection`1 attributeAstCollection)
                    at Microsoft.PowerShell.Workflow.AstToWorkflowConverter.CompileSingleWorkflow(Scope scope, FunctionDefinitionAst func, Dictionary`2 scriptBlockTokenCache, 
                 PSModuleInfo definingModule, IEnumerable`1 assemblyList, Dictionary`2 activityMap, HashSet`1 processedActivityLibraries, PowerShell invoker, Nullable`1 
                 sourceLanguageMode, String rootWorkflowName)
                    at Microsoft.PowerShell.Workflow.AstToWorkflowConverter.CompileWorkflowsImpl(ScriptBlockAst ast, PSModuleInfo definingModule, InitialSessionState 
                 initialSessionState, Nullable`1 sourceLanguageMode, ParseException& parsingErrors, String rootWorkflowName)
                    at Microsoft.PowerShell.Workflow.AstToWorkflowConverter.CompileWorkflows(ScriptBlockAst ast, PSModuleInfo definingModule, InitialSessionState 
                 initialSessionState, Nullable`1 sourceLanguageMode, ParseException& parsingErrors)
                    at System.Management.Automation.FunctionOps.DefineWorkflows(ExecutionContext context, ScriptBlockAst scriptBlockAst)
Exception      : System.Xaml.XamlObjectWriterException
InvocationInfo : {}
Line           : <#****************************DISCLAIMER****************************
                 
Position       : At C:\ACRGUI\Code\Add-CUAOnExistingResources.ps1:1 char:1
                 + <#****************************DISCLAIMER****************************
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot 
                 find the file specified.
StackTrace     :    at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 
                 methodInstCount, ObjectHandleOnStack type)
                    at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] 
                 methodInstantiationContext)
                    at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
                    at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, 
                 RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList 
                 derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
                    at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, 
                 Int32 attributeCtorToken, Boolean mustBeInheritable)
                    at System.Reflection.CustomAttribute.IsDefined(RuntimeAssembly assembly, RuntimeType caType)
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicExpressionConverter.AssemblyCache.EnsureInitialized()
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicExpressionConverter.WrapCachedMapping(NamespaceDeclaration prefix, ReadOnlyXmlnsMapping& 
                 readOnlyMapping)
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicExpressionConverter.CollectXmlNamespacesAndAssemblies(ITypeDescriptorContext context)
                    at Microsoft.VisualBasic.Activities.XamlIntegration.VisualBasicSettingsConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
                    at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value)
                    at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String 
                 targetName, IAddLineInfo lineInfo)
Exception      : System.IO.FileNotFoundException
InvocationInfo : {}
Line           : <#****************************DISCLAIMER****************************
                 
Position       : At C:\ACRGUI\Code\Add-CUAOnExistingResources.ps1:1 char:1
                 + <#****************************DISCLAIMER****************************
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.6.1; CommandName: Resolve-AzError; PSVersion: 5.1.14393.4583; IsSuccess: True; Duration: 00:00:00.2331548
DEBUG: Finish sending metric.
DEBUG: 3:13:43 PM - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Could you provide more information about reproduce step?

**Comment by dingmeng-xue** [comment]
We are sharing an engineering build of Az.Accounts https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.6.1.nupkg.

Please download and install it following instruction.
* Download and save Az.Accounts.2.6.1.nupkg to local folder, for instance C:\Dev\testrepo
* Register local folder as local repository following instruction https://docs.microsoft.com/powershell/scripting/gallery/how-to/working-with-local-psrepositories?#registering-a-local-repository
```
Register-PSRepository -Name LocalPSRepo -SourceLocation ' C:\Dev\testrepo' -ScriptSourceLocation ' C:\Dev\testrepo' -InstallationPolicy Trusted
```
* Install Az.Accounts module from local repository.
```
* Install-Module Az.Accounts -Repository LocalPSRepo
```

Please let us know whether issue can be eliminated. Your feedback is very important to us.

**Comment by dingmeng-xue** [comment]
Please append `Get-Module` at the end of the script. We need to know which modules have been loaded into process.

**Comment by YogiPanchanathan** [comment]
Hi dingmeng-xue, as Mentioned in the chat. after using the engineering build, i am getting the below error.

Cannot find the 'Export-AzResourceGroup' command. If this command is defined as a workflow, ensure it is defined before the workflow that calls it. If it is a command intended to run directly within Windows 
PowerShell (or is not available on this system), place it in an InlineScript: 'InlineScript { Export-AzResourceGroup }'

Can u share the Respective Az.Resources Module version details

**Comment by YogiPanchanathan** [comment]
try
{
if(!(Get-InstalledModule Az -RequiredVersion 6.4.0 -ErrorAction SilentlyContinue))
    {
        Install-Module Az -RequiredVersion 6.4.0 -Scope CurrentUser -AllowClobber -Confirm:$false -ErrorAction Stop -SkipPublisherCheck -Force
    }
    else
    {
        
        Write-Output "Az module version 6.4.0 is already installed"
    }

    if (!(Get-InstalledModule -Name Az.Accounts -RequiredVersion 2.5.3 -ErrorAction SilentlyContinue )) 
    {
        Install-Module Az.Accounts -RequiredVersion 2.5.3 -AllowClobber -Scope CurrentUser -Confirm:$false -Force -ErrorAction Stop -SkipPublisherCheck
        Import-Module Az.Accounts -RequiredVersion 2.5.3 -Force -ErrorAction Stop        
    }
    else
    {
        Write-Output "Az.accounts version 2.5.3 is already installed"
        Import-Module Az.Accounts -RequiredVersion 2.5.3 -Force -ErrorAction Stop        
    }
}
catch
{
   throw "Error at Module Installation"
} 

after installing Module A 6.4.0 with Az.Accounts pointing to 2.53 this issue got resolved
