### ISSUE TITLE
Start-AzSynapseTrigger throws error but starts the trigger

### ISSUE THREAD

**Issue by sarajag** [Azure/azure-powershell#16368]
### Description

When using the {Start-AzSynapseTrigger} PS cmd in Azure Powershell 5.0 task in Azure DevOps pipeline, the cmd fails with the error 
"Request operation requires element of type Object byt target is String"
However, in the background it would have started the trigger.

### Issue script & Debug output

```PowerShell
Start-AzSynapseTrigger : The requested operation requires an element of type 'Object', but the target element has type
'String'.
At line:1 char:26
+ ... ach-Object {Start-AzSynapseTrigger -WorkspaceName $workspaceName -Nam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzSynapseTrigger], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Synapse.StartAzureSynapseTrigger
```

### Environment data

```PowerShell
**************************************
Name                           Value
----                           -----
PSVersion                      5.1.22000.65
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.65
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
0.11.0     Az.Synapse
```

### Error output

```PowerShell
Exception      : System.InvalidOperationException
InvocationInfo : {Start-AzSynapseTrigger}
Line           : $trigs | ForEach-Object {Start-AzSynapseTrigger -WorkspaceName $workspaceName -Name $_.name}
Position       : At line:1 char:26
                 + ... ach-Object {Start-AzSynapseTrigger -WorkspaceName $workspaceName -Nam ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 17

Message        : The requested operation requires an element of type 'Object', but the target element has type
                 'String'.
StackTrace     :    at System.Text.Json.JsonElement.EnumerateObject()
                    at Azure.Core.ArmOperationHelpers`1.IsTerminalState(String& state)
                    at Azure.Core.ArmOperationHelpers`1.<UpdateStatusAsync>d__25.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Azure.Core.ArmOperationHelpers`1.<UpdateStatusAsync>d__26.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Azure.Core.ArmOperationHelpers`1.<WaitForCompletionAsync>d__24.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at System.Threading.Tasks.ValueTask`1.get_Result()
                    at Microsoft.Azure.Commands.Synapse.Common.Utils.Poll[T](Operation`1 operation)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.StartTrigger(String
                 triggerName)
                    at Microsoft.Azure.Commands.Synapse.StartAzureSynapseTrigger.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. Could you try the latest version of Az.Synapse?

**Comment by PramodValavala-MSFT** [comment]
@sarajag The error you are seeing is from the `ForEach-Object` cmdlet since the [output of the `Start-AzSynapseTrigger`](https://docs.microsoft.com/en-us/powershell/module/az.synapse/start-azsynapsetrigger?view=azps-6.6.0#outputs) cmdlet is a Boolean value.

**Comment by KirstenBurnett-weir** [comment]
Hello. 
Having the same issue as @sarajag all of a sudden on disabling a trigger - was this resolved or is there a workaround?

**Comment by sarajag** [comment]
@dingmeng-xue - Thanks for the reply. Reverted back to version 0.7.0 and that worked well. 

@PramodValavala-MSFT  - Thanks for the reply. I do not think that is the issue, the ForEach takes object from the $trigs and applies it on the  Start-AzSynapseTrigger cmd. And this cmd had been working well for more than a month until yesterday. Figured out that it is the problem in the module version

@KirstenBurnett-weir  - I changed the module version (to 0.7.0) and it worked, But like suggested you can change to latest version. The problem resolved.

**Comment by PramodValavala-MSFT** [comment]
@sarajag You are right. Not sure what I was thinking earlier. I am going to reopen this and have the concerning team take a look.

**Comment by wonner** [comment]
Hi @sarajag @PramodValavala-MSFT @KirstenBurnett-weir , thanks for your feedback. It's a known issue which is caused by the backend return with an unexpected response. The service team has started to fix this bug. Here is the related IcM ticket: https://portal.microsofticm.com/imp/v3/incidents/details/271676115/home

**Comment by RobARichardson** [comment]
We've been seeing this same problem for several weeks. Glad to hear a fix is being worked on. Thank you!

**Comment by PramodValavala-MSFT** [comment]
@wonner Looks like this has been fixed on the service end. Thanks!

@sarajag @RobARichardson @KirstenBurnett-weir Could you confirm if you are still facing this issue?

**Comment by RobARichardson** [comment]
@PramodValavala-MSFT As of 2 minutes ago, I'm still seeing the issue

**Comment by KirstenBurnett-weir** [comment]
@PramodValavala-MSFT I have just tested and still have the same issue: 
![image](https://user-images.githubusercontent.com/72784477/142183207-43af706c-2c3d-49b4-86a9-3776df6e1d7d.png)

**Comment by KranthiPakala-MSFT** [comment]
@RobARichardson , @KirstenBurnett-weir  - Thanks for getting back and sorry for your inconvenience. We are looking into it and will get back to you as soon as we have an update. 

We appreciate your patience.

**Comment by wonner** [comment]
Hi all, before the bug is fixed, you could try to use below script as workaround.
```powershell
# Get token for data plane
$token = Get-AzAccessToken -ResourceUrl https://dev.azuresynapse.net
$authHeader = @{
    'Content-Type'  = 'application/octet-stream'
    'Authorization' = 'Bearer ' + $token.Token
}

$workspaceName = "<your-worksapce-name>"
$triggerName = "<your-trigger-name>"
 
# start trigger
Invoke-WebRequest -Method POST -Uri "https://${workspaceName}.dev.azuresynapse.net/triggers/${triggerName}/start?api-version=2020-12-01" -Headers $authHeader
```

**Comment by wonner** [comment]
Hi @KranthiPakala-MSFT , customers meet the same problem when running Stop-AzSynapseTrigger. https://github.com/Azure/azure-powershell/issues/16542
Please make sure the fix will cover it as well, thank you!

**Comment by gfree76** [comment]
@wonner, thanks! That workaround unblocked me. 

@KranthiPakala-MSFT, Is there an ETA for when this will be fixed?

**Comment by afogarty85** [comment]
> Hi all, before the bug is fixed, you could try to use below script as workaround.
> 
> ```powershell
> # Get token for data plane
> $token = Get-AzAccessToken -ResourceUrl https://dev.azuresynapse.net
> $authHeader = @{
>     'Content-Type'  = 'application/octet-stream'
>     'Authorization' = 'Bearer ' + $token.Token
> }
> 
> $workspaceName = "<your-worksapce-name>"
> $triggerName = "<your-trigger-name>"
>  
> # start trigger
> Invoke-WebRequest -Method POST -Uri "https://${workspaceName}.dev.azuresynapse.net/triggers/${triggerName}/start?api-version=2020-12-01" -Headers $authHeader
> ```


Thanks for the code! If I try this, I get this result, but my trigger will not turn from stopped to start. Results:

Command sent:

```
Invoke-WebRequest -Method POST -Uri "https://${workspaceName}.dev.azuresynapse.net/triggers/${triggerName}/start?api-version=2020-12-01" -Headers $authHeader
```

```
StatusCode        : 200
StatusDescription : OK
Content           :
RawContent        : HTTP/1.1 200 OK
                    Server: Kestrel
                    Server: Microsoft-HTTPAPI/2.0
                    Strict-Transport-Security: max-age=31536000; includeSubDomains
                    x-ms-correlation-request-id: f704566b-4deb-4cb2-b13f-5cafd88f758f
                    x-ms-requ…
Headers           : {[Server, System.String[]], [Strict-Transport-Security, System.String[]], [x-ms-correlation-request-id, System.String[]], [x-ms-request-id, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 0
RelationLink      : {}
```

**Comment by afogarty85** [comment]
Just wondering if anyone can verify whether or not the proposed fix actually works or if I am doing something wrong!

**Comment by gfree76** [comment]
It's working for me. We get the same sort of response but no issues with triggers not stopping/starting

**Comment by wonner** [comment]
Hi @afogarty85, could you please check if you under live mode?
![image](https://user-images.githubusercontent.com/22408725/145342380-52797223-b267-40d9-bd99-5244db3557f6.png)
It should work if return with 200.

**Comment by NowinskiK** [comment]
If you are struggling to apply the above code - you can use this module: [azure.synapse.tools](https://www.powershellgallery.com/packages/azure.synapse.tools/)  
Then start or stop all triggers:
```
$SynapseWorkspace = "SQLPlayerSynapseDemo"
Start-SynapseTriggers -SynapseWorkspace "$SynapseWorkspace"
```

**Comment by navba-MSFT** [comment]
@sarajag @gfree76 Apologies for the late reply. The Engineering team is aware of this issue and a workitem has been created to prioritize the fix. The only workaround as of now is to invoke this REST API directly using [this](https://github.com/Azure/azure-powershell/issues/16368#issuecomment-975110601) Powershell sample script provided by @wonner. We will update this thread once we have more details about the fix

**Comment by UJJAVALKR** [comment]
@navba-MSFT Workaround provided by  @wonner  is just to start or stop single trigger at a time, but as part of Synapse Workspace deployment we need to stop all the triggers and start is back once the deployment is succeeded. 
Let me know if your team has a workaround for this.

**Comment by navba-MSFT** [comment]
@wonner @zesluo Please let us know if you have an update on the permanent fix. Awaiting your reply.

**Comment by UJJAVALKR** [comment]
@wonner @navba-MSFT  This workaround is not working with the Storage events trigger.

**Comment by yanjungao718** [comment]
@UJJAVALKR  It would be helpful if you can provide detail messages about what scenario and what kind of error you met.

**Comment by ruudsuithoff** [comment]
Is this issue still being worked on? We encountered the same issues.

**Comment by mvdwielen** [comment]
@navba-MSFT any update on this issue, version 1.2.0 of Powershell module 1.2.0 still contains this issue

2022-04-14T07:30:05.3606515Z - Starting trigger: tr_daily
2022-04-14T07:30:09.5010876Z ##[error]The requested operation requires an element of type 'Object', but the target element has type 'String'.
2022-04-14T07:30:09.6701513Z ##[error]PowerShell exited with code '1'.

Powershell script:

$triggersADF = Get-AzSynapseTrigger -WorkspaceName $SynapseWorkspaceName

Write-Host "Start triggers if required..."
$counter = 0

$triggersADF | ForEach-Object {
    $triggerState = Out-String -InputObject $_.Properties.RuntimeState
    if($triggerState.Trim() -eq "Stopped") {
        Write-host "- Starting trigger: $($_.Name)"
        Start-AzSynapseTrigger `
            -WorkspaceName $_.WorkspaceName `
            -Name $_.Name `
            | Out-Null
        $counter += 1
    }
}

if($counter -eq 0){
    Write-Host "No triggers to start, starting triggers completed"
} else {
    Write-Host "Started $counter triggers, starting triggers completed"
}

**Comment by fvalencia12** [comment]
I just encountered the issue. It seems like it is taking a long time to fix this.
