### ISSUE TITLE
Error while fetching key credential information from certificate in Keyvault with Az module

### ISSUE THREAD

**Issue by AartiGorade** [Azure/azure-powershell#16405]
### Description

I am using below Powershell commands to retrieve key credentials from Certificate. I tried two solutions but none of them worked with Az module. It was working with AzureRM module earlier. 

### Issue script & Debug output

```PowerShell
Solution 1:
$kvSecret = Get-AzKeyVaultSecret -VaultName $vaultName -Name $certName
$secretVal = $kvSecret.SecretValue | ConvertFrom-SecureString
$kvSecretBytes = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($secretVal))
$jsonCert = ConvertFrom-Json($kvSecretBytes)
$certBytes = [System.Convert]::FromBase64String($jsonCert.data)
$certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$certCollection.Import($certBytes,$jsonCert.password,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)


Runtime outputs:

$kvSecret = Get-AzKeyVaultSecret -VaultName $vaultName -Name $certName

$secretVal = $kvSecret.SecretValue | ConvertFrom-SecureString     <<<<< Using this as $kvSecret.SecretValueText is returning null and seems no longer supported with Az module

$kvSecretBytes = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($secretVal))

$jsonCert = ConvertFrom-Json($kvSecretBytes)
**ConvertFrom-Json : Invalid JSON primitive: .**
At line:1 char:13
+ $jsonCert = ConvertFrom-Json($kvSecretBytes)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand


Solution 2:
$cert = Get-AzKeyVaultSecret -VaultName $vaultname -Name $certSecretName
$secretVal = $cert.SecretValue | ConvertFrom-SecureString
$certBytes = [System.Convert]::FromBase64String($cert.secretVal)
$certCollection = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection
$certCollection.Import($certBytes,$null,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)


Runtime Output:

PS C:\Users\aagorade>     $certCollection.Import($certBytes,$null,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
Exception calling "Import" with "3" argument(s): "Cannot find the requested object.      <<<<<<<<
"
At line:1 char:5
+     $certCollection.Import($certBytes,$null,[System.Security.Cryptogr ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : CryptographicException

PS C:\Users\aagorade>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     3.6.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount...}
```

### Error output

```PowerShell
Solution 1: 

  HistoryId: 52


Message        : Invalid JSON primitive: .
StackTrace     :    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
                    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
                    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer)
                    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
                    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.ArgumentException
InvocationInfo : {ConvertFrom-Json}
Line           : $jsonCert = ConvertFrom-Json($kvSecretBytes)
Position       : At line:1 char:13
                 + $jsonCert = ConvertFrom-Json($kvSecretBytes)
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 52


Solution 2:

   HistoryId: -1


Message        : Exception calling "Import" with "3" argument(s): "Cannot find the requested object.
                 "
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                    at CallSite.Target(Closure , CallSite , Object , Object , Object , X509KeyStorageFlags )
                    at System.Dynamic.UpdateDelegates.UpdateAndExecute4[T0,T1,T2,T3,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
                    at System.Management.Automation.Interpreter.DynamicInstruction`5.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.MethodInvocationException
InvocationInfo : {}
Line           :     $certCollection.Import($certBytes,$null,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
Position       : At line:1 char:5
                 +     $certCollection.Import($certBytes,$null,[System.Security.Cryptogr ...
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Cannot find the requested object.

StackTrace     :    at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.LoadStoreFromBlob(Byte[] rawData, String password, UInt32 dwFlags, Boolean persistKeyContainers)
                    at System.Security.Cryptography.X509Certificates.X509Certificate2Collection.Import(Byte[] rawData, String password, X509KeyStorageFlags keyStorageFlags)
                    at CallSite.Target(Closure , CallSite , Object , Object , Object , X509KeyStorageFlags )
Exception      : System.Security.Cryptography.CryptographicException
InvocationInfo : {}
Line           :     $certCollection.Import($certBytes,$null,[System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
Position       : At line:1 char:5
                 +     $certCollection.Import($certBytes,$null,[System.Security.Cryptogr ...
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by dingmeng-xue** [comment]
Please share how you created keyvaultsecret using Azure PowerShell. What's the parameter used?

**Comment by AartiGorade** [comment]
I resolved the issue with following change:
$cert = Get-AzKeyVaultSecret -VaultName $vaultname -Name $certSecretName **-AsPlainText**
$certBytes = [System.Convert]::FromBase64String($cert)
