### ISSUE TITLE
New-AzRoleAssignment HTTP 403 error when running as Service Principal

### ISSUE THREAD

**Issue by MPowellFDB** [Azure/azure-powershell#16414]
### Description

I'm trying to deploy a policy assignment via a GitHub Actions pipeline using a Service Principal. The Policy Assignment requires both Contributor and User Access Administrator permissions for remediation, so I'm trying to assign both roles within the same script. However, the deployment is receiving the following error on New-AzRoleAssignment:

Error:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
      "value": "Insufficient privileges to complete the operation."
    },
    "requestId": "5ef4ece3-49af-437f-89b5-943f6d5c3a98",
    "date": "2021-11-16T15:23:10"
  }
}

Full Az Powershell script I'm running:

```Powershell
$ErrorActionPreference = "Stop"
$subscriptionId = (Get-AzContext).Subscription.Id
$policyName = Split-Path -Path . -Leaf
$displayName = $PolicyName.Replace("_", " ")

if (!(Get-AzPolicyAssignment -Name $policyName -ErrorAction SilentlyContinue)) {
    Write-Host "Assignment does not exist, creating"
}
else {
    Write-Host "Assignment already exists, dropping and re-creating"
    Remove-AzPolicyAssignment -Name $policyName -Confirm:$false
} 

$policyDefinition = Get-AzPolicyDefinition -Name $policyName

New-AzPolicyAssignment `
    -Name $policyName `
    -DisplayName $displayName `
    -Description "Apply CanNotDelete resource lock if it is missing from specified resource groups" `
    -PolicyDefinition $policyDefinition `
    -AssignIdentity `
    -Location 'uksouth' `
    -Scope "/subscriptions/$($subscriptionId)"

$policyAssignment = Get-AzPolicyAssignment -Name $policyName -Scope "/subscriptions/$($subscriptionId)"
$objectID = ($policyAssignment.Identity.principalId).ToString()

Write-Host "Principal ID is: $objectID"

New-AzRoleAssignment `
    -ObjectId $objectID `
    -RoleDefinitionId '18d7d88d-d35e-4fb5-a5c3-7773c20a72d9' ` #User Access Administrator
    -Scope "/subscriptions/$($subscriptionId)" `
    -Debug 

New-AzRoleAssignment `
    -ObjectId $objectID `
    -RoleDefinitionId 'b24988ac-6180-42a0-ab88-20f7382dd24c' ` #Contributor
    -Scope "/subscriptions/$($subscriptionId)"
```

I have granted the GH Actions Service Principal User Access Administrator, Contributor, and Directory.Read.All Graph permissions with Admin Grant, but am still receiving this error. I even tried granting it Owner permissions but it still wouldn't work.

### Issue script & Debug output

```PowerShell
DEBUG: 15:23:09 - using account id '<redacted>'...
DEBUG: [Common.Authentication]: Authenticating using Account: '<redacted>', environment: 'AzureCloud', tenant: '<redacted>'
DEBUG: 15:23:09 - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'<redacted>', TenantId:'<redacted>', Scopes:'https://graph.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://graph.windows.net//.default ] ParentRequestId:
DEBUG: Request [50783042-4542-448b-bd25-d33380aae525] POST https://login.microsoftonline.com/<redacted>/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
Content-Type:application/x-www-form-urlencoded
x-ms-client-request-id:50783042-4542-448b-bd25-d33380aae525
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0 (.NET Framework 4.8.4300.0; Microsoft Windows 10.0.19042 )
client assembly: Azure.Identity
DEBUG: Response [50783042-4542-448b-bd25-d33380aae525] 200 OK (00.3s)
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
client-request-id:REDACTED
x-ms-request-id:0b648e93-62b8-4024-baa8-20f39464b400
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Cache-Control:no-store, no-cache
Content-Type:application/json; charset=utf-8
Expires:-1
P3P:REDACTED
Set-Cookie:REDACTED
Date:Tue, 16 Nov 2021 15:23:09 GMT
Content-Length:1353

DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://graph.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-11-16T16:23:08.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<redacted>', UserId: '<redacted>'
DEBUG: [Common.Authentication]: Authenticating using Account: '<redacted>', environment: 'AzureCloud', tenant: '<redacted>'
DEBUG: 15:23:09 - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'<redacted>', TenantId:'<redacted>', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: Request [09c55fe6-7404-4a6c-a648-11c9eff2c909] POST https://login.microsoftonline.com/<redacted>/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
Content-Type:application/x-www-form-urlencoded
x-ms-client-request-id:09c55fe6-7404-4a6c-a648-11c9eff2c909
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0 (.NET Framework 4.8.4300.0; Microsoft Windows 10.0.19042 )
client assembly: Azure.Identity
DEBUG: Response [09c55fe6-7404-4a6c-a648-11c9eff2c909] 200 OK (00.4s)
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
client-request-id:REDACTED
x-ms-request-id:642e7b32-1f39-4bf9-9620-74635b0a5f00
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Cache-Control:no-store, no-cache
Content-Type:application/json; charset=utf-8
Expires:-1
P3P:REDACTED
Set-Cookie:REDACTED
Date:Tue, 16 Nov 2021 15:23:09 GMT
Content-Length:1360

DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-11-16T16:23:09.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<redacted>', UserId: '<redacted>'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.windows.net/<redacted>/getObjectsByObjectIds?api-version=1.6

Headers:
x-ms-client-request-id        : 5ad20a41-9033-4c64-917f-4e5c533dc44f
accept-language               : en-US

Body:
{
  "objectIds": [
    "f7ed82d0-04da-47a2-8022-d4488e7da10e"
  ],
  "includeDirectoryObjectReferences": true
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Pragma                        : no-cache
ocp-aad-diagnostics-server-name: fo7U9TuOQ9EsDaHq5XA512kRHyEu+MIa2jcw+jaeG80=
request-id                    : 5ef4ece3-49af-437f-89b5-943f6d5c3a98
client-request-id             : 5ad20a41-9033-4c64-917f-4e5c533dc44f
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : nfKQPvbW7JN9ZuuftJ2rHWyn_3wKvIdiAdONbifLGpRGaitpXPF-aqLTvOkIbqRfq8r9mQaZHhcf8B7eE27DNlDA7X21xRQ3qEDp3tXzy07M0u3ZpGanp7tagLW6iKFY.2Qqj2SMl3OAGiCuvVf6hbplTYuz0SGHIgUW4N7bPUz8
Duration                      : 1921859
x-ms-resource-unit            : 3
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Cache-Control                 : no-cache
Date                          : Tue, 16 Nov 2021 15:23:10 GMT
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    },
    "requestId": "5ef4ece3-49af-437f-89b5-943f6d5c3a98",
    "date": "2021-11-16T15:23:10"
  }
}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.5.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     4.3.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential...}
```

### Error output

```PowerShell
HistoryId: 12


RequestId      :
Message        : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
ServerMessage  : :  (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {Forbidden}
RequestMessage : {POST https://graph.windows.net/07b8cd86-984b-4b35-a11c-0dd97d944789/getObjectsByObjectIds?api-version=1.6}
InvocationInfo : {New-AzRoleAssignment}
Line           : New-AzRoleAssignment `

Position       : At line:6 char:1
                 + New-AzRoleAssignment `
                 + ~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Graph.RBAC.ObjectsOperations.<GetObjectsByObjectIdsWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Graph.RBAC.ObjectsOperationsExtensions.<GetObjectsByObjectIdsAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Graph.RBAC.ObjectsOperationsExtensions.GetObjectsByObjectIds(IObjectsOperations operations, GetObjectsParameters parameters)
                    at Microsoft.Azure.Commands.ActiveDirectory.ActiveDirectoryClient.GetObjectsByObjectId(List`1 objectIds)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.CreateRoleAssignment(FilterRoleAssignmentsOptions parameters, Guid roleAssignmentId)
                    at Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 12
```

**Comment by dingmeng-xue** [comment]
Hi @MPowellFDB , you could check couple things in your environment.
1. Could you reproduce the issue in your local environment instead of GH Action using the same service principal and secret?
2. You need to grant API permission to your SP to allow calling AAD Graph API? Permission type should be delegated permission. You can reference this one https://github.com/Azure/azure-powershell/issues/16067

**Comment by MPowellFDB** [comment]
Apologies, I thought I'd closed this issue as I managed to fix it.

I did indeed follow the workaround mentioned in #16067, but I had to change the AAD Graph permission from Delegated to Application after running the workaround
