### ISSUE TITLE
[Az.DeviceProvisioningServices] Get-AzIoTDeviceProvisioningServiceCertificate throws error

### ISSUE THREAD

**Issue by vivere-dally** [Azure/azure-powershell#16413]
### Description

I'm trying to list all my certificates from the DCP resource but running `Get-AzIoTDeviceProvisioningServiceCertificate` raises an error.

As you can see in the `Issue script & Debug output` section, the certificates are in fact fetched correctly, but after that, some processing is executing which causes a conversion error `'Microsoft.Rest.Serialization.DateTimeRfc1123JsonConverter' to type 'Newtonsoft.Json.JsonConverter'.`

### Issue script & Debug output

```PowerShell
PS> Get-AzIoTDeviceProvisioningServiceCertificate -DpsObject $dps

DEBUG: 12:14:25 PM - GetAzureRmIoTDeviceProvisioningServiceCertificate begin processing with ParameterSet
'InputObjectSet'.
DEBUG: 12:14:25 PM - using account id '<me>'...
DEBUG: [Common.Authentication]: Authenticating using Account: '<me>', environment: 'AzureCloud', tenant:
 '<tenantId>'
DEBUG: 12:14:25 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync -
TenantId:'<tenantId>', Scopes:'https://management.core.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId:'<me>'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] Azure region was not
configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25] Found 1 cache accounts and 0
broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] MSAL MSAL.Desktop with
assembly version '4.30.1.0'. CorrelationId(faae0b5b-776b-4a79-9666-50e0ab89b529)
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] === AcquireTokenSilent
Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - faae0b5b-776b-4a79-9666-50e0ab89b529
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] === Token Acquisition
(SilentRequest) started:

 Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] Azure region was not
configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] Access token is not expired.
Returning the found cache entry. [Current time (11/16/2021 10:14:25) - Expiration Time (11/16/2021 11:25:03 +00:00) -
Extended Expiration Time (11/16/2021 11:25:03 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] Returning access token found
in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] Fetched access token from host
 login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Enterprise [11/16/2021 10:14:25 - ] === Token Acquisition finished
 successfully. An access token was returned with Expiration Time: 11/16/2021 11:25:03 +00:00 and Scopes
https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:  ExpiresOn: 2021-11-16T11:25:03.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<tenantId>',
UserId: '<me>'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<subscriptionId>/resourceGroups/<rgName>/providers/
Microsoft.Devices/provisioningServices/<dpsName>/certificates?api-version=2017-11-15

Headers:
x-ms-client-request-id        : 9f79387f-bf2d-48ed-9f46-7b31d852e715
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-request-id               : 134eee32-ab65-4e99-b7b7-cac1e0b1d5f0
x-ms-correlation-request-id   : 134eee32-ab65-4e99-b7b7-cac1e0b1d5f0
x-ms-routing-request-id       : GERMANYWESTCENTRAL:20211116T101426Z:134eee32-ab65-4e99-b7b7-cac1e0b1d5f0
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 16 Nov 2021 10:14:25 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "value": [
      Valid Certificate Results
  ]
}

Get-AzIoTDeviceProvisioningServiceCertificate : Unable to cast object of type
'Microsoft.Rest.Serialization.DateTimeRfc1123JsonConverter' to type 'Newtonsoft.Json.JsonConverter'.
At line:1 char:1
+ Get-AzIoTDeviceProvisioningServiceCertificate -DpsObject $dps
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzIoTDevice...viceCertificate], InvalidCastException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.DeviceProvisioningServices.GetAzureRmIoTDeviceProvis
   ioningServiceCertificate

DEBUG: AzureQoSEvent: Module: Az.DeviceProvisioningServices:0.10.0; CommandName:
Get-AzIoTDeviceProvisioningServiceCertificate; PSVersion: 5.1.18362.1801; IsSuccess: False; Duration: 00:00:00.6161479;
 Exception: Unable to cast object of type 'Microsoft.Rest.Serialization.DateTimeRfc1123JsonConverter' to type
'Newtonsoft.Json.JsonConverter'.;
DEBUG: Finish sending metric.
DEBUG: 12:14:27 PM - GetAzureRmIoTDeviceProvisioningServiceCertificate end processing.
```

### Environment data

```PowerShell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.1801
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1801
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
Script     0.10.0     Az.DeviceProvisioningServices       {Add-AzIoTDeviceProvisioningServiceAccessPolicy, Add-AzIoT...
```

### Error output

```PowerShell
PS> Resolve-AzError

DEBUG: 12:23:06 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 12:23:06 PM - using account id 'S.Buciu@stratec.com'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use
`Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.


   HistoryId: 9


Message        : Unable to cast object of type 'Microsoft.Rest.Serialization.DateTimeRfc1123JsonConverter' to type
                 'Newtonsoft.Json.JsonConverter'.
StackTrace     :    at Newtonsoft.Json.Serialization.JsonTypeReflector.GetJsonConverter(Object attributeProvider)
                    at
                 Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes(JsonProperty
                 property, Object attributeProvider, String name, Type declaringType, MemberSerialization
                 memberSerialization, Boolean& allowNonPublicAccess)
                    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty(MemberInfo member,
                 MemberSerialization memberSerialization)
                    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type,
                 MemberSerialization memberSerialization)
                    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
                    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
                    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
                    at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject,
                 JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type
                 objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract,
                 JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader
                 reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader
                 reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type
                 objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader
                 reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type
                 objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings
                 settings)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
                    at Microsoft.Azure.Commands.Management.DeviceProvisioningServices.GetAzureRmIoTDeviceProvisioningSe
                 rviceCertificate.GetIotDpsCertificates()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.InvalidCastException
InvocationInfo : {Get-AzIoTDeviceProvisioningServiceCertificate}
Line           : Get-AzIoTDeviceProvisioningServiceCertificate -DpsObject $dps
Position       : At line:1 char:1
                 + Get-AzIoTDeviceProvisioningServiceCertificate -DpsObject $dps
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9
```

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@vivere-dally Can you please share what value you are passing against `-DpsObject $dps` ?

**Comment by asergaz** [comment]
Hello @vivere-dally I have the same error when using Powershell 5.1. Though I was able to run the command when using Powershell Version 7.2. Can you install this version and give it a try?

https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#msi

Thanks!

**Comment by vivere-dally** [comment]
Hello @asergaz, I tried with PS Version `7.0.3` and it works as expected. I would presume that it works on every 7+ version?

**Comment by asergaz** [comment]
@vivere-daily I just tested on 7.2. I also tested in Azure Portal that is version 7.2. Nevertheless the documentation should mention what minimum version is needed. And currently is saying 5.1 :(. So I consider this a doc or product bug.

https://www.powershellgallery.com/packages/Az.DeviceProvisioningServices/0.10.0

![image](https://user-images.githubusercontent.com/22173500/143438768-e6e1ad3c-b993-42e7-a056-ed3375593fc7.png)

**Comment by SaurabhSharma-MSFT** [comment]
@vivere-dally We are proceeding with the closure of this issue as we are working internally to get the documentation updated with the correct PowerShell version.  Please feel free to open a new issue if you have any other questions.
@asergaz Appreciate your help on this issue.

Thanks
Saurabh
