### ISSUE TITLE
Problems when creating linked service via Az.DataFactory

### ISSUE THREAD

**Issue by Yuiheart** [Azure/azure-powershell#16485]
### Description

I was trying to create linked service via PowerShell. I selected the Service Principal as authentication method as follows.
![image](https://user-images.githubusercontent.com/37691347/143220766-f93590d2-288d-42b0-b94e-ec6522bf16b2.png)

However, in the json file of linked service which I copied from an existing linked service, there is no support for Service Principal Key field and I got the following error.
![image](https://user-images.githubusercontent.com/37691347/143220819-b14e5450-2209-4ea2-96cf-da384f676805.png)

Could you please help me with how to create a linked service via PowerShell using Service Principal?

### Issue script & Debug output

```PowerShell
Body:
{
  "id": "",
  "name": "",
  "type": "Microsoft.DataFactory/factories/linkedservices",
  "properties": {
    "annotations": [],
    "type": "AzureDataLakeStore",
    "typeProperties": {
      "dataLakeStoreUri": "",
      "servicePrincipalId": "",
      "tenant": "",
      "subscriptionId": "",
      "resourceGroupName": "",
      "encryptedCredential": ""
    },
    "connectVia": {
      "referenceName": "ADLSintegrationRuntime",
      "type": "IntegrationRuntimeReference"
    }
  },
  "etag": ""
}

Set-AzDataFactoryV2LinkedService: Json is not valid. Details: 'Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path 'typeProperties.servicePrincipalKey', line 13, position 71.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreateOrUpdateLinkedService(String resourceGroupName, String dataFactoryName, String linkedServiceName, String rawJsonContent)'
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
6.4.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resourc…
2.5.3                Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential manag…
1.1.1                Az.Advisor                          PSGallery            Microsoft Azure PowerShell - Azure Advisor Cmdlets for…
2.4.0                Az.Aks                              PSGallery            Microsoft Azure PowerShell - Azure managed Kubernetes …
1.1.4                Az.AnalysisServices                 PSGallery            Microsoft Azure PowerShell - Analysis Services cmdlets…
2.3.0                Az.ApiManagement                    PSGallery            Microsoft Azure PowerShell - Api Management service cm…
1.0.0                Az.AppConfiguration                 PSGallery            Microsoft Azure PowerShell: AppConfiguration cmdlets
1.2.0                Az.ApplicationInsights              PSGallery            Microsoft Azure PowerShell - Application Insights mana…
1.7.1                Az.Automation                       PSGallery            Microsoft Azure PowerShell - Automation service cmdlet…
3.1.0                Az.Batch                            PSGallery            Microsoft Azure PowerShell - Batch service cmdlets for…
2.0.0                Az.Billing                          PSGallery            Microsoft Azure PowerShell - Billing service cmdlets f…
1.8.0                Az.Cdn                              PSGallery            Microsoft Azure PowerShell - CDN service cmdlets for A…
1.9.0                Az.CognitiveServices                PSGallery            Microsoft Azure PowerShell - Cognitive Services manage…
4.17.0               Az.Compute                          PSGallery            Microsoft Azure PowerShell - Compute service cmdlets f…
2.1.0                Az.ContainerInstance                PSGallery            Microsoft Azure PowerShell: ContainerInstance cmdlets
2.2.3                Az.ContainerRegistry                PSGallery            Microsoft Azure PowerShell - Container Registry servic…
1.3.1                Az.CosmosDB                         PSGallery            Microsoft Azure PowerShell - CosmosDB service cmdlets …
1.1.0                Az.DataBoxEdge                      PSGallery            Microsoft Azure PowerShell - DataBoxEdge service cmdle…
1.1.0                Az.Databricks                       PSGallery            Microsoft Azure PowerShell: Databricks cmdlets
1.14.0               Az.DataFactory                      PSGallery            Microsoft Azure PowerShell - Data Factory service cmdl…
1.0.2                Az.DataLakeAnalytics                PSGallery            Microsoft Azure PowerShell - Data Lake Analytics in Wi…
1.3.0                Az.DataLakeStore                    PSGallery            Microsoft Azure PowerShell - Azure Data Lake Store cmd…
1.0.0                Az.DataShare                        PSGallery            Microsoft Azure PowerShell - DataShare service cmdlets…
1.1.0                Az.DeploymentManager                PSGallery            PowerShell .Net Core Microsoft Azure PowerShell - Depl…
3.0.0                Az.DesktopVirtualization            PSGallery            Microsoft Azure PowerShell: DesktopVirtualization cmdl…
1.0.2                Az.DevTestLabs                      PSGallery            Microsoft Azure PowerShell - DevTest Labs service cmdl…
1.1.2                Az.Dns                              PSGallery            Microsoft Azure PowerShell - DNS service cmdlets for A…
1.3.0                Az.EventGrid                        PSGallery            Microsoft Azure PowerShell - Event Grid service cmdlet…
1.8.0                Az.EventHub                         PSGallery            Microsoft Azure PowerShell - Event Hubs service cmdlet…
1.8.0                Az.FrontDoor                        PSGallery            Microsoft Azure PowerShell - Front Door service cmdlet…
3.1.0                Az.Functions                        PSGallery            Microsoft Azure PowerShell - Azure Functions service c…
4.3.0                Az.HDInsight                        PSGallery            Microsoft Azure PowerShell - HDInsight service cmdlets…
1.3.1                Az.HealthcareApis                   PSGallery            Microsoft Azure PowerShell - HealthcareApis management…
2.7.3                Az.IotHub                           PSGallery            Microsoft Azure PowerShell - IoT Hub service cmdlets f…
3.5.0                Az.KeyVault                         PSGallery            Microsoft Azure PowerShell - Key Vault service cmdlets…
2.0.0                Az.Kusto                            PSGallery            Microsoft Azure PowerShell: Kusto cmdlets
1.5.0                Az.LogicApp                         PSGallery            Microsoft Azure PowerShell - Logic Apps cmdlets for Az…
1.1.3                Az.MachineLearning                  PSGallery            Microsoft Azure PowerShell - Machine Learning Web Serv…
1.1.1                Az.Maintenance                      PSGallery            Microsoft Azure PowerShell - Maintenance cmdlets for A…
2.0.0                Az.ManagedServices                  PSGallery            Microsoft Azure PowerShell - ManagedServices cmdlets f…
1.0.2                Az.MarketplaceOrdering              PSGallery            Microsoft Azure PowerShell - Marketplace Ordering agre…
1.1.1                Az.Media                            PSGallery            Microsoft Azure PowerShell - Media service cmdlets for…
1.1.1                Az.Migrate                          PSGallery            Microsoft Azure PowerShell: Migrate cmdlets
2.7.0                Az.Monitor                          PSGallery            Microsoft Azure PowerShell - Monitor service cmdlets f…
4.11.0               Az.Network                          PSGallery            Microsoft Azure PowerShell - Networking service cmdlet…
1.1.1                Az.NotificationHubs                 PSGallery            Microsoft Azure PowerShell - Notification Hubs cmdlets…
2.3.0                Az.OperationalInsights              PSGallery            Microsoft Azure PowerShell - Operational Insights serv…
1.4.1                Az.PolicyInsights                   PSGallery            Microsoft Azure PowerShell - Azure Policy Insights cmd…
1.1.2                Az.PowerBIEmbedded                  PSGallery            Microsoft Azure PowerShell - Power BI Embedded service…
1.0.3                Az.PrivateDns                       PSGallery            Microsoft Azure PowerShell - Private DNS service cmdle…
4.6.0                Az.RecoveryServices                 PSGallery            Microsoft Azure PowerShell - Recovery Services cmdlets…
1.5.0                Az.RedisCache                       PSGallery            Microsoft Azure PowerShell - Redis Cache service cmdle…
1.0.0                Az.RedisEnterpriseCache             PSGallery            Microsoft Azure PowerShell: RedisEnterpriseCache cmdle…
1.0.3                Az.Relay                            PSGallery            Microsoft Azure PowerShell - Relay service cmdlets for…
1.0.0                Az.ResourceMover                    PSGallery            Microsoft Azure PowerShell: ResourceMover cmdlets
4.3.1                Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resource Manager an…
1.0.0                Az.Security                         PSGallery            Microsoft Azure PowerShell - Azure Security Center cmd…
1.1.0                Az.SecurityInsights                 PSGallery            Microsoft Azure PowerShell - Azure Sentinel cmdlets in…
1.5.0                Az.ServiceBus                       PSGallery            Microsoft Azure PowerShell - Service Bus service cmdle…
3.0.1                Az.ServiceFabric                    PSGallery            Microsoft Azure PowerShell - Service Fabric cmdlets fo…
1.3.0                Az.SignalR                          PSGallery            Microsoft Azure PowerShell - Azure SignalR service com…
3.5.0                Az.Sql                              PSGallery            Microsoft Azure PowerShell - SQL service cmdlets for A…
1.1.0                Az.SqlVirtualMachine                PSGallery            Microsoft Azure PowerShell - SqlVirtualMachine service…
3.11.0               Az.Storage                          PSGallery            Microsoft Azure PowerShell - Storage service data plan…
1.6.0                Az.StorageSync                      PSGallery            Microsoft Azure PowerShell - Storage Sync cmdlets in W…
2.0.0                Az.StreamAnalytics                  PSGallery            Microsoft Azure PowerShell: StreamAnalytics cmdlets
1.0.0                Az.Support                          PSGallery            Microsoft Azure PowerShell - Azure Support cmdlets for…
1.0.4                Az.TrafficManager                   PSGallery            Microsoft Azure PowerShell - Traffic Manager service c…
2.8.2                Az.Websites                         PSGallery            Microsoft Azure PowerShell - App Service (Web Apps) s
```

### Error output

```PowerShell
Position       : At C:\ADF_automation\ADF_automation\BuildCAInfoPipelines.ps1:317 char:24
                 + … ($null -eq (Get-AzDataFactoryV2LinkedService -ResourceGroupName $Prod …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :
HistoryId      : 26

Message        : Json is not valid. Details: 'Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current
                 JsonReader item is not an object: String. Path 'typeProperties.servicePrincipalKey', line 13, position 71.
                    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
                    at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type
                 objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,
                 JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType,
                 Boolean checkAdditionalContent)
                    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
                    at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type
                 objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter,
                 JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property,
                 JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty,
                 JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader
                 reader, JsonObjectContract contract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType,
                 JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember,
                 Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type
                 objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty
                 containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType,
                 Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings
                 settings)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreateOrUpdateLinkedService(String
                 resourceGroupName, String dataFactoryName, String linkedServiceName, String rawJsonContent)'
StackTrace     :    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreateOrUpdateLinkedService(String
                 resourceGroupName, String dataFactoryName, String linkedServiceName, String rawJsonContent)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.<>c__DisplayClass66_0.<CreatePSLinkedService>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String
                 continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.CreatePSLinkedService(CreatePSAdfEntityParameters
                 parameters)
                    at Microsoft.Azure.Commands.DataFactoryV2.SetAzureDataFactoryLinkedServiceCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Set-AzDataFactoryV2LinkedService}
Line           :             Set-AzDataFactoryV2LinkedService -Name $ProdConfig.ADLALinkedServiceforCAInfo -ResourceGroupName
                 $ProdConfig.ResourceGroupName -DataFactoryName $ProdConfig.DataFactoryNameforCAInfo -DefinitionFile
                 "$($ProdConfig.PipelineSettingRootforCAInfo)\ADLALinkedService.json"
```

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@Yuiheart You need to pass ServicePrincipalKey like below to create the required linked service - 
`"servicePrincipalKey": {"type": "SecureString", "value": "<client secret>"}`
Final Json will look like below:
![image](https://user-images.githubusercontent.com/38112130/143364674-b9932086-bb9c-4667-bcda-0f42d4ab46c8.png)
I have tested this and it worked fine in my environment.
Please refer to the [AzureDataLakeStoreLinkedService](https://docs.microsoft.com/en-us/rest/api/datafactory/linked-services/create-or-update#azuredatalakestorelinkedservice) for details.

**Comment by Yuiheart** [comment]
Hi @SaurabhSharma-MSFT 
Thanks! It works for me too.
