### ISSUE TITLE
Az powershell: Stop-AzSynapseTrigger not working

### ISSUE THREAD

**Issue by afogarty85** [Azure/azure-powershell#16542]
### Description

According to the docs: https://docs.microsoft.com/en-us/powershell/module/az.synapse/stop-azsynapsetrigger?view=azps-6.6.0

```
Stop-AzSynapseTrigger
    -WorkspaceName <String>
    -Name <String>
```

Returns this error:

```
Stop-AzSynapseTrigger: The requested operation requires an element of type 'Object', but the target element has type 'String'.

```

### Issue script & Debug output

```PowerShell
DEBUG: 3:08:56 PM - StopAzureSynapseTrigger begin processing with ParameterSet 'StopByName'.
DEBUG: 3:08:56 PM - using account id 'MSI@50342'...
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [5c42205b-9637-439f-b89c-6944c834df9c] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:5c42205b-9637-439f-b89c-6944c834df9c
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [5c42205b-9637-439f-b89c-6944c834df9c] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [66ebed3e-37c1-44f4-9930-68dd32e53a44] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:66ebed3e-37c1-44f4-9930-68dd32e53a44
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [66ebed3e-37c1-44f4-9930-68dd32e53a44] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [0b3acb6f-88f3-49bd-bab3-e471e2248fab] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:0b3acb6f-88f3-49bd-bab3-e471e2248fab
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [0b3acb6f-88f3-49bd-bab3-e471e2248fab] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [0ed17cef-4c2c-46b9-8796-4c3918b1b809] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:0ed17cef-4c2c-46b9-8796-4c3918b1b809
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [0ed17cef-4c2c-46b9-8796-4c3918b1b809] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [1b61481a-7969-4963-a074-1d99c64893aa] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:1b61481a-7969-4963-a074-1d99c64893aa
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [1b61481a-7969-4963-a074-1d99c64893aa] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [16616c22-9b7a-452c-9256-3e8cd7672c15] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:16616c22-9b7a-452c-9256-3e8cd7672c15
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [16616c22-9b7a-452c-9256-3e8cd7672c15] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [39511a7d-73ce-4d57-929f-a547204cf079] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:39511a7d-73ce-4d57-929f-a547204cf079
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [39511a7d-73ce-4d57-929f-a547204cf079] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [973be4ed-3783-459f-b699-46fd64ebc338] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:973be4ed-3783-459f-b699-46fd64ebc338
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [973be4ed-3783-459f-b699-46fd64ebc338] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [b06631d8-21fb-4482-939a-c7bc5dcb3410] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:b06631d8-21fb-4482-939a-c7bc5dcb3410
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [b06631d8-21fb-4482-939a-c7bc5dcb3410] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [d6b05332-6a0d-41dc-b325-233a0e02b4ff] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:d6b05332-6a0d-41dc-b325-233a0e02b4ff
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [d6b05332-6a0d-41dc-b325-233a0e02b4ff] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [f61741b3-aca9-4f5c-b076-9e86d88507d4] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:f61741b3-aca9-4f5c-b076-9e86d88507d4
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [f61741b3-aca9-4f5c-b076-9e86d88507d4] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: 3:08:56 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'72f988bf-86f1-41af-91ab-2d7cd011db47', Scopes:'https://dev.azuresynapse.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:
DEBUG: Request [b1721388-7e6d-45a9-9105-5f6ad30b32a2] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:b1721388-7e6d-45a9-9105-5f6ad30b32a2
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [b1721388-7e6d-45a9-9105-5f6ad30b32a2] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"891-lnAfO0MnDGlhdbpEZLNiDh3Jjzk"
Date:Tue, 30 Nov 2021 15:08:56 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2193

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://dev.azuresynapse.net ] ParentRequestId:  ExpiresOn: 2021-11-30T16:08:49.0000000+00:00
DEBUG: Request [762e2d74-55ac-4d06-8766-282f9b22a3ed] POST https://myurl.dev.azuresynapse.net/triggers/daily_dim_trigger/stop?api-version=REDACTED
Accept:application/json
x-ms-client-request-id:762e2d74-55ac-4d06-8766-282f9b22a3ed
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Analytics.Synapse.Artifacts/1.0.0-preview.11,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Authorization:REDACTED
client assembly: Azure.Analytics.Synapse.Artifacts
DEBUG: Response [762e2d74-55ac-4d06-8766-282f9b22a3ed] 200 OK (01.2s)
Server:Kestrel,Microsoft-HTTPAPI/2.0
Strict-Transport-Security:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-request-id:016742d8-9b90-41bf-a8bd-4912a4d5492a
x-ms-client-request-id:762e2d74-55ac-4d06-8766-282f9b22a3ed
Date:Tue, 30 Nov 2021 15:08:56 GMT
Content-Length:2
Content-Type:application/json; charset=utf-8

Stop-AzSynapseTrigger: The requested operation requires an element of type 'Object', but the target element has type 'String'.
DEBUG: AzureQoSEvent: Module: Az.Synapse:0.18.0; CommandName: Stop-AzSynapseTrigger; PSVersion: 7.2.0; IsSuccess: False; Duration: 00:00:01.2890663; Exception: The requested operation requires an element of type 'Object', but the target element has type 'String'.;
DEBUG: Finish sending metric.
DEBUG: 3:08:58 PM - StopAzureSynapseTrigger end processing.
```
```


### Environment data

```PowerShell
$PSVersionTable.PSVersion
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      0

```
```


### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.6.2                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.18.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     4.12.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzApplicationGatewayCustomError…}
Script     4.4.1                 Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential…}
Script     3.12.0                Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember…}
Script     0.9.3                 AzurePSDrive
```
```


### Error output

```PowerShell
essage        : The requested operation requires an element of type 'Object', but the target element has type 'String'.
StackTrace     :    at System.Text.Json.JsonElement.EnumerateObject()
                    at Azure.Core.OperationInternals.IsTerminalState(String& state)
                    at Azure.Core.OperationInternals.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
                    at Azure.Core.OperationInternals.UpdateStatusAsync(CancellationToken cancellationToken)
                    at Azure.Core.OperationInternals.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Synapse.Common.Utils.Poll(Operation operation)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.StopTrigger(String triggerName)
                    at Microsoft.Azure.Commands.Synapse.StopAzureSynapseTrigger.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.InvalidOperationException
InvocationInfo : {Stop-AzSynapseTrigger}
Line           : Stop-AzSynapseTrigger
Position       : At line:1 char:1
                 + Stop-AzSynapseTrigger
                 + ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3
```
```

**Comment by dingmeng-xue** [comment]
Thank you for your reporting. Tagging and routing to the team member best able to assist.

**Comment by PramodValavala-MSFT** [comment]
@afogarty85 While a different cmdlet, the same error is seen for the `Start-AzSynapseTrigger` cmdlet as discussed in #16368. The [workaround](https://github.com/Azure/azure-powershell/issues/16368#issuecomment-975110601) should work I believe since the error is from deserializing the response.

@wonner Could you confirm if the service side fix would cover this as well?

**Comment by wonner** [comment]
Thank you @PramodValavala-MSFT , you are right.
@afogarty85 Sorry for your inconvenience. Could you please try to run the above script as a temporary workaround?

I will close this issue and track it in https://github.com/Azure/azure-powershell/issues/16368, since it's the same problem, thank you.

**Comment by jaknigh** [comment]
@wonner I am also seeing this issue on Get-AzSynapsePipeline

![image](https://user-images.githubusercontent.com/97691779/149373986-0bf1dcc3-bf89-4497-9949-a202ee963f9d.png)
