### ISSUE TITLE
Set-AzVMExtension, parameter "Location" returns error when empty/not used

### ISSUE THREAD

**Issue by yordanbechev** [Azure/azure-powershell#16566]
### Description

Set-AzVMExtension has parameter location which is not mandatory (similar to the alternative in Bash). This is also as per the documentation and Get-Command ouput:

PS /home/yordan> ((Get-Command -Name Set-AzVMExtension).ParameterSets).Parameters | Where-Object -FilterScript {$_.Name -like "Location"}

Name                            : Location
ParameterType                   : System.String
**IsMandatory                     : False**
IsDynamic                       : False
Position                        : -2147483648
ValueFromPipeline               : False
ValueFromPipelineByPropertyName : True
ValueFromRemainingArguments     : False
HelpMessage                     : The location.
Aliases                         : {}
Attributes                      : {True, Microsoft.Azure.Commands.ResourceManager.Common.ArgumentCompleters.LocationCompleterAttribute, System.Management.Automation.ValidateNotNullOrEmptyAttribute} 

when the Location parameter is empty error is returned:
**Set-AzVMExtension: 'Location' cannot be null.**

This is issue does not exists in Bash. Location is not mandatory there and does not return error.

### Issue script & Debug output

```PowerShell
PS /home/yordan> Set-AzVMExtension -Name AMAWindows -ExtensionType AzureMonitorWindowsAgent -Publisher Microsoft.Azure.Monitor -ResourceGroupName RG01 -VMName Server1 -TypeHandlerVersion 1.0
DEBUG: 5:20:58 PM - SetAzureVMExtensionCommand begin processing with ParameterSet 'Settings'.
DEBUG: 5:20:58 PM - using account id '********'...
DEBUG: [Common.Authentication]: Authenticating using Account: '*******', environment: 'AzureCloud', tenant: '**********'
DEBUG: 5:20:58 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'********', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:
DEBUG: Request [********] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:*************
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 6.0.0-rtm.21522.10; Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [***********] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"********************"
Date:Thu, 02 Dec 2021 17:20:58 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2238

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  ExpiresOn: 2021-12-02T17:45:08.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '******************', UserId: '*********'
Set-AzVMExtension: 'Location' cannot be null.
DEBUG: AzureQoSEvent: Module: Az.Compute:4.18.0; CommandName: Set-AzVMExtension; PSVersion: 7.2.0; IsSuccess: False;Duration: 00:00:00.0379731; Exception: 'Location' cannot be null.;
DEBUG: Finish sending metric.
DEBUG: 5:20:58 PM - SetAzureVMExtensionCommand end processing.
PS /home/yordan>
```

### Environment data

```PowerShell
PS /home/yordan> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS /home/yordan> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.6.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzD…
Script     4.18.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAddit…
Script     4.12.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertifi…
Script     4.4.1                 Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, …
Script     3.12.0                Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStor…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDevic…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
PS /home/yordan> Resolve-AzError
DEBUG: 5:24:10 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 5:24:10 PM - using account id '***********'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use`Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 3

Message        : 'Location' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.Models.Resource.Validate()
                    at Microsoft.Azure.Management.Compute.Models.VirtualMachineExtension.Validate()
                    at Microsoft.Azure.Management.Compute.VirtualMachineExtensionsOperations.BeginCreateOrUpdateWith
                 HttpMessagesAsync(String resourceGroupName, String vmName, String vmExtensionName,
                 VirtualMachineExtension extensionParameters, Dictionary`2 customHeaders, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Management.Compute.VirtualMachineExtensionsOperations.CreateOrUpdateWithHttpM
                 essagesAsync(String resourceGroupName, String vmName, String vmExtensionName,
                 VirtualMachineExtension extensionParameters, Dictionary`2 customHeaders, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand.<ExecuteCmdlet>b__30_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronou
                 slyOrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Set-AzVMExtension}
Line           : Set-AzVMExtension -Name AMAWindows -ExtensionType AzureMonitorWindowsAgent -Publisher
                 Microsoft.Azure.Monitor -ResourceGroupName RG01 -VMName Server1 -TypeHandlerVersion 1.0
Position       : At line:1 char:1
                 + Set-AzVMExtension -Name AMAWindows -ExtensionType AzureMonitorWindows …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3


   HistoryId: 1

Message        : 'Location' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Compute.Models.Resource.Validate()
                    at Microsoft.Azure.Management.Compute.Models.VirtualMachineExtension.Validate()
                    at Microsoft.Azure.Management.Compute.VirtualMachineExtensionsOperations.BeginCreateOrUpdateWith
                 HttpMessagesAsync(String resourceGroupName, String vmName, String vmExtensionName,
                 VirtualMachineExtension extensionParameters, Dictionary`2 customHeaders, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Management.Compute.VirtualMachineExtensionsOperations.CreateOrUpdateWithHttpM
                 essagesAsync(String resourceGroupName, String vmName, String vmExtensionName,
                 VirtualMachineExtension extensionParameters, Dictionary`2 customHeaders, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand.<ExecuteCmdlet>b__30_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronou
                 slyOrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Set-AzVMExtension}
Line           : Set-AzVMExtension -Name AMAWindows -ExtensionType AzureMonitorWindowsAgent -Publisher
                 Microsoft.Azure.Monitor -ResourceGroupName RG01 -VMName Server1 -TypeHandlerVersion 1.0
Position       : At line:1 char:1
                 + Set-AzVMExtension -Name AMAWindows -ExtensionType AzureMonitorWindows …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.6.1; CommandName: Resolve-AzError; PSVersion: 7.2.0; IsSuccess: True; Duration: 00:00:00.0327678
DEBUG: Finish sending metric.
DEBUG: 5:24:11 PM - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by SatishBoddu-MSFT** [comment]
Hello @yordanbechev Thanks for reporting this issue.

We see that the parameter is optional as per the document, but the command throws the error **"Set-AzVMExtension: 'Location' cannot be null."**

![image](https://user-images.githubusercontent.com/62923178/144701516-c85da8ec-0d88-49b2-b9de-3c9071d5b56f.png)

![image](https://user-images.githubusercontent.com/62923178/144701520-3ae5a74d-df8b-4774-83fb-ef1e83c0fdd0.png)

Routing to the Service team.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
@MsGabsta Could you please look into the issue?

**Comment by MsGabsta** [comment]
> Hello @yordanbechev Thanks for reporting this issue.
> 
> We see that the parameter is optional as per the document, but the command throws the error **"Set-AzVMExtension: 'Location' cannot be null."**
> 
> ![image](https://user-images.githubusercontent.com/62923178/144701516-c85da8ec-0d88-49b2-b9de-3c9071d5b56f.png)
> 
> ![image](https://user-images.githubusercontent.com/62923178/144701520-3ae5a74d-df8b-4774-83fb-ef1e83c0fdd0.png)
> 
> Routing to the Service team.

As Satish mentioned I can see where the doc for this command states it optional for the location parameter, but when trying to use it you get the error message that it is mandatory.

Engaging @jaylabell on this.

**Comment by jaylabell** [comment]
The team has been made aware of this error and improvements are on the way. Thank you!

**Comment by grizzlytheodore** [comment]
Hello, I am an engineer from the CPlat SDK/PS team. I will be working on resolving this. Will post updates as I make progress.

**Comment by grizzlytheodore** [comment]
the fix has been merged in the PR above. It will be GA with the [2/8 release ](https://github.com/Azure/azure-powershell/pull/16786)

**Comment by navba-MSFT** [comment]
Thanks @grizzlytheodore for looking into this.

@yordanbechev Could you please let us know if you have any further queries on this or need any further assistance ?

**Comment by MsGabsta** [comment]
Issue has been resolved, no further response from customer, closing the issue.
