### ISSUE TITLE
AZ.Compute 4.21.0 throws exception on UserData when using Update-AZVM

### ISSUE THREAD

**Issue by MrFly72** [Azure/azure-powershell#16597]
### Description

When using the documented way:
$vm=Get-AZVM -Name MachineName
$vm.hardwareProfile.vmSize = "Standard_B2ms"
$vm | Update-AZVM -NoWait
It throws an exception, that Userdata has to be in Base64.

### Issue script & Debug output

```PowerShell
$vm=Get-AZVM -Name MachineName
$vm.hardwareProfile.vmSize = "Standard_B2ms"
$vm | Update-AZVM -NoWait

Exception:
Update-AzVM: UserData must be in Base64 encoding and with a maximum length of 87384 characters.
ErrorCode: InvalidParameter
ErrorMessage: UserData must be in Base64 encoding and with a maximum length of 87384 characters.
ErrorTarget: userData
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 490d441a-285a-4be8-bb2c-445e64a1d7bc
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.21.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
```

### Error output

```PowerShell
HistoryId: 23

RequestId      : 
Message        : UserData must be in Base64 encoding and with a maximum length of 87384 characters.
                 ErrorCode: InvalidParameter
                 ErrorMessage: UserData must be in Base64 encoding and with a maximum length of 87384 characters.
                 ErrorTarget: userData
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 OperationID : 490d441a-285a-4be8-bb2c-445e64a1d7bc
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Update-AzVM}
Line           : $vm | update-azvm -NoWait
Position       : At line:1 char:7
                 + $vm | update-azvm -NoWait
                 +       ~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 23
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by Karishma-Tiwari-MSFT** [comment]
Redirecting to service team as it is reproduceable.

**Comment by jaylabell** [comment]
Taking a look into this issue.

**Comment by navba-MSFT** [comment]
@MrFly72 Apologies for the late reply. The similar issue was reported here #16689 too. Seems like using the [latest version ](https://www.powershellgallery.com/packages/Az.Compute/4.23.0) resolves the issue. Could you please try that let us know if that helps ? Awaiting your reply.

**Comment by superfliege** [comment]
For me the issue is resolved with Az.Compute Version 4.26.0
