### ISSUE TITLE
Get-AzDataFactoryV2Dataset : Can not convert Object to String

### ISSUE THREAD

**Issue by jpaulo-kumulus** [Azure/azure-powershell#16593]
### Description

Get-AzDataFactoryV2Dataset fails to retrieve the information of a specific DATASET 
When creating a Dataset with "Compression Type" using "add dynamic content" with parameter input "@dataset().compression"
After Saving and Publishing, if I try to run the following command it returns the Error
```powershell
Get-AzDataFactoryV2Dataset -ResourceGroupName "$ResourceGroupName" -DataFactoryName "$FactoryName"
Get-AzDataFactoryV2Dataset: Can not convert Object to String.
``` 

### Issue script & Debug output

```PowerShell
DEBUG: 11:47:03 - GetAzureDataFactoryDatasetCommand begin processing with ParameterSet 'ByFactoryName'.
DEBUG: 11:47:03 - using account id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', environment: 'AzureCloud', tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: 11:47:03 - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', TenantId:'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: Request [2a3b7da1-d417-432f-b429-aa52f11f979b] POST https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:2a3b7da1-d417-432f-b429-aa52f11f979b
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 6.0.0-rtm.21522.10; Microsoft Windows 10.0.19043)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [2a3b7da1-d417-432f-b429-aa52f11f979b] 200 OK (00.4s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:e737ac4d-882f-40aa-a43a-a043526f1100
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Set-Cookie:REDACTED
Date:Tue, 07 Dec 2021 14:47:04 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1360

DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2021-12-07T15:47:03.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', UserId: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.DataFactory/factories/xxxxxxxx/datasets/DS_55_GCP_GoogleStorageArchiveFile?api-version=2018-06-01

Headers:
x-ms-client-request-id        : a58e879a-f32a-44b6-a49a-77f5d02f46b4
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 11996
x-ms-request-id               : a3139e91-5b4d-417b-91f5-5c4a7f6db228
x-ms-correlation-request-id   : a3139e91-5b4d-417b-91f5-5c4a7f6db228
x-ms-routing-request-id       : BRAZILSOUTH:20211207T144706Z:a3139e91-5b4d-417b-91f5-5c4a7f6db228
Date                          : Tue, 07 Dec 2021 14:47:05 GMT

Body:
{
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.DataFactory/factories/xxxxxxxx/datasets/DS_55_GCP_GoogleStorageArchiveFile",
  "name": "DS_55_GCP_GoogleStorageArchiveFile",
  "type": "Microsoft.DataFactory/factories/datasets",
  "properties": {
    "description": "DS_55_GCP_GoogleStorageArchiveFile",
    "linkedServiceName": {
      "referenceName": "LS_55_GCP_STORAGE",
      "type": "LinkedServiceReference"
    },
    "parameters": {
      "bucket": {
        "type": "string"
      },
      "folder": {
        "type": "string"
      },
      "wildcardFile": {
        "type": "string"
      },
      "compression": {
        "type": "string",
        "defaultValue": "gzip"
      }
    },
    "folder": {
      "name": "GCP_CloudStorage"
    },
    "annotations": [],
    "type": "Binary",
    "typeProperties": {
      "location": {
        "type": "GoogleCloudStorageLocation",
        "bucketName": {
          "value": "@dataset().bucket",
          "type": "Expression"
        },
        "folderPath": {
          "value": "@dataset().folder",
          "type": "Expression"
        },
        "fileName": {
          "value": "@dataset().wildcardFile",
          "type": "Expression"
        }
      },
      "compression": {
        "type": {
          "value": "@dataset().compression",
          "type": "Expression"
        },
        "level": "Optimal"
      }
    }
  },
  "etag": "1700f859-0000-0c00-0000-61af72390000"
}


Get-AzDataFactoryV2Dataset: Can not convert Object to String.
DEBUG: AzureQoSEvent: Module: Az.DataFactory:1.15.0; CommandName: Get-AzDataFactoryV2Dataset; PSVersion: 7.2.0; IsSuccess: False; Duration: 00:00:02.0170243; Exception: Can not convert Object to String.;
DEBUG: Finish sending metric.
DEBUG: 11:47:07 - GetAzureDataFactoryDatasetCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.6.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     1.15.0                Az.DataFactory                      {Add-AzDataFactoryV2DataFlowDebugSessionPackage, …
```

### Error output

```PowerShell
HistoryId: 50

Message        : Can not convert Object to String.
StackTrace     :    at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
                    at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader,
                 Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter
                 converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type
                 objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
                    at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader,
                 Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter
                 converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty
                 property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty
                 containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject,
                 JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type
                 objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract,
                 JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader
                 reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract
                 containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type
                 objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json,
                 JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.DataFactory.DatasetsOperations.GetWithHttpMessagesAsync(String
                 resourceGroupName, String factoryName, String datasetName, String ifNoneMatch, Dictionary`2
                 customHeaders, CancellationToken cancellationToken)
                    at
                 Microsoft.Azure.Management.DataFactory.DatasetsOperationsExtensions.GetAsync(IDatasetsOperations
                 operations, String resourceGroupName, String factoryName, String datasetName, String ifNoneMatch,
                 CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.DataFactory.DatasetsOperationsExtensions.Get(IDatasetsOperations
                 operations, String resourceGroupName, String factoryName, String datasetName, String ifNoneMatch)
                    at Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.GetDataset(String resourceGroupName,
                 String dataFactoryName, String datasetName)
                    at
                 Microsoft.Azure.Commands.DataFactoryV2.DataFactoryClient.FilterPSDatasets(AdfEntityFilterOptions
                 filterOptions)
                    at Microsoft.Azure.Commands.DataFactoryV2.GetAzureDataFactoryDatasetCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzDataFactoryV2Dataset}
Line           : Get-AzDataFactoryV2Dataset -ResourceGroupName xxxxxxxxx -DataFactoryName xxxxxxx
                 -DatasetName DS_55_GCP_GoogleStorageArchiveFile -Verbose
Position       : At line:1 char:1
                 + Get-AzDataFactoryV2Dataset -ResourceGroupName xxxxxxxxxxxxxx -D …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 50
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by SaurabhSharma-MSFT** [comment]
@jpaulo-kumulus I do not see any error getting dataset with compression type using `Get-AzDataFactoryV2Dataset`.  I have also used the same 1.15.0 version.
![image](https://user-images.githubusercontent.com/38112130/146620282-730674d6-78bc-4ba1-99fd-befa5d494069.png)

**Comment by SaurabhSharma-MSFT** [comment]
@jpaulo-kumulus Please let me know if you have any other questions.

**Comment by SaurabhSharma-MSFT** [comment]
@jpaulo-kumulus We are proceeding with the closure of this issue as we have not heard back from you. Thanks.

**Comment by jpaulo-kumulus** [comment]
Sorry for the delay in my response @SaurabhSharma-MSFT, the error stopped without any modifications on my part.
Thanks for the response
