### ISSUE TITLE
Copy-AzStorageBlob fails when the filename is too long

### ISSUE THREAD

**Issue by nathan-given-health-catalyst** [Azure/azure-powershell#16628]
### Description

This doesn't work when using Azure Powershell:
`$blob | Copy-AzStorageBlob -DestContainer "$containerNM" -DestBlob "ABCD__DEV__Abcdefghi.AbcdefghijklmnopqrstuvwxyBASE_load20211130_175336.0001.gz"`

But it does work when using Azure Storage Explorer to copy blobs from one folder to another.

After some research, it appears that there is a limit on the number of characters for `-DestBlob`?  I say this because this azure powershell works just fine:

`$blob | Copy-AzStorageBlob -DestContainer "$containerNM" -DestBlob "ABCD__DEV__Abcdefghi.AbcdefBASE_load20211130_175336.0001.gz"`

Is this by design?

We built a process around encoding some metadata into the filename and we're now automating the process (rather than manually copying files around in azure storage explorer).  With this hiccup we're now wondering if using azure powershell for automation was the best choice (or we're wondering if we are doing something wrong).

PS: Here is the full error message

```
Copy-AzStorageBlob: One of the request inputs is out of range.
RequestId:143bc961-f01e-0037-667c-f07e91000000
Time:2021-12-13T23:54:34.9217064Z
Status: 400 (One of the request inputs is out of range.)
ErrorCode: OutOfRangeInput
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>OutOfRangeInput</Code><Message>One of the request inputs is out of range.
RequestId:143bc961-f01e-0037-667c-f07e91000000
Time:2021-12-13T23:54:34.9217064Z</Message></Error>
Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 143bc961-f01e-0037-667c-f07e91000000
x-ms-client-request-id: 30f15426-cfa8-4615-88f9-e41bc483ace8
x-ms-version: 2020-10-02
x-ms-error-code: OutOfRangeInput
Date: Mon, 13 Dec 2021 23:54:34 GMT
Content-Length: 226
Content-Type: application/xml
```

### Issue script & Debug output

```PowerShell
[DBG]: PS C:\Users\nathang\Documents\ls-platform-dataops> $destBlob = Copy-AzStorageBlob -SrcContainer $containerNM -SrcBlob $blob.name -DestContainer $containerNM -DestBlob 'ABCD__DEV__Abcdefghi.AbcdefghijklmnoBASE_load20211130_175336.0001.gz' -Context $storageaccount.context

Copy-AzStorageBlob: One of the request inputs is out of range.
RequestId:143bc961-f01e-0037-667c-f07e91000000
Time:2021-12-13T23:54:34.9217064Z
Status: 400 (One of the request inputs is out of range.)
ErrorCode: OutOfRangeInput
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>OutOfRangeInput</Code><Message>One of the request inputs is out of range.
RequestId:143bc961-f01e-0037-667c-f07e91000000
Time:2021-12-13T23:54:34.9217064Z</Message></Error>
Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 143bc961-f01e-0037-667c-f07e91000000
x-ms-client-request-id: 30f15426-cfa8-4615-88f9-e41bc483ace8
x-ms-version: 2020-10-02
x-ms-error-code: OutOfRangeInput
Date: Mon, 13 Dec 2021 23:54:34 GMT
Content-Length: 226
Content-Type: application/xml

[DBG]: PS C:\Users\nathang\Documents\ls-platform-dataops> $destBlob = Copy-AzStorageBlob -SrcContainer $containerNM -SrcBlob $blob.name -DestContainer $containerNM -DestBlob 'ABCD__DEV__Abcdefghi.AbcdefghijBASE_load20211130_175336.0001.gz' -Context $storageaccount.context

Copy-AzStorageBlob: One of the request inputs is out of range.
RequestId:143bdb85-f01e-0037-507c-f07e91000000
Time:2021-12-13T23:54:43.4502620Z
Status: 400 (One of the request inputs is out of range.)
ErrorCode: OutOfRangeInput
Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>OutOfRangeInput</Code><Message>One of the request inputs is out of range.
RequestId:143bdb85-f01e-0037-507c-f07e91000000
Time:2021-12-13T23:54:43.4502620Z</Message></Error>
Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 143bdb85-f01e-0037-507c-f07e91000000
x-ms-client-request-id: 2ed3c261-73ab-444f-b189-dba7577a7e62
x-ms-version: 2020-10-02
x-ms-error-code: OutOfRangeInput
Date: Mon, 13 Dec 2021 23:54:43 GMT
Content-Length: 226
Content-Type: application/xml
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.1.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, C…
```

### Error output

```PowerShell
HistoryId: 187

Message        : One of the request inputs is out of range.
                 RequestId:f4581145-701e-0004-1e3f-f0ff88000000
                 Time:2021-12-13T16:36:08.6043602Z
                 Status: 400 (One of the request inputs is out of range.)
                 ErrorCode: OutOfRangeInput

                 Content:
                 <?xml version="1.0" encoding="utf-8"?><Error><Code>OutOfRangeInput</Code><Message>One of the request inputs is out of range.
                 RequestId:f4581145-701e-0004-1e3f-f0ff88000000
                 Time:2021-12-13T16:36:08.6043602Z</Message></Error>

                 Headers:
                 Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
                 x-ms-request-id: f4581145-701e-0004-1e3f-f0ff88000000
                 x-ms-client-request-id: 8d72d74e-e635-47d0-b935-ade11e4d6605
                 x-ms-version: 2020-10-02
                 x-ms-error-code: OutOfRangeInput
                 Date: Mon, 13 Dec 2021 16:36:07 GMT
                 Content-Length: 226
                 Content-Type: application/xml

StackTrace     :    at Azure.Storage.Blobs.BlockBlobRestClient.StageBlockFromURL(String blockId, Int64 contentLength, String sourceUrl, String sourceRange, Byte[] sourceContentMD5, Byte[] sourceContentcrc64, Nullable`1 timeout, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, String leaseId, Nullable`1 sourceIfModifiedSince, Nullable`1 sourceIfUnmodifiedSince, String sourceIfMatch, String sourceIfNoneMatch, String copySourceAuthorization, CancellationToken cancellationToken)
                    at Azure.Storage.Blobs.Specialized.BlockBlobClient.StageBlockFromUriInternal(Uri sourceUri, String base64BlockId, HttpRange sourceRange, Byte[] sourceContentHash, RequestConditions sourceConditions, BlobRequestConditions conditions, HttpAuthorization sourceAuthentication, Boolean async, CancellationToken cancellationToken)
                    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
                    at Azure.Storage.Blobs.Specialized.BlockBlobClient.StageBlockFromUri(Uri sourceUri, String base64BlockId, HttpRange sourceRange, Byte[] sourceContentHash, RequestConditions sourceConditions, BlobRequestConditions conditions, CancellationToken cancellationToken)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.CopyAzureStorageBlob.CopyFromUri(Int64 taskId, IStorageBlobManagement destChannel, Uri srcUri, BlobBaseClient destBlob)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTask(Int64 taskId, Task task)
Exception      : Azure.RequestFailedException
InvocationInfo : {Copy-AzStorageBlob}
Line           :                 $destBlob = Copy-AzStorageBlob -SrcContainer $containerNM -SrcBlob $blob.name -DestContainer $containerNM -DestBlob $filename -Context $storageaccount.context

Position       : At C:\Users\user\Documents\misc\scripts\invoke-temporarycopyblobforingest.ps1:56 char:29
                 + … $destBlob = Copy-AzStorageBlob -SrcContainer $containerNM -SrcBlob $b …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 187


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by nathan-given-health-catalyst** [comment]
Is `copy-azstorageblob` converting my command to a put request with a blockid?
And the put request blockid has a max length of 64 bytes?

Documentation: https://docs.microsoft.com/en-us/rest/api/storageservices/put-block

(Credit to https://stackoverflow.com/questions/46997836/azure-blobstorage-400-one-of-the-request-inputs-is-out-of-range for referencing the above doc).

If this is true, how do I get around this in Azure Powershell?  (The `Copy-AzStorageBlob` docs make no reference to character limits)

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by blueww** [comment]
@nathan-given-health-catalyst

Thanks for reporting this issue!
I have found the root cause of the issue and have raise a PR to fix it. https://github.com/Azure/azure-powershell/pull/16630/

Before the issue is fixed, you can use "Start-AzStorageBlobCopy" instead of "Copy-AzStorageBlob" to copy blob. This cmdlet don't have this issue.
Please note, if your source and dest blob are in same storage account:
- you don't need to run below `$blobdest  | Get-AzStorageBlobCopyState  -WaitForComplete`, since the copy will be finished with the first command.
- For copy big blob in same account, "Start-AzStorageBlobCopy" normally can be faster than "Copy-AzStorageBlob", since it won't do blob content copy.

```
$blobdest = $blob | Start-AzStorageBlobCopy -DestContainer "$containerNM" -DestBlob "ABCD__DEV__Abcdefghi.AbcdefghijklmnopqrstuvwxyBASE_load20211130_175336.0001.gz"
$blobdest  | Get-AzStorageBlobCopyState  -WaitForComplete
```

**Comment by nathan-given-health-catalyst** [comment]
Thank you!  I've switched our code to use `Start-AzStorageBlobCopy` and this issue can likely be closed?

**Comment by SaurabhSharma-MSFT** [comment]
@nathan-given-health-catalyst Thanks for the confirmation.  We are proceeding with the closure of this case.  If you have any further questions, please let us know we will continue the conversation over here.
