### ISSUE TITLE
New-AzRoleAssignment using ApplicationId parameter fails with 

### ISSUE THREAD

**Issue by afedyashov** [Azure/azure-powershell#16656]
### Description

Attempt to create role assignment with `New-AzRoleAssignment` using ApplicationId parameter results in BadRequest error.

Debug mode reveals the problem is in request body containing invalid service principal information, namely "ServicePrincipal" literal is used as both principalId and principalType. Note that previous request to fetch service principal metadata returned correct fields (as can be seen in debug output).

Request:

PUT: https://management.azure.com//subscriptions/.../providers/Microsoft.Authorization/roleAssignments/...?api-version=2020-08-01-preview

Body:

```
{
  "properties": {
    "roleDefinitionId": "/subscriptions/.../providers/Microsoft.Authorization/roleDefinitions/...",
    "principalId": "ServicePrincipal",
    "principalType": "ServicePrincipal"
  }
}
```

Response
Status Code: BadRequest:
Body:
```
{
  "error": {
    "code": "InvalidPrincipalId",
    "message": "The Principal ID 'ServicePrincipal' is not valid. Principal ID must be a GUID."
  }
}
```

## Workaround

I was able to create role assignment using a different parameter set: 

    New-AzRoleAssignment -RoleDefinitionName Reader -ObjectId $sp.Id

For which PUT assignment body was correct:
```
{
  "properties": {
    "roleDefinitionId": "/subscriptions/.../providers/Microsoft.Authorization/roleDefinitions/...",
    "principalId": "...",
    "principalType": "ServicePrincipal"
  }
}
```

### Issue script & Debug output

```PowerShell
$sp = New-AzADServicePrincipal -DisplayName $ApplicationDisplayName
New-AzRoleAssignment -RoleDefinitionName Reader -ApplicationId $sp.AppId -Debug

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=...

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Body:
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#servicePrincipals",
  "value": [
    {
      "id": "...",
      ...
      "servicePrincipalNames": [
        ...
      ],
      "servicePrincipalType": "Application",
      ...
    }
  ]
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/.../providers/Microsoft.Authorization/roleDefinitions?$filter=roleName eq 'Reader'&api-version=2018-01-01-preview

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Body:
{
  "value": [
    {
      "properties": {
        "roleName": "Reader",
        "type": "BuiltInRole",
        "description": "View all resources, but does not allow you to make any changes.",
        ...
      },
      ... 
    }
  ]
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com//subscriptions/.../providers/Microsoft.Authorization/roleAssignments/...?api-version=2020-08-01-preview

Body:
{
  "properties": {
    "roleDefinitionId": "/subscriptions/.../providers/Microsoft.Authorization/roleDefinitions/...",
    "principalId": "ServicePrincipal",
    "principalType": "ServicePrincipal"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Body:
{
  "error": {
    "code": "InvalidPrincipalId",
    "message": "The Principal ID 'ServicePrincipal' is not valid. Principal ID must be a GUID."
  }
}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     5.1.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperations.CreateWithHttpMessagesAsync(String scope, String roleAssignmentName, RoleAssignmentCreateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.CreateAsync(IRoleAssignmentsOperations operations, String scope, String roleAssignmentName, RoleAssignmentCreateParameters parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.Create(IRoleAssignmentsOperations operations, String scope, String roleAssignmentName, RoleAssignmentCreateParameters parameters)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.CreateRoleAssignment(FilterRoleAssignmentsOptions parameters, Guid roleAssignmentId)
                    at Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.Authorization.Models.ErrorResponseException
InvocationInfo : {New-AzRoleAssignment}
Line           : New-AzRoleAssignment -RoleDefinitionName Reader -ApplicationId $sp.AppId -Debug
Position       : At line:1 char:1
                 + New-AzRoleAssignment -RoleDefinitionName Reader -ApplicationId $sp.Ap …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We will look into it.

**Comment by BethanyZhou** [comment]
It's same with https://github.com/Azure/azure-powershell/issues/16627. Fix will be available in next Az.Resources. Date to release to Customers: 01/04/2022
