### ISSUE TITLE
Unable to create new Application using New-AzAdApplication

### ISSUE THREAD

**Issue by ruankr** [Azure/azure-powershell#16659]
### Description

Previously, we created AD applications using the simple command:
New-AzAdServicePrincipal -DisplayName $spnName -StartDate $(Get-Date).AddDays(-1) -EndDate $(Get-Date).AddYears(100)

This in turn would create an Azure AD Application and Azure AD Service principal, with user_impersonation exposed API's and a secret on the application. We would then use this to grant restricted access to PowerBi via the app (isolated workspace per app/spn using CCFlow).

Since the modules were upgraded to 5.1.0 this no longer works and it seems we now have to jump through a tonne of hoops to try and get this working again. Below is what I've tried thus far:

In order to create the app we are still using the same command, however as per the breaking changes we can no longer perform the following to retrieve the secret when the new app is created:
$spnSecret = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($spn.Secret))

The documentation states to use "PasswordCredential", however we are getting the below error:
[Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential]$pwdCred = @{
    EndDateTime = $(Get-Date).AddYears(100)
    StartDateTime = $(Get-Date).AddDays(-1)
    KeyId = (New-Guid).Guid
}

We also notice that the default api exposure does not exist anymore so am trying to also add this in using the Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPermissionScope as per docuimentation.

[Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPermissionScope]$oathObj = @{
    AdminConsentDescription = "Allow the application to access $spnName on behalf of the signed-in user."
    AdminConsentDisplayName = "Access $spnName"
    IsEnabled = $true
    Type = "User"
    userConsentDescription = "Allow the application to access $spnName on your behalf."
    userConsentDisplayName = "Access $spnName"
    Value = "user_impersonation"
}

We then run it all together with no success

New-AzADServicePrincipal -DisplayName $spnName -PasswordCredential $pwdCred -Oauth2PermissionScope $oathObj

New-AzADServicePrincipal: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.

Documentation and error does not clearly state what is going wrong or missing.

### Issue script & Debug output

```PowerShell
DEBUG: Setting WindowTitle: C:\ - PowerShell 7.2 (22728)
C:\> $spnName = "testapp1"
DEBUG: Setting WindowTitle: C:\ - PowerShell 7.2 (22728)
C:\> [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPermissionScope]$oathObj = @{
    AdminConsentDescription = "Allow the application to access $spnName on behalf of the signed-in user."
    AdminConsentDisplayName = "Access $spnName"
    IsEnabled = $true
    Type = "User"
    userConsentDescription = "Allow the application to access $spnName on your behalf."
    userConsentDisplayName = "Access $spnName"
    Value = "user_impersonation"
}
DEBUG: Setting WindowTitle: C:\ - PowerShell 7.2 (22728)
C:\> [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential]$pwdCred = @{
    EndDateTime = $(Get-Date).AddYears(100)
    StartDateTime = $(Get-Date).AddDays(-1)
    KeyId = (New-Guid).Guid
}
DEBUG: Setting WindowTitle: C:\ - PowerShell 7.2 (22728)
C:\> New-AzADServicePrincipal -DisplayName $spnName -PasswordCredential $pwdCred -Oauth2PermissionScope $oathObj
DEBUG: Registering Az shared AssemblyLoadContext for path: 'C:\WorkFolder\Documents\PowerShell\Modules\Az.Accounts\2.7.0\StartupScripts\..\AzSharedAlcAssemblies'.
DEBUG: AssemblyLoadContext registered.
New-AzADServicePrincipal: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
DEBUG: Setting WindowTitle: C:\ - PowerShell 7.2 (25880)
```

### Environment data

```PowerShell
$PSVersionTable


Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
get-module Az*


ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     5.1.0                 az.resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Binary     2.0.2.140             azuread                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember…}
```

### Error output

```PowerShell
Resolve-AzError

DEBUG: Sought all Az modules and got latest version 5.9.0
DEBUG: 15:07:57 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 15:07:57 - using account id 'xxxxx'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 8

Message        : Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADApplication}
Line           :       $app = New-AzADApplication @PSBoundParameters

Position       : At C:\WorkFolder\Documents\PowerShell\Modules\Az.Resources\5.1.0\MSGraph\custom\New-AzADServicePrincipal.ps1:733 char:14
                 +       $app = New-AzADApplication @PSBoundParameters
                 +              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.0; CommandName: Resolve-AzError; PSVersion: 7.2.0; IsSuccess: True; Duration: 00:00:00.1443869
DEBUG: Finish sending metric.
DEBUG: 15:07:58 - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. @VeryEarly , please look into it.

**Comment by ruankr** [comment]
Further to this trying to use the "-ApplicationObject" parameter also seems to fail. 

```   
$spnName = "test-new-app"

    [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPermissionScope]$oathObj = @{
        AdminConsentDescription = "Allow the application to access $spnName on behalf of the signed-in user."
        AdminConsentDisplayName = "Access $spnName"
        IsEnabled = $true
        Type = "User"
     #   userConsentDescription = "Allow the application to access $spnName on your behalf."
     #   userConsentDisplayName = "Access $spnName"
        Value = "user_impersonation"
    }
    
    [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential]$pwdCred = @{
        EndDateTime = $(Get-Date).AddYears(100)
        StartDateTime = $(Get-Date).AddDays(-1)
        KeyId = (New-Guid).Guid
    }

[Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphApplication]$appObject = @{
        api = [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphApiApplication]@{ 
            Oauth2PermissionScope  = [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPermissionScope]@{ 
                AdminConsentDescription = "Allow the application to access $spnName on behalf of the signed-in user."
                AdminConsentDisplayName = "Access $spnName"
                IsEnabled = $true
                Type = "User"
                userConsentDescription = "Allow the application to access $spnName on your behalf."
                userConsentDisplayName = "Access $spnName"
                Value = "user_impersonation"
                Id = (New-Guid).Guid
            } 
        }

        Web = [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphWebApplication]@{
            homePageUrl = "http://$spnName"
            implicitGrantSettings = [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphImplicitGrantSettings]@{
              enableAccessTokenIssuance = $false
              enableIdTokenIssuance = $true
            }
        }

        PasswordCredentials = [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphPasswordCredential] @{
            EndDateTime = $(Get-Date).AddYears(100)
            StartDateTime = $(Get-Date).AddDays(-1)
            KeyId = (New-Guid).Guid
        }

        DisplayName = $spnName
    }

New-AzADServicePrincipal -ApplicationObject $appObject -PasswordCredential $pwdCred -HomePage "http://$spnName" -Oauth2PermissionScope $oathObj
```

This produces the error:

```
New-AzADServicePrincipal -ApplicationObject $appObject -PasswordCredential $pwdCred -HomePage "http://$spnName" -Oauth2PermissionScope $oathObj
New-AzADServicePrincipal_CreateExpanded: C:\WorkFolder\Documents\PowerShell\Modules\az.resources\5.1.0\MSGraph\custom\New-AzADServicePrincipal.ps1:741:19
Line |
 741 |  … Write-Output ($sp = MSGraph.internal\New-AzADServicePrincipal @param)
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Invalid value specified for property 'appId' of resource 'ServicePrincipal'.
```

Not able to replicate the old module behaviour at all as a result... Any help would be appreciated.

**Comment by VeryEarly** [comment]
Hi @ruankr , I'm working on the bug fix now, thanks for reporting this issue.
Fix will be out early next month in https://github.com/Azure/azure-powershell/milestone/130 release

For now, I recommend you try setting these properties to application by New-AzADApplication and link that application to serviceprincipal with New-AzADServiceprincipal -ApplicationObject $appObject

**Comment by VeryEarly** [comment]
Hi @ruankr 
The old Az.Resources module mixed sp with app altogether which is misleading, what you want to do is actually
```
$web=New-Object -TypeName "Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphWebApplication" -Property @{HomePageUrl = "http://$spnName";ImplicitGrantSetting.EnableIdTokenIssuance = $true}
New-AzAdApplication -DisplayName $spnName -PasswordCredentials $pwdCred -Api $apiProperties -Web $web
```
The Oauth2PermissionScope was generated by swagger microsoft graph provided, it is possible that some properties do not match the AAD apis

**Comment by ruankr** [comment]
@VeryEarly 

"-Web" is not an allowed propertyand generates:
```
New-AzAdApplication -DisplayName $spnName -PasswordCredentials $pwdCred -Api $apiProperties -Web $web
New-AzADApplication: Parameter cannot be processed because the parameter name 'Web' is ambiguous. Possible matches include: -HomePage -ReplyUrls.
```

Also, your syntax does not work What I have noticed however is I can add it like below, however it does not honour the IMicrosoftGraphImplicitGrantSettings values:

```
[Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphWebApplication]$web = @{
    homePageUrl = "http://$spnName"
    implicitGrantSettings = [Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.IMicrosoftGraphImplicitGrantSettings]@{
      enableAccessTokenIssuance = $false
      enableIdTokenIssuance = $true
    }
}

$web | fl *
$web.ImplicitGrantSetting | fl *

HomePageUrl          : http://mytestapp
ImplicitGrantSetting : {
                       }
LogoutUrl            : 
RedirectUri          : 
AdditionalProperties : 



EnableAccessTokenIssuance : 
EnableIdTokenIssuance     : 
AdditionalProperties      : {}
```

**Comment by VeryEarly** [comment]
> 

Thanks for pointing out, I have 'Web' exposed now please expect it in the next official release.

For now, please set homepageurl by using parameter 'HomePage', I'm afraid you cannot set the implicitGrantSettings this time but it will be available when new version of Az.Resources publichsed
