### ISSUE TITLE
Unable to create a new Kusto Script using New-AzKustoScript

### ISSUE THREAD

**Issue by CaptainFanZzz** [Azure/azure-powershell#16668]
### Description

Previously, we created Cluster and  Database
```
New-AzKustoDatabase -ResourceGroupName testrg -ClusterName testnewkustocluster -Name mykustodatabase -Kind ReadWrite -Location 'East US'

Kind      Location Name                                Type
----      -------- ----                                ----
ReadWrite East US  testnewkustocluster/mykustodatabase Microsoft.Kusto/Clusters/Databases
```
 Then using the simple command:
```
New-AzKustoScript -ClusterName testnewkustocluster -DatabaseName mykustodatabase -Name newkustoscript -ResourceGroupName testrg
```
This in turn would warn that my cluster location is invalid. My Location is 'East US', which only contains space, so it should be succeeded.

### Issue script & Debug output

```PowerShell
New-AzKustoScript -ClusterName testnewkustocluster -DatabaseName mykustodatabase -Name newkustoscript -ResourceGroupName testrg
New-AzKustoScript_CreateExpanded: The value for the provided property 'location' contains invalid characters. The property value can only contain spaces, letters, digits or any of the following characters '()'.

DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : 219e6af0-4156-4010-b1fa-18ddb69f5208
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-resource-requests: 199
x-ms-correlation-request-id   : 70908e67-0ade-412e-9bad-5ca144a02504
x-ms-routing-request-id       : SOUTHEASTASIA:20211217T071731Z:70908e67-0ade-412e-9bad-5ca144a02504
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Fri, 17 Dec 2021 07:17:31 GMT

Body:
{
  "error": {
    "code": "InvalidPropertyValue",
    "message": "The value for the provided property 'location' contains invalid characters. The property value can only contain spaces, letters, digits or any of the following characters '()'."
  }
}


DEBUG: ResponseCreated:
VERBOSE: BEFORE RESPONSE DISPATCH The contents are 'BeforeResponseDispatch' and ''
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.0-preview.10
PSEdition                      Core
GitCommitId                    7.2.0-preview.10
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.0.0                 Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKustoDa…
```

### Error output

```PowerShell
HistoryId: 11

Message        : The term 'Reslove-AzError' is not recognized as a name of a cmdlet, function, script file, or
                 executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try
                 again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes
                 commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin,
                 ExecutionContext context)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe,
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[]
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Reslove-AzError
Position       : At line:1 char:1
                 + Reslove-AzError
                 + ~~~~~~~~~~~~~~~
HistoryId      : 11


   HistoryId: 10

Message        : [InvalidPropertyValue] : The value for the provided property 'location' contains invalid characters.
                 The property value can only contain spaces, letters, digits or any of the following characters '()'.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {New-AzKustoScript_CreateExpanded}
Line           : New-AzKustoScript -ClusterName testnewkustocluster -DatabaseName mykustodatabase -Name newkustoscript
                 -ResourceGroupName testrg
Position       : At line:1 char:1
                 + New-AzKustoScript -ClusterName testnewkustocluster -DatabaseName myku …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 10


   HistoryId: 3

Message        : [ParentResourceNotFound] : Can not perform requested operation on nested resource. Parent resource
                 'testnewkustocluster' not found.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Test-AzKustoScriptNameAvailability_CheckExpanded}
Line           : Test-AzKustoScriptNameAvailability -ClusterName testnewkustocluster -DatabaseName mykustodatabase
                 -ResourceGroupName testrg -Name newkustoscript
Position       : At line:1 char:1
                 + Test-AzKustoScriptNameAvailability -ClusterName testnewkustocluster - …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3


   HistoryId: 2

Message        : [ResourceGroupNotFound] : Resource group 'testrg' could not be found.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Test-AzKustoScriptNameAvailability_CheckExpanded}
Line           : Test-AzKustoScriptNameAvailability -ClusterName testnewkustocluster -DatabaseName mykustodatabase
                 -ResourceGroupName testrg -Name newkustoscript
Position       : At line:1 char:1
                 + Test-AzKustoScriptNameAvailability -ClusterName testnewkustocluster - …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
@CaptainFanZzz , `East US` is display name of `eastus`. Could you try script again and use `eastus`? If it works, it means location name instead of display name should be used.

**Comment by CaptainFanZzz** [comment]
@dingmeng-xue , when creating cluster and database by using ```eastus```, it turns out to the same result.
```
New-AzKustoCluster -ResourceGroupName testrg -Name testnewkustocluster -Location 'eastus' -SkuName Standard_D11_v2 -SkuTier Standard -EngineType 'V2'

Location Name                Type                     Etag                           Zone
-------- ----                ----                     ----                           ----
East US  testnewkustocluster Microsoft.Kusto/Clusters "2021-12-20T02:23:53.5883516Z"

New-AzKustoDatabase -ResourceGroupName testrg -ClusterName testnewkustocluster -Name mykustodatabase -Kind ReadWrite -Location 'eastus'

Kind      Location Name                                Type
----      -------- ----                                ----
ReadWrite East US  testnewkustocluster/mykustodatabase Microsoft.Kusto/Clusters/Databases

New-AzKustoScript -ClusterName testnewkustocluster -DatabaseName mykustodatabase -Name newkustoscript -ResourceGroupName testrg
New-AzKustoScript_CreateExpanded: The value for the provided property 'location' contains invalid characters. The property value can only contain spaces, letters, digits or any of the following characters '()'.
```
Also, I have tried this.
```
New-AzKustoScript -ClusterName testnewkustocluster -DatabaseName mykustodatabase -Name newkustoscript -ResourceGroupName testrg -Location 'eastus'
New-AzKustoScript: A parameter cannot be found that matches parameter name 'Location'.
```

**Comment by lijinpei2008** [comment]
Hi @CaptainFanZzz
When you want to use "New-AzKustoScript", you need to push your script into the Blob of the Storage Account, and then Generate SAS for the script.

Save the generated "Blob SAS Token" and "Blob SAS URL" and fill in [-scripturlsastoken], [-scripturl].

Like this:
`New-AzKustoScript -ClusterName $AzureDataExplorerClusterName -DatabaseName $AzureDataExplorerClusterDatabaseName -Name $KustoScriptName -ResourceGroupName $ResourceGroupName -ScriptUrl $BlobSASRUL -ScriptUrlSasToken $BlobSASToken`

**Comment by CaptainFanZzz** [comment]
@lijinpei2008 Thanks! It works.
