### ISSUE TITLE
How should I use service principal to search data lake store?

### ISSUE THREAD

**Issue by Yuiheart** [Azure/azure-powershell#16677]
### Description

Hi team,

I'm trying to use `Get-AzDataLakeStoreChildItem` command to search items in adls gen1 with service principal. I tried to pass the service principal as DefaultProfile but failed.

Could you please help me with how to connect to the adls with service principal?

Thanks!

### Script or Debug output

```PowerShell
Get-AzDataLakeStoreChildItem: Cannot bind parameter 'DefaultProfile'. Cannot convert the "Microsoft.Azure.Commands.ActiveDirectory.PSADServicePrincipal" value of type "Microsoft.Azure.Commands.ActiveDirectory.PSADServicePrincipal" to type "Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.5.3                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     1.3.0                 Az.DataLakeStore                    {Add-AzDataLakeStoreFirewallRule, Add-AzDataLakeS…
Script     4.3.1                 Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Exp…
```

### Error output

```PowerShell
Message        : Cannot bind parameter 'DefaultProfile'. Cannot convert the
                 "Microsoft.Azure.Commands.ActiveDirectory.PSADServicePrincipal" value of type
                 "Microsoft.Azure.Commands.ActiveDirectory.PSADServicePrincipal" to type
                 "Microsoft.Azure.Commands.Common.Authentication.Abstractions.Core.IAzureContextContainer".
StackTrace     :    at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal
                 argument, String parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo,
                 Object currentValue)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                 parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal
                 argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32
                 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
                 ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32
                 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
                    at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32
                 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidati
                 on(Collection`1 arguments)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1
                 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
                 psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzDataLakeStoreChildItem}
Line           : Get-AzDataLakeStoreChildItem -Account $Global:PostValidation.ADLSAccount -Path
                 "" -DefaultProfile $sp -Debug
Position       : At line:1 char:193
                 + … -Format 'yyyy')/$(Get-Date -Format 'MM')/" -DefaultProfile $sp -Debug
                 +                                                              ~~~
HistoryId      : 19
```

**Comment by msJinLei** [comment]
@Yuiheart  According to the error message, It seems that what you input for DefaultProfile is not the type allowed. Could you provide the cmdlets with the parameters you input to get the error messages?

**Comment by Yuiheart** [comment]
Hi @msJinLei,

`$sp = Get-AzADServicePrincipal -ApplicationId $Global:PostValidation.AppRegistrationClientID`
` $items = Get-AzDataLakeStoreChildItem -Account $Global:PostValidation.ADLSAccount -Path $entry.Value -DefaultProfile $sp`

These are the cmdlets I used to get the service principal and pass it to the DefaultProfile parameter. I learnt about that the allowed type is **IAzureContextContainer**, but wondering how to convert service principal to this type.

**Comment by Yuiheart** [comment]
Hi @msJinLei ! Gentle ping on this issue~

**Comment by msJinLei** [comment]
DefaultProfile is not used for accepting serviceprinpal. It is used to store your current login information, such as your username, tenant, subscription, etc. It is optional. Usually, you are not required to provide value for the parameter.

**Comment by dingmeng-xue** [comment]
Value of default profile is current or other context in Azure PowerShell. For instance, below code uses current context to fetch data lake store item. Please reopen this issue if there is any further question.
```
$context = Get-AzContext
Get-AzDataLakeStoreChildItem -Account test -DefaultProfile $context 
```
