### ISSUE TITLE
New-AzADAppCredential -ApplicationID broke in 5.2.0 (was working in 5.1.0)

### ISSUE THREAD

**Issue by jaromirk** [Azure/azure-powershell#16764]
### Description

Example code:

```PowerShell
$SP=New-AzADServicePrincipal -DisplayName MyServicePrincipal
        $credential = New-Object -TypeName "Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphPasswordCredential" -Property @{
            "KeyID"         = (new-guid).Guid ;
            "EndDateTime" = [DateTime]::UtcNow.AddYears(1)
        }
        $Creds=New-AzADAppCredential -PasswordCredentials $credential -ApplicationID $SP.AppID
```

```PowerShell
New-AzADAppCredential : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
At line:1 char:9
+         $Creds=New-AzADAppCredential -PasswordCredentials $credential ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-AzADAppCredential], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,New-AzADAppCredential
```

![image](https://user-images.githubusercontent.com/9829838/148212951-b62f956d-d62c-42f7-a3fe-700f056d8c02.png)

### Issue script & Debug output

```PowerShell
PSMessageDetails      : 
Exception             : System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to 
                        parameter 'ApplicationId' because it is an empty string.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                        funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
                           at 
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                        frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object 
                        dollarUnderbar, Object inputToProcess)
                           at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : 
CategoryInfo          : InvalidData: (:) [Add-AzADApplicationPassword], ParameterBindingValidationException
FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Add-AzADApplicationPassword
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at New-AzADAppCredential<Process>, C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.
                        0\MSGraph.Autorest\custom\New-AzADAppCredential.ps1: line 273
                        at New-AzADAppCredential<Process>, C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.
                        0\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1: line 2552
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.20348.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     2.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
Script     5.2.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...
```

### Error output

```PowerShell
HistoryId: 34


Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, 
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Add-AzADApplicationPassword}
Line           :                 Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\New-AzADAppCr
                 edential.ps1:273 char:65
                 + ...    Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 +                                                        ~~~~~~~~~~~~~~~~~~
HistoryId      : 34



   HistoryId: 30


Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, 
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Add-AzADApplicationPassword}
Line           :                 Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\New-AzADAppCr
                 edential.ps1:273 char:65
                 + ...    Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 +                                                        ~~~~~~~~~~~~~~~~~~
HistoryId      : 30



   HistoryId: 28


Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, 
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Add-AzADApplicationPassword}
Line           :                 Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\New-AzADAppCr
                 edential.ps1:273 char:65
                 + ...    Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 +                                                        ~~~~~~~~~~~~~~~~~~
HistoryId      : 28



   HistoryId: 24


Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, 
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {New-AzADAppCredential}
Line           :  $Creds=Get-AzADApplication -ApplicationId $SP.AppID | New-AzADAppCredential -PasswordCredentials 
                 $credential
Position       : At line:1 char:2
                 +  $Creds=Get-AzADApplication -ApplicationId $SP.AppID | New-AzADAppCre ...
                 +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 24

Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& 
                 exceptionThrown, ExecutionOptions options)
Exception      : System.Management.Automation.CmdletInvocationException
InvocationInfo : {Get-AzADApplication_List}
Line           :     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\Get-AzADAppli
                 cation.ps1:206 char:5
                 +     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 24

Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, 
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Get-AzADApplication_List}
Line           :     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\Get-AzADAppli
                 cation.ps1:206 char:5
                 +     Az.MSGraph.internal\Get-AzADApplication @PSBoundParameters
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 24

Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, 
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Add-AzADApplicationPassword}
Line           :                 Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\New-AzADAppCr
                 edential.ps1:273 char:65
                 + ...    Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 +                                                        ~~~~~~~~~~~~~~~~~~
HistoryId      : 24



   HistoryId: 23


Message        : Cannot bind argument to parameter 'ApplicationId' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, 
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Add-AzADApplicationPassword}
Line           :                 Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\5.2.0\MSGraph.Autorest\custom\New-AzADAppCr
                 edential.ps1:273 char:65
                 + ...    Az.MSGraph.internal\Add-AzADApplicationPassword @PSBoundParameters
                 +                                                        ~~~~~~~~~~~~~~~~~~
HistoryId      : 23
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into this issue.

**Comment by tldevops** [comment]
Is there an estimate for fixing this? I have the exact same issue.

**Comment by VeryEarly** [comment]
Hi @jaromirk @tldevops ,

This fix will be available early next month.
