### ISSUE TITLE
Set-AzApiManagementPolicy fails when operationId contains forward slash

### ISSUE THREAD

**Issue by gpsarkar** [Azure/azure-powershell#16772]
### Description

`Set-AzApiManagementPolicy` throws error when **operationId** contains a forward slash in it. 

This used to work with RM module `Set-AzureRmApiManagementPolicy`

### Issue script & Debug output

```PowerShell
Connect-AzAccount ....  #as usual
$context = New-AzApiManagementContext ....  #as usual
$apiId = "test-api-id" #example
$policyString = "<policies><inbound><base /></inbound><backend><base/></backend><outbound><base /></outbound><on-error><base /></on-error></policies>" # example

# NOTE: OperationId has a slash in it.
$operationId = "GET_my-api/testEndpoint"

Set-AzApiManagementPolicy `
  -Context $context `
  -ApiId $apiId `
  -OperationId $operationId `
  -Policy $policyString `
  -Format "application/vnd.ms-azure-apim.policy.raw+xml" `
  -ErrorVariable errVar `
  -ErrorAction SilentlyContinue
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.5.3                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     2.3.0                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup,…
```

### Error output

```PowerShell
HistoryId: 217

Message        : 
                 Error message: Microsoft.Azure.Management.ApiManagement.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound'
                    at Microsoft.Azure.Management.ApiManagement.ApiOperationPolicyOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String serviceName, String apiId, String operationId, PolicyContract parameters, String ifMatch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ApiManagement.ApiOperationPolicyOperationsExtensions.CreateOrUpdateAsync(IApiOperationPolicyOperations operations, String resourceGroupName, String serviceName, String apiId, String operationId, PolicyContract parameters, String ifMatch, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ApiManagement.ApiOperationPolicyOperationsExtensions.CreateOrUpdate(IApiOperationPolicyOperations operations, String resourceGroupName, String serviceName, String apiId, String operationId, PolicyContract parameters, String ifMatch)
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.PolicySetOperationLevel(PsApiManagementContext context, String policyContent, String apiId, String operationId, String contentFormat)
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.SetAzureApiManagementPolicy.ExecuteApiManagementCmdlet()
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet()
                 
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Set-AzApiManagementPolicy}
Line           :                 Set-AzApiManagementPolicy `
                 
Position       : At D:\myscript.ps1:255 char:17
                 +                 Set-AzApiManagementPolicy `
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 217


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We believe this inconsistency should be resolve by service side. I reply team member to look into it further.

**Comment by SaurabhSharma-MSFT** [comment]
@gpsarkar You not passing the correct operation id and thus you are getting error.  You need to pass Operation Id something like below  - 
![image](https://user-images.githubusercontent.com/38112130/152046940-d1dd0d9a-5af7-4794-81b0-9707a4b2ed68.png)

You can get a list of operation Ids available by your APIM by executing the below cmdlet - 
`Get-AzApiManagementOperation -Context $apimContext -ApiId $APIId `

Please let me know if you have any questions.

Thanks
Saurabh
