### ISSUE TITLE
new-azadgroup -mailenabled does not exist in v7.1.0

### ISSUE THREAD

**Issue by MikeBakerSAV** [Azure/azure-powershell#16784]
### Description

new-azadgroup -mailenabled does not exist in module version 7.1.0

https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadgroup?view=azps-7.1.0

"New-AzADGroup : A parameter cannot be found that matches parameter name 'MailEnabled'.

### Issue script & Debug output

```PowerShell
New-AzADGroup : A parameter cannot be found that matches parameter name 'MailEnabled'.
At line:1 char:131
+ ... E Azure $subname Subscription Owners and Admins" -MailEnabled $false  ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzADGroup], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.ActiveDirectory.NewAzureADGroupCommand
```

### Environment data

```PowerShell
PS C:\github_local\ce-azure-build> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\github_local\ce-azure-build> get-module az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.5.4      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     4.4.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential...}
```

### Error output

```PowerShell
HistoryId: 42


Message        : A parameter cannot be found that matches parameter name 'MailEnabled'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[]
                 pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADGroup}
Line           : New-AzADGroup -DisplayName "<name>" -description "<description>" -MailEnabled $false -SecurityEnabled
                 $true -MailNickName "NotSet" -IsAssignableToRole $true
Position       : At line:1 char:131
                 + ... <description>" -MailEnabled $false  ...
                 +                                                      ~~~~~~~~~~~~
HistoryId      : 42
```

**Comment by dingmeng-xue** [comment]
@VeryEarly, please look into this issue.

**Comment by VeryEarly** [comment]
Hi @MikeBakerSAV ,

The parameter "MailEnabled" is a switch parameter, please use it as below:

- if you do not need mail to be enabled, do not provide this parameter
- if you want the mail to be enabled, provide "-MailEnabled" (no value needed)
