### ISSUE TITLE
Set-AzVMBackupExtension and Remove-AzVMBackup throw NullReferenceException when running.

### ISSUE THREAD

**Issue by ziyuezh576** [Azure/azure-powershell#16793]
### Description

Set-AzVMBackupExtension and Remove-AzVMBackup report "Object reference not set to an instance of an object" when running.

### Issue script & Debug output

```PowerShell
PS> $DebugPreference = 'Continue'
PS> Set-AzVMBackupExtension -ResourceGroupName "ziyue-rg" -VMName "ziyuevm2" -Name "BakExt" -Tag "Backup1"
PS> Remove-AzVMBackup -ResourceGroupName "ziyue-rg" -VMName "ziyuevm" -Tag "Backup1"

DEBUG: 4:08:45 PM - SetAzureVMBackupExtension begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 4:08:45 PM - using account id 'xxx@xxx.com'...
(Omitted here...)
UserId: 'xxx@xxx.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Micro
soft.Compute/virtualMachines/ziyuevm2?$expand=instanceView&api-version=2021-07-01

Headers:
x-ms-client-request-id        : 50eb09b2-105a-4a7e-89f4-8892addad77d
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGet3Min;3996,Microsoft.Compute/LowCostGet30Min;31979
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 949a5fae-6983-4eb2-88ad-030ab885c71e
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 859f207a-3508-4ce7-9811-e4346ef08eb1
x-ms-routing-request-id       : EASTASIA:20220107T080848Z:859f207a-3508-4ce7-9811-e4346ef08eb1
X-Content-Type-Options        : nosniff
Date                          : Fri, 07 Jan 2022 08:08:48 GMT

Body:
{
  "name": "ziyuevm2",
  "id":
"/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachine
s/ziyuevm2",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "eastus",
  "properties": {
    "vmId": "acb4b8bb-d2ff-4c54-8d49-3246c0047695",
    "hardwareProfile": {
      "vmSize": "Standard_B1s"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2019-datacenter-gensecond",
        "version": "latest",
        "exactVersion": "17763.3125.2112070401"
      },
      "osDisk": {
        "osType": "Windows",
        "name": "ziyuevm2_OsDisk_1_625a1996293b4fd7947ba5bb53778ed8",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "Premium_LRS",
          "id":
"/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/disks/ziyuevm2
_OsDisk_1_625a1996293b4fd7947ba5bb53778ed8"
        },
        "deleteOption": "Detach",
        "diskSizeGB": 127
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "ziyuevm2",
      "adminUsername": "azureuser",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": true,
        "patchSettings": {
          "patchMode": "AutomaticByOS",
          "assessmentMode": "ImageDefault",
          "enableHotpatching": false
        }
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id":
"/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Network/networkInterfa
ces/ziyuevm2706"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "provisioningState": "Succeeded",
    "instanceView": {
      "computerName": "ziyuevm2",
      "osName": "Windows Server 2019 Datacenter",
      "osVersion": "10.0.17763.2366",
      "vmAgent": {
        "vmAgentVersion": "2.7.41491.1032",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Ready",
            "message": "GuestAgent is running and processing the extensions.",
            "time": "2022-01-07T16:08:05.224+08:00"
          }
        ],
        "extensionHandlers": [
          {
            "type": "Microsoft.Azure.AzureDefenderForServers.MDE.Windows",
            "typeHandlerVersion": "1.0.5.2",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready"
            }
          },
          {
            "type": "Microsoft.Compute.JsonADDomainExtension",
            "typeHandlerVersion": "1.3.6",
            "status": {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Ready"
            }
          }
        ]
      },
      "disks": [
        {
          "name": "ziyuevm2_OsDisk_1_625a1996293b4fd7947ba5bb53778ed8",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2022-01-07T14:43:07.4945997+08:00"
            }
          ]
        }
      ],
      "bootDiagnostics": {},
      "extensions": [
        {
          "name": "JsonADDomainExtension",
          "type": "Microsoft.Compute.JsonADDomainExtension",
          "typeHandlerVersion": "1.3.6",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "Join completed for Workgroup 'ahh.com'"
            }
          ]
        },
        {
          "name": "MDE.Windows",
          "type": "Microsoft.Azure.AzureDefenderForServers.MDE.Windows",
          "typeHandlerVersion": "1.0.5.2",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "message": "{\r\n    \"azureResourceId\":
\"/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachin
es/ziyuevm2\",\r\n    \"securityWorkspaceId\":  \"11111111-1111-1111-1111-111111111111\",\r\n    \"osDetails\":  {\r\n
                     \"osMetadata\":  {\r\n                                         \"majorVersion\":  10,\r\n
                                \"minorVersion\":  0,\r\n                                         \"buildVersion\":
17763,\r\n                                         \"productType\":  3,\r\n
\"operatingSystemSku\":  8\r\n                                     },\r\n                      \"osName\":  \"Microsoft
 Windows Server 2019 Datacenter\"\r\n                  },\r\n    \"onboardingPackageOperationResultCode\":
\"Success\",\r\n    \"machineId\":  \"036c6b7f7482bd51658b4545646153177ce94e14\"\r\n}",
              "time": "2022-01-07T15:33:54+08:00"
            }
          ]
        }
      ],
      "hyperVGeneration": "V2",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2022-01-07T15:34:08.1653726+08:00"
        },
        {
          "code": "PowerState/running",
          "level": "Info",
          "displayStatus": "VM running"
        }
      ]
    }
  },
  "resources": [
    {
      "name": "JsonADDomainExtension",
      "id":
"/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachine
s/ziyuevm2/extensions/JsonADDomainExtension",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "eastus",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "provisioningState": "Succeeded",
        "publisher": "Microsoft.Compute",
        "type": "JsonADDomainExtension",
        "typeHandlerVersion": "1.3",
        "settings": {
          "Restart": false,
          "Name": "ahh.com"
        }
      }
    },
    {
      "name": "MDE.Windows",
      "id":
"/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachine
s/ziyuevm2/extensions/MDE.Windows",
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "eastus",
      "properties": {
        "autoUpgradeMinorVersion": true,
        "forceUpdateTag": "b5ca266d-5853-4b4c-a9a0-5087cd8a7118",
        "provisioningState": "Succeeded",
        "publisher": "Microsoft.Azure.AzureDefenderForServers",
        "type": "MDE.Windows",
        "typeHandlerVersion": "1.0",
        "settings": {
          "azureResourceId":
"/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ZIYUE-RG/providers/Microsoft.Compute/virtualMachine
s/ziyuevm2",
          "forceReOnboarding": false,
          "vNextEnabled": false
        }
      }
    }
  ]
}

Set-AzVMBackupExtension : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-AzVMBackupExtension -ResourceGroupName "ziyue-rg" -VMName "ziyuev ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzVMBackupExtension], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Extension.AzureDiskEncryption.SetAzureVMBackupExtension

DEBUG: AzureQoSEvent: Module: Az.Compute:4.21.0; CommandName: Set-AzVMBackupExtension; PSVersion: 5.1.19041.1320;
IsSuccess: False; Duration: 00:00:03.6286338; Exception: Object reference not set to an instance of an object.;
DEBUG: Finish sending metric.
DEBUG: 4:08:54 PM - SetAzureVMBackupExtension end processing.

-----------------------------------------------------------------------------

DEBUG: Registering Az shared AssemblyLoadContext for path: 'C:\Program Files\WindowsPowerShell\Modules\Az.Accounts\2.7.0\StartupScripts\..\AzSharedAlcAssemblies'.
DEBUG: AssemblyLoadContext registered.
DEBUG: Registering module AssemblyLoadContext for path: 'C:\Program Files\WindowsPowerShell\Modules\Az.Compute\4.21.0\PostImportScripts\..\ModuleAlcAssemblies'.
DEBUG: AssemblyLoadContext registered.
DEBUG: Sought all Az modules and got latest version 7.0.0
DEBUG: 5:27:06 PM - RemoveAzureVMBackup begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 5:27:06 PM - using account id 'xxx@xxx.com'...
(Omitted here...)
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', UserId: 'xxx@xxx.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachines/ziyuevm?$expand=instanceView&api-version=2021-07-01

Headers:
x-ms-client-request-id        : 7ddc7cb4-b05c-4998-9e2d-286a9d76d46c
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGet3Min;3991,Microsoft.Compute/LowCostGet30Min;31974
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : c4497f66-8574-4a9f-afd6-ecf9c2312a1e
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 194fc2d0-9d10-463e-89c8-344d0c21eae6
x-ms-routing-request-id       : EASTASIA:20220107T092710Z:194fc2d0-9d10-463e-89c8-344d0c21eae6
X-Content-Type-Options        : nosniff
Date                          : Fri, 07 Jan 2022 09:27:09 GMT

Body:
{
  "name": "ziyuevm",
  "id": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachines/ziyuevm",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "eastus",
  "properties": {
    "vmId": "cdd3ec68-162f-4075-bd68-87e499231ba6",
    "hardwareProfile": {
      "vmSize": "Standard_B1s"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "18_04-lts-gen2",
        "version": "latest",
        "exactVersion": "18.04.202201060"
      },
      "osDisk": {
        "osType": "Linux",
        "name": "ziyuevm_disk1_601c50bfa8d248cb815b2b5050095335",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "Premium_LRS",
          "id": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/disks/ziyuevm_disk1_601c50bfa8d248cb815b2b5050095335"
        },
        "deleteOption": "Detach",
        "diskSizeGB": 30
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "ziyuevm",
      "adminUsername": "azureuser",
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "ssh": {
          "publicKeys": [
            {
              "path": "/home/azureuser/.ssh/authorized_keys",
              "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCaGfduaEHewIFAVh7GEq+5HPgJ\r\nQBqBhfDM0LBokJYqfPCU8WREL46MgokOpQteB+DvbspPKZk36o2/3H1/lMZgki6T\r\nMIRqVXWvY0q4EVbPUlcyY8e4Pnrp7PKDboiY3cHLC1WEc/qLa7tsF37XEdlAtkve\r\nhEjxaPVNr+oUTfytLPsLuWMLcp7Pr2utxxIirDF0tvnSltaZKHZPaBsODH0yo3aP\r\n5WY2YsVf6gV9GW+y/xLNu3ZfRbHZ1/RrW9jq0a2Rs9Uxrhau8cAUvSqjc9+bEsFY\r\nt02gYXOlLP90nXmSy+teOTEEcg90oWKztySdb4KJcfUIn/ChY8q0+Mu+R+QUVbk2\r\nD72BgpjtFRxyMNpAy3iOeqRlcSQ+5Uag0DfvC+IqXZqOjuTOoGX1pukoim/42hY0\r\n0IHTRr/A1djxAmovM7ZdZjuMXxNsYPbg/G2zpOkg4rfK8zWGTpNP/f2gFTE8DGJX\r\nsflLFtEl+AuJYG0d3oOVnEQeV4WTdvdZpSS1Jek= generated-by-azure\r\n"
            }
          ]
        },
        "provisionVMAgent": true,
        "patchSettings": {
          "patchMode": "ImageDefault",
          "assessmentMode": "ImageDefault"
        }
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Network/networkInterfaces/ziyuevm708"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "provisioningState": "Succeeded",
    "instanceView": {
      "computerName": "ziyuevm",
      "osName": "ubuntu",
      "osVersion": "18.04",
      "vmAgent": {
        "vmAgentVersion": "2.6.0.2",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Ready",
            "message": "Guest Agent is running",
            "time": "2022-01-07T17:26:16+08:00"
          }
        ],
        "extensionHandlers": []
      },
      "disks": [
        {
          "name": "ziyuevm_disk1_601c50bfa8d248cb815b2b5050095335",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2022-01-07T14:33:57.507129+08:00"
            }
          ]
        }
      ],
      "bootDiagnostics": {},
      "hyperVGeneration": "V2",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2022-01-07T14:37:39.0708836+08:00"
        },
        {
          "code": "PowerState/running",
          "level": "Info",
          "displayStatus": "VM running"
        }
      ]
    }
  }
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachines/ziyuevm?$expand=instanceView&api-version=2021-07-01

Headers:
x-ms-client-request-id        : 7ddc7cb4-b05c-4998-9e2d-286a9d76d46c
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGet3Min;3990,Microsoft.Compute/LowCostGet30Min;31973
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : e76dce10-6c03-48fc-bc7f-e89a94d30c55
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : c18a99da-a157-481f-be0d-2af563a46cea
x-ms-routing-request-id       : EASTASIA:20220107T092710Z:c18a99da-a157-481f-be0d-2af563a46cea
X-Content-Type-Options        : nosniff
Date                          : Fri, 07 Jan 2022 09:27:10 GMT

Body:
{
  "name": "ziyuevm",
  "id": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/virtualMachines/ziyuevm",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "eastus",
  "properties": {
    "vmId": "cdd3ec68-162f-4075-bd68-87e499231ba6",
    "hardwareProfile": {
      "vmSize": "Standard_B1s"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "18_04-lts-gen2",
        "version": "latest",
        "exactVersion": "18.04.202201060"
      },
      "osDisk": {
        "osType": "Linux",
        "name": "ziyuevm_disk1_601c50bfa8d248cb815b2b5050095335",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "managedDisk": {
          "storageAccountType": "Premium_LRS",
          "id": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Compute/disks/ziyuevm_disk1_601c50bfa8d248cb815b2b5050095335"
        },
        "deleteOption": "Detach",
        "diskSizeGB": 30
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "ziyuevm",
      "adminUsername": "azureuser",
      "linuxConfiguration": {
        "disablePasswordAuthentication": true,
        "ssh": {
          "publicKeys": [
            {
              "path": "/home/azureuser/.ssh/authorized_keys",
              "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCaGfduaEHewIFAVh7GEq+5HPgJ\r\nQBqBhfDM0LBokJYqfPCU8WREL46MgokOpQteB+DvbspPKZk36o2/3H1/lMZgki6T\r\nMIRqVXWvY0q4EVbPUlcyY8e4Pnrp7PKDboiY3cHLC1WEc/qLa7tsF37XEdlAtkve\r\nhEjxaPVNr+oUTfytLPsLuWMLcp7Pr2utxxIirDF0tvnSltaZKHZPaBsODH0yo3aP\r\n5WY2YsVf6gV9GW+y/xLNu3ZfRbHZ1/RrW9jq0a2Rs9Uxrhau8cAUvSqjc9+bEsFY\r\nt02gYXOlLP90nXmSy+teOTEEcg90oWKztySdb4KJcfUIn/ChY8q0+Mu+R+QUVbk2\r\nD72BgpjtFRxyMNpAy3iOeqRlcSQ+5Uag0DfvC+IqXZqOjuTOoGX1pukoim/42hY0\r\n0IHTRr/A1djxAmovM7ZdZjuMXxNsYPbg/G2zpOkg4rfK8zWGTpNP/f2gFTE8DGJX\r\nsflLFtEl+AuJYG0d3oOVnEQeV4WTdvdZpSS1Jek= generated-by-azure\r\n"
            }
          ]
        },
        "provisionVMAgent": true,
        "patchSettings": {
          "patchMode": "ImageDefault",
          "assessmentMode": "ImageDefault"
        }
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/ziyue-rg/providers/Microsoft.Network/networkInterfaces/ziyuevm708"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true
      }
    },
    "provisioningState": "Succeeded",
    "instanceView": {
      "computerName": "ziyuevm",
      "osName": "ubuntu",
      "osVersion": "18.04",
      "vmAgent": {
        "vmAgentVersion": "2.6.0.2",
        "statuses": [
          {
            "code": "ProvisioningState/succeeded",
            "level": "Info",
            "displayStatus": "Ready",
            "message": "Guest Agent is running",
            "time": "2022-01-07T17:26:16+08:00"
          }
        ],
        "extensionHandlers": []
      },
      "disks": [
        {
          "name": "ziyuevm_disk1_601c50bfa8d248cb815b2b5050095335",
          "statuses": [
            {
              "code": "ProvisioningState/succeeded",
              "level": "Info",
              "displayStatus": "Provisioning succeeded",
              "time": "2022-01-07T14:33:57.507129+08:00"
            }
          ]
        }
      ],
      "bootDiagnostics": {},
      "hyperVGeneration": "V2",
      "statuses": [
        {
          "code": "ProvisioningState/succeeded",
          "level": "Info",
          "displayStatus": "Provisioning succeeded",
          "time": "2022-01-07T14:37:39.0708836+08:00"
        },
        {
          "code": "PowerState/running",
          "level": "Info",
          "displayStatus": "VM running"
        }
      ]
    }
  }
}


DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx@xxx.com', environment: 'AzureCloud', tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: 5:27:11 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx@xxx.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(d65be23c-8be4-424c-b622-11be9ea42d76)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - d65be23c-8be4-424c-b622-11be9ea42d76

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] Access token is not expired. Returning the found cache entry. [Current time (01/07/2022 09:27:11) - Expiration Time (01/07/2022 10:18:20 +00:00) - Extended Expiration Time (01/07/2022 10:18:20 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.19044 [01/07/2022 09:27:11 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 01/07/2022 10:18:20 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-01-07T10:18:20.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', UserId: 'xxx@xxx.com'
Remove-AzVMBackup: Object reference not set to an instance of an object.
DEBUG: AzureQoSEvent: Module: Az.Compute:4.21.0; CommandName: Remove-AzVMBackup; PSVersion: 7.2.1; IsSuccess: False; Duration: 00:00:05.0205312; Exception: Object reference not set to an instance of an object.;
DEBUG: Finish sending metric.
DEBUG: 5:27:15 PM - RemoveAzureVMBackup end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     4.21.0     Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk...}
```

### Error output

```PowerShell
HistoryId: 39


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Compute.Extension.AzureVMBackup.AzureVMBackupExtensionUtil.GetDiskBlobUris(VirtualMachine virtualMachineResponse)
                    at Microsoft.Azure.Commands.Compute.Extension.AzureVMBackup.AzureVMBackupExtensionUtil.RemoveSnapshot(AzureVMBackupConfig vmConfig, String snapshotTag, VirtualMachineExtensionBaseCmdlet
                 virtualMachineExtensionBaseCmdlet)
                    at Microsoft.Azure.Commands.Compute.Extension.AzureVMBackup.RemoveAzureVMBackup.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Remove-AzVMBackup}
Line           : Remove-AzVMBackup -ResourceGroupName "ziyue-rg" -VMName "ziyuevm" -Tag "Backup1"
Position       : At line:1 char:1
                 + Remove-AzVMBackup -ResourceGroupName "ziyue-rg" -VMName "ziyuevm" -Ta ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 39



   HistoryId: 35


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Compute.Extension.AzureVMBackup.AzureVMBackupExtensionUtil.GetDiskBlobUris(VirtualMachine virtualMachineResponse)
                    at Microsoft.Azure.Commands.Compute.Extension.AzureVMBackup.AzureVMBackupExtensionUtil.CreateSnapshotForDisks(AzureVMBackupConfig vmConfig, String snapshotTag, VirtualMachineExtensionBaseCmdlet
                 virtualMachineExtensionBaseCmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Set-AzVMBackupExtension}
Line           : Set-AzVMBackupExtension -ResourceGroupName "ziyue-rg" -VMName "ziyuevm2" -Name "BakExt" -Tag "Backup1"
Position       : At line:1 char:1
                 + Set-AzVMBackupExtension -ResourceGroupName "ziyue-rg" -VMName "ziyuev ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 35
```

**Comment by jaylabell** [comment]
Taking a look into this issue.

**Comment by jaylabell** [comment]
Thanks for reporting, working to resolve this issue.

**Comment by jaylabell** [comment]
@ziyuezh576 are you still experiencing this issue?

**Comment by jaylabell** [comment]
@ziyuezh576  I assume that you are no longer experiencing this issue. Please re-open if you have any additional questions. Closing for now.
