### ISSUE TITLE
Get-AzAccessToken -ResourceTypeName MSGraph returns expired access token

### ISSUE THREAD

**Issue by jelleholtkamp** [Azure/azure-powershell#16999]
### Description

Get-AzAccessToken -ResourceTypeName MSGraph returns a token that is immediately expired. Same thing happens with Get-AzAccessToken -ResourceUrl 'https://graph.microsoft.com/'

### Issue script & Debug output

```PowerShell
$context = Get-AzContext
$graphToken = Get-AzAccessToken -ResourceUrl 'https://graph.microsoft.com/'
$session = Connect-AzureAD -AadAccessToken $graphToken.Token -AccountId $context.Account.Id -TenantId $context.tenant.id -Verbos
Get-AzureAdUser
DEBUG: 16:04:05 - GetAzureRMContextCommand end processing.
DEBUG: 16:04:05 - GetAzureRmAccessTokenCommand begin processing with ParameterSet 'ResourceUrl'.
DEBUG: 16:04:05 - using account id '***'...
DEBUG: 16:04:05 - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'***', TenantId:'***', Scopes:'https://graph.microsoft.com//.default', AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] MSAL MSAL.Desktop with assembly version '4.30.1.0'. CorrelationId(***)
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.microsoft.com//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - ***

DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] === Token Acquisition (ClientCredentialRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Resolving authority endpoints... Already resolved? - TRUE
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Resolving authority endpoints... Already resolved? - TRUE
DEBUG: Request [***] POST https://login.microsoftonline.com/***/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Content-Type:REDACTED
client assembly: Azure.Identity
DEBUG: Response [***] 200 OK (00.1s)
Pragma:REDACTED
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
client-request-id:REDACTED
x-ms-request-id:REDACTED
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
Cache-Control:REDACTED
P3P:REDACTED
Set-Cookie:REDACTED
Date:REDACTED
Content-Length:REDACTED
Content-Type:REDACTED
Expires:REDACTED

DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] ScopeSet was missing from the token response, so using developer provided scopes in the result.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Checking client info returned from the server..
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Saving Token Response to cache..
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] ID Token not present in response.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Saving AT in cache and removing overlapping ATs...
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Looking for scopes for the authority in the cache which intersect with https://graph.microsoft.com//.default
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Intersecting scope entries count - 0
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.Desktop Windows 10 Pro [02/02/2022 15:04:05 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 02/02/2022 16:04:04 +00:00 and Scopes https://graph.microsoft.com//.default
DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://graph.microsoft.com//.default ] ParentRequestId:  ExpiresOn: 2022-02-02T16:04:04.0000000+00:00     
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.0; CommandName: Get-AzAccessToken; PSVersion: 5.1.19041.1320; IsSuccess: True; Duration: 00:00:00.2074713
DEBUG: Finish sending metric.
DEBUG: 16:04:06 - GetAzureRmAccessTokenCommand end processing.
VERBOSE: Performing the operation "Connect-AzureAD" on target "Establishing a PowerShell session connected to {0} environment.".
Get-AzureAdUser : Error occurred while executing GetUsers 
Code: Authentication_ExpiredToken
Message: Your access token has expired. Please renew it before submitting the request.
HttpStatusCode: Unauthorized
HttpStatusDescription: Unauthorized
HttpResponseStatus: Completed
At line:4 char:5
+     Get-AzureAdUser
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADUser], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.AzureAD16.Client.ApiException,Microsoft.Open.AzureAD16.PowerShell.GetUser
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1320
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1320
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.7.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}
Script     5.1.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
Binary     2.0.2.140  AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-Azur...
```

### Error output

```PowerShell
HistoryId: 158


Message        : Error occurred while executing GetUsers 
                 Code: Authentication_ExpiredToken
                 Message: Your access token has expired. Please renew it before submitting the request.
                 HttpStatusCode: Unauthorized
                 HttpStatusDescription: Unauthorized
                 HttpResponseStatus: Completed
                 
StackTrace     :    at Microsoft.Open.AzureAD16.Client.Configuration.<>c.<.cctor>b__47_0(String methodName, IRestResponse response) in X:\bt\1218881\repo\src\dev\Powe
                 rShell.V2\AzureAD16.Client\Client\Configuration.cs:line 188
                    at Microsoft.Open.AzureAD16.Api.UserApi.GetUsersWithHttpInfo(String tenantId, String authorization, String cmdletName, String clientRequestId, Str
                 ing apiVersion, String objectId, Nullable`1 all, Nullable`1 top, String skiptoken, String filter, String orderby) in X:\bt\1218881\repo\src\dev\Power
                 Shell.V2\AzureAD16.Client\Api\UserApi.cs:line 4613
                    at Microsoft.Open.AzureAD16.PowerShell.GetUsers.ProcessRecord() in X:\bt\1218881\repo\src\dev\PowerShell.V2\AzureAD16.PowerShell\AzureAD16.PowerSh
                 ell.AutoGen\API\UserApi.cs:line 2044
                    at System.Management.Automation.Cmdlet.GetResults()
                    at System.Management.Automation.Cmdlet.<Invoke>d__40.MoveNext()
                    at System.Management.Automation.MshCommandRuntime._WriteObjectsSkipAllowCheck(Object sendToPipeline)
                    at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
                    at System.Management.Automation.MshCommandRuntime.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
                    at System.Management.Automation.Cmdlet.WriteObject(Object sendToPipeline, Boolean enumerateCollection)
                    at Microsoft.Open.AzureAD16.PowerShell.GetUser.ProcessRecord() in X:\bt\1218881\repo\src\dev\PowerShell.V2\AzureAD16.PowerShell\AzureAD16.PowerShe
                 ll.AutoGen\API\UserApi.cs:line 258
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : Microsoft.Open.AzureAD16.Client.ApiException
InvocationInfo : {Get-AzureADUser}
Line           :     Get-AzureAdUser
Position       : At line:3 char:5
                 +     Get-AzureAdUser
                 +     ~~~~~~~~~~~~~~~
HistoryId      : 158
```

**Comment by jelleholtkamp** [comment]
Some additional information: I use a service principal to connect using Connect-AzAccount.

**Comment by jelleholtkamp** [comment]
I figured out I was doing something wrong. I was using an MS Graph token as input for the -AadAccessToken parameter for the Connect-AzureAd cmdlet. It produced no error, but what I needed to do is generate an Azure AD graph token and use it as input for the -AadAccessToken parameter, and generate an MS graph access token and use it as input for the -MsAccessToken parameter.
