### ISSUE TITLE
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'ApplicationId'.

### ISSUE THREAD

**Issue by AjKundnani** [Azure/azure-powershell#17054]
### Description

When running cmdlet **New-AzADServicePrincipal** with Az.Resource Module version 5.3.0, updated from 5.2.0, I keep getting below error:
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'ApplicationId'.

This happens whether I am trying with -ApplicationID Parameter or -ApplicationObject parameter.

### Issue script & Debug output

```PowerShell
PS C:\Windows\System32> $DebugPreference = 'Continue'
PS C:\Windows\System32> New-AzADServicePrincipal -ApplicationId 358d5609-69ba-44f7-b799-bd1c0150210a
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'ApplicationId'.
PS C:\Windows\System32>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     5.3.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
DEBUG: 1:23:03 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 1:23:03 PM - using account id 'ajay.kundnani@outlook.com'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 8

Message        : A parameter cannot be found that matches parameter name 'ApplicationId'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters

Position       : At C:\Users\mis-sa-locadmin\Documents\PowerShell\Modules\Az.Resources\5.3.0\MSGraph.Autorest\custom\New-AzADServicePrincipal.ps1:760 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 8


   HistoryId: 5

Message        : A parameter cannot be found that matches parameter name 'ApplicationId'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters

Position       : At C:\Users\mis-sa-locadmin\Documents\PowerShell\Modules\Az.Resources\5.3.0\MSGraph.Autorest\custom\New-AzADServicePrincipal.ps1:760 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 5


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.1; CommandName: Resolve-AzError; PSVersion: 7.2.1; IsSuccess: True; Duration: 00:00:00.1275089
DEBUG: Finish sending metric.
DEBUG: 1:23:03 PM - ResolveError end processing.
```

**Comment by tldevops** [comment]
I'm experiencing the same issue with 5.3.0 of Az.Resources.

**Comment by matsest** [comment]
Related to #17040

**Comment by jrdnbradford** [comment]
I'm experiencing the same issue with `Az.Resources 5.3.0` except with the `CertValue` parameter instead of `ApplicationId`. I can file a separate issue if necessary.

**Comment by larsvillaume** [comment]
same here issue here with 5.3.0 of Az.Resources.

**Comment by VeryEarly** [comment]
Hi @jrdnbradford @larsvillaume @tldevops ,

Please find the hotfix https://www.powershellgallery.com/packages/Az.Resources/5.3.1,
Thanks for reporting.

**Comment by felickz** [comment]
Holy cow did i jump down the rabbit hole by updating Az modules :(  

Similar but different - is ROLE now deprecated?  Still showing in docs: https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azadserviceprincipal?view=azps-7.2.0

`New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'Role'.`

**Comment by dcaro** [comment]
@felickz the '-Role' parameter is still present and should work in any parameter set. 
For example: `New-AzADServicePrincipal -DisplayName 'myserviceprincipal' -Role Reader`
Please make sure that you have Az.Accounts v2.7.2 and Az.Resources 5.3.1

**Comment by felickz** [comment]
> @felickz the '-Role' parameter is still present and should work in any parameter set. For example: `New-AzADServicePrincipal -DisplayName 'myserviceprincipal' -Role Reader` Please make sure that you have Az.Accounts v2.7.2 and Az.Resources 5.3.1

thanks 5.3.0 to 5.3.1 was issue for me there

**Comment by felickz** [comment]
> @felickz the '-Role' parameter is still present and should work in any parameter set. For example: `New-AzADServicePrincipal -DisplayName 'myserviceprincipal' -Role Reader` Please make sure that you have Az.Accounts v2.7.2 and Az.Resources 5.3.1

Thanks, i dont know how to powershell .. this was my issue: 

```powershell
-Role $null
```

**Comment by dcaro** [comment]
The parameter is optional (marked between [] in the doc), if the role is not needed, you can omit the parameter in the command.

**Comment by jrdnbradford** [comment]
I'm still having issues with the `CertValue` parameter:
```powershell
PS C:\> $Cert = New-SelfSignedCertificate -CertStoreLocation "cert:\LocalMachine\my" -Subject "CN=CertSubject" -KeySpec KeyExchange -FriendlyName "Friendly" -NotAfter (Get-Date).AddDays(20)
PS C:\> $KeyValue = [System.Convert]::ToBase64String($Cert.GetRawCertData())
PS C:\> $ServicePrincipal = New-AzADServicePrincipal -DisplayName ServicePrincipalDisplayName -CertValue $KeyValue -EndDate $Cert.NotAfter -StartDate $Cert.NotBefore

New-AzADServicePrincipal : A parameter cannot be found that matches parameter name 'CertValue'.
At line:1 char:1
+ $ServicePrincipal = New-AzADServicePrincipal -DisplayName ServicePrin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzADServicePrincipal], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-AzADServicePrincipal
```
## Versions
```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.2268
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2268
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PS C:\> Get-Module -Name Az.Resources
ModuleType Version    Name                              
---------- -------    ----                         
Script     5.3.1      Az.Resources         


PS C:\> Get-Module -Name Az.Accounts
ModuleType Version    Name           
---------- -------    ----                     
Script     2.7.2      Az.Accounts                        
```

## Error Output
```powershell
PS C:\> Resolve-AzError

   HistoryId: 18


Message        : A parameter cannot be found that matches parameter name 'CertValue'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar,
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters

Position       : At C:\Users\user\Documents\WindowsPowerShell\Modules\Az.Resources\5.3.1\MSGraph.Autorest\custom\
                 New-AzADServicePrincipal.ps1:763 char:56
                 + ... $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                        ~~~~~~~~~~~~~~~~~~
HistoryId      : 18
```

**Comment by daveops1** [comment]
Will this also get ported to the Azure Cloud shell as well?

**Comment by francisferreira** [comment]
Same question as @daveops1 here... The fix is not very helpful if it is not ported to Azure Cloud Shell.

**Comment by VeryEarly** [comment]
> 

Hi @jrdnbradford 

The above Az.Resources 5.3.1 fixed the reported issue only, 
However the CertValue parameter was fixed already and will be available on 2022-03-01.

Sorry for the inconvenience.

**Comment by jrdnbradford** [comment]
No worries, thanks for the info!

**Comment by gump0882** [comment]
The issue continues to torment in 5.4.0

<img width="629" alt="image" src="https://user-images.githubusercontent.com/100766641/156539387-135e2fbd-2483-4dfd-8ec3-1a09d04b4bed.png">
