### ISSUE TITLE
Cannot set 'accessTokenAcceptedVersion' for app registration

### ISSUE THREAD

**Issue by vexingpos** [Azure/azure-powershell#17090]
### Description

I am trying to use PowerShell to configure the `accessTokenAcceptedVersion` property of my app registration but not able to.

# Error
````
Update-AzADApplication_UpdateExpanded: /home/XXX/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/Update-AzADApplication.ps1:549
Line |
 549 |      Az.MSGraph.internal\Update-AzADApplication @PSBoundParameters
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | An item with the same key has already been added. Key: requestedAccessTokenVersion
````

### Issue script & Debug output

```PowerShell
$DebugPreference='Continue'

$name = "foobar"

$appReg = New-AzADApplication -DisplayName $name
$sp = New-AzADServicePrincipal -ApplicationId $appReg.AppId
 
$preGeneratedApiConfig = @{
  "requestedAccessTokenVersion" = 2
}

Update-AzADApplication -ObjectId (Get-AzADApplication -DisplayName $name).Id -Api $preGeneratedApiConfig
```

### Environment data

```PowerShell
PS /home/XXX> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.4.0-1069-azure #72~18.04.1-Ubuntu SMP Mon Feb 7 11:12:24 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS /home/XXX> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.2                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.23.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     4.14.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGate…
Script     5.3.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     4.2.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Clos…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectory…
Script     0.9.3                 AzurePSDrive

PS /home/XXX>
```

### Error output

```PowerShell
PS /home/XXX> Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 1

Message        : An item with the same key has already been added. Key: requestedAccessTokenVersion
StackTrace     :    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Runtime.Json.JsonObject.Add(String name, JsonNode value)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Runtime.Extensions.AddIf[T](T value, String serializedName, Action`2 addMethod)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphApiApplication.ToJson(JsonObject container, SerializationMode serializationMode)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphApplication.ToJson(JsonObject container, SerializationMode serializationMode)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ApplicationsApplicationUpdateApplication(String applicationId, IMicrosoftGraphApplication body, Func`2
                 onNoContent, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.UpdateAzADApplication_UpdateExpanded.ProcessRecordAsync()
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.UpdateAzADApplication_UpdateExpanded.ProcessRecordAsync()
Exception      : System.ArgumentException
InvocationInfo : {Update-AzADApplication_UpdateExpanded}
Line           :     Az.MSGraph.internal\Update-AzADApplication @PSBoundParameters

Position       : At /home/XXX/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/Update-AzADApplication.ps1:549 char:5
                 +     Az.MSGraph.internal\Update-AzADApplication @PSBoundParameters
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.


PS /home/XXX>
```

**Comment by dingmeng-xue** [comment]
Hi @vexingpos , the service doesn't support that property. https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/v1.0/Applications.yml 
Could you check further?

**Comment by vexingpos** [comment]
Hi @dingmeng-xue 

The property is called `requestedAccessTokenVersion` and is defined here:

https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/openApiDocs/v1.0/Applications.yml#L7418

**Comment by dingmeng-xue** [comment]
The inconsistency between Portal and other client tools is known problem. Sometime it's really confusing user. Azure PowerShell respects swagger definition and ensure consistency with other client tools. 

Once you use `requestedAccessTokenVersion`, does it work now?

**Comment by vexingpos** [comment]
Error messages for each property:

`requestedAccessTokenVersion` ➡️ `An item with the same key has already been added. Key: requestedAccessTokenVersion`

`accessTokenAcceptedVersion` ➡️`Expected property 'accessTokenAcceptedVersion' is not present on resource of type 'ApiApplication'`

**Comment by dingmeng-xue** [comment]
HI Vexingpos, is there any detailed doc about `requestedAccessTokenVersion`? Couple you share us debug message? You can turn on it via `$DebugPreference = "Continue"`

**Comment by vexingpos** [comment]
Hi @dingmeng-xue 

`$DebugPreference = "Continue"` doesn't do anything. 

If you look at my original post, my repro steps include the Debug variable, but the output when I run the command is the error I posted originally. 

Here is some info from the MS Graph docs about the `requestedAccessTokenVersion` property:

https://docs.microsoft.com/en-us/graph/api/resources/apiapplication?view=graph-rest-1.0

**Comment by Thaval** [comment]
Well.. im facing a problem where I want to change the authentication (because the default changed?) and run az rest PATCH with `requestedAccessTokenVersion`. It does not change the `accessTokenAcceptedVersion`, it remains "null".
Calling it like this in powershell 7:
`az rest --method PATCH --uri https://graph.microsoft.com/v1.0/applications/$objectId --headers Content-Type="application/json" --body '{"api":{"requestedAccessTokenVersion": "1"}}'`
Doesn't throw an error, but also doesn't change anything.

**Comment by dingmeng-xue** [comment]
Thanks @vexingpos . `apiApplication` resource page is a little weird to me. I cannot get its parent resource from TOC on left panel. It seems an orphan page. Azure PowerShell supports [application](https://learn.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0) and [service principal](https://learn.microsoft.com/en-us/graph/api/resources/serviceprincipal?view=graph-rest-1.0). I believe apiApplication is different resource type from them.
