### ISSUE TITLE
Get-AzRestorePointCollection should return the list of restore points inside it

### ISSUE THREAD

**Issue by dikethir** [Azure/azure-powershell#17236]
### Description

Problem: I have 3 RestorePoints created inside my RestorePointCollection however, Get-AzRestorePointCollection is returning empty list for RestorePoints. 

Expected results: Get-AzRestorePointCollection should return all the RestorePoints under it.

### Issue script & Debug output

```PowerShell
Get-AzRestorePointCollection -ResourceGroupName "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1"

DEBUG: 5:43:03 AM - GetAzureRestorePointCollection begin processing with ParameterSet 'DefaultParameter'.
DEBUG: 5:43:03 AM - using account id 'MSI@50342'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: 'e4623817-ee7d-4903-aa9b-9635e7837726'
DEBUG: 5:43:03 AM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'e4623817-ee7d-4903-aa9b-9635e7837726', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId: 
DEBUG: Request [d7247264-cfc1-48c0-9541-ea3ff3893d36] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Content-Type:REDACTED
client assembly: Azure.Identity
DEBUG: Response [d7247264-cfc1-48c0-9541-ea3ff3893d36] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:REDACTED
Date:REDACTED
Connection:REDACTED
Content-Type:REDACTED
Content-Length:REDACTED

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  ExpiresOn: 2022-02-23T06:36:01.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'e4623817-ee7d-4903-aa9b-9635e7837726', UserId: 'MSI@50342'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/fa926218-30ed-460a-82d0-f6eb3b9b2a90/resourceGroups/RPC-Public-Preview/providers/Microsoft.Compute/restorePointCollections/RPC-PP-SourceRPC-1?api-version=2021-07-01

Headers:
x-ms-client-request-id        : 8f39e064-3a9e-4948-91cb-2f5df7274d62
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGetRestorePoint3Min;498,Microsoft.Compute/LowCostGetRestorePoint30Min;2494
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 98c34b20-d34c-4097-b6bd-1dcb99eea274
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : e1d6f96c-9cf5-41eb-bbbe-0d8121d92397
x-ms-routing-request-id       : WESTINDIA:20220223T054304Z:e1d6f96c-9cf5-41eb-bbbe-0d8121d92397
X-Content-Type-Options        : nosniff
Date                          : Wed, 23 Feb 2022 05:43:03 GMT

Body:
{
  "name": "RPC-PP-SourceRPC-1",
  "id": "/subscriptions/fa926218-30ed-460a-82d0-f6eb3b9b2a90/resourceGroups/RPC-Public-Preview/providers/Microsoft.Compute/restorePointCollections/RPC-PP-SourceRPC-1",
  "type": "Microsoft.Compute/restorePointCollections",
  "location": "centraluseuap",
  "tags": {
    "department": "public preview testing"
  },
  "properties": {
    "source": {
      "location": "CentralUSEUAP",
      "id": "/subscriptions/fa926218-30ed-460a-82d0-f6eb3b9b2a90/resourceGroups/RPC-Public-Preview/providers/Microsoft.Compute/virtualMachines/RPC-PP-Test-VM-1"
    },
    "restorePointCollectionId": "c8a745b4-d017-410a-9a79-06d43fd1c45b",
    "provisioningState": "Succeeded"
  }
}



DEBUG: AzureQoSEvent: Module: Az.Compute:4.23.0; CommandName: Get-AzRestorePointCollection; PSVersion: 7.2.1; IsSuccess: True; Duration: 00:00:00.3521953
DEBUG: Finish sending metric.
DEBUG: 5:43:04 AM - GetAzureRestorePointCollection end processing.
Source                                                                           ProvisioningState RestorePointCollectionId             RestorePoints
------                                                                           ----------------- ------------------------             -------------
Microsoft.Azure.Management.Compute.Models.RestorePointCollectionSourceProperties Succeeded         c8a745b4-d017-410a-9a79-06d43fd1c45b {}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.4.0-1070-azure #73~18.04.1-Ubuntu SMP Wed Feb 9 15:36:45 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.2                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.23.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     4.14.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool…
Script     5.3.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     4.2.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageA…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUse…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
Resolve-AzError

DEBUG: 5:45:54 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 5:45:54 AM - using account id 'MSI@50342'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 7

Message        : A parameter cannot be found that matches parameter name 'DisplayHint'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzRestorePointCollection}
Line           : Get-AzRestorePointCollection -ResourceGroupName "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1" -DisplayHint Expand
Position       : At line:1 char:97
                 + … e "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1" -DisplayHint Expand
                 +                                                     ~~~~~~~~~~~~
HistoryId      : 7


   HistoryId: 5

Message        : A parameter cannot be found that matches parameter name 'Expand'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzRestorePointCollection}
Line           : Get-AzRestorePointCollection -ResourceGroupName "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1" -Expand "Yes"
Position       : At line:1 char:97
                 + … oupName "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1" -Expand "Yes"
                 +                                                           ~~~~~~~
HistoryId      : 5


   HistoryId: 3

Message        : A parameter cannot be found that matches parameter name 'Expand'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzRestorePointCollection}
Line           : Get-AzRestorePointCollection -ResourceGroupName "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1" -Expand "RestorePoints"
Position       : At line:1 char:97
                 + … pName "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1" -Expand "Restor …
                 +                                                         ~~~~~~~
HistoryId      : 3


   HistoryId: 2

Message        : A parameter cannot be found that matches parameter name 'Expand'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzRestorePointCollection}
Line           : Get-AzRestorePointCollection -ResourceGroupName "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1"  -Expand "RestorePoints"
Position       : At line:1 char:98
                 + … Name "RPC-Public-Preview" -Name "RPC-PP-SourceRPC-1"  -Expand "Restor …
                 +                                                         ~~~~~~~
HistoryId      : 2


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.2; CommandName: Resolve-AzError; PSVersion: 7.2.1; IsSuccess: True; Duration: 00:00:00.0182265
DEBUG: Finish sending metric.
DEBUG: 5:45:55 AM - ResolveError end processing.
```

**Comment by Drewm3** [comment]
@TravisCragg-MSFT, could you look into this issue.

**Comment by haagha** [comment]
@dikethir if you can do :
`$rpccol = Get-AzRestorePointCollection -ResourceGroupName $rgname -Name $restorePointCollectionName
$rpccol.Source`

you will be able to see list of restorepoints.

**Comment by TravisCragg-MSFT** [comment]
@dikethir were you able to see the list of restore points when doing the procedure by @haagha?

**Comment by TravisCragg-MSFT** [comment]
@dikethir I am closing this issue. If you are still having this issue and the above workaround does not resolve the problem let me know.
