### ISSUE TITLE
Get-AzWebAppSnapshot fails to convert DateTime if console is in different Culture

### ISSUE THREAD

**Issue by AlexJPawlak** [Azure/azure-powershell#17253]
### Description

When running the cmdlet with non en-US (at least, in pl-PL culture) the cmdlet fails with example error:

 String '01/24/2022 22:52:39' was not recognized as a valid DateTime.
 
 Output of: 
[system.threading.thread]::CurrentThread.CurrentCulture
LCID             Name             DisplayName
----             ----             -----------
1045             pl-PL            Polish (Poland)

Steps to reproduce:

[system.threading.thread]::CurrentThread.CurrentCulture = [System.Globalization.CultureInfo]::GetCultureInfo("pl-PL")
Get-AzWebAppSnapshot -ResourceGroupName $SourceRG  -Name $WebAppName

When changing CurrentThread.CurrentCulture to en-US it works OK. 

Error, presumably, in  https://github.com/Azure/azure-powershell/blob/4668bff1cc4ed6510d9b0d4c6ec289ab27f04241/src/Websites/Websites/Cmdlets/BackupRestore/GetAzureWebAppSnapshot.cs 

```
return new AzureWebAppSnapshot()
                {
                    ResourceGroupName = this.ResourceGroupName,
                    Name = this.Name,
                    Slot = string.IsNullOrEmpty(this.Slot) ? "Production" : this.Slot,
                    **SnapshotTime = DateTime.Parse(s.Time)**
                };
```
Service returns datetime in en-US culture, which cannot be parsed properly. Forcing a change to en-US culture will allow parsing properly. Not a C# dev at all, but I think using dateTime Parse method with IFormatProvider overload might be helpful here https://docs.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=net-6.0#system-datetime-parse(system-string-system-iformatprovider)

### Issue script & Debug output

```PowerShell
PS C:\Users\AleksanderPawlak> Get-AzWebAppSnapshot -ResourceGroupName $SourceRG  -Name $WebAppName
DEBUG: 14:28:22 - GetAzureWebAppSnapshot begin processing with ParameterSet 'FromResourceName'.
DEBUG: 14:28:22 - using account id 'apawlak@redacted.co'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'apawlak@redacted.co', environment: 'AzureCloud', tenant: 'tenantID'
DEBUG: 14:28:22 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'tenantID', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'apawlak@redacted.co'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22] Found 3 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22] Returning 3 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(e660072a-98a2-400b-b94c-cf0818e49965)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - e660072a-98a2-400b-b94c-cf0818e49965

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] Access token is not expired. Returning the found cache entry. [Current time (02/23/2022 13:28:22) - Expiration Time (02/23/2022 14:31:11 +00:00) - Extended Expiration Time (02/23/2022 14:31:11 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [02/23/2022 13:28:22 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 02/23/2022 14:31:11 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-02-23T14:31:11.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'tenantID', UserId: 'apawlak@redacted.co'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.comMyWebAppResourceID/snapshots?api-version=2021-01-15

Headers:
x-ms-client-request-id        : e9551354-5196-477a-b4a9-c29f9abaf8c3
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : "1D81F26F277838B"
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : e225dab9-cde9-456d-a45e-11e54305f1c2
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : 470f7b9c-e979-4e57-8d13-5ab814f2f620
x-ms-routing-request-id       : GERMANYNORTH:20220223T132824Z:470f7b9c-e979-4e57-8d13-5ab814f2f620
X-Content-Type-Options        : nosniff
Date                          : Wed, 23 Feb 2022 13:28:23 GMT

Body:
{
  "value": [
    {
      "id": "MyWebAppResourceID/snapshots/2022-01-24T22_52_39_6740469",
      "name": "2022-01-24T22:52:39.6740469",
      "type": "Microsoft.Web/sites/snapshots",
      "properties": {
        "time": "2022-01-24T22:52:39.6740469"
      }
    },
    {
      "id": "MyWebAppResourceID/snapshots/2022-02-23T12_45_57_5273305",
      "name": "2022-02-23T12:45:57.5273305",
      "type": "Microsoft.Web/sites/snapshots",
      "properties": {
        "time": "2022-02-23T12:45:57.5273305"
      }
    }
  ],
  "nextLink": null,
  "id": null
}


Get-AzWebAppSnapshot: String '01/24/2022 22:52:39' was not recognized as a valid DateTime.
DEBUG: AzureQoSEvent: Module: Az.Websites:2.9.0; CommandName: Get-AzWebAppSnapshot; PSVersion: 7.2.1; IsSuccess: False; Duration: 00:00:01.9445481; Exception: String '01/24/2022 22:52:39' was not recognized as a valid DateTime.;
DEBUG: Finish sending metric.
DEBUG: 14:28:25 - GetAzureWebAppSnapshot end processing.
PS C:\Users\AleksanderPawlak>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Users\AleksanderPawlak> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.1.2                 Az.Dns                              {Add-AzDnsRecordConfig, Get-AzDnsRecordSet, Get-AzDnsZone, New-AzDnsRecordConfig…}
Script     2.9.0                 Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRouting, Edit-AzWebAppBackupConfiguration, Enter-AzWebAppContainerPSSession…}
Script     5.5.2                 AzureRM.Resources                   {Export-AzureRmResourceGroup, Find-AzureRmResource, Find-AzureRmResourceGroup, Get-AzureRmADAppCredential…}

PS C:\Users\AleksanderPawlak>
```

### Error output

```PowerShell
PS C:\Users\AleksanderPawlak> Resolve-AzError | Select -First 1
DEBUG: 14:33:43 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 14:33:43 - using account id 'apawlak@trebu.co'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 72

Message        : String '01/24/2022 22:52:39' was not recognized as a valid DateTime.
StackTrace     :    at Microsoft.Azure.Commands.WebApps.Cmdlets.BackupRestore.GetAzureWebAppSnapshot.<ExecuteCmdlet>b__4_0(Snapshot s)
                    at System.Linq.Enumerable.SelectListIterator`2.ToArray()
                    at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
                    at System.Linq.OrderedEnumerable`1.ToArray()
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.BackupRestore.GetAzureWebAppSnapshot.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.FormatException
InvocationInfo : {Get-AzWebAppSnapshot}
Line           : Get-AzWebAppSnapshot -ResourceGroupName $SourceRG  -Name $WebAppName
Position       : At line:1 char:1
                 + Get-AzWebAppSnapshot -ResourceGroupName $SourceRG  -Name $WebAppName
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 72
```

**Comment by navba-MSFT** [comment]
@AlexJPawlak Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will update this thread once we have more details on this.

**Comment by Kotasudhakarreddy** [comment]
@navba-MSFT I am looking in to it. Will update you.

**Comment by Kotasudhakarreddy** [comment]
Closing as the code fix is given.
