### ISSUE TITLE
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'EndDate' or 'StartDate'

### ISSUE THREAD

**Issue by smithg6** [Azure/azure-powershell#17256]
### Description

When running cmdlet New-AzADServicePrincipal with Az.Resource Module version 5.3.1 and Az Module 7.2.1, I keep getting below error:
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'EndDate'.

This happens whether I am trying with -ApplicationId Parameter or -ApplicationObject parameter.

### Issue script & Debug output

```PowerShell
PS /home/user> $DebugPreference='Continue'                                                                                                   
PS /home/user> New-AzADServicePrincipal -ApplicationId $id -EndDate $EndDate                                                   
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'EndDate'.
PS /home/user> New-AzADServicePrincipal -ApplicationId $id -StartDate $EndDate  
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'StartDate'.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.4.0-1070-azure #73~18.04.1-Ubuntu SMP Wed Feb 9 15:36:45 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.2                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.23.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDa…
Script     4.14.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBa…
Script     5.3.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDe…
Script     4.2.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDev…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
> Resolve-AzError
DEBUG: 11:24:05 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 11:24:05 PM - using account id 'MSI@50342'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 20

Message        : A parameter cannot be found that matches parameter name 'StartDate'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 
Position       : At /home/user/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:763 
                 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 20


   HistoryId: 19

Message        : A parameter cannot be found that matches parameter name 'EndDate'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 
Position       : At /home/user/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:763 
                 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 19


   HistoryId: 16

Message        : A parameter cannot be found that matches parameter name 'EndDate'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 
Position       : At /home/user/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:763 
                 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 16


   HistoryId: 13

Message        : A parameter cannot be found that matches parameter name 'EndDate'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 
Position       : At /home/user/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:763 
                 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 13


   HistoryId: 9

Message        : A parameter cannot be found that matches parameter name 'StartDate'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 
Position       : At /home/user/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:763 
                 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 9


   HistoryId: 5

Message        : A parameter cannot be found that matches parameter name 'EndDate'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADServicePrincipal}
Line           :     $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 
Position       : At /home/user/.local/share/powershell/Modules/Az.Resources/5.3.1/MSGraph.Autorest/custom/New-AzADServicePrincipal.ps1:763 
                 char:56
                 + … $sp = Az.MSGraph.internal\New-AzADServicePrincipal @PSBoundParameters
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 5


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.2; CommandName: Resolve-AzError; PSVersion: 7.2.1; IsSuccess: True; Duration: 00:00:00.0197876
DEBUG: Finish sending metric.
DEBUG: 11:24:06 PM - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , could you look into it?

**Comment by VeryEarly** [comment]
Hi @smithg6 ,

When creating serviceprincipal with startdate/enddate, the legacy behavior is to set a passsword with startdate/enddate for a new created application (which associate service principal), 
while you provided application ID already, startdate/enddate should not be needed, however the error message doesn't make sense here, I already made fix and will be out on 2022-03-01 PST.

Thanks

**Comment by smithg6** [comment]
Thanks, I'll make sure and get the latest next week and try it out. FWIW the creation does seem to work fine when both StartDate and EndDate aren't present.

So just wanted to confirm this real quick: you're saying that since the legacy password creation is no longer happening, we are not going to be able to set an enddate since the credential is made server side?

**Comment by VeryEarly** [comment]
> Thanks, I'll make sure and get the latest next week and try it out. FWIW the creation does seem to work fine when both StartDate and EndDate aren't present.
> 
> So just wanted to confirm this real quick: you're saying that since the legacy password creation is no longer happening, we are not going to be able to set an enddate since the credential is made server side?

Yes, password will be created upon creation at server side.

**Comment by smithg6** [comment]
Looks like the latest version 7.3.0 is still showing the unclear error message as of today if you use start-date or end-date.

```
PS /home/user> New-AzADServicePrincipal -ApplicationId $application.AppId -startdate (Get-Date) -EndDate ((Get-Date).AddDays(14))
New-AzADServicePrincipal: A parameter cannot be found that matches parameter name 'StartDate'.
PS /home/user> Get-InstalledModule az

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
7.3.0                Az                                  https://www.poshtes… Microsoft Azure PowerShell - Cmdlets to manage resources in Azure.
```

**Comment by VeryEarly** [comment]
Hi @smithg6 ,

Thanks for report this bug, I've made fix in #17571 ,
Error message will now be:
```
Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

**Comment by smithg6** [comment]
Thanks @VeryEarly, good to know. So you're saying that because I'm using the older "ApplicationId" param, that is not compatible with the StartDate and EndDate params, and that is causing the failure?

**Comment by VeryEarly** [comment]
Hi @smithg6 , 
Yes, the start/end date is for application password when application is not provided (New-AzADServicePrincipal will create application, and then serviceprincpal), since application ID is already available, no need to specify start/end date.

**Comment by dingmeng-xue** [comment]
Close this issue as pull request is merged.
