### ISSUE TITLE
Get-AzAksVersion Results in Access Token Exception

### ISSUE THREAD

**Issue by Adriana171** [Azure/azure-powershell#17268]
### Description

I am running the following command:
            Get-AzAksVersion -Location westeurope -SubscriptionId $subscriptionId | ConvertTo-Json -Depth 3. 

I have checked the scope of the access token and should have the ability to use this cmdlet. 

"token_type": "Bearer",
    "scope": "user_impersonation",
    "expires_in": "5235",
    "ext_expires_in": "5235",
    "expires_on": "1645801520",
    "not_before": "1645795984",
    "resource": "https://management.azure.com",

I am able to run the same command using the Azure CLI using a service principal. 

### Issue script & Debug output

```PowerShell
Az.Aks.internal\Get-AzAksContainerServiceOrchestrator : [AccessTokenAuthenticator] failed to retrieve access token for resource 'ResourceManager';. Please ensure that you have provided the appropriate 
access tokens when using access token login.
At C:\Users\adria\OneDrive\Documents\WindowsPowerShell\Modules\Az.Aks\3.1.0\Aks.Autorest\custom\Get-AzAksVersion.ps1:112 char:16
+ ...      return (Az.Aks.internal\Get-AzAksContainerServiceOrchestrator -L ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzAksContai...chestrator_List], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.19041.1320                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.19041.1320                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                                  
Script     2.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                                                                       
Script     3.1.0      Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNodePool...}                                                                   
Script     5.2.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}                                                        
Binary     2.0.2.76   AzureAD                             {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember...}
```

### Error output

```PowerShell
Message        : [AccessTokenAuthenticator] failed to retrieve access token for resource 'ResourceManager';. Please ensure that you have provided the appropriate access tokens when using access token 
                 login.
StackTrace     :    at Microsoft.Azure.PowerShell.Authenticators.AccessTokenAuthenticator.Authenticate(AuthenticationParameters parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString 
                 password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString 
                 password, String promptBehavior, Action`1 promptAction, String resourceId)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass14_0.<AuthorizeRequest>b__0()
                    at System.Threading.Tasks.Task.Execute()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<AuthorizeRequest>d__14.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass13_0.<<SendHandler>b__0>d.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators_Call>d__30.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators_Call>d__30.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators>d__28.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List.<ProcessRecordAsync>d__63.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List.<ProcessRecordAsync>d__63.MoveNext()
Exception      : System.InvalidOperationException
InvocationInfo : {Get-AzAksContainerServiceOrchestrator_List}
Line           :         return (Az.Aks.internal\Get-AzAksContainerServiceOrchestrator -Location $Location -ResourceType 'managedClusters' @EnvPSBoundParameters).Orchestrator
                 
Position       : At C:\Users\adria\OneDrive\Documents\WindowsPowerShell\Modules\Az.Aks\3.1.0\Aks.Autorest\custom\Get-AzAksVersion.ps1:112 char:16
                 + ...      return (Az.Aks.internal\Get-AzAksContainerServiceOrchestrator -L ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Adriana171** [comment]
PS C:\Users\adria> $DebugPreference = "Continue"

PS C:\Users\adria> Get-AzAksVersion
cmdlet Get-AzAksVersion at command pipeline position 1
Supply values for the following parameters:
Location: westeurope 
DEBUG: 8:26:46 AM - GetAzureRMContextCommand end processing.
DEBUG: 8:26:46 AM - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzAksContainerServiceOrchestrator_List'
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/westeurope%20/orchestrators?api-version=2019-08-01&resource-type=managedClusters
DEBUG: RequestCreated: /subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/westeurope%20/orchestrators?api-version=2019-08-01&resource-type=managedClusters
DEBUG: HeaderParametersAdded: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/westeurope /orchestrators?api-version=2019-08-01&resource-type=managedClusters


Headers:
x-ms-unique-id                : 1
x-ms-client-request-id        : 7cb5feed-41c3-43e6-bb0d-e52efa0bb4c9
CommandName                   : Az.Aks.internal\Get-AzAksContainerServiceOrchestrator
FullCommandName               : Get-AzAksContainerServiceOrchestrator_List
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v5.1.19041.1320,Az.Aks/3.1.0

Body:



DEBUG: BeforeCall: 
DEBUG: Finally: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: [CmdletException]: Received Exception with message 'InvalidOperationException - [AccessTokenAuthenticator] failed to retrieve access token for resource 'ResourceManager';. Please ensure that you hav
e provided the appropriate access tokens when using access token login. :    at Microsoft.Azure.PowerShell.Authenticators.AccessTokenAuthenticator.Authenticate(AuthenticationParameters parameters, Cancella
tionToken cancellationToken)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBe
havior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBe
havior, Action`1 promptAction, String resourceId)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass14_0.<AuthorizeRequest>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<AuthorizeRequest>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass13_0.<<SendHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators_Call>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators_Call>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List.<ProcessRecordAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List.<ProcessRecordAsync>d__63.MoveNext()'
DEBUG: CmdletException: InvalidOperationException - [AccessTokenAuthenticator] failed to retrieve access token for resource 'ResourceManager';. Please ensure that you have provided the appropriate access t
okens when using access token login. :    at Microsoft.Azure.PowerShell.Authenticators.AccessTokenAuthenticator.Authenticate(AuthenticationParameters parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.DelegatingAuthenticator.TryAuthenticate(AuthenticationParameters parameters, CancellationToken cancellationToken, Task`1& token)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBe
havior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBe
havior, Action`1 promptAction, String resourceId)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass14_0.<AuthorizeRequest>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<AuthorizeRequest>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass13_0.<<SendHandler>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators_Call>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators_Call>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Aks.<ContainerServicesListOrchestrators>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List.<ProcessRecordAsync>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List.<ProcessRecordAsync>d__63.MoveNext()
Az.Aks.internal\Get-AzAksContainerServiceOrchestrator : [AccessTokenAuthenticator] failed to retrieve access token for resource 'ResourceManager';. Please ensure that you have provided the appropriate 
access tokens when using access token login.
At C:\Users\adria\OneDrive\Documents\WindowsPowerShell\Modules\Az.Aks\3.1.0\Aks.Autorest\custom\Get-AzAksVersion.ps1:112 char:16
+ ...      return (Az.Aks.internal\Get-AzAksContainerServiceOrchestrator -L ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzAksContai...chestrator_List], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.PowerShell.Cmdlets.Aks.Cmdlets.GetAzAksContainerServiceOrchestrator_List
 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: AzureQoSEvent: Module: Az.Aks:3.1.0; CommandName: Get-AzAksContainerServiceOrchestrator_List; PSVersion: 5.1.19041.1320; IsSuccess: True; Duration: 00:00:00
DEBUG: Finish sending metric.
DEBUG: CmdletEndProcessing:

**Comment by Adriana171** [comment]
When I send a request to :[https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.ContainerService/locations/westeurope](https://management.azure.com/subscriptions/%7BsubscriptionId%7D/providers/Microsoft.ContainerService/locations/westeurope) /orchestrators?api-version=2019-08-01&resource-type=managedClusters

I get a response. I am using the same token.

{
    "id": "/subscriptions/80115be8-23dd-4136-918f-965b0b078853/providers/Microsoft.ContainerService/locations/westeurope/orchestrators",
    "name": "default",
    "type": "Microsoft.ContainerService/locations/orchestrators",
    "properties": {
        "orchestrators": [
            {
                "orchestratorType": "Kubernetes",
                "orchestratorVersion": "1.20.13",
                "upgrades": [
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.20.15"
                    },
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.21.7"
                    },
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.21.9"
                    }
                ]
            },
            {
                "orchestratorType": "Kubernetes",
                "orchestratorVersion": "1.20.15",
                "upgrades": [
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.21.7"
                    },
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.21.9"
                    }
                ]
            },
            {
                "orchestratorType": "Kubernetes",
                "orchestratorVersion": "1.21.7",
                "upgrades": [
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.21.9"
                    },
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.22.4"
                    },
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.22.6"
                    }
                ]
            },
            {
                "orchestratorType": "Kubernetes",
                "orchestratorVersion": "1.21.9",
                "default": true,
                "upgrades": [
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.22.4"
                    },
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.22.6"
                    }
                ]
            },
            {
                "orchestratorType": "Kubernetes",
                "orchestratorVersion": "1.22.4",
                "upgrades": [
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.22.6"
                    },
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.23.3",
                        "isPreview": true
                    }
                ]
            },
            {
                "orchestratorType": "Kubernetes",
                "orchestratorVersion": "1.22.6",
                "upgrades": [
                    {
                        "orchestratorType": "Kubernetes",
                        "orchestratorVersion": "1.23.3",
                        "isPreview": true
                    }
                ]
            },
            {
                "orchestratorType": "Kubernetes",
                "orchestratorVersion": "1.23.3",
                "isPreview": true
            }
        ]
    }
}

**Comment by Adriana171** [comment]
I am currently getting an access token OBO of another tenant. 

Connect-AzAccount -Tenant $customerTenantId -AccountId $tenantId -SubscriptionId $subscriptionId -AccessToken $azureManagementAccessToken -MicrosoftGraphAccessToken $msGraphToken


-MicrosoftGraphAccessToken Retrieval:
grant_type:refresh_token
client_id:{clientId}
client_secret:{clientSecret}
resource:https://graph.microsoft.com
refresh_token:{refreshToken}


-AccessToken Retrieval:
grant_type:refresh_token
client_id:{clientId}
client_secret:{clientSecret}
resource:https://management.azure.com
refresh_token:{refreshToken}

**Comment by dingmeng-xue** [comment]
Hi @adriana171, I cannot reproduce this issue yet. I suspect it is related to your access token. I do not how you get that access token. Normally, access token doesn't contain all claims listed by you.
