### ISSUE TITLE
Add-AzVHD - Error with path with ampersand (&), even if properly quoted

### ISSUE THREAD

**Issue by fowl2** [Azure/azure-powershell#17276]
### Description

`Add-AzVHD` will fail at the MD5 calculation step if the path to the VHD contains an ampersand, which is a legal path character on Windows. 

The problem is here:

https://github.com/Azure/azure-powershell/blob/ebc4710853f09e2e16d33ff479fd2ee9b45a8156/src/Compute/Compute/Models/PSSyncOutputEvents.cs#L108-L116

I'm not sure why it's doing this instead of just calling [WriteProgress](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation.cmdlet.writeprogress), `WriteInformation`, or similar.

There seems to be a lot of what is effectively "eval"ing in this file and it should probably all be audited for injection vulnerabilities.

### Environment data

```PowerShell
Name                           Value                                                                                                                  
----                           -----                                                                                                                  
PSVersion                      5.1.20348.320                                                                                                          
PSEdition                      Desktop                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                
BuildVersion                   10.0.20348.320                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                        
WSManStackVersion              3.0                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                    
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name         
---------- -------    ----         
Script     2.7.1      Az.Accounts  
Script     4.23.0     Az.Compute
```

### Error output

```PowerShell
Message        : At line:1 char:79
                 + ... sh is being calculated for the file 'E:\my vms & more ...
                 +                                                                 ~
                 The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
                 ("&") to pass it as part of a string.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
                    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, 
                 PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, 
                 PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
                    at Microsoft.Azure.Commands.Compute.Models.PSSyncOutputEvents.LogMessage(String format, Object[] parameters)
                    at Microsoft.WindowsAzure.Commands.Sync.Upload.FileMetaData.CalculateMd5Hash(Stream stream, String filePath)
                    at Microsoft.WindowsAzure.Commands.Sync.Upload.FileMetaData.Create(String filePath)
                    at Microsoft.Azure.Commands.Compute.Sync.Upload.DiskUploadCreator.get_OperationMetaData()
                    at Microsoft.Azure.Commands.Compute.Sync.Upload.DiskUploadCreator.get_MD5HashOfLocalVhd()
                    at Microsoft.Azure.Commands.Compute.Sync.Upload.DiskUploadCreator.Create(FileInfo localVhd, PSPageBlobClient pageblob, Boolean 
                 overWrite)
                    at Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand.<ExecuteCmdlet>b__51_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.ParseException
InvocationInfo : {Add-AzVhd}

                 
Position       : At line:2 char:1
                 + Add-AzVhd -LocalFilePath "E:\my vms & more\disk ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 20

Message        : At line:1 char:79
                 + ... sh is being calculated for the file 'E:\my vms & more...
                 +                                                                 ~
                 The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks 
                 ("&") to pass it as part of a string.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
                    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, 
                 PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, 
                 PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
                    at Microsoft.Azure.Commands.Compute.Models.PSSyncOutputEvents.LogMessage(String format, Object[] parameters)
                    at Microsoft.WindowsAzure.Commands.Sync.Upload.FileMetaData.CalculateMd5Hash(Stream stream, String filePath)
                    at Microsoft.WindowsAzure.Commands.Sync.Upload.FileMetaData.Create(String filePath)
                    at Microsoft.Azure.Commands.Compute.Sync.Upload.DiskUploadCreator.get_OperationMetaData()
                    at Microsoft.Azure.Commands.Compute.Sync.Upload.DiskUploadCreator.get_MD5HashOfLocalVhd()
                    at Microsoft.Azure.Commands.Compute.Sync.Upload.DiskUploadCreator.Create(FileInfo localVhd, PSPageBlobClient pageblob, Boolean 
                 overWrite)
                    at Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand.<ExecuteCmdlet>b__51_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.ParseException
InvocationInfo : {Add-AzVhd}
Line           : Add-AzVhd -LocalFilePath "E:\my vms & more\disk-0.vhdx" -ResourceGroupName RG-PrintScan -Location 
                 australiasoutheast -DiskName dsubmel753_os -DiskSku StandardSSD_LRS
                 
```

**Comment by SaurabhSharma-MSFT** [comment]
@fowl2 We are looking into this and get back to you in case any questions.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by jaylabell** [comment]
@grizzlytheodore can you please take a look at this issue?

**Comment by grizzlytheodore** [comment]
@fowl2 thank you for sharing this. We will take a look and share the solution plan with you soon. 
For now, please remove the "&" from your file name.

**Comment by grizzlytheodore** [comment]
Update: this issue is fixed in https://github.com/Azure/azure-powershell/pull/17786 and will GA on 4/26
