### ISSUE TITLE
[AKS] GenerateSSHKey option silently fails if %USERPROFILE%\.ssh doesn't exist

### ISSUE THREAD

**Issue by phealy** [Azure/azure-powershell#17421]
### Description

The [GenerateSshKeyValue function](https://github.com/Azure/azure-powershell/blob/main/src/Aks/Aks/Commands/NewAzureRmAks.cs#L264) doesn't create the .ssh directory if it's not there, and ssh-keygen doesn't automatically create the folder when you explicitly specify the path.

### Issue script & Debug output

```PowerShell
$ New-AzAksCluster -ResourceGroup $RG -Name powershell -GenerateSshKey
DEBUG: 11:24:18 AM - NewAzureRmAks begin processing with ParameterSet 'defaultParameterSet'.
DEBUG: 11:24:18 AM - using account id 'pahealy@microsoft.com'...
WARNING: Upcoming breaking changes in the cmdlet 'New-AzAksCluster' :
The cmdlet 'New-AzAksCluster' is replacing this cmdlet.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
DEBUG: Generating public/private rsa key pair.

New-AzAksCluster: Could not find SSH public key in default path 'C:\Users\pahealy\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you have ssh-keygen installed.
DEBUG: AzureQoSEvent: Module: Az.Aks:3.1.0; CommandName: New-AzAksCluster; PSVersion: 7.2.1; IsSuccess: False; Duration: 00:00:02.6891192; Exception: Could not find SSH public key in default path 'C:\Users\pahealy\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you have ssh-keygen installed.;
DEBUG: Finish sending metric.
DEBUG: 11:24:21 AM - NewAzureRmAks end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
```


### Module versions

```PowerShell
Az.Accounts
Az.Aks
Az.Resources
```

### Error output

```PowerShell
DEBUG: 11:25:23 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 11:25:23 AM - using account id 'pahealy@microsoft.com'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 17

Message        : Could not find SSH public key in default path 'C:\Users\pahealy\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or
                 https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you
                 have ssh-keygen installed.
StackTrace     :    at Microsoft.Azure.Commands.Aks.CreateOrUpdateKubeBase.GetSshKey(String sshKeyOrFile)
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.GenerateSshKeyValue()
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.PrepareParameter()
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.Common.Exceptions.AzPSArgumentException
InvocationInfo : {New-AzAksCluster}
Line           : New-AzAksCluster -ResourceGroup $RG -Name powershell -GenerateSshKey
Position       : At line:1 char:1
                 + New-AzAksCluster -ResourceGroup $RG -Name powershell -GenerateSshKey
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 17


   HistoryId: 13

Message        : Could not find SSH public key in default path 'C:\Users\pahealy\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or
                 https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you
                 have ssh-keygen installed.
StackTrace     :    at Microsoft.Azure.Commands.Aks.CreateOrUpdateKubeBase.GetSshKey(String sshKeyOrFile)
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.GenerateSshKeyValue()
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.PrepareParameter()
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.Common.Exceptions.AzPSArgumentException
InvocationInfo : {New-AzAksCluster}
Line           : New-AzAksCluster -ResourceGroup $RG -Name powershell -GenerateSshKey
Position       : At line:1 char:1
                 + New-AzAksCluster -ResourceGroup $RG -Name powershell -GenerateSshKey
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 13


   HistoryId: 11

Message        : Could not find SSH public key in default path 'C:\Users\pahealy\.ssh\id_rsa.pub' which is required for creating k8s cluster. See https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys or
                 https://docs.microsoft.com/en-us/azure/virtual-machines/linux/ssh-from-windows for generating a key pair manually; or you could try to add switch parameter -GenerateSshKey during calling New-AzAksCluster which will automatically generate SSH key file if you
                 have ssh-keygen installed.
StackTrace     :    at Microsoft.Azure.Commands.Aks.CreateOrUpdateKubeBase.GetSshKey(String sshKeyOrFile)
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.GenerateSshKeyValue()
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.PrepareParameter()
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.Common.Exceptions.AzPSArgumentException
InvocationInfo : {New-AzAksCluster}
Line           : New-AzAksCluster -ResourceGroup $RG -Name powershell -GenerateSshKey
Position       : At line:1 char:1
                 + New-AzAksCluster -ResourceGroup $RG -Name powershell -GenerateSshKey
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.1; CommandName: Resolve-AzError; PSVersion: 7.2.1; IsSuccess: True; Duration: 00:00:00.0729003
DEBUG: Finish sending metric.
DEBUG: 11:25:23 AM - ResolveError end processing.
```
```

**Comment by dingmeng-xue** [comment]
We will look into it.

**Comment by wyunchi-ms** [comment]
Hi @phealy , can `%USERPROFILE%\.ssh` be created first on your environment?
