### ISSUE TITLE
The "Confirm" parameter cannot work with any values in the New-AzResourceLock command

### ISSUE THREAD

**Issue by AmberYangY** [Azure/azure-powershell#17539]
### Description

Users used the following PowerShell command with the "Confirm" parameter to create resource lock for specific resources.
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azresourcelock?view=azps-7.3.2

According to the above documentation, the "Confirm" parameter should be the "True" or "False"
But users tried all the following values, all of them showed the same error message
“True”, “true”, “Yes”, “yes”, “1”, “0”, True, true, Yes, yes, 1, 0

Taking the "True" value as an example, please see the below results.

New-AzResourceLock -LockLevel CanNotDelete -LockNotes "xxx" -LockName "xxx"  -ResourceGroupName "xxx" -ResourceName "xxx" -ResourceType "xxxx" -Confirm "True"

New-AzResourceLock : A positional parameter cannot be found that accepts argument 'True'.

At line:1 char:1
+New-AzResourceLock -LockLevel CanNotDelete -LockNotes "My lock notes" ...
+~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzResourceLock], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceLockCmdlet

### Issue script & Debug output

```PowerShell
New-AzResourceLock -LockLevel CanNotDelete -LockNotes "xxx" -LockName "xxx"  -ResourceGroupName "xxx" -ResourceName "xxx" -ResourceType "xxxx" -Confirm "True"
If I click the Debug, it will raised a lot of prompted windows to ask whether to create the locks.
```

### Environment data

```PowerShell
Name                           Value                                                                                                                               
----                           -----                                                                                                                               
PSVersion                      5.1.22000.282                                                                                                                       
PSEdition                      Desktop                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                             
BuildVersion                   10.0.22000.282                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                     
WSManStackVersion              3.0                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                 
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                         
---------- -------    ----                                ----------------                                                                                         
Script     2.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                              
Script     4.4.0      Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCredential...}
```

### Error output

```PowerShell
Message        : A positional parameter cannot be found that accepts argument 'True'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzResourceLock}
Line           : New-AzResourceLock -LockLevel CanNotDelete -LockNotes "xx" -LockName "xx"  -ResourceGroupName "xx" -ResourceName 
                 "xx" -ResourceType "xx"-Confirm "True"
Position       : At line:1 char:1
                 + New-AzResourceLock -LockLevel CanNotDelete -LockNotes "xx" ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dingmeng-xue** [comment]
Hi @AmberYangY , thanks for reporting.

`-Confirm` is a switch parameter. You can try to use `-Confirm:$true`.

**Comment by PramodValavala-MSFT** [comment]
@AmberYangY Hope @dingmeng-xue answer clears things up. Here is the reference for [switch parameters](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2#switch-parameters).

Usually, you could just use `-Confirm` in your commands.
