### ISSUE TITLE
Add-AzStorageAccountNetworkRule doesn't add multiple IPs

### ISSUE THREAD

**Issue by prabhakarreddy1234** [Azure/azure-powershell#17605]
### Description

As per the [documentation](https://docs.microsoft.com/en-us/powershell/module/az.storage/add-azstorageaccountnetworkrule?view=azps-7.3.2#examples)  array of IP addresses can be added. But the same command as shown in the example throws below error.

`Add-AzStorageAccountNetworkRule: Values for request parameters are invalid: networkAcls.ipRule[*].value. For more information, see - https://aka.ms/storagenetworkruleset`

### Issue script & Debug output

```PowerShell
Add-AzStorageAccountNetworkRule -ResourceGroupName "myResourceGroup" -Name "mystorageaccount" -IPAddressOrRange "10.0.0.0/24","28.2.0.0/16"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.6.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     3.12.0                Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetwork…
```

### Error output

```PowerShell
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 2

StackTrace     :    at Microsoft.Azure.Management.Storage.StorageAccountsOperations.UpdateWithHttpMessagesAsync(String resourceGroupName, String accountName,
                 StorageAccountUpdateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.UpdateAsync(IStorageAccountsOperations operations, String resourceGroupName,        
                 String accountName, StorageAccountUpdateParameters parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.Update(IStorageAccountsOperations operations, String resourceGroupName, String      
                 accountName, StorageAccountUpdateParameters parameters)
                    at Microsoft.Azure.Commands.Management.Storage.AddAzureStorageAccountNetworkRuleCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 2


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by blueww** [comment]
@prabhakarreddy1234 
It looks server not allow "10.0.0.0/24".
If you change to other IP like `"20.11.0.0/16","232.0.18.177/7"`, it work well on my side.

There might be some restriction added by server after we add the sample.
I will update the sample.

Would you like try to add other IPs? If you have business reason to add "10.0.0.0/24", please raise an issue in Azure Portal - Help & Support, and ask server team help.

**Comment by navba-MSFT** [comment]
@prabhakarreddy1234 Could you please let us know if you had a chance to look at the above comment? Please let us know if you have any further questions on this. Awaiting your reply.

**Comment by prabhakarreddy1234** [comment]
@navba-MSFT   yes it works with `"20.11.0.0/16","232.0.18.177/7"`. So only  `10.*` IPs doesn't get added using that command. If the documentation can be updated that's good enough for now.

**Comment by navba-MSFT** [comment]
Thanks @prabhakarreddy1234 for getting back. PR https://github.com/Azure/azure-powershell/issues/17605 has been filed by @blueww and it is pending under review now.

**Comment by blueww** [comment]
@navba-MSFT 
It looks it's an ip address with mask 24 can't be added. 
I have raised a PR to updated the doc, https://github.com/Azure/azure-powershell/pull/17588

**Comment by blueww** [comment]
@navba-MSFT

The help fix PR is merged, should be public when the next release is out (target 4/5).
I will close this issue.

Feel free to contact us again if need any further assistance on Azure Powershell.
