### ISSUE TITLE
Feature in General Availability throwing preview error message

### ISSUE THREAD

**Issue by MarcSteene** [Azure/azure-powershell#17803]
### Description

Archive tier has gone GA for backup items, however the PowerShell described in the ([docs](https://docs.microsoft.com/en-us/powershell/module/az.recoveryservices/get-azrecoveryservicesbackuprecommendedarchivablerpgroup?view=azps-7.4.0)) results in a preview error message being thrown.

The PowerShell is being run from an Azure Automation Account PowerShell runbook.

### Issue script & Debug output

```PowerShell
$vault = Get-AzRecoveryServicesVault -ResourceGroupName "ALB_RG1" -Name "testarchivevault"
$item = Get-AzRecoveryServicesBackupItem -BackupManagementType "AzureVM" -WorkloadType "AzureVM" -VaultId $vault.ID

$rpGroup = Get-AzRecoveryServicesBackupRecommendedArchivableRPGroup -Item $item[0] -VaultId $vault.ID

Environments                                                                                                            
------------                                                                                                            
{[AzureChinaCloud, AzureChinaCloud], [AzureCloud, AzureCloud], [AzureGermanCloud, AzureGermanCloud], [AzureUSGovernme...
The operation you are trying requires enrollment into a feature that is currently in limited preview. Please enroll your subscription in the limited preview and retry the operation, or retry after this feature is availble to all customers.
```

### Environment data

```PowerShell
Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Manifest   1.1.0.0    AuditPolicyDsc                                                                                    
Script     2.7.4      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enabl...
Script     1.1.2      Az.Advisor                          {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendatio...
Script     3.1.2      Az.Aks                              {Get-AzAksCluster, New-AzAksCluster, Remove-AzAksCluster, I...
Script     1.1.4      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisService...
Script     2.3.1      Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToP...
Script     1.0.0      Az.AppConfiguration                 {Get-AzAppConfigurationStore, Get-AzAppConfigurationStoreKe...
Script     1.3.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remo...
Script     1.0.0      Az.Attestation                      {New-AzAttestation, Get-AzAttestation, Remove-AzAttestation...
Script     1.7.3      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybr...
Script     3.1.1      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAcco...
Script     2.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmen...
Script     1.8.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile...
Script     1.1.0      Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-Az...
Script     1.10.0     Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAcc...
Script     4.24.1     Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAva...
Script     3.0.1      Az.ContainerInstance                {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-A...
Script     2.2.3      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-A...
Script     1.5.1      Az.CosmosDB                         {Get-AzCosmosDBSqlContainer, Get-AzCosmosDBSqlContainerThro...
Script     1.1.0      Az.DataBoxEdge                      {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDa...
Script     1.2.0      Az.Databricks                       {Get-AzDatabricksOutboundNetworkDependenciesEndpoint, Get-A...
Script     1.16.4     Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFac...
Script     1.0.2      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalytics...
Script     1.3.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeSto...
Script     1.0.1      Az.DataShare                        {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzD...
Script     1.1.0      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentMan...
Script     3.1.0      Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-Az...
Script     1.0.2      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy...
Script     1.1.2      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRec...
Script     1.3.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGri...
Script     1.11.0     Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEv...
Script     1.9.0      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-...
Script     4.0.1      Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get...
Script     5.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wai...
Script     1.3.2      Az.HealthcareApis                   {New-AzHealthcareApisService, Remove-AzHealthcareApisServic...
Script     2.7.4      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-Az...
Script     4.3.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, S...
Script     2.0.0      Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabasePr...
Script     1.5.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccoun...
Script     1.1.3      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociat...
Script     1.2.0      Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMa...
Script     3.0.0      Az.ManagedServices                  {Get-AzManagedServicesAssignment, Get-AzManagedServicesDefi...
Script     1.0.2      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}              
Script     1.1.1      Az.Media                            {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-...
Script     1.1.2      Az.Migrate                          {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMig...
Script     3.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile,...
Script     1.0.0      Az.MySql                            {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Get...
The runbook job failed due to a job stream being larger than 1MB, the limit that is supported by an Azure Automation sandbox. See some common ways to resolve this at https://aka.ms/AAjobstreamlimit
Script     1.1.1      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationR...
Script     3.0.1      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-A...
Script     1.5.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSum...
Script     1.0.0      Az.PostgreSql                       {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnectionS...
Script     1.1.2      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspac...
Script     1.0.3      Az.PrivateDns                       {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPriva...
Script     5.2.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServic...
Script     1.6.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheSchedule...
Script     1.0.0      Az.RedisEnterpriseCache             {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache,...
Script     1.0.3      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNam...
Script     1.1.0      Az.ResourceMover                    {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveCo...
Script     5.4.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRo...
Script     1.1.1      Az.Security                         {Get-AzSecurityAlert, Set-AzSecurityAlert, Get-AzSecurityAu...
Script     1.1.0      Az.SecurityInsights                 {Get-AzSentinelAlertRuleAction, New-AzSentinelAlertRuleActi...
Script     1.8.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-...
Script     3.0.1      Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricN...
Script     1.4.1      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSign...
The runbook job failed due to a job stream being larger than 1MB, the limit that is supported by an Azure Automation sandbox. See some common ways to resolve this at https://aka.ms/AAjobstreamlimit
Script     1.1.0      Az.SqlVirtualMachine                {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM...} 
Script     1.1.0      Az.StackHCI                         {Register-AzStackHCI, Unregister-AzStackHCI, Test-AzStackHC...
Script     4.3.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStora...
Script     1.7.0      Az.StorageSync                      {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncS...
Script     2.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsCluster...
Script     1.0.0      Az.Support                          {Get-AzSupportService, Get-AzSupportProblemClassification, ...
Script     1.1.0      Az.Synapse                          {Get-AzSynapseSparkJob, Stop-AzSynapseSparkJob, Submit-AzSy...
Script     1.1.0      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTraff...
Script     2.10.0     Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServi...
The runbook job failed due to a job stream being larger than 1MB, the limit that is supported by an Azure Automation sandbox. See some common ways to resolve this at https://aka.ms/AAjobstreamlimit
Manifest   1.0.3      Azure.Storage                       {Get-AzureStorageBlob, Get-AzureStorageBlobContent, Get-Azu...
Manifest   1.0.3      AzureRM.Automation                  {Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutoma...
Manifest   1.2.1      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet,...
Manifest   1.0.3      AzureRM.Profile                     {Enable-AzureRmDataCollection, Disable-AzureRmDataCollectio...
Manifest   1.0.3      AzureRM.Resources                   {Get-AzureRmADApplication, Get-AzureRmADGroupMember, Get-Az...
Manifest   1.0.3      AzureRM.Sql                         {Get-AzureRmSqlDatabaseThreatDetectionPolicy, Set-AzureRmSq...
Manifest   1.0.3      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, G...
Manifest   5.0.0.0    ComputerManagementDsc                                                                             
Script     0.2        GPRegistryPolicyParser              {Parse-PolFile, Read-RegistryPolicies, Create-RegistrySetti...
Script     0.0        Microsoft.PowerShell.Core                                                                         
Script     0.0        Microsoft.PowerShell.Diagnostics                                                                  
Script     0.0        Microsoft.PowerShell.Management                                                                   
Script     0.0        Microsoft.PowerShell.Security                                                                     
Script     0.0        Microsoft.PowerShell.Utility                                                                      
Script     0.0        Microsoft.WSMan.Management                                                                        
Binary     1.0        Orchestrator.AssetManagement.Cmd... {Get-AutomationVariable, Set-AutomationVariable, Get-Automa...
Manifest   2.9.0.0    PSDscResources                                                                                    
Manifest   2.1.0.0    SecurityPolicyDsc                                                                                 
Manifest   1.0        StateConfigCompositeResources                                                                     
Manifest   1.1        xDSCDomainjoin                                                                                    
Manifest   1.1.0.0    xPowerShellExecutionPolicy          {Get-TargetResource, Test-TargetResource, Set-TargetResource} 
Manifest   1.1.0.0    xRemoteDesktopAdmin                                                                               
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}         
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-Packag...
Script     3.4.0      Pester                              {Describe, Context, It, Should...}                            
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}  
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Set-PSReadlineKeyHandler, Remove...
    Directory: C:\Windows\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Manifest   1.0.0.0    AppBackgroundTask                   {Disable-AppBackgroundTaskDiagnosticLog, Enable-AppBackgrou...
Manifest   2.0.0.0    Appx                                {Add-AppxPackage, Get-AppxPackage, Get-AppxPackageManifest,...
Manifest   2.0.0.0    BitsTransfer                        {Add-BitsFile, Complete-BitsTransfer, Get-BitsTransfer, Rem...
Manifest   1.0.0.0    CimCmdlets                          {Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, ...
Manifest   1.0        Defender                            {Get-MpPreference, Set-MpPreference, Add-MpPreference, Remo...
Manifest   1.0.0.0    DeliveryOptimization                {Get-DeliveryOptimizationStatus, Get-DeliveryOptimizationPe...
Manifest   1.0.0.0    DirectAccessClientComponents        {Disable-DAManualEntryPointSelection, Enable-DAManualEntryP...
Script     3.0        Dism                                {Add-AppxProvisionedPackage, Add-WindowsDriver, Add-Windows...
Manifest   1.0.0.0    DnsClient                           {Resolve-DnsName, Clear-DnsClientCache, Get-DnsClient, Get-...
Manifest   1.0.0.0    EventTracingManagement              {Start-EtwTraceSession, New-EtwTraceSession, Get-EtwTraceSe...
Manifest   2.0.0.0    International                       {Get-WinDefaultInputMethodOverride, Set-WinDefaultInputMeth...
Manifest   1.0.0.0    iSCSI                               {Get-IscsiTargetPortal, New-IscsiTargetPortal, Remove-Iscsi...
Script     1.0.0.0    ISE                                 {New-IseSnippet, Import-IseSnippet, Get-IseSnippet}           
Manifest   1.0.0.0    Kds                                 {Add-KdsRootKey, Get-KdsRootKey, Test-KdsRootKey, Set-KdsCo...
Manifest   1.0.1.0    Microsoft.PowerShell.Archive        {Compress-Archive, Expand-Archive}                            
Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics    {Get-WinEvent, Get-Counter, Import-Counter, Export-Counter...}
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript, Stop-Transcript}                           
Manifest   1.0.0.0    Microsoft.PowerShell.LocalAccounts  {Add-LocalGroupMember, Disable-LocalUser, Enable-LocalUser,...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path...}
Script     1.0        Microsoft.PowerShell.ODataUtils     Export-ODataEndpointProxy                                     
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Credential...}     
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Format-List, Format-Custom, Format-Table, Format-Wide...}    
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-WSManCredSS...
Manifest   1.0        MMAgent                             {Disable-MMAgent, Enable-MMAgent, Set-MMAgent, Get-MMAgent...}
Manifest   1.0.0.0    MsDtc                               {New-DtcDiagnosticTransaction, Complete-DtcDiagnosticTransa...
Manifest   2.0.0.0    NetAdapter                          {Disable-NetAdapter, Disable-NetAdapterBinding, Disable-Net...
Manifest   1.0.0.0    NetConnection                       {Get-NetConnectionProfile, Set-NetConnectionProfile}          
Manifest   1.0.0.0    NetEventPacketCapture               {New-NetEventSession, Remove-NetEventSession, Get-NetEventS...
Manifest   2.0.0.0    NetLbfo                             {Add-NetLbfoTeamMember, Add-NetLbfoTeamNic, Get-NetLbfoTeam...
Manifest   1.0.0.0    NetNat                              {Get-NetNat, Get-NetNatExternalAddress, Get-NetNatStaticMap...
Manifest   2.0.0.0    NetQos                              {Get-NetQosPolicy, Set-NetQosPolicy, Remove-NetQosPolicy, N...
Manifest   2.0.0.0    NetSecurity                         {Get-DAPolicyChange, New-NetIPsecAuthProposal, New-NetIPsec...
Manifest   1.0.0.0    NetSwitchTeam                       {New-NetSwitchTeam, Remove-NetSwitchTeam, Get-NetSwitchTeam...
Manifest   1.0.0.0    NetTCPIP                            {Get-NetIPAddress, Get-NetIPInterface, Get-NetIPv4Protocol,...
Manifest   1.0.0.0    NetworkConnectivityStatus           {Get-DAConnectionStatus, Get-NCSIPolicyConfiguration, Reset...
Manifest   1.0.0.0    NetworkSwitchManager                {Disable-NetworkSwitchEthernetPort, Enable-NetworkSwitchEth...
Manifest   1.0.0.0    NetworkTransition                   {Add-NetIPHttpsCertBinding, Disable-NetDnsTransitionConfigu...
Manifest   1.0.0.0    PcsvDevice                          {Get-PcsvDevice, Start-PcsvDevice, Stop-PcsvDevice, Restart...
Manifest   1.0.0.0    PKI                                 {Add-CertificateEnrollmentPolicyServer, Export-Certificate,...
Manifest   1.0.0.0    PnpDevice                           {Get-PnpDevice, Get-PnpDeviceProperty, Enable-PnpDevice, Di...
Manifest   1.1        PrintManagement                     {Add-Printer, Add-PrinterDriver, Add-PrinterPort, Get-Print...
Script     3.0        Provisioning                        {Install-ProvisioningPackage, Export-ProvisioningPackage, I...
Manifest   1.1        PSDesiredStateConfiguration         {Set-DscLocalConfigurationManager, Start-DscConfiguration, ...
Script     1.0.0.0    PSDiagnostics                       {Disable-PSTrace, Disable-PSWSManCombinedTrace, Disable-WSM...
Binary     1.1.0.0    PSScheduledJob                      {New-JobTrigger, Add-JobTrigger, Remove-JobTrigger, Get-Job...
Manifest   2.0.0.0    PSWorkflow                          {New-PSWorkflowExecutionOption, New-PSWorkflowSession, nwsn}  
Manifest   1.0.0.0    PSWorkflowUtility                   Invoke-AsWorkflow                                             
Manifest   1.0.0.0    ScheduledTasks                      {Get-ScheduledTask, Set-ScheduledTask, Register-ScheduledTa...
Manifest   2.0.0.0    SecureBoot                          {Confirm-SecureBootUEFI, Set-SecureBootUEFI, Get-SecureBoot...
Manifest   2.0.0.0    SmbShare                            {Get-SmbShare, Remove-SmbShare, Set-SmbShare, Block-SmbShar...
Manifest   2.0.0.0    SmbWitness                          {Get-SmbWitnessClient, Move-SmbWitnessClient, gsmbw, msmbw...}
Manifest   1.0.0.0    StartLayout                         {Export-StartLayout, Import-StartLayout, Export-StartLayout...
Manifest   2.0.0.0    Storage                             {Add-InitiatorIdToMaskingSet, Add-PartitionAccessPath, Add-...
Manifest   2.0.0.0    TLS                                 {New-TlsSessionTicketKey, Enable-TlsSessionTicketKey, Disab...
Manifest   1.0.0.0    TroubleshootingPack                 {Get-TroubleshootingPack, Invoke-TroubleshootingPack}         
Manifest   2.0.0.0    TrustedPlatformModule               {Get-Tpm, Initialize-Tpm, Clear-Tpm, Unblock-Tpm...}          
Manifest   2.0.0.0    VpnClient                           {Add-VpnConnection, Set-VpnConnection, Remove-VpnConnection...
Manifest   1.0.0.0    Wdac                                {Get-OdbcDriver, Set-OdbcDriver, Get-OdbcDsn, Add-OdbcDsn...} 
Manifest   1.0.0.0    WindowsDeveloperLicense             {Get-WindowsDeveloperLicense, Unregister-WindowsDeveloperLi...
Script     1.0        WindowsErrorReporting               {Enable-WindowsErrorReporting, Disable-WindowsErrorReportin...
Manifest   1.0.0.0    WindowsSearch                       {Get-WindowsSearchSetting, Set-WindowsSearchSetting}          
Manifest   1.0.0.0    WindowsUpdate                       Get-WindowsUpdateLog
```

### Error output

```PowerShell
ServerMessage    : UserErrorPreviewFeatureEnrollmentRequired: The operation you are trying requires enrollment into a 
                   feature that is currently in limited preview. Please enroll your subscription in the limited preview 
                   and retry the operation, or retry after this feature is availble to all customers. 
                   (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse   : {BadRequest}
RequestMessage   : {POST https://management.azure.com/subscriptions/0d5f0c34-d84e-4ca7-8c07-74c2a4d86f20/resourceGroups/
                   ALB_RG1/providers/Microsoft.RecoveryServices/vaults/testarchivevault/backupFabrics/Azure/protectionCo
                   ntainers/IaasVMContainer%3Biaasvmcontainerv2%3Balb_rg1%3Bredhatvmtest/protectedItems/VM%3Biaasvmconta
                   inerv2%3Balb_rg1%3Bredhatvmtest/recoveryPointsRecommendedForMove?api-version=2021-10-01}
RequestId        : a1eef649-9e86-48f9-b039-2af7c1e3d64a
InnerException   : False
Exception        : Microsoft.Rest.Azure.CloudException: The operation you are trying requires enrollment into a feature 
                   that is currently in limited preview. Please enroll your subscription in the limited preview and 
                   retry the operation, or retry after this feature is availble to all customers.
                      at Microsoft.Azure.Management.RecoveryServices.Backup.RecoveryPointsRecommendedForMoveOperations.<
                   ListWithHttpMessagesAsync>d__5.MoveNext()
Message          : The operation you are trying requires enrollment into a feature that is currently in limited 
                   preview. Please enroll your subscription in the limited preview and retry the operation, or retry 
                   after this feature is availble to all customers.
StackTrace       :    at Microsoft.Azure.Management.RecoveryServices.Backup.RecoveryPointsRecommendedForMoveOperations.<
                   ListWithHttpMessagesAsync>d__5.MoveNext()
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : InvalidOperation: (:) [Get-AzRecoveryS...chivableRPGroup], CloudException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, <No file>: line 25

InnerException   : False
Exception        : System.Management.Automation.CommandNotFoundException: The term 
                   'Get-AzRecoveryServicesRecommendedArchivableRPGroup' is not recognized as the name of a cmdlet, 
                   function, script file, or operable program. Check the spelling of the name, or if a path was 
                   included, verify that the path is correct and try again.
                      at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, 
                   CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin 
                   commandOrigin, ExecutionContext context)
                      at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, 
                   CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                      at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                      at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, 
                   CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] 
                   redirections, ExecutionContext context)
                      at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, 
                   CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] 
                   commandRedirections, FunctionContext funcContext)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
Message          : The term 'Get-AzRecoveryServicesRecommendedArchivableRPGroup' is not recognized as the name of a 
                   cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was 
                   included, verify that the path is correct and try again.
StackTrace       :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, 
                   CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin 
                   commandOrigin, ExecutionContext context)
                      at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, 
                   CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                      at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                      at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, 
                   CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] 
                   redirections, ExecutionContext context)
                      at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, 
                   CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] 
                   commandRedirections, FunctionContext funcContext)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : ObjectNotFound: (Get-AzRecoveryS...chivableRPGroup:String) [], CommandNotFoundException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, <No file>: line 23
InnerException   : False
Exception        : System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. 
                   Retrieve the LoaderExceptions property for more information.
                      at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                      at System.Reflection.Assembly.GetTypes()
                      at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                      at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                      at System.Management.Automation.CommandProcessorBase.Complete()
Message          : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more 
                   information.
StackTrace       :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                      at System.Reflection.Assembly.GetTypes()
                      at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                      at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                      at System.Management.Automation.CommandProcessorBase.Complete()
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : NotSpecified: (:) [Add-Type], ReflectionTypeLoadException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, C:\Modules\Global\Az.Accounts\Az.Accounts.psm1: line 39
                   at Preload-Assembly, C:\Modules\Global\Az.Accounts\Az.Accounts.psm1: line 36
                   at <ScriptBlock>, C:\Modules\Global\Az.Accounts\Az.Accounts.psm1: line 88
                   at <ScriptBlock>, <No file>: line 6
```

**Comment by adityabalaji-msft** [comment]
Adding @hiaga to look into this

**Comment by Debpriya1994** [comment]
The feature for Azure VMs is generally available only in 5 regions as of now (Australia East, South East Asia, West Central US, South Central US and Central India). For the remaining region whitelisting is still required. This is defined in the support Matrix https://docs.microsoft.com/en-us/azure/backup/archive-tier-support#supported-regions.

Do let me know if this solves the issue.

**Comment by adityabalaji-msft** [comment]
Closing the issue as it was expected behaviour. Feel free to reach out in case of any questions
