### ISSUE TITLE
Unable to unassigns User from Azure Virtual Desktop Host Pool using Update-AzWvdSessionHost

### ISSUE THREAD

**Issue by kiazhi** [Azure/azure-powershell#18017]
### Description

According to the documentation below,
- https://docs.microsoft.com/en-us/azure/virtual-desktop/configure-host-pool-personal-desktop-assignment-type#how-to-unassign-a-personal-desktop
I should be able to unassigns User from a session host with the command parameters `-AssignedUser ""` with `-Force` like below.
```PowerShell
Update-AzWvdSessionHost -HostPoolName <hostpoolname> -Name <sessionhostname> -ResourceGroupName <resourcegroupname> -AssignedUser "" -Force
```

But it is not achievable at all according to the documentation.

### Issue script & Debug output

```PowerShell
PS /Users/ryentang/repository> Update-AzWvdSessionHost `
>>   -ResourceGroupName "avd-components-uat-rvqfdd1b" `
>>   -HostPoolName "avd-host-pool-rvqfdd1b" `
>>   -Name "fb36d8-avd-host" `
>>   -AssignedUser ""
DEBUG: 10:51:44 - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Update-AzWvdSessionHost_UpdateExpanded'
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /subscriptions/b52e02b9-4a59-4f7e-bd69-e9c61a7bffe5/resourceGroups/avd-components-uat-rvqfdd1b/providers/Microsoft.DesktopVirtualization/hostPools/avd-host-pool-rvqfdd1b/sessionHosts/fb36d8-avd-host?api-version=2021-07-12
DEBUG: RequestCreated: /subscriptions/b52e02b9-4a59-4f7e-bd69-e9c61a7bffe5/resourceGroups/avd-components-uat-rvqfdd1b/providers/Microsoft.DesktopVirtualization/hostPools/avd-host-pool-rvqfdd1b/sessionHosts/fb36d8-avd-host?api-version=2021-07-12
DEBUG: HeaderParametersAdded: 
DEBUG: BodyContentSet: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/b52e02b9-4a59-4f7e-bd69-e9c61a7bffe5/resourceGroups/avd-components-uat-rvqfdd1b/providers/Microsoft.DesktopVirtualization/hostPools/avd-host-pool-rvqfdd1b/sessionHosts/fb36d8-avd-host?api-version=2021-07-12

Headers:
x-ms-unique-id                : 6
x-ms-client-request-id        : 619ae214-fb29-4252-826c-6c09b578cdae
CommandName                   : Update-AzWvdSessionHost
FullCommandName               : Update-AzWvdSessionHost_UpdateExpanded
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v7.5.0,PSVersion/v7.2.1,Az.DesktopVirtualization/3.1.0

Body:
{
  "properties": {
    "assignedUser": ""
  }
}


DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
X-Rate-Limit-Limit            : 0
X-Rate-Limit-Remaining        : 9223372036854775807
X-Rate-Limit-Reset            : 0
x-ms-opsarmpath64             : L3N1YnNjcmlwdGlvbnMvYjUyZTAyYjktNGE1OS00ZjdlLWJkNjktZTljNjFhN2JmZmU1L3Jlc291cmNlR3JvdXBzL2F2ZC1jb21wb25lbnRzLXVhdC1ydnFmZGQxYi9wcm92aWRlcnMvTWljcm9zb2Z0LkRlc2t0b3BWaXJ0dWFsaXphdGlvbi9ob3N0UG9vbHMvYXZkLWhvc3QtcG9vbC1ydnFmZGQxYi9zZXNzaW9uSG9zdHMvZmIzNmQ4LWF2ZC1ob3N0
x-ms-lamport-ts               : 2344687440
x-ms-correlation-id           : 812e866f-3f30-422f-a6c6-da7ee8269c65
x-ms-request-id               : 619ae214-fb29-4252-826c-6c09b578cdae
X-Content-Type-Options        : nosniff
Set-Cookie                    : ARRAffinity=7370067215f49a50b9568dd2af2b20f273b5ad9b4ce5a0042e2457ca35096ce0;Path=/;HttpOnly;Secure;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com,ARRAffinitySameSite=7370067215f49a50b9568dd2af2b20f273b5ad9b4ce5a0042e2457ca35096ce0;Path=/;HttpOnly;SameSite=None;Secure;Domain=rdarmprovider-g-us-r0.wvd.microsoft.com
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 5528e78f-e4e8-40d0-a1ac-8d59de7426fd
x-ms-routing-request-id       : SOUTHEASTASIA:20220429T025146Z:5528e78f-e4e8-40d0-a1ac-8d59de7426fd
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Date                          : Fri, 29 Apr 2022 02:51:45 GMT

Body:
{
  "error": {
    "code": "400",
    "message": "ActivityId: 812e866f-3f30-422f-a6c6-da7ee8269c65 Error: To unassign a user, please use the -force flag."
  }
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
Update-AzWvdSessionHost_UpdateExpanded: ActivityId: 812e866f-3f30-422f-a6c6-da7ee8269c65 Error: To unassign a user, please use the -force flag.
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSCloudException: InternalException' from response
DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: AzureQoSEvent: Module: Az.DesktopVirtualization:3.1.0; CommandName: Update-AzWvdSessionHost_UpdateExpanded; PSVersion: 7.2.1; IsSuccess: False; Duration: 00:00:00; Exception: InternalException;
DEBUG: Finish sending metric.
DEBUG: CmdletEndProcessing: 
PS /Users/ryentang/repository> Update-AzWvdSessionHost `
>>   -ResourceGroupName "avd-components-uat-rvqfdd1b" `
>>   -HostPoolName "avd-host-pool-rvqfdd1b" `
>>   -Name "fb36d8-avd-host" `
>>   -AssignedUser "" `
>>   -Force
Update-AzWvdSessionHost: 
Line |
   6 |    -Force
     |    ~~~~~~
     | A parameter cannot be found that matches parameter name 'Force'.
```

### Environment data

```PowerShell
PS /Users/ryentang/repository> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS /Users/ryentang/repository> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     7.5.0                 Az                                  
Script     2.7.6                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.1.2                 Az.Advisor                          {Disable-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Get-AzAdvisorConfiguration, Ge…
Script     3.1.3                 Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNodePool…}
Script     1.1.4                 Az.AnalysisServices                 {Add-AzAnalysisServicesAccount, Export-AzAnalysisServicesInstanceLog, Get-AzAnalysisServicesServ…
Script     2.3.2                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToG…
Script     1.1.0                 Az.AppConfiguration                 {Get-AzAppConfigurationStore, Get-AzAppConfigurationStoreKey, New-AzAppConfigurationStore, New-A…
Script     1.3.1                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplicationInsightsContinuous…
Script     1.0.0                 Az.Attestation                      {Add-AzAttestationPolicySigner, Get-AzAttestation, Get-AzAttestationPolicy, Get-AzAttestationPol…
Script     1.7.3                 Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomati…
Script     3.2.0                 Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchComputeNodeScheduling, Disable-AzBatchJob, Disable-AzB…
Script     2.0.0                 Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzBillingProfile…}
Script     1.8.3                 Az.Cdn                              {Confirm-AzCdnEndpointProbeURL, Disable-AzCdnCustomDomain, Disable-AzCdnCustomDomainHttps, Enabl…
Script     1.1.0                 Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-AzCloudServiceNetworkInterface, Get-AzC…
Script     1.11.0                Az.CognitiveServices                {Add-AzCognitiveServicesAccountNetworkRule, Get-AzCognitiveServicesAccount, Get-AzCognitiveServi…
Script     4.26.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     3.1.0                 Az.ContainerInstance                {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-AzContainerInstanceCachedImage, Get-Az…
Script     2.2.3                 Az.ContainerRegistry                {Connect-AzContainerRegistry, Get-AzContainerRegistry, Get-AzContainerRegistryCredential, Get-Az…
Script     1.7.0                 Az.CosmosDB                         {Get-AzCosmosDBAccount, Get-AzCosmosDBAccountKey, Get-AzCosmosDBCassandraKeyspace, Get-AzCosmosD…
Script     1.1.0                 Az.DataBoxEdge                      {Get-AzDataBoxEdgeBandwidthSchedule, Get-AzDataBoxEdgeDevice, Get-AzDataBoxEdgeJob, Get-AzDataBo…
Script     1.2.0                 Az.Databricks                       {Get-AzDatabricksOutboundNetworkDependenciesEndpoint, Get-AzDatabricksVNetPeering, Get-AzDatabri…
Script     1.16.6                Az.DataFactory                      {Add-AzDataFactoryV2DataFlowDebugSessionPackage, Add-AzDataFactoryV2TriggerSubscription, Get-AzD…
Script     1.0.2                 Az.DataLakeAnalytics                {Add-AzDataLakeAnalyticsDataSource, Add-AzDataLakeAnalyticsFirewallRule, Get-AzDataLakeAnalytics…
Script     1.3.0                 Az.DataLakeStore                    {Add-AzDataLakeStoreFirewallRule, Add-AzDataLakeStoreItemContent, Add-AzDataLakeStoreTrustedIdPr…
Script     1.0.1                 Az.DataShare                        {Get-AzDataShare, Get-AzDataShareAccount, Get-AzDataShareDataSet, Get-AzDataShareDataSetMapping…}
Script     1.1.0                 Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, Get-AzDeploymentManagerRollout, Get-AzDeploymentManagerS…
Script     3.1.0                 Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-AzWvdApplication, Get-AzWvdApplicationG…
Script     1.0.2                 Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtl…
Script     1.1.2                 Az.Dns                              {Add-AzDnsRecordConfig, Get-AzDnsRecordSet, Get-AzDnsZone, New-AzDnsRecordConfig…}
Script     1.3.0                 Az.EventGrid                        {Get-AzEventGridDomain, Get-AzEventGridDomainKey, Get-AzEventGridDomainTopic, Get-AzEventGridSub…
Script     1.11.1                Az.EventHub                         {Add-AzEventHubIPRule, Add-AzEventHubVirtualNetworkRule, Get-AzEventHub, Get-AzEventHubAuthoriza…
Script     1.9.0                 Az.FrontDoor                        {Disable-AzFrontDoorCustomDomainHttps, Enable-AzFrontDoorCustomDomainHttps, Get-AzFrontDoor, Get…
Script     4.0.2                 Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan, Get-AzFunctionApp…
Script     5.0.1                 Az.HDInsight                        {Add-AzHDInsightClusterIdentity, Add-AzHDInsightComponentVersion, Add-AzHDInsightConfigValue, Ad…
Script     1.3.2                 Az.HealthcareApis                   {Get-AzHealthcareApisService, New-AzHealthcareApisService, Remove-AzHealthcareApisService, Set-A…
Script     2.7.4                 Az.IotHub                           {Add-AzIotHubCertificate, Add-AzIotHubConfiguration, Add-AzIotHubDeployment, Add-AzIotHubDevice…}
Script     4.4.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultM…
Script     2.1.0                 Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabasePrincipal, Get-AzKustoAttachedDatabaseC…
Script     1.5.0                 Az.LogicApp                         {Get-AzIntegrationAccount, Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, …
Script     1.1.3                 Az.MachineLearning                  {Add-AzMlWebServiceRegionalProperty, Export-AzMlWebService, Get-AzMlCommitmentAssociation, Get-A…
Script     1.2.0                 Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfiguration, Get-AzMainten…
Script     3.0.0                 Az.ManagedServices                  {Get-AzManagedServicesAssignment, Get-AzManagedServicesDefinition, Get-AzManagedServicesMarketpl…
Script     1.0.2                 Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            {Get-AzMediaService, Get-AzMediaServiceKey, Get-AzMediaServiceNameAvailability, New-AzMediaServi…
Script     1.1.2                 Az.Migrate                          {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMigrateProject, Get-AzMigrateReplication…
Script     3.0.1                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2…}
Script     1.0.0                 Az.MySql                            {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Get-AzMySqlFirewallRule, Get-AzMySqlFlex…
Script     4.16.1                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, …
Script     1.1.1                 Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Ge…
Script     3.1.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsLinuxCustomLogColle…
Script     1.5.0                 Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyMetadata, Get-AzPolicyRemediation, Get-AzPolicyState…}
Script     1.1.0                 Az.PostgreSql                       {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnectionString, Get-AzPostgreSqlFirewallRule, …
Script     1.1.2                 Az.PowerBIEmbedded                  {Get-AzPowerBIEmbeddedCapacity, Get-AzPowerBIWorkspace, Get-AzPowerBIWorkspaceCollection, Get-Az…
Script     1.0.3                 Az.PrivateDns                       {Add-AzPrivateDnsRecordConfig, Get-AzPrivateDnsRecordSet, Get-AzPrivateDnsVirtualNetworkLink, Ge…
Script     5.3.1                 Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Backup-AzRecoveryServicesBackupItem, Cop…
Script     1.6.0                 Az.RedisCache                       {Export-AzRedisCache, Get-AzRedisCache, Get-AzRedisCacheFirewallRule, Get-AzRedisCacheKey…}
Script     1.0.0                 Az.RedisEnterpriseCache             {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCacheDatabase, …
Script     1.0.3                 Az.Relay                            {Get-AzRelayAuthorizationRule, Get-AzRelayHybridConnection, Get-AzRelayKey, Get-AzRelayNamespace…
Script     1.1.0                 Az.ResourceMover                    {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveCollection, Get-AzResourceMoverMoveReso…
Script     5.6.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     1.2.0                 Az.Security                         {Add-AzSecurityAdaptiveNetworkHardening, Add-AzSecuritySqlVulnerabilityAssessmentBaseline, Confi…
Script     1.1.0                 Az.SecurityInsights                 {Get-AzSentinelAlertRule, Get-AzSentinelAlertRuleAction, Get-AzSentinelAlertRuleTemplate, Get-Az…
Script     1.8.1                 Az.ServiceBus                       {Add-AzServiceBusIPRule, Add-AzServiceBusVirtualNetworkRule, Complete-AzServiceBusMigration, Get…
Script     3.0.2                 Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricManagedClusterClientCertificate, Add-A…
Script     1.4.1                 Az.SignalR                          {Get-AzSignalR, Get-AzSignalRKey, Get-AzSignalRUsage, New-AzSignalR…}
Script     3.8.0                 Az.Sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElasticJobStep, Add-AzSqlElasticJobTarget, Add-AzSql…
Script     1.1.0                 Az.SqlVirtualMachine                {Get-AzAvailabilityGroupListener, Get-AzSqlVM, Get-AzSqlVMGroup, New-AzAvailabilityGroupListener…
Script     1.1.1                 Az.StackHCI                         {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestation, Disable-AzStackHCIRemoteSupport, En…
Script     4.5.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAcc…
Script     1.7.0                 Az.StorageSync                      {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyncGroup, Get-AzStorageSyncServer, Get-AzStorageS…
Script     2.0.0                 Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsClusterStreamingJob, Get-AzStreamAnalyticsDe…
Script     1.0.0                 Az.Support                          {Get-AzSupportProblemClassification, Get-AzSupportService, Get-AzSupportTicket, Get-AzSupportTic…
Script     1.3.0                 Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTriggerSubscription, Clear-AzSynapseSqlP…
Script     1.1.0                 Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Add-AzTr…
Script     2.11.1                Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRouting, Edit-AzWebAppBackupConfiguration…
```

### Error output

```PowerShell
PS /Users/ryentang/repository> Resolve-AzError
DEBUG: 10:54:57 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 10:54:57 - using account id '879ebfe2-f054-47f6-91cc-134d7e25ef60'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 37

Message        : A parameter cannot be found that matches parameter name 'Force'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, 
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Update-AzWvdSessionHost}
Line           :   -Force
Position       : At line:6 char:3
                 +   -Force
                 +   ~~~~~~
HistoryId      : 37


   HistoryId: 36

Message        : [400] : ActivityId: 812e866f-3f30-422f-a6c6-da7ee8269c65 Error: To unassign a user, please use the -force flag.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Update-AzWvdSessionHost_UpdateExpanded}
Line           : Update-AzWvdSessionHost `
                 
Position       : At line:1 char:1
                 + Update-AzWvdSessionHost `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 36
```

**Comment by russhenderson86** [comment]
Appears this is still an issue. This makes large scale tasks difficult due to this issue and the functionality does not yet exist in the Azure CLI. Is there a known workaround?

**Comment by WplusAzureAuto** [comment]
still an issue on version 3.1.0 for module Az.DesktopVirtualization

**Comment by XRTce** [comment]
Still getting the issue in 3.1.1
I helped myself and wrote a function which uses the rest api to unassign a session host:
```
function Unassign-AzWvdSessionHost{
    [CmdletBinding(PositionalBinding=$false)]
    param(
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        $HostPoolName,
        [Parameter(Mandatory)]
        [Alias('Name')]
        [ValidateNotNullOrEmpty()]
        $SessionHostName,
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        $ResourceGroupName,
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        $SubscriptionID,
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        $Token
    )
    Begin{
        $SessionHostShortName = $SessionHostName.Split('/')[1]
    }
    Process{
        $session = New-Object Microsoft.PowerShell.Commands.WebRequestSession
        $session.UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47"
        $result = Invoke-WebRequest -Uri "https://management.azure.com/subscriptions/$SubscriptionID/resourcegroups/$ResourceGroupName/providers/Microsoft.DesktopVirtualization/hostpools/$HostPoolName/sessionhosts/$($SessionHostShortName)?api-version=2022-02-10-preview&force=true" `
        -Method "PATCH" `
        -WebSession $session `
        -Headers @{
        "Authorization"="Bearer $Token"
        "Accept"="*/*"
        } `
        -ContentType "application/json" `
        -Body "{`"properties`": {`"allowNewSession`": true,`"assignedUser`": `"`"}}"

         if($result.StatusCode -eq "200"){
             Write-Host "Unassigned session host $SessionHostName" -ForegroundColor Green
         }
    }
}
```
an access token can be generated with the following command out of the Az POSH Module:
`connect-azaccount -tenant "$tenantID"`
`$Token = (Get-AzAccessToken).Token`

**Comment by dcaro** [comment]
@eva-seydl PTAL

**Comment by vsquare-engg** [comment]
function Unassign-AzWvdSessionHost is not working, can validate again?

**Comment by WiseK** [comment]
@SatishBoddu-MSFT  
Update-AzWvdSessionHost -HostPoolName <hostpoolname> -Name <sessionhostname> -ResourceGroupName <resourcegroupname> -AssignedUser "" -Force

This still doesn't work correctly. 
Update-AzWvdSessionHost_UpdateExpanded: ActivityId:  Error: To unassign a user, please use the -force flag.

When you use -force you get this error.
Update-AvdSessionHost: Cannot validate argument on parameter 'AssignedUser'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

**Comment by WiseK** [comment]
You can use Rest API 
https://learn.microsoft.com/en-us/rest/api/desktopvirtualization/session-hosts/update?tabs=HTTP#code-try-0


$subscriptionId = "subid"
$ResourceGroupName = 'rgna'
$hostpoolname = "hpname"
$SessionHostName = "AVD"
$baseUrl = https://management.azure.com/subscriptions/{0}/resourceGroups/{1}/providers/Microsoft.DesktopVirtualization/hostpools/{2}/sessionHosts/{3}?api-version=2022-02-10-preview&force=true -f $subscriptionId, $ResourceGroupName, $hostpoolname, $SessionHostName
$Body = @{
  properties = @{
      allowNewSession = "true"
        assignedUser = ""
  }
}
$parameters = @{
    URI     = $baseUrl 
    Method  = "PATCH"
    Headers = $token
    Body = $Body | ConvertTo-Json
}
$hostpoolToken = Invoke-RestMethod @parameters

**Comment by cookmatt** [comment]
Thank you @WiseK and @XRTce you pointed me in the right direction but I thought it might help others to share how I approached the REST api call using Invoke-AzRestMethod instead of Invoke-WebRequest

As it happened I had previously obtained the SessionHost object via it's parent HostPool and stored it as $sessionHost.  That simplified things because the Id property of that object actually has the Path information you need for the API call which means you don't need to assemble it.

So I did this -

            $settings=@{
                Properties=@{
                    assignedUser=''
                    allowNewSession=$True
                }
            }            
            Invoke-AzRestMethod -Path "$($sessionHost.Id)?api-version=2022-09-09&force=true" -method 'PATCH' -Payload (ConvertTo-Json -InputObject $settings)

**Comment by sefriend** [comment]
Hi all, 
Just want to quickly mention that we have published the PowerShell commands for unassigning and reassigning personal desktops in our documentation here - https://learn.microsoft.com/en-us/azure/virtual-desktop/configure-host-pool-personal-desktop-assignment-type#unassign-a-personal-desktop-using-powershell. Check it out!

**Comment by sefriend** [comment]
> > Hi all, Just want to quickly mention that we have published the PowerShell commands for unassigning and reassigning personal desktops in our documentation here - https://learn.microsoft.com/en-us/azure/virtual-desktop/configure-host-pool-personal-desktop-assignment-type#unassign-a-personal-desktop-using-powershell. Check it out!
> 
> This is all well and good, but is there some reason nobody can be bothered to just fix the cmdlet described in the OP? If the option is going to exist, it would be great if it worked.

Thanks for the response. We are working to get the new PowerShell version that includes these changes. It will come in the future but this should be the PowerShell you use in the meantime.

**Comment by cdiskan** [comment]
@sefriend 

Any updates on this? It is six months later and is still broken. Either the option should be removed from the PowerShell module, or it should be fixed. Right now this github issue is the only record of this being a known issue.
