### ISSUE TITLE
Update-AzADDomainService : The certificate or password provided for LDAPs is invalid

### ISSUE THREAD

**Issue by alex-3sr** [Azure/azure-powershell#18075]
### Description

Hi,

I'm trying to use Preview of module Az.ADDomainServices in actual version 0.1.0
I just try to update LDAPS certificate with a simple command like ->
```ps
$adds_rg_name = "RG-TEST"
$adds_domain = "contoso.com"
$ldaps_pfx_path = "C:\TEMP\certificate.pfx"
$ldaps_pfx_pass = "MyStrongPassword" | ConvertTo-SecureString -Force -AsPlainText
$adds_rg = Get-AzResourceGroup -Name $adds_rg_name
$adds = Get-AzADDomainService -Name $adds_domain -ResourceGroupName $adds_rg.ResourceGroupName
$ldaps_update = Update-AzADDomainService -InputObject $adds -LdapSettingLdaps $true -LdapSettingPfxCertificate $ldaps_pfx_path -LdapSettingPfxCertificatePassword $ldaps_pfx_pass
```

But I've this error : 
`
Update-AzADDomainService_UpdateViaIdentityExpanded: script.ps1:283:13
Line |
 283 |              Az.ADDomainServices.internal\Update-AzADDomainService @PS …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The certificate or password provided for LDAPs is invalid.
`

If I use the same file and password directly from GUI, all is working as expected !

Thanks
Regards
Alexandre

### Issue script & Debug output

```PowerShell
HTTP Method:
PATCH

Absolute Uri:
https://management.azure.com/subscriptions/xxxx/resourceGroups/RES-INFRA/providers/Microsoft.AAD/domainServices/contoso.com?api-version=2020-01-01

Headers:
x-ms-unique-id                : 14
x-ms-client-request-id        : 3713ef7f-e743-49ec-9713-9cd67e295827
CommandName                   : Az.ADDomainServices.internal\Update-AzADDomainService
FullCommandName               : Update-AzADDomainService_UpdateViaIdentityExpanded
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v7.1.0,PSVersion/v7.2.3,Az.ADDomainServices/0.1.0

Body:
{
  "properties": {
    "ldapsSettings": {
      "ldaps": "True",
      "pfxCertificate": "C:\\TEMP\\certificate.pfx",
      "pfxCertificatePassword": "MyStrongPassword"
    }
  }
}


DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Accepted

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : W/"datetime'2022-05-09T09%3A36%3A26.1385566Z'"
Location                      : https://management.azure.com/subscriptions/xxxx/providers/Microsoft.AAD/locations/westeurope/operationResults/xxxx?api-version=2020-01-01&operationResultResponseType=Location
x-ms-request-id               : 2fe95953-3d8d-4133-b3b9-c4692ba8bafe
Azure-AsyncOperation          : https://management.azure.com/subscriptions/xxxx/providers/Microsoft.AAD/locations/westeurope/operationResults/xxxx?api-version=2020-01-01
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 8b94e009-aec9-4c67-92df-67aa4e4c6bb3
x-ms-routing-request-id       : FRANCECENTRAL:20220509T093633Z:8b94e009-aec9-4c67-92df-67aa4e4c6bb3
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Mon, 09 May 2022 09:36:33 GMT

Body:
{
  "id": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.AAD/domainServices/contoso.com",
  "name": "contoso.com",
  "type": "Microsoft.AAD/domainServices",
  "etag": "W/\"datetime'2022-05-09T09%3A36%3A26.1385566Z'\"",
  "location": "westeurope",
  "properties": {
    "version": 2,
    "tenantId": "xxxx",
    "domainName": "contoso.com",
    "deploymentId": "015ad100-5930-47ca-aeec-3648ec70e68f",
    "syncOwner": "015ad100-5930-47ca-aeec-3648ec70e68f",
    "replicaSets": [
      {
        "replicaSetId": "015ad100-5930-47ca-aeec-3648ec70e68f",
        "location": "West Europe",
        "subnetId": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Network/virtualNetworks/xxxx/subnets/xxxx",
        "domainControllerIpAddress": [
          "x.x.x.x"
        ],
        "externalAccessIpAddress": "",
        "serviceStatus": "Running"
      }
    ],
    "ldapsSettings": {
      "ldaps": "Enabled",
      "publicCertificate": "xxxx",
      "certificateThumbprint": "xxxx",
      "certificateNotAfter": "2022-07-30T11:12:48Z",
      "externalAccess": "Disabled"
    },
    "domainSecuritySettings": {
      "ntlmV1": "Enabled",
      "tlsV1": "Enabled",
      "syncNtlmPasswords": "Enabled",
      "syncKerberosPasswords": "Enabled",
      "syncOnPremPasswords": "Enabled"
    },
    "filteredSync": "Enabled",
    "resourceForestSettings": {
      "settings": []
    },
    "notificationSettings": {
      "notifyGlobalAdmins": "Disabled",
      "notifyDcAdmins": "Disabled",
      "additionalRecipients": [
        "xxxx@contoso.com"
      ]
    },
    "sku": "Standard",
    "provisioningState": "Accepted"
  }
}


DEBUG: ResponseCreated: 
DEBUG: DelayBeforePolling: Delaying 30 seconds before polling.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxx/providers/Microsoft.AAD/locations/westeurope/operationResults/xxxx?api-version=2020-01-01

Headers:
x-ms-unique-id                : 15
x-ms-client-request-id        : 3713ef7f-e743-49ec-9713-9cd67e295827
CommandName                   : Az.ADDomainServices.internal\Update-AzADDomainService
FullCommandName               : Update-AzADDomainService_UpdateViaIdentityExpanded
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v7.1.0,PSVersion/v7.2.3,Az.ADDomainServices/0.1.0

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : 2a4fd315-f986-4f22-8d07-3954451cd4eb
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : e1b62e5a-91f1-489a-af21-1a92a78e71e8
x-ms-routing-request-id       : FRANCECENTRAL:20220509T093704Z:e1b62e5a-91f1-489a-af21-1a92a78e71e8
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Mon, 09 May 2022 09:37:03 GMT

Body:
{
  "id": "/subscriptions/xxxx/providers/Microsoft.AAD/locations/westeurope/operationResults/xxxx",
  "name": "xxxx",
  "status": "Failed",
  "startTime": "0001-01-01T08:00:00Z",
  "endTime": "0001-01-01T08:00:00Z",
  "percentComplete": 0.0,
  "error": {
    "code": "BadRequest",
    "message": "The certificate or password provided for LDAPs is invalid."
  }
}


DEBUG: Polling: 
DEBUG: Finally: 
Update-AzADDomainService_UpdateViaIdentityExpanded: C:\Users\xxxx\Documents\PowerShell\Modules\Az.ADDomainServices\0.1.0\custom\Update-AzADDomainService.ps1:283:13
Line |
 283 |              Az.ADDomainServices.internal\Update-AzADDomainService @PS …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The certificate or password provided for LDAPs is invalid.

DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: AzureQoSEvent: Module: Az.ADDomainServices:0.1.0; CommandName: Update-AzADDomainService_UpdateViaIdentityExpanded; PSVersion: 7.2.3; IsSuccess: True; Duration: 00:00:00
DEBUG: Finish sending metric.
DEBUG: CmdletEndProcessing:
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.5                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     0.1.0                 Az.ADDomainServices                 {Get-AzADDomainService, New-AzADDomainService, New-AzADDomainServiceForestTrust, New-AzADDomainServiceReplicaSet…}
Script     4.2.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount…}
Script     5.2.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
DEBUG: 11:41:46 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 11:41:46 - using account id 'xxxx@contoso.com'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 57

Message        : The certificate or password provided for LDAPs is invalid.
StackTrace     :    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.AdDomainServices.DomainServicesUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.AdDomainServices.DomainServicesUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.AdDomainServices.DomainServicesUpdateViaIdentity(String viaIdentity, IDomainService body, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync  
                 sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.Cmdlets.UpdateAzADDomainService_UpdateViaIdentityExpanded.ProcessRecordAsync()
Exception      : Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.Runtime.UndeclaredResponseException
InvocationInfo : {Update-AzADDomainService_UpdateViaIdentityExpanded}
Line           :             Az.ADDomainServices.internal\Update-AzADDomainService @PSBoundParameters

Position       : At C:\Users\xxxx\Documents\PowerShell\Modules\Az.ADDomainServices\0.1.0\custom\Update-AzADDomainService.ps1:283 char:13
                 +             Az.ADDomainServices.internal\Update-AzADDomainService @PS …
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 57


   HistoryId: 54

Message        : The certificate or password provided for LDAPs is invalid.
StackTrace     :    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.AdDomainServices.DomainServicesUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.AdDomainServices.DomainServicesUpdate_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.AdDomainServices.DomainServicesUpdateViaIdentity(String viaIdentity, IDomainService body, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync  
                 sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.Cmdlets.UpdateAzADDomainService_UpdateViaIdentityExpanded.ProcessRecordAsync()
Exception      : Microsoft.Azure.PowerShell.Cmdlets.ADDomainServices.Runtime.UndeclaredResponseException
InvocationInfo : {Update-AzADDomainService_UpdateViaIdentityExpanded}
Line           :             Az.ADDomainServices.internal\Update-AzADDomainService @PSBoundParameters

Position       : At C:\Users\xxxx\Documents\PowerShell\Modules\Az.ADDomainServices\0.1.0\custom\Update-AzADDomainService.ps1:283 char:13
                 +             Az.ADDomainServices.internal\Update-AzADDomainService @PS …
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 54



The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.5; CommandName: Resolve-AzError; PSVersion: 7.2.3; IsSuccess: True; Duration: 00:00:00.2753625
DEBUG: Finish sending metric.
DEBUG: 11:41:47 - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
@dolauli , please help to look into its API spec.

**Comment by BethanyZhou** [comment]
Hi @alex-3sr , please pass a base64encoded representation of the certificate pfx file in parameter LdapSettingPfxCertificate. The way to get base64 string from pfx file is as below
```
$fileContentBytes = get-content "C:\TEMP\certificate.pfx" -Encoding Byte
$base64String = [System.Convert]::ToBase64String($fileContentBytes) 
```

**Comment by alex-3sr** [comment]
> 

Hi @BethanyZhou ,

Thanks for your response and just try your commands for Base64, but ... On 1st command, **-Encoding Byte** is not accepted and I have this error ->
`Get-Content: Cannot process argument transformation on parameter 'Encoding'. 'Byte' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')`

And If i Ignore Enconding arguments, on 2nde one I've this error ->
`MethodException: Cannot convert argument "inArray", with value: "System.Object[]", for "ToBase64String" to type "System.Byte[]": "Cannot convert value "0�.0��    *�H��" to type "System.Byte". Error: "Input string was not in a correct format.""`

If I just Get-Content of my PFX Files, you have to know that this is PKCS12, so not readable like PEM, etc..
![image](https://user-images.githubusercontent.com/38663389/167569634-682586da-f60a-46b8-83f2-e2ee35fbc783.png)

So That's why I'm bit surprised about encoding Base64 a PKCS12 file who is already encoded, but why not, I'm ready for all tests :) BTW, I'm unable to encode it as Base64 and upload to Azure AD Domain Services for LDAPs certificates as mentionned at this time. Please let me know if need further tests, investigations, whatever, I'm free for this.

Have a nice day,
Thanks by advance
Regards
Alexandre

**Comment by BethanyZhou** [comment]
How about trying follow commands:
```powershell
$file = [System.IO.FileInfo]::new("C:\TEMP\certificate.pfx")
$cert = [System.Security.Cryptography.X509Certificates.X509Certificate2Collection]::new()
$cert.Import($file.FullName, "MyStrongPassword", ([System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable))
$bytes = $cert.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx, "MyStrongPassword")
$base64String = [System.Convert]::ToBase64String($bytes)
```

**Comment by alex-3sr** [comment]
Hi again ;)

Ok it's now perfect like this :) and So my full script is now like this, hapoy to share and can be use in documentation if needed.

```ps
# Variables
$tenantId = "yyyy"
$subcriptionId = "xxxx"
$adds_rg_name = "RG-TEST"
$adds_domain = "contoso.com"
$ldaps_pfx_path = "C:\TEMP\certificate.pfx"
$ldaps_pfx_pass = "MyStrongPassword"

# Prepare PFX file
$file_pfx = [System.IO.FileInfo]::new($ldaps_pfx_path)
$cert_pfx = [System.Security.Cryptography.X509Certificates.X509Certificate2Collection]::new()
$cert_pfx.Import($file_pfx.FullName, $ldaps_pfx_pass, ([System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable))
$cert_bytes = $cert_pfx.Export([System.Security.Cryptography.X509Certificates.X509ContentType]::Pfx, $ldaps_pfx_pass)
$cert_b64 = [System.Convert]::ToBase64String($cert_bytes)

# Update LDAPS Certificate
Set-AzContext -TenantId $tenantId -SubscriptionId $subcriptionId
try {
    $adds_rg = Get-AzResourceGroup -Name $adds_rg_name -ErrorAction Stop
    $adds = Get-AzADDomainService -Name $adds_domain -ResourceGroupName $adds_rg.ResourceGroupName -ErrorAction Stop
    $ldaps_update = Update-AzADDomainService -InputObject $adds -LdapSettingLdaps $true -LdapSettingPfxCertificate $cert_b64 -LdapSettingPfxCertificatePassword $($ldaps_pfx_pass | ConvertTo-SecureString -Force -AsPlainText) `
        -LdapSettingExternalAccess $adds.LdapSettingExternalAccess -ErrorAction Stop
}
catch {
    throw $_.Exception
}

# Output
if ($ldaps_update.ProvisioningState -eq "Succeeded"){
    Write-Host "LDAPS is correctly updated !"
} else {
    Write-Warning "LDAPS Provisionning is in error with status : $($ldaps_update.ProvisioningState)"
}
```

Thank you for your help
Have a nice day
Regards
Alexandre

**Comment by BethanyZhou** [comment]
Thanks @alex-3sr for sharing full script. 

I will close this issue and please feel free to reopen this issue if you have any question. Have a nice day.

**Comment by BethanyZhou** [comment]
BTW, LdapSettingLdaps is enum string. Its value should be Enabled or Disabled.

**Comment by BethanyZhou** [comment]
Created an issue to track feature request that allows this command to accept file path. https://github.com/Azure/azure-powershell/issues/18075

**Comment by dolauli** [comment]
@BethanyZhou @dingmeng-xue 
Just check the swagger, in which something is not clear defined as below. If these issues are fixed in swagger, autorest.powershell should generate the cmdlet as expected.
Change
```
        "pfxCertificate": {
          "type": "string",
          "description": "The certificate required to configure Secure LDAP. The parameter passed here should be a base64encoded representation of the certificate pfx file."
        },
```
to
```
        "pfxCertificate": {
          "type": "string",
          "format": "byte",
          "description": "The certificate required to configure Secure LDAP. The parameter passed here should be a base64encoded representation of the certificate pfx file."
        },
```
Change
```
        "pfxCertificatePassword": {
          "type": "string",
          "description": "The password to decrypt the provided Secure LDAP certificate pfx file."
        }
```
to
```
        "pfxCertificatePassword": {
          "type": "string",
          "format": "password",
          "description": "The password to decrypt the provided Secure LDAP certificate pfx file."
        }
```

**Comment by BethanyZhou** [comment]
In next version for Az.ADDomainService (version > 0.1.0), we will replace parameter LdapSettingPfxCertificate  with LdapSettingPfxCertificateInputFile, which allows user input certificate as file path. https://github.com/Azure/azure-powershell/pull/18282
