### ISSUE TITLE
Az-APIManagement Module- AllowTracing not working for New-AzApiManagementSubscription

### ISSUE THREAD

**Issue by nagashreeb** [Azure/azure-powershell#18240]
### Description

Unable to create Subscriptions in Azure APIM  with tracing enabled using the AllowTracing flag in the powershell command.

### Issue script & Debug output

```PowerShell
PS /home/admin> New-AzApiManagementSubscription -Context $context -Name $subscriptionName -Scope $scope -PrimaryKey $primarykey -SecondaryKey $secondarykey -State $subscriptionState -AllowTracing "true"       
New-AzApiManagementSubscription: A positional parameter cannot be found that accepts argument 'true'.
PS /home/admin> New-AzApiManagementSubscription -Context $context -Name $subscriptionName -Scope $scope -PrimaryKey $primarykey -SecondaryKey $secondarykey -State $subscriptionState -AllowTracing "True"
New-AzApiManagementSubscription: A positional parameter cannot be found that accepts argument 'True'.
PS /home/admin> New-AzApiManagementSubscription -Context $context -Name $subscriptionName -Scope $scope -PrimaryKey $primarykey -SecondaryKey $secondarykey -State $subscriptionState -AllowTracing True  
New-AzApiManagementSubscription: A positional parameter cannot be found that accepts argument 'True'.
PS /home/admin> $allowtracing = "true"
PS /home/admin> $enabletracing = [System.Convert]::ToBoolean($allowtracing)
PS /home/admin> New-AzApiManagementSubscription -Context $context -Name $subscriptionName -Scope $scope -PrimaryKey $primarykey -SecondaryKey $secondarykey -State $subscriptionState -AllowTracing $enabletracing

New-AzApiManagementSubscription: A positional parameter cannot be found that accepts argument 'True'.
PS /home/admin> New-AzApiManagementSubscription -Context $context -Name $subscriptionName -Scope $scope -PrimaryKey $primarykey -SecondaryKey $secondarykey -State $subscriptionState -AllowTracing $enabletracing

New-AzApiManagementSubscription: A positional parameter cannot be found that accepts argument 'True'.
```

### Environment data

```PowerShell
PS /home/admin> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS /home/admin> Get-Module Az.ApiManagement

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.3.2                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion…}
```

### Error output

```PowerShell
PS /home/admin> Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 25

Message        : A positional parameter cannot be found that accepts argument 'True'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzApiManagementSubscription}
Line           : New-AzApiManagementSubscription -Context $context -Name $subscriptionName -Scope $scope -PrimaryKey $primarykey -SecondaryKey $secondarykey -State $subscriptionState -AllowTracing 
                 $enabletracing
Position       : At line:1 char:1
                 + New-AzApiManagementSubscription -Context $context -Name $subscription …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 25


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
Hi @Nagashreeb , thanks for contacting us. 
`-AllowTracing` is switch parameters. So, you should try`-AllowTracing` or `-AllowTracing:$true`. However `-AllowTracing:$enabletracing` depends on cmdlet implementation. If you have issue, please let us know.

Here is info https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2#switch-parameters

**Comment by dingmeng-xue** [comment]
That's great. Feel free to contact us when you have any question. 

Close this issue now.
