### ISSUE TITLE
Get-AzAccessToken with ResourceUrl fails in cloud shell

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-powershell#18258]
### Description

Running `Get-AzAccessToken` fails in cloud shell (shell.azure.com) if the `-ResourceUrl` parameter is provided.
Without the parameter a valid token is returned, but we need to get a token for `'https://servicebus.azure.net'` and that fails.

Works perfectly fine ran locally.

### Issue script & Debug output

```PowerShell
$Resource = 'https://servicebus.azure.net'
Get-AzAccessToken -ResourceUrl $Resource
DEBUG: 2:35:00 AM - GetAzureRmAccessTokenCommand begin processing with ParameterSet 'ResourceUrl'.
DEBUG: 2:35:00 AM - using account id 'MSI@50342'...
DEBUG: 2:35:00 AM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'0324676a-8d8c-4682-b129-a59bbf393fe7', Scopes:'https://servicebus.azure.net', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://servicebus.azure.net ] ParentRequestId: 
DEBUG: Request [5fc22f59-8dd6-4d08-8ff2-2bd87f85fee1] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:5fc22f59-8dd6-4d08-8ff2-2bd87f85fee1
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.3; Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Error response [5fc22f59-8dd6-4d08-8ff2-2bd87f85fee1] 400 Bad Request (00.0s)
X-Powered-By:REDACTED
ETag:W/"3ac-pZk9saKwddEu8sosDW96j9/yZ9w"
Date:Sun, 22 May 2022 02:35:00 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:940

DEBUG: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://servicebus.azure.net ] ParentRequestId:  Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Content:


Headers:
X-Powered-By: REDACTED
ETag: W/"3ac-pZk9saKwddEu8sosDW96j9/yZ9w"
Date: Sun, 22 May 2022 02:35:00 GMT
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Content-Length: 940

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> Azure.RequestFailedException (0x80131500): Service request failed.
Status: 400 (Bad Request)

Content:


Headers:
X-Powered-By: REDACTED
ETag: W/"3ac-pZk9saKwddEu8sosDW96j9/yZ9w"
Date: Sun, 22 May 2022 02:35:00 GMT
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Content-Length: 940

Get-AzAccessToken: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)
Content:
Headers:
X-Powered-By: REDACTED
ETag: W/"3ac-pZk9saKwddEu8sosDW96j9/yZ9w"
Date: Sun, 22 May 2022 02:35:00 GMT
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Content-Length: 940
See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.7.6; CommandName: Get-AzAccessToken; PSVersion: 7.2.2; IsSuccess: False; Duration: 00:00:00.0242055; Exception: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Content:


Headers:
X-Powered-By: REDACTED
ETag: W/"3ac-pZk9saKwddEu8sosDW96j9/yZ9w"
Date: Sun, 22 May 2022 02:35:00 GMT
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Content-Length: 940

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot;
DEBUG: Finish sending metric.
DEBUG: 2:35:01 AM - GetAzureRmAccessTokenCommand end processing.
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.6                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.26.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     4.16.1                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzApplicationGatewayCustomError…}
Script     5.6.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     4.5.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember…}
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
Resolve-AzError
DEBUG: 2:38:23 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 2:38:23 AM - using account id 'MSI@50342'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 12

Message        : ManagedIdentityCredential authentication failed: Service request failed.
                 Status: 400 (Bad Request)
                 
                 Content:
                 
                 
                 Headers:
                 X-Powered-By: REDACTED
                 ETag: W/"3ac-pZk9saKwddEu8sosDW96j9/yZ9w"
                 Date: Sun, 22 May 2022 02:35:00 GMT
                 Connection: keep-alive
                 Content-Type: application/json; charset=utf-8
                 Content-Length: 940
                 
                 See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
StackTrace     :    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
                    at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
                    at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
                    at Microsoft.Azure.PowerShell.Authenticators.MsalAccessTokenAcquirer.GetAccessTokenAsync(String callerClassName, String parametersLog, TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken, String tenantId, String userId, String homeAccountId)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.Profile.GetAzureRmAccessTokenCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Azure.Identity.AuthenticationFailedException
InvocationInfo : {Get-AzAccessToken}
Line           : Get-AzAccessToken -ResourceUrl $Resource
Position       : At line:1 char:1
                 + Get-AzAccessToken -ResourceUrl $Resource
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by dingmeng-xue** [comment]
@davidobrien1985 , thanks for contacting us.

CloudShell default login account is different from your local. It leverages MSI and you can it via `(Get-AzAccessToken).UserId`. I am not sure how to grant the permission to that MSI but I believe you can get access token when you login with your account via `Connect-AzAccount -DeviceCode`

**Comment by dcaro** [comment]
cc @maertendMSFT

**Comment by davidobrien1985** [comment]
@dingmeng-xue Hi, and indeed, thanks. Calling `Connect-AzAccount` again does fix the issue. I don't think I fully understand why, because the first token that gets created on login is already in my context, but I'll take it.
