### ISSUE TITLE
New-AzKeyvault not triggering soft delete to be enabled

### ISSUE THREAD

**Issue by extmaper** [Azure/azure-powershell#18280]
### Description

When trying to create a new Keyvault from powershell with Azure policy /providers/Microsoft.Authorization/policyDefinitions/0b60c0b2-2dc2-4e1c-b5c9-abbed971de53 active in the environment the deployment gets blocked.

New-AzKeyVault -Location westeurope -name testing54654564 -ResourceGroupName xxxxx -Sku Standard -EnablePurgeProtection -SoftDeleteRetentionInDays 90.

The corresponding command in Az cli works as expected.
az keyvault create -g xxxxx -n testing485454 --enable-purge-protection --enable-soft-delete true --retention-days 90 --location westeurope

The powershell module seems to be missing an option to enable the Soft Delete feature on the Keyvault.

### Issue script & Debug output

```PowerShell
PS /home/service> New-AzKeyVault -Location westeurope -name testing54654564 -ResourceGroupName xxxx -Sku Standard -EnablePurgeProtection -SoftDeleteRetentionInDays 90
DEBUG: 9:54:32 AM - NewAzureKeyVault begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 9:54:32 AM - using account id 'MSI@50342'...
WARNING: We have migrated the API calls for this cmdlet from Azure Active Directory Graph to Microsoft Graph.
Visit https://go.microsoft.com/fwlink/?linkid=2181475 for any permission issues.
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: 'xxxxxxxxxxxxxxxxxxxx'
DEBUG: 9:54:32 AM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'xxxxxxxxxxxxxxxxxxxxxxx', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId: 
DEBUG: Request [091f0bcd-96c6-4d8c-9755-7bc63e226b78] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:091f0bcd-96c6-4d8c-9755-7bc63e226b78
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.3; Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [091f0bcd-96c6-4d8c-9755-7bc63e226b78] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"8a2-JnVUESDs2zKAfCtTYmryfodwlaQ"
Date:Tue, 24 May 2022 09:54:32 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2210

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  ExpiresOn: 2022-05-24T10:15:11.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxxxxxxxxxxx', UserId: 'MSI@50342'
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: 'xxxxxxxxxxxxxxxxxx'
DEBUG: 9:54:32 AM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'xxxxxxxxxxxxxxxxxx', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId: 
DEBUG: Request [12db1d20-02a2-473d-8590-c14a0afee3ec] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:12db1d20-02a2-473d-8590-c14a0afee3ec
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.3; Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [12db1d20-02a2-473d-8590-c14a0afee3ec] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"8a2-JnVUESDs2zKAfCtTYmryfodwlaQ"
Date:Tue, 24 May 2022 09:54:32 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2210

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  ExpiresOn: 2022-05-24T10:15:11.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxxxxxxxxxxxxxxxxx', UserId: 'MSI@50342'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resources?$filter=resourceType eq 'Microsoft.KeyVault%2Fvaults'&api-version=2016-09-01

Headers:
x-ms-client-request-id        : a9288bcc-f145-4291-90ab-b352e51768a8
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id               : 498d5447-cd2f-4348-855e-526c519789a6
x-ms-correlation-request-id   : 498d5447-cd2f-4348-855e-526c519789a6
x-ms-routing-request-id       : WESTEUROPE:20220524T095432Z:498d5447-cd2f-4348-855e-526c519789a6
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 24 May 2022 09:54:32 GMT

Body:
{
  "value": [
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxx/providers/Microsoft.KeyVault/vaults/kv-xxxxx",
      "name": "demodemo4568",
      "type": "Microsoft.KeyVault/vaults",
      "location": "westeurope",
      "tags": {}
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.KeyVault/vaults/testing485454",
      "name": "testing485454",
      "type": "Microsoft.KeyVault/vaults",
      "location": "westeurope",
      "tags": {}
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.KeyVault/vaults/kv-xxxxx",
      "name": "testspace9706731704",
      "type": "Microsoft.KeyVault/vaults",
      "location": "westeurope",
      "tags": {}
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxx/providers/Microsoft.KeyVault/vaults/kv-xxxxx",
      "name": "kv-testsub1-015",
      "type": "Microsoft.KeyVault/vaults",
      "location": "westeurope",
      "tags": {}
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxx/providers/Microsoft.KeyVault/vaults/kv-xxxxx",
      "name": "testKVST2021122010",
      "type": "Microsoft.KeyVault/vaults",
      "location": "westeurope",
      "tags": {}
    }
  ]
}


DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: 'xxxxxxxxxxxxxxxxxxxxx'
DEBUG: 9:54:32 AM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'xxxxxxxxxxxxxxx', Scopes:'https://graph.microsoft.com/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com/ ] ParentRequestId: 
DEBUG: Request [96a5d987-883c-41dd-bdd1-5eacb2dd8481] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:96a5d987-883c-41dd-bdd1-5eacb2dd8481
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0,(.NET 6.0.3; Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [96a5d987-883c-41dd-bdd1-5eacb2dd8481] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"91c-SYqEndaCU/qAOqPJzweFfdVPE08"
Date:Tue, 24 May 2022 09:54:32 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:2332

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://graph.microsoft.com/ ] ParentRequestId:  ExpiresOn: 2022-05-24T11:19:29.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxxxxxxxxxxxxxxxxx', UserId: 'MSI@50342'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxxxx/resourceGroups/mp-666/providers/Microsoft.KeyVault/vaults/testing54654564?api-version=2021-06-01-preview

Headers:
x-ms-client-request-id        : a9288bcc-f145-4291-90ab-b352e51768a8
Accept-Language               : en-US

Body:
{
  "location": "westeurope",
  "properties": {
    "tenantId": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "sku": {
      "name": "standard",
      "family": "A"
    },
    "accessPolicies": [],
    "vaultUri": "",
    "enabledForDeployment": false,
    "enabledForDiskEncryption": false,
    "enabledForTemplateDeployment": false,
    "softDeleteRetentionInDays": 90,
    "enableRbacAuthorization": false,
    "enablePurgeProtection": true,
    "networkAcls": {
      "bypass": "AzureServices",
      "defaultAction": "Allow"
    }
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 770d7521-0c5a-4311-b475-6b0de2e79458
x-ms-correlation-request-id   : 770d7521-0c5a-4311-b475-6b0de2e79458
x-ms-routing-request-id       : WESTEUROPE:20220524T095433Z:770d7521-0c5a-4311-b475-6b0de2e79458
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 24 May 2022 09:54:32 GMT
Connection                    : close

Body:
{
  "error": {
    "code": "RequestDisallowedByPolicy",
    "target": "testing54654564",
    "message": "Resource 'testing54654564' was disallowed by policy.See error details for policy resource IDs.",
    "additionalInfo": [
      {
        "type": "PolicyViolation",
        "info": {
          "policyDefinitionDisplayName": "Key vaults should have purge protection enabled",
          "policySetDefinitionDisplayName": "xxxxxxxxxxxxxxxxx",
          "evaluationDetails": {
            "evaluatedExpressions": [
              {
                "result": "True",
                "expressionKind": "Field",
                "expression": "type",
                "path": "type",
                "expressionValue": "Microsoft.KeyVault/vaults",
                "targetValue": "Microsoft.KeyVault/vaults",
                "operator": "Equals"
              },
              {
                "result": "False",
                "expressionKind": "Field",
                "expression": "Microsoft.KeyVault/vaults/createMode",
                "path": "properties.createMode",
                "targetValue": "recover",
                "operator": "Equals"
              },
              {
                "result": "True",
                "expressionKind": "Field",
                "expression": "Microsoft.KeyVault/vaults/enableSoftDelete",
                "path": "properties.enableSoftDelete",
                "targetValue": "false",
                "operator": "Exists"
              }
            ],
            "reason": ""
          },
          "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/0b60c0b2-2dc2-4e1c-b5c9-abbed971de53",
          "policySetDefinitionId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "policyDefinitionReferenceId": "EnsureKeyVaultPurgeProtection",
          "policySetDefinitionName": "xxxxxxxxxxxxxxxxxxxxx",
          "policyDefinitionName": "0b60c0b2-2dc2-4e1c-b5c9-abbed971de53",
          "policyDefinitionEffect": "Deny",
          "policyAssignmentId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
          "policyAssignmentName": "xxxxxxxxxxxxxxx",
          "policyAssignmentDisplayName": "xxxxxxxxxxxxxxxxx",
          "policyAssignmentScope": "xxxxxxxxxxxxxxxxxxxxx"
        }
      }
    ]
  }
}


New-AzKeyVault: Resource 'testing54654564' was disallowed by policy.See error details for policy resource IDs.
DEBUG: AzureQoSEvent: Module: Az.KeyVault:4.4.0; CommandName: New-AzKeyVault; PSVersion: 7.2.2; IsSuccess: False; Duration: 00:00:00.4031430; Exception: Resource 'testing54654564' was disallowed by policy. See error details for policy resource IDs.;
DEBUG: Finish sending metric.
DEBUG: 9:54:33 AM - NewAzureKeyVault end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
[32;1mModuleType Version    PreRelease Name                                ExportedCommands[0m
[32;1m---------- -------    ---------- ----                                ----------------[0m
Script     2.7.6                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.26.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     4.4.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount…}
Script     4.16.1                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Ad…
Script     5.6.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     4.5.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember…}
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
HistoryId: 5

[32;1mRequestId      : [0m770d7521-0c5a-4311-b475-6b0de2e79458
[32;1mMessage        : [0mResource 'testing54654564' was disallowed by policy.See error details for policy resource IDs.
[32;1mServerMessage  : [0mRequestDisallowedByPolicy: Resource 'testing54654564' was disallowed by policy. See error details for policy resource IDs. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
[32;1mServerResponse : [0m{Forbidden}
[32;1mRequestMessage : [0m{PUT https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.KeyVault/vaults/testing54654564?api-version=2021-06-01-preview}
[32;1mInvocationInfo : [0m{New-AzKeyVault}
[32;1mLine           : [0mNew-AzKeyVault -Location westeurope -name testing54654564 -ResourceGroupName xxxxx -Sku Standard -EnablePurgeProtection -SoftDeleteRetentionInDays 90
[32;1mPosition       : [0mAt line:1 char:1
[32;1m                 [0m+ New-AzKeyVault -Location westeurope -name testing54654564 -ResourceGr …
[32;1m                 [0m+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[32;1mStackTrace     : [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
[32;1m                 [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
[32;1m                 [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.CreateOrUpdateAsync(IVaultsOperations operations, String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters, CancellationToken cancellationToken)
[32;1m                 [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.CreateOrUpdate(IVaultsOperations operations, String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters)
[32;1m                 [0m   at Microsoft.Azure.Commands.KeyVault.Models.VaultManagementClient.CreateNewVault(VaultCreationOrUpdateParameters parameters, IMicrosoftGraphClient graphClient, PSKeyVaultNetworkRuleSet networkRuleSet)
[32;1m                 [0m   at Microsoft.Azure.Commands.KeyVault.NewAzureKeyVault.ExecuteCmdlet()
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
[32;1mHistoryId      : [0m5


   HistoryId: 3

[32;1mRequestId      : [0mf2e2172b-d46a-4486-9f23-847d72d6ce91
[32;1mMessage        : [0mResource 'testing54654564' was disallowed by policy. See error details for policy resource IDs.
[32;1mServerMessage  : [0mRequestDisallowedByPolicy: See error details for policy resource IDs. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
[32;1mServerResponse : [0m{Forbidden}
[32;1mRequestMessage : [0m{PUT https://management.azure.com/subscriptions/xxxxxxx/resourceGroups/xxxx/providers/Microsoft.KeyVault/vaults/testing54654564?api-version=2021-06-01-preview}
[32;1mInvocationInfo : [0m{New-AzKeyVault}
[32;1mLine           : [0mNew-AzKeyVault -Location westeurope -name testing54654564 -ResourceGroupName xxxxx -Sku Standard -EnablePurgeProtection -SoftDeleteRetentionInDays 90
[32;1mPosition       : [0mAt line:1 char:1
[32;1m                 [0m+ New-AzKeyVault -Location westeurope -name testing54654564 -ResourceGr …
[32;1m                 [0m+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[32;1mStackTrace     : [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
[32;1m                 [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
[32;1m                 [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.CreateOrUpdateAsync(IVaultsOperations operations, String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters, CancellationToken cancellationToken)
[32;1m                 [0m   at Microsoft.Azure.Management.KeyVault.VaultsOperationsExtensions.CreateOrUpdate(IVaultsOperations operations, String resourceGroupName, String vaultName, VaultCreateOrUpdateParameters parameters)
[32;1m                 [0m   at Microsoft.Azure.Commands.KeyVault.Models.VaultManagementClient.CreateNewVault(VaultCreationOrUpdateParameters parameters, IMicrosoftGraphClient graphClient, PSKeyVaultNetworkRuleSet networkRuleSet)
[32;1m                 [0m   at Microsoft.Azure.Commands.KeyVault.NewAzureKeyVault.ExecuteCmdlet()
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
[32;1m                 [0m   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
[32;1mHistoryId      : [0m3
```

**Comment by dingmeng-xue** [comment]
@extmaper , thanks for reporting. We will look into it.

**Comment by jlichwa** [comment]
We have a bug in Azure Policy to handle soft-delete correctly.

**Comment by dingmeng-xue** [comment]
@extmaper , could you try the latest Az.Keyvault and Az.Account? When we try the same script , the request body is different from what you have shared. No matter on Linux or Windows, `enableSoftDelete` presents and is true in HTTP request body.

**Comment by extmaper** [comment]
@dingmeng-xue, I have tried with version Az.Accounts 2.8.0 and Az.KeyVault 4.5.0 now. Same error and the body looks like this

Body:
{
  "location": "westeurope",
  "properties": {
    "tenantId": "xxxxxxxxxxxxxxxxxxxxxxxxxx",
    "sku": {
      "name": "standard",
      "family": "A"
    },
    "accessPolicies": [
      {
        "tenantId": "xxxxxxxxxxxxxxxxxxxxxxx",
        "objectId": "xxxxxxxxxxxxxxxxxxxxxxx",
        "permissions": {
          "keys": [
            "all"
          ],
          "secrets": [
            "get",
            "list",
            "set",
            "delete",
            "backup",
            "restore",
            "recover"
          ],
          "certificates": [
            "get",
            "delete",
            "list",
            "create",
            "import",
            "update",
            "deleteissuers",
            "getissuers",
            "listissuers",
            "managecontacts",
            "manageissuers",
            "setissuers",
            "recover",
            "backup",
            "restore"
          ],
          "storage": [
            "delete",
            "deletesas",
            "get",
            "getsas",
            "list",
            "listsas",
            "regeneratekey",
            "set",
            "setsas",
            "update",
            "recover",
            "backup",
            "restore"
          ]
        }
      }
    ],
    "vaultUri": "",
    "enabledForDeployment": false,
    "enabledForDiskEncryption": false,
    "enabledForTemplateDeployment": false,
    "softDeleteRetentionInDays": 90,
    "enableRbacAuthorization": false,
    "enablePurgeProtection": true,
    "networkAcls": {
      "bypass": "AzureServices",
      "defaultAction": "Allow"
    }
  }
}

**Comment by BethanyZhou** [comment]
The policy with id "0b60c0b2-2dc2-4e1c-b5c9-abbed971de53", named "Key vaults should have purge protection enabled", is a built-in policy. It hit similar issue with "Key vaults should have soft delete enabled", see https://github.com/Azure/azure-powershell/issues/15970.

**Comment by jlichwa** [comment]
This is now fixed for soft delete with Policy version 3.0.
