### ISSUE TITLE
Get-AzureRmAutomationModule -name "azurerm*" fails (wildcard search)

### ISSUE THREAD

**Issue by JakobGSvendsen** [Azure/azure-powershell#1829]
Get-AzureRmAutomationModule -name "azurerm" works fine
Get-AzureRmAutomationModule -name "azurerm*" fails.

here are the error details:

```
PS C:\WINDOWS\system32> Get-AzureRmAutomationModule -name "azurerm*"
Get-AzureRmAutomationModule : <!DOCTYPE html>
<html>
    <head>
        <title>A potentially dangerous Request.Path value was detected from the client (*).</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;}
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>
    <body bgcolor="white">
            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>
            <h2> <i>A potentially dangerous Request.Path value was detected from the client (*).</i> </h2></span>
            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">
            <b> Description: </b>An unhandled exception occurred during the execution of the current web request.
Please review the stack trace for more information about the error and where it originated in the code.
            <br><br>
            <b> Exception Details: </b>System.Web.HttpException: A potentially dangerous Request.Path value was
detected from the client (*).<br><br>
            <b>Source Error:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>
An unhandled exception was generated during the execution of the current web request. Information regarding the origin
and location of the exception can be identified using the exception stack trace below.</code>
                  </td>
               </tr>
            </table>
            <br>
            <b>Stack Trace:</b> <br><br>
            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>
[HttpException (0x80004005): A potentially dangerous Request.Path value was detected from the client (*).]
   System.Web.HttpRequest.ValidateInputIfRequiredByConfig() +12353567
   System.Web.PipelineStepManager.ValidateHelper(HttpContext context) +166
</pre></code>
                  </td>
               </tr>
            </table>
            <br>
            <hr width=100% size=1 color=silver>
            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET
Version:4.0.30319.34274
            </font>
    </body>
</html>
<!--
[HttpException]: A potentially dangerous Request.Path value was detected from the client (*).
   at System.Web.HttpRequest.ValidateInputIfRequiredByConfig()
   at System.Web.HttpApplication.PipelineStepManager.ValidateHelper(HttpContext context)
--><!--
This error page might contain sensitive information because ASP.NET is configured to show verbose error messages using
&lt;customErrors mode="Off"/&gt;. Consider using &lt;customErrors mode="On"/&gt; or &lt;customErrors
mode="RemoteOnly"/&gt; in production environments.-->
At line:1 char:1
+ Get-AzureRmAutomationModule -name "azurerm*"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAutomationModule], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationModule

PS C:\WINDOWS\system32>
```

**Comment by markcowl** [comment]
@jodoglevy Please take a look

**Comment by jodoglevy** [comment]
You can do:

`Get-AzureRMModule | where { $_.Name.Contains("azurerm") }`

to limit the results to just modules with azurerm in the name

**Comment by markcowl** [comment]
@jodoglevy This seems like an ominous message though, doesn't it?

**Comment by jodoglevy** [comment]
Yup, filed a bug on that.

**Comment by JakobGSvendsen** [comment]
"Get-AzureRMAutomationModule | where { $_.Name.Contains("azurerm") }"


yes but it is bad practice to not filter any kind of search. 
Look bad when I as a PowerShell teacher try to teach students best practice.  ;-)

Is there a reason why many azure rm cmdlets does not support wildcards?

limitation in ARM?

It is really weird to me that we need to to bad code to make it work :)

anyways, thanks!

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/issues/5447
