### ISSUE TITLE
Set-AzApplicationInsightsDailyCap fails with "A parameter cannot be found that matches parameter name 'ResourceName'."

### ISSUE THREAD

**Issue by michaelkc** [Azure/azure-powershell#18315]
### Description

When running the command, I consistently get the error

Enabling $DebugPreference = "Continue" prior to running produces lots of debug output for other Az commands, but nothing here.

I have reproduced it locally, as well as in Azure Cloud Shell (where Az is upgraded from standard 7.5 to 8 via `Install-Module -Name Az -AllowClobber -Scope CurrentUser -Force`

Output below is from Azure Cloud Shell

### Issue script & Debug output

```PowerShell
Set-AzApplicationInsightsDailyCap -Name <some-appinsights-name> -ResourceGroupName <some-resource-group> -SubscriptionId <subscription guid> -DailyCapGB 1

Set-AzApplicationInsightsDailyCap: A parameter cannot be found that matches parameter name 'ResourceName'.
```

### Environment data

```PowerShell
PS /home/michael> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Linux 5.4.0-1078-azure #81~18.04.1-Ubuntu SMP Mon Apr 25 23:16:13 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS /home/michael> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     2.0.0                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplicationInsightsContinuousExpor…
Script     4.27.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     4.17.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-A…
Script     6.0.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     4.6.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountN…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
PS /home/michael> Resolve-AzError                                                                                                                                           WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 1

Message        : A parameter cannot be found that matches parameter name 'ResourceName'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzApplicationInsightsComponentCurrentBillingFeature}
Line           :         $feature = (. Az.ApplicationInsights.internal\Get-AzApplicationInsightsComponentCurrentBillingFeature -ResourceGroupName 
                 $PSBoundParameters['ResourceGroupName'] -SubscriptionId $PSBoundParameters['SubscriptionId'] -ResourceName $PSBoundParameters['ResourceName'])
                 
Position       : At /home/michael/.local/share/powershell/Modules/Az.ApplicationInsights/2.0.0/custom/Set-AzApplicationInsightsDailyCap.ps1:113 char:223
                 + … criptionId $PSBoundParameters['SubscriptionId'] -ResourceName $PSBoun …
                 +                                                   ~~~~~~~~~~~~~
HistoryId      : 1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , please help look into this question.

**Comment by michaelkc** [comment]
To clarify, it is not possible to set a ResourceName parameter, neither directly or via splatting. This aligns with the documentation
https://docs.microsoft.com/en-us/powershell/module/az.applicationinsights/set-azapplicationinsightsdailycap?view=azps-8.0.0
not mentioning such a parameter.

**Comment by VeryEarly** [comment]
> 

Hi @michaelkc ,

It's a bug introduced in the new version of Az.ApplicationInsights, I've made the fix and will keep this issue updated when it will be released.

For this time being please use previous version of Az.ApplicationInsights for Set-AzApplicationInsightsDailyCap
