### ISSUE TITLE
New-AzFrontDoorRulesEngineMatchConditionObject does not allow Operators 'IP Not Match' or 'Geo Not Match'

### ISSUE THREAD

**Issue by PaulGarnerUk** [Azure/azure-powershell#18354]
### Description

When configuring front door rules engine via the portal, when using 'Remote Address' the options for match conditions include 'IP Not Match' and 'Geo Not Match' (as well as 'IP Match' and 'Geo Match')

However the enum `PSRulesEngineOperator` does not allow for these values : https://github.com/Azure/azure-powershell/blob/main/src/FrontDoor/FrontDoor/Models/PSRulesEngineRule.cs

This means we can't create match conditions like:

`$matchCondition = New-AzFrontDoorRulesEngineMatchConditionObject -MatchVariable RemoteAddr -Operator IPNotMatch -MatchValue "1.2.3.4"`

### Issue script & Debug output

```PowerShell
$matchCondition = New-AzFrontDoorRulesEngineMatchConditionObject -MatchVariable RemoteAddr -Operator IPNotMatch -MatchValue "1.2.3.4"

New-AzFrontDoorRulesEngineMatchConditionObject: Cannot bind parameter 'Operator'. Cannot convert value "IPNotMatch" to type "Microsoft.Azure.Commands.FrontDoor.Models.PSRulesEngineOperator". Error: "Unable to match the identifier name IPNotMatch to a valid enumerator name. Specify one of the following enumerator names and try again:
Any, IPMatch, GeoMatch, Equal, Contains, LessThan, GreaterThan, LessThanOrEqual, GreaterThanOrEqual, BeginsWith, EndsWith"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}

Script     1.9.0                 Az.FrontDoor                        {Disable-AzFrontDoorCustomDomainHttps, Enable-AzFrontDoorCustomDomainHttps…
```

### Error output

```PowerShell
Message        : Cannot bind parameter 'Operator'. Cannot convert value "IPNotMatch" to type
                 "Microsoft.Azure.Commands.FrontDoor.Models.PSRulesEngineOperator". Error: "Unable to match the identifier name IPNotMatch to a
                 valid enumerator name. Specify one of the following enumerator names and try again:
                 Any, IPMatch, GeoMatch, Equal, Contains, LessThan, GreaterThan, LessThanOrEqual, GreaterThanOrEqual, BeginsWith, EndsWith"
StackTrace     :    at System.Management.Automation.ParameterBinderBase.CoerceTypeAsNeeded(CommandParameterInternal argument, String
                 parameterName, Type toType, ParameterCollectionTypeInformation collectionTypeInfo, Object currentValue)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter,
                 CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument,
                 MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets,
                 CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets,
                 CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
                    at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1
                 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][]
                 pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzFrontDoorRulesEngineMatchConditionObject}
Line           : $matchCondition = New-AzFrontDoorRulesEngineMatchConditionObject -MatchVariable RemoteAddr -Operator IPNotMatch -MatchValue
                 "1.2.3.4"
Position       : At line:1 char:102
                 + … onditionObject -MatchVariable RemoteAddr -Operator IPNotMatch -MatchV …
                 +                                                      ~~~~~~~~~~
```

**Comment by PaulGarnerUk** [comment]
Just noticed the -NegateCondition parameter.  Sorry!
