### ISSUE TITLE
Error while creating continuous export of azure log to storage using powershell command

### ISSUE THREAD

**Issue by MusthaqAli123** [Azure/azure-powershell#18350]
### Description

I am trying to create ContinuousExport for Azure Application Insights Logs to Storage Container using Powershell cmd, but I am getting below error 
![continuousexport_bug](https://user-images.githubusercontent.com/59656517/171111121-0109704d-f1ae-43c2-95fe-68fb5a0a8686.png)
New-AzApplicationInsightsContinuousExport: Exception calling "Join" with "2" argument(s): "Value cannot be null. (Parameter 'values')"

### Issue script & Debug output

```PowerShell
$contextmobile = New-AzureStorageContext -StorageAccountName "name" -StorageAccountKey "key1"
$sastokenmobile = New-AzStorageContainerSASToken -Name "name" -Context $contextmobile -ExpiryTime (Get-Date).AddYears(50) -Permission w
$sasurimobile = "http" + $sastokenmobile
New-AzApplicationInsightsContinuousExport -ResourceGroupName "name" -Name "name" -DocumentType "Custom Event" -StorageAccountId "storageaccid" -StorageLocation  -StorageSASUri $sasurimobile
```

### Environment data

```PowerShell
New-AzApplicationInsightsContinuousExport: Exception calling "Join" with "2" argument(s): "Value cannot be null. (Parameter 'values')"
```

### Module versions

```PowerShell
New-AzApplicationInsightsContinuousExport
```

### Error output

```PowerShell
HistoryId: -1

Message        : Exception calling "Join" with "2" argument(s): "Value cannot be null. (Parameter 'values')"
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.MethodInvocationException
InvocationInfo : {}
Line           :         $PSBoundParameters['RecordType'] = [System.String]::Join(",", $PSBoundParameters['DocumentType'])
                 
Position       : At /usr/local/share/powershell/Modules/Az.ApplicationInsights/2.0.0/custom/New-AzApplicationInsightsContinuousExport.ps1:157 char:9
                 +         $PSBoundParameters['RecordType'] = [System.String]::Join(",", …
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Value cannot be null. (Parameter 'values')
StackTrace     :    at System.String.JoinCore(ReadOnlySpan`1 separator, Object[] values)
                    at CallSite.Target(Closure , CallSite , Type , String , Object )
Exception      : System.ArgumentNullException
InvocationInfo : {}
Line           :         $PSBoundParameters['RecordType'] = [System.String]::Join(",", $PSBoundParameters['DocumentType'])
                 
Position       : At /usr/local/share/powershell/Modules/Az.ApplicationInsights/2.0.0/custom/New-AzApplicationInsightsContinuousExport.ps1:157 char:9
                 +         $PSBoundParameters['RecordType'] = [System.String]::Join(",", …
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by MusthaqAli123** [comment]
I provided that as well, You can see it in my screenshot attached

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into this questions. Is there problem we introduced when we upgrade ApplicationInsights this time?
