### ISSUE TITLE
Connect-AzAccount : ClientCertificateCredential authentication failed

### ISSUE THREAD

**Issue by lroan** [Azure/azure-powershell#18495]
### Description

After updating to 2.8.0, the connect-azaccount fails to use a certificate to authenticate against a service principal, example error:

Connect-AzAccount : ClientCertificateCredential authentication failed: Could not use the certificate for signing. See
inner exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or
lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different certificate type (non-CNG)
or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion.

This continues to work perfectly fine in 2.7.6.

### Issue script & Debug output

```PowerShell
DEBUG: 5:02:04 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet
'ServicePrincipalCertificateFileWithSubscriptionId'.
DEBUG: 5:02:04 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: 5:02:04 PM - [ConfigManager] Got nothing from [DefaultSubscriptionForLogin], Module = [], Cmdlet = []. Returning
 default value [].
DEBUG: 5:02:04 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 5:02:04 PM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 5:02:04 PM - Using Autosave scope 'CurrentUser'
DEBUG: 5:02:04 PM - [ServicePrincipalAuthenticator] Calling ClientCertificateCredential.GetTokenAsync -
CertificatePath:'XXXXXX', ApplicationId:'XXXXX-XXXXX-XXXXX-XXXXX',
TenantId:'XXXXXX-XXXX-XXXX-XXXX-XXXXXXXX', Scopes:'https://management.core.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientCertificateCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [06/13 21:02:04.15 -
92010757-f8e1-4343-b875-6d9bf0852d6c] MSAL MSAL.Desktop with assembly version '4.39.0.0'.
CorrelationId(92010757-f8e1-4343-b875-6d9bf0852d6c)
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [06/13 21:02:04.15 -
92010757-f8e1-4343-b875-6d9bf0852d6c] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [06/13 21:02:04.15 -
92010757-f8e1-4343-b875-6d9bf0852d6c]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - XXXXXXX-XXX-XXXX-XXXXXXXXXXX
UserAssertion set: False
LongRunningOboCacheKey set: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [06/13 21:02:04.15 -
92010757-f8e1-4343-b875-6d9bf0852d6c] === Token Acquisition (ClientCredentialRequest) started:
  Scopes: https://management.core.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [06/13 21:02:04.15 -
92010757-f8e1-4343-b875-6d9bf0852d6c] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [06/13 21:02:04.16 -
92010757-f8e1-4343-b875-6d9bf0852d6c] Exception type: Microsoft.Identity.Client.MsalClientException
, ErrorCode: crypto_net45
---> Inner Exception Details
Exception type: System.Security.Cryptography.CryptographicException

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean
randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean
useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at
Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.GetCryptoProviderForSha256_Net45(X509Certificat
e2 certificate)
=== End of inner exception stack trace ===

   at
Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.GetCryptoProviderForSha256_Net45(X509Certificat
e2 certificate)
   at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message,
X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendX5C)
   at
Microsoft.Identity.Client.Internal.ClientCredentialWrapper.<AddConfidentialClientParametersAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<AddBodyParamsAndHeadersAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendTokenRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<FetchNewAccessTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
DEBUG: ClientCertificateCredential.GetToken was unable to retrieve an access token. Scopes: [
https://management.core.windows.net//.default ] ParentRequestId:  Exception:
Azure.Identity.AuthenticationFailedException (0x80131500): ClientCertificateCredential authentication failed: Could not
 use the certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps
build against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a
different certificate type (non-CNG) or sign your own assertion as described at
https://aka.ms/msal-net-signed-assertion.
 ---> Microsoft.Identity.Client.MsalClientException (0x80131500): Could not use the certificate for signing. See inner
exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or lower.
Either target a higher version of .NET desktop - 4.6.1 and above, or use a different certificate type (non-CNG) or sign
 your own assertion as described at https://aka.ms/msal-net-signed-assertion.
 ---> System.Security.Cryptography.CryptographicException (0x80090014): Invalid provider type specified.
DEBUG: Azure.Identity.AuthenticationFailedException: ClientCertificateCredential authentication failed: Could not use
the certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build
 against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a
different certificate type (non-CNG) or sign your own assertion as described at
https://aka.ms/msal-net-signed-assertion.  ---> Microsoft.Identity.Client.MsalClientException: Could not use the
certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build
against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different
 certificate type (non-CNG) or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion.  --->
System.Security.Cryptography.CryptographicException: Invalid provider type specified.

   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean
randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean
useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at
Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.GetCryptoProviderForSha256_Net45(X509Certificat
e2 certificate)
   --- End of inner exception stack trace ---
   at
Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.GetCryptoProviderForSha256_Net45(X509Certificat
e2 certificate)
   at Microsoft.Identity.Client.Platforms.net45.NetDesktopCryptographyManager.SignWithCertificate(String message,
X509Certificate2 certificate)
   at Microsoft.Identity.Client.Internal.JsonWebToken.Sign(ClientCredentialWrapper credential, Boolean sendX5C)
   at
Microsoft.Identity.Client.Internal.ClientCredentialWrapper.<AddConfidentialClientParametersAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<AddBodyParamsAndHeadersAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.OAuth2.TokenClient.<SendTokenRequestAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<FetchNewAccessTokenAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<RunAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.<ExecuteAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.MsalConfidentialClient.<AcquireTokenForClientCoreAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.MsalConfidentialClient.<AcquireTokenForClientAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.ClientCertificateCredential.<GetTokenAsync>d__25.MoveNext()
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.ClientCertificateCredential.<GetTokenAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.<GetAccessTokenAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount
account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1
promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account,
IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction,
String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment
environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean
skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList, Int32 maxContextPopulation,
String authScope)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass127_2.<ExecuteCmdlet>b__5()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass127_0.<ExecuteCmdlet>b__1(AzureRmProfile
 localProfile, RMProfileClient profileClient, String name)
DEBUG: 5:02:04 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning
default value [True].
Connect-AzAccount : ClientCertificateCredential authentication failed: Could not use the certificate for signing. See
inner exception for details. Possible cause: this may be a known issue with apps build against .NET Desktop 4.6 or
lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different certificate type (non-CNG)
or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion.
At line:1 char:1
+ Connect-AzAccount -ServicePrincipal -CertificatePath "XXXXXX ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], AuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

DEBUG: 5:02:04 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.8.0; CommandName: Connect-AzAccount; PSVersion: 5.1.19041.1682; IsSuccess:
False; Duration: 00:00:00.3096969; Exception: ClientCertificateCredential authentication failed: Could not use the
certificate for signing. See inner exception for details. Possible cause: this may be a known issue with apps build
against .NET Desktop 4.6 or lower. Either target a higher version of .NET desktop - 4.6.1 and above, or use a different
 certificate type (non-CNG) or sign your own assertion as described at https://aka.ms/msal-net-signed-assertion. ;
DEBUG: Finish sending metric.
DEBUG: 5:02:04 PM - ConnectAzureRmAccountCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.8.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig,
```

**Comment by dingmeng-xue** [comment]
Raised one question to MSAL repo.

**Comment by dingmeng-xue** [comment]
@lroan , I cannot reproduce your issue. It may relate to the type of your cert. According to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3391, it needs we update the version of MSAL. 

I have created an engineering build based on PR https://github.com/Azure/azure-powershell/pull/18579. Could you help to verify it with your cert?

You can install engineering package using below script.
```
Install-Module -Name Az.Tools.Installer -Repository PSGallery
Install-AzModule -Path https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.8.0.nupkg -RemovePrevious
```

**Comment by lroan** [comment]
@dingmeng-xue Thanks for looking at this!

I tested the engineering package, and it works with that build.

**Comment by dingmeng-xue** [comment]
@robinmalik , the link is expired. But no worries. The change is merged into main. The next release is July 5. https://github.com/Azure/azure-powershell/milestones

**Comment by dingmeng-xue** [comment]
My pleasure. Please try below code. Please uninstall Az.Accounts in advance just in case.
```
Install-Module -Name Az.Tools.Installer -Repository PSGallery
Install-AzModule -Path https://azposhpreview.blob.core.windows.net/public/Az.Accounts.2.8.0.nupkg -RemovePrevious
```

**Comment by robinmalik** [comment]
Thanks. I'll test this tomorrow when a colleague returns.

**Comment by robinmalik** [comment]
@dingmeng-xue After testing some working code on a development system with your patched module, we moved the code to the production system using the standard unpatched module and it worked. No patch needed for us then, in this case. Thanks for your help.

**Comment by sevaa** [comment]
Spent some time fighting with the Connect-AzAccount connection errors, will share my experience for anyone who stumbles upon this issue on their debugging journey.

In general, the "Connect-AzAccount : ClientCertificateCredential authentication failed: Invalid provider type specified." message pops up if the script can get to the certificate, but can't to get to the certificate's private key - over private key permissions or location.

In my particular case, the script was running in a no-stored-credentials scheduled task, the key was in the current user store, and the no-password tasks have a problem with that. Creating a cert with a key in the local machine key store solved that.

Internally, the .NET method that throws an exception with this message is RSACertificateExtensions.GetRSAPrivateKey(), passing the cert object. In place of your `Connect-AzAccount`, run the following:

```
$Thumb="..." #Paste the thumbprint that goes into the -CertificateThumbprint parameter
$Cert = Get-Item cert://LocalMachine/My/$Thumb # Or CurrentUser
[System.Security.Cryptography.X509Certificates.RSACertificateExtensions]::GetRSAPrivateKey($Cert)
```
If that gives you an invalid provider error, you where to look.
