### ISSUE TITLE
Get-AzExpressRoutePortsLocation for location CDC-Canberra-CBR20 hangs and eventually errors out after 15 minutes

### ISSUE THREAD

**Issue by PCSshell** [Azure/azure-powershell#18651]
### Description

If you execute "Get-AzExpressRoutePortsLocation -LocationName CDC-Canberra-CBR20" in a PowerShell session, the command hangs for over 15 minutes before it errors out and you cannot stop execution of the command by executing ctrl+c. The only course of action to recover is to close the PowerShell session or wait for the command to error out. This issue is specific to location "CDC-Canberra-CBR20"

### Issue script & Debug output

```PowerShell
> $DebugPreference="Continue"
DEBUG: 7:21:52 AM - GetAzureRMContextCommand end processing.

> Get-AzExpressRoutePortsLocation -LocationName CDC-Canberra-CBR20
DEBUG: 7:21:57 AM - GetAzureRmExpressRoutePortsLocation begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 7:21:57 AM - using account id 'REDACTED'.
DEBUG: [Common.Authentication]: Authenticating using Account: 'REDACTED', environment: 'AzureCloud', tenant: 'REDACTED'
DEBUG: 7:21:57 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'REDACTED', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'REDACTED'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57] Found 1 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57] Returning 1 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(7dc8ea6e-4ccb-4a18-a6ea-b3c27d3bd2c4)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 7dc8ea6e-4ccb-4a18-a6ea-b3c27d3bd2c4

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] Access token is not expired. Returning the found cache entry. [Current time (06/21/2022 13:21:57) - Expiration Time (06/21/2022 14:18:57 +00:00) - Extended Expiration Time (06/21/2022 14:18:57 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22000 [06/21/2022 13:21:57 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 06/21/2022 14:18:57 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-06-21T14:18:57.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'REDACTED', UserId: 'REDACTED'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.Network/ExpressRoutePortsLocations/CDC-Canberra-CBR20?api-version=2021-05-01

Headers:
x-ms-client-request-id        : 7b79d71a-dd27-40c8-a173-dda6ae411b89
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
InternalServerError

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : 74659fed-7a14-4be9-a529-2ed0eeac190b
x-ms-correlation-request-id   : 083c1a07-48cb-4755-85dc-b5278edc8f1a
x-ms-arm-service-request-id   : aceaad35-9c62-45e4-869f-b94a7d19ddf8
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-failure-cause            : service
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-routing-request-id       : EASTUS:20220621T133821Z:083c1a07-48cb-4755-85dc-b5278edc8f1a
X-Content-Type-Options        : nosniff
Date                          : Tue, 21 Jun 2022 13:38:21 GMT
Connection                    : close

Body:
{
  "error": {
    "code": "InternalServerError",
    "message": "An error occurred.",
    "details": []
  }
}


Get-AzExpressRoutePortsLocation: An error occurred.
StatusCode: 500
ReasonPhrase: Internal Server Error
ErrorCode: InternalServerError
ErrorMessage: An error occurred.
OperationID : 74659fed-7a14-4be9-a529-2ed0eeac190b
DEBUG: 7:38:20 AM - GetAzureRmExpressRoutePortsLocation end processing.
DEBUG: 7:38:20 AM - GetAzureRMContextCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name     
---------- -------    ---------- ---- 
Script     2.8.0                 Az.Accounts
Script     4.17.0                Az.Network 
Script     1.0.1                 Az.Tools.Predictor
```

### Error output

```PowerShell
 resolve-azerror
DEBUG: 7:41:19 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 7:41:19 AM - using account id 'REDACTED'...
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 5

RequestId      :
Message        : An error occurred.
                 StatusCode: 500
                 ReasonPhrase: Internal Server Error
                 ErrorCode: InternalServerError
                 ErrorMessage: An error occurred.
                 OperationID : 74659fed-7a14-4be9-a529-2ed0eeac190b
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {Get-AzExpressRoutePortsLocation}
Line           : Get-AzExpressRoutePortsLocation -LocationName CDC-Canberra-CBR20
Position       : At line:1 char:1
                 + Get-AzExpressRoutePortsLocation -LocationName CDC-Canberra-CBR20
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1
                 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 5


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 7:41:20 AM - ResolveError end processing.

DEBUG: 7:41:20 AM - GetAzureRMContextCommand end processing.
```

**Comment by SatishBoddu-MSFT** [comment]
Hello @PCSshell Thanks for reporting this issue.

We need to check if this location ("CDC-Canberra **-CBR20** ") is actually available or not. Please stay tuned on this page for further updates.

[Azure regions to ExpressRoute locations within a geopolitical region.](https://docs.microsoft.com/en-us/azure/expressroute/expressroute-locations#locations)

<img width="436" alt="image" src="https://user-images.githubusercontent.com/62923178/176017253-f7e19cb8-26ee-488f-8344-02e02d84acd1.png">

**Comment by PCSshell** [comment]
If you perform a Get-AzExpressRoutePortsLocation this location is returned in the results from the Get-AzExpressRoutePortsLocation command.

**Comment by SatishBoddu-MSFT** [comment]
> 

Yes, I agree and I too can see the list contains this location "CDC-Canberra -CBR20 ", but the documentation never shows that location and the exclusive Get call on the location ("CDC-Canberra -CBR20 ") is not returning anything....!

**Comment by SatishBoddu-MSFT** [comment]
Hello @PCSshell Thanks for asking this query.

We have got a confirmation on this issue!

_CBR20 is not a valid location. Below are the ER D locations for Canberra and Canberra2._ 

**CDC-Canberra
CDC-Canberra2** 

Get call will be fixed soon.
