### ISSUE TITLE
Get-AzApplicationInsights errors when passing ResourceId

### ISSUE THREAD

**Issue by caosborn** [Azure/azure-powershell#18707]
### Description

Get-AzApplicationInsights is erroring when passing the ResourceId parameter saying an internal function could not be found.

The expected result would be the Application Insights resource object.

Works as expected when passing the SubscriptionId, ResourceGroupName and Name values extracted from the resource Id value.

### Issue script & Debug output

```PowerShell
Get-AzApplicationInsights -ResourceId '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.insights/components/{name}'
Get-AzApplicationInsights: The term 'Az.ApplicationInsights.internal\Get-AzApplicationInsightsComponent' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     2.0.0                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzA…}
```

### Error output

```PowerShell
Message        : The term 'Az.ApplicationInsights.internal\Get-AzApplicationInsightsComponent' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           :                 $component = ($resourceId | . Az.ApplicationInsights.internal\Get-AzApplicationInsightsComponent)

Position       : At C:\Users\REDACTED\Documents\PowerShell\Modules\Az.ApplicationInsights\2.0.0\custom\Get-AzApplicationInsights.ps1:129 char:47
                 + … ourceId | . Az.ApplicationInsights.internal\Get-AzApplicationInsights …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3
```

**Comment by dingmeng-xue** [comment]
@VeryEarly , please look into this issue.
