### ISSUE TITLE
Get-AzAutomationJob (Az.Automation 1.7.3): Conversion from JSON failed with error: Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by ppaschedag** [Azure/azure-powershell#18783]
### Description

`Get-AzAutomationJob` fails on the latest version of Az.Automation with an error about JSON parsing. This error is identical to #15707 which was closed without actually resolving the issue, we have seens this issue for months and on all machines that I have tried it on (5+)

This error happens on windows 11 while using PowerShell 7. However Get-AzAutomationJob works correctly when using PowerShell 5.

### Issue script & Debug output

```PowerShell
Get-AzAutomationJob -Id [MyId] -ResourceGroupName [MyResourceGroupName] -AutomationAccountName [MyAutomationAccountName]
DEBUG: 16:19:17 - GetAzureAutomationJob begin processing with ParameterSet 'ByJobId'.
DEBUG: 16:19:17 - using account id 'xxx'...
DEBUG: 16:19:17 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxx', environment: 'AzureCloud', tenant: '[TenantId]'
DEBUG: 16:19:17 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'[TenantId]', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
??
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 8228846b-3fa4-4b12-8c3e-c0cd6bdf27a9
UserAssertion set: False
LongRunningOboCacheKey set: False

??
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-06-28T15:18:55.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '[TenantId]', UserId: 'xxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Automation/automationAccounts/xxx/jobs/xxx?api-version=2019-06-01

Headers:
x-ms-client-request-id        : xxx
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : xxx
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-resource-requests: 599
x-ms-correlation-request-id   : xxx
x-ms-routing-request-id       : WESTEUROPE:20220628T141917Z:xxx
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 28 Jun 2022 14:19:17 GMT

Body:
{
  "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Automation/automationAccounts/xxx/jobs/xxx",
  "name": "xxx",
  "type": "Microsoft.Automation/AutomationAccounts/Jobs",
  "properties": {
    "jobId": "xxx",
    "creationTime": "2022-06-28T14:38:42.4157697+02:00",
    "provisioningState": "Succeeded",
    "status": "Completed",
    "statusDetails": "None",
    "startedBy": null,
    "startTime": "2022-06-28T14:39:41.9844584+02:00",
    "endTime": "2022-06-28T14:39:56.5001867+02:00",
    "lastModifiedTime": "2022-06-28T14:39:56.5001867+02:00",
    "lastStatusModifiedTime": "2022-06-28T14:39:56.5001867+02:00",
    "exception": null,
    "parameters": {
      "ConfigurationScript": "Configuration JumpBox {\r\n\r\n    Import-DscResource -Module xPSDesiredStateConfiguration\r\n    Import-DscResource -Module PsDscResources\r\n    Import-DscResource -Module ComputerManagementDsc\r\n\r\n    Node $AllNodes.NodeName {\r\n\r\n        Registry 'DisableAutoUpdate' {\r\n            Ensure = 'Present'\r\n            Key = 'HKLM:\\Software\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU'\r\n            ValueName = 'NoAutoUpdate'\r\n            ValueType = 'Dword'\r\n            ValueData = '1'\r\n            Force = $true\r\n        }\r\n\r\n        Registry 'AutoDownloadUpdate' {\r\n            Ensure = 'Present'\r\n            Key = 'HKLM:\\Software\\Policies\\Microsoft\\Windows\\WindowsUpdate\\AU'\r\n            ValueName = 'AUOptions'\r\n            ValueType = 'Dword'\r\n            ValueData = '3'\r\n            Force = $true\r\n        }\r\n\r\n        foreach($DotNetCoreSetup in $Node.DotNetCore) {\r\n\r\n            xRemoteFile ('DownloadDotNetCore-{0}-HostingBundle' -f $DotNetCoreSetup.Version) {\r\n                Uri = '{0}{1}' -f $DotNetCoreSetup.Url, $Node.sasToken\r\n                DestinationPath = 'C:\\ConfigWorkingFolder\\dnhosting-{0}.exe' -f $DotNetCoreSetup.Version\r\n                MatchSource = $true\r\n            }\r\n\r\n            Package ('DotNetCore-{0}' -f $DotNetCoreSetup.Version) {\r\n                Ensure = 'Present'\r\n                Path = 'C:\\ConfigWorkingFolder\\dnhosting-{0}.exe' -f $DotNetCoreSetup.Version\r\n                Arguments = '/quiet'\r\n                Name = $DotNetCoreSetup.ProductName\r\n                ProductId = $DotNetCoreSetup.ProductId\r\n                LogPath = 'C:\\ConfigWorkingFolder\\DotNetCoreInstall.log'\r\n                DependsOn = '[xRemoteFile]DownloadDotNetCore-{0}-HostingBundle' -f $DotNetCoreSetup.Version\r\n            }\r\n\r\n        }\r\n\r\n    }\r\n\r\n}",
      "ConfigurationName": "JumpBox",
      "ParamsValue": "{\"ConfigurationData\":\"{\\\"AllNodes\\\":[{\\\"NodeName\\\":\\\"*\\\",\\\"dotNetCore\\\":[{\\\"ProductName\\\":\\\"Microsoft .NET 5.0.16 - Windows Server Hosting\\\",\\\"Version\\\":\\\"5.0.16\\\",\\\"ProductId\\\":\\\"{ded14c3c-21f9-479d-b127-1223819f44ce}\\\",\\\"Url\\\":\\\"https://xxx.blob.core.windows.net/deploymentfiles/dotnet-hosting-5.0.16-win.exe\\\"},{\\\"ProductName\\\":\\\"Microsoft .NET 6.0.5 - Windows Server Hosting\\\",\\\"Version\\\":\\\"6.0.5\\\",\\\"ProductId\\\":\\\"{623bc5ad-1ff0-4d68-95ee-02a5d4c10bf6}\\\",\\\"Url\\\":\\\"https://xxx.blob.core.windows.net/deploymentfiles/dotnet-hosting-6.0.5-win.exe\\\"}],\\\"sasToken\\\":\\\"?xxx\\\"},{\\\"NodeName\\\":\\\"jumpboxA\\\"},{\\\"NodeName\\\":\\\"jumpboxB\\\"}]}\"}",
      "SasUri": "xxx",
      "ConfigParamsDef": "",
      "NewNodeConfigurationBuildVersionRequired": "false"
    },
    "runOn": null,
    "runbook": {
      "name": "Compile-ConfigurationV3"
    }
  }
}


DEBUG: 16:19:17 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzAutomationJob: Conversion from JSON failed with error: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
DEBUG: 16:19:17 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Automation:1.7.3; CommandName: Get-AzAutomationJob; PSVersion: 7.2.5; IsSuccess: False; Duration: 00:00:00.2892092; Exception: Conversion from JSON failed with error: Unexpected character encountered while parsing value: C. Path '', line 0, position 0.;
DEBUG: Finish sending metric.
DEBUG: 16:19:17 - GetAzureAutomationJob end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     1.7.3                 Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAu…
```

### Error output

```PowerShell
HistoryId: 2

Message        : Conversion from JSON failed with error: Unexpected character encountered while parsing value: C. Path
                 '', line 0, position 0.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.Runspaces.Pipeline.Invoke()
                    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean p
                 erformSyncInvoke)
                    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 inpu
                 t, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSD
                 ataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`
                 1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke()
                    at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.InvokeScript(String scriptNam
                 e, Hashtable parameters)
                    at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.Deserialize(String json)
                    at Microsoft.Azure.Commands.Automation.Model.Job..ctor(String resourceGroupName, String accountName
                 , Job job)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetJob(String resourceGroupName, S
                 tring automationAccountName, Guid Id)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationJob.AutomationProcessRecord()
                    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T]
                 (T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T]
                 (T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.CmdletInvocationException
InvocationInfo : {Get-AzAutomationJob}
Line           : Get-AzAutomationJob -Id xxx -ResourceGroupName xxx -Aut
                 omationAccountName xxx
Position       : At line:1 char:1
                 + Get-AzAutomationJob -Id xxx -Resourc …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Conversion from JSON failed with error: Unexpected character encountered while parsing value: C. Path
                 '', line 0, position 0.
StackTrace     :    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable,
                 Nullable`1 maxDepth, ErrorRecord& error)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.EndProcessing()
                    at System.Management.Automation.Cmdlet.DoEndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzAutomationJob}
Line           : Get-AzAutomationJob -Id xxx -ResourceGroupName xxx -AutomationAccountName xxx
Position       : At line:1 char:1
                 + Get-AzAutomationJob -Id xxx -Resourc …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Unexpected character encountered while parsing value: C. Path '', line 0, position 0.
StackTrace     :    at Newtonsoft.Json.JsonTextReader.ParseValue()
                    at Newtonsoft.Json.JsonTextReader.Read()
                    at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
                    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type o
                 bjectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings se
                 ttings)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings)
                    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, Boolean returnHashtable,
                 Nullable`1 maxDepth, ErrorRecord& error)
Exception      : Newtonsoft.Json.JsonReaderException
InvocationInfo : {Get-AzAutomationJob}
Line           : Get-AzAutomationJob -Id xxx -ResourceGroupName xxx -AutomationAccountName xxx
Position       : At line:1 char:1
                 + Get-AzAutomationJob -Id xxx -Resourc …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by SatishBoddu-MSFT** [comment]
We are routing this to the service team's attention for further action!

**Comment by ppaschedag** [comment]
I have updated the AZ modules and the issue is no longer present, the new versions are:
Az.Accounts 2.10.1
Az.Automation 1.7.4
