### ISSUE TITLE
Internal Server Error when using Enable-AzAksAddOn

### ISSUE THREAD

**Issue by Luiz-Monad** [Azure/azure-powershell#18846]
### Description

I'm converting a script from `az` to `az module`

<details>
  <summary>Creating the cluster</summary>

```powershell

Install-Module -Name Az.Aks -Repository PSGallery
Install-Module -Name Az.Compute -Repository PSGallery
Install-Module -Name Az.Resources -Repository PSGallery

Import-Module Az.Aks
Import-Module Az.Compute
Import-Module Az.Resources

Login-AzAccount
$ssh = (Get-Content '~/.ssh/id_rsa.pub')

$resource_group = 'docker-swarm'
$cluster_location = 'westcentralus'
$cluster_name = 'swarm'
$dns_name = 'cluster'
$vnet_name = 'cluster-vnet'
$vnet_address = '10.0.0.0/8'
$vnet_subnet_k8s_name = 'default'
$vnet_subnet_k8s_address = '10.240.0.0/16'
$vnet_subnet_aci_name = 'aci'
$vnet_subnet_aci_address = '10.241.0.0/16'
$cluster_service_cidr = '10.0.0.0/16'
$cluster_dns_ip='10.0.0.10'
$cluster_docker_cidr = '172.17.0.1/16'
$service_principal = 'virtual-kubelet-sp'

New-AzResourceGroup `
    -Name $resource_group `
    -Location $cluster_location

$cluster_vnet = New-AzVirtualNetworkSubnetConfig `
    -Name $vnet_subnet_k8s_name `
    -AddressPrefix $vnet_subnet_k8s_address

$aci_vnet = New-AzVirtualNetworkSubnetConfig `
    -Name $vnet_subnet_aci_name `
    -AddressPrefix $vnet_subnet_aci_address

$vnet = New-AzVirtualNetwork `
    -ResourceGroupName $resource_group `
    -Location $cluster_location `
    -Name $vnet_name `
    -AddressPrefix $vnet_address `
    -Subnet $cluster_vnet, $aci_vnet

$sp = New-AzADServicePrincipal -DisplayName $service_principal
$pw = ConvertTo-SecureString -AsPlainText $sp.PasswordCredentials.SecretText
$cred = [System.Management.Automation.PSCredential]::new($sp.AppId, $pw)

New-AzRoleAssignment `
    -RoleDefinitionName 'Network Contributor' `
    -Scope ($vnet.Id) `
    -ApplicationId ($sp.AppId)

$cluster_vnet = Get-AzVirtualnetwork | 
    Get-AzVirtualNetworkSubnetConfig `
        -Name $vnet_subnet_k8s_name

New-AzAksCluster `
    -ResourceGroupName $resource_group `
    -Name $cluster_name `
    -SshKeyValue $ssh `
    -KubernetesVersion '1.22.6' `
    -DnsNamePrefix $dns_name `
    -NetworkPlugin azure `
    -LoadBalancerSku standard `
    -ServiceCidr $cluster_service_cidr `
    -DnsServiceIP $cluster_dns_ip `
    -DockerBridgeCidr $cluster_docker_cidr `
    -NodeName 'agentpool' `
    -NodeOsDiskSize 30 `
    -NodeCount 1 `
    -NodeMaxPodCount 250 `
    -NodePoolMode System `
    -NodeVmSetType VirtualMachineScaleSets `
    -NodeVmSize 'Standard_A2_v2' `
    -NodeVnetSubnetID $cluster_vnet.Id `
    -SubnetName $vnet_subnet_k8s_name `
    -EnableRbac:$false `
    -ServicePrincipalIdAndSecret $cred `
    -Verbose

```

</details>

This script bellow works.
```powershell
az aks addon enable `
    -g $resource_group `
    -n $cluster_name `
    --addon 'virtual-node' `
    --subnet-name $vnet_subnet_aci_name
```

This doesn't work. Both should produce the same result.
```powershell
$cluster = Get-AzAksCluster `
    -ResourceGroupName $resource_group `
    -Name $cluster_name 

$cluster | Enable-AzAksAddOn `
    -SubnetName $vnet_subnet_aci_name `
    -Name VirtualNode
```

### Script or Debug output

```PowerShell
$cluster = Get-AzAksCluster `
    -ResourceGroupName $resource_group `
    -Name $cluster_name

$cluster | Enable-AzAksAddOn `
    -SubnetName $vnet_subnet_aci_name `
    -Name VirtualNode

DEBUG: 1:48:35 PM - GetAzureRmAks begin processing with ParameterSet 'NameParameterSet'.
DEBUG: 1:48:35 PM - using account id 'mail@provider'...
DEBUG: 1:48:35 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Get-AzAksCluster' :
Get-AzAks will be removed in the next major release. Please use Get-AzAksCluster instead of Get-AzAks
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
DEBUG: [Common.Authentication]: Authenticating using Account: 'mail@provider', environment: 'AzureCloud', tenant: '[[GUID]]'
DEBUG: 1:48:35 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'[[GUID]]', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'mail@provider'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - b0c6dc7d-36c6-4965-abcc-40d48ccfdd99] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98] Found 4 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98] Returning 4 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - 47d771ef-0255-427e-83c8-d8fd16aee723] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(47d771ef-0255-427e-83c8-d8fd16aee723)
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - 47d771ef-0255-427e-83c8-d8fd16aee723] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - 47d771ef-0255-427e-83c8-d8fd16aee723] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - 47d771ef-0255-427e-83c8-d8fd16aee723] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - 47d771ef-0255-427e-83c8-d8fd16aee723] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - 47d771ef-0255-427e-83c8-d8fd16aee723] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 47d771ef-0255-427e-83c8-d8fd16aee723
UserAssertion set: False
LongRunningOboCacheKey set: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:35.98 - 47d771ef-0255-427e-83c8-d8fd16aee723] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:36.00 - 47d771ef-0255-427e-83c8-d8fd16aee723] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:36.00 - 47d771ef-0255-427e-83c8-d8fd16aee723] Access token is not expired. Returning the found cache entry. [Current time (06/30/2022 19:48:36) - Expiration Time (06/30/2022 20:09:29 +00:00) - Extended Expiration Time (06/30/2022 20:09:29 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:36.00 - 47d771ef-0255-427e-83c8-d8fd16aee723] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:36.00 - 47d771ef-0255-427e-83c8-d8fd16aee723] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:36.00 - 47d771ef-0255-427e-83c8-d8fd16aee723] Fetched access token from host login.microsoftonline.com. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:36.00 - 47d771ef-0255-427e-83c8-d8fd16aee723] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:36.00 - 47d771ef-0255-427e-83c8-d8fd16aee723]  AT expiration time: 2022-06-30 8:09:29 PM +00:00, scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default source Cache from login.microsoftonline.com appHashCode 37012383
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-06-30T20:09:29.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '[[GUID]]', UserId: 'mail@provider'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/[[GUID]]/resourceGroups/docker-swarm/providers/Microsoft.ContainerService/managedClusters/swarm?api-version=2021-05-01

Headers:
x-ms-client-request-id        : 7f8381c3-09f5-4249-98a6-fb9c7e8b9724
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-routing-request-id       : <<REDACTED>>
x-ms-ratelimit-remaining-subscription-reads: 11996
x-ms-correlation-request-id   : e8d8f85f-037f-4e85-b98c-ff8a3ac18c90
x-ms-request-id               : 55ae85ab-84e0-4322-a0bd-0bc219560e86
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Server                        : nginx
Date                          : Thu, 30 Jun 2022 19:48:38 GMT

Body:
{
  "id": "/subscriptions/[[GUID]]/resourcegroups/docker-swarm/providers/Microsoft.ContainerService/managedClusters/swarm",
  "location": "westcentralus",
  "name": "swarm",
  "type": "Microsoft.ContainerService/ManagedClusters",
  "properties": {
    "provisioningState": "Succeeded",
    "powerState": {
      "code": "Running"
    },
    "kubernetesVersion": "1.22.6",
    "dnsPrefix": "cluster",
    "fqdn": "cluster-[[ID]].hcp.westcentralus.azmk8s.io",
    "azurePortalFQDN": "cluster-[[ID]].portal.hcp.westcentralus.azmk8s.io",
    "agentPoolProfiles": [
      {
        "name": "agentpool",
        "count": 1,
        "vmSize": "Standard_A2_v2",
        "osDiskSizeGB": 30,
        "osDiskType": "Managed",
        "kubeletDiskType": "OS",
        "vnetSubnetID": "/subscriptions/[[GUID]]/resourceGroups/docker-swarm/providers/Microsoft.Network/virtualNetworks/cluster-vnet/subnets/default",
        "maxPods": 250,
        "type": "VirtualMachineScaleSets",
        "provisioningState": "Succeeded",
        "powerState": {
          "code": "Running"
        },
        "orchestratorVersion": "1.22.6",
        "mode": "System",
        "osType": "Linux",
        "osSKU": "Ubuntu",
        "nodeImageVersion": "AKSUbuntu-1804containerd-2022.06.22",
        "enableFIPS": false
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa REDACTED"
          }
        ]
      }
    },
    "windowsProfile": {
      "adminUsername": "azureuser",
      "enableCSIProxy": true
    },
    "servicePrincipalProfile": {
      "clientId": "[[GUID]]"
    },
    "addonProfiles": {
      "aciConnectorLinux": {
        "enabled": false,
        "config": null
      }
    },
    "nodeResourceGroup": "MC_docker-swarm_swarm_westcentralus",
    "enableRBAC": true,
    "networkProfile": {
      "networkPlugin": "azure",
      "loadBalancerSku": "Standard",
      "loadBalancerProfile": {
        "managedOutboundIPs": {
          "count": 1
        },
        "effectiveOutboundIPs": [
          {
            "id": "/subscriptions/[[GUID]]/resourceGroups/MC_docker-swarm_swarm_westcentralus/providers/Microsoft.Network/publicIPAddresses/[[GUID]]"
          }
        ]
      },
      "serviceCidr": "10.0.0.0/16",
      "dnsServiceIP": "10.0.0.10",
      "dockerBridgeCidr": "172.17.0.1/16",
      "outboundType": "loadBalancer"
    },
    "maxAgentPools": 100
  },
  "sku": {
    "name": "Basic",
    "tier": "Free"
  }
}


DEBUG: 1:48:38 PM - GetAzureRmAks end processing.
DEBUG: 1:48:38 PM - EnableAzureRmAddons begin processing with ParameterSet 'InputObjectParameterSet'.
DEBUG: 1:48:38 PM - using account id 'mail@provider'...
DEBUG: 1:48:38 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'mail@provider', environment: 'AzureCloud', tenant: '[[GUID]]'
DEBUG: 1:48:38 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'[[GUID]]', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'mail@provider'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - 1223498d-2cd6-4c6c-89b2-b7bcc9278bdd] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71] Found 4 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71] Returning 4 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(b1cf21f2-34a2-4e59-8894-e46da3bc0c7b)
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b
UserAssertion set: False
LongRunningOboCacheKey set: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.71 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.73 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.73 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] Access token is not expired. Returning the found cache entry. [Current time (06/30/2022 19:48:38) - Expiration Time (06/30/2022 20:09:29 +00:00) - Extended Expiration Time (06/30/2022 20:09:29 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.73 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.73 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.73 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] Fetched access token from host login.microsoftonline.com. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.73 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [06-30 19:48:38.73 - b1cf21f2-34a2-4e59-8894-e46da3bc0c7b]  AT expiration time: 2022-06-30 8:09:29 PM +00:00, scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default source Cache from login.microsoftonline.com appHashCode 57705536
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-06-30T20:09:29.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '[[GUID]]', UserId: 'mail@provider'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/[[GUID]]/resourceGroups/docker-swarm/providers/Microsoft.ContainerService/managedClusters/swarm?api-version=2021-05-01

Headers:
x-ms-client-request-id        : cf6d8a9c-5f96-4467-a63c-6726b5f99e4f
Accept-Language               : en-US

Body:
{
  "properties": {
    "kubernetesVersion": "1.22.6",
    "dnsPrefix": "cluster",
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa REDACTED"
          }
        ]
      }
    },
    "windowsProfile": {
      "adminUsername": "azureuser"
    },
    "addonProfiles": {
      "aciConnectorLinux": {
        "enabled": true,
        "config": {
          "SubnetName": "aci"
        }
      }
    },
    "nodeResourceGroup": "MC_docker-swarm_swarm_westcentralus",
    "enableRBAC": true,
    "networkProfile": {
      "networkPlugin": "azure",
      "serviceCidr": "10.0.0.0/16",
      "dnsServiceIP": "10.0.0.10",
      "dockerBridgeCidr": "172.17.0.1/16",
      "loadBalancerSku": "Standard",
      "loadBalancerProfile": {
        "managedOutboundIPs": {
          "count": 1
        },
        "effectiveOutboundIPs": [
          {
            "id": "/subscriptions/[[GUID]]/resourceGroups/MC_docker-swarm_swarm_westcentralus/providers/Microsoft.Network/publicIPAddresses/[[GUID]]"
          }
        ]
      }
    },
    "identityProfile": {},
    "privateLinkResources": []
  },
  "location": "westcentralus",
  "tags": {}
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
InternalServerError

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : service
x-ms-correlation-request-id   : dccb190d-7793-471f-b2a0-a4031b2c5ad6
x-ms-request-id               : f02137e2-0714-415f-b206-915ed0e6f71a
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : nginx
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-routing-request-id       : <<REDACTED>>
X-Content-Type-Options        : nosniff
Date                          : Thu, 30 Jun 2022 19:49:08 GMT
Connection                    : close

Body:
{
  "code": "InternalOperationError",
  "message": "Internal server error"
}


DEBUG: 1:49:07 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Enable-AzAksAddOn: 
Line |
   5 |  $cluster | Enable-AzAksAddOn `
     |             ~~~~~~~~~~~~~~~~~~~
     | Internal server error
DEBUG: 1:49:07 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 1:49:07 PM - EnableAzureRmAddons end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.1.0                 Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNodePool…}
Script     4.26.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     4.16.1                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzApplicati…
Script     5.6.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
Resolve-AzError
DEBUG: 1:58:32 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 1:58:32 PM - using account id 'mail@profile'...
DEBUG: 1:58:32 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 84

RequestId      : e3d0713e-7465-47b6-bf08-baed1a32863b
Message        : Internal server error
ServerMessage  : InternalOperationError: Internal server error (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {InternalServerError}
RequestMessage : {PUT https://management.azure.com/subscriptions/[[GUID]]/resourceGroups/docker-swarm/providers/Microsoft.ContainerService/managedClusters/swarm?api-version=2021-05-01}
InvocationInfo : {Enable-AzAksAddOn}
Line           : $cluster | Enable-AzAksAddOn `

Position       : At line:5 char:12
                 + $cluster | Enable-AzAksAddOn `
                 +            ~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceName, ManagedCluster parameters, Dictionary`2      
                 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceName, ManagedCluster parameters, Dictionary`2
                 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperationsExtensions.CreateOrUpdateAsync(IManagedClustersOperations operations, String resourceGroupName, String resourceName, ManagedCluster   
                 parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ContainerService.ManagedClustersOperationsExtensions.CreateOrUpdate(IManagedClustersOperations operations, String resourceGroupName, String resourceName, ManagedCluster        
                 parameters)
                    at Microsoft.Azure.Commands.Aks.Commands.UpdateAddonsBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 84
```

**Comment by dingmeng-xue** [comment]
@Luiz-Monad , thanks for reporting issue. Could you help to share the output of cli script execution?

**Comment by Luiz-Monad** [comment]
The only output I have is that `Output error`.
