### ISSUE TITLE
Publish-AzWebApp reports deployment failure, Portal/Kudu reports successful deployment

### ISSUE THREAD

**Issue by jfitch11** [Azure/azure-powershell#18896]
### Description

When performing a zip deploy via `Publish-AzWebApp `the cmdlet reports a deployment failure however the Deployment Center on the Azure Web App reports a success (and I confirmed my code updated sucessfully). `Publish-AzWebApp` is run following an ARM template deployment of the web app + appsettings + connectionstrings

### Issue script & Debug output

```PowerShell
DEBUG:   57+      >>>> Publish-AzWebApp @publishToAppParams
DEBUG: 12:17:13 - PublishAzureWebAppCmdlet begin processing with ParameterSet 'FromResourceName'.
DEBUG: 12:17:13 - using account id '[Redacted]'...
DEBUG: 12:17:13 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default
value [True].
VERBOSE: Performing the operation "The web app has been deployed." on target "[Redacted]".
DEBUG: [Common.Authentication]: Authenticating using Account: '[Redacted]', environment: 'AzureCloud', tenant:
'[Redacted]'
DEBUG: 12:17:13 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync -
TenantId:'[Redacted]', Scopes:'https://management.core.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId:'[Redacted]'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - e13309cd-5d10-404e-b23c-4ef598375d87]
IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - e13309cd-5d10-404e-b23c-4ef598375d87]
[Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - e13309cd-5d10-404e-b23c-4ef598375d87]
[Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - e13309cd-5d10-404e-b23c-4ef598375d87]
IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - e13309cd-5d10-404e-b23c-4ef598375d87]
IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86] Found 1 cache accounts and 0 broker
accounts
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86] Returning 1 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
MSAL MSAL.Desktop with assembly version '4.39.0.0'. CorrelationId(de623a56-d57b-4992-a457-a02c66f27764)
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764] ===
 AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - de623a56-d57b-4992-a457-a02c66f27764
UserAssertion set: False
LongRunningOboCacheKey set: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764] ===
 Token Acquisition (SilentRequest) started:
  Scopes: https://management.core.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
[Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
Access token is not expired. Returning the found cache entry. [Current time (07/07/2022 16:17:13) - Expiration Time (07/07/2022
16:46:02 +00:00) - Extended Expiration Time (07/07/2022 16:46:02 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
[Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
Fetched access token from host login.microsoftonline.com.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [07/07 16:17:13.86 - de623a56-d57b-4992-a457-a02c66f27764]  AT
 expiration time: 7/7/2022 16:46:02 +00:00, scopes https://management.core.windows.net//user_impersonation
https://management.core.windows.net//.default source Cache from login.microsoftonline.com appHashCode 59331185
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
ExpiresOn: 2022-07-07T16:46:02.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '[Redacted]', UserId:
'[Redacted]'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/[Redacted]/resourceGroups/[Redacted]/providers/Microsoft.Web/sites
/[Redacted]/config/publishingcredentials/list?api-version=2021-01-15

Headers:
x-ms-client-request-id        : 57c341a7-b7aa-4ea7-89a1-2cd6be851dce
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : c9d33678-3d42-4f96-8e16-47db735dc021
x-ms-ratelimit-remaining-subscription-resource-requests: 11996
x-ms-correlation-request-id   : df33e7e8-75d7-4386-8f92-79ba2cfb2392
x-ms-routing-request-id       : CANADAEAST:20220707T161715Z:df33e7e8-75d7-4386-8f92-79ba2cfb2392
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 07 Jul 2022 16:17:14 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id":
"/subscriptions/[Redacted]/resourceGroups/[Redacted]/providers/Microsoft.Web/sites/[Redacted]/publishing
credentials/$[Redacted]",
  "name": "[Redacted]",
  "type": "Microsoft.Web/sites/publishingcredentials",
  "location": "East US",
  "tags": {},
  "properties": {
    "name": null,
    "publishingUserName": "$[Redacted]",
    "publishingPassword": "[Redacted]",
    "publishingPasswordHash": null,
    "publishingPasswordHashSalt": null,
    "metadata": null,
    "isDeleted": false,
    "scmUri":
"https://$[Redacted]:[Redacted]@[Redacted].scm.azurewebsites.net"
  }
}

DEBUG: 12:18:55 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG:   19+                                         if ( &  >>>> { Set-StrictMode -Version 1; $_.PSMessageDetails } ) {
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   19+                                         if ( & {  >>>> Set-StrictMode -Version 1; $_.PSMessageDetails } ) {
DEBUG:   19+                                         if ( & { Set-StrictMode -Version 1;  >>>> $_.PSMessageDetails } ) {
DEBUG:    1+ &  >>>> { Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails }
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:    1+ & {  >>>> Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails }
DEBUG:    1+ & { Set-StrictMode -Version 1;  >>>> $this.Exception.InnerException.PSMessageDetails }
DEBUG:    1+ & { Set-StrictMode -Version 1; $this.Exception.InnerException.PSMessageDetails  >>>> }
DEBUG:   19+                                         if ( & { Set-StrictMode -Version 1; $_.PSMessageDetails  >>>> } ) {
DEBUG:   26+                                         $errorCategoryMsg = &  >>>> { Set-StrictMode -Version 1;
$_.ErrorCategory_Message }
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   26+                                         $errorCategoryMsg = & {  >>>> Set-StrictMode -Version 1;
$_.ErrorCategory_Message }
DEBUG:   26+                                         $errorCategoryMsg = & { Set-StrictMode -Version 1;  >>>>
$_.ErrorCategory_Message }
DEBUG:   26+                                         $errorCategoryMsg = & { Set-StrictMode -Version 1; $_.ErrorCategory_Message
>>>> }
DEBUG:   42+                                         $originInfo = &  >>>> { Set-StrictMode -Version 1; $_.OriginInfo }
DEBUG:     ! CALL function '<ScriptBlock>'
DEBUG:   42+                                         $originInfo = & {  >>>> Set-StrictMode -Version 1; $_.OriginInfo }
DEBUG:   42+                                         $originInfo = & { Set-StrictMode -Version 1;  >>>> $_.OriginInfo }
DEBUG:   42+                                         $originInfo = & { Set-StrictMode -Version 1; $_.OriginInfo  >>>> }
Publish-AzWebApp : One or more errors occurred.
At C:\Git\DevOpsTools\azure_powershell\DeploySteps\Invoke-AppCodeDeploy.ps1:57 char:5
+     Publish-AzWebApp @publishToAppParams
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzWebApp], AggregateException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet

DEBUG: 12:18:55 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default
value [True].
DEBUG: AzureQoSEvent: Module: Az.Websites:2.11.2; CommandName: Publish-AzWebApp; PSVersion: 5.1.19041.1682; IsSuccess: False;
Duration: 00:01:41.5874493; Exception: One or more errors occurred.;
DEBUG: Finish sending metric.
DEBUG: 12:18:56 - PublishAzureWebAppCmdlet end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.9.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCo...
Script     1.1.2      Az.Advisor                          {Get-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Disable...
Script     4.2.0      Az.Aks                              {Get-AzAksCluster, New-AzAksCluster, Remove-AzAksCluster, Import-AzAk...
Script     1.1.4      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, G...
Script     3.0.0      Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Ad...
Script     1.1.0      Az.AppConfiguration                 {Get-AzAppConfigurationStore, Get-AzAppConfigurationStoreKey, New-AzA...
Script     2.1.0      Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzAp...
Script     1.0.0      Az.Attestation                      {New-AzAttestation, Get-AzAttestation, Remove-AzAttestation, Get-AzAt...
Script     1.7.3      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGr...
Script     3.2.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKey, Ne...
Script     2.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, ...
Script     2.1.0      Az.Cdn                              {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointContent, Dis...
Script     1.1.0      Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-AzCloudServi...
Script     1.11.0     Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, G...
Script     4.29.0     Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilityS...
Script     3.1.0      Az.ContainerInstance                {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-AzContainer...
Script     3.0.0      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainer...
Script     1.8.2      Az.CosmosDB                         {Get-AzCosmosDBSqlContainer, Get-AzCosmosDBSqlContainerThroughput, Ge...
Script     1.1.0      Az.DataBoxEdge                      {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeDevice, Invoke-AzDataBoxEdgeD...
Script     1.2.0      Az.Databricks                       {Get-AzDatabricksOutboundNetworkDependenciesEndpoint, Get-AzDatabrick...
Script     1.16.8     Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Re...
Script     1.0.2      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCre...
Script     1.3.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedI...
Script     1.0.1      Az.DataShare                        {New-AzDataShareAccount, Get-AzDataShareAccount, Remove-AzDataShareAc...
Script     1.1.0      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, New-AzDeploymentManagerArtifa...
Script     3.1.0      Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-AzWvdApplica...
Script     1.0.2      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDt...
Script     1.1.2      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Se...
Script     1.3.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, Ne...
Script     2.1.0      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubName...
Script     1.9.0      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFrontDoor, Set-AzFrontDoor, Remove-AzFrontDoo...
Script     4.0.3      Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctio...
Script     5.0.1      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsi...
Script     2.0.0      Az.HealthcareApis                   {Get-AzHealthcareApisService, Get-AzHealthcareApisWorkspace, Get-AzHe...
Script     2.7.4      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConn...
Script     4.6.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyV...
Script     2.1.0      Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabasePrincipal, G...
Script     1.5.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly,...
Script     1.1.3      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-A...
Script     1.2.0      Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceC...
Script     1.0.0      Az.ManagedServiceIdentity           {Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity, New-AzUser...
Script     3.0.0      Az.ManagedServices                  {Get-AzManagedServicesAssignment, Get-AzManagedServicesDefinition, Ge...
Script     1.0.2      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1      Az.Media                            {Sync-AzMediaServiceStorageKey, Set-AzMediaServiceKey, Get-AzMediaSer...
Script     1.1.2      Az.Migrate                          {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMigrateProjec...
Script     3.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLog...
Script     1.0.0      Az.MySql                            {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Get-AzMySqlFi...
Script     4.18.0     Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplication...
Script     1.1.1      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-A...
Script     3.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperation...
Script     1.5.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-...
Script     1.1.0      Az.PostgreSql                       {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnectionString, Get...
Script     1.2.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectio...
Script     1.0.3      Az.PrivateDns                       {Get-AzPrivateDnsZone, Remove-AzPrivateDnsZone, Set-AzPrivateDnsZone,...
Script     5.4.1      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, G...
Script     1.6.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get...
Script     1.0.0      Az.RedisEnterpriseCache             {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache, Get-AzRed...
Script     1.0.3      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Re...
Script     1.1.0      Az.ResourceMover                    {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveCollection, ...
Script     6.0.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignme...
Script     1.3.0      Az.Security                         {Get-AzSecuritySolution, Get-AzSecuritySolutionsReferenceData, New-Az...
Script     1.1.0      Az.SecurityInsights                 {Get-AzSentinelAlertRuleAction, New-AzSentinelAlertRuleAction, Remove...
Script     1.10.0     Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceB...
Script     3.1.0      Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricNode, Add-A...
Script     1.4.1      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     3.10.0     Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTranspa...
Script     1.1.0      Az.SqlVirtualMachine                {New-AzSqlVM, Get-AzSqlVM, Update-AzSqlVM, Remove-AzSqlVM...}
Script     1.3.0      Az.StackHCI                         {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestation, Disable-...
Script     4.7.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount,...
Script     1.7.0      Az.StorageSync                      {Invoke-AzStorageSyncCompatibilityCheck, New-AzStorageSyncService, Ge...
Script     2.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsClusterStreamingJ...
Script     1.0.0      Az.Support                          {Get-AzSupportService, Get-AzSupportProblemClassification, Get-AzSupp...
Script     1.4.0      Az.Synapse                          {Get-AzSynapseSparkJob, Stop-AzSynapseSparkJob, Submit-AzSynapseSpark...
Script     1.1.0      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerC...
Script     2.11.2     Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Re...
```

### Error output

```PowerShell
Message        : A task was canceled.
StackTrace     :
Exception      : System.Threading.Tasks.TaskCanceledException
InvocationInfo : {Publish-AzWebApp}
Line           :     Publish-AzWebApp @publishToAppParams

Position       : At C:\Git\DevOpsTools\azure_powershell\DeploySteps\Invoke-AppCodeDeploy.ps1:57 char:5
                 +     Publish-AzWebApp @publishToAppParams
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 13
```

**Comment by Kotasudhakarreddy** [comment]
Unable to Repro the issue when performing zip deployment. Is it occurring continuously or sporadically?

**Comment by Kotasudhakarreddy** [comment]
closing due to lack of response. Please file a new issue if this is still a problem.

**Comment by daninthemix** [comment]
I'm having exactly this issue - errors with the commandlet but the OneDeploy task is successful. 
```
writeErrorStream      : True
Exception             : System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
                           --- End of inner exception stack trace ---
                           at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
                           at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet.<>c__DisplayClass45_0.<ExecuteCmdlet>b__0()
                           at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
                           at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action)
                           at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet.ExecuteCmdlet()
                           at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
                        ---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
                        
TargetObject          : 
CategoryInfo          : CloseError: (:) [Publish-AzWebApp], AggregateException
FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.PublishAzureWebAppCmdlet
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, C:\Downloads\testing.ps1: line 8
PipelineIterationInfo : {0, 1}
PSMessageDetails      : 
```
