### ISSUE TITLE
Get-AzNotificationHub fails in AzureChinaCloud

### ISSUE THREAD

**Issue by dduede** [Azure/azure-powershell#18910]
### Description

When running the cmdlet `Get-AzNotificationHub` in an `AzureChinaCloud` environment, the cmdlet fails with `Get-AzNotificationHub: Value cannot be null. (Parameter 'source')`.

The cmdlet is working as expected in our european subscriptions.

### Issue script & Debug output

```PowerShell
PS> $ns = Get-AzNotificationHubsNamespace | select -First 1
PS> Get-AzNotificationHub -ResourceGroup $ns.ResourceGroupName -Namespace $ns.Name
Get-AzNotificationHub: Value cannot be null. (Parameter 'source')
```

### Environment data

```PowerShell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     2.0.0                 Az.EventHub                         {Add-AzEventHubIPRule, Add-AzEventHubVirtualNetwo…
Script     1.1.1                 Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuth…
```

### Error output

```PowerShell
Message        : Value cannot be null. (Parameter 'source')
StackTrace     :    at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
                    at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
                    at Microsoft.Azure.Commands.NotificationHubs.NotificationHubsManagementClient.ListNotificationHubs(
                 String resourceGroupName, String namespaceName)
                    at Microsoft.Azure.Commands.NotificationHubs.Commands.NotificationHub.GetAzureNotificationHub.Execu
                 teCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentNullException
InvocationInfo : {Get-AzNotificationHub}
Line           : Get-AzNotificationHub -ResourceGroup $ns.ResourceGroupName -Namespace $ns.Name
Position       : At line:1 char:1
                 + Get-AzNotificationHub -ResourceGroup $ns.ResourceGroupName -Namespace …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 36
```

**Comment by dduede** [comment]
I've just attempted running the same cmdlet again and it seems its working now. Can this happen from an outage in china? We had this issue for a few days (over the weekend), so I wasn't sure if this was just an outage. We'll keep an eye on it but it seems to working fine now.
