### ISSUE TITLE
Set-AzDiagnosticSetting failing to modify diagnostic setting with one or more category groups selected because it is using an old api-version.

### ISSUE THREAD

**Issue by TwoPatient** [Azure/azure-powershell#18937]
### Description

When running Set-AzDiagnosticSetting on the master database for Azure SQL I am getting the following error:

##[error]Exception type: ErrorResponseException, Message: Invalid API version used to modify diagnostic setting with one or more category groups selected: audit, please use version higher than: 2021-05-01-preview, Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request

### Issue script & Debug output

```PowerShell
DEBUG: 9:06:43 AM - SetAzureRmDiagnosticSettingCommand begin processing with ParameterSet 'OldSetDiagnosticSetting'.
DEBUG: 9:06:43 AM - using account id 'MSI@50342'...
DEBUG: 9:06:43 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: 9:06:43 AM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 9:06:43 AM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
DEBUG: 9:06:43 AM - Processing using command line arguments
DEBUG: 9:06:43 AM - Listing existing diagnostics settings for resourceId '/subscriptions/xxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxx/providers/Microsoft.Sql/servers/xxxxxxxxxxx/databases/master'
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: 'xxxxxxxxxxxxxxxx'
DEBUG: 9:06:43 AM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'xxxxxxxxxxxxxxxxxxxx', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId: 
DEBUG: Request [21a35c9f-f5f4-4acf-a1bb-5f4ea3cf248a] POST http://localhost:50342/oauth2/token
Metadata:REDACTED
x-ms-client-request-id:21a35c9f-f5f4-4acf-a1bb-5f4ea3cf248a
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.0,(.NET 6.0.6; Linux 5.4.0-1086-azure #91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [21a35c9f-f5f4-4acf-a1bb-5f4ea3cf248a] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"c8a-aFzHGhCmYJ55BzPJMpiMQjkgFbQ"
Date:Thu, 14 Jul 2022 09:06:43 GMT
Connection:keep-alive
Content-Type:application/json; charset=utf-8
Content-Length:3210

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  ExpiresOn: 2022-07-14T10:12:23.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxxxxxxxxxxxxxxxxx', UserId: 'MSI@50342'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/Microsoft.Insights/diagnosticSettings?api-version=2017-05-01-preview

Headers:
x-ms-client-request-id        : cefaeb80-9fda-4ea5-bb79-508ba9f0e3c0
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : ea79def3-3551-46dc-b1ba-3bcbed2d28c5
Server                        : Microsoft-IIS/10.0
x-ms-ratelimit-remaining-subscription-reads: 11996
x-ms-correlation-request-id   : 36c53e2b-a013-4b8c-8dbd-15a64fcd5118
x-ms-routing-request-id       : WESTEUROPE:20220714T090645Z:36c53e2b-a013-4b8c-8dbd-15a64fcd5118
X-Content-Type-Options        : nosniff
Date                          : Thu, 14 Jul 2022 09:06:44 GMT

Body:
{
  "value": []
}


DEBUG: 9:06:45 AM - Diagnostic setting named: 'audit' not found in list of 0 settings. Creating a new one.
DEBUG: 9:06:45 AM - Retrieving supported categories for resource: '/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/Microsoft.Insights/diagnosticSettingsCategories?api-version=2017-05-01-preview

Headers:
x-ms-client-request-id        : cefaeb80-9fda-4ea5-bb79-508ba9f0e3c0
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : f557c1c3-edf0-48da-8ea4-e18c9dab0d1d
Server                        : Microsoft-IIS/10.0
x-ms-ratelimit-remaining-subscription-reads: 11995
x-ms-correlation-request-id   : efa7a0db-ec2a-4b94-85fa-cbb0b129be12
x-ms-routing-request-id       : WESTEUROPE:20220714T090645Z:efa7a0db-ec2a-4b94-85fa-cbb0b129be12
X-Content-Type-Options        : nosniff
Date                          : Thu, 14 Jul 2022 09:06:45 GMT

Body:
{
  "value": [
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/SQLInsights",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "SQLInsights",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/AutomaticTuning",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "AutomaticTuning",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/QueryStoreRuntimeStatistics",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "QueryStoreRuntimeStatistics",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/QueryStoreWaitStatistics",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "QueryStoreWaitStatistics",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/Errors",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "Errors",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/DatabaseWaitStatistics",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "DatabaseWaitStatistics",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/Timeouts",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "Timeouts",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/Blocks",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "Blocks",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/Deadlocks",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "Deadlocks",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/DevOpsOperationsAudit",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "DevOpsOperationsAudit",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/SQLSecurityAuditEvents",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "SQLSecurityAuditEvents",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Logs"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/Basic",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "Basic",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Metrics"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/InstanceAndAppAdvanced",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "InstanceAndAppAdvanced",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Metrics"
      },
      "identity": null
    },
    {
      "id": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxxx/providers/microsoft.sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/microsoft.insights/diagnosticSettingsCategories/WorkloadManagement",
      "type": "microsoft.insights/diagnosticSettingsCategories",
      "name": "WorkloadManagement",
      "location": null,
      "kind": null,
      "tags": null,
      "properties": {
        "categoryType": "Metrics"
      },
      "identity": null
    }
  ]
}


DEBUG: 9:06:45 AM - Setting supported categories for resource: '/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master'
DEBUG: 9:06:45 AM - Merging data. Existing setting is: not null
DEBUG: 9:06:45 AM - Setting workspace Id
DEBUG: 9:06:45 AM - Setting LogAnalyticsDestinationType
DEBUG: 9:06:45 AM - Changing the enable properties
DEBUG: 9:06:45 AM - Setting Enabled property for logs
DEBUG: 9:06:45 AM - Setting Enabled property for metrics
DEBUG: 9:06:45 AM - Copying diagnostic settings
DEBUG: 9:06:45 AM - Sending create/update request setting: audit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com//subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Sql/servers/xxxxxxxxxxxxxxxxxxxx/databases/master/providers/Microsoft.Insights/diagnosticSettings/audit?api-version=2017-05-01-preview

Headers:
x-ms-client-request-id        : cefaeb80-9fda-4ea5-bb79-508ba9f0e3c0
Accept-Language               : en-US

Body:
{
  "properties": {
    "metrics": [
      {
        "category": "Basic",
        "enabled": true
      },
      {
        "category": "InstanceAndAppAdvanced",
        "enabled": true
      },
      {
        "category": "WorkloadManagement",
        "enabled": true
      }
    ],
    "logs": [
      {
        "category": "SQLInsights",
        "enabled": true
      },
      {
        "category": "AutomaticTuning",
        "enabled": true
      },
      {
        "category": "QueryStoreRuntimeStatistics",
        "enabled": true
      },
      {
        "category": "QueryStoreWaitStatistics",
        "enabled": true
      },
      {
        "category": "Errors",
        "enabled": true
      },
      {
        "category": "DatabaseWaitStatistics",
        "enabled": true
      },
      {
        "category": "Timeouts",
        "enabled": true
      },
      {
        "category": "Blocks",
        "enabled": true
      },
      {
        "category": "Deadlocks",
        "enabled": true
      },
      {
        "category": "DevOpsOperationsAudit",
        "enabled": true
      },
      {
        "category": "SQLSecurityAuditEvents",
        "enabled": true
      }
    ],
    "workspaceId": "/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourcegroups/dev_westeurope_logs/providers/Microsoft.OperationalInsights/workspaces/lvsdevwesteuroperesourceauditlogs"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
Server                        : Microsoft-IIS/10.0
x-ms-ratelimit-remaining-subscription-resource-requests: 148
x-ms-correlation-request-id   : 27c65996-02df-4246-82a4-4780d56508e9
x-ms-routing-request-id       : WESTEUROPE:20220714T090647Z:27c65996-02df-4246-82a4-4780d56508e9
X-Content-Type-Options        : nosniff
Date                          : Thu, 14 Jul 2022 09:06:47 GMT

Body:
{
  "code": "BadRequest",
  "message": "Invalid API version used to modify diagnostic setting with one or more category groups selected: audit, please use version higher than: 2021-05-01-preview"
}


DEBUG: 9:06:47 AM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Set-AzDiagnosticSetting: Exception type: ErrorResponseException, Message: Invalid API version used to modify diagnostic setting with one or more category groups selected: audit, please use version higher than: 2021-05-01-preview, Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request
DEBUG: 9:06:47 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Monitor:3.0.1; CommandName: Set-AzDiagnosticSetting; PSVersion: 7.2.5; IsSuccess: False; Duration: 00:00:03.6994766; Exception: Exception type: ErrorResponseException, Message: Invalid API version used to modify diagnostic setting with one or more category groups selected: audit, please use version higher than: 2021-05-01-preview, Code: BadRequest, Status code:BadRequest, Reason phrase: Bad Request;
DEBUG: Finish sending metric.
DEBUG: 9:06:47 AM - SetAzureRmDiagnosticSettingCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Linux 5.4.0-1086-azure #91~18.04.1-Ubuntu SMP Thu Jun 23 20:33:05 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.9.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-Az…
Script     4.29.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendCo…
Script     3.0.1                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertR…
Script     4.18.0                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApp…
Script     6.0.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAss…
Script     4.7.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManag…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwne…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
DEBUG: 9:09:35 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 9:09:35 AM - using account id 'MSI@50342'...
DEBUG: 9:09:35 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 13

Message        : Exception type: ErrorResponseException, Message: Invalid API version used to modify diagnostic setting with one 
                 or more category groups selected: audit, please use version higher than: 2021-05-01-preview, Code: BadRequest, 
                 Status code:BadRequest, Reason phrase: Bad Request
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at 
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T 
                 c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, 
                 Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 13

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(String 
                 resourceUri, DiagnosticSettingsResource parameters, String name, Dictionary`2 customHeaders, CancellationToken 
                 cancellationToken)
                    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperationsExtensions.CreateOrUpdateAsync(IDiagnosticSet
                 tingsOperations operations, String resourceUri, DiagnosticSettingsResource parameters, String name, 
                 CancellationToken cancellationToken)
Exception      : Microsoft.Azure.Management.Monitor.Models.ErrorResponseException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 13


   HistoryId: 11

Message        : Exception type: ErrorResponseException, Message: Invalid API version used to modify diagnostic setting with one 
                 or more category groups selected: audit, please use version higher than: 2021-05-01-preview, Code: BadRequest, 
                 Status code:BadRequest, Reason phrase: Bad Request
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at 
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T 
                 c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, 
                 Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(String 
                 resourceUri, DiagnosticSettingsResource parameters, String name, Dictionary`2 customHeaders, CancellationToken 
                 cancellationToken)
                    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperationsExtensions.CreateOrUpdateAsync(IDiagnosticSet
                 tingsOperations operations, String resourceUri, DiagnosticSettingsResource parameters, String name, 
                 CancellationToken cancellationToken)
Exception      : Microsoft.Azure.Management.Monitor.Models.ErrorResponseException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11


   HistoryId: 7

Message        : Exception type: ErrorResponseException, Message: Invalid API version used to modify diagnostic setting with one 
                 or more category groups selected: audit, please use version higher than: 2021-05-01-preview, Code: BadRequest, 
                 Status code:BadRequest, Reason phrase: Bad Request
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at 
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T 
                 c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, 
                 Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(String 
                 resourceUri, DiagnosticSettingsResource parameters, String name, Dictionary`2 customHeaders, CancellationToken 
                 cancellationToken)
                    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperationsExtensions.CreateOrUpdateAsync(IDiagnosticSet
                 tingsOperations operations, String resourceUri, DiagnosticSettingsResource parameters, String name, 
                 CancellationToken cancellationToken)
Exception      : Microsoft.Azure.Management.Monitor.Models.ErrorResponseException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7


   HistoryId: 5

Message        : Exception type: ErrorResponseException, Message: Invalid API version used to modify diagnostic setting with one 
                 or more category groups selected: audit, please use version higher than: 2021-05-01-preview, Code: BadRequest, 
                 Status code:BadRequest, Reason phrase: Bad Request
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at 
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T 
                 c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, 
                 Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperations.CreateOrUpdateWithHttpMessagesAsync(String 
                 resourceUri, DiagnosticSettingsResource parameters, String name, Dictionary`2 customHeaders, CancellationToken 
                 cancellationToken)
                    at Microsoft.Azure.Management.Monitor.DiagnosticSettingsOperationsExtensions.CreateOrUpdateAsync(IDiagnosticSet
                 tingsOperations operations, String resourceUri, DiagnosticSettingsResource parameters, String name, 
                 CancellationToken cancellationToken)
Exception      : Microsoft.Azure.Management.Monitor.Models.ErrorResponseException
InvocationInfo : {Set-AzDiagnosticSetting}
Line           : Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspaceId -Name "audit" -Enabled $True
Position       : At line:1 char:1
                 + Set-AzDiagnosticSetting -ResourceId $resourceId -WorkspaceId $workspa …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 9:09:35 AM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.9.0; CommandName: Resolve-AzError; PSVersion: 7.2.5; IsSuccess: True; Duration: 00:00:00.0125976
DEBUG: Finish sending metric.
DEBUG: 9:09:35 AM - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. We are working on new version of Diagnostic settings.

**Comment by VeryEarly** [comment]
will be released on 2022-10-12

**Comment by msjammu** [comment]
I am hitting this issue. From above comments, it seems the issue has been fixed. How do I leverage the fix?
