### ISSUE TITLE
Update-AzADApplication : Cannot bind argument to parameter 'Id' because it is an empty string.

### ISSUE THREAD

**Issue by psdgal** [Azure/azure-powershell#19069]
### Description

Hi,

while updating this service principal I get the following error.

### Issue script & Debug output

```PowerShell
Connect-AzAccount

$appId = "00000015-0000-0000-c000-000000000000"
$sp = Get-AzADServicePrincipal -ApplicationId $appId
$sp | Set-AzADServicePrincipal -ReplyUrl $sp.ReplyUrl

Update-AzADApplication : Cannot bind argument to parameter 'Id' because it is an empty string.
At C:\Program
Files\WindowsPowerShell\Modules\Az.Resources\6.0.1\MSGraph.Autorest\custom\Update-AzADServicePrincipal.ps1:617 char:5
+     Update-AzADApplication @param
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-AzADApplication], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Update-AzADApplication
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.9.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     6.0.1      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...
```

### Error output

```PowerShell
HistoryId: 5


Message        : Cannot bind argument to parameter 'Id' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar,
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Update-AzADApplication}
Line           :     Az.MSGraph.internal\Update-AzADApplication @PSBoundParameters

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\6.0.1\MSGraph.Autorest\custom\Update-AzADAp
                 plication.ps1:545 char:48
                 +     Az.MSGraph.internal\Update-AzADApplication @PSBoundParameters
                 +                                                ~~~~~~~~~~~~~~~~~~
HistoryId      : 5


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
@psdgal , I tried the same script with the same version but cannot reproduce it. Could you check the value of id in the output of `$sp | fl`? BTW, your app id is very special. Is it mock one?

**Comment by psdgal** [comment]
@dingmeng-xue, the Id is present and it's a GUID. I confirm that the app is "special" and I am not mocking it. We need to add new reply url sometime.

By the way... The same script works with AzureAD module (which is being deprecated):

```
$appId = "00000015-0000-0000-c000-000000000000"
$sp = Get-AzureADServicePrincipal -Filter "AppId eq '$($appId)'"
Set-AzureADServicePrincipal -ObjectId $sp.ObjectId -ReplyUrls $sp.ReplyUrls
```

**Comment by dingmeng-xue** [comment]
I found the root cause. Application of "00000015-0000-0000-c000-000000000000" is inaccessible to user. Current `Set-AzADServicePrincipal -InputObject` internally updates app and sp both. The logic is blocked by failure of application update.  

If we want to keep consistent with previous implementation, cmdlet needs to check existing of app at the first.
https://github.com/Azure/azure-powershell/blob/c230bcf4fa8417d28df1617c29142477dbeb052a/src/Resources/MSGraph.Autorest/custom/Update-AzADServicePrincipal.ps1#L617

**Comment by VeryEarly** [comment]
Hi @psdgal 

Can you please try the latest version of Az.Resources instead of version 6.0.1
This error appeared to be fixed in the past.

**Comment by psdgal** [comment]
Hi,

I keep getting the same error with version 6.2.0 of Az.Resources

**Comment by Underdoge** [comment]
Same here

**Comment by VeryEarly** [comment]
> Hi,
> 
> I keep getting the same error with version 6.2.0 of Az.Resources

Hi @psdgal ,

Can you please help provide snapshot for result of  "Get-Module -Name Az.Resources" and steps to reproduce this issue?

Thanks

**Comment by Underdoge** [comment]
@VeryEarly I'm not them but I can reproduce as well:
```
PS C:\Windows\system32> Get-Module -Name Az.Resources

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.2.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...

PS C:\Windows\system32> Update-AzADServicePrincipal -ObjectId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -DisplayName "Testing"
Update-AzADApplication : Cannot bind argument to parameter 'Id' because it is an empty string.
At C:\Program
Files\WindowsPowerShell\Modules\Az.Resources\6.2.0\MSGraph.Autorest\custom\Update-AzADServicePrincipal.ps1:617 char:5
+     Update-AzADApplication @param
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Update-AzADApplication], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Update-AzADApplication

PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                                                                     
----                           -----                                                                                                                                                                     
PSVersion                      5.1.22000.832                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
BuildVersion                   10.0.22000.832                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                           
WSManStackVersion              3.0                                                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                                                       
SerializationVersion           1.1.0.1
```

**Comment by VeryEarly** [comment]
> @VeryEarly I'm not them but I can reproduce as well:
> 
> ```
> PS C:\Windows\system32> Get-Module -Name Az.Resources
> 
> ModuleType Version    Name                                ExportedCommands
> ---------- -------    ----                                ----------------
> Script     6.2.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...
> 
> PS C:\Windows\system32> Update-AzADServicePrincipal -ObjectId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -DisplayName "Testing"
> Update-AzADApplication : Cannot bind argument to parameter 'Id' because it is an empty string.
> At C:\Program
> Files\WindowsPowerShell\Modules\Az.Resources\6.2.0\MSGraph.Autorest\custom\Update-AzADServicePrincipal.ps1:617 char:5
> +     Update-AzADApplication @param
> +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Update-AzADApplication], ParameterBindingValidationException
>     + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Update-AzADApplication
> 
> PS C:\Windows\system32> $PSVersionTable
> 
> Name                           Value                                                                                                                                                                     
> ----                           -----                                                                                                                                                                     
> PSVersion                      5.1.22000.832                                                                                                                                                             
> PSEdition                      Desktop                                                                                                                                                                   
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                   
> BuildVersion                   10.0.22000.832                                                                                                                                                            
> CLRVersion                     4.0.30319.42000                                                                                                                                                           
> WSManStackVersion              3.0                                                                                                                                                                       
> PSRemotingProtocolVersion      2.3                                                                                                                                                                       
> SerializationVersion           1.1.0.1
> ```

Hi @Underdoge 
Thanks I'll take a look

**Comment by VeryEarly** [comment]
Hi @Underdoge
I'm not able to reproduce this issue in my environment, do you have any suggested steps I need to take?
```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.169
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.169
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Install-Module -Name Az.Resources -RequiredVersion 6.2.0 -Repository PSGallery
Get-InstalledModule -Name Az.Resources

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
6.2.0                Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resou…

Import-Module Az.Resources -RequiredVersion 6.2.0
Get-Module -Name Az.Resources
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     6.2.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…

Update-AzADServicePrincipal -ObjectId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -DisplayName "2022-09-27-test-sp1"
```

**Comment by VeryEarly** [comment]
···
Install-Module -Name Az.Resources -RequiredVersion 6.5.0 -Repository PSGallery
Get-InstalledModule -Name Az.Resources

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
6.5.0                Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resou…

Import-Module Az.Resources -RequiredVersion 6.5.0
Get-Module -Name Az.Resources
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     6.5.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…

Update-AzADServicePrincipal -ObjectId "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -DisplayName "2022-09-27-test-sp1"
···
Hi @biste5 
I'm not able to reproduce this issue in my environment, can you please provide steps how you can see this error.

**Comment by biste5** [comment]
Hi @VeryEarly ,

here's a simple script with which I can reproduce consistently the error.
The Application is a multi-tenant app, so you should be able to use it if you're willing

```powershell
[guid]$ClientId = "0c8a2367-b25a-4263-a03f-425b59a5d4e6"

Write-Host "Creating Service Principal"
$sp = New-AzADServicePrincipal -ApplicationId $ClientId

Write-Host "Waiting 30 seconds..."
Start-Sleep -Seconds 30

Write-Host "Updating Service Principal"

try {
    Write-Host "SPN Id: $($sp.Id)"

    Update-AzADServicePrincipal -ObjectId $sp.Id -Tag { HideApp }
}
catch {
    Write-Error $_
}

Write-Host "Removing Service Principal"
Remove-AzADServicePrincipal -ApplicationId $ClientId
```
![image](https://user-images.githubusercontent.com/8156032/208407499-034ce038-2a24-4496-9a1b-63df155e1fed.png)

**Comment by biste5** [comment]
Any clue? Were you able to reproduce? @VeryEarly

**Comment by biste5** [comment]
Still looking for this to be resolved, or a feedback from Microsoft if they can reproduce the error

**Comment by jotheman0303** [comment]
Had this same issue, but wanted to note: You (apparently) cannot set a comment (which I tested for/with) or make changes to just any app. For example the "Azure Iot Hub Publisher App" app, offered by Microsoft, I cannot add a note to. I can for others though. So might not be (fully) command/Powershell related, but also related to this.

**Comment by biste5** [comment]
we're having issues with custom application registrations; not with Microsoft published ones (we haven't tried those)

**Comment by Pikhulya** [comment]
Seeing the same issue 9 months ago since this issue was first reported.  

The code which results in the error at the very last line:

``` PowerShell
$tenantId = "ReplaceWithMyTenantId"
$objectId = "ReplaceWithMySPsObjectId"
Connect-AzAccount -Tenant $tenantId
$sp = Get-AzADServicePrincipal -ObjectId $objectId
$replyUrls = $sp.ReplyUrl
Update-AzADServicePrincipal -ObjectId $objectId -ReplyUrl $replyUrls
```

The error:
`Update-AzADApplication: C:\Users\Admin\Documents\PowerShell\Modules\Az.Resources\6.6.0\MSGraph.Autorest\custom\Update-AzADServicePrincipal.ps1:617:5
Line |
 617 |      Update-AzADApplication @param
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Id' because it is an empty string.`


Software versions used:

- PowerShell 7.3.4
- Az.Resources 6.6.0
- Windows 10 Pro 21H2

**Comment by accentsoftware-simonl** [comment]
I just had a similar issue calling Update-AzADApplication. And the reason was the context was on the wrong subscription / tenant.

**Comment by HenrikVestli** [comment]
I think this issue happens when you try to use Update-AzADApplication on applications created by another AppOwnerOrganizationId than your current Az session.
