### ISSUE TITLE
Get-AzConsumptionUsageDetail uses an old API version (2018-01-31) and does not return all data

### ISSUE THREAD

**Issue by mrblackistone** [Azure/azure-powershell#19195]
### Description

Get-AzConsumptionUsageDetail uses an old API version (2018-01-31), and does not return all data.  Specifically billing charges with a Part Number of "-2" are excluded from the results.  However, when I construct a custom REST API call using a newer API version of "2021-10-01" works fine and returns all data.

This does not retrieve all data:
HTTP Method:  GET
Absolute Uri:  https://management.usgovcloudapi.net/subscriptions/redacted/providers/Microsoft.Consumption/usageDetails?$expand=properties%2FmeterDetails&$filter=properties%2FusageStart ge %272022-07-12%27 and properties%2FusageEnd le %272022-07-12%27&api-version=2018-01-31

This does retrieve all data (as far as I can tell):
HTTP Method:  GET
Absolute Uri:  https://management.usgovcloudapi.net/subscriptions/redacted/providers/Microsoft.Consumption/usageDetails?$expand=properties%2FmeterDetails&$filter=properties%2FusageStart ge %272022-07-12%27 and properties%2FusageEnd le %272022-07-12%27&api-version=2021-10-01

### Issue script & Debug output

```PowerShell
PS> $DebugPreference='Continue'
PS> Get-AzConsumptionUsageDetail -StartDate "2022-07-12" -EndDate "2022-07-12" -MaxCount 1 -IncludeMeterDetails -Debug

DEBUG: 10:23:21 AM - GetAzureRmConsumptionUsageDetail begin processing with ParameterSet 'Subscription'.
DEBUG: 10:23:21 AM - using account id 'redacted@redacted'...
DEBUG: 10:23:21 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'redacted@redacted', environment: 'AzureUSGovernment', tenant: 'redacted'
DEBUG: 10:23:21 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'redacted', Scopes:'https://management.core.usgovcloudapi.net//.default', AuthorityHost:'https://login.microsoftonline.us/', UserId:'redacted@redacted'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.usgovcloudapi.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - 6c2b554d-ffee-4d9f-b43a-506371191936] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - 6c2b554d-ffee-4d9f-b43a-506371191936] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - 6c2b554d-ffee-4d9f-b43a-506371191936] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - 6c2b554d-ffee-4d9f-b43a-506371191936] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - 6c2b554d-ffee-4d9f-b43a-506371191936] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - 6c2b554d-ffee-4d9f-b43a-506371191936] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62] Found 2 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62] Returning 2 accounts     
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - ba285d88-e080-4685-9e09-41e53b167b2f] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(ba285d88-e080-4685-9e09-41e53b167b2f)        
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - ba285d88-e080-4685-9e09-41e53b167b2f] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - ba285d88-e080-4685-9e09-41e53b167b2f] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - ba285d88-e080-4685-9e09-41e53b167b2f] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - ba285d88-e080-4685-9e09-41e53b167b2f] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - ba285d88-e080-4685-9e09-41e53b167b2f] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.usgovcloudapi.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - ba285d88-e080-4685-9e09-41e53b167b2f
UserAssertion set: False
LongRunningOboCacheKey set: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.62 - ba285d88-e080-4685-9e09-41e53b167b2f] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.usgovcloudapi.net//.default
        Authority Host: login.microsoftonline.us
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.63 - ba285d88-e080-4685-9e09-41e53b167b2f] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.63 - ba285d88-e080-4685-9e09-41e53b167b2f] Access token is not expired. Returning the found cache entry. [Current time (08/10/2022 14:23:21) - Expiration Time (08/10/2022 15:23:10 +00:00) - Extended Expiration Time (08/10/2022 15:23:10 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.63 - ba285d88-e080-4685-9e09-41e53b167b2f] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.63 - ba285d88-e080-4685-9e09-41e53b167b2f] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.63 - ba285d88-e080-4685-9e09-41e53b167b2f] Fetched access token from host login.microsoftonline.us. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.63 - ba285d88-e080-4685-9e09-41e53b167b2f] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.22000 [08/10 14:23:21.63 - ba285d88-e080-4685-9e09-41e53b167b2f]  AT expiration time: 8/10/2022 3:23:10 PM +00:00, scopes https://management.core.usgovcloudapi.net//user_impersonation https://management.core.usgovcloudapi.net//.default source Cache from login.microsoftonline.us appHashCode 31158600  
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.usgovcloudapi.net//.default ] ParentRequestId:  ExpiresOn: 2022-08-10T15:23:10.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'redacted', UserId: 'redacted@redacted'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.usgovcloudapi.net/subscriptions/redacted/providers/Microsoft.Consumption/usageDetails?$expand=properties%2FmeterDetails&$filter=properties%2FusageStart ge %272022-07-12%27 and properties%2FusageEnd le %272022-07-12%27&$top=1&api-version=2018-01-31

Headers:
x-ms-client-request-id        : 2e9a6a0b-faa7-4647-af63-6375f7c2eae3
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : private
Vary                          : Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 14999
session-id                    : 60788127-0a25-4a61-a74a-09ea0fe4d253
x-ms-request-id               : 09070776-4d1c-442e-9137-a28d1cd7848b
x-ms-correlation-request-id   : d6171969-793b-4d13-b3a0-86c17d848360
x-ms-client-request-id        : 2e9a6a0b-faa7-4647-af63-6375f7c2eae3
x-ms-ratelimit-microsoft.consumption-tenant-retry-after: 60
x-ms-ratelimit-remaining-microsoft.consumption-tenant-requests: 9
OData-Version                 : 4.0
X-Powered-By                  : ASP.NET
x-ms-routing-request-id       : USDODEAST:20220810T142328Z:d6171969-793b-4d13-b3a0-86c17d848360
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Wed, 10 Aug 2022 14:23:28 GMT

Body:
{
  "nextLink": "https://management.usgovcloudapi.net/subscriptions/redacted/providers/Microsoft.Consumption/usageDetails?$expand=properties/meterDetails&$filter=properties/usageStart ge '2022-07-12' and properties/usageEnd le '2022-07-12'&$top=1&api-version=2018-01-31&sessiontoken=1:60866331&$skiptoken=327C317C317C46616C73657C547275657C30&skiptokenver=v1&id=6cc91d48-d507-4155-bc9d-177f021b7b0f",
  "value": [
    {
      "id": "/subscriptions/redacted/providers/Microsoft.Billing/billingPeriods/20220701/providers/Microsoft.Consumption/usageDetails/redacted",
      "name": "redacted",
      "type": "Microsoft.Consumption/usageDetails",
      "tags": {
        "AppName": "",
        "CostCenter": "",
        "Customer": "",
        "Environment": "redacted",
        "Requestor": ""
      },
      "properties": {
        "billingPeriodId": "/subscriptions/redacted/providers/Microsoft.Billing/billingPeriods/20220701",
        "usageStart": "2022-07-12T00:00:00Z",
        "usageEnd": "2022-07-12T23:59:59Z",
        "instanceId": "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Compute/virtualMachines/redacted",
        "instanceName": "redacted",
        "instanceLocation": "usgovvirginia",
        "meterId": "redacted",
        "usageQuantity": 0.002366160973907,
        "pretaxCost": 0.00015488085816734,
        "currency": "USD",
        "isEstimated": false,
        "subscriptionGuid": "redacted",
        "subscriptionName": "redacted",
        "accountName": "redacted",
        "departmentName": "redacted",
        "product": "Bandwidth - Standard Data Transfer Out - US Gov Zone 1",
        "consumedService": "Microsoft.Compute",
        "costCenter": "183200",
        "meterDetails": {
          "meterName": "Standard Data Transfer Out",
          "meterCategory": "Bandwidth",
          "unit": "10 GB",
          "meterLocation": "usgovvirginia",
          "meterSubCategory": ""
        }
      }
    }
  ]
}



DEBUG: 10:23:29 AM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent: Module: Az.Billing:2.0.0; CommandName: Get-AzConsumptionUsageDetail; PSVersion: 7.2.5; IsSuccess: True; Duration: 00:00:07.5018683
DEBUG: Finish sending metric.
DEBUG: 10:23:29 AM - GetAzureRmConsumptionUsageDetail end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.8.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, C… 
Script     2.0.0                 Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBil…
```

### Error output

```PowerShell
HistoryId: -1

Message        : You cannot call a method on a null-valued expression.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext,  
                 Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)  
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)  
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke
                 clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine,
                 ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe      
                 outputPipe, InvocationInfo invocationInfo, Object[] args)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior  
                 errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe,
                 InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2  
                 functionsToDefine, Object[] args)
                    at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope,
                 ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[]  
                 args)
                    at Microsoft.PowerShell.Commands.PSPropertyExpression.GetValue(PSObject target, Boolean eatExceptions)   
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           : if ($_.MeterDetails -ne $null) {$_.BillableQuantity.ToString() + " " + $_.MeterDetails.Unit} else
                 {$_.BillableQuantity}
Position       : At line:1 char:33
                 + … -ne $null) {$_.BillableQuantity.ToString() + " " + $_.MeterDetails.Un …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : You cannot call a method on a null-valued expression.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext,  
                 Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)  
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)  
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke
                 clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine,
                 ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe      
                 outputPipe, InvocationInfo invocationInfo, Object[] args)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior  
                 errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe,
                 InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2  
                 functionsToDefine, Object[] args)
                    at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope,
                 ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[]  
                 args)
                    at Microsoft.PowerShell.Commands.PSPropertyExpression.GetValue(PSObject target, Boolean eatExceptions)   
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           : if ($_.MeterDetails -ne $null) {$_.BillableQuantity.ToString() + " " + $_.MeterDetails.Unit} else
                 {$_.BillableQuantity}
Position       : At line:1 char:33
                 + … -ne $null) {$_.BillableQuantity.ToString() + " " + $_.MeterDetails.Un …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by navba-MSFT** [comment]
@mrblackistone Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mrblackistone It seems like this service is in our pipeline. We will work with service to upgrade API version.

In the meantime, I am sending the below powershell sample script to workaround this issue.

```
$auth=Get-AzAccessToken
$authHeader= $auth.token
$subscriptionId='XXXXX-XXXX-XXX-XXXXX'
$uri= "https://management.azure.com/subscriptions/" + $subscriptionId + "/providers/Microsoft.Consumption/usageDetails?api-version=2021-10-01&`$expand=properties%2FmeterDetails&`$filter=properties%2FusageStart ge %272022-07-12%27 and properties%2FusageEnd le %272022-07-12%20"
$output=Invoke-WebRequest -Uri $uri -Method GET -Headers @{"Authorization"="Bearer $authHeader"}
$output
```

Hope this helps.

**Comment by navba-MSFT** [comment]
@mrblackistone I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@mrblackistone The action is currently pending on you to try the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by mrblackistone** [comment]
No updates from my end. Thank you

Sent from Surface Duo
________________________________
