### ISSUE TITLE
Remove-AzTag cannot delete

### ISSUE THREAD

**Issue by shannonlowder** [Azure/azure-powershell#19194]
### Description

When trying to remove an unused tag or tag value, I get an error saying the tag and value cannot be deleted. It is associated to one or more resources.  I can run Get-AzResource and confirm the tag and tag value are not in use.

![Screen Shot 2022-08-10 at 8 21 51 AM](https://user-images.githubusercontent.com/2295514/183899874-8e8cbf13-1ea7-4975-9031-c8ad27937abc.png)

### Issue script & Debug output

```PowerShell
DEBUG: 8:24:22 AM - RemoveAzureTagCommand begin processing with ParameterSet 'RemovePredefinedTagParameterSet'.
DEBUG: 8:24:22 AM - using account id 'slowder@toyboxcreations.net'...
DEBUG: 8:24:22 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'slowder@toyboxcreations.net', environment: 'AzureCloud', tenant: '30ed3f6b-8790-43f5-b14e-baee211d7fd1'
DEBUG: 8:24:22 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'30ed3f6b-8790-43f5-b14e-baee211d7fd1', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'slowder@toyboxcreations.net'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - c7b8f922-631f-4663-8740-c003df1f6dab] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - c7b8f922-631f-4663-8740-c003df1f6dab] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - c7b8f922-631f-4663-8740-c003df1f6dab] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - c7b8f922-631f-4663-8740-c003df1f6dab] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - c7b8f922-631f-4663-8740-c003df1f6dab] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - c7b8f922-631f-4663-8740-c003df1f6dab] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60] Found 2 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60] Returning 2 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(7c0d2b9c-f076-4794-a79c-1a09e786626e)
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 7c0d2b9c-f076-4794-a79c-1a09e786626e
UserAssertion set: False
LongRunningOboCacheKey set: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.60 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.61 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.61 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] Access token is not expired. Returning the found cache entry. [Current time (08/10/2022 12:24:22) - Expiration Time (08/10/2022 12:42:22 +00:00) - Extended Expiration Time (08/10/2022 12:42:22 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.61 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.61 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.61 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] Fetched access token from host login.microsoftonline.com. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.61 - 7c0d2b9c-f076-4794-a79c-1a09e786626e] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.5 Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101 [08/10 12:24:22.61 - 7c0d2b9c-f076-4794-a79c-1a09e786626e]  AT expiration time: 8/10/2022 12:42:22 PM +00:00, scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default source Cache from login.microsoftonline.com appHashCode 17462678
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-08-10T12:42:22.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '30ed3f6b-8790-43f5-b14e-baee211d7fd1', UserId: 'slowder@toyboxcreations.net'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
DELETE

Absolute Uri:
https://management.azure.com/subscriptions/8c3db9a5-b321-44b0-b605-39c287d75dfb/tagNames/ClusterId/tagValues/%5B0525-171853-pc1ld43c%5D?api-version=2021-04-01

Headers:
x-ms-client-request-id        : 9f73ec6a-0752-49c5-8e35-6aca039eb247
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-ratelimit-remaining-subscription-deletes: 14999
x-ms-request-id               : 682b3b67-df63-4aa4-b75e-7592e05a8570
x-ms-correlation-request-id   : 682b3b67-df63-4aa4-b75e-7592e05a8570
x-ms-routing-request-id       : CENTRALUS:20220810T122423Z:682b3b67-df63-4aa4-b75e-7592e05a8570
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Wed, 10 Aug 2022 12:24:23 GMT

Body:
{
  "error": {
    "code": "PredefinedTagNameNotFound",
    "message": "Predefined tag name 'ClusterId' could not be found."
  }
}


DEBUG: 8:24:23 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Remove-AzTag: Predefined tag name 'ClusterId' could not be found.
DEBUG: 8:24:23 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Resources:6.1.0; CommandName: Remove-AzTag; PSVersion: 7.2.4; IsSuccess: False; Duration: 00:00:01.1037398; Exception: Predefined tag name 'ClusterId' could not be found.;
DEBUG: Finish sending metric.
DEBUG: 8:24:25 AM - RemoveAzureTagCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.9.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.1.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
DEBUG: 8:27:11 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 8:27:11 AM - using account id 'slowder@toyboxcreations.net'...
DEBUG: 8:27:11 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 316

RequestId      : 5cd97cd5-e619-405f-84b0-9554b25f7ca8
Message        : Predefined tag name 'ClusterId' could not be found.
ServerMessage  : PredefinedTagNameNotFound: Predefined tag name 'ClusterId' could not be found. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {NotFound}
RequestMessage : {DELETE https://management.azure.com/subscriptions/8c3db9a5-b321-44b0-b605-39c287d75dfb/tagNames/ClusterId/tagValues/%5B0525-171853-pc1ld43c%5D?api-version=2021-04-01}
InvocationInfo : {Remove-AzTag}
Line           : remove-Aztag -name "ClusterId" -value ["0525-171853-pc1ld43c"]
Position       : At line:1 char:1
                 + remove-Aztag -name "ClusterId" -value ["0525-171853-pc1ld43c"]
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.ResourceManager.TagsOperations.DeleteValueWithHttpMessagesAsync(String tagName, String tagValue, Dictionary`2 customHeaders, CancellationToken 
                 cancellationToken)
                    at Microsoft.Azure.Management.ResourceManager.TagsOperationsExtensions.DeleteValueAsync(ITagsOperations operations, String tagName, String tagValue, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ResourceManager.TagsOperationsExtensions.DeleteValue(ITagsOperations operations, String tagName, String tagValue)
                    at Microsoft.Azure.Commands.Tags.Client.TagsClient.<>c__DisplayClass22_0.<DeleteTag>b__1(String v)
                    at System.Collections.Generic.List`1.ForEach(Action`1 action)
                    at Microsoft.Azure.Commands.Tags.Client.TagsClient.DeleteTag(String tag, List`1 values)
                    at Microsoft.Azure.Commands.Tags.Tag.RemoveAzureTagCommand.<>c__DisplayClass18_0.<ExecuteCmdlet>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
                    at Microsoft.Azure.Commands.Tags.Tag.RemoveAzureTagCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 316


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 8:27:11 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.9.1; CommandName: Resolve-AzError; PSVersion: 7.2.4; IsSuccess: True; Duration: 00:00:00.0030341
DEBUG: Finish sending metric.
DEBUG: 8:27:12 AM - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
@shannonlowder , according to message returned from service, `ClusterId` is not predefined id or you cannot access it. Could you double check?

**Comment by SaurabhSharma-MSFT** [comment]
@shannonlowder I am seeing the same behavior and looking into it. I will update you as soon as I have more information.

**Comment by navba-MSFT** [comment]
@shannonlowder Apologies for the late reply. I tried the same above steps but unable to reproduce the issue at my end. Below are the steps that I followed:

1. Firstly, I tried to create a new tag. 
2. Confirmed that the tag is not associated with any resource. 
3. Removed the tag successfully.
4. Then checked if the tag still exists. See the below screenshot.

![image](https://user-images.githubusercontent.com/57353862/209050556-b2956f4b-9ad6-4528-acd7-e433f6d9f237.png)

I am using the most recent version of `Az.Resources` in my environment (see below). Could you please [update your `Az.Resources` module](https://www.powershellgallery.com/packages/Az.Resources/6.5.1) and check if you see the same issue ? Awaiting your reply.

```
PS C:\WINDOWS\system32> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.4     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     6.5.1      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...

```
