### ISSUE TITLE
Get-AzStorageTable not using AD credentials

### ISSUE THREAD

**Issue by Devvox93** [Azure/azure-powershell#19208]
### Description

Run the following command:
```powershell
Get-AzStorageTable -Name $tableName -Context $storageAccount.Context
```

Expected result:
A table object is returned (either printed to console or put in a variable).

Actual result:
Error in console:
`Get-AzStorageTable: Key based authentication is not permitted on this storage account.`

### Issue script & Debug output

```PowerShell
Get-AzStorageTable -Name $tableName -Context $storageAccount.Context

DEBUG: 17:27:31 - Init Operation Context for 'GetAzureStorageTableCommand' with client request id  Azure-Storage-PowerShell-06d35964-8aeb-4215-bee4-575e09232ad9. If you want to get more details, please add "-Debug" to your command.
DEBUG: 17:27:31 - GetAzureStorageTableCommand begin processing with ParameterSet 'TableName'.
DEBUG: 17:27:31 - Use storage account 'kbustinthubdwe001' from storage context.
DEBUG: 17:27:31 - Start 2th remote call, method: , destination: https://<redacted>.table.core.windows.net/Tables('<redacted>').     
Get-AzStorageTable: Key based authentication is not permitted on this storage account.
DEBUG: 17:27:31 - GetAzureStorageTableCommand end processing, Start 2 remote calls. Finish 2 remote calls. Elapsed time 1504010,65 ms. Client operation id: Azure-Storage-PowerShell-06d35964-8aeb-4215-bee4-575e09232ad9.
DEBUG: AzureQoSEvent: Module: Az.Storage:3.12.0; CommandName: Get-AzStorageTable; PSVersion: 7.2.5; IsSuccess: False; Duration: 00:00:00.1536187; Exception: Key based authentication is not permitted on this storage account.;
DEBUG: Finish sending metric.
DEBUG: 17:27:31 - GetAzureStorageTableCommand end processing.
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Get-Module Az*       

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.9.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}   
Script     4.8.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolic…
```

### Error output

```PowerShell
Resolve-AzError

WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 7

Message        : Key based authentication is not permitted on this storage account.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Storage.Model.Contract.StorageTableManagement.DoesTableExist(CloudTable table,
                 TableRequestOptions requestOptions, OperationContext operationContext)
                    at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.ListTablesByName(String
                 name)+MoveNext()
                    at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.WriteTablesWithStorageContext(IEnumer 
                 able`1 tableList)
                    at Microsoft.WindowsAzure.Commands.Storage.Table.Cmdlet.GetAzureStorageTableCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)    
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1    
                 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Cosmos.Table.StorageException
InvocationInfo : {Get-AzStorageTable}
Line           : $storageTable = Get-AzStorageTable -Name $tableName -Context $storageAccount.Context
Position       : At line:1 char:17
                 + … rageTable = Get-AzStorageTable -Name $tableName -Context $storageAcco …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by navba-MSFT** [comment]
@Devvox93 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by blueww** [comment]
@Devvox93 

Oauth (AD credential) is already supported on `Get-AzStorageTable` in the lastest Az.Storage.

But `$storageAccount.Context` is a shared key based credencial. 
And it looks you have disable key access on the storage account (If you can send me the account name, I can help to confirm).

To resolved, please create a storage context with AD credential and run `Get-AzStorageTable`

```
Connect-AzAccount
$ctx = New-AzStorageContext -StorageAccountName $storageAccountName
Get-AzStorageTable -Name $tableName -Context $ctx
```

BTW, AzTable module still not support Oauth, you can find more details in https://github.com/Azure/azure-powershell/issues/16861

**Comment by navba-MSFT** [comment]
@Devvox93 This is a quick follow-up to check if you had a chance to look at the above comment. Please let us know if you  had a chance to follow the above suggestion. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Devvox93 Hope you have got a chance to test with the [above ](https://github.com/Azure/azure-powershell/issues/19208#issuecomment-1212729469)mentioned sample script. If you have any follow-up questions or still facing the same issue, please feel free to reopen this thread. We would be happy to help.

**Comment by Devvox93** [comment]
Thank you @navba-MSFT. I guess I had a mixup of docs/examples to get and pass the right context.
Apologies for the delayed response, but yes, the provided suggestion will help me :)
