### ISSUE TITLE
New-AzApplicationInsights inside Az.ApplicationInsights module does not expose the WorkspaceResourceId parameter

### ISSUE THREAD

**Issue by watsonb** [Azure/azure-powershell#19262]
### Description

I would like to create ApplicationInsights in the newer fashion by linking it to a log analytics workspace instead of the Classic mode.    According to #16027 (https://github.com/Azure/azure-powershell/issues/16027), this was to appear in version 2.0.0 of Az.ApplicationInsights.

I currently have Az 8.2.0 and Az.ApplicationInsights 2.1.0 installed on both Windows Server 2019 and PowerShell Core on Linux and in both instances, I encounter the following error when attempting to supply the WorkspaceResourceId parameter:

New-AzApplicationInsights: A parameter cannot be found that matches parameter name 'WorkspaceResourceId'.

Looking at version output, `Get-InstalledModule` shows Az.ApplicationInsights 2.1.0 is installed but `Get-Module` shows script version 1.2.0 is installed.

How to update and resolve this?

### Issue script & Debug output

```PowerShell
New-AzApplicationInsights -ResourceGroupName "REDACTED" -Name "REDACTED" -Location "southcentralus" -Kind "web" -RetentionInDays 90 -WorkspaceResourceId "REDACTED"
New-AzApplicationInsights: A parameter cannot be found that matches parameter name 'WorkspaceResourceId'.
```

### Environment data

```PowerShell
On my Linux System

Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Linux 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

On my Windows System

Name                           Value                                                                                                                                                      
----                           -----                                                                                                                                                      
PSVersion                      5.1.14393.5127                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                    
BuildVersion                   10.0.14393.5127                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                        
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.5.2                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     1.2.0                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplic

Get-InstalledModule Az.ApplicationInsights

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.1.0                Az.ApplicationInsights              PSGallery            Microsoft Azure PowerShell: ApplicationInsights cmdlets
```

### Error output

```PowerShell
HistoryId: 9

Message        : A parameter cannot be found that matches parameter name 'WorkspaceResourceId'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzApplicationInsights}
Line           : New-AzApplicationInsights -ResourceGroupName "REDACTED" -Name "REDACTED" -Location "southcentralus" -Kind "web" -RetentionInDays 90 -WorkspaceResourceId 
                 "REDACTED"
Position       : At line:1 char:155
                 + … ntralus" -Kind "web" -RetentionInDays 90 -WorkspaceResourceId "e79f81 …
                 +                                            ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9
```

**Comment by watsonb** [comment]
I apologize for opening this.  It seems I've been bitten by having multiple versions installed simultaneously per this article.

https://github.com/Azure/azure-powershell/blob/main/documentation/troubleshoot-module-load.md

I'll close this issue.
