### ISSUE TITLE
Update-AzSynapseSparkPool now requires min/max executors on -PackageAction Add

### ISSUE THREAD

**Issue by frizzleqq** [Azure/azure-powershell#19403]
### Description

As shown in [example-9](https://docs.microsoft.com/en-us/powershell/module/az.synapse/update-azsynapsesparkpool?view=azps-8.2.0#example-9) of Update-AzSynapseSparkPool we used to be able to upload a package to a SparkPool without having to specify Min/Max executors of a SparkPool.

This command fails since a recent update and it now requires specifiying (and potentially altering) other SparkPool properties

### Issue script & Debug output

```PowerShell
PS> Update-AzSynapseSparkPool -WorkspaceName $ws.Name -Name spark32 -PackageAction Add -Package $new_package
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 
x-ms-routing-request-id       : 
X-Content-Type-Options        : nosniff
Date                          : Mon, 05 Sep 2022 14:29:45 GMT

Body:
{
  "error": {
    "code": "ValidationFailed",
    "message": "Spark pool request validation failed.",
    "details": [
      {
        "code": "DynamicExecutorAllocationNotValid",
        "message": "Min and max executors properties are mandatory fields when dynamic executor allocation is enabled"
      }
    ]
  }
}

DEBUG: 16:29:46 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Update-AzSynapseSparkPool: Operation returned an invalid status code 'BadRequest' Spark pool request validation failed. Min and max executors properties are mandatory fields when dynamic executor allocation is enabled
DEBUG: 16:29:46 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Synapse:1.5.0; CommandName: Update-AzSynapseSparkPool; PSVersion: 7.2.6; IsSuccess: False; Duration: 00:00:01.2148633; Exception: Operation returned an invalid status code 'BadRequest' Spark pool request validation failed. Min and max executors properties are mandatory fields when dynamic executor allocation is enabled;
DEBUG: Finish sending metric.
DEBUG: 16:29:46 - UpdateAzureSynapseSparkPool end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     1.5.0                 Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTriggerSubscription, Clear-AzSynapseSqlPoolVulnerabilityAssessmentRuleBaseline, Convert-AzSynapseSqlPoolVulnerabilityAssessmentScan…}
```

### Error output

```PowerShell
Message        : Operation returned an invalid status code 'BadRequest' Spark pool request validation failed. Min and max executors properties are mandatory fields when dynamic executor allocation is enabled
StackTrace     :    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsManagementClient.CreateOrUpdateSparkPool(String resourceGroupName, String workspaceName, String sparkPoolName, BigDataPoolResourceInfo createOrUpdateParams, Nullable`1 Force)
                    at Microsoft.Azure.Commands.Synapse.UpdateAzureSynapseSparkPool.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.Common.Exceptions.AzPSException
InvocationInfo : {Update-AzSynapseSparkPool}
Line           : Update-AzSynapseSparkPool -WorkspaceName $ws.Name -Name spark32 -PackageAction Add -Package $new_package
Position       : At line:1 char:1
                 + Update-AzSynapseSparkPool -WorkspaceName $ws.Name -Name spark32 -Pack …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 13
```

**Comment by RakeshMohanMSFT** [comment]
@frizzleqq Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@frizzleqq Yes, it is expected.  its documented [here ](https://learn.microsoft.com/en-us/powershell/module/az.synapse/update-azsynapsesparkpool?view=azps-9.0.1) **This command enables dynamic executor allocation and specify min executor count and max executor count for an Apache Spark pool in Azure Synapse Analytics.**

**Comment by frizzleqq** [comment]
@RakeshMohanMSFT The numbering of the examples has unfortunately changed with this commit: https://github.com/Azure/azure-powershell/commit/80a34f264ef9054019b3e4af6a78588d8b6d50d5

So my link to the example is outdated.

It changed from 9 to 11. But from the issue description it should be clear that the Commando in question is:
```
$packages = Get-AzSynapseWorkspacePackage -WorkspaceName ContosoWorkspace Update-AzSynapseSparkPool -WorkspaceName ContosoWorkspace -Name ContosoSparkPool -PackageAction Add -Package $packages
```

**Comment by RakeshMohanMSFT** [comment]
@frizzleqq Apologies for the delay, let me look into it.

**Comment by RakeshMohanMSFT** [comment]
@frizzleqq I am still unable to reproduce the issue, please look at the below image. One difference is the synapse module version. Can you please upgrade it and retry?
![image](https://user-images.githubusercontent.com/49954584/201972751-16dae4ba-4714-4d5d-85a4-95dad3c275f9.png)

![image](https://user-images.githubusercontent.com/49954584/201973060-3d11418d-2b26-4b7f-8c82-1e86cead8646.png)

**Comment by frizzleqq** [comment]
@RakeshMohanMSFT I can confirm that after updating modules the issue has been resolved.
