### ISSUE TITLE
Add-AzKeyVaultKey throws "The requested operation is not supported" exception with "Microsoft Software Key Storage Provider" certificate

### ISSUE THREAD

**Issue by lee27350** [Azure/azure-powershell#19623]
### Description

I am trying to import a key from a password-protected PFX into Azure Key Vault using Add-AzKeyVaultKey.

I don't think there's anything wrong with the PFX, because it can be successfully uploaded through Azure Portal. Likewise, I know the PFX password I'm providing is correct, because it complains with a different error if I deliberately provide an incorrect password. Similarly, I know all other parameters are correct, because deliberately incorrect values produce different (and expected) error messages.

The certificate is being created and exported to the PFX as follows:

New-SelfSignedCertificate -Provider "Microsoft Software Key Storage Provider" -Subject "CN=$BitLockerKekName" -KeyExportPolicy Exportable -KeyAlgorithm RSA -KeyLength 2048 -CertStoreLocation $CertificateStore -KeyUsage KeyEncipherment -NotAfter (Get-Date).AddYears(50)

Export-PfxCertificate -Cert $Certificate -FilePath $PfxFile -Password $PfxCredentials.Password

The Add-AzKeyVaultKey command is running in the context of a service principal. However, the exact same exception is thrown if run in the context of a user with the "Key Management" access policy template applied - the exact same user account that can successfully import the exact same PFX through Azure Portal.

Add-AzKeyVaultKey throws a "The requested operation is not supported." exception. Instead, I am expecting Add-AzKeyVaultKey to succeed and import the key.

From the digging I've done, the error message implies that the PFX file might not be being opened with X509KeyStorageFlags.Exportable. However, this does not appear to be the case in the Az reference source code that I've found. (But I don't know if I'm looking at the right code.) I am wondering if some of the comments in https://github.com/dotnet/runtime/issues/26031 are relevant (reproduced below), but, as I say, the same certificate is accepted by Azure Portal.

From 26031: _Exportable ends up meaning two different things depending on if the key got loaded into Windows CAPI or Windows CNG. For CAPI it means ... exportable -- ExportParameters will work, and exporting as a PFX will work. For CNG it ends up meaning "exportable if encrypted", so PFX export works, and ExportEncryptedPkcs8PrivateKey works... but ExportParameters and ExportPkcs8PrivateKey do not._

However, the certificate is accepted by Azure Portal, so shouldn't Add-AzKeyVaultKey work as well?

### Issue script & Debug output

```PowerShell
> Add-AzKeyVaultKey -VaultName $KeyVaultName -Name $BitLockerKekNameInAzure -KeyFilePath $PfxFile -KeyFilePassword $PfxCredentials.Password -KeyOps @("wrapKey", "unwrapKey")
DEBUG: 10:52:56 - AddAzureKeyVaultKey begin processing with ParameterSet 'InteractiveImport'.
DEBUG: 10:52:56 - using account id '***REDACTED***'...
DEBUG: 10:52:56 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: '***REDACTED***', environment: 'AzureCloud', tenant: '***REDACTED***'
DEBUG: 10:52:56 - [ServicePrincipalAuthenticator] Calling ClientCertificateCredential.GetTokenAsync - Thumbprint:'***REDACTED***', ApplicationId:'***REDACTED***', TenantId:'***REDACTED***', Scopes:'https://vault.azure.net/.default', AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientCertificateCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.69 - ***REDACTED***] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(***REDACTED***)
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.69 - ***REDACTED***] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.69 - ***REDACTED***]
=== Request Data ===
Authority Provided? - True
Scopes - https://vault.azure.net/.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - ***REDACTED***
UserAssertion set: False
LongRunningOboCacheKey set: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.69 - ***REDACTED***] === Token Acquisition (ClientCredentialRequest) started:
         Scopes: https://vault.azure.net/.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.69 - ***REDACTED***] [Region discovery] Not using a regional authority.
DEBUG: Request [***REDACTED***] POST https://login.microsoftonline.com/***REDACTED***/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:***REDACTED***
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.0,(.NET 6.0.8; Microsoft Windows 10.0.22000)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [***REDACTED***] 200 OK (00.1s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:***REDACTED***
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Mon, 26 Sep 2022 09:52:56 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1313

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] ScopeSet was missing from the token response, so using developer provided scopes in the result.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] Checking client info returned from the server..
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] Saving token response to cache..
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] ID Token not present in response.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] Cannot determine home account id - or id token or no client info and no subject
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] Saving AT in cache and removing overlapping ATs...
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] Looking for scopes for the authority in the cache which intersect with https://vault.azure.net/.default
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] Intersecting scope entries count - 0
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***] Fetched access token from host login.microsoftonline.com.
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***]
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22000 [09/26 09:52:56.77 - ***REDACTED***]  AT expiration time: 26/09/2022 10:52:55 +00:00, scopes https://vault.azure.net/.default source IdentityProvider from login.microsoftonline.com appHashCode ***REDACTED***
DEBUG: ClientCertificateCredential.GetToken succeeded. Scopes: [ https://vault.azure.net/.default ] ParentRequestId:  ExpiresOn: 2022-09-26T10:52:55.7768047+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '***REDACTED***', UserId: '***REDACTED***'
DEBUG: 10:52:56 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Add-AzKeyVaultKey: ***REDACTED***\SetUpKeyVault.ps1:54
Line |
  54 |      Add-AzKeyVaultKey -VaultName $KeyVaultName -Name $BitLockerKekNam …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The requested operation is not supported.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     8.3.0                 Az
Script     2.10.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     1.1.2                 Az.Advisor                          {Disable-AzAdvisorRecommendation, Enable-AzAdvisorRecommendation, Get-AzAdvisorConfiguration, Get-AzAdvisorRecommendation…}
Script     4.3.0                 Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNodePool…}
Script     1.1.4                 Az.AnalysisServices                 {Add-AzAnalysisServicesAccount, Export-AzAnalysisServicesInstanceLog, Get-AzAnalysisServicesServer, New-AzAnalysisServicesFirewal…
Script     3.0.1                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion…}
Script     1.2.0                 Az.AppConfiguration                 {Clear-AzAppConfigurationDeletedStore, Get-AzAppConfigurationDeletedStore, Get-AzAppConfigurationStore, Get-AzAppConfigurationSto…
Script     2.1.0                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplicationInsightsContinuousExport, Get-AzApplicationInsights…
Script     1.0.0                 Az.Attestation                      {Add-AzAttestationPolicySigner, Get-AzAttestation, Get-AzAttestationPolicy, Get-AzAttestationPolicySigners…}
Script     1.7.4                 Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationRunbook, Get-AzAutomationAccoun…
Script     3.2.1                 Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchComputeNodeScheduling, Disable-AzBatchJob, Disable-AzBatchJobSchedule…}
Script     2.0.0                 Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzBillingProfile…}
Script     2.1.0                 Az.Cdn                              {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointContent, Disable-AzCdnCustomDomainCustomHttps, Enable-AzCdnCustomDomainC…
Script     1.1.0                 Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-AzCloudServiceNetworkInterface, Get-AzCloudServiceOSFamily…}
Script     1.11.0                Az.CognitiveServices                {Add-AzCognitiveServicesAccountNetworkRule, Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountCommitmentPlan, Get-AzC…
Script     4.31.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     1.0.0                 Az.ConfidentialLedger               {Get-AzConfidentialLedger, New-AzConfidentialLedger, New-AzConfidentialLedgerAADBasedSecurityPrincipalObject, New-AzConfidentialL…
Script     3.1.0                 Az.ContainerInstance                {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-AzContainerInstanceCachedImage, Get-AzContainerInstanceCapability…}
Script     3.0.0                 Az.ContainerRegistry                {Connect-AzContainerRegistry, Get-AzContainerRegistry, Get-AzContainerRegistryCredential, Get-AzContainerRegistryManifest…}
Script     1.8.2                 Az.CosmosDB                         {Get-AzCosmosDBAccount, Get-AzCosmosDBAccountKey, Get-AzCosmosDBCassandraKeyspace, Get-AzCosmosDBCassandraKeyspaceThroughput…}
Script     1.1.0                 Az.DataBoxEdge                      {Get-AzDataBoxEdgeBandwidthSchedule, Get-AzDataBoxEdgeDevice, Get-AzDataBoxEdgeJob, Get-AzDataBoxEdgeOrder…}
Script     1.2.0                 Az.Databricks                       {Get-AzDatabricksOutboundNetworkDependenciesEndpoint, Get-AzDatabricksVNetPeering, Get-AzDatabricksWorkspace, New-AzDatabricksVNe…
Script     1.16.8                Az.DataFactory                      {Add-AzDataFactoryV2DataFlowDebugSessionPackage, Add-AzDataFactoryV2TriggerSubscription, Get-AzDataFactory, Get-AzDataFactoryActi…
Script     1.0.2                 Az.DataLakeAnalytics                {Add-AzDataLakeAnalyticsDataSource, Add-AzDataLakeAnalyticsFirewallRule, Get-AzDataLakeAnalyticsAccount, Get-AzDataLakeAnalyticsC…
Script     1.3.0                 Az.DataLakeStore                    {Add-AzDataLakeStoreFirewallRule, Add-AzDataLakeStoreItemContent, Add-AzDataLakeStoreTrustedIdProvider, Add-AzDataLakeStoreVirtua…
Script     1.0.1                 Az.DataShare                        {Get-AzDataShare, Get-AzDataShareAccount, Get-AzDataShareDataSet, Get-AzDataShareDataSetMapping…}
Script     1.1.0                 Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, Get-AzDeploymentManagerRollout, Get-AzDeploymentManagerService, Get-AzDeploymentManagerSe…
Script     3.1.1                 Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-AzWvdApplication, Get-AzWvdApplicationGroup…}
Script     1.0.2                 Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy…}
Script     1.1.2                 Az.Dns                              {Add-AzDnsRecordConfig, Get-AzDnsRecordSet, Get-AzDnsZone, New-AzDnsRecordConfig…}
Script     1.4.0                 Az.EventGrid                        {Get-AzEventGridDomain, Get-AzEventGridDomainKey, Get-AzEventGridDomainTopic, Get-AzEventGridFullUrlForSystemTopicEventSubscripti…
Script     2.2.1                 Az.EventHub                         {Add-AzEventHubIPRule, Add-AzEventHubVirtualNetworkRule, Approve-AzEventHubPrivateEndpointConnection, Deny-AzEventHubPrivateEndpo…
Script     1.9.0                 Az.FrontDoor                        {Disable-AzFrontDoorCustomDomainHttps, Enable-AzFrontDoorCustomDomainHttps, Get-AzFrontDoor, Get-AzFrontDoorFrontendEndpoint…}
Script     4.0.4                 Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFunctionAppPlan, Get-AzFunctionAppSetting…}
Script     5.0.1                 Az.HDInsight                        {Add-AzHDInsightClusterIdentity, Add-AzHDInsightComponentVersion, Add-AzHDInsightConfigValue, Add-AzHDInsightMetastore…}
Script     2.0.0                 Az.HealthcareApis                   {Get-AzHealthcareApisService, Get-AzHealthcareApisWorkspace, Get-AzHealthcareDicomService, Get-AzHealthcareFhirDestination…}
Script     2.7.4                 Az.IotHub                           {Add-AzIotHubCertificate, Add-AzIotHubConfiguration, Add-AzIotHubDeployment, Add-AzIotHubDevice…}
Script     4.7.0                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount…}
Script     2.1.0                 Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabasePrincipal, Get-AzKustoAttachedDatabaseConfiguration, Get-AzKustoCluster…}
Script     1.5.0                 Az.LogicApp                         {Get-AzIntegrationAccount, Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConf…
Script     1.1.3                 Az.MachineLearning                  {Add-AzMlWebServiceRegionalProperty, Export-AzMlWebService, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlan…}
Script     1.2.0                 Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfiguration, Get-AzMaintenancePublicConfiguration…}
Script     1.0.0                 Az.ManagedServiceIdentity           {Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity, New-AzUserAssignedIdentity, Remove-AzUserAssignedIdentity…}
Script     3.0.0                 Az.ManagedServices                  {Get-AzManagedServicesAssignment, Get-AzManagedServicesDefinition, Get-AzManagedServicesMarketplaceDefinition, New-AzManagedServi…
Script     1.0.3                 Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.1.1                 Az.Media                            {Get-AzMediaService, Get-AzMediaServiceKey, Get-AzMediaServiceNameAvailability, New-AzMediaService…}
Script     1.1.3                 Az.Migrate                          {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMigrateProject, Get-AzMigrateReplicationEligibilityResult…}
Script     3.1.0                 Az.Monitor                          {Add-AzAutoscaleSetting, Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2…}
Script     1.0.0                 Az.MySql                            {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Get-AzMySqlFirewallRule, Get-AzMySqlFlexibleServer…}
Script     4.20.1                Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHt…
Script     1.1.1                 Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRule, Get-AzNotificationHubListKey, Get-AzNotificationHubPNSCredential…}
Script     3.2.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperationalInsig…
Script     1.5.1                 Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyMetadata, Get-AzPolicyRemediation, Get-AzPolicyState…}
Script     1.1.0                 Az.PostgreSql                       {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnectionString, Get-AzPostgreSqlFirewallRule, Get-AzPostgreSqlFlexibleServer…}
Script     1.2.0                 Az.PowerBIEmbedded                  {Get-AzPowerBIEmbeddedCapacity, Get-AzPowerBIWorkspace, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessK…
Script     1.0.3                 Az.PrivateDns                       {Add-AzPrivateDnsRecordConfig, Get-AzPrivateDnsRecordSet, Get-AzPrivateDnsVirtualNetworkLink, Get-AzPrivateDnsZone…}
Script     5.6.0                 Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Backup-AzRecoveryServicesBackupItem, Copy-AzRecoveryServicesVault, Disabl…
Script     1.6.0                 Az.RedisCache                       {Export-AzRedisCache, Get-AzRedisCache, Get-AzRedisCacheFirewallRule, Get-AzRedisCacheKey…}
Script     1.1.0                 Az.RedisEnterpriseCache             {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCacheDatabase, Get-AzRedisEnterpriseCacheKey…}
Script     1.0.3                 Az.Relay                            {Get-AzRelayAuthorizationRule, Get-AzRelayHybridConnection, Get-AzRelayKey, Get-AzRelayNamespace…}
Script     1.1.0                 Az.ResourceMover                    {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveCollection, Get-AzResourceMoverMoveResource, Get-AzResourceMoverRequired…
Script     6.2.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     1.3.0                 Az.Security                         {Add-AzSecurityAdaptiveNetworkHardening, Add-AzSecuritySqlVulnerabilityAssessmentBaseline, Confirm-AzSecurityAutomation, Disable-…
Script     1.1.0                 Az.SecurityInsights                 {Get-AzSentinelAlertRule, Get-AzSentinelAlertRuleAction, Get-AzSentinelAlertRuleTemplate, Get-AzSentinelBookmark…}
Script     1.11.0                Az.ServiceBus                       {Add-AzServiceBusIPRule, Add-AzServiceBusVirtualNetworkRule, Approve-AzServiceBusPrivateEndpointConnection, Complete-AzServiceBus…
Script     3.1.0                 Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabricManagedClusterClientCertificate, Add-AzServiceFabricManagedNodeTypeVMEx…
Script     1.4.1                 Az.SignalR                          {Get-AzSignalR, Get-AzSignalRKey, Get-AzSignalRUsage, New-AzSignalR…}
Script     3.11.0                Az.Sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElasticJobStep, Add-AzSqlElasticJobTarget, Add-AzSqlInstanceKeyVaultKey…}
Script     1.1.0                 Az.SqlVirtualMachine                {Get-AzAvailabilityGroupListener, Get-AzSqlVM, Get-AzSqlVMGroup, New-AzAvailabilityGroupListener…}
Script     1.3.0                 Az.StackHCI                         {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestation, Disable-AzStackHCIRemoteSupport, Enable-AzStackHCIAttestation…}
Script     4.9.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageF…
Script     1.7.0                 Az.StorageSync                      {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyncGroup, Get-AzStorageSyncServer, Get-AzStorageSyncServerEndpoint…}
Script     2.0.0                 Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsClusterStreamingJob, Get-AzStreamAnalyticsDefaultFunctionDefinition, Get-AzSt…
Script     1.0.0                 Az.Support                          {Get-AzSupportProblemClassification, Get-AzSupportService, Get-AzSupportTicket, Get-AzSupportTicketCommunication…}
Script     1.6.0                 Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTriggerSubscription, Clear-AzSynapseSqlPoolVulnerabilityAssessmentRuleBas…
Script     1.1.0                 Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Add-AzTrafficManagerEndpointConfig, Add-A…
Script     2.11.4                Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRouting, Edit-AzWebAppBackupConfiguration, Enter-AzWebAppContainerPSSessio…
```

### Error output

```PowerShell
Message        : The requested operation is not supported.
StackTrace     :    at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
                    at System.Security.Cryptography.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
                    at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
                    at Microsoft.Azure.Commands.KeyVault.Models.PfxWebKeyConverter.CreateJWK(RSA rsa)
                    at Microsoft.Azure.Commands.KeyVault.Models.PfxWebKeyConverter.Convert(String pfxFileName, SecureString pfxPassword)
                    at Microsoft.Azure.Commands.KeyVault.Models.PfxWebKeyConverter.ConvertKeyFromFile(FileInfo fileInfo, SecureString password, WebKeyConverterExtraInfo extraInfo)
                    at Microsoft.Azure.Commands.KeyVault.AddAzureKeyVaultKey.CreateWebKeyFromFile()
                    at Microsoft.Azure.Commands.KeyVault.AddAzureKeyVaultKey.CreateKeyVaultKey()
                    at Microsoft.Azure.Commands.KeyVault.AddAzureKeyVaultKey.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException
InvocationInfo : {Add-AzKeyVaultKey}
Line           :        Add-AzKeyVaultKey -VaultName $KeyVaultName -Name $BitLockerKekNameInAzure -KeyFilePath $PfxFile -KeyFilePassword $PfxCredentials.Password -KeyOps @("wrapKey", "unwrapKey")
```

**Comment by SaurabhSharma-MSFT** [comment]
@lee27350 We are looking into it and get back to you for any additional information.

**Comment by jlichwa** [comment]
@lee27350 Add-AzKeyVaultKey is for cryptographic keys not certificates. You mentioned you are tried import certificate in Key Vault Portal, correct?

**Comment by lee27350** [comment]
Hi @jlichwa

I am trying to use Add-AzKeyVaultKey to import a key. I am simply using a PFX as a convenient container for the private key. I am not trying to import a certificate. This should be possible according to the documentation. See

https://learn.microsoft.com/en-us/powershell/module/az.keyvault/add-azkeyvaultkey?view=azps-9.0.1#example-6-import-a-software-protected-key

![image](https://user-images.githubusercontent.com/114397039/198237238-ab0dd49c-d239-405b-9f7d-e363f7028085.png)

The same PFX file is accepted by Azure Portal, and imports as a key (not a certificate):

![image](https://user-images.githubusercontent.com/114397039/198240790-558b237e-8fe6-4812-ac65-27fe163d28b4.png)

The Azure Portal can successfully import the key from the exact same PFX, as shown above. Add-AzKeyVaultKey fails with the exact same PFX.

So how does the Azure Portal successfully import the private key from the PFX if Add-AzKeyVaultKey cannot do it **when the key provider is "Microsoft Software Key Storage Provider" (i.e. CNG, not CAPI)**?

**Comment by jlichwa** [comment]
@lee27350  thank you for clarification. You mentioned that you use password and tried exact same through Portal UX and it worked, but there is no password in Import Key UX, only in certificate UX:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/52512203/198358521-a23e209d-9927-42de-811a-d65d7c46ae77.png">

**Comment by dingmeng-xue** [comment]
Azure PowerShell team will evaluate this requirement.

**Comment by lee27350** [comment]
Hi @jlichwa

The Azure Portal does allow keys to be imported from password-protected PFX files.

In the same way that the portal UI changes if you select "Import" rather than "Generate", it also changes when you upload a password-protected PFX file:

![image](https://user-images.githubusercontent.com/114397039/198558671-8056b1cc-d595-48af-a171-d0d464c92409.png)

i.e. If you actually upload a password-protected PFX file, then you will see the "Password" field appear.

Add-AzKeyVaultKey supports a password-protected PFX file as well. The following will work(*) if you use CAPI to generate the key:

`Add-AzKeyVaultKey -VaultName $KeyVaultName -Name $BitLockerKekNameInAzure -KeyFilePath $PfxFile -KeyFilePassword $PfxCredentials.Password -KeyOps @("wrapKey", "unwrapKey") -KeyType RSA -Destination HSM`

(*) Full disclosure: I haven't tested this since 2019, but the problem here appears clear, and I've no reason to suspect that importing a CAPI-generated key will fail in 2022.

It only doesn't work if you use CNG to generate the key. However, my understanding in that CAPI has been deprecated in favour of CNG.

So the situation is as follows: Azure Portal can import both CAPI-generated and CNG-generated keys from a password-protected PFX; `Add-AzKeyVaultKey` can only import CAPI-generated keys from a password-protected PXF - it fails with an unclear error if you use it to try to import a CNG-generated key from a password-protected PFX. (As mentioned, I suspect this is because of how `ExportParameters()` behaves differently under CNG to CAPI.)

@dingmeng-xue, given the previous paragraph, this feels like a bug more than a feature request: at the very least the `Add-AzKeyVaultKey` documentation should state that it only supports deprecated CAPI-generated keys in password-protected PFX files; ideally, `Add-AzKeyVaultKey` needs to support CNG-generated keys in password-protected PFX files. (As I say, Azure Portal can cope, so it's currently possible to do something through Azure Portal that it is not possible to do through Azure PowerShell.)
