### ISSUE TITLE
Get-AzStorageBlob Status Getting Hung Up

### ISSUE THREAD

**Issue by jmpompeo** [Azure/azure-powershell#19688]
### Description

Hello, 

I'm trying to run a script that uses Get-AzStorageBlob to retrieve blobs from an Azure storage account using the storage context & container name. The command keeps getting hung up and not showing any progress. I included the command below and also the message that it gets hung up on. 

![GetAzStorageBlob](https://user-images.githubusercontent.com/75942346/192819534-477b2e36-2f8e-4848-9654-76e998a74611.jpg)

### Issue script & Debug output

```PowerShell
DEBUG: 9:18:46 AM - Init Operation Context for 'GetAzureStorageBlobCommand' with client request id  Azure-Storage-PowerShell-id. If you want to get more details, please add "-Debug" to your command.
DEBUG: 9:18:46 AM - GetAzureStorageBlobCommand begin processing with ParameterSet 'BlobName'.
DEBUG: 9:18:46 AM - Use storage account 'storage account' from storage context.
DEBUG: 9:18:46 AM - Start 339th remote call, method: , destination: destination

Get-AzStorageBlob: The operation was canceled.
DEBUG: 11:59:48 AM - GetAzureStorageBlobCommand end processing, Start 383 remote calls. Finish 383 remote calls. Elapsed time 2649496.28 ms. Client operation id: Azure-Storage-PowerShell-d545bf21-4e08-4869-bb2f-8805303507ac.
DEBUG: AzureQoSEvent: Module: Az.Storage:4.8.0; CommandName: Get-AzStorageBlob; PSVersion: 7.2.6; IsSuccess: False; Duration: 00:42:34.9173121; Exception: The operation was canceled.;
DEBUG: Finish sending metric.
DEBUG: 11:59:48 AM - GetAzureStorageBlobCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.9.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     4.1.1      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle...}
```

### Error output

```PowerShell
Message        : The operation was canceled.
StackTrace     :    at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
                    at Microsoft.Azure.Storage.Blob.CloudBlobContainer.ListBlobsSegmentedAsync(String prefix, Boolean useFlatBlobListing, BlobListingDetails blobListingDetails, Nullable`1 maxResults,
                 BlobContinuationToken currentToken, BlobRequestOptions options, OperationContext operationContext, CancellationToken cancellationToken)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByPrefix(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String prefix,
                 Func`2 blobFilter, Boolean includeDeleted, Boolean includeVersion)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByName(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String blobName,
                 Boolean includeDeleted, Boolean includeVersion)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTask(Int64 taskId, Task task)
Exception      : Microsoft.Azure.Storage.StorageException
InvocationInfo : {Get-AzStorageBlob}
Line           : $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container $ContainerName -Debug
Position       : At line:1 char:10
                 + $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container  …
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18

Message        : The operation was canceled.
StackTrace     :    at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
                    at Microsoft.Azure.Storage.Core.TimeoutStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
                    at Microsoft.Azure.Storage.Core.ByteCountingStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
                    at System.Xml.XmlTextReaderImpl.ReadDataAsync()
                    at System.Xml.XmlTextReaderImpl.ReadDataInNameAsync(Int32 pos)
                    at System.Xml.XmlTextReaderImpl.ParseQNameAsync(Boolean isQName, Int32 startOffset)
                    at System.Xml.XmlTextReaderImpl._ParseElementAsync_ContinueWithSetElement(Task`1 task)
                    at System.Xml.AsyncHelper.ReturnTrueTaskWhenFinishCoreAsync(Task task)
                    at System.Xml.XmlTextReaderImpl.SkipAsync()
                    at Microsoft.Azure.Storage.Blob.Protocol.ListBlobsResponse.ParseBlobEntryAsync(XmlReader reader, Uri baseUri, CancellationToken token)
                    at Microsoft.Azure.Storage.Blob.Protocol.ListBlobsResponse.ParseAsync(Stream stream, CancellationToken token)
                    at Microsoft.Azure.Storage.Blob.CloudBlobContainer.<>c__DisplayClass163_0.<<ListBlobsImpl>b__2>d.MoveNext()
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.Storage.Core.Executor.Executor.ProcessEndOfRequestAsync[T](ExecutionState`1 executionState, CancellationToken cancellationToken)
                    at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
Exception      : System.Threading.Tasks.TaskCanceledException
InvocationInfo : {Get-AzStorageBlob}
Line           : $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container $ContainerName -Debug
Position       : At line:1 char:10
                 + $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container  …
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18

Message        : Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
StackTrace     :    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
                    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
                    at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
                    at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
                    at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
                    at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.ReadAsyncCore(Memory`1 buffer, CancellationToken cancellationToken)
Exception      : System.IO.IOException
InvocationInfo : {Get-AzStorageBlob}
Line           : $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container $ContainerName -Debug
Position       : At line:1 char:10
                 + $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container  …
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18

Message        : The I/O operation has been aborted because of either a thread exit or an application request.
StackTrace     :
Exception      : System.Net.Sockets.SocketException
InvocationInfo : {Get-AzStorageBlob}
Line           : $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container $ContainerName -Debug
Position       : At line:1 char:10
                 + $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container  …
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18


   HistoryId: 12

Message        : The term 'GetAzStorageContainer' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections,
                 ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : $AzContainer = GetAzStorageContainer -Context $SourceStorageContext
Position       : At line:1 char:16
                 + $AzContainer = GetAzStorageContainer -Context $SourceStorageContext
                 +                ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12


   HistoryId: 2

Message        : Cannot validate argument on parameter 'Container'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
                 ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
                    at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Get-AzStorageBlob}
Line           : $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container $ContainerName
Position       : At line:1 char:70
                 + … zStorageBlob -Context $SourceStorageContext -Container $ContainerName
                 +                                                          ~~~~~~~~~~~~~~
HistoryId      : 2

Message        : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
Exception      : System.Management.Automation.ValidationMetadataException
InvocationInfo : {Get-AzStorageBlob}
Line           : $Blobs = Get-AzStorageBlob -Context $SourceStorageContext -Container $ContainerName
Position       : At line:1 char:70
                 + … zStorageBlob -Context $SourceStorageContext -Container $ContainerName
                 +                                                          ~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by navba-MSFT** [comment]
@jmpompeo Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by fhmessas** [comment]
Same happening here, adding a comment to follow the solution

**Comment by navba-MSFT** [comment]
@jmpompeo Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@jmpompeo I was able to run the command successfully in my machine. I also tried with the containers that have many blobs and it worked fine.

```
Get-AzStorageBlob -Container MyContainerName -Context $ctx

   AccountName: MyAccountName, ContainerName: MyContainerName

Name                 BlobType  Length          ContentType                    LastModified         AccessTier SnapshotTime                 IsDeleted 
----                 --------  ------          -----------                    ------------         ---------- ------------                 --------- 
blob.exe             BlockBlob 217160          application/x-msdownload       2022-07-31 08:05:01Z Cool                                    False     
srcblobname          BlockBlob 8192            application/octet-stream       2022-06-23 10:49:46Z Cool                                    False     
test/dstblobname     BlockBlob 8192            application/octet-stream       2022-06-23 10:49:46Z Cool                                    False     
```

Could you please update to the most recent Az.Storage module (4.9.0) and check if that helps ?

https://www.powershellgallery.com/packages/Az.Storage/4.9.0

Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jmpompeo I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@jmpompeo The action is currently pending on you to follow the above action plan. If you still encounter this issue, please feel free to reopen this thread. We would be happy to help.
