### ISSUE TITLE
New-AzSqlServer not working with -ExternalAdminSID option

### ISSUE THREAD

**Issue by amolagar5** [Azure/azure-powershell#19711]
### Description

Create an Azure SQL Server with ExternalAdminSID  option will fail.. 

New-AzSqlServer -EnableActiveDirectoryOnlyAuthentication -ExternalAdminSID "xxd505xx-4834-4919-a961-6a87f3cc8a6e" -ExternalAdminName "user@abc.com"  -ResourceGroupName abcrg-ServerName newserver -Location westeurope 

### Issue script & Debug output

```PowerShell
PS C:\WINDOWS\system32> New-AzSqlServer -EnableActiveDirectoryOnlyAuthentication -ExternalAdminSID "97d505ee-4834-4919-a961-6a87f3cc8a6e" -ExternalAdminName "amagarwa@microsoft.com"  -ResourceGroupName amoltestwe -ServerName amagarwapstestserver -Location westeurope
DEBUG: 12:15:40 PM - NewAzureSqlServer begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 12:15:40 PM - using account id 'amagarwa@microsoft.com'...
DEBUG: 12:15:40 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/e1775f9f-a286-474d-b6f0-29c42ac74554/resourceGroups/amoltestwe/providers/Mic
rosoft.Sql/servers/amagarwapstestserver?api-version=2021-02-01-preview

Headers:
x-ms-client-request-id        : 8df8af0f-761f-4a91-a80a-0fb7c2e0e063
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 1108c51a-e390-4890-9e80-463c412e5a0d
x-ms-correlation-request-id   : 1108c51a-e390-4890-9e80-463c412e5a0d
x-ms-routing-request-id       : WESTUS:20220929T191430Z:1108c51a-e390-4890-9e80-463c412e5a0d
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 29 Sep 2022 19:14:29 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Sql/servers/amagarwapstestserver' under resource group 'amoltestwe' was not
found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}

DEBUG: [Common.Authentication]: Authenticating using Account: 'amagarwa@microsoft.com', environment: 'AzureCloud',
tenant: 'dbef1e29-488c-4b64-90ac-287b977faaa3'
DEBUG: 12:15:41 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync -
TenantId:'dbef1e29-488c-4b64-90ac-287b977faaa3', Scopes:'https://graph.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId:'amagarwa@microsoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://graph.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a15fb1a5-a9c0-4b8a-9578-6f7ff1b4c652] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a15fb1a5-a9c0-4b8a-9578-6f7ff1b4c652] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a15fb1a5-a9c0-4b8a-9578-6f7ff1b4c652] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a15fb1a5-a9c0-4b8a-9578-6f7ff1b4c652] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a15fb1a5-a9c0-4b8a-9578-6f7ff1b4c652] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65] Found 1 cache accounts
and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65] Returning 1 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] MSAL MSAL.Desktop with assembly version '4.39.0.0'.
CorrelationId(a5f45418-86d7-41d7-b3d0-4a91fbf20e0e)
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e]
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - a5f45418-86d7-41d7-b3d0-4a91fbf20e0e
UserAssertion set: False
LongRunningOboCacheKey set: False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.65 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] === Token Acquisition (SilentRequest) started:
  Scopes: https://graph.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.66 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.66 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] Access token is not expired. Returning the found cache entry. [Current time
(09/29/2022 19:15:41) - Expiration Time (09/29/2022 19:41:30 +00:00) - Extended Expiration Time (09/29/2022 19:41:30
+00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.66 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.66 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.66 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e] Fetched access token from host login.microsoftonline.com.
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.66 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e]
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [09/29 19:15:41.66 -
a5f45418-86d7-41d7-b3d0-4a91fbf20e0e]  AT expiration time: 9/29/2022 7:41:30 PM +00:00, scopes
https://graph.windows.net//62e90394-69f5-4237-9190-012177145e10 https://graph.windows.net//.default source Cache from
login.microsoftonline.com appHashCode 18425219
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://graph.windows.net//.default ] ParentRequestId:
 ExpiresOn: 2022-09-29T19:41:30.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'dbef1e29-488c-4b64-90ac-287b977faaa3',
UserId: 'amagarwa@microsoft.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.windows.net/v1.0/groups/97d505ee-4834-4919-a961-6a87f3cc8a6e

Headers:
x-ms-client-request-id        : 8df8af0f-761f-4a91-a80a-0fb7c2e0e063
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
ocp-aad-diagnostics-server-name: qClph0+sGE865KItfMxE5Ys6gHmht1/RUYqNkg+kdRM=
request-id                    : dc46bc4f-235e-4bbf-aec8-21364f85d418
client-request-id             : 8df8af0f-761f-4a91-a80a-0fb7c2e0e063
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Duration                      : 252063
Date                          : Thu, 29 Sep 2022 19:14:30 GMT
X-Powered-By                  : ASP.NET

Body:
{
  "odata.error": {
    "code": "Request_DataContractVersionMissing",
    "message": {
      "lang": "en",
      "value": "The specified api-version is invalid. The value must exactly match a supported version."
    }
  }
}

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.windows.net/v1.0/servicePrincipals?$filter=appId eq '97d505ee-4834-4919-a961-6a87f3cc8a6e'

Headers:
x-ms-client-request-id        : 8df8af0f-761f-4a91-a80a-0fb7c2e0e063
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
ocp-aad-diagnostics-server-name: qClph0+sGE865KItfMxE5Ys6gHmht1/RUYqNkg+kdRM=
request-id                    : 68031606-71ab-402b-8db2-d2c3e99730e7
client-request-id             : 8df8af0f-761f-4a91-a80a-0fb7c2e0e063
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Duration                      : 248653
Date                          : Thu, 29 Sep 2022 19:14:30 GMT
X-Powered-By                  : ASP.NET

Body:
{
  "odata.error": {
    "code": "Request_DataContractVersionMissing",
    "message": {
      "lang": "en",
      "value": "The specified api-version is invalid. The value must exactly match a supported version."
    }
  }
}

DEBUG: 12:15:41 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
New-AzSqlServer : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ New-AzSqlServer -EnableActiveDirectoryOnlyAuthentication -ExternalAdm ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzSqlServer], OdataErrorException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Server.Cmdlet.NewAzureSqlServer

DEBUG: 12:15:41 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Sql:3.11.0; CommandName: New-AzSqlServer; PSVersion: 5.1.22621.169; IsSuccess: False;
Duration: 00:00:01.1059900; Exception: Operation returned an invalid status code 'BadRequest';
DEBUG: Finish sending metric.
DEBUG: 12:15:42 PM - NewAzureSqlServer end processing.
PS C:\WINDOWS\system32>
```

### Environment data

```PowerShell
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.169
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.169
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\WINDOWS\system32> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.1     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     3.11.0     Az.Sql
```

### Error output

```PowerShell
Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Applications.ServicePrincipalsOperations.<Lis
                 tServicePrincipalWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Applications.ServicePrincipalsOperationsExten
                 sions.<ListServicePrincipalAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Common.MSGraph.Version1_0.MicrosoftGraphClientExtensions.FilterServiceP
                 rincipals(IMicrosoftGraphClient client, ODataQuery`1 odataQuery)
                    at Microsoft.Azure.Commands.Sql.Server.Adapter.AzureSqlServerAdapter.GetActiveDirectoryInformation(
                 ServerExternalAdministrator input)
                    at
                 Microsoft.Azure.Commands.Sql.Server.Adapter.AzureSqlServerAdapter.UpsertServer(AzureSqlServerModel
                 model)
                    at Microsoft.Azure.Commands.Sql.Server.Cmdlet.NewAzureSqlServer.PersistChanges(IEnumerable`1
                 entity)
                    at
                 Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String
                 processMessage, String target, Action action)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
                    at Microsoft.Azure.Commands.Sql.Server.Cmdlet.NewAzureSqlServer.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.Common.MSGraph.Version1_0.Applications.Models.OdataErrorException
InvocationInfo : {New-AzSqlServer}
Line           : New-AzSqlServer -EnableActiveDirectoryOnlyAuthentication -ExternalAdminSID
                 "97d505ee-4834-4919-a961-6a87f3cc8a6e" -ExternalAdminName "amagarwa@microsoft.com"
                 -ResourceGroupName amoltestwe -ServerName amagarwapstestserver -Location westeurope
Position       : At line:1 char:1
                 + New-AzSqlServer -EnableActiveDirectoryOnlyAuthentication -ExternalAdm ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8
```

**Comment by amolagar5** [comment]
I have checked in the fix.
