### ISSUE TITLE
[Get-AzPrivateDnsZone] doesn't found existing subscriptions

### ISSUE THREAD

**Issue by clowa** [Azure/azure-powershell#19835]
### Description

The cmdlet `Get-AzPrivateDnsZone` sometimes returns the error `The specified subscription <SUBSCRIPTION_ID> does not exist` on existing subscriptions.

I discovered this behavior when listing all private dns zones in all subscriptions of a tenant using a service principal using the code [below](#test-code). 

### Expected Result
Returning `$null`.

### Test Code
```powershell
PS> Get-AzSubscription | % {
>     $_ | Set-AzContext
>     Get-AzPrivateDnsZone
> }

Name                             Account                              SubscriptionName                                     Environment                                        TenantId
----                             -------                              ----------------                                     -----------                                        --------
DEV MGMT(Converted to EA) (99ef… <ACCOUNT_ID>                         DEV MGMT(Converted to EA)                            AzureCloud                                         <TENANT_ID>
Get-AzPrivateDnsZone:
Line |
   3 |  Get-AzPrivateDnsZone
     |  ~~~~~~~~~~~~~~~~~~~~
     | The specified subscription 99efXXX does not exist
DEV AUTH(Converted to EA) (d1bd… <ACCOUNT_ID>                         DEV AUTH(Converted to EA)                            AzureCloud                                         <TENANT_ID>
DEV Infra Win 10(Converted to E… <ACCOUNT_ID>                         DEV Infra Win 10(Converted to EA)                    AzureCloud                                         <TENANT_ID>
DEV Data Caching In Branches(Co… <ACCOUNT_ID>                         DEV Data Caching In Branches(Converted to EA)        AzureCloud                                         <TENANT_ID>
Get-AzPrivateDnsZone:
Line |
   3 |  Get-AzPrivateDnsZone
     |  ~~~~~~~~~~~~~~~~~~~~
     | The specified subscription f4b5XXX does not exist
DEV BI (42afd9d4-669e-4a8f-a47f… <ACCOUNT_ID>                         DEV BI                                               AzureCloud                                         <TENANT_ID>

Name                                           : privatelink.datafactory.azure.net
ResourceId                                     : /subscriptions/42afXXX/resourceGroups/dashboards/providers/Microsoft.Network/privateDnsZones/privatelink.datafactory.azure.net
ResourceGroupName                              : dashboards
Location                                       :
Etag                                           : 7cefa419-a91e-4d3c-95fe-5d27548f0dd1
Tags                                           : {}
NumberOfRecordSets                             : 1
MaxNumberOfRecordSets                          : 25000
NumberOfVirtualNetworkLinks                    : 0
MaxNumberOfVirtualNetworkLinks                 : 1000
NumberOfVirtualNetworkLinksWithRegistration    : 0
MaxNumberOfVirtualNetworkLinksWithRegistration : 100
```

### Issue script & Debug output

```PowerShell
PS> Get-AzPrivateDnsZone
DEBUG: 09:18:00 - GetAzurePrivateDnsZone begin processing with ParameterSet 'Default'.
DEBUG: 09:18:00 - using account id '<ACCOUNT_ID>'...
DEBUG: 09:18:00 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: '<ACCOUNT_ID>', environment: 'AzureCloud', tenant: '<TENANT_ID>'
DEBUG: 09:18:00 - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'<APPLICATION_ID>', TenantId:'<TENANT_ID>', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/'
DEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] MSAL MSAL.NetCore with assembly version '4.46.0.0'. CorrelationId(d35aa62a-9f14-4045-8fca-d22c66c27bf2)
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - d35aa62a-9f14-4045-8fca-d22c66c27bf2
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] === Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://management.core.windows.net//.default
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] [Region discovery] Not using a regional authority.
DEBUG: Request [d099f356-48fa-4621-a2a8-bcc9d64d350e] POST https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:d099f356-48fa-4621-a2a8-bcc9d64d350e
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.1,(.NET 6.0.8; Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
DEBUG: Response [d099f356-48fa-4621-a2a8-bcc9d64d350e] 200 OK (00.1s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:891dfa0d-501d-4baa-af71-381564ff1c00
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Tue, 18 Oct 2022 07:17:59 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1379

DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] ScopeSet was missing from the token response, so using developer provided scopes in the result.
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] Checking client info returned from the server..
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] Saving token response to cache..
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] ID Token not present in response.
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] Cannot determine home account id - or id token or no client info and no subject
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] Saving AT in cache and removing overlapping ATs...
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] Looking for scopes for the authority in the cache which intersect with https://management.core.windows.net//.default
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] Intersecting scope entries count - 0
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2]
	=== Token Acquisition finished successfully:
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2]  AT expiration time: 18.10.2022 08:17:59 +00:00, scopes: https://management.core.windows.net//.default. source: IdentityProvider
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 [2022-10-18 07:18:00Z - d35aa62a-9f14-4045-8fca-d22c66c27bf2] Fetched access token from host login.microsoftonline.com.
DEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-10-18T08:17:59.3490660+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<TENANT_ID>', UserId: '<USER_ID>'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Network/privateDnsZones?api-version=2018-09-01

Headers:
x-ms-client-request-id        : 3ed19ecb-8c41-45ca-bb94-383f2e654ddb
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : private
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 3ed19ecb-8c41-45ca-bb94-383f2e654ddb
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-resource-requests: 499
x-ms-ratelimit-remaining-subscription-resource-entities-read: 60000
x-ms-correlation-request-id   : 15191d57-5ae5-4a48-9639-5b0936fcd037
x-ms-routing-request-id       : GERMANYWESTCENTRAL:20221018T071800Z:15191d57-5ae5-4a48-9639-5b0936fcd037
Date                          : Tue, 18 Oct 2022 07:18:00 GMT

Body:
{
  "code": "BadRequest",
  "message": "The specified subscription <SUBSCRIPTION_ID> does not exist"
}


DEBUG: 09:18:00 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Get-AzPrivateDnsZone: The specified subscription <SUBSCRIPTION_ID> does not exist
DEBUG: 09:18:01 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.PrivateDns:1.0.3; CommandName: Get-AzPrivateDnsZone; PSVersion: 7.2.6; IsSuccess: False; Duration: 00:00:00.7822706; Exception: The specified subscription <SUBSCRIPTION_ID> does not exist;
DEBUG: 09:18:01 - GetAzurePrivateDnsZone end processing.
```

### Environment data

```PowerShell
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     1.0.3                 Az.PrivateDns                       {Add-AzPrivateDnsRecordConfig, Get-AzPrivateDnsRecordSet, Get-AzPrivateDnsVirtualNetworkLink, Get-AzPrivateDnsZone…}
```

### Error output

```PowerShell
RequestId      : 7ef2e28c-721e-4adc-b095-0e25fe738ea3
Message        : The specified subscription <SUBSCRIPTION_ID> does not exist
ServerMessage  : BadRequest: The specified subscription <SUBSCRIPTION_ID> does not exist (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {GET https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.Network/privateDnsZones?api-version=2018-09-01}
InvocationInfo : {Get-AzPrivateDnsZone}
Line           : Get-AzPrivateDnsZone
Position       : At line:1 char:1
                 + Get-AzPrivateDnsZone
                 + ~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.PrivateDns.PrivateZonesOperations.ListWithHttpMessagesAsync(Nullable`1 top, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.PrivateDns.PrivateZonesOperationsExtensions.ListAsync(IPrivateZonesOperations operations, Nullable`1 top, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.PrivateDns.PrivateZonesOperationsExtensions.List(IPrivateZonesOperations operations, Nullable`1 top)
                    at Microsoft.Azure.Commands.PrivateDns.Models.PrivateDnsClient.ListPrivateDnsZonesInSubscription()
                    at Microsoft.Azure.Commands.PrivateDns.Zones.GetAzurePrivateDnsZone.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 3
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. @clowa , can you get private DNS zone when you specify issue subscription id to `Get-AzPrivateDnsZone`?

**Comment by navba-MSFT** [comment]
@clowa Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by clowa** [comment]
Hey @dingmeng-xue
I'm not 100 % sure what you mean.
The cmdlet `Get-AzPrivateDnsZone` doesn't allow to set a specific subscription so I tried `Set-AzContext -SubscriptionId <SUBSCRIPTION_ID>; Get-AzPrivateDnsZone` but the same error occurred.

Just to make sure, the affected subscriptions doesn't contain an active Azure private dns zone. On other subscriptions, also without any Azure private dns zone, the cmdlet returns nothing and no error is displayed. I'm just not sure why just some subscriptions are affected by this error and some not.

Let me know if I should provide more information - like the effected subscription id - on a secured channel.

**Comment by navba-MSFT** [comment]
@clowa I am unable to reproduce this issue at my end. So while enumerating through each of the subscriptions, Could you run the below command and check if the same issue occurs ?

> **Select-AzSubscription -SubscriptionId 'XXXX-XXXX-XXXXX-XXXX-XXX'**

Awaiting your reply.

**Comment by clowa** [comment]
Hey @navba-MSFT

too bad you can't reproduce it ...

I have run the following code. The Subscription was selected and the context was set without errors. The `Get-AzPrivateDnsZone` failed as expected.

```powershell
PS> Get-AzSubscription | % {
>        Select-AzSubscription -SubscriptionId $_.Id
>        $_ | Set-AzContext
>        Get-AzPrivateDnsZone
> }
```

I'm also able to receive other resources from the effected subscription eg. Resource Groups.

I don't know if it is important but as far as I can remember the effected subscription has never contained any Azure private dns zone resource.

Let me know how I can help!

**Comment by navba-MSFT** [comment]
@clowa Thanks for your reply. Apologies for my late reply. It took sometime for me to fetch the right subscription and reproduce this issue at my end. 

I have an interesting observation to share. I have a working scenario where the cmdlet **doesn't** throw any `Bad Request `error on the subscription where there are **no** Azure private dns zone resources. 

Also I was able to get another subscription where the same cmdlet throws `Bad Request `error while there are no Azure private dns zone resources.

I am looking at my backend logs to find the difference between both the subscriptions to find the root cause. 
I am also discussing this further with the Product Owners. Hoping to hearing back from them now. I will keep you posted on this.

**Comment by clowa** [comment]
Hey @navba-MSFT,

great to hear you were able to reproduce the issue - it's super weird isn't it ?

I have no clue, my first guess was the API is messing up this. Looking forward to hear from you. Again - let me know if I can help!

Really appreciate your effort!

**Comment by navba-MSFT** [comment]
@clowa After looking at the backend logs, I could identity the cause of this issue.

The subscription that is "Not Registered" for the Microsoft.Network resource provider will result in this issue. You can check this for your failed subscription from Azure portal. 
Navigate to that failing **Subscription** in Azure Portal --> Select **Resource providers** --> Search for **Microsoft.Network** Resource Provider and you can select **Register**.

![image](https://user-images.githubusercontent.com/57353862/198503253-18cb7274-ebce-4249-bb7e-54262218842a.png)

You need to follow the above action plan manually for all the subscriptions _that are failing_ while running your test script. Registering should take sometime. Post that you can test again. Hope this helps.

**Comment by navba-MSFT** [comment]
@clowa I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@clowa The action is currently pending on you to test the above suggestion. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by clowa** [comment]
Hey @navba-MSFT,
I'm sorry for my late reply! I can confirm the issue is resolved by registering the `Microsoft.Network` provider on the affected subscriptions.

Big thank's for your assistance!
