### ISSUE TITLE
Get-AzNetworkInterface raises Error mapping types when NIC chains GWLB

### ISSUE THREAD

**Issue by kongou-ae** [Azure/azure-powershell#19849]
### Description

Get-AzNetworkInterface raises "Error mapping types" when NIC chains GWLB. There are no error when NIC doesn't chain GWLB.

### Issue script & Debug output

```PowerShell
DEBUG: 14:25:16 - GetAzureNetworkInterfaceCommand begin processing with ParameterSet 'NoExpandStandAloneNic'.
DEBUG: 14:25:16 - using account id 'MY-ACCOUNT-ID'...
DEBUG: 14:25:16 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'MY-ACCOUNT-ID', environment: 'AzureCloud', tenant: 'MY-TENANT-ID'
DEBUG: 14:25:16 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'MY-TENANT-ID', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'MY-ACCOUNT-ID'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - 09acf72d-d3d9-4a83-b782-a59f1ad87282] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - 09acf72d-d3d9-4a83-b782-a59f1ad87282] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - 09acf72d-d3d9-4a83-b782-a59f1ad87282] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - 09acf72d-d3d9-4a83-b782-a59f1ad87282] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - 09acf72d-d3d9-4a83-b782-a59f1ad87282] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z] Returning 1 accounts
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] MSAL MSAL.NetCore with assembly version '4.46.0.0'. CorrelationId(c2e757dc-61ca-4df4-9047-97df5acafbcf)
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] LoginHint provided: False
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] Account provided: True
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] ForceRefresh: False
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - c2e757dc-61ca-4df4-9047-97df5acafbcf
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] Access token is not expired. Returning the found cache entry. [Current time (10/19/2022 05:25:16) - Expiration Time (10/19/2022 06:49:48 +00:00) - Extended Expiration Time (10/19/2022 06:49:48 +00:00)]
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.46.0.0 MSAL.NetCore .NET 6.0.8 Microsoft Windows 10.0.22621 [2022-10-19 05:25:16Z - c2e757dc-61ca-4df4-9047-97df5acafbcf]  AT expiration time: 2022/10/19 6:49:48 +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-10-19T06:49:48.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'MY-TENANT-ID', UserId: 'MY-ACCOUNT-ID'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/azfwdiag/providers/Microsoft.Network/networkInterfaces/diag632_z1?api-version=2022-05-01

Headers:
x-ms-client-request-id        : 25a05bf9-8308-455b-bd95-ff9954ae20c1
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : W/"a37bd661-46d6-47a4-9cec-4fc5f9e5402b"
x-ms-request-id               : 9280b715-dfd8-4e72-abde-77c28eedc0ae
x-ms-correlation-request-id   : bd2c13a6-99a3-430c-b636-14ee6dcc8634
x-ms-arm-service-request-id   : 4a91c28e-60bf-4d50-9e9f-56eb5a475dd5
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-routing-request-id       : JAPANEAST:20221019T052516Z:bd2c13a6-99a3-430c-b636-14ee6dcc8634
X-Content-Type-Options        : nosniff
Date                          : Wed, 19 Oct 2022 05:25:16 GMT

Body:
{
  "name": "diag632_z1",
  "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/azfwdiag/providers/Microsoft.Network/networkInterfaces/diag632_z1",
  "etag": "W/\"a37bd661-46d6-47a4-9cec-4fc5f9e5402b\"",
  "properties": {
    "provisioningState": "Succeeded",
    "resourceGuid": "86c3e6e0-25ca-4de7-9c69-4e174c04ef83",
    "ipConfigurations": [
      {
        "name": "ipconfig1",
        "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/azfwdiag/providers/Microsoft.Network/networkInterfaces/diag632_z1/ipConfigurations/ipconfig1",
        "etag": "W/\"a37bd661-46d6-47a4-9cec-4fc5f9e5402b\"",
        "type": "Microsoft.Network/networkInterfaces/ipConfigurations",
        "properties": {
          "provisioningState": "Succeeded",
          "privateIPAddress": "172.16.0.5",
          "privateIPAllocationMethod": "Dynamic",
          "publicIPAddress": {
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/azfwdiag/providers/Microsoft.Network/publicIPAddresses/nnn"
          },
          "subnet": {
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/gwlb0928/providers/Microsoft.Network/virtualNetworks/gwlbvnet/subnets/default"
          },
          "primary": true,
          "privateIPAddressVersion": "IPv4",
          "gatewayLoadBalancer": {
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/gw/providers/Microsoft.Network/loadBalancers/gw/frontendIPConfigurations/aaaa"
          }
        }
      }
    ],
    "dnsSettings": {
      "dnsServers": [],
      "appliedDnsServers": [],
      "internalDomainNameSuffix": "2ie2yarobu1ercv5owf3fs4xte.lx.internal.cloudapp.net"
    },
    "macAddress": "00-22-48-E7-37-17",
    "enableAcceleratedNetworking": false,
    "vnetEncryptionSupported": false,
    "enableIPForwarding": false,
    "disableTcpStateTracking": false,
    "primary": true,
    "virtualMachine": {
      "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/AZFWDIAG/providers/Microsoft.Compute/virtualMachines/diag"
    },
    "hostedWorkloads": [],
    "tapConfigurations": [],
    "nicType": "Standard",
    "allowPort25Out": true
  },
  "type": "Microsoft.Network/networkInterfaces",
  "location": "japaneast",
  "kind": "Regular"
}


DEBUG: 14:25:16 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzNetworkInterface: Error mapping types.
Mapping types:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface
Type Map configuration:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface
Property:
IpConfigurations
DEBUG: 14:25:16 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Network:5.0.0; CommandName: Get-AzNetworkInterface; PSVersion: 7.2.6; IsSuccess: False; Duration: 00:00:00.2213222; Exception: Error mapping types.

Mapping types:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface

Type Map configuration:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface

Property:
IpConfigurations;
DEBUG: 14:25:16 - GetAzureNetworkInterfaceCommand end processing.
```

### Environment data

```PowerShell
\> $PSVersionTable 

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     5.0.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzApplicationGatewayBackendSe…
```

### Error output

```PowerShell
DEBUG: 14:28:04 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 14:28:04 - using account id 'ymatsumoto@microsoft.com'...
DEBUG: 14:28:04 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 21

Message        : Error mapping types.

                 Mapping types:
                 NetworkInterface -> PSNetworkInterface
                 Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface

                 Type Map configuration:
                 NetworkInterface -> PSNetworkInterface
                 Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface

                 Property:
                 IpConfigurations
StackTrace     :    at lambda_method652(Closure , NetworkInterface , PSNetworkInterface , ResolutionContext )
                    at lambda_method653(Closure , Object , Object , ResolutionContext )
                    at Microsoft.Azure.Commands.Network.NetworkInterfaceBaseCmdlet.GetNetworkInterface(String resourceGroupName, String name, String expandResource)
                    at Microsoft.Azure.Commands.Network.GetAzureNetworkInterfaceCommand.Execute()
                    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : AutoMapper.AutoMapperMappingException
InvocationInfo : {Get-AzNetworkInterface}
Line           : Get-AzNetworkInterface -ResourceGroupName azfwdiag -Name diag632_z1
Position       : At line:1 char:1
                 + Get-AzNetworkInterface -ResourceGroupName azfwdiag -Name diag632_z1
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 21

Message        : Error mapping types.

                 Mapping types:
                 NetworkInterfaceIPConfiguration -> PSNetworkInterfaceIPConfiguration
                 Microsoft.Azure.Management.Network.Models.NetworkInterfaceIPConfiguration -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterfaceIPConfiguration

                 Type Map configuration:
                 NetworkInterfaceIPConfiguration -> PSNetworkInterfaceIPConfiguration
                 Microsoft.Azure.Management.Network.Models.NetworkInterfaceIPConfiguration -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterfaceIPConfiguration

                 Property:
                 GatewayLoadBalancer
StackTrace     :    at lambda_method652(Closure , NetworkInterface , PSNetworkInterface , ResolutionContext )
Exception      : AutoMapper.AutoMapperMappingException
InvocationInfo : {Get-AzNetworkInterface}
Line           : Get-AzNetworkInterface -ResourceGroupName azfwdiag -Name diag632_z1
Position       : At line:1 char:1
                 + Get-AzNetworkInterface -ResourceGroupName azfwdiag -Name diag632_z1
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 21

Message        : Unable to cast object of type 'Microsoft.Azure.Commands.Network.Models.PSResourceId' to type 'Microsoft.Azure.Commands.Network.Models.PSFrontendIPConfiguration'.
StackTrace     :    at lambda_method666(Closure , SubResource , PSFrontendIPConfiguration , ResolutionContext )
                    at AutoMapper.Mapper.AutoMapper.IRuntimeMapper.Map[TSource,TDestination](TSource source, TDestination destination, ResolutionContext context)
                    at lambda_method652(Closure , NetworkInterface , PSNetworkInterface , ResolutionContext )
Exception      : System.InvalidCastException
InvocationInfo : {Get-AzNetworkInterface}
Line           : Get-AzNetworkInterface -ResourceGroupName azfwdiag -Name diag632_z1
Position       : At line:1 char:1
                 + Get-AzNetworkInterface -ResourceGroupName azfwdiag -Name diag632_z1
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 21
```

**Comment by navba-MSFT** [comment]
@kongou-ae Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

Could you please remove your old `Az.Network `module and then install the most recent module (5.3.0)  and check if you face the same issue. https://www.powershellgallery.com/packages/Az.Network/5.3.0 .

Awaiting your reply.

**Comment by kongou-ae** [comment]
HI @navba-MSFT 

Thank you for your reply. In Az.Network 5.3, I encountered the same error.

```
PS C:\Users\ymatsumoto> Get-Module Az.Network

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     5.3.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificat…

PS C:\Users\ymatsumoto> Get-AzNetworkInterface
Get-AzNetworkInterface: Error mapping types.
Mapping types:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface
Type Map configuration:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface
Property:
IpConfigurations
```

**Comment by navba-MSFT** [comment]
@kongou-ae Could you please run the below PS script and let me know if that helps ?

```
$auth=Get-AzAccessToken
$authHeader= $auth.token

$output=Invoke-WebRequest -Uri "https://management.azure.com/subscriptions/XXXX-XXX-XXX-XXXX/resourceGroups/azfwdiag/providers/Microsoft.Network/networkInterfaces/diag632_z1?api-version=2022-05-01" -Method GET -Headers @{"Authorization"="Bearer $authHeader"}

$output
```

**Comment by kongou-ae** [comment]
@navba-MSFT 

PowerShell raises an error. But API doesn't raise an error.

```
> Get-AzNetworkInterface -ResourceId /subscriptions/<MY-SUB-ID>/resourceGroups/fimcheck/providers/Microsoft.Network/networkInterfaces/fimcheck01930
Get-AzNetworkInterface: Error mapping types.
Mapping types:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface
Type Map configuration:
NetworkInterface -> PSNetworkInterface
Microsoft.Azure.Management.Network.Models.NetworkInterface -> Microsoft.Azure.Commands.Network.Models.PSNetworkInterface
Property:
IpConfigurations

> $output=Invoke-WebRequest -Uri "https://management.azure.com/subscriptions/<MY-SUB-ID>/resourceGroups/fimcheck/providers/Microsoft.Network/networkInterfaces/fimcheck01930?api-version=2022-05-01" -Method GET -Headers @{"Authorization"="Bearer $authHeader"}
> $output

StatusCode        : 200
StatusDescription : OK
Content           : {
                      "name": "fimcheck01930",
                      "id": "/subscriptions/<MY-SUB-ID>/resourceGroups/fimcheck/providers/Micr
                    osoft.Network/networkInterfaces/fimcheck01930",
                      "etag": "W/\"2a70f1…
RawContent        : HTTP/1.1 200 OK
                    Cache-Control: no-cache
                    Pragma: no-cache
                    ETag: W/"2a70f1f1-9bfe-4665-992e-301bd3bd5022"
                    x-ms-request-id: cc31cf0a-5e15-42a5-92c1-45649dd5b0a0
                    x-ms-correlation-request-id: 333df685…
Headers           : {[Cache-Control, System.String[]], [Pragma, System.String[]], [ETag, System.String[]], [x-ms-reques
                    t-id, System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 2620
RelationLink      : {}
```

**Comment by navba-MSFT** [comment]
@kongou-ae Thanks for getting back. I am glad that invoking the API directly helps. Could you please share the steps on how to reproduce this issue at end ? I am able to get this working with a simple plain NetworkInterface resource.

**Comment by kongou-ae** [comment]
@navba-MSFT 

1. Create the virtual machine which has a public IP address.
2. Create Gateway Load Balancer
3. Chain this Gateway Load Balancer to this Virtual Machine
4. Run Get-AzNetworkInterface

![image](https://user-images.githubusercontent.com/3410186/213968780-91f690c5-66ba-4011-a8e8-9c7240ee3ff6.png)

**Comment by navba-MSFT** [comment]
@kongou-ae Thanks for sharing the repro details. I am involving the Service team to look into this. 

@aznetsuppgithub Could you please look into this issue ? Thanks in advance.

**Comment by kongou-ae** [comment]
I checked that Az.Network 6.0.0.0 fixed this issue. I appreciate your kind support.
