### ISSUE TITLE
Get-AzMetric on SQL Server Database intermittenly doesn't find all valid metrics

### ISSUE THREAD

**Issue by jared-koiter** [Azure/azure-powershell#19892]
### Description

When attempting to run `Get-AzMetric -MetricName 'storage'` against a SQL Server Database resource, the call intermittently fails with a "BadRequest" response and the following message:

```
Failed to find metric configuration for provider: Microsoft.Sql, resource Type: servers/databases, metric: storage, Valid metrics: cpu_percent,physical_data_read_percent,connection_successful,connection_failed,connection_failed_user_error,blocked_by_firewall,ledger_digest_upload_success,ledger_digest_upload_failed
```

This list of valid metrics is much smaller than it should be, as in usual cases the list of valid metrics looks something more like the following:

```
cpu_percent,physical_data_read_percent,log_write_percent,storage,connection_successful,connection_failed,connection_failed_user_error,blocked_by_firewall,deadlock,storage_percent,xtp_storage_percent,workers_perce
nt,sessions_percent,sessions_count,cpu_limit,cpu_used,allocated_data_storage,full_backup_size_bytes,diff_backup_size_bytes,log_backup_size_bytes,ledger_digest_upload_success,ledger_digest_upload_failed
```

Repeated attempts to run the command doesn't seem to show a particular pattern in when the issue occurs. Trying to run `Get-AzMetricDefinition` on the same resource also appears to be affected, and shows the same limited set of valid metrics.

Notably the issue seems to only affect certain database resources, and I cannot reproduce the same effect on some seemingly identical databases in the same server/resource group whereas I can reproduce it on others. I don't currently know what difference is causing this change in behaviour.

### Issue script & Debug output

```PowerShell
PS> $DebugPreference = 'Continue'
PS> $resourceId = '/subscriptions/abcdef12-3456-7890-abcd-ef1234567890/resourceGroups/exampleRg/providers/Microsoft.Sql/servers/exampleSqlServer/databases/exampleDatabase'
PS> Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
DEBUG: 2:34:08 PM - GetAzureRmMetricCommand begin processing with ParameterSet 'GetWithDefaultParameters'.
DEBUG: 2:34:08 PM - using account id 'scrubbed.user@example.com'...
DEBUG: 2:34:08 PM - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
WARNING: 2:34:08 PM - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 2:34:08 PM - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
WARNING: [Get-AzMetric] Parameter deprecation: The DetailedOutput parameter will be deprecated in a future breaking change release.
DEBUG: [Common.Authentication]: Authenticating using Account: 'scrubbed.user@example.com', environment: 'AzureCloud', tenant: 'abcdef12-3456-7890-abcd-ef1234567890'
DEBUG: 2:34:08 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'abcdef12-3456-7890-abcd-ef1234567890', Scopes:'https://management.core.windows.net//.default', AuthorityHost:
'https://login.microsoftonline.com/', UserId:'scrubbed.user@example.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 613adf76-0dd6-443a-9e9a-2acae11f7ed7] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 613adf76-0dd6-443a-9e9a-2acae11f7ed7] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 613adf76-0dd6-443a-9e9a-2acae11f7ed7] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 613adf76-0dd6-443a-9e9a-2acae11f7ed7] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 613adf76-0dd6-443a-9e9a-2acae11f7ed7] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z] Returning 1 accounts
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] MSAL MSAL.Desktop with assembly version '4.46.0.0'. CorrelationId(739c0598-b76d-4c
d3-bb52-721d79ade9ab)
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] LoginHint provided: False
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] Account provided: True
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] ForceRefresh: False
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 739c0598-b76d-4cd3-bb52-721d79ade9ab
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] === Token Acquisition (SilentRequest) started:
	 Scopes: https://management.core.windows.net//.default
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] Access token is not expired. Returning the found cache entry. [Current time (10/20
/2022 18:34:08) - Expiration Time (10/20/2022 19:24:27 +00:00) - Extended Expiration Time (10/20/2022 19:24:27 +00:00)]
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab] 
	=== Token Acquisition finished successfully:
DEBUG: False MSAL 4.46.0.0 MSAL.Desktop 4.8 or later Windows 10 Pro [2022-10-20 18:34:08Z - 739c0598-b76d-4cd3-bb52-721d79ade9ab]  AT expiration time: 2022-10-20 7:24:27 PM +00:00, scopes: https://management.core
.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-10-20T19:24:27.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'abcdef12-3456-7890-abcd-ef1234567890', UserId: 'scrubbed.user@example.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/abcdef12-3456-7890-abcd-ef1234567890/resourceGroups/exampleRg/providers/Microsoft.Sql/servers/exampleSqlServer/databases/exampleDatabase/providers/Microsoft.
Insights/metrics?timespan=2022-10-20T17:34:08.3912764Z%2F2022-10-20T18:34:08.3912764Z&metricnames=storage&api-version=2018-01-01

Headers:
x-ms-client-request-id        : abcdef12-3456-7890-abcd-ef1234567890
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-correlation-request-id   : abcdef12-3456-7890-abcd-ef1234567890
x-ms-ratelimit-remaining-subscription-reads: 11999
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Request-Context               : appId=cid-v1:abcdef12-3456-7890-abcd-ef1234567890
x-ms-request-id               : {abcdef12-3456-7890-abcd-ef1234567890}
Access-Control-Allow-Origin   : *
x-ms-routing-request-id       : CANADACENTRAL:20221020T183408Z:abcdef12-3456-7890-abcd-ef1234567890
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 20 Oct 2022 18:34:08 GMT

Body:
{
  "code": "BadRequest",
  "message": "Failed to find metric configuration for provider: Microsoft.Sql, resource Type: servers/databases, metric: storage, Valid metrics: cpu_percent,physical_data_read_percent,connection_successful,connec
tion_failed,connection_failed_user_error,blocked_by_firewall,ledger_digest_upload_success,ledger_digest_upload_failed"
}


DEBUG: 2:34:08 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzMetric : Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.MetricsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.<ListAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
At line:1 char:1
+ Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzMetric], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand
```

### Environment data

```PowerShell
PS> $PSVersionTable

Name                           Value                                                                                                                                                                               
----                           -----                                                                                                                                                                               
PSVersion                      5.1.19041.1682                                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                             
BuildVersion                   10.0.19041.1682                                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                                 
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS> Get-Module Az*

ModuleType Version    Name                                ExportedCommands                                                                                                                                         
---------- -------    ----                                ----------------                                                                                                                                         
Script     2.10.2     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}                                                                                 
Script     4.2.0      Az.Monitor                          {Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2, Add-AzWebtestAlertRule...}
```

### Error output

```PowerShell
PS> Resolve-AzError
DEBUG: 2:48:17 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 2:48:17 PM - using account id 'scrubbed.user@example.com'...
DEBUG: 2:48:17 PM - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].


   HistoryId: 32


Message        : Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
                    at Microsoft.Azure.Management.Monitor.MetricsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.<ListAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Get-AzMetric}
Line           : Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
Position       : At line:1 char:1
                 + Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 32

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.MetricsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.<ListAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Monitor.Models.ErrorResponseException
InvocationInfo : {Get-AzMetric}
Line           : Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
Position       : At line:1 char:1
                 + Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 32



   HistoryId: 12


Message        : Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
                    at Microsoft.Azure.Management.Monitor.MetricsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.<ListAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Get-AzMetric}
Line           :     Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
                 
Position       : At line:2 char:5
                 +     Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.MetricsOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.<ListAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Monitor.Models.ErrorResponseException
InvocationInfo : {Get-AzMetric}
Line           :     Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
                 
Position       : At line:2 char:5
                 +     Get-AzMetric -ResourceId $resourceId -MetricName 'storage'
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 2:48:17 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent: Module: Az.Accounts:2.10.2; CommandName: Resolve-AzError; PSVersion: 5.1.19041.1682; IsSuccess: True; Duration: 00:00:00.0958491
DEBUG: 2:48:17 PM - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
@jared-koiter , thanks for reporting. As you mentioned, the issue occurs in some resource but cannot occur in others. You need to provide resource information to Microsoft support to get further assistance. From client side, it doesn't have further information.

**Comment by jared-koiter** [comment]
I have contacted Microsoft support as suggested and will see if they can provide any insight into what's going on with these databases.

**Comment by jared-koiter** [comment]
I still have a ticket open with Microsoft support, who themselves appear to be waiting on a response from an internal product team. I'll provide an update here as soon as I get an answer from Microsoft.

**Comment by RakeshMohanMSFT** [comment]
@jared-koiter Thank you, we will wait for your update.
