### ISSUE TITLE
PowerShell 7.3.0 rejects New-AzNetworkSecurityGroup with a constraint violation

### ISSUE THREAD

**Issue by StephanTLavavej** [Azure/azure-powershell#20059]
### Description

With PowerShell 7.3.0 and Azure PowerShell 9.1.0, `New-AzNetworkSecurityGroup` fails with:

```
New-AzNetworkSecurityGroup: GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
```

Downgrading PowerShell to 7.2.7, but keeping Azure PowerShell 9.1.0, succeeds. I'm unsure if this is a regression in PowerShell, or a bug in Azure PowerShell that is newly being diagnosed.

### Issue script & Debug output

```PowerShell
Here are exact steps to demonstrate the failure:

C:\Temp>pwsh
PowerShell 7.3.0
PS C:\Temp> ((Get-InstalledModule -Name Az -AllVersions).Version | Sort-Object -Descending { [version] $_ })[0]
9.1.0
PS C:\Temp> $Location = 'eastus'
PS C:\Temp> $ResourceGroupName = 'BugReport'
PS C:\Temp> $NetworkSecurityGroupName = $ResourceGroupName + '-NetworkSecurity'
PS C:\Temp> New-AzResourceGroup -Name $ResourceGroupName -Location $Location

ResourceGroupName : BugReport
Location          : eastus
ProvisioningState : Succeeded
Tags              :
ResourceId        : /subscriptions/ddddd02b-5e77-473c-afde-c40253b5343e/resourceGroups/BugReport


PS C:\Temp> New-AzNetworkSecurityGroup -Name $NetworkSecurityGroupName -ResourceGroupName $ResourceGroupName -Location $Location
New-AzNetworkSecurityGroup: GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.


Here's the successful behavior after downgrading to PowerShell 7.2.7:


C:\Temp>pwsh
PowerShell 7.2.7
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Temp> ((Get-InstalledModule -Name Az -AllVersions).Version | Sort-Object -Descending { [version] $_ })[0]
9.1.0
PS C:\Temp> $Location = 'eastus'
PS C:\Temp> $ResourceGroupName = 'BugReport2'
PS C:\Temp> $NetworkSecurityGroupName = $ResourceGroupName + '-NetworkSecurity'
PS C:\Temp> New-AzResourceGroup -Name $ResourceGroupName -Location $Location

ResourceGroupName : BugReport2
Location          : eastus
ProvisioningState : Succeeded
Tags              :
ResourceId        : /subscriptions/ddddd02b-5e77-473c-afde-c40253b5343e/resourceGroups/BugReport2


PS C:\Temp> New-AzNetworkSecurityGroup -Name $NetworkSecurityGroupName -ResourceGroupName $ResourceGroupName -Location $Location

Name                 : BugReport2-NetworkSecurity
ResourceGroupName    : BugReport2
Location             : eastus
[...]
ProvisioningState    : Succeeded
[...]
```

### Environment data

```PowerShell
PS C:\Temp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Temp> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     5.1.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificat…
Script     6.4.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…
```

### Error output

```PowerShell
Message        : GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T
                 MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
StackTrace     :    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[]
                 genericArguments, Exception e)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
                    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2
                 <>h__TransparentIdentifier1)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
                    at System.Linq.Enumerable.UnionIterator`1.FillSet()
                    at System.Linq.Enumerable.UnionIterator`1.ToArray()
                    at AutoMapper.TypeDetails.BuildPublicNoArgExtensionMethods(IEnumerable`1
                 sourceExtensionMethodSearch)
                    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
                    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
                    at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
                    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean
                 useDefaultConstructor)
                    at System.Lazy`1.CreateValue()
                    at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
                    at AutoMapper.ProfileMap.CreateTypeDetails(Type type)
                    at AutoMapper.Configuration.Conventions.NameSplitMember.MapDestinationPropertyToSource(ProfileMap
                 options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch,
                 LinkedList`1 resolvers, IMemberConfiguration parent)
                    at
                 AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap
                 options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch,
                 LinkedList`1 resolvers)
                    at AutoMapper.TypeMapFactory.<>c__DisplayClass1_0.<MapDestinationPropertyToSource>b__0(IMemberConfi
                 guration _)
                    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
                    at AutoMapper.TypeMapFactory.MapDestinationPropertyToSource(ProfileMap options, TypeDetails
                 sourceTypeInfo, Type destType, Type destMemberType, String destMemberInfo, LinkedList`1 members)
                    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap
                 options)
                    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration
                 config)
                    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
                    at AutoMapper.MapperConfiguration.Seal()
                    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
                    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
                    at Microsoft.Azure.Commands.Network.NetworkResourceManagerProfile.Initialize()
                    at Microsoft.Azure.Commands.Network.NetworkResourceManagerProfile.get_Mapper()
                    at
                 Microsoft.Azure.Commands.Network.NewAzureNetworkSecurityGroupCommand.CreateNetworkSecurityGroup()
                    at Microsoft.Azure.Commands.Network.NewAzureNetworkSecurityGroupCommand.<>c__DisplayClass28_0.<Exec
                 ute>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force,
                 String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
                    at Microsoft.Azure.Commands.Network.NewAzureNetworkSecurityGroupCommand.Execute()
                    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {New-AzNetworkSecurityGroup}
Line           : New-AzNetworkSecurityGroup -Name $NetworkSecurityGroupName -ResourceGroupName $ResourceGroupName
                 -Location $Location
Position       : At line:1 char:1
                 + New-AzNetworkSecurityGroup -Name $NetworkSecurityGroupName -ResourceG …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : Method System.Linq.Enumerable.MaxInteger: type argument
                 'Microsoft.Azure.Management.Network.Models.SecurityRule' violates the constraint of type parameter
                 'T'.
StackTrace     :    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType
                 declaringType, RuntimeType[] methodInstantiation)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
Exception      : System.Security.VerificationException
InvocationInfo : {New-AzNetworkSecurityGroup}
Line           : New-AzNetworkSecurityGroup -Name $NetworkSecurityGroupName -ResourceGroupName $ResourceGroupName
                 -Location $Location
Position       : At line:1 char:1
                 + New-AzNetworkSecurityGroup -Name $NetworkSecurityGroupName -ResourceG …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7
```

**Comment by JelleBroekhuijsen** [comment]
I am experiencing the same issue with the Get-AzVirtualNetwork cmdlet:

````
Get-AzVirtualNetwork: GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
````

````
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
````

````
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     9.1.0                 Az                                  Core,Desk
````

**Comment by jkav58** [comment]
Same issue with `get-azvm`; code works without issue in 7.2.7

**Comment by tracsman** [comment]
Same issue for me with ```Get-azExpressRouteCircuit``` and ````Get-azExpressRoutePort```` on PS 7.3.0.

**Comment by erwynNL** [comment]
Same issue for me on `Get-AzVM` after updating to 7.3.0:

```
Get-AzVM: GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
```

**Comment by dingmeng-xue** [comment]
It's the same issue as #18721. Close this one and please track progress on #18721
