### ISSUE TITLE
[Az.Network] [PS7.3] Get-AzVirtualNetwork fails on security rule generic with PowerShell 7.3

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-powershell#20082]
### Description

CC @SteveL-MSFT 

Was trying to fetch all subscriptions, this happened on a couple vnets, I think it may be related to the new generic type arguments in PS 7.3, or maybe something in .NET 7. Works fine on 5.1 and 7.2.6. 
![image](https://user-images.githubusercontent.com/15258962/201153587-33fe32af-7602-4e8a-86f8-7e43111ae642.png)

### Issue script & Debug output

```PowerShell
Get-AzSubscription |% {$_ | Set-AzContext;Get-AzVirtualNetwork}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     5.1.1                 az.network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSet…
```

### Error output

```
Exception             :
    Type           : System.ArgumentException
    Message        : GenericArguments[0], 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
    TargetSite     :
        Name          : ValidateGenericArguments
        DeclaringType : System.RuntimeType, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    InnerException :
        Type       : System.Security.VerificationException
        TargetSite :
            Name          : GetStubIfNeeded
            DeclaringType : System.RuntimeMethodHandle
            MemberType    : Method
            Module        : System.Private.CoreLib.dll
        Message    : Method System.Linq.Enumerable.MaxInteger: type argument 'Microsoft.Azure.Management.Network.Models.SecurityRule' violates the constraint of type parameter 'T'.
        Source     : System.Private.CoreLib
        HResult    : -2146233075
        StackTrace :
   at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
    Source         : System.Private.CoreLib
    HResult        : -2147024809
    StackTrace     :
   at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
   at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
   at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2 <>h__TransparentIdentifier1)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToArray()
   at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
   at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at AutoMapper.Configuration.Conventions.NameSplitMember.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1
resolvers, IMemberConfiguration parent)
   at AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch,
LinkedList`1 resolvers)
   at AutoMapper.TypeMapFactory.<>c__DisplayClass1_0.<MapDestinationPropertyToSource>b__0(IMemberConfiguration _)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options)
   at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)
   at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
   at AutoMapper.MapperConfiguration.Seal()
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
   at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
   at Microsoft.Azure.Commands.Network.NetworkResourceManagerProfile.Initialize()
   at Microsoft.Azure.Commands.Network.NetworkResourceManagerProfile.get_Mapper()
   at Microsoft.Azure.Commands.Network.VirtualNetworkBaseCmdlet.ToPsVirtualNetwork(VirtualNetwork vnet)
   at Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkCommand.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
CategoryInfo          : CloseError: (:) [Get-AzVirtualNetwork], ArgumentException
FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkCommand
InvocationInfo        :
    MyCommand        : Get-AzVirtualNetwork
    ScriptLineNumber : 1
    OffsetInLine     : 20
    HistoryId        : 1
    Line             : $_ | Set-AzContext;Get-AzVirtualNetwork
    PositionMessage  : At line:1 char:20
                       + $_ | Set-AzContext;Get-AzVirtualNetwork
                       +                    ~~~~~~~~~~~~~~~~~~~~
    InvocationName   : Get-AzVirtualNetwork
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

**Comment by JustinGrote** [comment]
Closing as dupe of https://github.com/Azure/azure-powershell/issues/18721
