### ISSUE TITLE
Get-AzComputeResourceSku encounters error and returns no data in latest Powershell 7.3.0 version

### ISSUE THREAD

**Issue by Get-Ryan** [Azure/azure-powershell#20084]
### Description

After updating to Powershell version 7.3.0, I noticed that Get-AzComputeResourceSku started returning the error listed and did not return any data.

I had a colleague of mine who hadn't updated to 7.3.0 yet run the same command and he obtained the expected return data.

### Issue script & Debug output

```PowerShell
$var = Get-AzComputeResourceSku
Get-AzComputeResourceSku: GenericArguments[0], 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.

Get-AzComputeResourceSku -Debug

...Seemingly quite a bit of valid return data, and then...

DEBUG: 3:15:41 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzComputeResourceSku: GenericArguments[0], 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
DEBUG: 3:15:58 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Compute:5.1.0; CommandName: Get-AzComputeResourceSku; PSVersion: 7.3.0; IsSuccess: False; Duration: 00:00:29.8305525; Exception: GenericArguments[0], 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.;
DEBUG: 3:15:58 PM - GetAzureRmComputeResourceSku end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Get-Module -Name Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     5.1.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAddition…
```

### Error output

```PowerShell
DEBUG: 3:27:22 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 3:27:22 PM - using account id '******************'...
DEBUG: 3:27:22 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 15

Message        : GenericArguments[0],
                 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension', on 'T
                 MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
StackTrace     :    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[]
                 genericArguments, Exception e)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
                    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2
                 <>h__TransparentIdentifier1)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
                    at System.Linq.Enumerable.UnionIterator`1.FillSet()
                    at System.Linq.Enumerable.UnionIterator`1.ToArray()
                    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
                    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
                    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean
                 useDefaultConstructor)
                    at System.Lazy`1.CreateValue()
                    at AutoMapper.ProfileMap.CreateTypeDetails(Type type)
                    at AutoMapper.Configuration.Conventions.NameSplitMember.MapDestinationPropertyToSource(ProfileMap
                 options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch,
                 LinkedList`1 resolvers, IMemberConfiguration parent)
                    at
                 AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap
                 options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch,
                 LinkedList`1 resolvers)
                    at AutoMapper.TypeMapFactory.<>c__DisplayClass1_0.<MapDestinationPropertyToSource>b__0(IMemberConfi
                 guration _)
                    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
                    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap
                 options)
                    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration
                 config)
                    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
                    at AutoMapper.MapperConfiguration.Seal()
                    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
                    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
                    at
                 Microsoft.Azure.Commands.Compute.Automation.Models.ComputeAutomationAutoMapperProfile.Initialize()
                    at
                 Microsoft.Azure.Commands.Compute.Automation.Models.ComputeAutomationAutoMapperProfile.get_Mapper()
                    at Microsoft.Azure.Commands.Compute.Automation.GetAzureRmComputeResourceSku.<ExecuteCmdlet>b__8_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.Automation.GetAzureRmComputeResourceSku.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzComputeResourceSku}
Line           : Get-AzComputeResourceSku -Debug
Position       : At line:1 char:1
                 + Get-AzComputeResourceSku -Debug
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 15

Message        : Method System.Linq.Enumerable.MaxInteger: type argument
                 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension' violates the
                 constraint of type parameter 'T'.
StackTrace     :    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType
                 declaringType, RuntimeType[] methodInstantiation)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
Exception      : System.Security.VerificationException
InvocationInfo : {Get-AzComputeResourceSku}
Line           : Get-AzComputeResourceSku -Debug
Position       : At line:1 char:1
                 + Get-AzComputeResourceSku -Debug
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 15


   HistoryId: 12

Message        : GenericArguments[0],
                 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension', on 'T
                 MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
StackTrace     :    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[]
                 genericArguments, Exception e)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
                    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2
                 <>h__TransparentIdentifier1)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
                    at System.Linq.Enumerable.UnionIterator`1.FillSet()
                    at System.Linq.Enumerable.UnionIterator`1.ToArray()
                    at AutoMapper.TypeDetails.BuildPublicNoArgExtensionMethods(IEnumerable`1
                 sourceExtensionMethodSearch)
                    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
                    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
                    at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
                    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean
                 useDefaultConstructor)
                    at System.Lazy`1.CreateValue()
                    at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
                    at AutoMapper.ProfileMap.CreateTypeDetails(Type type)
                    at AutoMapper.Configuration.Conventions.NameSplitMember.MapDestinationPropertyToSource(ProfileMap
                 options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch,
                 LinkedList`1 resolvers, IMemberConfiguration parent)
                    at
                 AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap
                 options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch,
                 LinkedList`1 resolvers)
                    at AutoMapper.TypeMapFactory.<>c__DisplayClass1_0.<MapDestinationPropertyToSource>b__0(IMemberConfi
                 guration _)
                    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
                    at AutoMapper.TypeMapFactory.MapDestinationPropertyToSource(ProfileMap options, TypeDetails
                 sourceTypeInfo, Type destType, Type destMemberType, String destMemberInfo, LinkedList`1 members)
                    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap
                 options)
                    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration
                 config)
                    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
                    at AutoMapper.MapperConfiguration.Seal()
                    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
                    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
                    at
                 Microsoft.Azure.Commands.Compute.Automation.Models.ComputeAutomationAutoMapperProfile.Initialize()
                    at
                 Microsoft.Azure.Commands.Compute.Automation.Models.ComputeAutomationAutoMapperProfile.get_Mapper()
                    at Microsoft.Azure.Commands.Compute.Automation.GetAzureRmComputeResourceSku.<ExecuteCmdlet>b__8_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.Automation.GetAzureRmComputeResourceSku.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzComputeResourceSku}
Line           : $var = Get-AzComputeResourceSku
Position       : At line:1 char:8
                 + $var = Get-AzComputeResourceSku
                 +        ~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12

Message        : Method System.Linq.Enumerable.MaxInteger: type argument
                 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension' violates the
                 constraint of type parameter 'T'.
StackTrace     :    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType
                 declaringType, RuntimeType[] methodInstantiation)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
Exception      : System.Security.VerificationException
InvocationInfo : {Get-AzComputeResourceSku}
Line           : $var = Get-AzComputeResourceSku
Position       : At line:1 char:8
                 + $var = Get-AzComputeResourceSku
                 +        ~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 3:27:22 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.10.3; CommandName: Resolve-AzError; PSVersion: 7.3.0; IsSuccess: True; Duration: 00:00:00.0477853
DEBUG: 3:27:22 PM - ResolveError end processing.
```

**Comment by ktremain** [comment]
this is probably #18721

**Comment by Get-Ryan** [comment]
It is. I didn't find that issue until a couple hours after posting. Hopefully having 7.3.0 go into general release will cause a bit more priority into this issue, as it seems to affect quite a number of cmdlets.

**Comment by Get-Ryan** [comment]
Did not intend that closure. Goes to show how often I use Github.

**Comment by RakeshMohanMSFT** [comment]
@dingmeng-xue for awareness

**Comment by dingmeng-xue** [comment]
The same one. Let's us track #18721. Close this one now.
