### ISSUE TITLE
New-AzVM with parameter "PublicIpSku" parameter fails with an exception - both with "Standard" nor "Basic"

### ISSUE THREAD

**Issue by lemsa** [Azure/azure-powershell#20091]
### If I use the following command the New-AzVM command fails badly

- New-AzVM -ResourceGroupName $resourceGroupName -Location $location -VM $vm -PublicIpSku Basic

**However if I use the following it works, but it gives me a warning and kind of tells me to use either the "PublicIpSku" parameter or the "Zone" parameter because of the change in May 2023:**

- New-AzVM -ResourceGroupName $resourceGroupName -Location $location -VM $vm

**The warning is as follows:**

`Starting in May 2023 the "New-AzVM" cmdlet will deploy with the Trusted Launch configuration by default. To know more about Trusted Launch, please visit
https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch
It is recommended to use parameter "-PublicIpSku Standard" in order to create a new VM with a Standard public IP.Specifying zone(s) using the "-Zone" parameter  
will also result in a Standard public IP.If "-Zone" and "-PublicIpSku" are not specified, the VM will be created with a Basic public IP instead.Please note that 
 the Standard SKU IPs will become the default behavior for VM creation in the future
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure
PowerShell.
WARNING: Error occurred when creating storage account for boot diagnostics.  Keep creating a VM with disabling boot diagnostics.  : 
Microsoft.Rest.ValidationException: 'Kind' cannot be null.
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.Models.StorageAccountCreateParameters.Validate()
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperations.<BeginCreateWithHttpMessagesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperations.<CreateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperationsExtensions.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.PowerShell.Cmdlets.Compute.Helpers.Storage.StorageAccountsOperationsExtensions.Create(IStorageAccountsOperations operations, String        
resourceGroupName, String accountName, StorageAccountCreateParameters parameters)
   at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.CreateStandardStorageAccount(StorageManagementClient client)`

### Issue script & Debug output

```PowerShell
New-AzVM : Parameter set cannot be resolved using the specified named parameters.
At C:\repos\wellcom-iac\wellcom-mono\build-agent\01.vm-create\02.wellcom-environment-deployment.ps1:78 char:19
+ ...       $vm = New-AzVM -ResourceGroupName $global:resourceGroupName -Lo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzVM], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.Compute.NewAzureVMCommand
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
[DBG]: PS C:\repos\wellcom-iac> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.3     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     5.1.0      Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk...}
Script     4.9.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultMana...
Script     5.1.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add...
Script     6.4.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
```

### Error output

```PowerShell
HistoryId      : 1

Message        : The specified module 'C:\Program Files\DesiredStateConfiguration\1.0.0.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1'  
                 was not loaded because no valid module file was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :
Position       :
HistoryId      : 1

Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Users\lemsa\Documents\WindowsPowerShell\Modules\Az.Compute\5.1.0\Az.Compute.psm1:39 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Users\lemsa\Documents\WindowsPowerShell\Modules\Az.Compute\5.1.0\Az.Compute.psm1:39 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Users\lemsa\Documents\WindowsPowerShell\Modules\Az.Accounts\2.10.3\Az.Accounts.psm1:39 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

13:14:37 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
AzureQoSEvent:  Module: Az.Accounts:2.10.3; CommandName: Resolve-AzError; PSVersion: 5.1.19041.1682; IsSuccess: True; Duration: 00:00:00.4383563
13:14:37 - ResolveError end processing.


[DBG]: PS C:\repos\wellcom-iac>
```

**Comment by RakeshMohanMSFT** [comment]
@lemsa Thank you for reaching out to us, we are looking into it.

**Comment by lemsa** [comment]
Updated the description with information that there is also an issue regarding creating storage account for boot diagnostics when using the New-AzVM command:

`WARNING:` Error occurred when creating storage account for boot diagnostics. Keep creating a VM with disabling boot diagnostics. :
Microsoft.Rest.ValidationException: 'Kind' cannot be null.`

**Comment by lemsa** [comment]
Hi

I see there is a fix for the storage account coming. 
That's good. Thank you :).

Just want to mention if you're not aware of it that there still is another issue related to the use of the "PublicIpSku" parameter as mentioned already in this issue.

**Comment by RakeshMohanMSFT** [comment]
@lemsa I am looking into that as well.

**Comment by lemsa** [comment]
> @lemsa I am looking into that as well.

Thanks :)

**Comment by lemsa** [comment]
Hi @RakeshMohanMSFT 

Any progress on the  "PublicIpSku" parameter which fails?

I see that this issue is now closed and I'm a bit worried it's not looked into...
