### ISSUE TITLE
Get-AzUserAssignedIdentity ignores the -DefaultProfile Subscription

### ISSUE THREAD

**Issue by jreinmilleratmosera** [Azure/azure-powershell#20109]
### Description

In the current version of Get-AzUserAssignedIdentity, the subscription information provided via the -DefaultProfile parameter is ignored. This breaks with the behavior of all other Az commands.
The Subscription must be provided by the -SubscriptionId parameter, otherwise the current Subscription is used.
The documentation indicates that the -SubscriptionId parameter defaults to the results of Get-Context, but ignoring the provided context still feels like a breaking change.

In addition, it appears that the current version of Get-AzUserAssignedIdentity lost the -AzContext alias for -DefaultProfile.

Steps to reproduce

1. Login to Azure and save Azure Context (call this Subscription 1)
2. Switch Azure Context to another Subscription (call this Subscription 2)
3. Run Get-AzUserAssignedIdentity with -DefaultProfile to lookup a UMI in Subscription 1
4. Will error as the command ignores the Subscription passed via -DefaultProfile and uses the current Subscription
5. Only works if the -SubscriptionId parameter is provided

### Issue script & Debug output

```PowerShell
$DebugPreference='Continue'

# Current Context (differs from the Subscription where Get-AzUserAssignedIdentity will be run)
Get-AzContext

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
Development (11a5xxxx-xxxx-xxxx-xxxx-xx… jxxxx@xxxxx.com           Development                                AzureCloud                                055xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx837
DEBUG: 7:41:33 AM - GetAzureRMContextCommand end processing.

# This is the saved context that will be used to run the command.
$context

Name                                     Account                                    SubscriptionName                           Environment                               TenantId
----                                     -------                                    ----------------                           -----------                               --------
TestSubscription (f14fxxxx-xxxx-xxxx-xxxx-x… jxxxx@xxxxx.com           TestSubscription                               AzureCloud                                055xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx837

# This command fails because -SubscriptionId is not provided.
# Does not use intended Subscription.
Get-AzUserAssignedIdentity -ResourceGroupName axxxxxxxxxx0 -name jrcbxxxxxxxxxxxxxxxx6258 -DefaultProfile $context
DEBUG: 7:46:23 AM - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/11a5xxxx-xxxx-xxxx-xxxxxxxxxxf2d7/resourceGroups/axxxxxxxxxx0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258?api-version=2022-01-31-preview
DEBUG: RequestCreated: /subscriptions/11a5xxxx-xxxx-xxxx-xxxxxxxxxxf2d7/resourceGroups/axxxxxxxxxx0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258?api-version=2022-01-31-preview
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/11a5xxxx-xxxx-xxxx-xxxxxxxxxxf2d7/resourceGroups/axxxxxxxxxx0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258?api-version=2022-01-31-preview

Headers:
x-ms-unique-id                : 18
x-ms-client-request-id        : 7ce1f30f-7424-416e-b0eb-3dfe0bb46366
CommandName                   : Get-AzUserAssignedIdentity
FullCommandName               : Get-AzUserAssignedIdentity_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v9.1.0,PSVersion/v7.2.7,Az.ManagedServiceIdentity/1.1.0

Body:



DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 9628e4b5-12d9-4fc8-a9a8-6c6c088a08d6
x-ms-correlation-request-id   : 9628e4b5-12d9-4fc8-a9a8-6c6c088a08d6
x-ms-routing-request-id       : WESTUS2:20221114T154637Z:9628e4b5-12d9-4fc8-a9a8-6c6c088a08d6
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Mon, 14 Nov 2022 15:46:37 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258' under resource group 'axxxxxxxxxx0' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
WARNING: Get-AzUserAssignedIdentity_Get is not found. The most similar Azure PowerShell command is:
        Get-AzUserAssignedIdentity
Get-AzUserAssignedIdentity_Get: The Resource 'Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258' under resource group 'axxxxxxxxxx0' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSResourceNotFoundCloudException: InternalException' from response
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent:  Module: Az.ManagedServiceIdentity:1.1.0; CommandName: Get-AzUserAssignedIdentity; PSVersion: 7.2.7; IsSuccess: False; Duration: 00:00:00.4553389; Exception: InternalException;

# And this will work because SubscriptionId is provided
Get-AzUserAssignedIdentity -ResourceGroupName axxxxxxxxxx0 -name jrcbxxxxxxxxxxxxxxxx6258 -DefaultProfile $context -SubscriptionId f14fxxxx-xxxx-xxxx-xxxx-xxxxxxxx6188
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/f14fxxxx-xxxx-xxxx-xxxx-xxxxxxxx6188/resourceGroups/axxxxxxxxxx0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258?api-version=2022-01-31-preview
DEBUG: RequestCreated: /subscriptions/f14fxxxx-xxxx-xxxx-xxxx-xxxxxxxx6188/resourceGroups/axxxxxxxxxx0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258?api-version=2022-01-31-preview
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/f14fxxxx-xxxx-xxxx-xxxx-xxxxxxxx6188/resourceGroups/axxxxxxxxxx0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258?api-version=2022-01-31-preview

Headers:
x-ms-unique-id                : 19
x-ms-client-request-id        : 7825c5e6-cec6-4aea-b340-e53cafd7f04f
CommandName                   : Get-AzUserAssignedIdentity
FullCommandName               : Get-AzUserAssignedIdentity_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v9.1.0,PSVersion/v7.2.7,Az.ManagedServiceIdentity/1.1.0

Body:



DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id               : a86d90ca-c058-43d7-8607-fbc976304c43
x-ms-correlation-request-id   : a86d90ca-c058-43d7-8607-fbc976304c43
x-ms-routing-request-id       : WESTUS2:20221114T154749Z:a86d90ca-c058-43d7-8607-fbc976304c43
X-Content-Type-Options        : nosniff
Date                          : Mon, 14 Nov 2022 15:47:48 GMT

Body:
{
  "id": "/subscriptions/f14fxxxx-xxxx-xxxx-xxxx-xxxxxxxx6188/resourcegroups/axxxxxxxxxx0/providers/Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258",
  "name": "jrcbxxxxxxxxxxxxxxxx6258",
  "type": "Microsoft.ManagedIdentity/userAssignedIdentities",
  "location": "westus",
  "tags": {},
  "properties": {
    "tenantId": "055xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx837",
    "principalId": "3458xxxx-xxxx-xxxx-xxxx-xxxxxxxxe16f",
    "clientId": "a9d7xxxx-xxxx-xxxx-xxxx-xxxxxxxx001e"
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:

DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent:  Module: Az.ManagedServiceIdentity:1.1.0; CommandName: Get-AzUserAssignedIdentity; PSVersion: 7.2.7; IsSuccess: True; Duration: 00:00:00.4501408
Location Name                     ResourceGroupName
-------- ----                     -----------------
westus   jrcbxxxxxxxxxxxxxxxx6258 axxxxxxxxxx0

# Maybe related, the -AzContext alias for -DefaultProfile is missing
Get-AzUserAssignedIdentity -ResourceGroupName axxxxxxxxxx0 -name jrcbxxxxxxxxxxxxxxxx6258 -AzContext $context -SubscriptionId f14fxxxx-xxxx-xxxx-xxxx-xxxxxxxx6188
Get-AzUserAssignedIdentity: A parameter cannot be found that matches parameter name 'AzContext'.
```

### Environment data

```PowerShell
$Psversiontable

Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     1.1.0                 Az.ManagedServiceIdentity           {Get-AzFederatedIdentityCredentials, Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity, Get-AzUserAssignedIdentityAssociatedResource…}
Script     6.4.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
DEBUG: 8:05:18 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 8:05:18 AM - using account id 'jxxxx@xxxxx.com'...
DEBUG: 8:05:18 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 90

Message        : A parameter cannot be found that matches parameter name 'AzContext'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzUserAssignedIdentity}
Line           : Get-AzUserAssignedIdentity -ResourceGroupName axxxxxxxxxx0 -name jrcbxxxxxxxxxxxxxxxx6258 -AzContext $context -SubscriptionId f14fxxxx-xxxx-xxxx-xxxx-xxxxxxxx6188
Position       : At line:1 char:91
                 + … upName axxxxxxxxxx0 -name jrcbxxxxxxxxxxxxxxxx6258 -AzContext $contex …
                 +                                                      ~~~~~~~~~~
HistoryId      : 90


   HistoryId: 87

Message        : [ResourceNotFound] : The Resource 'Microsoft.ManagedIdentity/userAssignedIdentities/jrcbxxxxxxxxxxxxxxxx6258' under resource group 'axxxxxxxxxx0' was not found. For more details please go to
                 https://aka.ms/ARMResourceNotFoundFix
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzUserAssignedIdentity_Get}
Line           : Get-AzUserAssignedIdentity -ResourceGroupName axxxxxxxxxx0 -name jrcbxxxxxxxxxxxxxxxx6258 -DefaultProfile $context
Position       : At line:1 char:1
                 + Get-AzUserAssignedIdentity -ResourceGroupName axxxxxxxxxx0 -name jrcb …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 87
```

**Comment by dingmeng-xue** [comment]
@jreinmilleratmosera , thanks for contacting us. New generation of Azure PowerShell doesn't rely on default profile or context. It is breaking change. So we upgrade modules to new design gradually. `Az.ManagedServiceIdentity` starts using this design since 1.0.0. This change based on what we had learned from Azure PowerShell users. if user can access multiple subscriptions, switching subscriptions was incontinent. User hopes they can set subscription id directly. It is also matching API design.

**Comment by jreinmilleratmosera** [comment]
/unresolve Thanks for the information. Can you direct me to where this design change is documented? I reviewed all of the release notes and KBs before posting the bug, and couldn't find anything, so it would be helpful to review the documentation to prepare for this change impacting other areas of our code. Thanks.

**Comment by dingmeng-xue** [comment]
HI @jreinmilleratmosera , the design of Az.ManagedServiceIdentity has been changed since preview version 0.8.0. The module under preview indicts it may introduce breaking change in any release according to user's feedback. Preview version is not included into Az package. As the result, it is not mentioned in migration guide of Az. Currently, its version is 1.1.0. It is stable version and packaged in Az. Its cmdlet API won't change frequently in future.

**Comment by jreinmilleratmosera** [comment]
@dingmeng-xue That is disappointing to learn. I don't see this change listed in any release notes for Az.ManagedServiceIdentity or the Microsoft.ManagedIdentity API. It would seem that at least the page on using Contexts should be updated to reflect this new design as it is no longer accurate. https://learn.microsoft.com/en-us/powershell/azure/context-persistence

**Comment by dingmeng-xue** [comment]
Sorry for that. That doc is still valid to classic modules such as Az.Compute, Az.Storage, and Az.Network, We should improve it and let user know the difference. 

@mikefrobbins , @dcaro @Alex-wdy , FYI

**Comment by dcaro** [comment]
@jreinmilleratmosera we cannot transfer this issue to the documentation team since those are two different github organization. Can you please open an issue about the page:
From https://learn.microsoft.com/en-us/powershell/azure/context-persistence, open an issue for "this page" and link to this issue.
![image](https://user-images.githubusercontent.com/6418658/205538733-3f286b32-2ac4-4564-99bb-9a6dbf123c55.png)

Thanks

**Comment by jreinmilleratmosera** [comment]
New issue submitted as requested.
https://github.com/MicrosoftDocs/azure-docs-powershell/issues/2397

Jeremiah

**Comment by dingmeng-xue** [comment]
@jreinmilleratmosera , thanks for your support. Close this issue now.
