### ISSUE TITLE
Get-AzVM and Get-AzDisk returns an error with or without parameters

### ISSUE THREAD

**Issue by ezam-ws** [Azure/azure-powershell#20113]
### Description

Running Get-AzVm returns this error: 
Get-AzDisk: GenericArguments[0], 'Microsoft.Azure.Commands.Compute.Automation.Models.PSVirtualMachineScaleSetExtension', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.

I also specified the resource group name or a known VM and the error is the same.

### Issue script & Debug output

```PowerShell
Get-AzVM: GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])'
violates the constraint of type 'T'.
DEBUG: AzureQoSEvent: CommandName - Get-AzVM; IsSuccess - False; Duration - 00:00:00.8223134; Exception - GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.;
DEBUG: Finish sending metric.
DEBUG: 17:15:47 - GetAzureVMCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.2.8                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount…}
Script     4.12.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     1.1.0                 Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzMaintenanceConfiguration, Get…
Script     3.5.0                 Az.Resources                        {Add-AzADGroupMember, Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzADAppCreden…
```

### Error output

```PowerShell
HistoryId: 51

Message        : GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
StackTrace     :    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
                    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2 <>h__TransparentIdentifier1)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
                    at System.Linq.Enumerable.UnionIterator`1.FillSet()
                    at System.Linq.Enumerable.UnionIterator`1.ToArray()
                    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
                    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
                    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
                    at System.Lazy`1.CreateValue()
                    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options)
                    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)
                    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
                    at AutoMapper.MapperConfiguration.Seal()
                    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
                    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.Initialize()
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.get_Mapper()
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.GetPowerstate(AzureOperationResponse`1 vmListResult, List`1 psResultListStatus)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.ReturnListVMObject(AzureOperationResponse`1 vmListResult, Func`4 listNextFunction)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.<ExecuteCmdlet>b__30_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzVM}
Line           : get-azvm >> 'D:\dev\report\get-azvm-output.txt'
Position       : At line:1 char:1
                 + get-azvm >> 'D:\dev\report\get-azvm-output.txt'
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 51

Message        : Method System.Linq.Enumerable.MaxInteger: type argument 'Microsoft.Azure.Management.Compute.Models.VirtualMachine' violates the constraint of type parameter 'T'.
StackTrace     :    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
Exception      : System.Security.VerificationException
InvocationInfo : {Get-AzVM}
Line           : get-azvm >> 'D:\dev\report\get-azvm-output.txt'
Position       : At line:1 char:1
                 + get-azvm >> 'D:\dev\report\get-azvm-output.txt'
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 51


   HistoryId: 50

Message        : GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
StackTrace     :    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
                    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2 <>h__TransparentIdentifier1)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
                    at System.Linq.Enumerable.UnionIterator`1.FillSet()
                    at System.Linq.Enumerable.UnionIterator`1.ToArray()
                    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
                    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
                    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
                    at System.Lazy`1.CreateValue()
                    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options)
                    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)
                    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
                    at AutoMapper.MapperConfiguration.Seal()
                    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
                    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.Initialize()
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.get_Mapper()
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.GetPowerstate(AzureOperationResponse`1 vmListResult, List`1 psResultListStatus)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.ReturnListVMObject(AzureOperationResponse`1 vmListResult, Func`4 listNextFunction)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.<ExecuteCmdlet>b__30_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzVM}
Line           : get-azvm | out-file -FilePath 'D:\dev\report\get-azvm-output.txt'
Position       : At line:1 char:1
                 + get-azvm | out-file -FilePath 'D:\dev\report\get-azvm-output.txt'
                 + ~~~~~~~~
HistoryId      : 50

Message        : Method System.Linq.Enumerable.MaxInteger: type argument 'Microsoft.Azure.Management.Compute.Models.VirtualMachine' violates the constraint of type parameter 'T'.
StackTrace     :    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
Exception      : System.Security.VerificationException
InvocationInfo : {Get-AzVM}
Line           : get-azvm | out-file -FilePath 'D:\dev\report\get-azvm-output.txt'
Position       : At line:1 char:1
                 + get-azvm | out-file -FilePath 'D:\dev\report\get-azvm-output.txt'
                 + ~~~~~~~~
HistoryId      : 50


   HistoryId: 49

Message        : GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
StackTrace     :    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
                    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2 <>h__TransparentIdentifier1)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
                    at System.Linq.Enumerable.UnionIterator`1.FillSet()
                    at System.Linq.Enumerable.UnionIterator`1.ToArray()
                    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
                    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
                    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
                    at System.Lazy`1.CreateValue()
                    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options)
                    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)
                    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
                    at AutoMapper.MapperConfiguration.Seal()
                    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
                    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.Initialize()
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.get_Mapper()
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.GetPowerstate(AzureOperationResponse`1 vmListResult, List`1 psResultListStatus)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.ReturnListVMObject(AzureOperationResponse`1 vmListResult, Func`4 listNextFunction)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.<ExecuteCmdlet>b__30_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzVM}
Line           : get-azvm
Position       : At line:1 char:1
                 + get-azvm
                 + ~~~~~~~~
HistoryId      : 49

Message        : Method System.Linq.Enumerable.MaxInteger: type argument 'Microsoft.Azure.Management.Compute.Models.VirtualMachine' violates the constraint of type parameter 'T'.
StackTrace     :    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
Exception      : System.Security.VerificationException
InvocationInfo : {Get-AzVM}
Line           : get-azvm
Position       : At line:1 char:1
                 + get-azvm
                 + ~~~~~~~~
HistoryId      : 49
```

**Comment by RakeshMohanMSFT** [comment]
@ezam-ws Thank you for reaching out, we are looking into it.

**Comment by dingmeng-xue** [comment]
@ezam-ws , please help to verify engineering build mentioned by https://github.com/Azure/azure-powershell/issues/18721#issuecomment-1314864891

I believe it is the same issue. Please track #18721 .

**Comment by ezam-ws** [comment]
Will do, thanks.

Walt Sutton III
***@***.***
865.548.4710

**Comment by s890542** [comment]
Getting this error with : New-AzLoadBalancer `
     |            ~~~~~~~~~~~~~~~~~~~~
     | GenericArguments[0],
     | 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T
     | MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the
     | constraint of type 'T'.
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
