### ISSUE TITLE
Get-AzSynapsePipeline fails when Data Flow activity uses expression to define staging area

### ISSUE THREAD

**Issue by BJarkowski** [Azure/azure-powershell#20186]
### Description

Both Get-AzSynapsePipeline and Set-AzSynapsePipeline fail when Data Flow activity in the pipeline uses expression to define staging area.
Error: Exception has been thrown by the target of an invocation
The requested operation requires an element of type 'String', but the target element has type 'Object'.

### Issue script & Debug output

```PowerShell
Pipeline definition:

{
    "name": "Pipeline 1",
    "properties": {
        "activities": [
            {
                "name": "Data flow1",
                "type": "ExecuteDataFlow",
                "dependsOn": [],
                "policy": {
                    "timeout": "0.12:00:00",
                    "retry": 0,
                    "retryIntervalInSeconds": 30,
                    "secureOutput": false,
                    "secureInput": false
                },
                "userProperties": [],
                "typeProperties": {
                    "dataflow": {
                        "referenceName": "Test",
                        "type": "DataFlowReference"
                    },
                    "staging": {
                        "linkedService": {
                            "referenceName": "ls_linked",
                            "type": "LinkedServiceReference"
                        },
                        "folderPath": {
                            "value": "@pipeline().parameters.p_path",
                            "type": "Expression"
                        }
                    },
                    "integrationRuntime": {
                        "referenceName": "Azure-IR",
                        "type": "IntegrationRuntimeReference"
                    },
                    "traceLevel": "Fine"
                }
            }
        ],
        "parameters": {
            "p_path": {
                "type": "string"
            }
        },
        "folder": {
            "name": "ADMD"
        },
        "annotations": []
    }
}

Publish the pipeline and use: Get-AzSynapsePipeline -WorkspaceObject $SynapseWorkspace -Name "Pipeline 1"

Error:
DEBUG: 14:12:44 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzSynapsePipeline: The requested operation requires an element of type 'String', but the target element has type 'Object'.
DEBUG: 14:12:44 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Synapse:2.0.0; CommandName: Get-AzSynapsePipeline; PSVersion: 7.3.0; IsSuccess: False; Duration: 00:00:00.3956857; Exception: The requested operation requires an element of type 'String', but the target element has type 'Object'.;
DEBUG: 14:12:44 - GetAzureSynapsePipeline end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.1.0                 Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTriggerSubscription, Clear-AzSynapseSqlPoolVulnerabilityAssessmentRuleBaseline, Convert-AzSynapseSqlPoolVulnerabilityAssessmentScan…}
```

### Error output

```PowerShell
Message        : The requested operation requires an element of type 'String', but the target element has type 'Object'.
StackTrace     :    at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
                    at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
                    at Azure.Analytics.Synapse.Artifacts.Models.DataFlowStagingInfo.DeserializeDataFlowStagingInfo(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.Models.ExecuteDataFlowActivity.DeserializeExecuteDataFlowActivity(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.Models.Activity.DeserializeActivity(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.Models.PipelineResource.DeserializePipelineResource(JsonElement element)
                    at Azure.Analytics.Synapse.Artifacts.PipelineRestClient.GetPipeline(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
                    at Azure.Analytics.Synapse.Artifacts.PipelineClient.GetPipeline(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Synapse.Models.SynapseAnalyticsArtifactsClient.GetPipeline(String pipelineName)
                    at Microsoft.Azure.Commands.Synapse.GetAzureSynapsePipeline.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.InvalidOperationException
InvocationInfo : {Get-AzSynapsePipeline}
Line           : Get-AzSynapsePipeline -WorkspaceObject $SynapseWorkspace -Name "Pipeline 1"
Position       : At line:1 char:1
                 + Get-AzSynapsePipeline -WorkspaceObject $SynapseWorkspace -Name "Pipel …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7
```

**Comment by RakeshMohanMSFT** [comment]
@BJarkowski Thank you for reaching out, we are looking into it.

**Comment by yanjungao718** [comment]
Hi @BJarkowski, this issue is caused by wrong type definition for folder path, now it does not accept Expression type but only String type, we will fix it asap.

**Comment by aanhalzer** [comment]
This remains an issue. Get-AzSynapsePipeline is failing on pipelines with dataflows and expressions. The command below is with Az.Synapse v 2.1.0
<img width="765" alt="image" src="https://user-images.githubusercontent.com/17557336/204655086-4e0cc68f-8e88-44e4-9077-5c1c5ecb568d.png">

When a command is run only providing the WorkspaceName parameter, since the workspace contains a Pipeline with Dataflows and expressions, it fails.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/17557336/204655258-bb55a81d-eb2e-401b-9719-8aa3dc9fe599.png">

**Comment by yanjungao718** [comment]
> I believe this remains an issue. Get-AzSynapsePipeline is failing on pipelines with dataflows and expressions. The command below is with Az.Synapse v 2.1.0 <img alt="image" width="765" src="https://user-images.githubusercontent.com/17557336/204655086-4e0cc68f-8e88-44e4-9077-5c1c5ecb568d.png">

>   **Above  issue is now fixing**.

> When a command is run only providing the WorkspaceName parameter, since the workspace contains a Pipeline with Dataflows and expressions, it fails. <img alt="image" width="759" src="https://user-images.githubusercontent.com/17557336/204655258-bb55a81d-eb2e-401b-9719-8aa3dc9fe599.png">

> Submitted another ticket #20324

>  **Let's discuss this new issue in your new ticket.**
