### ISSUE TITLE
New-AzADAppCredential Property Key expects System.Byte Value instead of System.String Base64

### ISSUE THREAD

**Issue by pheeling** [Azure/azure-powershell#20183]
### Description

When creating new app credential from Powershell 7.2 Az.Resources 6.4.1. For certificate it expects in the properties a System.Byte value and not System.String Base64 encoded string. The example is wrongly written. 

### Issue script & Debug output

```PowerShell
$cert = New-Object System.Security.Cryptography.X509Certificates.X509Certificate("$pfxExportPath", $tenantCertRequirements.certPwd)
$keyValue = [System.Convert]::ToBase64String($cert.GetRawCertData())

New-Object -TypeName "Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Models.ApiV10.MicrosoftGraphKeyCredential" `
                                    -Property @{'Key' = $keyValue ;
                                    'Usage'       = 'Verify';
                                    'Type'        = 'AsymmetricX509Cert'
                                };
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clea… 
Script     6.4.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDen…
```

### Error output

```PowerShell
Message        : Exception setting "Key": "Cannot convert value "<base64stringfromcertificate>" to type "System.Byte[]". Error:  
                 "Cannot convert value "<base64stringfromcertificate>" to type "System.Byte". Error: "Input string was not in a  
                 correct format."""
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception
                 exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                    at CallSite.Target(Closure , CallSite , Object , Object )
                    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)     
Exception      : System.Management.Automation.SetValueInvocationException
InvocationInfo : {}
Line           : $objectcred.Key = $keyValue
Position       : At line:1 char:1
                 + $objectcred.Key = $keyValue
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by dingmeng-xue** [comment]
@pheeling , according to API description, it seems need a bytes array representing base64 encoded. Please try 
```
$keyValue = [System.Text.Encoding]::UTF8.GetBytes([System.Convert]::ToBase64String($cert.GetRawCertData()))
```

@VeryEarly , please look into it as well.
