### ISSUE TITLE
Malformed URI used in Az.Monitor Remove-AzDataCollectionRuleAssociation cmdlet

### ISSUE THREAD

**Issue by OneAndOnlySeabass** [Azure/azure-powershell#20207]
### Description

We tried using the cmdlet Remove-AzDataCollectionRuleAssociation from the Az.Monitor module, but it threw a Bad Request error when trying this operation. From the debug logging, we discovered that the absolute request URI is malformed:
`https://management.azure.com//subscriptions/[sub-id]/resourcegroups/[rg-name]/providers/microsoft.compute/virtualmachines/[vm-name]/providers/microsoft.insights/datacollectionruleassocia
tions/[dcr-association-name]/providers/Microsoft.Insights/dataCollectionRuleAssociations/[dcr-association-name]?api-version=2021-04-01`

Where, according to the [REST API documentation](https://learn.microsoft.com/en-us/rest/api/monitor/data-collection-rule-associations/delete?tabs=HTTP), it should be formed like this:
`https://management.azure.com//subscriptions/[sub-id]/resourcegroups/[rg-name]/providers/microsoft.compute/virtualmachines/[vm-name]/providers/microsoft.insights/datacollectionruleassocia
tions/[dcr-association-name]?api-version=2021-04-01`

When we make a DELETE REST request according to the above, the data collection rule association is successfully removed. Could you fix the URI forming for this cmdlet?

### Issue script & Debug output

```PowerShell
PS > $DebugPreference='Continue'                                 
PS > $assocId = '/subscriptions/$subId/resourcegroups/$rgName/providers/microsoft.compute/virtualmachines/$vmName/providers/microsoft.insights/datacollectionruleassocia
>> tions/$dcrAssociationName'
PS > Remove-AzDataCollectionRuleAssociation -AssociationId $assocId
DEBUG: 11:45:27 - RemoveAzureRmDataCollectionRuleAssociationCommand begin processing with ParameterSet 'ByResourceId'.
DEBUG: 11:45:27 - using account id '***@***.nl'...
DEBUG: 11:45:27 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: 11:45:27 - *** The namespace for all the model classes will change from Microsoft.Azure.Management.Monitor.Management.Models to Microsoft.Azure.Management.Monitor.Models in future releases.
WARNING: 11:45:27 - *** The namespace for output classes will be uniform for all classes in future releases to make it independent of modifications in the model classes.
DEBUG: [Common.Authentication]: Authenticating using Account: '***@***.nl', environment: 'AzureCloud', tenant: '***'
DEBUG: 11:45:27 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'***', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'***@***.nl'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - d186ed4a-2fe9-401a-b01d-ac3269289a7c] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - d186ed4a-2fe9-401a-b01d-ac3269289a7c] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - d186ed4a-2fe9-401a-b01d-ac3269289a7c] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - d186ed4a-2fe9-401a-b01d-ac3269289a7c] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - d186ed4a-2fe9-401a-b01d-ac3269289a7c] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16] Returning 1 accounts
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - 57b40c22-96ec-4050-9e25-34df071c2d1a] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(57b40c22-96ec-4050-9e25-34df071c2d1a)
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - 57b40c22-96ec-4050-9e25-34df071c2d1a] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - 57b40c22-96ec-4050-9e25-34df071c2d1a] LoginHint provided: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - 57b40c22-96ec-4050-9e25-34df071c2d1a] Account provided: True
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - 57b40c22-96ec-4050-9e25-34df071c2d1a] ForceRefresh: False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - 57b40c22-96ec-4050-9e25-34df071c2d1a] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 57b40c22-96ec-4050-9e25-34df071c2d1a
UserAssertion set: False
LongRunningOboCacheKey set: False

DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.16 - 57b40c22-96ec-4050-9e25-34df071c2d1a] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.19 - 57b40c22-96ec-4050-9e25-34df071c2d1a] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.19 - 57b40c22-96ec-4050-9e25-34df071c2d1a] Access token is not expired. Returning the found cache entry. [Current time (11/22/2022 10:45:27) - Expiration Time (11/22/2022 11:14:31 +00:00) - Extended Expiration Time (11/22/2022 11:14:31 +00:00)]
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.19 - 57b40c22-96ec-4050-9e25-34df071c2d1a] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.19 - 57b40c22-96ec-4050-9e25-34df071c2d1a] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.19 - 57b40c22-96ec-4050-9e25-34df071c2d1a] Fetched access token from host login.microsoftonline.com. 
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.19 - 57b40c22-96ec-4050-9e25-34df071c2d1a] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.0 Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 [11/22 10:45:27.19 - 57b40c22-96ec-4050-9e25-34df071c2d1a]  AT expiration time: 22/11/2022 11:14:31 +00:00, scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default source Cache from login.microsoftonline.com appHashCode 59271282
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-11-22T11:14:31.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '***', UserId: '***@***.nl'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
DELETE

Absolute Uri:
https://management.azure.com//subscriptions/[sub-id]/resourcegroups/[rg-name]/providers/microsoft.compute/virtualmachines/[vm-name]/providers/microsoft.insights/datacollectionruleassocia
tions/[dcr-association-name]/providers/Microsoft.Insights/dataCollectionRuleAssociations/[dcr-association-name]?api-version=2021-04-01

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 7e87d1a1-f287-4a9b-af3d-df0949c0912d

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Server                        : Microsoft-HTTPAPI/2.0
Date                          : Tue, 22 Nov 2022 10:45:26 GMT
Connection                    : close

Body:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>



DEBUG: 11:45:27 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Remove-AzDataCollectionRuleAssociation: Exception type: ErrorResponseCommonV2Exception, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseCommonV2Exception: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.DataCollectionRuleAssociationsOperations.DeleteWithHttpMessagesAsync(String resourceUri, String associationName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Insights.DataCollectionRules.RemoveAzureRmDataCollectionRuleAssociationCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
DEBUG: 11:45:27 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent: Module: Az.Monitor:3.0.1; CommandName: Remove-AzDataCollectionRuleAssociation; PSVersion: 7.3.0; IsSuccess: False; Duration: 00:00:00.0903139; Exception: Exception type: ErrorResponseCommonV2Exception, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseCommonV2Exception: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.DataCollectionRuleAssociationsOperations.DeleteWithHttpMessagesAsync(String resourceUri, String associationName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Insights.DataCollectionRules.RemoveAzureRmDataCollectionRuleAssociationCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null;
DEBUG: Finish sending metric.
DEBUG: 11:45:27 - RemoveAzureRmDataCollectionRuleAssociationCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.2.1                 Az.Monitor                          {Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2, Add-AzWebtestAlertRule…}
```

### Error output

```PowerShell
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 2

Message        : Exception type: ErrorResponseCommonV2Exception, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseCommonV2Exception: Operation returned an 
                 invalid status code 'BadRequest'
                    at Microsoft.Azure.Management.Monitor.DataCollectionRuleAssociationsOperations.DeleteWithHttpMessagesAsync(String resourceUri, String associationName, 
                 Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Insights.DataCollectionRules.RemoveAzureRmDataCollectionRuleAssociationCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Remove-AzDataCollectionRuleAssociation}
Line           : Remove-AzDataCollectionRuleAssociation -AssociationId $assocId
Position       : At line:1 char:1
                 + Remove-AzDataCollectionRuleAssociation -AssociationId $assocId
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.DataCollectionRuleAssociationsOperations.DeleteWithHttpMessagesAsync(String resourceUri, String associationName, 
                 Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Commands.Insights.DataCollectionRules.RemoveAzureRmDataCollectionRuleAssociationCommand.ProcessRecordInternal()
                    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Monitor.Models.ErrorResponseCommonV2Exception
InvocationInfo : {Remove-AzDataCollectionRuleAssociation}
Line           : Remove-AzDataCollectionRuleAssociation -AssociationId $assocId
Position       : At line:1 char:1
                 + Remove-AzDataCollectionRuleAssociation -AssociationId $assocId
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by dingmeng-xue** [comment]
It's a bug in below code. It analyze resource id in case sensitive way. It should be insensitive. 
https://github.com/Azure/azure-powershell/blob/9c9a4eaa2b64a23629aa6ede13dee00be2abc756/src/Monitor/Monitor/DataCollectionRules/RemoveAzureRmDataCollectionRuleAssociationCommand.cs#L91


Before we fix it, please construct id as
```
$assocId = '/subscriptions/$subId/resourcegroups/$rgName/providers/microsoft.compute/virtualmachines/$vmName//providers/Microsoft.Insights/dataCollectionRuleAssociations/$dcrAssociationName'
```
