### ISSUE TITLE
non-recoverable issue when running AzureRm PowerShell cmd in multiple runsapces

### ISSUE THREAD

**Issue by sunbinzhu** [Azure/azure-powershell#2021]
Since the current AzureRm PowerShell only supports to Get VM status, Start/Stop/Restart/Deallocate VM one by one. I have to use runspaces to execute the corresponding Azure PowerShell commands(Get-AzureRmVM, Start-AzureRmVM, Stop-AzureRmVM) in multiple threads, and I found that some exceptions thrown during the multiple threading execution. The last error (Error 3) is a non-recoverable error, when the error occurs, the powershell console fails to execute any AzureRM commands with this same error. I also pasted the script to reproduce this issue, the more VMs in the resource group, the more likely to reproduce the errors.

**ERROR 1:** 
System.Management.Automation.RuntimeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.RemoveAt(Int32 index)
   at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet..ctor()
   at Microsoft.Azure.Commands.Compute.GetAzureVMCommand..ctor()
   at lambda_method(Closure )
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)
   --- End of inner exception stack trace ---
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at CallSite.Target(Closure , CallSite , Object , Object )

**ERROR 2:**
System.Management.Automation.RuntimeException: Collection was modified;
enumeration operation may not execute. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.GetCustomHandlers()
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateArmClient[TClient](AzureContext context, Endpoint endpoint)
   at Microsoft.Azure.Commands.Compute.VirtualMachineBaseCmdlet.get_VirtualMachineClient()
   at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.<ExecuteCmdlet>b__0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at CallSite.Target(Closure , CallSite , Object , Object )

**ERROR 3:**
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Specialized.OrderedDictionary.IndexOfKey(Object key)
   at System.Collections.Specialized.OrderedDictionary.Remove(Object key)
   at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet..ctor()
   at Microsoft.Azure.Commands.Compute.GetAzureVMCommand..ctor()
   at lambda_method(Closure )
   at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)

**The script to repro this issue**
function GetVMsStatus
{
    param 
    (
        [Parameter(Mandatory=$true)]
        [string] $ResourceGroup
    )

    $vms = Get-AzureRmVM -ResourceGroupName $ResourceGroup
    $ScriptBlock = {
        param($resourceGroup, $name)
        Get-AzureRmVM -ResourceGroupName $resourceGroup -Name $name -Status
    }
    $InitialSessionState = [System.Management.Automation.Runspaces.InitialSessionState]::CreateDefault()
    [void]$InitialSessionState.ImportPSModule("AzureRm.Compute")

    $initScriptStr = '$ErrorActionPreference = "Stop";'
    $RunspacePool = [RunspaceFactory]::CreateRunspacePool(1, 30, $InitialSessionState, $Host)
    $RunspacePool.CleanupInterval = [timespan]::FromMinutes(2)
    $RunspacePool.Open()
    $pshJobs = @()
    foreach($vm in $vms)
    {
        $ps = [powershell]::Create()
        [void]$ps.AddScript($initScriptStr)
        [void]$ps.AddScript($ScriptBlock).AddArgument($ResourceGroup).AddArgument($vm.Name)
        $ps.RunspacePool = $RunspacePool
        $pshJobs += New-Object PSObject -Property @{
            Pipe = $ps
            Result = $ps.BeginInvoke()
        }        
    }
        
    ForEach ($pshJob in $pshJobs)
    {
        try
        {
            $results += $pshJob.Pipe.EndInvoke($pshJob.Result)
        }
        catch
        {
            $ex = $_.Exception
            if($ex.InnerException -ne $null)
            {
                $ex = $ex.InnerException
            }
            
            Write-Host "$ex"
        }
        $pshJob.Pipe.Dispose()
        $pshJob.Pipe = $null
    }

    $RunspacePool.Dispose()
    return $results
}

$vmStatus = GetVMsStatus -ResourceGroup theresourcegroupname

**Comment by markcowl** [comment]
@singhkay can you take a look?

**Comment by sunbinzhu** [comment]
I got a similar error in Azure PowerShell (**Classic mode**) when trying to run Get-AzureVM in multiple runspaces, So it is not an ARM particular issue, but a general issue in Azure PowerShell.

**ERROR**: 
System.Management.Automation.RuntimeException: Item has already been added. Key in dictionary: 'Microsoft.WindowsAzure.Commands.Common.CmdletInfoHandler'  Key being added: 'Microsoft.WindowsAzure.Commands.Common.CmdletInfoHandler' ---> System.ArgumentException: Item has already been added. Key in dictionary: 'Microsoft.WindowsAzure.Commands.Common.CmdletInfoHandler'  Key being added: 'Microsoft.WindowsAzure.Commands.Common.CmdletInfoHandler'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Specialized.OrderedDictionary.set_Item(Object key, Object value)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.AddHandler[T](T handler) in d:\workspace\powershell-publish\src\Common\Commands.Common.Authentication\Factories\ClientFactory.cs:line 265
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing() in d:\workspace\powershell-publish\src\Common\Commands.Common\AzurePSCmdlet.cs:line 269
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at CallSite.Target(Closure , CallSite , Object , Object )

**Comment by sunbinzhu** [comment]
And the fatal error also reproduced in classic mode.
**ERROR 3**
System.Management.Automation.RuntimeException: Object reference not setto an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Specialized.OrderedDictionary.IndexOfKey(Object key)
   at System.Collections.Specialized.OrderedDictionary.set_Item(Object key, Object value)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.AddHandler[T](T handler) in d:\workspace\powershell-publish\src\Common\Commands.Common.Authentication\Factories\ClientFactory.cs:line 265
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing() in d:\workspace\powershell-publish\src\Common\Commands.Common\AzurePSCmdlet.cs:line 269
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
   --- End of inner exception stack trace ---
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at CallSite.Target(Closure , CallSite , Object , Object )

**Comment by singhkay** [comment]
@huangpf @hyonholee Can you take a look at if the cmdlets can support runspaces? 

@sunbinzhu Are you seeing this just with VM cmdlets or other Azure cmdlets as well?

**Comment by huangpf** [comment]
The error comes from AzurePSCmdlet.cs. +@markcowl & @hovsepm

**Comment by sunbinzhu** [comment]
@singhkay I just tried VM cmdlets, but it shall be a general issue. you can easily modify my script to try any other cmdlets.

**Comment by singhkay** [comment]
@markcowl Can you take a look at @huangpf's suggestion that this comes from base cmdlet?

**Comment by kennyqiu** [comment]
I saw this exception a lot too. Any update on this topic?

**Comment by markcowl** [comment]
Note, this is identical to this issue: https://github.com/Azure/azure-powershell/issues/2701  Which is planned for this release.  Closing as a duplicate.
