### ISSUE TITLE
New-AzBotService 

### ISSUE THREAD

**Issue by ThatDodoBird** [Azure/azure-powershell#20373]
### Description

Cannot create a new bot with the `New-AzBotService` command. When running the command it seems error and the error seems to state that the `-ApplicationSecret` flag is needed. However, the [examples and documentations](https://learn.microsoft.com/en-us/powershell/module/az.botservice/new-azbotservice?view=azps-9.1.0) on this command suggest that only the `-ApplicationId` is needed.

### Issue script & Debug output

```PowerShell
$bot = New-AzBotService -ApplicationId $appInfo.AppId -Name $botName -ResourceGroupName $resourceGroupName
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Linux 5.10.124-linuxkit #1 SMP Thu Jun 30 08:19:10 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzCo…
Script     0.4.0                 Az.BotService                       {Export-AzBotServiceApp, Get-A…
Script     6.4.1                 Az.Resources                        {Export-AzResourceGroup, Expor…
```

### Error output

```PowerShell
Message        : Cannot bind argument to parameter 'SecureString' because it is null.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.Runspaces.Pipeline.Invoke()
                    at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exc
                 eption& exceptionThrown, ExecutionOptions options)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Unprotect-SecureString.ps1}
Line           :                 $AppSecret = . "$PSScriptRoot/../utils/Unprotect-SecureString.ps1" 
                 $ApplicationSecret
                 
Position       : At /home/user/.local/share/powershell/Modules/Az.BotService/0.4.0/custom/New-AzBotS
                 ervice.ps1:226 char:84
                 + … $PSScriptRoot/../utils/Unprotect-SecureString.ps1" $ApplicationSecret
                 +                                                      ~~~~~~~~~~~~~~~~~~
HistoryId      : 27
```

**Comment by RakeshMohanMSFT** [comment]
@ThatDodoBird Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@ThatDodoBird We are unable to reproduce this issue at our end. 
![image](https://user-images.githubusercontent.com/49954584/205965988-17bd85d5-fce7-4bc5-b541-e1d7573d200a.png)
Can you please try upgrading to latest version of Az.BotService to 0.5.0? and retry

**Comment by ThatDodoBird** [comment]
Works with the module update - thank you very much
