### ISSUE TITLE
Get-AzVM fails with GenericArguments error

### ISSUE THREAD

**Issue by zanedp** [Azure/azure-powershell#20379]
### Description

When using Get-AzVM, this error message is produced:

    PS> Get-AzVM -ResourceGroupName "resource-group" -Name "my-vm"
    Get-AzVM: GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.

### Issue script & Debug output

```PowerShell
PS> Get-AzVM -ResourceGroupName "<redacted>" -Name "<redacted>"
DEBUG: 3:12:11 PM - GetAzureVMCommand begin processing with ParameterSet 'DefaultParamSet'.
DEBUG: 3:12:11 PM - using account id '<redacted@redacted.com>'...
DEBUG: [Common.Authentication]: Authenticating using Account: '<redacted@redacted.com>', environment: 'AzureCloud', tenant: '<redacted>'
DEBUG: 3:12:11 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'<redacted>', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'<redacted@redacted.com>'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11] Found 2 cache accounts and 0 broker accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11] Returning 2 accounts
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] MSAL MSAL.NetCore with assembly version '4.30.1.0'. CorrelationId(d663cad4-40ba-4717-a86f-07b2b1aec3c8)
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] === AcquireTokenSilent Parameters ===
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] LoginHint provided: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] Account provided: True
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] ForceRefresh: False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - d663cad4-40ba-4717-a86f-07b2b1aec3c8

DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] === Token Acquisition (SilentRequest) started:

        Authority Host: login.microsoftonline.com
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] Azure region was not configured or could not be discovered. Not using a regional authority.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] Access token is not expired. Returning the found cache entry. [Current time (12/06/2022 20:12:11) - Expiration Time (12/06/2022 21:00:49 +00:00) - Extended Expiration Time (12/06/2022 21:00:49 +00:00)]
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] Returning access token found in cache. RefreshOn exists ? False
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] Fetched access token from host login.microsoftonline.com.
DEBUG: (False) MSAL 4.30.1.0 MSAL.NetCore Microsoft Windows 10.0.22621 [12/06/2022 20:12:11 - ] === Token Acquisition finished successfully. An access token was returned with Expiration Time: 12/06/2022 21:00:49 +00:00 and Scopes https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-12-06T21:00:49.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<redacted>', UserId: '<redacted@redacted.com>'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/virtualMachines/<redacted>?api-version=2021-11-01

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 542a659d-9e33-4c08-aac8-4ab9f34f4750

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGet3Min;3998,Microsoft.Compute/LowCostGet30Min;31998
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 6127d4fb-6172-490e-a33d-ae497d623c7e
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : f2f67fb9-ab7d-47fb-a790-85c14559c602
x-ms-routing-request-id       : EASTUS:20221206T201211Z:f2f67fb9-ab7d-47fb-a790-85c14559c602
X-Content-Type-Options        : nosniff
Date                          : Tue, 06 Dec 2022 20:12:11 GMT

Body:
{
  "name": "<redacted>",
  "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/virtualMachines/<redacted>",
  "type": "Microsoft.Compute/virtualMachines",
  "location": "eastus2euap",
  "properties": {
    "vmId": "16a893e6-904a-4003-817c-1d508cce62a9",
    "availabilitySet": {
      "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/availabilitySets/LOAD-AS"
    },
    "hardwareProfile": {
      "vmSize": "Standard_D32ps_v5"
    },
    "storageProfile": {
      "imageReference": {
        "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/galleries/OurTeamSIG_Internal/images/<redacted>/versions/latest",
        "exactVersion": "0.0.1"
      },
      "osDisk": {
        "osType": "Linux",
        "name": "<redacted>_OsDisk_1_c5e6aaa9c8264f0eb89a6e0d4c8ab2e6",
        "createOption": "FromImage",
        "caching": "ReadOnly",
        "managedDisk": {
          "storageAccountType": "Standard_LRS",
          "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/<redacted>_OsDisk_1_c5e6aaa9c8264f0eb89a6e0d4c8ab2e6"
        },
        "deleteOption": "Detach",
        "diskSizeGB": 64
      },
      "dataDisks": [
        {
          "lun": 0,
          "name": "<redacted>_disk2_a7d286bb37144ab29f6cafc972275b86",
          "createOption": "Empty",
          "caching": "None",
          "managedDisk": {
            "storageAccountType": "Premium_LRS",
            "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Compute/disks/<redacted>_disk2_a7d286bb37144ab29f6cafc972275b86"
          },
          "deleteOption": "Detach",
          "diskSizeGB": 1024,
          "toBeDetached": false
        }
      ]
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Network/networkInterfaces/<redacted>-nic"
        }
      ]
    },
    "provisioningState": "Succeeded",
    "timeCreated": "2022-11-02T13:22:07.1691452-04:00"
  }
}


Get-AzVM: GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
DEBUG: AzureQoSEvent: Module: Az.Compute:4.24.0; CommandName: Get-AzVM; PSVersion: 7.3.0; IsSuccess: False; Duration: 00:00:00.2462818; Exception: GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.;
DEBUG: Finish sending metric.
DEBUG: 3:12:12 PM - GetAzureVMCommand end processing.
```

### Environment data

```PowerShell
PS D:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS D:\> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.7.3                 Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefa…
Script     4.24.0                Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAddition…
```

### Error output

```PowerShell
PS D:\> Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 1

Message        : GenericArguments[0], 'Microsoft.Azure.Management.Compute.Models.VirtualMachine', on 'T
                 MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.
StackTrace     :    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[]
                 genericArguments, Exception e)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
                    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2
                 <>h__TransparentIdentifier1)
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
                    at System.Linq.Enumerable.UnionIterator`1.FillSet()
                    at System.Linq.Enumerable.UnionIterator`1.ToArray()
                    at AutoMapper.TypeDetails.BuildPublicNoArgExtensionMethods(IEnumerable`1
                 sourceExtensionMethodSearch)
                    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)
                    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)
                    at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()
                    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean
                 useDefaultConstructor)
                    at System.Lazy`1.CreateValue()
                    at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)
                    at AutoMapper.ProfileMap.CreateTypeDetails(Type type)
                    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap
                 options)
                    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration
                 config)
                    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)
                    at AutoMapper.MapperConfiguration.Seal()
                    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)
                    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.Initialize()
                    at Microsoft.Azure.Commands.Compute.ComputeAutoMapperProfile.get_Mapper()
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.<ExecuteCmdlet>b__35_0()
                    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.GetAzureVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzVM}
Line           : get-azvm -name "<redacted>" -ResourceGroupName <redacted>
Position       : At line:1 char:1
                 + get-azvm -name "<redacted>" -ResourceGroupName <redacted>…
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Method System.Linq.Enumerable.MaxInteger: type argument
                 'Microsoft.Azure.Management.Compute.Models.VirtualMachine' violates the constraint of type parameter
                 'T'.
StackTrace     :    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType
                 declaringType, RuntimeType[] methodInstantiation)
                    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)
Exception      : System.Security.VerificationException
InvocationInfo : {Get-AzVM}
Line           : get-azvm -name "<redacted>" -ResourceGroupName <redacted>
Position       : At line:1 char:1
                 + get-azvm -name "<redacted>" -ResourceGroupName <redacted>…
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.
```

**Comment by zanedp** [comment]
My bad. I didn't realize I wasn't running the latest. For some reason, `Update-Module` didn't do anything for me, but after some `Remove-Module`, `Install-Module`, and quitting my shell a few times, I now have: 

```
PS D:\> get-module Az*
...
Script     2.10.4                Az.Accounts
Script     5.2.0                 Az.Compute
```

`Get-AzVM` works, now.
