### ISSUE TITLE
New-AzPolicyExemption can not find the PolicyDefinitionReferenceId specified

### ISSUE THREAD

**Issue by dunluo** [Azure/azure-powershell#20381]
### Description

With new Az.Resources 6.5, New-AzPolicyExemption is not being able to find the PolicyDefinitionReferenceId specified. This is working with 6.3 version. Look like it is removing all blank spaces from the reference Id in the argument hence can not find it as it has blanks in it.

`New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -PolicyAssignment $Assignment -PolicyDefinitionReferenceId $($Policy.Value) -Scope $ResourceGroupID -ExemptionCategory Waiver -Description $Description}`

$($Policy.Value) = "Function apps should disable public network access_1"
$Assignment is an initiative with several policies in it.

### Issue script & Debug output

```PowerShell
DEBUG: 2:33:06 PM - NewAzurePolicyExemptionCmdlet begin processing with ParameterSet 'DefaultParameterSet'.
DEBUG: 2:33:06 PM - using account id 'xxxx@xxxx.onmicrosoft.com'...
DEBUG: 2:33:06 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'removed', environment: 'AzureCloud', tenant: 'd16de530-94e7-4158-b7e2-xxxxxxx'
DEBUG: 2:33:06 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'d16de530-94e7-4158-b7e2-xxxxxxx', 
Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxx@xxxx.onmicrosoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - 37e40dbd-4f5a-485e-b4de-320b89bbd983] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - 37e40dbd-4f5a-485e-b4de-320b89bbd983] [Region discovery] Not using a regional authority.  
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - 37e40dbd-4f5a-485e-b4de-320b89bbd983] [Region discovery] Not using a regional authority.  
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - 37e40dbd-4f5a-485e-b4de-320b89bbd983] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - 37e40dbd-4f5a-485e-b4de-320b89bbd983] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z] Returning 1 accounts
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] MSAL MSAL.Desktop with assembly version '4.46.2.0'. 
 CorrelationId(ac3905bd-0bee-4fcd-9746-e15cc3fe3d04)
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] LoginHint provided: False
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] Account provided: True
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] ForceRefresh: False
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] === Token Acquisition (SilentRequest) started:      
  Scopes: https://management.core.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] [Region discovery] Not using a regional authority.  
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] Access token is not expired. Returning the found    
cache entry. [Current time (12/07/2022 04:33:06) - Expiration Time (12/07/2022 05:27:37 +00:00) - Extended Expiration Time (12/07/2022 05:27:37 +00:00)]
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] Returning access token found in cache. RefreshOn    
exists ? False
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] [Region discovery] Not using a regional authority.  
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04] 
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.46.2.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2022-12-07 04:33:06Z - ac3905bd-0bee-4fcd-9746-e15cc3fe3d04]  AT expiration time: 7/12/2022 5:27:37 AM +00:00,   
scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2022-12-07T05:27:37.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'd16de530-94e7-4158-b7e2-xxxxxxxxxx', UserId: 'xxxx@xxxx.onmicrosoft.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/569cfcea-159b-41eb-8d1b-xxxxxx/resourceGroups/rg-xxxxxx-dev/providers/Microsoft.Authorization/policyexemptions/CAF-Initiative-Functi 
onApps?api-version=2020-07-01-preview

Headers:
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v5.1.19041.1682,Az.Resources/6.5.0
ParameterSetName              : DefaultParameterSet
CommandName                   : New-AzPolicyExemption

Body:
{
  "properties": {
    "policyAssignmentId": "/providers/Microsoft.Management/managementGroups/CAF/providers/Microsoft.Authorization/policyAssignments/b46a1ef0aa9e4d6697148e11",
    "policyDefinitionReferenceIds": [
      "Functionappsshoulddisablepublicnetworkaccess_1"
    ],
    "exemptionCategory": "Waiver",
    "description": "DeployedbytheHybridCloudteamBlueprintbuildfile''at'07/12/202214:18:05(UTC+10:00)'"
  },
  "name": "CAF-Initiative-FunctionApps"
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 1203673b-d161-4305-8c50-adb62b0166c7
x-ms-correlation-request-id   : 1203673b-d161-4305-8c50-adb62b0166c7
x-ms-routing-request-id       : AUSTRALIAEAST:20221207T043307Z:1203673b-d161-4305-8c50-adb62b0166c7
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-store, no-cache
Date                          : Wed, 07 Dec 2022 04:33:07 GMT
Server                        : Kestrel

Body:
{
  "error": {
    "code": "InvalidPolicyDefinitionReference",
    "message": "The policy exemption 'CAF-Initiative-FunctionApps' create request is invalid.  The specified policy definition reference id 'Functionappsshoulddisablepublicnetworkaccess_1' 
 is invalid."
  }
}

DEBUG: 2:33:07 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
New-AzPolicyExemption : InvalidPolicyDefinitionReference : The policy exemption 'CAF-Initiative-FunctionApps' create request is invalid.  The specified policy definition reference id       
'Functionappsshoulddisablepublicnetworkaccess_1' is invalid.
CorrelationId: 1203673b-d161-4305-8c50-adb62b0166c7
At line:1 char:1
+ New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -Polic ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzPolicyExemption], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzurePolicyExemptionCmdlet
 
DEBUG: 2:33:07 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Resources:6.5.0; CommandName: New-AzPolicyExemption; PSVersion: 5.1.19041.1682; IsSuccess: False; Duration: 00:00:00.9926847; Exception: 
InvalidPolicyDefinitionReference : The policy exemption 'CAF-Initiative-FunctionApps' create request is invalid.  The specified policy definition reference id
'Functionappsshoulddisablepublicnetworkaccess_1' is invalid.
CorrelationId: 1203673b-d161-4305-8c50-adb62b0166c7;
DEBUG: 2:33:07 PM - NewAzurePolicyExemptionCmdlet end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.4     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     6.5.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
```

### Error output

```PowerShell
DEBUG: 2:41:22 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 2:41:22 PM - using account id 'xxxx@xxxxxx.onmicrosoft.com'...
DEBUG: 2:41:22 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.


   HistoryId: 35


Message        : InvalidPolicyDefinitionReference : The policy exemption 'CAF-Initiative-FunctionApps' create request is invalid.  The specified policy definition reference id
                 'Functionappsshoulddisablepublicnetworkaccess_1' is invalid.
                 CorrelationId: 1203673b-d161-4305-8c50-adb62b0166c7
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {New-AzPolicyExemption}
Line           : New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -PolicyAssignment $Assignment -PolicyDefinitionReferenceId $($Policy.Value) -Scope $ResourceGroupID
                 -ExemptionCategory Waiver -Description $Description
Position       : At line:1 char:1
                 + New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -Polic ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 35



   HistoryId: 29


Message        : InvalidPolicyDefinitionReference : The policy exemption 'CAF-Initiative-FunctionApps' create request is invalid.  The specified policy definition reference id
                 'Functionappsshoulddisablepublicnetworkaccess_1' is invalid.
                 CorrelationId: 58cdccd9-b6c9-4ad9-b76d-2f9d23d2c668
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {New-AzPolicyExemption}
Line           :    If($($Policy.Value)) {New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -PolicyAssignment $Assignment -PolicyDefinitionReferenceId $($Policy.Value) -Scope  
                 $ResourceGroupID -ExemptionCategory Waiver -Description $Description}

Position       : At line:1 char:26
                 + ... cy.Value)) {New-AzPolicyExemption -Name $Assignment.Properties.Displa ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 29



   HistoryId: 18


Message        : Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags  
                 flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
                 ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter    
                 parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[]
                 pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {New-AzPolicyExemption}
Line           :                     If($($Policy.Value)) {New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -PolicyAssignment $Assignment -PolicyDefinitionReferenceId
                 ($Policy.Value) -Scope $ResourceGroupID -ExemptionCategory Waiver -Description $Description}

Position       : At line:2 char:71
                 + ... ew-AzPolicyExemption -Name $Assignment.Properties.DisplayName -Policy ...
                 +                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18

Message        : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags  
                 flags)
Exception      : System.Management.Automation.ValidationMetadataException
InvocationInfo : {New-AzPolicyExemption}
Line           :                     If($($Policy.Value)) {New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -PolicyAssignment $Assignment -PolicyDefinitionReferenceId 
                 ($Policy.Value) -Scope $ResourceGroupID -ExemptionCategory Waiver -Description $Description}

Position       : At line:2 char:71
                 + ... ew-AzPolicyExemption -Name $Assignment.Properties.DisplayName -Policy ...
                 +                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18



   HistoryId: 1


Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Users\luod\Documents\WindowsPowerShell\Modules\Az.Accounts\2.10.4\Az.Accounts.psm1:39 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.10.4; CommandName: Resolve-AzError; PSVersion: 5.1.19041.1682; IsSuccess: True; Duration: 00:00:00.0997086
DEBUG: 2:41:22 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: 2:41:22 PM - ResolveError end processing.
```

**Comment by luodun2020** [comment]
I passed it as an object which is returned by Get-AzPolicyAssignment.
$Assignment = Get-AzPolicyAssignment -Scope "/subscriptions/$($SubscriptionId)" | Where-Object {$_.Properties.DisplayName -match ($Policy.Name)}

$($Policy.Value) is an string which is the ID value of a policy inside an initiative

**Comment by SaurabhSharma-MSFT** [comment]
@luodun2020 sorry for the delay but I am not able to reproduce this issue and New-AzPolicyExemption works as expected.
![image](https://user-images.githubusercontent.com/38112130/210309029-1df558fc-d43a-4528-af1d-e401eed603f5.png)
![image](https://user-images.githubusercontent.com/38112130/210309172-bb4c7749-a7bf-475c-b486-7976806f8254.png)

**Comment by luodun2020** [comment]
Hi @SaurabhSharma-MSFT, 

it is a policy inside an initiative. Not a policy itself.

`New-AzPolicyExemption -Name $Assignment.Properties.DisplayName -PolicyAssignment $Assignment -PolicyDefinitionReferenceId $($Policy.Value) -Scope $ResourceGroupID -ExemptionCategory Waiver -Description $Description}`

You need to specify the PolicyDefinitionReferenceId to be exempt only one policy inside an initiative.

**Comment by lpalerm** [comment]
Have you gotten this resolved?  I am having the same issue.

**Comment by brianstringfellow** [comment]
I saw a similar problem when I updated to Az.Resources module 6.5.0 (Release date 2022.12.06). About two weeks later, a newer version 6.5.1 (Release date 2022.12.19) was available. After I installed 6.5.1 the problem was resolved for me.

https://www.powershellgallery.com/packages/Az.Resources/6.5.1

The changelog doesn't explicitly mention the problem seen here but does mention a change around `Set-AzPolicySetDefinition`.
https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/ChangeLog.md

**Comment by lpalerm** [comment]
> I saw a similar problem when I updated to Az.Resources module 6.5.0 (Release date 2022.12.06). About two weeks later, a newer version 6.5.1 (Release date 2022.12.19) was available. After I installed 6.5.1 the problem was resolved for me.
> 
> https://www.powershellgallery.com/packages/Az.Resources/6.5.1
> 
> The changelog doesn't explicitly mention the problem seen here but does mention a change around `Set-AzPolicySetDefinition`. https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/ChangeLog.md

Thanks!  I will give it a try.  I was able to accomplish the same task using azure cli.

**Comment by eoq** [comment]
Upgrading Az.Resources from 6.5.0 to 6.5.2 seemed to have resolved this issue for me as well

**Comment by SaurabhSharma-MSFT** [comment]
@dunluo Sorry for delay on this.  Are you still facing this issue?
