### ISSUE TITLE
Get-AzStorageBlobContent fails for some files with "Cannot set percent because PercentComplete cannot be greater than 100."

### ISSUE THREAD

**Issue by sopelt** [Azure/azure-powershell#20489]
### Description

In Az.Storage 5.0.0 (contained in [Az 9.0.1](https://www.powershellgallery.com/packages/Az/9.0.1), the current default version for [windows-2022 hosted DevOps agents](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md)) some files cause an error in [Get-AzStorageBlobContent](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstorageblobcontent) when used similar to [this example](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstorageblobcontent?view=azps-9.2.0#example-2-download-blob-content-using-the-pipeline).

File size seems to play a role as well as only a static set of files fails while others work as expected.

On of the problematic files has a content lenght of 52951904.

The problem seems to be resolved when forcing Az 9.1.1 in the task or installing Az.Storage 5.1.0+.

[This issue](https://github.com/Azure/azure-powershell/issues/17743) seems to be related.

### Issue script & Debug output

```PowerShell
PS C:\Temp\blobtest> Import-Module Az.Storage -RequiredVersion 5.0.0
PS C:\Temp\blobtest> $storage = New-AzStorageContext -StorageAccountName "REDACTED"
PS C:\Temp\blobtest>
PS C:\Temp\blobtest> $DebugPreference='Continue'
PS C:\Temp\blobtest>
PS C:\Temp\blobtest> $blob = Get-AzStorageBlob -Blob "REDACTED" -Container "REDACTED" -Context $storage
DEBUG: 18:01:45 - Init Operation Context for 'GetAzureStorageBlobCommand' with client request id  Azure-Storage-PowerShell-REDACTED. If you want to get more details, please add "-Debug" to your command.
DEBUG: 18:01:45 - GetAzureStorageBlobCommand begin processing with ParameterSet 'BlobName'.
DEBUG: 18:01:45 - Use storage account 'REDACTED' from storage context.
DEBUG: Request [b02d04a3-9a9b-47d1-9748-298647b92b4f] HEAD https://REDACTED
x-ms-version:2021-06-08
Accept:application/xml
User-Agent:AzurePowershell/v1.0.0,azsdk-net-Storage.Blobs/12.12.0,(.NET 7.0.0; Microsoft Windows 10.0.22621)
x-ms-client-request-id:b02d04a3-9a9b-47d1-9748-298647b92b4f
x-ms-return-client-request-id:true
Authorization:REDACTED
client assembly: Azure.Storage.Blobs
DEBUG: Response [b02d04a3-9a9b-47d1-9748-298647b92b4f] 200 OK (00.2s)
Accept-Ranges:bytes
ETag:"0x8DAD1E90D46936C"
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:6efb0afd-301e-0062-1f94-14e23a000000
x-ms-client-request-id:b02d04a3-9a9b-47d1-9748-298647b92b4f
x-ms-version:2021-06-08
x-ms-meta-BuildDate:REDACTED
x-ms-creation-time:Tue, 29 Nov 2022 09:06:50 GMT
x-ms-lease-status:unlocked
x-ms-lease-state:available
x-ms-blob-type:BlockBlob
x-ms-server-encrypted:true
x-ms-access-tier:Hot
x-ms-access-tier-inferred:true
Date:Tue, 20 Dec 2022 17:01:35 GMT
Content-Length:52951904
Content-Type:application/octet-stream
Content-MD5:StrcVbhOa5VJGGa6mQrRjw==
Last-Modified:Tue, 29 Nov 2022 09:06:50 GMT

DEBUG: 18:01:46 - GetAzureStorageBlobCommand end processing, Start 0 remote calls. Finish 0 remote calls. Elapsed time 307,55 ms. Client operation id: Azure-Storage-PowerShell-e536165b-31bc-4a09-8c74-338634228ee6.
DEBUG: AzureQoSEvent:  Module: Az.Storage:5.0.0; CommandName: Get-AzStorageBlob; PSVersion: 7.3.1; IsSuccess: True; Duration: 00:00:00.3033303
DEBUG: 18:01:46 - GetAzureStorageBlobCommand end processing.
PS C:\Temp\blobtest> $blob | Get-AzStorageBlobContent
DEBUG: 18:01:47 - Init Operation Context for 'GetAzureStorageBlobContentCommand' with client request id  Azure-Storage-PowerShell-e536165b-31bc-4a09-8c74-338634228ee6. If you want to get more details, please add "-Debug" to your command.
DEBUG: 18:01:47 - Use storage account 'REDACTED' from storage context.
Get-AzStorageBlobContent: Cannot set percent because PercentComplete cannot be greater than 100. (Parameter 'value')
Actual value was 1778384896.
DEBUG: 18:01:49 - GetAzureStorageBlobContentCommand end processing, Start 0 remote calls. Finish 0 remote calls. Elapsed time 3909,91 ms. Client operation id: Azure-Storage-PowerShell-e536165b-31bc-4a09-8c74-338634228ee6.
DEBUG: 18:01:49 - GetAzureStorageBlobContentCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.4                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     5.0.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorage…
```

### Error output

```PowerShell
Resolve-AzError
DEBUG: 18:03:56 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 18:03:56 - using account id 'simon@software-architects.at'...
DEBUG: 18:03:56 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 6

Message        : Cannot set percent because PercentComplete cannot be greater than 100. (Parameter 'value')
                 Actual value was 1778384896.
StackTrace     :    at System.Management.Automation.ProgressRecord.set_PercentComplete(Int32 value)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.StorageDataMovementCmdletBase.<>c__DisplayClass26_0
                 .<GetTransferContext>b__0(TransferStatus transferProgress)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.TransferProgressHandler.Report(TransferStatus
                 value)
                    at Microsoft.Azure.Storage.DataMovement.TransferProgressTracker.InvokeProgressHandler()
                    at Microsoft.Azure.Storage.DataMovement.TransferProgressTracker.AddNumberOfFilesFailed(Int64
                 numberOfFilesToIncrease)
                    at Microsoft.Azure.Storage.DataMovement.TransferProgressTracker.AddNumberOfFilesFailed(Int64
                 numberOfFilesToIncrease)
                    at Microsoft.Azure.Storage.DataMovement.Transfer.<UpdateTransferJobStatus>b__51_3()
                    at Microsoft.Azure.Storage.DataMovement.Transfer.UpdateProgress(TransferJob job, Action
                 updateAction)
                    at Microsoft.Azure.Storage.DataMovement.Transfer.UpdateTransferJobStatus(TransferJob transferJob,
                 TransferJobStatus targetStatus)
                    at Microsoft.Azure.Storage.DataMovement.SingleObjectTransfer.OnTransferFailed(TransferEventArgs
                 eventArgs)
                    at Microsoft.Azure.Storage.DataMovement.SingleObjectTransfer.ExecuteAsync(TransferScheduler
                 scheduler, CancellationToken cancellationToken)
                    at Microsoft.Azure.Storage.DataMovement.TransferManager.DoTransfer(Transfer transfer,
                 TransferContext transferContext, CancellationToken cancellationToken)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.DataMovementTransferHelper.DoTransfer(Func`1
                 doTransfer, ProgressRecord record, TaskOutputStream outputStream)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobContentCommand.DownloadBl
                 ob(Int64 taskId, IStorageBlobManagement localChannel, CloudBlob blob, String filePath)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTask
                 (Int64 taskId, Task task)
Exception      : System.Management.Automation.PSArgumentOutOfRangeException
InvocationInfo : {Get-AzStorageBlobContent}
Line           : $blob | Get-AzStorageBlobContent
Position       : At line:1 char:9
                 + $blob | Get-AzStorageBlobContent
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.10.4; CommandName: Resolve-AzError; PSVersion: 7.3.1; IsSuccess: True; Duration: 00:00:00.0314385
DEBUG: 18:03:56 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: 18:03:56 - ResolveError end processing.
```

**Comment by navba-MSFT** [comment]
@sopelt Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by blueww** [comment]
@sopelt 
It looks the issue should already been fixed in Az.Storage 5.1.0.
Would you please upgrade to the latest Az.Storage, and see if the issue still repro?

**Comment by sopelt** [comment]
Hi @blueww and @navba-MSFT,

thanks for getting back. Yes, as per my initial post specifying Az 9.1.1 in the pipeline task or manually installing Az.Storage 5.1+ fixes the issue. Because I have found nothing on the issue I wanted to at least document it (also in https://github.com/actions/runner-images/issues/6819 ) to help others around this issue as long as the packages containing the regression are still the default in the runner images.

**Comment by blueww** [comment]
@sopelt 

Thanks for reporting that!

For the document, as you have both open issue here and https://github.com/actions/runner-images/issues/6819, I think other users can find the problem by search the issues.

**Comment by sopelt** [comment]
Thank you for quickly looking into this @blueww 

Closing this issue should be fine as the root cause in the module is already resolved and https://github.com/actions/runner-images/issues/6819 is the better place for tracking the runner-image itself.
