### ISSUE TITLE
Get-AzMarketplaceTerms failing

### ISSUE THREAD

**Issue by briansaxbergMSFT** [Azure/azure-powershell#20590]
### Description

When trying this command  Get-AzMarketplaceTerms -Publisher 'barracudanetworks' -Product 'barracuda-ng-firewall' -Name 'byol' 

I also get the error when trying to run it from Cloud Shell.

### Issue script & Debug output

```PowerShell
PS C:\WINDOWS\system32> $DebugPreference='Continue'
PS C:\WINDOWS\system32> Get-AzMarketplaceTerms -Publisher 'barracudanetworks' -Product 'barracuda-ng-firewall' -Name 'byol' -verbose
DEBUG: 3:00:13 PM - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated:
/subscriptions/<REDACTED>/providers/Microsoft.MarketplaceOrdering/agreements/barracudanetworks/offers/barracuda-ng-firewall
/plans/byol?api-version=2021-01-01
DEBUG: RequestCreated:
/subscriptions/<REDACTED>/providers/Microsoft.MarketplaceOrdering/agreements/barracudanetworks/offers/barracuda-ng-firewall
/plans/byol?api-version=2021-01-01
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<REDACTED>/providers/Microsoft.MarketplaceOrdering/agreements/barracudanetworks/
offers/barracuda-ng-firewall/plans/byol?api-version=2021-01-01

Headers:
x-ms-unique-id                : 4
x-ms-client-request-id        : 2e3127de-c34f-4b69-8b21-7dc794f33728
CommandName                   : Get-AzMarketplaceTerms
FullCommandName               : Get-AzMarketplaceTerms_Get1
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v5.1.22621.963,Az.MarketplaceOrdering/2.0.0

Body:


DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
X-Frame-Options               : SAMEORIGIN
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-request-id               : ddbc2def-7b8c-44e0-b24c-1bbbb900f572
x-ms-correlation-request-id   : ddbc2def-7b8c-44e0-b24c-1bbbb900f572
x-ms-routing-request-id       : CENTRALUS:20230107T205957Z:ddbc2def-7b8c-44e0-b24c-1bbbb900f572
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Sat, 07 Jan 2023 20:59:57 GMT
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
{
  "error": {
    "code": "NotFound",
    "message": "Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer = 'barracuda-ng-firewall', sku =
'byol',  Correlation Id: 'ddbc2def-7b8c-44e0-b24c-1bbbb900f572'."
  }
}

DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
Get-AzMarketplaceTerms : Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer = 'barracuda-ng-firewall',
sku = 'byol',  Correlation Id: 'ddbc2def-7b8c-44e0-b24c-1bbbb900f572'.
At C:\Users\briansaxberg\Documents\WindowsPowerShell\Modules\Az.MarketplaceOrdering\2.0.0\exports\ProxyCmdletDefinitions.ps1:537 char:9
+         $steppablePipeline.Begin($PSCmdlet)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SubscriptionI..., Name = byol }:<>f__AnonymousType1`4) [Get-AzMarketplaceTerms_Get1], Exception
    + FullyQualifiedErrorId : NotFound,Microsoft.Azure.PowerShell.Cmdlets.MarketplaceOrdering.Cmdlets.GetAzMarketplaceTerms_Get1
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:

DEBUG INFORMATION FROM CLOUDSHELL
PS /home/brian> $DebugPreference='Continue'                                                                            
PS /home/brian> Get-AzMarketplaceTerms -Publisher 'barracudanetworks' -Product 'barracuda-ng-firewall' -Name 'byol' -verbose
DEBUG: 9:07:30 PM - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /subscriptions/<REDACTED>/providers/Microsoft.MarketplaceOrdering/agreements/barracudanetworks/offers/barracuda-ng-firewall/plans/byol?api-version=2021-01-01
DEBUG: RequestCreated: /subscriptions/<REDACTED>/providers/Microsoft.MarketplaceOrdering/agreements/barracudanetworks/offers/barracuda-ng-firewall/plans/byol?api-version=2021-01-01
DEBUG: HeaderParametersAdded: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<REDACTED>/providers/Microsoft.MarketplaceOrdering/agreements/barracudanetworks/offers/barracuda-ng-firewall/plans/byol?api-version=2021-01-01

Headers:
x-ms-unique-id                : 1
x-ms-client-request-id        : 3bd72487-5613-4ead-b8ce-7a1ed68cbd88
CommandName                   : Get-AzMarketplaceTerms
FullCommandName               : Get-AzMarketplaceTerms_Get1
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v9.2.0,PSVersion/v7.3.0,Az.MarketplaceOrdering/2.0.0

Body:



DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
X-Frame-Options               : SAMEORIGIN
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-request-id               : ba51b5ea-f9c9-43f2-945b-8bedba5749a1
x-ms-correlation-request-id   : ba51b5ea-f9c9-43f2-945b-8bedba5749a1
x-ms-routing-request-id       : EASTUS:20230107T210740Z:ba51b5ea-f9c9-43f2-945b-8bedba5749a1
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Sat, 07 Jan 2023 21:07:39 GMT

Body:
{
  "error": {
    "code": "NotFound",
    "message": "Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer = 'barracuda-ng-firewall', sku = 'byol',  Correlation Id: 'ba51b5ea-f9c9-43f2-945b-8bedba5749a1'."
  }
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
WARNING: Get-AzMarketplaceTerms_Get1 is not found. The most similar Azure PowerShell command is:
        Get-AzMarketplaceTerms
WARNING: The intelligent recommendation feature is in preview. Help us improve it by sharing your experience: https://go.microsoft.com/fwlink/?linkid=2202436
Get-AzMarketplaceTerms_Get1: /usr/local/share/powershell/Modules/Az.MarketplaceOrdering/2.0.0/exports/ProxyCmdletDefinitions.ps1:537
Line |
 537 |          $steppablePipeline.Begin($PSCmdlet)
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer = 'barracuda-ng-firewall', sku = 'byol',  Correlation Id: 'ba51b5ea-f9c9-43f2-945b-8bedba5749a1'.
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSResourceNotFoundCloudException: InternalException' from response
DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: AzureQoSEvent:  Module: Az.MarketplaceOrdering:2.0.0; CommandName: Get-AzMarketplaceTerms; PSVersion: 7.3.0; IsSuccess: False; Duration: 00:00:10.3216073; Exception: InternalException;
```

### Environment data

```PowerShell
PS C:\WINDOWS\system32> $PSversionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

PSVersion Information from Cloudshell.
PS /home/brian> $PSVersionTable                   

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Linux 5.4.0-1098-azure #104~18.04.2-Ubuntu SMP Tue Nov 29 12:13:35 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\WINDOWS\system32> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.10.4     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     2.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Invoke-AzMarketplaceSignTerms, Set-AzMarketplaceTerms, Stop-AzM...

Modules from Cloudshell
PS /home/brian> Get-Module Az*                                                                                              

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.4                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     5.2.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     2.0.0                 Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Invoke-AzMarketplaceSignTerms, Set-AzMarketplaceTerms, Stop-AzMarketplaceTerms}
Script     5.2.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzApplicationGatewayBa…
Script     6.5.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     5.2.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember…}
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
PS C:\WINDOWS\system32> Resolve-AzError
DEBUG: 3:04:38 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 3:04:38 PM - using account id 'briansaxberg@microsoft.com'...
DEBUG: 3:04:38 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in
Azure PowerShell.


   HistoryId: 14


Message        : [NotFound] : Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer =
                 'barracuda-ng-firewall', sku = 'byol',  Correlation Id: 'ddbc2def-7b8c-44e0-b24c-1bbbb900f572'.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzMarketplaceTerms_Get1}
Line           :         $steppablePipeline.Begin($PSCmdlet)

Position       : At C:\Users\briansaxberg\Documents\WindowsPowerShell\Modules\Az.MarketplaceOrdering\2.0.0\exports\ProxyCmdletDefinitions.ps1:537
                 char:9
                 +         $steppablePipeline.Begin($PSCmdlet)
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 14



   HistoryId: 12


Message        : [NotFound] : Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer =
                 'barracuda-ng-firewall', sku = 'byol',  Correlation Id: '73c2dba1-a8bc-41dc-9d78-7956d27b36e5'.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzMarketplaceTerms_Get1}
Line           :         $steppablePipeline.Begin($PSCmdlet)

Position       : At C:\Users\briansaxberg\Documents\WindowsPowerShell\Modules\Az.MarketplaceOrdering\2.0.0\exports\ProxyCmdletDefinitions.ps1:537
                 char:9
                 +         $steppablePipeline.Begin($PSCmdlet)
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 12



   HistoryId: 9


Message        : [NotFound] : Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer =
                 'barracuda-ng-firewall', sku = 'byol',  Correlation Id: '863d7939-fb35-4359-a6b6-bbf4db185506'.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzMarketplaceTerms_Get1}
Line           :         $steppablePipeline.Begin($PSCmdlet)

Position       : At C:\Users\briansaxberg\Documents\WindowsPowerShell\Modules\Az.MarketplaceOrdering\2.0.0\exports\ProxyCmdletDefinitions.ps1:537
                 char:9
                 +         $steppablePipeline.Begin($PSCmdlet)
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9



   HistoryId: 8


Message        : [NotFound] : Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer =
                 'barracuda-ng-firewall', sku = 'byol',  Correlation Id: 'b9982286-601e-4b27-80d2-8b2073af3371'.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-AzMarketplaceTerms_Get1}
Line           :         $steppablePipeline.Begin($PSCmdlet)

Position       : At C:\Users\briansaxberg\Documents\WindowsPowerShell\Modules\Az.MarketplaceOrdering\2.0.0\exports\ProxyCmdletDefinitions.ps1:537
                 char:9
                 +         $steppablePipeline.Begin($PSCmdlet)
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8



   HistoryId: 5


Message        : Module 'Az' was not updated because no valid module was found in the module directory. Verify that the module is located in the
                 folder specified by $env:PSModulePath.
StackTrace     :
Exception      : Microsoft.PowerShell.Commands.WriteErrorException
InvocationInfo : {Update-Module}
Line           : Update-Module -Name Az
Position       : At line:1 char:1
                 + Update-Module -Name Az
                 + ~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5

Message        : No match was found for the specified search criteria and module names 'Az'.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Get-Package}
Line           :                 $installedPackages = PackageManagement\Get-Package @GetPackageParameters

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2000 char:38
                 + ... stalledPackages = PackageManagement\Get-Package @GetPackageParameters
                 +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5



   HistoryId: 4


Message        : The term 'Connect-AzAccount' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
                 spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes,
                 SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin,
                 Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements,
                 CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][]
                 pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Connect-AzAccount
Position       : At line:1 char:1
                 + Connect-AzAccount
                 + ~~~~~~~~~~~~~~~~~
HistoryId      : 4



   HistoryId: 3


Message        : The following commands are already available on this system:'Login-AzAccount,Logout-AzAccount,Resolve-Error,Send-Feedback'. This
                 module 'Az.Accounts' may override the existing commands. If you still want to install this module 'Az.Accounts', use -AllowClobber
                 parameter.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Install-Package}
Line           :             $null = PackageManagement\Install-Package @PSBoundParameters

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
                 + ...          $null = PackageManagement\Install-Package @PSBoundParameters
                 +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3



   HistoryId: -1


Message        : Unable to find type [System.Net.Http.HttpClient].
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :         [System.Net.Http.HttpClient]

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:6260 char:9
                 +         [System.Net.Http.HttpClient]
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Unable to find type [System.Net.Http.HttpClient].
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :         [System.Net.Http.HttpClient]

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:6260 char:9
                 +         [System.Net.Http.HttpClient]
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Unable to find type [Microsoft.PowerShell.Commands.PowerShellGet.Telemetry].
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :     $telemetryMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | Get-Member -Static).Name

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:715 char:26
                 + ... yMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: 3:04:38 PM - ResolveError end processing.

Resolve-AzError from cloudshell.
Resolve-AzError                                                                     
DEBUG: 9:11:17 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 9:11:17 PM - using account id 'MSI@50342'...
DEBUG: 9:11:17 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 2

Message        : [NotFound] : Unable to find legal terms for this offer. Agreement has never been signed for this offer. offer = 'barracuda-ng-firewall', sku = 'byol',  Correlation Id: 'ba51b5ea-f9c9-43f2-945b-8bedba5749a1'.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzMarketplaceTerms_Get1}
Line           :         $steppablePipeline.Begin($PSCmdlet)
                 
Position       : At /usr/local/share/powershell/Modules/Az.MarketplaceOrdering/2.0.0/exports/ProxyCmdletDefinitions.ps1:537 char:9
                 +         $steppablePipeline.Begin($PSCmdlet)
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2


The Azure PowerShell team is listening, please let us know how we are doing: https://aka.ms/azpssurvey?Q_CHL=ERROR.

DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.10.4; CommandName: Resolve-AzError; PSVersion: 7.3.0; IsSuccess: True; Duration: 00:00:00.0176659
DEBUG: 9:11:17 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: 9:11:17 PM - ResolveError end processing.
```

**Comment by dingmeng-xue** [comment]
Thanks for reporting. It seems this issue is the same as #20443 . You can see error was returned from service. Please try to `Set-AzMarketPlaceTerms` to accept term and then get term.

**Comment by briansaxbergMSFT** [comment]
@dingmeng-xue 

PS C:\Users\briansaxberg> Set-AzMarketPlaceTerms

cmdlet Set-AzMarketplaceTerms at command pipeline position 1
Supply values for the following parameters:
Product: barracuda-ng-firewall
Name: byol
Publisher: barracudenetworks
Accept: 1
Set-AzMarketplaceTerms : Cannot process argument transformation on parameter 'Accept'. Cannot convert value
"System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept only Boolean values
and numbers, such as $True, $False, 1 or 0.
At line:1 char:1
+ Set-AzMarketPlaceTerms
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzMarketplaceTerms], ParameterBindingArgumentTransformationExcepti
   on
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-AzMarketplaceTerms

PS C:\Users\briansaxberg> Set-AzMarketPlaceTerms

cmdlet Set-AzMarketplaceTerms at command pipeline position 1
Supply values for the following parameters:
Product: barracude-ng-firewall
Name: byol
Publisher: barracudanetworks
Accept: $True
Set-AzMarketplaceTerms : Cannot process argument transformation on parameter 'Accept'. Cannot convert value
"System.String" to type "System.Management.Automation.SwitchParameter". Boolean parameters accept only Boolean values
and numbers, such as $True, $False, 1 or 0.
At line:1 char:1
+ Set-AzMarketPlaceTerms
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzMarketplaceTerms], ParameterBindingArgumentTransformationExcepti
   on
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Set-AzMarketplaceTerms

PS C:\Users\briansaxberg>

Same results from Cloudshell

**Comment by briansaxbergMSFT** [comment]
I was able to make this work with CLI.

I was able to make the Azure CLI work on my workstations from Powershell.
az vm image terms accept --urn barracudanetworks:barracuda-ng-firewall:byol:latest 

This will work to show the terms.
az vm image terms show --urn barracudanetworks:barracuda-ng-firewall:byol:latest 

If you want to cancel the terms.
az vm image terms cancel --urn barracudanetworks:barracuda-ng-firewall:byol:latest

**Comment by dingmeng-xue** [comment]
@briansaxbergMSFT , `-Accept` is switch parameter. Please follow this example https://learn.microsoft.com/en-us/powershell/module/az.marketplaceordering/set-azmarketplaceterms?view=azps-9.3.0#example-1-accept-terms-for-a-given-publisher-id(publisher)-offer-id(product)-and-plan-id(name)

**Comment by briansaxbergMSFT** [comment]
Perfect thank you!  Sorry I missed that switch!  That does work.
