### ISSUE TITLE
Get-AzApplicationInsights : Exception calling ".ctor" with "3" argument(s): "Value cannot be null. Parameter name: source" At line:1 char:1

### ISSUE THREAD

**Issue by krishnasingh1818** [Azure/azure-powershell#20697]
### Description

This command earlier used to work but now its not working 

`Get-AzApplicationInsights  -Name "appinsname"  -ResourceGroupName "rgname" -Full`

returns error 

```
Get-AzApplicationInsights : Exception calling ".ctor" with "3" argument(s): "Value cannot be null.
Parameter name: source"
At line:1 char:1
```

![image](https://user-images.githubusercontent.com/10679463/213260797-51d560c8-1bb6-4e19-9d48-729ca14b6394.png)

Please advise what could be causing this error.

### Issue script & Debug output

```PowerShell
Get-AzApplicationInsights : Exception calling ".ctor" with "3" argument(s): "Value cannot be null.
Parameter name: source"
At line:1 char:1
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.19041.2364                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.19041.2364                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\Users\v485292> Get-Module Az*

ModuleType Version    Name                                ExportedCommands                                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                                  
Script     2.10.4     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}                                                                          
Script     2.2.0      Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKey, Get-AzApplicationInsightsContinuousExport, Get-AzApplicationInsightsLinkedStorageA...
```

### Error output

```PowerShell
Message        : Exception calling ".ctor" with "3" argument(s): "Value cannot be null.
                 Parameter name: source"
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.MethodInvocationException
InvocationInfo : {}
Line           :             $PSCmdlet.WriteObject([Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Models.PSApplicationInsightsComponentWithPricingPlan]::New($component, $pricingPlan, 
                 $dailyCapStatus))
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.ApplicationInsights\2.2.0\custom\Get-AzApplicationInsights.ps1:149 char:13
                 +             $PSCmdlet.WriteObject([Microsoft.Azure.PowerShell.Cmdlets ...
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Value cannot be null.
                 Parameter name: source
StackTrace     :    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
                    at Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Models.PSApplicationInsightsComponent..ctor(ApplicationInsightsComponent component)
                    at Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Models.PSApplicationInsightsComponentWithPricingPlan..ctor(ApplicationInsightsComponent component, 
                 ApplicationInsightsComponentBillingFeatures billing, ApplicationInsightsComponentQuotaStatus status)
                    at CallSite.Target(Closure , CallSite , Type , Object , Object , Object )
Exception      : System.ArgumentNullException
InvocationInfo : {}
Line           :             $PSCmdlet.WriteObject([Microsoft.Azure.PowerShell.Cmdlets.ApplicationInsights.Models.PSApplicationInsightsComponentWithPricingPlan]::New($component, $pricingPlan, 
                 $dailyCapStatus))
                 
Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.ApplicationInsights\2.2.0\custom\Get-AzApplicationInsights.ps1:149 char:13
                 +             $PSCmdlet.WriteObject([Microsoft.Azure.PowerShell.Cmdlets ...
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by RakeshMohanMSFT** [comment]
@krishnasingh1818 Thank you for reaching out to us, we are looking into it.
