### ISSUE TITLE
New-AzVM The platform image UbuntuLTS is not available

### ISSUE THREAD

**Issue by mikefrobbins** [Azure/azure-powershell#20732]
### Description

Error when attempting to create a new VM with `New-AzVM` with an image type of `UbuntuLTS`.
_New-AzVM: The platform image 'Canonical:UbuntuServer:20.04-LTS:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile_

### Issue script & Debug output

```PowerShell
PS C:\> New-AzVM -ResourceGroupName MyResourceGroup -Name mytestvm -Location westus -Image UbuntuLTS
DEBUG: Initializing ConditionalAssemblyContext. PSEdition is [Core]. PSVersion is [7.3.1].
...
DEBUG: [Common.Authentication]: Authenticating using Account: '<account name>', environment: 'AzureCloud', tenant: '00000000-0000-0000-0000-000000000000'
DEBUG: 9:06:40 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'00000000-0000-0000-0000-000000000000', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'<account name>'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z] [WamBroker] WAM supported OS.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z] [WamBroker] ListWindowsWorkAndSchoolAccounts option was not enabled.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z] Found 2 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z] Returning 2 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] MSAL MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(00000000-0000-0000-0000-000000000000)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - True
HomeAccountId - False
CorrelationId - 00000000-0000-0000-0000-000000000000
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] Access token is not expired. Returning the found cache entry. [Current time (01/23/2023 15:06:40) - Expiration Time (01/23/2023 15:24:01 +00:00) - Extended Expiration Time (01/23/2023 15:24:01 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000]
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.22621 [2023-01-23 15:06:40Z - 00000000-0000-0000-0000-000000000000]  AT expiration time: 1/23/2023 3:24:01 PM +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-01-23T15:24:01.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '00000000-0000-0000-0000-000000000000', UserId: '<account name>'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsoft.Compute/virtualMachines/mytestvm?api-version=2022-08-01

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 00000000-0000-0000-0000-000000000000

Body:
{
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_D2s_v3"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "Canonical",
        "offer": "UbuntuServer",
        "sku": "20.04-LTS",
        "version": "latest"
      },
      "osDisk": {
        "createOption": "FromImage"
      }
    },
    "additionalCapabilities": {},
    "osProfile": {
      "computerName": "mytestvm",
      "adminUsername": "mytestadmin",
      "adminPassword": "********************",
      "linuxConfiguration": {
        "ssh": {}
      }
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/MyResourceGroup/providers/Microsoft.Network/networkInterfaces/mytestvm"
        }
      ]
    }
  },
  "location": "westus"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/PutVM3Min;239,Microsoft.Compute/PutVM30Min;1198
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 00000000-0000-0000-0000-000000000000
x-ms-routing-request-id       : SOUTHCENTRALUS:20230123T150639Z:00000000-0000-0000-0000-000000000000
X-Content-Type-Options        : nosniff
Date                          : Mon, 23 Jan 2023 15:06:38 GMT

Body:
{
  "error": {
    "code": "PlatformImageNotFound",
    "message": "The platform image 'Canonical:UbuntuServer:20.04-LTS:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile",
    "target": "imageReference"
  }
}


DEBUG: 9:06:43 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
New-AzVM: The platform image 'Canonical:UbuntuServer:20.04-LTS:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile
DEBUG: 9:06:43 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Compute:5.3.0; CommandName: New-AzVM; PSVersion: 7.3.1; IsSuccess: False; Duration: 00:00:05.5689864; Exception: The platform image 'Canonical:UbuntuServer:20.04-LTS:latest' is not available. Verify that all fields in the storage profile are correct. For more details about storage profile information, please refer to https://aka.ms/storageprofile;
DEBUG: 9:06:43 AM - NewAzureVMCommand end processing.
PS C:\>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version Name
---------- ------- ----
    Script 2.11.1  Az.Accounts
    Script 5.3.0   Az.Compute
    Script 6.5.1   Az.Resources
```

### Error output

```PowerShell
RequestId      : 00000000-0000-0000-0000-000000000000
Message        : The platform image 'Canonical:UbuntuServer:20.04-LTS:latest' is not available. Verify that all fields
                 in the storage profile are correct. For more details about storage profile information, please refer
                 to https://aka.ms/storageprofile
ServerMessage  : PlatformImageNotFound: The platform image 'Canonical:UbuntuServer:20.04-LTS:latest' is not available.
                 Verify that all fields in the storage profile are correct. For more details about storage profile
                 information, please refer to https://aka.ms/storageprofile
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {NotFound}
RequestMessage : {PUT https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/My
                 ResourceGroup/providers/Microsoft.Compute/virtualMachines/mytestvm?api-version=2022-08-01}
InvocationInfo : {New-AzVM}
Line           : New-AzVM -ResourceGroupName MyResourceGroup -Name mytestvm -Location westus -Image UbuntuLTS
Position       : At line:1 char:1
                 + New-AzVM -ResourceGroupName MyResourceGroup -Name mytestvm -Location  …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Common.Strategies.SyncTaskScheduler.Wait(Task task, Action
                 progressUpdate)
                    at Microsoft.Azure.Commands.Common.Strategies.AsyncCmdletExtensions.CmdletStartAndWait(ICmdlet
                 cmdlet, Func`2 createAndStartTask)
                    at Microsoft.Azure.Commands.Compute.Strategies.AsyncCmdletExtensions.StartAndWait[T](T cmdlet,
                 Func`2 createAndStartTask)
                    at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by Sandido** [comment]
In PS, the name for the image UbuntuLTS maps to the info seen in the error:
"UbuntuLTS":  {
                                    "publisher":  "Canonical",
                                    "offer":  "UbuntuServer",
                                    "sku":  "20.04-LTS",
                                    "version":  "latest"
                                }
And when I check if the 20.04-LTS sku under the UbuntuServer offer exists, 
'$skus = az vm image list --all --offer UbuntuLTS --sku 20.04-LTS'
it seems like it is not available. 

I will inquire if this is a temporary or permanent issue.

**Comment by mikefrobbins** [comment]
@Sandido The `--image UbuntuLTS` option works without issue using the Azure CLI.

**Comment by WarGloom** [comment]
bump?

**Comment by Sandido** [comment]
@mikefrobbins ,
The PS UbuntuLTS alias has been reverted back to its original value (Canonical:UbuntuServer:16.04-LTS:latest) for now and works. The fix will be released in the coming days in the Az.Compute PS module version 5.4.0. 
CLI uses 18.04.
We are discussing a sooner update, but at least in the next PS breaking change release, should be around May, the PS and CLI values will be updated to more recent values (20 or 22_04).

**Comment by WarGloom** [comment]
Thank you
 the fix  works as expected.
