### ISSUE TITLE
Set-AzSqlServerAudit not working for configuring Eventhub auditing: 'operation not supported...'

### ISSUE THREAD

**Issue by kmoninsis** [Azure/azure-powershell#20730]
### Description

We cannot update the SQL server Eventhub auditing with set-AzSqlServerAudit cmdlet anymore.
This seems to be happening since az.sql version 4.2.0 (also LogAnalytics auditing not working, see #20703 )

### Issue script & Debug output

```PowerShell
Set-AzSqlServerAudit -ResourceGroupName $resourcegroup -Servername $resourcename -EventHubTargetState Enabled -EventHubName $eventhubname -EventHubAuthorizationRuleResourceId $eventhubresourceid

Error: Operation is not supported when multiple Diagnostic Settings enable SQLSecurityAuditEvents
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.11.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.2.0                 AZ.sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElasticJobStep, Add-AzSqlElasticJobTarget, Add-AzSqlInsta…
```

### Error output

```PowerShell
Message        : Operation is not supported when multiple Diagnostic Settings enable SQLSecurityAuditEvents
TargetSite     : Void VerifyAuditBeforePersistChanges(AuditModelType)
Data           : {}
InnerException :
HelpLink       :
Source         : Microsoft.Azure.PowerShell.Cmdlets.Sql
HResult        : -2146233088
StackTrace     :    at Microsoft.Azure.Commands.Sql.Auditing.Services.SqlAuditAdapter`2.VerifyAuditBeforePersistChanges(AuditModelType model)
                    at Microsoft.Azure.Commands.Sql.Auditing.Services.SqlAuditAdapter`2.PersistAuditChanges(AuditModelType model)
                    at Microsoft.Azure.Commands.Sql.Auditing.Cmdlet.SetSqlServerAuditCmdlet`3.PersistChanges(ServerAuditModelType entity)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
                    at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by SaurabhSharma-MSFT** [comment]
@kmoninsis We are looking into it and get back to you for any additional information.

**Comment by kmoninsis** [comment]
Hi, it seems the issue was not related to the cmdlet. Rather, there were Diagnostic Settings already applied to the **database**, which I first had to remove in order to successfully configure the **server** auditing settings.
