### ISSUE TITLE
[Feature]: Improve New-AzSubscriptionAlias error handling

### ISSUE THREAD

**Issue by dbaileyut** [Azure/azure-powershell#20812]
### Description of the new feature

Handle the error when New-AzSubscriptionAlias is run without the -Workload parameter with a more informative message, make the parameter required, or add a default.

```
New-AzSubscriptionAlias -AliasName MyTestAlias -BillingScope '/providers/Microsoft.Billing/billingAccounts/XXXXXX/enrollmentAccounts/XXXXXX' -SubscriptionName MysSubscription
New-AzSubscriptionAlias: Operation returned an invalid status code 'BadRequest'
```
This error isn't very helpful. If I add `-Workload Production`, the command succeeds.

Az.Subscription module version: 0.8.1
```
> $Error[0].Exception   

Request        : Microsoft.Rest.HttpRequestMessageWrapper
Response       : Microsoft.Rest.HttpResponseMessageWrapper
Body           : Microsoft.Azure.Management.Subscription.Models.ErrorResponseBody
TargetSite     : Void MoveNext()
Message        : Operation returned an invalid status code 'BadRequest'
Data           : {}
InnerException : 
HelpLink       : 
Source         : Microsoft.Azure.Management.Subscription
HResult        : -2146233088
StackTrace     :    at Microsoft.Azure.Management.Subscription.AliasOperations.BeginCreateWithHttpMessagesAsync(String aliasName, PutAliasRequest body, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Subscription.AliasOperations.CreateWithHttpMessagesAsync(String aliasName, PutAliasRequest body, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Subscription.AliasOperationsExtensions.CreateAsync(IAliasOperations operations, String aliasName, PutAliasRequest body, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Subscription.AliasOperationsExtensions.Create(IAliasOperations operations, String aliasName, PutAliasRequest body)
                    at Microsoft.Azure.Commands.Subscription.Cmdlets.NewAzureRmSubscriptionAlias.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ΓÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by dingmeng-xue** [comment]
@dbaileyut , thanks for contacting us. Please turn on debug log and check service response. If you have question, please share response to us. You can turn on debug via `$DebugPreference = "Continue"`

**Comment by dbaileyut** [comment]
```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
mise-correlation-id           : xxxxxxx
MS-CV                         : bOPwaw8NcEuS1QvttAhacA.0
x-ms-correlation-request-id   : xxxxxxx
Request-Id                    : xxxxxxx
x-gsm                         : 1.0.0.0
X-Content-Type-Options        : nosniff
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-tenant-writes: 1199
x-ms-request-id               : xxxxxxx
x-ms-routing-request-id       : SOUTHCENTRALUS:20230201T160628Z:xxxxxxx
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Date                          : Wed, 01 Feb 2023 16:06:27 GMT

Body:
{
  "error": {
    "code": "InvalidWorkLoad",
    "message": "Invalid WorkLoad provided, Only Production or DevTest are allowed"
  },
  "code": "InvalidWorkLoad",
  "message": "Invalid WorkLoad provided, Only Production or DevTest are allowed"
}

```

**Comment by navba-MSFT** [comment]
@dbaileyut Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
