### ISSUE TITLE
New-AzApplicationGateway doesn't support creating WAF_v2 Tier with Managed Identity

### ISSUE THREAD

**Issue by david-eagles** [Azure/azure-powershell#20910]
### Description

The Identity-based parameter sets (IdentityByUserAssignedIdentityId and IdentityByIdentityObject) for New-AzApplicationGateway don't include either the FirewallPolicyId or FirewallPolicy parameters (but they do support the ForceFirewallPolicyAssociation parameter) so trying to create a WAF_v2 app gateway with a managed identity results in a ParameterBindingException (parameter set cannot be resolved...).

### Issue script & Debug output

```PowerShell
# Lots of unrelated preliminary app gw setup commands removed for brevity...
$params = @{
    Name = $appGwName
    ResourceGroupName = $resourceGroupName
    Location = $locationName
    Identity = $appGwIdentity
    Sku = $appGwStandard2Sku
    EnableHttp2 = $true
    SSLCertificates = $tlsCertificates
    SSLPolicy = $tlsPolicy
    FirewallPolicy = $appGwFirewallPolicy
    GatewayIpConfigurations = $appGwIpConfigs
    FrontendIpConfigurations = $frontEndIpConfigs
    FrontendPorts = $frontEndPorts
    HttpListeners = $httpListeners
    BackendAddressPools = $backEndPools
    BackendHttpSettingsCollection = $backEndHttpSettings
    UrlPathMaps = $urlPathMaps
    RequestRoutingRules = $routingRules
    Tag = $tags
}
$DebugPreference='Continue'
New-AzApplicationGateway @params

New-AzApplicationGateway : Parameter set cannot be resolved using the specified named parameters.
At Test.ps1:232 char:10
+ New-AzApplicationGateway @params
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzApplicationGateway], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Azure.Commands.Network.NewAzureApplicationGatewayCommand
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.22621.963                                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.22621.963                                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                                  
Script     2.11.2     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}                                                                          
Script     4.9.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzKeyVaultManagedStorageAccount...}                          
Script     1.1.0      Az.ManagedServiceIdentity           {Get-AzFederatedIdentityCredentials, Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity, Get-AzUserAssignedIdentityAssociatedResource...}   
Script     5.4.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add...
```

### Error output

```PowerShell
Message        : Parameter set cannot be resolved using the specified named parameters.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.ThrowAmbiguousParameterSetException(UInt32 parameterSetFlags, MergedCommandParameterMetadata bindableParameters)
                    at System.Management.Automation.CmdletParameterBinderController.ValidateParameterSets(Boolean prePipelineInput, Boolean setDefault)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzApplicationGateway}
Line           : New-AzApplicationGateway @params
```

**Comment by david-eagles** [comment]
Since FirewallPolicy is a required parameter to create a WAF_v2 app gateway instance, the current workaround to this is to create the app gateway as a Standard_v2 tier, omitting the FirewallPolicy parameter, then upgrade the instance to WAF_v2 and supply the FirewallPolicy as a second stage.

It would much easier to do this in one operation, and since the identity-bases parameter sets already support the ForceFirewallPolicyAssociation parameter, I assumed their lack of support for the FirewallPolicy parameter is a mistake.

**Comment by isra-fel** [comment]
Thanks for reporting. Routing this to the correct team.
