### ISSUE TITLE
New-AzWvdHostPool Cannot bind argument to parameter 'Name' because it is an empty string

### ISSUE THREAD

**Issue by gh-d-z** [Azure/azure-powershell#21046]
### Description

I am trying to execute the command 
`New-AzWvdHostPool -ResourceGroupName $ResourceGroupName -Name $hostPoolName -Location $location -PreferredAppGroupType "RailApplications" -HostPoolType "Pooled" -LoadBalancerType "BreadthFirst" -WorkspaceName $workspaceName`
and getting the error
`Cannot bind argument to parameter 'Name' because it is an empty string.`
I know that the resource is being created, and the name is not an empty string, because I can see the newly created HostPool in the Azure Portal. 
The activity log of the Resource Group also shows the operation 'Write HostPools' has a status of 'Succeeded'

### Issue script & Debug output

```PowerShell
create_hostpool.ps1:
Line |
     |  New-AzWvdHostPool -ResourceGroupName $ResourceGroupName -Name $hostPo …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Name' because it is an empty string.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.2.9
PSEdition                      Core
GitCommitId                    7.2.9
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.11.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContex… 
Script     3.1.0                 Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImag…
```

### Error output

```PowerShell
Message        : Cannot bind argument to parameter 'Name' because it is an empty string.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)      
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame     
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame     
                 frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {New-AzWvdHostPool}
Line           :     New-AzWvdHostPool -ResourceGroupName $ResourceGroupName -Name $hostPoolName -Location $location     
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar,     
                 Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {New-AzWvdApplicationGroup}
Line           :         $applicationGroup = Az.DesktopVirtualization\New-AzWvdApplicationGroup @PSBoundParameters `     

Position       : At C:\Users\user\PowerShell\Modules\Az.DesktopVirtualization\3.1.0\c 
                 ustom\New-AzWvdHostPool_FullSenerioCreate.ps1:118 char:80
                 + … .DesktopVirtualization\New-AzWvdApplicationGroup @PSBoundParameters `
                 +                                                    ~~~~~~~~~~~~~~~~~~
HistoryId      : 5
```

**Comment by SaurabhSharma-MSFT** [comment]
@gh-d-z We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@gh-d-z I am not able to reproduce this issue.  
![image](https://user-images.githubusercontent.com/38112130/224386488-06404bdc-adda-4639-b035-931717f80d79.png)
Please try upgrading your `Az.DesktopVirtualization` module.

**Comment by SaurabhSharma-MSFT** [comment]
@gh-d-z Please let us know if you need any further help on this issue.
