### ISSUE TITLE
Key Vault cmdlets fail when run in non-interactive environment

### ISSUE THREAD

**Issue by seanbamsft** [Azure/azure-powershell#2105]
ADAL fails to get a token for AAD Graph or Key Vault service when the Key Vault cmdlets are run from Azure Automation. The trace logs show:

`Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 :  AsyncMethodBuilderCore: 
System.EntryPointNotFoundException: Unable to find an entry point named 'GetPerAdapterInfo' in DLL 'iphlpapi.dll'.
at System.Net.NetworkInformation.UnsafeNetInfoNativeMethods.GetPerAdapterInfo(UInt32 IfIndex, SafeLocalFree 
pPerAdapterInfo, UInt32& pOutBufLen)
at System.Net.NetworkInformation.SystemIPv4InterfaceProperties.GetPerAdapterInfo(UInt32 index)
at System.Net.NetworkInformation.SystemIPv4InterfaceProperties..ctor(FixedInfo fixedInfo, IpAdapterAddresses 
ipAdapterAddresses)
at System.Net.NetworkInformation.SystemIPInterfaceProperties..ctor(FixedInfo fixedInfo, IpAdapterAddresses 
ipAdapterAddresses)
at System.Net.NetworkInformation.SystemNetworkInterface..ctor(FixedInfo fixedInfo, IpAdapterAddresses 
ipAdapterAddresses)
at System.Net.NetworkInformation.SystemNetworkInterface.GetNetworkInterfaces()
at System.Net.NetworkInformation.SystemNetworkInterface.InternalGetIsNetworkAvailable()
at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WebUI.Authenticate(Uri requestUri, Uri callbackUri)
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.<AcquireAuthorization>b__0()
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.AcquireAuthorization()
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.PreTokenRequest()
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()`

**Comment by seanbamsft** [comment]
[This change](https://github.com/seanbamsft/azure-powershell/commit/bbbe209f585ba1fd3559293409ec355e29e19b12) appears to fix the issue. Due to the regression risk in changing authentication code, I'll need to test this with a variety of subscriptions, account types, and interactive/non-interactive sessions before submitting a PR.

**Comment by slapointe** [comment]
@markcowl do you have an ETA when this will be released? We hit this problem yesterday and it is a major blocker for us in our automation strategy w/ KeyVault.

Thanks
