### ISSUE TITLE
New-AzADApplication: A parameter cannot be found that matches parameter name 'SPARedirectUri'

### ISSUE THREAD

**Issue by vlnzr** [Azure/azure-powershell#21108]
### Description

When running cmdlet New-AzADApplication (Az.Resource Module v. 6.5.2)  I keep getting below error:
New-AzADApplication: A parameter cannot be found that matches parameter name 'SPARedirectUri'

### Issue script & Debug output

```PowerShell
$DebugPreference='Continue'
New-AzADApplication -DisplayName $ExcelDisplayName `
                    -HomePage $homePage `
                    -IdentifierUris $excelAppIdUri `
                    -SPARedirectUri $excelRedirectUrl `
                    -Web $excelWebSetting `
                    -RequiredResourceAccess $excelResources `
                    -ErrorAction Stop -ErrorVariable result | out-null
New-AzADApplication : A parameter cannot be found that matches parameter name 'SPARedirectUri'.
At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\6.5.2\MSGraph.Autorest\exports\ProxyCmdletDefinitions.ps1:5011 char:23
+         $scriptCmd = {& $wrappedCmd @PSBoundParameters}
+                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-AzADApplication], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,New-AzADApplication
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.2364
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2364
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version Name
---------- ------- ----
    Script 2.11.2  Az.Accounts
    Script 6.5.2   Az.Resources
```

### Error output

```PowerShell
HistoryId: 2


Message        : A parameter cannot be found that matches parameter name 'SPARedirectUri'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
                    at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzADApplication}
Line           :     $app = Az.MSGraph.internal\New-AzADApplication @PSBoundParameters

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Resources\6.5.2\MSGraph.Autorest\custom\New-AzADApplication.ps1:689 char:52
                 +     $app = Az.MSGraph.internal\New-AzADApplication @PSBoundParameters
                 +                                                    ~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : The specified module 'C:\Program Files\DesiredStateConfiguration\1.0.0.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1' was not loaded because no valid module file 
                 was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :
Position       :
HistoryId      : 2

Message        : The specified module 'C:\Program Files\DesiredStateConfiguration\1.0.0.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1' was not loaded because no valid module file     
                 was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :
Position       :
HistoryId      : 2

Message        : The specified module 'C:\Program Files\DesiredStateConfiguration\1.0.0.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1' was not loaded because no valid module file     
                 was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :
Position       :
HistoryId      : 2



   HistoryId: 1


Message        : The specified module 'C:\Program Files\DesiredStateConfiguration\1.0.0.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1' was not loaded because no valid module file 
                 was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :
Position       :
HistoryId      : 1

Message        : The specified module 'C:\Program Files\DesiredStateConfiguration\1.0.0.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1' was not loaded because no valid module file     
                 was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           : 
Position       :
HistoryId      : 1

Message        : The specified module 'C:\Program Files\DesiredStateConfiguration\1.0.0.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psd1' was not loaded because no valid module file     
                 was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :
Position       :
HistoryId      : 1
```

**Comment by isra-fel** [comment]
Thanks for reporting :)
Hi @VeryEarly could you investigate this issue? Thanks.

**Comment by VeryEarly** [comment]
Hi @vlnzr ,

-SPARedirectUri cannot be used with 'HomePage' or 'ReplyUrls', the error message doesn't make sense indeed, will throw something more meaningful.
