### ISSUE TITLE
Object reference not set to an instance of an object - Set-AzBatchPool

### ISSUE THREAD

**Issue by xenon8** [Azure/azure-powershell#21116]
### Description

The code below results in a null reference exception, I do not understand why as all I am doing is setting it to itself. Note, I would like to update some settings in the pool but I am providing the simplest of examples.

```powershell
$context = Get-AzBatchAccount -ResourceGroupName "MyResourceGroup"
$pool = Get-AzBatchPool -id MyPool -BatchContext $Context 

Set-AzBatchPool -Pool $pool -BatchContext $context -Verbose
```

results in 

VERBOSE: 07:40:10 - Using Azure Active Directory authentication to interact with the Batch service. To use shared key authentication, supply a BatchAccountContext that was returned from the Get-AzBatchAccountKeys cmdlet.
VERBOSE: 07:40:10 - Updating pool MyPool.
Set-AzBatchPool : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-AzBatchPool -Pool $pool -BatchContext $context -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzBatchPool], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Batch.SetBatchPoolCommand

I do not understand why it is throwing this error. I am using Az PowerShell modules 9.4.0. I rebooted after installing them.

### Issue script & Debug output

```PowerShell
$context = Get-AzBatchAccount -ResourceGroupName "MyResourceGroup"
$pool = Get-AzBatchPool -id MyPool -BatchContext $Context 

Set-AzBatchPool -Pool $pool -BatchContext $context -Verbose


DEBUG: 07:49:55 - SetBatchPoolCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 07:49:55 - using account id 'redacted'...
DEBUG: 07:49:55 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
VERBOSE: 07:49:55 - Using Azure Active Directory authentication to interact with the Batch service. To use shared key authentication, supply a BatchAccountC
ontext that was returned from the Get-AzBatchAccountKeys cmdlet.
DEBUG: [Common.Authentication]: Authenticating using Account: 'redacted', environment: 'AzureCloud', tenant: 'redacted'
DEBUG: 07:49:55 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'redacted', Scopes:'https://
management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'redacted'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - b136afb5-f7f7-49ce-acad-9dea6114cfe2] IsLegacyAdalCacheEn
abled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - b136afb5-f7f7-49ce-acad-9dea6114cfe2] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - b136afb5-f7f7-49ce-acad-9dea6114cfe2] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - b136afb5-f7f7-49ce-acad-9dea6114cfe2] IsLegacyAdalCacheEn
abled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - b136afb5-f7f7-49ce-acad-9dea6114cfe2] IsLegacyAdalCacheEn
abled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] [WamBroker] WAM supported OS.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] [WamBroker] ListWindowsWorkAndSchoolAccounts option was no
t enabled.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - e3927024-0093-4666-857c-45e85af59a82] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] MSAL MSAL.Desktop w
ith assembly version '4.49.1.0'. CorrelationId(195f5863-d390-47b6-96bf-e5bd60f011d5)
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] === AcquireTokenSil
ent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] LoginHint provided:
 False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] Account provided: T
rue
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - True
HomeAccountId - False
CorrelationId - 195f5863-d390-47b6-96bf-e5bd60f011d5
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] === Token Acquisiti
on (SilentRequest) started:
	 Scopes: https://management.core.windows.net//.default
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] Access token is not
 expired. Returning the found cache entry. [Current time (03/03/2023 07:49:55) - Expiration Time (03/03/2023 09:02:44 +00:00) - Extended Expiration Time (03
/03/2023 09:02:44 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] Returning access to
ken found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5] 
	=== Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 195f5863-d390-47b6-96bf-e5bd60f011d5]  AT expiration time
: 03/03/2023 09:02:44 +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-03-03T09:0
2:44.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'redacted', UserId: 'redacted'
DEBUG: [Common.Authentication]: Authenticating using Account: 'redacted', environment: 'AzureCloud', tenant: 'redacted'
DEBUG: 07:49:55 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'redacted', Scopes:'https://
management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'redacted'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - aaaa77b9-2a18-4a70-af45-f5398b616dd4] IsLegacyAdalCacheEn
abled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - aaaa77b9-2a18-4a70-af45-f5398b616dd4] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - aaaa77b9-2a18-4a70-af45-f5398b616dd4] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - aaaa77b9-2a18-4a70-af45-f5398b616dd4] IsLegacyAdalCacheEn
abled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - aaaa77b9-2a18-4a70-af45-f5398b616dd4] IsLegacyAdalCacheEn
abled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] [WamBroker] WAM supported OS.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] [WamBroker] ListWindowsWorkAndSchoolAccounts option was no
t enabled.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - e923a5cf-cbf9-4462-b485-cfc7eaad1265] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] MSAL MSAL.Desktop w
ith assembly version '4.49.1.0'. CorrelationId(66a520d4-e9a7-4e57-b58a-18c7fb38110d)
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] === AcquireTokenSil
ent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] LoginHint provided:
 False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] Account provided: T
rue
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - True
HomeAccountId - False
CorrelationId - 66a520d4-e9a7-4e57-b58a-18c7fb38110d
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] === Token Acquisiti
on (SilentRequest) started:
	 Scopes: https://management.core.windows.net//.default
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] Access token is not
 expired. Returning the found cache entry. [Current time (03/03/2023 07:49:55) - Expiration Time (03/03/2023 09:02:44 +00:00) - Extended Expiration Time (03
/03/2023 09:02:44 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] Returning access to
ken found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] [Region discovery] 
Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d] 
	=== Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-03-03 07:49:55Z - 66a520d4-e9a7-4e57-b58a-18c7fb38110d]  AT expiration time
: 03/03/2023 09:02:44 +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-03-03T09:0
2:44.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'redacted', UserId: 'redacted'
VERBOSE: 07:49:55 - Updating pool MyPool.
DEBUG: 07:49:55 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Set-AzBatchPool : Object reference not set to an instance of an object.
At line:1 char:1
+ Set-AzBatchPool -Pool $pool -BatchContext $context -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzBatchPool], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Batch.SetBatchPoolCommand
 
DEBUG: 07:49:55 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Batch:3.3.0; CommandName: Set-AzBatchPool; PSVersion: 5.1.19041.2364; IsSuccess: False; Duration: 00:00:00.0737070; Except
ion: Object reference not set to an instance of an object.;
DEBUG: 07:49:55 - SetBatchPoolCommand end processing.
```

### Environment data

```PowerShell
PSVersion                      5.1.19041.2364                                                                                                              
PSEdition                      Desktop                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                     
BuildVersion                   10.0.19041.2364                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                             
WSManStackVersion              3.0                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                         
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                 
---------- -------    ----                                ----------------                                                                                 
Script     2.11.2     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}                         
Script     3.3.0      Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchComputeNodeScheduling, Disable-AzBatchJob, Disable-A...
```

### Error output

```PowerShell
Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Batch.Utils.Utils.CreateSyncedDict[Tom](IDictionary psDict, Func`3 mappingFunction)
                    at Microsoft.Azure.Commands.Batch.Utils.Utils.StartTaskSyncCollections(PSStartTask startTask)
                    at Microsoft.Azure.Commands.Batch.Utils.Utils.BoundPoolSyncCollections(PSCloudPool pool)
                    at Microsoft.Azure.Commands.Batch.Models.BatchClient.UpdatePool(BatchAccountContext context, PSCloudPool pool, IEnumerable`1 
                 additionBehaviors)
                    at Microsoft.Azure.Commands.Batch.BatchCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Set-AzBatchPool}
Line           : Set-AzBatchPool -Pool $pool -BatchContext $context -Verbose
Position       : At line:1 char:1
                 + Set-AzBatchPool -Pool $pool -BatchContext $context -Verbose
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by isra-fel** [comment]
Thanks for providing the detailed info. I'll route to the support team

**Comment by navba-MSFT** [comment]
@xenon8 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@xenon8 I used the same version [Az.Batch module 3.3.0 ](https://www.powershellgallery.com/packages/Az.Batch/3.3.0)and tried running the same above code and it worked fine for me.

<img width="375" alt="image" src="https://user-images.githubusercontent.com/57353862/223418964-5a8b9d95-154e-4efa-8285-772920849c25.png">

Could you please confirm if the $context and $pool variables have returned fine ? Also open the portal and confirm that your pool is active and ready.

**Comment by xenon8** [comment]
@navba-MSFT  Hiya, thanks for getting back to us, we have managed to work out the cause.

One of the environment settings on the Start Task had no value. The portal appears to allow this to be configured but the PowerShell module does not.

Please can you update the module to deal with this scenario? Or at least give a more detailed error of what is null? So that it is obvious what the cause is?

**Comment by navba-MSFT** [comment]
@xenon8 Thanks for your reply. The [New-AzBatchTask ](https://learn.microsoft.com/en-us/powershell/module/az.batch/new-azbatchtask?view=azps-9.4.0)accepts the `EnvironmentSettings`  parameter. The default value for this is `None`. This is by-design.

You could run the [Get-AzBatchTask ](https://learn.microsoft.com/en-us/powershell/module/az.batch/get-azbatchtask?view=azps-9.4.0) PS cmdlet to check if the EnvironmentSettings is null before assinging that job task to the pool.

**Comment by navba-MSFT** [comment]
@xenon8 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@xenon8 The action is currently pending on you to try the above suggestion. If you need any further assistance on this, please feel free to reopen this thread. We would be happy to help.

**Comment by xenon8** [comment]
@navba-MSFT sorry, it has been a bit of hectic week. Yes we are happy with your proposed solution however we would like better error handling implemented when updating the Batch Account using the PS function. It is not clear what is null, especially if you are not directly working with Environment settings at the time.
