### ISSUE TITLE
New-AzureRMResourceGroupDeployment fails with DeploymentNotFound for nested deployment

### ISSUE THREAD

**Issue by antmeehan** [Azure/azure-powershell#2120]
We have a fairly complex set of linked ARM template deployments, which we use `New-AzureRMResourceGroupDeployment` to deploy (both locally and in Visual Studio Team Services).

We've started getting fairly regular failures while deploying:

````
2016-04-13T08:41:06.2976049Z ##[error]Hyak.Common.CloudException: DeploymentNotFound: Deployment 'createbusbooking-0.0.194.0' could not be found.
2016-04-13T08:41:06.2976049Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-04-13T08:41:06.2976049Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task) 
2016-04-13T08:41:06.2976049Z ##[error]   at Microsoft.Azure.Management.Resources.DeploymentOperationOperationsExtensions.List(IDeploymentOperationOperations operations, String resourceGroupName, String deploymentName, DeploymentOperationsListParameters parameters)
2016-04-13T08:41:06.3132285Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.GetNewOperations(List`1 old, IList`1 current)
2016-04-13T08:41:06.3132285Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.WriteDeploymentProgress(String resourceGroup, String deploymentName, Deployment deployment)
2016-04-13T08:41:06.3132285Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.WaitDeploymentStatus(String resourceGroup, String deploymentName, Deployment basicDeployment, Action`3 job, String[] status)
2016-04-13T08:41:06.3132285Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.ProvisionDeploymentStatus(String resourceGroup, String deploymentName, Deployment deployment)
2016-04-13T08:41:06.3132285Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.ExecuteDeployment(CreatePSResourceGroupDeploymentParameters parameters)
2016-04-13T08:41:06.3132285Z ##[error]   at Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand.ExecuteCmdlet()
2016-04-13T08:41:06.3132285Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
````

The deployment resource `createbusbooking-0.0.194.0` definitely exists, and even succeeds despite `New-AzureRMResourceGroupDeployment` throwing this exception.

Note it doesn't happen every time, but has we add more nested deployments it seem to be happening more frequently.

Looking at the code it looks like turning on the Hyak TracingAdapter may help but I'm not sure how to do that.

Any help would be much appreciated.

Thanks.

**Comment by markcowl** [comment]
@antmeehan If you set ```$DebugPreference="Continue"``` before running the failing script, this should provide additional debugging information, including the traffic between client and server, which will tell us if we're getting throttled.

@vivsriaus Anything else we can do to take a look?

**Comment by vivsriaus** [comment]
@antmeehan Can you please help us with these?
1. Ensure you're running the latest version of Azure powershell. I vaguely recall seeing this issue before and fixing it by end of last year. Irrespective, please install the latest Azure powershell and re-try the deployment.
2. If the issue still persists, please send us the actual cmdlet you're running and as Mark pointed out above, please run it with $debugPreference set to 'Continue' and send us the request/response traces, so we can look at it on our end. Thanks

cc: @ravbhatnagar

**Comment by antmeehan** [comment]
@vivsriaus We're only seeing this on Visual Studio Team Services, and the agent has:

````
PS C:\Users\ant> (get-module azure).version

Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      4      -1
````

We can't upgrade, as the agent tasks are only compatible with that version as far as I'm aware.

I'll try the `$DebugPreference="Continue"` setting now and let you know.

Thanks for your help.

**Comment by antmeehan** [comment]
I've had this fail with `$DebugPreference="Continue"` now:

````
2016-04-26T08:19:36.2585275Z ##[debug][Common.Authentication]: Checking token expiration, token expires '04/26/2016 09:11:46 +00:00' Comparing to '04/26/2016 08:19:18 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:52:28.1159365'
2016-04-26T08:19:36.2585275Z ##[debug]============================ HTTP REQUEST ============================
2016-04-26T08:19:36.2585275Z HTTP Method:
2016-04-26T08:19:36.2585275Z GET
2016-04-26T08:19:36.2585275Z Absolute Uri:
2016-04-26T08:19:36.2585275Z https://management.azure.com/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourcegroups/au-sdx-integration-apps-dev/deployments/invoicescreated-0.0.1230.0/operations?api-version=2014-04-01-preview
2016-04-26T08:19:36.2585275Z Headers:
2016-04-26T08:19:36.2585275Z Body:
2016-04-26T08:19:36.2585275Z ##[debug]============================ HTTP RESPONSE ============================
2016-04-26T08:19:36.2585275Z Status Code:
2016-04-26T08:19:36.2585275Z NotFound
2016-04-26T08:19:36.2585275Z Headers:
2016-04-26T08:19:36.2585275Z Pragma                        : no-cache
2016-04-26T08:19:36.2585275Z x-ms-failure-cause            : gateway
2016-04-26T08:19:36.2585275Z x-ms-ratelimit-remaining-subscription-reads: 14368
2016-04-26T08:19:36.2585275Z x-ms-request-id               : e460e19f-667b-446a-818d-ead01cbb7615
2016-04-26T08:19:36.2585275Z x-ms-correlation-request-id   : e460e19f-667b-446a-818d-ead01cbb7615
2016-04-26T08:19:36.2585275Z x-ms-routing-request-id       : AUSTRALIASOUTHEAST:20160426T081918Z:e460e19f-667b-446a-818d-ead01cbb7615
2016-04-26T08:19:36.2585275Z Strict-Transport-Security     : max-age=31536000; includeSubDomains
2016-04-26T08:19:36.2585275Z Cache-Control                 : no-cache
2016-04-26T08:19:36.2585275Z Date                          : Tue, 26 Apr 2016 08:19:18 GMT
2016-04-26T08:19:36.2585275Z Body:
2016-04-26T08:19:36.2585275Z {
2016-04-26T08:19:36.2585275Z   "error": {
2016-04-26T08:19:36.2585275Z     "code": "DeploymentNotFound",
2016-04-26T08:19:36.2585275Z     "message": "Deployment 'invoicescreated-0.0.1230.0' could not be found."
2016-04-26T08:19:36.2585275Z   }
2016-04-26T08:19:36.2585275Z }
2016-04-26T08:19:36.2585275Z ##[debug]8:19:36 AM - NewAzureResourceGroupDeploymentCommand end processing.
2016-04-26T08:19:36.3054213Z ##[error]Hyak.Common.CloudException: DeploymentNotFound: Deployment 'invoicescreated-0.0.1230.0' could not be found.
2016-04-26T08:19:36.3054213Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Management.Resources.DeploymentOperationOperationsExtensions.List(IDeploymentOperationOperations operations, String resourceGroupName, String deploymentName, DeploymentOperationsListParameters parameters)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.GetNewOperations(List`1 old, IList`1 current)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.WriteDeploymentProgress(String resourceGroup, String deploymentName, Deployment deployment)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.WaitDeploymentStatus(String resourceGroup, String deploymentName, Deployment basicDeployment, Action`3 job, String[] status)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.ProvisionDeploymentStatus(String resourceGroup, String deploymentName, Deployment deployment)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.ExecuteDeployment(CreatePSResourceGroupDeploymentParameters parameters)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand.<>c__DisplayClass3.<ExecuteCmdlet>b__1()
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String actionMessage, String processMessage, String target, Action action)
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand.ExecuteCmdlet()
2016-04-26T08:19:36.3210231Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
````

So it doesn't look like rate-limiting. As previously mentioned, the deployment does succeed and I can actually hit that URL using armclient and get a valid response.

`armclient get https://management.azure.com/subscriptions/9e3012dd-f3e1-4d83-****/resourcegroups/au-sdx-integration-apps-dev/deployments/invoicescreated-0.0.1230.0/operations?api-version=2014-04-01-preview`

````
{
  "value": [
    {
      "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/deployments/invoicescreated-0.0.1230.0/operations/4462FBEF9A66177B",
      "operationId": "4462FBEF9A66177B",
      "properties": {
        "provisioningState": "Succeeded",
        "timestamp": "2016-04-26T08:23:09.4912956Z",
        "duration": "PT1M52.8424032S",
        "trackingId": "b8d9a8c8-4232-43aa-a743-dbe3288a228c",
        "statusCode": "OK",
        "targetResource": {
          "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/providers/Microsoft.Resources/deployments/adapter-billing-invoicescreated-0.0.1230.0",
          "resourceType": "Microsoft.Resources/deployments",
          "resourceName": "adapter-billing-invoicescreated-0.0.1230.0"
        }
      }
    },
    {
      "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/deployments/invoicescreated-0.0.1230.0/operations/21F7A6EAFD63B20F",
      "operationId": "21F7A6EAFD63B20F",
      "properties": {
        "provisioningState": "Succeeded",
        "timestamp": "2016-04-26T08:21:34.7593903Z",
        "duration": "PT6.921443S",
        "trackingId": "71a6ffc8-e1bc-4408-b8a6-674231b7da2b",
        "statusCode": "OK",
        "targetResource": {
          "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/providers/Microsoft.ServiceBus/namespaces/au-sdx-integration-dev/Topics/InvoicesCreated/Subscriptions/audit",
          "resourceType": "Microsoft.ServiceBus/namespaces/Topics/Subscriptions",
          "resourceName": "au-sdx-integration-dev/InvoicesCreated/audit"
        }
      }
    },
    {
      "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/deployments/invoicescreated-0.0.1230.0/operations/9E1CCFF6E3F40C7A",
      "operationId": "9E1CCFF6E3F40C7A",
      "properties": {
        "provisioningState": "Succeeded",
        "timestamp": "2016-04-26T08:21:32.3730891Z",
        "duration": "PT4.5395346S",
        "trackingId": "8e85d571-c9c9-4c59-a609-d61f13c184f5",
        "statusCode": "OK",
        "targetResource": {
          "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/providers/Microsoft.ServiceBus/namespaces/au-sdx-integration-dev/Topics/InvoicesCreated/Subscriptions/bus",
          "resourceType": "Microsoft.ServiceBus/namespaces/Topics/Subscriptions",
          "resourceName": "au-sdx-integration-dev/InvoicesCreated/bus"
        }
      }
    },
    {
      "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/deployments/invoicescreated-0.0.1230.0/operations/0B7B453A7084FDAD",
      "operationId": "0B7B453A7084FDAD",
      "properties": {
        "provisioningState": "Succeeded",
        "timestamp": "2016-04-26T08:21:27.3695058Z",
        "duration": "PT10.7209267S",
        "trackingId": "de6025a7-97b2-4167-bdc8-9734bb81aee0",
        "statusCode": "OK",
        "targetResource": {
          "id": "/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourceGroups/au-sdx-integration-apps-dev/providers/Microsoft.ServiceBus/namespaces/au-sdx-integration-dev/Topics/InvoicesCreated",
          "resourceType": "Microsoft.ServiceBus/namespaces/Topics",
          "resourceName": "au-sdx-integration-dev/InvoicesCreated"
        }
      }
    }
  ]
}
````

**Comment by ravbhatnagar** [comment]
@antmeehan - A related issue on this was fixed. Can you please try and verify this using the latest PS (1.0.7) maybe?

**Comment by antmeehan** [comment]
@ravbhatnagar We're only seeing this on Visual Studio Team Services, and the agent has PS 1.0.4
We can't upgrade, as the agent tasks are only compatible with that version as far as I'm aware.

We've not seen this on our local machines, using 1.3 (that's what `(Get-Module Azure).Version` returns).

**Comment by vivsriaus** [comment]
@antmeehan This was an issue that was already fixed last December. The fix was made to not do a GET on nested deployments before they start running (ARM returns a 404 in this case). The commit for this fix is [here](https://github.com/Azure/azure-powershell/commit/ba086e8e576126a857ef556a34f2ba806d75c6c7).

As you mentioned, this error doesn't appear if you use the latest powershell version, or anything above 1.0.4. Unfortunately, there is nothing we can do to help here, besides suggesting to use the latest azure powershell version that has a fix for this very particular issue. We (the ARM powershell team) don't control what version is used by the VSTS team, so you'll have to contact them to get this resolved. Irrespective, we highly recommend our partners to update to the latest because we keep adding new features/bug fixes/cmdlets to our ARM powershell package every month.

**Comment by antmeehan** [comment]
@vivsriaus We've updated to the latest powershell and it was looking okay, but now we've hit the error again.

````
2016-04-28T08:43:44.8559055Z AzurePSCmdletsVersion= 1.3.2
````

````
2016-04-28T08:51:49.6353668Z ##[debug][Common.Authentication]: Checking token expiration, token expires '04/28/2016 09:43:29 +00:00' Comparing to '04/28/2016 08:51:48 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:51:41.4879815'
2016-04-28T08:51:49.6353668Z ##[debug]============================ HTTP REQUEST ============================
2016-04-28T08:51:49.6363675Z HTTP Method:
2016-04-28T08:51:49.6363675Z GET
2016-04-28T08:51:49.6363675Z Absolute Uri:
2016-04-28T08:51:49.6373645Z https://management.azure.com/subscriptions/9e3012dd-f3e1-4d83-b9be-*****/resourcegroups/au-sdx-integration-apps-dev/deployments/adp-0.0.1338.0/operations?api-version=2016-02-01
2016-04-28T08:51:49.6373645Z Headers:
2016-04-28T08:51:49.6383658Z Body:
2016-04-28T08:51:49.6383658Z ##[debug]============================ HTTP RESPONSE ============================
2016-04-28T08:51:49.6393669Z Status Code:
2016-04-28T08:51:49.6393669Z NotFound
2016-04-28T08:51:49.6403666Z Headers:
2016-04-28T08:51:49.6403666Z Pragma                        : no-cache
2016-04-28T08:51:49.6403666Z x-ms-failure-cause            : gateway
2016-04-28T08:51:49.6413666Z x-ms-ratelimit-remaining-subscription-reads: 14813
2016-04-28T08:51:49.6413666Z x-ms-request-id               : 84b5507c-3d61-4384-b867-690fd7c436aa
2016-04-28T08:51:49.6413666Z x-ms-correlation-request-id   : 84b5507c-3d61-4384-b867-690fd7c436aa
2016-04-28T08:51:49.6423657Z x-ms-routing-request-id       : AUSTRALIASOUTHEAST:20160428T085148Z:84b5507c-3d61-4384-b867-690fd7c436aa
2016-04-28T08:51:49.6423657Z Strict-Transport-Security     : max-age=31536000; includeSubDomains
2016-04-28T08:51:49.6433666Z Cache-Control                 : no-cache
2016-04-28T08:51:49.6433666Z Date                          : Thu, 28 Apr 2016 08:51:48 GMT
2016-04-28T08:51:49.6433666Z Body:
2016-04-28T08:51:49.6443677Z {
2016-04-28T08:51:49.6443677Z   "error": {
2016-04-28T08:51:49.6443677Z     "code": "DeploymentNotFound",
2016-04-28T08:51:49.6453668Z     "message": "Deployment 'adp-0.0.1338.0' could not be found."
2016-04-28T08:51:49.6453668Z   }
2016-04-28T08:51:49.6453668Z }
2016-04-28T08:51:49.6473664Z ##[debug]8:51:49 AM - NewAzureResourceGroupDeploymentCommand end processing.
2016-04-28T08:51:49.6473664Z ##[debug]8:51:49 AM - NewAzureResourceGroupDeploymentCommand end processing.
2016-04-28T08:51:49.6763665Z ##[error]Hyak.Common.CloudException: DeploymentNotFound: Deployment 'adp-0.0.1338.0' could not be found.
2016-04-28T08:51:49.6773688Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-04-28T08:51:49.6773688Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
2016-04-28T08:51:49.6783686Z ##[error]   at Microsoft.Azure.Management.Resources.DeploymentOperationOperationsExtensions.List(IDeploymentOperationOperations operations, String resourceGroupName, String deploymentName, DeploymentOperationsListParameters parameters)
2016-04-28T08:51:49.6793676Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.GetNewOperations(List`1 old, IList`1 current)
2016-04-28T08:51:49.6793676Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.WriteDeploymentProgress(String resourceGroup, String deploymentName, Deployment deployment)
2016-04-28T08:51:49.6803692Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.WaitDeploymentStatus(String resourceGroup, String deploymentName, Deployment basicDeployment, Action`3 job, String[] status)
2016-04-28T08:51:49.6803692Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.ProvisionDeploymentStatus(String resourceGroup, String deploymentName, Deployment deployment)
2016-04-28T08:51:49.6813683Z ##[error]   at Microsoft.Azure.Commands.Resources.Models.ResourcesClient.ExecuteDeployment(CreatePSResourceGroupDeploymentParameters parameters)
2016-04-28T08:51:49.6813683Z ##[error]   at Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand.<>c__DisplayClass3.<ExecuteCmdlet>b__1()
2016-04-28T08:51:49.6823683Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String actionMessage, String processMessage, String target, Action action)
2016-04-28T08:51:49.6823683Z ##[error]   at Microsoft.Azure.Commands.Resources.NewAzureResourceGroupDeploymentCommand.ExecuteCmdlet()
2016-04-28T08:51:49.6833681Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
````

I noticed in the [commit](https://github.com/Azure/azure-powershell/commit/ba086e8e576126a857ef556a34f2ba806d75c6c7) you referenced that it was ignoring a `BadRequest` (ie 400), but in our case it is actually returning a `NotFound` (404).

**Comment by vivsriaus** [comment]
@antmeehan can you please share the template and the parameters used in this deployment?

**Comment by antmeehan** [comment]
@vivsriaus Can I email it to you?

**Comment by vivsriaus** [comment]
@antmeehan yes please. Feel free to omit any sensitive information

**Comment by antmeehan** [comment]
Sorry what's your email address?

**Comment by vivsriaus** [comment]
@antmeehan visriniv@microsoft.com

**Comment by ravbhatnagar** [comment]
@antmeehan - Are you fine with us closing the issue now? You can re-open if you still see this issue when you migrate to 1.4.0 on VSTS. Or you can set up custom build servers and install 1.4.0 on that.

**Comment by antmeehan** [comment]
@ravbhatnagar I'm happy to have it closed. I can't test on 1.4.0 since the Azure File Copy Task on VSTS doesn't work on 1.4.0 (https://github.com/Microsoft/vsts-tasks/issues/1660). As soon as that is resolved I'll let you know here if we still hit the issue. Thanks.

**Comment by ravbhatnagar** [comment]
Closing this issue. Please re-open if this still repros on 1.4. Thanks!
