### ISSUE TITLE
Update AzFunctionApp usage of parameter -Force

### ISSUE THREAD

**Issue by emallpay01** [Azure/azure-powershell#21531]
### Description

Using the Update Az function app in a yaml build pipeline it was discovered that the -Force parameter was causing the following error

2023-04-06T08:26:04.3300752Z ##[error]A parameter cannot be found that matches parameter name 'Force'.
2023-04-06T08:26:04.4332260Z ##[error]PowerShell exited with code '1'.

This was the power shell command running in the yaml pipeline.

 Update-AzFunctionApp -Name "${{ parameters.app }}/slots/$(Environment.BranchAlias)" -ResourceGroupName ${{ parameters.resourceGroup }} -IdentityType SystemAssigned -Force

When using the command directly in power shell the -Force parameter still cannot be matched.

Update-AzFunctionApp -Name test -ResourceGroupName -testrg -IdentityType SystemAssigned -Force

Update-AzFunctionApp : A parameter cannot be found that matches parameter name 'Force'.
At line:1 char:89
+ ... e test -ResourceGroupName -testrg -IdentityType SystemAssigned -Force
+                                                                    ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-AzFunctionApp], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-AzFunctionApp

### Issue script & Debug output

```PowerShell
Update-AzFunctionApp : A parameter cannot be found that matches parameter name 'Force'.
At line:1 char:89
+ ... e test -ResourceGroupName -testrg -IdentityType SystemAssigned -Force
+                                                                    ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-AzFunctionApp], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Update-AzFunctionApp
```

### Environment data

```PowerShell
PS C:\User> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.2.7      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzA...
Script     2.0.0      Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Get-AzFun...
```

### Error output

```PowerShell
HistoryId: 9


Message        : A parameter cannot be found that matches parameter name 'Force'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingE
                 xception originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Coll
                 ection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1
                 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Update-AzFunctionApp}
Line           : Update-AzFunctionApp -Name test -ResourceGroupName -testrg -IdentityType SystemAssigned -Force
Position       : At line:1 char:89
                 + ... e test -ResourceGroupName -testrg -IdentityType SystemAssigned -Force
                 +                                                                    ~~~~~~
```

**Comment by wyunchi-ms** [comment]
Hi @emallpay01 , thanks for your feedback! The latest version of Az.Function is 4.0.6. You can find it [here](https://www.powershellgallery.com/packages/Az.Functions/4.0.6). Could you please upgrade the latest version first?

**Comment by emallpay01** [comment]
The update fixed the issue, thank you.
