### ISSUE TITLE
Enable-AzAksAddon for Monitoring returns "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by mhessaveva** [Azure/azure-powershell#21665]
### Description

When running:

Enable-AzAksAddon -Name 'Monitoring' -WorkspaceResourceId $log.ResourceId -ClusterName $akscluster.Name -ResourceGroupName $akscluster.ResourceGroupName

The commandlet errors out with "Object reference not set to an instance of an object." despite the $log.ResourceId containing a valid resource ID for the log analytics workspace (e.g. "/subscriptions/xxxxxxx/resourceGroups/rg-mhtest/providers/Microsoft.OperationalInsights/workspaces/log-mhtest")

This happens on both Az.Aks version 5.3.0 and 5.3.2 that I have tested with so far.

### Issue script & Debug output

```PowerShell
2023-04-27T16:19:50.8959945Z [33;1mDEBUG:  405+          >>>> Enable-AzAksAddon -Name 'Monitoring' -WorkspaceResourceId $log.ResourceId -ClusterName $akscluster.Name -ResourceGroupName $akscluster.ResourceGroupName
2023-04-27T16:19:50.8960671Z [0m
2023-04-27T16:19:50.9082377Z [33;1mDEBUG: 9:19:50 AM - EnableAzureRmAddons begin processing with ParameterSet 'defaultParameterSet'.[0m
2023-04-27T16:19:50.9083714Z [33;1mDEBUG: 9:19:50 AM - using account id '***'...[0m
2023-04-27T16:19:50.9084393Z [33;1mDEBUG: 9:19:50 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].[0m
2023-04-27T16:19:51.6028929Z [33;1mDEBUG: [Common.Authentication]: Authenticating using Account: '***', environment: 'AzureCloud', tenant: 'xxxxx'[0m
2023-04-27T16:19:51.6032652Z [33;1mDEBUG: 9:19:50 AM - [ServicePrincipalAuthenticator] Calling ClientSecretCredential.GetTokenAsync - ApplicationId:'***', TenantId:'xxxxxxx', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/'[0m
2023-04-27T16:19:51.6034726Z [33;1mDEBUG: ClientSecretCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: [0m
2023-04-27T16:19:51.6036767Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:50Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] MSAL MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(991b69c0-638a-4a27-8b20-37e79d0e3157)[0m
2023-04-27T16:19:51.6039199Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:50Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] === AcquireTokenForClientParameters ===
2023-04-27T16:19:51.6039901Z SendX5C: False
2023-04-27T16:19:51.6040204Z ForceRefresh: False
2023-04-27T16:19:51.6040600Z [0m
2023-04-27T16:19:51.6043308Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:50Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] 
2023-04-27T16:19:51.6044518Z === Request Data ===
2023-04-27T16:19:51.6044870Z Authority Provided? - True
2023-04-27T16:19:51.6045279Z Scopes - https://management.core.windows.net//.default
2023-04-27T16:19:51.6045682Z Extra Query Params Keys (space separated) - 
2023-04-27T16:19:51.6046063Z ApiId - AcquireTokenForClient
2023-04-27T16:19:51.6049866Z IsConfidentialClient - True
2023-04-27T16:19:51.6050588Z SendX5C - False
2023-04-27T16:19:51.6050916Z LoginHint ? False
2023-04-27T16:19:51.6051260Z IsBrokerConfigured - False
2023-04-27T16:19:51.6052620Z HomeAccountId - False
2023-04-27T16:19:51.6053848Z CorrelationId - 991b69c0-638a-4a27-8b20-37e79d0e3157
2023-04-27T16:19:51.6054905Z UserAssertion set: False
2023-04-27T16:19:51.6055257Z LongRunningOboCacheKey set: False
2023-04-27T16:19:51.6055607Z Region configured: 
2023-04-27T16:19:51.6055880Z [0m
2023-04-27T16:19:51.6056593Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:50Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] === Token Acquisition (ClientCredentialRequest) started:
2023-04-27T16:19:51.6057345Z 	 Scopes: https://management.core.windows.net//.default
2023-04-27T16:19:51.6057756Z 	Authority Host: login.microsoftonline.com[0m
2023-04-27T16:19:51.6058527Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:50Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] [Instance Discovery] Instance discovery is enabled and will be performed[0m
2023-04-27T16:19:51.6060439Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:50Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] [Region discovery] Not using a regional authority. [0m
2023-04-27T16:19:51.6061756Z [33;1mDEBUG: Request [b6073cfc-c249-40da-8b28-1af384df85fa] POST https://login.microsoftonline.com/a445ee81-2b91-4806-883b-1dc673d59147/oauth2/v2.0/token
2023-04-27T16:19:51.6062931Z x-client-SKU:REDACTED
2023-04-27T16:19:51.6063325Z x-client-Ver:REDACTED
2023-04-27T16:19:51.6063693Z x-client-CPU:REDACTED
2023-04-27T16:19:51.6064047Z x-client-OS:REDACTED
2023-04-27T16:19:51.6064408Z x-client-current-telemetry:REDACTED
2023-04-27T16:19:51.6065133Z x-client-last-telemetry:REDACTED
2023-04-27T16:19:51.6065607Z x-ms-lib-capability:REDACTED
2023-04-27T16:19:51.6066000Z client-request-id:REDACTED
2023-04-27T16:19:51.6066368Z return-client-request-id:REDACTED
2023-04-27T16:19:51.6066867Z x-app-name:REDACTED
2023-04-27T16:19:51.6067190Z x-app-ver:REDACTED
2023-04-27T16:19:51.6067622Z x-ms-client-request-id:xxxxxxx
2023-04-27T16:19:51.6068963Z x-ms-return-client-request-id:true
2023-04-27T16:19:51.6069490Z User-Agent:azsdk-net-Identity/1.6.1,(.NET 7.0.0; Microsoft Windows 10.0.17763)
2023-04-27T16:19:51.6069994Z Content-Type:application/x-www-form-urlencoded
2023-04-27T16:19:51.6070672Z client assembly: Azure.Identity[0m
2023-04-27T16:19:51.6071917Z [33;1mDEBUG: Response [b6073cfc-c249-40da-8b28-1af384df85fa] 200 OK (00.1s)
2023-04-27T16:19:51.6072837Z Cache-Control:no-store, no-cache
2023-04-27T16:19:51.6073583Z Pragma:no-cache
2023-04-27T16:19:51.6074066Z Strict-Transport-Security:REDACTED
2023-04-27T16:19:51.6074461Z X-Content-Type-Options:REDACTED
2023-04-27T16:19:51.6074812Z P3P:REDACTED
2023-04-27T16:19:51.6075131Z client-request-id:REDACTED
2023-04-27T16:19:51.6075560Z x-ms-request-id:xxxxx
2023-04-27T16:19:51.6076273Z x-ms-ests-server:REDACTED
2023-04-27T16:19:51.6076648Z x-ms-clitelem:REDACTED
2023-04-27T16:19:51.6076991Z X-XSS-Protection:REDACTED
2023-04-27T16:19:51.6077363Z Set-Cookie:REDACTED
2023-04-27T16:19:51.6077740Z Date:Thu, 27 Apr 2023 16:19:50 GMT
2023-04-27T16:19:51.6078899Z Content-Type:application/json; charset=utf-8
2023-04-27T16:19:51.6079304Z Expires:-1
2023-04-27T16:19:51.6079608Z Content-Length:1400
2023-04-27T16:19:51.6079936Z [0m
2023-04-27T16:19:51.6080652Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] ScopeSet was missing from the token response, so using developer provided scopes in the result. [0m
2023-04-27T16:19:51.6081773Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] Checking client info returned from the server..[0m
2023-04-27T16:19:51.6082766Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] Saving token response to cache..[0m
2023-04-27T16:19:51.6083772Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] [SaveTokenResponseAsync] ID Token not present in response. [0m
2023-04-27T16:19:51.6084859Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] Cannot determine home account id - or id token or no client info and no subject [0m
2023-04-27T16:19:51.6085994Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] [SaveTokenResponseAsync] Saving AT in cache and removing overlapping ATs...[0m
2023-04-27T16:19:51.6087184Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] Looking for scopes for the authority in the cache which intersect with https://management.core.windows.net//.default[0m
2023-04-27T16:19:51.6088947Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] Intersecting scope entries count - 0[0m
2023-04-27T16:19:51.6089955Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] 
2023-04-27T16:19:51.6090586Z 	=== Token Acquisition finished successfully:[0m
2023-04-27T16:19:51.6091451Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157]  AT expiration time: 4/28/2023 3:19:50 PM +00:00, scopes: https://management.core.windows.net//.default. source: IdentityProvider[0m
2023-04-27T16:19:51.6092654Z [33;1mDEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.0 Microsoft Windows 10.0.17763 [2023-04-27 16:19:51Z - 991b69c0-638a-4a27-8b20-37e79d0e3157] Fetched access token from host login.microsoftonline.com. [0m
2023-04-27T16:19:51.6093636Z [33;1mDEBUG: ClientSecretCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-04-28T15:19:50.0165391+00:00[0m
2023-04-27T16:19:51.6096173Z [33;1mDEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'xxxxx', UserId: '***'[0m
2023-04-27T16:19:51.6096813Z [33;1mDEBUG: ============================ HTTP REQUEST ============================
2023-04-27T16:19:51.6097051Z 
2023-04-27T16:19:51.6097335Z HTTP Method:
2023-04-27T16:19:51.6097616Z GET
2023-04-27T16:19:51.6097714Z 
2023-04-27T16:19:51.6097967Z Absolute Uri:
2023-04-27T16:19:51.6099886Z https://management.azure.com/subscriptions/28fb33dd-25f0-49a0-926f-72236b87290b/resourceGroups/rg-mhtest/providers/Microsoft.ContainerService/managedClusters/aks-mh-test?api-version=2022-09-01
2023-04-27T16:19:51.6101486Z 
2023-04-27T16:19:51.6101795Z Headers:
2023-04-27T16:19:51.6102093Z Accept-Language               : en-US
2023-04-27T16:19:51.6102517Z x-ms-client-request-id        : xxxxxxx
2023-04-27T16:19:51.6102719Z 
2023-04-27T16:19:51.6102978Z Body:
2023-04-27T16:19:51.6103081Z 
2023-04-27T16:19:51.6103180Z 
2023-04-27T16:19:51.6103436Z [0m
2023-04-27T16:19:51.6103828Z [33;1mDEBUG: ============================ HTTP RESPONSE ============================
2023-04-27T16:19:51.6104334Z 
2023-04-27T16:19:51.6104822Z Status Code:
2023-04-27T16:19:51.6105343Z OK
2023-04-27T16:19:51.6105443Z 
2023-04-27T16:19:51.6105710Z Headers:
2023-04-27T16:19:51.6106006Z Cache-Control                 : no-cache
2023-04-27T16:19:51.6106353Z Pragma                        : no-cache
2023-04-27T16:19:51.6106843Z x-ms-routing-request-id       : WESTUS:20230427T161951Z:e955deb9-2d8b-46e6-8717-63d648a0f479
2023-04-27T16:19:51.6107361Z x-ms-ratelimit-remaining-subscription-reads: 11995
2023-04-27T16:19:51.6107836Z x-ms-correlation-request-id   : xxxxxx
2023-04-27T16:19:51.6109818Z x-ms-request-id               : xxxxxx
2023-04-27T16:19:51.6110382Z Strict-Transport-Security     : max-age=31536000; includeSubDomains
2023-04-27T16:19:51.6110806Z X-Content-Type-Options        : nosniff
2023-04-27T16:19:51.6111144Z Server                        : nginx
2023-04-27T16:19:51.6111526Z Date                          : Thu, 27 Apr 2023 16:19:51 GMT
2023-04-27T16:19:51.6111849Z 
2023-04-27T16:19:51.6112503Z Body:
2023-04-27T16:19:51.6112798Z {
2023-04-27T16:19:51.6113343Z   "id": "/subscriptions/xxxxxxxx/resourcegroups/rg-mhtest/providers/Microsoft.ContainerService/managedClusters/aks-mh-test",
2023-04-27T16:19:51.6113865Z   "location": "westus",
2023-04-27T16:19:51.6114249Z   "name": "aks-mh-test",
2023-04-27T16:19:51.6114897Z   "tags": {
2023-04-27T16:19:51.6115222Z     "Creation Date": "04/27/2023",
2023-04-27T16:19:51.6115556Z     "Description": "MH Test Cluster",
2023-04-27T16:19:51.6115934Z     "Owner eMail": "xxxxx@aveva.com",
2023-04-27T16:19:51.6116281Z     "Team": "OpsGuild"
2023-04-27T16:19:51.6116548Z   },
2023-04-27T16:19:51.6116904Z   "type": "Microsoft.ContainerService/ManagedClusters",
2023-04-27T16:19:51.6117262Z   "properties": {
2023-04-27T16:19:51.6117596Z     "provisioningState": "Succeeded",
2023-04-27T16:19:51.6118484Z     "powerState": {
2023-04-27T16:19:51.6118909Z       "code": "Running"
2023-04-27T16:19:51.6119444Z     },
2023-04-27T16:19:51.6120109Z     "kubernetesVersion": "1.25.6",
2023-04-27T16:19:51.6120488Z     "currentKubernetesVersion": "1.25.6",
2023-04-27T16:19:51.6120984Z     "dnsPrefix": "aksmhtst",
2023-04-27T16:19:51.6121355Z     "fqdn": "aksmhtst-pkueylea.hcp.westus.azmk8s.io",
2023-04-27T16:19:51.6121895Z     "azurePortalFQDN": "aksmhtst-pkueylea.portal.hcp.westus.azmk8s.io",
2023-04-27T16:19:51.6123192Z     "agentPoolProfiles": [
2023-04-27T16:19:51.6123521Z       {
2023-04-27T16:19:51.6123810Z         "name": "default",
2023-04-27T16:19:51.6124091Z         "count": 3,
2023-04-27T16:19:51.6124417Z         "vmSize": "standard_d2s_v4",
2023-04-27T16:19:51.6124731Z         "osDiskSizeGB": 30,
2023-04-27T16:19:51.6125058Z         "osDiskType": "Managed",
2023-04-27T16:19:51.6125696Z         "kubeletDiskType": "OS",
2023-04-27T16:19:51.6126020Z         "maxPods": 30,
2023-04-27T16:19:51.6126883Z         "type": "VirtualMachineScaleSets",
2023-04-27T16:19:51.6127266Z         "maxCount": 3,
2023-04-27T16:19:51.6127572Z         "minCount": 3,
2023-04-27T16:19:51.6127875Z         "enableAutoScaling": true,
2023-04-27T16:19:51.6128863Z         "provisioningState": "Succeeded",
2023-04-27T16:19:51.6129221Z         "powerState": {
2023-04-27T16:19:51.6129524Z           "code": "Running"
2023-04-27T16:19:51.6130072Z         },
2023-04-27T16:19:51.6130395Z         "orchestratorVersion": "1.25.6",
2023-04-27T16:19:51.6130752Z         "currentOrchestratorVersion": "1.25.6",
2023-04-27T16:19:51.6131104Z         "mode": "System",
2023-04-27T16:19:51.6131413Z         "osType": "Linux",
2023-04-27T16:19:51.6131704Z         "osSKU": "Ubuntu",
2023-04-27T16:19:51.6132109Z         "nodeImageVersion": "AKSUbuntu-2204gen2containerd-202304.10.0",
2023-04-27T16:19:51.6132485Z         "enableFIPS": false
2023-04-27T16:19:51.6132778Z       }
2023-04-27T16:19:51.6133011Z     ],
2023-04-27T16:19:51.6133290Z     "linuxProfile": {
2023-04-27T16:19:51.6133626Z       "adminUsername": "k8sadmin",
2023-04-27T16:19:51.6133921Z       "ssh": {
2023-04-27T16:19:51.6134222Z         "publicKeys": [
2023-04-27T16:19:51.6134482Z           {
2023-04-27T16:19:51.6135577Z             "keyData": "ssh-rsa xxxxxx user manager\\containeradministrator@xxxxxxx\r\n"
2023-04-27T16:19:51.6136628Z           }
2023-04-27T16:19:51.6136934Z         ]
2023-04-27T16:19:51.6137195Z       }
2023-04-27T16:19:51.6137429Z     },
2023-04-27T16:19:51.6137720Z     "windowsProfile": {
2023-04-27T16:19:51.6138694Z       "adminUsername": "k8sadmin",
2023-04-27T16:19:51.6139103Z       "enableCSIProxy": true
2023-04-27T16:19:51.6139377Z     },
2023-04-27T16:19:51.6139685Z     "servicePrincipalProfile": {
2023-04-27T16:19:51.6140009Z       "clientId": "msi"
2023-04-27T16:19:51.6140270Z     },
2023-04-27T16:19:51.6140633Z     "nodeResourceGroup": "MC_rg-mhtest_aks-mh-test_westus",
2023-04-27T16:19:51.6140998Z     "enableRBAC": true,
2023-04-27T16:19:51.6141308Z     "networkProfile": {
2023-04-27T16:19:51.6141622Z       "networkPlugin": "azure",
2023-04-27T16:19:51.6141970Z       "loadBalancerSku": "Standard",
2023-04-27T16:19:51.6142311Z       "loadBalancerProfile": {
2023-04-27T16:19:51.6142621Z         "managedOutboundIPs": {
2023-04-27T16:19:51.6142933Z           "count": 1
2023-04-27T16:19:51.6143193Z         },
2023-04-27T16:19:51.6143500Z         "effectiveOutboundIPs": [
2023-04-27T16:19:51.6143777Z           {
2023-04-27T16:19:51.6144383Z             "id": "/subscriptions/xxxxxxx/resourceGroups/MC_rg-mhtest_aks-mh-test_westus/providers/Microsoft.Network/publicIPAddresses/xxxxxx"
2023-04-27T16:19:51.6144971Z           }
2023-04-27T16:19:51.6145204Z         ]
2023-04-27T16:19:51.6145457Z       },
2023-04-27T16:19:51.6145742Z       "serviceCidr": "10.2.0.0/16",
2023-04-27T16:19:51.6146094Z       "dnsServiceIP": "10.2.0.10",
2023-04-27T16:19:51.6146438Z       "dockerBridgeCidr": "172.17.0.1/16",
2023-04-27T16:19:51.6146815Z       "outboundType": "loadBalancer",
2023-04-27T16:19:51.6147129Z       "serviceCidrs": [
2023-04-27T16:19:51.6147437Z         "10.2.0.0/16"
2023-04-27T16:19:51.6147715Z       ],
2023-04-27T16:19:51.6148778Z       "ipFamilies": [
2023-04-27T16:19:51.6149132Z         "IPv4"
2023-04-27T16:19:51.6149377Z       ]
2023-04-27T16:19:51.6149630Z     },
2023-04-27T16:19:51.6149885Z     "aadProfile": {
2023-04-27T16:19:51.6150188Z       "managed": true,
2023-04-27T16:19:51.6150785Z       "adminGroupObjectIDs": [
2023-04-27T16:19:51.6151156Z         "xxxxxxxxx"
2023-04-27T16:19:51.6151480Z       ],
2023-04-27T16:19:51.6151750Z       "adminUsers": null,
2023-04-27T16:19:51.6152077Z       "enableAzureRBAC": true,
2023-04-27T16:19:51.6152450Z       "tenantID": "xxxxxx"
2023-04-27T16:19:51.6152791Z     },
2023-04-27T16:19:51.6153061Z     "maxAgentPools": 100,
2023-04-27T16:19:51.6153396Z     "apiServerAccessProfile": {
2023-04-27T16:19:51.6153863Z       "authorizedIPRanges": [
2023-04-27T16:19:51.6154184Z         "10.0.0.0/8",
2023-04-27T16:19:51.6154486Z         "172.16.0.0/12",
2023-04-27T16:19:51.6154779Z         "192.168.0.0/16",
2023-04-27T16:19:51.6155107Z         "104.183.240.195/32",
2023-04-27T16:19:51.6155410Z         "198.140.27.240/32",
2023-04-27T16:19:51.6155732Z         "102.120.211.32/32"
2023-04-27T16:19:51.6155999Z       ]
2023-04-27T16:19:51.6156262Z     },
2023-04-27T16:19:51.6156537Z     "identityProfile": {
2023-04-27T16:19:51.6156865Z       "kubeletidentity": {
2023-04-27T16:19:51.6157514Z         "resourceId": "/subscriptions/xxxxxx/resourcegroups/MC_rg-mhtest_aks-mh-test_westus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-mh-test-agentpool",
2023-04-27T16:19:51.6158931Z         "clientId": "xxxxxx",
2023-04-27T16:19:51.6159408Z         "objectId": "xxxx"
2023-04-27T16:19:51.6159724Z       }
2023-04-27T16:19:51.6159994Z     },
2023-04-27T16:19:51.6160278Z     "autoScalerProfile": {
2023-04-27T16:19:51.6160620Z       "balance-similar-node-groups": "false",
2023-04-27T16:19:51.6160971Z       "expander": "random",
2023-04-27T16:19:51.6161289Z       "max-empty-bulk-delete": "10",
2023-04-27T16:19:51.6161664Z       "max-graceful-termination-sec": "600",
2023-04-27T16:19:51.6162013Z       "max-node-provision-time": "15m",
2023-04-27T16:19:51.6162392Z       "max-total-unready-percentage": "45",
2023-04-27T16:19:51.6162745Z       "new-pod-scale-up-delay": "0s",
2023-04-27T16:19:51.6163111Z       "ok-total-unready-count": "3",
2023-04-27T16:19:51.6163476Z       "scale-down-delay-after-add": "10m",
2023-04-27T16:19:51.6163839Z       "scale-down-delay-after-delete": "10s",
2023-04-27T16:19:51.6164224Z       "scale-down-delay-after-failure": "3m",
2023-04-27T16:19:51.6164576Z       "scale-down-unneeded-time": "10m",
2023-04-27T16:19:51.6164946Z       "scale-down-unready-time": "20m",
2023-04-27T16:19:51.6165320Z       "scale-down-utilization-threshold": "0.5",
2023-04-27T16:19:51.6165686Z       "scan-interval": "10s",
2023-04-27T16:19:51.6166055Z       "skip-nodes-with-local-storage": "false",
2023-04-27T16:19:51.6166417Z       "skip-nodes-with-system-pods": "true"
2023-04-27T16:19:51.6166736Z     },
2023-04-27T16:19:51.6167002Z     "securityProfile": {},
2023-04-27T16:19:51.6167323Z     "storageProfile": {
2023-04-27T16:19:51.6167617Z       "diskCSIDriver": {
2023-04-27T16:19:51.6168828Z         "enabled": true
2023-04-27T16:19:51.6169186Z       },
2023-04-27T16:19:51.6169452Z       "fileCSIDriver": {
2023-04-27T16:19:51.6169758Z         "enabled": true
2023-04-27T16:19:51.6170015Z       },
2023-04-27T16:19:51.6170309Z       "snapshotController": {
2023-04-27T16:19:51.6170604Z         "enabled": true
2023-04-27T16:19:51.6170880Z       }
2023-04-27T16:19:51.6171113Z     },
2023-04-27T16:19:51.6171399Z     "oidcIssuerProfile": {
2023-04-27T16:19:51.6171692Z       "enabled": false
2023-04-27T16:19:51.6171991Z     }
2023-04-27T16:19:51.6172243Z   },
2023-04-27T16:19:51.6172493Z   "identity": {
2023-04-27T16:19:51.6172812Z     "type": "SystemAssigned",
2023-04-27T16:19:51.6173192Z     "principalId": "xxxxx",
2023-04-27T16:19:51.6173630Z     "tenantId": "xxxx"
2023-04-27T16:19:51.6173950Z   },
2023-04-27T16:19:51.6174213Z   "sku": {
2023-04-27T16:19:51.6174478Z     "name": "Basic",
2023-04-27T16:19:51.6175049Z     "tier": "Free"
2023-04-27T16:19:51.6175327Z   }
2023-04-27T16:19:51.6175559Z }
2023-04-27T16:19:51.6175652Z 
2023-04-27T16:19:51.6175908Z [0m
2023-04-27T16:19:51.6176402Z [33;1mDEBUG: 9:19:51 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].[0m
2023-04-27T16:19:51.8548479Z ##[error]Object reference not set to an instance of an object.
2023-04-27T16:19:52.1779002Z ##[error]PowerShell exited with code '1'.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}       
Script     5.3.2                 Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, Get-AzAksNodePool… 
Script     3.2.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsigh…
```

### Error output

```PowerShell
HistoryId: 4

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Aks.Utils.AddonUtils.EnableAddonsProfile(IDictionary`2 addonProfiles, String addonServiceName,    
                 ManagedClusterAddonProfile addonProfile)
                    at Microsoft.Azure.Commands.Aks.Utils.AddonUtils.EnableAddonMonitoring(IDictionary`2 addonProfiles, String
                 workspaceResourceIdValue, String workspaceResourceIdParameterName)
                    at Microsoft.Azure.Commands.Aks.Utils.AddonUtils.EnableAddonsProfile(IDictionary`2 addonProfiles, String[]
                 addOnParameterValue, String addOnParameterName, String workspaceResourceIdValue, String workspaceResourceIdParameterName,        
                 String subnetNameValue, String subnetNameParameterName)
                    at Microsoft.Azure.Commands.Aks.Commands.EnableAzureRmAddons.UpdateAddonsProfile(IDictionary`2 addonProfiles)
                    at Microsoft.Azure.Commands.Aks.Commands.UpdateAddonsBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)        
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1        
                 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Enable-AzAksAddOn}
Line           : Enable-AzAksAddon -Name Monitoring -WorkspaceResourceId $log.ResourceId -ClusterName aks-mh-test -ResourceGroupName rg-mhtest    
Position       : At line:1 char:1
                 + Enable-AzAksAddon -Name Monitoring -WorkspaceResourceId $log.Resource …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4
```

**Comment by isra-fel** [comment]
Looks like an client-side issue. @YanaXu could you take a look? Thanks.

**Comment by mhessaveva** [comment]
We also discovered a second issue in the commandlet.

$akscluster | Enable-AzAksAddon -Name 'Monitoring' -WorkspaceResourceId $log.ResourceId

also errors out for clusters created using managed identity, tho this time with a different error.

In that case userAssignedidentities is empty, but it's still part of the PUT request from the call to ARM API that the PS commandlet makes, and the API doesn't like that.

**Comment by YanaXu** [comment]
Hi @mhessaveva , please try the following workaround to unblock the issue:
```powershell
$akscluster.AddonProfiles = New-Object 'System.Collections.Generic.Dictionary[System.String,Microsoft.Azure.Commands.Aks.Models.PSManagedClusterAddonProfile]'
$akscluster.AddonProfiles.Add('omsagent', [Microsoft.Azure.Commands.Aks.Models.PSManagedClusterAddonProfile]@{})

$cluster | Enable-AzAksAddon -Name 'Monitoring' -WorkspaceResourceId $log.ResourceId
```

We'll fix this in a later release.
