### ISSUE TITLE
Get-AzRoleAssignment should support MSI with `-ServicePrincipalName`

### ISSUE THREAD

**Issue by jikuja** [Azure/azure-powershell#21678]
### Description

Get-ZzRoleAssignment and other should support MSI with `-ServicePrincipalName`, not just service principals.

When running `get-azRoleAssignment -ServicePrincipalName xxx` where xxx is the name of to MSI underlying graph API query fails to fetch data: `GET https://graph.microsoft.com/v1.0/servicePrincipals?$filter=servicePrincipalNames%2Fany%28c%3A c eq %27xx%27%29` returns empty array.

Same time `https://graph.microsoft.com/v1.0/servicePrincipals?$count=true&$search="displayName:xxx"&$select=id,displayName` returns requested MSI

----

The main issue is in https://github.com/Azure/azure-powershell/blob/main/src/Resources/Resources/ActiveDirectory/Models/ActiveDirectoryClient.cs#L111-L125 : ActiveDirectoryClient should do MSI compatible queries or should support an interface to get data for MSIs.

### Issue script & Debug output

```PowerShell
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=servicePrincipalNames%2Fany%28c%3A c eq %27xxx%27%29

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 751ff0ca-4f25-4265-afeb-4fb68f678cb4

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Strict-Transport-Security     : max-age=31536000
request-id                    : 9c72f257-fd41-4553-9f0b-a5ec8cb461b2
client-request-id             : 9c72f257-fd41-4553-9f0b-a5ec8cb461b2
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Sweden Central","Slice":"E","Ring":"5","ScaleUnit":"002","RoleInstance":"GV3PEPF00000908"}}
x-ms-resource-unit            : 1
OData-Version                 : 4.0
Date                          : Mon, 01 May 2023 13:14:02 GMT

Body:
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#servicePrincipals",
  "value": []
}


DEBUG: 4:14:03 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzRoleAssignment: Cannot find principal using the specified options
DEBUG: 4:14:03 PM - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: AzureQoSEvent:  Module: Az.Resources:6.5.0; CommandName: Get-AzRoleAssignment; PSVersion: 7.3.4; IsSuccess: False; Duration: 00:00:00.2383998; Exception: Cannot find principal using the specified options;
DEBUG: 4:14:03 PM - GetAzureRoleAssignmentCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Darwin 21.6.0 Darwin Kernel Version 21.6.0: Thu Mar  9 20:08:59 PST 2023; root:xnu-8020.240.18.700.8~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.10.4                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.5.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     1.1.0                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, Open-AzPredictorSurvey, Send-AzPredictorRating}
```

### Error output

```PowerShell
Message        : Cannot find principal using the specified options
StackTrace     :    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.FilterRoleAssignments(FilterRoleAssignmentsOptions options, String 
                 currentSubscription, UInt64 first, UInt64 skip)
                    at Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Collections.Generic.KeyNotFoundException
InvocationInfo : {Get-AzRoleAssignment}
Line           : get-azRoleAssignment -ServicePrincipalName xxx
Position       : At line:1 char:1
                 + get-azRoleAssignment -ServicePrincipalName xxx
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by isra-fel** [comment]
Adding folks from ARM team @LizMS @cbrooksmsft to comment on the feasibility and risks of changing the underlying API of `Get-AzRoleAssignment` from based on `$filter` to `$search` to support getting MSI.
I'm not sure if `$search` would impact performance in some cases. Also could there be another way to support MSI?

**Comment by isra-fel** [comment]
@VeryEarly could you check real quick if we can get managed service identity with `$filter` + `servicePrincipalNames` using the beta API version?

**Comment by VeryEarly** [comment]
Hi @jikuja ,

display name cannot be used to uniquely identity a service principal (or managed identity), that's why we do not accept using display name to do role assignment.

Please try following scripts:
```
# if there is only one service principal named "xxx" under current tenant
identity = Get-AzADServicePrincipal -DisplayName "xxx"
Get-AzRoleAssignment -ObjectId identity.Id
```
