### ISSUE TITLE
[Az.ManagedServiceIdentity 1.1.1] New-AzUserAssignedIdentity throws error 'cannot call method on a null-valued expression'

### ISSUE THREAD

**Issue by PeterJamesLawson** [Azure/azure-powershell#21692]
### Description

Error when running:
`New-AzUserAssignedIdentity -Name $autoAcctUserAMI -ResourceGroupName $resourceGroup -Location $location`
`You cannot call a method on a null-valued expression.'

### Issue script & Debug output

```PowerShell
PS> $DebugPreference='Continue'
PS> $autoAcctUserAMI = 'aaUserAMI' 
PS> $resourceGroup = 'rg-automation'
PS> $location = 'eastus'
PS> New-AzUserAssignedIdentity -Name $autoAcctUserAMI -ResourceGroupName $resourceGroup -Location $location
You cannot call a method on a null-valued expression.
At C:\WindowsPowerShell\Modules\Az.ManagedServiceIdentity\1.1.1\exports\ProxyCmdletDefinitions.ps1:1073 char:13
+             [Microsoft.Azure.PowerShell.Cmdlets.ManagedServiceIdentit ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22621.963
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.963
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS> Get-Module Az*
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.12.2     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     1.1.1      Az.ManagedServiceIdentity           {Get-AzFederatedIdentityCredentials, Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity, Get-AzUserAssig...
```

### Error output

```PowerShell
PS> Resolve-AzError
DEBUG: Got version 0 of Az
DEBUG: Got version 0 of Az.Accounts
DEBUG: 4:01:31 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 4:01:31 PM - using account id 'plawson1@metrohealth.org'...
DEBUG: 4:01:31 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.


   HistoryId: -1


Message        : You cannot call a method on a null-valued expression.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
                    at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
                    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings   
                 settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings
                 settings)
                    at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
                    at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](PowerShell pwsh, PSInvocationSettings   
                 invocationSettings)
                    at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken)   
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :             [Microsoft.Azure.PowerShell.Cmdlets.ManagedServiceIdentity.module]::Instance.Telemetry.Invoke('Create', $MyInvocation, $parameterSet,
                 $PSCmdlet)

Position       : At C:\Users\plawson1\Documents\WindowsPowerShell\Modules\Az.ManagedServiceIdentity\1.1.1\exports\ProxyCmdletDefinitions.ps1:1073 char:13
                 +             [Microsoft.Azure.PowerShell.Cmdlets.ManagedServiceIdentit ...
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1



   HistoryId: 2


Message        : The type initializer for 'Microsoft.Azure.Commands.Common.AzModule' threw an exception.
StackTrace     :    at Microsoft.Azure.Commands.Common.RegisterAzModule.ProcessRecord()
Exception      : System.TypeInitializationException
InvocationInfo : {Register-AzModule}
Line           :   $VTable = Register-AzModule

Position       : At C:\Users\plawson1\Documents\WindowsPowerShell\Modules\Az.ManagedServiceIdentity\1.1.1\Az.ManagedServiceIdentity.psm1:49 char:13
                 +   $VTable = Register-AzModule
                 +             ~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Attempted to access an element as a type incompatible with the array.
StackTrace     :    at System.Collections.Generic.List`1.Add(T item)
                    at Microsoft.Azure.Commands.Common.AzModule..cctor()
Exception      : System.ArrayTypeMismatchException
InvocationInfo : {Register-AzModule}
Line           :   $VTable = Register-AzModule

Position       : At C:\Users\plawson1\Documents\WindowsPowerShell\Modules\Az.ManagedServiceIdentity\1.1.1\Az.ManagedServiceIdentity.psm1:49 char:13
                 +   $VTable = Register-AzModule
                 +             ~~~~~~~~~~~~~~~~~
HistoryId      : 2



DEBUG: 4:01:31 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.12.2; CommandName: Resolve-AzError; PSVersion: 5.1.22621.963; IsSuccess: True; Duration: 00:00:00.2974527
DEBUG: 4:01:31 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 4:01:31 PM - ResolveError end processing.
```

**Comment by SwathiDhanwada-MSFT** [comment]
@PeterJamesLawson Could you kindly confirm if you have had the opportunity to review my comment? If you have any questions, please don't hesitate to ask.

**Comment by SwathiDhanwada-MSFT** [comment]
@PeterJamesLawson Have you had a chance to review my comment? Please feel free to let me know if you have any questions.

**Comment by SwathiDhanwada-MSFT** [comment]
@PeterJamesLawson Could you kindly confirm if you have had the opportunity to review my comment? If you have any questions, please don't hesitate to ask.

**Comment by SwathiDhanwada-MSFT** [comment]
@PeterJamesLawson As we haven't heard from you, we will close the issue for now. If there are further questions , please revert and we will be glad to assist you.
