### ISSUE TITLE
Not able to connect to Azure with Az.Accounts version 2.12.3

### ISSUE THREAD

**Issue by kellyMicrosoft** [Azure/azure-powershell#21952]
### Description

The Az.Accounts module updated to 2.12.3 last week and our service has been down since then. 
The error message is `System.EntryPointNotFoundException: Entry point was not found.` when we execute `Connect-AzAccount`

### Issue script & Debug output

```PowerShell
DEBUG: 00:00:00.0003030 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0002163 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.0000022 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0000224 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.0002702 Trying provider assembly: C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0000002 Trying provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0032966 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0034113 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0037001 Attempting loading of assembly: C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0044924 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0049845 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.0059177 Attempting loading of assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.0082622 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.0084102 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.0086779 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.0086918 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:00.0087377 Acquiring providers for assemblyC:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.0091419 Acquiring providers for assemblyC:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.0510673 Registering providers via metaproviders for assembly
Microsoft.PackageManagement.MetaProvider.PowerShell.Internal.PowerShellMetaProvider
DEBUG: 00:00:00.0928136 Initializing provider 'zipfile'
DEBUG: 00:00:00.0930390 Initializing provider 'msi'
DEBUG: 00:00:00.0937778 Initializing provider 'WebDownloader'
DEBUG: 00:00:00.0945989 Initializing provider 'Programs'
DEBUG: 00:00:00.0968796 Initializing provider 'NuGet'
DEBUG: 00:00:00.0976181 Initializing provider 'Bootstrap'
DEBUG: 00:00:00.1000606 Initializing provider 'msu'
DEBUG: 00:00:00.1163767 Provider 'WebDownloader' Initialized
DEBUG: 00:00:00.1164357 Using Downloader Provider WebDownloader
DEBUG: 00:00:00.1181710 Provider 'zipfile' Initialized
DEBUG: 00:00:00.1182073 Using Archiver Provider zipfile
DEBUG: 00:00:00.1190294 Initialize Bootstrapper
DEBUG: 00:00:00.1208925 Calling 'msi::InitializeProvider'
DEBUG: 00:00:00.1209386 Provider 'msi' Initialized
DEBUG: 00:00:00.1209572 Using Package Provider msi
DEBUG: 00:00:00.1209853 Calling 'Programs::InitializeProvider'
DEBUG: 00:00:00.1210044 Calling 'msu::InitializeProvider'
DEBUG: 00:00:00.1210236 Provider 'Programs' Initialized
DEBUG: 00:00:00.1210415 Provider 'msu' Initialized
DEBUG: 00:00:00.1210396 Using Package Provider Programs
DEBUG: 00:00:00.1210556 Using Package Provider msu
DEBUG: 00:00:00.1237285 Provider 'Bootstrap' Initialized
DEBUG: 00:00:00.1237614 Using Package Provider Bootstrap
DEBUG: 00:00:00.1237420 Trying to register metaprovider
DEBUG: 00:00:00.1295492 Calling 'NuGet'::'InitializeProvider'.
DEBUG: 00:00:00.1295970 Provider 'NuGet' Initialized
DEBUG: 00:00:00.1296143 Using Package Provider NuGet
DEBUG: 00:00:00.1357188 Initializing PowerShell MetaProvider
DEBUG: 00:00:00.1367221 Calling 'Programs::GetFeatures'
DEBUG: 00:00:00.1367265 Calling 'zipfile::GetFeatures'
DEBUG: 00:00:00.1368898 Calling 'WebDownloader::GetFeatures'
DEBUG: 00:00:00.1375639 The provider 'Programs' is imported
DEBUG: 00:00:00.1393223 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.ArchiverProviders.dll
DEBUG: 00:00:00.1402680 Calling 'Bootstrap::GetFeatures'
DEBUG: 00:00:00.1406361 Calling 'msu::GetFeatures'
DEBUG: 00:00:00.1407062 Calling 'msi::GetFeatures'
DEBUG: 00:00:00.1409182 The provider 'msu' is imported
DEBUG: 00:00:00.1412324 The provider 'Bootstrap' is imported
DEBUG: 00:00:00.1412945 The provider 'msi' is imported
DEBUG: 00:00:00.1414786 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsuProvider.dll
DEBUG: 00:00:00.1415841 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.CoreProviders.dll
DEBUG: 00:00:00.1416545 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MsiProvider.dll
DEBUG: 00:00:00.1485211 Calling 'NuGet'::'GetFeatures'.
DEBUG: 00:00:00.1497940 The provider 'NuGet' is imported
DEBUG: 00:00:00.1508182 SUCCESS provider assembly: C:\Program
Files\PackageManagement\ProviderAssemblies\nuget\2.8.5.208\Microsoft.PackageManagement.NuGetProvider.dll
DEBUG: 00:00:00.1727235 Calling 'WebDownloader::DownloadFile'
'','','40000','False'
DEBUG: 00:00:00.2871256 Attempting to load PowerShell Provider Module [C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1]
DEBUG: 00:00:00.3959033 Calling 'WebDownloader::DownloadFile'
'https://onegetcdn.azureedge.net/providers/nuget-2.8.5.208.package.swidtag','','40000','False'
DEBUG: 00:00:00.4102271 Calling 'WebDownloader::DownloadFile'
'https://onegetcdn.azureedge.net/providers/psl-1.0.0.210.package.swidtag','','40000','False'
DEBUG: 00:00:00.4262670 Calling 'WebDownloader::DownloadFile'
'https://onegetcdn.azureedge.net/providers/ChocolateyPrototype-2.8.5.130.package.swidtag','','40000','False'
DEBUG: 00:00:00.4470323 Loaded PowerShell package provider: '[C:\Program
Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1]'.
DEBUG: 00:00:00.4563679 Loaded PowerShell Provider: PowerShellGet
DEBUG: 00:00:00.4591499 Initializing provider 'PowerShellGet'
DEBUG: 00:00:00.4702252 Calling New() : MethodName = 'InitializeProvider'
DEBUG: 00:00:00.4702858 ErrorAction: Ignore
DEBUG: 00:00:00.4703023 Name: Az
DEBUG: 00:00:00.4741610 INVOKING PowerShell Fn Initialize-Provider with args  that has length 0
DEBUG: 00:00:00.5023910 In PowerShellGet Provider - 'Initialize-Provider'.
DEBUG: 00:00:00.5028013 PowerShell Script 'PSModule' Function 'Initialize-Provider' returns null.
DEBUG: 00:00:00.5042826 Done calling powershell «Initialize-Provider» «PSModule»
DEBUG: 00:00:00.5043549 Provider 'PowerShellGet' Initialized
DEBUG: 00:00:00.5043758 Using Package Provider PowerShellGet
DEBUG: 00:00:00.5123093 Calling New() : MethodName = 'GetFeatures'
DEBUG: 00:00:00.5123408 ErrorAction: Ignore
DEBUG: 00:00:00.5123614 Name: Az
DEBUG: 00:00:00.5132995 INVOKING PowerShell Fn Get-Feature with args  that has length 0
DEBUG: 00:00:00.5235549 In PowerShellGet Provider - 'Get-Feature'.
DEBUG: 00:00:00.5378773 Done calling powershell «Get-Feature» «PSModule»
DEBUG: 00:00:00.5379860 The provider 'PowerShellGet' is imported
DEBUG: 00:00:00.5393900 SUCCESS provider assembly: C:\Program
Files\WindowsPowerShell\Modules\PackageManagement\1.0.0.1\Microsoft.PackageManagement.MetaProvider.PowerShell.dll
DEBUG: 00:00:01.0944090 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:01.0944698 ErrorAction: Ignore
DEBUG: 00:00:01.0944889 Name: Az
DEBUG: 00:00:01.0956194 INVOKING PowerShell Fn Get-DynamicOptions with args Provider that has length 1
DEBUG: 00:00:01.1111360 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:01.1285783 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:01.1342451 Calling New() : MethodName = 'GetDynamicOptions'
DEBUG: 00:00:01.1342739 ErrorAction: Ignore
DEBUG: 00:00:01.1342924 Name: Az
DEBUG: 00:00:01.1353837 INVOKING PowerShell Fn Get-DynamicOptions with args Install that has length 1
DEBUG: 00:00:01.1362912 In PowerShellGet Provider - 'Get-DynamicOptions'.
DEBUG: 00:00:01.1755679 Done calling powershell «Get-DynamicOptions» «PSModule»
DEBUG: 00:00:01.4212072 Calling New() : MethodName = 'GetInstalledPackages'
DEBUG: 00:00:01.4230646 ProviderName: PowerShellGet
DEBUG: 00:00:01.4244161 Type: Module
DEBUG: 00:00:01.4255399 MessageResolver: Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.4268268 Name: Az
DEBUG: 00:00:01.4280463 ErrorAction: Ignore
DEBUG: 00:00:01.4297762 INVOKING PowerShell Fn Get-InstalledPackage with args Az, , ,  that has length 4
DEBUG: 00:00:01.4439519 In PowerShellGet Provider - 'Get-InstalledPackage'.
DEBUG: 00:00:01.4481946 OPTION: ProviderName => PowerShellGet
DEBUG: 00:00:01.4500614 OPTION: Type => Module
DEBUG: 00:00:01.4515689 OPTION: MessageResolver => Microsoft.PowerShell.PackageManagement.Cmdlets.GetMessageString
DEBUG: 00:00:01.4530290 OPTION: Name => Az
DEBUG: 00:00:01.4543884 OPTION: ErrorAction => Ignore
DEBUG: 00:00:02.7580780 Done calling powershell «Get-InstalledPackage» «PSModule»
DEBUG: Initializing ConditionalAssemblyContext. PSEdition is [Desktop]. PSVersion is [5.1.20348.1366].
DEBUG: Initializing ConditionalAssemblyProvider. AssemblyRootPath is [C:\Program
Files\WindowsPowerShell\Modules\Az.Accounts\2.12.3\StartupScripts\..\lib].
WARNING: The names of some imported commands from the module 'Microsoft.Azure.PowerShell.Cmdlets.Network' include
unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the
Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
WARNING: The names of some imported commands from the module 'Az.Network' include unapproved verbs that might make them
less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose
parameter. For a list of approved verbs, type Get-Verb.
DEBUG: Got version 0 of Az
DEBUG: Got version 0 of Az.Accounts
DEBUG: 1:03:46 PM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'ManagedServiceLogin'.
DEBUG: 1:03:46 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: 1:03:46 PM - [ConfigManager] Got nothing from [DefaultSubscriptionForLogin], Module = [], Cmdlet = []. Returning
default value [].
DEBUG: 1:03:46 PM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 1:03:46 PM - No autosave setting detected in environment variable 'AzContextAutoSave'.
DEBUG: 1:03:46 PM - Using Autosave scope 'CurrentUser'
DEBUG: 1:03:46 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync -
TenantId:'organizations', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:
DEBUG: Request [] GET
x-ms-client-request-id:
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.1 (.NET Framework 4.8.4614.0; Microsoft Windows 10.0.20348 )
client assembly: Azure.Identity
WARNING: Unable to acquire token for tenant 'organizations' with error 'Entry point was not found.'
DEBUG: 1:03:46 PM - Unable to acquire token for tenant 'organizations' with error 'System.EntryPointNotFoundException:
Entry point was not found.
   at System.Threading.Tasks.Sources.IValueTaskSource`1.GetStatus(Int16 token)
   at Microsoft.Azure.PowerShell.Authenticators.MsalAccessTokenAcquirer.<GetAccessTokenAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount
account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1
promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account,
IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction,
String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account,
IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)'
DEBUG: Response [] 200 OK (00.0s)
Content-Length:2123
Content-Type:application/json; charset=utf-8
Date:Tue, 30 May 2023 20:03:46 GMT
Server:IMDS/150.870.65.1015
DEBUG: 1:03:46 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning
default value [True].
Connect-AzAccount : Entry point was not found.
+ Connect-AzAccount -Identity;
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], EntryPointNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

 

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:
ExpiresOn: 2023-05-31T19:25:23.0000000+00:00
DEBUG: 1:03:46 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: 1:03:46 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning
default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.12.3; CommandName: Connect-AzAccount; PSVersion: 5.1.20348.1366;
IsSuccess: False; Duration: 00:00:00.4086243; Exception: Entry point was not found.;
DEBUG: 1:03:46 PM - ConnectAzureRmAccountCommand end processing.
```

### Environment data

```PowerShell
5.1.20348.1366
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     9.0.1      Az
Script     2.12.3     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     2.0.0      Az.Advisor                          {Disable-AzAdvisorRecommendation, Enable-AzAdvisorRecommen...
Script     5.0.0      Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, ...
Script     1.1.4      Az.AnalysisServices                 {Add-AzAnalysisServicesAccount, Export-AzAnalysisServicesI...
Script     4.0.0      Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiTo...
Script     1.2.0      Az.AppConfiguration                 {Clear-AzAppConfigurationDeletedStore, Get-AzAppConfigurat...
Script     2.1.0      Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKe...
Script     2.0.0      Az.Attestation                      {Add-AzAttestationPolicySigner, Get-AzAttestationPolicy, G...
Script     1.8.0      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationD...
Script     3.2.1      Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchComputeNodeSched...
Script     2.0.0      Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBilling...
Script     2.1.0      Az.Cdn                              {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointC...
Script     1.1.0      Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-A...
Script     1.11.0     Az.CognitiveServices                {Add-AzCognitiveServicesAccountNetworkRule, Get-AzCognitiv...
Script     5.0.0      Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnatten...
Script     1.0.0      Az.ConfidentialLedger               {Get-AzConfidentialLedger, New-AzConfidentialLedger, New-A...
Script     3.1.0      Az.ContainerInstance                {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-...
Script     3.0.0      Az.ContainerRegistry                {Connect-AzContainerRegistry, Get-AzContainerRegistry, Get...
Script     1.8.2      Az.CosmosDB                         {Get-AzCosmosDBAccount, Get-AzCosmosDBAccountKey, Get-AzCo...
Script     1.1.0      Az.DataBoxEdge                      {Get-AzDataBoxEdgeBandwidthSchedule, Get-AzDataBoxEdgeDevi...
Script     1.3.0      Az.Databricks                       {Get-AzDatabricksAccessConnector, Get-AzDatabricksOutbound...
Script     1.16.9     Az.DataFactory                      {Add-AzDataFactoryV2DataFlowDebugSessionPackage, Add-AzDat...
Script     1.0.2      Az.DataLakeAnalytics                {Add-AzDataLakeAnalyticsDataSource, Add-AzDataLakeAnalytic...
Script     1.3.0      Az.DataLakeStore                    {Add-AzDataLakeStoreFirewallRule, Add-AzDataLakeStoreItemC...
Script     1.0.1      Az.DataShare                        {Get-AzDataShare, Get-AzDataShareAccount, Get-AzDataShareD...
Script     1.1.0      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, Get-AzDeploymentMa...
Script     3.1.1      Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-A...
Script     1.0.2      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolic...
Script     1.1.2      Az.Dns                              {Add-AzDnsRecordConfig, Get-AzDnsRecordSet, Get-AzDnsZone,...
Script     1.4.1      Az.EventGrid                        {Get-AzEventGridDomain, Get-AzEventGridDomainKey, Get-AzEv...
Script     3.0.0      Az.EventHub                         {Add-AzEventHubIPRule, Add-AzEventHubVirtualNetworkRule, G...
Script     1.9.0      Az.FrontDoor                        {Disable-AzFrontDoorCustomDomainHttps, Enable-AzFrontDoorC...
Script     4.0.5      Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Ge...
Script     5.0.1      Az.HDInsight                        {Add-AzHDInsightClusterIdentity, Add-AzHDInsightComponentV...
Script     2.0.0      Az.HealthcareApis                   {Get-AzHealthcareApisService, Get-AzHealthcareApisWorkspac...
Script     2.7.4      Az.IotHub                           {Add-AzIotHubCertificate, Add-AzIotHubConfiguration, Add-A...
Script     4.8.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateConta...
Script     2.1.0      Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabaseP...
Script     1.5.0      Az.LogicApp                         {Get-AzIntegrationAccount, Get-AzIntegrationAccountAgreeme...
Script     1.1.3      Az.MachineLearning                  {Add-AzMlWebServiceRegionalProperty, Export-AzMlWebService...
Script     1.2.0      Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzM...
Script     1.0.0      Az.ManagedServiceIdentity           {Get-AzSystemAssignedIdentity, Get-AzUserAssignedIdentity,...
Script     3.0.0      Az.ManagedServices                  {Get-AzManagedServicesAssignment, Get-AzManagedServicesDef...
Script     2.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Invoke-AzMarketplaceSignTerms, Se...
Script     1.1.1      Az.Media                            {Get-AzMediaService, Get-AzMediaServiceKey, Get-AzMediaSer...
Script     2.0.0      Az.Migrate                          {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMi...
Script     4.2.0      Az.Monitor                          {Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAler...
Script     1.1.0      Az.MySql                            {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Ge...
Script     5.0.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-Az...
Script     1.1.1      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorization...
Script     3.2.0      Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-Az...
Script     1.5.1      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyMetadata, Get-AzPolicyReme...
Script     1.1.0      Az.PostgreSql                       {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnection...
Script     1.2.0      Az.PowerBIEmbedded                  {Get-AzPowerBIEmbeddedCapacity, Get-AzPowerBIWorkspace, Ge...
Script     1.0.3      Az.PrivateDns                       {Add-AzPrivateDnsRecordConfig, Get-AzPrivateDnsRecordSet, ...
Script     6.0.0      Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Ba...
Script     1.6.0      Az.RedisCache                       {Export-AzRedisCache, Get-AzRedisCache, Get-AzRedisCacheFi...
Script     1.1.0      Az.RedisEnterpriseCache             {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache...
Script     1.0.3      Az.Relay                            {Get-AzRelayAuthorizationRule, Get-AzRelayHybridConnection...
Script     1.1.0      Az.ResourceMover                    {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveC...
Script     6.3.1      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...
Script     1.3.0      Az.Security                         {Add-AzSecurityAdaptiveNetworkHardening, Add-AzSecuritySql...
Script     3.0.0      Az.SecurityInsights                 {Get-AzSentinelAlertRule, Get-AzSentinelAlertRuleAction, G...
Script     2.0.0      Az.ServiceBus                       {Add-AzServiceBusIPRule, Add-AzServiceBusVirtualNetworkRul...
Script     3.1.0      Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabric...
Script     1.4.1      Az.SignalR                          {Get-AzSignalR, Get-AzSignalRKey, Get-AzSignalRUsage, New-...
Script     4.0.0      Az.Sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElasticJobStep...
Script     1.1.0      Az.SqlVirtualMachine                {Get-AzAvailabilityGroupListener, Get-AzSqlVM, Get-AzSqlVM...
Script     1.3.1      Az.StackHCI                         {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestatio...
Script     5.0.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountMa...
Script     1.7.0      Az.StorageSync                      {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyncGroup, G...
Script     2.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsCluste...
Script     1.0.0      Az.Support                          {Get-AzSupportProblemClassification, Get-AzSupportService,...
Script     2.0.0      Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTr...
Script     1.1.0      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Add-AzTraffic...
Script     2.11.4     Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRou...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Con...
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, En...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-Pack...
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCap...
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, Remove-PS...
Script     22.0.59    SqlServer                           {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-SqlAvail...
```

### Error output

```PowerShell
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.12.3; CommandName: Connect-AzAccount; PSVersion: 5.1.20348.1366;
IsSuccess: False; Duration: 00:00:00.4086243; Exception: Entry point was not found.;
DEBUG: 1:03:46 PM - ConnectAzureRmAccountCommand end processing.
```

**Comment by linuxpizzacats** [comment]
I have similar issues with Powershell Extensions inside vscode. 

When running Connect-AzAccount with module version 2.12.3 I get the following error:

```
Connect-AzAccount : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 
'Microsoft.Azure.PowerShell.Clients.ResourceManager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
At C:\Users\SX956NZ\git\ps-test\test.ps1:1 char:1
+ Connect-AzAccount
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-AzAccount], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand

````

Not happening with previous 2.12.2

**Comment by buttspie** [comment]
I'm having the same issue and found that if the dbatools module (version 2.0.4) is imported it causes this issue with Connect-AzAccount.  If I run Connect-AzAccount before importing dbatools, then it connects successfully.

**Comment by jberezanski** [comment]
This probably means that some other module imported before Az.Accounts loads an earlier and incompatible version of assembly Azure.Core.dll. I've seen it happen with Microsoft.Graph.Authentication 2.0.0-rc3 - it contains Azure.Core 1.25, but recent Az.Accounts module versions need a newer Azure.Core (Az.Accounts 2.12.3 uses Azure.Core 1.31, if I'm not mistaken).

I can see that the dbatools module contains Azure.Core 1.25, same as Microsoft.Graph.Authentication 2.0.0-rc3. I don't see any other workaround than ensuring Az.Accounts is imported first and Connect-AzAccount is called before the other modules are imported.

**Comment by wintec01** [comment]
Hello, any news here?
I am currently struggling with same issue.

Using Az.Accounts 2.13.1 and Connect-AzAccount or Login-AzAccount is working fine for normal and ISE environment.

But I am trying to run PowerShell from an external tool (Adaxes) and there I always get entry point error ...

**Comment by robinmalik** [comment]
Possibly related: https://github.com/Azure/azure-powershell/issues/21398

I get the 'entry point was not found' error under PS5.1 but not PS7.

**Comment by ngcdev** [comment]
I'm experiencing the same issue using `-Identity` parameter.
