### ISSUE TITLE
Get-AzKeyVaultSecret failed if log in with accesstoken

### ISSUE THREAD

**Issue by Yan1-MSFT** [Azure/azure-powershell#22035]
### Description

For the same command `Get-AzKeyVaultSecret -VaultName x -Name x -AsPlainText`, it works if we log in (Connect-AzAccount) with credential while it return error if we log in with AccessToken.
Both credential and AccessToken are from the same AAD.
The error message is:

```
Get-AzKeyVaultSecret: Operation returned an invalid status code 'Unauthorized'
Code: Unauthorized
Message: AKV10000: Request is missing a Bearer or PoP token.
```

### Issue script & Debug output

```PowerShell
>Clear-AzContext -Force
>Connect-AzAccount -Credential $pscred -ServicePrincipal -Tenant x -SubscriptionId x -Environment AzureCloud
>Get-AzKeyVaultSecret -VaultName x -Name x -AsPlainText
# works

>Clear-AzContext -Force
>Connect-AzAccount -Environment AzureCloud -Tenant x -AccountId x -AccessToken x -Subscription x -ErrorAction Stop -Force
>Get-AzKeyVaultSecret -VaultName x -Name x -AsPlainText
Get-AzKeyVaultSecret: Operation returned an invalid status code 'Unauthorized'
Code: Unauthorized
Message: AKV10000: Request is missing a Bearer or PoP token.
# not working
```
```


### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
9.4.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is…
2.12.3               Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Res…
2.0.0                Az.Advisor                          PSGallery            Microsoft Azure PowerShell: Advisor cmdlets
5.3.0                Az.Aks                              PSGallery            Microsoft Azure PowerShell - Azure managed Kubernetes cmdlets for Windows PowerSh…
1.1.4                Az.AnalysisServices                 PSGallery            Microsoft Azure PowerShell - Analysis Services cmdlets for Windows PowerShell and…
4.0.2                Az.ApiManagement                    PSGallery            Microsoft Azure PowerShell - Api Management service cmdlets for Azure Resource Ma…
1.2.0                Az.AppConfiguration                 PSGallery            Microsoft Azure PowerShell: AppConfiguration cmdlets
2.2.2                Az.ApplicationInsights              PSGallery            Microsoft Azure PowerShell: ApplicationInsights cmdlets
2.0.0                Az.Attestation                      PSGallery            Microsoft Azure PowerShell - Attestation service cmdlets for Azure Resource Manag…
1.9.0                Az.Automation                       PSGallery            Microsoft Azure PowerShell - Automation service cmdlets for Azure Resource Manage…
3.3.0                Az.Batch                            PSGallery            Microsoft Azure PowerShell - Batch service cmdlets for Azure Resource Manager in …
2.0.0                Az.Billing                          PSGallery            Microsoft Azure PowerShell - Billing service cmdlets for Azure Resource Manager i…
2.1.0                Az.Cdn                              PSGallery            Microsoft Azure PowerShell: Cdn cmdlets
1.1.0                Az.CloudService                     PSGallery            Microsoft Azure PowerShell: CloudService cmdlets
1.12.0               Az.CognitiveServices                PSGallery            Microsoft Azure PowerShell - Cognitive Services management cmdlets for Azure Reso…
5.4.0                Az.Compute                          PSGallery            Microsoft Azure PowerShell - Compute service cmdlets for Azure Resource Manager i…
1.0.0                Az.ConfidentialLedger               PSGallery            Microsoft Azure PowerShell: ConfidentialLedger cmdlets
3.1.0                Az.ContainerInstance                PSGallery            Microsoft Azure PowerShell: ContainerInstance cmdlets
3.0.1                Az.ContainerRegistry                PSGallery            Microsoft Azure PowerShell - Container Registry service cmdlets for Azure Resourc…
1.9.0                Az.CosmosDB                         PSGallery            Microsoft Azure PowerShell - CosmosDB service cmdlets for Azure Resource Manager …
1.1.0                Az.DataBoxEdge                      PSGallery            Microsoft Azure PowerShell - DataBoxEdge service cmdlets for Azure Resource Manag…
1.4.0                Az.Databricks                       PSGallery            Microsoft Azure PowerShell: Databricks cmdlets
1.16.12              Az.DataFactory                      PSGallery            Microsoft Azure PowerShell - Data Factory service cmdlets for Azure Resource Mana…
1.0.2                Az.DataLakeAnalytics                PSGallery            Microsoft Azure PowerShell - Data Lake Analytics in Windows PowerShell and PowerS…
1.3.0                Az.DataLakeStore                    PSGallery            Microsoft Azure PowerShell - Azure Data Lake Store cmdlets in Windows PowerShell …
1.1.0                Az.DataProtection                   PSGallery            Microsoft Azure PowerShell: DataProtection cmdlets
1.0.1                Az.DataShare                        PSGallery            Microsoft Azure PowerShell - DataShare service cmdlets for Azure Resource Manager…
1.1.0                Az.DeploymentManager                PSGallery            PowerShell .Net Core Microsoft Azure PowerShell - Deployment Manager cmdlets for …
3.1.1                Az.DesktopVirtualization            PSGallery            Microsoft Azure PowerShell: DesktopVirtualization cmdlets
1.0.2                Az.DevTestLabs                      PSGallery            Microsoft Azure PowerShell - DevTest Labs service cmdlets for Azure Resource Mana…
1.1.2                Az.Dns                              PSGallery            Microsoft Azure PowerShell - DNS service cmdlets for Azure Resource Manager in Wi…
1.5.0                Az.EventGrid                        PSGallery            Microsoft Azure PowerShell - Event Grid service cmdlets for Azure Resource Manage…
3.2.1                Az.EventHub                         PSGallery            Microsoft Azure PowerShell - Event Hubs service cmdlets for Azure Resource Manage…
1.9.0                Az.FrontDoor                        PSGallery            Microsoft Azure PowerShell - Front Door service cmdlets for Azure Resource Manage…
4.0.6                Az.Functions                        PSGallery            Microsoft Azure PowerShell - Azure Functions service cmdlets for Azure Resource M…
5.0.1                Az.HDInsight                        PSGallery            Microsoft Azure PowerShell - HDInsight service cmdlets for Azure Resource Manager…
2.0.0                Az.HealthcareApis                   PSGallery            Microsoft Azure PowerShell: HealthcareApis cmdlets
2.7.4                Az.IotHub                           PSGallery            Microsoft Azure PowerShell - IoT Hub service cmdlets for Azure Resource Manager i…
4.10.0               Az.KeyVault                         PSGallery            Microsoft Azure PowerShell - Key Vault service cmdlets for Azure Resource Manager…
2.1.0                Az.Kusto                            PSGallery            Microsoft Azure PowerShell: Kusto cmdlets
1.5.0                Az.LogicApp                         PSGallery            Microsoft Azure PowerShell - Logic Apps cmdlets for Azure Resource Manager in Win…
1.1.3                Az.MachineLearning                  PSGallery            Microsoft Azure PowerShell - Machine Learning Web Services cmdlets for Azure Reso…
1.2.1                Az.Maintenance                      PSGallery            Microsoft Azure PowerShell - Maintenance cmdlets for Azure Resource Manager in Wi…
1.1.0                Az.ManagedServiceIdentity           PSGallery            Microsoft Azure PowerShell: ManagedServiceIdentity cmdlets
3.0.0                Az.ManagedServices                  PSGallery            Microsoft Azure PowerShell: ManagedServices cmdlets
2.0.0                Az.MarketplaceOrdering              PSGallery            Microsoft Azure PowerShell: MarketplaceOrdering cmdlets
1.1.1                Az.Media                            PSGallery            Microsoft Azure PowerShell - Media service cmdlets for Azure Resource Manager in …
2.1.0                Az.Migrate                          PSGallery            Microsoft Azure PowerShell: Migrate cmdlets
4.4.1                Az.Monitor                          PSGallery            Microsoft Azure PowerShell - Monitor service cmdlets for Azure Resource Manager i…
1.1.0                Az.MySql                            PSGallery            Microsoft Azure PowerShell: MySql cmdlets
5.4.0                Az.Network                          PSGallery            Microsoft Azure PowerShell - Networking service cmdlets for Azure Resource Manage…
1.1.1                Az.NotificationHubs                 PSGallery            Microsoft Azure PowerShell - Notification Hubs cmdlets for Azure Resource Manager…
3.2.0                Az.OperationalInsights              PSGallery            Microsoft Azure PowerShell - Operational Insights service cmdlets for Azure Resou…
1.5.1                Az.PolicyInsights                   PSGallery            Microsoft Azure PowerShell - Azure Policy Insights cmdlets for Windows PowerShell…
1.1.0                Az.PostgreSql                       PSGallery            Microsoft Azure PowerShell: PostgreSql cmdlets
1.2.0                Az.PowerBIEmbedded                  PSGallery            Microsoft Azure PowerShell - Power BI Embedded service management cmdlets for Azu…
1.0.3                Az.PrivateDns                       PSGallery            Microsoft Azure PowerShell - Private DNS service cmdlets for Azure Resource Manag…
6.2.0                Az.RecoveryServices                 PSGallery            Microsoft Azure PowerShell - Recovery Services cmdlets for Azure Resource Manager…
1.7.1                Az.RedisCache                       PSGallery            Microsoft Azure PowerShell - Redis Cache service cmdlets for Azure Resource Manag…
1.1.0                Az.RedisEnterpriseCache             PSGallery            Microsoft Azure PowerShell: RedisEnterpriseCache cmdlets
1.0.3                Az.Relay                            PSGallery            Microsoft Azure PowerShell - Relay service cmdlets for Azure Resource Manager in …
1.1.0                Az.ResourceMover                    PSGallery            Microsoft Azure PowerShell: ResourceMover cmdlets
6.5.2                Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resource Manager and Active Directory cmdlets …
1.3.0                Az.Security                         PSGallery            Microsoft Azure PowerShell - Azure Security Center cmdlets in Windows PowerShell …
3.0.1                Az.SecurityInsights                 PSGallery            Microsoft Azure PowerShell: SecurityInsights cmdlets
2.1.0                Az.ServiceBus                       PSGallery            Microsoft Azure PowerShell - Service Bus service cmdlets for Azure Resource Manag…
3.1.0                Az.ServiceFabric                    PSGallery            Microsoft Azure PowerShell - Service Fabric cmdlets for Azure Resource Manager in…
1.5.0                Az.SignalR                          PSGallery            Microsoft Azure PowerShell - Azure SignalR service commands for Windows PowerShel…
4.3.0                Az.Sql                              PSGallery            Microsoft Azure PowerShell - SQL service cmdlets for Azure Resource Manager in Wi…
1.1.0                Az.SqlVirtualMachine                PSGallery            Microsoft Azure PowerShell - SqlVirtualMachine service cmdlets for Azure Resource…
1.4.2                Az.StackHCI                         PSGallery            Microsoft Azure PowerShell: StackHci cmdlets
5.4.0                Az.Storage                          PSGallery            Microsoft Azure PowerShell - Storage service data plane and management cmdlets fo…
1.7.0                Az.StorageSync                      PSGallery            Microsoft Azure PowerShell - Storage Sync cmdlets in Windows PowerShell and Power…
2.0.0                Az.StreamAnalytics                  PSGallery            Microsoft Azure PowerShell: StreamAnalytics cmdlets
1.0.0                Az.Support                          PSGallery            Microsoft Azure PowerShell - Azure Support cmdlets for Azure Resource Manager in …
2.2.0                Az.Synapse                          PSGallery            Microsoft Azure PowerShell - Azure Synapse Analytics in Windows PowerShell and Po…
1.2.0                Az.TrafficManager                   PSGallery            Microsoft Azure PowerShell - Traffic Manager service cmdlets for Azure Resource M…
2.12.1               Az.Websites                         PSGallery            Microsoft Azure PowerShell - App Service (Web Apps) service cmdlets for Azure Res…
```

### Error output

```PowerShell
HistoryId: 8

Message        : Operation returned an invalid status code 'Unauthorized'
                 Code: Unauthorized
                 Message: AKV10000: Request is missing a Bearer or PoP token.
StackTrace     :    at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecret(String vaultName, String secretName, String secretVersion)
                    at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.KeyVault.Models.KeyVaultErrorException
InvocationInfo : {Get-AzKeyVaultSecret}
Line           : Get-AzKeyVaultSecret -VaultName siotest -Name vmUserName -AsPlainText
Position       : At line:1 char:1
                 + Get-AzKeyVaultSecret -VaultName siotest -Name vmUserName -AsPlainText
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8

Message        : Operation returned an invalid status code 'Unauthorized'
StackTrace     :    at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion,
                 Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String secretIdentifier, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecret(String vaultName, String secretName, String secretVersion)
Exception      : Microsoft.Azure.KeyVault.Models.KeyVaultErrorException
InvocationInfo : {Get-AzKeyVaultSecret}
Line           : Get-AzKeyVaultSecret -VaultName siotest -Name vmUserName -AsPlainText
Position       : At line:1 char:1
                 + Get-AzKeyVaultSecret -VaultName siotest -Name vmUserName -AsPlainText
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8


   HistoryId: 3

Message        : Operation returned an invalid status code 'Unauthorized'
                 Code: Unauthorized
                 Message: AKV10000: Request is missing a Bearer or PoP token.
StackTrace     :    at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecret(String vaultName, String secretName, String secretVersion)
                    at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.KeyVault.Models.KeyVaultErrorException
InvocationInfo : {Get-AzKeyVaultSecret}
Line           : Get-AzKeyVaultSecret -VaultName x -Name x -AsPlainText
Position       : At line:1 char:1
                 + Get-AzKeyVaultSecret -VaultName x -Name x -AsPlainText
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

Message        : Operation returned an invalid status code 'Unauthorized'
StackTrace     :    at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion,
                 Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String secretIdentifier, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecret(String vaultName, String secretName, String secretVersion)
Exception      : Microsoft.Azure.KeyVault.Models.KeyVaultErrorException
InvocationInfo : {Get-AzKeyVaultSecret}
Line           : Get-AzKeyVaultSecret -VaultName x -Name x -AsPlainText
Position       : At line:1 char:1
                 + Get-AzKeyVaultSecret -VaultName x -Name x -AsPlainText
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3
```

**Comment by isra-fel** [comment]
Thanks for reporting. When Connect-AzAccount with access token, make sure you provide not only the AT of Azure Resource Manager for management plane operations, but also the necessary data plane ATs if you intend to run data plane cmdlets.
In your case, make sure to provide -KeyVaultAccessToken when Connect-AzAccount
