### ISSUE TITLE
Enable-AzRecoveryServicesBackupProtection: 'containerName' cannot be null. - Az.RecoveryServices 6.3.0

### ISSUE THREAD

**Issue by GR3V3N** [Azure/azure-powershell#22032]
### Description

When I am trying to back up a storage account share I get an error that the container name is empty even though it is not, I have confirmed it many times and tried diffrent versions of the module but get the same error.

Im running the command like this:
Enable-AzRecoveryServicesBackupProtection -Name $sharename -Policy $Pol -StorageAccountName $myStorageAccount.StorageAccountName -VaultId $Vault.ID

### Issue script & Debug output

```PowerShell
Enable-AzRecoveryServicesBackupProtection: 'containerName' cannot be null.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Darwin 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:19:12 PDT 2022; root:xnu-8792.41.9~3/RELEASE_ARM64_T6020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.3.0                 Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Backup-AzRecoveryServicesBackupItem, Copy-AzRecoveryServicesVault, Disable-AzRecoveryServicesBackupAutoProtection…}
Script     6.5.3                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     5.6.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
```

### Error output

```PowerShell
Message        : 'containerName' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.RecoveryServices.Backup.ProtectionContainersOperations.InquireWithHttpMessagesAsync(String vaultName, String resourceGroupName, String fabricName, String containerName, ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {Enable-AzRecoveryServicesBackupProtection}
Line           :         Enable-AzRecoveryServicesBackupProtection -Name $sharename -Policy $Pol -StorageAccountName $myStorageAccount.StorageAccountName -VaultId $Vault.ID
                 
Position       : At line:18 char:9
                 +         Enable-AzRecoveryServicesBackupProtection -Name $sharename -P …
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9


   HistoryId: 3

Message        : Cannot validate argument on parameter 'ResourceId'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
                    at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Get-AzResource}
Line           : Get-AzResource -ResourceId $resourceid
Position       : At line:1 char:28
                 + Get-AzResource -ResourceId $resourceid
                 +                            ~~~~~~~~~~~
HistoryId      : 3

Message        : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
Exception      : System.Management.Automation.ValidationMetadataException
InvocationInfo : {Get-AzResource}
Line           : Get-AzResource -ResourceId $resourceid
Position       : At line:1 char:28
                 + Get-AzResource -ResourceId $resourceid
                 +                            ~~~~~~~~~~~
HistoryId      : 3
```

**Comment by superfliege** [comment]
Same Problem here. i use also powershell 7.3 and the newest az module versions.
Error: Enable-AzRecoveryServicesBackupProtection: 'containerName' cannot be null.

**Comment by adityabalaji-msft** [comment]
@Daya-Patil , @hiaga - could you help review the above and if it is still occurring, and if this is expected behaviour? Since another user reported this to me recently

**Comment by hiaga** [comment]
Ack, we're looking into this and will fix this in upcoming release. 

@GR3V3N, @superfliege can you please share the complete debug trace with us after adding -Debug parameter to the command

**Comment by hiaga** [comment]
@GR3V3N, @superfliege not able to reproduce this issue in latest release. can you please share debug trace after adding -Debug parameter or check if you are still facing this issue.

**Comment by Daya-Patil** [comment]
@GR3V3N @superfliege A gentle reminder to update on the issue

**Comment by GR3V3N** [comment]
> @GR3V3N, @superfliege not able to reproduce this issue in latest release. can you please share debug trace after adding -Debug parameter or check if you are still facing this issue.

Hi Superfliege, i am unable to reproduce the issue rn, so probably fixed with a newer release ty.
