### ISSUE TITLE
Unable to use VMPublicIPUpgrade

### ISSUE THREAD

**Issue by tpautschSPS** [Azure/azure-powershell#22133]
### Description

Followed the Learn page documentation and script will not run. Always gets the same error message:

InvalidOperation: Unable to find type [Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine].

### Script or Debug output

```PowerShell
PS C:\Users\admin_tpautsch> Start-VMPublicIPUpgrade -VMname 'AZSWCO127' -ResourceGroupName 'rg-infra-cloud-sub-vdi-02' -WhatIf
InvalidOperation: Unable to f$PSind type [Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine].
```

### Environment data

```PowerShell
PS C:\Users\admin_tpautsch> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.1
PSEdition                      Core
GitCommitId                    7.3.1
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Users\admin_tpautsch> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     1.0.0                 AzureVMPublicIPUpgrade              Start-VMPublicIPUpgrade
Resolve
```

### Error output

```PowerShell
PS C:\Users\admin_tpautsch> Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: -1

Message        : Unable to find type [Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine].
StackTrace     :    at System.Management.Automation.TypeOps.ResolveTypeName(ITypeName typeName, IScriptExtent errorPos)
                    at System.Management.Automation.Language.Compiler.GetAttribute(TypeConstraintAst typeConstraintAst)
                    at System.Management.Automation.Language.Compiler.GetRuntimeDefinedParameter(ParameterAst
                 parameterAst, Boolean& customParameterSet, Boolean& usesCmdletBinding)
                    at System.Management.Automation.Language.Compiler.GetParameterMetaData(ReadOnlyCollection`1
                 parameters, Boolean automaticPositions, Boolean& usesCmdletBinding)
                    at System.Management.Automation.CompiledScriptBlockData.InitializeMetadata()
                    at System.Management.Automation.CompiledScriptBlockData.Compile(Boolean optimized)
                    at System.Management.Automation.PSScriptCmdlet..ctor(ScriptBlock scriptBlock, Boolean useNewScope,
                 Boolean fromScriptFile, ExecutionContext context)
                    at System.Management.Automation.CommandProcessor.Init(IScriptCommandInfo scriptCommandInfo)
                    at System.Management.Automation.CommandDiscovery.GetScriptAsCmdletProcessor(IScriptCommandInfo
                 scriptCommandInfo, ExecutionContext context, Boolean useNewScope, Boolean fromScriptFile,
                 SessionStateInternal sessionState)
                    at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(FunctionInfo
                 functionInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo,
                 CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe,
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[]
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :         [Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine]

Position       : At C:\Users\admin_tpautsch\Documents\PowerShell\Modules\AzureVMPublicIPUpgrade\1.0.0\AzureVMPublicIPUp
                 grade.psm1:85 char:9
                 +         [Microsoft.Azure.Commands.Compute.Models.PSVirtualMachine]
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1


   HistoryId: 7

Message        : InteractiveBrowserCredential authentication failed: User canceled authentication.
StackTrace     :    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String
                 additionalMessage)
                    at Azure.Identity.InteractiveBrowserCredential.AuthenticateImplAsync(Boolean async,
                 TokenRequestContext requestContext, CancellationToken cancellationToken)
                    at Azure.Identity.InteractiveBrowserCredential.AuthenticateAsync(TokenRequestContext
                 requestContext, CancellationToken cancellationToken)
                    at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.GetAccessTokenAsync(Task`1 authTask,
                 TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzu
                 reAccount account, IAzureEnvironment environment, String tenant, SecureString password, String
                 promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at
                 Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount
                 account, IAzureEnvironment environment, String tenantId, SecureString password, String
                 promptBehavior, Action`1 promptAction, String resourceId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account,
                 IAzureEnvironment environment, String tenantIdOrName, String subscriptionId, String subscriptionName,
                 SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean
                 shouldPopulateContextList, Int32 maxContextPopulation, String authScope)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass127_2.<ExecuteCmd
                 let>b__5()
                    at System.Threading.Tasks.Task`1.InnerInvoke()
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread,
                 ExecutionContext executionContext, ContextCallback callback, Object state)
                 --- End of stack trace from previous location ---
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread,
                 ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread
                 threadPoolThread)
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass127_0.<ExecuteCmd
                 let>b__1(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass136_0.<SetContext
                 WithOverwritePrompt>b__0(AzureRmProfile prof, RMProfileClient client)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2
                 contextAction)
                    at
                 Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3
                 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Azure.Identity.AuthenticationFailedException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -Tenant 4835d31c-bdea-4a37-ba1d-b928ff9aee7b -Subscription
                 a041fa6d-8193-46cb-8952-50911dbc4cde
Position       : At line:1 char:1
                 + Connect-AzAccount -Tenant 4835d31c-bdea-4a37-ba1d-b928ff9aee7b -Subsc …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : User canceled authentication.
StackTrace     :    at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.VerifyAuthorizationResult(Authorizat
                 ionResult authorizationResult, String originalState)
                    at
                 Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceInternalAsync(IWebUI
                 webUi, CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(Ca
                 ncellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(Cancellatio
                 nToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenComm
                 onParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters,
                 CancellationToken cancellationToken)
                    at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTok
                 enParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveCoreAsync(String[] scopes, String
                 claims, Prompt prompt, String loginHint, String tenantId, Boolean async, CancellationToken
                 cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveAsync(String[] scopes, String claims,
                 Prompt prompt, String loginHint, String tenantId, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.InteractiveBrowserCredential.GetTokenViaBrowserLoginAsync(TokenRequestContext
                 context, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.InteractiveBrowserCredential.AuthenticateImplAsync(Boolean async,
                 TokenRequestContext requestContext, CancellationToken cancellationToken)
Exception      : Microsoft.Identity.Client.MsalClientException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -Tenant 4835d31c-bdea-4a37-ba1d-b928ff9aee7b -Subscription
                 a041fa6d-8193-46cb-8952-50911dbc4cde
Position       : At line:1 char:1
                 + Connect-AzAccount -Tenant 4835d31c-bdea-4a37-ba1d-b928ff9aee7b -Subsc …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7
```

**Comment by isra-fel** [comment]
Hi @tpautschSPS I presume you were following this document, ["Upgrade public IP addresses attached to VM from Basic to Standard"](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-upgrade-vm)?

Can you run `Import-Module Az` before `Start-VMPublicIPUpgrade`?
If it doesn't work, please share the modules installed on you system by running `Get-Module Az* -ListAvailable`.
