### ISSUE TITLE
New-AzRoleAssignment: 'PrincipalId' cannot be null. 

### ISSUE THREAD

**Issue by samyi001** [Azure/azure-powershell#22139]
### Description

When running command in Powershell - tested in Azure Cloud Shell and local machine:
New-AzRoleAssignment -ResourceGroupName <rgname> -SignInName "email@gmail.com" -RoleDefinitionName Reader -AllowDelegation

I receive error:
New-AzRoleAssignment: 'PrincipalId' cannot be null. 

### Issue script & Debug output

```PowerShell
PS> New-AzRoleAssignment -ResourceGroupName name -SignInName "email@email.com" -RoleDefinitionName Reader -AllowDelegation
DEBUG: 3:26:22 PM - NewAzureRoleAssignmentCommand begin processing with ParameterSet 'ResourceGroupWithSignInNameParameterSet'.
DEBUG: 3:26:22 PM - using account id '<account ID Removed>'...
DEBUG: 3:26:22 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: '<account ID Removed>', environment: 'AzureCloud', tenant: '<Tenant Removed>'
DEBUG: 3:26:22 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'<Tenant Removed>', Scopes:'https://graph.microsoft.com/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com/ ] ParentRequestId: 
DEBUG: Request [f7ca1be0-1e9c-4828-8a87-37ee7a2fb540] POST http://localhost:50342/oauth2/token
Content-Type:application/x-www-form-urlencoded
Metadata:REDACTED
x-ms-client-request-id:f7ca1be0-1e9c-4828-8a87-37ee7a2fb540
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.1 (.NET 7.0.5; Linux 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023)
client assembly: Azure.Identity
DEBUG: Response [f7ca1be0-1e9c-4828-8a87-37ee7a2fb540] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"b0c-joMvEvgWRALrrN60Ccm/9vEi2A0"
Date:Thu, 22 Jun 2023 15:26:22 GMT
Connection:keep-alive
Keep-Alive:REDACTED
Content-Type:application/json; charset=utf-8
Content-Length:2828

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://graph.microsoft.com/ ] ParentRequestId:  ExpiresOn: 2023-06-22T16:35:17.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<Tenant Removed>', UserId: '<account ID Removed>'
DEBUG: [Common.Authentication]: Authenticating using Account: '<account ID Removed>', environment: 'AzureCloud', tenant: '<Tenant Removed>'
DEBUG: 3:26:22 PM - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'<Tenant Removed>', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId: 
DEBUG: Request [15ac3f88-2e34-422a-8fae-158987e198b7] POST http://localhost:50342/oauth2/token
Content-Type:application/x-www-form-urlencoded
Metadata:REDACTED
x-ms-client-request-id:15ac3f88-2e34-422a-8fae-158987e198b7
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.1 (.NET 7.0.5; Linux 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023)
client assembly: Azure.Identity
DEBUG: Response [15ac3f88-2e34-422a-8fae-158987e198b7] 200 OK (00.0s)
X-Powered-By:REDACTED
ETag:W/"989-BPPilpF39tUd93z/J/n9aG8uBts"
Date:Thu, 22 Jun 2023 15:26:22 GMT
Connection:keep-alive
Keep-Alive:REDACTED
Content-Type:application/json; charset=utf-8
Content-Length:2441

DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  ExpiresOn: 2023-06-22T16:44:07.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '<Tenant Removed>', UserId: '<account ID Removed>'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/users?$filter=userPrincipalName eq %27removed%40gmail.com%27

Headers:
Accept-Language               : en-US
ConsistencyLevel              : eventual
x-ms-client-request-id        : 745591b0-f43e-4960-a5b8-70d9618dd152

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Strict-Transport-Security     : max-age=31536000
request-id                    : e1d760f8-13df-46dd-bf0d-73c5b4bc7123
client-request-id             : e1d760f8-13df-46dd-bf0d-73c5b4bc7123
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"East US","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"BL6PEPF00018897"}}
x-ms-resource-unit            : 2
OData-Version                 : 4.0
Date                          : Thu, 22 Jun 2023 15:26:22 GMT

Body:
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users",
  "value": []
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com//subscriptions/<SubID Removed>/resourceGroups/ubu/providers/Microsoft.Authorization/roleDefinitions?$filter=roleName eq 'Reader'&api-version=2018-01-01-preview

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 745591b0-f43e-4960-a5b8-70d9618dd152

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : a22047ef-fc74-4ac3-a30c-b678b1724182
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Set-Cookie                    : x-ms-gateway-slice=Production; path=/; secure; samesite=none; httponly
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : 9df90dad-6bf6-4adc-ac71-349e5e4a0430
x-ms-routing-request-id       : EASTUS:20230622T152622Z:9df90dad-6bf6-4adc-ac71-349e5e4a0430
Date                          : Thu, 22 Jun 2023 15:26:22 GMT

Body:
{
  "value": [
    {
      "properties": {
        "roleName": "Reader",
        "type": "BuiltInRole",
        "description": "View all resources, but does not allow you to make any changes.",
        "assignableScopes": [
          "/"
        ],
        "permissions": [
          {
            "actions": [
              "*/read"
            ],
            "notActions": [],
            "dataActions": [],
            "notDataActions": []
          }
        ],
        "createdOn": "2015-02-02T21:55:09.8806423Z",
        "updatedOn": "2021-11-11T20:13:47.8628684Z",
        "createdBy": null,
        "updatedBy": null
      },
      "id": "/subscriptions/<SubID Removed>/providers/Microsoft.Authorization/roleDefinitions/acdd72a7-3385-48ef-bd42-f606fba81ae7",
      "type": "Microsoft.Authorization/roleDefinitions",
      "name": "acdd72a7-3385-48ef-bd42-f606fba81ae7"
    }
  ]
}


DEBUG: 3:26:22 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
New-AzRoleAssignment: 'PrincipalId' cannot be null.
DEBUG: 3:26:22 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:26:22 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Resources:6.7.0; CommandName: New-AzRoleAssignment; PSVersion: 7.3.4; IsSuccess: False; Duration: 00:00:00.3168891; Exception: 'PrincipalId' cannot be null.;
DEBUG: 3:26:22 PM - NewAzureRoleAssignmentCommand end processing.
```

### Environment data

```PowerShell
PS>  $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Linux 5.4.0-1109-azure #115~18.04.1-Ubuntu SMP Mon May 22 20:06:37 UTC 2023
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS> get-module az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.0.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     6.0.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayB…
Script     6.7.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     5.7.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-Az…
Script     1.1.1                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, Open-AzPredictorSurvey, Send-AzPredictorRating}
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRole…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
PS> Resolve-AzError
DEBUG: 3:29:20 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 3:29:20 PM - using account id 'MSI@50342'...
DEBUG: 3:29:20 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 5

Message        : 'PrincipalId' cannot be null.
StackTrace     :    at Microsoft.Azure.Management.Authorization.Models.RoleAssignmentCreateParameters.Validate()
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperations.CreateWithHttpMessagesAsync(String scope, String roleAssignmentName, RoleAssignmentCreateParameters 
                 parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.CreateAsync(IRoleAssignmentsOperations operations, String scope, String 
                 roleAssignmentName, RoleAssignmentCreateParameters parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.Create(IRoleAssignmentsOperations operations, String scope, String roleAssignmentName, 
                 RoleAssignmentCreateParameters parameters)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.CreateRoleAssignment(FilterRoleAssignmentsOptions parameters, Guid roleAssignmentId)
                    at Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.ValidationException
InvocationInfo : {New-AzRoleAssignment}
Line           : New-AzRoleAssignment -ResourceGroupName ubu -SignInName "email@gmail.com" -RoleDefinitionName Reader -AllowDelegation
Position       : At line:1 char:1
                 + New-AzRoleAssignment -ResourceGroupName ubu -SignInName "email…
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5
```

**Comment by isra-fel** [comment]
Hi, the error indicated that the signed in user didn't have the permission of Graph API to query the principal ID of the assignee. You can assign the ["User.Read.All"](https://learn.microsoft.com/en-us/graph/permissions-reference#delegated-permissions-96) permission to the signed in user then try again, or if you do know the object ID of the assignee, you can use `-ObjectId` instead of `-SignInName`.

**Comment by samyi001** [comment]
Hi, I tested this in my test sub. Can you provide in more detail how to add the permissions?  The user account I am using is a Global Administrator for the Directory

/unresolve

**Comment by samyi001** [comment]
Hi, just to update: I think the userprincipalID appears different from email address for some users (external) which is why this error is occurring. 

For example: with an external user, the principalID is **(bold is replaced)**
**__email_**gmail.com#EXT#@**_email_**gmail.onmicrosoft.com_
