### ISSUE TITLE
create-a-firewall-attached-to-a-virtual-hub failed due to "HubIPAddressNotProvidedForCurrentApiVersion"

### ISSUE THREAD

**Issue by yinoa** [Azure/azure-powershell#22172]
### Description

create-a-firewall-attached-to-a-virtual-hub failed due to "HubIPAddressNotProvidedForCurrentApiVersion"

Public Link:
https://learn.microsoft.com/en-us/powershell/module/az.network/new-azfirewall?view=azps-10.0.0#example-9-create-a-firewall-attached-to-a-virtual-hub

### Issue script & Debug output

```PowerShell
PS C:\> $fp = Get-AzFirewallPolicy -ResourceGroupName "alexinternalRG" -Name "alexFirewallPolicy"
PS C:\> $fpId = $fp.Id
PS C:\> $vHub = Get-AzVirtualHub -ResourceGroupName "NetworkWatcherRG" -Name "alexseavhub"
PS C:\> $vHubId = $vHub.Id
PS C:\>
PS C:\> New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub -VirtualHubId $vHubId -FirewallPolicyId $fpId
New-AzFirewall: HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
ErrorMessage: HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
OperationID : 254dee0e-9dff-4c18-a7e8-9bb0f2a496fb
```

### Environment data

```PowerShell
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      2      11
```

### Module versions

```PowerShell
PS C:\> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.0.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, Add-AzAp…
```

### Error output

```PowerShell
PS C:\> Resolve-AzError
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 41

RequestId      : 
Message        : HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual    
                 Hub /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
                 ErrorMessage: HubIPAddresses not provided for Azure Firewall
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 OperationID : 254dee0e-9dff-4c18-a7e8-9bb0f2a496fb
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {New-AzFirewall}
Line           : New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub -VirtualHubId $vHubId -FirewallPolicyId $fpId
Position       : At line:1 char:1
                 + New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatch …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 41


   HistoryId: 34

RequestId      : 
Message        : HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual    
                 Hub /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
                 ErrorMessage: HubIPAddresses not provided for Azure Firewall
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 OperationID : adbcabe4-d27c-4dc4-b867-cb2cdf48e6dc
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {New-AzFirewall}
Line           : New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub -VirtualHubId $vHubId -FirewallPolicyId $fpId
Position       : At line:1 char:1
                 + New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatch …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 34


   HistoryId: 33

RequestId      : 
Message        : HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual    
                 Hub  for API version 2020-04-01.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
                 ErrorMessage: HubIPAddresses not provided for Azure Firewall
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub  for API version 2020-04-01.
                 OperationID : c620ec87-ac84-47ed-b26d-e8aa441e8e2e
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {New-AzFirewall}
Line           : New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName "AZFW_Hub"
Position       : At line:1 char:1
                 + New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatch …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 33


   HistoryId: 32

RequestId      : 
Message        : HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual    
                 Hub  for API version 2020-04-01.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
                 ErrorMessage: HubIPAddresses not provided for Azure Firewall
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub  for API version 2020-04-01.
                 OperationID : 6111c454-d227-405e-ad91-31d8143f5352
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {New-AzFirewall}
Line           : New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub
Position       : At line:1 char:1
                 + New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatch …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 32


   HistoryId: 31

RequestId      : 
Message        : HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual    
                 Hub /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
                 ErrorMessage: HubIPAddresses not provided for Azure Firewall
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 OperationID : b2454b05-5496-43e8-937e-bce9743f4574
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {New-AzFirewall}
Line           : New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub -VirtualHubId $vHubId -FirewallPolicyId $fpId
Position       : At line:1 char:1
                 + New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatch …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 31


   HistoryId: 25

RequestId      : 
Message        : HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual    
                 Hub /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
                 ErrorMessage: HubIPAddresses not provided for Azure Firewall
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 OperationID : a6e3899f-fea0-432d-9e4a-f5a750917b9e
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {New-AzFirewall}
Line           : New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub -VirtualHubId $vHubId -FirewallPolicyId $fpId
Position       : At line:1 char:1
                 + New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatch …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 25


   HistoryId: 6

RequestId      : 
Message        : HubIPAddresses not provided for Azure Firewall /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual    
                 Hub /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: HubIPAddressNotProvidedForCurrentApiVersion
                 ErrorMessage: HubIPAddresses not provided for Azure Firewall
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/azureFirewalls/alexseavhubfw in Virtual Hub
                 /subscriptions/a3a61dba-9d76-4451-abb7-231da88d92ae/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/virtualHubs/alexseavhub for API version 2020-04-01.
                 OperationID : a9b3fcda-4f21-4127-a47e-c0ffc9146747
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {New-AzFirewall}
Line           : New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub -VirtualHubId $vHubId -FirewallPolicyId $fpId
Position       : At line:1 char:1
                 + New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatch …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 6
```

**Comment by yinoa** [comment]
I have resolved the issue. The sample provided in public guide is wrong which missed the "New-AzFirewallHubIpAddress" part.

Please update the guide with correct sample.

$fp = Get-AzFirewallPolicy -ResourceGroupName "alexinternalRG" -Name "alexFirewallPolicy"
$fpId = $fp.Id
$vHub = Get-AzVirtualHub -ResourceGroupName "NetworkWatcherRG" -Name "alexseavhub"
$vHubId = $vHub.Id

$fwpips = New-AzFirewallHubPublicIpAddress -Count 1
$HubIPAddress = New-AzFirewallHubIpAddress -PublicIP $fwpips

New-AzFirewall -Name "alexseavhubfw" -ResourceGroupName "NetworkWatcherRG" -Location southeastasia -SkuName AZFW_Hub -VirtualHubId $vHubId -HubIPAddress $HubIPAddress -FirewallPolicyId $fpId
