### ISSUE TITLE
Get-AzADServicePrincipal fails with AADSTS70011

### ISSUE THREAD

**Issue by haagha** [Azure/azure-powershell#22180]
### Description

Get-AzADServicePrincipal -ApplicationId "xxxxx" fails with the following error :

SharedTokenCacheCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input
     | parameter. The provided value for the input parameter 'scope' is not valid. The scope
     | MicrosoftGraphEndpointResourceId/.default offline_access openid profile is not valid. 

### Issue script & Debug output

```PowerShell
PS C:\azure-powershell2> Get-AzADServicePrincipal -ApplicationId xxxxx -DEBUG
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: Client side pagination is enabled for this cmdlet
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /servicePrincipals?$filter=AppId%20eq%20%xxxx
DEBUG: RequestCreated: /v1.0/servicePrincipals?$filter=AppId%20eq%20%xxxx%27
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://graph.microsoft.com/v1.0/servicePrincipals?$filter=AppId eq %27xxxx%27

Headers:
x-ms-unique-id                : 3
x-ms-client-request-id        : xxx
CommandName                   : Az.MSGraph.internal\Get-AzADServicePrincipal
FullCommandName               : Get-AzADServicePrincipal_List
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v0.0.0,PSVersion/v7.3.4,Az.MSGraph/6.0.1

Body:



DEBUG: BeforeCall:
DEBUG: Finally:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: [CmdletException]: Received Exception with message 'AuthenticationFailedException - SharedTokenCacheCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope MicrosoftGraphEndpointResourceId/.default offline_access openid profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.
Trace ID: xxxx
Correlation ID: xxxxx
Timestamp: 2023-06-26 20:58:37Z :    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.GetAccessTokenAsync(String callerClassName, String parametersLog, TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken, String tenantId, String userId, String homeAccountId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, String resourceId)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass15_0.<AuthorizeRequest>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Commands.Common.ContextAdapter.AuthorizeRequest(IAzureContext context, HttpRequestMessage request, CancellationToken cancellationToken, String endpointResourceIdKey, String endpointSuffixKey, Func`6 tokenAudienceConverter, IDictionary`2 extensibleParamters)
   at Microsoft.Azure.Commands.Common.ContextAdapter.AuthenticationHelper(IAzureContext context, String endpointResourceIdKey, String endpointSuffixKey, HttpRequestMessage request, CancellationToken cancelToken, Action cancelAction, Func`4 signal, Func`5 next, Func`6 tokenAudienceConverter)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass10_0.<<AddAuthorizeRequestHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass9_0.<<AddPatchRequestUriHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Module.SendAsync(HttpRequestMessage request, IEventListener callback, ISendAsync next)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalListServicePrincipal_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalListServicePrincipal_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalListServicePrincipal(String consistencyLevel, String Search, String Filter, Nullable`1 Count, String[] Orderby, String[] Select, String[] Expand, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.GetAzADServicePrincipal_List.ProcessRecordAsync()
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.GetAzADServicePrincipal_List.ProcessRecordAsync()'
DEBUG: CmdletException: AuthenticationFailedException - SharedTokenCacheCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope MicrosoftGraphEndpointResourceId/.default offline_access openid profile is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.
Trace ID: xxxxxxx
Correlation ID: xxxxxx
Timestamp: 2023-06-26 20:58:37Z :    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.SharedTokenCacheCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.GetAccessTokenAsync(String callerClassName, String parametersLog, TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken, String tenantId, String userId, String homeAccountId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, String resourceId)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass15_0.<AuthorizeRequest>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Commands.Common.ContextAdapter.AuthorizeRequest(IAzureContext context, HttpRequestMessage request, CancellationToken cancellationToken, String endpointResourceIdKey, String endpointSuffixKey, Func`6 tokenAudienceConverter, IDictionary`2 extensibleParamters)
   at Microsoft.Azure.Commands.Common.ContextAdapter.AuthenticationHelper(IAzureContext context, String endpointResourceIdKey, String endpointSuffixKey, HttpRequestMessage request, CancellationToken cancelToken, Action cancelAction, Func`4 signal, Func`5 next, Func`6 tokenAudienceConverter)
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass10_0.<<AddAuthorizeRequestHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass9_0.<<AddPatchRequestUriHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Module.SendAsync(HttpRequestMessage request, IEventListener callback, ISendAsync next)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalListServicePrincipal_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalListServicePrincipal_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalListServicePrincipal(String consistencyLevel, String Search, String Filter, Nullable`1 Count, String[] Orderby, String[] Select, String[] Expand, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.GetAzADServicePrincipal_List.ProcessRecordAsync()
   at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.GetAzADServicePrincipal_List.ProcessRecordAsync()
Get-AzADServicePrincipal_List: C:\Users\haagha\Documents\PowerShell\Modules\Az.Resources\6.0.1\MSGraph.Autorest\custom\Get-AzADServicePrincipal.ps1:208
Line |
 208 |      Az.MSGraph.internal\Get-AzADServicePrincipal @PSBoundParameters
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | SharedTokenCacheCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input
     | parameter. The provided value for the input parameter 'scope' is not valid. The scope
     | MicrosoftGraphEndpointResourceId/.default offline_access openid profile is not valid. The scope format is
     | invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>. Trace ID:
     | xxxxxxx Correlation ID: xxxxxxx Timestamp: 2023-06-26
     | 20:58:37Z
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent:  Module: Az.Resources:6.0.1; CommandName: Get-AzADServicePrincipal; PSVersion: 7.3.4; IsSuccess: True; Duration: 00:00:00.4422376
PS C:\azure-powershell2>
```

### Environment data

```PowerShell
PS C:\azure-powershell2> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\azure-powershell2> Get-Module -Name Az.Resources

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     6.0.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…
```

### Error output

```PowerShell
Message        : SharedTokenCacheCredential authentication failed: AADSTS70011: The provided request must include a
                 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope
                 MicrosoftGraphEndpointResourceId/.default offline_access openid profile is not valid. The scope
                 format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid
                 <guid/scope>.
                 Trace ID: ca51d844-9391-4971-8729-d61cdb1d8800
                 Correlation ID: e2a35a2e-a1a2-4b3e-bd55-f4dfc0c1e12f
                 Timestamp: 2023-06-26 21:04:03Z
StackTrace     :    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String
                 additionalMessage)
                    at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext
                 requestContext, CancellationToken cancellationToken)
                    at Azure.Identity.SharedTokenCacheCredential.GetTokenAsync(TokenRequestContext requestContext,
                 CancellationToken cancellationToken)
                    at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.GetAccessTokenAsync(String
                 callerClassName, String parametersLog, TokenCredential tokenCredential, TokenRequestContext
                 requestContext, CancellationToken cancellationToken, String tenantId, String userId, String
                 homeAccountId)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzu
                 reAccount account, IAzureEnvironment environment, String tenant, SecureString password, String
                 promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzu
                 reAccount account, IAzureEnvironment environment, String tenant, SecureString password, String
                 promptBehavior, Action`1 promptAction, String resourceId)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass15_0.<AuthorizeRequest>b__0()
                    at System.Threading.Tasks.Task`1.InnerInvoke()
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread,
                 ExecutionContext executionContext, ContextCallback callback, Object state)
                 --- End of stack trace from previous location ---
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread,
                 ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread
                 threadPoolThread)
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.Commands.Common.ContextAdapter.AuthorizeRequest(IAzureContext context,
                 HttpRequestMessage request, CancellationToken cancellationToken, String endpointResourceIdKey, String
                 endpointSuffixKey, Func`6 tokenAudienceConverter, IDictionary`2 extensibleParamters)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.AuthenticationHelper(IAzureContext context,
                 String endpointResourceIdKey, String endpointSuffixKey, HttpRequestMessage request, CancellationToken
                 cancelToken, Action cancelAction, Func`4 signal, Func`5 next, Func`6 tokenAudienceConverter)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass10_0.<<AddAuthorizeRequestHandle
                 r>b__0>d.MoveNext()
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass9_0.<<AddPatchRequestUriHandler>
                 b__0>d.MoveNext()
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Module.SendAsync(HttpRequestMessage
                 request, IEventListener callback, ISendAsync next)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalLi
                 stServicePrincipal_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener
                 eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalLi
                 stServicePrincipal_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener
                 eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.MSGraph.ServicePrincipalsServicePrincipalLi
                 stServicePrincipal(String consistencyLevel, String Search, String Filter, Nullable`1 Count, String[]
                 Orderby, String[] Select, String[] Expand, Func`3 onOk, Func`3 onDefault, IEventListener
                 eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.GetAzADServicePrincipal_List.Proces
                 sRecordAsync()
                    at Microsoft.Azure.PowerShell.Cmdlets.Resources.MSGraph.Cmdlets.GetAzADServicePrincipal_List.Proces
                 sRecordAsync()
Exception      : Azure.Identity.AuthenticationFailedException
InvocationInfo : {Get-AzADServicePrincipal_List}
Line           :     Az.MSGraph.internal\Get-AzADServicePrincipal @PSBoundParameters

Position       : At C:\Users\haagha\Documents\PowerShell\Modules\Az.Resources\6.0.1\MSGraph.Autorest\custom\Get-AzADSer
                 vicePrincipal.ps1:208 char:5
                 +     Az.MSGraph.internal\Get-AzADServicePrincipal @PSBoundParameters
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the
                 input parameter 'scope' is not valid. The scope MicrosoftGraphEndpointResourceId/.default
                 offline_access openid profile is not valid. The scope format is invalid. Scope must be in a valid URI
                 form <https://example/scope> or a valid Guid <guid/scope>.
                 Trace ID: ca51d844-9391-4971-8729-d61cdb1d8800
                 Correlation ID: e2a35a2e-a1a2-4b3e-bd55-f4dfc0c1e12f
                 Timestamp: 2023-06-26 21:04:03Z
StackTrace     :    at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response,
                 RequestContext requestContext)
                    at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response,
                 RequestContext requestContext)
                    at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod
                 method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders, Func`2
                 onBeforePostRequestData)
                    at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext
                 requestContext, Boolean addCommonHeaders, Func`2 onBeforePostRequestHandler)
                    at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String
                 tokenEndpoint, ILoggerAdapter logger)
                    at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String
                 tokenEndpoint, ILoggerAdapter logger)
                    at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2
                 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.Internal.SilentRequestHelper.RefreshAccessTokenAsync(MsalRefreshTokenC
                 acheItem msalRefreshTokenItem, RequestBase request, AuthenticationRequestParameters
                 authenticationRequestParameters, CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.TryGetTokenUsingFociAsync
                 (CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.RefreshRtOrFailAsync(Canc
                 ellationToken cancellationToken)
                    at
                 Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.ExecuteAsync(CancellationToken
                 cancellationToken)
                    at
                 Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.ExecuteAsync(CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken
                 cancellationToken)
                    at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(Acquire
                 TokenCommonParameters commonParameters, AcquireTokenSilentParameters silentParameters,
                 CancellationToken cancellationToken)
                    at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTok
                 enParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenSilentCoreAsync(String[] scopes, String claims,
                 IAccount account, String tenantId, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenSilentAsync(String[] scopes, String claims,
                 IAccount account, String tenantId, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext
                 requestContext, CancellationToken cancellationToken)
Exception      : Microsoft.Identity.Client.MsalServiceException
InvocationInfo : {Get-AzADServicePrincipal_List}
Line           :     Az.MSGraph.internal\Get-AzADServicePrincipal @PSBoundParameters

Position       : At C:\Users\haagha\Documents\PowerShell\Modules\Az.Resources\6.0.1\MSGraph.Autorest\custom\Get-AzADSer
                 vicePrincipal.ps1:208 char:5
                 +     Az.MSGraph.internal\Get-AzADServicePrincipal @PSBoundParameters
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by VeryEarly** [comment]
please check the environment you are running these cmdlets in:
```(Get-AzContext).Environment```
please configure below 2 parameters when you add environment.
[-MicrosoftGraphEndpointResourceId <String>]
[-MicrosoftGraphUrl <String>]
if it's non-public cloud.

**Comment by dolauli** [comment]
Seems the same issue as https://github.com/Azure/azure-powershell/issues/18142.
