### ISSUE TITLE
Connect-AzContainerRegistry error, "The given key not present in the dictionary."

### ISSUE THREAD

**Issue by jlperkins** [Azure/azure-powershell#22226]
### Description

Having trouble connecting to our container registry in Az.ContainerRegistry @ 3.0.4 (with Az @ 9.7.1). Also reproduces with Az @10.0.0 and Az.ContainerRegistry @ 4.0.0.

|
|          Connect-AzContainerRegistry -Name "$ContainerRegistryName"
|          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 | The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.

Seems extremely similar to #20742.

### Issue script & Debug output

```PowerShell
connect-AzContainerRegistry -Name $ACRName
DEBUG: 4:11:50 PM - ConnectAzureContainerRegistry begin processing with ParameterSet 'WithoutNameAndPasswordParameterSet'.
DEBUG: 4:11:50 PM - using account id 'myid@microsoft.com'...
DEBUG: 4:11:50 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 4:11:50 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Connect-AzContainerRegistry: The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.
DEBUG: 4:11:50 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 4:11:50 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.ContainerRegistry:3.0.4; CommandName: Connect-AzContainerRegistry; PSVersion: 7.3.4; IsSuccess: False; Duration: 00:00:00.0168254; Exception: The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.;
DEBUG: 4:11:50 PM - ConnectAzureContainerRegistry end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzC…
Script     2.2.2                 Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplication…
Script     3.0.4                 Az.ContainerRegistry                {Connect-AzContainerRegistry, Get-AzContainer…
Script     6.7.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpe…
```

### Error output

```PowerShell
Message        : The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.
StackTrace     :    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
                    at
                 Microsoft.Azure.Commands.ContainerRegistry.ContainerRegistryDataPlaneClient.SetEndPoint(String
                 RegistryName)
                    at Microsoft.Azure.Commands.ContainerRegistry.ConnectAzureContainerRegistry.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchrono
                 uslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJo
                 b[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJo
                 b[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Collections.Generic.KeyNotFoundException
InvocationInfo : {Connect-AzContainerRegistry}
Line           : connect-AzContainerRegistry -Name $ACRName
Position       : At line:1 char:1
                 + connect-AzContainerRegistry -Name $ACRName
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by isra-fel** [comment]
@Nickcandy please look into it in this sprint. Thanks.

**Comment by Nickcandy** [comment]
Hi @jlperkins , I really want to reproduce this error but I cannot. Here is my test:
![image](https://github.com/Azure/azure-powershell/assets/33285578/53d6a262-b9ce-4d7d-a07d-77f0b58eb535)
I think the issue is caused by the azure environment did not refresh. Could you update your module and re-import the account and ACR module and retry?
If still failed, please help us to run the cmdlet 
`$a = Get-AzEnvironment
$a[0].ExtendedProperties
`

**Comment by timpoppleton** [comment]
This one is happening for me also. I've performed a completely clean installation of the Az module which should ideally have brought everything through.

```
Connect-AzContainerRegistry -Name <name> -Debug
DEBUG: 12:59:00 - ConnectAzureContainerRegistry begin processing with ParameterSet 'WithoutNameAndPasswordParameterSet'.
DEBUG: 12:59:00 - using account id '<removed>'...
DEBUG: 12:59:00 - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: 12:59:00 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Connect-AzContainerRegistry: The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.
DEBUG: 12:59:00 - [ConfigManager] Got [False] from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
DEBUG: 12:59:00 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.ContainerRegistry:4.1.0; CommandName: Connect-AzContainerRegistry; PSVersion: 7.3.6; IsSuccess: False; Duration: 00:00:00.0317968; Exception: The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.;
DEBUG: 12:59:00 - ConnectAzureContainerRegistry end processing.
```

Can see that the Az.ContainerRegistry is at 4.1.0

```
Get-Module Az.ContainerRegistry -ListAvailable

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     4.1.0                 Az.ContainerRegistry                Core,Desk {Connect-AzContainerRegistry, Get-AzContainerRegistryRepository, Remove-AzContainerRegistryRepository, Update-AzContainerRegistr…
```

Running PowerShell 7.3.6

```
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by jlperkins** [comment]
I am also still seeing this issue at Az.ContainerRegistry @ 4.1.0. 

Running the command you suggested gave: 
`PS C:\Users\julesperkins> $a = Get-AzEnvironment $a[0].ExtendedProperties
InvalidOperation: Cannot index into a null array.`

The debug output: 
```
PS C:\Users\redacted> Connect-AzContainerRegistry -Name $ACRName
DEBUG: 12:56:44 PM - ConnectAzureContainerRegistry begin processing with ParameterSet 'WithoutNameAndPasswordParameterSet'.
DEBUG: 12:56:44 PM - using account id 'redacted@microsoft.com'...
DEBUG: 12:56:44 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:56:44 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Connect-AzContainerRegistry: The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.
DEBUG: 12:56:44 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:56:44 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.ContainerRegistry:4.1.0; CommandName: Connect-AzContainerRegistry; PSVersion: 7.3.6; IsSuccess: False; Duration: 00:00:00.0192233; Exception: The given key 'ContainerRegistryEndpointResourceId' was not present in the dictionary.;
DEBUG: 12:56:44 PM - ConnectAzureContainerRegistry end processing.
```

**Comment by Nickcandy** [comment]
@jlperkins @timpoppleton Hi all, sorry for the late response. We've found that this issue is because we added some configuration in the user's environments, but updating the version won't refresh it. Here is the solution:
1. `Clear-AzContext`
2.  `Connect-AzAccount`

This would refresh the local file for you.
