### ISSUE TITLE
New-AzVm when creating Trusted Launch VM

### ISSUE THREAD

**Issue by sirfamelin** [Azure/azure-powershell#22429]
### Description

When the following cmd is run, an exception is returned because the default image is not supported by Trusted Launch. The image needs to be the Gen2 equivalent of the default image, eg. Win2016DataCenterGenSecond

`$ New-AzVM -ResourceGroupName "sirlin1" -Name "pstvm" -SecurityType "TrustedLaunch"`

The next issue is that if the subscription does not have EncryptionAtHost enabled, the command also fails. The command I used does not pass in the EncryptionAtHost switch parameter. Trusted Launch does not have a dependency on EncryptionAtHost, so I would expect this request to succeed without enabling EncryptionAtHost.

### Issue script & Debug output

```PowerShell
PS C:\Users\sirlin.REDMOND> New-AzVM -ResourceGroupName "sirlin1" -Name "pstvm" -SecurityType "TrustedLaunch"                                                                                                                                   cmdlet New-AzVM at command pipeline position 1                                                                          Supply values for the following parameters:                                                                             Credential
WARNING: Upcoming breaking changes in the cmdlet 'New-AzVM' :
Consider using the image alias including the version of the distribution you want to use in the "-Image" parameter of
the "New-AzVM" cmdlet. On April 30, 2023, the image deployed using `UbuntuLTS` will reach its end of life. In October
2023, the aliases `UbuntuLTS`, `CentOS`, `Debian`, and `RHEL` will be removed.
- The change is expected to take effect from Az version : '11.0.0'
- The change is expected to take effect from version : '7.0.0'
Starting in November 2023 the "New-AzVM" cmdlet will deploy with the Trusted Launch configuration by default. To know
more about Trusted Launch, please visit https://docs.microsoft.com/en-us/azure/virtual-machines/trusted-launch
- The change is expected to take effect from Az version : '11.0.0'
- The change is expected to take effect from version : '7.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other
information on breaking changes in Azure PowerShell.
No Size value has been provided. The VM will be created with the default size Standard_D2s_v3.
New-AzVM : Use of TrustedLaunch setting is not supported for the provided image.
At line:1 char:1
+ New-AzVM -ResourceGroupName "sirlin1" -Name "pstvm" -SecurityType "Tr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzVM], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand
```

### Environment data

```PowerShell
PS C:\Users\sirlin.REDMOND> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.12.4     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     6.1.0      Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnatten...
```

### Error output

```PowerShell
PS C:\Users\sirlin.REDMOND> Resolve-AzError


   HistoryId: 1


RequestId      : 2ae0af29-fb7e-45a3-b186-cb98dcd76e02
Message        : Use of TrustedLaunch setting is not supported for the provided image.
ServerMessage  : BadRequest: Use of TrustedLaunch setting is not supported for the provided image.
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {PUT https://management.azure.com/subscriptions/130068aa-dcf8-46e8-a2cc-205ab4a32b30/resourceGroups/si
                 rlin1/providers/Microsoft.Compute/virtualMachines/pstvm?api-version=2022-11-01}
InvocationInfo : {New-AzVM}
Line           : New-AzVM -ResourceGroupName "sirlin1" -Name "pstvm" -SecurityType "TrustedLaunch"
Position       : At line:1 char:1
                 + New-AzVM -ResourceGroupName "sirlin1" -Name "pstvm" -SecurityType "Tr ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Common.Strategies.SyncTaskScheduler.Wait(Task task, Action
                 progressUpdate)
                    at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 1

Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
                 information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.RuntimeModule.GetTypes()
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Users\sirlin.REDMOND\Documents\WindowsPowerShell\Modules\Az.Compute\6.1.0\Az.Compute.psm1:39
                 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by Drewm3** [comment]
Travis, could you look into these two issues?

**Comment by kpatcrowe** [comment]
same issue 
![c1](https://github.com/Azure/azure-powershell/assets/144170873/9d031a7b-3e11-4da5-917f-cf63b584f008)

**Comment by TravisCragg-MSFT** [comment]
@sirfamelin Can you confirm if this is still happening with a supported image version?

**Comment by kpatcrowe** [comment]
No longer happening...issue is now resolved
