### ISSUE TITLE
Get-AzNetworkWatcherTopology (Az.Network) | unexpected error message in context of Suspended subscription

### ISSUE THREAD

**Issue by SjoerdV** [Azure/azure-powershell#22592]
### Description

when running `Get-AzNetworkWatcherTopology` within the context of a **Suspended** subscription an illogical error message is presented

`Operation returned an invalid status code 'Conflict' StatusCode: 409 ReasonPhrase: Conflict ErrorCode: SubscriptionSuspended
     | ErrorMessage: Subscription xxxxxxxx-cace-xxxx-acea-xxxxxxxxxxxx is in 'Suspended' state. Only GET and DELETE operations on resources
     | are permitted.`

since the cmdlet is obviously a GET operation, why is this not permitted?

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.5                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.1.1                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplication…
Script     6.9.1                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment,…
Script     1.2.1                 AzViz                               Export-AzViz
```

### Error output

```PowerShell
RequestId      : 
Message        : Operation returned an invalid status code 'Conflict'
                 StatusCode: 409
                 ReasonPhrase: Conflict
                 ErrorCode: SubscriptionSuspended
                 ErrorMessage: Subscription xxxxxxxx-cace-xxxx-acea-xxxxxxxxxxxx is in 'Suspended' state. Only GET and DELETE operations 
                 on resources are permitted.
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Get-AzNetworkWatcherTopology}
Line           :                 $Topology = Get-AzNetworkWatcherTopology -NetworkWatcher $networkWatcher -TargetResourceGroupName 
                 $ResourceGroup -Verbose:$false 
                 
Position       : At /home/user/.local/share/powershell/Modules/AzViz/1.2.1/src/private/ConvertFrom-Network.ps1:67 char:29
                 + … $Topology = Get-AzNetworkWatcherTopology -NetworkWatcher $networkWatc …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 
                 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by kumaam** [comment]
Get-AzNetworkWatcherTopology is a POST operation. I see the confusion as the name of the cmdlet suggests it's a GET operation. 

We'll update our public documentation with these details. Since this cmdlet is a POST-operation, this would not work with suspended subscriptions as only GET and DELETE operations are permitted on suspended subscription.
