### ISSUE TITLE
Unable to use Get-AzCdnCustomDomain 

### ISSUE THREAD

**Issue by tomaustin700** [Azure/azure-powershell#22682]
### Description

Hi,
I am attempting to use `Get-AzCdnCustomDomain ` however when running it constantly throws the following error
```
| Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource
     | '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/endpoints/redacted' could not  
     | be found.

```
The parameters I am setting on the command are correct. When viewing the Id of the endpoint I am providing I can see it listed as:
```
"/subscriptions/redacted/resourcegroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdendpoints/redacted"

```

See the difference of `endpoints` and `afdendpoints``.

### Issue script & Debug output

```PowerShell
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.11.2; CommandName: Set-AzContext; PSVersion: 7.3.6; IsSuccess: True; Duration: 00:00:00.8372678
DEBUG: 09:40:57 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 09:40:57 - SetAzureRMContextCommand end processing.
DEBUG: 09:40:57 - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdEndpoints?api-version=2023-05-01
DEBUG: RequestCreated: /subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdEndpoints?api-version=2023-05-01
DEBUG: HeaderParametersAdded: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdEndpoints?api-version=2023-05-01

Headers:
x-ms-unique-id                : 33,34
x-ms-client-request-id        : 74fc5af4-0cf1-4de5-91d9-1b5c112f41cb
CommandName                   : Get-AzFrontDoorCdnEndpoint
FullCommandName               : Get-AzFrontDoorCdnEndpoint_List
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v10.1.0,PSVersion/v7.3.6,Az.Cdn/3.1.0

Body:



DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 272545db-0e1a-4682-95ee-3a4067ca9445
x-ms-client-request-id        : 74fc5af4-0cf1-4de5-91d9-1b5c112f41cb
Server                        : Kestrel
x-ms-ratelimit-remaining-subscription-resource-requests: 499
x-ms-correlation-request-id   : aa9e40f1-7be1-4d1e-a95e-7df197df8a84
x-ms-routing-request-id       : UKSOUTH:20230829T084058Z:aa9e40f1-7be1-4d1e-a95e-7df197df8a84
X-Content-Type-Options        : nosniff
Date                          : Tue, 29 Aug 2023 08:40:57 GMT

Body:
{
  "value": [
    {
      "id": "/subscriptions/redacted/resourcegroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdendpoints/redacted",   
      "type": "Microsoft.Cdn/profiles/afdendpoints",
      "name": "redacted",
      "location": "Global",
      "tags": {},
      "properties": {
        "hostName": "redacted.z01.azurefd.net",
        "autoGeneratedDomainNameLabelScope": null,
        "enabledState": "Enabled",
        "provisioningState": "Succeeded",
        "deploymentStatus": "NotStarted"
      }
    },
    {
      "id": "/subscriptions/redacted/resourcegroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdendpoints/redacted",
      "type": "Microsoft.Cdn/profiles/afdendpoints",
      "name": "redacted",
      "location": "Global",
      "tags": {},
      "properties": {
        "hostName": "redacted-cjf3hjedekbnb9dc.z01.azurefd.net",
        "autoGeneratedDomainNameLabelScope": null,
        "enabledState": "Enabled",
        "provisioningState": "Succeeded",
        "deploymentStatus": "NotStarted"
      }
    },
    {
      "id": "/subscriptions/redacted/resourcegroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdendpoints/redacted",     
      "type": "Microsoft.Cdn/profiles/afdendpoints",
      "name": "redacted",
      "location": "Global",
      "tags": {},
      "properties": {
        "hostName": "redacted-c6g3e4heg2fcagce.z01.azurefd.net",
        "autoGeneratedDomainNameLabelScope": null,
        "enabledState": "Enabled",
        "provisioningState": "Succeeded",
        "deploymentStatus": "NotStarted"
      }
    },
    {
      "id": "/subscriptionsredacted/resourcegroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdendpoints/Imperial",      
      "type": "Microsoft.Cdn/profiles/afdendpoints",
      "name": "redacted",
      "location": "Global",
      "tags": {},
      "properties": {
        "hostName": "redacted-ctdmagamfuaqf9h0.z01.azurefd.net",
        "autoGeneratedDomainNameLabelScope": null,
        "enabledState": "Enabled",
        "provisioningState": "Succeeded",
        "deploymentStatus": "NotStarted"
      }
    },
    {
      "id": "/subscriptions/redacted/resourcegroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/afdendpoints/redacted",
      "type": "Microsoft.Cdn/profiles/afdendpoints",
      "name": "redacted",
      "location": "Global",
      "tags": {},
      "properties": {
        "hostName": "redacted-dddqcef9h7bvcnfu.z01.azurefd.net",
        "autoGeneratedDomainNameLabelScope": null,
        "enabledState": "Enabled",
        "provisioningState": "Succeeded",
        "deploymentStatus": "NotStarted"
      }
    }
  ]
}


DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
DEBUG: Finally: 
DEBUG: CmdletAfterAPICall: 
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: AzureQoSEvent:  Module: Az.Cdn:3.1.0; CommandName: Get-AzFrontDoorCdnEndpoint; PSVersion: 7.3.6; IsSuccess: True; Duration: 00:00:00.3969493
DEBUG: 09:40:58 - GetAzureRMContextCommand end processing.
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: /subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/endpoints/redacted/customDomains?api-version=2023-05-01
DEBUG: RequestCreated: /subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/endpoints/redacted/customDomains?api-version=2023-05-01
DEBUG: HeaderParametersAdded: 
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/endpoints/redacted/customDomains?api-version=2023-05-01

Headers:
x-ms-unique-id                : 35,36
x-ms-client-request-id        : 8c485f56-5a20-4c10-a9d3-f39f6e7935d4
CommandName                   : Get-AzCdnCustomDomain
FullCommandName               : Get-AzCdnCustomDomain_List1
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v10.1.0,PSVersion/v7.3.6,Az.Cdn/3.1.0

Body:



DEBUG: BeforeCall: 
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : f3ff5313-f3f3-4089-98f4-c408dfb00fee
x-ms-correlation-request-id   : f3ff5313-f3f3-4089-98f4-c408dfb00fee
x-ms-routing-request-id       : UKSOUTH:20230829T084058Z:f3ff5313-f3f3-4089-98f4-c408dfb00fee
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 29 Aug 2023 08:40:57 GMT

Body:
{
  "error": {
    "code": "ParentResourceNotFound",
    "message": "Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/SHFrontDoor' could not be found."
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
Get-AzCdnCustomDomain_List1: C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8:5
Line |
   8 |      Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontD …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource
     | '/subscriptions/9a9a8155-42fa-40b6-8454-945ad23e3d64/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/SHFrontDoor' could not  
     | be found.
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSResourceNotFoundCloudException: InternalException' from response
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: AzureQoSEvent:  Module: Az.Cdn:3.1.0; CommandName: Get-AzCdnCustomDomain; PSVersion: 7.3.6; IsSuccess: False; Duration: 00:00:00.6956089; Exception: InternalException;

Here is my script
$RG = "FrontDoor"


$endPoints = Get-AzFrontDoorCdnEndpoint -ResourceGroupName $RG -ProfileName "redacted" | Where-Object { $_.Name -eq "redacted" }
foreach ($endpoint in $endPoints) {
    Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "redacted" -EndpointName  $endpoint.Name


}
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.11.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     3.1.0                 Az.Cdn                              {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointContent, Disable-AzCdnCustomDomain…
```

### Error output

```PowerShell
HistoryId: 14

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource       
                 '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/redacted/endpoints/redacted'  
                 could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           :     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName  $endpoint.Name

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8 char:5
                 +     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontD …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 14


   HistoryId: 10

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource       
                 '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/redacted'  
                 could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           :     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName  $endpoint.Name

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8 char:5
                 +     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontD …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 10


   HistoryId: 9

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource       
                 '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/redacted'  
                 could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           :     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName  $endpoint.Name

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8 char:5
                 +     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontD …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9


   HistoryId: 7

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource       
                 '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/redacted'  
                 could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           :     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName  $endpoint.Name

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8 char:5
                 +     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontD …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7


   HistoryId: 6

Message        : A positional parameter cannot be found that accepts argument 'SHFrontDoor'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException originalBindingException)  
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements,      
                 CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzCdnCustomDomain}
Line           :     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor"  $endpoint.Name

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8 char:5
                 +     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontD …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6


   HistoryId: 5

Message        : Cannot process command because of one or more missing mandatory parameters: EndpointName.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Get-AzCdnCustomDomain}
Line           :     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor"

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8 char:5
                 +     Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontD …
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5


   HistoryId: 4

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource       
                 '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/SHFrontDoor'  
                 could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           :         Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName $endpoint.Name

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:8 char:9
                 +         Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "Fr …
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4


   HistoryId: 3

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource       
                 '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/redacted'  
                 could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           : Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName "SHFrontDoor"

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:5 char:1
                 + Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3


   HistoryId: 2

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource '/sub 
                 scriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/redacted.z01.az 
                 urefd.net' could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           : Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName "SHFrontDoor.z01.azurefd.net"

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:5 char:1
                 + Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2


   HistoryId: 1

Message        : [ParentResourceNotFound] : Failed to perform 'read' on resource(s) of type 'profiles/endpoints/customdomains', because the parent resource       
                 '/subscriptions/redacted/resourceGroups/FrontDoor/providers/Microsoft.Cdn/profiles/FrontDoor/endpoints/redacted'  
                 could not be found.
StackTrace     : 
Exception      : System.Exception
InvocationInfo : {Get-AzCdnCustomDomain_List1}
Line           : Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" -EndpointName "SHFrontDoor"

Position       : At C:\Users\TomA\source\repos\Scripts\Front Door\ListFrontDoorCustomDomains.ps1:5 char:1
                 + Get-AzCdnCustomDomain -ResourceGroupName $RG -ProfileName "FrontDoor" …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1



DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.11.2; CommandName: Resolve-AzError; PSVersion: 7.3.6; IsSuccess: True; Duration: 00:00:00.1115760
DEBUG: 09:46:48 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 09:46:48 - ResolveError end processing.
```

**Comment by tomaustin700** [comment]
Ignore this, should have been using `Get-AzFrontDoorCdnCustomDomain`
