### ISSUE TITLE
Get-AzMetric failing for Bastion Host with TimeGrain specified

### ISSUE THREAD

**Issue by thgossler** [Azure/azure-powershell#22750]
### Description

I'm querying metrics for many types of resources in the same way. Only for Bastion hosts this approach is failing.

When I use the TimeGrain argument with any value the call if failing. When I remove the TimeGrain argument from the call then it is succeeding. See also the screenshot below.

<img width="1582" alt="2023-09-07 11_49_34" src="https://github.com/Azure/azure-powershell/assets/57985062/c65c34f3-b9af-492b-9e63-4bdd48d2e152">

### Issue script & Debug output

```PowerShell
$resourceId = "/subscriptions/.../resourceGroups/.../providers/Microsoft.Network/bastionHosts/..."
Get-AzMetric -ResourceId $resourceId -MetricName 'sessions' -AggregationType Total -StartTime (Get-Date -AsUTC).AddDays(-35) -EndTime (Get-Date -AsUTC) -TimeGrain ([timespan]::FromHours(12).ToString())
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.0                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     3.5.0                 Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchComputeNodeScheduling, Disable-AzBatchJob, Disable-AzBatchJobSchedule…}
Script     2.0.0                 Az.DataProtection                   {Backup-AzDataProtectionBackupInstanceAdhoc, Edit-AzDataProtectionPolicyRetentionRuleClientObject, Edit-AzDataProtectionPolicyTagClientObject, Edit-AzDataProtectionPolicyTriggerClientObject…}  
Script     4.6.0                 Az.Monitor                          {Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAlertRuleV2, Add-AzWebtestAlertRule…}
Script     0.13.0                Az.ResourceGraph                    {Search-AzGraph, Get-AzResourceGraphQuery, New-AzResourceGraphQuery, Remove-AzResourceGraphQuery…}
Script     6.10.0                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     3.0.0                 Az.ServiceBus                       {New-AzServiceBusAuthorizationRuleSASToken, Test-AzServiceBusNameAvailability, Approve-AzServiceBusPrivateEndpointConnection, Complete-AzServiceBusMigration…}
```

### Error output

```PowerShell
Get-AzMetric: Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.MetricsOperations.ListWithHttpMessagesAsync(String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.ListAsync(IMetricsOperations operations, String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null
```

**Comment by isra-fel** [comment]
Thanks for reporting. @nori could you look into it?

**Comment by NoriZC** [comment]
Hi @thgossler, current info provided is not enough for me to reproduce the exact issue. Could you please using `-debug` after the command throwing error and share the debug log? Thanks.

**Comment by thgossler** [comment]
Here the output of such a failing Get-AzMetric command execution with -Debug flag enabled:

```
Get-AzMetric -ResourceId $ResourceId -MetricName $MetricN …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException:
     | Operation returned an invalid status code 'BadRequest'    at
     | Microsoft.Azure.Management.Monitor.MetricsOperations.ListWithHttpMessagesAsync(String resourceUri, ODataQuery`1 odataQuery, 
     | String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1    
     | resultType, String metricnamespace, Dictionary`2 customHeaders, CancellationToken cancellationToken)    at
     | Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.ListAsync(IMetricsOperations operations, String resourceUri, 
     | ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top,      
     | String orderby, Nullable`1 resultType, String metricnamespace, CancellationToken cancellationToken)    at
     | Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.List(IMetricsOperations operations, String resourceUri,      
     | ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top,      
     | String orderby, Nullable`1 resultType, String metricnamespace)    at
     | Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()    at
     | Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null      
DEBUG: 14:28:51 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 14:28:51 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 14:28:51 - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: AzureQoSEvent:  Module: Az.Monitor:4.6.0; CommandName: Get-AzMetric; PSVersion: 7.3.6; IsSuccess: False; Duration: 00:00:44.5731111; Exception: Exception type: ErrorResponseException, Message: Microsoft.Azure.Management.Monitor.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Monitor.MetricsOperations.ListWithHttpMessagesAsync(String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.ListAsync(IMetricsOperations operations, String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Monitor.MetricsOperationsExtensions.List(IMetricsOperations operations, String resourceUri, ODataQuery`1 odataQuery, String timespan, Nullable`1 interval, String metricnames, String aggregation, Nullable`1 top, String orderby, Nullable`1 resultType, String metricnamespace)
   at Microsoft.Azure.Commands.Insights.Metrics.GetAzureRmMetricCommand.ProcessRecordInternal()
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet(), Code: Null, Status code:Null, Reason phrase: Null;      
DEBUG: 14:28:51 - GetAzureRmMetricCommand end processing.
```

**Comment by NoriZC** [comment]
Hi @thgossler Could you try setting `-TimeGrain` as `00:05:00`?

**Comment by thgossler** [comment]
With `-TimeGrain` as `00:05:00` it seams to be working fine. Would expect it to work especially with the following values as well also for Bastian hosts: e.g. `01:00:00`, `12:00:00`, `1.00:00:00`

**Comment by NoriZC** [comment]
Hi @thgossler, when I reproducing the error, the error message is as below: 

Body:
{
  "code": "BadRequest",
  "message": "Commonly allowed time grains: 00:05:00,00:15:00 between metrics: sessions, can not support requested time grain: 12:00:00 please adjust your interval parameter to use one of the common grains, TraceId: {xxxxxxx-53d2-4969-9b63-393195c5e256}"
}

Seems what you are expecting is actually not supported, we will need to involve Monitor team to follow up.

**Comment by thgossler** [comment]
Interestingly, for "all" other resource types a time grain of 24 hours (1.00:00:00) seems to work fine. At least my script runs with that config for a long time and without issues. Just now that Bastian hosts came across it was starting to fail.

**Comment by thgossler** [comment]
Why would you need more information? I'm suggesting to align the supported time intervals across all Azure PowerShell cmdlets. If Microsoft doesn't want this that please state it clearly. From a user perspective this makes a lot of sense.

**Comment by NoriZC** [comment]
> Why would you need more information? I'm suggesting to align the supported time intervals across all Azure PowerShell cmdlets. If Microsoft doesn't want this that please state it clearly. From a user perspective this makes a lot of sense.

Hi @thgossler Could you elaborate more about "align the supported time intervals across all Azure PowerShell cmdlets"? Which cmdlets are you talking about? 

For the `Get-AzMetric` command, the difference among different resources are listed [here](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/metrics-index). Especially for Network/bastionHosts: [link](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/microsoft-network-bastionhosts-metrics). 

@ToddKingMSFT Could you please help explain since when the Time Grains started to vary amoung different resources, and why it did so?

BTW to avoid further user confusion, we will plan to add [this link](https://learn.microsoft.com/en-us/azure/azure-monitor/reference/supported-metrics/metrics-index) to the `-TimeGrain` parameter description. Thanks for report.
