### ISSUE TITLE
The 'Get-azVM' command was found in the module 'Az.Compute', but the module could not be loaded..

### ISSUE THREAD

**Issue by manojgupta702** [Azure/azure-powershell#22767]
### Description

While using Az modules in powershell script which is getting executed from powershell core but getting error while executing the script from application. Tried running 'Import-Module Az.Compute' manually and is running successfully. 

Line |
  26 |  $vm = Get-AzVM -Name $vmName -ResourceGroupName $resourceGroup
     |        ~~~~~~~~
     | The 'Get-AzVM' command was found in the module 'Az.Compute', but the module could not be loaded. For more
     | information, run 'Import-Module Az.Compute'.

### Issue script & Debug output

```PowerShell
$vm = Get-AzVM -Name $vmName -ResourceGroupName $resourceGroup
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.17763.4720
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.4720
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.13.0     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     6.3.0      Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnatten...
```

### Error output

```PowerShell
PS C:\Windows\system32> Resolve-AzError


   HistoryId: 3


Message        : The term 'psversiontable' is not recognized as the name of a cmdlet, function, script file, or
                 operable program. Check the spelling of the name, or if a path was included, verify that the path is
                 correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName,
                 CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName,
                 CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe,
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[]
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : psversiontable
Position       : At line:1 char:1
                 + psversiontable
                 + ~~~~~~~~~~~~~~
HistoryId      : 3



   HistoryId: 2


Message        : Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more
                 information.
StackTrace     :    at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
                    at System.Reflection.Assembly.GetTypes()
                    at Microsoft.PowerShell.Commands.AddTypeCommand.LoadAssemblyFromPathOrName(List`1 generatedTypes)
                    at Microsoft.PowerShell.Commands.AddTypeCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Reflection.ReflectionTypeLoadException
InvocationInfo : {Add-Type}
Line           :                     Add-Type -Path $_.FullName -ErrorAction Ignore | Out-Null

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.Compute\6.3.0\Az.Compute.psm1:39 char:21
                 + ...                Add-Type -Path $_.FullName -ErrorAction Ignore | Out-N ...
                 +                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by isra-fel** [comment]
Thanks for reporting. Please help clarify some questions
1. Is this issue happen in PowerShell 5 (aka windows powershell) or PowerShell 7 (aka powershell core)?
2. By "Tried running 'Import-Module Az.Compute' manually and is running successfully." do you mean your script ran successfully or just the "Import-Module" was successful?
3. Please run `Import-Module Az.Compute` in a new PS session and share the results.
4. Please check that you only installed one version of Azure PowerShell by `Get-Module Az* -ListAvailable`.
