### ISSUE TITLE
Get-AzRoleAssignment is failing for the newly released Az.Resources Module

### ISSUE THREAD

**Issue by IndraneelPal** [Azure/azure-powershell#22863]
### Description

For the newly released Az.Accounts module 2.13.1 and Az.Resources module 6.11.0 we are seeing the failure for Get-AzRoleAssignment 

It is failing with the error: No subscription was found in the default profile and no scope was specified

![MicrosoftTeams-image (9)](https://github.com/Azure/azure-powershell/assets/105407886/f80954e7-1be1-4650-bb73-3dc708be12c6)

### Issue script & Debug output

```PowerShell
PS C:\Users\Administrator> Get-AzRoleAssignment
DEBUG: Got version 0 of Az
DEBUG: Got version 0 of Az.Accounts
DEBUG: 5:01:40 PM - GetAzureRoleAssignmentCommand begin processing with ParameterSet 'EmptyParameterSet'.
DEBUG: 5:01:40 PM - using account id 'aszregistration@microsoft.com'...
DEBUG: 5:01:40 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: 5:01:40 PM - [ConfigManager] Got nothing from [DisableErrorRecordsPersistence], Module = [], Cmdlet = [].
Returning default value [False].
DEBUG: 5:01:40 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning
default value [True].
Get-AzRoleAssignment : No subscription was found in the default profile and no scope was specified. Either specify a
scope or use a tenant with a subscription to run the command.
At line:1 char:1
+ Get-AzRoleAssignment
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzRoleAssignment], Exception
    + FullyQualifiedErrorId : Error,Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand
```

### Environment data

```PowerShell
PS C:\Users\Administrator> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.1366
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1366
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\Users\Administrator> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.13.1     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     6.11.0     Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...
```

### Error output

```PowerShell
DEBUG: 5:05:57 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 5:05:57 PM - using account id 'aszregistration@microsoft.com'...
DEBUG: 5:05:57 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].


   HistoryId: 19


Message        : No subscription was found in the default profile and no scope was specified. Either specify a scope
                 or use a tenant with a subscription to run the command.
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : System.Exception
InvocationInfo : {Get-AzRoleAssignment}
Line           : Get-AzRoleAssignment
Position       : At line:1 char:1
                 + Get-AzRoleAssignment
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 19



   HistoryId: 18


Message        : The term 'Get-AzRoleAssignments' is not recognized as the name of a cmdlet, function, script file, or
                 operable program. Check the spelling of the name, or if a path was included, verify that the path is
                 correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName,
                 CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName,
                 CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe,
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[]
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Get-AzRoleAssignments
Position       : At line:1 char:1
                 + Get-AzRoleAssignments
                 + ~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 18



   HistoryId: 17


Message        : No subscription was found in the default profile and no scope was specified. Either specify a scope
                 or use a tenant with a subscription to run the command.
StackTrace     :    at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
Exception      : System.Exception
InvocationInfo : {Get-AzRoleAssignment}
Line           : Get-AzRoleAssignment
Position       : At line:1 char:1
                 + Get-AzRoleAssignment
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 17
```

**Comment by TorstenH82** [comment]
Just let me confirm this issue:


```
[...]
VERBOSE: Loading module from path '/root/.local/share/powershell/Modules/Az.Accounts/2.13.1/Az.Accounts.psd1
VERBOSE: Loading module from path '/root/.local/share/powershell/Modules/Az.Resources/6.11.0/Az.Resources.psd1'.
[...]
Line |
 610 |  …  $existingAssignments = Get-AzRoleAssignment -ObjectId $groupOriginId
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No subscription was found in the default profile and no scope was
     | specified. Either specify a scope or use a tenant with a subscription to
     | run the command.
##[error]PowerShell exited with code '1'.
##[error]PowerShell wrote one or more lines to the standard error stream.
##[error]Get-AzRoleAssignment: /azp/_work/1/s/000_AAD_Users_Groups/EntitlementMgmt/script/createCatalog.ps1:610
```

**Comment by isra-fel** [comment]
Update: we have just [released the hotfix](https://github.com/Azure/azure-powershell/releases/tag/v10.4.1-September2023) for this issue. If you are encountering this, please make sure to update to the latest version of Azure PowerShell 10.4.1 (or Az.Resources module to 6.11.1 if it is installed individually).
