### ISSUE TITLE
Command New-AzSnapshotUpdateConfig does not support parameter -DiskAccessId

### ISSUE THREAD

**Issue by AragornSun** [Azure/azure-powershell#22886]
### Description

The command **New-AzSnapshotUpdateConfig** creates a configurable snapshot update object, which is then used in the command **Update-AzSnapshot** to update the configurations of existing snapshots accordingly. The command **New-AzSnapshotUpdateConfig** supports the parameter **-NetworkAccessPolicy** with 3 possible values, including **AllowPrivate**, which requires another mandatory parameter **-DiskAccessId** to specify the Disk Access resource ID from the same Resource Group of the target snapshot. However, from the [command reference page](https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azsnapshotupdateconfig?view=azps-10.4.1), the command **New-AzSnapshotUpdateConfig** does not support the parameter **-DiskAccessId**. 
 
The similar command **New-AzDiskUpdateConfig**, which is basically for the same configuration update for managed disks, does support the parameter **-NetworkAccessPolicy** and **-DiskAccessId**. Please see the [command reference page](https://learn.microsoft.com/en-us/powershell/module/az.compute/new-azdiskupdateconfig?view=azps-10.4.1) FYI. The command has been tested successfully.

### Issue script & Debug output

```PowerShell
Connect-AzAccount -SubscriptionId "mySubId"
$ResourceGroupName = "myRgName"
$diskAccessID = (Get-AzDiskAccess -ResourceGroupName $ResourceGroupName).Id
$snapshotUpdateConfig = New-AzSnapshotUpdateConfig -NetworkAccessPolicy AllowPrivate -DiskAccessId $diskAccessID -PublicNetworkAccess Disabled
 
New-AzSnapshotUpdateConfig: A parameter cannot be found that matches parameter name 'DiskAccessId'.
```

### Environment data

```PowerShell
$PSVersionTable
 
Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Get-Module Az*
 
ModuleType Version    PreRelease Name
---------- -------    ---------- ----
Script     2.13.1                Az.Accounts                         
Script     6.3.0                 Az.Compute
```

### Error output

```PowerShell
Resolve-AzError
 
Message        : A parameter cannot be found that matches parameter name 'DiskAccessId'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException
                 originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][]
                 pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzSnapshotUpdateConfig}
Line           : $snapshotUpdateConfig = New-AzSnapshotUpdateConfig -NetworkAccessPolicy AllowPrivate -DiskAccessId $diskAccessID
                 -PublicNetworkAccess Disabled
Position       : At line:1 char:86
                 + … tUpdateConfig -NetworkAccessPolicy AllowPrivate -DiskAccessId $diskAc …
                 +                                                   ~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by nikhilpatel909** [comment]
@ramankumarlive could you please review the issue?

**Comment by AdamZLi** [comment]
Thanks for the feedback, we have added this request to PowerShell backlog, will reply in the thread once change is confirmed.
