### ISSUE TITLE
"Object reference"exception when `Set-AzVMOperatingSystem` is called on the result of `New-AzVMConfig`

### ISSUE THREAD

**Issue by rabiaabrar** [Azure/azure-powershell#22956]
### Description

When I call `Set-AzVMOperatingSystem` on the result of `New-AzVMConfig`, I get the exception "Object reference not set to an instance of an object."

Powershell 7 version 7.3.8
Az version 10.4.1

### Issue script & Debug output

```PowerShell
PS C:\Users\rabia> $debugPreference='Continue'
PS C:\Users\rabia> $VirtualMachine = New-AzVMConfig -VMName Srv-Work -VMSize "Standard_DS2"
DEBUG: Initializing ConditionalAssemblyContext. PSEdition is [Core]. PSVersion is [7.3.8].
DEBUG: Initializing ConditionalAssemblyProvider. AssemblyRootPath is [C:\Users\rabia\OneDrive\Documents\PowerShell\Modules\Az.Accounts\2.13.1\StartupScripts\..\lib].
DEBUG: Registering Az shared AssemblyLoadContext.
DEBUG: AssemblyLoadContext registered.
DEBUG: Registering module AssemblyLoadContext for path: 'C:\Users\rabia\OneDrive\Documents\PowerShell\Modules\Az.Compute\6.3.0\PostImportScripts\..\ModuleAlcAssemblies'.
DEBUG: AssemblyLoadContext registered.
DEBUG: Got version 0 of Az
DEBUG: Got version 0 of Az.Accounts
DEBUG: 3:47:50 PM - NewAzureVMConfigCommand begin processing with ParameterSet 'DefaultParameterSet'.
DEBUG: 3:47:50 PM - using account id 'rabia.abrar@gmail.com'...
DEBUG: 3:47:50 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:47:50 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:47:50 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: AzureQoSEvent:  Module: Az.Compute:6.3.0; CommandName: New-AzVMConfig; PSVersion: 7.3.8; IsSuccess: True; Duration: 00:00:00.1512828
DEBUG: 3:47:50 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:47:50 PM - NewAzureVMConfigCommand end processing.
PS C:\Users\rabia> $VirtualMachine = Set-AzVMOperatingSystem -VM $VirtualMachine -Windows -ComputerName Srv-Work -ProvisionVMAgent -EnableAutoUpdate -Debug
DEBUG: 3:47:54 PM - SetAzureVMOperatingSystemCommand begin processing with ParameterSet 'Windows'.
DEBUG: 3:47:54 PM - using account id 'rabia.abrar@gmail.com'...
DEBUG: 3:47:54 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:47:54 PM - [ConfigManager] Got nothing from [DisableErrorRecordsPersistence], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 3:47:54 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Set-AzVMOperatingSystem: Object reference not set to an instance of an object.
DEBUG: 3:47:55 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:47:55 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:47:55 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: AzureQoSEvent:  Module: Az.Compute:6.3.0; CommandName: Set-AzVMOperatingSystem; PSVersion: 7.3.8; IsSuccess: False; Duration: 00:00:00.1892248; Exception: Object reference not set to an instance of an object.;
DEBUG: 3:47:55 PM - SetAzureVMOperatingSystemCommand end processing.
```

### Environment data

```PowerShell
PS C:\Users\rabia> $psversionTable

Name                           Value
----                           -----
PSVersion                      7.3.8
PSEdition                      Core
GitCommitId                    7.3.8
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Users\rabia> get-module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.3.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
```

### Error output

```PowerShell
PS C:\Users\rabia> resolve-AzError
DEBUG: 3:48:49 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 3:48:49 PM - using account id 'rabia.abrar@gmail.com'...
DEBUG: 3:48:49 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 3

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Compute.SetAzureVMOperatingSystemCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Set-AzVMOperatingSystem}
Line           : $VirtualMachine = Set-AzVMOperatingSystem -VM $VirtualMachine -Windows -ComputerName Srv-Work -ProvisionVMAgent -EnableAutoUpdate -Debug
Position       : At line:1 char:19
                 + … alMachine = Set-AzVMOperatingSystem -VM $VirtualMachine -Windows -Com …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3



DEBUG: 3:48:49 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:48:49 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.13.1; CommandName: Resolve-AzError; PSVersion: 7.3.8; IsSuccess: True; Duration: 00:00:00.0424994
DEBUG: 3:48:49 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:48:49 PM - ResolveError end processing.
```

**Comment by Tircffffexsw** [comment]
Que hay q aser

**Comment by magno101** [comment]
Also seeing the same with a -Linux VM on PowerShell 5

`
PS> Get-InstalledModule

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.4.8.1              PackageManagement                   PSGallery            PackageManagement (a.k.a. OneGet) is a new way to discover and install software packages from around the web....
2.2.5                PowerShellGet                       PSGallery            PowerShell module with commands for discovering, installing, updating and publishing the PowerShell artifacts like Modules, DSC Resources, Role Capabiliti...
10.4.1               Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with PowerShell and Windows PowerShell....
...
6.3.0                Az.Compute                          PSGallery            Microsoft Azure PowerShell - Compute service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Manages virtual machines, host...
...

PS> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      22621  2428

PS> $vmConfig = New-AzVMConfig -VMName "VMName" -VMSize "Standard_DS2"
PS> $vmConfig = Set-AzVMOperatingSystem -VM $vmConfig -Linux -ComputerName "ComputerName"
Set-AzVMOperatingSystem : Object reference not set to an instance of an object.
At line:1 char:13
+ $vmConfig = Set-AzVMOperatingSystem -VM $vmConfig -Linux -ComputerNam ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzVMOperatingSystem], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMOperatingSystemCommand
`

**Comment by magno101** [comment]
I started installing previous versions of the Az.Compute module and found that version "6.0.0" prompts you via a pop-up credential window to create a PSCredential object which it then passes via the -Credential parameter. The resulting command is successful and produces a valid VM Object. 

It appears that the documentation may need some updating as the -Credential parameter looks to be required (if that was the intent). I ran the following:

```
PS D:\Users\marcu> $vmConfig = New-AzVMConfig -VMName "VMName" -VMSize "Standard_DS2"
PS D:\Users\marcu> $vmConfig = Set-AzVMOperatingSystem -VM $vmConfig -Linux -ComputerName "ComputerName" -Credential (Get-Credential)
```

With success.

**Comment by rabiaabrar** [comment]
Nice work @magno101, this unblocked me for now. It makes sense.

In addition to the documentation for `-Credential` needing updating, the code itself needs to be tweaked to either throw an appropriate error or let the user enter credentials at runtime.

**Comment by Drewm3** [comment]
@TravisCragg-MSFT, could you look into this with the Az.compute PS team? This looks to be something specific to the powershell client as compared to any problem with the Azure serverside.

**Comment by TheKevinWang** [comment]
So how can I create a linux VM without password, only key authentication? pretty easy to do in gui.

**Comment by Sandido** [comment]
I have resolved this bug and the fix will ship in the next PS release, releasing to customers on 9/3. There may still be an error when attempting to create the VM if a Credential is not provided at some point.
