### ISSUE TITLE
Install fails and recommends --scope CurrentUser although already specified

### ISSUE THREAD

**Issue by Hefaistos68** [Azure/azure-powershell#23030]
### Description

First run this command as normal user, fails and recommends specifying "--scope CurrentUser" which clearly is passed at the command line.
![image](https://github.com/Azure/azure-powershell/assets/8855055/8814faab-615b-4be4-88f6-97680131a2a1)

Then started a command promt with run as admin, and still get the same error (note: domain users are NOT members of BUILTIN\Administrators, instead we get BUILTIN\Network Configuration Operators).

Finally running it with MakeMeAdmin tool to get membership of Administrators group + run-as-admin:
![image](https://github.com/Azure/azure-powershell/assets/8855055/56253a39-4633-4eeb-9e71-e4bd329a3ce1)

### Issue script & Debug output

```PowerShell
no script run
```

### Environment data

```PowerShell
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
none at all
```

### Error output

```PowerShell
PS C:\WINDOWS\system32> resolve-azerror


   HistoryId: 1


Message        : Administrator rights are required to install or update. Log on to the computer with an account that
                 has Administrator rights, and then try again, or install by adding "-Scope CurrentUser" to your
                 command. You can also try running the Windows PowerShell session with elevated rights (Run as
                 Administrator).
StackTrace     :
Exception      : System.Exception
InvocationInfo : {Install-Package}
Line           :             $null = PackageManagement\Install-Package @PSBoundParameters

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
                 + ...          $null = PackageManagement\Install-Package @PSBoundParameters
                 +                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1



   HistoryId: -1


Message        : Unable to find type [System.Net.Http.HttpClient].
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :         [System.Net.Http.HttpClient]

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:6260 char:9
                 +         [System.Net.Http.HttpClient]
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Unable to find type [System.Net.Http.HttpClient].
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :         [System.Net.Http.HttpClient]

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:6260 char:9
                 +         [System.Net.Http.HttpClient]
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : Unable to find type [Microsoft.PowerShell.Commands.PowerShellGet.Telemetry].
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :     $telemetryMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | Get-Member
                 -Static).Name

Position       : At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:715 char:26
                 + ... yMethods = ([Microsoft.PowerShell.Commands.PowerShellGet.Telemetry] | ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by isra-fel** [comment]
Thanks for the feedback. I believe this is a general question about installing PowerShell modules therefore can be better answered in PowerShell/PowerShell repo.
BTW you can try [updating PowerShellGet](https://learn.microsoft.com/en-us/powershell/gallery/powershellget/overview?view=powershellget-2.x)
