### ISSUE TITLE
Getting "Unexpected end of file has occurred" error in Get-AzStorageBlob

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-powershell#23398]
### Description

Getting this error message randomly.

```
2023-11-09T23:05:59.4286814Z Exception        : System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not 
2023-11-09T23:05:59.4324629Z                    closed: Last-Modified, Properties, Blob, Blobs, EnumerationResults. Line 1, position 65215.
2023-11-09T23:05:59.4335195Z                       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2023-11-09T23:05:59.4349384Z                       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
2023-11-09T23:05:59.4363313Z                       at System.Xml.XmlTextReaderImpl.ParseElementContent()
2023-11-09T23:05:59.4377925Z                       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
2023-11-09T23:05:59.4391701Z                       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2023-11-09T23:05:59.4404042Z                       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
2023-11-09T23:05:59.4418993Z                       at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegment(String prefix, String marker, 
2023-11-09T23:05:59.4432017Z                    Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken 
2023-11-09T23:05:59.4449108Z                    cancellationToken)
2023-11-09T23:05:59.4471091Z                       at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, 
2023-11-09T23:05:59.4486407Z                    BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken 
2023-11-09T23:05:59.4505290Z                    cancellationToken)
2023-11-09T23:05:59.4521537Z                       at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, 
2023-11-09T23:05:59.4528909Z                    Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
2023-11-09T23:05:59.4541387Z                       at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2023-11-09T23:05:59.4553957Z                       at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.AsPages(String continuationToken, 
2023-11-09T23:05:59.4566248Z                    Nullable`1 pageHintSize)+MoveNext()
2023-11-09T23:05:59.4585914Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByPref
2023-11-09T23:05:59.4658346Z                    ix(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String prefix, Func`2 
2023-11-09T23:05:59.4658891Z                    blobFilter, Boolean includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.4659442Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByName
2023-11-09T23:05:59.4660065Z                    (Int64 taskId, IStorageBlobManagement localChannel, String containerName, String blobName, Boolean 
2023-11-09T23:05:59.4662196Z                    includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.4679451Z                       at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTa
2023-11-09T23:05:59.4689706Z                    sk(Int64 taskId, Task task)
2023-11-09T23:05:59.4703725Z Message          : Unexpected end of file has occurred. The following elements are not closed: Last-Modified, 
2023-11-09T23:05:59.4716872Z                    Properties, Blob, Blobs, EnumerationResults. Line 1, position 65215.
2023-11-09T23:05:59.4731451Z StackTrace       :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2023-11-09T23:05:59.4741118Z                       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
2023-11-09T23:05:59.4756183Z                       at System.Xml.XmlTextReaderImpl.ParseElementContent()
2023-11-09T23:05:59.4785888Z                       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
2023-11-09T23:05:59.4800422Z                       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2023-11-09T23:05:59.4813311Z                       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
2023-11-09T23:05:59.4826058Z                       at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegment(String prefix, String marker, 
2023-11-09T23:05:59.4843339Z                    Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken 
2023-11-09T23:05:59.4853849Z                    cancellationToken)
2023-11-09T23:05:59.4873257Z                       at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, 
2023-11-09T23:05:59.4885694Z                    BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken 
2023-11-09T23:05:59.4939986Z                    cancellationToken)
2023-11-09T23:05:59.4958996Z                       at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, 
2023-11-09T23:05:59.4973311Z                    Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
2023-11-09T23:05:59.4994641Z                       at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2023-11-09T23:05:59.5009552Z                       at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.AsPages(String continuationToken, 
2023-11-09T23:05:59.5046172Z                    Nullable`1 pageHintSize)+MoveNext()
2023-11-09T23:05:59.5067706Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByPref
2023-11-09T23:05:59.5090293Z                    ix(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String prefix, Func`2 
2023-11-09T23:05:59.5103729Z                    blobFilter, Boolean includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.5122139Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByName
2023-11-09T23:05:59.5135690Z                    (Int64 taskId, IStorageBlobManagement localChannel, String containerName, String blobName, Boolean 
2023-11-09T23:05:59.5153513Z                    includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.5173087Z                       at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTa
2023-11-09T23:05:59.5196098Z                    sk(Int64 taskId, Task task)
```

### Issue script & Debug output

```PowerShell
$blobs = Get-AzStorageBlob -Container $containerName -Context $context
Can't attach debug output, it's too long.
```

### Environment data

```PowerShell
2023-11-10T21:10:22.7649432Z Key   : PSVersion
2023-11-10T21:10:22.7668712Z Value : 7.3.6
2023-11-10T21:10:22.7681497Z Name  : PSVersion
2023-11-10T21:10:22.7690419Z 
2023-11-10T21:10:22.7722753Z Key   : PSEdition
2023-11-10T21:10:22.7737638Z Value : Core
2023-11-10T21:10:22.7753919Z Name  : PSEdition
2023-11-10T21:10:22.7764539Z 
2023-11-10T21:10:22.7786344Z Key   : GitCommitId
2023-11-10T21:10:22.7800122Z Value : 7.3.6
2023-11-10T21:10:22.7882564Z Name  : GitCommitId
2023-11-10T21:10:22.7885559Z 
2023-11-10T21:10:22.7899059Z Key   : OS
2023-11-10T21:10:22.7916945Z Value : Microsoft Windows 10.0.20348
2023-11-10T21:10:22.7935054Z Name  : OS
2023-11-10T21:10:22.7944770Z 
2023-11-10T21:10:22.7969993Z Key   : Platform
2023-11-10T21:10:22.7984669Z Value : Win32NT
2023-11-10T21:10:22.7999939Z Name  : Platform
2023-11-10T21:10:22.8009677Z 
2023-11-10T21:10:22.8036313Z Key   : PSCompatibleVersions
2023-11-10T21:10:22.8173182Z Value : {1.0, 2.0, 3.0, 4.0…}
2023-11-10T21:10:22.8174117Z Name  : PSCompatibleVersions
2023-11-10T21:10:22.8174320Z 
2023-11-10T21:10:22.8174911Z Key   : PSRemotingProtocolVersion
2023-11-10T21:10:22.8175299Z Value : 2.3
2023-11-10T21:10:22.8176301Z Name  : PSRemotingProtocolVersion
2023-11-10T21:10:22.8176799Z 
2023-11-10T21:10:22.8185050Z Key   : SerializationVersion
2023-11-10T21:10:22.8198450Z Value : 1.1.0.1
2023-11-10T21:10:22.8223615Z Name  : SerializationVersion
2023-11-10T21:10:22.8225104Z 
2023-11-10T21:10:22.8250905Z Key   : WSManStackVersion
2023-11-10T21:10:22.8268208Z Value : 3.0
2023-11-10T21:10:22.8289491Z Name  : WSManStackVersion
```

### Module versions

```PowerShell
2023-11-10T21:10:22.8347013Z Name              : Az.Accounts
2023-11-10T21:10:22.8364417Z Path              : C:\program files\powershell\7\Modules\Az.Accounts\2.12.2\Az.Accounts.psm1
2023-11-10T21:10:22.8378478Z Description       : Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in 
2023-11-10T21:10:22.8400800Z                     Windows PowerShell and PowerShell Core.
2023-11-10T21:10:22.8407834Z                     
2023-11-10T21:10:22.8425620Z                     For more information on account credential management, please visit the following: 
2023-11-10T21:10:22.8438911Z                     https://learn.microsoft.com/powershell/azure/authenticate-azureps
2023-11-10T21:10:22.8453817Z Guid              : 17a2feff-488b-47f9-8729-e2cec094624c
2023-11-10T21:10:22.8471895Z Version           : 2.12.2
2023-11-10T21:10:22.8497730Z ModuleBase        : C:\program files\powershell\7\Modules\Az.Accounts\2.12.2
2023-11-10T21:10:22.8510525Z ModuleType        : Script
2023-11-10T21:10:22.8527535Z PrivateData       : {[PSData, System.Collections.Hashtable]}
2023-11-10T21:10:22.8547995Z AccessMode        : ReadWrite
2023-11-10T21:10:22.8561096Z ExportedAliases   : {[Add-AzAccount, Add-AzAccount], [Get-AzDomain, Get-AzDomain], [Invoke-AzRest, Invoke-AzRest], 
2023-11-10T21:10:22.8580023Z                     [Login-AzAccount, Login-AzAccount]…}
2023-11-10T21:10:22.8602766Z ExportedCmdlets   : {[Add-AzEnvironment, Add-AzEnvironment], [Clear-AzConfig, Clear-AzConfig], [Clear-AzContext, 
2023-11-10T21:10:22.8614237Z                     Clear-AzContext], [Clear-AzDefault, Clear-AzDefault]…}
2023-11-10T21:10:22.8635343Z ExportedFunctions : {}
2023-11-10T21:10:22.8659001Z ExportedVariables : {}
2023-11-10T21:10:22.8673598Z NestedModules     : {Microsoft.Azure.PowerShell.Cmdlets.Accounts}
2023-11-10T21:10:22.8682978Z 
2023-11-10T21:10:22.8693860Z 
2023-11-10T21:10:22.8710053Z Name              : Az.Resources
2023-11-10T21:10:22.8723218Z Path              : C:\program files\powershell\7\Modules\Az.Resources\6.6.1\Az.Resources.psm1
2023-11-10T21:10:22.8740203Z Description       : Microsoft Azure PowerShell - Azure Resource Manager and Active Directory cmdlets in Windows 
2023-11-10T21:10:22.8748611Z                     PowerShell and PowerShell Core.  Manages subscriptions, tenants, resource groups, deployment 
2023-11-10T21:10:22.8764501Z                     templates, providers, and resource permissions in Azure Resource Manager.  Provides cmdlets for 
2023-11-10T21:10:22.8777773Z                     managing resources generically across resource providers.
2023-11-10T21:10:22.8793145Z                     For more information on Resource Manager, please visit the following: 
2023-11-10T21:10:22.8807050Z                     https://learn.microsoft.com/azure/azure-resource-manager/
2023-11-10T21:10:22.8821179Z                     For more information on Active Directory, please visit the following: 
2023-11-10T21:10:22.8835889Z                     https://learn.microsoft.com/azure/active-directory/fundamentals/active-directory-whatis
2023-11-10T21:10:22.8850977Z Guid              : 48bb344d-4c24-441e-8ea0-589947784700
2023-11-10T21:10:22.8864934Z Version           : 6.6.1
2023-11-10T21:10:22.8881518Z ModuleBase        : C:\program files\powershell\7\Modules\Az.Resources\6.6.1
2023-11-10T21:10:22.8894927Z ModuleType        : Script
2023-11-10T21:10:22.8907922Z PrivateData       : {[PSData, System.Collections.Hashtable]}
2023-11-10T21:10:22.8929939Z AccessMode        : ReadWrite
2023-11-10T21:10:22.8937239Z ExportedAliases   : {[Get-AzADServicePrincipalCredential, Get-AzADServicePrincipalCredential], 
2023-11-10T21:10:22.8978047Z                     [Get-AzResourceProviderAction, Get-AzResourceProviderAction], [Get-AzSubscriptionDeployment, 
2023-11-10T21:10:22.8984902Z                     Get-AzSubscriptionDeployment], [Get-AzSubscriptionDeploymentOperation, 
2023-11-10T21:10:22.9004929Z                     Get-AzSubscriptionDeploymentOperation]…}
2023-11-10T21:10:22.9018226Z ExportedCmdlets   : {[Export-AzResourceGroup, Export-AzResourceGroup], [Export-AzTemplateSpec, Export-AzTemplateSpec], 
2023-11-10T21:10:22.9038440Z                     [Get-AzDenyAssignment, Get-AzDenyAssignment], [Get-AzDeployment, Get-AzDeployment]…}
2023-11-10T21:10:22.9047120Z ExportedFunctions : {[Add-AzADAppPermission, Add-AzADAppPermission], [Add-AzADGroupMember, Add-AzADGroupMember], 
2023-11-10T21:10:22.9061493Z                     [Get-AzADAppCredential, Get-AzADAppCredential], [Get-AzADAppFederatedCredential, 
2023-11-10T21:10:22.9073042Z                     Get-AzADAppFederatedCredential]…}
2023-11-10T21:10:22.9087695Z ExportedVariables : {}
2023-11-10T21:10:22.9102365Z NestedModules     : {Microsoft.Azure.PowerShell.Cmdlets.Resources, Microsoft.Azure.PowerShell.Cmdlets.ResourceManager, 
2023-11-10T21:10:22.9120465Z                     Microsoft.Azure.PowerShell.Cmdlets.Tags, Az.MSGraph…}
2023-11-10T21:10:22.9131356Z 
2023-11-10T21:10:22.9143720Z 
2023-11-10T21:10:22.9154286Z Name              : Az.Storage
2023-11-10T21:10:22.9172503Z Path              : C:\program files\powershell\7\Modules\Az.Storage\5.6.0\Az.Storage.psm1
2023-11-10T21:10:22.9184796Z Description       : Microsoft Azure PowerShell - Storage service data plane and management cmdlets for Azure Resource 
2023-11-10T21:10:22.9199891Z                     Manager in Windows PowerShell and PowerShell Core.  Creates and manages storage accounts in Azure 
2023-11-10T21:10:22.9214133Z                     Resource Manager.
2023-11-10T21:10:22.9226361Z                     
2023-11-10T21:10:22.9239149Z                     For more information on Storage, please visit the following: 
2023-11-10T21:10:22.9254517Z                     https://learn.microsoft.com/azure/storage/
2023-11-10T21:10:22.9276432Z Guid              : dfa9e4ea-1407-446d-9111-79122977ab20
2023-11-10T21:10:22.9298482Z Version           : 5.6.0
2023-11-10T21:10:22.9316269Z ModuleBase        : C:\program files\powershell\7\Modules\Az.Storage\5.6.0
2023-11-10T21:10:22.9331426Z ModuleType        : Script
2023-11-10T21:10:22.9349519Z PrivateData       : {[PSData, System.Collections.Hashtable]}
2023-11-10T21:10:22.9373355Z AccessMode        : ReadWrite
2023-11-10T21:10:22.9399065Z ExportedAliases   : {[Disable-AzStorageSoftDelete, Disable-AzStorageSoftDelete], [Enable-AzStorageSoftDelete, 
2023-11-10T21:10:22.9409275Z                     Enable-AzStorageSoftDelete], [Get-AzDatalakeGen2FileSystem, Get-AzDatalakeGen2FileSystem], 
2023-11-10T21:10:22.9425136Z                     [Get-AzStorageContainerAcl, Get-AzStorageContainerAcl]…}
2023-11-10T21:10:22.9439534Z ExportedCmdlets   : {[Add-AzRmStorageContainerLegalHold, Add-AzRmStorageContainerLegalHold], 
2023-11-10T21:10:22.9452254Z                     [Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountManagementPolicyAction], 
2023-11-10T21:10:22.9467720Z                     [Add-AzStorageAccountNetworkRule, Add-AzStorageAccountNetworkRule], [Close-AzStorageFileHandle, 
2023-11-10T21:10:22.9480430Z                     Close-AzStorageFileHandle]…}
2023-11-10T21:10:22.9495014Z ExportedFunctions : {}
2023-11-10T21:10:22.9509998Z ExportedVariables : {}
2023-11-10T21:10:22.9526957Z NestedModules     : {Microsoft.Azure.PowerShell.Cmdlets.Storage.Management, Microsoft.Azure.PowerShell.Cmdlets.Storage}
```

### Error output

```PowerShell
2023-11-09T23:05:59.4286814Z Exception        : System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not 
2023-11-09T23:05:59.4324629Z                    closed: Last-Modified, Properties, Blob, Blobs, EnumerationResults. Line 1, position 65215.
2023-11-09T23:05:59.4335195Z                       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2023-11-09T23:05:59.4349384Z                       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
2023-11-09T23:05:59.4363313Z                       at System.Xml.XmlTextReaderImpl.ParseElementContent()
2023-11-09T23:05:59.4377925Z                       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
2023-11-09T23:05:59.4391701Z                       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2023-11-09T23:05:59.4404042Z                       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
2023-11-09T23:05:59.4418993Z                       at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegment(String prefix, String marker, 
2023-11-09T23:05:59.4432017Z                    Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken 
2023-11-09T23:05:59.4449108Z                    cancellationToken)
2023-11-09T23:05:59.4471091Z                       at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, 
2023-11-09T23:05:59.4486407Z                    BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken 
2023-11-09T23:05:59.4505290Z                    cancellationToken)
2023-11-09T23:05:59.4521537Z                       at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, 
2023-11-09T23:05:59.4528909Z                    Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
2023-11-09T23:05:59.4541387Z                       at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2023-11-09T23:05:59.4553957Z                       at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.AsPages(String continuationToken, 
2023-11-09T23:05:59.4566248Z                    Nullable`1 pageHintSize)+MoveNext()
2023-11-09T23:05:59.4585914Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByPref
2023-11-09T23:05:59.4658346Z                    ix(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String prefix, Func`2 
2023-11-09T23:05:59.4658891Z                    blobFilter, Boolean includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.4659442Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByName
2023-11-09T23:05:59.4660065Z                    (Int64 taskId, IStorageBlobManagement localChannel, String containerName, String blobName, Boolean 
2023-11-09T23:05:59.4662196Z                    includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.4679451Z                       at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTa
2023-11-09T23:05:59.4689706Z                    sk(Int64 taskId, Task task)
2023-11-09T23:05:59.4703725Z Message          : Unexpected end of file has occurred. The following elements are not closed: Last-Modified, 
2023-11-09T23:05:59.4716872Z                    Properties, Blob, Blobs, EnumerationResults. Line 1, position 65215.
2023-11-09T23:05:59.4731451Z StackTrace       :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2023-11-09T23:05:59.4741118Z                       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
2023-11-09T23:05:59.4756183Z                       at System.Xml.XmlTextReaderImpl.ParseElementContent()
2023-11-09T23:05:59.4785888Z                       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
2023-11-09T23:05:59.4800422Z                       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2023-11-09T23:05:59.4813311Z                       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
2023-11-09T23:05:59.4826058Z                       at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegment(String prefix, String marker, 
2023-11-09T23:05:59.4843339Z                    Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken 
2023-11-09T23:05:59.4853849Z                    cancellationToken)
2023-11-09T23:05:59.4873257Z                       at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, 
2023-11-09T23:05:59.4885694Z                    BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken 
2023-11-09T23:05:59.4939986Z                    cancellationToken)
2023-11-09T23:05:59.4958996Z                       at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, 
2023-11-09T23:05:59.4973311Z                    Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
2023-11-09T23:05:59.4994641Z                       at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2023-11-09T23:05:59.5009552Z                       at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.AsPages(String continuationToken, 
2023-11-09T23:05:59.5046172Z                    Nullable`1 pageHintSize)+MoveNext()
2023-11-09T23:05:59.5067706Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByPref
2023-11-09T23:05:59.5090293Z                    ix(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String prefix, Func`2 
2023-11-09T23:05:59.5103729Z                    blobFilter, Boolean includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.5122139Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByName
2023-11-09T23:05:59.5135690Z                    (Int64 taskId, IStorageBlobManagement localChannel, String containerName, String blobName, Boolean 
2023-11-09T23:05:59.5153513Z                    includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.5173087Z                       at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTa
2023-11-09T23:05:59.5196098Z                    sk(Int64 taskId, Task task)
```

**Comment by blueww** [comment]
@andrei-faber 

The error is reported from storage .net SDK (Powershell based on .net SDK).
We have not see this kind of issue before.

Would you please open an issue in .net SDK repo for that: https://github.com/Azure/azure-sdk-for-net/issues? 
Please add following information:
1. The SDK version: For Az.Storage 5.6.0, SDK "Azure.Storage.Blobs" version is "12.16.0".
2. How to repro this issue, like how many blobs in the container.
3. Better with network trace (debug log) of the cmdlet. you can save it in a file and attach to the issue (hide credential).
4. Other information the SDK issue template asked.

Besides that, could you please see if the issue can repro on latest Az.Storage module? https://www.powershellgallery.com/packages/Az.Storage

**Comment by blueww** [comment]
@andrei-faber 

Thanks for opening the SDK issue!
However, as I see you have not added all the information I suggested into the issue, like 2-4.
Without this information, it's very difficult for us to do the investigation.

**Comment by andrei-faber** [comment]
It's difficult to get the number of blobs, as listing those blobs often fails.
Getting fiddler trace in this environment is impossible.
And as I already wrote, it's happening randomly. Much more often in one of the environments, though. Or at least at the current moment.

**Comment by blueww** [comment]
@andrei-faber


This issue looks not cause by PSH/SDK, but cause by the server responds Client received in not complete. As you have said, it happens much more often in one of the environments, it looks related with the current status on the client machine/environment, like CPU/memory is too high, or network is not stable. I have met some similar issue resolved by restart client machine. 

If this issue still can repro on your side, as this looks not PSH/SDK issue, might related with client/server connection, or client machine status, or server behavior, I would suggest you open a help ticket by follow https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header to ask server team help.

For number of blobs, you might can share a range, like > 1K blobs, > 10K blobs.
As you can't get fiddler trace, please at least give the storage account name, repro UTC time, and better with other details like request ID which can help to identify the issue.

**Comment by andrei-faber** [comment]
@blueww
The only thing that I can say about the number of blobs is that it's > 9 millions. Also, I'm getting same error on another host that requests same storage account.
I don't think that it's a good idea to publish detailed information in the public repo.

**Comment by blueww** [comment]
@andrei-faber 

The issue should be related with the container contains a big number of blobs.

As we don't want to publish detailed information in the public repo, would you please raise a help ticker by follow https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header, and you can give more details in that help ticket?

Besides that, as you have a big number of blobs in container, it's not suggested to list blob with one command, I would suggest you listing blobs chunk by chuck, you can find a sample script in https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstorageblob?view=azps-11.0.0#example-4-list-blobs-in-multiple-batches. Feel free to let me know if you meet any issue when use this script.

**Comment by blueww** [comment]
@andrei-faber

Have you tried to list blobs in the container chunk by chunk with the [sample script](https://learn.microsoft.com/en-us/powershell/module/az.storage/get-azstorageblob?view=azps-11.0.0#example-4-list-blobs-in-multiple-batches) in my above comment? 
As the container contains a big number of blobs, this should be the suggested way to list blobs in the container.
Feel free to let us know if you meet any issue to use the sample script.

**Comment by andrei-faber** [comment]
Hi @blueww 
How do I make this support request be routed to you?
Trying to list it using batches, but that takes a lot of time.

**Comment by blueww** [comment]
@andrei-faber 

I don't think you need route this support request to me. Since this error is mostly from server responds, and it can repro with only SDK (Powershell based on SDK). So this is not PSH issue actually. I think someone from server team or SDK team should look at it.

For the workaround, list blob batch by batch must take a long time as you have so many blobs in the container, not sure what's the time difference when list blobs with single command vs batch by batch on the same test machine on your side? You might can adjust $MaxReturn to a bigger number (but not too big or the error might occur again) to see if the list will be faster.

**Comment by andrei-faber** [comment]
@blueww I've tried using the batch script and it didn't fail, but this may be just a random deviation. Will need more testing.
The total number of blobs is a bit more than 12 millions.

However, doesn't Azure.Storage.Blobs always run the requests in batches?
Also, I intercepted one of the requests that had incomplete response, and the response was 272346 bytes.

I've created the support request. Case 2311300040013278

**Comment by blueww** [comment]
@andrei-faber 

For Azure.Storage.Blobs, in [list blob API](https://github.com/Azure/azure-sdk-for-net/blob/54d94d1ad4a22d7510b915e6a67db63f4e2f4f9e/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L2446C42-L2446C42), it will return type `Pageable<BlobItem>`， and the SDK user can set pageSizeHint in AsPage function to indicate the max blob count return in 1 request, like [this sample](https://github.com/Azure/azure-sdk-for-net/blob/54d94d1ad4a22d7510b915e6a67db63f4e2f4f9e/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L2381).

As you have created support request, the related team will come to help you. (I don't have access to the support request.)

**Comment by blueww** [comment]
@andrei-faber

I will close this issue, as this is not a PowerShell issue, and we have provided workaround.
Feel free to contact us if you need any further assistance on Azure Powershell.
