### ISSUE TITLE
New-AzVM failed with an Azure Compute Gallery image with Az.Compute module v7.0.0

### ISSUE THREAD

**Issue by lavanack** [Azure/azure-powershell#23560]
### Description

The script https://github.com/lavanack/laurentvanacker.com/blob/master/Azure/Azure%20Virtual%20Desktop/Azure%20Image%20Builder/New-AzureComputeGalleryVM.ps1 works perfectly with AZ.Compute v6.3.0 but fails when upgrading to v7.
I used this script as a demo for depoying a VM with an image coming from an Azure Compute Gallery.
The error occurs line 264 

### Issue script & Debug output

```PowerShell
[DBG]: PS C:\laurentvanacker.com\Azure\Azure Virtual Desktop\Azure Image Builder>> 
DEBUG: 10:43:09 AM - NewAzureVMCommand begin processing with ParameterSet 'DefaultParameterSet'.
DEBUG: 10:43:09 AM - using account id 'admin@MngEnv113816.onmicrosoft.com'...
DEBUG: 10:43:09 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'New-AzVM' :
Starting in November 2023 the "New-AzVM" cmdlet will deploy with the Trusted Launch configuration by default. To know more about Trusted Launch, please visit https://aka.ms/TLaD
- The change is expected to take effect in Az version : '11.0.0'
- The change is expected to take effect in Az.Compute version : '7.0.0'
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
DEBUG: [Common.Authentication]: Authenticating using Account: 'admin@MngEnv113816.onmicrosoft.com', environment: 'AzureCloud', tenant: 'f4662c1d-e072-46af-8700-b8ca2968ccab'
DEBUG: 10:43:09 AM - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 10:43:09 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'f4662c1d-e072-46af-8700-b8ca2968ccab', Scopes:'https://management.core.windows.net//.d
efault', AuthorityHost:'https://login.microsoftonline.com/', UserId:'admin@MngEnv113816.onmicrosoft.com'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 2e8e0aa8-38e8-487b-ad25-4b3628d83850] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 2e8e0aa8-38e8-487b-ad25-4b3628d83850] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 2e8e0aa8-38e8-487b-ad25-4b3628d83850] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 2e8e0aa8-38e8-487b-ad25-4b3628d83850] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 2e8e0aa8-38e8-487b-ad25-4b3628d83850] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 2e8e0aa8-38e8-487b-ad25-4b3628d83850] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z] Found 2 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z] Returning 2 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] MSAL MSAL.Desktop with assembly version '4.49.1.0'. C
orrelationId(6478bc96-c4cd-448b-bf56-1c67e24281c3)
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 6478bc96-c4cd-448b-bf56-1c67e24281c3
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] === Token Acquisition (SilentRequest) started:
	 Scopes: https://management.core.windows.net//.default
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] Access token is not expired. Returning the found cach
e entry. [Current time (11/26/2023 09:43:09) - Expiration Time (11/26/2023 11:03:40 +00:00) - Extended Expiration Time (11/26/2023 11:03:40 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] Returning access token found in cache. RefreshOn exis
ts ? False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3] 
	=== Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2023-11-26 09:43:09Z - 6478bc96-c4cd-448b-bf56-1c67e24281c3]  AT expiration time: 11/26/2023 11:03:40 AM +00:00, s
copes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-11-26T11:03:40.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'f4662c1d-e072-46af-8700-b8ca2968ccab', UserId: 'admin@MngEnv113816.onmicrosoft.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/{subscription}/providers/Microsoft.Compute/locations/eastus/publishers/subscriptions/artifacttypes/vmimage/offers/subscriptio
ns/skus/subscriptions/versions/subscriptions?api-version=2023-07-01

Headers:
x-ms-client-request-id        : 42abc8f9-6041-4f74-bb96-0cb9bf058f61
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/GetVMImageFromLocation3Min;12999,Microsoft.Compute/GetVMImageFromLocation30Min;73999
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : d2beb48f-8596-4c83-894e-30459ea28873_133428454371327588
x-ms-request-id               : d91a3e99-e898-4e13-9e68-c2c3b28e9a34
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11995
x-ms-correlation-request-id   : 4ad12509-bc52-4af5-abc3-18954f6846f2
x-ms-routing-request-id       : FRANCECENTRAL:20231126T094309Z:4ad12509-bc52-4af5-abc3-18954f6846f2
X-Content-Type-Options        : nosniff
Date                          : Sun, 26 Nov 2023 09:43:08 GMT

Body:
{
  "error": {
    "code": "InvalidParameter",
    "message": "The value of parameter version is invalid.",
    "target": "version"
  }
}


DEBUG: 10:43:09 AM - [ConfigManager] Got nothing from [DisableErrorRecordsPersistence], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 10:43:09 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
New-AzVM : The value of parameter version is invalid.
At C:\laurentvanacker.com\Azure\Azure Virtual Desktop\Azure Image Builder\New-AzureComputeGalleryVM.ps1:264 char:1
+ New-AzVM -ResourceGroupName $ResourceGroupName -Location $Location -V ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzVM], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.NewAzureVMCommand
 
DEBUG: 10:43:09 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 10:43:09 AM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 10:43:09 AM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Compute:7.0.0; CommandName: New-AzVM; PSVersion: 5.1.22621.2506; IsSuccess: False; Duration: 00:00:00.5492584; Exception: The value of parameter version is 
invalid.;
DEBUG: 10:43:10 AM - NewAzureVMCommand end processing.
```

### Environment data

```PowerShell
Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.22621.2506                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.22621.2506                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                                                                   
---------- -------    ----                                ----------------                                                                                                                   
Script     2.13.2     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}                                                           
Script     7.0.0      Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk...}                                           
Script     7.0.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendH...
Script     6.12.0     Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}                                         
Script     1.5.0      Az.Security                         {Add-AzSecurityAdaptiveNetworkHardening, Add-AzSecuritySqlVulnerabilityAssessmentBaseline, Confirm-AzSecurityAutomation, Disable...
Script     6.0.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorage...
```

### Error output

```PowerShell
RequestId      : 0c3b0ef8-795a-48a9-ad96-ad171ade8597
Message        : The value of parameter version is invalid.
ServerMessage  : InvalidParameter: The value of parameter version is invalid. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {GET https://management.azure.com/subscriptions/{subscription}/providers/Microsoft.Compute/locations/eastus/publishers/subscriptions/artifacttypes/vmi
                 mage/offers/subscriptions/skus/subscriptions/versions/subscriptions?api-version=2023-07-01}
InvocationInfo : {New-AzVM}
Line           : New-AzVM -ResourceGroupName $ResourceGroupName -Location $Location -VM $VMConfig #-DisableBginfoExtension
                 
Position       : At C:\laurentvanacker.com\Azure\Azure Virtual Desktop\Azure Image Builder\New-AzureComputeGalleryVM.ps1:264 char:1
                 + New-AzVM -ResourceGroupName $ResourceGroupName -Location $Location -V ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.Compute.VirtualMachineImagesOperations.<GetWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Compute.NewAzureVMCommand.DefaultExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 3
```

**Comment by lbouriez** [comment]
Hello, having the same issue, following up

**Comment by sandeepraichura** [comment]
Thanks for reporting the issue, we will be looking into it.

**Comment by AlyaKoni** [comment]
Same issue here. With image gallery and also with a managed image. Even with newest modules:

```
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     7.1.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDa…
Script     4.2.0                 Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-AzWvdAppAttachPackage… 
Script     5.0.1                 Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKe… 
Script     7.1.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBa… 
Script     3.2.0                 Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-AzOperationalInsightsL… 
Script     6.12.1                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDe… 
Script     6.0.1                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction… 
```

**Comment by AlyaKoni** [comment]
Still working well with Az.Compute v6.3.0

**Comment by AlyaKoni** [comment]
> @lavanack , What is the Gallery Image Version value that is trying to be used here?

If I take a managed image, there is no version:

```
$VMCredential = New-Object System.Management.Automation.PSCredential ("$($VmToImage)admin", $VMPasswordSec)
$netIfaceName = $Vm.NetworkProfile.NetworkInterfaces[0].Id.Substring($Vm.NetworkProfile.NetworkInterfaces[0].Id.LastIndexOf("/") + 1)
$netIface = Get-AzNetworkInterface -ResourceGroupName $VmResourceGroupName -Name $netIfaceName
$VmConfig = New-AzVMConfig -VMName $VmToImage -VMSize $Vm.HardwareProfile.VmSize
$VmConfig | Set-AzVMOperatingSystem -Windows -ComputerName $VmToImage -Credential $VMCredential
$image = Get-AzImage -ImageName $ImageName -ResourceGroupName $ImageResourceGroupName
$VmConfig | Set-AzVMSourceImage -Id $image.Id | Out-Null
$VmConfig | Add-AzVMNetworkInterface -Id $netIface.Id | Out-Null
$VmConfig | Set-AzVMBootDiagnostic -Enable -ResourceGroupName $DiagnosticResourceGroupName -StorageAccountName $DiagnosticStorageName | Out-Null
$VmConfig | Set-AzVMOSDisk -Name $VMDiskName -CreateOption FromImage -Caching ReadWrite -DiskSizeInGB $Vm.StorageProfile.OsDisk.DiskSizeGB | Out-Null
$newVm = New-AzVM -ResourceGroupName $VmResourceGroupName -Location $Vm.Location -VM $VmConfig -DisableBginfoExtension
```

**Comment by Sandido** [comment]
> > @lavanack , What is the Gallery Image Version value that is trying to be used here?
> 
> If I take a managed image, there is no version:
> 
> ```
> $VMCredential = New-Object System.Management.Automation.PSCredential ("$($VmToImage)admin", $VMPasswordSec)
> $netIfaceName = $Vm.NetworkProfile.NetworkInterfaces[0].Id.Substring($Vm.NetworkProfile.NetworkInterfaces[0].Id.LastIndexOf("/") + 1)
> $netIface = Get-AzNetworkInterface -ResourceGroupName $VmResourceGroupName -Name $netIfaceName
> $VmConfig = New-AzVMConfig -VMName $VmToImage -VMSize $Vm.HardwareProfile.VmSize
> $VmConfig | Set-AzVMOperatingSystem -Windows -ComputerName $VmToImage -Credential $VMCredential
> $image = Get-AzImage -ImageName $ImageName -ResourceGroupName $ImageResourceGroupName
> $VmConfig | Set-AzVMSourceImage -Id $image.Id | Out-Null
> $VmConfig | Add-AzVMNetworkInterface -Id $netIface.Id | Out-Null
> $VmConfig | Set-AzVMBootDiagnostic -Enable -ResourceGroupName $DiagnosticResourceGroupName -StorageAccountName $DiagnosticStorageName | Out-Null
> $VmConfig | Set-AzVMOSDisk -Name $VMDiskName -CreateOption FromImage -Caching ReadWrite -DiskSizeInGB $Vm.StorageProfile.OsDisk.DiskSizeGB | Out-Null
> $newVm = New-AzVM -ResourceGroupName $VmResourceGroupName -Location $Vm.Location -VM $VmConfig -DisableBginfoExtension
> ```

@AlyaKoni , what image are you providing in this script? Does this script work or not?

**Comment by AlyaKoni** [comment]
The script is part of an image creation script to store to image gallery. I create an image with:
```
New-AzImage -Image $image -ImageName $ImageName -ResourceGroupName $ImageResourceGroupName -ErrorAction Stop
```
then I recreate with above code the VM.

This code is working well with  Az.Compute v6.3.0. The entire script you can find here: https://github.com/AlyaKoni/ALYADO-ADM-Public/blob/master/scripts/avd/image/Prepare-ImageClient.ps1

**Comment by TiTi** [comment]
Same issue here during New-AzVM on a brand new Az module install

```
$_image = Get-AzGalleryImageDefinition -ResourceGroupName $ImageResourcegroupName -GalleryName $ImageGalleryName -Name $imageName

$vmConfig = New-AzVMConfig -VMName $vmName -VMSize $VMSize`
# ...
$vmConfig | Set-AzVMOSDisk -Name "$vmName-OsDisk" -CreateOption FromImage
$vmConfig | Set-AzVMSourceImage -Id $_image.Id
```

**Comment by Sandido** [comment]
As a short term fix, you can set the SecurityType on the virtual machine to 'Standard' which should avoid this error. I am working on a fix for the default scenario.

**Comment by TiTi** [comment]
Workaround i used was to rollback to previous Az version :
```
Uninstall-Module Az
# restart terminal
# clean up PowerShell\Modules\Az* folders
Install-Module -Name Az -RequiredVersion 10.4.1 -Force
```
10.4.1 is the latest with Az.Compute in 6.3.0 (before it jumps to 7.0.0)

**Comment by AlyaKoni** [comment]
Are there any news on this bug? Even with SecurityType set to 'Standard' the bug still exists!

**Comment by Sandido** [comment]
The fix will be released on Feb 6th in the new Compute PS version.

**Comment by shendan19880401** [comment]
Has the fix be released?

**Comment by shendan19880401** [comment]
> The fix will be released on Feb 6th in the new Compute PS version.

Has the fix be released?
I installed latest version 11.3.0, the bug seemed not been fixed.
can you help to confirm the bug? Thank you!

**Comment by Sandido** [comment]
Based on the repro I was given and the issue I was able to reproduce, this issue was resolved. If this issue persists for you, I need to see the image Id you are providing in Set-AzVMSourceImage -Id as well as well as how you are making the image you are providing the id for.

**Comment by shendan19880401** [comment]
> Based on the repro I was given and the issue I was able to reproduce, this issue was resolved. If this issue persists for you, I need to see the image Id you are providing in Set-AzVMSourceImage -Id as well as well as how you are making the image you are providing the id for. Also provide the resource group name and vmname you are using as well as a time of your attempt.

1. this issue persists, you can reproduce it on your local PS client(with the latest version 11.3.0).

2.image id is below, it is not gallery, it is general image.
/subscriptions/03326e9d-6aa5-41ee-b308-4e70cc1b7cd6/resourceGroups/sd0961/providers/Microsoft.Compute/images/sdrhel88-image-20231220175907

3.the method of making the image:
I created a RHEL 88-gen2, [Standard] Security type VM, then generalized the VM, captured the generalized VM to the image [sdrhel88-image-20231220175907] via portal,
When I used the image to create the VM using the script below, the deploy failed with the error "The value of parameter version is invalid".

Generalized the linux VM:
[Deprovision or generalize a VM before creating an image - Azure Virtual Machines | Microsoft Learn](https://learn.microsoft.com/en-us/azure/virtual-machines/generalize#linux)

the script of creating the VM:
===
Select-AzSubscription -SubscriptionId 03326e9d-6aa5-41ee-b308-4e70cc1b7cd6

#????
$VM_RG = "sd0961"
$location = "Japan east"
$VmName = "sdvm12251"
$VmSize = "Standard_D4s_v3"
$VMLocalAdminUser = "sd"
$VMLocalAdminSecurePassword = ConvertTo-SecureString "xxx" -AsPlainText -Force
$NicName = "sdnic1"
 
$Image_RG = "sd0961"
$ImageName = "sdrhel88-image-20231220175907"
 
$VNET_RG = "sd0961"
$VnetName = "sdrhel88-vnet"
$SubnetName = "default"
 
 
#??????????????????????
$Vnet = Get-AzVirtualNetwork -ResourceGroupName $VNET_RG -Name $VnetName
$Subnet = Get-AzVirtualNetworkSubnetConfig -Name $SubnetName -VirtualNetwork $Vnet
 
# ???????????
$image = Get-AzImage -ResourceGroupName $Image_RG -ImageName $ImageName
$Credential = New-Object System.Management.Automation.PSCredential ($VMLocalAdminUser, $VMLocalAdminSecurePassword)
$VmConfig = New-AzVMConfig -Name $VmName -VMSize $VmSize
#$vmConfig = Set-AzVMSecurityProfile -VM $VmConfig -SecurityType Standard
$VmConfig = Set-AzVMSourceImage -VM $VmConfig -Id $image.Id
$VmConfig = Set-AzVMOperatingSystem -VM $VmConfig -Linux -ComputerName $VmName -Credential $Credential
 
# NIC ??????
$Nic = New-AzNetworkInterface -Name $NicName -ResourceGroupName $VM_RG -Location $Location -SubnetId $Subnet.Id
$VmConfig = Add-AzVMNetworkInterface -VM $VmConfig -Id $Nic.Id
$VmConfig.NetworkProfile.NetworkInterfaces.Item(0).Primary = $true
 
#????????
New-AzVM -VM $VmConfig -ResourceGroupName $VM_RG -Location $location
===

The original VM:

?????? ???? ????????, ????????

???????????

The image:

?????? ???? ????????, ????, ????????, ??????????? ?????

???????????

**Comment by shendan19880401** [comment]
The cause of the issue is below change in Az.Compute 7.0.0?

[Azure PowerShell release notes | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fpowershell%2Fazure%2Frelease-notes-azureps%3Fview%3Dazps-11.3.0&data=05%7C02%7Cv-danshen%40microsoft.com%7Ce54f05251e2b41eff4a808dc322f9048%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638440427187404213%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=sRBBjdT5dINN2UN%2FsZJhokkULXoGAn5sfDxkyPMedv8%3D&reserved=0)

[Breaking Change] Added defaulting logic for VM and VMSS creation to set SecurityType to TrustedLaunch and SecureBootEnabled and VTpmEnalbed to true when those are not set by the user.

**Comment by InsaneNL** [comment]
I'm having the same issue, with a Image from Azure compute gallery. Looking at the changelog it seems like the fix never got released? Just did a fresh install in a sandbox and AZ gives Az.compute 7.1.1  and the 6th line Az.compute.psd1 reads "# Generated on: 12/27/2023"

**Comment by lbouriez** [comment]
I confirm that we are still having the issues and we had to use a previous version of the AZ modules...
Can you link the files where the fix has been pushed ?

**Comment by sandeepraichura** [comment]
This should have been fixed with Az.Compute 7.1.2. Closing this out, please reopen if needed.

**Comment by chromebohemian448** [comment]
do you know when Az.Compute 7.1.2 will be pushed to the MS hosted ADO agents ?
