### ISSUE TITLE
`Az.SecurityInsights` v3.1.1 randomly runs something in the terminal

### ISSUE THREAD

**Issue by o-l-a-v** [Azure/azure-powershell#23573]
### Description

I've had the same issue with `Az.Accounts` earlier. Thought it was `vscode-powershell`s fault, but seems it was `Az`.

* 231006: https://github.com/PowerShell/vscode-powershell/issues/4773

Here's what happened today: I started writing down a script to `Get-AzSentinelDataConnector`. Suddenly the terminal outputs the following and won't finish/quit unless I do CTRL+C:

```
PS C:\Users\olav.birkeland\OneDrive\IT\Code> PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
   at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
   at System.Management.Automation.ScriptBlock.DoInvokeReturnAsIs(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[] args)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(ScriptBlock sb, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)       
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(String script)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.PsHelpers.RunScript[T](CommandInvocationIntrinsics cii, String script)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.PsExtensions.RunScript[T](PSCmdlet cmdlet, String script)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.PsHelpers.GetScriptCmdlets(PSCmdlet cmdlet, String scriptFolder)
   at Microsoft.Azure.PowerShell.Cmdlets.SecurityInsights.Runtime.PowerShell.GetScriptCmdlet.ProcessRecord()
                                             ^C
PS C:\Users\olav.birkeland\OneDrive\IT\Code>
```

### Issue script & Debug output

```PowerShell
I can't reliably reproduce it.
```

### Environment data

```PowerShell
Windows 11 23H2
PowerShell v7.4.0 x64 from MSI installer
vscode-powershell v2023.8.0
```

### Module versions

```PowerShell
Az.Accounts v2.13.2
Az.SecurityInsights v3.1.1
```

### Error output

```PowerShell
No output.
```

**Comment by o-l-a-v** [comment]
I answered in the `vscode-powershell` issue @isra-fel. Doesn't look obvious to me that this is `Az`'s fault alone.

**Comment by dolauli** [comment]
@o-l-a-v @isra-fel 

GetScriptCmdlet is called when autogen module is imported to get the function cmdlets within a folder. And the code is as below.

```
        public static IEnumerable<FunctionInfo> GetScriptCmdlets(PSCmdlet cmdlet, string scriptFolder)
        {
            // https://stackoverflow.com/a/40969712/294804
            var wrappedFolder = scriptFolder.Contains("'") ? $@"""{scriptFolder}""" : $@"'{scriptFolder}'";
            var getCmdletsCommand = $@"
$currentFunctions = Get-ChildItem function:
Get-ChildItem -Path {wrappedFolder} -Recurse -Include '*.ps1' -File | ForEach-Object {{ . $_.FullName }}
Get-ChildItem function: | Where-Object {{ ($currentFunctions -notcontains $_) -and $_.CmdletBinding }}
";
            return cmdlet?.RunScript<FunctionInfo>(getCmdletsCommand) ?? RunScript<FunctionInfo>(getCmdletsCommand);
        }
```

I do not see the issue in `pwsh 7`.  Could it be an issue of `vscode-powershell`?
