### ISSUE TITLE
Az.RecoveryService 6.6.x Set-AzRecoveryServicesVaultProperty : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by invisibleninja06** [Azure/azure-powershell#23627]
### Description

When trying to use Set-AzRecoveryServicesVaultProperty with any 6.6.x version of Az.RecoveryServices im getting Object reference not set to an instance of an object. I tested both 6.6.0 and 6.6.1 just to be sure 6.6.0 was the version it first started in.

Downgrading to Az.RecoveryService 6.5.x results in a successful execution.

Tried on two distinct machines with same results.
One machine is brand new freshly setup box.

![image](https://github.com/Azure/azure-powershell/assets/56641995/dd026199-e770-41f5-98af-7ef7dba75492)

### Issue script & Debug output

```PowerShell
PS C:\Users\1Valet> $DebugPreference = "Continue"
PS C:\Windows\System32> $RecoveryVault = Get-AzRecoveryServicesVault -ResourceGroupName redacted -Name redacted
PS C:\Users\1Valet> Set-AzRecoveryServicesVaultProperty -VaultId "$($RecoveryVault.ID)" -DisableHybridBackupSecurityFeature $true

## Debug output

DEBUG: 12:39:31 PM - SetAzureRmRecoveryServicesVaultProperty begin processing with ParameterSet 'AzureRSVaultSoftDelteParameterSet'.
DEBUG: 12:39:31 PM - using account id 'redacted'...
DEBUG: 12:39:31 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: Inside Restore. Going to create ResourceClient.
DEBUG: [Common.Authentication]: Authenticating using Account: 'redacted', environment: 'AzureCloud', tenant: 'redacted'
DEBUG: 12:39:31 PM - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 12:39:31 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'redacted', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'redacted'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] MSAL MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(redacted)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - redacted
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] Access token is not expired. Returning the found cache entry. [Current time (11/30/2023 20:39:31) - Expiration Time (11/30/2023 21:35:55 +00:00) - Extended Expiration Time (11/30/2023 21:35:55 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted]
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted]  AT expiration time: 2023-11-30 9:35:55 PM +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-11-30T21:35:55.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'redacted', UserId: 'redacted'
DEBUG: Client Created successfully
DEBUG: [Common.Authentication]: Authenticating using Account: 'redacted', environment: 'AzureCloud', tenant: 'redacted'
DEBUG: 12:39:31 PM - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 12:39:31 PM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'redacted', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'redacted'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] MSAL MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(redacted)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - redacted
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] Access token is not expired. Returning the found cache entry. [Current time (11/30/2023 20:39:31) - Expiration Time (11/30/2023 21:35:55 +00:00) - Extended Expiration Time (11/30/2023 21:35:55 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted]
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Microsoft Windows 10.0.22000 [2023-11-30 20:39:31Z - redacted]  AT expiration time: 2023-11-30 9:35:55 PM +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2023-11-30T21:35:55.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'redacted', UserId: 'redacted'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
redacted

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : redacted

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
X-Content-Type-Options        : nosniff
x-ms-request-id               : redacted
x-ms-client-request-id        : redacted
x-ms-ratelimit-remaining-subscription-resource-requests: 149
x-ms-correlation-request-id   : redacted
x-ms-routing-request-id       : CANADACENTRAL:redacted
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Cache                       : CONFIG_NOCACHE
X-MSEdge-Ref                  : Ref A: redacted Ref B: redacted Ref C: 2023-11-30T20:39:19Z
Date                          : Thu, 30 Nov 2023 20:39:18 GMT

Body:
{
  "id": "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.RecoveryServices/vaults/redacted/backupconfig/vaultconfig",
  "name": "vaultconfig",
  "type": "Microsoft.RecoveryServices/vaults/backupconfig",
  "properties": {
    "enhancedSecurityState": "Disabled",
    "softDeleteFeatureState": "Enabled",
    "softDeleteRetentionPeriodInDays": 14,
    "isSoftDeleteFeatureStateEditable": true
  }
}


DEBUG: 12:39:32 PM - [ConfigManager] Got nothing from [DisableErrorRecordsPersistence], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 12:39:32 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Set-AzRecoveryServicesVaultProperty: Object reference not set to an instance of an object.
DEBUG: 12:39:32 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:39:32 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:39:32 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.RecoveryServices:6.6.0; CommandName: Set-AzRecoveryServicesVaultProperty; PSVersion: 7.4.0; IsSuccess: False; Duration: 00:00:00.2866282; Exception: Object reference not set to an instance of an object.;
DEBUG: 12:39:32 PM - SetAzureRmRecoveryServicesVaultProperty end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.6.0                 Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Backup-AzRecoveryServicesBac…
```

### Error output

```PowerShell
PS C:\Windows\System32> Resolve-AzError

   HistoryId: 6

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.SetAzureRmRecoveryServicesVaultProperty.<ExecuteCmdlet>b__16_0()
Exception      : System.NullReferenceException
InvocationInfo : {Set-AzRecoveryServicesVaultProperty}
Line           : Set-AzRecoveryServicesVaultProperty -VaultId "$($RecoveryVault.ID)" -DisableHybridBackupSecurityFeature $true
Position       : At line:1 char:1
                 + Set-AzRecoveryServicesVaultProperty -VaultId "$($RecoveryVault.ID)" - …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6


   HistoryId: 2

Message        : Cannot validate argument on parameter 'VaultId'. The argument is null or empty. Provide an argument that is not null or empty, and then
                 try the command again.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter
                 parameterMetadata, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument,
                 MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal
                 argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal
                 argument, MergedCompiledCommandParameter parameter)
                    at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][]
                 pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Set-AzRecoveryServicesVaultProperty}
Line           : Set-AzRecoveryServicesVaultProperty -VaultId "$($RecoveryVault.ID)" -DisableHybridBackupSecurityFeature $true
Position       : At line:1 char:46
                 + … RecoveryServicesVaultProperty -VaultId "$($RecoveryVault.ID)" -Disabl …
                 +                                          ~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ValidateNotNullOrAttributeBase.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter
                 parameterMetadata, ParameterBindingFlags flags)
Exception      : System.Management.Automation.ValidationMetadataException
InvocationInfo : {Set-AzRecoveryServicesVaultProperty}
Line           : Set-AzRecoveryServicesVaultProperty -VaultId "$($RecoveryVault.ID)" -DisableHybridBackupSecurityFeature $true
Position       : At line:1 char:46
                 + … RecoveryServicesVaultProperty -VaultId "$($RecoveryVault.ID)" -Disabl …
                 +                                          ~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2
```

**Comment by ScottMonolith** [comment]
Just wanted to update this open issue, I have the same problem on 6.7.0 of Az.RecoveryServices.  I was able to downgrade to 6.5.0 and complete the task.

Note - this Set-AzRecoveryServicesVaultProperty cmdlet is required to use the PoSH script provided within Azure to delete a recovery services vault.

**Comment by Daya-Patil** [comment]
@hiaga could you please check

**Comment by hiaga** [comment]
Ack, looking into this

**Comment by hiaga** [comment]
Identified the issue, will be fixed in upcoming release. ETA - 05th March

**Comment by hiaga** [comment]
closing this. pls reopen if the issue persists after next release.

**Comment by efd7887** [comment]
Ah, more genius by Microsoft developers.  Provide a script to remove an RSV but fail to provide a working command....required to delete an RSV.  The fact that there is even a GH issue section about the Az PS modules should tell you a lot about the competency of the people who develop said "tool".  This is laughable.  You all may want to find a set of developers who are getting it right and look over their shoulders.  Might do you good

**Comment by WillyMoselhy** [comment]
I am facing the same issue on 7.11.1

```
Resolve-AzError 

   HistoryId: 14

Message        : Operation failed.
                 ClientRequestId: bef96343-b6dd-468e-a3c2-4e058ab2af6e-2026-02-11 15:43:39Z-Ps
                 Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.HandleException(Exception ex)
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Exception
InvocationInfo : {Set-AzRecoveryServicesAsrVaultContext}
Line           : Set-AzRecoveryServicesAsrVaultContext -Vault $VaultToDelete -Debug
Position       : At line:1 char:1
                 + Set-AzRecoveryServicesAsrVaultContext -Vault $VaultToDelete -Debug
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 14

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SetAzureRmRecoveryServicesAsrVaultSettings.SetARSVaultContext(ARSVault arsVault)
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SetAzureRmRecoveryServicesAsrVaultSettings.ExecuteSiteRecoveryCmdlet()
                    at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
Exception      : System.NullReferenceException
InvocationInfo : {Set-AzRecoveryServicesAsrVaultContext}
Line           : Set-AzRecoveryServicesAsrVaultContext -Vault $VaultToDelete -Debug
Position       : At line:1 char:1
                 + Set-AzRecoveryServicesAsrVaultContext -Vault $VaultToDelete -Debug
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 14
```

**Comment by hiaga** [comment]
please reopen a new issue for this command Set-AzRecoveryServicesAsrVaultContext. original issue was for a different cmdlet
