### ISSUE TITLE
New-AzBatchApplicationPackage doesn't upload new package if application doesn't allow updates

### ISSUE THREAD

**Issue by manio143** [Azure/azure-powershell#23809]
### Description

I was looking at automating creating application packages for Azure Batch using powershell.
The file was not being uploaded and I was getting error that `The package already exists and the application does not allow existing packages to be updated.`
This is not expected because I am able to create new packages with the same configuration of the application through Azure Portal. I imagine either there is an alternate way to create a new package or the update is allowed while package is in the `Pending` state after uploading the file.

I see that the package version I am using is a bit old (constrained SAW environment), feel free to close if this has already been addressed since.

### Issue script & Debug output

```PowerShell
PS> New-AzBatchApplicationPackage -AccountName usertestbatch -ResourceGroupName user-test-december -ApplicationName rewards -ApplicationVersion 1.0.5-test4 -FilePath file.zip -Format zip -Verbose -Debug

DEBUG: 3:33:23 PM - NewBatchApplicationPackageCommand begin processing with ParameterSet 'UploadAndActivate'.
DEBUG: 3:33:33 PM - using account id 'user_jit@<tenant>'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'user_jit@<tenant>', environment:
'AzureCloud', tenant: '<tenant>'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'<tenant>', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority
'https://login.microsoftonline.com/<tenant>/', CorrelationId:
'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain:
'<tenant>', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: ADAL
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: ADAL
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: ===
Token Acquisition started:
 CacheType: null
 Authentication Target: User
 , Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: ===
Token Acquisition started:
 Authority: https://login.microsoftonline.com/<tenant>/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User
DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: Loading
from cache.
DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: Loading
from cache.
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs:
Deserialized 1 items to token cache.
DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: Looking up
cache for a token...
DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: Looking up
cache for a token...
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: An item
 matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: An item
 matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs:
10.88012414 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs:
10.88012414 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: A
matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: A
matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: ===
Token Acquisition finished successfully. An access token was returned: Expiration Time: 12/21/2023 3:44:30 PM +00:00
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 647362a8-da90-4c63-a33b-5585cdb2d8c9 - LoggerBase.cs: ===
Token Acquisition finished successfully. An access token was returned: Expiration Time: 12/21/2023 3:44:30 PM
+00:00Access Token Hash: =======
  User id: ####
DEBUG: [Common.Authentication]: Authenticating using Account: 'user_jit@<tenant>', environment:
'AzureCloud', tenant: '<tenant>'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'<tenant>', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority
'https://login.microsoftonline.com/<tenant>/', CorrelationId:
'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain:
'<tenant>', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: ADAL
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: ADAL
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: ===
Token Acquisition started:
 CacheType: null
 Authentication Target: User
 , Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: ===
Token Acquisition started:
 Authority: https://login.microsoftonline.com/<tenant>/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: Loading
from cache.
DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: Loading
from cache.
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs:
Deserialized 1 items to token cache.
DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: Looking up
cache for a token...
DEBUG: [ADAL]: Verbose: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: Looking up
cache for a token...
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: An item
 matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: An item
 matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs:
10.88012414 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs:
10.88012414 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: A
matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: A
matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: ===
Token Acquisition finished successfully. An access token was returned: Expiration Time: 12/21/2023 3:44:30 PM +00:00
DEBUG: [ADAL]: Information: 2023-12-21T15:33:37.4195516Z: ba3d3f9a-3835-4328-9fce-cf77d01cd35d - LoggerBase.cs: ===
Token Acquisition finished successfully. An access token was returned: Expiration Time: 12/21/2023 3:44:30 PM
+00:00Access Token Hash: =======
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/21/2023 15:44:30 +00:00',
MultipleResource? 'True', Tenant: '<tenant>', UserId:
'user_jit@<tenant>'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'user_jit@<tenant>', Name:  ,
IdProvider: 'https://sts.windows.net/<tenant>/', Uid:
'#####'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/21/2023 15:44:30 +00:00' Comparing to
'12/21/2023 15:33:37 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:10:52.8074484'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<subscription>/resourceGroups/user-test-december/p
roviders/Microsoft.Batch/batchAccounts/usertestbatch/applications/rewards/versions/1.0.5-test4?api-version=2019-08-
01

Headers:
x-ms-client-request-id        : efffe53a-2ee5-41a5-9ba1-3f24c0486871
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11997
x-ms-request-id               : b6d97f76-ffec-45e0-9d5a-ac1d973534e7
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
x-ms-correlation-request-id   : 964751ed-7bd6-4943-9efe-55415064291f
x-ms-routing-request-id       : NORTHEUROPE:20231221T153337Z:964751ed-7bd6-4943-9efe-55415064291f
Cache-Control                 : no-cache
Date                          : Thu, 21 Dec 2023 15:33:37 GMT
Server                        : Kestrel

Body:
{
  "error": {
    "code": "ApplicationPackageNotFound",
    "message": "The specified application package does not
exist.\nRequestId:b6d97f76-ffec-45e0-9d5a-ac1d973534e7\nTime:2023-12-21T15:33:37.8932957Z",
    "target": "BatchAccount"
  }
}

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/21/2023 15:44:30 +00:00',
MultipleResource? 'True', Tenant: '<tenant>', UserId:
'user_jit@<tenant>'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'user_jit@<tenant>', Name:  ,
IdProvider: 'https://sts.windows.net/<tenant>/', Uid:
'####'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/21/2023 15:44:30 +00:00' Comparing to
'12/21/2023 15:33:37 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:10:52.2998679'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/<subscription>/resourceGroups/user-test-december/p
roviders/Microsoft.Batch/batchAccounts/usertestbatch/applications/rewards/versions/1.0.5-test4?api-version=2019-08-
01

Headers:
x-ms-client-request-id        : 83a50d4f-a733-48ed-98cd-8896807705f3
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 1c8e0de5-3e4c-4cab-93d4-fcc59504ed72
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 83a20920-5565-425c-a642-22b7f0f0990e
x-ms-routing-request-id       : NORTHEUROPE:20231221T153338Z:83a20920-5565-425c-a642-22b7f0f0990e
Cache-Control                 : no-cache
Date                          : Thu, 21 Dec 2023 15:33:37 GMT
ETag                          : W/"0x8DC023A33EC3602"
Server                        : Kestrel

Body:
{
  "type": "Microsoft.Batch/batchAccounts/applications/versions",
  "id":
"/subscriptions/<subscription>/resourceGroups/user-test-december/providers/Microsoft.Batch/ba
tchAccounts/usertestbatch/applications/rewards/versions/1.0.5-test4",
  "name": "1.0.5-test4",
  "etag": "W/\"0x8DC023A33EC3602\"",
  "properties": {
    "storageUrl":
"<SAS>",
    "storageUrlExpiry": "2023-12-21T19:33:38.2690724Z",
    "state": "Pending"
  }
}

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '12/21/2023 15:44:30 +00:00',
MultipleResource? 'True', Tenant: '<tenant>', UserId:
'user_jit@<tenant>'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'user_jit@<tenant>', Name:  ,
IdProvider: 'https://sts.windows.net/<tenant>/', Uid:
'####'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '12/21/2023 15:44:30 +00:00' Comparing to
'12/21/2023 15:33:38 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:10:51.9058248'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/<subscription>/resourceGroups/user-test-december/p
roviders/Microsoft.Batch/batchAccounts/usertestbatch/applications/rewards?api-version=2019-08-01

Headers:
x-ms-client-request-id        : 94e2ff69-ad7f-4053-9a19-18255e3da40c
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : f5cf43bf-cd75-40fc-80fe-9fdd3f8a17c5
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
x-ms-ratelimit-remaining-subscription-reads: 11996
x-ms-correlation-request-id   : bcc09ade-30c3-4c8f-9996-d62589be057d
x-ms-routing-request-id       : NORTHEUROPE:20231221T153338Z:bcc09ade-30c3-4c8f-9996-d62589be057d
Cache-Control                 : no-cache
Date                          : Thu, 21 Dec 2023 15:33:38 GMT
ETag                          : W/"0x8DC016B3C1B2237"
Server                        : Kestrel

Body:
{
  "type": "Microsoft.Batch/batchAccounts/applications",
  "id":
"/subscriptions/<subscription>/resourceGroups/user-test-december/providers/Microsoft.Batch/ba
tchAccounts/usertestbatch/applications/rewards",
  "name": "rewards",
  "etag": "W/\"0x8DC016B3C1B2237\"",
  "properties": {
    "displayName": "rewards",
    "allowUpdates": false
  }
}


New-AzBatchApplicationPackage : Failed to create application package rewards version 1.0.5-test4. The package already
exists, and the application does not allow existing packages to be updated. You must upload your package using a new
version number.
At line:1 char:1
+ New-AzBatchApplicationPackage -AccountName usertestbatch -Resourc ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzBatchApplicationPackage], NewApplicationPackageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Batch.NewBatchApplicationPackageCommand

DEBUG: AzureQoSEvent: CommandName - New-AzBatchApplicationPackage; IsSuccess - False; Duration - 00:02:24.2762387;
Exception - Microsoft.Azure.Commands.Batch.NewApplicationPackageException: Failed to create application package rewards
 version 1.0.5-test4. The package already exists, and the application does not allow existing packages to be updated.
You must upload your package using a new version number.
   at Microsoft.Azure.Commands.Batch.Models.BatchClient.CheckApplicationAllowsUpdates(String resourceGroupName, String
accountName, String applicationName, String version)
   at Microsoft.Azure.Commands.Batch.Models.BatchClient.UploadAndActivateApplicationPackage(String resourceGroupName,
String accountName, String applicationName, String version, String filePath, String format, Boolean activateOnly)
   at Microsoft.Azure.Commands.Batch.NewBatchApplicationPackageCommand.ExecuteCmdletImpl()
   at Microsoft.Azure.Commands.Batch.BatchCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 3:35:48 PM - NewBatchApplicationPackageCommand end processing.
DEBUG: 3:35:48 PM - NewBatchApplicationPackageCommand end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name
---------- -------    ----
Script     1.7.1      Az.Accounts
Script     2.0.2      Az.Batch
```

**Comment by isra-fel** [comment]
Thanks for reporting. Let me loop in the batch team.
