### ISSUE TITLE
New-AzPrivateEndpoint returns error, debug shows resource I'm creating not found?

### ISSUE THREAD

**Issue by stan-spotts** [Azure/azure-powershell#24015]
### Description

I'm trying to add a private endpoint to a Static Web App (yeah, just find docs on this one) and I tried adding a new private link service connection, then a private endpoint. The private endpoint creation fails.

### Issue script & Debug output

```PowerShell
$location = "eastus"
$swalocation = "eastus2"
$appSubnetData = $vnet.Subnets[$vnet.Subnets.IndexOf($($vnet.Subnets.Where{$_.Name -eq "$appsubnetName" }))]

$webApp = New-AzStaticWebApp `
  -ResourceGroupName $resGroupName `
  -Name $appname `
  -Location $swaLocation `
  -RepositoryUrl $githubRepo `
  -RepositoryToken $githubAccessToken `
  -Branch $branch `
  -AppLocation "/" `
  -ApiLocation "" `
  -OutputLocation "dist" `
  -AppBuildCommand "npm build run" `
  -SkuName 'Standard'
  
$appResourceId = $webApp.Id
# Create a private link service connection
$privateLinkServiceConnection = New-AzPrivateLinkServiceConnection `
  -Name "$($appName)Connection" -PrivateLinkServiceId $appResourceId -GroupId "staticSites"
$appSubnetData.PrivateEndpointNetworkPolicies = "Disabled"
$vnet | Set-AzVirtualNetwork

# Add private endpoint
$privateEndpoint = New-AzPrivateEndpoint -ResourceGroupName $resGroupName `
  -Name $appPrivateEndpointName -Location $location -Subnet $appSubnet `
  -PrivateLinkServiceConnection $privateLinkServiceConnection

DEBUG: 1:18:57 AM - NewAzurePrivateEndpoint begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 1:19:02 AM - using account id 'sspotts@cgfns.org'...
DEBUG: 1:19:02 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'sspotts@cgfns.org', environment: 'AzureCloud', tenant:
'29156038-3a23-47f6-810b-e1476fa8855c'
DEBUG: 1:19:02 AM - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync -
TenantId:'29156038-3a23-47f6-810b-e1476fa8855c', Scopes:'https://management.core.windows.net//.default',
AuthorityHost:'https://login.microsoftonline.com/', UserId:'sspotts@cgfns.org'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
7f101756-50b1-4d13-80da-3fe3f405863c] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
7f101756-50b1-4d13-80da-3fe3f405863c] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
7f101756-50b1-4d13-80da-3fe3f405863c] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
7f101756-50b1-4d13-80da-3fe3f405863c] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
7f101756-50b1-4d13-80da-3fe3f405863c] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z] [WamBroker] WAM
supported OS.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z] [WamBroker]
ListWindowsWorkAndSchoolAccounts option was not enabled.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
6c516af2-a4b6-4e43-a371-84b973d58479] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z] Found 1 cache
accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] MSAL MSAL.Desktop with assembly version '4.49.1.0'.
CorrelationId(0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee)
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - True
HomeAccountId - False
CorrelationId - 0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] === Token Acquisition (SilentRequest) started:
  Scopes: https://management.core.windows.net//.default
 Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] Access token is not expired. Returning the found cache entry. [Current time
(01/22/2024 06:19:02) - Expiration Time (01/22/2024 07:23:30 +00:00) - Extended Expiration Time (01/22/2024 07:23:30
+00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee]
 === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.Desktop 4.8 or later Windows 10 Enterprise [2024-01-22 06:19:02Z -
0ed0a8bb-4cf7-4510-b072-f99ccfd8c3ee]  AT expiration time: 1/22/2024 7:23:30 AM +00:00, scopes:
https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ]
ParentRequestId:  ExpiresOn: 2024-01-22T07:23:30.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '29156038-3a23-47f6-810b-e1476fa8855c',
UserId: 'sspotts@cgfns.org'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/gpvault-rg/providers/Mic
rosoft.Network/privateEndpoints/app-private-ip?api-version=2022-07-01

Headers:
x-ms-client-request-id        : fe75fc45-e3c8-4b23-adaf-3f6b11a8f35a
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : e98dddc2-c13c-4874-9a03-d413b2e9a424
x-ms-correlation-request-id   : e98dddc2-c13c-4874-9a03-d413b2e9a424
x-ms-routing-request-id       : EASTUS2:20240122T061902Z:xxxxxxx-xxxxxx-xxxxxx-xxxxxxxxxxxxxx
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 22 Jan 2024 06:19:01 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Network/privateEndpoints/app-private-ip' under resource group 'gpvault-rg' was
not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
  }
}

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/gpvault-rg/providers/Mic
rosoft.Network/privateEndpoints/app-private-ip?api-version=2022-07-01

Headers:
x-ms-client-request-id        : fe75fc45-e3c8-4b23-adaf-3f6b11a8f35a
accept-language               : en-US

Body:
{
  "properties": {
    "subnet": {
      "properties": {
        "addressPrefix": "10.0.3.0/24",
        "addressPrefixes": [],
        "serviceEndpoints": [],
        "serviceEndpointPolicies": [],
        "ipAllocations": [],
        "delegations": [],
        "privateEndpointNetworkPolicies": "Disabled",
        "privateLinkServiceNetworkPolicies": "Enabled",
        "applicationGatewayIpConfigurations": []
      },
      "name": "appsubnet"
    },
    "privateLinkServiceConnections": [
      {
        "properties": {
          "privateLinkServiceId":
"/subscriptions/57e97795-534c-432f-abf5-7a50d0597124/resourceGroups/gpvault-rg/providers/Microsoft.Web/staticSites/gpva
ult",
          "groupIds": [
            "staticSites"
          ]
        },
        "name": "gpvaultConnection"
      }
    ],
    "manualPrivateLinkServiceConnections": [],
    "customDnsConfigs": [],
    "applicationSecurityGroups": [],
    "ipConfigurations": []
  },
  "location": "EastUS"
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : ca30b4a0-2038-4644-a6fc-47a6d067c585
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : baf07d9e-2e34-418d-a8cc-2c5c562dbfa5
x-ms-routing-request-id       : EASTUS2:20240122T061904Z:baf07d9e-2e34-418d-a8cc-2c5c562dbfa5
X-Content-Type-Options        : nosniff
Date                          : Mon, 22 Jan 2024 06:19:03 GMT

Body:
{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.subnet."
      }
    ]
  }
}

DEBUG: 1:19:04 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning
default value [True].

Confirm
Operation returned an invalid status code 'BadRequest'
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidRequestFormat
ErrorMessage: Cannot parse the request.
New-AzPrivateEndpoint : Operation returned an invalid status code 'BadRequest'
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidRequestFormat
ErrorMessage: Cannot parse the request.
At line:1 char:20
+ ... teEndpoint = New-AzPrivateEndpoint -ResourceGroupName $resGroupName `
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzPrivateEndpoint], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzurePrivateEndpoint

DEBUG: 1:19:06 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = [].
Returning default value [True].
DEBUG: AzureQoSEvent:  Module: az.network:5.3.0; CommandName: New-AzPrivateEndpoint; PSVersion: 5.1.19041.3930;
IsSuccess: False; Duration: 00:00:07.1771369; Exception: Operation returned an invalid status code 'BadRequest'
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: InvalidRequestFormat
ErrorMessage: Cannot parse the request.;
DEBUG: 1:19:06 AM - NewAzurePrivateEndpoint end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.19041.3930
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.3930
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     9.3.0      az
Script     2.11.1     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear...
Script     2.0.0      Az.Advisor                          {Disable-AzAdvisorRecommendation, Enable-AzAdvisorRecommen...
Script     5.2.0      Az.Aks                              {Disable-AzAksAddOn, Enable-AzAksAddOn, Get-AzAksCluster, ...
Script     1.1.4      Az.AnalysisServices                 {Add-AzAnalysisServicesAccount, Export-AzAnalysisServicesI...
Script     4.0.2      Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiTo...
Script     1.2.0      Az.AppConfiguration                 {Clear-AzAppConfigurationDeletedStore, Get-AzAppConfigurat...
Script     2.2.1      Az.ApplicationInsights              {Get-AzApplicationInsights, Get-AzApplicationInsightsApiKe...
Script     2.0.0      Az.Attestation                      {Add-AzAttestationPolicySigner, Get-AzAttestationPolicy, G...
Script     1.9.0      Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationD...
Script     3.3.0      Az.Batch                            {Disable-AzBatchAutoScale, Disable-AzBatchComputeNodeSched...
Script     2.0.0      Az.Billing                          {Get-AzBillingAccount, Get-AzBillingInvoice, Get-AzBilling...
Script     2.1.0      Az.Cdn                              {Clear-AzCdnEndpointContent, Clear-AzFrontDoorCdnEndpointC...
Script     1.1.0      Az.CloudService                     {Get-AzCloudService, Get-AzCloudServiceInstanceView, Get-A...
Script     1.12.0     Az.CognitiveServices                {Add-AzCognitiveServicesAccountNetworkRule, Get-AzCognitiv...
Script     5.3.0      Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnatten...
Script     1.0.0      Az.ConfidentialLedger               {Get-AzConfidentialLedger, New-AzConfidentialLedger, New-A...
Script     3.1.0      Az.ContainerInstance                {Add-AzContainerInstanceOutput, Get-AzContainerGroup, Get-...
Script     3.0.1      Az.ContainerRegistry                {Connect-AzContainerRegistry, Get-AzContainerRegistry, Get...
Script     1.9.0      Az.CosmosDB                         {Get-AzCosmosDBAccount, Get-AzCosmosDBAccountKey, Get-AzCo...
Script     1.1.0      Az.DataBoxEdge                      {Get-AzDataBoxEdgeBandwidthSchedule, Get-AzDataBoxEdgeDevi...
Script     1.4.0      Az.Databricks                       {Get-AzDatabricksAccessConnector, Get-AzDatabricksOutbound...
Script     1.16.11    Az.DataFactory                      {Add-AzDataFactoryV2DataFlowDebugSessionPackage, Add-AzDat...
Script     1.0.2      Az.DataLakeAnalytics                {Add-AzDataLakeAnalyticsDataSource, Add-AzDataLakeAnalytic...
Script     1.3.0      Az.DataLakeStore                    {Add-AzDataLakeStoreFirewallRule, Add-AzDataLakeStoreItemC...
Script     1.0.1      Az.DataProtection                   {Backup-AzDataProtectionBackupInstanceAdhoc, Edit-AzDataPr...
Script     1.0.1      Az.DataShare                        {Get-AzDataShare, Get-AzDataShareAccount, Get-AzDataShareD...
Script     1.1.0      Az.DeploymentManager                {Get-AzDeploymentManagerArtifactSource, Get-AzDeploymentMa...
Script     3.1.1      Az.DesktopVirtualization            {Disconnect-AzWvdUserSession, Expand-AzWvdMsixImage, Get-A...
Script     1.0.2      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolic...
Script     1.1.2      Az.Dns                              {Add-AzDnsRecordConfig, Get-AzDnsRecordSet, Get-AzDnsZone,...
Script     1.5.0      Az.EventGrid                        {Enable-AzEventGridPartnerTopic, Get-AzEventGridChannel, G...
Script     3.2.0      Az.EventHub                         {Add-AzEventHubIPRule, Add-AzEventHubVirtualNetworkRule, G...
Script     1.9.0      Az.FrontDoor                        {Disable-AzFrontDoorCustomDomainHttps, Enable-AzFrontDoorC...
Script     4.0.6      Az.Functions                        {Get-AzFunctionApp, Get-AzFunctionAppAvailableLocation, Ge...
Script     5.0.1      Az.HDInsight                        {Add-AzHDInsightClusterIdentity, Add-AzHDInsightComponentV...
Script     2.0.0      Az.HealthcareApis                   {Get-AzHealthcareApisService, Get-AzHealthcareApisWorkspac...
Script     2.7.4      Az.IotHub                           {Add-AzIotHubCertificate, Add-AzIotHubConfiguration, Add-A...
Script     4.9.1      Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateConta...
Script     2.1.0      Az.Kusto                            {Add-AzKustoClusterLanguageExtension, Add-AzKustoDatabaseP...
Script     1.5.0      Az.LogicApp                         {Get-AzIntegrationAccount, Get-AzIntegrationAccountAgreeme...
Script     1.1.3      Az.MachineLearning                  {Add-AzMlWebServiceRegionalProperty, Export-AzMlWebService...
Script     1.2.1      Az.Maintenance                      {Get-AzApplyUpdate, Get-AzConfigurationAssignment, Get-AzM...
Script     1.1.0      Az.ManagedServiceIdentity           {Get-AzFederatedIdentityCredentials, Get-AzSystemAssignedI...
Script     3.0.0      Az.ManagedServices                  {Get-AzManagedServicesAssignment, Get-AzManagedServicesDef...
Script     2.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Invoke-AzMarketplaceSignTerms, Se...
Script     1.1.1      Az.Media                            {Get-AzMediaService, Get-AzMediaServiceKey, Get-AzMediaSer...
Script     2.1.0      Az.Migrate                          {Get-AzMigrateDiscoveredServer, Get-AzMigrateJob, Get-AzMi...
Script     4.4.0      Az.Monitor                          {Add-AzLogProfile, Add-AzMetricAlertRule, Add-AzMetricAler...
Script     1.1.0      Az.MySql                            {Get-AzMySqlConfiguration, Get-AzMySqlConnectionString, Ge...
Script     5.3.0      az.network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-Az...
Script     1.1.1      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorization...
Script     3.2.0      Az.OperationalInsights              {Disable-AzOperationalInsightsIISLogCollection, Disable-Az...
Script     1.5.1      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyMetadata, Get-AzPolicyReme...
Script     1.1.0      Az.PostgreSql                       {Get-AzPostgreSqlConfiguration, Get-AzPostgreSqlConnection...
Script     1.2.0      Az.PowerBIEmbedded                  {Get-AzPowerBIEmbeddedCapacity, Get-AzPowerBIWorkspace, Ge...
Script     1.0.3      Az.PrivateDns                       {Add-AzPrivateDnsRecordConfig, Get-AzPrivateDnsRecordSet, ...
Script     6.1.2      Az.RecoveryServices                 {Add-AzRecoveryServicesAsrReplicationProtectedItemDisk, Ba...
Script     1.7.0      Az.RedisCache                       {Export-AzRedisCache, Get-AzRedisCache, Get-AzRedisCacheFi...
Script     1.1.0      Az.RedisEnterpriseCache             {Export-AzRedisEnterpriseCache, Get-AzRedisEnterpriseCache...
Script     1.0.3      Az.Relay                            {Get-AzRelayAuthorizationRule, Get-AzRelayHybridConnection...
Script     1.1.0      Az.ResourceMover                    {Add-AzResourceMoverMoveResource, Get-AzResourceMoverMoveC...
Script     6.5.1      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDeny...
Script     1.3.0      Az.Security                         {Add-AzSecurityAdaptiveNetworkHardening, Add-AzSecuritySql...
Script     3.0.1      Az.SecurityInsights                 {Get-AzSentinelAlertRule, Get-AzSentinelAlertRuleAction, G...
Script     2.1.0      Az.ServiceBus                       {Add-AzServiceBusIPRule, Add-AzServiceBusVirtualNetworkRul...
Script     3.1.0      Az.ServiceFabric                    {Add-AzServiceFabricClientCertificate, Add-AzServiceFabric...
Script     1.5.0      Az.SignalR                          {Get-AzSignalR, Get-AzSignalRKey, Get-AzSignalRUsage, New-...
Script     4.2.0      Az.Sql                              {Add-AzSqlDatabaseToFailoverGroup, Add-AzSqlElasticJobStep...
Script     1.1.0      Az.SqlVirtualMachine                {Get-AzAvailabilityGroupListener, Get-AzSqlVM, Get-AzSqlVM...
Script     1.4.1      Az.StackHCI                         {Add-AzStackHCIVMAttestation, Disable-AzStackHCIAttestatio...
Script     5.3.0      Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountMa...
Script     1.7.0      Az.StorageSync                      {Get-AzStorageSyncCloudEndpoint, Get-AzStorageSyncGroup, G...
Script     2.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsCluster, Get-AzStreamAnalyticsCluste...
Script     1.0.0      Az.Support                          {Get-AzSupportProblemClassification, Get-AzSupportService,...
Script     2.2.0      Az.Synapse                          {Add-AzSynapseDataFlowDebugSessionPackage, Add-AzSynapseTr...
Script     1.1.0      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Add-AzTraffic...
Script     2.12.1     Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRou...
```

### Error output

```PowerShell
HistoryId: 774


RequestId      :
Message        : Operation returned an invalid status code 'BadRequest'
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 ErrorCode: InvalidRequestFormat
                 ErrorMessage: Cannot parse the request.
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {New-AzPrivateEndpoint}
Line           : $privateEndpoint = New-AzPrivateEndpoint -ResourceGroupName $resGroupName -Name
                 $appPrivateEndpointName -Location $location -Subnet $appSubnet -PrivateLinkServiceConnection
                 $privateLinkServiceConnection
Position       : At line:1 char:20
                 + ... eEndpoint = New-AzPrivateEndpoint -ResourceGroupName $resGroupName -N ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 774
```

**Comment by CGFNSOrg** [comment]
> @stan-spotts at a glance
> 
> ```powershell
> $privateEndpoint = New-AzPrivateEndpoint -ResourceGroupName $resGroupName `
>   -Name $appPrivateEndpointName -Location $location -Subnet $appSubnet ` # <--- $appSubnet is not defined
>   -PrivateLinkServiceConnection $privateLinkServiceConnection
> ```
Thanks, but It was defined, I just did not supply it in the issue:

$appsubnetName = "appsubnet"
$appSubnet = New-AzVirtualNetworkSubnetConfig -Name $appsubnetName -AddressPrefix "10.0.3.0/24"

**Comment by stan-spotts** [comment]
@isra-fel sorry, just realized I was logged in with another account (cgfnsorg) when I responded.

**Comment by stan-spotts** [comment]
@isra-fel this is marked as completed now, but doesn't say why. Was it a bug that was fixed, or is it completed because I responded from a different account and my response wasn't accepted?

**Comment by stan-spotts** [comment]
@isra-fel Seriously, I responded but with another account, and then came back and said this. This issue is still an issue.

FWIW, I've tried every example I can find to create a private endpoint for an Azure Static Web App in a subnet that I can find, and no combination seems to work. If there isn't a bug here, what's the trick?   Not an App Service, but a Static Web App.

**Comment by DereMann** [comment]
To me, the exact same error happened because my subnet's Id has not been set properly due to the structure of my script. I needed to reload my vnet and according subnet into the local variables from Azure

`$vnet = Get-AzVirtualNetwork -Name $vnetName -ResourceGroupName $resourceGroupName
$subnet = $vnet | select -ExpandProperty subnets | Where-Object {$_.Name -eq $subnetName}`

this made it work for me
