### ISSUE TITLE
"Grant-AzSnapshotAccess" fails with "Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX."

### ISSUE THREAD

**Issue by riccom76** [Azure/azure-powershell#24129]
### Description

CLI cmdlet "Grant-AzSnapshotAccess", using APIs equal or later than 2023-01-02, fails with "Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX".

<table><td>
PS>  $AzSnapshotAccess = @{
ResourceGroupName = $rgName
SnapshotName            = $snapshotName
Access                        = 'Read'
DurationInSecond  = 3600
}

PS> Grant-AzSnapshotAccess @AzSnapshotAccess
Grant-AzSnapshotAccess: Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX.
ErrorCode: BadRequest
ErrorMessage: Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX.
ErrorTarget: 
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 12d9211a-5723-4bfe-a02c-d7fe6f4a2748
<td></table>

When trying to pass the "fileFormat" as parameter for CMDLets, an error is returned saying the 'fileFormat' isn't valid.

<table><td>
PS> $AzSnapshotAccess = @{
>> ResourceGroupName = $rgName
>> SnapshotName            = $snapshotName
>> Access                        = 'Read'
>> DurationInSecond  = 3600 
>> fileFormat = 'VHDX'}

----                           -----
PS> $azSnapshotAccess                       

Name                           Value

fileFormat                     VHDX
Access                         Read
DurationInSecond               3600
SnapshotName                   $rgName
ResourceGroupName              $snapshotName

----                           -----
PS> Grant-AzSnapshotAccess @AzSnapshotAccess
Grant-AzSnapshotAccess: A parameter cannot be found that matches parameter name 'fileFormat'.
<td></table>

Tested with RESTAPI --> [Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&tabs=HTTP)
The supported api-versions are '2016-04-30-preview, 2017-03-30, 2018-04-01, 2018-06-01, 2018-09-30, 2019-03-01, 2019-07-01, 2019-11-01, 2020-05-01, 2020-06-30, 2020-09-30, 2020-12-01, 2021-04-01, 2021-08-01, 2021-12-01, 2022-03-02, 2022-07-02, 2023-01-02, 2023-04-02, 2023-10-02'

<html>
<body>
<ul style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 14.6667px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li style="box-sizing: border-box; font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);"><span style="box-sizing: border-box; background-color: rgb(0, 255, 0);">SUCCESS:</span><span> </span>I've tried it again with the RestAPI by specifying with the fileFormat set to VHDX in the body and it works with the latest API version<span> </span><span style="box-sizing: border-box; background-color: rgb(255, 255, 0); display: inline !important;">2023-10-02 </span>as well: <a href="https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&amp;tabs=HTTP" target="_blank" style="box-sizing: border-box; color: var(--icm-primary-color, #0078d4); text-decoration: none; cursor: pointer;">Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn</a></li><li style="box-sizing: border-box; font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 11pt; color: rgb(0, 0, 0);">
{access: "Read",durationInSeconds: "3600",fileFormat: "VHDX"}
--
</li></ul>

"Grant-AzSnapshotAccess", using APIs equal or later than 2023-01-02, do not offer any parameter to define the "fileFormat".

RestAPI [Snapshots - Grant Access - REST API (Azure Compute) | Microsoft Learn](https://learn.microsoft.com/en-us/rest/api/compute/snapshots/grant-access?view=rest-compute-2023-10-02&tabs=HTTP) accepts the "fileFormat" as parameter. Azure "Grant-AzSnapshotAccess" cmdlet should do the same.

### Issue script & Debug output

```PowerShell
See above
```

### Environment data

```PowerShell
Run in Azure Portal CloudShell

PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             CBL-Mariner/Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Run in Azure Portal CloudShell

PS> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.15.0                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     7.1.1                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     7.3.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAdd…
Script     6.13.0                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…
Script     6.1.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-Az…
Script     1.1.3                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, Open-AzPredictorSurvey, Send-AzPredictorRati…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegis…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
Run in Azure Portal CloudShell


PS> Resolve-AzError

   HistoryId: 11

Message        : The term 'PSVersionTable' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, 
                 SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, 
                 CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] 
                 pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : PSVersionTable
Position       : At line:1 char:1
                 + PSVersionTable
                 + ~~~~~~~~~~~~~~
HistoryId      : 11


   HistoryId: 10

Message        : A parameter cannot be found that matches parameter name 'fileFormat'.
StackTrace     :    at System.Management.Automation.CmdletParameterBinderController.VerifyArgumentsProcessed(ParameterBindingException 
                 originalBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] 
                 pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {Grant-AzSnapshotAccess}
Line           : Grant-AzSnapshotAccess @AzSnapshotAccess
Position       : At line:1 char:24
                 + Grant-AzSnapshotAccess @AzSnapshotAccess
                 +                        ~~~~~~~~~~~~~~~~~
HistoryId      : 10


   HistoryId: 6

RequestId      : 
Message        : Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat property to VHDX.
                 ErrorCode: BadRequest
                 ErrorMessage: Accessing disk or snapshot with a logical sector size of 4096 requires specifying the file format. Set the fileFormat 
                 property to VHDX.
                 ErrorTarget: 
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 OperationID : 12d9211a-5723-4bfe-a02c-d7fe6f4a2748
ServerMessage  : 
ServerResponse : 
RequestMessage : 
InvocationInfo : {Grant-AzSnapshotAccess}
Line           : Grant-AzSnapshotAccess @AzSnapshotAccess
Position       : At line:1 char:1
                 + Grant-AzSnapshotAccess @AzSnapshotAccess
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.Automation.GrantAzureRmSnapshotAccess.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 6


   HistoryId: 3

Message        : The term 'martinme_repro' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, 
                 SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, 
                 CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] 
                 pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : ResourceGroupName = martinme_repro
                 
Position       : At line:2 char:21
                 + ResourceGroupName = martinme_repro
                 +                     ~~~~~~~~~~~~~~
HistoryId      : 3
```

**Comment by hilaryw29** [comment]
@ushnaarshadkhan Would you mind taking a look at this? Thanks!

**Comment by ushnaarshadkhan** [comment]
Thanks for the feedback! We are looking into this and will provide an update soon.

**Comment by AdamZLi** [comment]
Thanks for the feedback. I've created a backlog item to track the effort to enable fileFormat support for Grant-AzSnapshotAccess in PowerShell. We will share an ETA once resource is assigned to this ask.
