### ISSUE TITLE
Set-AzStorageFileContent fails with HTTP 403 Not Authorized

### ISSUE THREAD

**Issue by msetogecko** [Azure/azure-powershell#24143]
### Description

I am using an Entra Application Registration that has Contributor at the subscription level, which is applying to a storage account within that subscription via inheritance; and trying to upload a simple CSV file to a container within that storage account. I am appearing to set the context correctly, but when attempting to execute the Set-AzStorageBlobContent cmdlet to upload the file, it is resulting in an error: "Set-AzStorageBlobContent: This request is not authorized to perform this operation using this permission. HTTP Status Code: 403 - HTTP Error Message: This request is not authorized to perform this operation using this permission.
ErrorCode: AuthorizationPermissionMismatch"

I can confirm the firewall on the storage account is disabled.

### Issue script & Debug output

```PowerShell
$StorageContext = New-AzStorageContext -StorageAccountName 'my_storage_account_name'
$StorageContainer = Get-AzStorageContainer -Name "container-name" -Context $StorageContext
Set-AzStorageBlobContent -Container "container-name" -File .\CsvFile.csv -Blob 'CsvFile.csv' -Context $StorageContext -Force
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.0
PSEdition                      Core
GitCommitId                    7.4.0
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.13.2                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     1.9.1                 Az.Automation                       {Export-AzAutomationDscConfiguration, Export-AzAutomationDscNodeReportContent, Export-AzAutomationRunbook, Get-AzAutomationAccount…}
Script     7.0.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     6.12.0                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     6.0.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
```

### Error output

```PowerShell
Message        : This request is not authorized to perform this operation using this permission. HTTP Status Code: 403 - HTTP Error Message: This request is not authorized to perform this operation using this permission.
                 ErrorCode: AuthorizationPermissionMismatch
                 ErrorMessage: This request is not authorized to perform this operation using this permission.
                 RequestId:a9cfc7aa-201e-0054-25bd-5a0da9000000
                 Time:2024-02-08T18:34:39.0830195Z
StackTrace     : 
Exception      : Microsoft.Azure.Storage.StorageException
InvocationInfo : {Set-AzStorageBlobContent}
Line           : Set-AzStorageBlobContent -Container "container-name" -File .\CsvFile.csv -Blob 'CsvFile.csv' -Context $StorageContext -Force
Position       : At line:1 char:1
                 + Set-AzStorageBlobContent -Container "container-name" -File .\CsvFile …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 171

Message        : This request is not authorized to perform this operation using this permission.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Storage.Common.DataMovementTransferHelper.DoTransfer(Func`1 doTransfer, ProgressRecord record, TaskOutputStream outputStream)
                    at Microsoft.WindowsAzure.Commands.Storage.Blob.SetAzureBlobContentCommand.Upload2Blob(Int64 taskId, IStorageBlobManagement localChannel, String filePath, CloudBlob blob)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTask(Int64 taskId, Task task)
Exception      : Microsoft.Azure.Storage.StorageException
InvocationInfo : {Set-AzStorageBlobContent}
Line           : Set-AzStorageBlobContent -Container "container-name" -File .\CsvFile.csv -Blob 'CsvFile.csv' -Context $StorageContext -Force
Position       : At line:1 char:1
                 + Set-AzStorageBlobContent -Container "container-name" -File .\CsvFile …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 171
```

**Comment by msetogecko** [comment]
Needed 'Storage Blob Data Owner' - I thought 'Contributor' would trump that.....I guess not
