### ISSUE TITLE
Changing property 'securityProfile.securityType' using update-azDisk is not allowed

### ISSUE THREAD

**Issue by martin-merdes** [Azure/azure-powershell#24253]
### Description

If you want to create a copy of a VM that has TrustedLaunch enabled, you can use snapshots:
1. create a snapshot of the VM (which contains the property TrustedLaunch)
2. create a VM with property TrustedLaunch using the snapshot
-> this works fine

However, if want to create the copy in a different tenant, you must use a BLOB copy to a storage account:
1. create a snapshot of the VM (which contains the property TrustedLaunch)
2. create a BLOB copy from snapshot using Start-AzStorageBlobCopy (the BLOB does not contain the property TrustedLaunch, because BLOBs simply do not have properties)
3. create a disk from the BLOB (which does not contain the property TrustedLaunch)
4. create a VM with property TrustedLaunch using the disk
-> this fails with error: **Security type of VM is not compatible with the security type of attached OS Disk.**

I tried several workarounds, but they all fail:
1. Setting the property during disk creation in an ARM template
-> this fails with error: **Security Type 'TrustedLaunch' is not supported for CreateOption 'Copy'**
2. Setting the property during disk creation using New-AzDisk is not possible
-> There is simply no parameter in New-AzDiskConfig or New-AzDisk for this
3. When trying to change the property using update-azDisk
-> it fails with: **Changing property 'securityProfile.securityType' is not allowed.**

There must be way to set the property TrustedLaunch again after it has been lost during BLOB copy. The easiest way would be, allowing to change the disk property using update-azDisk

### Issue script & Debug output

```PowerShell
$rg_name = 'martinme_repro_bc2_target'
$disk_name = 'osdisk'
$d = get-azDisk -ResourceGroupName $rg_name -Name $disk_name
$d.securityProfile = @{securityType = 'TrustedLaunch'}
update-azDisk -ResourceGroupName $rg_name -disk $d -Name $disk_name
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.1
PSEdition                      Core
GitCommitId                    7.4.1
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.15.1                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     7.1.1                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAddition…
Script     6.15.1                Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, G…
Script     6.1.1                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorage…
```

### Error output

```PowerShell
RequestId      :
Message        : Changing property 'securityProfile.securityType' is not allowed.
                 ErrorCode: PropertyChangeNotAllowed
                 ErrorMessage: Changing property 'securityProfile.securityType' is not allowed.
                 ErrorTarget: securityProfile.securityType
                 StatusCode: 409
                 ReasonPhrase: Conflict
                 OperationID : c1df0c0f-f9dd-4ebf-851c-165dd1eabd38
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {Update-AzDisk}
Line           : update-azDisk -ResourceGroupName $rg_name -disk $d -Name $disk_name
Position       : At line:1 char:1
                 + update-azDisk -ResourceGroupName $rg_name -disk $d -Name $disk_name
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmDisk.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 7
```

**Comment by TravisCragg-MSFT** [comment]
@martin-merdes As discussed internally, this is not allowed. We will now close this issue, please follow up with me if you have any additional questions.
