### ISSUE TITLE
Approve-AzPrivateEndpointConnection does not work for Azure PaaS services

### ISSUE THREAD

**Issue by dimitri-furman** [Azure/azure-powershell#24324]
### Description

The `ServiceName` paramater of [Approve-AzPrivateEndpointConnection](https://learn.microsoft.com/powershell/module/az.network/approve-azprivateendpointconnection?view=azps-11.4.0) is required. This implies that the cmdlet can only be used to approve a private endpoint to a customer- or partner-provided [private link service](https://learn.microsoft.com/azure/private-link/private-link-service-overview) that has a defined service name.

It is not possible to use this cmdlet to approve a private endpoint to an instance of an Azure PaaS service such as Azure SQL DB.

### Issue script & Debug output

```PowerShell
C:\Windows\system32> Approve-AzPrivateEndpointConnection `
>>        -Name pe-test-1-ad10d3ff-d94d-4a98-b918-ee3631494635 `
>>        -ResourceGroupName test-rg `
>>        -PrivateLinkResourceType Microsoft.Sql/servers
>>

cmdlet Approve-AzPrivateEndpointConnection at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ServiceName:
Approve-AzPrivateEndpointConnection : Cannot validate argument on parameter 'ServiceName'. The argument is null or
empty. Provide an argument that is not null or empty, and then try the command again.
At line:1 char:1
+ Approve-AzPrivateEndpointConnection `
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Approve-AzPrivateEndpointConnection], ParameterBindingValidationExcept
   ion
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.Azure.Commands.Network.ApproveAzurePrivateEnd
   pointConnection
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.5.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
Script     4.10.0     Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-Az...
```

### Error output

```PowerShell
Message        : Cannot validate argument on parameter 'ServiceName'. The argument is null or empty. Provide an
                 argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                 parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal
                 argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32
                 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
                 ParameterBindingFlags flags)
                    at System.Management.Automation.ParameterBinderController.BindParameter(CommandParameterInternal
                 argument, ParameterBindingFlags flags)
                    at
                 System.Management.Automation.CmdletParameterBinderController.HandleUnboundMandatoryParameters(Int32
                 validParameterSetCount, Boolean processMissingMandatory, Boolean promptForMandatory, Boolean
                 isPipelineInputExpected, Collection`1& missingMandatoryParameters)
                    at
                 System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1
                 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
                 psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
                 commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Approve-AzPrivateEndpointConnection}
Line           : Approve-AzPrivateEndpointConnection `

Position       : At line:1 char:1
                 + Approve-AzPrivateEndpointConnection `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : The argument is null or empty. Provide an argument that is not null or empty, and then try the
                 command again.
StackTrace     :    at System.Management.Automation.ValidateNotNullOrEmptyAttribute.Validate(Object arguments,
                 EngineIntrinsics engineIntrinsics)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                 parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
Exception      : System.Management.Automation.ValidationMetadataException
InvocationInfo : {Approve-AzPrivateEndpointConnection}
Line           : Approve-AzPrivateEndpointConnection `

Position       : At line:1 char:1
                 + Approve-AzPrivateEndpointConnection `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7
```

**Comment by isra-fel** [comment]
Thanks for the feedback. IMO it's the matter of constructing the private endpoint connection URL.
The URL has to follow this pattern, which means ServiceName is necessary:

https://github.com/Azure/azure-powershell/blob/3318943634bab88fb39cfc7f150650f23502ddc9/src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/GenericProvider.cs#L203

What would it be in the case of "an Azure PaaS service"? Any document or spec is appreciated.

**Comment by isra-fel** [comment]
> Thanks for the feedback. IMO it's the matter of constructing the private endpoint connection URL. The URL has to follow this pattern, which means ServiceName is necessary:
> 
> https://github.com/Azure/azure-powershell/blob/3318943634bab88fb39cfc7f150650f23502ddc9/src/Network/Network/PrivateLinkService/PrivateLinkServiceProvider/GenericProvider.cs#L203
> 
> What would it be in the case of "an Azure PaaS service"? Any document or spec is appreciated.

echo
