### ISSUE TITLE
Set-AzStorageObjectReplicationPolicy fails when setting a date based policy while having Dutch (Netherlands) regional settings

### ISSUE THREAD

**Issue by RobertWielink** [Azure/azure-powershell#24434]
### Description

We are trying to setup object replication between two blob containers in two storage accounts. 
This is not working when the (system) regional settings are set to for instance Dutch (Netherlands). 
When we change the regional settings to English the script to setup object replication will work.
But when we try to run it on a machine which uses Dutch regional settings this fails. It seems to have something to do with the difference between English (MMddyyyy) and Dutch date formats (ddMMyyyy).
But I would assume when you create a policy rule based on a date object that the powershell functions internally do not mess up dates in string formats.

### Issue script & Debug output

```PowerShell
$SourceStorageAccountResourceGroupName = '****'
$sourceStorageAccountName = '****'
$SourceContainerName = '****'

$DestinationStorageAccountResourceGroupName = '****'
$DestinationStorageAccountName = "****"
$DestinationContainerName = '****'

#Convert string to datetime
$StartSyncDateTimeInUTCConverted = [datetime]::ParseExact("20240321T0000000000Z", "yyyyMMddTHHmmssffffZ", $null)

$srcAccount = Get-AzStorageAccount -ResourceGroupName $SourceStorageAccountResourceGroupName -StorageAccountName $sourceStorageAccountName

$DebugPreference='Continue'

$rule1 = @()
try {
    $rule = New-AzStorageObjectReplicationPolicyRule -SourceContainer $SourceContainerName -DestinationContainer $DestinationContainerName -MinCreationTime $StartSyncDateTimeInUTCConverted
    $rule1 += $rule
}
catch {
    if ($_.Exception.Message -match "already exists") {
        Write-Host "Object replication policy already exists. Skipping step." -Verbose
        Continue
    }
    else {
        Write-Error "Error creating object replication policy: $($_.Exception.Message)"
        Break
    }
}

try {
    Write-Host "Create the replication policy on the destination account."
    $destPolicy = Set-AzStorageObjectReplicationPolicy -ResourceGroupName $DestinationStorageAccountResourceGroupName `
        -StorageAccountName $DestinationStorageAccountName `
        -PolicyId default `
        -SourceAccount $srcAccount.Id `
        -Rule $rule1

    # Write-Host "Create the same policy on the source account"
    # Set-AzStorageObjectReplicationPolicy -ResourceGroupName $SourceStorageAccountResourceGroupName `
    #     -StorageAccountName $SourceStorageAccountName `
    #     -InputObject $destPolicy
}
catch {
    if ($_.Exception.Message -match "already exists") {
        Write-Host "Object replication policy already exists. Skipping step." -Verbose
        continue
    }
    else {
        Write-Error "Error creating object replication policy: $($_.Exception.Message)"
        Break
    }
}

Debug output: 

DEBUG: 12:09:49 - NewAzureStorageAccountObjectReplicationPolicyRuleCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 12:09:49 - using account id '****'...
DEBUG: 12:09:49 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:09:49 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:09:49 - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Storage:5.8.0; CommandName: New-AzStorageObjectReplicationPolicyRule; PSVersion: 7.3.6; IsSuccess: True; Duration: 00:00:00.0012861
DEBUG: 12:09:49 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 12:09:49 - NewAzureStorageAccountObjectReplicationPolicyRuleCommand end processing.
Create the replication policy on the destination account.
DEBUG: 12:09:49 - RSetAzureStorageAccountObjectReplicationPolicyCommand begin processing with ParameterSet 'AccountName'.
DEBUG: 12:09:49 - using account id '****'...
DEBUG: 12:09:49 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: '****', environment: 'AzureCloud', tenant: '****'
DEBUG: 12:09:49 - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 12:09:49 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'****', Scopes:'https://management.core.windows.
net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'****'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - a11187a1-7e35-46b0-a547-e3041da5ec75] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - a11187a1-7e35-46b0-a547-e3041da5ec75] [Region discovery] Not using a regiona
l authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - a11187a1-7e35-46b0-a547-e3041da5ec75] [Region discovery] Not using a regiona
l authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - a11187a1-7e35-46b0-a547-e3041da5ec75] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - a11187a1-7e35-46b0-a547-e3041da5ec75] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] MSAL MSAL.NetCore with assembly versio
n '4.49.1.0'. CorrelationId(7fb13110-c005-49a4-8c83-1c53eec63b15)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 7fb13110-c005-49a4-8c83-1c53eec63b15
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] === Token Acquisition (SilentRequest)
started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] [Region discovery] Not using a regiona
l authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] Access token is not expired. Returning
 the found cache entry. [Current time (03/21/2024 11:09:49) - Expiration Time (03/21/2024 12:26:52 +00:00) - Extended Expiration Time (03/21/2024 12:26:52 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] Returning access token found in cache.
 RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] [Region discovery] Not using a regiona
l authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.9 Microsoft Windows 10.0.14393 [2024-03-21 11:09:49Z - 7fb13110-c005-49a4-8c83-1c53eec63b15]  AT expiration time: 21-3-2024 12:26:5
2 +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2024-03-21T12:26:52.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: '****', UserId: '****'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****?api-version=2022-09-01

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : deebc6c9-4ec4-4896-b538-5748269aec2c

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : 81d1b5fe-72f0-4c9e-8a46-1d8ea7d831c0
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : 3e4c1fce-e058-4d98-9ad7-b6c36bdf74c8
x-ms-routing-request-id       : WESTEUROPE:20240321T110949Z:3e4c1fce-e058-4d98-9ad7-b6c36bdf74c8
X-Content-Type-Options        : nosniff
Date                          : Thu, 21 Mar 2024 11:09:48 GMT

Body:
{
  "sku": {
    "name": "Standard_LRS",
    "tier": "Standard"
  },
  "kind": "StorageV2",
  "id": "/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****",
  "name": "****",
  "type": "Microsoft.Storage/storageAccounts",
  "location": "northeurope",
  "tags": {},
  "properties": {
    "keyCreationTime": {
      "key1": "2024-02-28T15:46:20.5369792Z",
      "key2": "2024-02-28T15:46:20.5369792Z"
    },
    "allowCrossTenantReplication": false,
    "privateEndpointConnections": [],
    "minimumTlsVersion": "TLS1_0",
    "allowBlobPublicAccess": false,
    "networkAcls": {
      "bypass": "AzureServices",
      "virtualNetworkRules": [],
      "ipRules": [],
      "defaultAction": "Allow"
    },
    "supportsHttpsTrafficOnly": true,
    "encryption": {
      "services": {
        "file": {
          "keyType": "Account",
          "enabled": true,
          "lastEnabledTime": "2024-02-28T15:46:20.5369792Z"
        },
        "blob": {
          "keyType": "Account",
          "enabled": true,
          "lastEnabledTime": "2024-02-28T15:46:20.5369792Z"
        }
      },
      "keySource": "Microsoft.Storage"
    },
    "accessTier": "Hot",
    "provisioningState": "Succeeded",
    "creationTime": "2024-02-28T15:46:20.4119662Z",
    "primaryEndpoints": {
      "dfs": "https://****.dfs.core.windows.net/",
      "web": "https://****.z16.web.core.windows.net/",
      "blob": "https://****.blob.core.windows.net/",
      "queue": "https://****.queue.core.windows.net/",
      "table": "https://****.table.core.windows.net/",
      "file": "https://****.file.core.windows.net/"
    },
    "primaryLocation": "northeurope",
    "statusOfPrimary": "available"
  }
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****/objectReplicationPolicie
s/default?api-version=2022-09-01

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : deebc6c9-4ec4-4896-b538-5748269aec2c

Body:
{
  "properties": {
    "sourceAccount": "/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****",
    "destinationAccount": "/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****",
    "rules": [
      {
        "sourceContainer": "****",
        "destinationContainer": "****",
        "filters": {
          "minCreationTime": "2024-03-21T00:00:00Z"
        }
      }
    ]
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-request-id               : c5664326-9558-4cd6-8e08-71f04a6d4b48
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 96e67ea0-fb91-491f-9fff-60819d228433
x-ms-routing-request-id       : WESTEUROPE:20240321T110959Z:96e67ea0-fb91-491f-9fff-60819d228433
X-Content-Type-Options        : nosniff
Date                          : Thu, 21 Mar 2024 11:09:59 GMT

Body:
{
  "id": "/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****/objectReplicationPolicies/c6b549b7-3776-415
3-a7bd-6cf7de1776de",
  "name": "c6b549b7-3776-4153-a7bd-6cf7de1776de",
  "type": "Microsoft.Storage/storageAccounts/objectReplicationPolicies",
  "properties": {
    "policyId": "c6b549b7-3776-4153-a7bd-6cf7de1776de",
    "sourceAccount": "/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****",
    "destinationAccount": "/subscriptions/****/resourceGroups/****/providers/Microsoft.Storage/storageAccounts/****",
    "rules": [
      {
        "ruleId": "3ed85a76-58b2-4d4b-bbb4-b5c30a3c5cde",
        "sourceContainer": "****",
        "destinationContainer": "****",
        "filters": {
          "minCreationTime": "2024-03-21T00:00:00Z"
        }
      }
    ]
  }
}


DEBUG: 12:09:59 - [ConfigManager] Got nothing from [DisableErrorRecordsPersistence], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 12:09:59 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Set-AzStorageObjectReplicationPolicy: 
Line |
  35 |  … estPolicy = Set-AzStorageObjectReplicationPolicy -ResourceGroupName $ …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | String '03/21/2024 00:00:00Z' was not recognized as a valid DateTime.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.16.0                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     6.1.2                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRu…
```

### Error output

```PowerShell
DEBUG: 13:11:34 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 13:11:34 - using account id '****'...
DEBUG: 13:11:34 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 13:11:34 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [False].

   HistoryId: 6

Message        : String '03/21/2024 00:00:00Z' was not recognized as a valid DateTime.
StackTrace     :    at System.Convert.ToDateTime(String value)
                    at Microsoft.Azure.Commands.Management.Storage.Models.PSObjectReplicationPolicyFilter..ctor(ObjectReplicationPolicyFilter filter)
                    at Microsoft.Azure.Commands.Management.Storage.Models.PSObjectReplicationPolicyRule..ctor(ObjectReplicationPolicyRule rule)
                    at Microsoft.Azure.Commands.Management.Storage.Models.PSObjectReplicationPolicyRule.GetPSObjectReplicationPolicyRules(IList`1 rules)
                    at Microsoft.Azure.Commands.Management.Storage.Models.PSObjectReplicationPolicy..ctor(ObjectReplicationPolicy policy, String ResourceGroupName, String StorageA
                 ccountName)
                    at Microsoft.Azure.Commands.Management.Storage.RSetAzureStorageAccountObjectReplicationPolicyCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.FormatException
InvocationInfo : {Set-AzStorageObjectReplicationPolicy}
Line           :     $destPolicy = Set-AzStorageObjectReplicationPolicy -ResourceGroupName $DestinationStorageAccountResourceGroupName `

Position       : At line:34 char:19
                 + … estPolicy = Set-AzStorageObjectReplicationPolicy -ResourceGroupName $ …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6



DEBUG: 13:11:34 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 13:11:34 - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.16.0; CommandName: Resolve-AzError; PSVersion: 7.3.6; IsSuccess: True; Duration: 00:00:00.0180217
DEBUG: 13:11:34 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 13:11:34 - ResolveError end processing.
```

**Comment by blueww** [comment]
@RobertWielink 

Thanks for reporting this issue!
It looks on a machine which uses Dutch regional settings, although server returns "2024-03-21T00:00:00Z", SDK code will return '03/21/2024 00:00:00' to Powershell code. And Powershell code will parse the string to DateTime format, but both '03/21/2024 00:00:00' and '03/21/2024 00:00:00Z' will fail in convert to DateTime type by `System.Convert.ToDateTime()`. 
We will look deeper into this and see how to fix that.

Besides that, as this works on English OS, we believe this doesn't block you work now. 
Feel free to let us know if you need a workaround before this is fixed in PowerShell.

**Comment by RobertWielink** [comment]
Our current workaround is making sure to use English regional settings. In this case we luckily do not have to rely on Dutch regional settings for other code on the same environment.
