### ISSUE TITLE
Receiving error, "A parameter cannot be found that matches parameter name 'AsPlainText'." when running Get-AzKeyVaultSecret for a specific version

### ISSUE THREAD

**Issue by chmaddix** [Azure/azure-powershell#24829]
### Description

$oldVersion.Version = anAlphaNumericVersion
$oldVersionSecret = Get-AzKeyVaultSecret -VaultName vaultName -Name secretName -Version $oldVersion.Version -AsPlainText

Above PowerShell script returns the below error:

Get-AzKeyVaultSecret : A parameter cannot be found that matches parameter name 'AsPlainText'.
At line:1 char:109
+ ...  vaultName -Name secretName -Version $oldVersion.Version -AsPlainText
+                                                              ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzKeyVaultSecret], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret

### Issue script & Debug output

```PowerShell
$oldVersion.Version = anAlphaNumericVersion
$oldVersionSecret = Get-AzKeyVaultSecret -VaultName vaultName -Name secretName -Version $oldVersion.Version -AsPlainText



Get-AzKeyVaultSecret : A parameter cannot be found that matches parameter name 'AsPlainText'.
At line:1 char:109
+ ...  vaultName -Name secretName -Version $oldVersion.Version -AsPlainText
+                                                              ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-AzKeyVaultSecret], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
```

### Environment data

```PowerShell
Name                           Value                                                                                                                 
----                           -----                                                                                                                 
PSVersion                      5.1.22621.2506                                                                                                        
PSEdition                      Desktop                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                               
BuildVersion                   10.0.22621.2506                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                       
WSManStackVersion              3.0                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                   
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                                                           
---------- -------    ----                                ----------------                                                                           
Script     1.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-AzAccount...}                
Script     1.5.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Add-AzKeyVaultCertificateContact, Add-AzKeyVaultKey, Add-AzK...
```

### Error output

```PowerShell
DEBUG: 1:54:32 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 1:54:32 PM - using account id 'alias@microsoft.com'...
WARNING: Breaking changes in the cmdlet 'Resolve-AzError' :
WARNING:  - The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` ins
tead.
 
 
WARNING: NOTE : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes
in Azure PowerShell.
 
 
   HistoryId: 29
 
 
ErrorCategory     : InvalidArgument: (:) [Get-AzKeyVaultSecret], ParameterBindingException
ErrorDetail       : 
InvocationInfo    : {Get-AzKeyVaultSecret}
Line              : $oldVersionSecret = Get-AzKeyVaultSecret -VaultName vaultName -Name secretName -Version $oldVersion.Version -AsPlainText
Position          : At line:1 char:109
                    + ...  vaultName -Name secretName -Version $oldVersion.Version -AsPlainText
                    +                                                              ~~~~~~~~~~~~
BoundParameters   : {}
UnboundParameters : 
HistoryId         : 29
 
Resolve-AzError : Collection was modified; enumeration operation may not execute.
At line:1 char:1
+ Resolve-AzError
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Resolve-AzError], InvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.Errors.ResolveError
DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - False; Duration - 00:00:00.2963025; Exception - System.InvalidOperationException: Col
lection was modified; enumeration operation may not execute.
   at System.Collections.ArrayList.ArrayListEnumeratorSimple.MoveNext()
   at System.Linq.Enumerable.<OfTypeIterator>d__95`1.MoveNext()
   at Microsoft.Azure.Commands.Profile.Errors.ResolveError.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:54:40 PM - ResolveError end processing.
DEBUG: 1:54:40 PM - ResolveError end processing.
```

**Comment by isra-fel** [comment]
Hi, AsPlainText was introduced in a later version. Please update Azure PowerShell to the latest version.
