### ISSUE TITLE
Api Management calls are failing with "The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."

### ISSUE THREAD

**Issue by vandanchev** [Azure/azure-powershell#24946]
### Description

Fetching and updating data is failing sporadically but frequently with timeout errors.

"The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing."

Exp.
Get-AzApiManagementUser -Context $APIMContext -Debug -UserId 1

### Issue script & Debug output

```PowerShell
PS C:\> $users = Get-AzApiManagementUser -Context $APIMContext -Debug -UserId 1
DEBUG: 09:37:51 - GetAzureApiManagementUser begin processing with ParameterSet 'GetByUserId'.
DEBUG: 09:37:51 - using account id 'xxxxxxxxxx'...
DEBUG: 09:37:51 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxxxxx', environment: 'AzureCloud', tenant: 'zzzzzzz'
DEBUG: 09:37:51 - [ConfigManager] Got nothing from [EnableLoginByWam], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: 09:37:51 - [SilentAuthenticator] Calling SharedTokenCacheCredential.GetTokenAsync - TenantId:'zzzzzzz', Scopes:'https://management.core.windows.net//.default', AuthorityHost:'https://login.microsoftonline.com/', UserId:'xxxxxxxxxx'
DEBUG: SharedTokenCacheCredential.GetToken invoked. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - b1c18e26-d3b8-42df-aa95-c60192409076] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - b1c18e26-d3b8-42df-aa95-c60192409076] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - b1c18e26-d3b8-42df-aa95-c60192409076] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - b1c18e26-d3b8-42df-aa95-c60192409076] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - b1c18e26-d3b8-42df-aa95-c60192409076] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] MSAL MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(6dd42614-82c9-4d9c-932a-436eebde09a0)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0]
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 6dd42614-82c9-4d9c-932a-436eebde09a0
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] Access token is not expired. Returning the found cache entry. [Current time (05/17/2024 06:37:51) - Expiration Time (05/17/2024 07:11:45 +00:00) - Extended Expiration Time (05/17/2024 07:11:45 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0] [Region discovery] Not using a regional authority.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0]
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.4 Microsoft Windows 10.0.22631 [2024-05-17 06:37:51Z - 6dd42614-82c9-4d9c-932a-436eebde09a0]  AT expiration time: 17/05/2024 07:11:45 +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2024-05-17T07:11:45.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'zzzzzzz', UserId: 'xxxxxxxxxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/users/1?api-version=2021-08-01

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 011f7757-28a3-4037-8e49-9ce82190e91a

Body:



DEBUG: 09:39:51 - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
Get-AzApiManagementUser: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
DEBUG: 09:39:51 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 09:39:51 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.ApiManagement:4.0.2; CommandName: Get-AzApiManagementUser; PSVersion: 7.4.2; IsSuccess: False; Duration: 00:02:00.5336506; Exception: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.;
DEBUG: 09:39:51 - GetAzureApiManagementUser end processing.
```

### Environment data

```PowerShell
PS C:\> $PSversiontable

Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\> get-module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.3                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     4.0.2                 Az.ApiManagement                    {Add-AzApiManagementApiToGateway, Add-AzApiManagementApiToProduct, Add-AzApiManagementProductToGroup, Add-AzApiManagementRegion…}
```

### Error output

```PowerShell
PS C:\> Resolve-AzError
DEBUG: 09:43:56 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 09:43:56 - using account id 'Ivan.Danchev@plan-b-gmbh.com'...
DEBUG: 09:43:56 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
WARNING: Upcoming breaking changes in the cmdlet 'Resolve-AzError' :
The `Resolve-Error` alias will be removed in a future release.  Please change any scripts that use this alias to use `Resolve-AzError` instead.
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.

   HistoryId: 65

Message        : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
StackTrace     :    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource
                 pendingRequestsCts)
                    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
                 CancellationToken originalCancellationToken)
                    at Microsoft.Azure.Management.ApiManagement.UserOperations.GetWithHttpMessagesAsync(String resourceGroupName, String serviceName, String userId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ApiManagement.UserOperationsExtensions.GetAsync(IUserOperations operations, String resourceGroupName, String serviceName, String userId, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.ApiManagement.UserOperationsExtensions.Get(IUserOperations operations, String resourceGroupName, String serviceName, String userId)
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.UserById(PsApiManagementContext context, String userId)
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.GetAzureApiManagementUser.ExecuteApiManagementCmdlet()
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet()
Exception      : System.Threading.Tasks.TaskCanceledException
InvocationInfo : {Get-AzApiManagementUser}
Line           : $users = Get-AzApiManagementUser -Context $APIMContext -Debug -UserId 1
Position       : At line:1 char:10
                 + $users = Get-AzApiManagementUser -Context $APIMContext -Debug -UserId …
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 65

Message        : A task was canceled.
StackTrace     :
Exception      : System.TimeoutException
InvocationInfo : {Get-AzApiManagementUser}
Line           : $users = Get-AzApiManagementUser -Context $APIMContext -Debug -UserId 1
Position       : At line:1 char:10
                 + $users = Get-AzApiManagementUser -Context $APIMContext -Debug -UserId …
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 65

Message        : A task was canceled.
StackTrace     :    at System.Net.Http.HttpConnectionResponseContent.<SerializeToStreamAsync>g__Impl|6_0(Stream stream, CancellationToken cancellationToken)
                    at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
                    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts,
                 CancellationToken originalCancellationToken)
Exception      : System.Threading.Tasks.TaskCanceledException
InvocationInfo : {Get-AzApiManagementUser}
Line           : $users = Get-AzApiManagementUser -Context $APIMContext -Debug -UserId 1
Position       : At line:1 char:10
                 + $users = Get-AzApiManagementUser -Context $APIMContext -Debug -UserId …
                 +          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 65

**Comment by vandanchev** [comment]
Confirmed with MS support that there is an ongoing issue with the Management Api that resulted in such delays.

**Comment by vandanchev** [comment]
Issue was mitigated by MS support
