### ISSUE TITLE
The parameter 'deploymentName' cannot be specified because it conflicts with the parameter alias of the same name for parameter 'Name'.

### ISSUE THREAD

**Issue by PriD98** [Azure/azure-powershell#25049]
### Description

I'm trying to deploy with ARM templates, and I keep getting the same error:

The parameter 'deploymentName' cannot be specified because it conflicts with the parameter alias of the same name for parameter 'Name'.

### Issue script & Debug output

```PowerShell
PS C:\Users\<myalias>\Downloads> New-AzResourceGroupDeployment -ResourceGroupName "test" -TemplateFile "template.json" -TemplateParameterFile "parameters.json"  
The parameter 'deploymentName' cannot be specified because it conflicts with the parameter alias of the same name for parameter 'Name'.
At line:1 char:1
+ New-AzResourceGroupDeployment -ResourceGroupName "test" -TemplateFile ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameConflictsWithAlias
```

### Environment data

```PowerShell
PS C:\Users\<myalias>\Downloads> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.2506
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.2506
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
PS C:\Users\<myalias>\Downloads> Get-Module Az*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.12.4     Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     6.8.0      Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment...}
```

### Error output

```PowerShell
PS C:\Users\<myalias>\Downloads>  Resolve-AzError
DEBUG: 14:29:21 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 14:29:21 - using account id 'priyadhami@microsoft.com'...
DEBUG: 14:29:21 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].


   HistoryId: -1


Message        : The parameter 'deploymentName' cannot be specified because it conflicts with the parameter alias of the same name for parameter 'Name'.
StackTrace     :    at System.Management.Automation.MergedCommandParameterMetadata.AddMetadataForBinder(InternalParameterMetadata parameterMetadata, ParameterBinderAssociation binderAssociation)
                    at System.Management.Automation.CmdletParameterBinderController.HandleCommandLineDynamicParameters(ParameterBindingException& outgoingBindingException)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.MetadataException
InvocationInfo : {}
Line           : New-AzResourceGroupDeployment -ResourceGroupName "test" -TemplateFile "template.json" -TemplateParameterFile "parameters.json"  
Position       : At line:1 char:1
                 + New-AzResourceGroupDeployment -ResourceGroupName "test" -TemplateFile ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1
```

**Comment by isra-fel** [comment]
Hi @PriD98 sorry for the late response. Basically this is a conflict between the parameters of the powershell cmdlet and of the ARM template. You see, each of ARM template parameters is mapped to a powershell parameter dynamically, giving you another option to input the values. The limitation is that the names of the mapped parameters can conflict with the static parameters. That's what happen in your case.

Based on that I assume your "template.json" defines a parameter called "deploymentName" or "Name". If that's the case, the simple fix is to rename it. Call it "CustomDeploymentName" for example. That should fix the issue.
