### ISSUE TITLE
How to copy an 8TiB snapshot using Start-AzStorageBlobCopy?

### ISSUE THREAD

**Issue by martin-merdes** [Azure/azure-powershell#25092]
### Description

When I try to copy a snapshot with a size of 8192GiB using Start-AzStorageBlobCopy, it fails with the error below. For smaller snapshots, it works. Is this an intended limitation of Start-AzStorageBlobCopy? I did not find anything in the documentation.

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
Directory: C:\Program Files\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     11.6.0                Az                                  Core,Desk
Script     11.5.0                Az                                  Core,Desk
Script     11.4.0                Az                                  Core,Desk
Script     2.19.0                Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     2.17.0                Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     2.16.0                Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzCo…
Script     2.0.1                 Az.Advisor                          Core,Desk {Disable-AzAdvisorRecommendation, Enabl…
Script     2.0.0                 Az.Advisor                          Core,Desk {Disable-AzAdvisorRecommendation, Enabl…
Script     6.0.3                 Az.Aks                              Core,Desk {Disable-AzAksAddOn, Enable-AzAksAddOn,…
Script     6.0.2                 Az.Aks                              Core,Desk {Disable-AzAksAddOn, Enable-AzAksAddOn,…
Script     6.0.1                 Az.Aks                              Core,Desk {Disable-AzAksAddOn, Enable-AzAksAddOn,…
Script     1.1.4                 Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspe…
Script     4.0.2                 Az.ApiManagement                    Core,Desk {Add-AzApiManagementApiToGateway, Add-A…
Script     1.0.0                 Az.App                              Core,Desk {Disable-AzContainerAppRevision, Enable…
Script     1.3.1                 Az.AppConfiguration                 Core,Desk {Clear-AzAppConfigurationDeletedStore, …
Script     1.3.0                 Az.AppConfiguration                 Core,Desk {Get-AzAppConfigurationStore, Get-AzApp…
Script     2.2.5                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, Get-AzAppli…
Script     2.2.4                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, Get-AzAppli…
Script     2.2.3                 Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, Get-AzAppli…
Script     1.0.1                 Az.ArcResourceBridge                Core,Desk {Get-AzArcResourceBridge, Get-AzArcReso…
Script     1.0.0                 Az.ArcResourceBridge                Core,Desk {Get-AzArcResourceBridge, Get-AzArcReso…
Script     2.0.2                 Az.Attestation                      Core,Desk {Add-AzAttestationPolicySigner, Get-AzA…
Script     2.0.1                 Az.Attestation                      Core,Desk {Add-AzAttestationPolicySigner, Get-AzA…
Script     2.0.0                 Az.Attestation                      Core,Desk {Get-AzAttestationPolicy, Set-AzAttesta…
Script     1.0.1                 Az.Automanage                       Core,Desk {Get-AzAutomanageBestPractice, Get-AzAu…
Script     1.0.0                 Az.Automanage                       Core,Desk {Get-AzAutomanageBestPractice, Get-AzAu…
Script     1.10.0                Az.Automation                       Core,Desk {Export-AzAutomationDscConfiguration, E…
Script     3.6.0                 Az.Batch                            Core,Desk {Disable-AzBatchAutoScale, Disable-AzBa…
Script     3.5.0                 Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAcco…
Script     2.0.3                 Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPer…
Script     3.2.0                 Az.Cdn                              Core,Desk {Clear-AzCdnEndpointContent, Clear-AzFr…
Script     3.1.2                 Az.Cdn                              Core,Desk {Clear-AzCdnEndpointContent, Clear-AzFr…
Script     2.0.1                 Az.CloudService                     Core,Desk {Get-AzCloudService, Get-AzCloudService…
Script     2.0.0                 Az.CloudService                     Core,Desk {Get-AzCloudService, Get-AzCloudService…
Script     1.14.1                Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-Az…
Script     7.3.0                 Az.Compute                          Core,Desk {Add-AzImageDataDisk, Add-AzVhd, Add-Az…
Script     7.2.0                 Az.Compute                          Core,Desk {Add-AzImageDataDisk, Add-AzVhd, Add-Az…
Script     7.1.2                 Az.Compute                          Core,Desk {Add-AzImageDataDisk, Add-AzVhd, Add-Az…
Script     1.0.1                 Az.ConfidentialLedger               Core,Desk {Get-AzConfidentialLedger, New-AzConfid…
Script     1.0.0                 Az.ConfidentialLedger               Core,Desk {Get-AzConfidentialLedger, New-AzConfid…
Script     4.0.1                 Az.ContainerInstance                Core,Desk {Add-AzContainerInstanceOutput, Get-AzC…
Script     4.0.0                 Az.ContainerInstance                Core,Desk {Add-AzContainerInstanceOutput, Get-AzC…
Script     4.2.1                 Az.ContainerRegistry                Core,Desk {Connect-AzContainerRegistry, Get-AzCon…
Script     4.2.0                 Az.ContainerRegistry                Core,Desk {Connect-AzContainerRegistry, Get-AzCon…
Script     4.1.3                 Az.ContainerRegistry                Core,Desk {Connect-AzContainerRegistry, Get-AzCon…
Script     1.14.2                Az.CosmosDB                         Core,Desk {Get-AzCosmosDBAccount, Get-AzCosmosDBA…
Script     1.14.1                Az.CosmosDB                         Core,Desk {Get-AzCosmosDBAccount, Get-AzCosmosDBA…
Script     1.1.0                 Az.DataBoxEdge                      Core,Desk {Get-AzDataBoxEdgeJob, Get-AzDataBoxEdg…
Script     1.7.2                 Az.Databricks                       Core,Desk {Get-AzDatabricksAccessConnector, Get-A…
Script     1.7.1                 Az.Databricks                       Core,Desk {Get-AzDatabricksAccessConnector, Get-A…
Script     1.18.3                Az.DataFactory                      Core,Desk {Add-AzDataFactoryV2DataFlowDebugSessio…
Script     1.18.2                Az.DataFactory                      Core,Desk {Add-AzDataFactoryV2DataFlowDebugSessio…
Script     1.0.3                 Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New…
Script     1.3.0                 Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, …
Script     2.4.0                 Az.DataProtection                   Core,Desk {Backup-AzDataProtectionBackupInstanceA…
Script     2.3.0                 Az.DataProtection                   Core,Desk {Backup-AzDataProtectionBackupInstanceA…
Script     2.2.0                 Az.DataProtection                   Core,Desk {Backup-AzDataProtectionBackupInstanceA…
Script     1.0.1                 Az.DataShare                        Core,Desk {New-AzDataShareAccount, Get-AzDataShar…
Script     4.3.1                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-Az…
Script     4.3.0                 Az.DesktopVirtualization            Core,Desk {Disconnect-AzWvdUserSession, Expand-Az…
Script     1.1.1                 Az.DevCenter                        Core,Desk {Deploy-AzDevCenterUserEnvironment, Get…
Script     1.1.0                 Az.DevCenter                        Core,Desk {Deploy-AzDevCenterUserEnvironment, Get…
Script     1.0.2                 Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzD…
Script     1.2.1                 Az.Dns                              Core,Desk {Add-AzDnsRecordConfig, Get-AzDnsRecord…
Script     1.2.0                 Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordCon…
Script     1.0.2                 Az.ElasticSan                       Core,Desk {Add-AzElasticSanVolumeGroupNetworkRule…
Script     1.0.1                 Az.ElasticSan                       Core,Desk {Add-AzElasticSanVolumeGroupNetworkRule…
Script     1.0.0                 Az.ElasticSan                       Core,Desk {Add-AzElasticSanVolumeGroupNetworkRule…
Script     1.6.1                 Az.EventGrid                        Core,Desk {Enable-AzEventGridPartnerTopic, Get-Az…
Script     1.6.0                 Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridT…
Script     4.2.2                 Az.EventHub                         Core,Desk {New-AzEventHubAuthorizationRuleSASToke…
Script     4.2.1                 Az.EventHub                         Core,Desk {New-AzEventHubAuthorizationRuleSASToke…
Script     4.2.0                 Az.EventHub                         Core,Desk {New-AzEventHubAuthorizationRuleSASToke…
Script     1.10.0                Az.FrontDoor                        Core,Desk {New-AzFrontDoor, Get-AzFrontDoor, Set-…
Script     4.0.8                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAv…
Script     4.0.7                 Az.Functions                        Core,Desk {Get-AzFunctionApp, Get-AzFunctionAppAv…
Script     6.1.0                 Az.HDInsight                        Core,Desk {Add-AzHDInsightClusterIdentity, Add-Az…
Script     2.0.1                 Az.HealthcareApis                   Core,Desk {Get-AzHealthcareApisService, Get-AzHea…
Script     2.0.0                 Az.HealthcareApis                   Core,Desk {Get-AzHealthcareApisService, Get-AzHea…
Script     2.7.5                 Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubC…
Script     5.3.0                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Add-AzKeyVa…
Script     5.2.2                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Add-AzKeyVa…
Script     5.2.1                 Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Add-AzKeyVa…
Script     2.3.1                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension, A…
Script     2.3.0                 Az.Kusto                            Core,Desk {Add-AzKustoClusterLanguageExtension, A…
Script     1.0.1                 Az.LoadTesting                      Core,Desk {Get-AzLoad, New-AzLoad, Remove-AzLoad,…
Script     1.0.0                 Az.LoadTesting                      Core,Desk {Get-AzLoad, New-AzLoad, Remove-AzLoad,…
Script     1.5.1                 Az.LogicApp                         Core,Desk {Get-AzIntegrationAccount, Get-AzIntegr…
Script     1.1.3                 Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-Az…
Script     1.0.0                 Az.MachineLearningServices          Core,Desk {Get-AzMLServiceQuota, Get-AzMLServiceU…
Script     1.4.1                 Az.Maintenance                      Core,Desk {Get-AzApplyUpdate, Get-AzConfiguration…
Script     1.2.1                 Az.ManagedServiceIdentity           Core,Desk {Get-AzFederatedIdentityCredential, Get…
Script     1.2.0                 Az.ManagedServiceIdentity           Core,Desk {Get-AzSystemAssignedIdentity, Get-AzUs…
Script     3.0.1                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, Get-A…
Script     3.0.0                 Az.ManagedServices                  Core,Desk {Get-AzManagedServicesAssignment, Get-A…
Script     2.0.1                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Invoke-AzMarke…
Script     2.0.0                 Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Invoke-AzMarke…
Script     1.1.2                 Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKey, Set-AzM…
Script     2.3.1                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzM…
Script     2.3.0                 Az.Migrate                          Core,Desk {Get-AzMigrateDiscoveredServer, Get-AzM…
Script     5.2.0                 Az.Monitor                          Core,Desk {Add-AzLogProfile, Add-AzMetricAlertRul…
Script     5.1.1                 Az.Monitor                          Core,Desk {Add-AzLogProfile, Add-AzMetricAlertRul…
Script     5.1.0                 Az.Monitor                          Core,Desk {Add-AzLogProfile, Add-AzMetricAlertRul…
Script     1.1.2                 Az.MySql                            Core,Desk {Get-AzMySqlConfiguration, Get-AzMySqlC…
Script     1.1.1                 Az.MySql                            Core,Desk {Get-AzMySqlConfiguration, Get-AzMySqlC…
Script     0.15.2                Az.NetAppFiles                      Core,Desk {Approve-AzNetAppFilesReplication, Get-…
Script     7.5.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthentication…
Script     7.4.1                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthentication…
Script     7.4.0                 Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthentication…
Script     1.0.1                 Az.NetworkCloud                     Core,Desk {Deploy-AzNetworkCloudCluster, Disable-…
Script     1.0.0                 Az.NetworkCloud                     Core,Desk {Deploy-AzNetworkCloudCluster, Disable-…
Script     1.0.1                 Az.Nginx                            Core,Desk {Get-AzNginxCertificate, Get-AzNginxCon…
Script     1.0.0                 Az.Nginx                            Core,Desk {Get-AzNginxCertificate, Get-AzNginxCon…
Script     1.1.2                 Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificat…
Script     3.2.0                 Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivity…
Script     1.6.5                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyAttestation, Get-AzPolicyE…
Script     1.6.4                 Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, …
Script     1.1.1                 Az.PostgreSql                       Core,Desk {Get-AzPostgreSqlConfiguration, Get-AzP…
Script     1.1.0                 Az.PostgreSql                       Core,Desk {Get-AzPostgreSqlConfiguration, Get-AzP…
Script     2.0.0                 Az.PowerBIEmbedded                  Core,Desk {Resume-AzPowerBIEmbeddedCapacity, Susp…
Script     1.0.4                 Az.PrivateDns                       Core,Desk {Get-AzPrivateDnsZone, Remove-AzPrivate…
Script     6.9.0                 Az.RecoveryServices                 Core,Desk {Add-AzRecoveryServicesAsrReplicationPr…
Script     6.8.0                 Az.RecoveryServices                 Core,Desk {Add-AzRecoveryServicesAsrReplicationPr…
Script     6.7.1                 Az.RecoveryServices                 Core,Desk {Add-AzRecoveryServicesAsrReplicationPr…
Script     1.9.0                 Az.RedisCache                       Core,Desk {Export-AzRedisCache, Get-AzRedisCache,…
Script     1.2.1                 Az.RedisEnterpriseCache             Core,Desk {Export-AzRedisEnterpriseCache, Get-AzR…
Script     1.2.0                 Az.RedisEnterpriseCache             Core,Desk {Export-AzRedisEnterpriseCache, Get-AzR…
Script     2.0.1                 Az.Relay                            Core,Desk {Get-AzRelayAuthorizationRule, Get-AzRe…
Script     2.0.0                 Az.Relay                            Core,Desk {Get-AzRelayAuthorizationRule, Get-AzRe…
Script     1.2.1                 Az.ResourceMover                    Core,Desk {Add-AzResourceMoverMoveResource, Get-A…
Script     1.2.0                 Az.ResourceMover                    Core,Desk {Add-AzResourceMoverMoveResource, Get-A…
Script     6.16.2                Az.Resources                        Core,Desk {Export-AzResourceGroup, Export-AzTempl…
Script     6.16.1                Az.Resources                        Core,Desk {Export-AzResourceGroup, Export-AzTempl…
Script     6.16.0                Az.Resources                        Core,Desk {Export-AzResourceGroup, Export-AzTempl…
Script     1.6.2                 Az.Security                         Core,Desk {Add-AzSecurityAdaptiveNetworkHardening…
Script     1.6.1                 Az.Security                         Core,Desk {Add-AzSecurityAdaptiveNetworkHardening…
Script     1.6.0                 Az.Security                         Core,Desk {Add-AzSecurityAdaptiveNetworkHardening…
Script     3.1.2                 Az.SecurityInsights                 Core,Desk {Get-AzSentinelAlertRule, Get-AzSentine…
Script     3.1.1                 Az.SecurityInsights                 Core,Desk {Get-AzSentinelAlertRule, Get-AzSentine…
Script     3.1.1                 Az.ServiceBus                       Core,Desk {New-AzServiceBusAuthorizationRuleSASTo…
Script     3.1.0                 Az.ServiceBus                       Core,Desk {New-AzServiceBusAuthorizationRuleSASTo…
Script     3.0.0                 Az.ServiceBus                       Core,Desk {New-AzServiceBusAuthorizationRuleSASTo…
Script     3.3.2                 Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricClientCertificate, …
Script     2.0.1                 Az.SignalR                          Core,Desk {Get-AzSignalR, Get-AzSignalRKey, Get-A…
Script     2.0.0                 Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSi…
Script     4.14.1                Az.Sql                              Core,Desk {Add-AzSqlDatabaseToFailoverGroup, Add-…
Script     4.14.0                Az.Sql                              Core,Desk {Add-AzSqlDatabaseToFailoverGroup, Add-…
Script     2.2.1                 Az.SqlVirtualMachine                Core,Desk {Get-AzAvailabilityGroupListener, Get-A…
Script     2.2.0                 Az.SqlVirtualMachine                Core,Desk {Get-AzAvailabilityGroupListener, Get-A…
Script     2.3.2                 Az.StackHCI                         Core,Desk {Add-AzStackHCIVMAttestation, Disable-A…
Script     2.3.1                 Az.StackHCI                         Core,Desk {Add-AzStackHCIVMAttestation, Disable-A…
Script     1.0.3                 Az.StackHCIVM                       Core,Desk {Add-AzStackHCIVMVirtualMachineDataDisk…
Script     1.0.2                 Az.StackHCIVM                       Core,Desk {Add-AzStackHCIVMVirtualMachineDataDisk…
Script     1.0.1                 Az.StackHCIVM                       Core,Desk {Add-AzStackHCIVMVirtualMachineDataDisk…
Script     6.2.0                 Az.Storage                          Core,Desk {Add-AzRmStorageContainerLegalHold, Add…
Script     6.1.3                 Az.Storage                          Core,Desk {Add-AzRmStorageContainerLegalHold, Add…
Script     6.1.2                 Az.Storage                          Core,Desk {Add-AzRmStorageContainerLegalHold, Add…
Script     1.3.1                 Az.StorageMover                     Core,Desk {Get-AzStorageMover, Get-AzStorageMover…
Script     1.3.0                 Az.StorageMover                     Core,Desk {Get-AzStorageMover, Get-AzStorageMover…
Script     2.1.1                 Az.StorageSync                      Core,Desk {Get-AzStorageSyncCloudEndpoint, Get-Az…
Script     2.0.1                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsCluster, Get-AzSt…
Script     2.0.0                 Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsCluster, Get-AzSt…
Script     1.0.1                 Az.Support                          Core,Desk {Get-AzSupportProblemClassification, Ge…
Script     1.0.0                 Az.Support                          Core,Desk {Get-AzSupportService, Get-AzSupportPro…
Script     3.0.7                 Az.Synapse                          Core,Desk {Add-AzSynapseDataFlowDebugSessionPacka…
Script     3.0.6                 Az.Synapse                          Core,Desk {Add-AzSynapseDataFlowDebugSessionPacka…
Script     3.0.5                 Az.Synapse                          Core,Desk {Add-AzSynapseDataFlowDebugSessionPacka…
Script     1.2.2                 Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndp…
Script     3.2.1                 Az.Websites                         Core,Desk {Add-AzWebAppAccessRestrictionRule, Add…
Script     3.2.0                 Az.Websites                         Core,Desk {Add-AzWebAppAccessRestrictionRule, Add…
```

### Error output

```PowerShell
HistoryId: 4

Message        : The running command stopped because the preference variable "ErrorActionPreference" or common
                 parameter is set to Stop: The source request body is too large and exceeds the maximum permissible
                 limit.
                 RequestId:e6628161-801e-00a4-563e-b7e308000000
                 Time:2024-06-05T11:53:07.6736763Z
                 Status: 413 (The source request body is too large and exceeds the maximum permissible limit.)
                 ErrorCode: CannotVerifyCopySource

                 Content:
                 ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>CannotVerifyCopySource</Code><Message>The source
                 request body is too large and exceeds the maximum permissible limit.
                 RequestId:e6628161-801e-00a4-563e-b7e308000000
                 Time:2024-06-05T11:53:07.6736763Z</Message></Error>

                 Headers:
                 Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
                 x-ms-request-id: e6628161-801e-00a4-563e-b7e308000000
                 x-ms-client-request-id: daeca7b9-d343-4afc-a704-7d1e6fb3ee68
                 x-ms-version: 2023-08-03
                 x-ms-error-code: CannotVerifyCopySource
                 Date: Wed, 05 Jun 2024 11:53:07 GMT
                 Content-Length: 270
                 Content-Type: application/xml

StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext
                 funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                 frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object
                 dollarUnderbar, Object inputToProcess)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                 input)
                    at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
                    at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()
Exception      : System.Management.Automation.ActionPreferenceStopException
InvocationInfo : {}
Line           :        $script:copyDisks.Values

Position       : At C:\Users\martinme\OneDrive - Microsoft\githubMS\rg-copy\rgcopy.ps1:7106 char:2
                 +     $script:copyDisks.Values
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4

Message        : Operation returned an invalid status code 'Conflict'
StackTrace     :    at
                 Microsoft.Azure.Management.Authorization.RoleAssignmentsOperations.CreateWithHttpMessagesAsync(String
                 scope, String roleAssignmentName, RoleAssignmentCreateParameters parameters, Dictionary`2
                 customHeaders, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.CreateAsync(IRoleAs
                 signmentsOperations operations, String scope, String roleAssignmentName,
                 RoleAssignmentCreateParameters parameters, CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.Authorization.RoleAssignmentsOperationsExtensions.Create(IRoleAssignm
                 entsOperations operations, String scope, String roleAssignmentName, RoleAssignmentCreateParameters
                 parameters)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.CreateRoleAssignment
                 (FilterRoleAssignmentsOptions parameters, Guid roleAssignmentId)
                    at Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.Authorization.Models.ErrorResponseException
InvocationInfo : {New-AzRoleAssignment}
Line           :                New-AzRoleAssignment @param | Out-Null

Position       : At C:\Users\martinme\OneDrive - Microsoft\githubMS\rg-copy\rgcopy.ps1:13265 char:3
                 +         New-AzRoleAssignment @param | Out-Null
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4
```

**Comment by blueww** [comment]
@martin-merdes

The failure is from storage server, so the size limitation is on server instead of Powershell. 
You might can raise a help ticket on Azurite portal to get help to server team: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header.
(Besides the above request trace, you might can also share the blob type.)

Besides that, You might can also try following workaround:
1. For transfer of big data , we would recommend using AzCopy, it will be more stable and fast in transfer big data,  you can call AzCopy command in your PSH script: https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azcopy-v10
2. If you must use Powershell cmdlet, you can try  "Copy-AzStorageBlob" cmdlet, this is Sync copy cmdlet and will copy data chunk by chunk. It will be very slow for 8TB blob. (Start-AzStorageBlobCopy is async copy, it will just send copy request, but won't wait for copy finish).

**Comment by martin-merdes** [comment]
@blueww 
Thanks for the clarification that there is a size limitation. If this is by design then Start-AzStorageBlobCopy should return a clear error message rather than throwing an exception. Furthermore, this should be documented. I was searching for a limitation using AI before opening this issue and I did not find any documentation regarding a 4TB blob size limit.

**Comment by blueww** [comment]
@martin-merdes 

Thanks for the suggestion!
However, Powershell don't do size limitation check (and most of other parameter check), we depends on server to check that and will report the error from server. This can mostly accurate show the real reason of the failure, and avoid incorrect (out-of-date) limitation in Powershell blocks customer from using the feature which server supported.

Currently Powershell report the error to customer and the error says "The source request body is too large and exceeds the maximum permissible limit." Actually, this is all what Powershell can get from the error. So actually Powershell can't guess the reason, or hide/parse some information in the error, since it will make the error not so accurate and might misleading customer.

For documentation of the size limitation, this should be updated in server API doc, instead of Powershell doc. You might can raise a help ticket on Azurite portal to get help to related team: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header.

**Comment by martin-merdes** [comment]
Thanks for the clarification that this does not work.

**Comment by blueww** [comment]
Hi @martin-merdes,

Thanks  for the reply!
However, not sure what do you mean by "this does not work." Do you mean server team not responds to your help ticket, or your incident?
