### ISSUE TITLE
Running Copy-AzStorageBlob with -AsJob fails with InvalidOperation: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ld0614** [Azure/azure-powershell#25105]
### Description

When running the command

`$BlobCopyJobs += $Blob | Copy-AzStorageBlob -DestContainer $containerName -DestBlob $CopyBlobName -DestContext $SAContext -StandardBlobTier 'Hot' -RehydratePriority High -Force -AsJob`

and then retrieve the job using 

`Receive-Job $BlobCopyJobs[0]`

I get the error 

> InvalidOperation: Object reference not set to an instance of an object.

This does not happen if I run the command without the -AsJob parameter

### Issue script & Debug output

```PowerShell
DEBUG: 10:38:18 - Init Operation Context for 'CopyAzureStorageBlob' with client request id  Azure-Storage-PowerShell-ea4a066e-bbbb-411f-ac9e-d9980becaaaa. If you want to get more details, please add "-Debug" to your command.
DEBUG: 10:38:18 - Use storage account 'mystorageaccount' from storage context.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name        
---------- -------    ---------- ----          
Script     3.0.0                 Az.Accounts                         
Script     8.0.0                 Az.Compute                          
Script     7.6.0                 Az.Network                          
Script     7.1.0                 Az.Resources                        
Script     7.0.0                 Az.Storage
```

### Error output

```PowerShell
HistoryId:

Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.CopyAzureStorageBlob.ExecuteCmdlet()
                    at Microsoft.Azure.Commands.Common.AzureLongRunningJob`1.RunJob(Object state)
Exception      : System.NullReferenceException
InvocationInfo : {}
Line           :
Position       :
HistoryId      :
```

**Comment by yifanz7** [comment]
@ld0614 Thanks for raising the issue! 
We found this is a bug in our current codebase after some investigations. We're actively working on the fix, and will include the fix in the next release on 7/2.
