### ISSUE TITLE
commands unexpectedly not available

### ISSUE THREAD

**Issue by michaelNGV** [Azure/azure-powershell#25163]
### Description

`New-ServicePrincipal` command is not available and [the MS solution](https://learn.microsoft.com/en-us/answers/questions/1027098/facing-new-serviceprincipal-the-term-new-servicepr) does not apply/work.

### Issue script & Debug output

```PowerShell
If you encounter any problem, please open an issue at: https://aka.ms/azpsissue

VERBOSE: Building your Azure drive ...
PS /home/michael> Install-Module -name ExchangeOnlineManagement               
PS /home/michael> Import-Module -Name ExchangeOnlineManagement                
PS /home/michael> New-ServicePrincipal -AppId ********* -ServiceId ************ -Organization ****************
New-ServicePrincipal: The term 'New-ServicePrincipal' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS /home/michael> $Perms = Get-ManagementRole -Cmdlet New-ServicePrincipal                          
Get-ManagementRole: The term 'Get-ManagementRole' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS /home/michael>
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             CBL-Mariner/Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     8.0.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAdditionalUnattendContent, Add-AzVMDataDisk…}
Script     7.6.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Add-AzApplicationGatewayBackendAddressPool, Add-AzApplicationGatewayBackendHttpSetting, …
Script     7.1.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
Script     7.0.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorageAccountManagementPolicyAction, Add-AzStorageAccountNetworkRule, Close-AzStorageFileHandle…}
Script     1.1.3                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, Open-AzPredictorSurvey, Send-AzPredictorRating}
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDeviceRegisteredOwner, Add-AzureADDeviceRegisteredUser, Add-AzureADDirectoryRoleMember…}
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
HistoryId: 4

Message        : The term 'Get-ManagementRole' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin 
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, 
                 ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : $Perms = Get-ManagementRole -Cmdlet New-ServicePrincipal  
Position       : At line:1 char:10
                 + $Perms = Get-ManagementRole -Cmdlet New-ServicePrincipal
                 +          ~~~~~~~~~~~~~~~~~~
HistoryId      : 4


   HistoryId: 3

Message        : The term 'New-ServicePrincipal' is not recognized as a name of a cmdlet, function, script file, or executable program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin 
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, 
                 ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : New-ServicePrincipal -AppId ac1946b2-8eee-4ddf-9224-3b3da79f8fb4 -ServiceId 4a5864b0-3120-4f57-900f-29733c56f1cd -Organization 9fdd3c18-3281-4f2b-acee-60a4308bc4de
Position       : At line:1 char:1
                 + New-ServicePrincipal -AppId ac1946b2-8eee-4ddf-9224-3b3da79f8fb4 -Ser …
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3
```

**Comment by Berend-Kalberg** [comment]
How did you solve this issue?

**Comment by michaelNGV** [comment]
Sorry, almost two years after I closed it, I cannot remember and there isn't enough information here for me to work out to which of our internal systems this applied.  We may just have moved the system to other hosting.

**Comment by damianremington274-blip** [comment]
I am following up on the discussion regarding Issue #25163.

Since the original solution isn't available, I will look into [alternative
troubleshooting steps/current environment details] to see if I can resolve
the missing commands. I'll update the thread if I find a fix that works for
our current setup.
