### ISSUE TITLE
az storage blob list issue

### ISSUE THREAD

**Issue by cl33n** [Azure/azure-powershell#25162]
### Description

"az storage blob list" fails from cloudshell on my storage container with a python error.

### Issue script & Debug output

```PowerShell
PS /home/user> az storage blob list -c <containername> --account-key <removed key> --account-name <accountname> --num-results "*" --show-next-marker --query "[].{name:name}" --output tsv
/usr/bin/az: line 5:  2200 Killed                  AZ_INSTALLER=RPM PYTHONPATH="$bin_dir/../lib64/az/lib/python3.9/site-packages" $python_cmd -sm azure.cli "$@"
PS /home/user>
##############
(with the --debug command added:)
(result: a long series of http 200 messages like the following, and then the az error)
##############
urllib3.connectionpool: https://account.blob.core.windows.net:443 "GET <container>?restype=container&comp=list&marker=2%21100%21MDAwMDMxIWZnci1pbmdlc3QvSkFUUy9vdG8vb29pMTkwMDA5LzIhMDAwMDI4ITk5OTktMTItMzFUMjM6NTk6NTkuOTk5OTk5OVoh HTTP/1.1" 200 None
/usr/bin/az: line 5:  3259 Killed                  AZ_INSTALLER=RPM PYTHONPATH="$bin_dir/../lib64/az/lib/python3.9/site-packages" $python_cmd -sm azure.cli "$@"
###########
(debug head)

PS /home/user> az storage blob list -c <containername> --account-key <removed key> --account-name <accountname> --num-results "*" --show-next-marker --query "[].{name:name}" --output tsv   --debug
cli.knack.cli: Command arguments: ['storage', 'blob', 'list', '-c', '<container>', '--account-key', '<key>', '--account-name', '<name>', '--num-results', '*', '--show-next-marker', '--query', '[].{name:name}', '--output', 'tsv', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f86c9648280>, <function OutputProducer.on_global_arguments at 0x7f86c9562e50>, <function CLIQuery.on_global_arguments at 0x7f86c94f9430>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'storage': ['azure.cli.command_modules.storage']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: storage                   0.322        59       273
cli.azure.cli.core: Total (1)                 0.322        59       273
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: ai-examples               0.150         1         1  /usr/lib/python3.9/site-packages/azure-cli-extensions/ai-examples
cli.azure.cli.core: Total (1)                 0.150         1         1  
cli.azure.cli.core: Loaded 60 groups, 274 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : storage blob list
cli.azure.cli.core: Command table: storage blob list
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f86c89a9940>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/user/.azure/commands/2024-06-13.20-45-22.storage_blob_list.3826.log'.
az_command_data_logger: command args: storage blob list -c {} --account-key {} --account-name {} --num-results {} --show-next-marker --query {} --output {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f86c8951550>]
cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/profiles/_shared.py", line 660, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2023_01_01.models' has no attribute 'ActiveDirectoryPropertiesAccountType'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/profiles/_shared.py", line 660, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2023_01_01.models' has no attribute 'ListKeyExpand'

cli.azure.cli.core.profiles._shared: Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/profiles/_shared.py", line 660, in _get_attr
    op = getattr(op, part)
AttributeError: module 'azure.mgmt.storage.v2023_01_01.models' has no attribute 'CorsRuleAllowedMethodsItem'

cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f86c8976550>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f86c891f430>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f86c9562ee0>, <function CLIQuery.handle_query_parameter at 0x7f86c94f94c0>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f86c891f3a0>]
cli.azure.cli.command_modules.storage._validators: Try to get storage auth_mode value from environment variables or config file.
cli.azure.cli.command_modules.storage._validators: Try to get storage sas_token value from environment variables or config file.
urllib3.connectionpool: Starting new HTTPS connection (1): account.blob.core.windows.net:443
urllib3.connectionpool: https://account.blob.core.windows.net:443 "GET /appp1355?restype=container&comp=list HTTP/1.1" 200 None
urllib3.connectionpool: https://accou t.blob.core.windows.net:443 "GET /appp1355?restype=container&comp=list&marker=2%21136%21MDAwMDU2IWZnci1pbmdlc3QvSkFUUy9jYXIvaGJyMjAwMDM1LzEvZ3JhcGhpY3MvaGJyMjAwMDM1ZjEucG5nITAwMDAyOCE5OTk5LTEyLTMxVDIzOjU5OjU5Ljk5OTk5OTlaIQ-- HTTP/1.1" 200 None
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.2
PSEdition                      Core
GitCommitId                    7.4.2
OS                             CBL-Mariner/Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-…
Script     8.0.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMA…
Script     7.6.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCer…
Script     7.1.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplate…
Script     7.0.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-Az…
Script     1.1.3                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, …
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADD…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
PS /home/user> Resolve-AzError


PS /home/user>
```

**Comment by blueww** [comment]
@cl33n 

`az storage blob list` is not Powershell cmdlet, it's Azure CLI command.
Please file the issue in Azure CLI github repo: https://github.com/Azure/azure-cli/issues

I will close this issue as it's not Azure Powershell issue.
Feel free to contact us again if need any further assistance on Azure Powershell.
