### ISSUE TITLE
https://sqlassess.blob.core.windows.net/app/SqlAssessment.zip not accessible

### ISSUE THREAD

**Issue by andy-mitchell** [Azure/azure-powershell#25307]
### Description

Running Get-AzDataMigrationAssessment downloads https://sqlassess.blob.core.windows.net/app/SqlAssessment.zip  which returns 

### Issue script & Debug output

```PowerShell
Invoke-RestMethod : The remote name could not be resolved: 'sqlassess.blob.core.windows.net'
At C:\Program Files\WindowsPowerShell\Modules\Az.DataMigration\0.14.6\DataMigration.Autorest\custom\Cmdlets\Get-AzDataMigrationAssessment.ps1:88 char:17
+ ...             Invoke-RestMethod -Uri $ZipSource -OutFile $ZipDestinatio ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.20348.2400
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.2400
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.0.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault...}
Script     0.14.6     Az.DataMigration                    {Get-AzDataMigrationProject, Get-AzDataMigrationService, Get-AzDataMigrationTask, Invoke-AzDataMigrationCommand...}
```

### Error output

```PowerShell
DEBUG: Got version 0 of Az
DEBUG: Got version 0 of Az.Accounts
DEBUG: 9:58:34 AM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 9:58:34 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 9:58:35 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 9:58:35 AM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].


   HistoryId: 7


Message        : The remote name could not be resolved: 'sqlassess.blob.core.windows.net'
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
Exception      : System.Net.WebException
InvocationInfo : {Invoke-RestMethod}
Line           :                 Invoke-RestMethod -Uri $ZipSource -OutFile $ZipDestination;

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.DataMigration\0.14.6\DataMigration.Autorest\custom\Cmdlets\Get-AzDataMigrationAssessment.ps1:88 char:17
                 + ...             Invoke-RestMethod -Uri $ZipSource -OutFile $ZipDestinatio ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

DEBUG: 9:58:35 AM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].


   HistoryId: 5


Message        : The remote name could not be resolved: 'sqlassess.blob.core.windows.net'
StackTrace     :    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                    at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
Exception      : System.Net.WebException
InvocationInfo : {Invoke-RestMethod}
Line           :                 Invoke-RestMethod -Uri $ZipSource -OutFile $ZipDestination;

Position       : At C:\Program Files\WindowsPowerShell\Modules\Az.DataMigration\0.14.6\DataMigration.Autorest\custom\Cmdlets\Get-AzDataMigrationAssessment.ps1:88 char:17
                 + ...             Invoke-RestMethod -Uri $ZipSource -OutFile $ZipDestinatio ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5



DEBUG: 9:58:35 AM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 9:58:35 AM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:3.0.0; CommandName: Resolve-AzError; PSVersion: 5.1.20348.2400; IsSuccess: True; Duration: 00:00:00.2679350; SanitizeDuration: 00:00:00.0088155
DEBUG: 9:58:35 AM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 9:58:35 AM - ResolveError end processing.
```

**Comment by isra-fel** [comment]
Thanks for reporting. Let me loop in the engineering team.

**Comment by tonyg0988** [comment]
@rgreenMSFT any update. facing the same issue.

**Comment by isra-fel** [comment]
Hi @andy-mitchell @tonyg0988 the engineering team has brought back the link. Could you try it again?

**Comment by tonyg0988** [comment]
@isra-fel  it's working now. Thanks for the help.

**Comment by abhims14** [comment]
We would recommend updating and use the latest version of Az.DataMigration to avoid any known issues. 

Try uninstall the older version, validate and install the latest version
PS C:\WINDOWS\system32> Uninstall-Module -Name Az.DataMigration
PS C:\WINDOWS\system32> Get-Module -ListAvailable -Name Az.DataMigration
PS C:\WINDOWS\system32> Install-Module -Name Az.DataMigration

Or

Please download the latest version from https://www.powershellgallery.com/packages/Az.DataMigration
