### ISSUE TITLE
AzCopy is not recognized in CloudShell

### ISSUE THREAD

**Issue by Toxifera** [Azure/azure-powershell#25420]
### Description

I was able to use "azcopy" cmdlet to transfer between storages, it was working ok. But as of today 1st of July 24", it cannot find the commandlet and returns error.
![azcopy_notfound](https://github.com/Azure/azure-powershell/assets/10058722/f8857ced-0ea5-4430-a02a-dfb91655cf28)

### Script or Debug output

```PowerShell
> azcopy
azcopy: The term 'azcopy' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

### Environment data

```PowerShell
$PSVersionTable            

Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             CBL-Mariner/Linux
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzCo…
Script     8.0.0                 Az.Compute                          {Add-AzImageDataDisk, Add-AzVhd, Add-AzVMAddit…
Script     7.6.0                 Az.Network                          {Add-AzApplicationGatewayAuthenticationCertifi…
Script     7.1.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec…
Script     7.0.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStor…
Script     1.1.3                 Az.Tools.Predictor                  {Disable-AzPredictor, Enable-AzPredictor, Open…
Script     0.0.0.10              AzureAD.Standard.Preview            {Add-AzureADApplicationOwner, Add-AzureADDevic…
Script     0.9.3                 AzurePSDrive
```

### Error output

```PowerShell
DEBUG: 2:51:16 PM - [ConfigManager] Got [True] from [DisplaySecretsWarning], Module = [], Cmdlet = [].
DEBUG: 2:51:16 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 2:51:16 PM - using account id '***@****'...
DEBUG: 2:51:16 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 2:51:16 PM - [ConfigManager] Got [True] from [DisplaySecretsWarning], Module = [], Cmdlet = [].

   HistoryId: 3

Message        : The term 'azcopy' is not recognized as a name of a cmdlet, function, script file, or executable 
                 program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try 
                 again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, 
                 CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin 
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean 
                 dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, 
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] 
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, 
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at 
                 System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : azcopy
Position       : At line:1 char:1
                 + azcopy
                 + ~~~~~~
HistoryId      : 3

DEBUG: 2:51:16 PM - [ConfigManager] Got [True] from [DisplaySecretsWarning], Module = [], Cmdlet = [].

   HistoryId: 1

Message        : The term 'azcopy' is not recognized as a name of a cmdlet, function, script file, or executable 
                 program.
                 Check the spelling of the name, or if a path was included, verify that the path is correct and try 
                 again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, 
                 CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin 
                 commandOrigin, ExecutionContext context)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean 
                 dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, 
                 CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] 
                 redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, 
                 CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, 
                 CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at 
                 System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                 frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : azcopy
Position       : At line:1 char:1
                 + azcopy
                 + ~~~~~~
HistoryId      : 1



DEBUG: 2:51:16 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 2:51:16 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:3.0.0; CommandName: Resolve-AzError; PSVersion: 7.4.3; IsSuccess: True; Duration: 00:00:00.0321876; SanitizeDuration: 00:00:00.0085854
DEBUG: 2:51:16 PM - [ConfigManager] Got [True] from [EnableDataCollection], Module = [], Cmdlet = [].
DEBUG: 2:51:16 PM - ResolveError end processing.
```

**Comment by isra-fel** [comment]
Thanks for reporting! CloudShell is not part of Azure PowerShell so please track the issue here: https://github.com/Azure/CloudShell/issues/450
