### ISSUE TITLE
Update-AzDatabricksWorkspace is not working in Az.Databricks-v1.8.0

### ISSUE THREAD

**Issue by v-vyedavelly** [Azure/azure-powershell#25743]
### Description

Update-AzDAtabricksWorkspace is failing with keyvault error even we are not updating anything related to encryption/keyvalut. 
We tried to update tags here,but the tags update is failing with keyvault details error. 
It worked during my development but same is not working in released version.

Can you please check and help to resolve ASAP ,we see the error is coming from New-AzDatabricksWorkspace_CreateViaIdentity 
,which is an autogenerated file ,we didnt modify any code related to this from our end .

![image](https://github.com/user-attachments/assets/9adf54e0-a236-4bb1-8ae0-b8f48737d0b0)

### Issue script & Debug output

```PowerShell
PS C:\Users\v-vyedavelly> Update-AzDatabricksWorkspace -Name "vnetwsarmtemplate" -ResourceGroupName "PStesting0711" -Sku "Premium"  -Tag @{test= "tag11"} -SubscriptionId 0140911e-1040-48da-8bc9-b99fb3dd88a6
DEBUG: 11:19:24 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Databricks/workspaces/vnetwsarmtemplate?api-version=2024-05-01
DEBUG: RequestCreated: /subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Databricks/workspaces/vnetwsarmtemplate?api-version=2024-05-01
DEBUG: HeaderParametersAdded:
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Databricks/workspaces/vnetwsarmtemplate?api-version=2024-05-01

Headers:
x-ms-unique-id                : 2
x-ms-client-request-id        : e6e67cc2-1d39-42b1-9908-b6dba25739bb
CommandName                   : Get-AzDatabricksWorkspace
FullCommandName               : Get-AzDatabricksWorkspace_Get
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v12.1.0,PSVersion/v7.4.4,Az.Databricks/1.8.0

Body:



DEBUG: 11:19:24 PM - [ConfigManager] Got nothing from [DisableInstanceDiscovery], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: BeforeCall:
DEBUG: 11:19:24 PM - [ConfigManager] Got [False] from [EnableLoginByWam], Module = [], Cmdlet = [].
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-resource-requests: 1799
x-ms-request-id               : eastus2:1d6fcd3d-b263-4e0b-938b-d4e267772d66
x-ms-correlation-request-id   : f1eebd27-b7f9-49b1-84af-a20d878565e1
x-ms-routing-request-id       : WESTUS2:20240805T061925Z:f1eebd27-b7f9-49b1-84af-a20d878565e1
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
X-Cache                       : CONFIG_NOCACHE
X-MSEdge-Ref                  : Ref A: C0B1F381F48A43BDA20D8337C587E55F Ref B: CO6AA3150218045 Ref C: 2024-08-05T06:19:24Z
Date                          : Mon, 05 Aug 2024 06:19:24 GMT

Body:
{
  "properties": {
    "isUcEnabled": true,
    "enhancedSecurityCompliance": {
      "automaticClusterUpdate": {
        "value": "Enabled"
      },
      "complianceSecurityProfile": {
        "complianceStandards": [],
        "value": "Disabled"
      },
      "enhancedSecurityMonitoring": {
        "value": "Enabled"
      }
    },
    "managedResourceGroupId": "/subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/databricks-rg-vnetwsarmtemplate-izvkluyqrj5jw",
    "parameters": {
      "customPrivateSubnetName": {
        "type": "String",
        "value": "private-subnet"
      },
      "customPublicSubnetName": {
        "type": "String",
        "value": "public-subnet"
      },
      "customVirtualNetworkId": {
        "type": "String",
        "value": "/subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Network/virtualNetworks/databricks-vnet"
      },
      "enableFedRampCertification": {
        "type": "Bool",
        "value": false
      },
      "enableNoPublicIp": {
        "type": "Bool",
        "value": true
      },
      "prepareEncryption": {
        "type": "Bool",
        "value": false
      },
      "publicIpName": {
        "type": "String",
        "value": "nat-gw-public-ip"
      },
      "requireInfrastructureEncryption": {
        "type": "Bool",
        "value": false
      },
      "resourceTags": {
        "type": "Object",
        "value": {
          "application": "databricks",
          "databricks-environment": "true"
        }
      },
      "storageAccountName": {
        "type": "String",
        "value": "dbstorageggedizvolohh6"
      },
      "storageAccountSkuName": {
        "type": "String",
        "value": "Standard_GRS"
      },
      "vnetAddressPrefix": {
        "type": "String",
        "value": "10.139"
      }
    },
    "provisioningState": "Succeeded",
    "authorizations": [
      {
        "principalId": "9a74af6f-d153-4348-988a-e2672920bee9",
        "roleDefinitionId": "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
      }
    ],
    "createdBy": {
      "oid": "a3209571-f019-4f59-bbbd-bff727a2d865",
      "puid": "100320020BBEDA85",
      "applicationId": "c44b4083-3bb0-49c1-b47d-974e53cbdf3c"
    },
    "updatedBy": {
      "oid": "a3209571-f019-4f59-bbbd-bff727a2d865",
      "puid": "100320020BBEDA85",
      "applicationId": "1950a258-227b-4e31-a9cf-717495945fc2"
    },
    "workspaceId": "2751319810863686",
    "workspaceUrl": "adb-2751319810863686.6.azuredatabricks.net",
    "createdDateTime": "2024-07-11T20:50:29.5631042Z"
  },
  "id": "/subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Databricks/workspaces/vnetwsarmtemplate",
  "name": "vnetwsarmtemplate",
  "type": "Microsoft.Databricks/workspaces",
  "sku": {
    "name": "premium",
    "tier": "Premium"
  },
  "location": "eastus2",
  "tags": {
    "test": "tag112"
  },
  "systemData": {
    "createdBy": "v-vyedavelly@microsoft.com",
    "createdByType": "User",
    "createdAt": "2024-07-11T13:50:29.5148327-07:00",
    "lastModifiedBy": "v-vyedavelly@microsoft.com",
    "lastModifiedByType": "User",
    "lastModifiedAt": "2024-07-12T12:49:28.5231695-07:00"
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
DEBUG: 11:19:24 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: [CmdletBeginProcessing]: Starting command
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: /subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Databricks/workspaces/vnetwsarmtemplate?api-version=2024-05-01
DEBUG: RequestCreated: /subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Databricks/workspaces/vnetwsarmtemplate?api-version=2024-05-01
DEBUG: HeaderParametersAdded:
DEBUG: BodyContentSet:
DEBUG: 11:19:25 PM - [ConfigManager] Got nothing from [DisableInstanceDiscovery], Module = [], Cmdlet = []. Returning default value [False].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Databricks/workspaces/vnetwsarmtemplate?api-version=2024-05-01

Headers:
x-ms-unique-id                : 3
x-ms-client-request-id        : 8d5f12c0-2f06-4c18-b727-a02f5640a9e9
CommandName                   : Az.Databricks.private\New-AzDatabricksWorkspace_CreateViaIdentity
FullCommandName               : New-AzDatabricksWorkspace_CreateViaIdentity
ParameterSetName              : __AllParameterSets
User-Agent                    : AzurePowershell/v12.1.0,PSVersion/v7.4.4,Az.Databricks/1.8.0

Body:
{
  "tags": {
    "test": "tag11"
  },
  "location": "eastus2",
  "properties": {
    "parameters": {
      "customVirtualNetworkId": {
        "value": "/subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/PStesting0711/providers/Microsoft.Network/virtualNetworks/databricks-vnet"
      },
      "customPublicSubnetName": {
        "value": "public-subnet"
      },
      "customPrivateSubnetName": {
        "value": "private-subnet"
      },
      "enableNoPublicIp": {
        "value": true
      },
      "publicIpName": {
        "value": "nat-gw-public-ip"
      },
      "prepareEncryption": {
        "value": false
      },
      "requireInfrastructureEncryption": {
        "value": false
      },
      "storageAccountName": {
        "value": "dbstorageggedizvolohh6"
      },
      "storageAccountSkuName": {
        "value": "Standard_GRS"
      },
      "vnetAddressPrefix": {
        "value": "10.139"
      }
    },
    "encryption": {
      "entities": {
        "managedServices": {
          "keySource": "Microsoft.Keyvault"
        },
        "managedDisk": {
          "keySource": "Microsoft.Keyvault"
        }
      }
    },
    "enhancedSecurityCompliance": {
      "automaticClusterUpdate": {
        "value": "Enabled"
      },
      "complianceSecurityProfile": {
        "complianceStandards": [],
        "value": "Disabled"
      },
      "enhancedSecurityMonitoring": {
        "value": "Enabled"
      }
    },
    "managedResourceGroupId": "/subscriptions/0140911e-1040-48da-8bc9-b99fb3dd88a6/resourceGroups/databricks-rg-vnetwsarmtemplate-izvkluyqrj5jw",
    "authorizations": [
      {
        "principalId": "9a74af6f-d153-4348-988a-e2672920bee9",
        "roleDefinitionId": "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
      }
    ]
  },
  "sku": {
    "name": "premium",
    "tier": "Premium"
  }
}


DEBUG: 11:19:25 PM - [ConfigManager] Got [False] from [EnableLoginByWam], Module = [], Cmdlet = [].
DEBUG: BeforeCall:
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-resource-requests: 149
x-ms-request-id               : eastus2:58a233ad-6cde-4bb3-90d2-6bde61bc8b91
x-ms-correlation-request-id   : 206f4fa9-a83e-4d04-a2b2-828cc0e2d7fa
x-ms-routing-request-id       : WESTUS2:20240805T061927Z:206f4fa9-a83e-4d04-a2b2-828cc0e2d7fa
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
X-Cache                       : CONFIG_NOCACHE
X-MSEdge-Ref                  : Ref A: CE8DF3CBE25E4E35BE7E679F1AA7462E Ref B: CO6AA3150218045 Ref C: 2024-08-05T06:19:25Z
Date                          : Mon, 05 Aug 2024 06:19:26 GMT

Body:
{
  "error": {
    "code": "InvalidEncryptionEntitiesKeyVaultValue",
    "message": "The keysource is specified as keyvault but keyvault details are not correctly provided."
  }
}


DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
New-AzDatabricksWorkspace_CreateViaIdentity: C:\Program Files\WindowsPowerShell\Modules\Az.Databricks\1.8.0\Databricks.Autorest\custom\Update-AzDatabricksWorkspace.ps1:498
Line |
 498 |  …             Az.Databricks.private\New-AzDatabricksWorkspace_CreateVia …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The keysource is specified as keyvault but keyvault details are not correctly provided.
DEBUG: [Finally]: Getting exception 'Microsoft.Azure.Commands.Common.Exceptions.AzPSCloudException: InternalException' from response
DEBUG: Finally:
DEBUG: CmdletAfterAPICall:
DEBUG: [CmdletProcessRecordAsyncEnd]: Finish HTTP process
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletProcessRecordEnd:
DEBUG: 11:19:26 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Databricks:1.8.0; CommandName: Update-AzDatabricksWorkspace; PSVersion: 7.4.4; IsSuccess: False; Duration: 00:00:02.5696622; SanitizeDuration: 00:00:00; Exception: InternalException;
```

### Environment data

```PowerShell
PS C:\Users\v-vyedavelly> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Users\v-vyedavelly> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.1                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     1.8.0                 Az.Databricks                       {Get-AzDatabricksAccessConnector, Get-AzDatabricksOutboundNetworkDepend…
```

### Error output

```PowerShell
PS C:\Users\v-vyedavelly> Resolve-AzError
DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:22:28 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 11:22:28 PM - using account id 'v-vyedavelly@microsoft.com'...
DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 8

Message        : [InvalidEncryptionEntitiesKeyVaultValue] : The keysource is specified as keyvault but keyvault details are not correctly
                 provided.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {New-AzDatabricksWorkspace_CreateViaIdentity}
Line           :                 Az.Databricks.private\New-AzDatabricksWorkspace_CreateViaIdentity -InputObject $workspace -Parameter
                 $workspace @PSBoundParameters

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\Az.Databricks\1.8.0\Databricks.Autorest\custom\Update-AzDatabricksWorkspace.ps1:498 char:17
                 + …             Az.Databricks.private\New-AzDatabricksWorkspace_CreateVia …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 8

DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 5

Message        : [InvalidEncryptionEntitiesKeyVaultValue] : The keysource is specified as keyvault but keyvault details are not correctly
                 provided.
StackTrace     :
Exception      : System.Exception
InvocationInfo : {New-AzDatabricksWorkspace_CreateViaIdentity}
Line           :                 Az.Databricks.private\New-AzDatabricksWorkspace_CreateViaIdentity -InputObject $workspace -Parameter
                 $workspace @PSBoundParameters

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\Az.Databricks\1.8.0\Databricks.Autorest\custom\Update-AzDatabricksWorkspace.ps1:498 char:17
                 + …             Az.Databricks.private\New-AzDatabricksWorkspace_CreateVia …
                 +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 5

DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 3

Message        : The property 'SkuTier' cannot be found on this object. Verify that the property exists and can be set.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at Microsoft.PowerShell.Executor.ExecuteCommandHelper(Pipeline tempPipeline, Exception& exceptionThrown,
                 ExecutionOptions options)
Exception      : System.Management.Automation.RuntimeException
InvocationInfo : {}
Line           :                 $workspace.SkuTier = $SkuTier

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\Az.Databricks\1.8.0\Databricks.Autorest\custom\Update-AzDatabricksWorkspace.ps1:429 char:17
                 +                 $workspace.SkuTier = $SkuTier
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
Message        : Authentication failed against tenant 72f988bf-86f1-41af-91ab-2d7cd011db47. User interaction is required. This may be due to
                 the conditional access policy settings such as multi-factor authentication (MFA). If you need to access subscriptions in
                 that tenant, please rerun 'Connect-AzAccount' with additional parameter '-TenantId 72f988bf-86f1-41af-91ab-2d7cd011db47'.
StackTrace     :    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account,
                 IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction,
                 IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account,
                 IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, String
                 resourceId)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass15_0.<AuthorizeRequest>b__0()
                    at System.Threading.Tasks.Task`1.InnerInvoke()
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
                 executionContext, ContextCallback callback, Object state)
                 --- End of stack trace from previous location ---
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext
                 executionContext, ContextCallback callback, Object state)
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.Commands.Common.ContextAdapter.AuthorizeRequest(IAzureContext context, HttpRequestMessage request,
                 CancellationToken cancellationToken, String endpointResourceIdKey, String endpointSuffixKey, Func`6 tokenAudienceConverter,
                 IDictionary`2 extensibleParamters)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.AuthenticationHelper(IAzureContext context, String
                 endpointResourceIdKey, String endpointSuffixKey, HttpRequestMessage request, CancellationToken cancelToken, Action
                 cancelAction, Func`4 signal, Func`5 next, Func`6 tokenAudienceConverter)
                    at Microsoft.Azure.Commands.Common.ContextAdapter.<>c__DisplayClass14_0.<<SendHandler>b__0>d.MoveNext()
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.PowerShell.Cmdlets.Databricks.Databricks.WorkspacesGet_Call(HttpRequestMessage request, Func`3 onOk,
                 Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Databricks.Databricks.WorkspacesGet_Call(HttpRequestMessage request, Func`3 onOk,
                 Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Databricks.Databricks.WorkspacesGet(String resourceGroupName, String
                 workspaceName, String subscriptionId, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Databricks.Cmdlets.GetAzDatabricksWorkspace_Get.ProcessRecordAsync()
                    at Microsoft.Azure.PowerShell.Cmdlets.Databricks.Cmdlets.GetAzDatabricksWorkspace_Get.ProcessRecordAsync()
Exception      : Microsoft.Azure.Commands.Common.Exceptions.AzPSAuthenticationFailedException
InvocationInfo : {Get-AzDatabricksWorkspace_Get}
Line           :             $workspace = Get-AzDatabricksWorkspace @PSBoundParameters

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\Az.Databricks\1.8.0\Databricks.Autorest\custom\Update-AzDatabricksWorkspace.ps1:390 char:13
                 +             $workspace = Get-AzDatabricksWorkspace @PSBoundParameters
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
Message        : SharedTokenCacheCredential authentication unavailable. Token acquisition failed for user v-vyedavelly@microsoft.com. Ensure
                 that you have authenticated with a developer tool that supports Azure single sign on.
StackTrace     :    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean
                 isCredentialUnavailable)
                    at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext,
                 CancellationToken cancellationToken)
                    at Azure.Identity.SharedTokenCacheCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken
                 cancellationToken)
                    at Microsoft.Azure.PowerShell.Authenticators.MsalAccessToken.GetAccessTokenAsync(String callerClassName, String
                 parametersLog, TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken,
                 String tenantId, String userId, String homeAccountId)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account,
                 IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction,
                 IAzureTokenCache tokenCache, String resourceId)
Exception      : Azure.Identity.CredentialUnavailableException
InvocationInfo : {Get-AzDatabricksWorkspace_Get}
Line           :             $workspace = Get-AzDatabricksWorkspace @PSBoundParameters

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\Az.Databricks\1.8.0\Databricks.Autorest\custom\Update-AzDatabricksWorkspace.ps1:390 char:13
                 +             $workspace = Get-AzDatabricksWorkspace @PSBoundParameters
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
Message        : No Refresh Token found in the cache.
StackTrace     :    at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()
                 --- End of stack trace from previous location ---
                    at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)
                    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters
                 commonParameters, AcquireTokenSilentParameters silentParameters, CancellationToken cancellationToken)
                    at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1
                 builder, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenSilentCoreAsync(String[] scopes, String claims, IAccount account, String
                 tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.MsalPublicClient.AcquireTokenSilentAsync(String[] scopes, String claims, IAccount account, String
                 tenantId, Boolean enableCae, Boolean async, CancellationToken cancellationToken)
                    at Azure.Identity.SharedTokenCacheCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext,
                 CancellationToken cancellationToken)
Exception      : Microsoft.Identity.Client.MsalUiRequiredException
InvocationInfo : {Get-AzDatabricksWorkspace_Get}
Line           :             $workspace = Get-AzDatabricksWorkspace @PSBoundParameters

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\Az.Databricks\1.8.0\Databricks.Autorest\custom\Update-AzDatabricksWorkspace.ps1:390 char:13
                 +             $workspace = Get-AzDatabricksWorkspace @PSBoundParameters
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3



DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:3.0.1; CommandName: Resolve-AzError; PSVersion: 7.4.4; IsSuccess: True; Duration: 00:00:00.1651397; SanitizeDuration: 00:00:00.0139880
DEBUG: 11:22:28 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 11:22:28 PM - ResolveError end processing.
PS C:\Users\v-vyedavelly>
```

**Comment by v-vyedavelly** [comment]
In 1.8.0 version during workspace tag update command call , cli is sending empty keyvault details in the body ,so databricks service is validating and sending the error .
 
"encryption": {
      "entities": {
        "managedServices": {
          "keySource": "Microsoft.Keyvault"
        },
        "managedDisk": {
          "keySource": "Microsoft.Keyvault"
        }
      }
    },
 
 
In 1.7.0 tag update is not sending any keyvault details .

**Comment by v-vyedavelly** [comment]
Hello @Alex-wdy , Can you help to triage this on priority. Let u know if you need any details from Azure Databricks side.

**Comment by v-vyedavelly** [comment]
Hello @Alex-wdy, Issue not yet assigned to anyone. Can you assign someone from powershell team to investigate.

**Comment by Alex-wdy** [comment]
@lijinpei2008  can you help in this issue?
