### ISSUE TITLE
Get-AzWebApp bug when using new loadBalancing options (e.g. LeastRequestsWithTieBreaker)

### ISSUE THREAD

**Issue by falk0069** [Azure/azure-powershell#26006]
### Description

The latest App Service Platform update added two new loadBalancing options:  LeastRequestsWithTieBreaker and PerSiteRoundRobin.

A deserialize error will occur when running a PowerShell command on an app service which one of these loadBalancing options set.  Command example:
`$webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App`

The error:
`Get-AzWebApp: Unable to deserialize the response.`

This is a sample AZ CLI that can be used to update the loadBalancing option:
`az webapp config set -g $RG -n $App --slot "staging" --generic-configurations "{'loadBalancing':'LeastRequestsWithTieBreaker'}"`

### Issue script & Debug output

```PowerShell
PS H:\> $DebugPreference='Continue'
PS H:\> $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
DEBUG: 4:33:18 PM - GetAzureWebAppCmdlet begin processing with ParameterSet 'S1'.
...
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ab098aae-b72c-4d8c-bd98-81be3ba6ed95] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ab098aae-b72c-4d8c-bd98-81be3ba6ed95] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ab098aae-b72c-4d8c-bd98-81be3ba6ed95] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ab098aae-b72c-4d8c-bd98-81be3ba6ed95] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ab098aae-b72c-4d8c-bd98-81be3ba6ed95] IsLegacyAdalCacheEnabled: yes
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z] Found 1 cache accounts and 0 broker accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z] Returning 1 accounts
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] MSAL MSAL.NetCore with assembly version '4.49.1.
0'. CorrelationId(ffeae322-ec94-4923-9d7d-c94250100579)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] === AcquireTokenSilent Parameters ===
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] LoginHint provided: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] Account provided: True
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net//.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenSilent
IsConfidentialClient - False
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - ffeae322-ec94-4923-9d7d-c94250100579
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] === Token Acquisition (SilentRequest) started:
         Scopes: https://management.core.windows.net//.default
        Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] Access token is not expired. Returning the found cache entry. [Current time (09/03/2024 16:33:18) - Expiration Time (09/03/2024 17:06:26 +00:00) - Extended Expiration Time (09/03/2024 17:06:26 +00:00)]
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] Returning access token found in cache. RefreshOn exists ? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579] 
        === Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.7 Microsoft Windows 10.0.14393 [2024-09-03 16:33:18Z - ffeae322-ec94-4923-9d7d-c94250100579]  AT expiration time: 9/3/2024 5:06:26 PM +00:00, scopes: https://management.core.windows.net//user_impersonation https://management.core.windows.net//.default. source: Cache
DEBUG: SharedTokenCacheCredential.GetToken succeeded. Scopes: [ https://management.core.windows.net//.default ] ParentRequestId:  ExpiresOn: 2024-09-03T17:06:26.0000000+00:00
DEBUG: [Common.Authentication]: Received token with LoginType 'User', Tenant: 'df722068-5fa4-4ebb-9e7f-1aa5ffa6b96f', UserId: 'ads.afalk@accenture.com'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/...?api-version=2021-01-15

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 55f75ca0-9e15-40bc-9fd2-8f0311155b40

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
ETag                          : "..."
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 89aa56ee-ce73-40b9-bae3-97eb12d0daaf
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 499
x-ms-ratelimit-remaining-subscription-global-reads: 7499
x-ms-correlation-request-id   : e4bbc89f-84d6-4033-921b-f6ef30232ecd
x-ms-routing-request-id       : CENTRALUS:20240903T163318Z:...
X-Content-Type-Options        : nosniff
X-Cache                       : CONFIG_NOCACHE
X-MSEdge-Ref                  : Ref A: ... Ref B: ... Ref C: 2024-09-03T16:33:18Z
Date                          : Tue, 03 Sep 2024 16:33:18 GMT

Body:
{
  "id": "/subscriptions/...",
 ...
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/.../config/web?api-version=2021-01-15

Headers:
Accept-Language               : en-US
x-ms-client-request-id        : 55f75ca0-9e15-40bc-9fd2-8f0311155b40

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 5640aa7e-3a06-4a53-8d39-7ec2d7a419c4
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-reads: 499
x-ms-ratelimit-remaining-subscription-global-reads: 7499
x-ms-correlation-request-id   : 544d2488-60a9-4eee-9355-c888e21c5e58
x-ms-routing-request-id       : CENTRALUS:20240903T163319Z:544d2488-60a9-4eee-9355-c888e21c5e58
X-Content-Type-Options        : nosniff
X-Cache                       : CONFIG_NOCACHE
X-MSEdge-Ref                  : Ref A: D73F5EC7542C412C8E974386290A185C Ref B: DM2AA1091213011 Ref C: 2024-09-03T16:33:18Z
Date                          : Tue, 03 Sep 2024 16:33:19 GMT

Body:
{
  "id": "/subscriptions/.../config/web",
...
  },
  "properties": {
    "numberOfWorkers": 1,
    "defaultDocuments": [],
    "netFrameworkVersion": "v4.0",
    "phpVersion": "",
    "pythonVersion": "",
    "nodeVersion": "",
    "powerShellVersion": "",
    "linuxFxVersion": "",
    "windowsFxVersion": "",
    "windowsConfiguredStacks": [],
    "requestTracingEnabled": false,
    "remoteDebuggingEnabled": false,
    "remoteDebuggingVersion": null,
    "httpLoggingEnabled": false,
    "azureMonitorLogCategories": [
      ""
    ],
    "acrUseManagedIdentityCreds": false,
    "acrUserManagedIdentityID": "",
    "logsDirectorySizeLimit": 35,
    "detailedErrorLoggingEnabled": false,
    "publishingUsername": "...",
    "publishingPassword": null,
    "appSettings": null,
    "metadata": null,
    "connectionStrings": null,
    "machineKey": null,
    "handlerMappings": null,
    "documentRoot": null,
    "scmType": "None",
    "use32BitWorkerProcess": false,
    "webSocketsEnabled": false,
    "alwaysOn": true,
    "javaVersion": null,
    "javaContainer": null,
    "javaContainerVersion": null,
    "appCommandLine": "",
    "managedPipelineMode": "Integrated",
    "virtualApplications": [
      {
        "virtualPath": "/",
        "physicalPath": "site\\wwwroot",
        "preloadEnabled": true,
        "virtualDirectories": null
      }
    ],
    "winAuthAdminState": 0,
    "winAuthTenantState": 0,
    "customAppPoolIdentityAdminState": false,
    "customAppPoolIdentityTenantState": false,
    "runtimeADUser": null,
    "runtimeADUserPassword": null,
    "loadBalancing": "LeastRequestsWithTieBreaker",  <---- PLACE WITH ISSUE
    "routingRules": [],
    "experiments": {
      "rampUpRules": []
    },
...
  }
}


DEBUG: 4:33:19 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
Get-AzWebApp: Unable to deserialize the response.
DEBUG: 4:33:19 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 4:33:19 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Websites:3.1.0; CommandName: Get-AzWebApp; PSVersion: 7.4.4; IsSuccess: False; Duration: 00:00:01.6474621; Exception: Unable to deserialize the response.;
DEBUG: 4:33:19 PM - GetAzureWebAppCmdlet end processing.
```

### Environment data

```PowerShell
PS H:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.4
PSEdition                      Core
GitCommitId                    7.4.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS H:\> Get-InstalledModule -Name Az

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
12.3.0               Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This mod…

PS H:\> Get-Module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.12.5                Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     3.1.0                 Az.Websites                         {Add-AzWebAppAccessRestrictionRule, Add-AzWebAppTrafficRouting, Edit-AzWebAppBackupConfiguration, Get-AzAppServiceEnvir…
```

### Error output

```PowerShell
PS H:\> Resolve-AzError
DEBUG: 4:43:15 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 4:43:15 PM - using account id 'ads.afalk@accenture.com'...
DEBUG: 4:43:15 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 23

Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.WebSites.WebAppsOperations.GetConfigurationWithHttpMessagesAsync(String resourceGroupName, String name, Dictionary`2 customHeaders,
                 CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.GetConfigurationAsync(IWebAppsOperations operations, String resourceGroupName, String name,
                 CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.GetConfiguration(IWebAppsOperations operations, String resourceGroupName, String name)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.GetWebAppConfiguration(String resourceGroupName, String webSiteName, String slotName, Site site, Boolean
                 ignoreError)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.GetWebApp(String resourceGroupName, String webSiteName, String slotName, Boolean ignoreError)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzWebApp}
Line           : $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
Position       : At line:1 char:11
                 + $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 23

Message        : Error converting value "LeastRequestsWithTieBreaker" to type 'System.Nullable`1[Microsoft.Azure.Management.WebSites.Models.SiteLoadBalancing]'. Path
                 'properties.loadBalancing', line 1, position 1732.
StackTrace     :    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
                    at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperations.GetConfigurationWithHttpMessagesAsync(String resourceGroupName, String name, Dictionary`2 customHeaders,
                 CancellationToken cancellationToken)
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {Get-AzWebApp}
Line           : $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
Position       : At line:1 char:11
                 + $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 23

Message        : Requested value 'LeastRequestsWithTieBreaker' was not found.
StackTrace     :    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
                    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
Exception      : System.ArgumentException
InvocationInfo : {Get-AzWebApp}
Line           : $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
Position       : At line:1 char:11
                 + $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 23


   HistoryId: 9

Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.WebSites.WebAppsOperations.GetConfigurationWithHttpMessagesAsync(String resourceGroupName, String name, Dictionary`2 customHeaders,
                 CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.GetConfigurationAsync(IWebAppsOperations operations, String resourceGroupName, String name,
                 CancellationToken cancellationToken)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.GetConfiguration(IWebAppsOperations operations, String resourceGroupName, String name)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.GetWebAppConfiguration(String resourceGroupName, String webSiteName, String slotName, Site site, Boolean
                 ignoreError)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.GetWebApp(String resourceGroupName, String webSiteName, String slotName, Boolean ignoreError)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.GetAzureWebAppCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzWebApp}
Line           : $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
Position       : At line:1 char:11
                 + $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9

Message        : Error converting value "LeastRequestsWithTieBreaker" to type 'System.Nullable`1[Microsoft.Azure.Management.WebSites.Models.SiteLoadBalancing]'. Path
                 'properties.loadBalancing', line 1, position 1732.
StackTrace     :    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
                    at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.WebSites.WebAppsOperations.GetConfigurationWithHttpMessagesAsync(String resourceGroupName, String name, Dictionary`2 customHeaders,
                 CancellationToken cancellationToken)
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {Get-AzWebApp}
Line           : $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
Position       : At line:1 char:11
                 + $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9

Message        : Requested value 'LeastRequestsWithTieBreaker' was not found.
StackTrace     :    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
                    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
Exception      : System.ArgumentException
InvocationInfo : {Get-AzWebApp}
Line           : $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
Position       : At line:1 char:11
                 + $webApp = Get-AzWebApp -ResourceGroupName $RG -Name $App
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 9



DEBUG: 4:43:15 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:2.12.5; CommandName: Resolve-AzError; PSVersion: 7.4.4; IsSuccess: True; Duration: 00:00:00.0538638
DEBUG: 4:43:15 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 4:43:15 PM - ResolveError end processing.
```

**Comment by isra-fel** [comment]
This needs to update management SDK - I'll loop in Web App team

**Comment by VixiXia** [comment]
Hi team, the Az.Websites PowerShell module did not get the SiteLoadBalancing updated with LeastRequestsWithTieBreaker, please help fix the bug:   
Microsoft.Azure.Management.Websites.dll
![image](https://github.com/user-attachments/assets/022d91f2-763e-4639-95d9-bede12993552)

**Comment by isra-fel** [comment]
Kindly ping @antcp and @AzureAppServiceCLI

**Comment by falk0069** [comment]
@antcp and @AzureAppServiceCLI do you have any updates on when the Az.Websites PowerShell module can include the additional LeastRequestsWithTieBreaker enum?  

Thanks

**Comment by falk0069** [comment]
This is really sad that the January 2025 update did not have the fix.  These new options have been present in the API definition since April 2024.  @antcp and @AzureAppServiceCLI can you provide any updates?

[https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list?view=rest-appservice-2024-04-01&tabs=HTTP#siteloadbalancing)

**Comment by naveedaz** [comment]
Tagging @joerob-msft

**Comment by joerob-msft** [comment]
Can you try to use Az.Resources as a workaround for now? This seems to work for me.

Instead of:

$webapp = Get-AzWebAppSlot -ResourceGroupName $webappName -Name $webappName -Slot $slotName

Use:

# Get the raw resource
$resource = Get-AzResource -ResourceGroupName $resourceGroup `
                           -ResourceType "Microsoft.Web/sites/slots" `
                           -ResourceName "$appName/$slotName" `
                           -ApiVersion "2022-03-01"

**Comment by falk0069** [comment]
@joerob-msft thanks for the suggestion.  I did play with that a few months ago a little bit and could not get it to work.  We basically need to extract the WEBSITE_RUN_FROM_PACKAGE appsettings and update the value.  But all attempts I've make to edit the appSettings values failed.  If you have a code sample that can do that, I'll give it a try.

**Comment by joerob-msft** [comment]
I was able to update single app setting value by using the REST API's directly. This is how the powershell cmdlets work behind the scenes. You can use a script like this as workaround while we investigate and fix this issue.

# Define variables
$resourceGroup = "[YOUR_RG_NAME_HERE]"
$appName = "[YOUR_APP_NAME_HERE]"
$slotName = "staging" # or [YOUR_SLOT_NAME_HERE]
$appSettingKey = "APPSETTINGNAME" # [YOUR_SETTING_TO_UPDATE_HERE]
$appSettingValue = "new_value" # New value for setting

# Get access token for Azure Resource Manager
$token = (Get-AzAccessToken -ResourceUrl "https://management.azure.com").Token
$headers = @{
    "Authorization" = "Bearer $token"
    "Content-Type" = "application/json"
}

# Build the REST API URL
$subscriptionId = (Get-AzContext).Subscription.Id
$apiVersion = "2022-03-01"
$url = "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Web/sites/$appName/slots/$slotName/config/appsettings/list?api-version=$apiVersion"

# Get current app settings

$response = Invoke-RestMethod -Uri $url -Method POST -Headers $headers
# Convert PSObject to hashtable
$appSettings = @{}

$response.properties.PSObject.Properties | ForEach-Object {
    $appSettings[$_.Name] = $_.Value
}

Write-Output "Current App Settings:"
$appSettings

# Update the specific setting
$appSettings[$appSettingKey] = $appSettingValue

# The payload should be the app settings directly, not wrapped in another properties object
# Build URL for updating app settings
$updateUrl = "https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Web/sites/$appName/slots/$slotName/config/appsettings?api-version=$apiVersion"
    
# Try different payload structure
Write-Output "Attempting to update app settings..."
$result = Invoke-RestMethod -Uri $updateUrl -Method PUT -Headers $headers -Body (ConvertTo-Json -InputObject @{ properties = $appSettings } -Depth 10)
    
Write-Output "App setting $appSettingKey updated to $appSettingValue"
$result.properties

**Comment by falk0069** [comment]
@joerob-msft - this is great!  I did do some basic testing with it and it appears to be working perfectly.  I'm going to see if I can get our support team to help do a more robust test.  

One small note, is I did force a securestring because I was getting a warning that it was going to break in an upcoming release.  Just adding this in case someone else stumbles upon this thread:

```
$tokenSecure = (Get-AzAccessToken -AsSecureString -ResourceUrl "https://management.azure.com/").Token 
$token = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto([System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($tokenSecure))
```
