### ISSUE TITLE
New-AzPolicyDefinition: A parameter cannot be found that matches parameter name 'versions'

### ISSUE THREAD

**Issue by bramvdklinkenberg** [Azure/azure-powershell#26082]
### Description

I am trying to deploy a new Azure Policy Definition, but I get the error `Error processing RIVM-CPT-PRIVATELINK-ADF-AZURE-NET.json: A parameter cannot be found that matches parameter name 'versions'.`

The command I use is:
`New-AzPolicyDefinition -Name $policyContent.name -Description $policyContent.properties.description -Policy 'policy.json' -ManagementGroupName $groupId`

I came across this [issue](https://github.com/Azure/azure-powershell/issues/24971) where people have the error with regards to the parameter `depth`. The fix for this issue has some lines of code that adds something with regards to `Versions`.
I thought maybe it has something to do with it.

### Issue script & Debug output

```PowerShell
❯ New-AzPolicyDefinition -Name $policyContent.name -Description $policyContent.properties.description -Policy 'policy.json' -ManagementGroupName $groupId
Invoke-Command: C:\Users\klinkvdb\Documents\PowerShell\Modules\Az.Resources\7.4.0\Policy.Autorest\custom\New-AzPolicyDefinition.ps1:257
Line |
 257 |      $item = Invoke-Command -ScriptBlock $scriptCmd
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | A parameter cannot be found that matches parameter name 'versions'.
```

### Environment data

```PowerShell
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      5
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.4                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     7.4.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
DEBUG: Got version 0 of Az
DEBUG: Got version 0 of Az.Accounts
DEBUG: 8:41:37 AM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 8:41:37 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 8:41:37 AM - using account id '<USER_INFO>'...
DEBUG: 8:41:37 AM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 8:41:37 AM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 36

Message        : A parameter cannot be found that matches parameter name 'versions'.
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1 variablesToDefine, ErrorHandlingBehavior
                 errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                    at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo
                 invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                    at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Object[]
                 args)
                    at Microsoft.PowerShell.Commands.InvokeCommandCommand.EndProcessing()
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.Management.Automation.ParameterBindingException
InvocationInfo : {New-AzPolicyDefinition_CreateExpanded1}
Line           :     $scriptCmd = {& $wrappedCmd @calledParameters}

Position       : At C:\<USER_INFO>\PowerShell\Modules\Az.Resources\7.4.0\Policy.Autorest\custom\New-AzPolicyDefinition.ps1:256 char:33
                 +     $scriptCmd = {& $wrappedCmd @calledParameters}
                 +                                 ~~~~~~~~~~~~~~~~~
HistoryId      : 36
```

**Comment by mortenlerudjordet** [comment]
In policy.json do you have a parameter named versions?

https://learn.microsoft.com/en-us/rest/api/policy/policy-definitions/create-or-update?view=rest-policy-2023-04-01&tabs=HTTP

**Comment by bramvdklinkenberg** [comment]
Hi @mortenlerudjordet , yes. This is the template:

```
{
    "properties": {
      "displayName": "AFS-POLICY",
      "policyType": "Custom",
      "mode": "Indexed",
      "description": "Learn more at: https://aka.ms/appconfig/private-endpoint.",
      "metadata": {
        "version": "1.1.0",
        "category": "Storage"
      },
      "version": "1.1.0",
      "parameters": {
        "privateDnsZoneId": {
          "type": "String",
          "metadata": {
            "displayName": "privateDnsZoneId",
            "description": null,
            "strongType": "Microsoft.Network/privateDnsZones"
          },
          "defaultValue": "/subscriptions/<SUB_ID>/resourceGroups/<RG_NAME>/providers/Microsoft.Network/privateDnsZones/privatelink.afs.azure.net"
        },
        "effect": {
          "type": "String",
          "metadata": {
            "displayName": "Effect",
            "description": "Enable or disable the execution of the policy"
          },
          "allowedValues": [
            "DeployIfNotExists",
            "Disabled"
          ],
          "defaultValue": "DeployIfNotExists"
        }
      },
      "policyRule": {
        "if": {
          "allOf": [
            {
              "field": "type",
              "equals": "Microsoft.Network/privateEndpoints"
            },
            {
              "count": {
                "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].groupIds[*]",
                "where": {
                  "field": "Microsoft.Network/privateEndpoints/privateLinkServiceConnections[*].groupIds[*]",
                  "equals": "afs"
                }
              },
              "greaterOrEquals": 1
            }
          ]
        },
        "then": {
          "effect": "[parameters('effect')]",
          "details": {
            "type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups",
            "evaluationDelay": "AfterProvisioning",
            "roleDefinitionIds": [
              "/providers/Microsoft.Authorization/roleDefinitions/4d97b98b-1d4f-4787-a291-c67834d212e7"
            ],
            "deployment": {
              "properties": {
                "mode": "incremental",
                "template": {
                  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
                  "contentVersion": "1.0.0.0",
                  "parameters": {
                    "privateDnsZoneId": {
                      "type": "string"
                    },
                    "privateEndpointName": {
                      "type": "string"
                    },
                    "location": {
                      "type": "string"
                    }
                  },
                  "resources": [
                    {
                      "name": "[concat(parameters('privateEndpointName'), '/deployedByPolicy')]",
                      "type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups",
                      "apiVersion": "2020-03-01",
                      "location": "[parameters('location')]",
                      "properties": {
                        "privateDnsZoneConfigs": [
                          {
                            "name": "privatelink-afs",
                            "properties": {
                              "privateDnsZoneId": "[parameters('privateDnsZoneId')]"
                            }
                          }
                        ]
                      }
                    }
                  ]
                },
                "parameters": {
                  "privateDnsZoneId": {
                    "value": "[parameters('privateDnsZoneId')]"
                  },
                  "privateEndpointName": {
                    "value": "[field('name')]"
                  },
                  "location": {
                    "value": "[field('location')]"
                  }
                }
              }
            }
          }
        }
      },
      "versions": [
        "1.1.0"
      ]
    },
    "type": "Microsoft.Authorization/policyDefinitions",
    "name": "AFS-POLICY"
  }
```

**Comment by mortenlerudjordet** [comment]
From my own code that works I do not pass in versions.
Think current implementation of New-AzPolicyDefinition does not target API version that knows about versions parameter yet.

So you should be good if you remove versions from policy.json before calling New-AzPolicyDefinition

Have to wait for them to upgrade targeted api version in use for most of the policy functions in the Az-module.
There are multiple issues with them at the moment, and I have had to switch to using the API directy instead of the functions.

**Comment by mortenlerudjordet** [comment]
I also think you will need to lose the properties parent.
The structure you have will work if using the REST api directly, but the az-function does not do it the same way.

Other things to note:
parameters = parameter

Here is a picture of the custom config file I use as input to New-AzPolicyDefinition
Also note they are using capital letters at the start of the param name also.

![image](https://github.com/user-attachments/assets/b49ee025-6d17-4226-8622-88ff414fb1d7)

Confusing, yes

**Comment by bramvdklinkenberg** [comment]
Leaving out properties.versions[] did the trick!
