### ISSUE TITLE
Error downloading Module (not applicable to any other modules)

### ISSUE THREAD

**Issue by Stevea37** [Azure/azure-powershell#2612]
I have tried downloading the "Azure" module onto several different systems, including onto azure machines and I get this same error when installing:

`DEBUG: 00:06:11.9413059 System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.PathUtility.GetHttpResponse(HttpClient httpClient, String query, Request request)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__f.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task``1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadPackage(String packageName, String version, String destination, String queryUrl, NuGetRequest request, PackageSource pkgSource)
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.PathUtility.GetHttpResponse(HttpClient httpClient, String query, Request request)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.<DownloadDataToFileAsync>d__f.MoveNext()
---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
<---
WARNING: Package 'Azure' failed to download.`

**Comment by hovsepm** [comment]
@Stevea37 I'm unable to repro with `install-module Azure -Repository PSGallery`. Can you paste here commands sequence that you use?

**Comment by Stevea37** [comment]
I used exactly the same command sequence as you. I haven't actually experienced the issue today, so perhaps it was just a temporary problem, I will close the issue.
