### ISSUE TITLE
Add test coverage for Chef Extension ARM commands

### ISSUE THREAD

**Issue by NimishaS** [Azure/azure-powershell#2638]
Test coverage for https://github.com/Azure/azure-powershell/pull/2587 needs to be added

**Comment by NimishaS** [comment]
@markcowl , @hovsepm, while running these tests in `Record` mode, we got this error:
```
Test Name:	Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ChefExtensionTests.TestChefExtensionBasic
Test FullName:	Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ChefExtensionTests.TestChefExtensionBasic
Test Source:	c:\Users\azure\nim\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\ScenarioTests\ChefExtensionTests.cs : line 11
Test Outcome:	Failed
Test Duration:	0:00:00.001

Result Message:	System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure.Authentication, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)
Result StackTrace:	
at Microsoft.Azure.Test.TokenCloudCredentialsHelper.GetUserToken(String authEndpoint, String tenant, String clientId, String managementResource, String graphResource, String userName, String password)
   at Microsoft.Azure.Test.Authentication.OrgIdAuthenticationProvider.TryDoAuthentication(TestEnvironment env, IDictionary`2 settings, ExecutionMode mode, AuthorizationContext& context) in D:\workspace\test-framework-publish\Test.Framework\Authentication\OrgIdAuthenticationProvider.cs:line 31
   at Microsoft.Azure.Test.Authentication.AuthenticationProvider.Authenticate(TestEnvironment environment, IDictionary`2 settings, ExecutionMode mode) in D:\workspace\test-framework-publish\Test.Framework\Authentication\AuthenticationProvider.cs:line 28
   at Microsoft.Azure.Test.Authentication.AuthenticationProvider.Authenticate(TestEnvironment environment, IDictionary`2 settings, ExecutionMode mode) in D:\workspace\test-framework-publish\Test.Framework\Authentication\AuthenticationProvider.cs:line 30
   at Microsoft.Azure.Test.Authentication.AuthenticationProvider.Authenticate(TestEnvironment environment, IDictionary`2 settings, ExecutionMode mode) in D:\workspace\test-framework-publish\Test.Framework\Authentication\AuthenticationProvider.cs:line 30
   at Microsoft.Azure.Test.TestEnvironmentFactory.LoadTestEnvironment(String envVariableName, ExecutionMode mode) in D:\workspace\test-framework-publish\Test.Framework\TestEnvironmentFactory.cs:line 117
   at Microsoft.Azure.Test.CSMTestEnvironmentFactory.GetTestEnvironmentFromContext() in D:\workspace\test-framework-publish\Test.Framework\CSMTestEnvironmentFactory.cs:line 37
   at Microsoft.Azure.Test.TestEnvironmentFactory.GetTestEnvironment() in D:\workspace\test-framework-publish\Test.Framework\TestEnvironmentFactory.cs:line 73
   at Microsoft.Azure.Test.TestBase.GetServiceClient[T](TestEnvironmentFactory factory) in D:\workspace\test-framework-publish\Test.Framework\TestBase.cs:line 47
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.GetResourceManagementClient() in c:\Users\azure\nim\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 237
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.SetupManagementClients(MockContext context) in c:\Users\azure\nim\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 180
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.RunPsTestWorkflow(Func`1 scriptBuilder, Action`1 initialize, Action cleanup, String callingClassType, String mockName) in c:\Users\azure\nim\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 136
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.RunPsTest(String[] scripts) in c:\Users\azure\nim\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 100
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ChefExtensionTests.TestChefExtensionBasic() in c:\Users\azure\nim\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\ScenarioTests\ChefExtensionTests.cs:line 12
```
