### ISSUE TITLE
Get-AzPolicyAssignment has problems with policy name containing an ampersand &

### ISSUE THREAD

**Issue by powershellpr0mpt** [Azure/azure-powershell#26790]
### Description

We have a customer that has subscriptions containing a `&`.
We construct a policy assignment name with `tag` - `subscriptionname`

So for example `Critical - Hewlett & Packard - Development`

If I want to check if a policy assignment with that name already exists, I would simply use `Get-AzPolicyAssignment` to check if the assignment exists or not.

Unfortunately the cmdlet doesn't seem to like `&` signs and throws up code:

```powershell
Get-AzPolicyAssignment -Name 'Critical - Hewlett & Packard - Development' -Scope '/subscriptions/00000000-0000-0000-0000-000000000' -ErrorAction Stop

Get-AzPolicyAssignment_Get: C:\bgates\PowerShell\Modules\Az.Resources\7.4.0\Policy.Autorest\custom\Get-AzPolicyAssignment.ps1:250:19
Line |
250 |      $scriptCmd = {& $wrappedCmd @calledParameters}
     |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Expected literal (number, boolean, or null). Was '<'.
```

Have tried this on various versions of the module, but problem still exists.
Ran this on my colleagues machine, but also in a 7.2 clean Automation Account using 'default' latest version of the modules.

When trying the same thing manually, using the exact same name in the Portal, it does work just fine, both getting the info and creating/editing a policy assignment.

### Issue script & Debug output

```PowerShell
$DebugPreference='Continue'
Get-AzPolicyAssignment -Name 'Critical - Hewlett & Packard - Development' -Scope '/subscriptions/00000000-0000-0000-0000-000000000' -ErrorAction Stop
```

### Environment data

```PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
get-module az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.4                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContext, Clear-AzDefault…}
Script     7.4.0                 Az.Resources                        {Export-AzResourceGroup, Export-AzTemplateSpec, Get-AzDenyAssignment, Get-AzDeployment…}
```

### Error output

```PowerShell
Resolve-AzError
DEBUG: 14:46:00 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 14:46:00 - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 14:46:00 - using account id 'adm_Gijs.vanSoest@topigsnorsvin.onmicrosoft.com'...
DEBUG: 14:46:00 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 14:46:00 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 32

Message        : Expected literal (number, boolean, or null). Was '<'.
StackTrace     :    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonTokenizer.ReadIdentifer()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonTokenizer.ReadLiteral()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonTokenizer.ReadNext()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.TokenReader.Next()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonParser..ctor(SourceReader sourceReader)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonNode.Parse(String text)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.<>c.<PolicyAssignmentsGet_Call>b__44_1(Task`1 body)
                    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                 --- End of stack trace from previous location ---
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Cmdlets.GetAzPolicyAssignment_Get.onDefault(HttpResponseMessage responseMessage, Task`1 response)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.PolicyAssignmentsGet_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.PolicyAssignmentsGet_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.PolicyAssignmentsGet(String scope, String policyAssignmentName, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Cmdlets.GetAzPolicyAssignment_Get.ProcessRecordAsync()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Cmdlets.GetAzPolicyAssignment_Get.ProcessRecordAsync()
Exception      : Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.ParserException
InvocationInfo : {Get-AzPolicyAssignment_Get}
Line           :     $scriptCmd = {& $wrappedCmd @calledParameters}

Position       : At C:\bgates\PowerShell\Modules\Az.Resources\7.4.0\Policy.Autorest\custom\Get-AzPolicyAssignment.ps1:250 char:19
                 +     $scriptCmd = {& $wrappedCmd @calledParameters}
                 +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 32

DEBUG: 14:46:01 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 30

Message        : Cannot validate argument on parameter 'Uri'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                    at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32 parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
                    at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32 parameterSets, Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoValidation(Collection`1 arguments)
                    at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Collection`1 arguments)
                    at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                    at System.Management.Automation.CommandProcessor.Prepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
                    at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                 --- End of stack trace from previous location ---
                    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)     
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.ParameterBindingValidationException
InvocationInfo : {Invoke-RestMethod}
Line           : $groups = Invoke-RestMethod -Method Get -Uri $groupUrl -Headers $authToken
Position       : At line:1 char:46
                 + $groups = Invoke-RestMethod -Method Get -Uri $groupUrl -Headers $auth …
                 +                                              ~~~~~~~~~
HistoryId      : 30

DEBUG: 14:46:01 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
Message        : The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
StackTrace     :    at System.Management.Automation.ValidateNotNullOrAttributeBase.Validate(Object arguments, EngineIntrinsics engineIntrinsics)
                    at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
Exception      : System.Management.Automation.ValidationMetadataException
InvocationInfo : {Invoke-RestMethod}
Line           : $groups = Invoke-RestMethod -Method Get -Uri $groupUrl -Headers $authToken
Position       : At line:1 char:46
                 + $groups = Invoke-RestMethod -Method Get -Uri $groupUrl -Headers $auth …
                 +                                              ~~~~~~~~~
HistoryId      : 30

DEBUG: 14:46:01 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 29

Message        : Expected literal (number, boolean, or null). Was '<'.
StackTrace     :    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonTokenizer.ReadIdentifer()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonTokenizer.ReadLiteral()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonTokenizer.ReadNext()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.TokenReader.Next()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonParser..ctor(SourceReader sourceReader)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonNode.Parse(SourceReader sourceReader)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.JsonNode.Parse(String text)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.<>c.<PolicyAssignmentsGet_Call>b__44_1(Task`1 body)
                    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                 --- End of stack trace from previous location ---
                    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
                    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
                 --- End of stack trace from previous location ---
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Cmdlets.GetAzPolicyAssignment_Get.onDefault(HttpResponseMessage responseMessage, Task`1 response)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.PolicyAssignmentsGet_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.PolicyAssignmentsGet_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Policy.PolicyAssignmentsGet(String scope, String policyAssignmentName, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Cmdlets.GetAzPolicyAssignment_Get.ProcessRecordAsync()
                    at Microsoft.Azure.PowerShell.Cmdlets.Policy.Cmdlets.GetAzPolicyAssignment_Get.ProcessRecordAsync()
Exception      : Microsoft.Azure.PowerShell.Cmdlets.Policy.Runtime.Json.ParserException
InvocationInfo : {Get-AzPolicyAssignment_Get}
Line           :     $scriptCmd = {& $wrappedCmd @calledParameters}

Position       : At C:\bgates\PowerShell\Modules\Az.Resources\7.4.0\Policy.Autorest\custom\Get-AzPolicyAssignment.ps1:250 char:19
                 +     $scriptCmd = {& $wrappedCmd @calledParameters}
                 +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 29



DEBUG: 14:46:01 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 14:46:01 - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:3.0.4; CommandName: Resolve-AzError; PSVersion: 7.4.6; IsSuccess: True; Duration: 00:00:00.1822805; SanitizeDuration: 00:00:00.0148568
DEBUG: 14:46:01 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 14:46:01 - ResolveError end processing.
DEBUG: Setting WindowTitle: My Terminal [main] - PowerShell 7.4 (42880)
```

**Comment by powershellpr0mpt** [comment]
Any expected update on this issue?
