### ISSUE TITLE
New-AzStorageContext errors Could not find the resource "Microsoft.WindowsAzure.Commands.Storage.Resources.resources"

### ISSUE THREAD

**Issue by sethmgray** [Azure/azure-powershell#26802]
### Description

On clean windows server 2022, and less clean windows server 2019 - current release versions installed via install-module (either install-module Az, or as below separate module installs) new-azstoragecontext doesnt' work. 

install-module Az.Accounts, Az.Storage

### Issue script & Debug output

```PowerShell
PS C:\Users\sgray> $debugpreference='Continue'
PS C:\Users\sgray> new-azstoragecontext

cmdlet New-AzStorageContext at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
StorageAccountName: bere
DEBUG: 3:51:34 PM - NewAzureStorageContext begin processing with ParameterSet 'OAuthAccount'.
New-AzStorageContext: Could not find the resource "Microsoft.WindowsAzure.Commands.Storage.Resources.resources" among the resources "Microsoft.WindowsAzure.Commands.Storage.Common.Resources.resources" embedded in the assembly "Microsoft.Azure.PowerShell.Storage.Common", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
DEBUG: AzureQoSEvent:  Module: Az.Storage:8.0.0; CommandName: New-AzStorageContext; PSVersion: 7.4.6; IsSuccess: False; Duration: 00:00:00.0512306; SanitizeDuration: 00:00:00; Exception: Could not find the resource "Microsoft.WindowsAzure.Commands.Storage.Resources.resources" among the resources "Microsoft.WindowsAzure.Commands.Storage.Common.Resources.resources" embedded in the assembly "Microsoft.Azure.PowerShell.Storage.Common", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.;
DEBUG: 3:51:35 PM - NewAzureStorageContext end processing.
```

### Environment data

```PowerShell
PS C:\Users\sgray> $psversiontable

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
PS C:\Users\sgray> get-module Az*

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     4.0.0                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzConte…
Script     8.0.0                 Az.Storage                          {Add-AzRmStorageContainerLegalHold, Add-AzStorage…
```

### Error output

```PowerShell
PS C:\Users\sgray> resolve-azerror
DEBUG: 3:52:59 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:52:59 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 3:52:59 PM - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:52:59 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 6

Message        : Could not find the resource "Microsoft.WindowsAzure.Commands.Storage.Resources.resources" among the
                 resources "Microsoft.WindowsAzure.Commands.Storage.Common.Resources.resources" embedded in the
                 assembly "Microsoft.Azure.PowerShell.Storage.Common", nor among the resources in any satellite
                 assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
StackTrace     :    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
                    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture,
                 Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
                    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean
                 createIfNotExists, Boolean tryParents)
                    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
                    at Microsoft.WindowsAzure.Commands.Storage.Resources.get_ContextCannotBeNull()
                    at Microsoft.WindowsAzure.Commands.Storage.Common.OAuthUtil.CreateOAuthToken(IAzureContext
                 DefaultContext)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.OAuthUtil.getTokenCredential(IAzureContext
                 DefaultContext, DebugLogWriter logWriter)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext.GetStorageAccountBy
                 OAuth(String storageAccountName, Boolean useHttps, String storageEndpoint)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Resources.MissingManifestResourceException
InvocationInfo : {New-AzStorageContext}
Line           : new-azstoragecontext
Position       : At line:1 char:1
                 + new-azstoragecontext
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6

DEBUG: 3:52:59 PM - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].

   HistoryId: 4

Message        : Could not find the resource "Microsoft.WindowsAzure.Commands.Storage.Resources.resources" among the
                 resources "Microsoft.WindowsAzure.Commands.Storage.Common.Resources.resources" embedded in the
                 assembly "Microsoft.Azure.PowerShell.Storage.Common", nor among the resources in any satellite
                 assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
StackTrace     :    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
                    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture,
                 Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
                    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean
                 createIfNotExists, Boolean tryParents)
                    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
                    at Microsoft.WindowsAzure.Commands.Storage.Resources.get_ContextCannotBeNull()
                    at Microsoft.WindowsAzure.Commands.Storage.Common.OAuthUtil.CreateOAuthToken(IAzureContext
                 DefaultContext)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.OAuthUtil.getTokenCredential(IAzureContext
                 DefaultContext, DebugLogWriter logWriter)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext.GetStorageAccountBy
                 OAuth(String storageAccountName, Boolean useHttps, String storageEndpoint)
                    at Microsoft.WindowsAzure.Commands.Storage.Common.Cmdlet.NewAzureStorageContext.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronously
                 OrAsJob>b__3_0(T c)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet, Action`1 executor)
                    at
                 Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T
                 cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Resources.MissingManifestResourceException
InvocationInfo : {New-AzStorageContext}
Line           : new-azstoragecontext
Position       : At line:1 char:1
                 + new-azstoragecontext
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4



DEBUG: 3:52:59 PM - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:52:59 PM - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.Accounts:4.0.0; CommandName: Resolve-AzError; PSVersion: 7.4.6; IsSuccess: True; Duration: 00:00:00.2757588; SanitizeDuration: 00:00:00.0046083
DEBUG: 3:52:59 PM - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 3:52:59 PM - ResolveError end processing.
```

**Comment by sethmgray** [comment]
same behavior is seen installing simply Az module, I reduced to reflect the nature of the script in question.

**Comment by blueww** [comment]
@sethmgray 

Have you Connect to Azure with an authenticated account by "Add-AzAccount", before run "New-AzStorageContext" ?
Run "New-AzStorageContext" with only storage account name will create a storage context based on Oauth credential, which need you first Connect to Azure  by "Add-AzAccount" (better with parameter '-AuthScope StorageOAuthEndpointResourceId').

"New-AzStorageContext" can also create storage context based on other credential, like based on sharedkey "New-AzStorageContext -StorageAccountName $accountname -StorageAccountKey $key". Other credentials doesn't need first Connect to Azure  by "Add-AzAccount", (only Oauth credential need first Connect to Azure  by "Add-AzAccount".)

**Comment by blueww** [comment]
@isra-fel 

Any idea why this error reported when run "New-AzStorageContext" to create Oauth context before run  "Add-AzAccount"?
Why the error not remind user to  Connect to Azure with an authenticated account by "Add-AzAccount"?

Feel free to let me know if any change needed from storage side,

**Comment by blueww** [comment]
I have raise a PR to fix the error message with creating OAuth based Storage context without first login with Connect-AzAccount . https://github.com/Azure/azure-powershell/pull/26803

**Comment by sethmgray** [comment]
I had not created the context, the code I was using that initially
discovered was providing an invalid sastoken - presumably null , code at
this time has corrected and moved past that issue. But yes better error
messaging appreciated!

**Comment by blueww** [comment]
@sethmgray 
Good to know you have past that issue!
I will close this issue as the error message fix PR is merged.

Feel free to contact us again if need any further assistance on PowerShell.
