### ISSUE TITLE
New-AzureRmResourceGroupDeployment sometimes throws "Deployment 'xxx' could not be found." exception

### ISSUE THREAD

**Issue by stankovski** [Azure/azure-powershell#2871]
### Cmdlet(s)
New-AzureRmResourceGroupDeployment

### PowerShell Version
5.0.10586.117

### Module Version
1.4.0

### OS Version
10.0.10586.117

### Description
Running the deployment via `New-AzureRmResourceGroupDeployment` sometimes results in the following error that terminates cmdlet execution:
```
Microsoft.Rest.Azure.CloudException: 
Deployment 'BackEnd-20160831-1658' could not be found.
   at Microsoft.Azure.Management.ResourceManager.DeploymentOperationsOperations.<ListWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentOperationsOperationsExtensions.<ListAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentOperationsOperationsExtensions.List(IDeploymentOperationsOperations operations, String resourceGroupName, String 
deploymentName, Nullable`1 top)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.WriteDeploymentProgress(String resourceGroup, String deploymentName, Deployment deployment)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.WaitDeploymentStatus(String resourceGroup, String deploymentName, Deployment basicDeployment, Action`3 job, ProvisioningState[] status)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ProvisionDeploymentStatus(String resourceGroup, String deploymentName, Deployment deployment)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ExecuteDeployment(PSCreateResourceGroupDeploymen
tParameters parameters)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet.ExecuteCmdlet()
at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord
```
### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

### Script/Steps for Reproduction
Run `New-AzureRmResourceGroupDeployment` (not a consistent repro)

**Comment by stankovski** [comment]
Fixed in 2.0.0 release
