### ISSUE TITLE
Fix concurrency issues in ClientFactory.UserAgents

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#2935]
### Description

Concurrent additions to the UserAgent HashSet can result in null reference exceptions like the following: 
Object reference not set to an instance of an object..Exception.StackTrace:    at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.SetupHttpClientPipeline()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
- [x] Add a simple functional test to reproduce the issue
- [x] Add a more comprehensive functional unit test that will spin up many threads with cmdlets usign the standard BeginProcessing() to create a management client, to reproduce the issue.
- [x] Implement a ConcurrentHashSet to serialize access to the HashSet UserAgent values and replace the ClientFactory values with this
- [x] Validate that additional tests pass
- [ ] Examine the IClientFactory, IAuthenticationFactory, and IDataStore interfaces for non thread-safe methods and data structures

**Comment by markcowl** [comment]
Need to update fix to include a ConcurrentHashSet

**Comment by markcowl** [comment]
Fixed
