### ISSUE TITLE
Login-AzureRmAccount -ServicePrincipal does not work on remote machine

### ISSUE THREAD

**Issue by JustinHackett** [Azure/azure-powershell#2966]
### Cmdlet(s)
Login-AzureRmAccount, Get-AzureRmResource

### PowerShell Version
4.0

### Module Version
1.1.0      AzureRM.ApiManagement
1.0.8      AzureRM.Automation
0.9.5      AzureRM.AzureStackAdmin
0.9.6      AzureRM.AzureStackStorage
1.0.8      AzureRM.Backup
1.1.0      AzureRM.Batch
1.0.2      AzureRM.Cdn
1.3.0      AzureRM.Compute
1.0.8      AzureRM.DataFactories
1.1.0      AzureRM.DataLakeAnalytics
1.0.8      AzureRM.DataLakeStore
1.0.8      AzureRM.Dns
1.1.0      AzureRM.HDInsight
1.0.8      AzureRM.Insights
1.1.7      AzureRM.KeyVault
1.0.4      AzureRM.LogicApp
1.0.9      AzureRM.Network
1.0.8      AzureRM.NotificationHubs
1.0.8      AzureRM.OperationalInsights
1.0.8      AzureRM.Profile
1.1.0      AzureRM.RecoveryServices
1.0.0      AzureRM.RecoveryServices.Backup
1.1.6      AzureRM.RedisCache
1.1.0      AzureRM.Resources
1.1.7      AzureRM.SiteRecovery
1.0.8      AzureRM.Sql
1.1.0      AzureRM.Storage
1.0.8      AzureRM.StreamAnalytics
1.0.8      AzureRM.Tags
1.0.8      AzureRM.TrafficManager
1.0.8      AzureRM.UsageAggregates
1.1.0      AzureRM.Websites

### OS Version
6.3.9600.17400

### Description
Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ArgumentException
    + FullyQualifiedErrorId : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.,Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

We are seeing this error when we try to run AzureRM cmdlet calls using PowerShell remoting. The same commands work when run locally. We have tried Azure PowerShell versions 1.4 and 2.1 (latest) with no success.

### Debug Output
Environment           : AzureCloud
Account               : [CorrectAccount]
TenantId              : [CorrectTenantId]
SubscriptionId        : [CorrectSubscriptionId]
CurrentStorageAccount :

Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ArgumentException
    + FullyQualifiedErrorId : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials.,Micro
   soft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
    + PSComputerName        : MYMACHINE2

### Script/Steps for Reproduction
Invoke-Command -ComputerName MYMACHINE2 {$creds = Get-Credential -Credential (New-Object pscredential("***SPNRemoved***",("***ClientSecretRemoved***" | ConvertTo-SecureString -AsPlainText -Force)));Login-AzureRmAccount -Credential $creds -TenantId "***TenantIDRemoved***" -ServicePrincipal | Out-String;Get-AzureRmResource | Out-String}

**Comment by JustinHackett** [comment]
This is the full stack trace:
System.ArgumentException: Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials. ---> System.Collections.Generic.KeyNotFoundException: Unable to retrieve service key for ServicePrincipal account bf9491b7-2355-4fa0-87e9-0b835c38bcf7. Please log in again to supply the credentials for this service principal. In PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets.
   at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.RenewWithSecret(AdalConfiguration config, String appId)
   at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessToken(AdalConfiguration config, ShowDialog promptBehavior, String u
serId, SecureString password, AccountType credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(AzureAccount account, AzureEnvironment environment, String te
nant, SecureString password, ShowDialog promptBehavior, TokenCache tokenCache, Endpoint resourceId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetSubscriptionCloudCredentials(AzureContext context, Endpoint targetEndpo
int)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetSubscriptionCloudCredentials(AzureContext context, Endpoint targetEndpo
int)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components.ResourceManagerClientHelper.GetResourceManagerClient(AzureContext context, Dictionary`2 cmdle
tHeaderValues)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components.ApiVersionHelper.GetApiVersionsForResourceType(AzureContext context, String providerNamespace
, String resourceType, CancellationToken cancellationToken, Dictionary`2 cmdletHeaderValues)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components.ApiVersionHelper.<>c__DisplayClass7.<DetermineApiVersion>b__0()
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components.ApiVersionHelper.ApiVersionCache.AddOrGetExisting(String cacheKey, Func`1 getFreshData)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components.ApiVersionHelper.DetermineApiVersion(AzureContext context, String providerNamespace, String r
esourceType, CancellationToken cancellationToken, Nullable`1 pre, Dictionary`2 cmdletHeaderValues)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.DetermineApiVersion(String providerNamespace, String resourceTy
pe, Nullable`1 pre)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet.<ListResourcesInSubscription>d__2c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet.<GetResources>d__c.MoveNext()

**Comment by markcowl** [comment]
@JustinHackett This looks like it is related to this issue #1835   If you're finding that this is related to the login type and not generally true for loging, then we will investigate this separately, otherwise, we'll close thsi as a duplicate and track the serializability issue.

**Comment by markcowl** [comment]
closing as duplicate per the above.
