### ISSUE TITLE
set-azureRMVMextension command does not execute correctly <reference to #2972 that was closed >

### ISSUE THREAD

**Issue by saimsh** [Azure/azure-powershell#3063]
### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
### OS Version

Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
### Script/Steps for Reproduction

continuation of #2972  that was closed.

@singhkays 
hi, my customer is still experiencing some issues with the extension. I was able to reproduce the same issues in my test. the following are the commands i used : 
rg="debian-arm"
$vm="ssdebian8"
$loc="Central US"
$TheURI = "https://customscripttest.blob.core.windows.net/sscustomscript/debian-systat.sh"
$ScriptSettings = @{"fileUris" = @($TheURI); "commandToExecute" = "./debian-systat.sh";}
Set-AzureRmVMExtension -ResourceGroupName $rg -VMName $vm -Name "CustomScriptForLinux" -Publisher "Microsoft.Azure.Extensions" -TypeHandlerVersion 2.0 -ExtensionType "CustomScriptForLinux" -Location $loc -Settings $ScriptSettings

ERROR:
Set-AzureRmVMExtension : Extension with publisher 'Microsoft.Azure.Extensions', type 'CustomScriptForLinux', and type handler version '2.0' could not be found in the extension repository.
StatusCode: 404
ReasonPhrase: Not Found
OperationID : '29f9d2df-4f56-4be2-871f-a74dd97d98b9'
At line:6 char:1

Set-AzureRmVMExtension -ResourceGroupName $rg -VMName $vm -Name "Cust ...

```
CategoryInfo : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand
it looks liek there is some issue with the extension publisher name or the type handler version. Could you please verify this.
thanks,



```

**Comment by saimsh** [comment]
also, when performing further tests with the old extension, I observed the following errrors : 
$rg="debian-arm"
$vm="ssdebian8"
$loc="Central US"
$TheURI = "https://customscripttest.blob.core.windows.net/sscustomscript/debian-systat.sh"
$ScriptSettings = @{"fileUris" = @($TheURI); "commandToExecute" = "./debian-systat.sh";}
Set-AzureRmVMExtension -ResourceGroupName $rg -VMName $vm -Name "CustomScriptForLinux" -Publisher "Microsoft.OSTCExtensions" -TypeHandlerVersion 1.5 -ExtensionType "CustomScriptForLinux" -Location $loc -Settings $ScriptSettings
Set-AzureRmVMExtension : Long running operation failed with status 'Failed'.
StartTime: 10/11/2016 4:09:41 PM
EndTime: 10/11/2016 4:14:24 PM
OperationID: 
Status: Failed
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'CustomScriptForLinux'. Error message: "Enable failed: Failed with error: Failed to download external file with uri: 
https://customscripttest.blob.core.windows.net/sscustomscript/debian-systat.sh with error HTTP Error 404: The specified blob does not exist., Traceback (most recent call last):
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/customscript.py", line 71, in main
    daemon(hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/customscript.py", line 269, in daemon
    retry_count = download_files_with_retry(hutil, retry_count, wait)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/customscript.py", line 110, in download_files_with_retry
    download_files(hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/customscript.py", line 215, in download_files
    download_external_files(blob_uris, cmd, hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/customscript.py", line 349, in download_external_files
    download_external_file(uri, command, hutil)
  File "/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/customscript.py", line 366, in download_external_file
    raise Exception(error_msg)
Exception: Failed to download external file with uri: https://customscripttest.blob.core.windows.net/sscustomscript/debian-systat.sh with error HTTP Error 404: The specified blob does not exist.
".
At line:6 char:1
+ Set-AzureRmVMExtension -ResourceGroupName $rg -VMName $vm -Name "Cust ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVMExtension], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.SetAzureVMExtensionCommand

Please provide some insights as to why the download failed. I created a public blob and i am able to download this file from any remote location. However, it failed download when executing the extension 
thanks,
regards,
saim

**Comment by markcowl** [comment]
@singhkays can you take a look?  Please reassign appropriately if needed.

**Comment by singhkays** [comment]
@saimsh The extension name for 2.0 is "customscript" instead of "CustomScriptForLinux". For the blob issue, can you download the blob on the vm manually? There might be an NSG blocking access to the internet from the VM.

**Comment by saimsh** [comment]
Ahh. i cna definitely try that out as I was able to get it working via azure cli. My customer would like to be able to add protected settings within custom script extension.
He used the older extension ( which i believe should also work) : 
$rg="debian-arm"
$vm="ssdebian8"
$loc="Central US"
$TheURI = "https://customscripttest.blob.core.windows.net/sscustomscript/debiansysstat.sh"
$ScriptSettings = @{"fileUris" = @($TheURI); "commandToExecute" = "./debiansysstat.sh";}
$protectedSettings = '{
                        "storageAccountName": "storage-account-name",
                        "storageAccountKey": "storage-account-key"
}'
Set-AzureRmVMExtension -ResourceGroupName $rg -VMName $vm -Name "CustomScriptForLinux" -Publisher "Microsoft.OSTCExtensions" -TypeHandlerVersion 1.5 -ExtensionType "CustomScriptForLinux" -Location $loc -Settings $ScriptSettings -ProtectedSettings $protectedSettings 

However, he is running into issues associated with protected settings:
![errorfile](https://cloud.githubusercontent.com/assets/20546414/19418416/5570dbb0-9378-11e6-8f8f-a003dc9fef41.jpg)

**Comment by saimsh** [comment]
@singhkays 
could you verify if the same protected settings syntax is used for both the publishers. When using an older extension, my customer is running in to the above attached errors. Please provide insights for this.
thanks,
saim

**Comment by saimsh** [comment]
Hi, 
I performed some more testings using the following cmdlets (as described in teh github page for using custom script for linux extension 
$RGName = 'saimubunturg'
$VmName = 'saimubuntu1404'
$Location = 'Central US'

$ExtensionName = 'CustomScriptForLinux'
$Publisher = 'Microsoft.OSTCExtensions'
$Version = '1.5'

$PublicConf = '{
    "fileUris": ["https://customscripttest.blob.core.windows.net/sscustomscript/ubuntusysstat.sh"],
    "commandToExecute": "sh ubuntusysstat.sh"
}'
$PrivateConf = '{
    "storageAccountName": "customscripttest",
    "storageAccountKey": "2TR5dsBNyrSF6h5MzIVLImzIt5Hdlx/YO7PNo9t5xcLPW4WdHrXrk5BV+58MCH+hkHaRlIprWyUGY1Dr8qfWGg=="
}'

Set-AzureRmVMExtension -ResourceGroupName $RGName -VMName $VmName -Location $Location `
  -Name $ExtensionName -Publisher $Publisher `
  -ExtensionType $ExtensionName -TypeHandlerVersion $Version `
  -Settingstring $PublicConf -ProtectedSettingString $PrivateConf

The execution failed with the following errors in the extension.log :
set most recent sequence number to 0
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Command to execute:sh ubuntusysstat.sh
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Enable,transitioning,0,Launching the script...
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] sequence number is 0
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] setting file path is/var/lib/waagent/Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1/config/0.settings
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] JSON config: {"runtimeSettings": [{"handlerSettings": {"protectedSettings": "MIICSgYJKoZIhvcNAQcDoIICOzCCAjcCAQAxggFpMIIBZQIBADBNMDkxNzA1BgoJkiaJk/IsZAEZFidXaW5kb3dzIEF6dXJlIENSUCBDZXJ0aWZpY2F0ZSBHZW5lcmF0b3ICEGN8zf/aHImWQEXxm8P86ywwDQYJKoZIhvcNAQEBBQAEggEAAnSMV1PpVzap1q2eL8syDQDAPUc5SpyKNdUmY0cvpw+RVJB5zA8wlY8xJpkIPn1K8L2RUpc5WgIXK4YdyykOvNN60zdDslH6AzueVRftZfad7y0dmT/7GUKCDabK3/z80DKlXrQCSHbvuvzXGX1xPNjb3Zitcaw/HNafNOHR+/SsaAoHEoFjcvpOEJTWeICAhKLVDE/YmNs/hrqpqwbUliVznysbyt57tqAkswLYV5tMrKaTn9E6FxuJqixymPh+fpbdwhZDZ7wJzUYmoAYOSIi/gKHCaDg0lkxgF8Nsa+LfdqzFOMQIr8uaexRJrcyTK3jzDQ8oBuV18GgHHhlcLjCBxAYJKoZIhvcNAQcBMBQGCCqGSIb3DQMHBAiFzThp1EKVw4CBoGCDBat9daXAtzhFaWTAXISYJ2+6/nwD1ohgYvPN8v+929YKt6XSRRb993NGobC8fBJXp8gqWxclHwDsuphrexk9mnaNZad0gxMuGArX81t7AdX1Y5x3ffIG6BP31+j1qYQtUNvgFxUfdYVgEBGN684QUG3z66P9PilkWAGowCiaHDGBWIyWlmK+DyQV88bxfThaqzA3EXaVu+F/BIvysiE=", "protectedSettingsCertThumbprint": "B28873D1FC3FE9BB91CFEA190B8F60AD990DB5E7", "publicSettings": {"commandToExecute": "sh ubuntusysstat.sh", "fileUris": ["https://customscripttest.blob.core.windows.net/sscustomscript/ubuntusysstat.sh"]}}}]}
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Config decoded correctly.
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Will try to download files, number of retries = 10, wait SECONDS between retrievals = 20s
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Command to execute:sh ubuntusysstat.sh
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Downloading,transitioning,0,Downloading files...
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Downloading scripts from azure storage...
2016/10/19 17:54:13 ERROR:[Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Failed to download blob with uri: https://customscripttest.blob.core.windows.net/sscustomscript/ubuntusysstat.sh with error Unknown error (The value for one of the HTTP headers is not in the correct format.), retry = 0, maxRetry = 10.
2016/10/19 17:54:13 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Sleep 20 seconds
2016/10/19 17:54:33 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Command to execute:sh ubuntusysstat.sh
2016/10/19 17:54:33 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Downloading,transitioning,0,Downloading files...
2016/10/19 17:54:33 [Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Downloading scripts from azure storage...
2016/10/19 17:54:33 ERROR:[Microsoft.OSTCExtensions.CustomScriptForLinux-1.5.2.1] Failed to download blob with uri: https://customscripttest.blob.core.windows.net/sscustomscript/ubuntusysstat.sh with error Unknown error (The value for one of the HTTP headers is not in the correct format.), retry = 1, maxRetry = 10.


I will try testing the same using the new extension version and update. 
thanks,
saim

**Comment by cormacpayne** [comment]
Closing this issue as there has been no activity for a few months.

@saimsh please feel free to reopen this issue if you find it is still a problem.
