### ISSUE TITLE
Get-AzureSqlDatabaseServiceObjective does not return all DTU tiers

### ISSUE THREAD

**Issue by robertmclaws** [Azure/azure-powershell#3077]
### Cmdlet(s)

Get-AzureSqlDatabaseServiceObjective
### PowerShell Version

5.0.10514.2
### Module Version

Unknown
### OS Version

10.0.10514.2
### Description

Attempts to update the performance level of an SQL Database to the P6 level, specifically, retrieving the AzureSqlDatabaseServiceObjective for the P6 level is what is causing the issue. I am able to successfully change the performance level to P1, P2, or P3 with the same block of code; however, when I specify P6, Get-AzureSqlDatabaseServiceObjective returns null.
### Debug Output

```
:25:45 PM - AddAzureRMAccountCommand begin processing with ParameterSet 'User'.
[Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 
'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 
'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
10/12/2016 8:26:10 PM:  - UserTokenProvider: ADAL .NET with assembly version '2.18.0.0', file version '2.18.20625.1556' 
and informational version 'b90841565e0ecaad0f3f73072c3d40e43223de4e' is running...

[Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common/', 
CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
[Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 
'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: 
urn:ietf:wg:oauth:2.0:oob
Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
10/12/2016 8:26:11 PM: da4ddc4b-b81f-4b32-bf91-564adb03f394 - AcquireTokenNonInteractiveHandler: === Token Acquisition 
started:
    Authority: https://login.microsoftonline.com/Common/
    Resource: https://management.core.windows.net/
    ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
    CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (0 items)
    Authentication Target: User


Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
10/12/2016 8:26:11 PM: da4ddc4b-b81f-4b32-bf91-564adb03f394 - <RunAsync>d__0: Looking up cache for a token...

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
10/12/2016 8:26:11 PM: da4ddc4b-b81f-4b32-bf91-564adb03f394 - <RunAsync>d__0: No matching token was found in the cache

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
10/12/2016 8:26:11 PM: da4ddc4b-b81f-4b32-bf91-564adb03f394 - AsyncMethodBuilderCore: Sending user realm discovery 
request to 'https://login.microsoftonline.com/common/UserRealm/robert@techgrows.com?api-version=1.0'

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
10/12/2016 8:26:13 PM: da4ddc4b-b81f-4b32-bf91-564adb03f394 - AsyncMethodBuilderCore: User with hash 
'5mwIPAD/wxLWAz3LJCIBYxfumeXmvFYQs6RP9T4DFpY=' detected as 'Unknown'

Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 : 
10/12/2016 8:26:13 PM: da4ddc4b-b81f-4b32-bf91-564adb03f394 - AsyncMethodBuilderCore: 
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: unknown_user_type: Unknown User Type
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
    ErrorCode: unknown_user_type

Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
10/12/2016 8:26:13 PM:  - RMProfileClient: Serializing token cache with 0 items.


Environments                                                                                           Context          
------------                                                                                           -------          
{[AzureCloud, AzureCloud], [AzureChinaCloud, AzureChinaCloud], [AzureUSGovernment, AzureUSGovernment]} Microsoft.Azur...
8:26:39 PM - AddAzureRMAccountCommand end processing.
8:26:44 PM - NewAzureSqlDatabaseServerContext begin processing with ParameterSet 'ByManageUrlWithSqlAuth'.
8:26:48 PM - NewAzureSqlDatabaseServerContext end processing.
8:26:49 PM - GetAzureSqlDatabaseServiceObjective begin processing with ParameterSet 'ByConnectionContext'.
8:26:50 PM - GetAzureSqlDatabaseServiceObjective end processing.
Set-AzureSqlDatabase : Cannot validate argument on parameter 'ServiceObjective'. The argument is null. Provide a valid 
value for the argument, and then try running the command again.
At line:40 char:81
+ ... atabaseName $DatabaseName –ServiceObjective $ServiceObjective –Editio ...
+                                                 ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-AzureSqlDatabase], ParameterBindingValidationException
    + FullyQualifiedErrorId : 
ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.SqlDatabase.Database.Cmdlet.SetAzureSqlDatabase
```
### Script/Steps for Reproduction

``` ps
        $SqlServerName = "[Insert Server Name Here]"
        $ServerLogin = "[Insert Server Login Name Here]"
        $serverPassword = ConvertTo-SecureString "[Insert Server Password Here]" -AsPlainText -Force
        $DatabaseName = "[Insert Database Name Here]"
        $Edition = "Premium"
        $PerfLevel = "P6"
        $azureAccountName ="[Insert Azure Account Name Here]"
        $azurePassword = ConvertTo-SecureString "[Insert Azure Account Password Here" -AsPlainText -Force

        #credential objects
        $serverLoginCred = New-Object System.Management.Automation.PSCredential($ServerLogin, $serverPassword)
        $accountCred = New-Object System.Management.Automation.PSCredential($azureAccountName, $azurePassword)

        #login to azure acc
        Add-AzureRmAccount -Credential $accountCred

        #get credentials for server 
        $ServerCredential = new-object System.Management.Automation.PSCredential($serverLoginCred.UserName, (($serverLoginCred).GetNetworkCredential().Password | ConvertTo-SecureString -asPlainText -Force))  

        #get connection context
        $CTX = New-AzureSqlDatabaseServerContext -ManageUrl “https://$SqlServerName.database.windows.net” -Credential $ServerCredential 

        #create a service objective for desired performance level
        $ServiceObjective = Get-AzureSqlDatabaseServiceObjective $CTX -ServiceObjectiveName $PerfLevel

        #set new level with context, db name, serviceObject, and edition (i.e. 'Premium') 
        Set-AzureSqlDatabase $CTX –DatabaseName $DatabaseName –ServiceObjective $ServiceObjective –Edition $Edition -Force 
```

**Comment by cormacpayne** [comment]
@akromm Hey Adam, would you mind taking a look at this issue?

**Comment by rrrrrrich** [comment]
This also returns Null for P4.

I have noticed that it works fine for Powershell running from a Windows Machine but from inside an Azure Automation Runbook it returns null.

The runbook i'm running is called "Set-AzureSqlDatabaseEdition"

Which is effectively https://gallery.technet.microsoft.com/scriptcenter/Azure-SQL-Database-e957354f

**Comment by akromm** [comment]
@robertmclaws We've recently made some changes in this area and when I call Get-AzureRmSqlServerServiceObjectives it returns P6.  Can you let me know if this is still an issue for you?

@rrrrrrich I don't have much experience with Azure Automation Runbook, but my understanding is their environment is a bit different and requires additional environmental setup.

**Comment by cormacpayne** [comment]
Closing this issue as it seems to have been fixed.

@robertmclaws please feel free to reopen this issue if you find it is still a problem.

**Comment by snekbaev** [comment]
Hi,

added a workbook yesterday from the gallery, the very same "Set-AzureSqlDatabaseEdition" mentioned ealier. I did some testing with S1 <-> S0, thought other tiers will also work just fine.

Target was P4. Checked the logs this morning:

```
Set-AzureSqlDatabase : Cannot validate argument on parameter 'ServiceObjective'. The argument is null. Provide a valid 
value for the argument, and then try running the command again.
At Scale-production-db:71 char:71
+ 
    + CategoryInfo          : InvalidData: (:) [Set-AzureSqlDatabase], ParameterBindingValidationException
    + FullyQualifiedErrorId : 
ParameterArgumentValidationError,Microsoft.WindowsAzure.Commands.SqlDatabase.Database.Cmdlet.SetAzureSqlDatabase
```

So apparently it is null for at least P4.

**Comment by legapat** [comment]
Hi @cormacpayne,

I got the same issue with S4.

Is there a solution?

**Comment by MPEV** [comment]
I too have the same issue. 

If the [documentation ](https://docs.microsoft.com/en-us/powershell/module/azure/get-azuresqldatabaseserviceobjective?view=azuresmps-4.0.0)is correct, it's **very** out of date with respect to the current SQL Azure [tiers](https://docs.microsoft.com/en-gb/azure/sql-database/sql-database-dtu-resource-limits). 

Is a new issue needed to request that Get-AzureSqlDatabaseServiceObjective is updated to reflect current SQL Azure tiers or could this one be reopened?

**Comment by legapat** [comment]
Hi @MPEV  ,
There was the solution for me.

I was using Classic cmdlet  : Set-AzureSqlDatabase.
https://docs.microsoft.com/en-us/powershell/module/azure/set-azuresqldatabase?view=azuresmps-4.0.0  . This was meant for the classic portal and supports only up to edition S3.

For the ARM portal, you can use the new RM cmdlet: https://docs.microsoft.com/en-us/powershell/module/azurerm.sql/set-azurermsqldatabase?view=azurermps-6.1.0 

Hope that will help!

**Comment by MPEV** [comment]
@legapat,

That makes sense - thanks!
