### ISSUE TITLE
Add-AzureRmEnvironment should be able to handle the Uri not ending with '\' for the parameter ActiveDirectoryEndpoint 

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-powershell#3264]
### Cmdlet(s)
Add-AzureRmEnvironment

### Version
1.2.6 (azurestack)

### Module Version
1.0.4.1

### Description

If the parameter value for ActiveDirectoryEndpoint doesn't end with '\' , then the subsequent Add-AzureRMAccount fails with 

VERBOSE: @{PSMessageDetails=; Exception=Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedException: : The remote server returned an error: (404) Not Found. ---> Microsoft
.IdentityModel.Clients.ActiveDirectory.AdalServiceException ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.DoAcquireToken(AdalConfiguration config, PromptBehavior promptBehavior, String userId, SecureString password) in d:\work
space\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 267
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.SafeAquireToken(AdalConfiguration config, ShowDialog showDialog, String userId, SecureString password, Exception& ex) in
d:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 183
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.AcquireToken(AdalConfiguration config, ShowDialog promptBehavior, String userId, SecureString password) in d:\workspace\
powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 165
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.GetAccessToken(AdalConfiguration config, ShowDialog promptBehavior, String userId, SecureString password, AccountType cr
edentialType) in d:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 61
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(AzureAccount account, AzureEnvironment environment, String tenant, SecureString password, Sho
wDialog promptBehavior, TokenCache tokenCache, Endpoint resourceId) in d:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Factories\AuthenticationFactory.cs:line 48
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(AzureAccount account, AzureEnvironment environment, String tenantId, SecureString password, ShowDialog
promptBehavior) in d:\workspace\powershell-sign\src\ResourceManager\Profile\Commands.Profile\Models\RMProfileClient.cs:line 476
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(AzureAccount account, AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName
, SecureString password) in d:\workspace\powershell-sign\src\ResourceManager\Profile\Commands.Profile\Models\RMProfileClient.cs:line 56
   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.ExecuteCmdlet() in d:\workspace\powershell-sign\src\ResourceManager\Profile\Commands.Profile\Account\AddAzureRmAccount.cs:line 
197
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet

**Comment by cormacpayne** [comment]
Fix has been merged
