### ISSUE TITLE
Facing error "The current SynchronizationContext may not be used as a TaskScheduler".

### ISSUE THREAD

**Issue by Aliasgar16** [Azure/azure-powershell#3341]
I am working on [PR](https://github.com/Azure/azure-powershell/pull/3322) to add missing options for `ChefExtension`. I have written test cases for the functionality for `ARM` mode but when I run the test case(s) in `Record` mode, I face the below mentioned error:

**System.AggregateException : One or more errors occurred.
---- System.InvalidOperationException : The current SynchronizationContext may not be used as a TaskScheduler.**

Complete stack trace is:
```
Result StackTrace:	
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.InteractiveLogin(String tenant, ActiveDirectoryServiceSettings aadServiceSettings, ActiveDirectoryServiceSettings graphAADServiceSettings)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.Login()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.RecorderModeSettings()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment..ctor(String connectionString)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironmentFactory.GetTestEnvironment()
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.GetStorageManagementClient(MockContext context) in D:\knife_repos\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 247
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.SetupManagementClients(MockContext context) in D:\knife_repos\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 182
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.RunPsTestWorkflow(Func`1 scriptBuilder, Action`1 initialize, Action cleanup, String callingClassType, String mockName) in D:\knife_repos\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 136
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ComputeTestController.RunPsTest(String[] scripts) in D:\knife_repos\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\Common\ComputeTestController.cs:line 100
   at Microsoft.Azure.Commands.Compute.Test.ScenarioTests.ChefExtensionTests.TestSetChefExtensionBasic() in D:\knife_repos\azure-powershell\src\ResourceManager\Compute\Commands.Compute.Test\ScenarioTests\ChefExtensionTests.cs:line 31
----- Inner Stack Trace -----
   at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.<LoginWithPromptAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.<LoginWithPromptAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.<>c__DisplayClass38_0.<<InteractiveLogin>b__0>d.MoveNext()
Result Message:	
System.AggregateException : One or more errors occurred.
---- System.InvalidOperationException : The current SynchronizationContext may not be used as a TaskScheduler.
```

I get the above error when I try to login to `Azure` while running the tests in `Record` mode.

I tried running all the test cases (to cross check if the issue persist only with my test case) and I face the exact same error for all the test cases at the exact point when I hit the `Sign-in` button on the `Azure login` page.

We had successfully written and recorded test cases for `Chef Extension` previously also but we did not faced any such issue at that time.

Any kind of help is appreciated.

Thanks

**Comment by markcowl** [comment]
This is because tests do authentication before running PowerShell, so you have to set up a new synchronization context.  You can do this with code like the following:

https://github.com/Azure/azure-powershell/blob/2eaf6175bc2533b83689120dc7f595ff0bdf8001/src/ResourceManager/Common/Commands.ScenarioTests.ResourceManager.Common/RMTestBase.cs#L73

If your test classes extend RMTestBase, this happens for free.

**Comment by Aliasgar16** [comment]
@markcowl Thanks for the help !! 

Unfortunately even after following your steps, I still get the same error. I even tried executing the other tests which had already extended the class `RMTestBase`, but still got the same error.

Can you please re-open this issue ?

**Comment by NimishaS** [comment]
I am also getting this issue. I tried  both solutions, i.e. Extending `RMTestBase`: https://gist.github.com/NimishaS/2342a0bd99d06c3c95e6da2dcbe37bcd#file-chefextensiontests-cs-L21 and calling `SynchronizationContext`: https://gist.github.com/NimishaS/cc4a2e98646a6a08c21ca30081479150#file-chefextensiontests-cs-L40.
I am still getting the same error.

**Comment by fhljys** [comment]
I am also facing this issue. Any solutions?

**Comment by sphibbs** [comment]
@fhljys can you update to the latest test framework. anything greater that >=1.7.1. If that doesn't resolve the issue please re-open
