### ISSUE TITLE
Set-AzureRmVirtualNetworkGatewayConnectionSharedKey command display incorrect failing message.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-powershell#3413]
###  Cmdlet(s)

Set-AzureRmVirtualNetworkGatewayConnectionSharedKey

###  PowerShell Version

5.1.14393.576

###  Module Version

3.4.0

###  OS Version

10.0.14393.576

### Description
Set-AzureRmVirtualNetworkGatewayConnectionSharedKey allways display error. But secret is changed.
This is an obstacle to scripting. 

```
$ Set-AzureRmVirtualNetworkGatewayConnectionSharedKey -ResourceGroupName kinmugiub02 -Name kinmugiub02-gw-kyrtoffice -Value "qwer1234" -Force
Set-AzureRmVirtualNetworkGatewayConnectionSharedKey : The response from long running operation does not contain a body.                                                          
At line:1 char:1                                                                                                                                                                 
+ Set-AzureRmVirtualNetworkGatewayConnectionSharedKey -ResourceGroupNam ...                                                                                                      
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                          
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVirt...ectionSharedKey], NetworkCloudException                                                                         
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionSharedKeyCommand                                                           

$ Get-AzureRmVirtualNetworkGatewayConnectionSharedKey -ResourceGroupName kinmugiub02 -Name kinmugiub02-gw-kyrtoffice
qwer1234
```
                                                                                                                                                                                 

### Debug Output
```

============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/b57e38a4-81b8-4a81-a164-745ef86f034c/resourceGroups/kinmugiub02/providers/Microsoft.Network/connections/kinmugiub02-gw-kyrtoffice/sharedkey?
api-version=2016-09-01

Headers:
x-ms-client-request-id        : 00610b42-0e9b-426f-9822-5c0194741c0c
accept-language               : en-US

Body:



============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 0588515f-8e30-4fde-bd6c-e16f375b539e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14978
x-ms-correlation-request-id   : 830c9e2b-1019-4e47-9dc1-017a8fa9c659
x-ms-routing-request-id       : JAPANEAST:20170122T085130Z:830c9e2b-1019-4e47-9dc1-017a8fa9c659
Date                          : Sun, 22 Jan 2017 08:51:29 GMT

Body:
{
  "value": "kUj21X8Skrl2efmggG1kQ9qb22t2poCc"
}


Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
01/22/2017 08:51:32: 51bbfe0c-ded9-4fa8-91c9-76bef9dc7f37 - AcquireTokenHandlerBase: === Token Acquisition started:

... snip ... 

============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/b57e38a4-81b8-4a81-a164-745ef86f034c/resourceGroups/kinmugiub02/providers/Microsoft.Network/connections/kinmugiub02-gw-kyrtoffice/sharedkey?
api-version=2016-09-01

Headers:
x-ms-client-request-id        : 4bbfa22f-9054-4788-a411-b75f445a104c
accept-language               : en-US

Body:
{
  "value": "qwer1234"
}


============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Retry-After                   : 10
x-ms-request-id               : 3f1a7c6d-cfbb-4753-b41a-4df443c912e3
Azure-AsyncOperation          : https://management.azure.com/subscriptions/b57e38a4-81b8-4a81-a164-745ef86f034c/providers/Microsoft.Network/locations/japanwest/operations/3f1a7c6d-cfb
b-4753-b41a-4df443c912e3?api-version=2016-09-01
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-correlation-request-id   : 6d5478ce-9103-42b0-91d4-ef5d6ba2bea7
x-ms-routing-request-id       : JAPANEAST:20170122T085131Z:6d5478ce-9103-42b0-91d4-ef5d6ba2bea7
Date                          : Sun, 22 Jan 2017 08:51:30 GMT

Body:


... snip ... 
	

============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/b57e38a4-81b8-4a81-a164-745ef86f034c/resourceGroups/kinmugiub02/providers/Microsoft.Network/connections/kinmugiub02-gw-kyrtoffice/sharedkey?
api-version=2016-09-01

Headers:

Body:



============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 193f8b9a-72f5-4fe0-85e2-62d69a7edaf1
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 14977
x-ms-correlation-request-id   : 8f2d0316-ccd5-45d3-b1fe-82fae8d6ecab
x-ms-routing-request-id       : JAPANEAST:20170122T085131Z:8f2d0316-ccd5-45d3-b1fe-82fae8d6ecab
Date                          : Sun, 22 Jan 2017 08:51:30 GMT

Body:
null


Set-AzureRmVirtualNetworkGatewayConnectionSharedKey : The response from long running operation does not contain a body.
At line:1 char:1
+ Set-AzureRmVirtualNetworkGatewayConnectionSharedKey -ResourceGroupNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmVirt...ectionSharedKey], NetworkCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionSharedKeyCommand
 
AzureQoSEvent: CommandName - Set-AzureRmVirtualNetworkGatewayConnectionSharedKey; IsSuccess - False; Duration - 00:00:01.3910120; Exception - Microsoft.Azure.Commands.Network.Common.N
etworkCloudException: The response from long running operation does not contain a body. ---> Microsoft.Rest.Azure.CloudException: The response from long running operation does not con
tain a body.
   at Microsoft.Rest.Azure.AzureClientExtensions.<UpdateStateFromGetResourceOperation>d__12`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.VirtualNetworkGatewayConnectionsOperations.<SetSharedKeyWithHttpMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.VirtualNetworkGatewayConnectionsOperationsExtensions.<SetSharedKeyAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.VirtualNetworkGatewayConnectionsOperationsExtensions.SetSharedKey(IVirtualNetworkGatewayConnectionsOperations operations, String resourceGroup
Name, String virtualNetworkGatewayConnectionName, ConnectionSharedKey parameters)
   at Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionSharedKeyCommand.SetVirtualNetworkGatewayConnectionSharedKey()
   at Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionSharedKeyCommand.<Execute>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action, Func`1 u
seShouldContinue)
   at Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionSharedKeyCommand.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
Finish sending metric.
17:51:34 - NewAzureVirtualNetworkGatewayConnectionSharedKeyCommand end processing.
17:51:34 - NewAzureVirtualNetworkGatewayConnectionSharedKeyCommand end processing.
```

**Comment by markcowl** [comment]
@DeepakRajendranMsft Please take a look

**Comment by takekazuomi** [comment]
confirmed. Thank you.
