### ISSUE TITLE
Investigate: UserPrincipal interactive authentication not working in TestFramework

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#3487]
Multiple teams are reporting that interactive user authentication is not working for test recording.

Users who use their corpnet accounts and supply a subscriptionId in the test connection string should be able to display the dialog to authenticate.

**Comment by jasper-schneider** [comment]
Adding my anecdotal experience.
I was able to successfully record my tests with interactive auth back in November.  It looks like the AAD and Microsoft.Rest.ClientRuntime.Azure.TestFramework packages were updated in December.  When I went to re-record in January, I hit an exception.

The line of code that generated the exception for me was:
context.GetServiceClient<BatchManagementClient>(TestEnvironmentFactory.GetTestEnvironment());
Where context is a MockContext instance created with this code:
using (MockContext context = MockContext.Start(callingClassType, mockName))
BatchManagementClient is an AutoRest-generated ARM service client.

Here's the Exception details I got:
Result StackTrace:	
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.InteractiveLogin(String tenant, ActiveDirectoryServiceSettings aadServiceSettings, ActiveDirectoryServiceSettings graphAADServiceSettings)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.Login()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.RecorderModeSettings()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment..ctor(String connectionString)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironmentFactory.GetTestEnvironment()
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchController.GetBatchManagementClient(MockContext context) in D:\azure-powershell-0\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchController.cs:line 200
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchController.SetupManagementClients(MockContext context) in D:\azure-powershell-0\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchController.cs:line 152
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchController.RunPsTestWorkflow(Func`1 scriptBuilder, Action initialize, Action cleanup, String callingClassType, String mockName) in D:\azure-powershell-0\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchController.cs:line 96
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchController.RunPsTest(String[] scripts) in D:\azure-powershell-0\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchController.cs:line 67
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchAccountTests.TestAadAuth() in D:\azure-powershell-0\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchAccountTests.cs:line 45
----- Inner Stack Trace -----
   at System.Threading.Tasks.SynchronizationContextTaskScheduler..ctor()
   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.<LoginWithPromptAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.Authentication.UserTokenProvider.<LoginWithPromptAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.<>c__DisplayClass38_0.<<InteractiveLogin>b__0>d.MoveNext()
Result Message:	
System.AggregateException : One or more errors occurred.
---- System.InvalidOperationException : The current SynchronizationContext may not be used as a TaskScheduler.

**Comment by markcowl** [comment]
@jasper-schneider It looks like this was removed after we moved the test framework to support .Net Core.   @shahabhijeet  has a fix for this, I believe

**Comment by cormacpayne** [comment]
It looks like the fix is in PR https://github.com/Azure/azure-sdk-for-net/pull/2892

**Comment by markcowl** [comment]
Fixed
