### ISSUE TITLE
Get-AzureRMWebApp fails when running from TFS release task

### ISSUE THREAD

**Issue by mrichman** [Azure/azure-powershell#3803]
Getting this error, even though `Get-AzureRMWebApp` works on the build agent machine from the PS command prompt:

`2017-04-20T17:06:11.8602453Z ##[error]The term 'Get-AzureRMWebApp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again...[sic]`

Installed on the build machine is "Microsoft Azure PowerShell - March 2017" (version 3.7.0), installed via MSI.
 
```
2017-04-20T17:06:11.3297365Z Getting connection details for azureRM WebApp:'888888deploytest' under Production Slot.
 
2017-04-20T17:06:11.3297365Z ##[debug]	 Getting azureRM WebApp:'888888deploytest' details.
 
2017-04-20T17:06:11.3453397Z ##[debug][Azure Call] Getting azure webapp details for webapp with name : 888888deploytest 
 
2017-04-20T17:06:11.4077525Z ##[debug]Leaving C:\Deploy_Agent\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.21\AzureRMWebAppDeployment.ps1.
 
2017-04-20T17:06:11.4233557Z ##[debug]Caught exception from task script.
 
2017-04-20T17:06:11.4389589Z ##[debug]Error record:
 
2017-04-20T17:06:11.6261973Z ##[debug]Get-AzureRMWebAppARM : The term 'Get-AzureRMWebApp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 
2017-04-20T17:06:11.6418005Z ##[debug]At C:\Deploy_Agent\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.21\AzureUtility.ps1:32 char:29
 
2017-04-20T17:06:11.6418005Z ##[debug]+     $azureRMWebAppDetails = Get-AzureRMWebAppARM -Name $webAppName
 
2017-04-20T17:06:11.6418005Z ##[debug]+                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 
2017-04-20T17:06:11.6418005Z ##[debug]    + CategoryInfo          : ObjectNotFound: (Get-AzureRMWebApp:String) [Get-    AzureRMWebAppARM], CommandNotFoundException
 
2017-04-20T17:06:11.6574037Z ##[debug]    + FullyQualifiedErrorId : CommandNotFoundException,Get-AzureRMWebAppARM
 
2017-04-20T17:06:11.6574037Z ##[debug] 
 
2017-04-20T17:06:11.6574037Z ##[debug]Script stack trace:
 
2017-04-20T17:06:11.6730069Z ##[debug]at Get-AzureRMWebAppARM, C:\Deploy_Agent\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.21\AzureUtilityGTE1.0.ps1: line 9
 
2017-04-20T17:06:11.6886101Z ##[debug]at Get-AzureRMWebAppDetails, C:\Deploy_Agent\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.21\AzureUtility.ps1: line 32
 
2017-04-20T17:06:11.6886101Z ##[debug]at Get-AzureRMWebAppConnectionDetailsWithProductionSlot, C:\Deploy_Agent\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.21\AzureUtility.ps1: line 80
 
2017-04-20T17:06:11.6886101Z ##[debug]at Get-AzureRMWebAppConnectionDetails, C:\Deploy_Agent\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.21\AzureUtility.ps1: line 116
 
2017-04-20T17:06:11.6886101Z ##[debug]at <ScriptBlock>, C:\Deploy_Agent\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.21\AzureRMWebAppDeployment.ps1: line 70
 
2017-04-20T17:06:11.7042133Z ##[debug]at <ScriptBlock>, <No file>: line 1
 
2017-04-20T17:06:11.7042133Z ##[debug]at <ScriptBlock>, <No file>: line 22
 
2017-04-20T17:06:11.7042133Z ##[debug]at <ScriptBlock>, <No file>: line 18
 
2017-04-20T17:06:11.7042133Z ##[debug]at <ScriptBlock>, <No file>: line 1
 
2017-04-20T17:06:11.7198165Z ##[debug]Exception:
 
2017-04-20T17:06:11.7354197Z ##[debug]System.Management.Automation.CommandNotFoundException: The term 'Get-AzureRMWebApp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 
2017-04-20T17:06:11.7354197Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
 
2017-04-20T17:06:11.7354197Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
 
2017-04-20T17:06:11.7510229Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-04-20T17:06:11.7510229Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
 
2017-04-20T17:06:11.7510229Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
 
2017-04-20T17:06:11.7510229Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
 
2017-04-20T17:06:11.7666261Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
 
2017-04-20T17:06:11.7666261Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
 
2017-04-20T17:06:11.7666261Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
 
2017-04-20T17:06:11.8602453Z ##[error]The term 'Get-AzureRMWebApp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 
2017-04-20T17:06:11.8602453Z ##[debug]Processed: ##vso[task.logissue type=error]The term 'Get-AzureRMWebApp' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
 
2017-04-20T17:06:11.8758485Z ##[debug]Processed: ##vso[task.complete result=Failed]
 
2017-04-20T17:06:11.9226581Z ##[section]Finishing: Deploy AzureRM Web App: 888888deploytest
```

**Comment by markcowl** [comment]
@mrichman How are you importing the module?  It's possible there is soemthign int he AppDomain that keeps the module from importing - the errors return from Import-Module would likely point to the underlying issue.

**Comment by shahabhijeet** [comment]
@mrichman please reopen this issue, once you can provide more information.
