### ISSUE TITLE
Run 'Add-AzureRmMetricAlertRule' failed

### ISSUE THREAD

**Issue by xucong5151600** [Azure/azure-powershell#3839]
### Cmdlet(s)
Add-AzureRmMetricAlertRule

### PowerShell Version
5.0.10586.672

### Module Version
AzureRM 3.8.0

### OS Version
10.0.10586.672

### Description
When i runned the command 
'Add-AzureRmMetricAlertRule -Name "metricRule5" -Location "East US" -ResourceGroup "Default-Web-EastUS" -Operator GreaterThan -Threshold 1 -TargetResourceId "/subscriptions/b93fb07a-6f93-30be-bf3e-4f0deca15f4f/resourceGroups/Default-Web-EastUS/providers/microsoft.web/sites/mywebsite" -MetricName "Requests" -TimeAggregationOperator Total' in azure powershell

I received the below exception,
Add-AzureRmMetricAlertRule : Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException
' was thrown.

**Comment by cormacpayne** [comment]
@xucong5151600 can you run the same command with `$DebugPreference="Continue"` set?

Also, can you run the script found in [this issue](https://github.com/Azure/azure-powershell/issues/3648) to get more details regarding the error?

**Comment by shahabhijeet** [comment]
@xucong5151600 please provide us more information to get traction on this issue.
If you we dont' hear from you in next 7 days, we will close it.

**Comment by KacperMucha** [comment]
I also stumbled upon this issue. Resolve-Error function returns this:
```powershell
   HistoryId: 58


Message        : Exception type: ErrorResponseException, Message: Exception of type 'Microsoft.WindowsAzure.Management.Monitoring.MonitoringServiceException' was thrown., Code: InternalServerError, Status code:BadRequest, Reason phrase: Bad Request
StackTrace     :    at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {Add-AzureRmMetricAlertRule}
Line           : Add-AzureRmMetricAlertRule `
                 
Position       : At line:1 char:1
                 + Add-AzureRmMetricAlertRule `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 58

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Monitor.Management.AlertRulesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
Exception      : Microsoft.Azure.Management.Monitor.Management.Models.ErrorResponseException
InvocationInfo : {Add-AzureRmMetricAlertRule}
Line           : Add-AzureRmMetricAlertRule `
                 
Position       : At line:1 char:1
                 + Add-AzureRmMetricAlertRule `
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 58
```

The command that I execute:
```powershell
Add-AzureRmMetricAlertRule `
     -Name "ruleName" `
     -Location "West Europe" `
     -ResourceGroup "rgName" `
     -Operator GreaterThan `
     -Threshold 1 `
     -WindowSize 00:05:00 `
     -TargetResourceId "/subscriptions/<subId>/resourcegroups/<rgName>/providers/microsoft.insights/components/appins1" `
     -MetricName "Requests" `
     -TimeAggregationOperator Total
```

I can also add output from command executed with DebugPreference set to Continue later. I'll have to remove subscription ids etc. first.

**Comment by cormacpayne** [comment]
@gucalder Hey Guillermo, would you mind taking a look at this issue?

**Comment by funkycoding** [comment]
I'm experiencing the same issue as @xucong5151600
