### ISSUE TITLE
[error]Move-AzureDeployment : InternalError : The server encountered an internal error. Please retry the request.

### ISSUE THREAD

**Issue by yshahin** [Azure/azure-powershell#3844]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

The version deployed on VSTS

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

The version deployed on VSTS Host Machine

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

+ Move-AzureDeployment -ServiceName $serviceName
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Move-AzureDeployment], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.HostedServices.MoveAzureDeploymentComm 
   and

2017-04-27T14:02:04.2197732Z ##[error]Process completed with exit code 0 and had 1 error(s) written to the error stream.
2017-04-27T14:02:04.2207753Z ##[debug]System.Exception: Process completed with exit code 0 and had 1 error(s) written to the error stream.
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.PowerShellExeHandler.<RunAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
2017-04-27T14:02:04.2217752Z ##[section]Finishing: PowerShell Script

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by singhkays** [comment]
@yshahin Please file a support request for this. This is most likely not a PS bug and something that needs to be investigated withing the platform.

**Comment by cormacpayne** [comment]
@twitchax: "Azure PowerShell continues to maintain RDFE support on a legacy basis: new functionality and bug fixes are addressed sparingly.  This issue does not meet the current threshold for consideration."
