### ISSUE TITLE
New-AzureRmRoleAssignment throws KeyNotFoundException when ran on VSTS

### ISSUE THREAD

**Issue by PropertyOfTuckerSystems** [Azure/azure-powershell#3866]
### Cmdlet(s)
`New-AzureRmRoleAssignment`

### PowerShell Version
`5.1.14393.1066`

### Module Version
```
    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   0.0.4      AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnalysisServicesServer, Get-AzureRmAnalysisServicesServer, Remove-AzureRmAnalysisServicesServer...}
Manifest   3.4.0      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoToken, New-AzureRmApiManagementHostnameConfiguration, New-AzureRmApiManagementRegion...}
Manifest   2.6.0      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRmAutomationDscConfiguration...}
Manifest   2.6.0      AzureRM.Backup                      {Backup-AzureRmBackupItem, Enable-AzureRmBackupContainerReregistration, Get-AzureRmBackupContainer, Register-AzureRmBackupContainer...}
Manifest   2.6.0      AzureRM.Batch                       {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-AzureRmBatchAccountKeys, New-AzureRmBatchAccount...}
Manifest   2.6.0      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-AzureRmCdnProfile, Remove-AzureRmCdnProfile...}
Manifest   0.4.4      AzureRM.CognitiveServices           {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveServicesAccountKey, Get-AzureRmCognitiveServicesAccountSkus, New-AzureRmCognitiveServicesAccount...}
Manifest   2.7.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Update-AzureRmAvailabilitySet...}
Manifest   2.6.0      AzureRM.DataFactories               {Remove-AzureRmDataFactory, Get-AzureRmDataFactoryRun, Get-AzureRmDataFactorySlice, Save-AzureRmDataFactoryLog...}
Manifest   2.6.0      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLakeAnalyticsCatalogCredential, Remove-AzureRmDataLakeAnalyticsCatalogCredential, Remove-AzureRmDataLakeAnalyticsCatalogSecret...}
Manifest   3.4.0      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeStoreFirewallRule, Set-AzureRmDataLakeStoreTrustedIdProvider...}
Manifest   2.6.0      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdownPolicy, Get-AzureRmDtlAutoStartPolicy, Get-AzureRmDtlVMsPerLabPolicy...}
Manifest   2.6.0      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-AzureRmDnsRecordSet, Set-AzureRmDnsRecordSet...}
Manifest   0.0        AzureRM.EventHub
Manifest   2.6.0      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New-AzureRmHDInsightSqoopJobDefinition, Wait-AzureRmHDInsightJob, New-AzureRmHDInsightStreamingMapReduceJobDefinition...}
Manifest   2.6.0      AzureRM.Insights                    {Get-AzureRmUsage, Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-AzureRmLogProfile...}
Manifest   1.2.0      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGroup, Get-AzureRmIotHubConnectionString, Get-AzureRmIotHubJob...}
Manifest   2.6.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Set-AzureKeyVaultCertificateAttribute, Stop-AzureKeyVaultCertificateOperation, Get-AzureKeyVaultCertificateOperation...}
Manifest   2.6.0      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrationAccountCallbackUrl, Get-AzureRmIntegrationAccountCertificate, Get-AzureRmIntegrationAccount...}
Manifest   0.11.4     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentPlanUsageHistory, Remove-AzureRmMlCommitmentPlan...}
Manifest   0.3.4      AzureRM.Media                       {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaServiceKey, Get-AzureRmMediaServiceKeys, Get-AzureRmMediaServiceNameAvailability...}
Manifest   3.5.0      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Get-AzureRmApplicationGatewayAuthenticationCertificate, New-AzureRmApplicationGatewayAuthenticationCertificate, Remove-AzureRmApplicationGatewayAuthenti...
Manifest   2.6.0      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, Get-AzureRmNotificationHubAuthorizationRules, Get-AzureRmNotificationHubListKeys, Get-AzureRmNotificationHubPNSCredentials...}
Manifest   2.6.0      AzureRM.OperationalInsights         {New-AzureRmOperationalInsightsAzureActivityLogDataSource, New-AzureRmOperationalInsightsCustomLogDataSource, Disable-AzureRmOperationalInsightsLinuxCustomLogCollection, Disable-AzureRmOperationalInsightsIISLo...
Manifest   2.6.0      AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollectionAccessKeys, Get-AzureRmPowerBIWorkspace...}
Manifest   2.6.0      AzureRM.Profile                     {Disable-AzureRmDataCollection, Enable-AzureRmDataCollection, Remove-AzureRmEnvironment, Get-AzureRmEnvironment...}
Manifest   2.6.0      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperties, Get-AzureRmRecoveryServicesVault, Get-AzureRmRecoveryServicesVaultSettingsFile, New-AzureRmRecoveryServicesVault...}
Manifest   2.6.0      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Get-AzureRmRecoveryServicesBackupManagementServer, Get-AzureRmRecoveryServicesBackupContainer, Unregister-AzureRmRecoveryServicesBackupContainer...}
Manifest   2.6.0      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCacheScheduleEntry, Get-AzureRmRedisCachePatchSchedule, New-AzureRmRedisCachePatchSchedule...}
Manifest   3.6.0      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, New-AzureRmRoleAssignment...}
Manifest   0.11.4     AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobCollection, Enable-AzureRmSchedulerJobCollection, Get-AzureRmSchedulerJobCollection, Get-AzureRmSchedulerJob...}
Manifest   2.6.0      AzureRM.ServerManagement            {Invoke-AzureRmServerManagementPowerShellCommand, Get-AzureRmServerManagementSession, New-AzureRmServerManagementSession, Remove-AzureRmServerManagementSession...}
Manifest   0.0        AzureRM.ServiceBus
Manifest   3.5.0      AzureRM.SiteRecovery                {Get-AzureRmSiteRecoveryFabric, New-AzureRmSiteRecoveryFabric, Remove-AzureRmSiteRecoveryFabric, Stop-AzureRmSiteRecoveryJob...}
Manifest   2.6.0      AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRmSqlDatabaseTransparentDataEncryptionActivity, Set-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRmSqlDatabaseUpgradeHint...}
Manifest   2.6.0      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-AzureRmStorageAccountKey...}
Manifest   2.6.0      AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyticsDefaultFunctionDefinition, New-AzureRmStreamAnalyticsFunction, Remove-AzureRmStreamAnalyticsFunction...}
Manifest   2.6.0      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Manifest   2.6.0      AzureRM.TrafficManager              {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTrafficManagerEndpoint, Set-AzureRmTrafficManagerEndpoint, Get-AzureRmTrafficManagerEndpoint...}
Manifest   2.6.0      AzureRM.UsageAggregates             Get-UsageAggregates
Manifest   2.6.0      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-AzureRmAppServicePlan, Remove-AzureRmAppServicePlan...}


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   3.5.0      Azure                               {Get-AzureAutomationCertificate, Get-AzureAutomationConnection, New-AzureAutomationConnection, Remove-AzureAutomationConnection...}


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\Storage


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.6.0      Azure.Storage                       {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStorageTableStoredAccessPolicy, New-AzureStorageTable...}
```

### OS Version
`10.0.14393.1066`

### Debug Output
```
DEBUG: 2:12:53 PM - NewAzureRoleAssignmentCommand begin processing with ParameterSet 
'ResourceGroupWithSPNParameterSet'.
DEBUG: 2:12:53 PM - using account id '********'...
DEBUG: [Common.Authentication]: Authenticating using Account: '********', environment: 
DEBUG: 'AzureCloud', tenant: '********'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:53:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:53: f4a18a00-8d65-4669-9776-6f174368a676 - AcquireTokenHandlerBase: === Token Acquisition 
started:
DEBUG:  Authority: https://login.microsoftonline.com/********/
DEBUG:  Resource: https://graph.windows.net/
DEBUG:  ClientId: ********
DEBUG:  CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (1 items)
DEBUG:  Authentication Target: Client
DEBUG:  
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 04/28/2017 21:12:53: f4a18a00-8d65-4669-9776-6f174368a676 - TokenCache: Looking up cache for a token...
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:53: f4a18a00-8d65-4669-9776-6f174368a676 - TokenCache: No matching token was found in the cache
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 04/28/2017 21:12:54: f4a18a00-8d65-4669-9776-6f174368a676 - TokenCache: Storing token in the cache...
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 04/28/2017 21:12:54: f4a18a00-8d65-4669-9776-6f174368a676 - TokenCache: An item was stored in the cache
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:54: f4a18a00-8d65-4669-9776-6f174368a676 - AcquireTokenHandlerBase: === Token Acquisition 
finished 
DEBUG: successfully. An access token was retuned:
DEBUG:  Access Token Hash: BgeI9nBntmLH7aWf3p9EzdxS7Vxj68Rw1pY8FhCsPm0=
DEBUG:  Refresh Token Hash: [No Refresh Token]
DEBUG:  Expiration Time: 04/28/2017 22:12:53 +00:00
DEBUG:  User Hash: null
DEBUG:  
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:54:  - TokenCache: Serializing token cache with 2 items.
DEBUG: 
DEBUG: [Common.Authentication]: Authenticating using Account: '********', environment: 
DEBUG: 'AzureCloud', tenant: '********'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:54:  - TokenCache: Deserialized 2 items to token cache.
DEBUG: 
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 
'********', 
DEBUG: Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', 
ClientRedirect: 
DEBUG: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Renewing token using AppId: '********', AdalConfiguration 
with 
DEBUG: ADDomain: '********', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: 
DEBUG: '1950a258-227b-4e31-a9cf-717495945fc2', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:55: ae803b2c-bb7e-4acb-861c-76043041beac - AcquireTokenHandlerBase: === Token Acquisition 
started:
DEBUG:  Authority: https://login.microsoftonline.com/********/
DEBUG:  Resource: https://management.core.windows.net/
DEBUG:  ClientId: ********
DEBUG:  CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (2 items)
DEBUG:  Authentication Target: Client
DEBUG:  
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 04/28/2017 21:12:55: ae803b2c-bb7e-4acb-861c-76043041beac - TokenCache: Looking up cache for a token...
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:55: ae803b2c-bb7e-4acb-861c-76043041beac - TokenCache: An item matching the requested resource 
was 
DEBUG: found in the cache
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 04/28/2017 21:12:55: ae803b2c-bb7e-4acb-861c-76043041beac - TokenCache: 57.2611253383333 minutes left until 
token in 
DEBUG: cache expires
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:55: ae803b2c-bb7e-4acb-861c-76043041beac - TokenCache: A matching item (access token or refresh
 token 
DEBUG: or both) was found in the cache
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:55: ae803b2c-bb7e-4acb-861c-76043041beac - AcquireTokenHandlerBase: === Token Acquisition 
finished 
DEBUG: successfully. An access token was retuned:
DEBUG:  Access Token Hash: 8tvayE6xZKMQB3H1uX2XwxPdrsiYmo7iWdZHd/5QvSU=
DEBUG:  Refresh Token Hash: [No Refresh Token]
DEBUG:  Expiration Time: 04/28/2017 22:10:10 +00:00
DEBUG:  User Hash: null
DEBUG:  
DEBUG: 
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 04/28/2017 21:12:55:  - TokenCache: Serializing token cache with 2 items.
DEBUG: 
DEBUG: [Common.Authentication]: Received token with LoginType 'OrgId', Tenant: '********', 
DEBUG: UserId: '********'
DEBUG: ============================ HTTP REQUEST ============================
DEBUG: 
DEBUG: HTTP Method:
DEBUG: GET
DEBUG: 
DEBUG: Absolute Uri:
DEBUG: 
https://graph.windows.net/********/servicePrincipals?$filter=servicePrincipalNames/any(c: 
DEBUG: c eq '3171428e-425b-484f-89b1-d30e9e6cc5ad')&api-version=1.6
DEBUG: 
DEBUG: Headers:
DEBUG: x-ms-client-request-id        : 4ec7a1a8-bd5d-4e38-b2dc-b9668d141ec4
DEBUG: accept-language               : en-US
DEBUG: 
DEBUG: Body:
DEBUG: 
DEBUG: 
DEBUG: 
DEBUG: ============================ HTTP RESPONSE ============================
DEBUG: 
DEBUG: Status Code:
DEBUG: Forbidden
DEBUG: 
DEBUG: Headers:
DEBUG: Pragma                        : no-cache
DEBUG: ocp-aad-diagnostics-server-name: JCB9s6WmXDNg4ds5rk3LZoj3HoNycIS+sxNzJbS5Z/w=
DEBUG: request-id                    : eca03055-3aea-440c-b197-30587e7e1e2a
DEBUG: client-request-id             : 0da677e3-b49d-4162-a0cc-b19253ee3cf0
DEBUG: x-ms-dirapi-data-contract-version: 1.6
DEBUG: ocp-aad-session-key           : 
uqtOtjFtlHjJeXRQbuWTGnw8NBtch4l3ZcihPRIUngS0OpA_Tk9Zq8aWMrCoTsuqp-3WXIMQgBRlfeRGy6C_Ajk
DEBUG: Qcp1JB3hp_AVke6jW-njn2b_IYA-YG8ia5N_eRN45.yjWdux6vbuMveRLLEORyGTSKKDWmRKapPfZAREFEj6U
DEBUG: X-Content-Type-Options        : nosniff
DEBUG: DataServiceVersion            : 3.0;
DEBUG: Strict-Transport-Security     : max-age=31536000; includeSubDomains
DEBUG: Access-Control-Allow-Origin   : *
DEBUG: Duration                      : 838854
DEBUG: Cache-Control                 : no-cache
DEBUG: Server                        : Microsoft-IIS/8.5
DEBUG: X-AspNet-Version              : 4.0.30319
DEBUG: X-Powered-By                  : ASP.NET,ASP.NET
DEBUG: Date                          : Fri, 28 Apr 2017 21:12:54 GMT
DEBUG: 
DEBUG: Body:
DEBUG: {
DEBUG:   "odata.error": {
DEBUG:     "code": "Authorization_RequestDenied",
DEBUG:     "message": {
DEBUG:       "lang": "en",
DEBUG:       "value": "Insufficient privileges to complete the operation."
DEBUG:     }
DEBUG:   }
DEBUG: }
DEBUG: 
DEBUG: 
```

### Issue

When ran on VSTS, our script crashes with

```
2017-04-28T20:44:22.8385335Z ------------------------------------------------------------------------------------------------------------------------
2017-04-28T20:44:22.8385335Z System.Collections.Generic.KeyNotFoundException: The provided information does not map to an AD object id.
2017-04-28T20:44:22.8385335Z    at Microsoft.Azure.Commands.Resources.Models.ActiveDirectory.ActiveDirectoryClient.GetObjectId(ADObjectFilterOptions options)
2017-04-28T20:44:22.8385335Z    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.CreateRoleAssignment(FilterRoleAssignmentsOptions parameters)
2017-04-28T20:44:22.8385335Z    at Microsoft.Azure.Commands.Resources.NewAzureRoleAssignmentCommand.ExecuteCmdlet()
2017-04-28T20:44:22.8385335Z    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2017-04-28T20:44:22.8385335Z ------------------------------------------------------------------------------------------------------------------------
```

at `New-AzureRmRoleAssignment` call

Same exact script executes successfully if ran locally. VSTS Azure AD App Principal has been granted "Owner" permission for the subscription.

* Why does not it work considering the permisions are as full as possible?
* The exception should explain what exactly went wrong, what "provided" information does not map to which "AD object id"? This is pretty much useless for API users as it is right now

**Comment by cormacpayne** [comment]
@TarasRoshko the issue is that the user credentials you are using do not have sufficient privileges to access the ADGraph API for the given tenant, and the command is not reacting well to the response.

@darshanhs90 would you mind taking a look at this issue? It appears the error message needs to be improved to handle the given response.

**Comment by gubdar** [comment]
@TarasRoshko could you please specify which ADGraph API permissions are needed to perform this operation ?

**Comment by darshanhs90** [comment]
@TarasRoshko can you retry using the new powershell version 5.1.0 and let me know if it can be repro'd

**Comment by darshanhs90** [comment]
@PropertyOfTuckerSystems ping?

**Comment by cormacpayne** [comment]
Closing due to lack of activity. Please feel free to re-open this issue if you are still facing this issue.
