### ISSUE TITLE
Publish-AzureRmVmDscConfiguration remembers current subscription for the entire session

### ISSUE THREAD

**Issue by brantb** [Azure/azure-powershell#3937]
### Cmdlet(s)
Publish-AzureRmVmDscConfiguration

### PowerShell Version
5.1.15063.138

### Module Version
```
Name            Version
----            -------
AzureRM.Compute 2.9.0
AzureRM.profile 2.8.0
```

### OS Version
10.0.15063.138 (Windows 10)

### Description
The current Azure subscription at the time `Publish-AzureRmVMDscConfiguration` is first run in a session becomes "sticky" and subsequent calls to `Set-AzureRmContext` do not change the subscription used by subsequent calls to `Publish-AzureRmVMDscConfiguration`.

Assumptions:

* You have an Azure account with two subscriptions:
  * Subscription A (ID: AAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA)
  * Subscription B (ID: BBBBBBB-BBBB-4BBB-BBBB-BBBBBBBBBBBB) 
* A storage account named `dscstorage` exists in Subscription B in a resource group named `dscstorage-rg`

### Steps to reproduce:

```powershell
# 1. Create an empty DSC configuration
PS> "Configuration Empty { Node localhost {} }" | Out-File empty.ps1
# 2. Log in to Azure
PS> Login-AzureRmAccount

Environment           : AzureCloud
Account               : <your account>
TenantId              : <tenant>
SubscriptionId        : AAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA
SubscriptionName      : SubscriptionA
CurrentStorageAccount :

# 3. Execute Publish-AzureRmVMDscConfiguration targeting a storage account that does not exist in SubscriptionA.
PS> Publish-AzureRmVMDscConfiguration -ConfigurationPath empty.ps1 -StorageAccountName ignore -ResourceGroupName ignore
# Error:
Publish-AzureRmVMDscConfiguration : Resource group 'dscstorage-rg' could not be found.

# 4. Change the active subscription
PS> Set-AzureRmContext -SubscriptionName SubscriptionB

Environment           : AzureCloud
Account               : <your account>
TenantId              : <tenant>
SubscriptionId        : BBBBBBB-BBBB-4BBB-BBBB-BBBBBBBBBBBB
SubscriptionName      : SubscriptionB
CurrentStorageAccount :

# 5. Run the same command again:
PS> Publish-AzureRmVMDscConfiguration -ConfigurationPath empty.ps1 -StorageAccountName ignore -ResourceGroupName ignore
# Error:
Publish-AzureRmVMDscConfiguration : Resource group 'dscstorage-rg' could not be found.
```

If step 3 is omitted, step 5 succeeds.

### Debug output

Running step 5 with with `-Debug` reveals a problem: The cmdlet is attempting to do a `fetchKeys` from Subscription A and not Subscription B (see the 'Absolute Uri' in the output), which returns HTTP 404.

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/AAAAAAA-AAAA-4AAA-AAAA-AAAAAAAAAAAA/resourceGroups/dscstorage-rg/providers/Microsoft.Stora
ge/storageAccounts/dscstorage/listKeys?api-version=2015-06-15

Headers:
x-ms-client-request-id        : eef7dbd7-fa49-44aa-8236-55467d7e85c4
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 23c333fd-4b07-4c66-855e-de296e0c59ac
x-ms-correlation-request-id   : 23c333fd-4b07-4c66-855e-de296e0c59ac
x-ms-routing-request-id       : CANADACENTRAL:20170509T214825Z:23c333fd-4b07-4c66-855e-de296e0c59ac
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Tue, 09 May 2017 21:48:24 GMT

Body:
{
  "error": {
    "code": "ResourceGroupNotFound",
    "message": "Resource group 'dscstorage' could not be found."
  }
}
}

Publish-AzureRmVMDscConfiguration : Resource group 'dscstorage' could not be found.
At line:1 char:1
+ Publish-AzureRmVMDscConfiguration -ConfigurationPath .\empty.ps1 -Sto ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureRmVMDscConfiguration], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand

DEBUG: AzureQoSEvent: CommandName - Publish-AzureRmVMDscConfiguration; IsSuccess - False; Duration - 00:00:00.8824174; Exception -
Microsoft.Rest.Azure.CloudException: Resource group 'dscstorage' could not be found.
   at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<ListKeysWithHttpMessagesAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<ListKeysAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.ListKeys(IStorageAccountsOperations operations, String
 resourceGroupName, String accountName)
   at Microsoft.Azure.Commands.Compute.Extension.DSC.DscExtensionCmdletCommonBase.GetStorageCredentials(AzureRMCmdlet cmdlet,
String resourceGroupName, String storageAccountName) in
D:\workspace\powershell-sign\src\ResourceManager\Compute\Commands.Compute\Extension\DSC\DscExtensionCmdletCommonBase.cs:line 34
   at Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand.ExecuteCmdlet() in
D:\workspace\powershell-sign\src\ResourceManager\Compute\Commands.Compute\Extension\DSC\PublishAzureVMDscConfigurationCommand.cs:li
ne 143
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in
D:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 642;
```

Workaround: Open a new PowerShell session whenever you need to operate on a different subscription.

**Comment by markcowl** [comment]
@brantb Have you set up a currentstorageaccount in your context?

**Comment by brantb** [comment]
@markcowl I repeated the test and used `Set-AzureRmCurrentStorageAccount` to set a CurrentStorageAccount, but it didn't seem to fix the issue.

**Comment by markcowl** [comment]
@brantb I didn't mean this was a requirement, merely that it might be a necessary precondition for the issue.

**Comment by markcowl** [comment]
@brantb Looking at the code, it appears that the cmdlet is incorrectly caching a storage management client, so that, the first timeyou call Publish or Set DSC Extension cmdlets in a session, it will retain that same client throughout the session, which caches the subscription, regardless of whether you login or switch subscriptions later in the session.

Let me know if this sounds like your scenario.  If so, we'll assign to the compute team to fix - at the very least they should be creating a new storage client whenever the subscription changes.

**Comment by brantb** [comment]
Yeah, that sounds like what might be happening here. I haven’t tested any other *-AzureRmVmDscConfiguration cmdlets to see if they exhibit the same behavior, so I’ll take your word that the Set- version has the same issue.

**Comment by markcowl** [comment]
@singhkays this looks like a caching issue in extension cmdlets for VMS.  Can you take a look and assign appropriately?

**Comment by singhkays** [comment]
@eshaparmar from the DSC team to take a look

**Comment by maddieclayton** [comment]
@eshaparmar Any update on this issue?

**Comment by mithunshanbhag** [comment]
Has there been any resolution to this issue?

**Comment by GabstaMSFT** [comment]
Is this still an issue?
