### ISSUE TITLE
AddAzureRMAccount is failing with SPN for specific user

### ISSUE THREAD

**Issue by niadak** [Azure/azure-powershell#4281]
### Cmdlet(s)
AddAzureRMAccount
### PowerShell Version
Latest

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Add-AzureRMAccount is working with SPN for some user. But if we run the same command with same spn details as different user (Open PowerShell as different user in same machine) it is failing with 403 exception
### Debug Output
##[debug]============================ HTTP REQUEST ============================
2017-05-30T09:43:21.3507639Z HTTP Method:
2017-05-30T09:43:21.3507639Z GET
2017-05-30T09:43:21.3507639Z Absolute Uri:
2017-05-30T09:43:21.3507639Z https://management.azure.com/subscriptions?api-version=2014-04-01-preview
2017-05-30T09:43:21.3507639Z Headers:
2017-05-30T09:43:21.3507639Z Body:
2017-05-30T09:43:21.3663873Z ##[error]System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (403) Forbidden.
2017-05-30T09:43:21.3663873Z ##[error]   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
2017-05-30T09:43:21.3663873Z ##[error]   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
2017-05-30T09:43:21.3663873Z ##[error]   --- End of inner exception stack trace ---
2017-05-30T09:43:21.3663873Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2017-05-30T09:43:21.3663873Z ##[error]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
2017-05-30T09:43:21.3663873Z ##[error]   at Microsoft.Azure.Subscriptions.SubscriptionOperationsExtensions.List(ISubscriptionOperations operations)
2017-05-30T09:43:21.3663873Z ##[error]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.TryGetTenantSubscription(IAccessToken accessToken, AzureAccount account, AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, AzureSubscription& subscription, AzureTenant& tenant)
2017-05-30T09:43:21.3663873Z ##[error]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(AzureAccount account, AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password)
2017-05-30T09:43:21.3820135Z ##[error]   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.ExecuteCmdlet()
2017-05-30T09:43:21.3820135Z ##[error]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
2017-05-30T09:43:21.3820135Z ##[debug]11:43:21 AM - AddAzureRMAccountCommand end processing.
2017-05-30T09:43:21.3820135Z ##[debug]11:43:21 AM - AddAzureRMAccountCommand end processing.

**Comment by markcowl** [comment]
@niadak The above does not provide enouigh information to diagnose the problem.  Can you please include the full script, including the cmdlet invocations with debugging for the login command?

**Comment by markcowl** [comment]
Closing for lack of response.  If you see a recurrence of this problem, please file an issue and include the error and debugging information requested.
