### ISSUE TITLE
Azure classic commands fail with "Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials."

### ISSUE THREAD

**Issue by sscchh2001** [Azure/azure-powershell#4289]
### PowerShell Version
PSVersion                      5.1.15063.413

### Module Version
Azure module v4.1.0

### OS Version
BuildVersion                   10.0.15063.413

### Description
When logging in government cloud (Mooncake), classic commands will remember the first user id and environment I used, and try to authenticate with these info even when I have logged in Azure with other accounts with add-azureaccount. This causes every classic command fail with "Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials."

### Debug Output
PS C:\WINDOWS\system32> get-azurevm -debug
DEBUG: 11:02:57 AM - GetAzureVMCommand begin processing with ParameterSet 'ListAllVMs'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: 11:02:59 AM - using account id 'xxxxxxx@xxxxxxx.partner.onmschina.cn'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxxxx@xxxxxxx.partner.onmschina.cn', environment:'AzureChinaCloud', tenant: 'xxxxxxx-66d7-47a8-8f9f-xxxxxxxxxxxxxxx'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:'xxxxxxx-66d7-47a8-8f9f-xxxxxxx', Endpoint: 'https://login.chinacloudapi.cn/', ClientId:'xxxxxxx-227b-4e31-a9cf-xxxxxxx', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', resourceClientUri:'https://management.core.chinacloudapi.cn/', ValidateAuthrity: 'True'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 07/11/2017 03:03:00:  - AuthenticationContext: ADAL .NET with assembly version '2.28.3.860', file version '2.28.31117.1411' and informational version '78bd21073cfd91768d97894ace1ba90c5b904eec' is running...
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.chinacloudapi.cn/xxxxxxx-66d7-47a8-8f9f-xxxxxxx/', CorrelationId:'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'xxxxxxx-66d7-47a8-8f9f-xxxxxxx', AdEndpoint: 'https://login.chinacloudapi.cn/', ClientId: 'xxxxxxx-227b-4e31-a9cf-xxxxxxx', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 07/11/2017 03:03:00: xxxxxxx-099b-4c52-9d71-xxxxxxx- AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.chinacloudapi.cn/xxxxxxx-66d7-47a8-8f9f-xxxxxxx/
 Resource: https://management.core.chinacloudapi.cn/
 ClientId: xxxxxxx-227b-4e31-a9cf-xxxxxxx
 CacheType: Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache (0 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 07/11/2017 03:03:00: xxxxxxx-099b-4c52-9d71-xxxxxxx- TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 07/11/2017 03:03:00: xxxxxxx-099b-4c52-9d71-xxxxxxx- TokenCache: No matching token was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 07/11/2017 03:03:00:  - WindowsFormsWebAuthenticationDialogBase: Navigating to 'https://login.chinacloudapi.cn/xxxxxxx-66d7-47a8-8f9f-xxxxxxx/oauth2/authorize?resource=https://management.core.chinacloudapi.cn/&client_id=xxxxxxx-227b-4e31-a9cf-xxxxxxx&response_type=code&haschrome=1&redirect_uri=urn:ietf:wg:oauth:2.0:oob&login_hint=xxxxxxx@xxxxxxx.partner.onmschina.cn&client-request-id=xxxxxxx-099b-4c52-9d71-xxxxxxx&prompt=attempt_none&x-client-SKU=.NET&x-client-Ver=2.28.3.860&x-client-CPU=x64&x-client-OS=Microsoft Windows NT 10.0.15063.0&site_id=501358&display=popup'.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 07/11/2017 03:03:01:  - WindowsFormsWebAuthenticationDialogBase: Navigating to 'https://login.partner.microsoftonline.cn/xxxxxxx-66d7-47a8-8f9f-xxxxxxx/oauth2/authorize?resource=https://management.core.chinacloudapi.cn/&client_id=xxxxxxx-227b-4e31-a9cf-xxxxxxx&response_type=code&haschrome=1&redirect_uri=urn:ietf:wg:oauth:2.0:oob&login_hint=xxxxxxx@xxxxxxx.partner.onmschina.cn&client-request-id=e0e7ba1d-099b-4c52-9d71-1a698eeb0673&prompt=attempt_none&x-client-SKU=.NET&x-client-Ver=2.28.3.860&x-client-CPU=x64&x-client-OS=Microsoft Windows NT  10.0.15063.0&site_id=501358&display=popup'.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 :
DEBUG: 07/11/2017 03:03:01: xxxxxxx-099b-4c52-9d71-xxxxxxx- <RunAsync>d__0: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: user_interaction_required: One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.PreTokenRequest()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
 ErrorCode: user_interaction_required
DEBUG: [Common.Authentication]: Received exception User Interaction is required to authenticate this user. Please authenticate using the log in dialog. In PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets., while authenticating.

Confirm
Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure
credentials.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
get-azurevm : Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your
Azure credentials.
At line:1 char:1
+ get-azurevm -debug
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureVM], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.GetAzureVMCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzureVM; IsSuccess - False; Duration - 00:00:05.7849031; Exception - System.ArgumentException: Your Azure credentials have not been set up or have expired, please run Add-AzureAccount to set up your Azure credentials. ---> Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedWithoutPopupException: User Interaction is required to authenticate this user. Please authenticate using the log in dialog. In PowerShell, execute Login-AzureRMAccount for Azure Resource Manager cmdlets or Add-AzureAccount for service management cmdlets. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: user_interaction_required: One of two conditions was encountered: 1. The PromptBehavior.Never flag was passed, but the constraint could not be honored, because user interaction was required. 2. An error occurred during a silent web authentication that prevented the http authentication flow from completing in a short enough time frame
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.DoAcquireToken(AdalConfiguration config, PromptBehavior promptBehavior, String userId, SecureString password) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 246
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.SafeAquireToken(AdalConfiguration config, String showDialog, String userId, SecureString password, Exception& ex) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 177
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.AcquireToken(AdalConfiguration config, String promptBehavior, String userId, SecureString password) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 157
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.GetAccessToken(AdalConfiguration config, String promptBehavior, String userId, SecureString password, String credentialType) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Authentication\UserTokenProvider.cs:line 55
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, IAzureTokenCache tokenCache, String resourceId) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Factories\AuthenticationFactory.cs:line 66
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetSubscriptionCloudCredentials(IAzureContext context, String targetEndpoint) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Factories\AuthenticationFactory.cs:line 158
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetSubscriptionCloudCredentials(IAzureContext context, String targetEndpoint) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Factories\AuthenticationFactory.cs:line 182
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateClient[TClient](IAzureContext context, String endpoint) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Factories\ClientFactory.cs:line 106
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateClient[TClient](IAzureContextContainer profile, IAzureSubscription subscription, String endpoint) in D:\workspace\powershell-sign\src\Common\Commands.Common.Authentication\Factories\ClientFactory.cs:line 164
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.GetAzureVMCommand.ExecuteCommand() in D:\workspace\powershell-sign\src\ServiceManagement\Compute\Commands.ServiceManagement\IaaS\PersistentVMs\GetAzureVM.cs: line 55
   at Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.IaaSDeploymentManagementCmdletBase.ProcessRecord() in D:\workspace\powershell-sign\src\ServiceManagement\Compute\Commands.ServiceManagement\IaaS\IaaSDeploymentManagementCmdletBase.cs:line 97;
DEBUG: Finish sending metric.
DEBUG: 11:03:06 AM - GetAzureVMCommand end processing.
DEBUG: 11:03:06 AM - GetAzureVMCommand end processing.

### Script/Steps for Reproduction
After azure module v4.1.0 installed, log in government Azure by using add-azureaccount and execute classic commands.

**Comment by WillHooke** [comment]
I'm experiencing the same issue, however I can workaround this issue by running the first classic command (e.g. Get-AzureService) 3 or 4 times until it stops returning the credential expired message and starts returning the proper results.

After this, all other classic commands should run as normal.

I believe this issue is related to #332 (#362 and #392) which was _fixed_ in Jan 2016.

**Comment by markcowl** [comment]
@sscchh2001 @WillHooke This is by design.  There is both a current and a default subscription in azure classic.  Use ```select-azurerubscription -Default``` to change the default subscription for subsequent sessions.

**Comment by WillHooke** [comment]
@markcowl 

The -default and -current switches are deprecated according to the command when it is running. Regardless of this however, even running
>Select-AzureSubscription -Default -SubscriptionName ...
Does not resolve the issue.

It appears to be random whether or not Get-AzureService or Get-AzureVM wants to start working.

**Comment by tigerdeccan** [comment]
I am getting this , I use import-azurermcontext to login noninteratively . Is this known issue with this version of module?

Any other Idea how to set default subsciption context ? 

I use for loop to go thorgh each susbcription and run some commands. 

DEBUG: 22:29:59 - SelectAzureSubscriptionCommand begin processing with ParameterSet 'SelectDefaultSubscriptionByNameParameterSet'.
DEBUG: 22:30:02 - using account id 'mumtaz.khan@CCCCC.onmicrosoft.com'...
Select-AzureSubscription : The subscription name Beta doesn't exist.
Parameter name: name
At line:1 char:4
+    Select-AzureSubscription -Default -SubscriptionName $subscription  ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Select-AzureSubscription], ArgumentException
    + FullyQualifiedErrorId : Microsoft.WindowsAzure.Commands.Profile.SelectAzureSubscriptionCommand
 
DEBUG: 22:30:03 - SelectAzureSubscriptionCommand end processing.
DEBUG: 22:30:03 - SelectAzureSubscriptionCommand end processing.
