### ISSUE TITLE
FileNotFoundException during test recording

### ISSUE THREAD

**Issue by MSSedusch** [Azure/azure-powershell#4332]
### Cmdlet(s)
n.a.

### PowerShell Version
Azure/azure-powershell/preview pulled on ~17/07/2017

### Module Version
n.a.

### OS Version
Win 10 Creators Update

### Description
I am trying to re-record the test for the AEM extension. If I record test by test it succeeds. When I try to record all tests at once I get the exception below starting with the second test (the first one is always green/ok). I think this is due to the latest change in azure-powershell\src\ResourceManager\Resources\Commands.ResourceManager\Cmdlets\Implementation\ResourceGroups\GetAzureResourceGroupCmdlet.cs line 81 which was part of PR #4117 

Test Name:	Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests.TestAEMExtensionBasicWindows
Test Outcome:	Failed
Result Message:	
System.Management.Automation.RuntimeException : Test failed due to a non-empty error stream. First error: PowerShell Error Record: C:\Users\sedusch\AppData\Local\Temp\c2af9cd9-c234-4b82-b814-1b8a2342a943\c2af9cd9-c234-4b82-b814-1b8a2342a943\assembly\dl3\605a59ee\04d66c25_a3ffd201\ResourceManagerStartup.ps1
Exception:System.IO.FileNotFoundException: C:\Users\sedusch\AppData\Local\Temp\c2af9cd9-c234-4b82-b814-1b8a2342a943\c2af9cd9-c234-4b82-b814-1b8a2342a943\assembly\dl3\605a59ee\04d66c25_a3ffd201\ResourceManagerStartup.ps1
   at Microsoft.WindowsAzure.Commands.Common.FileUtilities.GetContentFilePath(String startDirectory, String fileName) in C:\work\dev\git\azure-powershell\src\Common\Commands.Common\Utilities\FileUtilities.cs:line 87
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceGroupCmdlet.OnImport() in C:\work\dev\git\azure-powershell\src\ResourceManager\Resources\Commands.ResourceManager\Cmdlets\Implementation\ResourceGroups\GetAzureResourceGroupCmdlet.cs:line 76
   at System.Management.Automation.Runspaces.PSSnapInHelpers.ExecuteModuleInitializer(Assembly assembly, Type[] assemblyTypes, Boolean isModuleLoad)
   at System.Management.Automation.Runspaces.PSSnapInHelpers.AnalyzePSSnapInAssembly(Assembly assembly, String name, PSSnapInInfo psSnapInInfo, PSModuleInfo moduleInfo, Boolean isModuleLoad, Dictionary`2& cmdlets, Dictionary`2& aliases, Dictionary`2& providers, String& helpFile)
   at System.Management.Automation.Runspaces.InitialSessionState.ImportCmdletsFromAssembly(Assembly assembly, PSModuleInfo module)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(PSModuleInfo parentModule, Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found, String shortModuleName, Boolean disableFormatUpdates)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadBinaryModule(Boolean trySnapInName, String moduleName, String fileName, Assembly assemblyToLoad, String moduleBase, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, String prefix, Boolean loadTypes, Boolean loadFormats, Boolean& found)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleNamedInManifest(PSModuleInfo parentModule, ModuleSpecification moduleSpecification, String moduleBase, Boolean searchModulePath, String prefix, SessionState ss, ImportModuleOptions options, ManifestProcessingFlags manifestProcessingFlags, Boolean loadTypesFiles, Boolean loadFormatFiles, Object privateData, Boolean& found, String shortModuleName)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(String moduleManifestPath, ExternalScriptInfo scriptInfo, Hashtable data, Hashtable localizedData, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options, Boolean& containedErrors)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifest(ExternalScriptInfo scriptInfo, ManifestProcessingFlags manifestProcessingFlags, Version minimumVersion, Version maximumVersion, Version requiredVersion, Nullable`1 requiredModuleGuid, ImportModuleOptions& options)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(PSModuleInfo parentModule, String fileName, String moduleBase, String prefix, SessionState ss, Object privateData, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found, Boolean& moduleFileFound)
   at Microsoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(String fileName, String moduleBase, String prefix, SessionState ss, ImportModuleOptions& options, ManifestProcessingFlags manifestProcessingFlags, Boolean& found)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions importModuleOptions, String name)
   at Microsoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord()
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
Details:
Script Stack Trace: at <ScriptBlock>, <No file>: line 1
: Target: 
Check the error stream in the test log for additional errors.
Result StandardOutput:	

### Script/Steps for Reproduction

**Comment by cormacpayne** [comment]
@hovsepm Hey Hovsep, any idea why recording multiple tests at once would be disallowed after your changes?

**Comment by cormacpayne** [comment]
Please re-open this issue if the problem persists.
