### ISSUE TITLE
Running Set-AzureSubscription under multiple subscriptions failing

### ISSUE THREAD

**Issue by n2name** [Azure/azure-powershell#440]
Running Azure PowerShell module under SCOM environment to automate Azure features with multiple subscriptions.
Tested 0.8.13 through 0.9.1, but they are consistently failing.

Repro (for 0.8.13):
1. Ran following command with multiple subscriptions (with all different X509Certificate2 objects)
Set-AzureSubcription  -SubscriptionId $SubscriptionId -SubscriptionName $SubscriptionName -Certificate $cert

2. Sometime fire following error:
System.IO.IOException: The process cannot access the file 'C:\Windows\system32\config\systemprofile\AppData\Roaming\Windows Azure Powershell\AzureProfile.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Microsoft.Azure.Common.Extensions.Models.AzureProfile.Save()
   at System.Management.Automation.CommandProcessorBase.Complete()

** Note that other versions fire out-of-index or similar exceptions. Higher versions than 0.8.13 were safe for the first time, but gradually increased exception chances. Finally, Set-AzureSubscription command were firing exception all the time in the higher versions.

Feel free to contact me if you want to see repro or any question.

**Comment by ogail** [comment]
@n2name for your scenario please use [-Profile](https://github.com/Azure/azure-powershell/wiki/Azure-Profile-Cmdlets) which supports executing cmdlets in parallel.

**Comment by n2name** [comment]
@ogail Thanks for the another direction, but I am looking for the specific scenario that only uses certificate instead of Azure Profile. Do you still have an option to run multiple instances at the same time?
