### ISSUE TITLE
Publish-AzureRmVMDscConfiguration does not work on MacOS

### ISSUE THREAD

**Issue by kensykora** [Azure/azure-powershell#4494]
### Cmdlet(s)

`Publish-AzureRmVMDscConfiguration`

### PowerShell Version

v6.0.0-beta.5

```
PS /Users/kensykora/Workspace/azure> $PSVersionTable                                                                                

Name                           Value                                                                                                    
----                           -----                                                                                                    
PSVersion                      6.0.0-beta                                                                                               
PSEdition                      Core                                                                                                     
GitCommitId                    v6.0.0-beta.5                                                                                            
OS                             Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEAS...
Platform                       Unix                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                      
SerializationVersion           1.1.0.1                                                                                                  
WSManStackVersion              3.0   
```

### Module Version

```
PS /Users/kensykora/Workspace/azure> Get-Module                                                                                     

ModuleType Version    Name                                ExportedCommands                                                              
---------- -------    ----                                ----------------                                                              
Manifest   0.9.1      AzureRM.Compute.Netcore             {Add-AzureRmContainerServiceAgentPoolProfile, Add-AzureRmImageDataDisk, Add...
Manifest   0.9.1      AzureRM.Profile.Netcore             {Add-AzureRmAccount, Add-AzureRmEnvironment, Disable-AzureRmDataCollection,...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-ItemProperty...}               
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}                     
Script     1.1.4.0    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackageProvider...}     
Script     1.1.3.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapability...}         
Script     1.2        PSReadLine                          {Get-PSReadlineKeyHandler, Get-PSReadlineOption, Remove-PSReadlineKeyHandle...
```

### OS Version

OSX 10.12.6   
`Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64`

### Description

When running the Azure commandlet to build powershell DSC manifest archives for uploading to Azure, The command fails with this error message:

`System.DllNotFoundException: Unable to load DLL 'libmi.so': The specified module or one of its dependencies could not be found. (Exception from HRESULT: 0x8007007E)`

### Debug Output

```
PS /Users/kensykora/Workspace/azure> Publish-AzureRmVMDscConfiguration ./src/app/DSC/SupportVM.ps1 -OutputArchivePath test.zip  
DEBUG: 4:54:25 PM - PublishAzureVMDscConfigurationCommand begin processing with ParameterSet 'CreateArchive'.
DEBUG: 4:54:25 PM - using account id 'ksykora@company.com'...
Publish-AzureRmVMDscConfiguration : The pipeline has been stopped.
At line:1 char:1
+ Publish-AzureRmVMDscConfiguration ./src/app/DSC/SupportVM.ps1 -Ou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Publish-AzureRmVMDscConfiguration], PipelineStoppedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand
 
DEBUG: AzureQoSEvent: CommandName - Publish-AzureRmVMDscConfiguration; IsSuccess - False; Duration - 00:00:00.0500310; Exception - 
System.Management.Automation.PipelineStoppedException: The pipeline has been stopped.
   at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)
   at System.Management.Automation.Cmdlet.ThrowTerminatingError(ErrorRecord errorRecord)
   at Microsoft.WindowsAzure.Commands.Common.Extensions.DSC.Publish.DscExtensionPublishCmdletCommonBase.GetRequiredModules(String configurationPath) in 
D:\workspace\powershell-sign-netcore\src\ResourceManager\Compute\Commands.Compute\Extension\DSC\DscExtensionPublishCmdletCommonBase.cs:line 369
   at Microsoft.WindowsAzure.Commands.Common.Extensions.DSC.Publish.DscExtensionPublishCmdletCommonBase.CopyRequiredModules(String configurationPath, String tempZipFolder) in 
D:\workspace\powershell-sign-netcore\src\ResourceManager\Compute\Commands.Compute\Extension\DSC\DscExtensionPublishCmdletCommonBase.cs:line 250
   at Microsoft.WindowsAzure.Commands.Common.Extensions.DSC.Publish.DscExtensionPublishCmdletCommonBase.CreateConfigurationArchive(String configurationPath, String configurationDataPath, String[] additionalPath, String configurationArchivePath, Boolean force, Boolean skipDependencyDetection, String parameterSetName) in 
D:\workspace\powershell-sign-netcore\src\ResourceManager\Compute\Commands.Compute\Extension\DSC\DscExtensionPublishCmdletCommonBase.cs:line 139
   at Microsoft.WindowsAzure.Commands.Common.Extensions.DSC.Publish.DscExtensionPublishCmdletCommonBase.<>c__DisplayClass8_0.<PublishConfiguration>b__0() in 
D:\workspace\powershell-sign-netcore\src\ResourceManager\Compute\Commands.Compute\Extension\DSC\DscExtensionPublishCmdletCommonBase.cs:line 213
   at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.ConfirmAction(Boolean force, String continueMessage, String processMessage, String target, Action action) in 
D:\workspace\powershell-sign-netcore\src\ResourceManager\Common\Commands.ResourceManager.Common\AzureRMCmdlet.cs:line 105
   at Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand.ExecuteCmdlet() in 
D:\workspace\powershell-sign-netcore\src\ResourceManager\Compute\Commands.Compute\Extension\DSC\PublishAzureVMDscConfigurationCommand.cs:line 144
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in 
D:\workspace\powershell-sign-netcore\src\Common\Commands.Common\AzurePSCmdlet.cs:line 642;
DEBUG: Finish sending metric.
DEBUG: 4:54:26 PM - PublishAzureVMDscConfigurationCommand end processing.
DEBUG: 4:54:26 PM - PublishAzureVMDscConfigurationCommand end processing.
Publish-AzureRmVMDscConfiguration : Configuration script '/Users/kensykora/Workspace/azure/src/app/DSC/SupportVM.ps1' 
contained parse errors:
At /Users/kensykora/Workspace/azure/src/app/DSC/SupportVM.ps1:1 char:15
+ Configuration SupportVM
+               ~~~~~~~~~
System.DllNotFoundException: Unable to load DLL 'libmi.so': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Microsoft.Management.Infrastructure.Native.NativeMethods.MI_Application_InitializeV1(UInt32 flags, String applicationID, 
IndirectPtr extendedError, DirectPtr application)
   at Microsoft.Management.Infrastructure.Native.MI_Application.Initialize(String applicationId, MI_Instance& extendedError, MI_Application& application)
   at Microsoft.Management.Infrastructure.Internal.CimApplication.GetApplicationHandle()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at Microsoft.Management.Infrastructure.Internal.CimApplication.get_Handle()
   at Microsoft.Management.Infrastructure.Serialization.CimMofDeserializer..ctor()
   at Microsoft.Management.Infrastructure.Serialization.CimMofDeserializer.Create()
   at Microsoft.PowerShell.DesiredStateConfiguration.CimDSCParser..ctor(OnClassNeeded onClassNeeded)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.ImportClasses(String path, Tuple`2 moduleInfo, Collection`1 errors)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.Initialize(Collection`1 errors, List`1 modulePathList)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Dictionary`2 functionsToDefine, Collection`1 errors, List`1 modulePathList, Boolean cacheResourcesFromMultipleModuleVersions)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.DscClassCache.LoadDefaultCimKeywords(Collection`1 errors)
   at System.Management.Automation.Language.Parser.ConfigurationStatementRule(IEnumerable`1 customAttributes, Token configurationToken)
At /Users/kensykora/Workspace/azure/src/app/DSC/SupportVM.ps1:2 char:1
+ {
+ ~
Unexpected token '{' in expression or statement.
At /Users/kensykora/Workspace/azure/src/app/DSC/SupportVM.ps1:17 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
At line:1 char:1
+ Publish-AzureRmVMDscConfiguration ./src/app/DSC/SupportVM.ps1 -Ou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Publish-AzureRmVMDscConfiguration], ParseException
    + FullyQualifiedErrorId : DscConfigurationParseError,Microsoft.Azure.Commands.Compute.Extension.DSC.PublishAzureVMDscConfigurationCommand
```

### Script/Steps for Reproduction

1. Create a Powershell DSC Script on OSX. This is what I'm using, very simple configuration.

SupportVM.ps1
```powershell
Configuration SupportVM
{
    Import-DscResource -ModuleName PsDesiredStateConfiguration

    Node 'localhost' {
        WindowsFeature Ftp
        {
          Ensure    = "Present"
          Name      = "Web-Ftp-Service"
        }
    }
}
```

2. Run this command: `Publish-AzureRmVMDscConfiguration ./SupportVM.ps1 -OutputArchivePath SupportVM.zip`

**Expected**: Creates zip archive for use in deploying Azure ARM templates  
**Actual**: Throws error as described above

**Comment by sphibbs** [comment]
@kensykora Please open an issue in https://github.com/PowerShell/PowerShell We understand it can be confusing on which product belongs to which repo
