### ISSUE TITLE
Set-AzureRmSqlDatabaseAuditing: Resource not found for the segment 'databases'.

### ISSUE THREAD

**Issue by SvenAelterman** [Azure/azure-powershell#4521]
### Cmdlet(s)
Set-AzureRmSqlDatabaseAuditing

### PowerShell Version
5.1.15063.483

### Module Version
4.3.1

### OS Version
10.0.15063.483

### Description
When using the Set-AzureRmSqlDatabaseAuditing cmdlet (and also the older Set-AzureRmSqlDatabaseAuditingPolicy cmdlet), I am getting this error.

### Debug Output
```
DEBUG: 12:46:12 PM - SetAzureSqlDatabaseAuditing begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 12:46:12 PM - using account id 'snipped'...
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '08/29/2017 18:39:51 +00:00', MultipleResource? 'True', Tenant: '5610b6f3-7901-479d-86c1-750bbdb7a13b', UserId: 'snipped'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'snipped', Name: Snipped, IdProvider: 'live.com', Uid: '6369b918-f686-4472-8d61-33ceada0895e'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '08/29/2017 18:39:51 +00:00' Comparing to '08/29/2017 17:46:12 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:53:39.6516093'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/9e3c3118-9945-460c-b8ab-42c59d36ccd7/resourceGroups/SSIO2017/providers/Microsoft.Sql/servers/ssio2017/databases/Contoso/auditingSettings/Default?api-version=2015-05-01-preview

Headers:

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : 5b6549e7-de37-4a33-8b5f-f1ed219edc4f
x-ms-ratelimit-remaining-subscription-reads: 14872
x-ms-correlation-request-id   : 2dbefd05-3302-400d-8c15-f64fadbe02e7
x-ms-routing-request-id       : SOUTHCENTRALUS:20170829T174612Z:2dbefd05-3302-400d-8c15-f64fadbe02e7
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Tue, 29 Aug 2017 17:46:12 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "properties": {
    "state": "Disabled",
    "storageEndpoint": "",
    "storageAccountAccessKey": "",
    "retentionDays": 0,
    "auditActionsAndGroups": [],
    "storageAccountSubscriptionId": "00000000-0000-0000-0000-000000000000",
    "isStorageSecondaryKeyInUse": false
  },
  "id": "/subscriptions/9e3c3118-9945-460c-b8ab-42c59d36ccd7/resourceGroups/SSIO2017/providers/Microsoft.Sql/servers/ssio2017/databases/Contoso/auditingSettings/Default",
  "name": "Default",
  "type": "Microsoft.Sql/servers/databases/auditingSettings"
}


DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '08/29/2017 18:39:51 +00:00', MultipleResource? 'True', Tenant: '5610b6f3-7901-479d-86c1-750bbdb7a13b', UserId: 'snipped'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'snipped', Name: Snipped, IdProvider: 'live.com', Uid: '6369b918-f686-4472-8d61-33ceada0895e'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '08/29/2017 18:39:51 +00:00' Comparing to '08/29/2017 17:46:12 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:53:39.0957935'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/9e3c3118-9945-460c-b8ab-42c59d36ccd7/resourceGroups/SSIO2017/providers/Microsoft.Sql/servers/ssio2017/databases/Contoso?api-version=201
4-04-01

Headers:

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
x-ms-request-id               : 56c725a3-0361-4113-a32c-fceb382843b1
X-Content-Type-Options        : nosniff
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 14889
x-ms-correlation-request-id   : 0ee22f08-3d30-4399-bf28-5f6620198613
x-ms-routing-request-id       : SOUTHCENTRALUS:20170829T174613Z:0ee22f08-3d30-4399-bf28-5f6620198613
Cache-Control                 : no-store, no-cache
Date                          : Tue, 29 Aug 2017 17:46:12 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "code": "NotFound",
  "message": "Resource not found for the segment 'databases'.",
  "target": null,
  "details": [],
  "innererror": []
}


Set-AzureRmSqlDatabaseAuditing : NotFound: Resource not found for the segment 'databases'.
At line:1 char:18
+ ... tSettings = Set-AzureRmSqlDatabaseAuditing -ResourceGroupName $resour ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmSqlDatabaseAuditing], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Sql.Auditing.Cmdlet.SetAzureSqlDatabaseAuditing
 
DEBUG: AzureQoSEvent: CommandName - Set-AzureRmSqlDatabaseAuditing; IsSuccess - False; Duration - 00:00:01.3195236; Exception - Hyak.Common.CloudException: NotFound: Resource not found for the segment 'databases'.
   at Microsoft.Azure.Management.Sql.LegacySdk.DatabaseOperations.<GetAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Sql.LegacySdk.DatabaseOperationsExtensions.Get(IDatabaseOperations operations, String resourceGroupName, String serverName, String databaseName)
   at Microsoft.Azure.Commands.Sql.Database.Services.AzureSqlDatabaseCommunicator.Get(String resourceGroupName, String serverName, String databaseName)
   at Microsoft.Azure.Commands.Sql.Auditing.Services.SqlAuditAdapter.IsDatabaseInServiceTierForPolicy(String resourceGroupName, String serverName, String databaseName)
   at Microsoft.Azure.Commands.Sql.Auditing.Services.SqlAuditAdapter.SetDatabaseBlobAuditingPolicyV2(DatabaseBlobAuditingSettingsModel model, String storageEndpointSuffix)
   at Microsoft.Azure.Commands.Sql.Auditing.Cmdlet.SqlDatabaseAuditingSettingsCmdletBase.PersistChanges(DatabaseBlobAuditingSettingsModel model)
   at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
   at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:46:14 PM - SetAzureSqlDatabaseAuditing end processing.
DEBUG: 12:46:14 PM - SetAzureSqlDatabaseAuditing end processing.
```

### Script/Steps for Reproduction
```
Set-AzureRmSqlDatabaseAuditing -ResourceGroupName $resourceGroupName `
    -ServerName $serverName -DatabaseName $databaseName `
    -StorageAccountName $storageAccountName `
    -StorageKeyType Primary `
    -RetentionInDays 365 -State Enabled
```

**Comment by SvenAelterman** [comment]
Never mind this... I was targeting the wrong server. Still, the error message could be more descriptive.
