### ISSUE TITLE
Hot Add NIC in Linux VM

### ISSUE THREAD

**Issue by ChandraKamarapu** [Azure/azure-powershell#4565]
### Cmdlet(s)
Add-AzureRmVMNetworkInterface
Update-AzureRmVM 

### PowerShell Version
5.1.15063.502

### OS Version
10.0.15063.502

### Description
Trying to hot add a NIC to a running Linux VM. 
First a Resource Group is deployed with a Linux VM with a single NIC. Later trying to add a second NIC while the VM is running.
Operation failed with "AddingOrDeletingNetworkInterfacesOnARunningVirtualMachineNotSupported"

### Debug Output
DEBUG: AzureQoSEvent: CommandName - Update-AzureRmVM; IsSuccess - False; Duration - 00:00:01.4610511; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: Virtual machine /subscriptions/.../resourceGroups/.../providers/Microsoft.Compute/virtualMachines/... with a single network interface must be stop-deallocated before it can be updated to have multiple network interfaces and vice-versa.
ErrorCode: AddingOrDeletingNetworkInterfacesOnARunningVirtualMachineNotSupported
ErrorMessage: Virtual machine /subscriptions/.../resourceGroups/.../providers/Microsoft.Compute/virtualMachines/... with a single network interface must be stop-deallocated before it can be updated to have multiple network interfaces and vice-versa.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : fed45ef1-36d4-4136-a905-d3d4710be2cb ---> Microsoft.Rest.Azure.CloudException: Virtual machine /subscriptions/.../resourceGroups/.../providers/Microsoft.Compute/virtualMachines/... with a single network interface must be stop-deallocated before it can be updated to have multiple network interfaces and vice-versa.
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.<ExecuteCmdlet>b__8_0() in D:\workspace\powershell-sign\src\ResourceManager\Compute\Commands.Compute\VirtualMachine\Operation\UpdateAzureVMCommand.cs:line 61
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action) in D:\workspace\powershell-sign\src\ResourceManager\Compute\Commands.Compute\Common\ComputeClientBaseCmdlet.cs:line 60
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action) in D:\workspace\powershell-sign\src\ResourceManager\Compute\Commands.Compute\Common\ComputeClientBaseCmdlet.cs:line 73
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.ExecuteCmdlet() in D:\workspace\powershell-sign\src\ResourceManager\Compute\Commands.Compute\VirtualMachine\Operation\UpdateAzureVMCommand.cs:line 69
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in D:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 642;
DEBUG: Finish sending metric.
DEBUG: 11:52:15 - UpdateAzureVMCommand end processing.
DEBUG: 11:52:15 - UpdateAzureVMCommand end processing.

### Script/Steps for Reproduction
1. Deploy a Resource Group with Linux VM and single NIC
2. Add another NIC to the Resource Group while VM is running
3. Now update the VM with the newly added NIC
4. Operation fails with error code AddingOrDeletingNetworkInterfacesOnARunningVirtualMachineNotSupported

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, would you mind taking a look at this issue? Is this by design in the API?

**Comment by cormacpayne** [comment]
@chandrasekarsrinivasan Hey Chandrasekar, would you mind taking a look at this issue?

**Comment by maddieclayton** [comment]
@koralski @nibhat @savyasachisamal Can you take a look at this issue?

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
