### ISSUE TITLE
Azure PowerShell task fails to init Azure subscriptions

### ISSUE THREAD

**Issue by rokmicrosoft** [Azure/azure-powershell#4883]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `4.4.0`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
Azure PowerShell task - fails to init Azure subscriptions

Select-AzureRMSubscription cmdlet is failing with error "Please provide a valid tenant or a valid subscription"

Stackoverflow issue link - https://stackoverflow.microsoft.com/questions/68389/vsts-build-release-azure-powershell-task-fails-to-init-azure-subscriptions 

### Debug Output
From our end we have already verified we are passing valid subscription  and tenant Id.
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/VstsAzureHelpers_/InitializeFunctions.ps1#L186

Still we are getting error "Please provide a valid tenant or a valid subscription", as per following code
https://github.com/Azure/azure-powershell/blob/f34c546fea58d48819e968cab9ac3dd5c50551f3/src/ResourceManager/Profile/Commands.Profile/Models/RMProfileClient.cs#L297

This issue is intermittent. Please provide your suggestion over this issue.

**Comment by markcowl** [comment]
@rokmicrosoft There could be lots of causes for this.  Can you please provide:

- The result when running the cmdlet with ```$DebugPreference="Continue"```
- The list of installed modules, by running ```Get-Module -ListAvailable```

**Comment by Ajay-MS** [comment]
@markcowl 

I will again have a call today with the customer and will share info you asked for.  Apart from that, I have few more info from last scheduled call. 

We downgraded Azure PS version to 4.0.0, few instance of Select-AzureRmSubscription worked fine there. But later we encountered the following issue. 
Error - "Provided subscription <Guid> does not exist"

**Comment by Ajay-MS** [comment]
@markcowl 

Below result is with Azure PS version 4.0.0

The result when running the cmdlet with $DebugPreference="Continue" 
[Skype Build Result](https://skype.visualstudio.com/DefaultCollection/SCC/CALLINGAPPS/_build/index?buildId=676952&_a=summary )

The list of installed modules, by running Get-Module -ListAvailable 
Since output list is long sharing it on mail.

**Comment by Ajay-MS** [comment]
@markcowl 

Below result is with Azure PS 4.0.0

The result when running the cmdlet with $DebugPreference="Continue" 
[Skype Build Result](https://skype.visualstudio.com/DefaultCollection/SCC/CALLINGAPPS/_build/index?buildId=676952&_a=summary)

Output of Get-Module -ListAvailable
Sharing on mail as the list is long.

**Comment by markcowl** [comment]
@Ajay-MS This link is  to a large set of logs, not the information we requested.  It is inefficient to expect us to pick through your logs looking for the data that we asked for. If you have specific debug logs with $DebugPreference=Continue" set, then please include them here.  Otherwise, we will have to close this as no repro.

Also, have you executed with the latest version of Azure PowerShell?  This is more than 5 versions out of date.

**Comment by Ajay-MS** [comment]
@markcowl 

We have tried with version 4.4.0 and 4.0.0 we are facing this issue with both the versions though error message is different in both cases and we have an almost continuous repo of this issue. I can add you to customer thread where you can directly check repro on customer setup. Also,  customer is blocked because of this issue. 

Error with version 4.4.0
Please provide a valid tenant or a valid subscription

Error with version 4.0.0
Provided subscription does not exist

Login is takin place as follow : 
```
 $psCredential = New-Object System.Management.Automation.PSCredential(
            <ServicePrincipalId>,
            (ConvertTo-SecureString <ServicePrincipalKey> -AsPlainText -Force))
Add-AzureRMAccount -ServicePrincipal -Tenant <TenantId> -Credential $psCredential -Environment "AzureCloud"
```

Snippet of code with $DebugPreference="Continue"
```
##[command]Add-AzureRMAccount -ServicePrincipal -Tenant ******** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
##[debug]2:08:12 PM - AddAzureRMAccountCommand begin processing with ParameterSet 'ServicePrincipalWithSubscriptionId'.
##[debug]Performing the operation "log in" on target "ServicePrincipal account in environment 'AzureCloud'".
##[debug][Common.Authentication]: Authenticating using configuration values: Domain: '********', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
##[debug]10/31/2017 14:08:12:  - AuthenticationContext: ADAL .NET with assembly version '2.28.3.860', file version '2.28.31117.1411' and informational version '78bd21073cfd91768d97894ace1ba90c5b904eec' is running...
##[debug]
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
##[debug]10/31/2017 14:08:12: 9c29a2d5-b35f-4631-9e64-f57df0e11d11 - AcquireTokenHandlerBase: === Token Acquisition started:
##[debug]	Authority: https://login.microsoftonline.com/********/
##[debug]	Resource: https://management.core.windows.net/
##[debug]	ClientId: ********
##[debug]	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (0 items)
##[debug]	Authentication Target: Client
##[debug]	
##[debug]
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
##[debug]10/31/2017 14:08:12: 9c29a2d5-b35f-4631-9e64-f57df0e11d11 - TokenCache: Looking up cache for a token...
##[debug]
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
##[debug]10/31/2017 14:08:12: 9c29a2d5-b35f-4631-9e64-f57df0e11d11 - TokenCache: No matching token was found in the cache
##[debug]
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
##[debug]10/31/2017 14:08:12: 9c29a2d5-b35f-4631-9e64-f57df0e11d11 - TokenCache: Storing token in the cache...
##[debug]
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
##[debug]10/31/2017 14:08:12: 9c29a2d5-b35f-4631-9e64-f57df0e11d11 - TokenCache: An item was stored in the cache
##[debug]
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
##[debug]10/31/2017 14:08:12: 9c29a2d5-b35f-4631-9e64-f57df0e11d11 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
##[debug]	Access Token Hash: rYhpjvJqS0QzvWb2VKZlnMHJ0cd7H4KY5F6cENfztRI=
##[debug]	Refresh Token Hash: [No Refresh Token]
##[debug]	Expiration Time: 10/31/2017 15:08:11 +00:00
##[debug]	User Hash: null
##[debug]	
##[debug]
##[debug]Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
##[debug]10/31/2017 14:08:12:  - TokenCache: Serializing token cache with 1 items.
##[debug]
##[debug]============================ HTTP REQUEST ============================
##[debug]
##[debug]HTTP Method:
##[debug]GET
##[debug]
##[debug]Absolute Uri:
##[debug]https://management.azure.com/subscriptions?api-version=2016-06-01
##[debug]
##[debug]Headers:
##[debug]x-ms-client-request-id        : 5a7733cc-7e40-41df-b876-337430a6815d
##[debug]accept-language               : en-US
##[debug]
##[debug]Body:
##[debug]
##[debug]
##[debug]
##[debug]============================ HTTP RESPONSE ============================
##[debug]
##[debug]Status Code:
##[debug]OK
##[debug]
##[debug]Headers:
##[debug]Pragma                        : no-cache
##[debug]x-ms-ratelimit-remaining-tenant-reads: 14999
##[debug]x-ms-request-id               : f5fd0ac9-59d9-4c15-94a7-c36a2e2277c0
##[debug]x-ms-correlation-request-id   : f5fd0ac9-59d9-4c15-94a7-c36a2e2277c0
##[debug]x-ms-routing-request-id       : UKSOUTH:20171031T140819Z:f5fd0ac9-59d9-4c15-94a7-c36a2e2277c0
##[debug]Strict-Transport-Security     : max-age=31536000; includeSubDomains
##[debug]Cache-Control                 : no-cache
##[debug]Date                          : Tue, 31 Oct 2017 14:08:19 GMT
##[debug]
##[debug]Body:
##[debug]{
##[debug]  "value": [
##[debug]    {
##[debug]      "id": "/subscriptions/a8371868-e497-4381-ac53-fa6fdf57673a",
##[debug]      "subscriptionId": "a8371868-e497-4381-ac53-fa6fdf57673a",
##[debug]      "displayName": "Skype-CallRecorder-Dev",
##[debug]      "state": "Enabled",
##[debug]      "subscriptionPolicies": {
##[debug]        "locationPlacementId": "Internal_2014-09-01",
##[debug]        "quotaId": "Internal_2014-09-01",
##[debug]        "spendingLimit": "Off"
##[debug]      },
##[debug]      "authorizationSource": "RoleBased"
##[debug]    }
##[debug]  ]
##[debug]}
##[debug]
##[debug]
##[debug]2:08:20 PM - AddAzureRMAccountCommand end processing.
##[debug]2:08:20 PM - AddAzureRMAccountCommand end processing.
##[debug]Debug1 Getting subscription details
##[debug]2:08:20 PM - GetAzureRMSubscriptionCommand begin processing with ParameterSet 'ListByIdInTenant'.
##[debug]2:08:20 PM - using account id '********'...
##[debug][Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
##[debug][Common.Authentication]: Renewing token using AppId: '********', AdalConfiguration with ADDomain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
##[warning]Unable to acquire token for tenant 'Common'
##[debug]Processed: ##vso[task.logissue type=warning]Unable to acquire token for tenant 'Common'
##[debug][Common.Authentication]: Authenticating using configuration values: Domain: '********', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
##[debug][Common.Authentication]: Renewing token using AppId: '********', AdalConfiguration with ADDomain: '********', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
##[warning]Unable to acquire token for tenant '********'
##[debug]Processed: ##vso[task.logissue type=warning]Unable to acquire token for tenant '********'
##[debug]2:08:20 PM - GetAzureRMSubscriptionCommand end processing.
##[debug]2:08:20 PM - GetAzureRMSubscriptionCommand end processing.
##[debug]Debug2 Got subscription details
##[command]Select-AzureRMSubscription -SubscriptionId a8371868-e497-4381-ac53-fa6fdf57673a -TenantId ********
##[debug]2:08:20 PM - SetAzureRMContextCommand begin processing with ParameterSet 'SubscriptionId'.
##[debug]2:08:20 PM - using account id '********'...
##[debug]Switching targeted subscription in the context to 'a8371868-e497-4381-ac53-fa6fdf57673a'
##[debug][Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
##[debug][Common.Authentication]: Renewing token using AppId: '********', AdalConfiguration with ADDomain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
##[debug][Common.Authentication]: Authenticating using configuration values: Domain: '********', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
##[debug][Common.Authentication]: Renewing token using AppId: '********', AdalConfiguration with ADDomain: '********', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', RedirectUri: 'urn:ietf:wg:oauth:2.0:oob'
##[debug]Error record:
##[debug]Select-AzureRMSubscription : Provided subscription a8371868-e497-4381-ac53-fa6fdf57673a does not exist
##[debug]At D:\a\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.0.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1:200 char:13
##[debug]+     $null = Select-AzureRMSubscription -SubscriptionId $SubscriptionI ...
##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : CloseError: (:) [Set-AzureRmContext], ArgumentException
##[debug]    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand
##[debug] 
##[debug]Script stack trace:
##[debug]at Set-CurrentAzureRMSubscription, D:\a\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.0.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 200
##[debug]at Initialize-AzureSubscription, D:\a\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.0.2\ps_modules\VstsAzureHelpers_\InitializeFunctions.ps1: line 153
##[debug]at Initialize-Azure, D:\a\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.0.2\ps_modules\VstsAzureHelpers_\VstsAzureHelpers_.psm1: line 48
##[debug]at <ScriptBlock>, D:\a\_work\_tasks\AzurePowerShell_72a1931b-effb-4d2e-8fd8-f8472a07cb62\2.0.2\AzurePowerShell.ps1: line 50
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.ArgumentException: Provided subscription a8371868-e497-4381-ac53-fa6fdf57673a does not exist
##[debug]   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.SetCurrentContext(String subscriptionId, String subscriptionName, String tenantId)
##[debug]   at Microsoft.Azure.Commands.Profile.SetAzureRMContextCommand.ExecuteCmdlet()
##[debug]   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
##[error]Provided subscription a8371868-e497-4381-ac53-fa6fdf57673a does not exist
##[debug]Processed: ##vso[task.logissue type=error]Provided subscription a8371868-e497-4381-ac53-fa6fdf57673a does not exist
##[debug]2:08:20 PM - SetAzureRMContextCommand end processing.
##[debug]2:08:20 PM - SetAzureRMContextCommand end processing.
##[debug]Leaving Initialize-Azure.
##[command]& 'D:\a\_work\_temp\7c181a7b-64a9-4548-b5c1-339fc1580d38.ps1' 
##[warning]Unable to acquire token for tenant 'Common'
##[debug]Processed: ##vso[task.logissue type=warning]Unable to acquire token for tenant 'Common'
##[warning]Unable to acquire token for tenant '********'
##[debug]Processed: ##vso[task.logissue type=warning]Unable to acquire token for tenant '********'
##[section]Finishing: Build, Test copy
```

Please let me know if you need some other info.

**Comment by markcowl** [comment]
@rokmicrosoft What value did you enter for the ```-Tenant``` parameter in Add-AzureRmAccount? ?  Was this a GUID or a domain name?

You must use a tenantID (GUID) in this case.

**Comment by maddieclayton** [comment]
@rokmicrosoft Are you still seeing this issue?

**Comment by markcowl** [comment]
Closing for lack of response.  Please open a new issue if you see this recur in 5.x
