### ISSUE TITLE
AuthorizationFailed on Powershell since installing latest Azure Powershell version

### ISSUE THREAD

**Issue by ColinM9991** [Azure/azure-powershell#4929]
### Cmdlet(s)

`Get-AzureRmApiManagement`

### PowerShell Version
`PSVersion                      4.0`

### OS Version
`BuildVersion                   6.3.9600.18728    `

### Description

Since updating to the latest version of the Azure Powershell cmdlets, I am getting an "AuthorizationFailed" error when attempting to do anything with Azure cmdlets on Powershell.

I am able to perform these operations just fine via the web portal.

### Debug Output

> DEBUG: 17:34:06 - GetAzureApiManagement begin processing with ParameterSet 'All In Resource Group'.
> DEBUG: 17:34:06 - using account id '<Email>'...
> DEBUG: [Common.Authentication]: Authenticating using Account: '<Email>', environment: 'AzureCloud', tenant: '<TenantId>'
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
> DEBUG: 11/06/2017 17:34:06:  - TokenCache: Serializing token cache with 2 items.
> 
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
> DEBUG: 11/06/2017 17:34:06:  - TokenCache: Serializing token cache with 2 items.
> 
> DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '<TenantId>', Endpoint: 'https://login.microsoftonline.com/', ClientId: '<ClientId>
> fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
> DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/<TenantId>/', CorrelationId: '00000000-0000-0000-0000-000000000000', Validate
> Authority: 'True'
> DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '<TenantId>', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '<ClientId>', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
> DEBUG: 11/06/2017 17:34:06: 11c741fb-747d-46d1-b6ba-c54187b7819f - AcquireTokenHandlerBase: === Token Acquisition started:
> 	Authority: https://login.microsoftonline.com/<TenantId>/
> 	Resource: https://management.core.windows.net/
> 	ClientId: <ClientId>
> 	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
> 	Authentication Target: User
> 	
> 
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
> DEBUG: 11/06/2017 17:34:06: 11c741fb-747d-46d1-b6ba-c54187b7819f - TokenCache: Looking up cache for a token...
> 
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
> DEBUG: 11/06/2017 17:34:06: 11c741fb-747d-46d1-b6ba-c54187b7819f - TokenCache: An item matching the requested resource was found in the cache
> 
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
> DEBUG: 11/06/2017 17:34:06: 11c741fb-747d-46d1-b6ba-c54187b7819f - TokenCache: 59.8718666666667 minutes left until token in cache expires
> 
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
> DEBUG: 11/06/2017 17:34:06: 11c741fb-747d-46d1-b6ba-c54187b7819f - TokenCache: A matching item (access token or refresh token or both) was found in the cache
> 
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
> DEBUG: 11/06/2017 17:34:06: 11c741fb-747d-46d1-b6ba-c54187b7819f - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
> 	Access Token Hash: <AccessTokenHash>
> 	Refresh Token Hash: <RefreshTokenHash>
> 	Expiration Time: 11/06/2017 18:33:58 +00:00
> 	User Hash: C74OekdmEya87NIp8GRs1RLjoQuy84QpMI6qqE4JVLI=
> 	
> 
> DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
> DEBUG: 11/06/2017 17:34:06:  - TokenCache: Serializing token cache with 2 items.
> 
> DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '<TenantId>', UserId: '<Email>'
> DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '11/06/2017 18:33:58 +00:00', MultipleResource? 'True', Tenant: '<TenantId>', UserId: 'Colin.Murphy@callcreditgro
> up.com'
> DEBUG: [Common.Authentication]: User info for token DisplayId: '<Email>', Name: Colin Murphy, IdProvider: 'https://sts.windows.net/<TenantId>/', Uid: '<Uid>'
> DEBUG: [Common.Authentication]: Checking token expiration, token expires '11/06/2017 18:33:58 +00:00' Comparing to '11/06/2017 17:34:06 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:59:5
> 2.3110000'
> DEBUG: ============================ HTTP REQUEST ============================
> 
> HTTP Method:
> GET
> 
> Absolute Uri:
> https://management.azure.com/subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupName>/providers/Microsoft.ApiManagement/service/?api-version=2016-10-10
> 
> Headers:
> 
> Body:
> 
> 
> 
> DEBUG: ============================ HTTP RESPONSE ============================
> 
> Status Code:
> Forbidden
> 
> Headers:
> Pragma                        : no-cache
> x-ms-failure-cause            : gateway
> x-ms-request-id               : 66628454-192a-42d4-b972-f0b814486d0d
> x-ms-correlation-request-id   : 66628454-192a-42d4-b972-f0b814486d0d
> x-ms-routing-request-id       : UKSOUTH:20171106T173406Z:66628454-192a-42d4-b972-f0b814486d0d
> Strict-Transport-Security     : max-age=31536000; includeSubDomains
> Connection                    : close
> Cache-Control                 : no-cache
> Date                          : Mon, 06 Nov 2017 17:34:05 GMT
> 
> Body:
> {
>   "error": {
>     "code": "AuthorizationFailed",
>     "message": "The client '<Email>' with object id '<ObjectId>' does not have authorization to perform action 'Microsoft.ApiManagement/service/read' over scope '/s
> ubscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupName>/providers/Microsoft.ApiManagement'."
>   }
> }
> 
> 
> Get-AzureRmApiManagement : AuthorizationFailed: The client '<Email>' with object id '<ObjectId>' does not have authorization to perform action 
> 'Microsoft.ApiManagement/service/read' over scope '/subscriptions/<SubscriptionId>/resourceGroups/<ResourceGroupName>/providers/Microsoft.ApiManagement'.
> At line:9 char:25
> + $apiManagementService = Get-AzureRmApiManagement -ResourceGroupName $ResourceGro ...
> +                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : CloseError: (:) [Get-AzureRmApiManagement], CloudException
>     + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.Commands.GetAzureApiManagement
>  
> DEBUG: AzureQoSEvent: CommandName - Get-AzureRmApiManagement; IsSuccess - False; Duration - 00:00:00.2841025; Exception - Hyak.Common.CloudException: AuthorizationFailed: The client '<Email>
> ' with object id '<ObjectId>' does not have authorization to perform action 'Microsoft.ApiManagement/service/read' over scope '/subscriptions/<SubscriptionId>/resourceGr
> oups/<ResourceGroupName>/providers/Microsoft.ApiManagement'.
>    at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
>    at Microsoft.Azure.Management.ApiManagement.ResourceProviderOperationsExtensions.List(IResourceProviderOperations operations, String resourceGroupName)
>    at Microsoft.Azure.Commands.ApiManagement.ApiManagementClient.ListApiManagements(String resourceGroupName)
>    at Microsoft.Azure.Commands.ApiManagement.Commands.GetAzureApiManagement.ExecuteCmdlet()
>    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
> DEBUG: Finish sending metric.
> DEBUG: 17:34:07 - GetAzureApiManagement end processing.
> DEBUG: 17:34:07 - GetAzureApiManagement end processing.

### Script/Steps for Reproduction

1. Create a new Powershell script with the following contents

```powershell
Login-AzureRmAccount

$DebugPreference="Continue"
$ResourceGroupName = "<ResourceGroupNameHere>"

$apiManagementService = Get-AzureRmApiManagement -ResourceGroupName $ResourceGroupName | Select-Object -first 1```


2. Execute script

**Comment by ColinM9991** [comment]
This issue was being caused by the wrong subscription being loaded as the default, which I have restricted access to.

I have resolved this by using

`Add-AzureRmAccount -Subscription "Subscription Guid"`
