### ISSUE TITLE
Get-AzureRmApiManagementProduct unsupported mapping

### ISSUE THREAD

**Issue by tom-canova** [Azure/azure-powershell#4944]
### Cmdlet(s)
Get-AzureRmApiManagementProduct

### PowerShell Version
5.1.14409.1012

### Module Version
5.0.0
### OS Version
10.0.14409.1012

### Description
Cannot use Get-AzureRmApiManagementProduct command (and some other api management commands).   It complains about missing type map configuration or unsupported mapping.

### Debug Output
```
PS C:\Users\ewq1ahe> Get-AzureRmApiManagementProduct -Context $context
Get-AzureRmApiManagementProduct : Missing type map configuration or unsupported mapping.
Mapping types:
ProductContract -> PsApiManagementProduct
Microsoft.Azure.Management.ApiManagement.SmapiModels.ProductContract -> Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementProduct
Destination path:
IList1[0]
Source value:
Microsoft.Azure.Management.ApiManagement.SmapiModels.ProductContract
At line:1 char:1
+ Get-AzureRmApiManagementProduct -Context $context
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmApiManagementProduct], AutoMapperMappingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.GetAzureApiManagementProduct
```

### Script/Steps for Reproduction
```
Login-AzureRmAccount
$context = New-AzureRmApiManagementContext -resourcegroup '****' -servicename '****'
Get-AzureRmApiManagementProduct -Context $context
```

**Comment by markcowl** [comment]
@tom-canova Can you execute ```Resolve-AzureRmError``` after this error occurs to provide additional details abotu the exception?

**Comment by markcowl** [comment]
@solankisamir Samir, can you take a look?

**Comment by solankisamir** [comment]
Taking a look

**Comment by solankisamir** [comment]
couldn't repro.
Installed 5.0.0      AzureRM.ApiManagement  

and tried the above cmdlet sequence. It works for me.

**Comment by tom-canova** [comment]
Our Api Management instance is setup with a virtual network.  Not sure if that matters in this case.  Here's the output of Resolve-AzureRmError
```
PS C:\Users\ewq1ahe> Resolve-AzureRmError


   HistoryId: 50


Message        : Missing type map configuration or unsupported mapping.

                 Mapping types:
                 ProductContract -> PsApiManagementProduct
                 Microsoft.Azure.Management.ApiManagement.SmapiModels.ProductContract ->
                 Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementProduct

                 Destination path:
                 IList`1[0]

                 Source value:
                 Microsoft.Azure.Management.ApiManagement.SmapiModels.ProductContract
StackTrace     :    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ProductList(PsApiManagementContext context, String title)
                 in D:\workspace\powershell-sign\src\ResourceManager\ApiManagement\Commands.ApiManagement.ServiceManagement\ApiManagementClient.cs:line 690
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.GetAzureApiManagementProduct.ExecuteApiManagementCmdlet() in D:\worksp
                 ace\powershell-sign\src\ResourceManager\ApiManagement\Commands.ApiManagement.ServiceManagement\Commands\GetAzureApiManagementProduct.cs:line
                 55
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet() in D:\workspace\powershel
                 l-sign\src\ResourceManager\ApiManagement\Commands.ApiManagement.ServiceManagement\Commands\AzureApiManagementCmdletBase.cs:line 55
Exception      : AutoMapper.AutoMapperMappingException
InvocationInfo : {Get-AzureRmApiManagementProduct}
Line           : Get-AzureRmApiManagementProduct -Context $context
Position       : At line:1 char:1
                 + Get-AzureRmApiManagementProduct -Context $context
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 50



   HistoryId: 47


Message        : Missing type map configuration or unsupported mapping.

                 Mapping types:
                 ProductContract -> PsApiManagementProduct
                 Microsoft.Azure.Management.ApiManagement.SmapiModels.ProductContract ->
                 Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Models.PsApiManagementProduct

                 Destination path:
                 IList`1[0]

                 Source value:
                 Microsoft.Azure.Management.ApiManagement.SmapiModels.ProductContract
StackTrace     :    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ProductList(PsApiManagementContext context, String title)
                 in D:\workspace\powershell-sign\src\ResourceManager\ApiManagement\Commands.ApiManagement.ServiceManagement\ApiManagementClient.cs:line 690
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.GetAzureApiManagementProduct.ExecuteApiManagementCmdlet() in D:\worksp
                 ace\powershell-sign\src\ResourceManager\ApiManagement\Commands.ApiManagement.ServiceManagement\Commands\GetAzureApiManagementProduct.cs:line
                 55
                    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet() in D:\workspace\powershel
                 l-sign\src\ResourceManager\ApiManagement\Commands.ApiManagement.ServiceManagement\Commands\AzureApiManagementCmdletBase.cs:line 55
Exception      : AutoMapper.AutoMapperMappingException
InvocationInfo : {Get-AzureRmApiManagementProduct}
Line           : Get-AzureRmApiManagementProduct -Context $context
Position       : At line:1 char:1
                 + Get-AzureRmApiManagementProduct -Context $context
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 47
```

**Comment by solankisamir** [comment]
I checked that the [Product Contract mapping](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/ApiManagement/Commands.ApiManagement.ServiceManagement/ApiManagementClient.cs#L125) is present

**Comment by tom-canova** [comment]
I've been able to use the api mgmt commands in a cloud shell, so closing.
