### ISSUE TITLE
Set-AzureRmDiagnosticSetting failing for data factory in West Europe

### ISSUE THREAD

**Issue by vinaydam** [Azure/azure-powershell#4991]
### Cmdlet(s)
Set-AzureRmDiagnosticSetting

### PowerShell Version
5.1.16299.19

### Module Version
4.0.0

### OS Version
10.0.16299.19

### Description
When I try to set the diagnostics for a data factory in West Europe with a corresponding storage account in West Europe, I keep getting an error saying "Set-AzureRmDiagnosticSetting : Exception type: CloudException, Message: Null/Empty, Code: InternalServerError, Status code:InternalServerError, Reason 
phrase: Internal Server Error". But, when I try to execute the same command for a data factory in East US, it works fine.

### Debug Output
Set-AzureRmDiagnosticSetting -ResourceId "/subscriptions/8d6baaa6-0ec4-49fd-acfa-55c3194e32dd/resourceGroups/datafactory/providers/Microsoft.DataFactory/factories/datfac" -Enabled $true -Timegrains "PT1M" -StorageAccountId "/subscriptions/8d6baaa6-0ec4-49fd-acfa-55c3194e32dd/resourceGroups/datafactory/providers/Microsoft.Storage/storageAccounts/datfac" -Categories "ActivityRuns" -Debug
DEBUG: 2:25:46 PM - SetAzureRmDiagnosticSettingCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 2:25:48 PM - using account id 'vinaydami@outlook.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'vinaydami@outlook.com', environment: 'AzureCloud', tenant: '5ed1d584-3cdd-4f8b-87b5-515a23
e7e65e'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 0a8355f1-a764-4503-aeb9-78eae881cd04 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/5ed1d584-3cdd-4f8b-87b5-515a23e7e65e/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (6 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 11/15/2017 08:55:48: 0a8355f1-a764-4503-aeb9-78eae881cd04 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 0a8355f1-a764-4503-aeb9-78eae881cd04 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 11/15/2017 08:55:48: 0a8355f1-a764-4503-aeb9-78eae881cd04 - TokenCache: 57.21151438 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 0a8355f1-a764-4503-aeb9-78eae881cd04 - TokenCache: A matching item (access token or refresh token or both) was found in the c
ache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 0a8355f1-a764-4503-aeb9-78eae881cd04 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token 
was retuned:
	Access Token Hash: rocPxtPtwxzDjF9V5v7BwnZV2jg6kbjjwH6aQu4sc+o=
	Refresh Token Hash: Ppl19v4Mb0NMlf1brAYCDyozle9nEXtS4QJ9uPH5Mfw=
	Expiration Time: 11/15/2017 09:53:01 +00:00
	User Hash: 4uMjdux6PlbHohqQSPfTCHKRPTSuusBeoflGpyYQ1ps=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48:  - TokenCache: Serializing token cache with 6 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 32b37e12-ee8c-4e1b-86c6-dafc266930c9 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/5ed1d584-3cdd-4f8b-87b5-515a23e7e65e/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (6 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 11/15/2017 08:55:48: 32b37e12-ee8c-4e1b-86c6-dafc266930c9 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 32b37e12-ee8c-4e1b-86c6-dafc266930c9 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 11/15/2017 08:55:48: 32b37e12-ee8c-4e1b-86c6-dafc266930c9 - TokenCache: 57.2112224033333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 32b37e12-ee8c-4e1b-86c6-dafc266930c9 - TokenCache: A matching item (access token or refresh token or both) was found in the c
ache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48: 32b37e12-ee8c-4e1b-86c6-dafc266930c9 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token 
was retuned:
	Access Token Hash: rocPxtPtwxzDjF9V5v7BwnZV2jg6kbjjwH6aQu4sc+o=
	Refresh Token Hash: Ppl19v4Mb0NMlf1brAYCDyozle9nEXtS4QJ9uPH5Mfw=
	Expiration Time: 11/15/2017 09:53:01 +00:00
	User Hash: 4uMjdux6PlbHohqQSPfTCHKRPTSuusBeoflGpyYQ1ps=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:55:48:  - TokenCache: Serializing token cache with 6 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/%2Fsubscriptions%2F8d6baaa6-0ec4-49fd-acfa-55c3194e32dd%2FresourceGroups%2Fdatafactory%2Fproviders%2FMicrosoft.DataFactory%2
Ffactories%2Fdatfac/providers/microsoft.insights/diagnosticSettings/service?api-version=2016-09-01

Headers:
x-ms-client-request-id        : d06d506c-4c53-47f4-9995-2acfb0e14a0e
accept-language               : en-US

Body:

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : b9de57b6-67e2-4ffe-ba77-2ad839f76fd0
x-ms-ratelimit-remaining-subscription-reads: 14981
x-ms-correlation-request-id   : 451d63e3-a9eb-4305-91a4-c86cb9f77685
x-ms-routing-request-id       : SOUTHINDIA:20171115T085549Z:451d63e3-a9eb-4305-91a4-c86cb9f77685
Cache-Control                 : no-cache
Date                          : Wed, 15 Nov 2017 08:55:49 GMT
Server                        : Microsoft-IIS/8.5

Body:
{
  "id": "/subscriptions/8d6baaa6-0ec4-49fd-acfa-55c3194e32dd/resourcegroups/datafactory/providers/microsoft.datafactory/factories/datfac/providers/micros
oft.insights/diagnosticSettings/service",
  "type": null,
  "name": "service",
  "location": null,
  "kind": null,
  "tags": null,
  "properties": {
    "storageAccountId": null,
    "serviceBusRuleId": null,
    "workspaceId": null,
    "eventHubAuthorizationRuleId": null,
    "eventHubName": null,
    "metrics": [
      {
        "timeGrain": "PT1M",
        "category": "AllMetrics",
        "enabled": false,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      }
    ],
    "logs": [
      {
        "category": "ActivityRuns",
        "enabled": false,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      },
      {
        "category": "PipelineRuns",
        "enabled": false,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      },
      {
        "category": "TriggerRuns",
        "enabled": false,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      }
    ]
  },
  "identity": null
}

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:56:19: 50219ce0-04a3-42bc-987f-071ce1fb61f3 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/5ed1d584-3cdd-4f8b-87b5-515a23e7e65e/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (6 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 11/15/2017 08:56:19: 50219ce0-04a3-42bc-987f-071ce1fb61f3 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:56:19: 50219ce0-04a3-42bc-987f-071ce1fb61f3 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 11/15/2017 08:56:19: 50219ce0-04a3-42bc-987f-071ce1fb61f3 - TokenCache: 56.6965475733333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:56:19: 50219ce0-04a3-42bc-987f-071ce1fb61f3 - TokenCache: A matching item (access token or refresh token or both) was found in the c
ache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:56:19: 50219ce0-04a3-42bc-987f-071ce1fb61f3 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token 
was retuned:
	Access Token Hash: rocPxtPtwxzDjF9V5v7BwnZV2jg6kbjjwH6aQu4sc+o=
	Refresh Token Hash: Ppl19v4Mb0NMlf1brAYCDyozle9nEXtS4QJ9uPH5Mfw=
	Expiration Time: 11/15/2017 09:53:01 +00:00
	User Hash: 4uMjdux6PlbHohqQSPfTCHKRPTSuusBeoflGpyYQ1ps=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 11/15/2017 08:56:19:  - TokenCache: Serializing token cache with 6 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/%2Fsubscriptions%2F8d6baaa6-0ec4-49fd-acfa-55c3194e32dd%2FresourceGroups%2Fdatafactory%2Fproviders%2FMicrosoft.DataFactory%2
Ffactories%2Fdatfac/providers/microsoft.insights/diagnosticSettings/service?api-version=2016-09-01

Headers:
x-ms-client-request-id        : 778321c4-9a20-4b37-9646-b6b3dbce65a9
accept-language               : en-US

Body:
{
  "properties": {
    "storageAccountId": "/subscriptions/8d6baaa6-0ec4-49fd-acfa-55c3194e32dd/resourceGroups/datafactory/providers/Microsoft.Storage/storageAccounts/datfa
c",
    "metrics": [
      {
        "timeGrain": "PT1M",
        "enabled": true,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      }
    ],
    "logs": [
      {
        "category": "ActivityRuns",
        "enabled": true,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      },
      {
        "category": "PipelineRuns",
        "enabled": false,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      },
      {
        "category": "TriggerRuns",
        "enabled": false,
        "retentionPolicy": {
          "enabled": false,
          "days": 0
        }
      }
    ]
  },
  "location": ""
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
InternalServerError

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 00000000-0000-0000-0000-000000000000
x-ms-failure-cause            : service
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : bcb1e3fc-0583-4583-9b2f-95c909b3d4c3
x-ms-routing-request-id       : SOUTHINDIA:20171115T085647Z:bcb1e3fc-0583-4583-9b2f-95c909b3d4c3
Connection                    : close
Cache-Control                 : no-cache
Date                          : Wed, 15 Nov 2017 08:56:47 GMT
Server                        : Microsoft-IIS/8.5

Body:
{
  "Code": "InternalServerError",
  "Message": ""
}

Set-AzureRmDiagnosticSetting : Exception type: CloudException, Message: Null/Empty, Code: InternalServerError, Status code:InternalServerError, Reason 
phrase: Internal Server Error
At line:1 char:1
+ Set-AzureRmDiagnosticSetting -ResourceId "/subscriptions/8d6baaa6-0ec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmDiagnosticSetting], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Insights.Diagnostics.SetAzureRmDiagnosticSettingCommand
 
DEBUG: AzureQoSEvent: CommandName - Set-AzureRmDiagnosticSetting; IsSuccess - False; Duration - 00:01:13.0986780; Exception - System.Management.Automatio
n.PSInvalidOperationException: Exception type: CloudException, Message: Null/Empty, Code: InternalServerError, Status code:InternalServerError, Reason ph
rase: Internal Server Error ---> Microsoft.Rest.Azure.CloudException
   at Microsoft.Azure.Management.Monitor.Management.ServiceDiagnosticSettingsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Monitor.Management.ServiceDiagnosticSettingsOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Insights.MonitorCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 2:27:00 PM - SetAzureRmDiagnosticSettingCommand end processing.
DEBUG: 2:27:00 PM - SetAzureRmDiagnosticSettingCommand end processing.

### Script/Steps for Reproduction
1) Create a storage account in West Europe
2) Create a data factory in West Europe
3) Execute the below command to set the diagnostic settings for the data factory:
Set-AzureRmDiagnosticSetting -ResourceId "/subscriptions/8d6baaa6-0ec4-49fd-acfa-55c3194e32dd/resourceGroups/datafactory/providers/Microsoft.DataFactory/factories/datfac" -Enabled $true -Timegrains "PT1M" -StorageAccountId "/subscriptions/8d6baaa6-0ec4-49fd-acfa-55c3194e32dd/resourceGroups/datafactory/providers/Microsoft.Storage/storageAccounts/datfac" -Categories "ActivityRuns"

**Comment by cormacpayne** [comment]
@gucalder Hey Guillermo, would you mind taking a look at this issue?

**Comment by vinaydam** [comment]
@cormacpayne @gucalder Just wanted to check if you have any update on this.

**Comment by cormacpayne** [comment]
Closing due to lack of activity. Please feel free to re-open this issue if you are still seeing the problem.
