### ISSUE TITLE
Fix intermittently failing Batch test

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#5006]
### Description
The CI build has been failing due to different Batch tests.
- [ ] Change the test runner to display more information about the failing test

Parent issue: https://github.com/Azure/azure-powershell/issues/3029

**Comment by maddieclayton** [comment]
batch test moved to on demand in this PR: https://github.com/Azure/azure-powershell/pull/5634

**Comment by maddieclayton** [comment]
Fixed!

**Comment by maddieclayton** [comment]
@matthchr Looks like the issue might have come up again: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell/5125/. Can you take a look?

**Comment by matthchr** [comment]
hey @maddieclayton - I looked but the only error I see is this:
```
[c:\workspace\powershell\build.proj]
        System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation was canceled.
        Stack Trace:
             at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
             at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
             at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
             at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
             at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
             at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
          src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(638,0): at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts)
          src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchController.cs(112,0): at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchController.RunPsTestWorkflow(Func`1 scriptBuilder, Action initialize, Action cleanup, String callingClassType, String mockName)
          src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\ComputeNodeUserTests.cs(37,0): at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeUserTests.TestComputeNodeUserEndToEnd()
```

I am not sure how I am supposed to diagnose the root cause of the error from the above?
Do you have any suggestions...? I already did your previous suggestion of making all our sleeps in record mode have a very long timeout (unless I missed one somewhere...)

**Comment by maddieclayton** [comment]
@matthchr Unfortunately we don't have any more specifics on the error in our logs.  Because it's a cancelled error again, I'm guessing it's still a timeout - would you mind doing a quick scan to ensure you didn't miss any sleeps? I'll also take a look later when I get a free moment.

**Comment by maddieclayton** [comment]
Another failed test here: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/5413/
```
210.5292203s ✘  Microsoft.Azure.Commands.Batch.Test.ScenarioTests.CertificateTests.TestCancelCertificateDelete
System.ArgumentNullException : Value cannot be null.\r\nParameter name: thumbprint
   at Microsoft.Azure.Commands.Batch.Models.CertificateOperationParameters..ctor(BatchAccountContext context, String thumbprintAlgorithm, String thumbprint, IEnumerable`1 additionalBehaviors) in c:\workspace\powershell\src\ResourceManager\AzureBatch\Commands.Batch\Models\CertificateOperationParameters.cs:line 36
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ScenarioTestHelpers.DeleteTestCertificate(BatchController controller, BatchAccountContext context, String thumbprintAlgorithm, String thumbprint) in c:\workspace\powershell\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\ScenarioTestHelpers.cs:line 137
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.CertificateTests.<>c__DisplayClass2_0.<TestCancelCertificateDelete>b__2() in c:\workspace\powershell\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\CertificateTests.cs:line 64
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchController.RunPsTestWorkflow(Func`1 scriptBuilder, Action initialize, Action cleanup, String callingClassType, String mockName) in c:\workspace\powershell\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchController.cs:line 118
   at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.CertificateTests.TestCancelCertificateDelete() in c:\workspace\powershell\src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\CertificateTests.cs:line 45
```

Moving batch tests back to on-demand for now.

**Comment by maddieclayton** [comment]
Closing as we will be serializing the tests, and should no longer run into this issue.  I'll move the batch tests over to CI once the PR to serialized tests is merged.
