### ISSUE TITLE
Build Failed: Could not load file or assembly 'Microsoft.Azure.Commands.AnalysisServices.Dataplane

### ISSUE THREAD

**Issue by joannakleong** [Azure/azure-powershell#5013]
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`

### Description
I'm trying to build the azure-powershell repo and getting an exception that a dll is not found

### Debug Output
INFO - Processing complete for analyzer: Signature Verifier
INFO - Executing analyzer: Breaking Change Analyzer
WARN - Using exceptions file D:\azure-powershell\src\Package\Exceptions\BreakingChangeIssues.csv
ERROR - System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Commands.AnalysisServices.Dataplane, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Azure.Commands.AnalysisServices.Dataplane, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)

   at StaticAnalysis.BreakingChangeAnalyzer.CmdletBreakingChangeLoader.GetModuleMetadata(String assemblyPath)
   at StaticAnalysis.BreakingChangeAnalyzer.BreakingChangeAnalyzer.Analyze(IEnumerable`1 cmdletProbingDirs, Func`2 directoryFilter, Func`2 cmdletFilter) in D:\azure-powershell\tools\StaticAnalysis\BreakingChangeAnalyzer\BreakingChangeAnalyzer.cs:line 126
   at StaticAnalysis.BreakingChangeAnalyzer.BreakingChangeAnalyzer.Analyze(IEnumerable`1 cmdletProbingDirs) in D:\azure-powershell\tools\StaticAnalysis\BreakingChangeAnalyzer\BreakingChangeAnalyzer.cs:line 50
   at StaticAnalysis.Program.Main(String[] args) in D:\azure-powershell\tools\StaticAnalysis\Program.cs:line 98

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Commands.AnalysisServices.Dataplane, Version=0.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.UnitySerializationHolder.GetRealObject(StreamingContext context)

   at StaticAnalysis.Program.Main(String[] args) in D:\azure-powershell\tools\StaticAnalysis\Program.cs:line 108

### Script/Steps for Reproduction
1. Open VS developer command prompt
2. Navigate to the tools folder
3. Run %comspec% /k "PSRepoStart.cmd & powershell" 
4. Run ipmo Build-Tasks.psm1
5. Run Start-Build

**Comment by maddieclayton** [comment]
Resolved
