### ISSUE TITLE
Get-AzureRmRoleAssignment throws unhandled exception on Service Provider account

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-powershell#5192]
### Cmdlet(s)
Get-AzureRmRoleAssignment
### PowerShell Version
PSVersion                      5.1.16299.98
### Module Version
5.1.1      AzureRM.Resources
### OS Version
BuildVersion                   10.0.16299.98
### Description
While logged into a Service Provider account, Get-AzureRmRoleAssignment (no params) throws an unhandled Microsoft.Rest.Azure.CloudException.
### Debug Output
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Forbidden

Headers:
Pragma                        : no-cache
ocp-aad-diagnostics-server-name: OzArKxpPSemSWWoFLWW7BNCbp+jQjreuu63QDSj69JM=
request-id                    : 2942ed39-8c4c-4aff-8a0e-a0da9c3dbfdc
client-request-id             : b3453f77-27ea-44a0-b8a7-c300b13dc04d
x-ms-dirapi-data-contract-version: 1.6
ocp-aad-session-key           : JBc28mv92xPoNCqpvat40jTYbFLzcucNdsy6NrboPoadL9M-jJKeGqIO1b-SWNlG_FKvEVmDy5F1ZQaS90v7RU8105cmbWNyK3s1p9zkenmD46Boy39OVgEZYCK8avAG.qzQSHzbrH8FZFF7Ce2De25BXwObq2YYlS9GhMc8GyEs
X-Content-Type-Options        : nosniff
DataServiceVersion            : 3.0;
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Access-Control-Allow-Origin   : *
Duration                      : 2474974
Cache-Control                 : no-cache
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET,ASP.NET
Date                          : Wed, 27 Dec 2017 18:24:27 GMT

Body:
{
  "odata.error": {
    "code": "Authorization_RequestDenied",
    "message": {
      "lang": "en",
      "value": "Insufficient privileges to complete the operation."
    }
  }
}

Get-AzureRmRoleAssignment : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
At line:1 char:1
+ Get-AzureRmRoleAssignment
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmRoleAssignment; IsSuccess - False; Duration - 00:00:01.0789912; Exception - Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure.CloudException' was
thrown.
   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperations.<GetObjectsByObjectIdsWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.<GetObjectsByObjectIdsAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.GetObjectsByObjectIds(IObjectsOperations operations, GetObjectsParameters parameters)
   at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryClient.GetObjectsByObjectId(List`1 objectIds)
   at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClientExtensions.ToPSRoleAssignments(IEnumerable`1 assignments, List`1 roleDefinitions, AuthorizationClient policyClient, ActiveDirectoryClient
activeDirectoryClient, Boolean excludeAssignmentsForDeletedPrincipals)
   at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.FilterRoleAssignments(FilterRoleAssignmentsOptions options, String currentSubscription)
   at Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:24:26 AM - GetAzureRoleAssignmentCommand end processing.
DEBUG: 10:24:26 AM - GetAzureRoleAssignmentCommand end processing.
### Script/Steps for Reproduction
Log into a Service Provider account. Then, run Get-AzureRmRoleAssignment. It throws an unhandled exception, Microsoft.Rest.Azure.CloudException.

**Comment by markcowl** [comment]
@MiYanni What is returned by ```Resolve-AzureRmError``` in this case?  Insufficient privileges is expected, because you also need to have access to graph to list the graph entities referenced in role assignments, but we should print a more helpful error that points at how to resolve the problem (giving your application sufficient privileges).

**Comment by MiYanni** [comment]
@markcowl 
PS C:\WINDOWS\system32> Resolve-AzureRmError


   HistoryId: 4


RequestId      :
Message        : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
ServerMessage  : :  (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {Forbidden}
RequestMessage : {POST
                 https://graph.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47/getObjectsByObjectIds?api-version=1.6}
InvocationInfo : {Get-AzureRmRoleAssignment}
Line           : Get-AzureRmRoleAssignment
Position       : At line:1 char:1
                 + Get-AzureRmRoleAssignment
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperations.<GetObjectsByObjectIdsWithHttpMessagesAs
                 ync>d__6.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.<GetObjectsByObjectIdsAsync>d_
                 _3.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Graph.RBAC.Version1_6.ObjectsOperationsExtensions.GetObjectsByObjectIds(IObjects
                 Operations operations, GetObjectsParameters parameters)
                    at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryClient.GetObjectsByObjectId
                 (List`1 objectIds)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClientExtensions.ToPSRoleAs
                 signments(IEnumerable`1 assignments, List`1 roleDefinitions, AuthorizationClient policyClient,
                 ActiveDirectoryClient activeDirectoryClient, Boolean excludeAssignmentsForDeletedPrincipals)
                    at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.FilterRoleAssignment
                 s(FilterRoleAssignmentsOptions options, String currentSubscription)
                    at Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 4

**Comment by markcowl** [comment]
@darshanhs90 This occurs frequently enough that we need to catch this error in the call to graph, and either not fill in the additional information in the output and print a warning letting them know they need  to add privileges to graph, or we could print a more informative error message telling them how to fix this issue.

**Comment by darshanhs90** [comment]
Fixed

**Comment by adhamod** [comment]
What privileges to graph are required? I'm using a Run As Account created by default with my Automation account. However, I also went to the permissions under App Registration and added Microsoft Graph and Windows Azure Active Directory.

 I attached output from Resolve-AzureRMError. 
[RBACCloudExceptionError.txt](https://github.com/Azure/azure-powershell/files/1869928/RBACCloudExceptionError.txt)
