### ISSUE TITLE
New-AzureRMAppServicePlan doesn't support isolated SKU with ASEv2

### ISSUE THREAD

**Issue by ivanl8** [Azure/azure-powershell#5204]
### Cmdlet(s)
New-AzureRMAppServicePlan

### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
PSVersion                      5.1.16299.98     

### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.16299.98 

### Description
After creating a new ASEv2, I attempt to try creating new app service plan. Works in portal but when in powershell, using the above cmdlet fails as it doesn't list the new isolated SKUs.

### Debug Output
Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue

PS C:\Users\ile> $DebugPreference=”Continue” 
New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeast -AseName ilease1 -AseResourceGroupName Demo -NumberofWorkers 1 -WorkerSize Small -ResourceGroupName Demo 

DEBUG: 11:27:12 AM - NewAzureAppServicePlanCmdlet begin processing with ParameterSet 'S1'.
DEBUG: 11:27:12 AM - using account id 'ile@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'ile@microsoft.com', environment: 'AzureCloud', tenant: '63a09168-9b34-4d60-aa46-31269763fbd4'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 3cb64edb-f20b-4a80-9523-3a7c7f9ce230 - AcquireTokenHandlerBase: === Token Acquisition started:
       Authority: https://login.microsoftonline.com/63a09168-9b34-4d60-aa46-31269763fbd4/
       Resource: https://management.core.windows.net/
       ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
       CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (6 items)
       Authentication Target: User
       

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/30/2017 00:27:12: 3cb64edb-f20b-4a80-9523-3a7c7f9ce230 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 3cb64edb-f20b-4a80-9523-3a7c7f9ce230 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/30/2017 00:27:12: 3cb64edb-f20b-4a80-9523-3a7c7f9ce230 - TokenCache: 56.1416566833333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 3cb64edb-f20b-4a80-9523-3a7c7f9ce230 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 3cb64edb-f20b-4a80-9523-3a7c7f9ce230 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retune
d:
       Access Token Hash: 0GqyK1dFelsBKE0NnGZ0lFIyDp6bMXOPewoeJ4gk5EA=
       Refresh Token Hash: SaQUCn/oUW0Nqp1q/ewoKjDlUWgtBeCaZRCXxC0yFRI=
       Expiration Time: 12/30/2017 01:23:21 +00:00
       User Hash: UzGKoRZEaTVUwMMwGdkycyeU2z2BdYcMFNl3FxDZtN4=
       

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12:  - TokenCache: Serializing token cache with 6 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 0c6d92d0-fdbb-4d5f-a4c9-1f2a01f10f95 - AcquireTokenHandlerBase: === Token Acquisition started:
       Authority: https://login.microsoftonline.com/63a09168-9b34-4d60-aa46-31269763fbd4/
       Resource: https://management.core.windows.net/
       ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
       CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (6 items)
       Authentication Target: User
       

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/30/2017 00:27:12: 0c6d92d0-fdbb-4d5f-a4c9-1f2a01f10f95 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 0c6d92d0-fdbb-4d5f-a4c9-1f2a01f10f95 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 12/30/2017 00:27:12: 0c6d92d0-fdbb-4d5f-a4c9-1f2a01f10f95 - TokenCache: 56.1413651283333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 0c6d92d0-fdbb-4d5f-a4c9-1f2a01f10f95 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12: 0c6d92d0-fdbb-4d5f-a4c9-1f2a01f10f95 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retune
d:
       Access Token Hash: 0GqyK1dFelsBKE0NnGZ0lFIyDp6bMXOPewoeJ4gk5EA=
       Refresh Token Hash: SaQUCn/oUW0Nqp1q/ewoKjDlUWgtBeCaZRCXxC0yFRI=
       Expiration Time: 12/30/2017 01:23:21 +00:00
       User Hash: UzGKoRZEaTVUwMMwGdkycyeU2z2BdYcMFNl3FxDZtN4=
       

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 12/30/2017 00:27:12:  - TokenCache: Serializing token cache with 6 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/78843dcf-334c-440e-abcc-0a7dbafbf688/resourceGroups/Demo/providers/Microsoft.Web/serverfarms/ileaseappplan1?api-version=
2015-08-01

Headers:
x-ms-client-request-id        : fef4687c-bc1d-48b6-bca6-b38151fd0372
accept-language               : en-US

Body:
{
  "sku": {
    "name": "F1",
    "tier": "Free",
    "capacity": 1
  },
  "location": "australiaeast",
  "properties": {
    "name": "ileaseappplan1",
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/78843dcf-334c-440e-abcc-0a7dbafbf688/resourcegroups/Demo/providers/Microsoft.Web/hostingEnvironments/ilease1",
      "name": "ilease1",
      "type": "hostingEnvironments"
    },
    "perSiteScaling": false
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 8871c86a-f59b-440c-b883-c932c303ee2d
x-ms-correlation-request-id   : 8871c86a-f59b-440c-b883-c932c303ee2d
x-ms-routing-request-id       : AUSTRALIAEAST:20171230T002716Z:8871c86a-f59b-440c-b883-c932c303ee2d
Cache-Control                 : no-cache
Date                          : Sat, 30 Dec 2017 00:27:15 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "Code": "BadRequest",
  "Message": "This version of AppServiceEnvironments only supports Isolated Sku.",
  "Target": null,
  "Details": [
    {
      "Message": "This version of AppServiceEnvironments only supports Isolated Sku."
    },
    {
      "Code": "BadRequest"
    },
   {
      "ErrorEntity": {
        "ExtendedCode": "59913",
        "MessageTemplate": "This version of AppServiceEnvironments only supports {0} Sku.",
        "Parameters": [
          "Isolated"
        ],
        "Code": "BadRequest",
        "Message": "This version of AppServiceEnvironments only supports Isolated Sku."
      }
    }
  ],
  "Innererror": null
}

New-AzureRmAppServicePlan : This version of AppServiceEnvironments only supports Isolated Sku.
At line:2 char:1
+ New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeas ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmAppServicePlan], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet

DEBUG: AzureQoSEvent: CommandName - New-AzureRmAppServicePlan; IsSuccess - False; Duration - 00:00:04.1827394; Exception - Microsoft.Rest.Azure.CloudException: Thi
s version of AppServiceEnvironments only supports Isolated Sku.
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<BeginCreateOrUpdateServerFarmWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<CreateOrUpdateServerFarmWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.<CreateOrUpdateServerFarmAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.CreateOrUpdateServerFarm(IServerFarmsOperations operations, String resourceGroupName, Str
ing name, ServerFarmWithRichSku serverFarmEnvelope, Nullable`1 allowPendingState)
   at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.CreateAppServicePlan(String resourceGroupName, String appServicePlanName, String location, String a
dminSiteName, SkuDescription sku, String aseName, String aseResourceGroupName, Nullable`1 perSiteScaling)
   at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:27:17 AM - NewAzureAppServicePlanCmdlet end processing.
DEBUG: 11:27:17 AM - NewAzureAppServicePlanCmdlet end processing.

PS C:\Users\ile> Resolve-AzureRmError 
DEBUG: 11:27:44 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 11:27:44 AM - using account id 'ile@microsoft.com'...

   HistoryId: 5

RequestId      : 8871c86a-f59b-440c-b883-c932c303ee2d
Message        : This version of AppServiceEnvironments only supports Isolated Sku.
ServerMessage  : BadRequest: This version of AppServiceEnvironments only supports Isolated Sku. 
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {PUT https://management.azure.com/subscriptions/78843dcf-334c-440e-abcc-0a7dbafbf688/resourceGroups/Demo/providers/Microsoft.Web/serverfarms/ilea
                 seappplan1?api-version=2015-08-01}
InvocationInfo : {New-AzureRmAppServicePlan}
Line           : New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeast -AseName ilease1 -AseResourceGroupName Demo -NumberofWorkers 1 
                 -WorkerSize Small -ResourceGroupName Demo 
                 
Position       : At line:2 char:1
                 + New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeas ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<BeginCreateOrUpdateServerFarmWithHttpMessagesAsync>d__8.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<CreateOrUpdateServerFarmWithHttpMessagesAsync>d__7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.<CreateOrUpdateServerFarmAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.CreateOrUpdateServerFarm(IServerFarmsOperations operations, String 
                 resourceGroupName, String name, ServerFarmWithRichSku serverFarmEnvelope, Nullable`1 allowPendingState)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.CreateAppServicePlan(String resourceGroupName, String appServicePlanName, String 
                 location, String adminSiteName, SkuDescription sku, String aseName, String aseResourceGroupName, Nullable`1 perSiteScaling)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 5

   HistoryId: 4

RequestId      : 4a349542-7db7-431f-a8c9-f1471159a815
Message        : This version of AppServiceEnvironments only supports Isolated Sku.
ServerMessage  : BadRequest: This version of AppServiceEnvironments only supports Isolated Sku. 
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {PUT https://management.azure.com/subscriptions/78843dcf-334c-440e-abcc-0a7dbafbf688/resourceGroups/Demo/providers/Microsoft.Web/serverfarms/ilea
                 seappplan1?api-version=2015-08-01}
InvocationInfo : {New-AzureRmAppServicePlan}
Line           : New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeast -AseName ilease1 -AseResourceGroupName Demo -NumberofWorkers 1 
                 -WorkerSize Small -ResourceGroupName Demo 
                 
Position       : At line:2 char:1
                 + New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeas ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<BeginCreateOrUpdateServerFarmWithHttpMessagesAsync>d__8.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<CreateOrUpdateServerFarmWithHttpMessagesAsync>d__7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.<CreateOrUpdateServerFarmAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.CreateOrUpdateServerFarm(IServerFarmsOperations operations, String 
                 resourceGroupName, String name, ServerFarmWithRichSku serverFarmEnvelope, Nullable`1 allowPendingState)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.CreateAppServicePlan(String resourceGroupName, String appServicePlanName, String 
                 location, String adminSiteName, SkuDescription sku, String aseName, String aseResourceGroupName, Nullable`1 perSiteScaling)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 4

   HistoryId: 3

RequestId      : acaa4d1a-0a61-46e9-a66d-bfa94377ff60
Message        : This version of AppServiceEnvironments only supports Isolated Sku.
ServerMessage  : BadRequest: This version of AppServiceEnvironments only supports Isolated Sku. 
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {PUT https://management.azure.com/subscriptions/78843dcf-334c-440e-abcc-0a7dbafbf688/resourceGroups/Demo/providers/Microsoft.Web/serverfarms/ilea
                 seappplan1?api-version=2015-08-01}
InvocationInfo : {New-AzureRmAppServicePlan}
Line           : New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeast -AseName ilease1 -AseResourceGroupName Demo -NumberofWorkers 1 
                 -WorkerSize Small -ResourceGroupName Demo
Position       : At line:1 char:1
                 + New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeas ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<BeginCreateOrUpdateServerFarmWithHttpMessagesAsync>d__8.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<CreateOrUpdateServerFarmWithHttpMessagesAsync>d__7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.<CreateOrUpdateServerFarmAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.CreateOrUpdateServerFarm(IServerFarmsOperations operations, String 
                 resourceGroupName, String name, ServerFarmWithRichSku serverFarmEnvelope, Nullable`1 allowPendingState)
                    at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.CreateAppServicePlan(String resourceGroupName, String appServicePlanName, String 
                 location, String adminSiteName, SkuDescription sku, String aseName, String aseResourceGroupName, Nullable`1 perSiteScaling)
                    at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 3

DEBUG: AzureQoSEvent: CommandName - Resolve-AzureRmError; IsSuccess - True; Duration - 00:00:00.1759886; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 11:27:45 AM - ResolveError end processing.
DEBUG: 11:27:45 AM - ResolveError end processing.

### Script/Steps for Reproduction
#Login to Azure
Login-AzureRmAccount 

Select-AzureRmSubscription -SubscriptionName "Int1"

$DebugPreference=”Continue” 
New-AzureRmAppServicePlan -Name ileaseappplan1 -Location australiaeast -AseName ilease1 -AseResourceGroupName Demo -NumberofWorkers 1 -WorkerSize Small -ResourceGroupName Demo 
Resolve-AzureRmError

**Comment by bgoldman69** [comment]
We are also seeing this issue currently.

**Comment by bgoldman69** [comment]
we are unable to use the powershell command to add app service plans to an ASE 2.0 now.

**Comment by panchagnula** [comment]
@bgoldman69 Isloated SKU support hasn't been enabled on the current CLI version. We will have a fix for this soon.

**Comment by bgoldman69** [comment]
@panchagnula does that mean that we will be unable to use the Powershell Module to create app service plans in an ASE 2.0 until you fix it? 

If so that really puts us in a terrible spot as we have been pressured to move to ASE 2.0 from ASE 1.0 and all of our automation code revolves around this stuff right now...

**Comment by panchagnula** [comment]
currently there is no work around for this until the support is turned on for powershell we are working on getting the fix out soon - until then please use Portal as the workaround - I understand this doesn't fix the automation part & so will give you an update on it soon.

**Comment by panchagnula** [comment]
This should now be available on the websites-preview module see  https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites
