### ISSUE TITLE
Set-AzureRmAppServicePlan throws CloudException on ASE v2

### ISSUE THREAD

**Issue by vermegi** [Azure/azure-powershell#5222]
### Cmdlet(s)

Set-AzureRmAppServicePlan

### PowerShell Version

5.1.16299.98

### OS Version

10.0.16299.98

### Description

After creating an ASE v2 with a Small App Service Plan, I try to scale up the App Service Plan to Medium, this fails with a CloudException. However the App Service Plan comes in the 'Scaling' state and after about 20 minutes will be scaled to the correct size.

### Debug Output

```
C:\Users\givermei> Set-AzureRmAppServicePlan -ResourceGroupName "asetryout" -Name "gitteasp2" -WorkerSize Medium
Set-AzureRmAppServicePlan : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
At line:1 char:1
+ Set-AzureRmAppServicePlan -ResourceGroupName "asetryout" -Name "gitte ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmAppServicePlan], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.SetAzureAppServicePlanCmdlet

C:\Users\givermei> Set-AzureRmAppServicePlan -ResourceGroupName "asetryout" -Name "gitteasp2" -WorkerSize Medium -Debug
DEBUG: 15:38:05 - SetAzureAppServicePlanCmdlet begin processing with ParameterSet 'S1'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 15:38:06 - using account id 'givermei@Microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'givermei@Microsoft.com', environment: 'AzureCloud', tenant:
'72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:06: 123a7acc-0b6b-4ee3-a6e2-889fdb321ff5 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (7 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/04/2018 14:38:06: 123a7acc-0b6b-4ee3-a6e2-889fdb321ff5 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:06: 123a7acc-0b6b-4ee3-a6e2-889fdb321ff5 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/04/2018 14:38:06: 123a7acc-0b6b-4ee3-a6e2-889fdb321ff5 - TokenCache: 58.7787955383333 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:06: 123a7acc-0b6b-4ee3-a6e2-889fdb321ff5 - TokenCache: A matching item (access token or refresh token or both) was found in the
cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:06: 123a7acc-0b6b-4ee3-a6e2-889fdb321ff5 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was
 retuned:
 Access Token Hash: Fvu9vce/K4v+hq9EO2Zh9+3OU2wd9eHn4YPFF0ohpRQ=
 Refresh Token Hash: 3YOEsACJDDH3lKUpCBWVlq0OirzRMOSuWag7DJaaK/w=
 Expiration Time: 01/04/2018 15:36:53 +00:00
 User Hash: 7X6D6fRtdNPxL937YpwX8yGZBRhFbGj1kv0QDh8NVOY=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:06:  - TokenCache: Serializing token cache with 7 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:07: 42d93ca7-bc06-42dd-8f6b-27c0a0d50be2 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (7 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/04/2018 14:38:07: 42d93ca7-bc06-42dd-8f6b-27c0a0d50be2 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:07: 42d93ca7-bc06-42dd-8f6b-27c0a0d50be2 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/04/2018 14:38:07: 42d93ca7-bc06-42dd-8f6b-27c0a0d50be2 - TokenCache: 58.7787622533333 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:07: 42d93ca7-bc06-42dd-8f6b-27c0a0d50be2 - TokenCache: A matching item (access token or refresh token or both) was found in the
cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:07: 42d93ca7-bc06-42dd-8f6b-27c0a0d50be2 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was
 retuned:
 Access Token Hash: Fvu9vce/K4v+hq9EO2Zh9+3OU2wd9eHn4YPFF0ohpRQ=
 Refresh Token Hash: 3YOEsACJDDH3lKUpCBWVlq0OirzRMOSuWag7DJaaK/w=
 Expiration Time: 01/04/2018 15:36:53 +00:00
 User Hash: 7X6D6fRtdNPxL937YpwX8yGZBRhFbGj1kv0QDh8NVOY=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:07:  - TokenCache: Serializing token cache with 7 items.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/serverfarms/gitteasp2?api-v
ersion=2015-08-01

Headers:
x-ms-client-request-id        : 453d125c-fe10-4821-9344-708183575cfc
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 4fdad2c5-834d-49d3-9a4b-1639cbe4be60
x-ms-ratelimit-remaining-subscription-reads: 14993
x-ms-correlation-request-id   : 71c40363-87fa-4733-b7fc-848b246acda8
x-ms-routing-request-id       : WESTEUROPE:20180104T143808Z:71c40363-87fa-4733-b7fc-848b246acda8
Cache-Control                 : no-cache
Date                          : Thu, 04 Jan 2018 14:38:08 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/serverfarms/gitteasp2",
  "name": "gitteasp2",
  "type": "Microsoft.Web/serverfarms",
  "kind": "app",
  "location": "West Europe",
  "properties": {
    "serverFarmId": 0,
    "name": "gitteasp2",
    "workerSize": 0,
    "workerSizeId": 0,
    "workerTierName": null,
    "numberOfWorkers": 1,
    "currentWorkerSize": 0,
    "currentWorkerSizeId": 0,
    "currentNumberOfWorkers": 1,
    "status": 1,
    "webSpace": "asetryout-asetryoutgitteappseWestEuropewebspace",
    "subscription": "49e23c68-dee0-4c5b-8c21-74acea0a2662",
    "adminSiteName": null,
    "hostingEnvironment": "asetryoutgitte",
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/hostingEnvironments/asetryoutgitte",
      "name": "asetryoutgitte",
      "type": "Microsoft.Web/hostingEnvironments"
    },
    "maximumNumberOfWorkers": 100,
    "planName": "VirtualDedicatedPlan",
    "adminRuntimeSiteName": null,
    "computeMode": 0,
    "siteMode": null,
    "geoRegion": "West Europe",
    "perSiteScaling": false,
    "numberOfSites": 1,
    "hostingEnvironmentId":
"/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/hostingEnvironments/asetryoutgitte",
    "isSpot": false,
    "spotExpirationTime": null,
    "tags": null,
    "kind": "app",
    "resourceGroup": "asetryout",
    "reserved": false,
    "mdmId": "waws-prod-am2-a423826a_3",
    "targetWorkerCount": 1,
    "targetWorkerSizeId": 1,
    "provisioningState": "InProgress"
  },
  "sku": {
    "name": "I1",
    "tier": "Isolated",
    "size": "I1",
    "family": "I",
    "capacity": 1
  }
}

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:08: b310505d-c6b1-4ac5-9821-049484a37d24 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (7 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/04/2018 14:38:08: b310505d-c6b1-4ac5-9821-049484a37d24 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:08: b310505d-c6b1-4ac5-9821-049484a37d24 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 01/04/2018 14:38:08: b310505d-c6b1-4ac5-9821-049484a37d24 - TokenCache: 58.7467164966667 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:08: b310505d-c6b1-4ac5-9821-049484a37d24 - TokenCache: A matching item (access token or refresh token or both) was found in the
cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:08: b310505d-c6b1-4ac5-9821-049484a37d24 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was
 retuned:
 Access Token Hash: Fvu9vce/K4v+hq9EO2Zh9+3OU2wd9eHn4YPFF0ohpRQ=
 Refresh Token Hash: 3YOEsACJDDH3lKUpCBWVlq0OirzRMOSuWag7DJaaK/w=
 Expiration Time: 01/04/2018 15:36:53 +00:00
 User Hash: 7X6D6fRtdNPxL937YpwX8yGZBRhFbGj1kv0QDh8NVOY=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 01/04/2018 14:38:08:  - TokenCache: Serializing token cache with 7 items.
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/serverfarms/gitteasp2?api-v
ersion=2015-08-01

Headers:
x-ms-client-request-id        : 037d1967-dae7-4863-93ac-f28622499444
accept-language               : en-US

Body:
{
  "sku": {
    "name": "I2",
    "tier": "Isolated",
    "size": "I2",
    "family": "I",
    "capacity": 1
  },
  "location": "West Europe",
  "properties": {
    "name": "gitteasp2",
    "perSiteScaling": false
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Created

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 724f5784-a02a-4c70-a253-4f2b9edbce8f
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 58a85cbd-814b-4815-b510-e7d700d14278
x-ms-routing-request-id       : WESTEUROPE:20180104T143810Z:58a85cbd-814b-4815-b510-e7d700d14278
Cache-Control                 : no-cache
Date                          : Thu, 04 Jan 2018 14:38:10 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/serverfarms/gitteasp2",
  "name": "gitteasp2",
  "type": "Microsoft.Web/serverfarms",
  "kind": "app",
  "location": "West Europe",
  "properties": {
    "serverFarmId": 0,
    "name": "gitteasp2",
    "workerSize": 0,
    "workerSizeId": 0,
    "workerTierName": null,
    "numberOfWorkers": 1,
    "currentWorkerSize": 0,
    "currentWorkerSizeId": 0,
    "currentNumberOfWorkers": 1,
    "status": 1,
    "webSpace": "asetryout-asetryoutgitteappseWestEuropewebspace",
    "subscription": "49e23c68-dee0-4c5b-8c21-74acea0a2662",
    "adminSiteName": null,
    "hostingEnvironment": "asetryoutgitte",
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/hostingEnvironments/asetryoutgitte",
      "name": "asetryoutgitte",
      "type": "Microsoft.Web/hostingEnvironments"
    },
    "maximumNumberOfWorkers": 100,
    "planName": "VirtualDedicatedPlan",
    "adminRuntimeSiteName": null,
    "computeMode": 0,
    "siteMode": null,
    "geoRegion": "West Europe",
    "perSiteScaling": false,
    "numberOfSites": 1,
    "hostingEnvironmentId":
"/subscriptions/49e23c68-dee0-4c5b-8c21-74acea0a2662/resourceGroups/asetryout/providers/Microsoft.Web/hostingEnvironments/asetryoutgitte",
    "isSpot": false,
    "spotExpirationTime": null,
    "tags": null,
    "kind": "app",
    "resourceGroup": "asetryout",
    "reserved": false,
    "mdmId": "waws-prod-am2-a423826a_3",
    "targetWorkerCount": 1,
    "targetWorkerSizeId": 1,
    "provisioningState": "InProgress"
  },
  "sku": {
    "name": "I1",
    "tier": "Isolated",
    "size": "I1",
    "family": "I",
    "capacity": 1
  }
}


Confirm
Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
Set-AzureRmAppServicePlan : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
At line:1 char:1
+ Set-AzureRmAppServicePlan -ResourceGroupName "asetryout" -Name "gitte ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmAppServicePlan], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.SetAzureAppServicePlanCmdlet

DEBUG: AzureQoSEvent: CommandName - Set-AzureRmAppServicePlan; IsSuccess - False; Duration - 00:00:08.2468381; Exception -
Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<BeginCreateOrUpdateServerFarmWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperations.<CreateOrUpdateServerFarmWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.<CreateOrUpdateServerFarmAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.ServerFarmsOperationsExtensions.CreateOrUpdateServerFarm(IServerFarmsOperations operations, String
resourceGroupName, String name, ServerFarmWithRichSku serverFarmEnvelope, Nullable`1 allowPendingState)
   at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.CreateAppServicePlan(String resourceGroupName, String appServicePlanName, String location,
String adminSiteName, SkuDescription sku, String aseName, String aseResourceGroupName, Nullable`1 perSiteScaling) in
D:\workspace\powershell-sign\src\ResourceManager\Websites\Commands.Websites\Utilities\WebsitesClient.cs:line 331
   at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.SetAzureAppServicePlanCmdlet.ExecuteCmdlet() in
D:\workspace\powershell-sign\src\ResourceManager\Websites\Commands.Websites\Cmdlets\AppServicePlans\SetAzureAppServicePlan.cs:line 60
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord() in
D:\workspace\powershell-sign\src\Common\Commands.Common\AzurePSCmdlet.cs:line 639;
DEBUG: Finish sending metric.
DEBUG: 15:38:14 - SetAzureAppServicePlanCmdlet end processing.
DEBUG: 15:38:14 - SetAzureAppServicePlanCmdlet end processing.
```

### Script/Steps for Reproduction

In the Azure portal, create an app service environment v2. Create an app service plan with the I1 SKU (Small). 

In powershell: 

Login-AzureRmAccount
Select-AzureRmSubscription -SubscriptionName "subscriptionName of your subscription"
Set-AzureRmAppServicePlan -ResourceGroupName "name of the resource group of your ASE" -Name "name of your ASP" -WorkerSize Medium

**Comment by cormacpayne** [comment]
@Nking92 Hey Nick, would you mind taking a look at this issue? It looks like it's a bug in the SDK

**Comment by panchagnula** [comment]
@vermegi We have support for Isolated SKU with websites-preview module, DETAILS HERE https://github.com/Azure/azure-powershell/releases/tag/v5.0.0-preview-AzureRM.Websites

**Comment by madhukarkonda** [comment]
I am seeing this issue when I execute Set-AzureRmAppServicePlan through DevOps Azure PowerShell task.  

_[error]Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown._

**Comment by panchagnula** [comment]
@madhukarkonda please try this using the latest PowerShell commandlet directly (without the Azure Devops task) & let us know if this repros.

**Comment by madhukarkonda** [comment]
@panchagnula I did and it works fine.

**Comment by panchagnula** [comment]
@madhukarkonda seems like a DevOps issue then - i am not sure how to contact DevOps folks via this. Is it possible for you to create a Support ticket on Azure DevOps? Thanks!

**Comment by madhukarkonda** [comment]
> @madhukarkonda seems like a DevOps issue then - i am not sure how to contact DevOps folks via this. Is it possible for you to create a Support ticket on Azure DevOps? Thanks!

Sure, thank you.

**Comment by madhukarkonda** [comment]
@panchagnula I found that DevOps hosted agents are using older 6.7.0 AzureRM modules.  I believe it is causing the issue.  I updated my pipeline to use new Az module and it works fine.
