### ISSUE TITLE
New-AzureRmResourceGroupDeployment does not have useful error messages when parameters cannot be retrieved from Key Vault

### ISSUE THREAD

**Issue by pshelton-skype** [Azure/azure-powershell#5324]
### Cmdlet(s)
New-AzureRmResourceGroupDeployment

### PowerShell Version
5.1.16299.98

### Module Version
5.1.1

### OS Version
10.0.16299.98

### Debug Output
```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : 406b0d86-cabc-46a3-b93b-5d940fe29766
x-ms-correlation-request-id   : 406b0d86-cabc-46a3-b93b-5d940fe29766
x-ms-routing-request-id       : EASTUS:20180120T044356Z:406b0d86-cabc-46a3-b93b-5d940fe29766
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Sat, 20 Jan 2018 04:43:55 GMT

Body:
{
  "error": {
    "code": "MultipleErrorsOccurred",
    "message": "Multiple error occurred: Conflict,Conflict,Conflict,Conflict. Please see details.",
    "details": [
      {
        "code": "KeyVaultParameterReferenceSecretRetrieveFailed",
        "message": "The secret of KeyVault parameter 'mediaServiceAccountKey' cannot be retrieved. Http status code:
'Forbidden'. Error message: 'Access denied'. Please see https://aka.ms/arm-keyvault for usage details."
      },
      {
        "code": "KeyVaultParameterReferenceSecretRetrieveFailed",
        "message": "The secret of KeyVault parameter 'MtlsCertContent' cannot be retrieved. Http status code:
 'Forbidden'. Error message: 'Access denied'. Please see https://aka.ms/arm-keyvault for usage details."
      },
      {
        "code": "KeyVaultParameterReferenceSecretRetrieveFailed",
        "message": "The secret of KeyVault parameter 'cosmosDbAccountKey' cannot be retrieved. Http status code:
'Forbidden'. Error message: 'Access denied'. Please see https://aka.ms/arm-keyvault for usage details."
      },
      {
        "code": "KeyVaultParameterReferenceSecretRetrieveFailed",
        "message": "The secret of KeyVault parameter 'redisAccountKey' cannot be retrieved. Http status code:
'Forbidden'. Error message: 'Access denied'. Please see https://aka.ms/arm-keyvault for usage details."
      }
    ]
  }
}
```

### Script/Steps for Reproduction

When deploying a template with parameter references to secrets and certificates in Key Vault, useless error messages are displayed in the output if the vault does not have `enabledForTemplateDeployment` set to `true`. 

```
New-AzureRmResourceGroupDeployment : Multiple error occurred: Conflict,Conflict,Conflict,Conflict,Conflict. Please see
details.
At D:\src\mediaservice\deployment\webapi.deploy.ps1:65 char:5
+     New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGr ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet

Deploying...DONE
```

Using the suggested `Resolve-AzureRmError` is not helpful:

```
PS D:\src\mediaservice\deployment> Resolve-AzureRmError


   HistoryId: 4


RequestId      : ef4bd5a1-ea3c-4a33-8360-0107eaaad7f7
Message        : Multiple error occurred: Conflict,Conflict,Conflict,Conflict,Conflict. Please see details.
ServerMessage  : MultipleErrorsOccurred: Multiple error occurred: Conflict,Conflict,Conflict,Conflict,Conflict. Please
                 see details. (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {Conflict}
RequestMessage : {POST https://management.azure.com/subscriptions/AAAAAAAA-1c34-47eb-a1ac-34900157dd38/resourcegroups/a
                 zmstestwebapiwestus/providers/Microsoft.Resources/deployments/webapi.template/validate?api-version=201
                 7-05-10}
InvocationInfo : {New-AzureRmResourceGroupDeployment}
Line           :     New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroupName -TemplateFile
                 "$deploymentDir\webapi.template.json" -TemplateParameterFile "$deploymentDir\$parametersFilePath"

Position       : At D:\src\mediaservice\deployment\webapi.deploy.ps1:65 char:5
                 +     New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGr ...
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<ValidateWithHttpMessagesAsync>
                 d__10.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.<ValidateAsync>d__11.
                 MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.Validate(IDeployments
                 Operations operations, String resourceGroupName, String deploymentName, Deployment parameters)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.CheckBasicDe
                 ploymentErrors(String resourceGroup, String deploymentName, Deployment deployment)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.ExecuteDeplo
                 yment(PSCreateResourceGroupDeploymentParameters parameters)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentC
                 mdlet.<ExecuteCmdlet>b__21_0()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(Boolean force,
                 String continueMessage, String processMessage, String target, Action action, Func`1 useShouldContinue)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentC
                 mdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 4
```

No deployments are listed in the portal under the resource group for further debugging, and the only way to determine the issue is to enable the debugging flag and inspect the output for the information pasted above.

Proper, helpful error messages should be surfaces in the error output from `New-AzureRmResourceGroupDeployment` in this scenario.

**Comment by maddieclayton** [comment]
@pshelton-skype Running this cmdlet with -Verbose should give even better information about the failure.  Additionally, can you post the template that you used in order for the ResourceManager team to debug the issue?

@vivsriaus @ravbhatnagar Can you take a look at this issue?

**Comment by pshelton-skype** [comment]
`-Verbose` doesn't give me any additional output. Only the `$DebugPreference="Continue"` parameter actually gives useful output. 

I actually have an almost identical repro today, but instead of a permissions issue, this one had a typo in the name of the secret, meaning I received a `NotFound` rather than `Forbidden`:

```
New-AzureRmResourceGroupDeployment : Multiple error occurred: Conflict,Conflict,Conflict,Conflict. Please see details.
At D:\src\async_azure_mediaservice\deployment\webapi.deploy.ps1:65 char:5
+     New-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGr ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmResourceGroupDeployment], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDep
   loymentCmdlet
```

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : dc407c0c-7fc9-4630-b267-eb4c9efd53f8
x-ms-correlation-request-id   : dc407c0c-7fc9-4630-b267-eb4c9efd53f8
x-ms-routing-request-id       : WESTUS2:20180125T025551Z:dc407c0c-7fc9-4630-b267-eb4c9efd53f8
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Cache-Control                 : no-cache
Date                          : Thu, 25 Jan 2018 02:55:51 GMT

Body:
{
  "error": {
    "code": "MultipleErrorsOccurred",
    "message": "Multiple error occurred: Conflict,Conflict,Conflict,Conflict. Please see details.",
    "details": [
      {
        "code": "KeyVaultParameterReferenceSecretRetrieveFailed",
        "message": "The secret of KeyVault parameter 'mediaServicesClientId' cannot be retrieved. Http status code:
'NotFound'. Error message: 'Secret not found: MediaServicesClientId'. Please see https://aka.ms/arm-keyvault for usage
details."
      },
    ]
  }
}
```

A minimal representative template is as follows:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "certContent": {
            "type": "securestring"
        }
    },
    "variables": {  },
    "resources": [
        {
            "type": "Microsoft.Web/serverfarms",
            "sku": {
                "name": "S1",
                "tier": "Standard",
                "size": "S1",
                "family": "S",
                "capacity": 1
            },
            "kind": "app",
            "name": "TestAppServicePlan",
            "apiVersion": "2016-09-01",
            "location": "Central US",
            "scale": null,
            "properties": {
                "name": "TestAppServicePlan"
            },
            "dependsOn": []
        },
        {
            "type": "Microsoft.Web/certificates",
            "name": "Certificate",
            "apiVersion": "2016-03-01",
            "location": "Central US",
            "properties": {
                "pfxBlob": "[parameters('certContent')]"
            },
            "dependsOn": [
                "[resourceId('Microsoft.Web/serverfarms/TestAppServicePlan')]"
            ]
        }
    ]
}
```
with corresponding parameter file:

```
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "certContent": {
            "reference": {
                "keyVault": {
                    "id": "/subscriptions/aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa/resourceGroups/ResourceGroupName/providers/Microsoft.KeyVault/vaults/KeyVaultName"
                },
                "secretName": "NonExistantCertificate"
            }
        }
    }
}
```
You can reproduce with a non-existant Key Vault name, or without having the `enabledForTemplateDeployment` parameter set to `true` on an existing Key Vault with a valid `secretName`.

**Comment by sepharg** [comment]
+1 to this, i spent a lot of time trying to figure out what was wrong until i realised my key vault wasn't enabled for template deployment

**Comment by kirankumargollapelly** [comment]
Can you please let me know, how to enable the key vault for template deployment ?

**Comment by sepharg** [comment]
It's a "hidden" setting you can set when under **Access Policies -> Click to show advanced access policies**
As shown here:

![image](https://user-images.githubusercontent.com/3963438/40120617-ee15a864-591f-11e8-9354-d1fd51cfaa7d.png)

**Comment by ridhoq** [comment]
+1. This error needs to be more clear from the error output without having to set `$DebugPreference="Continue"`.

**Comment by cormacpayne** [comment]
CC: @Tiano2017

**Comment by itsramz** [comment]
Hi, Im trying to create a template that generates Key vault,key and and secret . JSON template doesnt throw any erro But when I execute it its giving "New-AzureRmResourceGroupDeployment : Cannot retrieve the dynamic parameters for the cmdlet. Parameter type in parameters cannot be 
null or empty" error

**Comment by abatishchev** [comment]
@itsramz: I'd recommend to create separate issue. I was receiving the same error and was able to overcome it.

@sepharg you've made my day!

@maddieclayton any news on addressing the overall issue by any chance?

**Comment by ForteUnited** [comment]
This issue has also just bit me. Even in a try catch the $_ doesn't contain the detail messages.

**Comment by mav108** [comment]
I have the similar issue, any update on this.

**Comment by torreymicrosoft** [comment]
@pshelton-skype Thanks for the detailed report. Good news this appears to be resolved in the current Az.Resources module. Deployment errors now surface nested detail such as `KeyVaultParameterReferenceSecretRetrieveFailed`, the affected parameter name, and HTTP status, instead of the generic "Multiple error occurred: Conflict" message you saw on AzureRM.

Closing as fixed. If a Key Vault parameter retrieval still produces an unclear error on latest Az.Resources, please file a new issue with the redacted output. @azcloudfarmer for vis.
