### ISSUE TITLE
Backup-AzureRmApiManagement Fails for Basic Instance

### ISSUE THREAD

**Issue by afyles** [Azure/azure-powershell#5437]
### Cmdlet(s)
Backup-AzureRmApiManagement 

### PowerShell Version
5.114393

### Module Version
5.1.0

### OS Version
10.0

### Description
Fails with the following error, seems to be unsupported, but not documentation states that as such.
```
Backup-AzureRmApiManagement : Requested value 'Basic' was not found.
At line:1 char:1
+ Backup-AzureRmApiManagement -ResourceGroupName $resourceGroup -Name w ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Backup-AzureRmApiManagement], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.Commands.BackupAzureApiManagement
```

### Debug Output
```
DEBUG: AzureQoSEvent: CommandName - Backup-AzureRmApiManagement; IsSuccess - False; Duration - 00:07:05.7206824;
Exception - System.ArgumentException: Requested value 'Basic' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object
failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at
Microsoft.Azure.Management.ApiManagement.ResourceProviderOperations.<GetApiServiceLongRunningOperationStatusAsync>d__15
.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Commands.ApiManagement.ApiManagementClient.GetLongRunningOperationStatus(ApiManagementLongRunningOperat
ion longRunningOperation)
   at
Microsoft.Azure.Commands.ApiManagement.Commands.AzureApiManagementCmdletBase.WaitForOperationToComplete(ApiManagementLo
ngRunningOperation longRunningOperation)
   at Microsoft.Azure.Commands.ApiManagement.Commands.AzureApiManagementCmdletBase.ExecuteLongRunningCmdletWrap(Func`1
func, Boolean passThru, Object passThruValue);
DEBUG: Finish sending metric.
DEBUG: 3:21:06 PM - BackupAzureApiManagement end processing.
DEBUG: 3:21:06 PM - BackupAzureApiManagement end processing.

```
### Script/Steps for Reproduction
Run the command:
`Backup-AzureRmApiManagement -ResourceGroupName $resourceGroup -Name $instanceName -StorageContext $storageContext -TargetContainerName $containerName -TargetBlobName $blobName -Verbose`

**Comment by markcowl** [comment]
@afyles Which region is this request against?

@solankisamir Can you take a look?

**Comment by solankisamir** [comment]
@afyles the PowerShell cmdlet does not support it. The fix was rejected https://github.com/Azure/azure-sdk-for-net/pull/3971

**Comment by afyles** [comment]
East-US is the region. Is this supported via the REST management API?

**Comment by solankisamir** [comment]
This is now supported with https://github.com/Azure/azure-powershell/releases/tag/v6.1.0-May2018
