### ISSUE TITLE
Login-AzureRMAccount causes unhandled exception

### ISSUE THREAD

**Issue by MrCNeale** [Azure/azure-powershell#5503]
### Cmdlet(s)
Login-AzureRMAccount
### PowerShell Version
Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`
6.0.1
### Module Version
4.2.0
### OS Version
Instructions: to get OS version, type `$PSversionTable` and look for value associated with `BuildVersion`
10.0.0.10586
### Description
Running **Login-AzureRMAccount** with or without parameters causes an unhandled exception to occur.

### Debug Output
```
PS C:\Program Files\PowerShell\6.0.1> Login-AzureRmAccount
DEBUG: 11:02:56 - AddAzureRMAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 11:02:56 - Autosave setting from startup session: 'Process'
DEBUG: 11:02:56 - No autosave setting detected in environment variable 'AzureRmContextAutoSave'.
DEBUG: 11:02:56 - Using Autosave scope 'Process'

An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'


Unhandled Exception: DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 02/12/2018 11:02:56:  - AuthenticationContext: ADAL .NET with assembly version '2.28.3.860', file version '2.28.31117.1411' and informational version '78bd21073cfd91768d97894ace1ba90c5b904eec' is running...
System.TypeLoadException: Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Windows.Forms.Form.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()

DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 02/12/2018 11:02:56: 5168a1b2-5c77-4578-bc9b-465c92f62516 - AcquireTokenHandlerBase: === Token Acquisition started:
        Authority: https://login.microsoftonline.com/Common/
        Resource: https://management.core.windows.net/
        ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
        CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (0 items)
        Authentication Target: User


DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 :
DEBUG: 02/12/2018 11:02:57: 5168a1b2-5c77-4578-bc9b-465c92f62516 - <RunAsync>d__0: System.TypeInitializationException: The type initializer for 'System.Windows.Forms.Form' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Windows.Forms.Form..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Forms.Form.get_CreateParams()
   at System.Windows.Forms.Control..ctor(Boolean autoInstallSyncContext)
   at System.Windows.Forms.ScrollableControl..ctor()
   at System.Windows.Forms.ContainerControl..ctor()
   at System.Windows.Forms.Form..ctor()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WindowsFormsWebAuthenticationDialogBase..ctor(Object ownerWindow)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WindowsFormsWebAuthenticationDialog..ctor(Object ownerWindow)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.InteractiveWebUI.OnAuthenticate()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.<AcquireAuthorization>b__0()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.AcquireAuthorization()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.PreTokenRequest()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()

Login-AzureRmAccount : The type initializer for 'System.Windows.Forms.Form' threw an exception.: Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
At line:1 char:1
+ Login-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Add-AzureRmAccount], AadAuthenticationFailedException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand

DEBUG: AzureQoSEvent: CommandName - Add-AzureRmAccount; IsSuccess - False; Duration - 00:00:01.0971130; Exception - Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedException: The type initializer for 'System.Windows.Forms.Form' threw an exception.: Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. ---> System.TypeInitializationException: The type initializer for 'System.Windows.Forms.Form' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Drawing.Icon' from assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at System.Windows.Forms.Form..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.DoAcquireToken(AdalConfiguration config, PromptBehavior promptBehavior, Action`1 promptAction, String userId, SecureString password)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.SafeAquireToken(AdalConfiguration config, String showDialog, Action`1 promptAction, String userId, SecureString password, Exception& ex)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.AcquireToken(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String userId, SecureString password)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.GetAccessToken(AdalConfiguration config, String promptBehavior, Action`1 promptAction, String userId, SecureString password, String credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name)
   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.<>c__DisplayClass77_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();

```
### Script/Steps for Reproduction
Open Powershell 6.0.1 window.
Type **Login-AzureRMAccount** and hit enter.
Unhandled exception occurs and is trapped by Windows which gives the "Powershell Core 6 has stopped working" prompt.

**Comment by markcowl** [comment]
@MrCNeale The AzureRM.Profile module is not netcore compatible.  You cna tell this because it is not listed in the galelry with the 'Linux' tag.  For NetCore compatible azure powershell modules, use AzureRM.NetCore: https://www.powershellgallery.com/packages/AzureRM.Netcore/
