### ISSUE TITLE
Some cmdlets aren't passing the token parameter after using the Add-AzureRmAccount cmdlet with the AccessToken parameter.

### ISSUE THREAD

**Issue by corydwood** [Azure/azure-powershell#5743]
### Description

When I authenticate to Azure using the **Add-AzureRmAccount** cmdlet with the **AccessToken** parameter and use certain cmdlets such as **Get-AzureRmRoleAssignment**, **New-AzureRmRoleAssignment**, or any of the **Get-AzureRmAd...** cmdlets, I receive the error below.

This is similar to #3088.

### Script/Steps for Reproduction

```powershell
Add-AzureRmAccount -AccessToken $token -AccountId $accountId
Get-AzureRmRoleAssignment

Get-AzureRmRoleAssignment : Value cannot be null.
Parameter name: token
At line:1 char:1
+ Get-AzureRmRoleAssignment
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.5.0      AzureRM
Script     5.1.1      AzureRM
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.15063.786                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.15063.786                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

### Debug Output

```
DEBUG: 1:25:25 PM - GetAzureRoleAssignmentCommand begin processing with ParameterSet 'EmptyParameterSet'.
DEBUG: 1:25:34 PM - using account id 'REMOVED'...
Get-AzureRmRoleAssignment : Value cannot be null.
Parameter name: token
At line:1 char:1
+ Get-AzureRmRoleAssignment -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmRoleAssignment], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmRoleAssignment; IsSuccess - False; Duration - 00:00:10.5838689;
Exception - System.ArgumentNullException: Value cannot be null.
Parameter name: token
   at Microsoft.Rest.TokenCredentials..ctor(String token, String tokenType)
   at
Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.GetServiceClientCredentials(IAzureContex
t context, String targetEndpoint)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateArmClient[TClient](IAzureContext
context, String endpoint)
   at Microsoft.Azure.Graph.RBAC.Version1_6.ActiveDirectory.ActiveDirectoryClient..ctor(IAzureContext context)
   at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient..ctor(IAzureContext context)
   at Microsoft.Azure.Commands.Resources.Models.ResourcesBaseCmdlet.get_PoliciesClient()
   at Microsoft.Azure.Commands.Resources.GetAzureRoleAssignmentCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:25:36 PM - GetAzureRoleAssignmentCommand end processing.
DEBUG: 1:25:36 PM - GetAzureRoleAssignmentCommand end processing.
```

**Comment by soulseak** [comment]
Hit the same Issue any workarround suggested? (except using the rest api directly)

**Comment by markcowl** [comment]
@corydwood @soulseak The role assignment cmdlets also need to have a token for graph.  To use all the cmdlets, you should pass tokens for graph, (and keyvaule if you are going to use keyvault data plane cmdlets): https://github.com/Azure/azure-powershell/blob/99a4b52c20dac795a360cb33a64c451aef5ee133/src/ResourceManager/Profile/Commands.Profile/help/Connect-AzureRmAccount.md#accesstokenwithsubscriptionid 

use the -GraphAccessToken parameter for the graph access token and -KeyVaultAccessToken for the KeyVault data plane access token.

**Comment by corydwood** [comment]
@markcowl - That did the trick. Thanks!
