### ISSUE TITLE
Get-AzureRmApiManagement Fails for Basic SKU Instance

### ISSUE THREAD

**Issue by mbsnl** [Azure/azure-powershell#5812]
### Description

Get-AzureRmApiManagement Fails for Basic SKU Instance

### Script/Steps for Reproduction

On a Basic SKU Instance, perform this command:
```powershell
Get-AzureRmApiManagement

```

### Module Version

```powershell
C:\> Get-Module -Name AzureRM.ApiManagement -ListAvailable
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.1.0      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementS...
```

### Environment Data

```powershell
C:\> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.2125
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2125
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : ffffffff-cd5c-46a3-b2b4-8bd671fd10ca
x-ms-ratelimit-remaining-subscription-reads: 14991
x-ms-correlation-request-id   : ffffffff-9b12-4008-85a6-1221003ddc41
x-ms-routing-request-id       : WESTUS:20180326T141624Z:ffffffff-9b12-4008-85a6-1221003ddc41
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 26 Mar 2018 14:16:23 GMT
ETag                          : "FFFFFFDkwjU="
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "id":
"/subscriptions/ffffffff-48e2-4b49-989c-515be28b2255/resourceGroups/RG-Name/providers/Microsoft.ApiManagement/service/apimname",
  "name": "apimname",
  "type": "Microsoft.ApiManagement/service",
  "tags": {},
  "location": "West Europe",
  "etag": "FFFFFFDkwjU=",
  "properties": {
    "publisherEmail": "first.last@email.com",
    "publisherName": "XX",
    "provisioningState": "Succeeded",
    "targetProvisioningState": "",
    "createdAtUtc": "2018-03-26T07:34:28.9946519Z",
    "runtimeUrl": "https://apimname.azure-api.net",
    "portalUrl": "https://apimname.portal.azure-api.net",
    "managementApiUrl": "https://apimname.management.azure-api.net",
    "scmUrl": "https://apimname.scm.azure-api.net",
    "addresserEmail": "apimgmt-noreply@mail.windowsazure.com",
    "hostnameConfigurations": [],
    "staticIPs": [
      "52.233.136.xxx"
    ],
    "additionalLocations": null,
    "vpnconfiguration": null,
    "customProperties": null,
    "vpnType": 0
  },
  "sku": {
    "name": "Basic",
    "capacity": 1
  }
}

Get-AzureRmApiManagement : Requested value 'Basic' was not found.
At line:1 char:1
+ Get-AzureRmApiManagement -ResourceGroupName 'RG-Name ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmApiManagement], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ApiManagement.Commands.GetAzureApiManagement

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmApiManagement; IsSuccess - False; Duration - 00:00:04.0653594; Exception
 - System.ArgumentException: Requested value 'Basic' was not found.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Azure.Management.ApiManagement.ResourceProviderOperationsExtensions.Get(IResourceProviderOperations
operations, String resourceGroupName, String name)
   at Microsoft.Azure.Commands.ApiManagement.ApiManagementClient.GetApiManagement(String resourceGroupName, String
serviceName)
   at Microsoft.Azure.Commands.ApiManagement.Commands.GetAzureApiManagement.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:16:26 PM - GetAzureApiManagement end processing.
DEBUG: 4:16:26 PM - GetAzureApiManagement end processing.
```

**Comment by cormacpayne** [comment]
@solankisamir Hey Samir, would you mind taking a look at this issue?

**Comment by solankisamir** [comment]
@cormacpayne we are working on the update to the cmdlets which will fix this issue.

**Comment by toddfoust** [comment]
Is there an ETA to get this cmdlet fixed to support Basic tier too?

**Comment by solankisamir** [comment]
We are actively working on this. Should be out within the next month.

**Comment by solankisamir** [comment]
This is now supported with release https://github.com/Azure/azure-powershell/releases/tag/v6.1.0-May2018
