### ISSUE TITLE
Get-AzureRMDisk: Unable to deserialize the response ("createOption": "Restore")

### ISSUE THREAD

**Issue by chris-bowman** [Azure/azure-powershell#5835]
Calling Get-AzureRmDisk with no parameters is failing to deserialize the json response. It doesn't seem to like "createOption": "Restore", which is what you'd get when you do a failover from ASR A2A with Managed Disks.

Using ASR replicate and failover a VM from region A to region B, then run Get-AzureRmDisk on any of the disks that have been created.
```powershell
get-azurermdisk : Unable to deserialize the response.
At line:1 char:1
+ get-azurermdisk
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDisk], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureRmDisk

```
Exception - Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "**Restore**" to type 'Microsoft.Azure.Management.Compute.Models.**DiskCreateOption**'. Path 'createOption', line 10, position 32. ---> System.ArgumentException: Requested value 'Restore' was not found.
### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                         
---------- -------    ----                                ----------------                                                                         
Script     5.6.0      AzureRM                                                                                                                      
```

### Environment Data

```powershell
$PSVersionTable

Name                           Value                                                                                                               
----                           -----                                                                                                               
PSVersion                      5.1.16299.251                                                                                                       
PSEdition                      Desktop                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                             
BuildVersion                   10.0.16299.251                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                     
WSManStackVersion              3.0                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                             

```

### Debug Output

```
DEBUG: 3:14:13 PM - GetAzureRmDisk begin processing with ParameterSet 'DefaultParameter'.
DEBUG: 3:14:14 PM - using account id 'xxxxxx'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xxxxxx', environment: 'AzureCloud', tenant: 'xxxxxxxxxx'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 9e533c42-7b71-4342-9818-15e095eb02dd - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/xxxxxxxxxx/
	Resource: https://management.core.windows.net/
	ClientId: xxxxxxxxxx
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (5 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 03/29/2018 04:14:14: 9e533c42-7b71-4342-9818-15e095eb02dd - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 9e533c42-7b71-4342-9818-15e095eb02dd - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 03/29/2018 04:14:14: 9e533c42-7b71-4342-9818-15e095eb02dd - TokenCache: 46.2392616616667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 9e533c42-7b71-4342-9818-15e095eb02dd - TokenCache: A matching item (access token or refresh token or both) was found in 
the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 9e533c42-7b71-4342-9818-15e095eb02dd - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access t
oken was retuned:
	Access Token Hash: XXXX
	Refresh Token Hash: XXXX
	Expiration Time: 03/29/2018 05:00:28 +00:00
	User Hash: XXXX
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14:  - TokenCache: Serializing token cache with 5 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 89b6b961-bca0-43eb-b00c-0a0bc26cbef3 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/xxxx
	Resource: https://management.core.windows.net/
	ClientId: xxxxx
	CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (5 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 03/29/2018 04:14:14: 89b6b961-bca0-43eb-b00c-0a0bc26cbef3 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 89b6b961-bca0-43eb-b00c-0a0bc26cbef3 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 03/29/2018 04:14:14: 89b6b961-bca0-43eb-b00c-0a0bc26cbef3 - TokenCache: 46.23907399 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 89b6b961-bca0-43eb-b00c-0a0bc26cbef3 - TokenCache: A matching item (access token or refresh token or both) was found in 
the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14: 89b6b961-bca0-43eb-b00c-0a0bc26cbef3 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access t
oken was retuned:
	Access Token Hash: xxxxx
	Refresh Token Hash: xxxxx
	Expiration Time: 03/29/2018 05:00:28 +00:00
	User Hash: xxxxx
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 03/29/2018 04:14:14:  - TokenCache: Serializing token cache with 5 items.

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxxxxa/providers/Microsoft.Compute/disks?api-version=2017-03-30

Headers:
x-ms-client-request-id        : c4847f06-eb8d-42eb-8923-6a25130f9a01
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-original-request-ids     : 89c60cf4-fe1b-46ec-9885-2f18420cd629,e89afbd4-e375-4b51-a6a8-400583767065
x-ms-ratelimit-remaining-subscription-reads: 14997
x-ms-request-id               : 3421c89e-0848-4578-9233-1898d0267b69
x-ms-correlation-request-id   : 3421c89e-0848-4578-9233-1898d0267b69
x-ms-routing-request-id       : AUSTRALIAEAST:20180329T041414Z:3421c89e-0848-4578-9233-1898d0267b69
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 29 Mar 2018 04:14:14 GMT

Body:
{
  "value": [
    {
      "managedBy": "/subscriptions/xxxxxxxxxxa/resourceGroups/bowmanlabs-rg/providers/Microsoft.Compute/virtualMachines/bow
mandc",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "properties": {
        "osType": "Windows",
        "creationData": {
          "createOption": "Restore",
          "sourceResourceId": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmanlabs-rg/providers/Microsoft.Compute/disks/bo
wmandc_osdisk_1_f0d0dd33c79d4acf93f68280aab7279e-ASRReplica/bookmark/4cdd6dbc-57f4-414c-b41c-c98f437c691c"
        },
        "diskSizeGB": 30,
        "timeCreated": "2018-03-22T15:41:10.253744+11:00",
        "provisioningState": "Succeeded",
        "diskState": "Attached"
      },
      "type": "Microsoft.Compute/disks",
      "location": "australiaeast",
      "tags": {
        "ASR-FODisk": "Created by Azure Site Recovery."
      },
      "id": "/subscriptions/xxxxxxxxxx/resourceGroups/BOWMANLABS-RG/providers/Microsoft.Compute/disks/bowmandc_OsDisk_1_f0
d0dd33c79d4acf93f68280aab7279e",
      "name": "bowmandc_OsDisk_1_f0d0dd33c79d4acf93f68280aab7279e"
    },
    {
      "managedBy": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmanlabs-rg/providers/Microsoft.Compute/virtualMachines/bow
manjmp",
      "sku": {
        "name": "Premium_LRS",
        "tier": "Premium"
      },
      "properties": {
        "osType": "Windows",
        "creationData": {
          "createOption": "Restore",
          "sourceResourceId": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmanlabs-rg/providers/Microsoft.Compute/disks/bo
wmanjmp_osdisk_1_f898ef4115e5416a875c5aa19cf95bce-ASRReplica/bookmark/3eac8e52-b2f5-44b0-8e9b-676335d8f7db"
        },
        "diskSizeGB": 32,
        "timeCreated": "2018-03-23T08:45:13.7916793+11:00",
        "provisioningState": "Succeeded",
        "diskState": "Reserved"
      },
      "type": "Microsoft.Compute/disks",
      "location": "australiaeast",
      "tags": {
        "ASR-FODisk": "Created by Azure Site Recovery."
      },
      "id": "/subscriptions/xxxxxxxxxx/resourceGroups/BOWMANLABS-RG/providers/Microsoft.Compute/disks/bowmanjmp_OsDisk_1_f
898ef4115e5416a875c5aa19cf95bce",
      "name": "bowmanjmp_OsDisk_1_f898ef4115e5416a875c5aa19cf95bce"
    },
    {
      "managedBy": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmanlabs-rg/providers/Microsoft.Compute/virtualMachines/bow
mantest",
      "sku": {
        "name": "Premium_LRS",
        "tier": "Premium"
      },
      "properties": {
        "osType": "Windows",
        "creationData": {
          "createOption": "Restore",
          "sourceResourceId": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmanlabs-rg/providers/Microsoft.Compute/disks/bo
wmantest_osdisk_1_7660ec4411ef45c88198d408bd3759a3-ASRReplica/bookmark/7bca924a-039d-498d-934f-d892631939b8"
        },
        "diskSizeGB": 128,
        "timeCreated": "2018-03-23T15:02:21.0575281+11:00",
        "provisioningState": "Succeeded",
        "diskState": "Reserved"
      },
      "type": "Microsoft.Compute/disks",
      "location": "australiaeast",
      "tags": {
        "ASR-FODisk": "Created by Azure Site Recovery."
      },
      "id": "/subscriptions/xxxxxxxxxx/resourceGroups/BOWMANLABS-RG/providers/Microsoft.Compute/disks/bowmantest_OsDisk_1_
7660ec4411ef45c88198d408bd3759a3",
      "name": "bowmantest_OsDisk_1_7660ec4411ef45c88198d408bd3759a3"
    },
    {
      "managedBy": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmansync-rg/providers/Microsoft.Compute/virtualMachines/bow
manfilesync",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "properties": {
        "creationData": {
          "createOption": "Empty"
        },
        "diskSizeGB": 256,
        "timeCreated": "2018-03-09T08:39:41.4382048+11:00",
        "provisioningState": "Succeeded",
        "diskState": "Reserved"
      },
      "type": "Microsoft.Compute/disks",
      "location": "australiaeast",
      "id": "/subscriptions/xxxxxxxxxx/resourceGroups/BOWMANSYNC-RG/providers/Microsoft.Compute/disks/bowmanfilesync-data"
,
      "name": "bowmanfilesync-data"
    },
    {
      "managedBy": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmansync-rg/providers/Microsoft.Compute/virtualMachines/bow
manfilesync",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "properties": {
        "osType": "Windows",
        "creationData": {
          "createOption": "FromImage",
          "imageReference": {
            "id": "/Subscriptions/xxxxxxxxxx/Providers/Microsoft.Compute/Locations/australiaeast/Publishers/MicrosoftWindo
wsServer/ArtifactTypes/VMImage/Offers/WindowsServer/Skus/2016-Datacenter/Versions/2016.127.20171217"
          }
        },
        "diskSizeGB": 127,
        "timeCreated": "2018-03-09T08:14:08.3501493+11:00",
        "provisioningState": "Succeeded",
        "diskState": "Reserved"
      },
      "type": "Microsoft.Compute/disks",
      "location": "australiaeast",
      "id": "/subscriptions/xxxxxxxxxx/resourceGroups/BOWMANSYNC-RG/providers/Microsoft.Compute/disks/bowmanfilesync_OsDis
k_1_dc86da7d06d84feba96e844bf82233db",
      "name": "bowmanfilesync_OsDisk_1_dc86da7d06d84feba96e844bf82233db"
    },
    {
      "managedBy": "/subscriptions/xxxxxxxxxx/resourceGroups/bowmansync-rg/providers/Microsoft.Compute/virtualMachines/bow
mafilesync2",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "properties": {
        "osType": "Windows",
        "creationData": {
          "createOption": "FromImage",
          "imageReference": {
            "id": "/Subscriptions/xxxxxxxxxx/Providers/Microsoft.Compute/Locations/australiasoutheast/Publishers/Microsoft
WindowsServer/ArtifactTypes/VMImage/Offers/WindowsServer/Skus/2016-Datacenter/Versions/2016.127.20171217"
          }
        },
        "diskSizeGB": 127,
        "timeCreated": "2018-03-09T08:52:53.9367897+11:00",
        "provisioningState": "Succeeded",
        "diskState": "Reserved"
      },
      "type": "Microsoft.Compute/disks",
      "location": "australiasoutheast",
      "id": "/subscriptions/xxxxxxxxxxxx/resourceGroups/BOWMANSYNC-RG/providers/Microsoft.Compute/disks/bowmafilesync2_OsDis
k_1_483ea50c98c140a498f8406c70aac236",
      "name": "bowmafilesync2_OsDisk_1_483ea50c98c140a498f8406c70aac236"
    },
    {
      "managedBy": "/subscriptions/xxxxxxxxx/resourceGroups/bowmansync-rg/providers/Microsoft.Compute/virtualMachines/bow
mafilesync2",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "properties": {
        "creationData": {
          "createOption": "Empty"
        },
        "diskSizeGB": 256,
        "timeCreated": "2018-03-09T08:57:17.821924+11:00",
        "provisioningState": "Succeeded",
        "diskState": "Reserved"
      },
      "type": "Microsoft.Compute/disks",
      "location": "australiasoutheast",
      "id": "/subscriptions/xxxxxxxx/resourceGroups/BOWMANSYNC-RG/providers/Microsoft.Compute/disks/bowmanfilesync2-data
",
      "name": "bowmanfilesync2-data"
    }
  ]
}


Get-AzureRmDisk : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmDisk -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmDisk], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.GetAzureRmDisk
 
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmDisk; IsSuccess - False; Duration - 00:00:03.7786164; Exception - Microsoft.Rest.SerializationExcepti
on: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "Restore" to type 'Microsoft.Azure.M
anagement.Compute.Models.DiskCreateOption'. Path 'createOption', line 1, position 280. ---> System.ArgumentException: Requested value 'Restore' was 
not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType,
 Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContai
nerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, Js
onProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonPropert
y member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer ser
ializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType,
 Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonPropert
y containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty 
member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContai
nerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, Js
onProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonPropert
y member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Compute.DisksOperations.<ListWithHttpMessagesAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.Compute.DisksOperations.<ListWithHttpMessagesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.DisksOperationsExtensions.<ListAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.DisksOperationsExtensions.List(IDisksOperations operations)
   at Microsoft.Azure.Commands.Compute.Automation.GetAzureRmDisk.<ExecuteCmdlet>b__0_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 3:14:19 PM - GetAzureRmDisk end processing.
DEBUG: 3:14:19 PM - GetAzureRmDisk end processing.
```

**Comment by vladimir-shcherbakov** [comment]
@praries880 Could you take care of the issue?

**Comment by praries880** [comment]
issue is because the generated code does not seem to have a valid value for CreationOption : 
```c#
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Microsoft.Azure.Management.Compute.Models
{
    //
    // Summary:
    //     Defines values for DiskCreateOption.
    [JsonConverter(typeof(StringEnumConverter))]
    public enum DiskCreateOption
    {
        Empty = 0,
        Attach = 1,
        FromImage = 2,
        Import = 3,
        Copy = 4
    }
}
```

Which is a part of :
```c#
namespace Microsoft.Azure.Management.Compute.Models
{
    //
    // Summary:
    //     Data used when creating a disk.
    public class CreationData
    {
        //
        // Summary:
        //     Initializes a new instance of the CreationData class.
        public CreationData();
        //
        // Summary:
        //     Initializes a new instance of the CreationData class.
        //
        // Parameters:
        //   createOption:
        //     This enumerates the possible sources of a disk's creation. Possible values include:
        //     'Empty', 'Attach', 'FromImage', 'Import', 'Copy'
        //
        //   storageAccountId:
        //     If createOption is Import, the Azure Resource Manager identifier of the storage
        //     account containing the blob to import as a disk. Required only if the blob is
        //     in a different subscription
        //
        //   imageReference:
        //     Disk source information.
        //
        //   sourceUri:
        //     If createOption is Import, this is the URI of a blob to be imported into a managed
        //     disk.
        //
        //   sourceResourceId:
        //     If createOption is Copy, this is the ARM id of the source snapshot or disk.
        public CreationData(DiskCreateOption createOption, string storageAccountId = null, ImageDiskReference imageReference = null, string sourceUri = null, string sourceResourceId = null);

        //
        // Summary:
        //     Gets or sets this enumerates the possible sources of a disk's creation. Possible
        //     values include: 'Empty', 'Attach', 'FromImage', 'Import', 'Copy'
        [JsonProperty(PropertyName = "createOption")]
        public DiskCreateOption CreateOption { get; set; }
        //
        // Summary:
        //     Gets or sets disk source information.
        [JsonProperty(PropertyName = "imageReference")]
        public ImageDiskReference ImageReference { get; set; }
        //
        // Summary:
        //     Gets or sets if createOption is Copy, this is the ARM id of the source snapshot
        //     or disk.
        [JsonProperty(PropertyName = "sourceResourceId")]
        public string SourceResourceId { get; set; }
        //
        // Summary:
        //     Gets or sets if createOption is Import, this is the URI of a blob to be imported
        //     into a managed disk.
        [JsonProperty(PropertyName = "sourceUri")]
        public string SourceUri { get; set; }
        //
        // Summary:
        //     Gets or sets if createOption is Import, the Azure Resource Manager identifier
        //     of the storage account containing the blob to import as a disk. Required only
        //     if the blob is in a different subscription
        [JsonProperty(PropertyName = "storageAccountId")]
        public string StorageAccountId { get; set; }

        //
        // Summary:
        //     Validate the object.
        //
        // Exceptions:
        //   T:Microsoft.Rest.ValidationException:
        //     Thrown if validation fails
        public virtual void Validate();
    }
}
```

@hyonholee  can you take a look?

**Comment by carlneal** [comment]
I get the same issue even when I just do PS C:\Windows\system32> Get-AzureRmDisk 

Get-AzureRmDisk : Unable to deserialize the response

**Comment by NeilBird** [comment]
@carlneal - I had the same problem today, but after updating my "AzureRM.Compute" module to v5.0.0 by running "Update-Module -Name AzureRM" and closing and re-opening PowerShell it has resolved the issue. Hope this is useful.

Get-Module -Name AzureRM -ListAvailable
6.0.1      AzureRM

ReleaseNotes                : 6.0.0 - May 2018

**Comment by chris-bowman** [comment]
I confirm that this also now works for me in 6.01 as well, in fact the CreationData property populated with CreateOption Restore as well:

`$disk.CreationData

CreateOption     : Restore
StorageAccountId : 
ImageReference   : 
SourceUri        : 
SourceResourceId : /subscriptions/xxxxxxxxxxxxx/resourceGroups/bowmanlabs-rg/providers/Microsoft.Compute/disks/bowmandc_osdisk_1_f0d0dd33c79d4acf93f68280aab7279e-ASRReplica/bookmark/xxxxxxxxxxxx`

**Comment by maddieclayton** [comment]
Looks like this issue was resolve by updating the version - please reopen if this is not working in Az 1.2.0.
