### ISSUE TITLE
Importing AzureRM.ServiceFabric before AzureRM.KeyVault causes KeyVaultSecret cmdlets to fail

### ISSUE THREAD

**Issue by milope** [Azure/azure-powershell#5840]
### Description

In the latest version of AzureRM.KeyVault and AzureRM.ServiceFabric, if AzureRM.ServiceFabric is imported before AzureRM.KeyVault, cmdlets like Get-AzureKeyVaultSecret and Set-AzureKeyVaultSecret fail with the following:

```
Get-AzureKeyVaultSecret : Method not found: 'System.String
Microsoft.Azure.KeyVault.Models.SecretAttributes.get_RecoveryLevel()'.
At line:1 char:1
+ Get-AzureKeyVaultSecret -Name test -VaultName milopekv
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureKeyVaultSecret], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
```
This appears to happen because AzureRM.ServiceFabric loads a pre-built Microsoft.Azure.KeyVault.dll for which its Microsoft.Azure.KeyVault.Models.SecretAttributes does not have a RecoverLevel property. Since this property is returned by KeyVault when getting a secret, it fails to convert the JSON string to the object.

### Script/Steps for Reproduction

Run the following in order (ensure to have a Key Vault Secret)

```powershell
Connect-AzureRmAccount
Import-Module AzureRM.ServiceFabric
Get-AzureKeyVaultSecret -Name $secretName -KeyVault $keyVaultName
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
PS > Get-Module -Name AzureRM -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.6.0      AzureRM
Script     5.4.0      AzureRM
Script     5.1.1      AzureRM
Script     4.3.1      AzureRM
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.16299.248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
DEBUG: 10:32:20 PM - GetAzureKeyVaultSecret begin processing with ParameterSet 'BySecretName'.
DEBUG: 10:32:20 PM - using account id 'email@tenant.onmicrosoft.com'...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20:  - TokenCache: Serializing token cache with 2 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20:  - TokenCache: Serializing token cache with 2 items.
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', Endpoint: 'https://login.microsoftonline.us/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://vault.usgovcloudapi.net', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority
'https://login.microsoftonline.us/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/', CorrelationId:
'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain:
'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', AdEndpoint: 'https://login.microsoftonline.us/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20: 05a5ad40-0bb5-46da-9dfe-b9805386d832 - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.us/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
 Resource: https://vault.usgovcloudapi.net
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache (2 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 03/30/2018 03:32:20: 05a5ad40-0bb5-46da-9dfe-b9805386d832 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20: 05a5ad40-0bb5-46da-9dfe-b9805386d832 - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 03/30/2018 03:32:20: 05a5ad40-0bb5-46da-9dfe-b9805386d832 - TokenCache: 58.6583908066667 minutes left until
token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20: 05a5ad40-0bb5-46da-9dfe-b9805386d832 - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20: 05a5ad40-0bb5-46da-9dfe-b9805386d832 - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: TqTImRr0MAvMWmP0dgfsH+UNp+gNtQFBuQIy+CVUHYM=
 Refresh Token Hash: lYOsszRoha39vgEI8mUDS1tsecFXqWiRsARNYPWHpls=
 Expiration Time: 03/30/2018 04:31:00 +00:00
 User Hash: 4tQzpazvlnq8u/YId781mqKxmCjAvEQ2e30XxjUV3eM=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20:  - TokenCache: Serializing token cache with 2 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20:  - TokenCache: Serializing token cache with 2 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 03/30/2018 03:32:20:  - TokenCache: Serializing token cache with 2 items.
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '03/30/2018 04:31:00 +00:00',
MultipleResource? 'True', Tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', UserId:
'milope@azuregovsupport.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'milope@azuregovsupport.onmicrosoft.com', Name:  ,
IdProvider: 'https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/', Uid:
'3c2ad3e6-92ef-4027-9213-258a86adb5ef'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '03/30/2018 04:31:00 +00:00' Comparing to
'03/30/2018 03:32:20 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:58:39.5014599'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://milopekv.vault.usgovcloudapi.net/secrets/test/?api-version=2016-10-01

Headers:
x-ms-client-request-id        : d528e859-1e73-4d8d-b023-83432e1b6f40
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-keyvault-region          : USGovTexas
x-ms-request-id               : 8b3ba038-b0b0-4abb-ad6e-adbe1a93490a
x-ms-keyvault-service-version : 1.0.0.842
x-ms-keyvault-network-info    : addr=99.139.151.155;act_addr_fam=InterNetwork;
Strict-Transport-Security     : max-age=31536000;includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Fri, 30 Mar 2018 03:32:21 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "value": "foo",
  "contentType": "application/text",
  "id": "https://milopekv.vault.usgovcloudapi.net/secrets/test/a962b84094a747f18efb5e2348d48038",
  "attributes": {
    "enabled": true,
    "created": 1522356903,
    "updated": 1522356903,
    "recoveryLevel": "Purgeable"
  }
}

Get-AzureKeyVaultSecret : Method not found: 'System.String
Microsoft.Azure.KeyVault.Models.SecretAttributes.get_RecoveryLevel()'.
At line:1 char:1
+ Get-AzureKeyVaultSecret -Name test -VaultName milopekv
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureKeyVaultSecret], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret

DEBUG: AzureQoSEvent: CommandName - Get-AzureKeyVaultSecret; IsSuccess - False; Duration - 00:00:00.5261813; Exception
- System.MissingMethodException: Method not found: 'System.String
Microsoft.Azure.KeyVault.Models.SecretAttributes.get_RecoveryLevel()'.
   at Microsoft.Azure.Commands.KeyVault.Models.Secret..ctor(SecretBundle secret, VaultUriHelper vaultUriHelper)
   at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.GetSecret(String vaultName, String secretName,
 String secretVersion)
   at Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:32:22 PM - GetAzureKeyVaultSecret end processing.
DEBUG: 10:32:22 PM - GetAzureKeyVaultSecret end processing.
```

**Comment by vladimir-shcherbakov** [comment]
@maddieclayton Could you take a look?

**Comment by cormacpayne** [comment]
@maddieclayton this is a result of the issue outlined in https://github.com/Azure/azure-powershell/issues/5365

To workaround this issue for now, we should ensure that `AzureRM.KeyVault` and `AzureRM.ServiceFabric` are using the same version of the underlying KeyVault SDK.

**Comment by maddieclayton** [comment]
Fixed

**Comment by itaibh** [comment]
I started to encounter the same issue now, 3.5 years after it has been solved.
What does it mean to "enusure that `AzureRM.KeyVault` and `AzureRM.ServiceFabric` are using the same version of the underlying KeyVault SDK" ? Where do I see the versions used for each, and how do I change it if needed?
