### ISSUE TITLE
Get-AzureRmRecoveryServicesBackupContainer fails in Azure Automation

### ISSUE THREAD

**Issue by DrBushyTop** [Azure/azure-powershell#5977]
### Description

I'm trying to loop through backup vaults in the subscription to find out if a VM is already being backed up. "Get-AzureRmRecoveryServicesBackupContainer -ContainerType AzureVM -Status Registered" -command fails with a error message "Get-AzureRmRecoveryServicesBackupContainer : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'." while ran in Azure Automation. This happens when using either a run as account or a normal one.

I cannot reproduce this on my own laptop, where everything works just fine. Simplified the code a bit in the example, but results are still the same.

### Script/Steps for Reproduction

Updated on 9th of May (added steps to have VMs in the vault):

Create a new Backup Vault,
Create a VM & Enable backup to the vault
Create a new Automation account, update azure modules, add AzureRM.RecoveryServices & AzureRM.RecoveryServices.Backup from the gallery.
Create Powershell Runbook with following code (edit bu vault name)

```powershell
#$DebugPreference = "Continue"
 
$RunAsConnection = Get-AutomationConnection -Name AzureRunAsConnection

Add-AzureRmAccount `
-ServicePrincipal `
-TenantId $RunAsConnection.TenantId `
-ApplicationId $RunAsConnection.ApplicationId `
-CertificateThumbprint $RunAsConnection.CertificateThumbprint | Write-Verbose
Select-AzureRmSubscription -SubscriptionId $RunAsConnection.SubscriptionID  | Write-Verbose

Get-AzureRmRecoveryServicesVault -Name PH-BUVault | Set-AzureRmRecoveryServicesVaultContext
$Cont = Get-AzureRmRecoveryServicesBackupContainer -ContainerType AzureVM -Status Registered 
```

### Module Version

```powershell
ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Script     4.6.0      AzureRM.Profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureR...

Script     4.1.2      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesBackupProperty, Get-AzureRmReco...

Script     4.1.2      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServicesBackupItem, Disable-AzureRmR...

Binary     1.0        Orchestrator.AssetManagement.Cmd... {Get-AutomationCertificate, Get-AutomationConnection, Get-A...

Script     0.0        Orchestrator.GraphRunbook.Cmdlets   {Invoke-RunbookFlow, New-RunbookFlowJunction, New-RunbookFl...

```

### Environment Data

```powershell
Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1                                                                                  
```

### Debug Output

Error message:

```
ERROR: Get-AzureRmRecoveryServicesBackupContainer : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
At line:16 char:13
+     $Cont = Get-AzureRmRecoveryServicesBackupContainer -ContainerType ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmReco...BackupContainer], MissingMethodException
    + FullyQualifiedErrorId : 
Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.GetAzureRmRecoveryServicesBackupContainer
```

Resolve-AzureRmError: 

```
InnerException   : False
Exception        : System.MissingMethodException: Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
                   Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
                      at Microsoft.Rest.Serialization.JsonConverterHelper.IsJsonExtensionData(JsonProperty property)
                      at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, 
                   Type objectType, Object existingValue, JsonSerializer serializer)
                      at 
                   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter 
                   converter, JsonReader reader, Type objectType, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty 
                   property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty 
                   containerProperty, JsonReader reader, Object target)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, 
                   JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, 
                   Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader 
                   reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader 
                   reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type 
                   objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader 
                   reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty 
                   property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty 
                   containerProperty, JsonReader reader, Object target)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, 
                   JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, 
                   Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader 
                   reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type 
                   objectType, Boolean checkAdditionalContent)
                      at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                      at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, 
                   JsonSerializerSettings settings)
                      at Microsoft.Azure.Management.RecoveryServices.Backup.BackupProtectionContainersOperations.<ListWi
                   thHttpMessagesAsync>d__5.MoveNext()
Message          : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
                   Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
StackTrace       :    at Microsoft.Rest.Serialization.JsonConverterHelper.IsJsonExtensionData(JsonProperty property)
                      at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, 
                   Type objectType, Object existingValue, JsonSerializer serializer)
                      at 
                   Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter 
                   converter, JsonReader reader, Type objectType, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty 
                   property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty 
                   containerProperty, JsonReader reader, Object target)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, 
                   JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, 
                   Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader 
                   reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader 
                   reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type 
                   objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader 
                   reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty 
                   property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty 
                   containerProperty, JsonReader reader, Object target)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, 
                   JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, 
                   Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader 
                   reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract 
                   containerContract, JsonProperty containerMember, Object existingValue)
                      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type 
                   objectType, Boolean checkAdditionalContent)
                      at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                      at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, 
                   JsonSerializerSettings settings)
                      at Microsoft.Azure.Management.RecoveryServices.Backup.BackupProtectionContainersOperations.<ListWi
                   thHttpMessagesAsync>d__5.MoveNext()
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : NotSpecified: (:) [Get-AzureRmReco...BackupContainer], MissingMethodException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, <No file>: line 12

```

Debug (full file at pastebin, subscription & tenant IDs redacted: https://pastebin.com/kurmTFbN):

```

Caught exception, type: System.AggregateException
Handling aggregate exception
Get-AzureRmRecoveryServicesBackupContainer : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
At line:13 char:9
+ $Cont = Get-AzureRmRecoveryServicesBackupContainer -ContainerType Azu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureRmReco...BackupContainer], MissingMethodException
    + FullyQualifiedErrorId : 
Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.GetAzureRmRecoveryServicesBackupContainer
 
AzureQoSEvent: CommandName - Get-AzureRmRecoveryServicesBackupContainer; IsSuccess - False; Duration - 
00:00:03.8538350; Exception - System.MissingMethodException: Method not found: 
'Newtonsoft.Json.Serialization.IAttributeProvider Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
   at Microsoft.Rest.Serialization.JsonConverterHelper.IsJsonExtensionData(JsonProperty property)
   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, 
Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, 
JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter 
propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object 
target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, 
JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, 
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, 
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type 
objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty 
containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, 
JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, 
JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type 
objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty 
containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter 
propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object 
target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, 
JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, 
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, 
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type 
objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty 
containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, 
Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.RecoveryServices.Backup.BackupProtectionContainersOperations.<ListWithHttpMessagesAsync
>d__5.MoveNext();
Finish sending metric.
7:56:14 AM - GetAzureRmRecoveryServicesBackupContainer end processing.
7:56:14 AM - GetAzureRmRecoveryServicesBackupContainer end processing.
```

**Comment by cormacpayne** [comment]
@DrBushyTop thanks for filing this issue -- just to confirm, the above script you provided is all that you are running in Azure Automation, correct? It looks like there might be a mismatch in the version of `Newtonsoft.Json` that's being loaded into the PowerShell session.

@eamonoreilly Hey Eamon, do you know if the `AzureAutomationAuthoringToolkit` module uses `Newtonsoft.Json` in any way? It appears that is one of the modules being used in the above script

CC: @dragonfly91

**Comment by DrBushyTop** [comment]
Hi,

Apologies, that paste was actually from running the test via the toolkit.
However, the result is similar when ran directly from the portal. Here's the full debug log from that:
https://pastebin.com/uaTqes2R
Env variables & Modules for this were the same as above.

The code in the first message is all I'm running to reproduce the issue, yes. It is also the only added runbook after the creation. Brand new automation account with just the two mentioned modules added.

**Comment by chris4jahn** [comment]
Hello,

in my case I found a solution for that. After checking for updated modules several times I uninstalled the modules AzureRM.RecoveryServices and AzureRM.RecoveryServices.Backup
On my attempt to reinstall them I received a message that it is dependant on a Version 5.0.0 of AzureRM.Profile. This Module was stuck on Version 4.6.0 and using "update" button didn't change that. So I installed it via the PowerShell Gallery Website "Deploy to Azure Automation". After that I could also install the two modules above again and now it works.

Hope this helps someone else as well. 

Regards
Christian

**Comment by chris4jahn** [comment]
sorry, this was a false alarm as I didn't receive the error messages any more. it remains like it was before.

**Comment by RussPitcher** [comment]
I've got a similar issue - basically the same error message.  However I've removed and redeployed the AzureRM.Profile (5.0.1/5.0.0), AzureRM.RecoveryServices (4.1.2/4.1.3) and AzureRM.RecoveryServices.Backup (4.1.2/4.1.3) modules and I'm still getting basically the same error from my automation account.

Get-AzureRmRecoveryServicesBackupContainer : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.

I'm reluctant to upgrade all modules to the latest version as there are a number of breaking changes that mean we will have to update pretty much all of our other runbooks if we do.  I accept that we need to update them soon, but right now is not a good time for us to do this.

**Comment by zinktic** [comment]
I am having a similar issue as RussPitcher as well. 
**When running:**
$Pol = Get-AzureRmRecoveryServicesBackupProtectionPolicy -Name "DefaultPolicy"
**Error details:**
Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.


Given the issue (Support said the bug will be resolved by May 18th) with AzureRM.Profile resetting to 4.6.0, I have installed that package and all its dependencies(55 packages) from PowershellGallery.com but the issue continues to be there. I even tried to reinstall newtonsoft.json module from PG. Even after that, I still continue to get the error.

**Comment by gpitzalis** [comment]
Try removing (or renaming) all of the newtonsoft.json.dll you have in C:\Windows\Assembly\GAC and C:\Windows\Assembly\GAC_MSIL.

Regards,
@giampitz

**Comment by zinktic** [comment]
@giampitz - Tried doing that on the Azure automation account. It still didn't work and failed with the same error. 

Note the script works perfectly fine on the local machine. At this point, I am going to wait for the Azure package issue to get resolved tomorrow (05/18) and try again.

**Comment by chris4jahn** [comment]
We managed to get it working by updating the modules through the Powershell Gallery Website and by adding the module AzureRM.Resources in addition to the three others mentioned above. All modules are now installed in the newest version and the code runs like a charm. 
Hope this helps you as well. 

Regards Christian

**Comment by gpitzalis** [comment]
Now it works but i needed to remove all of the previous module versions by using this script:

http://sharepointjack.com/2017/powershell-script-to-remove-duplicate-old-modules/

Regards,
@giampitz

**Comment by KarlGW** [comment]
Experiencing the same issues with a Hybid Worker. Have removed all previous Azure Modules and installed the latest ones, but working with the AzureRm-cmdlets against RecoveryServices still throws 'Newtonsoft.Json.Serialization.IAttributeProvider
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
