### ISSUE TITLE
Issue with Stream Analytics Cmdlets and Newtonsoft.Json

### ISSUE THREAD

**Issue by schwasam** [Azure/azure-powershell#5990]
### Description

Get-AzureRMStreamAnalyticsJob, Get-AzureRMStreamAnalyticsInput and Get-AzureRMStreamAnalyticsOutput do not work when used in the context of an Azure Automation Account.

### Script/Steps for Reproduction

```powershell
Workflow Test-StreamAnalyticsIO
{
    Param(
        [parameter(Mandatory=$True)]
        [string] $SubscriptionNameVariableName,

        [parameter(Mandatory=$True)]
        [string] $ResourceGroupNameVariableName
    )

    ###############################################################################
    # Constants (same for all environments)                                       #
    ###############################################################################

    $ADTenantId = "[AD Tenant Id]"

    ###############################################################################
    # Settings from Automation Account (different for each environment)           #
    ###############################################################################

    $AutomationAdminCredential = Get-AutomationPSCredential -Name "AutomationAdmin"

    # Get the subscription name from the Automation variable
    $SubscriptionName = Get-AutomationVariable -Name $SubscriptionNameVariableName
    If ($SubscriptionName -eq $null)
    {
        Throw "Could not retrieve '$SubscriptionNameVariableName' variable asset. Check that you created this first in the Automation service."
    }

    $ResourceGroupName = Get-AutomationVariable -Name $ResourceGroupNameVariableName
    If ($ResourceGroupName -eq $null)
    {
        Throw "Could not retrieve '$ResourceGroupNameVariableName' variable asset. Check that you created this first in the Automation service."
    }

    ###############################################################################
    # Test Stream Analytics Inputs and Outputs                                    #
    ###############################################################################

    # suppress output
    $null = Add-AzureRmAccount -SubscriptionName $SubscriptionName -TenantId $ADTenantId -Credential $AutomationAdminCredential

    ForEach -Parallel ($Job in Get-AzureRMStreamAnalyticsJob -ResourceGroupName $ResourceGroupName)
    { 
        ForEach($Input in Get-AzureRMStreamAnalyticsInput -ResourceGroupName $Job.ResourceGroupName -JobName $Job.JobName)
        {
            $InputResult = Test-AzureRMStreamAnalyticsInput -ResourceGroupName $Job.ResourceGroupName –JobName $Job.JobName –Name $Input.Name;
            Write-Output "Testing Job $($Job.JobName), Input $($Input.Name): $($InputResult)"
            
        }
        ForEach($Output in Get-AzureRMStreamAnalyticsOutput -ResourceGroupName $Job.ResourceGroupName -JobName $Job.JobName)
        {
            $OutputResult = Test-AzureRMStreamAnalyticsOutput -ResourceGroupName $Job.ResourceGroupName –JobName $Job.JobName –Name $Output.Name;
            Write-Output "Testing Job $($Job.JobName), Input $($Output.Name): $($OutputResult)"
        }
    }
}
```

### Module Version

AzureRM.Profile 4.6.0
AzureRM.StreamAnalytics 4.0.4

### Environment Data

```
Name                           Value                                                                                    
----                           -----                                                                                    
PSRemotingProtocolVersion      2.3                                                                                      
BuildVersion                   10.0.15063.726                                                                           
PSVersion                      5.1.15063.726                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
PSEdition                      Desktop                                                                                  
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
SerializationVersion           1.1.0.1 
```

### Debug Output

```
Get-AzureRMStreamAnalyticsJob : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
At Test-StreamAnalyticsIO:70 char:70
+ 
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStreamAnalyticsJob], MissingMethodException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.StreamAnalytics.GetAzureStreamAnalyticsJobCommand
 
5f4374ad-d464-47e0-a9ec-fa71324372ec:[localhost]:AzureQoSEvent: CommandName - Get-AzureRmStreamAnalyticsJob; IsSuccess 
- False; Duration - 00:00:02.7612497; Exception - System.MissingMethodException: Method not found: 
'Newtonsoft.Json.Serialization.IAttributeProvider Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
   at Microsoft.Rest.Serialization.JsonConverterHelper.IsJsonExtensionData(JsonProperty property)
   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, 
Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, 
JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, 
Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.PolymorphicDeserializeJsonConverter`1.ReadJson(JsonReader reader, Type objectType, 
Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, 
JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter 
propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object 
target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, 
JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, 
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, 
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type 
objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty 
containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, 
JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, 
JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type 
objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty 
containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, 
Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object 
existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, 
JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, 
JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, 
JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type 
objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty 
containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter 
propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object 
target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, 
JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, 
JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, 
Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type 
objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty 
containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, 
Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.StreamAnalytics.StreamingJobsOperations.<ListByResourceGroupWithHttpMessagesAsync>d__9.
MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at 
Microsoft.Azure.Management.StreamAnalytics.StreamingJobsOperationsExtensions.<ListByResourceGroupAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.StreamAnalytics.Models.StreamAnalyticsClient.ListJobs(String resourceGroupName, String 
propertiesToExpand)
   at Microsoft.Azure.Commands.StreamAnalytics.Models.StreamAnalyticsClient.FilterPSJobs(JobFilterOptions filterOptions)
   at Microsoft.Azure.Commands.StreamAnalytics.GetAzureStreamAnalyticsJobCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
```

**Comment by schwasam** [comment]
```
Name                                                         Version                                                    
----                                                         -------                                                    

Azure                                                        5.1.2                                                      

Azure.Storage                                                4.2.1                                                      

AzureAD                                                      2.0.0.155                                                  

AzureRM.Automation                                           4.3.2                                                      

AzureRM.Compute                                              4.6.0                                                      

AzureRM.IotHub                                               3.1.2                                                      

AzureRM.profile                                              4.6.0                                                      

AzureRM.Resources                                            5.5.2                                                      

AzureRM.ServiceBus                                           0.6.4                                                      

AzureRM.Sql                                                  4.4.0                                                      

AzureRM.Storage                                              4.2.3                                                      

AzureRM.StreamAnalytics                                      4.0.4                                                      

AzureRmStorageTable                                          1.0.0.21                                                   

Microsoft.PowerShell.Core                                    0.0                                                        

Microsoft.PowerShell.Diagnostics                             0.0                                                        

Microsoft.PowerShell.Management                              0.0                                                        

Microsoft.PowerShell.Security                                0.0                                                        

Microsoft.PowerShell.Utility                                 0.0                                                        

Microsoft.WSMan.Management                                   0.0                                                        

Orchestrator.AssetManagement.Cmdlets                         1.0                                                        

Microsoft.PowerShell.Operation.Validation                    1.0.1                                                      

PackageManagement                                            1.0.0.1                                                    

Pester                                                       3.4.0                                                      

PowerShellGet                                                1.0.0.1                                                    

PSReadline                                                   1.2                                                        

AppBackgroundTask                                            1.0.0.0                                                    

Appx                                                         2.0.0.0                                                    

BitsTransfer                                                 2.0.0.0                                                    

CimCmdlets                                                   1.0.0.0                                                    

Defender                                                     1.0                                                        

DeliveryOptimization                                         1.0.0.0                                                    

DirectAccessClientComponents                                 1.0.0.0                                                    

Dism                                                         3.0                                                        

DnsClient                                                    1.0.0.0                                                    

EventTracingManagement                                       1.0.0.0                                                    

International                                                2.0.0.0                                                    

iSCSI                                                        1.0.0.0                                                    

ISE                                                          1.0.0.0                                                    

Kds                                                          1.0.0.0                                                    

Microsoft.PowerShell.Archive                                 1.0.1.0                                                    

Microsoft.PowerShell.Diagnostics                             3.0.0.0                                                    

Microsoft.PowerShell.Host                                    3.0.0.0                                                    

Microsoft.PowerShell.LocalAccounts                           1.0.0.0                                                    

Microsoft.PowerShell.Management                              3.1.0.0                                                    

Microsoft.PowerShell.ODataUtils                              1.0                                                        

Microsoft.PowerShell.Security                                3.0.0.0                                                    

Microsoft.PowerShell.Utility                                 3.1.0.0                                                    

Microsoft.WSMan.Management                                   3.0.0.0                                                    

MMAgent                                                      1.0                                                        

MsDtc                                                        1.0.0.0                                                    

NetAdapter                                                   2.0.0.0                                                    

NetConnection                                                1.0.0.0                                                    

NetEventPacketCapture                                        1.0.0.0                                                    

NetLbfo                                                      2.0.0.0                                                    

NetNat                                                       1.0.0.0                                                    

NetQos                                                       2.0.0.0                                                    

NetSecurity                                                  2.0.0.0                                                    

NetSwitchTeam                                                1.0.0.0                                                    

NetTCPIP                                                     1.0.0.0                                                    

NetworkConnectivityStatus                                    1.0.0.0                                                    

NetworkSwitchManager                                         1.0.0.0                                                    

NetworkTransition                                            1.0.0.0                                                    

PcsvDevice                                                   1.0.0.0                                                    

PKI                                                          1.0.0.0                                                    

PnpDevice                                                    1.0.0.0                                                    

PrintManagement                                              1.1                                                        

Provisioning                                                 3.0                                                        

PSDesiredStateConfiguration                                  1.1                                                        

PSDiagnostics                                                1.0.0.0                                                    

PSScheduledJob                                               1.1.0.0                                                    

PSWorkflow                                                   2.0.0.0                                                    

PSWorkflowUtility                                            1.0.0.0                                                    

ScheduledTasks                                               1.0.0.0                                                    

SecureBoot                                                   2.0.0.0                                                    

SmbShare                                                     2.0.0.0                                                    

SmbWitness                                                   2.0.0.0                                                    

StartLayout                                                  1.0.0.0                                                    

Storage                                                      2.0.0.0                                                    

TLS                                                          2.0.0.0                                                    

TroubleshootingPack                                          1.0.0.0                                                    

TrustedPlatformModule                                        2.0.0.0                                                    

VpnClient                                                    2.0.0.0                                                    

Wdac                                                         1.0.0.0                                                    

WindowsDeveloperLicense                                      1.0.0.0                                                    

WindowsErrorReporting                                        1.0                                                        

WindowsSearch                                                1.0.0.0                                                    

WindowsUpdate                                                1.0.0.0 
```

**Comment by markcowl** [comment]
This is because the Automation executor automatically loads Newtonsoft.Json 6.0.5 in the AppDomain, which does not have some of the APIs exepcted.  The Automation team plans to deploy a new service executor that allows using the latest 6.x version of Newtonsoft.Json.

**Comment by asears** [comment]
We are experiencing this similar issue with Get-AzureRmDataLakeAnalyticsJob when transitioning to azure automation credentials.

```
Get-AzureRmDataLakeAnalyticsJob : Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'
```

@markcowl do you have any expectation when this would be resolved  in Automation or a workaround we can place in Runbook or on Hybrid Worker?

**Comment by KarlGW** [comment]
Running Add-AzureRmMetricAlert rules on app services also triggers this exception.

Have uninstalled all old Azure PowerShell modules, and installed the latest (`6.7.0`).

```
System.Management.Automation.PSInvalidOperationException: Exception type: MissingMethodException, 
                Message: Method not found: 'Newtonsoft.Json.Serialization.IAttributeProvider 
                Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'., Code: Null, Status code:Null, 
                Reason phrase: Null ---> System.MissingMethodException: Method not found: 
                'Newtonsoft.Json.Serialization.IAttributeProvider 
                Newtonsoft.Json.Serialization.JsonProperty.get_AttributeProvider()'.
````
