### ISSUE TITLE
New-AzureRmVmss : The value of parameter zoneBalance is invalid.

### ISSUE THREAD

**Issue by surlypants** [Azure/azure-powershell#6012]
previously functioning posh script (without reference to AZs) now returns:

New-AzureRmVmss : The value of parameter zoneBalance is invalid.

```
New-AzureRmVmss : The value of parameter zoneBalance is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter zoneBalance is invalid.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 0c8ab554-609f-4068-b17e-21b38446fcf6
At line:1 char:1
+ New-AzureRmVmss `
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVmss], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss
```

I've looked over the new docs here
https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones
and here
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesets/createorupdate

and have updated my posh modules.

Note: I am _not_ supplying -ZoneBalance 

relevant bits
```
$vmssConfig = New-AzureRmVmssConfig `
  -Location $location `
  -SkuName $vmSize `
  -SkuCapacity $vmssCount `
  -UpgradePolicyMode Automatic `
  -OverProvision $false

...

New-AzureRmVmss `
  -ResourceGroupName $RG `
  -Name "$vmssNamePrefix-vmss" `
  -VirtualMachineScaleSet $vmssConfig
```

**Comment by surlypants** [comment]
debug output

```
DEBUG: AzureQoSEvent: CommandName - New-AzureRmVmss; IsSuccess - False; Duration - 00:00:20.3404840; Exception -
Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: The value of parameter zoneBalance is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter zoneBalance is invalid.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : ffe9ab66-21ae-4770-8db0-6ba74429c752 ---> Microsoft.Rest.Azure.CloudException: The value of parameter
zoneBalance is invalid.
   at
Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at
Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.CreateOrUpdate(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSet parameters)
   at Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss.<ExecuteCmdlet>b__1_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 2:37:48 PM - NewAzureRmVmss end processing.
DEBUG: 2:37:48 PM - NewAzureRmVmss end processing.

```

**Comment by cormacpayne** [comment]
@surlypants Hey Robin, do you happen to know the last version of `AzureRM.Compute` that above command(s) worked for you, and what version you are currently using?

CC: @hyonholee @gatneil

**Comment by surlypants** [comment]
non-functional posh
```
Get-Module -ListAvailable -Name AzureRM.Compute |Select-Object Version

Version
-------
4.6.0
4.5.0
4.4.0
```

functional posh
```
Get-Module -ListAvailable -Name AzureRM.Compute |Select-Object Version

Version
-------
4.5.0
4.3.2
4.3.1
4.3.0
4.0.1
3.4.1
3.4.0
3.3.1
```


I believe this indicates the break was introduced in 4.6.0 (where the ZoneBalance parameter is introduced).

For those following along, the storage sku naming is also changed between 4.5.0 and 4.6.0.

**Comment by gatneil** [comment]
@surlypants could you share the REST API parts from the debug output?

**Comment by surlypants** [comment]
this was the tail of the debug JSON:

```
    "overprovision": false,
    "zoneBalance": false
  },
  "location": "my_region",
  "tags": {}
}
```

let me know if you need for me to capture the entire bit again.

**Comment by surlypants** [comment]
re-ran (with AzureRM.Compute 4.6.0)
complete (semi redacted) debug

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/-redacted-/resourceGroups/-redacted-/providers/Microsoft.Compute/virtualMachineScaleSets/-redacted-?api-version=2017-12-01

Headers:
x-ms-client-request-id        : -redacted-
accept-language               : en-US

Body:
{
  "sku": {
    "name": "Standard_DS3_v2_Promo",
    "capacity": 3
  },
  "properties": {
    "upgradePolicy": {
      "mode": "Automatic",
      "automaticOSUpgrade": false
    },
    "virtualMachineProfile": {
      "osProfile": {
        "computerNamePrefix": "-redacted-",
        "adminUsername": "-redacted-",
        "adminPassword": "-redacted-",
        "windowsConfiguration": {
          "provisionVMAgent": true,
          "enableAutomaticUpdates": false
        }
      },
      "storageProfile": {
        "imageReference": {
          "id": "/subscriptions/-redacted-/resourceGroups/-redacted-/providers/Microsoft.Compute/images/from_packer_vhd"
        },
        "osDisk": {
          "caching": "None",
          "writeAcceleratorEnabled": false,
          "createOption": "FromImage",
          "osType": "Windows",
          "managedDisk": {
            "storageAccountType": "Premium_LRS"
          }
        }
      },
      "networkProfile": {
        "networkInterfaceConfigurations": [
          {
            "name": "network-config",
            "properties": {
              "primary": true,
              "enableAcceleratedNetworking": true,
              "ipConfigurations": [
                {
                  "name": "-redacted-",
                  "properties": {
                    "subnet": {
                      "id": "/subscriptions/-redacted-/resourceGroups/-redacted-/providers/Microsoft.Network/virtualNetworks/-redacted-/subnets/-redacted-"
                    },
                    "primary": false,
                    "publicIPAddressConfiguration": {
                      "properties": {
                        "idleTimeoutInMinutes": 0
                      }
                    },
                    "loadBalancerBackendAddressPools": [
                      {
                        "id": "/subscriptions/-redacted-/resourceGroups/-redacted-/providers/Microsoft.Network/loadBalancers/-redacted-/backendAddressPools/-redacted-"
                      }
                    ],
                    "loadBalancerInboundNatPools": [
                      {
                        "id": "/subscriptions/-redacted-/resourceGroups/-redacted-/providers/Microsoft.Network/loadBalancers/-redacted-/inboundNatPools/rdp"
                      }
                    ]
                  }
                }
              ],
              "enableIPForwarding": false
            },
            "id": "True"
          }
        ]
      }
    },
    "overprovision": false,
    "zoneBalance": false
  },
  "location": "southcentralus",
  "tags": {}
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/CreateVMScaleSet3Min;39,Microsoft.Compute/CreateVMScaleSet30Min;199
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : -redacted-
x-ms-request-id               : -redacted-
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-correlation-request-id   : -redacted-
x-ms-routing-request-id       : EASTUS:20180425T125503Z:-redacted-
X-Content-Type-Options        : nosniff
Date                          : Wed, 25 Apr 2018 12:55:02 GMT

Body:
{
  "error": {
    "code": "InvalidParameter",
    "target": "zoneBalance",
    "message": "The value of parameter zoneBalance is invalid."
  }
}

DEBUG: AzureQoSEvent: CommandName - New-AzureRmVmss; IsSuccess - True; Duration - 00:00:11.1553314; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 7:55:04 AM - NewAzureRmVmss end processing.
DEBUG: 7:55:04 AM - NewAzureRmVmss end processing.

Confirm
The value of parameter zoneBalance is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter zoneBalance is invalid.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : -redacted-
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
New-AzureRmVmss : The value of parameter zoneBalance is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter zoneBalance is invalid.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : -redacted-
At line:1 char:1
+ New-AzureRmVmss `
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVmss], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss

DEBUG: AzureQoSEvent: CommandName - New-AzureRmVmss; IsSuccess - False; Duration - 00:00:11.1553314; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: The value of parameter zoneBalance is invalid.
ErrorCode: InvalidParameter
ErrorMessage: The value of parameter zoneBalance is invalid.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : -redacted- ---> Microsoft.Rest.Azure.CloudException: The value of parameter zoneBalance is invalid.
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.CreateOrUpdate(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSet parameters)
   at Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss.<ExecuteCmdlet>b__1_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 7:55:38 AM - NewAzureRmVmss end processing.
DEBUG: 7:55:38 AM - NewAzureRmVmss end processing.
```

**Comment by gatneil** [comment]
So, at the REST API level, any value is invalid for zoneBalance if one or zero zones are specified. So the REST API PUT above is invalid (since it doesn't specify zones but has a value for zoneBalance). I'll start discussions with the server-side folks, and we will address this. I'll post back here once fixed :)

**Comment by gatneil** [comment]
Actually, the fix for this has already been merged: https://github.com/Azure/azure-powershell/pull/5992. It should be in the next powershell release :)
