### ISSUE TITLE
new-azurermsubscription returning InternalServerError

### ISSUE THREAD

**Issue by ikiris04** [Azure/azure-powershell#6226]
### Description

new-azurermsubscription returns internalservererror

### Script/Steps for Reproduction

Follow the steps in the [documentation ](https://docs.microsoft.com/en-us/azure/azure-resource-manager/programmatically-create-subscription?tabs=rest)

I have tested this with account owner and a delegated account owner and with as simple as command as possible on my machine and cloud shell.

```
New-AzureRmSubscription -OfferType MS-AZR-0017P -Name "new sub" -EnrollmentAccountObjectId 77eb0955-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

### Module Version

```powershell
PS C:\> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.0.1      AzureRM
Script     5.7.0      AzureRM
Script     5.4.1      AzureRM
Script     5.1.1      AzureRM
Script     4.3.1      AzureRM
Script     4.2.0      AzureRM


```

### Environment Data

```powershell
PS C:\> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.16299.98
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.98
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Debug Output

```
PS C:\> $newSub=New-AzureRmSubscription -OfferType MS-AZR-0017P -Name $subname -EnrollmentAccountObjectId $enrollmentAccount.objectid -ownerobjectid $ownerObjectIds
DEBUG: 5:16:56 PM - NewAzureRmSubscription begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 5:16:56 PM - using account id 'azure-account-admin-xxxx@xxxx.onmicrosoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'azure-account-admin-xxx@xxx.onmicrosoft.com', environment: 'AzureCloud', tenant: <tenant>'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: dc063117-4323-4f0d-9981-5aa6179ca78b - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/<tenant>/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (8 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56:  - TokenCache: Deserialized 8 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 05/16/2018 00:16:56: dc063117-4323-4f0d-9981-5aa6179ca78b - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: dc063117-4323-4f0d-9981-5aa6179ca78b - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 05/16/2018 00:16:56: dc063117-4323-4f0d-9981-5aa6179ca78b - TokenCache: 53.3027700016667 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: dc063117-4323-4f0d-9981-5aa6179ca78b - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: dc063117-4323-4f0d-9981-5aa6179ca78b - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: <hash>
 Refresh Token Hash: <hash>
 Expiration Time: 05/16/2018 01:10:14 +00:00
 User Hash: <hash>

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: 47faa60a-a572-4167-b5c2-ea4eb0628987 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/<tenant>/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (8 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56:  - TokenCache: Deserialized 8 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 05/16/2018 00:16:56: 47faa60a-a572-4167-b5c2-ea4eb0628987 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: 47faa60a-a572-4167-b5c2-ea4eb0628987 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 05/16/2018 00:16:56: 47faa60a-a572-4167-b5c2-ea4eb0628987 - TokenCache: 53.3025531916667 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: 47faa60a-a572-4167-b5c2-ea4eb0628987 - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/16/2018 00:16:56: 47faa60a-a572-4167-b5c2-ea4eb0628987 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: <hash>
 Refresh Token Hash: <hash>
 Expiration Time: 05/16/2018 01:10:14 +00:00
 User Hash: <hash>

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/providers/Microsoft.Billing/enrollmentAccounts/<enrollmentaccountobjectid>/providers/Microsoft.Subscription/createSubscription?api-version=2018-03-01-preview

Headers:
x-ms-client-request-id        : f018825a-c0c3-4f82-8f7c-a6f5eb80a379
accept-language               : en-US

Body:
{
  "displayName": "<nameofsub>",
  "owners": [
    {
      "objectId": "9bad387c-fc8c-41b7-ade5-d7ff9c4eedf2"
    },
    {
      "objectId": "b0f6b659-6a03-4b41-b092-456bf6d7fecd"
    }
  ],
  "offerType": "MS-AZR-0017P"
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
InternalServerError

Headers:
Pragma                        : no-cache
api-supported-versions        : 2018-03-01-preview
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-failure-cause            : service
x-ms-ratelimit-remaining-tenant-resource-requests: 496
x-ms-request-id               : 0f69d740-2369-4279-b0ae-3150068f83bf
x-ms-correlation-request-id   : 0f69d740-2369-4279-b0ae-3150068f83bf
x-ms-routing-request-id       : FRANCECENTRAL:20180516T001741Z:0f69d740-2369-4279-b0ae-3150068f83bf
Connection                    : close
Cache-Control                 : no-cache
Date                          : Wed, 16 May 2018 00:17:41 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:


New-AzureRmSubscription : Operation returned an invalid status code 'InternalServerError'
At line:1 char:9
+ $newSub=New-AzureRmSubscription -OfferType MS-AZR-0017P -Name $subnam ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmSubscription], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Subscription.Cmdlets.NewAzureRmSubscription

DEBUG: AzureQoSEvent: CommandName - New-AzureRmSubscription; IsSuccess - False; Duration - 00:00:44.9653998; Exception - Microsoft.Azure.Management.Subscription.Models.ErrorResponseException: Operation returned an invalid
status code 'InternalServerError'
   at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperations.<BeginCreateSubscriptionInEnrollmentAccountWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperations.<CreateSubscriptionInEnrollmentAccountWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperationsExtensions.<CreateSubscriptionInEnrollmentAccountAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Subscription.SubscriptionFactoryOperationsExtensions.CreateSubscriptionInEnrollmentAccount(ISubscriptionFactoryOperations operations, String enrollmentAccountName,
SubscriptionCreationParameters body)
   at Microsoft.Azure.Commands.Subscription.Cmdlets.NewAzureRmSubscription.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 5:17:45 PM - NewAzureRmSubscription end processing.
DEBUG: 5:17:45 PM - NewAzureRmSubscription end processing.
PS C:\>
```

**Comment by cormacpayne** [comment]
@ms-premp @wilcobmsft hey guys, would you mind taking a look at this issue?

**Comment by ikiris04** [comment]
An observation. I also tried the preview “add subscription” blade in the portal and the task never finished.

**Comment by MaddyMicrosoft** [comment]
New-AzureRmSubscription is now a retired module. The modern equivalent is New-AzSubscription in Az.Subscription. If you can still get an InternalServerError on the current cmdlet please open a new issue.
