### ISSUE TITLE
Unable to deserialize the response

### ISSUE THREAD

**Issue by ToMakeSense** [Azure/azure-powershell#6261]
I have encountered this issue on VSTS for Azure resources deployment with azure PowerShell recently, the script doesn’t work for one resource group, but it works for others, strange.  It seemed the same issue as #5835 , I  tried the solution given in my local machine, it's not work for me.
```powershell
PS C:\WINDOWS\system32> Get-AzureRmIntegrationAccount -Name XXXXX -ResourceGroupName XXXXX
Get-AzureRmIntegrationAccount : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmIntegrationAccount -Name nok-ipaas-shared-we-iac-01 -Resou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmIntegrationAccount], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureIntegrationAccountCommand
```

**Comment by maddieclayton** [comment]
@ToMakeSense Can you give us the current modules you are running by giving us the output of "Get-Module -ListAvailable"?  It looks like some people were not seeing this issue anymore in AzureRM 6.0.1, so if you have not updated to 6.0.1 can you update and let me know if you still see this issue?

**Comment by ToMakeSense** [comment]
I had updated to the latest version
```powershell
PS C:\WINDOWS\system32> Get-Module -name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                 
---------- -------    ----                                ----------------                                                                                 
Script     6.0.1      AzureRM                                                                                                                              
Script     5.6.0      AzureRM                                                                                                                              
Script     5.1.1      AzureRM      
```

**Comment by maddieclayton** [comment]
@ToMakeSense Thanks for the confirmation.  Can you print the output of running ```Get-AzureRmIntegrationAccount``` as well as the output of Resolve-AzureRmError (run after you get this deserialization error).  This will help us narrow down where the error is coming from. Thanks!

**Comment by ToMakeSense** [comment]
```powershell
PS C:\WINDOWS\system32> Get-AzureRmIntegrationAccount
Get-AzureRmIntegrationAccount : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmIntegrationAccount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmIntegrationAccount], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureIntegrationAccountCommand
 

PS C:\WINDOWS\system32> Resolve-AzureRmError


   HistoryId: 2


Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperations.<ListBySubscriptionWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperationsExtensions.<ListBySubscriptionAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperationsExtensions.ListBySubscription(IIntegrationAccountsOperations operation
                 s, Nullable`1 top)
                    at Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureIntegrationAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzureRmIntegrationAccount}
Line           : Get-AzureRmIntegrationAccount
Position       : At line:1 char:1
                 + Get-AzureRmIntegrationAccount
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Error converting value "Basic" to type 'Microsoft.Azure.Management.Logic.Models.IntegrationAccountSkuName'. Path 'value[1].sku.name', line
                  1, position 562.
StackTrace     :    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer ser
                 ializer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type o
                 bjectType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, 
                 JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract co
                 ntract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, J
                 sonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, 
                 JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract co
                 ntract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, J
                 sonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, J
                 sonProperty containerProperty, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, Jso
                 nProperty member, Object existingValue, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, 
                 JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract co
                 ntract, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, J
                 sonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalCo
                 ntent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperations.<ListBySubscriptionWithHttpMessagesAsync>d__5.MoveNext()
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {Get-AzureRmIntegrationAccount}
Line           : Get-AzureRmIntegrationAccount
Position       : At line:1 char:1
                 + Get-AzureRmIntegrationAccount
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Requested value 'Basic' was not found.
StackTrace     :    at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
                    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
                    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
                    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer ser
                 ializer)
Exception      : System.ArgumentException
InvocationInfo : {Get-AzureRmIntegrationAccount}
Line           : Get-AzureRmIntegrationAccount
Position       : At line:1 char:1
                 + Get-AzureRmIntegrationAccount
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

PS C:\WINDOWS\system32> 
```

**Comment by maddieclayton** [comment]
@pankajsn @daviburg Can you take a look at this issue? Looks like an account with skuname "Basic" is being returned, but cannot be parsed because it is not one of the enum types (NotSpecified, Free, Standard).

**Comment by ToMakeSense** [comment]
@daviburg @pankajsn any feedback?

**Comment by ToMakeSense** [comment]
the latest version 6.3.0 is still not work on my machine, any updates on this?
```cmd
PS C:\Users\XXXXX> Get-AzureRmIntegrationAccount
Get-AzureRmIntegrationAccount : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmIntegrationAccount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmIntegrationAccount], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureIntegrationAccountCommand

PS C:\Users\XXXXX>  Resolve-AzureRmError


   HistoryId: 1


Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperations.<ListBySubscriptionWithHttpMessagesAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperationsExtensions.<ListBySubscriptionAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperationsExtensions.ListBySubscription(IIntegrationAccountsOperations operations, 
                 Nullable`1 top)
                    at Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureIntegrationAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Get-AzureRmIntegrationAccount}
Line           : Get-AzureRmIntegrationAccount
Position       : At line:1 char:1
                 + Get-AzureRmIntegrationAccount
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Error converting value "Basic" to type 'Microsoft.Azure.Management.Logic.Models.IntegrationAccountSkuName'. Path 'value[1].sku.name', line 1,
                  position 562.
StackTrace     :    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serial
                 izer)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type obje
                 ctType, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, Jso
                 nContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contr
                 act, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, Json
                 Property member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, Jso
                 nContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contr
                 act, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, Json
                 Property member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, Json
                 Property containerProperty, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonPr
                 operty member, Object existingValue, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, Jso
                 nContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contr
                 act, JsonProperty member, String id)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, Json
                 Property member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalConte
                 nt)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.Logic.IntegrationAccountsOperations.<ListBySubscriptionWithHttpMessagesAsync>d__5.MoveNext()
Exception      : Newtonsoft.Json.JsonSerializationException
InvocationInfo : {Get-AzureRmIntegrationAccount}
Line           : Get-AzureRmIntegrationAccount
Position       : At line:1 char:1
                 + Get-AzureRmIntegrationAccount
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

Message        : Requested value 'Basic' was not found.
StackTrace     :    at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
                    at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
                    at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
                    at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serial
                 izer)
Exception      : System.ArgumentException
InvocationInfo : {Get-AzureRmIntegrationAccount}
Line           : Get-AzureRmIntegrationAccount
Position       : At line:1 char:1
                 + Get-AzureRmIntegrationAccount
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

**Comment by felixmondelo** [comment]
Any updates on this error? I have the same error deploying schemas, maps, ...

**Comment by najgel** [comment]
We encountered the same problem and it still persists, a workaround seems to be to set the powershell version to 2.1.0

**Comment by ToMakeSense** [comment]
@najgel thanks for your workaround, it works for me.

PS: If you use the hosted agent pool, you can try "**Hosted VS2017**", "**Hosted**"is not working i without extra configration.

![image](https://user-images.githubusercontent.com/6244148/45473818-a0621900-b76a-11e8-9b0a-f1c21adb516a.png)

Log for version-2.1.0 with “Hosted” Agent pool
```log
2018-09-13T03:58:21.2074801Z ##[section]Starting: Upload maps & schemas into integration account
2018-09-13T03:58:21.2080738Z ==============================================================================
2018-09-13T03:58:21.2081103Z Task         : Azure PowerShell
2018-09-13T03:58:21.2081372Z Description  : Run a PowerShell script within an Azure environment
2018-09-13T03:58:21.2081555Z Version      : 2.0.12
2018-09-13T03:58:21.2081706Z Author       : Microsoft Corporation
2018-09-13T03:58:21.2081910Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
2018-09-13T03:58:21.2082124Z ==============================================================================
2018-09-13T03:58:27.7221833Z The list of available Azure modules:
2018-09-13T03:58:28.1398738Z 
2018-09-13T03:58:28.1399891Z Name  Version
2018-09-13T03:58:28.1400188Z ----  -------
2018-09-13T03:58:28.1400420Z Azure 3.5.0  
2018-09-13T03:58:28.1400594Z 
2018-09-13T03:58:28.1400747Z 
2018-09-13T03:58:28.1400970Z The list of available AzureRM modules:
2018-09-13T03:58:28.4924759Z ##[error]Neither the Azure module ('2.1.0') nor the AzureRM module ('2.1.0') was found. If the module was recently installed, retry after restarting the VSTS task agent.
2018-09-13T03:58:28.5277701Z ##[section]Finishing: Upload maps & schemas into integration account

```

**Comment by asaleh81** [comment]
I'm using PowerShell AzureRm 6.13.1 with basic integration account and Set-AzureRmIntegrationAccountSchema is erroring out. 

Set-AzureRmIntegrationAccountSchema : Unable to deserialize the response.
At C:\Workspace\sanmar\powershell\test-integration-account.ps1:20 char:1
+ Set-AzureRmIntegrationAccountSchema -ResourceGroupName $ResourceGroup ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmIntegrationAccountSchema], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.UpdateAzureIntegrationAccountSchemaCommand
 
DEBUG: AzureQoSEvent: CommandName - Set-AzureRmIntegrationAccountSchema; IsSuccess - False; Duration - 00:00:00.7113133; Exception - Microsoft.Rest.SerializationException: Unable to deserialize the respons
e_### **. ---> **Newtonsoft.Json.JsonSerializationException: Error converting value "Basic" to type 'Microsoft.Azure.Management.Logic.Models.IntegrationAccountSkuName'. Path 'sku.name', line 1, position 55. ---> Sy
stem.ArgumentException: Requested value 'Basic' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)****_
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProp
erty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonPr
operty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProp
erty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonPr
operty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Logic.IntegrationAccountsOperations.<GetWithHttpMessagesAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.Logic.IntegrationAccountsOperations.<GetWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.IntegrationAccountsOperationsExtensions.<GetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.IntegrationAccountsOperationsExtensions.Get(IIntegrationAccountsOperations operations, String resourceGroupName, String integrationAccountName)
   at Microsoft.Azure.Commands.LogicApp.Cmdlets.UpdateAzureIntegrationAccountSchemaCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:47:01 AM - UpdateAzureIntegrationAccountSchemaCommand end processing.
DEBUG: 1:47:01 AM - UpdateAzureIntegrationAccountSchemaCommand end processing.
DEBUG: 1:47:01 AM - GetAzureServiceBusKey begin processing with ParameterSet 'NamespaceAuthorizationRuleSet'.
DEBUG: 1:47:01 AM - using account id 'asaleh@stonedonut.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'asaleh@stonedonut.com', environment: 'AzureCloud', tenant: '7c5d5df7-38dc-4b8d-b84e-4c5697ddf810'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 02/28/2019 06:47:01: 5314af74-7703-4ea6-978e-b727502d3b5b - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/7c5d5df7-38dc-4b8d-b84e-4c5697ddf810/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (4 items)
	Authentication Target: User

**Comment by ToMakeSense** [comment]
Updates: the issue have been fixed on **Az** Module since **V-1.4.0**, but still existed in lastest **AzureRm(V-6.13.1)** module.

You can search with **"Basic"** key word to find it out in below reference links.
[Release notes of Az PoweShell module](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-2.1.0/release-notes-azureps.md)
[Release notes of AzureRm PoweShell module](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/release-notes-azureps.md)

**Comment by SahinOzdemir** [comment]
I have installed latest 6.13.1 AzureRM Module and the issue with Basic still persists. Any update on this?

**Comment by ToMakeSense** [comment]
> Updates: the issue has been fixed on **Az** Module since **V-1.4.0**, but still existed in lastest **AzureRm(V-6.13.1)** module.
> 
> You can search with **"Basic"** key word to find it out in below reference links.
> [Release notes of Az PoweShell module](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/release-notes-azureps.md)
> [Release notes of AzureRm PoweShell module](https://github.com/MicrosoftDocs/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/release-notes-azureps.md)

@SahinOzdemir see my comments above

**Comment by Ashish-Jovial** [comment]
Hi Team,

I am getting the same error, a couple of days ago, it was working fine but today as I tried to deploy, it has broken. I am pasting my error details below.

`[ERROR] Get-AzureRmDataFactoryV2Pipeline : Unable to deserialize the response.
[ERROR] At C:\Users\ashishjain06\source\repos\JMHAuditAzureAnalytics\JMHAuditAzureAnaly
[ERROR] tics\DataFactory\PowerShell\Delete-ADFPipelines.ps1:38 char:20
[ERROR] + ... lineNames = Get-AzureRmDataFactoryV2Pipeline -DataFactoryName $dataFa ...
[ERROR] +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ERROR]     + CategoryInfo          : CloseError: (:) [Get-AzureRmDataFactoryV2Pipelin 
[ERROR]    e], SerializationException
[ERROR]     + FullyQualifiedErrorId : Microsoft.Azure.Commands.DataFactoryV2.GetAzureD 
[ERROR]    ataFactoryPipelineCommand`

**Comment by tudorsibiu90** [comment]
we are also having this issue lately

**Comment by cdhakshinamoorthy** [comment]
@everyone We are facing the same 'Unable to deserialize the response' error in devops release pipeline task when executing a powershell script that fetches the build release number and clones the existing database.

**Comment by JackBruceShell** [comment]
Is there any resolution to this deserialization problem?

I am facing something similar now with the below

Get-AzWebApp -ResourceGroupName RG-XXX -Name LA-XXX).Id

Get-AzWebApp: /home/***/actions-runner/_work/_temp/5e6a3afc-64d0-43e5-a535-43ad6bd1ffbc.ps1:2
Line |
   2 |  … icappurl = (Get-AzWebApp -ResourceGroupName RG-XXX …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to deserialize the response.
Error: Process completed with exit code 1.
