### ISSUE TITLE
Get-AzureRmResource returns Get-AzureRmResource : Invalid format of the resource identifier. Parameter name: idFromServer on some resources

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-powershell#6300]
### Description

I am trying to use 

```powershell
Get-AzureRmResource -ResourceId "/subscriptions/3e8bd477-8247-4d77-9663-baed0a3fa254/providers/Microsoft.Advisor/recommendations"
```

To get list of Advisor recommendations but I get an error. This command was running fine wiht 5.X versions.

```powershell
Get-AzureRmResource : Invalid format of the resource identifier.
Parameter name: idFromServer
At line:1 char:1
+ Get-AzureRmResource -ResourceId "/subscriptions/3e8bd466-8247-4d77-96 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet
```

### Script/Steps for Reproduction

```powershell
Get-AzureRmResource -ResourceId "/subscriptions/3e8bd477-8247-4d77-9663-baed0a3fa254/providers/Microsoft.Advisor/recommendations"
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable

PS C:\WINDOWS\system32> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.0      AzureRM
```

### Environment Data

```powershell
$PSVersionTable
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.81
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.81
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

I've removed some values for privacy reasons

```
Get-AzureRmResource -ResourceId "/subscriptions/3e8bd477-8247-4d77-9663-baed0a3fa254/providers/Microsoft.Advisor/recommendations"
DEBUG: 9:38:14 - GetAzureResourceCmdlet begin processing with ParameterSet 'ByResourceId'.
DEBUG: 9:38:14 - using account id 'automation@mgmt.windowscloudservices.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: '', environment: 'AzureCloud', tenant: ''
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/25/2018 06:38:14:  - AcquireTokenHandlerBase: === Token Acquisition started:
        Authority: https://login.microsoftonline.com//
        Resource: https://management.core.windows.net/
        ClientId: 
        CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (31 items)
        Authentication Target: User


DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/25/2018 06:38:14:  - TokenCache: Deserialized 31 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 05/25/2018 06:38:14:  - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/25/2018 06:38:14:  TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 05/25/2018 06:38:14:  - TokenCache: 42.3750481433333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/25/2018 06:38:14:  - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 05/25/2018 06:38:14:  - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
        Access Token Hash: 
        Refresh Token Hash: 
        Expiration Time: 05/25/2018 07:20:36 +00:00
        User Hash:


Get-AzureRmResource : Invalid format of the resource identifier.
Parameter name: idFromServer
At line:1 char:1
+ Get-AzureRmResource -ResourceId "/subscriptions/3e8bd477-8247-4d77-96 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmResource], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmResource; IsSuccess - False; Duration - 00:00:00.0762421; Exception - System.ArgumentException: Invalid format of the resource identifier.
Parameter name: idFromServer
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Components.ResourceIdentifier..ctor(String idFromServer)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.GetById(String resourceId, String apiVersion)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceCmdlet.OnProcessRecord()
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 9:38:15 - GetAzureResourceCmdlet end processing.
DEBUG: 9:38:15 - GetAzureResourceCmdlet end processing.
```

**Comment by maddieclayton** [comment]
@cormacpayne Can you take a look at this issue?

**Comment by cormacpayne** [comment]
@slavizh Hey Stanislav, we made some changes to `Get-AzureRmResource` in the 6.0.0 release of Azure PowerShell. Would you mind using the `ResourceType` parameter to perform the desired action?

```powershell
Get-AzureRmResource -ResourceType Microsoft.Advisor/recommendations
```

**Comment by slavizh** [comment]
@cormacpayne  Hey Cormac, I've tried that option and it runs without error but unfortunately does not return results where with the previous command I am getting results. Any other options?

**Comment by cormacpayne** [comment]
@twitchax would you mind contacting the Advisor team and seeing what their plans are for supporting their service in .NET SDK and PowerShell?

**Comment by twitchax** [comment]
@cormacpayne, they are comitting to the work, but a firm date is not available yet.

**Comment by twitchax** [comment]
Closing in favor of #6467, and the fact that the previous behavior was a "spurious feature".

**Comment by corydwood** [comment]
I worked around this issue by replacing
```powershell
$backupItems | Disable-AzureRmRecoveryServicesBackupProtection -RemoveRecoveryPoints -Force
```
with
```powershell
Disable-AzureRmRecoveryServicesBackupProtection -Item $backupItems -RemoveRecoveryPoints -Force
```
though it would be nice to get the pipeline fixed since it was working in a previous version. It's still broken in version 6.9.0.
