### ISSUE TITLE
[CloudShell]: Investigate token expiry issues in CloudShell LRO

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#6328]
Some reports of token expiry in requests for long-runnign operations, as below:

- [ ] Obtain a repro of failed requests for this token expiry issue
- [ ] Add additional tracing as necessary to determine root cause
- [ ] Fix inline, or file issue for fix in next PowerShell release.

**Comment by edyoung** [comment]
This is not limited to long-running operations. I have been able to reproduce using a variety of azurerm.netcore commands, including Get-AzureRmResourceGroup. The cmdlet continues to present the same expired token when run multiple times, including tokens that expired more than 30 mins ago.

Below is a debug log from one execution.
```
PS Azure:\> Get-AzureRmResourceGroup -Name brywang*
DEBUG: >> MakePath([AzureRM.Resources.Netcore, Get-AzureRmResourceGroup])
DEBUG: << MakePath([AzureRM.Resources.Netcore, Get-AzureRmResourceGroup])
DEBUG: 11:50:29 PM - GetAzureResourceGroupCmdlet begin processing with ParameterSet 'GetByResourceGroupName'.
DEBUG: 11:50:29 PM - using account id '202a11ee-6fc8-4990-8960-1aaf4aad10fa'...
DEBUG: [Common.Authentication]: Authenticating using Account: '202a11ee-6fc8-4990-8960-1aaf4aad10fa', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=202a11ee-6fc8-4990-8960-1aaf4aad10fa&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/4b462a8b-b30d-450b-b924-633ae6190e66/resourcegroups?api-version=2017-05-10

Headers:
x-ms-client-request-id        : e77835f4-af51-4ff4-b592-658b923b5252
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Unauthorized

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
WWW-Authenticate              : Bearer authorization_uri="https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47", error="invalid_token", error_description="The access token has expired."
x-ms-failure-cause            : gateway
x-ms-request-id               : e823a67a-9181-441b-b02f-e90ea4a4b61c
x-ms-correlation-request-id   : e823a67a-9181-441b-b02f-e90ea4a4b61c
x-ms-routing-request-id       : WESTUS:20180618T235029Z:e823a67a-9181-441b-b02f-e90ea4a4b61c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Mon, 18 Jun 2018 23:50:28 GMT
Connection                    : close

Body:
{
  "error": {
    "code": "ExpiredAuthenticationToken",
    "message": "The access token expiry UTC time '6/18/2018 11:41:14 PM' is earlier than current UTC time '6/18/2018 11:50:29 PM'."
  }
}


Get-AzureRmResourceGroup : The access token expiry UTC time '6/18/2018 11:41:14 PM' is earlier than current UTC time '6/18/2018 11:50:29 PM'.
At line:1 char:1
+ Get-AzureRmResourceGroup -Name brywang*
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzureRmResourceGroup], CloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceGroupCmdlet

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmResourceGroup; IsSuccess - False; Duration - 00:00:00.0704684; Exception - Microsoft.Rest.Azure.CloudException: The access token expiry UTC time '6/18/2018 11:41:14 PM' is earlier than current UTC time '6/18/2018 11:50:29 PM'.
   at Microsoft.Azure.Management.ResourceManager.ResourceGroupsOperations.ListWithHttpMessagesAsync(ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.ResourceGroupsOperationsExtensions.ListAsync(IResourceGroupsOperations operations, ODataQuery`1 odataQuery, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.ResourceGroupsOperationsExtensions.List(IResourceGroupsOperations operations, ODataQuery`1 odataQuery)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkClient.ResourceManagerSdkClient.FilterResourceGroups(String name, Hashtable tag, Boolean detailed, String location)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceGroupCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:50:30 PM - GetAzureResourceGroupCmdlet end processing.
DEBUG: 11:50:30 PM - GetAzureResourceGroupCmdlet end processing.
```

**Comment by dhmorrison** [comment]
I can repo this in the _Azure Portal Cloud Shell:_

1. Execute a command without parameters
1. Provide input values as the system prompts for _required parameters_
1. Input a value that is not to the liking of the shell, perhaps it wants a single quoted parameter
1. Profit!  I"M _HORDING_ all the single quotes for my own use.  lol

```
cmdlet New-AzResourceGroupDeployment at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ResourceGroupName: sqlcloneprodrgrp
TemplateFile: azuredeploy.json
```

**BLAM!**  _Errors will be happening_ as more than one contractor has reported to me...
It would be super awesome if we can eliminate this, as I think we all get the promise of Azure resource group deployments.  IMO, it's pretty challenging to get them debugged and sorted out in the best circumstances.  Errors (false errors-can an error be true || false?) kind of add insult to injury.  Disrupts whatever little bit of flow I'm eking out.
______________
```
cmdlet New-AzResourceGroupDeployment at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
ResourceGroupName: sqlcloneprodrgrp
TemplateFile: azuredeploy.json
New-AzureRmResourceGroupDeployment : The access token expiry UTC time '1/21/2019 11:27:25 PM' is earlier than current UTC time '1/21/2019 11:32:17 PM'
At line:1 char:1
+ New-AzureRmResourceGroupDeployment
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzResourceGroupDeployment], CloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzureResourceGroupDeploymentCmdlet
```
______________

**Comment by nycbobby** [comment]
Please see the following link: https://docs.microsoft.com/en-us/azure/cloud-shell/limitations

It states the following: "Cloud Shell is intended for interactive use cases. As a result, any long-running non-interactive sessions are ended without warning."

This is not very intuitive considering Cloud Shell has an editor to write & save long script files which one would assume you could use for Azure VM deployments. I've had problems with this token expiring at random times. Sometimes 40 minutes after restarting Cloud Shell, sometimes 18 minutes.

The solution is to use Powershell from local PC and sign-in to Azure through the script-pane. Please see: https://www.jgspiers.com/how-to-connect-to-azure-powershell-arm-azuread
