### ISSUE TITLE
Get-AzureRmSchedulerJobCollection is throwing NullReferenceException

### ISSUE THREAD

**Issue by amoghnatu** [Azure/azure-powershell#6349]
### Description

Get-AzureRmSchedulerjobCollection cmdlet is throwing a NullReferenceException when trying to retrieve the scheduler job collection details.

```
PS C:\WINDOWS\system32> Get-AzureRmSchedulerJobCollection -JobCollectionName "MySchedulerJobCollectionNameHere" -ResourceGroupName "MySchedulerJobCollectionResourceGroupHere"
Get-AzureRmSchedulerJobCollection : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-AzureRmSchedulerJobCollection -JobCollectionName "MySchedulerJobColl ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmSchedulerJobCollection], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Scheduler.Cmdlets.GetAzureSchedulerJobCollectionCommand
 

PS C:\WINDOWS\system32> Resolve-AzureRmError -Last


   HistoryId: 4


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Scheduler.Utilities.Converter.ConvertJobCollectionDefinitionToPS(JobCollectionDefinition jobCollectionDefinition)
                    at Microsoft.Azure.Commands.Scheduler.Utilities.Converter.ConvertJobCollectionDefinitionListToPSList(IList`1 jobCollectionDefinitionList)
                    at Microsoft.Azure.Commands.Scheduler.Cmdlets.GetAzureSchedulerJobCollectionCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzureRmSchedulerJobCollection}
Line           : Get-AzureRmSchedulerJobCollection -JobCollectionName "MySchedulerJobCollectionNameHere" -ResourceGroupName "MySchedulerJobCollectionResourceGroupHere"
Position       : At line:1 char:1
                 + Get-AzureRmSchedulerJobCollection -JobCollectionName "MySchedulerJobColl ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4

```

I'm getting the exception AFTER receiving the HTTPResponse as seen from the debug stream screenshot below

![image](https://user-images.githubusercontent.com/2187662/40766478-3c84bc2a-64cd-11e8-84a1-d40674747529.png)

### Script/Steps for Reproduction

```powershell
Get-AzureRmSchedulerJobCollection -JobCollectionName "MySchedulerJobCollectionNameHere" -ResourceGroupName "MySchedulerJobCollectionResourceGroupHere"
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
PS C:\WINDOWS\system32> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                                   
---------- -------    ----                                ----------------                                                                                                                                   
Script     6.1.1      AzureRM                                                                                                                                                                                
Script     6.0.1      AzureRM 

```

### Environment Data

```powershell
PS C:\WINDOWS\system32> $PSVersionTable

Name                           Value                                                                                                                                                                         
----                           -----                                                                                                                                                                         
PSVersion                      5.1.16299.431                                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                       
BuildVersion                   10.0.16299.431                                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                           
SerializationVersion           1.1.0.1   

```

### Debug Output

```
PS C:\WINDOWS\system32> Get-AzureRmSchedulerJobCollection -JobCollectionName "MySchedulerJobCollectionNameHere" -ResourceGroupName "MySchedulerJobCollectionResourceGroupHere" -Debug
DEBUG: 11:56:12 AM - GetAzureSchedulerJobCollectionCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 11:56:14 AM - using account id 'myemailidhere@tenant.onmicrosoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'myemailidhere@tenant.onmicrosoft.com', environment: 'AzureCloud', tenant: 'bd3eeefe-e2f5-40d6-abc6-bbb9c8f48d03'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:14: 020268a8-b1a8-438b-80a4-48d6915c3682 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/bd3eeefe-e2f5-40d6-abc6-bbb9c8f48d03/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:14:  - TokenCache: Deserialized 4 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:14: 020268a8-b1a8-438b-80a4-48d6915c3682 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:14: 020268a8-b1a8-438b-80a4-48d6915c3682 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:14: 020268a8-b1a8-438b-80a4-48d6915c3682 - TokenCache: An expired or near expiry token was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:14: 020268a8-b1a8-438b-80a4-48d6915c3682 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:14: 020268a8-b1a8-438b-80a4-48d6915c3682 - <RefreshAccessTokenAsync>d__11: Refreshing access token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:15: 020268a8-b1a8-438b-80a4-48d6915c3682 - TokenCache: Storing token in the cache...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:15: 020268a8-b1a8-438b-80a4-48d6915c3682 - TokenCache: An item was stored in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 020268a8-b1a8-438b-80a4-48d6915c3682 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 6MNezefxKH6c79eVwUNwHakFxPOjcY7z9GsNeHTTbPg=
	Refresh Token Hash: h/c8PYYYRmjtnevYUN8qL9GF+iaR6SrPgTHjeiCTm5Y=
	Expiration Time: 05/31/2018 07:26:14 +00:00
	User Hash: 0suXSN4+jzoys3IwtT2eQMGZKAEMsP2Sr6heBKDuZDk=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15:  - TokenCache: Serializing token cache with 4 items.

DEBUG: [Common.Authentication]: Authenticating using Account: 'myemailidhere@tenant.onmicrosoft.com', environment: 'AzureCloud', tenant: 'bd3eeefe-e2f5-40d6-abc6-bbb9c8f48d03'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 16b5467e-0175-4184-9364-8040aec8c41f - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/bd3eeefe-e2f5-40d6-abc6-bbb9c8f48d03/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15:  - TokenCache: Deserialized 4 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:15: 16b5467e-0175-4184-9364-8040aec8c41f - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 16b5467e-0175-4184-9364-8040aec8c41f - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:15: 16b5467e-0175-4184-9364-8040aec8c41f - TokenCache: 59.9827116266667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 16b5467e-0175-4184-9364-8040aec8c41f - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 16b5467e-0175-4184-9364-8040aec8c41f - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 6MNezefxKH6c79eVwUNwHakFxPOjcY7z9GsNeHTTbPg=
	Refresh Token Hash: h/c8PYYYRmjtnevYUN8qL9GF+iaR6SrPgTHjeiCTm5Y=
	Expiration Time: 05/31/2018 07:26:14 +00:00
	User Hash: 0suXSN4+jzoys3IwtT2eQMGZKAEMsP2Sr6heBKDuZDk=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 981079c6-a5d0-4ebc-a445-1936ccde9dc3 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/bd3eeefe-e2f5-40d6-abc6-bbb9c8f48d03/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15:  - TokenCache: Deserialized 4 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:15: 981079c6-a5d0-4ebc-a445-1936ccde9dc3 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 981079c6-a5d0-4ebc-a445-1936ccde9dc3 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:15: 981079c6-a5d0-4ebc-a445-1936ccde9dc3 - TokenCache: 59.9826119083333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 981079c6-a5d0-4ebc-a445-1936ccde9dc3 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:15: 981079c6-a5d0-4ebc-a445-1936ccde9dc3 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 6MNezefxKH6c79eVwUNwHakFxPOjcY7z9GsNeHTTbPg=
	Refresh Token Hash: h/c8PYYYRmjtnevYUN8qL9GF+iaR6SrPgTHjeiCTm5Y=
	Expiration Time: 05/31/2018 07:26:14 +00:00
	User Hash: 0suXSN4+jzoys3IwtT2eQMGZKAEMsP2Sr6heBKDuZDk=
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/5ef79c0f-1020-44df-9a79-f8932f9ee94b/providers/Microsoft.Scheduler?api-version=2016-09-01

Headers:
x-ms-client-request-id        : edc87adc-5834-45bb-ae6d-18b0d51b8924
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 14999
x-ms-request-id               : 5c488b50-cb7b-4c87-ae7d-776c9f9ecd9b
x-ms-correlation-request-id   : 5c488b50-cb7b-4c87-ae7d-776c9f9ecd9b
x-ms-routing-request-id       : WESTINDIA:20180531T062615Z:5c488b50-cb7b-4c87-ae7d-776c9f9ecd9b
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 31 May 2018 06:26:14 GMT

Body:
{
  "id": "/subscriptions/5ef79c0f-1020-44df-9a79-f8932f9ee94b/providers/Microsoft.Scheduler",
  "namespace": "Microsoft.Scheduler",
  "resourceTypes": [
    {
      "resourceType": "jobcollections",
      "locations": [
        "North Central US",
        "South Central US",
        "North Europe",
        "West Europe",
        "East Asia",
        "Southeast Asia",
        "West US",
        "East US",
        "Japan West",
        "Japan East",
        "Brazil South",
        "Central US",
        "East US 2",
        "Australia East",
        "Australia Southeast",
        "South India",
        "Central India",
        "West India",
        "Canada Central",
        "Canada East",
        "West US 2",
        "West Central US",
        "UK South",
        "UK West",
        "Korea Central",
        "Korea South"
      ],
      "apiVersions": [
        "2016-03-01",
        "2016-01-01",
        "2014-08-01-preview"
      ],
      "capabilities": "CrossResourceGroupResourceMove, CrossSubscriptionResourceMove"
    },
    {
      "resourceType": "operations",
      "locations": [
        "North Central US",
        "South Central US",
        "North Europe",
        "West Europe",
        "East Asia",
        "Southeast Asia",
        "West US",
        "East US",
        "Japan West",
        "Japan East",
        "Brazil South",
        "Central US",
        "East US 2",
        "Australia East",
        "Australia Southeast",
        "South India",
        "Central India",
        "West India",
        "Canada Central",
        "Canada East",
        "West US 2",
        "West Central US",
        "UK South",
        "UK West",
        "Korea Central",
        "Korea South"
      ],
      "apiVersions": [
        "2016-03-01",
        "2016-01-01",
        "2014-08-01-preview"
      ]
    },
    {
      "resourceType": "operationResults",
      "locations": [
        "North Central US",
        "South Central US",
        "North Europe",
        "West Europe",
        "East Asia",
        "Southeast Asia",
        "West US",
        "East US",
        "Japan West",
        "Japan East",
        "Brazil South",
        "Central US",
        "East US 2",
        "Australia East",
        "Australia Southeast",
        "South India",
        "Central India",
        "West India",
        "Canada Central",
        "Canada East",
        "West US 2",
        "West Central US",
        "UK South",
        "UK West",
        "Korea Central",
        "Korea South"
      ],
      "apiVersions": [
        "2016-03-01",
        "2016-01-01",
        "2014-08-01-preview"
      ]
    },
    {
      "resourceType": "flows",
      "locations": [
        "North Central US",
        "Central US",
        "South Central US",
        "North Europe",
        "West Europe",
        "East Asia",
        "Southeast Asia",
        "West US",
        "East US",
        "East US 2",
        "Japan West",
        "Japan East",
        "Brazil South",
        "Australia East",
        "Australia Southeast"
      ],
      "apiVersions": [
        "2015-08-01-preview",
        "2015-02-01-preview"
      ],
      "capabilities": "CrossResourceGroupResourceMove, CrossSubscriptionResourceMove"
    }
  ],
  "registrationState": "Registered"
}


DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:16: 09f2999d-2805-4c02-94b7-83a8fc8f1ba3 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/bd3eeefe-e2f5-40d6-abc6-bbb9c8f48d03/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (4 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:16:  - TokenCache: Deserialized 4 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:16: 09f2999d-2805-4c02-94b7-83a8fc8f1ba3 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:16: 09f2999d-2805-4c02-94b7-83a8fc8f1ba3 - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 05/31/2018 06:26:16: 09f2999d-2805-4c02-94b7-83a8fc8f1ba3 - TokenCache: 59.97446555 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:16: 09f2999d-2805-4c02-94b7-83a8fc8f1ba3 - TokenCache: A matching item (access token or refresh token or both) was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 05/31/2018 06:26:16: 09f2999d-2805-4c02-94b7-83a8fc8f1ba3 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
	Access Token Hash: 6MNezefxKH6c79eVwUNwHakFxPOjcY7z9GsNeHTTbPg=
	Refresh Token Hash: h/c8PYYYRmjtnevYUN8qL9GF+iaR6SrPgTHjeiCTm5Y=
	Expiration Time: 05/31/2018 07:26:14 +00:00
	User Hash: 0suXSN4+jzoys3IwtT2eQMGZKAEMsP2Sr6heBKDuZDk=
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/5ef79c0f-1020-44df-9a79-f8932f9ee94b/resourceGroups/MySchedulerJobCollectionResourceGroupHere/providers/Microsoft.Scheduler/jobCollections/MySchedulerJobCollectionNameHere?api-version=
2016-03-01

Headers:
x-ms-client-request-id        : fa02c4c1-101f-4710-b970-a8ac4edf5f39
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-burst-remaining-scheduler-reads: 249
x-ms-request-id               : 746dc49b-9b21-4827-9261-e6682d1dc451
x-ms-ratelimit-remaining-subscription-reads: 14997
x-ms-correlation-request-id   : 289df229-a8aa-4271-a58c-c13faef5e997
x-ms-routing-request-id       : WESTINDIA:20180531T062617Z:289df229-a8aa-4271-a58c-c13faef5e997
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 31 May 2018 06:26:17 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/5ef79c0f-1020-44df-9a79-f8932f9ee94b/resourceGroups/MySchedulerJobCollectionResourceGroupHere/providers/Microsoft.Scheduler/jobCollections/MySchedulerJobCollectionNameHere",
  "type": "Microsoft.Scheduler/jobCollections",
  "name": "MySchedulerJobCollectionNameHere",
  "location": "North Europe",
  "properties": {
    "sku": {
      "name": "Standard"
    },
    "state": "Enabled"
  }
}


Get-AzureRmSchedulerJobCollection : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-AzureRmSchedulerJobCollection -JobCollectionName "MAHSBC-SCH-0001 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmSchedulerJobCollection], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Scheduler.Cmdlets.GetAzureSchedulerJobCollectionCommand
 
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmSchedulerJobCollection; IsSuccess - False; Duration - 00:00:30.0732484; Exception - System.NullReferenceException: Object reference not set to an instance of a
n object.
   at Microsoft.Azure.Commands.Scheduler.Utilities.Converter.ConvertJobCollectionDefinitionToPS(JobCollectionDefinition jobCollectionDefinition)
   at Microsoft.Azure.Commands.Scheduler.Utilities.Converter.ConvertJobCollectionDefinitionListToPSList(IList`1 jobCollectionDefinitionList)
   at Microsoft.Azure.Commands.Scheduler.Cmdlets.GetAzureSchedulerJobCollectionCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:56:43 AM - GetAzureSchedulerJobCollectionCommand end processing.
DEBUG: 11:56:43 AM - GetAzureSchedulerJobCollectionCommand end processing.
```

Please let me know if any more information is required.

**Comment by maddieclayton** [comment]
@derek1ee Can you take a look at this issue?

**Comment by cormacpayne** [comment]
Closing as the Scheduler module no longer ships with `Az`.
