### ISSUE TITLE
New-AzureRmRoleDefinition throws error, "Cannot deserialize the current JSON array"

### ISSUE THREAD

**Issue by praveendhac** [Azure/azure-powershell#6350]
### Issue Description
Issue is seen on Azure cloud Powershell provided on Azure Portal.
```Executing custom role creation command throws trace/exception.
PS Azure:> New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"
`New-AzureRmRoleDefinition : Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition' because the type requires a JSON object (e.g.
{"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be
deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
At line:1 char:1

New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"
  + CategoryInfo          : CloseError: (:) [New-AzureRmRoleDefinition], JsonSerializationException
  + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand

Azure:
PS Azure:>```

<!--
If this issue is a bug report:
- Upgrade to the latest version of AzureRM and verify you are able to reproduce the issue
    - You can install the latest version of AzureRM from the PowerShell Gallery
        - https://www.powershellgallery.com/packages/AzureRM
    - You can also install the latest version from the Releases section
        - https://github.com/Azure/azure-powershell/releases
- Ensure that you repro the issue with $DebugPreference = "Continue" to receive the debug stream
- If this bug involves an exception being thrown, please run Resolve-AzureRmError to receive extended information on the error
- Fill out the below template

If this issue is not a bug report, please remove the below template

-->

### Description

<!-- Please provide a description of the issue you are facing -->

### Script/Steps for Reproduction

<!-- Please provide the necessary script(s) that reproduce the issue -->
Execute New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"
```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
    Directory: C:\Program Files\WindowsPowerShell\Modules
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.0      AzureRM
### Environment Data

```powershell
$PSVersionTable
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.2248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### Debug Output

```
PS Azure:\> New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"
DEBUG: >> MakePath([AzureRM.Resources, New-AzureRmRoleDefinition])
DEBUG: << MakePath([AzureRM.Resources, New-AzureRmRoleDefinition])
DEBUG: 10:19:25 AM - NewAzureRoleDefinitionCommand begin processing with ParameterSet 'InputFileParameterSet'.
DEBUG: 10:19:25 AM - using account id '1111-2222-3333-4444'...
New-AzureRmRoleDefinition : Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition' because the type requires a JSON object (e.g.
{"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be
deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
At line:1 char:1
+ New-AzureRmRoleDefinition -InputFile "C:\Users\prav_devops_provisioning.json"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleDefinition], JsonSerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand

DEBUG: AzureQoSEvent: CommandName - New-AzureRmRoleDefinition; IsSuccess - False; Duration - 00:00:00.0325537; Exception - Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into
 type 'Microsoft.Azure.Commands.Resources.Models.Authorization.PSRoleDefinition' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be
deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(JsonReader reader, Type objectType, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:19:27 AM - NewAzureRoleDefinitionCommand end processing.
DEBUG: 10:19:27 AM - NewAzureRoleDefinitionCommand end processing.
```

```powershell
PS Azure:> cat C:\Users\prav_devops_provisioning.json
```

```json
[
{
"assignableScopes": [
""/subscriptions/111-222-333-444/resourceGroups/prav-/providers/Microsoft.ContainerRegistry/registries/prav-/providers/Microsoft.Authorization/roleAssignments/""
],
"description": "DevOps",
"name": "prav-DevOps",
"id": null,
"iscustom": true,
"permissions": [
{
"actions": [
"Microsoft.Authorization/roleAssignments/write",
"Microsoft.Authorization/roleAssignments/delete"
],
"dataActions": [],
"notActions": [
"Microsoft.Authorization//Delete",
"Microsoft.Authorization/*/Write",
"Microsoft.Authorization/elevateAccess/Action"
],
"notDataActions": []
}
],
"roleName": "prav-DevOps"
}
]
Azure:
PS Azure:>
`

**Comment by markcowl** [comment]
@praveendhac So, I think the issue is that your json file is presenting an array and it needs to present a definition object - can you try removing the outer brackets ```[]```

**Comment by praveendhac** [comment]
Below is the error after removing outer [], also tried with one action instead of two and still get below error.
```"actions": [
"Microsoft.Authorization/roleAssignments/write"
]```

Log
```Azure:\
PS Azure:\> $DebugPreference = "Continue"
Azure:\
PS Azure:\> New-AzureRmRoleDefinition -InputFile "C:\devops.json"
DEBUG: >> MakePath([AzureRM.Resources, New-AzureRmRoleDefinition])
DEBUG: << MakePath([AzureRM.Resources, New-AzureRmRoleDefinition])
DEBUG: 11:50:30 AM - NewAzureRoleDefinitionCommand begin processing with ParameterSet 'InputFileParameterSet'.
DEBUG: 11:50:30 AM - using account id '5c977ba4-b7a8-4d79-bf45-53e977f97e60'...
DEBUG: [Common.Authentication]: Authenticating using Account: '5c977ba4-b7a8-4d79-bf45-53e977f97e60', environment: 'AzureCloud', tenant: 'f373c3b4-4541-46c0-8835-f782346094b0'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: [Common.Authentication]: Authenticating using Account: '5c977ba4-b7a8-4d79-bf45-53e977f97e60', environment: 'AzureCloud', tenant: 'f373c3b4-4541-46c0-8835-f782346094b0'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
New-AzureRmRoleDefinition : Invalid value for Actions
At line:1 char:1
+ New-AzureRmRoleDefinition -InputFile "C:\devops.json"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmRoleDefinition], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand

DEBUG: AzureQoSEvent: CommandName - New-AzureRmRoleDefinition; IsSuccess - False; Duration - 00:00:00.0196498; Exception - System.ArgumentException: Invalid value for Actions
   at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.ValidateRoleDefinition(PSRoleDefinition roleDefinition)
   at Microsoft.Azure.Commands.Resources.Models.Authorization.AuthorizationClient.CreateRoleDefinition(PSRoleDefinition roleDefinition)
   at Microsoft.Azure.Commands.Resources.NewAzureRoleDefinitionCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:50:31 AM - NewAzureRoleDefinitionCommand end processing.
DEBUG: 11:50:31 AM - NewAzureRoleDefinitionCommand end processing.
Azure:\
PS Azure:\>```

**Comment by praveendhac** [comment]
"actions": [
                                "Microsoft.Authorization/roleAssignments/*"
],

DEBUG: AzureQoSEvent: CommandName - New-AzureRmRoleDefinition; IsSuccess - False; Duration - 00:00:00.0095130; Exception - System.ArgumentException: Invalid value for Actions

**Comment by praveendhac** [comment]
closed the issue by mistake.

**Comment by markcowl** [comment]
@darshanhs90 @cormacpayne Can you take a look?

**Comment by darshanhs90** [comment]
@praveendhac The attribute name is case sensitive and it should be **Actions**
