### ISSUE TITLE
webapp:New-AzureRmAppServicePlan does not parse Region/Location correctly when deploying with AppServiceEnvironment

### ISSUE THREAD

**Issue by blueelvis** [Azure/azure-powershell#6504]
### Description

The commandlet `New-AzureRmAppServicePlan` does not accept Locations like `eastus`,'eastus2` but accepts locations like `East US`, `East US 2` only. It should accept both of them. I believe this is a problem at the API because I seem to face this issue even when deploying via ARM templates.

### Script/Steps for Reproduction

1. Ensure that you have an App Service Environment created already. Ensure that this is a brand new ASE and no App Service Plan already exists in it.
2. Use the following command and replace values accordingling.

```powershell
New-AzureRmAppServicePlan -Location "eastus" -Tier "Isolated" -AseName "TEST-ASE" -AseResourceGroupName "TEST-ASE" -Name "Test" -ResourceGroupName "tests00"
```

### Module Version

```powershell
PS C:\Users\Pranav> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                           
---------- -------    ----                                ----------------                                                           
Script     5.7.0      AzureRM                                                                                                        
Script     5.6.0      AzureRM       ```

### Environment Data

<!-- Please run $PSVersionTable to get the necessary environment data -->

```powershell
PS C:\Users\Pranav> $PSVersionTable

Name                           Value                                                                                                 
----                           -----                                                                                                 
PSVersion                      5.1.17134.48                                                                                          
PSEdition                      Desktop                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   10.0.17134.48                                                                                         
CLRVersion                     4.0.30319.42000                                                                                       
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1                                                                                               

```

### Debug Output
When location is set to "eastus"
```
PS C:\> New-AzureRmAppServicePlan -Location "eastus" -Tier "Isolated" -AseName "XZE-PD-ASE-02" -AseResourceGroupName "XZE-PD-ASE-01" -Name "Test" -ResourceGroupName "xze-i-n-tests00-s-rgp-01" -Debug
DEBUG: 11:37:09 AM - NewAzureAppServicePlanCmdlet begin processing with ParameterSet 'S1'.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
DEBUG: 11:37:11 AM - using account id '6e2d74e3-8ec9-4a53-9463-53bf6cf36596'...
DEBUG: [Common.Authentication]: Authenticating using Account: '6e2d74e3-8ec9-4a53-9463-53bf6cf36596', environment: 'AzureCloud', tenant: '2dfc6a32-d03c-4504-8d69-f08da326f294'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https://management.core.windows.net/&client_id=6e2d74e3-8ec9-4a53-9463-53bf6cf36596&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/66d477ee-6241-4568-9e3f-d533bd3a8953/resourceGroups/xze-i-n-tests00-s-rgp-01/providers/Microsoft.Web/serverfarms/Test?api-version=2016-09-01

Headers:
x-ms-client-request-id        : 33d18866-da91-41a8-833d-a499c8a36460
accept-language               : en-US

Body:
{
  "properties": {
    "name": "Test",
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/66d477ee-6241-4568-9e3f-d533bd3a8953/resourcegroups/XZE-PD-ASE-01/providers/Microsoft.Web/hostingEnvironments/XZE-PD-ASE-02"
    },
    "perSiteScaling": false
  },
  "sku": {
    "name": "I1",
    "tier": "Isolated",
    "capacity": 1
  },
  "location": "eastus"
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Created

Headers:
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 1685b711-2587-4b3a-a967-572b4845c05d
x-ms-ratelimit-remaining-subscription-writes: 1198
x-ms-correlation-request-id   : b6ffc8b4-9d49-4af0-8541-5666c8173f2c
x-ms-routing-request-id       : EASTUS:20180621T113714Z:b6ffc8b4-9d49-4af0-8541-5666c8173f2c
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 21 Jun 2018 11:37:13 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/66d477ee-6241-4568-9e3f-d533bd3a8953/resourceGroups/xze-i-n-tests00-s-rgp-01/providers/Microsoft.Web/serverfarms/Test",
  "name": "Test",
  "type": "Microsoft.Web/serverfarms",
  "kind": "app",
  "location": "East US",
  "properties": {
    "serverFarmId": 2,
    "name": "Test",
    "workerSize": "Default",
    "workerSizeId": 0,
    "workerTierName": null,
    "numberOfWorkers": 1,
    "currentWorkerSize": "Default",
    "currentWorkerSizeId": 0,
    "currentNumberOfWorkers": 1,
    "status": "Ready",
    "webSpace": "xze-i-n-tests00-s-rgp-01-XZE-PD-ASE-02appseEastUSwebspace",
    "subscription": "66d477ee-6241-4568-9e3f-d533bd3a8953",
    "adminSiteName": null,
    "hostingEnvironment": "XZE-PD-ASE-02",
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/66d477ee-6241-4568-9e3f-d533bd3a8953/resourceGroups/XZE-PD-ASE-01/providers/Microsoft.Web/hostingEnvironments/XZE-PD-ASE-02",
      "name": "XZE-PD-ASE-02",
      "type": "Microsoft.Web/hostingEnvironments"
    },
    "maximumNumberOfWorkers": 100,
    "planName": "VirtualDedicatedPlan",
    "adminRuntimeSiteName": null,
    "computeMode": "Dedicated",
    "siteMode": null,
    "geoRegion": "East US",
    "perSiteScaling": false,
    "numberOfSites": 0,
    "hostingEnvironmentId": "/subscriptions/66d477ee-6241-4568-9e3f-d533bd3a8953/resourceGroups/XZE-PD-ASE-01/providers/Microsoft.Web/hostingEnvironments/XZE-PD-ASE-02",
    "isSpot": false,
    "spotExpirationTime": null,
    "freeOfferExpirationTime": null,
    "tags": null,
    "kind": "app",
    "resourceGroup": "xze-i-n-tests00-s-rgp-01",
    "reserved": false,
    "isXenon": false,
    "mdmId": "waws-prod-blu-ca0a4a1a_2",
    "targetWorkerCount": 0,
    "targetWorkerSizeId": 0,
    "provisioningState": "Succeeded",
    "webSiteId": null
  },
  "sku": {
    "name": "I1",
    "tier": "Isolated",
    "size": "I1",
    "family": "I",
    "capacity": 1
  }
}


Confirm
Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
New-AzureRmAppServicePlan : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
At line:1 char:1
+ New-AzureRmAppServicePlan -Location "eastus" -Tier "Isolated" -AseNam ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmAppServicePlan], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet

DEBUG: AzureQoSEvent: CommandName - New-AzureRmAppServicePlan; IsSuccess - False; Duration - 00:00:08.4224035; Exception - Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperationsExtensions.CreateOrUpdate(IAppServicePlansOperations operations, String resourceGroupName, String name, AppServicePlan appServicePlan)
   at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.CreateAppServicePlan(String resourceGroupName, String appServicePlanName, String location, String adminSiteName, SkuDescription sku, String aseName, String
aseResourceGroupName, Nullable`1 perSiteScaling)
   at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.NewAzureAppServicePlanCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:37:18 AM - NewAzureAppServicePlanCmdlet end processing.
DEBUG: 11:37:18 AM - NewAzureAppServicePlanCmdlet end processing.
```

**Comment by vladimir-shcherbakov** [comment]
@blueelvis 
To avoid issues with the hard-coded parameter value. please use one of the following approaches:
* In the **interactive mode** you may want to use the [tab completer feature](https://github.com/Azure/azure-powershell/blob/ec67339da182e82bfab7fc0cadadbb3700f1e2a3/src/ResourceManager/Websites/Commands.Websites/Cmdlets/AppServicePlans/NewAzureAppServicePlan.cs#L33) to iterate through available location:
```Powershell
New-AzureRmAppServicePlan -Location <Hit tab key here>
```
* In the script mode  - request available location for a resource type and select the most suitable:
```Powershell
$provider = Get-AzureRmResourceProvider -ProviderNamespace Microsoft.Web
$locations = $provider.ResourceTypes.Where{($_.ResourceTypeName -eq 'serverfarms')}.Locations
$myLocation = $locations | Where { $_ -like "*West U*"} | Select-Object -first 1
```

**Comment by blueelvis** [comment]
@vladimir-shcherbakov - I am facing issue with the ARM Templates as well in this case. Specifying `eastus` or `East US` should work right?

**Comment by blueelvis** [comment]
@vladimir-shcherbakov - Any update on this?

**Comment by vladimir-shcherbakov** [comment]
@blueelvis 
You know that location "eastus" doesn't work for you but "East US" works fine. Why is it so important for  you to use "eastus" and not "East US"?

**Comment by blueelvis** [comment]
@vladimir-shcherbakov - It is because of the following reasons -

1. I have scripts and configuration data using "eastus" which is centrally stored. Each deployment script takes into account this region. I can add the "East US" region but it would be quite a lot of work and testing.
2. It works with all the other deployment to Azure services but not this. 
3. If a customer is using ASE's (which are costly) then why not fix the service to make it similar in consumption like others?

**Comment by panchagnula** [comment]
@blueelvis is this still an issue ? can you please try with the latest version of Az commands let us know if this still an issue, especially since this not an issue with the commandlet but the API. Thank you.

**Comment by blueelvis** [comment]
@panchagnula - Sure thing. Let me test it out and get back to you.
