### ISSUE TITLE
Connect-azurermaccount fails to login to azure

### ISSUE THREAD

**Issue by whiggs** [Azure/azure-powershell#6534]
### Description

Attempting to authenticate to azure using "Connect-azurermaccount" fails.

```powershell
Connect-azurermaccount
```

### Module Version

```powershell

    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                           
---------- -------    ----                                ----------------                                           
Script     6.3.0      AzureRM                                                                                        


```

### Environment Data

```powershell
Name                           Value                                                                                 
----                           -----                                                                                 
PSVersion                      5.1.16299.492                                                                         
PSEdition                      Desktop                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                               
BuildVersion                   10.0.16299.492                                                                        
CLRVersion                     4.0.30319.42000                                                                       
WSManStackVersion              3.0                                                                                   
PSRemotingProtocolVersion      2.3                                                                                   
SerializationVersion           1.1.0.1                   
```

### Debug Output

```
PS C:\Windows\system32> $DebugPreference = "Continue"
Connect-AzureRmAccount
DEBUG: 1:00:13 AM - ConnectAzureRmAccountCommand begin processing with ParameterSet 'UserWithSubscriptionId'.
DEBUG: 1:00:13 AM - Autosave setting from startup session: 'CurrentUser'
DEBUG: 1:00:13 AM - No autosave setting detected in environment variable 'AzureRmContextAutoSave'. 
DEBUG: 1:00:13 AM - Using Autosave scope 'CurrentUser'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'Common', Endpoint: 'https://login.
microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', 
ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/Common
/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'Common', AdEndpoint: 'https://lo
gin.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:
oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 06/26/2018 05:00:13: 5ff2b104-8c9b-4df9-81e0-50568e49ba71 - AcquireTokenHandlerBase: === Token Acquisition star
ted:
	Authority: https://login.microsoftonline.com/Common/
	Resource: https://management.core.windows.net/
	ClientId: a string here
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (0 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/26/2018 05:00:13:  - WindowsFormsWebAuthenticationDialogBase: Navigating to 'https://login.microsoftonline.c
om/Common/oauth2/authorize?resource=https://management.core.windows.net/&client_id=1950a258-227b-4e31-a9cf-717495945fc
2&response_type=code&haschrome=1&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client-request-id=5ff2b104-8c9b-4df9-81e0-5056
8e49ba71&prompt=login&x-client-SKU=.NET&x-client-Ver=2.28.3.860&x-client-CPU=x64&x-client-OS=Microsoft Windows NT 10.0
.16299.0&site_id=501358&display=popup'.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/26/2018 05:00:13:  - WindowsFormsWebAuthenticationDialogBase: Navigated to 'https://login.microsoftonline.co
m/Common/oauth2/authorize?resource=https://management.core.windows.net/&client_id=1950a258-227b-4e31-a9cf-717495945fc2
&response_type=code&haschrome=1&redirect_uri=urn:ietf:wg:oauth:2.0:oob&client-request-id=5ff2b104-8c9b-4df9-81e0-50568
e49ba71&prompt=login&x-client-SKU=.NET&x-client-Ver=2.28.3.860&x-client-CPU=x64&x-client-OS=Microsoft Windows NT 10.0.
16299.0&site_id=501358&display=popup'.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/26/2018 05:00:31:  - WindowsFormsWebAuthenticationDialogBase: Navigating to 'https://login.microsoftonline.c
om/common/login'.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/26/2018 05:00:31:  - WindowsFormsWebAuthenticationDialogBase: WebBrowser state: IsBusy: True, ReadyState: Co
mplete, Created: True, Disposing: False, IsDisposed: False, IsOffline: False

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 06/26/2018 05:00:31:  - WindowsFormsWebAuthenticationDialogBase: WebBrowser state (after Stop): IsBusy: False, 
ReadyState: Complete, Created: True, Disposing: False, IsDisposed: False, IsOffline: False

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Error: 4 : 
DEBUG: 06/26/2018 05:00:32: 5ff2b104-8c9b-4df9-81e0-50568e49ba71 - <RunAsync>d__0: Microsoft.IdentityModel.Clients.Act
iveDirectory.AdalServiceException: AADSTS70002: Error validating credentials. AADSTS80005: Validation encountered unpr
edictable WebException
Trace ID: 2b81db94-4800-4092-a157-75559f180100
Correlation ID: 5ff2b104-8c9b-4df9-81e0-50568e49ba71
Timestamp: 2018-06-26 05:00:31Z
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.VerifyAuthorizationResult()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenInteractiveHandler.PreTokenRequest()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__0.MoveNext()
	ErrorCode: invalid_client
	StatusCode: 0

Connect-AzureRmAccount : AADSTS70002: Error validating credentials. AADSTS80005: Validation encountered 
unpredictable WebException
Trace ID: 2b81db94-4800-4092-a157-75559f180100
Correlation ID: 5ff2b104-8c9b-4df9-81e0-50568e49ba71
Timestamp: 2018-06-26 05:00:31Z
At line:2 char:1
+ Connect-AzureRmAccount
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzureRmAccount], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
 
DEBUG: AzureQoSEvent: CommandName - Connect-AzureRmAccount; IsSuccess - False; Duration - 00:00:18.6441931; Exception 
- Microsoft.Azure.Commands.Common.Authentication.AadAuthenticationFailedException: AADSTS70002: Error validating crede
ntials. AADSTS80005: Validation encountered unpredictable WebException
Trace ID: 2b81db94-4800-4092-a157-75559f180100
Correlation ID: 5ff2b104-8c9b-4df9-81e0-50568e49ba71
Timestamp: 2018-06-26 05:00:31Z ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS70002
: Error validating credentials. AADSTS80005: Validation encountered unpredictable WebException
Trace ID: 2b81db94-4800-4092-a157-75559f180100
Correlation ID: 5ff2b104-8c9b-4df9-81e0-50568e49ba71
Timestamp: 2018-06-26 05:00:31Z
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.DoAcquireToken(AdalConfiguration config, Prompt
Behavior promptBehavior, Action`1 promptAction, String userId, SecureString password)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.SafeAquireToken(AdalConfiguration config, Strin
g showDialog, Action`1 promptAction, String userId, SecureString password, Exception& ex)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.AcquireToken(AdalConfiguration config, String p
romptBehavior, Action`1 promptAction, String userId, SecureString password)
   at Microsoft.Azure.Commands.Common.Authentication.UserTokenProvider.GetAccessToken(AdalConfiguration config, String
 promptBehavior, Action`1 promptAction, String userId, SecureString password, String credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount accoun
t, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, 
IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzure
Environment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzure
Environment environment, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment e
nvironment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValida
tion, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass87_0.<ExecuteCmdlet>b__0(AzureRmP
rofile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextA
ction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:00:32 AM - ConnectAzureRmAccountCommand end processing.
DEBUG: 1:00:32 AM - ConnectAzureRmAccountCommand end processing.
```

**Comment by whiggs** [comment]
Closing this issue.  The problem had to do with our azure environment and the fact that the version of azure ad connect was the preview version and out of date.  Now working
