### ISSUE TITLE
Import-AzureRmApiManagementApi command started to fire errors

### ISSUE THREAD

**Issue by osemyonov** [Azure/azure-powershell#6639]
PS script updats Azure APIs by swagger files. Everything worked. Recently it started to fire errors:
PS script worked last 6 month and was not modified.

**Cmd**: 
Import-AzureRmApiManagementApi  -Context $azureContext -SpecificationFormat Swagger -SpecificationPath $fileName -Path $_.Path -ApiId $_.ApiId -ErrorAction Continue -ErrorVariable +azureImportError;

**Error**:
Import-AzureRmApiManagementApi : UnsupportedMediaType: The content media type 'application/vnd.swagger.doc+json' is not supported. Only
'application/json' is supported

**Comment by cormacpayne** [comment]
@solankisamir Hey Samir, would you mind taking a look at this issue?

**Comment by solankisamir** [comment]
@osemyonov can you move to https://www.powershellgallery.com/packages/AzureRM.Resources/6.1.0 package, as it seems the [AzureResourceManager](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-overview) has started blocking our older apis, which had a custom media type implementation.

**Comment by sgoyal85** [comment]
@cormacpayne even we are aslo started receiving the same error for all existing applicaitons, we tried updating the module on server, but didn't worked.

Can you please look ?


Importing API Swagger Doc
July 16th 2018 12:48:07Info
FAILURE! An error occurred!!! Aborting script...
July 16th 2018 12:48:07Info
UnsupportedMediaType: The content media type 'application/vnd.swagger.link+json' is not supported. Only 'application/json' is supported.
July 16th 2018 12:48:07Info
Hyak.Common.CloudException: UnsupportedMediaType: The content media type 'application/vnd.swagger.link+json' is not supported. Only 'application/json' is supported.
July 16th 2018 12:48:07Info
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
July 16th 2018 12:48:07Info
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
July 16th 2018 12:48:07Info
   at Microsoft.Azure.Management.ApiManagement.ApisOperationsExtensions.Import(IApisOperations operations, String resourceGroupName, String serviceName, String aid, String contentType, Stream content, String path)
July 16th 2018 12:48:07Info
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ApiImportFromUrl(PsApiManagementContext context, String apiId, PsApiManagementApiFormat specificationFormat, String specificationUrl, String urlSuffix)
July 16th 2018 12:48:07Info
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.ImportAzureApiManagementApi.ExecuteApiManagementCmdlet()
July 16th 2018 12:48:07Info
   at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.Commands.AzureApiManagementCmdletBase.ExecuteCmdlet()

**Comment by solankisamir** [comment]
The partner team is deploying a fix for this issue.

**Comment by solankisamir** [comment]
@sgoyal85 it could stretch to End of this week unless they find another regression.

**Comment by osemyonov** [comment]
it is resolved. Thanks
