### ISSUE TITLE
[Storage] Can't set File share quota bigger than 5120GB in PowerShell

### ISSUE THREAD

**Issue by blueww** [Azure/azure-powershell#6812]
### Description

This issue comes from a mail from Dariusz Mokwa <damok@microsoft.com>.
Since he don't have GitHub account, open an issue for him.

> We noticed that powershell SDK sets maximum quota size to 5120GB, which is a bug.
> 
> The bug is, powershell SDK should NOT have knowledge of a maximum quota size.
> 
> It’s especially important in LFS where the limit is much higher and it blocks customers.

### Script/Steps for Reproduction

```powershell

```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
```
Not get this from Dariusz , but Dariusz can't repro the issue.
### Environment Data

```powershell
$PSVersionTable
```

### Debug Output

```

```

**Comment by blueww** [comment]
Dariusz can't repro the issue on his machine.

After discuss with him online, I get the issue is in $share.SetProperties().

Actually, “$share.SetProperties()” is call XSCL (Storage Client Library) in Powershell, so actually the error is reported by XSCL, not Powershell.

And I have tried this scenario with latest PowerShell https://github.com/Azure/azure-powershell/releases/tag/v6.6.0-July2018

The (400) Bad Request reported. Actually the error is from server, not from XSCL. So seems the server still not support share quota bigger than 5TB
```
PS C:\WINDOWS\system32> $share.Properties.Quota = 10240


PS C:\WINDOWS\system32> $share.SetProperties()
Exception calling "SetProperties" with "0" argument(s): "The remote server returned an error: (400) Bad Request."
At line:1 char:1
+ $share.SetProperties()
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : StorageException


PS C:\WINDOWS\system32> $Error[0].Exception.InnerException.ToString()
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an e
rror: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.File.CloudFileShare.SetProperties(AccessCondition accessCondition, FileRequestOptions options, OperationContext operationContext)

   at CallSite.Target(Closure , CallSite , Object )
Request Information
RequestID:a6f766ec-901a-00c1-1bbb-27a745000000
RequestDate:Mon, 30 Jul 2018 04:13:53 GMT
StatusMessage:The value for one of the HTTP headers is not in the correct format.
ErrorCode:InvalidHeaderValue
ErrorMessage:The value for one of the HTTP headers is not in the correct format.
RequestId:a6f766ec-901a-00c1-1bbb-27a745000000
Time:2018-07-30T04:13:54.5166746Z 

```

**Comment by blueww** [comment]
This should already been fixed in the latest Powershell release.
