### ISSUE TITLE
Unable to Import AzureRM.RedisCache Module More Than Once

### ISSUE THREAD

**Issue by brubch** [Azure/azure-powershell#6835]
### Description

Importing AzureRM.RedisCache adds a default parameter value with key `New-AzureRmRedisCache:ResourceGroupName` which is not cleared when the module is removed.  Any subsequent attempts to import the module fail because this key already exists in the current session.

### Script/Steps for Reproduction

```powershell
Import-Module -Name AzureRM.RedisCache
Remove-Module -Name AzureRM.RedisCache
Import-Module -Name AzureRM.RedisCache
```

### Module Version

```powershell
Get-Module -Name AzureRM -ListAvailable
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.0.2      AzureRM.RedisCache                  {Export-AzureRmRedisCache, Get-AzureRmRedisCache, Get-AzureRmRedisCacheF...
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14393.2189
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2189
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
DEBUG: 9:26:45 AM - ResolveError begin processing with ParameterSet 'LastErrorParameterSet'.
DEBUG: 9:26:45 AM - using account id 'cbrubaker@athenahealth.com'...


   HistoryId: -1


Message        : Exception calling "Add" with "2" argument(s): "The key 'New-AzureRmRedisCache:ResourceGroupName' has already been
                 added to the dictionary."
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception,
                 Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
                    at CallSite.Target(Closure , CallSite , Object , Object , ScriptBlock )
                    at System.Management.Automation.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.MethodInvocationException
InvocationInfo : {}
Line           :         $global:PSDefaultParameterValues.Add($_,

Position       : At C:\Program Files\WindowsPowerShell\Modules\AzureRM.RedisCache\5.0.2\AzureRM.RedisCache.psm1:36 char:9
                 +         $global:PSDefaultParameterValues.Add($_,
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

Message        : The key 'New-AzureRmRedisCache:ResourceGroupName' has already been added to the dictionary.
StackTrace     :    at System.Management.Automation.DefaultParameterDictionary.AddImpl(Object key, Object value, Boolean
                 isSelfIndexing)
                    at CallSite.Target(Closure , CallSite , Object , Object , ScriptBlock )
Exception      : System.Management.Automation.PSArgumentException
InvocationInfo : {}
Line           :         $global:PSDefaultParameterValues.Add($_,

Position       : At C:\Program Files\WindowsPowerShell\Modules\AzureRM.RedisCache\5.0.2\AzureRM.RedisCache.psm1:36 char:9
                 +         $global:PSDefaultParameterValues.Add($_,
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : -1

DEBUG: AzureQoSEvent: CommandName - Resolve-AzureRmError; IsSuccess - True; Duration - 00:00:00.0698211; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 9:26:46 AM - ResolveError end processing.
DEBUG: 9:26:46 AM - ResolveError end processing.
```

**Comment by markcowl** [comment]
@maddieclayton Looks like this might have to do with default parameter values - can you take a look?
