### ISSUE TITLE
Start-AzureRmAksDashboard returns startIndex cannot be larger than length of string

### ISSUE THREAD

**Issue by lwsrbrts** [Azure/azure-powershell#6972]
### Description

Start-AzureRmAksDashboard fails to run with a `startIndex cannot be larger than length of string.` error.

Something tells me it's related to the fact that I have *a space in my profile path* since running the kubectl command verbatim yields an error also.

### Script/Steps for Reproduction

Just running: 

```powershell
Start-AzureRmAksDashboard -ResourceGroupName rg-aks-pre-apps-1 -Name akspreapps1 -Verbose
```
Results in:

```powershell
PS C:\Users\Lewis Roberts> Start-AzureRmAksDashboard -ResourceGroupName rg-aks-pre-apps-1 -Name akspreapps1 -Verbose
VERBOSE: Running: kubectl get pods --kubeconfig C:\Users\Lewis Roberts\AppData\Local\Temp\tmpDB29.tmp --namespace
kube-system --output name --selector k8s-app=kubernetes-dashboard
Start-AzureRmAksDashboard : startIndex cannot be larger than length of string.
Parameter name: startIndex
At line:1 char:1
+ Start-AzureRmAksDashboard -ResourceGroupName rg-aks-pre-apps-1 -Name  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureRmAksDashboard], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Aks.StartAzureRmAksDashboard
```

### Module Version

```powershell
PS C:\Users\Lewis Roberts> Get-Module -Name AzureRM -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.7.0      AzureRM
Script     6.6.0      AzureRM
Script     6.4.0      AzureRM

PS C:\Users\Lewis Roberts> Get-Module -Name AzureRM.aks -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.0.5      AzureRM.Aks                         {Get-AzureRmAks, New-AzureRmAks, Remove-AzureRmAks, Import...
Script     0.0.4      AzureRM.Aks                         {Get-AzureRmAks, New-AzureRmAks, Remove-AzureRmAks, Import...
```

### Environment Data

```powershell
PS C:\Users\Lewis Roberts> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.228
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.228
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Debug Output

This is with $DebugPreference set. I've omitted some obviously sensitive data, this is the point at which the command fails:

```
VERBOSE: Running: kubectl get pods --kubeconfig C:\Users\Lewis Roberts\AppData\Local\Temp\tmp171.tmp --namespace
kube-system --output name --selector k8s-app=kubernetes-dashboard
Start-AzureRmAksDashboard : startIndex cannot be larger than length of string.
Parameter name: startIndex
At line:1 char:1
+ Start-AzureRmAksDashboard -ResourceGroupName rg-aks-pre-apps-1 -Name  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzureRmAksDashboard], ArgumentOutOfRangeException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Aks.StartAzureRmAksDashboard

DEBUG: AzureQoSEvent: CommandName - Start-AzureRmAksDashboard; IsSuccess - False; Duration - 00:00:00.6390040;
Exception - System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.Azure.Commands.Aks.StartAzureRmAksDashboard.<ExecuteCmdlet>b__28_0()
   at Microsoft.Azure.Commands.Aks.KubeCmdletBase.RunCmdLet(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 10:25:00 - StartAzureRmAksDashboard end processing.
DEBUG: 10:25:00 - StartAzureRmAksDashboard end processing.
```

**Comment by lwsrbrts** [comment]
Likely related to this line:

https://github.com/Azure/azure-powershell/blob/90e3d3871dd7e3f27770eeaa9848488bc3b12083/src/ResourceManager/Aks/Commands.Aks/Commands/StartAzureRmAksDashboard.cs#L137

And this one is also likely to cause problems:

https://github.com/Azure/azure-powershell/blob/90e3d3871dd7e3f27770eeaa9848488bc3b12083/src/ResourceManager/Aks/Commands.Aks/Commands/StartAzureRmAksDashboard.cs#L251

**Comment by cormacpayne** [comment]
@mboersma Hey Matt, would you mind taking a look at this issue when you get the chance?

**Comment by dingmeng-xue** [comment]
@erich-wang , please check if we have provide parity in `Start-AzAksDashboard`.

**Comment by erich-wang** [comment]
In latest version Az.Aks 1.1.2, Start-AzAksDashboard works well. Close this issue as it could not be re-produced.
