### ISSUE TITLE
Register-AzureRmAutomationDscNode - Asks for 'ResourceGroupName' and 'TemplateFile' when they are already Provided

### ISSUE THREAD

**Issue by GenesisCoast** [Azure/azure-powershell#7129]
### Description

When trying to register a new node in an Azure Automation account I get the following error message:

```
Register-AzureRmAutomationDscNode : Cannot process command because of one or more missing mandatory parameters: ResourceGroupName TemplateFile.
At line:1 char:1
+ Register-AzureRmAutomationDscNode
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Register-AzureRmAutomationDscNode], ParameterBindingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.RegisterAzureAutomationDscNode
```

Even when all the madatory parameters according to the documentation [here](https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/register-azurermautomationdscnode?view=azurermps-6.8.1#required-parameters) are fulfilled.

### Script/Steps for Reproduction

```powershell
Register-AzureRmAutomationDscNode -AzureVMName "Test" -ResourceGroupName "MyGroup" -AutomationAccountName "MyName"
```

### Module Version

- AzureRM **[v6.8.1]**
- AzureRM.Profile **[v4.0.0]**
- AzureRM.Automation **[v4.0.0]**

### Environment Data

- PSVersion **[5.1.14409.1012]**                                                                                                     
- PSEdition **[Desktop]**                                                                                                           
- PSCompatibleVersions **[1.0, 2.0, 3.0, 4.0...]**                                                                                           
- BuildVersion **[10.0.14409.1012]**                                                                                                  
- CLRVersion **[4.0.30319.42000]**                                                                                                   
- WSManStackVersion **[3.0]**                                                             
- PSRemotingProtocolVersion **[2.3]**                                                                         
- SerializationVersion **[1.1.0.1]**                                                            

### Debug Output

Output has been sanitised.

```
PS C:\Windows\system32> Register-AzureRmAutomationDscNode
DEBUG: 3:58:02 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 3:58:02 PM - using account id 'h.sanderson@####.com'...
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmContext; IsSuccess - True; Duration - 00:00:00.0085143; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 3:58:03 PM - GetAzureRMContextCommand end processing.
DEBUG: 3:58:03 PM - GetAzureRMContextCommand end processing.
DEBUG: 3:58:03 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 3:58:03 PM - using account id 'h.sanderson@####.com'...
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmContext; IsSuccess - True; Duration - 00:00:00.0011673; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 3:58:03 PM - GetAzureRMContextCommand end processing.
DEBUG: 3:58:03 PM - GetAzureRMContextCommand end processing.
DEBUG: 3:58:03 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 3:58:03 PM - using account id 'h.sanderson@####.com'...
DEBUG: AzureQoSEvent: CommandName - Get-AzureRmContext; IsSuccess - True; Duration - 00:00:00.0012280; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 3:58:04 PM - GetAzureRMContextCommand end processing.
DEBUG: 3:58:04 PM - GetAzureRMContextCommand end processing.
cmdlet Register-AzureRmAutomationDscNode at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
AzureVMName: ###-####-vm-01
ResourceGroupName: ###-####-NE-01-rg
AutomationAccountName: ###-Automation
DEBUG: 3:58:31 PM - RegisterAzureAutomationDscNode begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 3:58:31 PM - using account id 'h.sanderson@####.com'...
DEBUG: ResourceGroupName: ###-####-NE-01-rg, AutomationAccountName: ###-Automation, AzureVMName: ###-####-vm-01, NodeConfigurationName: , Configura
tionMode: ApplyAndMonitor, ConfigurationModeFrequencyMins: 15, RefreshFrequencyMins: 30, RebootNodeIfNeeded: False, ActionAfterReboot: ContinueConfi
guration,  AllowModuleOverwrite: False, AzureVMResourceGroup: , AzureVMLocation: 
DEBUG: [Common.Authentication]: Authenticating using Account: 'h.sanderson@####.com', environment: 'AzureCloud', tenant: '########-####-####-####'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/04/2018 14:58:31:  - TokenCache: Serializing token cache with 5 items.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/04/2018 14:58:31:  - TokenCache: Serializing token cache with 5 items.

DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '########-####-####-####', Endpoint: 'https://login.
microsoftonline.com/', ClientId: '########-####-####-####', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://ma
nagement.####.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/########-####-####-####
/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '########-####-####-####', AdEndpoint: 'https://lo
gin.microsoftonline.com/', ClientId: '########-####-####-####', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/04/2018 14:58:31: ########-####-####-#### - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/########-####-####-####/
	Resource: https://management.####.windows.net/
	ClientId: ########-####-####-####
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (5 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/04/2018 14:58:31:  - TokenCache: Deserialized 5 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/04/2018 14:58:31: ########-####-####-#### - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/04/2018 14:58:31: ########-####-####-#### - TokenCache: An item matching the requested resource was found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 09/04/2018 14:58:31: ########-####-####-#### - TokenCache: 39.39044429 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/04/2018 14:58:31: ########-####-####-#### - TokenCache: A matching item (access token or refresh token or both) was found in 
the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 09/04/2018 14:58:31: ########-####-####-#### - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access t
oken was retuned:
	Access Token Hash: ####
	Refresh Token Hash: ####
	Expiration Time: 09/04/2018 15:37:54 +00:00
	User Hash: ####
	

DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '########-####-####-####', UserId: 'h.sanderson@####
.com'
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '09/04/2018 15:37:54 +00:00', MultipleResource? 'True', Tenant: '########-####-####-####', UserId: 'h.sanderson@####.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'h.sanderson@####.com', Name:  , IdProvider: 'https://sts.windows.net/########-####-####-############/', Uid: 'a9d5c67e-e98f-4b36-a98a-3bd932ef9db7'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '09/04/2018 15:37:54 +00:00' Comparing to '09/04/2018 14:58:31 +00:00' With
 threshold '00:05:00', calculated time until token expiry: '00:39:23.4110710'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/########-####-####-####/resourceGroups/###-####-NE-01-rg/providers/Microsoft.Automation/auto
mationAccounts/###-Automation?api-version=2015-10-31

Headers:
Accept                        : application/json
x-ms-version                  : 2014-06-01

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
ocp-automation-accountid      : ########-####-####-####
x-ms-request-id               : 3ab84c0a-2ba4-4c25-8784-da9a41b0f93d
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-correlation-request-id   : 32e9c15c-b185-42a4-81bf-31306894722c
x-ms-routing-request-id       : WESTEUROPE:20180904T145831Z:32e9c15c-b185-42a4-81bf-31306894722c
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 04 Sep 2018 14:58:31 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "name": "###-Automation",
  "id": "/subscriptions/########-####-####-####/resourceGroups/###-####-NE-01-rg/providers/Microsoft.Automation/automationAccounts/###-
Automation",
  "type": "Microsoft.Automation/AutomationAccounts",
  "location": "northeurope",
  "tags": {},
  "etag": null,
  "properties": {
    "sku": {
      "name": "Basic",
      "family": null,
      "capacity": null
    },
    "state": "Ok",
    "RegistrationUrl": "https://ne-agentservice-prod-1.azure-automation.net/accounts/########-####-####-####",
    "creationTime": "2017-07-10T08:18:33.96+01:00",
    "lastModifiedBy": "garima.h.singh@####.com",
    "lastModifiedTime": "2018-08-09T14:45:52.187+01:00"
  }
}


DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '09/04/2018 15:37:54 +00:00', MultipleResource? 'True', Tenant: '########-####-####-####', UserId: 'h.sanderson@####.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'h.sanderson@####.com', Name:  , IdProvider: 'https://sts.windows.net/########-####-####-############/', Uid: 'a9d5c67e-e98f-4b36-a98a-3bd932ef9db7'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '09/04/2018 15:37:54 +00:00' Comparing to '09/04/2018 14:58:31 +00:00' With
 threshold '00:05:00', calculated time until token expiry: '00:39:23.0235353'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/########-####-####-####/resourceGroups/###-####-NE-01-rg/providers/Microsoft.Automation/auto
mationAccounts/###-Automation/agentRegistrationInformation?api-version=2015-10-31

Headers:
Accept                        : application/json
x-ms-version                  : 2014-06-01

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : a3e0a285-d73b-415c-9452-9507aa65f1d9
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11997
x-ms-correlation-request-id   : aec09934-d489-49df-96c2-5978a874c413
x-ms-routing-request-id       : WESTEUROPE:20180904T145831Z:aec09934-d489-49df-96c2-5978a874c413
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 04 Sep 2018 14:58:31 GMT
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/########-####-####-####/resourceGroups/###-####-NE-01-rg/providers/Microsoft.Automation/automationAccounts/###-
Automation/agentRegistrationInformation/https://ne-agentservice-prod-1.azure-automation.net/accounts/########-####-####-####",
  "keys": {
    "primary": "########################################################################################",
    "secondary": "########################################################################################"
  },
  "endpoint": "https://ne-agentservice-prod-1.azure-automation.net/accounts/########-####-####-####",
  "dscMetaConfiguration": "\r\n\tinstance of MSFT_WebDownloadManager as $MSFT_WebDownloadManager1ref\r\n\t{\r\n\tResourceID = \"[ConfigurationReposi
toryWeb]AzureAutomationDSC\";\r\n\t SourceInfo = \"C:\\\\OaaS-RegistrationMetaConfig2.ps1::20::9::ConfigurationRepositoryWeb\";\r\n\t RegistrationKe
y = \"#########################################################################################\"; \r\n\t ServerURL = \"https://ne-agentservice-prod-
1.azure-automation.net/accounts/########-####-####-####\";\r\n\t};\r\n\r\n\tinstance of MSFT_WebResourceManager as $MSFT_WebResourceMan
ager1ref\r\n\t{\r\n\t SourceInfo = \"C:\\\\OaaS-RegistrationMetaConfig2.ps1::27::9::ResourceRepositoryWeb\";\r\n\t ServerURL = \"https://ne-agentser
vice-prod-1.azure-automation.net/accounts/########-####-####-####\";\r\n\t ResourceID = \"[ResourceRepositoryWeb]AzureAutomationDSC\";\
r\n\t RegistrationKey = \"#########################################################################################\"; \r\n\t};\r\n\r\n\tinstance of 
MSFT_WebReportManager as $MSFT_WebReportManager1ref\r\n\t{\r\n\t SourceInfo = \"C:\\\\OaaS-RegistrationMetaConfig2.ps1::34::9::ReportServerWeb\";\r\
n\t ServerURL = \"https://ne-agentservice-prod-1.azure-automation.net/accounts/########-####-####-####\";\r\n\t ResourceID = \"[ReportS
erverWeb]AzureAutomationDSC\";\r\n\t RegistrationKey = \"#########################################################################################\";
 \r\n\t};\r\n\r\n\tinstance of MSFT_DSCMetaConfiguration as $MSFT_DSCMetaConfiguration1ref\r\n\t{\r\n\t RefreshMode = \"Pull\";\r\n\t AllowModuleOve
rwrite = False;\r\n\t ActionAfterReboot = \"ContinueConfiguration\";\r\n\t RefreshFrequencyMins = 30;\r\n\t RebootNodeIfNeeded = False;\r\n\t Config
urationModeFrequencyMins = 15;\r\n\t ConfigurationMode = \"ApplyAndMonitor\";\r\n\r\n\t  ResourceModuleManagers = {\r\n\t  $MSFT_WebResourceManager1
ref  \r\n\t};\r\n\t  ReportManagers = {\r\n\t  $MSFT_WebReportManager1ref  \r\n\t };\r\n\t  ConfigurationDownloadManagers = {\r\n\t  $MSFT_WebDownlo
adManager1ref  \r\n\t };\r\n\t};\r\n\r\n\tinstance of OMI_ConfigurationDocument\r\n\t{\r\n\t Version=\"2.0.0\";\r\n\t MinimumCompatibleVersion = \"2
.0.0\";\r\n\t CompatibleVersionAdditionalProperties= { \"MSFT_DSCMetaConfiguration:StatusRetentionTimeInDays\" };\r\n\t Author=\"azureautomation\";\
r\n\t GenerationDate=\"04/17/2015 11:41:09\";\r\n\t GenerationHost=\"azureautomation-01\";\r\n\t Name=\"RegistrationMetaConfig\";\r\n\t};\r\n\t"
}


Register-AzureRmAutomationDscNode : Cannot process command because of one or more missing mandatory parameters: ResourceGroupName TemplateFile.
At line:1 char:1
+ Register-AzureRmAutomationDscNode
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Register-AzureRmAutomationDscNode], ParameterBindingException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.RegisterAzureAutomationDscNode
 
DEBUG: AzureQoSEvent: CommandName - Register-AzureRmAutomationDscNode; IsSuccess - False; Duration - 00:00:02.1250368; Exception - System.Management
.Automation.ParameterBindingException: Cannot process command because of one or more missing mandatory parameters: ResourceGroupName TemplateFile.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.####InvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSett
ings settings)
   at System.Management.Automation.PowerShell.####Invoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings s
ettings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.Azure.Commands.Automation.Common.AutomationClient.RegisterDscNode(String resourceGroupName, String automationAccountName, String azu
reVMName, String nodeconfigurationName, String configurationMode, Int32 configurationModeFrequencyMins, Int32 refreshFrequencyMins, Boolean rebootFl
ag, String actionAfterReboot, Boolean moduleOverwriteFlag, String azureVmResourceGroup, String azureVmLocation)
   at Microsoft.Azure.Commands.Automation.Cmdlet.RegisterAzureAutomationDscNode.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 3:58:34 PM - RegisterAzureAutomationDscNode end processing.
DEBUG: 3:58:34 PM - RegisterAzureAutomationDscNode end processing.
```

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this issue?

**Comment by manericstam** [comment]
Any clue when a corretion will come? 
Br
Manuel

**Comment by GenesisCoast** [comment]
@maddieclayton @vrdmr Has there been any update? Is there anything I can do to help?

**Comment by aatif912** [comment]
Facing the same issue. Waiting for some update.

**Comment by lukeb1961** [comment]
STILL waiting?  I had a perfectly functional script that is now toast.  :-(

**Comment by mcruz-QS** [comment]
Is this an issue with the Module or is it on the back end? I am also experiencing this issue.
6.10.0     AzureRM
5.1.1      AzureRM.Automation
5.6.0      AzureRM.profile

**Comment by vrdmr** [comment]
Fix in: #7505.

FYI @avkaur

**Comment by mivica** [comment]
Hi,  I am experiencing the same issue after I did modules upgrade. I see it has been code fixed, but I need some clarification on a workaround until the fix gets released?
Shall I roll back to the previous version? If so which one and what modules I need to roll back to make Register-AzureRmAutomationDscNode work again?

**Comment by kdutt** [comment]
You can roll back to ComputerManagementDsc version 5.2.0.0

**Comment by nitinbps** [comment]
This issue has been fixed in Az.Automation version 1.1.1.
