### ISSUE TITLE
Get-RoleDefinition cmdlet throws null reference when there is no context

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-powershell#7479]
```powershell
PS C:\Users\markcowl> Get-AzRoleDefinition
Get-AzRoleDefinition : Object reference not set to an instance of an object.
At line:1 char:1
+ Get-AzRoleDefinition
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzRoleDefinition], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.GetAzureRoleDefinitionCommand

PS C:\Users\markcowl> Resolve-AzError


   HistoryId: 1


Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Resources.GetAzureRoleDefinitionCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {Get-AzRoleDefinition}
Line           : Get-AzRoleDefinition
Position       : At line:1 char:1
                 + Get-AzRoleDefinition
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1


```

**Comment by praries880** [comment]
Pr merged : https://github.com/Azure/azure-powershell/pull/7592

**Comment by hausec** [comment]
Still getting this error on azure-cli 2.5.1

There is a subscription for the tenant.
