### ISSUE TITLE
New-AzureRmVmssConfig The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#7556]
```
(get-module azurerm).version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      10     0      -1   

$PSVersionTable
Name                           Value                                                                                                     
----                           -----                                                                                                     
PSVersion                      5.1.17763.1                                                                                               
PSEdition                      Desktop                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                   
BuildVersion                   10.0.17763.1                                                                                              
CLRVersion                     4.0.30319.42000                                                                                           
WSManStackVersion              3.0                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                       
SerializationVersion           1.1.0.1 
```
I had a perfectly functional script, but with a recent update to AzureRM I have a broken script..
One of the new errors:
ErrorMessage: The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 

Regardless of what I put for -IdentityType, via New-AzureRmVmssConfig
New-AzureRmVmss complains about some aspect. 
I never had this parameter  before and now my script is broken...

See below as an example of the debug output.
```
New-AzureRmVmss -ResourceGroupName $RG -Name $SydneylxVMSS -VirtualMachineScaleSet $SydlxVMSSConfig -Verbose -debug
DEBUG: 14:18:26 - NewAzureRmVmss begin processing with ParameterSet 'DefaultParameter'.
DEBUG: 14:18:28 - using account id 'LukeBrennan@outlook.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'LukeBrennan@outlook.com', environment: 'AzureCloud', tenant: '1f89577f-4235
-4965-83e5-aad1a7e761fc'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 24045a7b-57d9-4b91-b63f-a1bb94593563 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (9 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30:  - TokenCache: Deserialized 9 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/15/2018 06:18:30: 24045a7b-57d9-4b91-b63f-a1bb94593563 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 24045a7b-57d9-4b91-b63f-a1bb94593563 - TokenCache: An item matching the requested resource was found in the ca
che

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/15/2018 06:18:30: 24045a7b-57d9-4b91-b63f-a1bb94593563 - TokenCache: 59.5018208416667 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 24045a7b-57d9-4b91-b63f-a1bb94593563 - TokenCache: A matching item (access token or refresh token or both) was
 found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 24045a7b-57d9-4b91-b63f-a1bb94593563 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. A
n access token was retuned:
	Access Token Hash: 6zbAaxncoldWv/HqhTKys8TddKWcP2NRimtaL+G+cE0=
	Refresh Token Hash: l6BRf/vJrfQ5maHQA+1U4q3KGnGVY4nSrQeI4IRVUCI=
	Expiration Time: 10/15/2018 07:18:00 +00:00
	User Hash: YaMfsGPkmwxwhyKw73ipmyjRqqUKsNAj5t9JRnaYlxk=
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 8c9d7f44-40eb-4ea1-ac63-3436140b9cd8 - AcquireTokenHandlerBase: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (9 items)
	Authentication Target: User
	

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30:  - TokenCache: Deserialized 9 items to token cache.

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/15/2018 06:18:30: 8c9d7f44-40eb-4ea1-ac63-3436140b9cd8 - TokenCache: Looking up cache for a token...

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 8c9d7f44-40eb-4ea1-ac63-3436140b9cd8 - TokenCache: An item matching the requested resource was found in the ca
che

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 : 
DEBUG: 10/15/2018 06:18:30: 8c9d7f44-40eb-4ea1-ac63-3436140b9cd8 - TokenCache: 59.5010042583333 minutes left until token in cache expires

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 8c9d7f44-40eb-4ea1-ac63-3436140b9cd8 - TokenCache: A matching item (access token or refresh token or both) was
 found in the cache

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 : 
DEBUG: 10/15/2018 06:18:30: 8c9d7f44-40eb-4ea1-ac63-3436140b9cd8 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. A
n access token was retuned:
	Access Token Hash: 6zbAaxncoldWv/HqhTKys8TddKWcP2NRimtaL+G+cE0=
	Refresh Token Hash: l6BRf/vJrfQ5maHQA+1U4q3KGnGVY4nSrQeI4IRVUCI=
	Expiration Time: 10/15/2018 07:18:00 +00:00
	User Hash: YaMfsGPkmwxwhyKw73ipmyjRqqUKsNAj5t9JRnaYlxk=
	

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/lukebrennan-AZUREthings/providers/Microsoft
.Compute/virtualMachineScaleSets/SydLxVMScaleSet?api-version=2018-06-01

Headers:
x-ms-client-request-id        : 377067e9-ecc1-410f-8926-649d9169e1c3
accept-language               : en-US

Body:
{
  "sku": {
    "name": "Standard_DS2",
    "capacity": 2
  },
  "properties": {
    "upgradePolicy": {
      "mode": "Automatic",
      "automaticOSUpgrade": false
    },
    "virtualMachineProfile": {
      "osProfile": {
        "computerNamePrefix": "SydLX",
        "adminUsername": "localadmin",
        "adminPassword": "XXXXXXXXXXX"
      },
      "storageProfile": {
        "imageReference": {
          "publisher": "OpenLogic",
          "offer": "CentOS",
          "sku": "7.4",
          "version": "latest"
        },
        "osDisk": {
          "caching": "None",
          "writeAcceleratorEnabled": false,
          "createOption": "FromImage",
          "osType": "Linux"
        }
      },
      "networkProfile": {
        "networkInterfaceConfigurations": [
          {
            "name": "network-config",
            "properties": {
              "primary": true,
              "enableAcceleratedNetworking": false,
              "ipConfigurations": [
                {
                  "name": "VMSSIPConfig",
                  "properties": {
                    "subnet": {
                      "id": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/lukebrennan-AZUREthings/providers/Microsof
t.Network/virtualNetworks/UNIX-vnet-Sydney/subnets/LX-Subnet"
                    },
                    "primary": false,
                    "loadBalancerBackendAddressPools": [
                      {
                        "id": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/lukebrennan-AZUREthings/providers/Micros
oft.Network/loadBalancers/sydlxlb/backendAddressPools/SydlxBEpool"
                      }
                    ]
                  }
                }
              ],
              "enableIPForwarding": false
            }
          }
        ]
      }
    }
  },
  "identity": {
    "userAssignedIdentities": {}
  },
  "location": "australiaeast",
  "tags": {
    "Value": "lukebrennan",
    "Name": "AnotherTagName"
  }
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 37b0b8f2-1bdf-4934-9c96-e89349b3fa9b
x-ms-correlation-request-id   : 37b0b8f2-1bdf-4934-9c96-e89349b3fa9b
x-ms-routing-request-id       : AUSTRALIAEAST:20181015T061832Z:37b0b8f2-1bdf-4934-9c96-e89349b3fa9b
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 15 Oct 2018 06:18:32 GMT

Body:
{
  "error": {
    "code": "InvalidRequestContent",
    "message": "The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 'identity
'.'."
  }
}


DEBUG: AzureQoSEvent: CommandName - New-AzureRmVmss; IsSuccess - True; Duration - 00:00:04.2842684; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 14:18:31 - NewAzureRmVmss end processing.
DEBUG: 14:18:31 - NewAzureRmVmss end processing.
New-AzureRmVmss : The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 
'identity'.'.
ErrorCode: InvalidRequestContent
ErrorMessage: The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 
'identity'.'.
ErrorTarget: 
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 37b0b8f2-1bdf-4934-9c96-e89349b3fa9b
At line:1 char:1
+ New-AzureRmVmss -ResourceGroupName $RG -Name $SydneylxVMSS -VirtualMa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzureRmVmss], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss
 
DEBUG: AzureQoSEvent: CommandName - New-AzureRmVmss; IsSuccess - False; Duration - 00:00:04.2842684; Exception - Microsoft.Azure.Commands.
Compute.Common.ComputeCloudException: The request content was invalid and could not be deserialized: 'Required property 'type' not found i
n JSON. Path 'identity'.'.
ErrorCode: InvalidRequestContent
ErrorMessage: The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 'identity'.
'.
ErrorTarget: 
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 37b0b8f2-1bdf-4934-9c96-e89349b3fa9b ---> Microsoft.Rest.Azure.CloudException: The request content was invalid and could not
 be deserialized: 'Required property 'type' not found in JSON. Path 'identity'.'.
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.<CreateOrUpdateAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.CreateOrUpdate(IVirtualMachineScaleSetsOperations ope
rations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSet parameters)
   at Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss.<ExecuteCmdlet>b__1_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 14:18:34 - NewAzureRmVmss end processing.
DEBUG: 14:18:34 - NewAzureRmVmss end processing.
```

**Comment by markcowl** [comment]
@lukeb1961 Can you please share the relevant contents of the VMSS Config?  This looks like an issue with an empty Managed Service Identity - I assume you are not using ManagedServiceIdentity in the conguration.

@hyonholee @praries880 Can you guys take a look?

**Comment by lukeb1961** [comment]
correct. I do not and have never used a ManagedServiceIdentity in the VMSSconfig. This has worked fine for a year or so. See below:

  Write-Verbose -Message 'Creating LINUX VMSS config (Sydney)'
  $SydlxVMSScapacity=2
  $NodePIP=@()
  for ($i=0; $i -lt $SydlxVMSScapacity; $i++) {
    $PipName = 'sydlxVMSSpip{0}' -f $i

    if ( -NOT (    Get-AzureRmPublicIpAddress -Name $PipName -ResourceGroupName $RG -ErrorAction SilentlyContinue)) {
      $null=New-AzureRMPublicIpAddress -Name $PipName -ResourceGroupName $RG -Location $Sydney -AllocationMethod Dynamic  
    }

    $NodePIP += Get-AzureRmPublicIpAddress -Name $PipName -ResourceGroupName $RG -ErrorAction SilentlyContinue
  }


# Create a VMSS config object
$SydlxVMSSConfig = New-AzureRmVmssConfig -Location $Sydney `
                                       -SkuCapacity $SydlxVMSScapacity -SkuName Standard_DS2 `
                                       -UpgradePolicyMode Automatic `
                                       -Tag @{Name='AnotherTagName';Value=$MyName}
# Reference a virtual machine image from the gallery
$SydlxVMSSConfig=Set-AzureRmVmssStorageProfile -VirtualMachineScaleSet $SydlxVMSSConfig `
                             -ImageReferencePublisher OpenLogic `
                             -ImageReferenceOffer CentOS `
                             -ImageReferenceSku 7.4 `
                             -ImageReferenceVersion latest `
                             -OsDiskCreateOption 'FromImage' -OsDiskCaching 'None' -OsDiskOsType Linux

# Set up information for authenticating with the virtual machine
$SydlxVMSSConfig=Set-AzureRmVmssOsProfile -VirtualMachineScaleSet $SydlxVMSSConfig `
                                        -AdminUsername $user -AdminPassword $password `
                                        -ComputerNamePrefix SydLX 

$SydVnet     = Get-AzureRmVirtualNetwork -Name $VnetSydney -ResourceGroupName $RG
$SydLXsubnet = Get-AzureRmVirtualNetworkSubnetConfig -Name $LXsubnetName -VirtualNetwork $SydVnet


$PublicIPconfig = New-AzureRmNetworkInterfaceIpConfig -Name 'PublicIP'  -PublicIpAddress $PIP1

$ipConfig    = New-AzureRmVmssIpConfig -Name 'VMSSIPConfig' `
                                    -LoadBalancerBackendAddressPoolsId $SydlxLB.BackendAddressPools[0].Id `
                                    -SubnetId $SydLXsubnet.Id #-PublicIPAddressConfigurationName $PublicIPconfig

# Attach the virtual network to the config object
$SydlxVMSSConfig=Add-AzureRmVmssNetworkInterfaceConfiguration -VirtualMachineScaleSet $SydlxVMSSConfig `
                                                            -Name 'network-config'  `
                                                            -Primary $true `
                                                            -IPConfiguration $ipConfig

**Comment by ossentoo** [comment]
The same or version similar issue for me. Assuming I've already connected to a subscription using Connect-AzureRmAccount,

running these commands results in an error

$vmssConfig = New-AzureRmVmssConfig `
    -Location "East US" `
    -SkuCapacity 1 `
    -SkuName "Standard_D1_v2" `
    -UpgradePolicyMode Automatic

$vmssConfig = Add-AzureRmVmssDataDisk `
    -VirtualMachineScaleSet $vmssConfig `
    -Name 'AZDODataDisk' `
    -Lun 0 `
    -Caching 'ReadOnly' `
    -CreateOption Empty `
    -DiskSizeGB 64 `
    -StorageAccountType StandardLRS

$vmss = New-AzureRmVmss `
    -ResourceGroupName "testVMSS" `
    -VMScaleSetName "test01" `
    -VirtualMachineScaleSet $vmssConfig -Verbose -debug

results in this error:

The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 'identity', line 31, position 3.'

I've tried AzureRM versions: 6.10.0 and 6.11.0 with the same result.

**Comment by surlypants** [comment]
Additionally, if supplying '-IdentityType SystemAssigned'

the error will instead be:

ErrorMessage: Identity operation for resource '/subscriptions/___REDACTED___/providers/Microsoft.Compute/virtualMachineScaleSets/___REDACTED___ failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","message":"The request format was unexpected, a non-UserAssigned identity type should not contain: userAssignedIdentities"}}'.'.

**Comment by surlypants** [comment]
any traction here?

**Comment by Dziubey** [comment]
I receive similar error when I copy-paste script from:
https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/new-azurermvmss?view=azurermps-6.11.0
(I fixed issues with resource names, etc)

The error message:

New-AzureRmVmss : The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 'identity', line 112, position 3.'.
ErrorCode: InvalidRequestContent
ErrorMessage: The request content was invalid and could not be deserialized: 'Required property 'type' not found in JSON. Path 'identity', line 112, position 3.'.
ErrorTarget:
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : bdacb740-d1fe-4f80-a5a5-dd6699f3392f
At <path to my script>
+ New-AzureRmVmss -ResourceGroupName $RGName -Name $VMSSName -VirtualMa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzVmss], ComputeCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.NewAzureRmVmss

**Comment by ossentoo** [comment]
Realized v6.12.0 of AzureRM has been released.  

I've tried my command above again, and it seems to work for me (though I haven't checked all the deployed resources yet). 👍 

https://github.com/Azure/azure-powershell/releases/tag/v6.12.0-November2018

At least I'm no longer getting a json related error.

Can you all try and see if it helps?

**Comment by surlypants** [comment]
6.12.0 resolves for me also.

**Comment by maddieclayton** [comment]
Closing as this issue seems to be resolved.  Please reopen if you continue to see this issue in the current version of AzureRM.
