### ISSUE TITLE
Update-AzureRmVM : Changing property 'osDisk.createOption' is not allowed

### ISSUE THREAD

**Issue by wuy3** [Azure/azure-powershell#7621]
### Description
I saw that [issue 4412](https://github.com/Azure/azure-powershell/issues/4412) was closed as fixed, but I'm still running into it with the latest AzureRM package (6.10.0). When trying to swap an AzureVM's OS disk with `Set-AzureRmVMOSDisk` and then `Update-AzureRmVM`, I get  **"Changing property 'osDisk.createOption' is not allowed"** error.

### Script/Steps for Reproduction

```powershell
PS C:\Users\yizwu\Desktop> $vm03 = Get-AzureRmVM -ResourceGroupName "AzureSecMgmtPlane" -Name "AZRSMPRDSH03"
PS C:\Users\yizwu\Desktop> $vm_03_disk = Get-AzureRmDisk -ResourceGroupName "AzureSecMgmtPlane" -Name AAZRSMPRDSH03_test01
PS C:\Users\yizwu\Desktop> $vm03_mod = Set-AzureRmVMOSDisk -VM $vm03 -ManagedDiskId $vm_03_disk.Id -CreateOption Attach -Windows
PS C:\Users\yizwu\Desktop> Update-AzureRmVM -ResourceGroupName AzureSecMgmtPlane -VM $vm03_mod
```
Error is thrown on `Update-AzureRmVM`

### Module Version

```
ModuleType Version   Name
---------- -------   ----
    Script 5.3.0     Azure
    Script 4.6.1     Azure.Storage
    Script 6.10.0    AzureRM
    Script 5.0.6     AzureRM.Cdn
    Script 0.9.11    AzureRM.CognitiveServices
    Script 5.7.0     AzureRM.Compute
    Script 0.5.11    AzureRM.DataFactoryV2
    Script 5.1.0     AzureRM.Dns
    Script 5.1.4     AzureRM.Insights
    Script 6.9.0     AzureRM.Network
    Script 5.6.0     AzureRM.profile
    Script 0.2.10    AzureRM.RecoveryServices.SiteRecovery
    Script 5.1.0     AzureRM.RedisCache
    Script 6.6.0     AzureRM.Resources
    Script 0.6.12    AzureRM.ServiceBus
    Script 1.0.0     AzureRM.SignalR
    Script 4.11.5    AzureRM.Sql
    Script 5.2.0     AzureRM.Storage
    Script 5.2.0     AzureRM.Websites
    Binary 1.37.19.0 AzureInformationProtection
```

### Environment Data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.1
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
PS C:\Users\yizwu\Desktop> $vm03 = Get-AzureRmVM -ResourceGroupName "AzureSecMgmtPlane" -Name "AZRSMPRDSH03"
PS C:\Users\yizwu\Desktop> $vm_03_disk = Get-AzureRmDisk -ResourceGroupName "AzureSecMgmtPlane" -Name AAZRSMPRDSH03_test01
PS C:\Users\yizwu\Desktop> $vm03_mod = Set-AzureRmVMOSDisk -VM $vm03 -ManagedDiskId $vm_03_disk.Id -CreateOption Attach -Windows
PS C:\Users\yizwu\Desktop> Update-AzureRmVM -ResourceGroupName AzureSecMgmtPlane -VM $vm03_mod
Update-AzureRmVM : Changing property 'osDisk.createOption' is not allowed.
ErrorCode: PropertyChangeNotAllowed
ErrorMessage: Changing property 'osDisk.createOption' is not allowed.
ErrorTarget: osDisk.createOption
StatusCode: 409
ReasonPhrase: Conflict
OperationID : 57c8d34f-e494-4901-8b81-fb1cf3617b40
At line:1 char:1
+ Update-AzureRmVM -ResourceGroupName AzureSecMgmtPlane -VM $vm03_mod
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand

PS C:\Users\yizwu\Desktop> $DebugPreference = "Continue"
PS C:\Users\yizwu\Desktop> Update-AzureRmVM -ResourceGroupName AzureSecMgmtPlane -VM $vm03_mod
DEBUG: 2:02:12 PM - UpdateAzureVMCommand begin processing with ParameterSet 'ResourceGroupNameParameterSetName'.
DEBUG: 2:02:12 PM - using account id 'yizwu@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'yizwu@microsoft.com', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:12: eaac522e-f11b-46fd-bf67-10147e9cf586 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:12:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 10/15/2018 21:02:12: eaac522e-f11b-46fd-bf67-10147e9cf586 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:12: eaac522e-f11b-46fd-bf67-10147e9cf586 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 10/15/2018 21:02:12: eaac522e-f11b-46fd-bf67-10147e9cf586 - TokenCache: An expired or near expiry token was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:12: eaac522e-f11b-46fd-bf67-10147e9cf586 - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 10/15/2018 21:02:12: eaac522e-f11b-46fd-bf67-10147e9cf586 - <RefreshAccessTokenAsync>d__11: Refreshing access token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 10/15/2018 21:02:13: eaac522e-f11b-46fd-bf67-10147e9cf586 - TokenCache: Storing token in the cache...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 10/15/2018 21:02:13: eaac522e-f11b-46fd-bf67-10147e9cf586 - TokenCache: An item was stored in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:13: eaac522e-f11b-46fd-bf67-10147e9cf586 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: s2TU5NLIIkg1ct17hlE7JHJSIjU1m+S/k3eqwyhQneY=
 Refresh Token Hash: kw5GLSfvXmIR4DR96GBLTUY7Zq+9SIeKx0Jkau4eyCQ=
 Expiration Time: 10/15/2018 22:02:12 +00:00
 User Hash: 07tRFmnaVRY/B3Px3QxWaquNGbkj7Jbsyb801ZBj0/4=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:13:  - TokenCache: Serializing token cache with 1 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:13: 2294975a-390e-42de-839a-55ee0481e87c - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:13:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 10/15/2018 21:02:13: 2294975a-390e-42de-839a-55ee0481e87c - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:13: 2294975a-390e-42de-839a-55ee0481e87c - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 10/15/2018 21:02:13: 2294975a-390e-42de-839a-55ee0481e87c - TokenCache: 59.9821665 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:13: 2294975a-390e-42de-839a-55ee0481e87c - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 10/15/2018 21:02:13: 2294975a-390e-42de-839a-55ee0481e87c - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: s2TU5NLIIkg1ct17hlE7JHJSIjU1m+S/k3eqwyhQneY=
 Refresh Token Hash: kw5GLSfvXmIR4DR96GBLTUY7Zq+9SIeKx0Jkau4eyCQ=
 Expiration Time: 10/15/2018 22:02:12 +00:00
 User Hash: 07tRFmnaVRY/B3Px3QxWaquNGbkj7Jbsyb801ZBj0/4=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/06f10951-12e0-43c4-a068-2869b4ee9509/resourceGroups/AzureSecMgmtPlane/providers/Microsoft.Compute/virtualMachines/AZRSMPRDSH03?api-v
ersion=2018-06-01

Headers:
x-ms-client-request-id        : 0f8422e3-a7d4-4588-9e2a-b6c70f064ebf
accept-language               : en-US

Body:
{
  "properties": {
    "hardwareProfile": {
      "vmSize": "Standard_D4s_v3"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2016-Datacenter",
        "version": "latest"
      },
      "osDisk": {
        "osType": "Windows",
        "name": "AZRSMPRDSH03_OsDisk_1_04e8dfd11a844fa5a301b552560e44cc",
        "caching": "ReadWrite",
        "writeAcceleratorEnabled": false,
        "createOption": "Attach",
        "managedDisk": {
          "id": "/subscriptions/06f10951-12e0-43c4-a068-2869b4ee9509/resourceGroups/AzureSecMgmtPlane/providers/Microsoft.Compute/disks/AAZRSMPRDSH03_test01"
        }
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "AZRSMPRDSH03",
      "adminUsername": "admin.local",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": true
      },
      "secrets": []
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/06f10951-12e0-43c4-a068-2869b4ee9509/resourceGroups/AzureSecMgmtPlane/providers/Microsoft.Network/networkInterfaces/azrsmprdsh03741"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true,
        "storageUri": "https://azuresecmgmtplanediag548.blob.core.windows.net/"
      }
    },
    "availabilitySet": {
      "id": "/subscriptions/06f10951-12e0-43c4-a068-2869b4ee9509/resourceGroups/AzureSecMgmtPlane/providers/Microsoft.Compute/availabilitySets/AZURESECMGMTPLANEAVSET"
    }
  },
  "location": "eastus2",
  "tags": {}
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/PutVM3Min;239,Microsoft.Compute/PutVM30Min;1199
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : b4f067ff-215e-46f1-af5e-0abf6fff8ece_131808056576914964
x-ms-request-id               : ff4a8036-621f-41de-8867-812661fb3f13
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 5db591b1-ba01-4e97-9f25-24dccec35cd5
x-ms-routing-request-id       : WESTUS2:20181015T210214Z:5db591b1-ba01-4e97-9f25-24dccec35cd5
X-Content-Type-Options        : nosniff
Date                          : Mon, 15 Oct 2018 21:02:14 GMT

Body:
{
  "error": {
    "code": "PropertyChangeNotAllowed",
    "target": "osDisk.createOption",
    "message": "Changing property 'osDisk.createOption' is not allowed."
  }
}

DEBUG: AzureQoSEvent: CommandName - Update-AzureRmVM; IsSuccess - True; Duration - 00:00:02.7153035; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 2:02:15 PM - UpdateAzureVMCommand end processing.
DEBUG: 2:02:15 PM - UpdateAzureVMCommand end processing.
Update-AzureRmVM : Changing property 'osDisk.createOption' is not allowed.
ErrorCode: PropertyChangeNotAllowed
ErrorMessage: Changing property 'osDisk.createOption' is not allowed.
ErrorTarget: osDisk.createOption
StatusCode: 409
ReasonPhrase: Conflict
OperationID : ff4a8036-621f-41de-8867-812661fb3f13
At line:1 char:1
+ Update-AzureRmVM -ResourceGroupName AzureSecMgmtPlane -VM $vm03_mod
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Update-AzureRmVM], ComputeCloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand

DEBUG: AzureQoSEvent: CommandName - Update-AzureRmVM; IsSuccess - False; Duration - 00:00:02.7153035; Exception -
Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: Changing property 'osDisk.createOption' is not allowed.
ErrorCode: PropertyChangeNotAllowed
ErrorMessage: Changing property 'osDisk.createOption' is not allowed.
ErrorTarget: osDisk.createOption
StatusCode: 409
ReasonPhrase: Conflict
OperationID : ff4a8036-621f-41de-8867-812661fb3f13 ---> Microsoft.Rest.Azure.CloudException: Changing property 'osDisk.createOption' is not allowed.
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.VirtualMachinesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.<ExecuteCmdlet>b__40_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.Compute.UpdateAzureVMCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 2:02:15 PM - UpdateAzureVMCommand end processing.
DEBUG: 2:02:15 PM - UpdateAzureVMCommand end processing.
```

**Comment by MiYanni** [comment]
@cormacpayne Hey buddy. I saw you commented on the original issue. Do you have any info to help @wuy3 out?

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you know why this issue would resurface?

**Comment by wuy3** [comment]
thanks for looking into this guys. I'm not currently blocked buy this issue, but in the near future I will have to change OS disks "in place" on existing VMs. This issue would block me then.

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
