### ISSUE TITLE
BadRequest using Set-AzureRmIotHub to change SKU and units of an IOT hub

### ISSUE THREAD

**Issue by HsiaoH** [Azure/azure-powershell#7639]
### Description

I am getting a BadRequest when trying to change the SKU and work units of an IOT Hub. The problem seems to be with a blob endpoint. This endpoint is working correctly.

### Script/Steps for Reproduction

    Set-AzureRmIotHub -ResourceGroupName "myresourcegroupname" -Name "iothubname" -SkuName S2 -Units 2

### Module Version

```ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     0.13.1     Azure.AnalysisServices.Netcore      Core      {Add-AzureAnalysisServicesAccount, Restart-AzureAnalysisServicesInstance, Export-AzureAnalysisServicesInstanceLog, Sync-AzureAnalysisServic...
Script     0.13.1     Azure.Storage.Netcore               Core      {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStorageTableStoredAccessPolicy, New-AzureStorageTable...}
Script     0.13.1     AzureRM.Aks.Netcore                 Core      {Get-AzureRmAks, New-AzureRmAks, Remove-AzureRmAks, Import-AzureRmAksCredential...}
Script     0.13.1     AzureRM.AnalysisServices.Netcore    Core      {Resume-AzureRmAnalysisServicesServer, Suspend-AzureRmAnalysisServicesServer, Get-AzureRmAnalysisServicesServer, Remove-AzureRmAnalysisServ...
Script     0.13.1     AzureRM.ApiManagement.Netcore       Core      {Add-AzureRmApiManagementRegion, Get-AzureRmApiManagementSsoToken, New-AzureRmApiManagementHostnameConfiguration, New-AzureRmApiManagementC...
Script     0.13.1     AzureRM.ApplicationInsights.Netcore Core      {Get-AzureRmApplicationInsights, New-AzureRmApplicationInsights, Remove-AzureRmApplicationInsights, Set-AzureRmApplicationInsightsPricingPl...
Script     0.13.1     AzureRM.Automation.Netcore          Core      {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRm...
Script     0.13.1     AzureRM.Batch.Netcore               Core      {Remove-AzureRmBatchAccount, Get-AzureRmBatchAccount, Get-AzureRmBatchAccountKeys, New-AzureRmBatchAccount...}
Script     0.13.1     AzureRM.Billing.Netcore             Core      {Get-AzureRmBillingInvoice, Get-AzureRmBillingPeriod, Get-AzureRmEnrollmentAccount}
Script     0.13.1     AzureRM.Cdn.Netcore                 Core      {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSsoUrl, New-AzureRmCdnProfile, Remove-AzureRmCdnProfile...}
Script     0.13.1     AzureRM.CognitiveServices.Netcore   Core      {Get-AzureRmCognitiveServicesAccount, Get-AzureRmCognitiveServicesAccountKey, Get-AzureRmCognitiveServicesAccountSkus, Get-AzureRmCognitive...
Script     0.13.1     AzureRM.Compute.Netcore             Core      {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Update-AzureRmAvailabilitySet...}
Script     0.13.1     AzureRM.Consumption.Netcore         Core      {Get-AzureRmConsumptionBudget, Get-AzureRmConsumptionMarketplace, Get-AzureRmConsumptionPriceSheet, Get-AzureRmConsumptionReservationDetail...
Script     0.13.1     AzureRM.ContainerInstance.Netcore   Core      {New-AzureRmContainerGroup, Get-AzureRmContainerGroup, Remove-AzureRmContainerGroup, Get-AzureRmContainerInstanceLog}
Script     0.13.1     AzureRM.ContainerRegistry.Netcore   Core      {New-AzureRmContainerRegistry, Get-AzureRmContainerRegistry, Update-AzureRmContainerRegistry, Remove-AzureRmContainerRegistry...}
Script     0.13.1     AzureRM.DataLakeAnalytics.Netcore   Core      {Get-AzureRmDataLakeAnalyticsDataSource, New-AzureRmDataLakeAnalyticsCatalogCredential, Remove-AzureRmDataLakeAnalyticsCatalogCredential, R...
Script     0.13.1     AzureRM.DataLakeStore.Netcore       Core      {Get-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeStoreTrustedIdProvider, Remove-AzureRmDataLakeStoreFirewallRule, Set-Azur...
Script     0.13.1     AzureRM.DevTestLabs.Netcore         Core      {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRmDtlAutoShutdownPolicy, Get-AzureRmDtlAutoStartPolicy, Get-AzureRmDtlVMsPerLabPolicy...}
Script     0.13.1     AzureRM.Dns.Netcore                 Core      {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-AzureRmDnsRecordSet, Set-AzureRmDnsRecordSet...}
Script     0.13.1     AzureRM.EventGrid.Netcore           Core      {New-AzureRmEventGridTopic, Get-AzureRmEventGridTopic, Set-AzureRmEventGridTopic, New-AzureRmEventGridTopicKey...}
Script     0.13.1     AzureRM.EventHub.Netcore            Core      {New-AzureRmEventHubNamespace, Get-AzureRmEventHubNamespace, Set-AzureRmEventHubNamespace, Remove-AzureRmEventHubNamespace...}
Script     0.13.1     AzureRM.Insights.Netcore            Core      {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-AzureRmLogProfile, Get-AzureRmLogProfile...}
Script     0.13.1     AzureRM.IotHub.Netcore              Core      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHubConsumerGroup, Get-AzureRmIotHubConnectionString, Get-AzureRmIotHubJob...}
Script     0.13.1     AzureRM.KeyVault.Netcore            Core      {Add-AzureKeyVaultCertificate, Update-AzureKeyVaultCertificate, Stop-AzureKeyVaultCertificateOperation, Get-AzureKeyVaultCertificateOperati...
Script     0.13.1     AzureRM.LogicApp.Netcore            Core      {Get-AzureRmIntegrationAccountAgreement, Get-AzureRmIntegrationAccountCallbackUrl, Get-AzureRmIntegrationAccountCertificate, Get-AzureRmInt...
Script     0.13.1     AzureRM.MachineLearning.Netcore     Core      {Move-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentAssociation, Get-AzureRmMlCommitmentPlanUsageHistory, Remove-AzureRmMlCommitme...
Script     0.13.1     AzureRM.MachineLearningCompute.N... Core      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterKey, Test-AzureRmMlOpClusterSystemServicesUpdateAvailability, Update-AzureRmMlOpClusterSyste...
Script     0.13.1     AzureRM.MarketplaceOrdering.Netcore Core      {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketplaceTerms}
Script     0.13.1     AzureRM.Media.Netcore               Core      {Sync-AzureRmMediaServiceStorageKeys, Set-AzureRmMediaServiceKey, Get-AzureRmMediaServiceKeys, Get-AzureRmMediaServiceNameAvailability...}
Script     0.13.1     AzureRM.Netcore                     Core
Script     0.13.1     AzureRM.Network.Netcore             Core      {Add-AzureRmApplicationGatewayAuthenticationCertificate, Get-AzureRmApplicationGatewayAuthenticationCertificate, New-AzureRmApplicationGate...
Script     0.13.1     AzureRM.NotificationHubs.Netcore    Core      {Get-AzureRmNotificationHub, Get-AzureRmNotificationHubAuthorizationRules, Get-AzureRmNotificationHubListKeys, Get-AzureRmNotificationHubPN...
Script     0.13.1     AzureRM.OperationalInsights.Netcore Core      {New-AzureRmOperationalInsightsAzureActivityLogDataSource, New-AzureRmOperationalInsightsCustomLogDataSource, Disable-AzureRmOperationalIns...
Script     0.13.1     AzureRM.PolicyInsights.Netcore      Core      {Get-AzureRmPolicyEvent, Get-AzureRmPolicyState, Get-AzureRmPolicyStateSummary}
Script     0.13.1     AzureRM.PowerBIEmbedded.Netcore     Core      {Remove-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollection, Get-AzureRmPowerBIWorkspaceCollectionAccessKeys, Get-Azur...
Script     0.13.1     AzureRM.Profile.Netcore             Core      {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosave, Enable-AzureRmDataCollection, Enable-AzureRmContextAutosave...}
Script     0.13.1     AzureRM.Relay.Netcore               Core      {New-AzureRmRelayNamespace, Get-AzureRmRelayNamespace, Set-AzureRmRelayNamespace, Remove-AzureRmRelayNamespace...}
Script     0.13.1     AzureRM.Resources.Netcore           Core      {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, New-AzureRmRoleAssignment...}
Script     0.13.1     AzureRM.ServiceBus.Netcore          Core      {New-AzureRmServiceBusNamespace, Get-AzureRmServiceBusNamespace, Set-AzureRmServiceBusNamespace, Remove-AzureRmServiceBusNamespace...}
Script     0.13.1     AzureRM.ServiceFabric.Netcore       Core      {Add-AzureRmServiceFabricApplicationCertificate, Add-AzureRmServiceFabricClientCertificate, Add-AzureRmServiceFabricClusterCertificate, Add...
Script     0.13.1     AzureRM.Sql.Netcore                 Core      {Get-AzureRmSqlDatabaseTransparentDataEncryption, Get-AzureRmSqlDatabaseTransparentDataEncryptionActivity, Set-AzureRmSqlDatabaseTransparen...
Script     0.13.1     AzureRM.Storage.Netcore             Core      {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-AzureRmStorageAccountKey...}
Script     0.13.1     AzureRM.StreamAnalytics.Netcore     Core      {Get-AzureRmStreamAnalyticsFunction, Get-AzureRmStreamAnalyticsDefaultFunctionDefinition, New-AzureRmStreamAnalyticsFunction, Remove-AzureR...
Script     0.13.1     AzureRM.Tags.Netcore                Core      {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Script     0.13.1     AzureRM.TrafficManager.Netcore      Core      {Disable-AzureRmTrafficManagerEndpoint, Enable-AzureRmTrafficManagerEndpoint, Set-AzureRmTrafficManagerEndpoint, Get-AzureRmTrafficManagerE...
Script     0.13.1     AzureRM.UsageAggregates.Netcore     Core      Get-UsageAggregates
Script     0.13.1     AzureRM.Websites.Netcore            Core      {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-AzureRmAppServicePlan, Remove-AzureRmAppServicePlan...}


    Directory: C:\program files\powershell\6\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   6.1.0.0    CimCmdlets                          Core      {Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, Get-CimSession...}
Manifest   1.1.0.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Diagnostics    Core      {Get-WinEvent, New-WinEvent}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path...}
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Credential...}
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Format-List, Format-Custom, Format-Table, Format-Wide...}
Manifest   6.1.0.0    Microsoft.WSMan.Management          Core      {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-WSManCredSSP, Set-WSManQuickConfig...}
Script     1.1.7.2    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability...}
Script     0.0        PSDesiredStateConfiguration         Desk      {Set-NodeManager, CheckResourceFound, Get-InnerMostErrorRecord, ValidateNoCircleInNodeResources...}
Script     6.1.0.0    PSDiagnostics                       Core      {Disable-PSTrace, Disable-PSWSManCombinedTrace, Disable-WSManTrace, Enable-PSTrace...}
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption...}
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob
```

### Environment Data

```
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Debug Output

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Server                        : Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-resource-requests: 4999
x-ms-request-id               : 3297b1a4-4509-4923-b260-3ede10f5b4a0
x-ms-correlation-request-id   : 3297b1a4-4509-4923-b260-3ede10f5b4a0
x-ms-routing-request-id       : CANADACENTRAL:20181022T072754Z:3297b1a4-4509-4923-b260-3ede10f5b4a0
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Mon, 22 Oct 2018 07:27:54 GMT

Body:
{
  "code": 400116,
  "httpStatusCode": "BadRequest",
  "message": "endpointName:blob-unknown, exceptionMessage:No valid combination of account information found. If you contact a support representative please include this correlation identifier: 4e65613c-ddfc-4386-9210-aaa96f3ab1d3, timestamp: 2018-10-22 07:27:54Z, errorcode: IH400116."
}


Set-AzureRmIotHub : Operation returned an invalid status code 'BadRequest'
At line:1 char:1
+ Set-AzureRmIotHub -ResourceGroupName "myresourcegroupname" -Name "io ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzureRmIotHub], ErrorDetailsException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.IotHub.SetAzureRmIotHub

DEBUG: AzureQoSEvent: CommandName - Set-AzureRmIotHub; IsSuccess - False; Duration - 00:00:02.0076859; Exception - Microsoft.Azure.Management.IotHub.Models.ErrorDetailsException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.IotHub.IotHubResourceOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceName, IotHubDescription iotHubDescription, String ifMatch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.IotHub.IotHubResourceOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceName, IotHubDescription iotHubDescription, String ifMatch, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.IotHub.IotHubResourceOperationsExtensions.CreateOrUpdateAsync(IIotHubResourceOperations operations, String resourceGroupName, String resourceName, IotHubDescription iotHubDescription, String ifMatch, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.IotHub.IotHubResourceOperationsExtensions.CreateOrUpdate(IIotHubResourceOperations operations, String resourceGroupName, String resourceName, IotHubDescription iotHubDescription, String ifMatch)
   at Microsoft.Azure.Commands.Management.IotHub.SetAzureRmIotHub.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 09:28:51 - SetAzureRmIotHub end processing.
DEBUG: 09:28:51 - SetAzureRmIotHub end processing.
```

**Comment by shiwani** [comment]
@HsiaoH ,I am facing th esame issue .How did you manage to solve this?

**Comment by VeryEarly** [comment]
> @HsiaoH ,I am facing th esame issue .How did you manage to solve this?

Hi @shiwani ,

since this issue was already closed, can you raise a new issue include all the required information and a "triage" label?

**Comment by shiwani** [comment]
@HsiaoH , I was able to fix this issue as in creating Namespace via C# I as passing" _" .It got solved once I removed it. Posting it here if someone can find it helpful.
