### ISSUE TITLE
Call Update-AzureRmVmss using latest Az and AzureRM modules failed with Identity operation error.

### ISSUE THREAD

**Issue by qishangg** [Azure/azure-powershell#7713]
### Script/Steps for Reproduction

```powershell
$workerVMSS = Remove-AzureRmVmssExtension -VirtualMachineScaleSet $workerVMSS -Name Initialize-Machine
$workerVMSS = Add-AzureRmVmssExtension -VirtualMachineScaleSet $workerVMSS -Name Initialize-Machine -Type CustomScript -Publisher Microsoft.Azure.Extensions -TypeHandlerVersion 2.0 -AutoUpgradeMinorVersion $True -Setting $newExtensionConfig

# This cmdlet will perform an update on the VMSS if required, or just return if the goal configuration is the same as the current configuration
$workerVMSS = Update-AzureRmVmss -ResourceGroupName $ResourceGroupName -VMScaleSetName $workerVMSS.Name -VirtualMachineScaleSet $workerVMSS
```

### Module Version

```powershell
Get-Module -ListAvailable
```

Script     0.4.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}

### Environment Data

```powershell
$PSVersionTable
```
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### Debug Output

```
DEBUG: AzureQoSEvent: CommandName - Update-AzVmss; IsSuccess - True; Duration - 00:00:02.5495138; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 11:03:22 PM - UpdateAzureRmVmss end processing.
DEBUG: 11:03:22 PM - UpdateAzureRmVmss end processing.
Update-AzureRmVmss : Identity operation for resource '/subscriptions/18b186e8-d683-4307-8779-591e27ac854a/resourceGroups/qcloudshell/providers/Microsoft.Compute/virtualMa
chineScaleSets/qcloudshell-worker-n' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","mes
sage":"The request format was unexpected, a non-UserAssigned identity type should not contain: userAssignedIdentities"}}'.'.
ErrorCode: FailedIdentityOperation
ErrorMessage: Identity operation for resource '/subscriptions/18b186e8-d683-4307-8779-591e27ac854a/resourceGroups/qcloudshell/providers/Microsoft.Compute/virtualMachineSc
aleSets/qcloudshell-worker-n' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","message":"
The request format was unexpected, a non-UserAssigned identity type should not contain: userAssignedIdentities"}}'.'.
ErrorTarget:
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : c954e0b1-6776-4066-851a-26cb7f48c3d0
At /home/qiuzi/azureBlockchainWorkbenchUpgradeTov1_5_new.ps1:393 char:15
+ ... orkerVMSS = Update-AzureRmVmss -ResourceGroupName $ResourceGroupName  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Update-AzVmss], ComputeCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss

DEBUG: AzureQoSEvent: CommandName - Update-AzVmss; IsSuccess - False; Duration - 00:00:02.5495138; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudExcepti
on: Identity operation for resource '/subscriptions/18b186e8-d683-4307-8779-591e27ac854a/resourceGroups/qcloudshell/providers/Microsoft.Compute/virtualMachineScaleSets/qc
loudshell-worker-n' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","message":"The reques
t format was unexpected, a non-UserAssigned identity type should not contain: userAssignedIdentities"}}'.'.
ErrorCode: FailedIdentityOperation
ErrorMessage: Identity operation for resource '/subscriptions/18b186e8-d683-4307-8779-591e27ac854a/resourceGroups/qcloudshell/providers/Microsoft.Compute/virtualMachineSc
aleSets/qcloudshell-worker-n' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","message":"
The request format was unexpected, a non-UserAssigned identity type should not contain: userAssignedIdentities"}}'.'.
ErrorTarget:
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : c954e0b1-6776-4066-851a-26cb7f48c3d0 ---> Microsoft.Rest.Azure.CloudException: Identity operation for resource '/subscriptions/18b186e8-d683-4307-8779-591e27ac854a/resourceGroups/qcloudshell/providers/Microsoft.Compute/virtualMachineScaleSets/qcloudshell-worker-n' failed with error 'Failed to perform resource identity operation. Status: 'BadRequest'. Response: '{"error":{"code":"BadRequest","message":"The request format was unexpected, a non-UserAssigned identity type should not contain: use
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSet parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSet parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.CreateOrUpdateAsync(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSet parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.VirtualMachineScaleSetsOperationsExtensions.CreateOrUpdate(IVirtualMachineScaleSetsOperations operations, String resourceGroupName, String vmScaleSetName, VirtualMachineScaleSet parameters)
   at Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss.<ExecuteCmdlet>b__0_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:03:37 PM - UpdateAzureRmVmss end processing.
DEBUG: 11:03:38 PM - UpdateAzureRmVmss end processing.
Unable to update the Workbench Worker VM. Please wait several minutes and try to run this script again. A description of the error can be found above.
At /home/qiuzi/azureBlockchainWorkbenchUpgradeTov1_5_new.ps1:396 char:5
+     throw "Unable to update the Workbench Worker VM. Please wait seve ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to updat...be found above.:String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to update the Workbench Worker VM. Please wait several minutes and try to run this script again. A description of the error can be found
above.
```

**Comment by markcowl** [comment]
@hyonholee this occurs when passing VMScaleSet objects to the Update cmdlet, when the scale set is using SystemAssigned ManagedServiceIdentity.  The type is serialized on the wire with:

```json
'userAssignedIdentities': {}
```

even though the input value is null.

**Comment by markcowl** [comment]
Note that this error is not particuylar to Az, it occurs in the AzureRM module as well.

**Comment by hyonholee** [comment]
This issue is fixed in the latest release.

https://github.com/Azure/azure-powershell/releases/tag/v6.13.0-November2018

**Comment by Drewm3** [comment]
Cleaning up old issues from 2016 - 2018. Please reopen this issue if it is still a concern.
