### ISSUE TITLE
New-AzureRmAks error

### ISSUE THREAD

**Issue by ibondy** [Azure/azure-powershell#7724]
### Description

When running  New-AzureRmAks -resourceGroupName mmcgf_rg -Name mycgfcluster command in Azure shell I get this error:
New-AzureRmAks : The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
At line:1 char:1
+ New-AzureRmAks mmcgf_rg -Name mycgfcluster
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzAks], PSInvalidOperationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Aks.NewAzureRmAks

I get the same error when running from my workstation PS session.
### Script/Steps for Reproduction

Open Azure PowerShell console
```powershell
New-AzureRmAks mmcgf_rg -Name mycgfcluster
```

### Module Version

```powershell
Get-Module -ListAvailable
ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     0.4.0      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCre...
Script     0.4.0      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysis...
Script     0.4.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiManagementSsoTo...
Script     0.4.0      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsight...
Script     0.4.0      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Get-AzAutomation...
Script     0.4.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBa...
Script     0.4.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEn...
Script     0.4.0      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdn...
Script     0.4.0      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServ...
Script     0.4.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, Ne...
Script     0.4.0      Az.Consumption                      Core,Desk {Get-AzConsumptionBudget, Get-AzConsumptionMarketpla...
Script     0.4.0      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-...
Script     0.4.0      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, U...
Script     0.4.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAn...
Script     0.4.0      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzData...
Script     0.4.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdow...
Script     0.4.0      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-A...
Script     0.4.0      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzE...
Script     0.4.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, S...
Script     0.4.0      Az.Insights                         Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogP...
Script     0.4.0      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup,...
Script     0.4.0      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertifi...
Script     0.4.0      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegratio...
Script     0.4.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentA...
Script     0.4.0      Az.MachineLearningCompute           Core,Desk {Get-AzMlOpCluster, Get-AzMlOpClusterKey, Test-AzMlO...
Script     0.4.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     0.4.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceK...
Script     0.4.0      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, ...
Script     0.4.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthori...
Script     0.4.0      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource...
Script     0.4.0      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyS...
Script     0.4.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIW...
Script     0.4.0      Az.Profile                          Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave...
Script     0.4.0      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecover...
Script     0.4.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheS...
Script     0.4.0      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzR...
Script     0.4.0      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, G...
Script     0.4.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespac...
Script     0.4.0      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add-AzSe...
Script     0.4.0      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New...
Script     0.4.0      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzS...
Script     0.4.0      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-...
Script     0.4.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalytic...
Script     0.4.0      Az.Tags                             Core,Desk {Remove-AzTag, Get-AzTag, New-AzTag}
Script     0.4.0      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-...
Script     0.4.0      Az.UsageAggregates                  Core,Desk Get-UsageAggregates
Script     0.4.0      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzA...
Script     0.0.0.8    AzureAD.Standard.Preview            Desk      {Set-AzureADApplicationProxyApplication, Remove-Azur...
Script     0.9.2      AzurePSDrive                        Desk
Manifest   1.0.326    MicrosoftPowerBIMgmt                Desk
Binary     1.0.326    MicrosoftPowerBIMgmt.Data           Desk      {Add-PowerBIDataset, Set-PowerBITable, New-PowerBIDa...
Binary     1.0.326    MicrosoftPowerBIMgmt.Profile        Desk      {Connect-PowerBIServiceAccount, Disconnect-PowerBISe...
Binary     1.0.326    MicrosoftPowerBIMgmt.Reports        Desk      {Get-PowerBIReport, Export-PowerBIReport, Get-PowerB...
Binary     1.0.326    MicrosoftPowerBIMgmt.Workspaces     Desk      {Get-PowerBIWorkspace, Add-PowerBIWorkspaceUser, Rem...
Script     0.9.2      PSCloudShellUtility                 Desk      {Enter-AzVM, Get-AzCommand, Invoke-AzVMCommand, Enab...
Binary     0.8.1      SHiPS                               Desk
Script     21.0.17279 SqlServer                           Desk      {Add-RoleMember, Add-SqlAvailabilityDatabase, Add-Sq...


    Directory: /opt/microsoft/powershell/6/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Manifest   1.1.0.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty, Joi...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, Set-ExecutionP...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Format-List, Format-Custom, Format-Table, Format-Wi...
Script     1.1.7.2    PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider, Get...
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Find-R...
Script     0.0        PSDesiredStateConfiguration         Desk      {Update-LocalConfigManager, Get-PSTopConfigurationNa...
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler,...
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Linux 4.15.0-1025-azure #26~16.04.1-Ubuntu SMP Tue Sep 25 11:09:50 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Debug Output

```
DEBUG: 4:10:43 PM - NewAzureRmAks begin processing with ParameterSet 'defaultParameterSet'.
DEBUG: 4:10:43 PM - using account id 'MSI@50342'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/cf63decd-c04a-4714-8b5f-8a84284c3ce2/resourceGroups/mmcgf_rg/providers/Microsoft.ContainerService/managedClusters/mycgfcluster?api-version=2017-08-31

Headers:
x-ms-client-request-id        : a484aa63-10d4-4f6a-ae09-1379b8397154
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 5b7403be-c29d-4580-922b-27b1dd244edb
x-ms-correlation-request-id   : 5b7403be-c29d-4580-922b-27b1dd244edb
x-ms-routing-request-id       : WESTUS:20181101T161043Z:5b7403be-c29d-4580-922b-27b1dd244edb
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 01 Nov 2018 16:10:43 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.ContainerService/managedClusters/mycgfcluster' under resource group 'mmcgf_rg' was not found."
  }
}


DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/cf63decd-c04a-4714-8b5f-8a84284c3ce2/resourcegroups/mmcgf_rg?api-version=2016-09-01

Headers:
x-ms-client-request-id        : 1bd92a16-2df7-4956-ba41-9f973c1d20b9
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id               : bb03f8ab-30b3-49a5-bdc7-750d68532433
x-ms-correlation-request-id   : bb03f8ab-30b3-49a5-bdc7-750d68532433
x-ms-routing-request-id       : WESTUS:20181101T161043Z:bb03f8ab-30b3-49a5-bdc7-750d68532433
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 01 Nov 2018 16:10:42 GMT

Body:
{
  "id": "/subscriptions/cf63decd-c04a-4714-8b5f-8a84284c3ce2/resourceGroups/mmcgf_rg",
  "name": "mmcgf_rg",
  "location": "westus2",
  "properties": {
    "provisioningState": "Succeeded"
  }
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/cf63decd-c04a-4714-8b5f-8a84284c3ce2/providers/Microsoft.ContainerService?api-version=2016-09-01

Headers:
x-ms-client-request-id        : 3b87d5bd-f1b9-47af-bfba-4987bfd57d4b
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11998
x-ms-request-id               : 887f5cb7-c294-4c3e-a03d-37c239e24ee0
x-ms-correlation-request-id   : 887f5cb7-c294-4c3e-a03d-37c239e24ee0
x-ms-routing-request-id       : WESTUS:20181101T161043Z:887f5cb7-c294-4c3e-a03d-37c239e24ee0
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Thu, 01 Nov 2018 16:10:43 GMT

Body:
{
  "id": "/subscriptions/cf63decd-c04a-4714-8b5f-8a84284c3ce2/providers/Microsoft.ContainerService",
  "namespace": "Microsoft.ContainerService",
  "authorization": {
    "applicationId": "7319c514-987d-4e9b-ac3d-d38c4f427f4c",
    "roleDefinitionId": "1b4a0c7f-2217-416f-acfa-cf73452fdc1c",
    "managedByRoleDefinitionId": "8e3af657-a8ff-443c-a75c-2fe8c4bcb635"
  },
  "resourceTypes": [
    {
      "resourceType": "containerServices",
      "locations": [
        "Japan East",
        "Central US",
        "East US 2",
        "Japan West",
        "East Asia",
        "South Central US",
        "Australia East",
        "Australia Southeast",
        "Brazil South",
        "Southeast Asia",
        "West US",
        "North Central US",
        "West Europe",
        "North Europe",
        "East US",
        "UK West",
        "UK South",
        "West Central US",
        "West US 2",
        "South India",
        "Central India",
        "West India",
        "Canada East",
        "Canada Central",
        "Korea South",
        "Korea Central"
      ],
      "apiVersions": [
        "2017-07-01",
        "2017-01-31",
        "2016-09-30",
        "2016-03-30"
      ],
      "capabilities": "None"
    },
    {
      "resourceType": "managedClusters",
      "locations": [
        "East US",
        "West Europe",
        "Central US",
        "Canada Central",
        "Canada East",
        "UK South",
        "West US",
        "West US 2",
        "Australia East",
        "North Europe",
        "Japan East",
        "East US 2",
        "Southeast Asia",
        "UK West"
      ],
      "apiVersions": [
        "2018-03-31",
        "2017-08-31"
      ],
      "capabilities": "None"
    },
    {
      "resourceType": "locations",
      "locations": [],
      "apiVersions": [
        "2017-08-31",
        "2017-01-31",
        "2016-09-30",
        "2016-03-30",
        "2015-11-01-preview"
      ]
    },
    {
      "resourceType": "locations/operationresults",
      "locations": [
        "East US",
        "West Europe",
        "Central US",
        "UK West",
        "West Central US",
        "West US 2",
        "South India",
        "Central India",
        "West India",
        "Canada East",
        "Canada Central",
        "Korea South",
        "Korea Central",
        "UK South",
        "Australia East",
        "Australia Southeast",
        "North Europe",
        "Japan East",
        "East US 2",
        "Southeast Asia"
      ],
      "apiVersions": [
        "2018-10-31",
        "2017-08-31",
        "2016-03-30"
      ]
    },
    {
      "resourceType": "locations/operations",
      "locations": [
        "Japan East",
        "Central US",
        "East US 2",
        "Japan West",
        "East Asia",
        "South Central US",
        "Australia East",
        "Australia Southeast",
        "Brazil South",
        "Southeast Asia",
        "West US",
        "North Central US",
        "West Europe",
        "North Europe",
        "East US",
        "UK West",
        "UK South",
        "West Central US",
        "West US 2",
        "South India",
        "Central India",
        "West India",
        "Canada East",
        "Canada Central",
        "Korea South",
        "Korea Central"
      ],
      "apiVersions": [
        "2017-07-01",
        "2017-01-31",
        "2016-09-30",
        "2016-03-30"
      ]
    },
    {
      "resourceType": "operations",
      "locations": [],
      "apiVersions": [
        "2018-10-31",
        "2018-03-31",
        "2017-08-31",
        "2017-07-01",
        "2017-01-31",
        "2016-09-30",
        "2016-03-30",
        "2015-11-01-preview"
      ]
    },
    {
      "resourceType": "locations/orchestrators",
      "locations": [
        "East US",
        "West Europe",
        "Central US",
        "Canada East",
        "Canada Central",
        "UK South",
        "UK West",
        "West US",
        "West US 2",
        "Australia East",
        "North Europe",
        "Japan East",
        "East US 2",
        "Southeast Asia"
      ],
      "apiVersions": [
        "2017-09-30"
      ]
    }
  ],
  "registrationState": "Registered"
}


DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/cf63decd-c04a-4714-8b5f-8a84284c3ce2/resourceGroups/mmcgf_rg/providers/Microsoft.ContainerService/managedClusters/mycgfcluster?api-version=2017-08-31

Headers:
x-ms-client-request-id        : 7afbf7d4-a315-4111-8a3b-c7abf66c3a08
Accept-Language               : en-US

Body:
{
  "properties": {
    "dnsPrefix": "mycgfclust-mmcgfrg-cf63de",
    "kubernetesVersion": "1.8.1",
    "agentPoolProfiles": [
      {
        "name": "default",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "osDiskSizeGB": 0,
        "dnsPrefix": "mycgfclust-mmcgfrg-cf63de"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/QD+eeL+DAhQ8dvIP1V7NQ3IJRvKFWh2OHauX/JZcFcdeiatGjdjwIzEu0ET1eRxQYQbzlHYfrXa8ulb/ObjQR9RFWxbx+JIzVJM3QSCG9EEHYgAEOQCJU4o/op5JjvBWjcyulnc0KyUoz343WtchzBWRThp3SSf4yFLQcx3QmAvEU55jWBU3qcqZkWCUQyRr56YgBSxRSS4kuBsvuu3N96Qh2oReeH7sfvB8UqnvPBB0513g5uQTZJDgdMU5kZBvBOBKQmHlrQ1ojZSZ5biFzwwpCJiqp/jAUXs5p+CAiWBSTVsjO49RUKSHozbWjPsyTIfxTUVuVY4EFvGjCFoj"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "e48bf729-9af4-48c7-a10b-d909498bfcfb",
      "secret": "f59fdfa5c761a2cc22ff"
    }
  },
  "location": "westus2"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 9d3112dd-c28f-4e96-800d-c6bbbbbc1678
x-ms-request-id               : 378ee800-2e00-44fb-8600-bcbafe72334d
Strict-Transport-Security     : max-age=31536000; includeSubDomains
Server                        : nginx
x-ms-routing-request-id       : WESTUS:20181101T161044Z:9d3112dd-c28f-4e96-800d-c6bbbbbc1678
X-Content-Type-Options        : nosniff
Date                          : Thu, 01 Nov 2018 16:10:44 GMT

Body:
{
  "code": "InvalidParameter",
  "message": "The value of parameter orchestratorProfile.OrchestratorVersion is invalid.",
  "target": "orchestratorProfile.OrchestratorVersion"
}


New-AzureRmAks : The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
At line:1 char:1
+ New-AzureRmAks -resourceGroupName mmcgf_rg -Name mycgfcluster
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzAks], PSInvalidOperationException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Aks.NewAzureRmAks

DEBUG: AzureQoSEvent: CommandName - New-AzAks; IsSuccess - False; Duration - 00:00:01.7302033; Exception - System.Management.Automation.PSInvalidOperationException: The value of parameter orchestratorProfile.OrchestratorVersion is invalid. ---> Microsoft.Rest.Azure.CloudException: The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
   at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceName, ManagedCluster parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String resourceName, ManagedCluster parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperationsExtensions.CreateOrUpdateAsync(IManagedClustersOperations operations, String resourceGroupName, String resourceName, ManagedCluster parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperationsExtensions.CreateOrUpdate(IManagedClustersOperations operations, String resourceGroupName, String resourceName, ManagedCluster parameters)
   at Microsoft.Azure.Commands.Aks.NewAzureRmAks.<ExecuteCmdlet>b__4_0()
   at Microsoft.Azure.Commands.Aks.KubeCmdletBase.RunCmdLet(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Aks.KubeCmdletBase.RunCmdLet(Action action)
   at Microsoft.Azure.Commands.Aks.NewAzureRmAks.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:10:45 PM - NewAzureRmAks end processing.
DEBUG: 4:10:45 PM - NewAzureRmAks end processing.
```

**Comment by markcowl** [comment]
@mboersma Can you take a look?  Perhaps a missing required value?

**Comment by ibondy** [comment]
Any update on this? We are unable to deploy AKS via PowerShell? Should we be using Azure CLI instead?

**Comment by cormacpayne** [comment]
@ibondy we will update the default Kubernetes version used in our AKS cmdlets in the upcoming sprint. A temporary workaround can be found in [this comment](https://github.com/Azure/azure-powershell/issues/9573#issuecomment-509823626). I'm going to close this issue in favor of the one linked previously and we will track the status of the fix to the default version there.
