### ISSUE TITLE
Get-AzureRmStorageAccount - "Unable to deserialize the response" - Unsupported Storage Account Type

### ISSUE THREAD

**Issue by shailesh91** [Azure/azure-powershell#7780]
### Description

When I try to list all Azure Storage Account using Get-AzureRmStorageAccount I get the following errror
"Unable to deserialize the response.". On running the following command with "Debug" switch I noticed that the module was not able to serliaze "FileStorage" Storage account type which is still in preview.

Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value
"FileStorage" to type 'System.Nullable`1[Microsoft.Azure.Management.Storage.Models.Kind]'. Path '', line 1, position 40038. ---> System.ArgumentException:
Requested value 'FileStorage' was not found.

### Script/Steps for Reproduction

```powershell
Get-AzureRmStorageAccount
```

### Module Version

```powershell
Get-Module AzureRM -ListAvailable
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.12.0     AzureRM
```

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.14393.2248
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2248
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
Get-AzureRmStorageAccount : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmStorageAccount -Debug | Where-Object{$_.StorageAccountName ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccount], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmStorageAccount; IsSuccess - False; Duration - 00:00:07.1667259; Exception -
Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonSerializationException: Error converting value
"FileStorage" to type 'System.Nullable`1[Microsoft.Azure.Management.Storage.Models.Kind]'. Path '', line 1, position 40038. ---> System.ArgumentException:
Requested value 'FileStorage' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName(String enumText, Boolean isNullable, Type t)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object
existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object
existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty
containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member,
Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter,
JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract,
JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member,
 JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<ListWithHttpMessagesAsync>d__10.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.Storage.StorageAccountsOperations.<ListWithHttpMessagesAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.<ListAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.StorageAccountsOperationsExtensions.List(IStorageAccountsOperations operations)
   at Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:58:59 AM - GetAzureStorageAccountCommand end processing.
```

**Comment by blueww** [comment]
Currently, Storage account Kind "FileStorage" is still not supported by official Azure Powershell release. (It also can't create this kind Account.)

You can install the latest version of preview module of AzureRm.Storage module, the latest preview module support FileStorage Kind.
https://www.powershellgallery.com/packages/AzureRM.Storage/6.0.0-preview

**Comment by maddieclayton** [comment]
@blueww How long until this support comes into stable? We shouldn't have the cmdlet error for customers in stable, even if they are creating the new type of storage account in a different platform.

**Comment by blueww** [comment]
@maddieclayton 

Add Try catch might not be very good.
It will make Get-AzureRmStorage Account Can't return the correct output, but fail quietly.

Upgrade to latest SDK might be good. As the Storage Account is wrappered  in PowerShell, I think it won't take breaking change.

**Comment by blueww** [comment]
@maddieclayton 
I find upgrade SRP SDK will still take breaking, since the Get Global Storage Usage API is remove in new API version. 
So with upgrade SRP SDK, `Get-AzureRmStorageUsage` parameter `-Location `change from optional to mandatory, this is a breaking change.

How do you think we should handle this breaking? Following are 3 options, which do you prefer?
1. Don't upgrade SRP SDK now, and upgrade it until a version allows breaking.
2. Upgrade SRP SDK, and take the breaking change that make `Get-AzureRmStorageUsage` parameter `-Location `change from optional to mandatory
3. Upgrade SRP SDK, Still allow user to run  `Get-AzureRmStorageUsage`  without parameter `-Location`, but report error.

**Comment by maddieclayton** [comment]
@blueww If you can, please open a PR to add a breaking change warning to the -Location parameter so we can get it in for the 11/20 release: https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-attribute-help.md

**Comment by blueww** [comment]
@maddieclayton 
PR for breaking warning is added in https://github.com/Azure/azure-powershell/pull/7834

**Comment by blueww** [comment]
The PR is merged and this will be fixed in Az 1.0 release.

**Comment by grecoe** [comment]
This still seems like an issue. I had an exception with Get-AzureRmStorageAccount not specifying any parameters. Found this post and looked at my version:

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.13.1     AzureRM
Script     5.7.0      AzureRM

So, thought I might be behind, even though the website didn't appear like it was and after an Install-Module -AllowClobber -Force I still have: 

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.13.1     AzureRM
Script     5.7.0      AzureRM

I still have an issue with several of my subs returning anything I can use. Now, mind you a couple of subs this was fine, but what I'm seeing on others:

Get-AzureRmStorageAccount : Unable to deserialize the response.
At line:1 char:1
+ Get-AzureRmStorageAccount
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmStorageAccount], SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Management.Storage.GetAzureStorageAccountCommand

**Comment by blueww** [comment]
@grecoe 

It seems the module on you machine is old, and not contain the fix.

You can install the latest Azure powershell by "install-module Az" 
(And the latest Storage module names "Az.Storage", the new cmdlet name is Get-AzStorageAccount )

Please note:
- You need remove the old modules AzureRm from you machine before install Az module.
For Powershell 5.1, you can just delete AzureRm* from C:\Program Files\WindowsPowerShell\Modules
- To check if you have any AzureRM.* modules installed on your machine, run the following command:
`Get-Module -Name AzureRm.* -ListAvailable`

**Comment by blueww** [comment]
This issue will not repro on latest Az.Storage module.

**Comment by marcosdiasfte** [comment]
@blueww 

OK, got it. Thank you for your reply and clarification.
