### ISSUE TITLE
Unable do Deploy from TFS 2015.4 to Web apps in West US

### ISSUE THREAD

**Issue by aghosh12** [Azure/azure-powershell#7895]
Description of the issue:

Unable do Deploy from TFS 2015.4 to Web apps in West US.
We are having 60 Web Apps to deploy and these are failing intermittently while using 'Azure Web App' Deployment task.
error:

```
2018-11-21T16:54:41.6505220Z ##[warning]System.ArgumentException: Requested value 'Isolated' was not found.
2018-11-21T16:54:41.6505220Z ##[warning]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2018-11-21T16:54:41.6505220Z ##[warning]   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
2018-11-21T16:54:41.6505220Z ##[warning]   at Microsoft.WindowsAzure.Management.WebSites.WebSpaceOperationsExtensions.ListWebSites(IWebSpaceOperations operations, String webSpaceName, WebSiteListParameters parameters)
2018-11-21T16:54:41.6505220Z ##[warning]   at Microsoft.WindowsAzure.Commands.Utilities.Websites.Services.WebSitesManagementExtensionMethods.GetFromAzure(IWebSiteManagementClient client, String website)


</Error>
2018-11-21T16:55:10.6398803Z ##[error]System.Exception: Conflict: Website with given name dv2-usw-devicemetadatainfo-api already exists.
2018-11-21T16:55:10.6398803Z ##[debug]AzureQoSEvent: CommandName - New-AzureWebsite; IsSuccess - False; Duration - 00:00:28.9540403; Exception - System.Exception: Conflict: Website with given name dv2-usw-devicemetadatainfo-api already exists.;
2018-11-21T16:55:11.1555399Z ##[debug]Finish sending metric.
2018-11-21T16:55:11.1715639Z ##[debug]11:55:11 AM - NewAzureWebsiteCommand end processing.
2018-11-21T16:55:11.1715639Z ##[debug]11:55:11 AM - NewAzureWebsiteCommand end processing.
```

Action taken so far:

1. - We have raised it to the MS support Azure team(118102325000310 ) who confirms that they are not supporting the commands like Get-AzureWebSite and they recommend using the ARM endpoint.
2. - We have tried the same yet we get the same intermittent errors.They have involved the TFS on premise team as well who have provided few workarounds using the azure powershell task in TFS to deploy the app.The solution hasn't yet worked.
3. We have 4 other environments  in West US and we are not facing this issue there.

Ask from MS:
Need a solution to be able to deploy the web apps from TFS 2015.4 to this affected environment.
There has been a change done by MS to this subscription only which is causing this error.

**Comment by cormacpayne** [comment]
@aghosh12 would you mind providing the full script that you are running when you are switching over to ARM? After this, would you mind providing the corresponding exceptions that you are seeing?

**Comment by maddieclayton** [comment]
Closing for inactivity - please reopen if you are still seeing an issue, and provide the requested information above.
