### ISSUE TITLE
Set-AzureRmVirtualNetwork unclear error when trying to rename VNet

### ISSUE THREAD

**Issue by Agazoth** [Azure/azure-powershell#7920]
### Description

Unclear error returned when trying to rename a VNet with the Set-AzureRMVirtualNetwork. I am aware that renaming VNets is not supported (the name is part of the URI) but it seems the formatting of the error string is not resolved correctly.

### Script/Steps for Reproduction

```powershell
$vnet = Get-AzureRMVirtualNetwork -Name CurrentName -ResourceGroupName VNetRG
$vnet.Name = 'NewName'
$vnet | Set-AzureRMVirtualNetwork

Set-AzureRmVirtualNetwork : Resource '{0}' not found
At line:1 char:9
+ $vnet | Set-AzureRmVirtualNetwork -Verbose
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzureRmVirtualNetwork], ArgumentException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkCommand

```

### Module Version

```powershell
Get-Module -ListAvailable
ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     0.0.5      AxTools                             Desk      Get-StringArray
Script     0.13.1     Azure.AnalysisServices.Netcore      Core      {Add-AzureAnalysisServicesAccount, Restart-Azure...
Script     0.13.1     Azure.Storage.Netcore               Core      {Get-AzureStorageTable, New-AzureStorageTableSAS...
Script     0.13.1     AzureRM.Aks.Netcore                 Core      {Get-AzureRmAks, New-AzureRmAks, Remove-AzureRmA...
Script     0.13.1     AzureRM.AnalysisServices.Netcore    Core      {Resume-AzureRmAnalysisServicesServer, Suspend-A...
Script     0.13.1     AzureRM.ApiManagement.Netcore       Core      {Add-AzureRmApiManagementRegion, Get-AzureRmApiM...
Script     0.13.1     AzureRM.ApplicationInsights.Netcore Core      {Get-AzureRmApplicationInsights, New-AzureRmAppl...
Script     0.13.1     AzureRM.Automation.Netcore          Core      {Get-AzureRMAutomationHybridWorkerGroup, Get-Azu...
Script     0.13.1     AzureRM.Batch.Netcore               Core      {Remove-AzureRmBatchAccount, Get-AzureRmBatchAcc...
Script     0.13.1     AzureRM.Billing.Netcore             Core      {Get-AzureRmBillingInvoice, Get-AzureRmBillingPe...
Script     0.13.1     AzureRM.Cdn.Netcore                 Core      {Get-AzureRmCdnProfile, Get-AzureRmCdnProfileSso...
Script     0.13.1     AzureRM.CognitiveServices.Netcore   Core      {Get-AzureRmCognitiveServicesAccount, Get-AzureR...
Script     0.13.1     AzureRM.Compute.Netcore             Core      {Remove-AzureRmAvailabilitySet, Get-AzureRmAvail...
Script     0.13.1     AzureRM.Consumption.Netcore         Core      {Get-AzureRmConsumptionBudget, Get-AzureRmConsum...
Script     0.13.1     AzureRM.ContainerInstance.Netcore   Core      {New-AzureRmContainerGroup, Get-AzureRmContainer...
Script     0.13.1     AzureRM.ContainerRegistry.Netcore   Core      {New-AzureRmContainerRegistry, Get-AzureRmContai...
Script     0.13.1     AzureRM.DataLakeAnalytics.Netcore   Core      {Get-AzureRmDataLakeAnalyticsDataSource, New-Azu...
Script     0.13.1     AzureRM.DataLakeStore.Netcore       Core      {Get-AzureRmDataLakeStoreTrustedIdProvider, Remo...
Script     0.13.1     AzureRM.DevTestLabs.Netcore         Core      {Get-AzureRmDtlAllowedVMSizesPolicy, Get-AzureRm...
Script     0.13.1     AzureRM.Dns.Netcore                 Core      {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordCo...
Script     0.13.1     AzureRM.EventGrid.Netcore           Core      {New-AzureRmEventGridTopic, Get-AzureRmEventGrid...
Script     0.13.1     AzureRM.EventHub.Netcore            Core      {New-AzureRmEventHubNamespace, Get-AzureRmEventH...
Script     0.13.1     AzureRM.Insights.Netcore            Core      {Get-AzureRmMetricDefinition, Get-AzureRmMetric,...
Script     0.13.1     AzureRM.IotHub.Netcore              Core      {Add-AzureRmIotHubKey, Get-AzureRmIotHubEventHub...
Script     0.13.1     AzureRM.KeyVault.Netcore            Core      {Add-AzureKeyVaultCertificate, Update-AzureKeyVa...
Script     0.13.1     AzureRM.LogicApp.Netcore            Core      {Get-AzureRmIntegrationAccountAgreement, Get-Azu...
Script     0.13.1     AzureRM.MachineLearning.Netcore     Core      {Move-AzureRmMlCommitmentAssociation, Get-AzureR...
Script     0.13.1     AzureRM.MachineLearningCompute.N... Core      {Get-AzureRmMlOpCluster, Get-AzureRmMlOpClusterK...
Script     0.13.1     AzureRM.MarketplaceOrdering.Netcore Core      {Get-AzureRmMarketplaceTerms, Set-AzureRmMarketp...
Script     0.13.1     AzureRM.Media.Netcore               Core      {Sync-AzureRmMediaServiceStorageKeys, Set-AzureR...
Script     0.13.1     AzureRM.Netcore                     Core
Script     0.13.1     AzureRM.Network.Netcore             Core      {Add-AzureRmApplicationGatewayAuthenticationCert...
Script     0.13.1     AzureRM.NotificationHubs.Netcore    Core      {Get-AzureRmNotificationHub, Get-AzureRmNotifica...
Script     0.13.1     AzureRM.OperationalInsights.Netcore Core      {New-AzureRmOperationalInsightsAzureActivityLogD...
Script     0.13.1     AzureRM.PolicyInsights.Netcore      Core      {Get-AzureRmPolicyEvent, Get-AzureRmPolicyState,...
Script     0.13.1     AzureRM.PowerBIEmbedded.Netcore     Core      {Remove-AzureRmPowerBIWorkspaceCollection, Get-A...
Script     0.13.1     AzureRM.Profile.Netcore             Core      {Disable-AzureRmDataCollection, Disable-AzureRmC...
Script     0.13.1     AzureRM.Relay.Netcore               Core      {New-AzureRmRelayNamespace, Get-AzureRmRelayName...
Script     0.13.1     AzureRM.Resources.Netcore           Core      {Get-AzureRmProviderOperation, Remove-AzureRmRol...
Script     0.13.1     AzureRM.ServiceBus.Netcore          Core      {New-AzureRmServiceBusNamespace, Get-AzureRmServ...
Script     0.13.1     AzureRM.ServiceFabric.Netcore       Core      {Add-AzureRmServiceFabricApplicationCertificate,...
Script     0.13.1     AzureRM.Sql.Netcore                 Core      {Get-AzureRmSqlDatabaseTransparentDataEncryption...
Script     0.13.1     AzureRM.Storage.Netcore             Core      {Get-AzureRmStorageAccount, Get-AzureRmStorageAc...
Script     0.13.1     AzureRM.StreamAnalytics.Netcore     Core      {Get-AzureRmStreamAnalyticsFunction, Get-AzureRm...
Script     0.13.1     AzureRM.Tags.Netcore                Core      {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Script     0.13.1     AzureRM.TrafficManager.Netcore      Core      {Disable-AzureRmTrafficManagerEndpoint, Enable-A...
Script     0.13.1     AzureRM.UsageAggregates.Netcore     Core      Get-UsageAggregates
Script     0.13.1     AzureRM.Websites.Netcore            Core      {Get-AzureRmAppServicePlan, Set-AzureRmAppServic...
Script     0.0.6      Get-PSGoodFirstIssue                Desk      Get-PSGoodFirstIssue
Script     1.1.3      Plaster                             Desk      {Invoke-Plaster, New-PlasterManifest, Get-Plaste...
Script     0.12.0     platyPS                             Desk      {New-MarkdownHelp, Get-MarkdownMetadata, New-Ext...
Script     0.7.3      posh-git                            Desk      {Invoke-NullCoalescing, Add-PoshGitToProfile, Ge...
Script     4.7.4      psake                               Desk      {Invoke-psake, Invoke-Task, Get-PSakeScriptTasks...


    Directory: C:\program files\powershell\6-preview\Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.0.0      AxAzureBlueprint                    Desk      {Connect-AzureBlueprint, Get-AzureBlueprint, Get...
Manifest   6.1.0.0    CimCmdlets                          Core      {Get-CimAssociatedInstance, Get-CimClass, Get-Ci...
Manifest   1.2.2.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Diagnostics    Core      {Get-WinEvent, New-WinEvent}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-ItemProperty,...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Crede...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Format-List, Format-Custom, Format-Table, Forma...
Manifest   6.1.0.0    Microsoft.WSMan.Management          Core      {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-...
Script     1.2.2      PackageManagement                   Desk      {Find-Package, Get-Package, Get-PackageProvider,...
Script     2.0.1      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-Module, Fi...
Script     0.0        PSDesiredStateConfiguration         Desk      {StrongConnect, ValidateNoCircleInNodeResources,...
Script     6.1.0.0    PSDiagnostics                       Core      {Disable-PSTrace, Disable-PSWSManCombinedTrace, ...
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHand...
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.2.0-preview.2
PSEdition                      Core
GitCommitId                    6.2.0-preview.2
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Debug Output

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/a5f49762-bed4-4c94-881a-bf71cc2f485c/resourceGroups/VNetRG/providers/Microsoft.Network/virtualNetworks/NewName?api-version=2018-04-01

Headers:
x-ms-client-request-id        : 3f7c7594-fb01-4037-b95d-eb987f64b10e
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : de0c2195-a915-4fba-8c81-7787eff4b42c
x-ms-correlation-request-id   : de0c2195-a915-4fba-8c81-7787eff4b42c
x-ms-routing-request-id       : WESTEUROPE:20181127T101834Z:de0c2195-a915-4fba-8c81-7787eff4b42c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Date                          : Tue, 27 Nov 2018 10:18:34 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Network/virtualNetworks/NewName' under resource group 'VNetRG' was not found."
  }
}


Set-AzureRmVirtualNetwork : Resource '{0}' not found
At line:1 char:9
+ $vnet | Set-AzureRmVirtualNetwork -Verbose
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzureRmVirtualNetwork], ArgumentException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkCommand

DEBUG: AzureQoSEvent: CommandName - Set-AzureRmVirtualNetwork; IsSuccess - False; Duration - 00:00:00.3155148; Exception - System.ArgumentException: Resource '{0}' not found
   at Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkCommand.Execute()
   at Microsoft.Azure.Commands.Network.NetworkBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:18:35 AM - SetAzureVirtualNetworkCommand end processing.
DEBUG: 11:18:35 AM - SetAzureVirtualNetworkCommand end processing.
```

**Comment by cormacpayne** [comment]
@Agazoth Hey Axel, it looks like you're using the `AzureRM.Netcore` modules. We have deprecated these modules in favor of the `Az` modules, which will GA next month. Would you mind uninstalling all `AzureRM.Netcore` modules on your box, installing `Az` instead, and checking if the incorrect resource string still pops up?

**Comment by maddieclayton** [comment]
Closing - please reopen if you are still seeing this issue in Az.
