### ISSUE TITLE
exception error while enabling managed identity service 

### ISSUE THREAD

**Issue by anoopkv39** [Azure/azure-powershell#7960]
### Description

Trying to enable Managed Identity Service for my function app using PowerShell. Application is hosted on ASE V2

### Script/Steps for Reproduction

```powershell

Set-AzureRmWebApp -AssignIdentity $True -Name $AppName -ResourceGroupName $RGName
```

### Module Version

```powershell
Get-Module -ListAvailable

Version     Name
-------     ----
1.0.0.0     ActiveDirectory
1.0.0.0     ADRMS
1.0.0.0     AppLocker
1.0         BestPractices
1.0.0.0     BitsTransfer
1.0.0.0     CimCmdlets
1.0.0.0     ISE
1.0.1.0     Microsoft.PowerShell.Archive
3.0.0.0     Microsoft.PowerShell.Diagnostics
3.0.0.0     Microsoft.PowerShell.Host
1.0.0.0     Microsoft.PowerShell.LocalAccounts
3.1.0.0     Microsoft.PowerShell.Management
1.0         Microsoft.PowerShell.ODataUtils
3.0.0.0     Microsoft.PowerShell.Security
3.1.0.0     Microsoft.PowerShell.Utility
3.0.0.0     Microsoft.WSMan.Management
1.0.0.0     NetworkSwitchManager
1.1         PSDesiredStateConfiguration
1.0.0.0     PSDiagnostics
1.1.0.0     PSScheduledJob
2.0.0.0     PSWorkflow
1.0.0.0     PSWorkflowUtility
1.0.0.0     ServerManager
2.0.0.0     SoftwareInventoryLogging
1.0.0.0     TroubleshootingPack
1.0.0.0     WebAdministration
2.13.1.0    AADRM
0.5.1       Azure.AnalysisServices
4.3.0       Azure.Storage
2.0.1.10    AzureAD
2.0.1.11    AzureADPreview
6.2.1       AzureRM
0.6.8       AzureRM.AnalysisServices
6.1.0       AzureRM.ApiManagement
0.1.4       AzureRM.ApplicationInsights
5.0.0       AzureRM.Automation
4.0.5       AzureRM.Backup
4.1.0       AzureRM.Batch
0.14.2      AzureRM.Billing
5.0.0       AzureRM.Cdn
0.9.5       AzureRM.CognitiveServices
5.1.0       AzureRM.Compute
0.3.3       AzureRM.Consumption
0.2.6       AzureRM.ContainerInstance
1.0.5       AzureRM.ContainerRegistry
5.0.0       AzureRM.DataFactories
0.5.5       AzureRM.DataFactoryV2
5.0.0       AzureRM.DataLakeAnalytics
6.0.1       AzureRM.DataLakeStore
4.0.5       AzureRM.DevTestLabs
5.0.0       AzureRM.Dns
0.3.3       AzureRM.EventGrid
0.6.4       AzureRM.EventHub
4.1.3       AzureRM.HDInsight
5.0.0       AzureRM.Insights
3.1.3       AzureRM.IotHub
5.0.1       AzureRM.KeyVault
4.0.4       AzureRM.LogicApp
0.18.0      AzureRM.MachineLearning
0.4.3       AzureRM.MachineLearningCompute
0.2.2       AzureRM.MarketplaceOrdering
0.10.0      AzureRM.Media
6.2.0       AzureRM.Network
5.0.0       AzureRM.NotificationHubs
5.0.1       AzureRM.OperationalInsights
4.1.5       AzureRM.PowerBIEmbedded
5.2.0       AzureRM.profile
4.1.3       AzureRM.RecoveryServices
4.1.3       AzureRM.RecoveryServices.Backup
0.2.5       AzureRM.RecoveryServices.SiteRecovery
5.0.0       AzureRM.RedisCache
0.3.4       AzureRM.Relay
6.1.0       AzureRM.Resources
0.16.5      AzureRM.Scheduler
0.6.5       AzureRM.ServiceBus
0.3.6       AzureRM.ServiceFabric
4.6.0       AzureRM.Sql
5.0.0       AzureRM.Storage
4.0.5       AzureRM.StreamAnalytics
4.0.2       AzureRM.Tags
4.0.5       AzureRM.TrafficManager
4.0.3       AzureRM.UsageAggregates
5.0.2       AzureRM.Websites
16.0.8212.0 Microsoft.Online.SharePoint.PowerShell
1.1.183.8   MSOnline
1.0.51      MSOnlineExt
1.0.0.1     PackageManagement
1.0.0.1     PowerShellGet
2.26.1805.1 SharePointPnPPowerShellOnline
0.5.0       Azure.AnalysisServices
0.5.0       AzureRM.AnalysisServices
5.0.1       AzureRM.ApiManagement
0.1.0       AzureRM.ApplicationInsights
4.0.0       AzureRM.Automation
4.0.1       AzureRM.Backup
4.0.1       AzureRM.Batch
0.14.0      AzureRM.Billing
4.0.0       AzureRM.Cdn
0.9.0       AzureRM.CognitiveServices
4.0.1       AzureRM.Compute
0.3.0       AzureRM.Consumption
0.1.0       AzureRM.ContainerInstance
0.3.0       AzureRM.ContainerRegistry
4.0.1       AzureRM.DataFactories
0.3.0       AzureRM.DataFactoryV2
4.0.0       AzureRM.DataLakeAnalytics
5.0.0       AzureRM.DataLakeStore
4.0.0       AzureRM.DevTestLabs
4.0.0       AzureRM.Dns
0.2.0       AzureRM.EventGrid
0.5.0       AzureRM.EventHub
4.0.1       AzureRM.HDInsight
4.0.0       AzureRM.Insights
3.0.0       AzureRM.IotHub
4.0.1       AzureRM.KeyVault
4.0.0       AzureRM.LogicApp
0.16.0      AzureRM.MachineLearning
0.2.0       AzureRM.MachineLearningCompute
0.2.0       AzureRM.MarketplaceOrdering
0.8.0       AzureRM.Media
5.0.0       AzureRM.Network
4.0.0       AzureRM.NotificationHubs
4.0.0       AzureRM.OperationalInsights
4.0.0       AzureRM.PowerBIEmbedded
4.0.0       AzureRM.Profile
4.0.1       AzureRM.RecoveryServices
4.0.1       AzureRM.RecoveryServices.Backup
0.2.1       AzureRM.RecoveryServices.SiteRecovery
4.0.1       AzureRM.RedisCache
0.3.0       AzureRM.Relay
5.0.0       AzureRM.Resources
0.16.0      AzureRM.Scheduler
4.0.0       AzureRM.ServerManagement
0.5.0       AzureRM.ServiceBus
0.3.0       AzureRM.ServiceFabric
5.0.1       AzureRM.SiteRecovery
4.0.1       AzureRM.Sql
4.0.1       AzureRM.Storage
4.0.1       AzureRM.StreamAnalytics
4.0.0       AzureRM.Tags
4.0.0       AzureRM.TrafficManager
4.0.0       AzureRM.UsageAggregates
4.0.0       AzureRM.Websites
5.0.0       Azure
4.0.0       Azure.Storage

```

### Environment Data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

```

### Debug Output

```
Body:
{
  "Code": "InternalServerError",
  "Message": null,
  "Target": null,
  "Details": [
    {
      "Message": null
    },
    {
      "Code": "InternalServerError"
    },
    {
      "ErrorEntity": {
        "Code": "InternalServerError",
        "Message": null
      }
    }
  ],
  "Innererror": null
}


Set-AzureRmWebApp : Exception of type 'Microsoft.Rest.Azure.CloudException' was thrown.
At line:3 char:1
+ Set-AzureRmWebApp -AssignIdentity $True -Name $AppName -ResourceGroup ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureRmWebApp], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet
 
DEBUG: AzureQoSEvent: CommandName - Set-AzureRmWebApp; IsSuccess - False; Duration - 00:01:08.9388866; Exception - Microsoft.Rest.Azure.CloudException: Exception of type 'Microsoft.Rest.Azure
.CloudException' was thrown.
   at Microsoft.Azure.Management.WebSites.WebAppsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__316.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.WebAppsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.CreateOrUpdate(IWebAppsOperations operations, String resourceGroupName, String name, Site siteEnvelope, Nullable`1 skipDn
sRegistration, Nullable`1 skipCustomDomainVerification, Nullable`1 forceDnsRegistration, String ttlInSeconds)
   at Microsoft.Azure.Commands.WebApps.Utilities.WebsitesClient.UpdateWebApp(String resourceGroupName, String location, String webAppName, String slotName, String appServicePlan, Site siteEnv
elope)
   at Microsoft.Azure.Commands.WebApps.Cmdlets.WebApps.SetAzureWebAppCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 3:12:12 PM - SetAzureWebAppCmdlet end processing.
DEBUG: 3:12:12 PM - SetAzureWebAppCmdlet end processing.
```

**Comment by cormacpayne** [comment]
@panchagnula Hey Sisira, would you mind taking a look at this issue?

**Comment by panchagnula** [comment]
Have seen this error earlier once another ASEV2 commandlet -> where the operation was completing successfully but the PowerShell returns InternalServer Exception 'Exception of type 'Microsoft.Rest.Azure.CloudException' , @anoopkv39  can you confirm if this is the case here?

**Comment by anoopkv39** [comment]
Opened Microsoft ticket and update is - "The issue where happens when we’re making the outbound call from our control plane to the MSI Resource Provider. This is an unauthenticated request, and as a result we’re expecting a 401 result so that we can extract the authorization parameters from the www-authenticate header. We don’t actually log what the response is, that’s a repair item for web apps to better trace this area of code. We need to work together with  MSI because we’re not receiving the expected 401 or not getting the proper headers. "

After few troubleshooting sessions, they adjusted our routing table to call the identity API. There was no actual exception logged instead it was just generic one. @panchagnula
