### ISSUE TITLE
Can't get the webhook (Get-AzureRmAutomationWebhook) but can Remove it if the name contians _. if name does not contains _, Get works fine

### ISSUE THREAD

**Issue by bingbing8** [Azure/azure-powershell#8131]
**Describe the bug**
Can't get the webhook but can Remove it if the name contians _. if name does not contains _, Get works fine

**To Reproduce**
```
Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -AutomationAccountName SourceControl-EAP -Name SourceControl-EAP_yanbingtestsc_webhook
Get-AzureRmAutomationWebhook : Invalid JSON primitive: yanbingtestsc.
At line:1 char:1
+ Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -Automa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAutomationWebhook], CmdletInvocationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationWebhook
 
Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -AutomationAccountName SourceControl-EAP -Name TestHook
Get-AzureRmAutomationWebhook : The Webhook with Name: TestHook was not found.
At line:1 char:1
+ Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -Automa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAutomationWebhook], ResourceNotFoundException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationWebhook
 
Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -AutomationAccountName SourceControl-EAP -Name Test-Webhook-SC
ResourceGroupName     : sourcecontrol
AutomationAccountName : SourceControl-EAP
Name                  : Test-Webhook-SC
CreationTime          : 5/7/2018 11:12:09 AM -07:00
Description           : 
ExpiryTime            : 5/10/2019 10:15:03 AM -07:00
IsEnabled             : True
LastInvokedTime       : 5/7/2018 11:20:06 AM -07:00
LastModifiedTime      : 5/7/2018 11:12:09 AM -07:00
Parameters            : {}
RunbookName           : Test-Runbook
WebhookURI            : 
HybridWorker          : 
```
**Expected behavior**
Get should work

**Environment summary**
```
$PSVersionTable

Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      5.1.14409.1018                                                                                                                                                     
PSEdition                      Desktop                                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                            
BuildVersion                   10.0.14409.1018                                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                                
SerializationVersion           1.1.0.1 
```
**Additional context**

**Comment by markcowl** [comment]
@bingbing8 Can you include the following information to help us diagnose the issue:

1. Debug stream for the failing cmdlet.  Set ```$DebugPreference="Continue"```, run the failing cmdlet and include the extra logging here
2. The result of runnign ```Resolve-AzureRmError``` after the error occurs
3. The module layout on your machine, by running ```Get-Module -ListAvailable```

**Comment by bingbing8** [comment]
Here are the debug trace:
```
PS C:\> get-Module AzureRM.Automation -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.1.1      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Remove-AzureRmAut...
Script     5.1.2      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutoma...


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.4.0      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutoma...


PS C:\> $DebugPreference="Continue"
PS C:\> Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -AutomationAccountName SourceControl-EAP -Name Sou
rceControl-EAP_yanbingtestsc_webhook
DEBUG: 7:44:18 PM - GetAzureAutomationWebhook begin processing with ParameterSet 'ByName'.
DEBUG: 7:44:18 PM - using account id 'yawang@microsoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'yawang@microsoft.com', environment: 'AzureCloud',
tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:18:  - AuthenticationContext: ADAL .NET with assembly version '2.28.3.860', file version
'2.28.31117.1411' and informational version '78bd21073cfd91768d97894ace1ba90c5b904eec' is running...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:18: 6e80b6c6-6110-42be-806f-335afd7e817c - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:18:  - TokenCache: Deserialized 3 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/15/2018 03:44:18: 6e80b6c6-6110-42be-806f-335afd7e817c - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:18: 6e80b6c6-6110-42be-806f-335afd7e817c - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/15/2018 03:44:18: 6e80b6c6-6110-42be-806f-335afd7e817c - TokenCache: An expired or near expiry token was
found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:18: 6e80b6c6-6110-42be-806f-335afd7e817c - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/15/2018 03:44:18: 6e80b6c6-6110-42be-806f-335afd7e817c - <RefreshAccessTokenAsync>d__11: Refreshing access
token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/15/2018 03:44:19: 6e80b6c6-6110-42be-806f-335afd7e817c - TokenCache: Storing token in the cache...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/15/2018 03:44:19: 6e80b6c6-6110-42be-806f-335afd7e817c - TokenCache: An item was stored in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:19: 6e80b6c6-6110-42be-806f-335afd7e817c - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: Z7bvO+mMcieWomYo4nyYRWeL9SxPNrL0JzE6nzQ4NhY=
 Refresh Token Hash: L9KqWLh30H/TsEFJw3ku7HsLBg6Hx8A6nh9kSCVHd1E=
 Expiration Time: 12/15/2018 04:44:19 +00:00
 User Hash: SchGK28GCVdjVsiwW8hLdmONsghbWrLelMQMgJMpiUg=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:19:  - TokenCache: Serializing token cache with 3 items.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:19: 8782ca0b-3772-4fcc-8804-b5700169f88e - AcquireTokenHandlerBase: === Token Acquisition
started:
 Authority: https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (3 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:19:  - TokenCache: Deserialized 3 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/15/2018 03:44:19: 8782ca0b-3772-4fcc-8804-b5700169f88e - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:19: 8782ca0b-3772-4fcc-8804-b5700169f88e - TokenCache: An item matching the requested resource
was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 12/15/2018 03:44:19: 8782ca0b-3772-4fcc-8804-b5700169f88e - TokenCache: 59.999079585 minutes left until token in
 cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:19: 8782ca0b-3772-4fcc-8804-b5700169f88e - TokenCache: A matching item (access token or refresh
 token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 12/15/2018 03:44:19: 8782ca0b-3772-4fcc-8804-b5700169f88e - AcquireTokenHandlerBase: === Token Acquisition
finished successfully. An access token was retuned:
 Access Token Hash: Z7bvO+mMcieWomYo4nyYRWeL9SxPNrL0JzE6nzQ4NhY=
 Refresh Token Hash: L9KqWLh30H/TsEFJw3ku7HsLBg6Hx8A6nh9kSCVHd1E=
 Expiration Time: 12/15/2018 04:44:19 +00:00
 User Hash: SchGK28GCVdjVsiwW8hLdmONsghbWrLelMQMgJMpiUg=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/4dda6ad2-730a-4053-88d1-0fa7ff209aea/resourceGroups/sourcecontrol/providers/
Microsoft.Automation/automationAccounts/SourceControl-EAP/webhooks/SourceControl-EAP_yanbingtestsc_webhook?api-version=
2015-10-31

Headers:
x-ms-client-request-id        : 89686131-d6ad-4561-92b1-cb6a09fd04fd
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-request-id               : b671f494-ac25-4c6c-a29c-76e8dd82b1c0
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-correlation-request-id   : dacae74f-56b4-4daa-b29e-71d64877187e
x-ms-routing-request-id       : WESTUS2:20181215T034420Z:dacae74f-56b4-4daa-b29e-71d64877187e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Sat, 15 Dec 2018 03:44:19 GMT
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
{
  "id":
"/subscriptions/4dda6ad2-730a-4053-88d1-0fa7ff209aea/resourceGroups/sourcecontrol/providers/Microsoft.Automation/automa
tionAccounts/SourceControl-EAP/webhooks/SourceControl-EAP_yanbingtestsc_webhook",
  "name": "SourceControl-EAP_yanbingtestsc_webhook",
  "type": "Microsoft.Automation/AutomationAccounts/Webhooks",
  "properties": {
    "isEnabled": true,
    "expiryTime": "2019-12-13T11:51:00.5067799-08:00",
    "runbook": {
      "name": "Process-SourceControlWebhook"
    },
    "lastInvokedTime": "2018-12-13T11:51:02.8034624-08:00",
    "runOn": null,
    "parameters": {
      "SourceControlName": "yanbingtestsc",
      "SubscriptionId": "4dda6ad2-730a-4053-88d1-0fa7ff209aea",
      "AutomationAccountName": "SourceControl-EAP",
      "ResourceGroupName": "sourcecontrol",
      "SourceControlAccountId": "390db18f-53ed-4374-b7e4-eff1a289e6c8",
      "AzureEnvironmentName": "AzureCloud"
    },
    "uri": "",
    "creationTime": "2018-12-13T11:51:01.7442079-08:00",
    "lastModifiedBy": "",
    "lastModifiedTime": "2018-12-13T11:51:01.7442079-08:00"
  }
}

Get-AzureRmAutomationWebhook : Invalid JSON primitive: yanbingtestsc.
At line:1 char:1
+ Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -Automa ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzureRmAutomationWebhook], CmdletInvocationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationWebhook

DEBUG: AzureQoSEvent: CommandName - Get-AzureRmAutomationWebhook; IsSuccess - False; Duration - 00:00:02.6410328;
Exception - System.Management.Automation.CmdletInvocationException: Invalid JSON primitive: yanbingtestsc. --->
System.ArgumentException: Invalid JSON primitive: yanbingtestsc.
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
   at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit,
JavaScriptSerializer serializer)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input,
Type type, Int32 depthLimit)
   at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
   at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
   at System.Management.Automation.CommandProcessorBase.Complete()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean
performSyncInvoke)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input,
PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1
output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.InvokeScript(String scriptName, Hashtable
parameters)
   at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.Deserialize(String json)
   at Microsoft.Azure.Commands.Automation.Model.Webhook..ctor(String resourceGroupName, String automationAccountName,
Webhook webhook, String webhookUri)
   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetWebhook(String resourceGroupName, String
automationAccountName, String name)
   at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationWebhook.AutomationProcessRecord()
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 7:44:20 PM - GetAzureAutomationWebhook end processing.
DEBUG: 7:44:20 PM - GetAzureAutomationWebhook end processing.
PS C:\> Resolve-AzureRmError
DEBUG: 7:44:45 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 7:44:45 PM - using account id 'yawang@microsoft.com'...


   HistoryId: 7


Message        : Invalid JSON primitive: yanbingtestsc.
StackTrace     :    at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
                    at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean
                 performSyncInvoke)
                    at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1
                 input, PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input,
                 PSDataCollection`1 output, PSInvocationSettings settings)
                    at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
                    at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.InvokeScript(String
                 scriptName, Hashtable parameters)
                    at Microsoft.Azure.Commands.Automation.Common.PowerShellJsonConverter.Deserialize(String json)
                    at Microsoft.Azure.Commands.Automation.Model.Webhook..ctor(String resourceGroupName, String
                 automationAccountName, Webhook webhook, String webhookUri)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetWebhook(String
                 resourceGroupName, String automationAccountName, String name)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationWebhook.AutomationProcessRecord()
                    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.CmdletInvocationException
InvocationInfo : {Get-AzureRmAutomationWebhook}
Line           : Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -AutomationAccountName
                 SourceControl-EAP -Name SourceControl-EAP_yanbingtestsc_webhook
Position       : At line:1 char:1
                 + Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -Automa ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : Invalid JSON primitive: yanbingtestsc.
StackTrace     :    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
                    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializeInternal(Int32 depth)
                    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input,
                 Int32 depthLimit, JavaScriptSerializer serializer)
                    at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer
                 serializer, String input, Type type, Int32 depthLimit)
                    at Microsoft.PowerShell.Commands.JsonObject.ConvertFromJson(String input, ErrorRecord& error)
                    at Microsoft.PowerShell.Commands.ConvertFromJsonCommand.ConvertFromJsonHelper(String input)
                    at System.Management.Automation.CommandProcessorBase.Complete()
Exception      : System.ArgumentException
InvocationInfo : {Get-AzureRmAutomationWebhook}
Line           : Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -AutomationAccountName
                 SourceControl-EAP -Name SourceControl-EAP_yanbingtestsc_webhook
Position       : At line:1 char:1
                 + Get-AzureRmAutomationWebhook -ResourceGroupName sourcecontrol -Automa ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : Could not find a part of the path 'C:\Users\yawang\.Azure\AzInstallationChecks.json'.
StackTrace     :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean
                 useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs,
                 String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
                    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
                    at Microsoft.PowerShell.Commands.FileSystemProvider.NewItem(String path, String type, Object value)
Exception      : System.IO.DirectoryNotFoundException
InvocationInfo : {New-Item}
Line           :         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -ItemType File -Value
                 ($installationchecks | ConvertTo-Json -ErrorAction Stop)

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\AzureRM.Profile\5.8.2\StartupScripts\AzureRmError.ps1:17 char:9
                 +         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -I ...
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7

Message        : Could not find a part of the path 'C:\Users\yawang\.Azure\AzInstallationChecks.json'.
StackTrace     :    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
                    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean
                 useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs,
                 String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
                    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
                    at Microsoft.PowerShell.Commands.FileSystemProvider.NewItem(String path, String type, Object value)
Exception      : System.IO.DirectoryNotFoundException
InvocationInfo : {New-Item}
Line           :         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -ItemType File -Value
                 ($installationchecks | ConvertTo-Json -ErrorAction Stop)

Position       : At C:\Program
                 Files\WindowsPowerShell\Modules\AzureRM.Automation\6.1.1\StartupScripts\AzureRmError.ps1:17 char:9
                 +         New-Item -Path $pathToInstallationChecks -ErrorAction Stop -I ...
                 +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 7



   HistoryId: 1


Message        : The specified module 'PSReadline' was not loaded because no valid module file was found in any module
                 directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :
Position       :
HistoryId      : 1

DEBUG: AzureQoSEvent: CommandName - Resolve-AzureRmError; IsSuccess - True; Duration - 00:00:00.1284990; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 7:44:45 PM - ResolveError end processing.
DEBUG: 7:44:45 PM - ResolveError end processing.
```

**Comment by maddieclayton** [comment]
@vrdmr Can you take a look at this issue?

**Comment by csand-msft** [comment]
The team will fix this.

**Comment by csand-msft** [comment]
Fix (if we allow the webhook to be created with name that has underscore character, then the other cmdlets should work with that)

**Comment by andyw248** [comment]
Vikram, Jeff - please assign.

**Comment by thomasyip-msft** [comment]
Issue not reproducible in az cmdlet. webhook name with _ can be get and deleted. AzureRM no longer being updated, please use Az.
