### ISSUE TITLE
Set-AzureRmAppServicePlan fails with invalid status code 'Created'

### ISSUE THREAD

**Issue by mgfink** [Azure/azure-powershell#8138]
### Description
PS cmdlets to enable/disable per site scaling in Azure fail with "Set-AzureRmAppServicePlan : Operation returned an invalid status code 'Created'

### Script/Steps for Reproduction

```
Set-AzureRmAppServicePlan -ResourceGroupName $asp.ResourceGroup -Name $asp.Name -PerSiteScaling $true

```

### Module Version

```powershell
Get-Module -ListAvailable


    Directory: /Users/mfink/.local/share/powershell/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     0.7.0      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, I...
Script     0.6.1      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, I...
Script     0.7.0      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Susp...
Script     0.6.1      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Susp...
Script     0.7.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiM...
Script     0.6.1      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiM...
Script     0.7.0      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzAppl...
Script     0.6.1      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzAppl...
Script     0.7.0      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Re...
Script     0.6.1      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Re...
Script     0.7.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAcc...
Script     0.6.1      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAcc...
Script     0.7.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPe...
Script     0.6.1      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPe...
Script     0.7.0      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSso...
Script     0.6.1      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSso...
Script     0.7.0      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-A...
Script     0.6.1      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-A...
Script     0.7.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvail...
Script     0.6.1      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvail...
Script     0.7.0      Az.Consumption                      Core,Desk {Get-AzConsumptionBudget, Get-AzConsum...
Script     0.6.1      Az.Consumption                      Core,Desk {Get-AzConsumptionBudget, Get-AzConsum...
Script     0.7.0      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainer...
Script     0.6.1      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainer...
Script     0.7.0      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContai...
Script     0.6.1      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContai...
Script     0.7.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, Ne...
Script     0.6.1      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, Ne...
Script     0.7.0      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider,...
Script     0.6.1      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider,...
Script     0.7.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-Az...
Script     0.6.1      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-Az...
Script     0.7.0      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordCo...
Script     0.6.1      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordCo...
Script     0.7.0      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGrid...
Script     0.6.1      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGrid...
Script     0.7.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventH...
Script     0.6.1      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventH...
Script     0.7.0      Az.Insights                         Core,Desk {Get-AzMetricDefinition, Get-AzMetric,...
Script     0.6.1      Az.Insights                         Core,Desk {Get-AzMetricDefinition, Get-AzMetric,...
Script     0.7.0      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHub...
Script     0.6.1      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHub...
Script     0.7.0      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzK...
Script     0.6.1      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzK...
Script     0.7.0      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Ge...
Script     0.6.1      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Ge...
Script     0.7.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-A...
Script     0.6.1      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-A...
Script     0.7.0      Az.MachineLearningCompute           Core,Desk {Get-AzMlOpCluster, Get-AzMlOpClusterK...
Script     0.6.1      Az.MachineLearningCompute           Core,Desk {Get-AzMlOpCluster, Get-AzMlOpClusterK...
Script     0.7.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketp...
Script     0.6.1      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketp...
Script     0.7.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKeys, Set-A...
Script     0.6.1      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKeys, Set-A...
Script     0.7.0      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticatio...
Script     0.6.1      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticatio...
Script     0.7.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotifica...
Script     0.6.1      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotifica...
Script     0.7.0      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivit...
Script     0.6.1      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivit...
Script     0.7.0      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState,...
Script     0.6.1      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState,...
Script     0.7.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, ...
Script     0.6.1      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, ...
Script     0.7.0      Az.Profile                          Core,Desk {Disable-AzDataCollection, Disable-AzC...
Script     0.6.1      Az.Profile                          Core,Desk {Disable-AzDataCollection, Disable-AzC...
Script     0.7.0      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty,...
Script     0.6.1      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty,...
Script     0.7.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New...
Script     0.6.1      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New...
Script     0.7.0      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayName...
Script     0.6.1      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayName...
Script     0.7.0      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRol...
Script     0.6.1      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRol...
Script     0.7.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServ...
Script     0.6.1      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServ...
Script     0.7.0      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertifi...
Script     0.6.1      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertifi...
Script     0.7.0      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzS...
Script     0.6.1      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzS...
Script     0.7.0      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncry...
Script     0.6.1      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncry...
Script     0.7.0      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAc...
Script     0.6.1      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAc...
Script     0.7.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-Az...
Script     0.6.1      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-Az...
Script     0.7.0      Az.Tags                             Core,Desk {Remove-AzTag, Get-AzTag, New-AzTag}
Script     0.6.1      Az.Tags                             Core,Desk {Remove-AzTag, Get-AzTag, New-AzTag}
Script     0.7.0      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEnd...
Script     0.6.1      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEnd...
Script     0.7.0      Az.UsageAggregates                  Core,Desk Get-UsageAggregates
Script     0.6.1      Az.UsageAggregates                  Core,Desk Get-UsageAggregates
Script     0.7.0      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServic...
Script     0.6.1      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServic...
Script     0.5.4      Azure.AnalysisServices              Desk      {Add-AzureAnalysisServicesAccount, Res...
Script     4.6.1      Azure.Storage                       Desk      {Get-AzureStorageTable, New-AzureStora...


    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.2.3      PackageManagement                   Desk      {Find-Package, Get-Package, Get-Packag...
Script     2.0.3      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-...


    Directory: /usr/local/microsoft/powershell/6/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     0.5.4      Azure.AnalysisServices              Desk      {Add-AzureAnalysisServicesAccount, Res...
Script     4.6.1      Azure.Storage                       Desk      {Get-AzureStorageTable, New-AzureStora...
Manifest   1.2.2.0    Microsoft.PowerShell.Archive        Desk      {Compress-Archive, Expand-Archive}
Manifest   6.1.0.0    Microsoft.PowerShell.Host           Core      {Start-Transcript, Stop-Transcript}
Manifest   6.1.0.0    Microsoft.PowerShell.Management     Core      {Add-Content, Clear-Content, Clear-Ite...
Manifest   6.1.0.0    Microsoft.PowerShell.Security       Core      {Get-Credential, Get-ExecutionPolicy, ...
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        Core      {Format-List, Format-Custom, Format-Ta...
Script     1.1.7.2    PackageManagement                   Desk      {Find-Package, Get-Package, Get-Packag...
Script     1.6.7      PowerShellGet                       Desk      {Find-Command, Find-DSCResource, Find-...
Script     0.0        PSDesiredStateConfiguration         Desk      {Update-DependsOn, Get-DSCResourceModu...
Script     2.0.0      PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadL...
Binary     1.1.2      ThreadJob                           Desk      Start-ThreadJob
```

### Environment Data

```powershell
Name                           Value
----                           -----
PSVersion                      6.1.1
PSEdition                      Core
GitCommitId                    6.1.1
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; r...
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Debug Output

```
DEBUG: ============================ HTTP RESPONSE ============================

**Status Code:
Created**

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 2889138f-74cc-47db-885f-2a74dc0fa4e1
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 762ecf61-a952-40eb-9ff6-e008e85ec9e3
x-ms-routing-request-id       : FRANCECENTRAL:20181214T173551Z:762ecf61-a952-40eb-9ff6-e008e85ec9e3
X-Content-Type-Options        : nosniff
Date                          : Fri, 14 Dec 2018 17:35:51 GMT

Set-AzureRmAppServicePlan : Operation returned an invalid status code 'Created'
At line:1 char:1
+ Set-AzureRmAppServicePlan -ResourceGroupName $asp.ResourceGroup -Name ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzAppServicePlan], DefaultErrorResponseException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.SetAzureAppServicePlanCmdlet

DEBUG: AzureQoSEvent: CommandName - Set-AzAppServicePlan; IsSuccess - False; Duration - 00:00:05.6607171; Exception - Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseException: Operation returned an invalid status code 'Created'
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, AppServicePlan appServicePlan, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String name, AppServicePlan appServicePlan, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperationsExtensions.CreateOrUpdateAsync(IAppServicePlansOperations operations, String resourceGroupName, String name, AppServicePlan appServicePlan, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.WebSites.AppServicePlansOperationsExtensions.CreateOrUpdate(IAppServicePlansOperations operations, String resourceGroupName, String name, AppServicePlan appServicePlan)
   at Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.SetAzureAppServicePlanCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
```

**Comment by markcowl** [comment]
@mgfink Can you include the request in your debug info?  Also, it looks like you have Azure.AnalysisServices and Azure.Storage installed alongside the Az cmdlets, that uyou have these installed in both the User and Machien scopes, and that you have multiple versions of the Az cmdlets installed. This does not contribute to this problem, but could cause problems if you try to mix the cmdlets in a script.

**Comment by mgfink** [comment]
@markcowl here's the info you requested. 
[log.zip](https://github.com/Azure/azure-powershell/files/2686710/log.zip)

**Comment by maddieclayton** [comment]
@panchagnula Can you take a look at this issue?

**Comment by mgfink** [comment]
This is still occurring....is anyone else seeing this or able to reproduce?

**Comment by panchagnula** [comment]
@mgfink can you share the site name & the timestamp for this so we can debug on our end. Thanks!

**Comment by mgfink** [comment]
PS Azure:\> $asp=Get-AzureRmAppServicePlan -ResourceGroupName mgfsandmixednc-app-rg -name mgfnewsandnc-aspwebext
Azure:/
PS Azure:\> Set-AzureRmAppServicePlan -ResourceGroupName $asp.ResourceGroup -name $asp.Name -PerSiteScaling $true
Set-AzureRmAppServicePlan : Operation returned an invalid status code 'Created'
At line:1 char:1
+ Set-AzureRmAppServicePlan -ResourceGroupName $asp.ResourceGroup -name ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Set-AzAppServicePlan], DefaultErrorResponseException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.WebApps.Cmdlets.AppServicePlans.SetAzureAppServicePlanCmdlet

Azure:/
PS Azure:\> date
Tue Feb 26 20:23:34 UTC 2019

**Comment by panchagnula** [comment]
@mgfink - the 'Created' status code is a new code that was added, however, the .NET SDK version Powershell is using hasn't been updated, so this throws as an unknown error code. The operation is successful, & so you can ignore this error for now. We will update our SDK soon, @Nking92 will update this issue once we update our SDK!

**Comment by mgfink** [comment]
@panchagnula that sounds good & thank you for the update!  Once the code has been released, I will do a retest.

**Comment by panchagnula** [comment]
this should now be fix @mgfink can you please validate?

**Comment by mgfink** [comment]
I was able to try this out and verify the error is no longer visible.  Thanks for your support to resolve!
