### ISSUE TITLE
Release new version of Azure without AzureRM dependency

### ISSUE THREAD

**Issue by maddieclayton** [Azure/azure-powershell#8167]
Fix was made for Azure to no longer have a dependency on Azure.Storage (and therefore AzureRM.Profile).  We need to make sure this is the correct long term fix, and if so, release a version of Azure with this fix from the AzureRM branch (this was previously only merged into master, so the PR needs to be recreated: https://github.com/Azure/azure-powershell/pull/8035)

**Comment by carlocardella** [comment]
Is this fix going to be release soon?

**Comment by maddieclayton** [comment]
Common code change is here: https://github.com/Azure/azure-powershell-common/tree/RDFE, all that needs to be done is to release a new version of Microsoft.Azure.Common and Hyak.Common that can be loaded side by side with the version used in Az. After that, the changes for the AzureRM branch in azure-powershell can be found here: https://github.com/maddieclayton/azure-powershell/tree/releaseazure.

**Comment by markcowl** [comment]
- Added investigation - cna Azure work side-by-side with Az without modification?

**Comment by ThinkFr33ly** [comment]
Is this issue the root cause of the following error? I'm trying to upgrade to Az from Azure/AzureRM. I've uninstalled AzureRM, but I now will seemingly randomly get this error when either trying to run service management command (Get-AzureService, for example), but also when I try and run standard Az commands like Get-AzSubscription.

`Message        : Exception has been thrown by the target of an invocation.
StackTrace     :    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.ClientFactory.CreateCustomArmClient[TClient](Object[] parameters)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAllSubscriptionsForTenant(String tenantId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListSubscriptions(String tenantIdOrDomain)
                    at Microsoft.Azure.Commands.Profile.GetAzureRMSubscriptionCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Reflection.TargetInvocationException
InvocationInfo : {Get-AzSubscription}
Line           : Get-AzSubscription
Position       : At line:1 char:1
                 + Get-AzSubscription
                 + ~~~~~~~~~~~~~~~~~~
HistoryId      : 6

Message        : Attempted to access an element as a type incompatible with the array.
StackTrace     :    at System.Collections.Generic.List`1.Add(T item)
                    at Microsoft.Azure.Internal.Subscriptions.SubscriptionClient.Initialize()
                    at Microsoft.Azure.Internal.Subscriptions.SubscriptionClient..ctor(Uri baseUri, ServiceClientCredentials credentials, DelegatingHandler[] handlers)
Exception      : System.ArrayTypeMismatchException
InvocationInfo : {Get-AzSubscription}
Line           : Get-AzSubscription
Position       : At line:1 char:1
                 + Get-AzSubscription
                 + ~~~~~~~~~~~~~~~~~~
HistoryId      : 6



   HistoryId: 3


Message        : The specified module 'Azure.Storage' with version '4.3.0' was not loaded because no valid module file was found in any module directory.
StackTrace     :
Exception      : System.IO.FileNotFoundException
InvocationInfo : {Import-Module}
Line           :     Import-Module Azure.Storage -MinimumVersion 4.3.0 -Scope Global

Position       : At C:\Program Files\WindowsPowerShell\Modules\Azure\5.3.0\Azure.psm1:19 char:5
                 +     Import-Module Azure.Storage -MinimumVersion 4.3.0 -Scope Global
                 +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3`
