### ISSUE TITLE
Get-AzRecoveryServicesAsrRecoveryPlan returns error: "Vault Settings are missing. Please import Vault Settings and verify the same"

### ISSUE THREAD

**Issue by ChristopherGLewis** [Azure/azure-powershell#8358]
### Description
`Get-AzRecoveryServicesAsrRecoveryPlan` returns error:

```powershell
Get-AzRecoveryServicesAsrRecoveryPlan : Operation failed.
ClientRequestId:
Vault Settings are missing. Please import Vault Settings and verify the same
At line:1 char:1
+ Get-AzRecoveryServicesAsrRecoveryPlan
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzRecoveryServicesAsrRecoveryPlan], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrRecoveryPlan
```

### Script/Steps for Reproduction
Just running the command
`Get-AzRecoveryServicesAsrRecoveryPlan `

```powershell
PS C:\> Get-AzRecoveryServicesAsrRecoveryPlan
Get-AzRecoveryServicesAsrRecoveryPlan : Operation failed.
ClientRequestId:
Vault Settings are missing. Please import Vault Settings and verify the same
At line:1 char:1
+ Get-AzRecoveryServicesAsrRecoveryPlan
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzRecoveryServicesAsrRecoveryPlan], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrRecoveryPlan



```

### Module Version

```powershell
PS C:\> Get-Module -ListAvailable | where {$_.name -eq 'az.recoveryservices'}

    Directory: C:\Program Files\PowerShell\Modules

ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.0.0      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile,...

```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.2
PSEdition                      Core
GitCommitId                    6.1.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### Debug Output

```
PS C:\> Get-AzRecoveryServicesAsrRecoveryPlan
DEBUG: 4:53:05 PM - GetAzureRmRecoveryServicesAsrRecoveryPlan begin processing with ParameterSet 'Default'.
DEBUG: 4:53:05 PM - using account id 'xx@yyyy.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'xx@yyyy.com', environment: 'AzureCloud', tenant: '052eb64f-2625-4572-a928-5e7d322291f1'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '052eb64f-2625-4572-a928-5e7d322291f1', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthrity: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/052eb64f-2625-4572-a928-5e7d322291f1/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '052eb64f-2625-4572-a928-5e7d322291f1', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [Common.Authentication]: Received token with LoginType 'LiveId', Tenant: '052eb64f-2625-4572-a928-5e7d322291f1', UserId: 'xx@yyyy.com'
DEBUG: [Common.Authentication]: Authenticating using Account: 'xx@yyyy.com', environment: 'AzureCloud', tenant: '052eb64f-2625-4572-a928-5e7d322291f1'
Get-AzRecoveryServicesAsrRecoveryPlan : Operation failed.
ClientRequestId:
Vault Settings are missing. Please import Vault Settings and verify the same
At line:1 char:1
+ Get-AzRecoveryServicesAsrRecoveryPlan
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzRecoveryServicesAsrRecoveryPlan], Exception
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrRecoveryPlan

DEBUG: AzureQoSEvent: CommandName - Get-AzRecoveryServicesAsrRecoveryPlan; IsSuccess - False; Duration - 00:00:00.1462798; Exception - System.Exception: Operation failed.
ClientRequestId:
Vault Settings are missing. Please import Vault Settings and verify the same ---> System.InvalidOperationException: Vault Settings are missing. Please import Vault Settings and verify the same
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.PSRecoveryServicesClient.GetSiteRecoveryClient()
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.PSRecoveryServicesClient.GetAzureSiteRecoveryRecoveryPlan()
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.GetAzureRmRecoveryServicesAsrRecoveryPlan.GetAll()
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.HandleException(Exception ex)
   at Microsoft.Azure.Commands.RecoveryServices.SiteRecovery.SiteRecoveryCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 4:53:06 PM - GetAzureRmRecoveryServicesAsrRecoveryPlan end processing.
DEBUG: 4:53:06 PM - GetAzureRmRecoveryServicesAsrRecoveryPlan end processing.
```

**Comment by markcowl** [comment]
@viverm Please take a look

**Comment by viverm** [comment]
@ChristopherGLewis 
For Asr Commandlet we need to set the ASR context for RecoveryServices vault.

we can do that by two ways 
1) downloading vault settings file and import that setting in PowerShell context
`Import-AzRecoveryServicesAsrVaultSettingsFile -Path $vaultSettingsFilePath`

2) Setting Vault context directly by executing below commands

```
PS C:\WINDOWS\system32> $vault = Get-AzRecoveryServicesVault -Name $vaultName -ResourceGroupName $vaultRG
PS C:\WINDOWS\system32>  Set-AzRecoveryServicesAsrVaultContext -Vault $vault
```

**Comment by ChristopherGLewis** [comment]
> @ChristopherGLewis
> For Asr Commandlet we need to set the ASR context for RecoveryServices vault.
> 
> we can do that by two ways
> 
> 1. downloading vault settings file and import that setting in PowerShell context
>    `Import-AzRecoveryServicesAsrVaultSettingsFile -Path $vaultSettingsFilePath`
> 2. Setting Vault context directly by executing below commands
> 
> ```
> PS C:\WINDOWS\system32> $vault = Get-AzRecoveryServicesVault -Name $vaultName -ResourceGroupName $vaultRG
> PS C:\WINDOWS\system32>  Set-AzRecoveryServicesAsrVaultContext -Vault $vault
> ```

Um, what????  None of the other AzureRM/Az powershell objects work that way.  *Everything* else has -ResouceGroup -Name as parameters.  And the use of a Context is NOT documented anywhere.

And a note for the whole AzPS team - using the verb "SET" implies that something is going to change.  I always think that when you SET a CONTEXT you are modifying the context.  A better verb for all CONTEXT actions would be SELECT or USE.

**Comment by viverm** [comment]
Closing as no current action required on this. For the Naming suggestion we will take a look want can be done on it .

**Comment by CaioBauab** [comment]
Same error here, even using Set-AzRecoveryServicesVaultContext

$vault = Get-AzRecoveryServicesVault -ResourceGroupName $ResourceGroupName -Name $RecoveryServicesVault
Set-AzRecoveryServicesVaultContext -Vault $vault
$recoveryPlans = Get-AzRecoveryServicesAsrRecoveryPlan

Line |
  10 |  $recoveryPlans = Get-AzRecoveryServicesAsrRecoveryPlan
     |                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Operation failed. ClientRequestId:  Vault Settings are missing. Please import Vault Settings and verify the   
     | same

@viverm can you reopen please?
