### ISSUE TITLE
Set-AzureKeyVaultSecret -tag doesn't accept numbers in tags

### ISSUE THREAD

**Issue by amcgregor1** [Azure/azure-powershell#8494]
### Description

Unable to use a date stamp for tagging KeyVault Secrets.
Important: I am running this against AzureStack so need to use the specific modules listed below

### Script/Steps for Reproduction

```powershell
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> $Secret = ConvertTo-SecureString -String 'Password' -AsPlainText -Force
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> $Tags = @{ 'RandomTag' = 'Seems:OKwith-these_Chars'}
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline>
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> Set-AzureKeyVaultSecret -VaultName 'acm-dev-equinix-kvt03' -Name 'ITSecret' -SecretValue $Secret -tag $tags


Vault Name   : acm-dev-equinix-kvt03
Name         : ITSecret
Version      : 285039cec5dd4bc0a7ffa6661669c3c1
Id           : https://acm-dev-equinix-kvt03.vault.equinix.vigilant.it:443/secrets/ITSecret/285039cec5dd4bc0a7ffa6661669c3c1
Enabled      : True
Expires      :
Not Before   :
Created      : 7/02/2019 9:10:18 AM
Updated      : 7/02/2019 9:10:18 AM
Content Type :
Tags         : Name       Value
               RandomTag  Seems:OKwith-these_Chars

PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> $Tags = @{ 'NotOKwithThese' = (get-date -UFormat %Y%m%d-%H:%M:%S)}
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> Set-AzureKeyVaultSecret -VaultName 'acm-dev-equinix-kvt03' -Name 'ITSecret' -SecretValue $Secret -tag $tags
Set-AzureKeyVaultSecret : Tag has invalid value
At line:1 char:1
+ Set-AzureKeyVaultSecret -VaultName 'acm-dev-equinix-kvt03' -Name 'ITS ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureKeyVaultSecret], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultSecret
 
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> get-date -UFormat %Y%m%d-%H:%M:%S
20190207-20:11:20

```

### Module Version

```powershell
Get-Module -ListAvailable

S C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> Get-Module -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.2.0      Azs.Azurebridge.Admin               {Get-AzsAzureBridgeProduct, Invoke-AzsAzureBridgeProductDownload, Get-AzsAzureBridgeActivation, Remove-AzsAzureBridgeDownloadedProduct...}
Script     0.2.0      Azs.Backup.Admin                    {Get-AzsBackupConfiguration, Get-AzsBackup, Restore-AzsBackup, Set-AzsBackupConfiguration...}
Script     0.2.0      Azs.Commerce.Admin                  Get-AzsSubscriberUsage
Script     0.2.1      Azs.Compute.Admin                   {Get-AzsVMExtension, Remove-AzsComputeQuota, New-AzsComputeQuota, Add-AzsPlatformImage...}
Script     0.3.0      Azs.Fabric.Admin                    {Restart-AzsInfrastructureRoleInstance, Get-AzsStorageSystem, Get-AzsScaleUnitNode, Disable-AzsScaleUnitNode...}
Script     0.2.0      Azs.Gallery.Admin                   {Add-AzsGalleryItem, Remove-AzsGalleryItem, Get-AzsGalleryItem}
Script     0.3.0      Azs.Infrastructureinsights.Admin    {Close-AzsAlert, Get-AzsRegionHealth, Get-AzsAlert, Get-AzsRPHealth...}
Script     0.2.0      Azs.Keyvault.Admin                  Get-AzsKeyVaultQuota
Script     0.2.0      Azs.Network.Admin                   {Get-AzsNetworkQuota, New-AzsNetworkQuota, Get-AzsNetworkAdminOverview, Remove-AzsNetworkQuota...}
Script     0.2.1      Azs.Storage.Admin                   {Restore-AzsStorageAccount, New-AzsStorageQuota, Get-AzsStorageFarmMetricDefinition, Get-AzsQueueServiceMetricDefinition...}
Script     0.2.0      Azs.Subscriptions                   {Get-AzsDelegatedProviderOffer, Remove-AzsSubscription, Get-AzsOffer, New-AzsSubscription...}
Script     0.3.1      Azs.Subscriptions.Admin             {Add-AzsPlanToOffer, Get-AzsSubscriptionsQuota, Get-AzsDelegatedProviderManagedOffer, Test-AzsNameAvailability...}
Script     0.2.1      Azs.Update.Admin                    {Resume-AzsUpdateRun, Get-AzsUpdateLocation, Get-AzsUpdateRun, Get-AzsUpdate...}
Script     4.5.0      Azure.Storage                       {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStorageTableStoredAccessPolicy, New-AzureStorageTable...}
Script     4.1.1      Azure.Storage                       {Get-AzureStorageTable, New-AzureStorageTableSASToken, New-AzureStorageTableStoredAccessPolicy, New-AzureStorageTable...}
Script     2.3.0      AzureRM
Script     0.4.0      AzureRM.BootStrapper                {Update-AzureRmProfile, Uninstall-AzureRmProfile, Install-AzureRmProfile, Use-AzureRmProfile...}
Script     4.0.2      AzureRM.Compute                     {Remove-AzureRmAvailabilitySet, Get-AzureRmAvailabilitySet, New-AzureRmAvailabilitySet, Update-AzureRmAvailabilitySet...}
Script     3.5.1      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New-AzureRmDnsRecordConfig, Remove-AzureRmDnsRecordSet, Set-AzureRmDnsRecordSet...}
Script     5.0.0      AzureRM.Insights                    {Get-AzureRmMetricDefinition, Get-AzureRmMetric, Remove-AzureRmLogProfile, Get-AzureRmLogProfile...}
Script     4.2.0      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Set-AzureKeyVaultCertificateAttribute, Stop-AzureKeyVaultCertificateOperation, Get-AzureKeyVaultCertificateOperation...}
Script     5.0.1      AzureRM.Network                     {Add-AzureRmApplicationGatewayAuthenticationCertificate, Get-AzureRmApplicationGatewayAuthenticationCertificate, New-AzureRmApplicationGatewayAuthenticationCertificate, Remove-AzureRmAp...
Script     5.8.2      AzureRM.profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosave, Enable-AzureRmDataCollection, Enable-AzureRmContextAutosave...}
Script     5.5.2      AzureRM.profile                     {Disable-AzureRmDataCollection, Disable-AzureRmContextAutosave, Enable-AzureRmDataCollection, Enable-AzureRmContextAutosave...}
Script     6.0.2      AzureRM.Resources                   {Get-AzureRmProviderOperation, Remove-AzureRmRoleAssignment, Get-AzureRmRoleAssignment, New-AzureRmRoleAssignment...}
Script     5.0.4      AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-AzureRmStorageAccountKey...}
Script     1.1.0.1    AzureRM.Storage                     {Get-AzureRmStorageAccount, Get-AzureRmStorageAccountKey, New-AzureRmStorageAccount, New-AzureRmStorageAccountKey...}
Script     4.0.2      AzureRM.Tags                        {Remove-AzureRmTag, Get-AzureRmTag, New-AzureRmTag}
Script     4.0.3      AzureRM.UsageAggregates             Get-UsageAggregates
Script     5.0.1      AzureRM.Websites                    {Get-AzureRmAppServicePlan, Set-AzureRmAppServicePlan, New-AzureRmAppServicePlan, Remove-AzureRmAppServicePlan...}
Script     1.6.0      AzureStack
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     3.4.0      Pester                              {Describe, Context, It, Should...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}
Script     2.0.0      PSReadline                          {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption...}


    Directory: C:\Program Files (x86)\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Invoke-OperationValidation}
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}
Script     3.4.0      Pester                              {Describe, Context, It, Should...}
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module, Save-Module, Update-Module...}


    Directory: C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.0.0.0    AppBackgroundTask                   {Disable-AppBackgroundTaskDiagnosticLog, Enable-AppBackgroundTaskDiagnosticLog, Set-AppBackgroundTaskResourcePolicy, Unregister-AppBackgroundTask...}
Manifest   2.0.0.0    AppLocker                           {Get-AppLockerFileInformation, Get-AppLockerPolicy, New-AppLockerPolicy, Set-AppLockerPolicy...}
Manifest   1.0.0.0    AppvClient                          {Add-AppvClientConnectionGroup, Add-AppvClientPackage, Add-AppvPublishingServer, Disable-Appv...}
Manifest   2.0.1.0    Appx                                {Add-AppxPackage, Get-AppxPackage, Get-AppxPackageManifest, Remove-AppxPackage...}
Script     1.0.0.0    AssignedAccess                      {Clear-AssignedAccess, Get-AssignedAccess, Set-AssignedAccess}
Manifest   1.0.0.0    BitLocker                           {Unlock-BitLocker, Suspend-BitLocker, Resume-BitLocker, Remove-BitLockerKeyProtector...}
Manifest   2.0.0.0    BitsTransfer                        {Add-BitsFile, Complete-BitsTransfer, Get-BitsTransfer, Remove-BitsTransfer...}
Manifest   1.0.0.0    BranchCache                         {Add-BCDataCacheExtension, Clear-BCCache, Disable-BC, Disable-BCDowngrading...}
Manifest   1.0.0.0    CimCmdlets                          {Get-CimAssociatedInstance, Get-CimClass, Get-CimInstance, Get-CimSession...}
Manifest   1.0        ConfigCI                            {Get-SystemDriver, New-CIPolicyRule, New-CIPolicy, Get-CIPolicy...}
Manifest   1.0        Defender                            {Get-MpPreference, Set-MpPreference, Add-MpPreference, Remove-MpPreference...}
Manifest   1.0.1.0    DeliveryOptimization                {Get-DeliveryOptimizationStatus, Get-DeliveryOptimizationPerfSnap, Get-DeliveryOptimizationLog, Get-DOConfig...}
Manifest   1.0.0.0    DirectAccessClientComponents        {Disable-DAManualEntryPointSelection, Enable-DAManualEntryPointSelection, Get-DAClientExperienceConfiguration, Get-DAEntryPointTableItem...}
Script     3.0        Dism                                {Add-AppxProvisionedPackage, Add-WindowsDriver, Add-WindowsCapability, Add-WindowsImage...}
Manifest   1.0.0.0    DnsClient                           {Resolve-DnsName, Clear-DnsClientCache, Get-DnsClient, Get-DnsClientCache...}
Manifest   1.0.0.0    EventTracingManagement              {Start-EtwTraceSession, New-EtwTraceSession, Get-EtwTraceSession, Update-EtwTraceSession...}
Binary     2.0.0.0    Hyper-V                             {Add-VMAssignableDevice, Add-VMDvdDrive, Add-VMFibreChannelHba, Add-VMGpuPartitionAdapter...}
Binary     1.1        Hyper-V                             {Add-VMDvdDrive, Add-VMFibreChannelHba, Add-VMHardDiskDrive, Add-VMMigrationNetwork...}
Manifest   2.0.0.0    International                       {Get-WinDefaultInputMethodOverride, Set-WinDefaultInputMethodOverride, Get-WinHomeLocation, Set-WinHomeLocation...}
Manifest   1.0.0.0    iSCSI                               {Get-IscsiTargetPortal, New-IscsiTargetPortal, Remove-IscsiTargetPortal, Update-IscsiTargetPortal...}
Script     1.0.0.0    ISE                                 {New-IseSnippet, Import-IseSnippet, Get-IseSnippet}
Manifest   1.0.0.0    Kds                                 {Add-KdsRootKey, Get-KdsRootKey, Test-KdsRootKey, Set-KdsConfiguration...}
Manifest   1.0.1.0    Microsoft.PowerShell.Archive        {Compress-Archive, Expand-Archive}
Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics    {Get-WinEvent, Get-Counter, Import-Counter, Export-Counter...}
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript, Stop-Transcript}
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-ItemProperty, Join-Path...}
Script     1.0        Microsoft.PowerShell.ODataUtils     Export-ODataEndpointProxy
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {Get-Acl, Set-Acl, Get-PfxCertificate, Get-Credential...}
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Format-List, Format-Custom, Format-Table, Format-Wide...}
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Disable-WSManCredSSP, Enable-WSManCredSSP, Get-WSManCredSSP, Set-WSManQuickConfig...}
Manifest   1.0        MMAgent                             {Disable-MMAgent, Enable-MMAgent, Set-MMAgent, Get-MMAgent...}
Manifest   1.0.0.0    MsDtc                               {New-DtcDiagnosticTransaction, Complete-DtcDiagnosticTransaction, Join-DtcDiagnosticResourceManager, Receive-DtcDiagnosticTransaction...}
Manifest   2.0.0.0    NetAdapter                          {Disable-NetAdapter, Disable-NetAdapterBinding, Disable-NetAdapterChecksumOffload, Disable-NetAdapterEncapsulatedPacketTaskOffload...}
Manifest   1.0.0.0    NetConnection                       {Get-NetConnectionProfile, Set-NetConnectionProfile}
Manifest   1.0.0.0    NetEventPacketCapture               {New-NetEventSession, Remove-NetEventSession, Get-NetEventSession, Set-NetEventSession...}
Manifest   2.0.0.0    NetLbfo                             {Add-NetLbfoTeamMember, Add-NetLbfoTeamNic, Get-NetLbfoTeam, Get-NetLbfoTeamMember...}
Manifest   1.0.0.0    NetNat                              {Get-NetNat, Get-NetNatExternalAddress, Get-NetNatStaticMapping, Get-NetNatSession...}
Manifest   2.0.0.0    NetQos                              {Get-NetQosPolicy, Set-NetQosPolicy, Remove-NetQosPolicy, New-NetQosPolicy}
Manifest   2.0.0.0    NetSecurity                         {Get-DAPolicyChange, New-NetIPsecAuthProposal, New-NetIPsecMainModeCryptoProposal, New-NetIPsecQuickModeCryptoProposal...}
Manifest   1.0.0.0    NetSwitchTeam                       {New-NetSwitchTeam, Remove-NetSwitchTeam, Get-NetSwitchTeam, Rename-NetSwitchTeam...}
Manifest   1.0.0.0    NetTCPIP                            {Get-NetIPAddress, Get-NetIPInterface, Get-NetIPv4Protocol, Get-NetIPv6Protocol...}
Manifest   1.0.0.0    NetWNV                              {Get-NetVirtualizationProviderAddress, Get-NetVirtualizationGlobal, Get-NetVirtualizationLookupRecord, Get-NetVirtualizationCustomerRoute...}
Manifest   1.0.0.0    NetworkConnectivityStatus           {Get-DAConnectionStatus, Get-NCSIPolicyConfiguration, Reset-NCSIPolicyConfiguration, Set-NCSIPolicyConfiguration}
Manifest   1.0.0.0    NetworkTransition                   {Add-NetIPHttpsCertBinding, Disable-NetDnsTransitionConfiguration, Disable-NetIPHttpsProfile, Disable-NetNatTransitionConfiguration...}
Manifest   1.0.0.0    PKI                                 {Add-CertificateEnrollmentPolicyServer, Export-Certificate, Export-PfxCertificate, Get-CertificateAutoEnrollmentPolicy...}
Manifest   1.0.0.0    PnpDevice                           {Get-PnpDevice, Get-PnpDeviceProperty, Enable-PnpDevice, Disable-PnpDevice}
Manifest   1.1        PrintManagement                     {Add-Printer, Add-PrinterDriver, Add-PrinterPort, Get-PrintConfiguration...}
Script     3.0        Provisioning                        {Install-ProvisioningPackage, Export-ProvisioningPackage, Install-TrustedProvisioningCertificate, Export-Trace...}
Manifest   1.1        PSDesiredStateConfiguration         {Set-DscLocalConfigurationManager, Start-DscConfiguration, Test-DscConfiguration, Publish-DscConfiguration...}
Script     1.0.0.0    PSDiagnostics                       {Disable-PSTrace, Disable-PSWSManCombinedTrace, Disable-WSManTrace, Enable-PSTrace...}
Binary     1.1.0.0    PSScheduledJob                      {New-JobTrigger, Add-JobTrigger, Remove-JobTrigger, Get-JobTrigger...}
Manifest   1.0.0.0    ScheduledTasks                      {Get-ScheduledTask, Set-ScheduledTask, Register-ScheduledTask, Unregister-ScheduledTask...}
Manifest   2.0.0.0    SecureBoot                          {Confirm-SecureBootUEFI, Set-SecureBootUEFI, Get-SecureBootUEFI, Format-SecureBootUEFI...}
Manifest   2.0.0.0    SmbShare                            {Get-SmbShare, Remove-SmbShare, Set-SmbShare, Block-SmbShareAccess...}
Manifest   2.0.0.0    Storage                             {Add-InitiatorIdToMaskingSet, Add-PartitionAccessPath, Add-PhysicalDisk, Add-StorageFaultDomain...}
Manifest   1.0.0.0    StorageBusCache                     {Clear-StorageBusDisk, Disable-StorageBusCache, Disable-StorageBusDisk, Enable-StorageBusCache...}
Manifest   2.0.0.0    TLS                                 {New-TlsSessionTicketKey, Enable-TlsSessionTicketKey, Disable-TlsSessionTicketKey, Export-TlsSessionTicketKey...}
Manifest   1.0.0.0    TroubleshootingPack                 {Get-TroubleshootingPack, Invoke-TroubleshootingPack}
Manifest   2.0.0.0    TrustedPlatformModule               {Get-Tpm, Initialize-Tpm, Clear-Tpm, Unblock-Tpm...}
Binary     2.1.639.0  UEV                                 {Clear-UevConfiguration, Clear-UevAppxPackage, Restore-UevBackup, Set-UevTemplateProfile...}
Manifest   2.0.0.0    VpnClient                           {Add-VpnConnection, Set-VpnConnection, Remove-VpnConnection, Get-VpnConnection...}
Manifest   1.0.0.0    Wdac                                {Get-OdbcDriver, Set-OdbcDriver, Get-OdbcDsn, Add-OdbcDsn...}
Manifest   1.0.0.0    WindowsDeveloperLicense             {Get-WindowsDeveloperLicense, Unregister-WindowsDeveloperLicense, Show-WindowsDeveloperLicenseRegistration}
Script     1.0        WindowsErrorReporting               {Enable-WindowsErrorReporting, Disable-WindowsErrorReporting, Get-WindowsErrorReporting}
Manifest   1.0.0.0    WindowsUpdate                       Get-WindowsUpdateLog


    Directory: C:\Users\mcgregan\.vscode\extensions\ms-vscode.powershell-1.11.0\modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.3      Plaster                             {Invoke-Plaster, New-PlasterManifest, Get-PlasterTemplate, Test-PlasterManifest}
Script     1.11.0     PowerShellEditorServices            {Start-EditorServicesHost, Get-PowerShellEditorServicesVersion, Compress-LogDir}
Script     0.2.0      PowerShellEditorServices.VSCode     {New-VSCodeHtmlContentView, Show-VSCodeHtmlContentView, Close-VSCodeHtmlContentView, Set-VSCodeHtmlContentView...}
Script     1.17.1     PSScriptAnalyzer                    {Get-ScriptAnalyzerRule, Invoke-ScriptAnalyzer, Invoke-Formatter}
```

### Environment Data

```powershell
$PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.17763.134
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.134
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> $DebugPreference='Continue'
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> $Tags = @{ 'NotOKwithThese' = (get-date -UFormat %Y%m%d-%H:%M:%S)}
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline> Set-AzureKeyVaultSecret -VaultName 'acm-dev-equinix-kvt03' -Name 'ITSecret' -SecretValue $Secret -tag $tags
DEBUG: 8:16:47 PM - SetAzureKeyVaultSecret begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 8:16:47 PM - using account id 'andrew.mcgregor@hpeasicsingapore.onmicrosoft.com'...
Set-AzureKeyVaultSecret : Tag has invalid value
At line:1 char:1
+ Set-AzureKeyVaultSecret -VaultName 'acm-dev-equinix-kvt03' -Name 'ITS ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureKeyVaultSecret], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultSecret
 
DEBUG: AzureQoSEvent: CommandName - Set-AzureKeyVaultSecret; IsSuccess - False; Duration - 00:00:00.0201007; Exception - System.ArgumentException: Tag has invalid value
   at Microsoft.Azure.Commands.KeyVault.Models.KeyVaultDataServiceClient.SetSecret(String vaultName, String secretName, SecureString secretValue, SecretAttributes secretAttributes)
   at Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultSecret.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 8:16:47 PM - SetAzureKeyVaultSecret end processing.
DEBUG: 8:16:47 PM - SetAzureKeyVaultSecret end processing.
PS C:\Users\mcgregan\hpeazservices\AzSIaC\pipeline>
```

**Comment by maddieclayton** [comment]
@RandalliLama @schaabs Is it accurate that KeyVault tags do not accept numbers? This doc: https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-using-tags seems to indicate that this formatting would be acceptable.

**Comment by amcgregor1** [comment]
Yes it should,  but have a look at the powershell and you can see that it doesn't

Mobile, please excuse autocorrect and typos...

________________________________

**Comment by lwajswaj** [comment]
Your problem is your passing the output which is not the String type, you are passing an object instead. To use value you want, you should run it like this:

```powershell
PS C:\Program Files\WindowsPowershellCore> $SecretValue = ConvertTo-SecureString -String "SuperSecretString" -AsPlainText -Force
PS C:\Program Files\WindowsPowershellCore> $Tags = @{ 'NowItIsOKwithThese' = (get-date -UFormat %Y%m%d-%H:%M:%S).ToString()}
PS C:\Program Files\WindowsPowershellCore> Set-AzKeyVaultSecret -VaultName "KeyVaultName" -Name "ITSecret" -SecretValue $SecretValue -Tag $Tags


Vault Name   : KeyVaultName
Name         : ITSecret
Version      : ba207f295ca74d93919a64cf1fa24aed
Id           : https://KeyVaultName.vault.azure.net:443/secrets/ITSe
               cret/ba207f295ca74d93919a64cf1fa24aed
Enabled      : True
Expires      :
Not Before   :
Created      : 15/02/2019 00:17:32
Updated      : 15/02/2019 00:17:32
Content Type :
Tags         : Name            Value
               NowItIsOKwithThese  20190214-21:16:58
```
You just need to force to cast it as string.

**Comment by maddieclayton** [comment]
@lwajswaj Great catch!

@amcgregor1 If this does not fix your issue feel free to reopen

**Comment by amcgregor1** [comment]
If this is true then it is inconsistent with all of the other RPs I have been testing:

Some examples:

```PowerShell
PS C:\>$Tags = @{ 'NowItIsOKwithThese' = (get-date -UFormat %Y%m%d-%H:%M:%S)}
PS C:\>(Set-AzureRmStorageAccount -Name acmdevequinixstr001 -ResourceGroupName acm-prod-dev-equinix-automation -Tag $Tags).tags

Key                Value
---                -----
NowItIsOKwithThese 20190215-12:22:40


PS C:\Users\mcgregan\hpeazservices> (Set-AzureRmResourceGroup -Name acm-prod-dev-equinix-automation -Tag $Tags).tags

Name                           Value
----                           -----
NowItIsOKwithThese             20190215-12:22:40
```

**Comment by amcgregor1** [comment]
Hi,

Keyvault is not consistent with other RPs then. Can you please re-investigate?

Examples:

```PowerShell
PS C:\>$Tags = @{ 'NowItIsOKwithThese' = (get-date -UFormat %Y%m%d-%H:%M:%S)}
PS C:\>(Set-AzureRmStorageAccount -Name acmdevequinixstr001 -ResourceGroupName acm-prod-dev-equinix-automation -Tag $Tags).tags

Key                Value
---                -----
NowItIsOKwithThese 20190215-12:22:40


PS C:\Users\mcgregan\hpeazservices> (Set-AzureRmResourceGroup -Name acm-prod-dev-equinix-automation -Tag $Tags).tags

Name                           Value
----                           -----
NowItIsOKwithThese             20190215-12:22:40
```

**Comment by maddieclayton** [comment]
Fix is in the PR linked above - this should be included in the 2/26 release.

**Comment by maddieclayton** [comment]
Thanks @lwajswaj!
