### ISSUE TITLE
Get-AzAutomationConnection : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by shietpas** [Azure/azure-powershell#8570]
## Description

The following error occurs when attempting to access the RunAs connection created within an Azure Automation account using the AZ module's **Get-AzAutomationConnection** cmdlet.  The same RunAs connection can be successfully obtained using the older AzureRM module cmdlet "Get-AutomationConnection".  It can also work if Connect-AzAccount is used with a separate set of credentials prior to calling the cmdlet, but this defeats the purpose of being able to leverage the RunAs credentials directly.

```
Get-AzAutomationConnection : Object reference not set to an instance of an object.
At line:5 char:31
+ ... onnection = Get-AzAutomationConnection -ResourceGroupName "Production ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomationConnection], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationConnection
```

## Steps to reproduce

```powershell
#Put the following cmdlet in a PowerShell Runbook in Azure Automation
$servicePrincipalConnection = Get-AzAutomationConnection -ResourceGroupName "MyResourceGroup" -AutomationAccountName "myautomationaccount" -Name "AzureRunAsConnection"
```

## Environment data

```
Name                           Value                                                                                    
----                           -----                                                                                    
PSVersion                      5.1.15063.726                                                                            
PSEdition                      Desktop                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  
BuildVersion                   10.0.15063.726                                                                           
CLRVersion                     4.0.30319.42000                                                                          
WSManStackVersion              3.0                                                                                      
PSRemotingProtocolVersion      2.3                                                                                      
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands                                              
---------- -------    ----                                ----------------                                              
Script     1.3.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enabl...
Script     1.1.0      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybr...
Script     1.1.2      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRo...
Script     1.0.2      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStora...
```

## Debug output

```
8:31:06 PM - GetAzureAutomationConnection begin processing with ParameterSet 'ByConnectionName'.
Get-AzAutomationConnection : Object reference not set to an instance of an object.
At line:5 char:31
+ ... onnection = Get-AzAutomationConnection -ResourceGroupName "Production ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomationConnection], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationConnection
 
AzureQoSEvent: CommandName - Get-AzAutomationConnection; IsSuccess - False; Duration - 00:00:00.7928667; Exception - 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient..ctor(IAzureContext context)
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.get_AutomationClient()
   at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationConnection.AutomationProcessRecord()
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
Finish sending metric.
8:31:08 PM - GetAzureAutomationConnection end processing.
8:31:08 PM - GetAzureAutomationConnection end processing.
```

## Error output

```
8:32:27 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.

InnerException   : False
Exception        : System.NullReferenceException: Object reference not set to an instance of an object.
                      at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient..ctor(IAzureContext context)
                      at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.get_AutomationClient()
                      at 
                   Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationConnection.AutomationProcessRecord()
                      at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Message          : Object reference not set to an instance of an object.
StackTrace       :    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient..ctor(IAzureContext context)
                      at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.get_AutomationClient()
                      at 
                   Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationConnection.AutomationProcessRecord()
                      at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : CloseError: (:) [Get-AzAutomationConnection], NullReferenceException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at <ScriptBlock>, <No file>: line 5
AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.1963090; Exception - ;
Finish sending metric.
8:32:27 PM - ResolveError end processing.
8:32:27 PM - ResolveError end processing.
```

**Comment by shietpas** [comment]
Although I find the documentation unclear, my current understanding is as follows...

The **Get-AutomationConnection** cmdlet should be used within Azure Automation to obtain the RunAs Connection information.  This cmdlet is part of the Azure module.

The following cmdlets require connecting to Azure prior to using (e.g. Connect-AzAccount):
* Get-AzureRmAutomationConnection within the AzureRm module
* Get-AzAutomationConnection within the AZ module

So, the above "error" may be expected functionality, and the Get-AutomationConnection should be used instead.

**Comment by ChuckByram** [comment]
Thanks, I was having the same issue as you were with the same thought of "Use Az now." Your post straightened me out and led me to an article I feel like I should have already run across describing how to use the connections (although, more or less global replace AzureRm with Az in the article). 

Reading it, I finally realized that `Get-AutomationConnection` is part of the Automation suite of internal cmdlets and was never part of AzureRm.Automation. The latter module had `Get-AzureRmAutomationConnection`, which is updated to Az.Automation with `Get-AzAutomationConnection`. 

https://docs.microsoft.com/en-us/azure/automation/automation-connections

**Comment by jpsebasti** [comment]
More pathetic documentation from Microsoft
