### ISSUE TITLE
Set-AzureRmKeyVaultAccessPolicy : Your Azure credentials have not been set up or have expired, please run Connect-AzureRmAccount to set up your Azure credentials.

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#8592]
## Description

I'm trying to create a resource group, key vault, assign access, policy. issue a certificate. All operations work but Key Vault. The error I'm getting is this:

>Set-AzureRmKeyVaultAccessPolicy : Your Azure credentials have not been set up or have expired, please run Connect-AzureRmAccount to set up your Azure credentials.
At line:1 char:1
 Set-AzureRmKeyVaultAccessPolicy -VaultName $kvName -ObjectId $account ...
    CategoryInfo          : CloseError: (:) [Set-AzureRmKeyVaultAccessPolicy], ArgumentException
    FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy

## Steps to reproduce

```powershell
$accountId = "..." # my aad app id
$accessToken = "..." # token for resource https://management.azure.com
$kvAccessToken = "..." # token for resource https://vault.azure.net

Connect-AzureRmAccount -Environment $cloudInstance `
						   -TenantId $tenantId `
						   -Subscription $subscriptionId `
						   -AccountId $accountId `
						   -AccessToken $accessToken `
						   -KeyVaultAccessToken $kvAccessToken `
						   -Verbose

Set-AzureRmKeyVaultAccessPolicy -VaultName $kvName `
								-ObjectId $accountId `
								-PermissionsToKeys create,list `
								-PermissionsToSecrets list,set `
								-PermissionsToCertificates get, create, update, setissuers, manageissuers, managecontacts, listissuers, getissuers `
								-Verbose
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.6.0      AzureRM.Profile                     {Add-AzureRmEnvironment, Clear-AzureRmContext, Clear-AzureRmDefault, Connect-AzureRmAccount...}
Script     5.2.1      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate, Add-AzureKeyVaultCertificateContact, Add-AzureKeyVaultKey, Add-AzureKeyVa...
```

## Debug output

>DEBUG: AzureQoSEvent: CommandName - Set-AzureRmKeyVaultAccessPolicy; IsSuccess - False; Duration - 00:00:00.4763048; Exception - System.ArgumentException: Your Azure credentials have not been set up or have expired, please run Connect-AzureRmAccount to set up your Azure credentials. ---> System.InvalidOperationException: Cannot retrieve access token for resource 'Graph'.  Please ensure that you have provided the appropriate access tokens when using access token login.
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String
tenant, SecureString password, String promptBehavior, Action``1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.KeyVault.Models.DataServiceCredential.GetTokenInternal(String tenantId, IAuthenticationFactory authFactory, IAzureContext context,
String resourceIdEndpoint)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.KeyVault.Models.DataServiceCredential.GetTokenInternal(String tenantId, IAuthenticationFactory authFactory, IAzureContext context,
String resourceIdEndpoint)
   at Microsoft.Azure.Commands.KeyVault.Models.DataServiceCredential.GetToken()
   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.<get_ActiveDirectoryClient>b__7_0()
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<SetToken>d__1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<ExecuteAsyncInternal>d__59`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ActiveDirectory.GraphClient.ActiveDirectoryClient.<GetObjectsByObjectIdsAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.ValidateObjectId(String objId)
   at Microsoft.Azure.Commands.KeyVault.KeyVaultManagementCmdletBase.GetObjectId(String objectId, String upn, String email, String spn)
   at Microsoft.Azure.Commands.KeyVault.SetAzureKeyVaultAccessPolicy.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
>DEBUG: Finish sending metric.
>DEBUG: 13:43:52 - SetAzureKeyVaultAccessPolicy end processing.
>DEBUG: 13:43:52 - SetAzureKeyVaultAccessPolicy end processing.

## Error output

>Message        : You must call the Connect-AzureAD cmdlet before calling any other cmdlets.
StackTrace     :    at Microsoft.Open.Azure.AD.CommonLibrary.AzureSession.ClientAuthenticated() in
                 X:\bt\916598\repo\src\dev\PowerShell.V2\CommonLibrary\Models\AzureSession.cs:line 110
                    at Microsoft.Open.Azure.AD.CommonLibrary.GetAzureADCurrentSessionInfo.ProcessRecord() in
                 X:\bt\916598\repo\src\dev\PowerShell.V2\CommonLibrary\ConnectAzureAD.cs:line 284
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
Exception      : Microsoft.Open.Azure.AD.CommonLibrary.AadNeedAuthenticationException
InvocationInfo : {Get-AzureADCurrentSessionInfo}
Line           : Get-AzureADCurrentSessionInfo
Position       : At line:1 char:1
                 Get-AzureADCurrentSessionInfo

**Comment by maddieclayton** [comment]
Hi @abatishchev - The issue here is that right now, Set-AzureRmKeyVaultAccessPolicy does a graph call to check that the ObjectId is valid, and your graph token is missing.  However, in the release tomorrow at 10am, I have added a fix that will only required the graph client to be created if you provide one of the parameter sets that does not contain ObjectId (in the case that you are required to do a graph lookup). Please update your Az module tomorrow morning, and let me know whether you continue to see an issue with this cmdlet (I will reopen the issue if this is the case)
