### ISSUE TITLE
Executing Connect-AzureRmAccount programmatically under unprivileged user throws UnauthorizedAccessException

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#8615]
## Description

I'm running my PowerShell script using C# API and console app runs under normal user (which indeed doesn't have the permissions to the said file) then it fails with an exception.

>ERROR: Access to the path 'C:\\Users\\Default\\AppData\\Roaming\\Windows Azure Powershell\\AzureRmContext.json' is denied.
 Exception: System.UnauthorizedAccessException: Access to the path 'C:\\Users\\Default\\AppData\\Roaming\\Windows Azu
re Powershell\\AzureRmContext.json' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.OpenForExclusiveWrite(String path)
   at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.ProtectedFileProvider.TryGetStreamLock(Func'2 acquireLock, String filePath, Stream& stream)
   at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.ProtectedFileProvider.InitializeStream()
   at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.ProtectedFileProvider.CreateReader()
   at Microsoft.Azure.Commands.Co
mmon.Authentication.Models.AzureRmProfile.Load(IFileProvider provider)
   at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.AzureRmAutosaveProfile.TrySetDefaultContext(IAzureContext context)
   at Microsoft.Azure.Commands.Common.Authentication.ResourceManager.AzureRmAutosaveProfile.TrySetDefaultContext(String name, IAzureContext context)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action'1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass87_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action'2 contextAction)
  at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action'3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

## Steps to reproduce

```c#
using (var shell = System.Management.Automation.PowerShell.Create())
{
    shell.AddScript(script.ScriptBody);
    shell.AddParameters(script.ScriptParameters);

    shell.Streams.Verbose.DataAdded += OnVerbose;
    shell.Streams.Warning.DataAdded += OnWarning;
    shell.Streams.Error.DataAdded += OnError;

    var result = await Task.Factory.FromAsync(this.shell.BeginInvoke(), r => this.shell.EndInvoke(r));
}
```

```powershell
Connect-AzureRmAccount -Environment $cloudInstance `
			-TenantId $tenantId `
			-Subscription $subscriptionId `
			-AccountId $accountId `
			-AccessToken $accessToken `
			-Verbose
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.6.0      AzureRM.Profile
```

## Error output

None of these two added anything to output what was not mentioned above.

**Comment by abatishchev** [comment]
Solution: add parameter `-Scope Process`.

Could this have been better documented, please?

**Comment by markcowl** [comment]
Closing, we should make sure this scenario is covered in #6185
