### ISSUE TITLE
Set-AzureRmStorageContainerImmutabilityPolicy throws Microsoft.Rest.Azure.CloudException: The server was unable to complete your request.

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-powershell#8617]
## Description

When I'm running my PowerShell script interactively it works fine. But if I'm running it using C# API then it fails with an exception:

>The server was unable to complete your request.
 Exception: Microsoft.Rest.Azure.CloudException: The server was unable to complete your request.
   at Microsoft.Azure.Management.Storage.BlobContainersOperations.<CreateOrU
pdateImmutabilityPolicyWithHttpMessagesAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.BlobContainersOperationsExtensions.<CreateOrUpdateImmutabilityPolicyAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Storage.BlobContainersOperationsExtensions.CreateOrUpdateImmutabilityPolicy(IBlobContainersOperations operations, String resourceGroupName, String accountName, String containerName, Int32 immutabilityPeriodSinceCreationInDays, String ifMatch)
   at Microsoft.Azure.Commands.Management.Storage.S
etAzureStorageContainerImmutabilityPolicyCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()

## Steps to reproduce

```c#
using (var shell = System.Management.Automation.PowerShell.Create())
{
    shell.AddScript(script.ScriptBody);
    shell.AddParameters(script.ScriptParameters);

    shell.Streams.Verbose.DataAdded += OnVerbose;
    shell.Streams.Warning.DataAdded += OnWarning;
    shell.Streams.Error.DataAdded += OnError;

    var result = await Task.Factory.FromAsync(this.shell.BeginInvoke(), r => this.shell.EndInvoke(r));
}
```

```powershell
New-AzureStorageContainer -Name $containerName -Permission Container -Context $storageAccount.Context -Verbose
Set-AzureRmStorageContainerImmutabilityPolicy -ResourceGroupName $storageResourceGroupName -StorageAccountName $storageAccountName -ContainerName $containerName -ImmutabilityPeriod 3 -Verbose
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     5.6.0      AzureRM.Profile                 
Script     6.5.0      AzureRM.Resources            
Script     5.1.0      AzureRM.Storage               
```

## Error output

None of these two added anything to output what was not mentioned above.

**Comment by abatishchev** [comment]
Actually same error when running interactively.

### Debug output

```
DEBUG: 10:23:49 - SetAzureStorageContainerImmutabilityPolicyCommand begin processing with ParameterSet 'AccountName'.                                 
DEBUG: 10:23:49 - using account id '959e90ed-628c-43d3-bfd7-de8aa49be65a'...                                                                          
VERBOSE: Performing the operation "Set container ImmutabilityPolicy" on target "clip2-lsm-westus2-dev-2-20190226-102348".                             
DEBUG: ============================ HTTP REQUEST ============================                                                                         
                                                                                                                                                      
HTTP Method:                                                                                                                                          
PUT                                                                                                                                                   
                                                                                                                                                      
Absolute Uri:                                                                                                                                         
https://management.azure.com/subscriptions/56f636bd-e8f9-4694-b03f-8c8dc99d8231/resourceGroups/clip2-lsm-dev-deploy/providers/Microsoft.Storage/stora 
geAccounts/deployclip2lsmdev/blobServices/default/containers/clip2-lsm-westus2-dev-2-20190226-102348/immutabilityPolicies/default?api-version=2018-03 
-01-preview                                                                                                                                           
                                                                                                                                                      
Headers:                                                                                                                                              
x-ms-client-request-id        : e5ce361a-3645-49ee-b5c6-2d5143df8c8c                                                                                  
accept-language               : en-US                                                                                                                 
                                                                                                                                                      
Body:                                                                                                                                                 
{                                                                                                                                                     
  "properties": {                                                                                                                                     
    "immutabilityPeriodSinceCreationInDays": 3                                                                                                        
  }                                                                                                                                                   
}                                                                                                                                                     
                                                                                                                                                      
DEBUG: ============================ HTTP RESPONSE ============================                                                                        
                                                                                                                                                      
Status Code:                                                                                                                                          
InternalServerError                                                                                                                                   
                                                                                                                                                      
Headers:                                                                                                                                              
Pragma                        : no-cache                                                                                                              
x-ms-request-id               : 3ae53635-0015-45d1-b954-ab419f356489                                                                                  
Strict-Transport-Security     : max-age=31536000; includeSubDomains                                                                                   
x-ms-failure-cause            : service                                                                                                               
x-ms-ratelimit-remaining-subscription-writes: 1199                                                                                                    
x-ms-correlation-request-id   : 396e9b2a-068c-40b1-b4ea-fad98211f430                                                                                  
x-ms-routing-request-id       : WESTUS2:20190226T182410Z:396e9b2a-068c-40b1-b4ea-fad98211f430                                                         
X-Content-Type-Options        : nosniff                                                                                                               
Connection                    : close                                                                                                                 
Cache-Control                 : no-cache                                                                                                              
Date                          : Tue, 26 Feb 2019 18:24:10 GMT                                                                                         
Server                        : Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0                             
                                                                                                                                                      
Body:                                                                                                                                                 
{                                                                                                                                                     
  "error": {                                                                                                                                          
    "code": "UnexpectedException",                                                                                                                    
    "message": "The server was unable to complete your request."                                                                                      
  }                                                                                                                                                   
}                                                                                                                                                     
```

### Error output

```
RequestId      : 3ae53635-0015-45d1-b954-ab419f356489
Message        : The server was unable to complete your request.
ServerMessage  : UnexpectedException: The server was unable to complete your request.
                 (System.Collections.Generic.List'1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {InternalServerError}
RequestMessage : {PUT https://management.azure.com/subscriptions/56f636bd-1234-56789-b03f-8c8dc99d8231/resourceGroups/clip2-lsm-dev-deploy/providers/Microsoft.Storage/storageAccounts/deployclip2lsmdev/blobServices/default/containers/xyz-20190226-102348/immutabilityPolicies/default?api-version=2018-03-01-preview}
InvocationInfo : {Set-AzureRmStorageContainerImmutabilityPolicy}
Line           : Set-AzureRmStorageContainerImmutabilityPolicy -ResourceGroupName $storageResourceGroupName `
Position       : At New-ScaleUnit.ps1:125 char:1
                 + Set-AzureRmStorageContainerImmutabilityPolicy -ResourceGroupName $sto ...
StackTrace     :    at Microsoft.Azure.Management.Storage.BlobContainersOperations.<CreateOrUpdateImmutabilityPolicyWithHttpMessagesAsync>d__12.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Storage.BlobContainersOperationsExtensions.<CreateOrUpdateImmutabilityPolicyAsync>d__15.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Storage.BlobContainersOperationsExtensions.CreateOrUpdateImmutabilityPolicy(IBlobContainersOperationsoperations, String resourceGroupName, String accountName, String containerName, Int32 immutabilityPeriodSinceCreationInDays, StringifMatch)
                    at Microsoft.Azure.Commands.Management.Storage.SetAzureStorageContainerImmutabilityPolicyCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
```

**Comment by cormacpayne** [comment]
@blueww Hey Wei, would you mind taking a look at this issue?

**Comment by blueww** [comment]
The error is reported from server. PowerShell just show the error from server as it is.
I will contact the feature team to see why server report the error, and update you later.

**Comment by abatishchev** [comment]
Fails with same error regardless having trailing slash in audience or not.

At least concerning what I can control at my end:

```c#
public class JobSecrets
{
    [JobSecret(SecretProviderType.AadToken, "https://management.azure.com/")] // here
    public SecureString AccessToken { get; set; }
}
```

**Comment by blueww** [comment]
@abatishchev 
I have replied the mail thread with SRP team again. 
Let's wait for their reply.

**Comment by blueww** [comment]
@abatishchev
The fix should already been deployed long ago.
I will close the issue now.

Feel free to contact us if you still see any issue or need any further assistant from us.
