### ISSUE TITLE
`error occured while evaluating OData query` when using -FilterExpression parameter in Get-AzVMImage

### ISSUE THREAD

**Issue by dlepow** [Azure/azure-powershell#8643]
## Description
`GetAzVMImage` has a `-FilterExpression` parameter that takes a string. Help documentation is limited to "Specifies a filter expression". I have unsuccessfully tried various OData filter expressions that I think are valid but see errors similar to 
```
An error occurred while evaluating OData query. Verify that OData query syntax is valid
```
What is the expected format of the filter expression? If this is due to my user error with OData filter syntax, apologies in advance. Consider adding valid query syntax example to parameter description.

## Steps to reproduce
Trivial example without `-FilterExpression` returns data:
```powershell
Azure:/
PS Azure:\> Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindowsServer" -Offer "windowsserver" -Skus "2016-Datacenter"

Version           FilterExpression Skus            Offer         PublisherName          Location  Id
-------           ---------------- ----            -----         -------------          --------  --
2016.127.20180613                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...
2016.127.20180815                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...
2016.127.20180912                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...
2016.127.20181010                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...
2016.127.20181122                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...
2016.127.20181218                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...
2016.127.20190115                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...
2016.127.20190214                  2016-Datacenter windowsserver MicrosoftWindowsServer centralus /Subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/Providers/Microsoft.Compute/Locations/centralus/Publishers/MicrosoftWindowsServer/A...

```

Simple OData filter expression `-FilterExpression "Offer eq 'windowsserver'"` fails:

```powershell
PS Azure:\> Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindowsServer" -Offer "windowsserver" -Skus "2016-Datacenter" -FilterExpression "Offer eq 'windowsserver'"
Get-AzVMImage : An error occurred while evaluating OData query. Verify that OData query syntax is valid.
ErrorCode: BadRequest
ErrorMessage: An error occurred while evaluating OData query. Verify that OData query syntax is valid.
ErrorTarget:
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : da0c632d-50a7-4f40-9dca-f1ba3445e3ea
At line:1 char:1
+ Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzVMImage], ComputeCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMImageCommand

```

Also tried passing in OData filter as a variable, fails:

```powershell
PS Azure:\> $query = "`$filter=Offer eq 'windowsserver'"
Azure:/
PS Azure:\> Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindowsServer" -Offer "windowsserver" -Skus "2016-Datacenter" -FilterExpression $query
Get-AzVMImage : An error occurred while evaluating OData query. Verify that OData query syntax is valid.
ErrorCode: BadRequest
ErrorMessage: An error occurred while evaluating OData query. Verify that OData query syntax is valid.
ErrorTarget:
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 583bad8e-2f92-4580-b436-edefb679f185
At line:1 char:1
+ Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzVMImage], ComputeCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMImageCommand
```
## Environment data (Azure Cloud Shell)

```
PS Azure:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Linux 4.15.0-1039-azure #43-Ubuntu SMP Fri Feb 15 17:43:49 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
PS Azure:\>  (Get-Module -Name Az.* -ListAvailable)


    Directory: /usr/local/share/powershell/Modules


ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.3.0      Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.0.1      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.0.2      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}
Script     1.0.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-AzApiManagementSystemCertificate...}
Script     1.0.0      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan...}
Script     1.1.1      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...}
Script     1.0.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}
Script     1.0.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}
Script     1.0.1      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.0.1      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveServicesAccountType...}
Script     1.4.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.0.0      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.0.1      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}
Script     1.0.1      Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCredential...}
Script     1.1.0      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider...}
Script     1.0.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}
Script     1.0.0      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}
Script     1.1.0      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}
Script     1.0.1      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.0.0      Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition...}
Script     1.0.2      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}
Script     1.0.2      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}
Script     1.2.0      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl...}
Script     1.0.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan...}
Script     1.0.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability...}
Script     1.0.1      Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     1.2.1      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzAp...
Script     1.0.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNSCredentials...}
Script     1.1.0      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-Az...
Script     1.0.0      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}
Script     1.0.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys, Get-AzPowerBIWorkspace...}
Script     1.0.1      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}
Script     1.0.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule...}
Script     1.0.0      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}
Script     1.1.3      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.0.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}
Script     1.0.1      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}
Script     1.0.2      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     1.3.0      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgrade...
Script     1.0.2      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.0.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction...}
Script     1.0.1      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficManagerCusto...
Script     1.1.1      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
```

## Debug output

```
PS Azure:\> Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindowsServer" -Offer "windowsserver" -Skus "2016-Datacenter" -FilterExpression "Offer eq 'windowsserver'"
DEBUG: 12:17:02 AM - GetAzureVMImageCommand begin processing with ParameterSet 'ListVMImage'.
DEBUG: 12:17:02 AM - using account id 'MSI@50342'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'MSI@50342', environment: 'AzureCloud', tenant: '72f988bf-86f1-41af-91ab-2d7cd011db47'
DEBUG: [HttpClientOperations]: Adding Header 'Metadata'
DEBUG: Checking Cache request http://localhost:50342/oauth2/token?resource=https%3A%2F%2Fmanagement.core.windows.net%2F&api-version=2018-02-01
DEBUG: Cache Hit
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/e44f251c-c67e-4760-9ed6-bf99a306ecff/providers/Microsoft.Compute/locations/centralus/publishers/MicrosoftWindowsServer/artifacttypes/vmimage/offers/windowsserver/skus/2016-Datacenter/versions?$filter=Offer eq 'windowsserver'&api-version=2018-10-01

Headers:
x-ms-client-request-id        : d15c4dd6-7ac3-4b36-ad90-65a16c7845ae
Accept-Language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Cache-Control                 : no-cache
Pragma                        : no-cache
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-served-by                : 6f07358a-dc74-42f6-aea3-3cb2b04c71e5_131844830384210407
x-ms-request-id               : 3d71a209-2c16-47b9-b0ad-0a58b418f187
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11996
x-ms-correlation-request-id   : a29c189b-d08b-4dec-9c1a-e5285eef5326
x-ms-routing-request-id       : WESTUS:20190228T001702Z:a29c189b-d08b-4dec-9c1a-e5285eef5326
X-Content-Type-Options        : nosniff
Date                          : Thu, 28 Feb 2019 00:17:02 GMT

Body:
{
  "error": {
    "code": "BadRequest",
    "message": "An error occurred while evaluating OData query. Verify that OData query syntax is valid."
  }
}


DEBUG: AzureQoSEvent: CommandName - Get-AzVMImage; IsSuccess - True; Duration - 00:00:00.4301169; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 12:17:02 AM - GetAzureVMImageCommand end processing.
DEBUG: 12:17:02 AM - GetAzureVMImageCommand end processing.
Get-AzVMImage : An error occurred while evaluating OData query. Verify that OData query syntax is valid.
ErrorCode: BadRequest
ErrorMessage: An error occurred while evaluating OData query. Verify that OData query syntax is valid.
ErrorTarget:
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 3d71a209-2c16-47b9-b0ad-0a58b418f187
At line:1 char:1
+ Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindows ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Get-AzVMImage], ComputeCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.GetAzureVMImageCommand

DEBUG: AzureQoSEvent: CommandName - Get-AzVMImage; IsSuccess - False; Duration - 00:00:00.4301169; Exception - Microsoft.Azure.Commands.Compute.Common.ComputeCloudException: An error occurred while evaluating OData query. Verify that OData query syntax is valid.
ErrorCode: BadRequest
ErrorTarget:
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : 3d71a209-2c16-47b9-b0ad-0a58b418f187 ---> Microsoft.Rest.Azure.CloudException: An error occurred while evaluating OData query. Verify that OData query syntax is valid.
   at Microsoft.Azure.Management.Compute.VirtualMachineImagesOperations.ListWithHttpMessagesAsync(String location, String publisherName, String offer, String skus, ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Commands.Compute.GetAzureVMImageCommand.<ExecuteCmdlet>b__26_0()
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:17:02 AM - GetAzureVMImageCommand end processing.
DEBUG: 12:17:02 AM - GetAzureVMImageCommand end processing.
```

## Error output

```
PS Azure:\> Resolve-AzureRmError
DEBUG: 12:17:25 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 12:17:25 AM - using account id 'MSI@50342'...


   HistoryId: 3


RequestId      :
Message        : An error occurred while evaluating OData query. Verify that OData query syntax is valid.
                 ErrorCode: BadRequest
                 ErrorMessage: An error occurred while evaluating OData query. Verify that OData query syntax is valid.
                 ErrorTarget:
                 StatusCode: 400
                 ReasonPhrase: Bad Request
                 OperationID : 3d71a209-2c16-47b9-b0ad-0a58b418f187
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {Get-AzVMImage}
Line           : Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindowsServer" -Offer "windowsserver" -Skus "2016-Datacenter" -FilterExpression "Offer eq 'windowsserver'"
Position       : At line:1 char:1
                 + Get-AzVMImage -Location "Central US" -PublisherName "MicrosoftWindows ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Compute.ComputeClientBaseCmdlet.ExecuteClientAction(Action action)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
HistoryId      : 3

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.0323606; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 12:17:25 AM - ResolveError end processing.
DEBUG: 12:17:25 AM - ResolveError end processing.
```

**Comment by cormacpayne** [comment]
@hyonholee Hey Hyonho, would you mind taking a look at this issue?

**Comment by dlepow** [comment]
@hyonholee @cormacpayne - Any advice on this? The short summary of this issue: What is the required/expected format of the `-FilterExpression` parameter in `Get-AzVmImage`? Thanks for clarifying.

**Comment by Drewm3** [comment]
The API docs have been updated to remove the $filter parameter because it is not supported on this API.
