### ISSUE TITLE
Invoke-AzResourceAction : BadRequest : Cannot deserialize the current JSON object

### ISSUE THREAD

**Issue by evgeniylu** [Azure/azure-powershell#8651]
## Description

Running script that perfectly run on Azure Automation, but fail with unexpected error - Cannot deserialize the current JSON object

## Steps to reproduce
Upload script.ps1 into blob container.
#### script.ps1
```powershell
param(
  [string]$arg1,
  [string]$arg2
)

Get-ChildItem -Path "env:" > C:\software\tmp\env.txt
$filename="c:\software\tmp\{0:HH-mm-ss}.txt" -f (Get-Date)
"$filename $arg1 $arg2" | out-file -filepath $filename -append -force

Write-EventLog -EventId '1234' -LogName Application -Message $filename -Source "Windows Error Reporting" -EntryType Error
```

And execute follow workflow:
```powershell
workflow Invoke-BlobOnVM {
    param(
        [Parameter(Position = 0, Mandatory = $true)][string]$AutomationUserName,
        [Parameter(Position = 1, Mandatory = $true)][string]$RgName,
        [Parameter(Position = 2, Mandatory = $true)][string]$StorageName,
        [Parameter(Position = 3, Mandatory = $true)][string]$ContainerName,
        [Parameter(Position = 4, Mandatory = $true)][string]$vmCollectionString,
        [Parameter(Position = 5, Mandatory = $true)][string]$ScriptName,
        [Parameter(Position = 6, Mandatory = $true)][string]$ScriptParameters
    )
    
    Az.Accounts\Login-AzAccount -Credential (Get-AutomationPSCredential -Name $AutomationUserName)
    
    $vmCollection = $VmCollectionString.Split(',')

    $runCommandParameters = @{ 
        commandId = 'RunPowerShellScript'
        script    = @(
@"
New-Item -Path 'c:\software\tmp' -ItemType Directory -ErrorAction SilentlyContinue
(New-Object System.Net.WebClient).DownloadFile("https://${StorageName}.blob.core.windows.net/${ContainerName}/${ScriptName}", "c:\software\tmp\${ScriptName}")
powershell -NonInteractive "& ""c:\software\tmp\${ScriptName}"" ${ScriptParameters}"
Remove-Item -Path "c:\software\tmp\${ScriptName}"
"@
        )
    }

    foreach -parallel ($vmName in $vmCollection) {
        $vm = Az.Compute\Get-AzVM -ResourceGroupName $RgName -Name $vmName
        Az.Resources\Invoke-AzResourceAction -ResourceId $vm.Id -Action runCommand -Parameters $runCommandParameters -Force -ApiVersion 2018-10-01
    }
}
Invoke-BlobOnVM 'user' 'resourceGroup' 'storageName' 'containerName' 'vmName1','vmName2' 'script.ps1' '-arg1 var1 -arg2 var2'
```
On Azure automation executed without explicit workflow invocation.
On local machine - without login action.

## Environment data

```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.576                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.576                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

```

## Module versions

```powershell


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     1.3.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enab...
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredentia...
Script     1.0.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServic...
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, N...
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Rem...
Script     1.1.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHyb...
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAcc...
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollme...
Script     1.0.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfil...
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAc...
Script     1.4.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAv...
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzCont...
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-...
Script     1.0.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFa...
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalytic...
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeSt...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolic...
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRe...
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGr...
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzE...
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wa...
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-A...
Script     1.0.2      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, ...
Script     1.2.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccou...
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssocia...
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}             
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Ge...
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile...
Script     1.2.1      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-Az...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorization...
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSu...
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspa...
Script     1.0.1      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServi...
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheSchedul...
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNa...
Script     1.1.3      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzR...
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set...
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceF...
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSig...
Script     1.3.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlData...
Script     1.0.2      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStor...
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefau...
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTraf...
Script     1.1.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServ...
```

## Debug output

```
PS C:\work\code\git\mygit\azure> $DebugPreference='Continue'
PS C:\work\code\git\mygit\azure> c:\work\code\git\mygit\azure\scripts\benchmark\runbooks\Invoke-BlobOnVm.ps1
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:32 - GetAzureVMCommand begin processing with ParameterSet 'GetVirtualMachineInResourceGroupParamSet'.
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:32 - using account id 'evgeniyl@xxx.com'...
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Authenticating using Account: 'evgeniyl@xxx.com', environment: 'AzureCloud', tenant: 'XXXXXXXX_TENANT_ID_XXXXXXXXXXXX'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/XXX_SUBSCRIPTION_ID_XXXXXXXXXXX/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/bench-app02?api-version=2018-10-01

Headers:
x-ms-client-request-id        : 53a68edd-5b6e-4b36-92aa-a202efc72e5a
accept-language               : en-US

Body:
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/LowCostGet3Min;3979,Microsoft.Compute/LowCostGet30Min;31838
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 5a96a61d-f2bd-4820-b3fb-267b77897912
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: 11969
x-ms-correlation-request-id   : 258d49ed-d224-4669-b6fa-234a55fd86d1
x-ms-routing-request-id       : UKSOUTH2:20190228T175432Z:258d49ed-d224-4669-b6fa-234a55fd86d1
X-Content-Type-Options        : nosniff
Date                          : Thu, 28 Feb 2019 17:54:31 GMT

Body:
{
  "properties": {
    "vmId": "8eeeb628-5dc1-4d41-a4ca-b5684f87d45c",
    "hardwareProfile": {
      "vmSize": "Standard_D11_v2"
    },
    "storageProfile": {
      "imageReference": {
        "publisher": "MicrosoftWindowsServer",
        "offer": "WindowsServer",
        "sku": "2016-Datacenter",
        "version": "latest"
      },
      "osDisk": {
        "osType": "Windows",
        "name": "bench-app02_OsDisk1e1cf002439e457cac5050bc07d0aabd",
        "createOption": "FromImage",
        "caching": "ReadWrite",
        "writeAcceleratorEnabled": false,
        "managedDisk": {
          "storageAccountType": "StandardSSD_LRS",
          "id": "/subscriptions/XXX_SUBSCRIPTION_ID_XXXXXXXXXXX/resourceGroups/myResourceGroup/providers/Microsoft.Compute/disks/bench-app02_OsDisk1e1cf002439e457cac5050bc07d0aabd"
        },
        "diskSizeGB": 128
      },
      "dataDisks": []
    },
    "osProfile": {
      "computerName": "bench-app02",
      "adminUsername": "dev",
      "windowsConfiguration": {
        "provisionVMAgent": true,
        "enableAutomaticUpdates": false
      },
      "secrets": [],
      "allowExtensionOperations": true,
      "requireGuestProvisionSignal": true
    },
    "networkProfile": {
      "networkInterfaces": [
        {
          "id": "/subscriptions/XXX_SUBSCRIPTION_ID_XXXXXXXXXXX/resourceGroups/myResourceGroup/providers/Microsoft.Network/networkInterfaces/bench-app02-nic"
        }
      ]
    },
    "diagnosticsProfile": {
      "bootDiagnostics": {
        "enabled": true,
        "storageUri": "https://myStorageName.blob.core.windows.net/"
      }
    },
    "provisioningState": "Succeeded"
  },
  "resources": [
    {
      "properties": {
        "autoUpgradeMinorVersion": true,
        "provisioningState": "Succeeded",
        "publisher": "Microsoft.Compute",
        "type": "BGInfo",
        "typeHandlerVersion": "2.1"
      },
      "type": "Microsoft.Compute/virtualMachines/extensions",
      "location": "westeurope",
      "id": "/subscriptions/XXX_SUBSCRIPTION_ID_XXXXXXXXXXX/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/bench-app02/extensions/BGInfo",
      "name": "BGInfo"
    }
  ],
  "type": "Microsoft.Compute/virtualMachines",
  "location": "westeurope",
  "tags": {
    "vmType": "Batch"
  },
  "id": "/subscriptions/XXX_SUBSCRIPTION_ID_XXXXXXXXXXX/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/bench-app02",
  "name": "bench-app02"
}
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:AzureQoSEvent: CommandName - Get-AzVM; IsSuccess - True; Duration - 00:00:00.4192409; Exception - ;
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:Finish sending metric.
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:33 - GetAzureVMCommand end processing.
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:33 - GetAzureVMCommand end processing.
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:33 - InvokAzureResourceActionCmdlet begin processing with ParameterSet 'ByResourceId'.
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:33 - using account id 'evgeniyl@xxx.com'...
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Authenticating using Account: 'evgeniyl@xxx.com', environment: 'AzureCloud', tenant: 'XXXXXXXX_TENANT_ID_XXXXXXXXXXXX'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Authenticating using configuration values: Domain: 'XXXXXXXX_TENANT_ID_XXXXXXXXXXXX', Endpoint: 'https://login.microsoftonline.com/', ClientId: 'XXX_CLIENT_ID_XXX', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/XXXXXXXX_TENANT_ID_XXXXXXXXXXXX/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'XXXXXXXX_TENANT_ID_XXXXXXXXXXXX', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: 'XXX_CLIENT_ID_XXX', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Received token with LoginType 'LiveId', Tenant: 'XXXXXXXX_TENANT_ID_XXXXXXXXXXXX', UserId: 'evgeniyl@xxx.com'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '02/28/2019 18:53:10 +00:00', MultipleResource? 'True', Tenant: 'XXXXXXXX_TENANT_ID_XXXXXXXXXXXX', UserId: 'evgeniyl@xxx.com'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: User info for token DisplayId: 'evgeniyl@xxx.com', Name: Evgeniy L, IdProvider: 'https://sts.windows.net/XXXXXXXX_TENANT_ID_XXXXXXXXXXXX/', Uid: 'XXX_UID_XXX'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:[Common.Authentication]: Checking token expiration, token expires '02/28/2019 18:53:10 +00:00' Comparing to '02/28/2019 17:54:33 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:58:36.5148372'
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/XXX_SUBSCRIPTION_ID_XXXXXXXXXXX/resourceGroups/myResourceGroup/providers/Microsoft.Compute/virtualMachines/bench-app02/runCommand?api-version=2018-10-01

Headers:
User-Agent                    : PSVersion/v1.0.0.0,AzurePowershell/v1.0.0
ParameterSetName              : ByResourceId
CommandName                   : Invoke-AzResourceAction

Body:
{
  "commandId": "RunPowerShellScript",
  "script": {
    "CliXml": "<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\">\r\n  <Obj RefId=\"0\">\r\n    <TN RefId=\"0\">\r\n      <T>Deserialized.System.Object[]</T>\r\n      <T>Deserialized.System.Array</T>\r\n      <T>Deserialized.System.Object</T>\r\n    </TN>\r\n    <LST>\r\n      <S>New-Item -Path 'c:\\software\\tmp' -ItemType Directory -ErrorAction SilentlyContinue_x000A_(New-Object System.Net.WebClient).DownloadFile(\"https://myStorageName.blob.core.windows.net/myBlobContainer/script.ps1\", \"c:\\software\\tmp\\script.ps1\")_x000A_powershell -NonInteractive \"&amp; \"\"c:\\software\\tmp\\script.ps1\"\" -arg1 var1 -arg2 var2\"_x000A_Remove-Item -Path \"c:\\software\\tmp\\script.ps1\"</S>\r\n    </LST>\r\n  </Obj>\r\n</Objs>"
  }
}
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-resource: Microsoft.Compute/UpdateVM3Min;238,Microsoft.Compute/UpdateVM30Min;1197
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 40cde7f9-6422-452f-8c7b-c7ae6f3f8835
Cache-Control                 : no-cache
Server                        : Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 79146db5-1a10-4931-9949-f6ea2c81d241
x-ms-routing-request-id       : UKSOUTH2:20190228T175434Z:79146db5-1a10-4931-9949-f6ea2c81d241
X-Content-Type-Options        : nosniff
Date                          : Thu, 28 Feb 2019 17:54:33 GMT

Body:
{
  "error": {
    "code": "BadRequest",
    "message": "Cannot deserialize the current JSON object (e.g. {\"name\":\"value\"}) into type 'System.Collections.Generic.List`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.\r\nPath 'script.CliXml', line 4, position 13.",
    "target": "runCommandInput.script.CliXml"
  }
}
Az.Resources\Invoke-AzResourceAction : BadRequest : Cannot deserialize the current JSON object (e.g. {"name":"value"}) 
into type 'System.Collections.Generic.List`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to 
deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a 
normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be 
deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a 
JSON object.
Path 'script.CliXml', line 4, position 13.
At Invoke-BlobOnVM:30 char:30
+ 
    + CategoryInfo          : CloseError: (:) [Invoke-AzResourceAction], ErrorResponseMessageException
    + FullyQualifiedErrorId : 
Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
    + PSComputerName        : [localhost]
Az.Resources\Invoke-AzResourceAction : BadRequest : Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type
'System.Collections.Generic.List`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a
primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be
added to the type to force it to deserialize from a JSON object.
Path 'script.CliXml', line 4, position 13.
At Invoke-BlobOnVM:30 char:30
+
    + CategoryInfo          : CloseError: (:) [Invoke-AzResourceAction], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.InvokAzureResourceActionCmdlet
    + PSComputerName        : [localhost]

DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:AzureQoSEvent: CommandName - Invoke-AzResourceAction; IsSuccess - False; Duration - 00:00:00.6287743; Exception - Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException: BadRequest : Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'script.CliXml', line 4, position 13.
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:Finish sending metric.
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:34 - InvokAzureResourceActionCmdlet end processing.
DEBUG: 6760fa6e-ff05-4eab-9372-6cd2780b3c89:[localhost]:19:54:34 - InvokAzureResourceActionCmdlet end processing.

```

## Error output

```


   HistoryId: -1


Message        : BadRequest : Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 
                 'System.Collections.Generic.List`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
                 To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type 
                 (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. 
                 JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
                 Path 'script.CliXml', line 4, position 13.
StackTrace     : 
Exception      : System.Management.Automation.RemoteException
InvocationInfo : {Invoke-AzResourceAction}
Line           : 
Position       : At Invoke-BlobOnVM:30 char:30
                 + 
HistoryId      : -1

Message        : BadRequest : Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 
                 'System.Collections.Generic.List`1[System.String]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
                 To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type 
                 (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. 
                 JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
                 Path 'script.CliXml', line 4, position 13.
StackTrace     : 
Exception      : System.Management.Automation.RemoteException
InvocationInfo : {Invoke-AzResourceAction}
Line           : 
Position       : At Invoke-BlobOnVM:30 char:30
                 + 
HistoryId      : -1

```

**Comment by evgeniylu** [comment]
This code works without a problem:
```powershell
$rgName = 'myResourceGroup'
$item = 'bench-app02'
$vm = Az.Compute\Get-AzVM -ResourceGroupName $rgName -Name $item
$resourceId = $vm.Id

$parameters = @{
    commandId = 'RunPowerShellScript'
    script = @( "ls /" )
    parameters = @( )
}
Invoke-AzResourceAction -ResourceId $resourceId -Action runCommand -Parameters $parameters -ApiVersion 2017-03-30 -Force

```

**Comment by markcowl** [comment]
@evgeniylu  Why are you executing the command this way, rather than using ```Invoke-AzVmRunCommand```

Also, can you provide the debug stream from a correct execution in Automation?  Generally you can get this by setting $DebugPreference="Continue" in your runbook script, and executing the runbook in the Test Pane

**Comment by cormacpayne** [comment]
@evgeniylu ping on the above comments

**Comment by maddieclayton** [comment]
Closing for inactivity - @evgeniylu Please reopen if you are able to provide the requested information above.
