### ISSUE TITLE
 Login to Azure with certificate from Linux environment

### ISSUE THREAD

**Issue by groovy-sky** [Azure/azure-powershell#8658]
## Description
I am trying non-interactive spn/certificate login(on Linux environment). 

Run screenshot - https://ibb.co/3SMtqy7

## Steps to reproduce

```powershell
openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout /etc/ssl/private/key.pem -out /etc/ssl/private/cert.pem -subj "/C=LV/ST=Some-State/L=LV/O=IT/OU=IT"

# Get cert thumbprint
$keyValue = Get-Content /etc/ssl/private/cert.pem
$Thumbprint=[Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($keyValue))

# Connect to Azure
Import-Module Az.Resources
Connect-AzAccount

# Create SPN and add certificate
$ApplicationDisplayName = 'AuditSPN' + $(Get-Date -UFormat "%Y%m%d%S")
$ServicePrincipal = New-AzADServicePrincipal -DisplayName $ApplicationDisplayName
sleep 20s 
$ServicePrincipal | New-AzADSpCredential -CertValue $Thumbprint

# Get required parameters
$Tenant = Get-AzTenant
$ApplicationId = $ServicePrincipal.Id

Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ApplicationId -Tenant $Tenant.Id -ServicePrincipal
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Linux 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
ModuleType Version    Name                                PSEdition ExportedCommands
---------- -------    ----                                --------- ----------------
Script     1.3.0      Az.Accounts                         Core,Desk {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.0.1      Az.Aks                              Core,Desk {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.0.0      Az.AnalysisServices                 Core,Desk {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}
Script     1.0.0      Az.ApiManagement                    Core,Desk {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-AzApiManagementSystemCertificate...}
Script     1.0.0      Az.ApplicationInsights              Core,Desk {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan...}
Script     1.1.0      Az.Automation                       Core,Desk {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...}
Script     1.0.0      Az.Batch                            Core,Desk {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}
Script     1.0.0      Az.Billing                          Core,Desk {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}
Script     1.0.1      Az.Cdn                              Core,Desk {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.0.0      Az.CognitiveServices                Core,Desk {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveServicesAccountType...}
Script     1.3.0      Az.Compute                          Core,Desk {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.0.0      Az.ContainerInstance                Core,Desk {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.0.1      Az.ContainerRegistry                Core,Desk {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}
Script     1.0.1      Az.DataFactory                      Core,Desk {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.0      Az.DataLakeAnalytics                Core,Desk {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCredential...}
Script     1.0.2      Az.DataLakeStore                    Core,Desk {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider...}
Script     1.0.0      Az.DevTestLabs                      Core,Desk {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}
Script     1.0.0      Az.Dns                              Core,Desk {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}
Script     1.1.0      Az.EventGrid                        Core,Desk {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}
Script     1.0.0      Az.EventHub                         Core,Desk {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.0.0      Az.HDInsight                        Core,Desk {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition...}
Script     1.0.2      Az.IotHub                           Core,Desk {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}
Script     1.0.1      Az.KeyVault                         Core,Desk {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}
Script     1.1.0      Az.LogicApp                         Core,Desk {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountCallbackUrl, Get-AzIntegrationAccountCertificate, Get-AzIntegrationAccount...}
Script     1.0.0      Az.MachineLearning                  Core,Desk {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan...}
Script     1.0.0      Az.MarketplaceOrdering              Core,Desk {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            Core,Desk {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability...}
Script     1.0.0      Az.Monitor                          Core,Desk {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     1.1.0      Az.Network                          Core,Desk {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzAp...
Script     1.0.0      Az.NotificationHubs                 Core,Desk {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNSCredentials...}
Script     1.0.0      Az.OperationalInsights              Core,Desk {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-Az...
Script     1.0.0      Az.PolicyInsights                   Core,Desk {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}
Script     1.0.0      Az.PowerBIEmbedded                  Core,Desk {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys, Get-AzPowerBIWorkspace...}
Script     1.0.0      Az.RecoveryServices                 Core,Desk {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}
Script     1.0.0      Az.RedisCache                       Core,Desk {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule...}
Script     1.0.0      Az.Relay                            Core,Desk {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}
Script     1.1.2      Az.Resources                        Core,Desk {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.0.0      Az.ServiceBus                       Core,Desk {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}
Script     1.0.1      Az.ServiceFabric                    Core,Desk {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}
Script     1.0.2      Az.SignalR                          Core,Desk {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     1.2.0      Az.Sql                              Core,Desk {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgrade...
Script     1.0.2      Az.Storage                          Core,Desk {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.0.0      Az.StreamAnalytics                  Core,Desk {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction...}
Script     1.0.1      Az.TrafficManager                   Core,Desk {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficManagerCusto...
Script     1.1.0      Az.Websites                         Core,Desk {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}

```

## Debug output

```
DEBUG: AzureQoSEvent: CommandName - Connect-AzAccount; IsSuccess - False; Duration - 00:00:00.0185088; Exception - System.Security.Cryptography.CryptographicException: Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores. ---> System.PlatformNotSupportedException: Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores.
   --- End of inner exception stack trace ---
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.<>c__DisplayClass22_0.<TryFindCertificatesInStore>b__0(X509Store store)
   at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.X509StoreWrapper(StoreName storeName, StoreLocation storeLocation, Action`1 action)
   at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.TryFindCertificatesInStore(String thumbprint, StoreLocation location, X509Certificate2Collection& certificates)
   at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.GetCertificate(String thumbprint)
   at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.AcquireTokenWithCertificate(AdalConfiguration config, String appId, String thumbprint)
   at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessTokenWithCertificate(AdalConfiguration config, String clientId, String certificateThumbprint, String credentialType)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password, Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
   at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
   at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 6:49:58 AM - ConnectAzureRmAccountCommand end processing.
DEBUG: 6:49:58 AM - ConnectAzureRmAccountCommand end processing.
```

## Error output

```

Message        : Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores.
StackTrace     :    at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
                    at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.<>c__DisplayClass22_0.<TryFindCertificatesInStore>b__0(X509Store store)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.X509StoreWrapper(StoreName storeName, StoreLocation storeLocation, Action`1 action)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.TryFindCertificatesInStore(String thumbprint, StoreLocation location, X509Certificate2Collection& certificates)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.GetCertificate(String thumbprint)
                    at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.AcquireTokenWithCertificate(AdalConfiguration config, String appId, String thumbprint)
                    at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessTokenWithCertificate(AdalConfiguration config, String clientId, String certificateThumbprint, String credentialType)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior,
                 Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1
                 promptAction)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password,
                 Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Security.Cryptography.CryptographicException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ApplicationId -Tenant $Tenant.Id -ServicePrincipal
Position       : At line:1 char:1
                 + Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 19

Message        : Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores.
StackTrace     :
Exception      : System.PlatformNotSupportedException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ApplicationId -Tenant $Tenant.Id -ServicePrincipal
Position       : At line:1 char:1
                 + Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 19



   HistoryId: 17


Message        : Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores.
StackTrace     :    at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
                    at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.<>c__DisplayClass22_0.<TryFindCertificatesInStore>b__0(X509Store store)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.X509StoreWrapper(StoreName storeName, StoreLocation storeLocation, Action`1 action)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.TryFindCertificatesInStore(String thumbprint, StoreLocation location, X509Certificate2Collection& certificates)
                    at Microsoft.Azure.Commands.Common.Authentication.Abstractions.DiskDataStore.GetCertificate(String thumbprint)
                    at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.AcquireTokenWithCertificate(AdalConfiguration config, String appId, String thumbprint)
                    at Microsoft.Azure.Commands.Common.Authentication.ServicePrincipalTokenProvider.GetAccessTokenWithCertificate(AdalConfiguration config, String clientId, String certificateThumbprint, String credentialType)
                    at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior,
                 Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1
                 promptAction)
                    at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(IAzureAccount account, IAzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password,
                 Boolean skipValidation, Action`1 promptAction, String name, Boolean shouldPopulateContextList)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.<>c__DisplayClass92_0.<ExecuteCmdlet>b__0(AzureRmProfile localProfile, RMProfileClient profileClient, String name)
                    at Microsoft.Azure.Commands.Profile.Common.AzureContextModificationCmdlet.ModifyContext(Action`2 contextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.SetContextWithOverwritePrompt(Action`3 setContextAction)
                    at Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Security.Cryptography.CryptographicException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ApplicationId -Tenant $Tenant.Id -ServicePrincipal
Position       : At line:1 char:1
                 + Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 17

Message        : Unix LocalMachine X509Store is limited to the Root and CertificateAuthority stores.
StackTrace     :
Exception      : System.PlatformNotSupportedException
InvocationInfo : {Connect-AzAccount}
Line           : Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ApplicationId -Tenant $Tenant.Id -ServicePrincipal
Position       : At line:1 char:1
                 + Connect-AzAccount -CertificateThumbprint $Thumbprint -ApplicationId $ ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 17

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.0565917; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 6:50:37 AM - ResolveError end processing.
DEBUG: 6:50:37 AM - ResolveError end processing.
```

**Comment by markcowl** [comment]
On a non-windows machine, you will need to create and add your certificate to the LocalMachine or CurrentUser My store.  It is also a little complex to create the necessary X509Certificate2 that is needed to populate the store from a PEM file.  Once solution would be to use openssl to create a pkcs12 file that could be easily transferred to an X509Certificate2. (described in detail here: https://www.codeproject.com/Articles/162194/Certificates-to-DB-and-Back)
```
openssl pkcs12 -in <path-to-public-key> -inkey <path-to-private-key> -export -out merged.pfx
```

This should prompt for a password which you will use later to access the private key.

Once you have a pkcs12 archive to represent the cert, here is some sample code that should allow you to login:

```powershell
$StoreName = [System.Security.Cryptography.X509Certificates.StoreName]::My 
$StoreLocation = [System.Security.Cryptography.X509Certificates.StoreLocation]::CurrentUser 
$Store = [System.Security.Cryptography.X509Certificates.X509Store]::new($StoreName, $StoreLocation) 
$Flag = [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable 
$Certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new(<path-to-pfx-archive>, <password-from-pfx-export>, $Flag) 
$Store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite) 
$Store.Add($Certificate) 
$Store.Close() 
```

You should then be able to log in using ```$Certificate.Thumbprint``` as the thumbprint.

For your scenario, it seems that it would be far simpler to simply be able to provide the public and private key for the cert as part of the Connect-AzAccount cmdlet, instead of the thumbprint.  How useful would this be to you, as opposed to using the SPN + Secret flow for logging in?

**Comment by groovy-sky** [comment]
[markcowl](/markcowl) thank you very much. I was able to login, but some parts still didn't worked (I uploaded certificate manually and copied from the portal a thumbprint).

For me it would be very useful if I could provide public and private key as part of the Connect-AzAccount cmdlet. Could you, please, describe how-to do that?

**Comment by cormacpayne** [comment]
@groovy-sky I'm going to close this issue in favor of https://github.com/Azure/azure-powershell/issues/8675 -- any additional comments from this issue can be addressed there

**Comment by AndreiDita** [comment]
> On a non-windows machine, you will need to create and add your certificate to the LocalMachine or CurrentUser My store. It is also a little complex to create the necessary X509Certificate2 that is needed to populate the store from a PEM file. Once solution would be to use openssl to create a pkcs12 file that could be easily transferred to an X509Certificate2. (described in detail here: https://www.codeproject.com/Articles/162194/Certificates-to-DB-and-Back)
> 
> ```
> openssl pkcs12 -in <path-to-public-key> -inkey <path-to-private-key> -export -out merged.pfx
> ```
> 
> This should prompt for a password which you will use later to access the private key.
> 
> Once you have a pkcs12 archive to represent the cert, here is some sample code that should allow you to login:
> 
> ```powershell
> $StoreName = [System.Security.Cryptography.X509Certificates.StoreName]::My 
> $StoreLocation = [System.Security.Cryptography.X509Certificates.StoreLocation]::CurrentUser 
> $Store = [System.Security.Cryptography.X509Certificates.X509Store]::new($StoreName, $StoreLocation) 
> $Flag = [System.Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable 
> $Certificate = [System.Security.Cryptography.X509Certificates.X509Certificate2]::new(<path-to-pfx-archive>, <password-from-pfx-export>, $Flag) 
> $Store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadWrite) 
> $Store.Add($Certificate) 
> $Store.Close() 
> ```
> 
> You should then be able to log in using `$Certificate.Thumbprint` as the thumbprint.
> 
> For your scenario, it seems that it would be far simpler to simply be able to provide the public and private key for the cert as part of the Connect-AzAccount cmdlet, instead of the thumbprint. How useful would this be to you, as opposed to using the SPN + Secret flow for logging in?

Is there any way to achieve the same without manipulating the Private Key used in association with Private Certificate Authority to create a PFX ?
