### ISSUE TITLE
[Automation Account Tests]  direct call to [Microsoft.Azure.Test.HttpRecorder.HttpMockServer] in *Common.ps1

### ISSUE THREAD

**Issue by vladimir-shcherbakov** [Azure/azure-powershell#8693]
## Description

Direct call to [Microsoft.Azure.Test.HttpRecorder.HttpMockServer] gets used in *Common.ps1 to get test mode value.

```
InnerException   : False
Exception        : System.Management.Automation.RuntimeException: Unable to find type 
                   [Microsoft.Azure.Test.HttpRecorder.HttpMockServer].
                      at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                   funcContext, Exception exception)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
Message          : Unable to find type [Microsoft.Azure.Test.HttpRecorder.HttpMockServer].
StackTrace       :    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext 
                   funcContext, Exception exception)
                      at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
                      at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame 
                   frame)
HelpLink         : 
ErrorDetails     : 
ErrorCategory    : InvalidOperation: (Microsoft.Azure....HttpMockServer:TypeName) [], RuntimeException
InvocationInfo   : System.Management.Automation.InvocationInfo
ScriptStackTrace : at getAssetName, C:\Modules\User\Smoke.Tests\Common.ps1: line 381
                   at Get-WebHostPlanName, C:\Modules\User\Smoke.Tests\WebsitesCommon.ps1: line 42
                   at Test-WindowsContainerWebAppPSSessionOpened, C:\Modules\User\Smoke.Tests\WebAppTests.ps1: line 827
                   at Run-Test, C:\Modules\User\Smoke.Helper\Smoke.Helper.psm1: line 60
                   at <ScriptBlock>, <No file>: line 40

```
This should be fixed with one of the possible ways:
1) Put the call into try-catch block and return "Record" 
2) Upload [Microsoft.Azure.Test.HttpRecorder.HttpMockServer] proxy.

## Cost
2

**Comment by markcowl** [comment]
no longer relevant
