### ISSUE TITLE
Get-AzAutomationDscNodeConfiguration cmdlet execution fails (with unterminated literal error) if we use it's parameter 'ConfigurationName'

### ISSUE THREAD

**Issue by KrishnaG-MSFT** [Azure/azure-powershell#8738]
## Description
Get-AzAutomationDscNodeConfiguration cmdlet execution fails if we use it's parameter 'ConfigurationName'.

## Steps to reproduce

```powershell
PS C:\windows\system32> Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishnaCorps" -AutomationAccountName "gttest1krishnacorpsautoacc" -ConfigurationName "httpdLinuxServiceDSC"
Get-AzAutomationDscNodeConfiguration : There is an unterminated literal at position 54 in 'properties/configuration/name eq httpdLinuxServiceDSC''.
At line:1 char:1
+ Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishn ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomationDscNodeConfiguration], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationDscNodeConfiguration
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.3.1      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.0.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-AzApiManagementSystemCertificate...}
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan...}
Script     1.1.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...}
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}
Script     1.0.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveServicesAccountType...}
Script     1.4.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}
Script     1.0.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCredential...}
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider...}
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition...}
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}
Script     1.0.2      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}
Script     1.2.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl...}
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan...}
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability...}
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     1.2.1      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzApplication...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNSCredentials...}
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperation...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys, Get-AzPowerBIWorkspace...}
Script     1.0.1      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule...}
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}
Script     1.1.3      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     1.3.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgradeHint...}
Script     1.0.2      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction...}
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficManagerCustomHeaderFr...
Script     1.1.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
```

## Debug output

```
DEBUG: 12:54:21 AM - GetAzureAutomationDscNodeConfiguration begin processing with ParameterSet 'ByConfigurationName'.
DEBUG: 12:54:21 AM - using account id 'gtbmkrishna1@outlook.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'gtbmkrishna1@outlook.com', environment: 'AzureCloud', tenant: 'ebb3922d-4260-402c-a9f7-6763686fbe48'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/a11dc7c8-3220-448a-b894-7481bc50bb9f/resourceGroups/GTTestKrishnaCorps/providers/Microsoft.Automation/automationAccounts/gttest1krishnacorpsautoacc/nodeConfigurations?$filter=properties/config
uration/name eq httpdLinuxServiceDSC'&api-version=2018-01-15

Headers:
x-ms-client-request-id        : 8d38e7e8-4373-4662-8ace-ca74d2d4f774
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : 802e06d1-4162-4962-8978-c4b180f588e9
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11987
x-ms-correlation-request-id   : 04d68ad6-cf43-48fb-b44e-afdfecfb4cad
x-ms-routing-request-id       : SOUTHINDIA:20190310T192422Z:04d68ad6-cf43-48fb-b44e-afdfecfb4cad
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Sun, 10 Mar 2019 19:24:22 GMT
Server                        : Microsoft-IIS/10.0
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "code": "BadRequest",
  "message": "There is an unterminated literal at position 54 in 'properties/configuration/name eq httpdLinuxServiceDSC''."
}

Get-AzAutomationDscNodeConfiguration : There is an unterminated literal at position 54 in 'properties/configuration/name eq httpdLinuxServiceDSC''.
At line:1 char:1
+ Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishn ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzAutomationDscNodeConfiguration], ErrorResponseException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationDscNodeConfiguration

DEBUG: AzureQoSEvent: CommandName - Get-AzAutomationDscNodeConfiguration; IsSuccess - False; Duration - 00:00:01.7901906; Exception - Microsoft.Azure.Management.Automation.Models.ErrorResponseException: There is an unterminated literal
 at position 54 in 'properties/configuration/name eq httpdLinuxServiceDSC''. ---> Microsoft.Azure.Management.Automation.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperations.<ListByAutomationAccountWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions.<ListByAutomationAccountAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions.ListByAutomationAccount(IDscNodeConfigurationOperations operations, String resourceGroupName, String automationAccountName, ODataQuery`1 odataQuery,
String inlinecount)
   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.ListNodeConfigurationsByConfigurationName(String resourceGroupName, String automationAccountName, String configurationName, String rollupStatus, String& nextLink)
   at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationDscNodeConfiguration.AutomationProcessRecord()
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:54:24 AM - GetAzureAutomationDscNodeConfiguration end processing.
DEBUG: 12:54:24 AM - GetAzureAutomationDscNodeConfiguration end processing.
```

## Error output

```
DEBUG: 12:54:54 AM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 12:54:54 AM - using account id 'gtbmkrishna1@outlook.com'...


   HistoryId: 6


Message        : There is an unterminated literal at position 54 in 'properties/configuration/name eq httpdLinuxServiceDSC''.
StackTrace     :    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.Automation.Models.ErrorResponseException
InvocationInfo : {Get-AzAutomationDscNodeConfiguration}
Line           : Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishnaCorps" -AutomationAccountName "gttest1krishnacorpsautoacc" -ConfigurationName "httpdLinuxServiceDSC"
Position       : At line:1 char:1
                 + Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishn ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperations.<ListByAutomationAccountWithHttpMessagesAsync>d__8.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions.<ListByAutomationAccountAsync>d__7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions.ListByAutomationAccount(IDscNodeConfigurationOperations operations, String resourceGroupName, String automationAccountName,
                 ODataQuery`1 odataQuery, String inlinecount)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.ListNodeConfigurationsByConfigurationName(String resourceGroupName, String automationAccountName, String configurationName, String rollupStatus,
                 String& nextLink)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationDscNodeConfiguration.AutomationProcessRecord()
                    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Automation.Models.ErrorResponseException
InvocationInfo : {Get-AzAutomationDscNodeConfiguration}
Line           : Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishnaCorps" -AutomationAccountName "gttest1krishnacorpsautoacc" -ConfigurationName "httpdLinuxServiceDSC"
Position       : At line:1 char:1
                 + Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishn ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6



   HistoryId: 2


Message        : There is an unterminated literal at position 54 in 'properties/configuration/name eq httpdLinuxServiceDSC''.
StackTrace     :    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Management.Automation.Models.ErrorResponseException
InvocationInfo : {Get-AzAutomationDscNodeConfiguration}
Line           : Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishnaCorps" -AutomationAccountName "gttest1krishnacorpsautoacc" -ConfigurationName "httpdLinuxServiceDSC"
Position       : At line:1 char:1
                 + Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishn ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Operation returned an invalid status code 'BadRequest'
StackTrace     :    at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperations.<ListByAutomationAccountWithHttpMessagesAsync>d__8.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions.<ListByAutomationAccountAsync>d__7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.DscNodeConfigurationOperationsExtensions.ListByAutomationAccount(IDscNodeConfigurationOperations operations, String resourceGroupName, String automationAccountName,
                 ODataQuery`1 odataQuery, String inlinecount)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.ListNodeConfigurationsByConfigurationName(String resourceGroupName, String automationAccountName, String configurationName, String rollupStatus,
                 String& nextLink)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.GetAzureAutomationDscNodeConfiguration.AutomationProcessRecord()
                    at Microsoft.Azure.Commands.Automation.Cmdlet.AzureAutomationBaseCmdlet.ExecuteCmdlet()
Exception      : Microsoft.Azure.Management.Automation.Models.ErrorResponseException
InvocationInfo : {Get-AzAutomationDscNodeConfiguration}
Line           : Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishnaCorps" -AutomationAccountName "gttest1krishnacorpsautoacc" -ConfigurationName "httpdLinuxServiceDSC"
Position       : At line:1 char:1
                 + Get-AzAutomationDscNodeConfiguration -ResourceGroupName "GTTestKrishn ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.4378551; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 12:54:56 AM - ResolveError end processing.
DEBUG: 12:54:56 AM - ResolveError end processing.
```

**Comment by markcowl** [comment]
@safeermohammed @eamonoreilly It looks like generation fo the query string in this cmdlet is failing, can you take a look?

**Comment by KrishnaG-MSFT** [comment]
@markcowl @safeermohammed @eamonoreilly @vrdmr Any update on this please ?

**Comment by vrdmr** [comment]
@avkaur @mgreenegit Can you please take a look?

**Comment by avkaur** [comment]
investigating it

**Comment by mikebou** [comment]
I am experiencing the same issue. Any update would be appreciated.

**Comment by andyw248** [comment]
Looks like a bug. We'll follow up.

**Comment by alexanderluchs** [comment]
This looks like its still an issue in `Az.Automation 1.3.7`.  Would appreciate any follow up.

**Comment by vikram-m** [comment]
Product team is aware of this issue, and unfortunately because of other priorities were not able to pick this up. Please expect an update in Q4CY20.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by StuartSquibb-KF** [comment]
Is there any update on this? It is now 2024 and the same issue occurs in version 1.10.o of the module.
