### ISSUE TITLE
New-AzAks doesnt work with default settings

### ISSUE THREAD

**Issue by 4c74356b41** [Azure/azure-powershell#8742]
## Description
New-AzAks uses slightly **cough** outdated aks versions and doesnt work

## Steps to reproduce
```powershell
New-AzAks -ResourceGroupName rg_name -Name aks_name -Location location
```

## Environment data
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions
```powershell
Name                   Version
----                   -------
Az.Accounts            1.3.1
Az.Accounts            1.1.0
Az.Aks                 1.0.1
Az.AnalysisServices    1.0.0
Az.ApiManagement       1.0.0
Az.ApplicationInsights 1.0.0
Az.Automation          1.0.0
Az.Batch               1.0.0
Az.Billing             1.0.0
Az.Cdn                 1.0.0
Az.CognitiveServices   1.0.0
Az.Compute             1.1.0
Az.ContainerInstance   1.0.0
Az.ContainerRegistry   1.0.0
Az.DataFactory         1.0.0
Az.DataLakeAnalytics   1.0.0
Az.DataLakeStore       1.0.1
Az.DevTestLabs         1.0.0
Az.Dns                 1.0.0
Az.EventGrid           1.1.0
Az.EventHub            1.0.0
Az.HDInsight           1.0.0
Az.IotHub              1.0.1
Az.KeyVault            1.0.0
Az.LogicApp            1.1.0
Az.MachineLearning     1.0.0
Az.MarketplaceOrdering 1.0.0
Az.Media               1.0.0
Az.Monitor             1.0.0
Az.Network             1.0.0
Az.NotificationHubs    1.0.0
Az.OperationalInsights 1.0.0
Az.PolicyInsights      1.0.0
Az.PowerBIEmbedded     1.0.0
Az.RecoveryServices    1.0.0
Az.RedisCache          1.0.0
Az.Relay               1.0.0
Az.Resources           1.1.0
Az.ServiceBus          1.0.0
Az.ServiceFabric       1.0.0
Az.SignalR             1.0.1
Az.Sql                 1.0.1
Az.Storage             1.0.1
Az.StreamAnalytics     1.0.0
Az.TrafficManager      1.0.0
Az.Websites            1.0.1
```

## Debug output
```
Body:
{
  "properties": {
    "dnsPrefix": "omg-testota-0534ec",
    "kubernetesVersion": "1.8.1", ### LOL??
    "agentPoolProfiles": [
      {
        "name": "default",
        "count": 3,
        "vmSize": "Standard_D2_v2",
        "osDiskSizeGB": 0,
        "dnsPrefix": "omg-testota-0534ec"
      }
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "ppp"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "xxx",
      "secret": "yyy"
    }
  },
  "location": "westeurope"
}
```

## Error output
```
   HistoryId: 6


Message        : The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
StackTrace     :    at Microsoft.Azure.Commands.Aks.KubeCmdletBase.RunCmdLet(Action action)
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Management.Automation.PSInvalidOperationException
InvocationInfo : {New-AzAks}
Line           : New-AzAks -ResourceGroupName testota -Name omg -Location westeurope
Position       : At line:1 char:1
                 + New-AzAks -ResourceGroupName testota -Name omg -Location westeurope
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 6

RequestId      : 97b88332-a387-4fd0-a78a-4815329e9a3f
Message        : The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
ServerMessage  : InvalidParameter: The value of parameter orchestratorProfile.OrchestratorVersion is invalid.
                 (System.Collections.Generic.List`1[Microsoft.Rest.Azure.CloudError])
ServerResponse : {BadRequest}
RequestMessage : {PUT https://management.azure.com/subscriptions/0534ece1-3f64-43de-a058-07d1da4960b0/resourceGroups/te
                 stota/providers/Microsoft.ContainerService/managedClusters/omg?api-version=2017-08-31}
InvocationInfo : {New-AzAks}
Line           : New-AzAks -ResourceGroupName testota -Name omg -Location westeurope
Position       : At line:1 char:1
                 + New-AzAks -ResourceGroupName testota -Name omg -Location westeurope
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperations.<BeginCreateO
                 rUpdateWithHttpMessagesAsync>d__12.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperations.<CreateOrUpda
                 teWithHttpMessagesAsync>d__10.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperationsExtensions.<Cr
                 eateOrUpdateAsync>d__11.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Aks.Generated.Version2017_08_31.ManagedClustersOperationsExtensions.Cre
                 ateOrUpdate(IManagedClustersOperations operations, String resourceGroupName, String resourceName,
                 ManagedCluster parameters)
                    at Microsoft.Azure.Commands.Aks.NewAzureRmAks.<ExecuteCmdlet>b__4_0()
                    at Microsoft.Azure.Commands.Aks.KubeCmdletBase.RunCmdLet(Action action)
HistoryId      : 6
```

Only available versions with autocomplete 1.7.7 and 1.8.1, but it accepts 1.12.6, for example, and works.

**Comment by markcowl** [comment]
@mboersma Sounds like w eneed to update our suggested values for orchastrator version, cna you take a look?

**Comment by mantakaras** [comment]
How to get a debug and error output?
P.S. I have the same issue

**Comment by 4c74356b41** [comment]
why do you need that? this issue says it all, you just need to pass in the proper version of k8s and it will work. surprisingly, you will get a debug output if you add `-Debug`.

**Comment by lukeb1961** [comment]
#8526

**Comment by lukeb1961** [comment]
still broken, four months later..

**Comment by cormacpayne** [comment]
@4c74356b41 we will update the default Kubernetes version used in our AKS cmdlets in the upcoming sprint. A temporary workaround can be found in [this comment](https://github.com/Azure/azure-powershell/issues/9573#issuecomment-509823626). I'm going to close this issue in favor of the one linked previously and we will track the status of the fix to the default version there.
