### ISSUE TITLE
Error using TargetListener or TargetListenerID with AzApplicationGatewayRedirectConfiguration cmdlets

### ISSUE THREAD

**Issue by Cavorter** [Azure/azure-powershell#8756]
## Description

When attempting to create a new RedirectConfiguration resource in an Azure Application Gateway it is not possible to specify a TargetListener or TargetListenerID without getting the following error:
```
New-AzApplicationGatewayRedirectConfiguration : Object reference not set to an instance of an object.
At line:1 char:1
+ New-AzApplicationGatewayRedirectConfiguration -Name TestRedirect -Tar ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzApplicati...ctConfiguration], NullReferenceException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureApplicationGatewayRedirectConfigurationCommand
```

This error occurs with `Add-AzApplicationGatewayRedirectConfiguration`, 'New-AzApplicationGatewayRedirectConfiguration', and 'Set-AzApplicationGatewayRedirectConfiguration`.

The error does NOT occur when using the `-TargetUrl` parameter and the cmdlets operate just fine in those instances. I have been able to reproduce the error on Windows PowerShell 5.1.17134.590 and PowerShell Core 6.1.3 both using Az.Network version 1.2.1

## Steps to reproduce

```powershell
$ResourceGroup = New-AzResourceGroup -Name "agTest-rg" -Location westus2
$commonParams = @{
    ResourceGroupName = $ResourceGroup.ResourceGroupName
    Location = $ResourceGroup.Location
}

$PublicIp = New-AzPublicIpAddress -Name "agTest-pip" -AllocationMethod "Dynamic" @commonParams
$FrontEndIpConfig = New-AzApplicationGatewayFrontendIPConfig -Name "agTest-feip" -PublicIPAddress $PublicIp

$FrontEndPort = New-AzApplicationGatewayFrontendPort -Name "agTest-port" -Port 80
$Listener = New-AzApplicationGatewayHttpListener -Name "agTest-listener" -Protocol "Http" -FrontendIpConfiguration $FrontEndIpConfig -FrontendPort $FrontEndPort

# turn on max output
$VerbosePreference = "Continue"
$DebugPreference = "Continue"

$redirect = New-AzApplicationGatewayRedirectConfiguration -Name "agTest-redirect" -RedirectType Permanent -TargetListenerID $Listener.Id
```

## Environment data

```
PS C:\Users\user> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
PS C:\Users\user> Get-Module -Name Az.* -ListAvailable


    Directory: C:\Users\user\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.3.1      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.0.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAna...
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-A...
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsights...
Script     1.1.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Imp...
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}
Script     1.0.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-Az...
Script     1.4.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}
Script     1.0.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalo...
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewall...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolic...
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduce...
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}
Script     1.0.2      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultC...
Script     1.2.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfigurati...
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzM...
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailabi...
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     1.2.1      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzA...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotifica...
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-Az...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccess...
Script     1.0.1      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, N...
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCa...
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}
Script     1.1.3      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCe...
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     1.3.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlData...
Script     1.0.2      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction,...
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficMan...
Script     1.1.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
```

## Debug output

```
DEBUG: 1:38:45 PM - NewAzureApplicationGatewayRedirectConfigurationCommand begin processing with ParameterSet 'SetByResourceId'.
DEBUG: 1:38:45 PM - using account id 'nathan.stohlmann@VerifyBrand.com'...
New-AzApplicationGatewayRedirectConfiguration : Object reference not set to an instance of an object.
At C:\scratch\RedirectError.ps1:17 char:13
+ $redirect = New-AzApplicationGatewayRedirectConfiguration -Name "agTe ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzApplicati...ctConfiguration], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureApplicationGatewayRedirectConfigurationCommand
 
DEBUG: AzureQoSEvent: CommandName - New-AzApplicationGatewayRedirectConfiguration; IsSuccess - False; Duration - 00:00:00.0517726; Exception - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Commands.Network.AzureApplicationGatewayRedirectConfigurationBase.NewObject()
   at Microsoft.Azure.Commands.Network.NewAzureApplicationGatewayRedirectConfigurationCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 1:38:46 PM - NewAzureApplicationGatewayRedirectConfigurationCommand end processing.
DEBUG: 1:38:46 PM - NewAzureApplicationGatewayRedirectConfigurationCommand end processing.
```

## Error output

```
Message        : Object reference not set to an instance of an object.
StackTrace     :    at Microsoft.Azure.Commands.Network.AzureApplicationGatewayRedirectConfigurationBase.NewObject()
                    at Microsoft.Azure.Commands.Network.NewAzureApplicationGatewayRedirectConfigurationCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.NullReferenceException
InvocationInfo : {New-AzApplicationGatewayRedirectConfiguration}
Line           : $redirect = New-AzApplicationGatewayRedirectConfiguration -Name "agTest-redirect" -RedirectType Permanent -TargetListenerID $Listener.Id
Position       : At C:\scratch\RedirectError.ps1:17 char:13
                 + $redirect = New-AzApplicationGatewayRedirectConfiguration -Name "agTe ...
                 +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 11
```

**Comment by vladimir-shcherbakov** [comment]
@akshaysngupta Could you take a look?

**Comment by preardon** [comment]
I have troubleshooted and tested Locally.

Please see the following PR
https://github.com/Azure/azure-powershell/pull/9138

**Comment by preardon** [comment]
This PR has now been Merged and now shuld be fixed
