### ISSUE TITLE
Export-AzAutomationDscConfiguration trying to export as JSON

### ISSUE THREAD

**Issue by robert-hanekom** [Azure/azure-powershell#8820]
## Description
When running the Export DscConfiguration, I get an error that it cannot deserialize the response.  From debug it looks like it's assuming the configuration file is in JSON format rather than PowerShell. 

## Steps to reproduce

Export-AzAutomationDscConfiguration -Name $configurationName -ResourceGroupName $resourceGroupName -AutomationAccountName $automationAccountName -OutputFolder "D:\" -Debug

## Environment data

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
PSVersion                      5.1.14393.2608                                                                                                                         
PSEdition                      Desktop                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                
BuildVersion                   10.0.14393.2608                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                        
WSManStackVersion              3.0                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                    
SerializationVersion           1.1.0.1    

## Module versions

Script     1.1.2      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord...

## Debug output

DEBUG: AzureQoSEvent: CommandName - Export-AzAutomationDscConfiguration; IsSuccess - False; Duration - 00:00:08.3913944; Exception - Microsoft.Rest.SerializationExcept
ion: Unable to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: C. Path '', line 1, position 1
.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Automation.DscConfigurationOperations.<GetContentWithHttpMessagesAsync>d__9.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.Automation.DscConfigurationOperations.<GetContentWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Automation.DscConfigurationOperationsExtensions.<GetContentAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Automation.DscConfigurationOperationsExtensions.GetContent(IDscConfigurationOperations operations, String resourceGroupName, String au
tomationAccountName, String configurationName)
   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetConfigurationContent(String resourceGroupName, String automationAccountName, String configuratio
nName, Nullable`1 isDraft, String outputFolder, Boolean overwriteExistingFile)
   at Microsoft.Azure.Commands.Automation.Cmdlet.ExportAzureAutomationDscConfiguration.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 12:11:39 AM - ExportAzureAutomationDscConfiguration end processing.
DEBUG: 12:11:39 AM - ExportAzureAutomationDscConfiguration end processing.

## Error output

HistoryId: 3

Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.Automation.DscConfigurationOperations.<GetContentWithHttpMessagesAsync>d__9.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.DscConfigurationOperationsExtensions.<GetContentAsync>d__9.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.DscConfigurationOperationsExtensions.GetContent(IDscConfigurationOperations operations, String 
                 resourceGroupName, String automationAccountName, String configurationName)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetConfigurationContent(String resourceGroupName, String automationAccountName, 
                 String configurationName, Nullable`1 isDraft, String outputFolder, Boolean overwriteExistingFile)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.ExportAzureAutomationDscConfiguration.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Export-AzAutomationDscConfiguration}
Line           : Export-AzAutomationDscConfiguration -Name $configurationName -ResourceGroupName $resourceGroupName -AutomationAccountName $automationAccountName -OutputFolder 
                 "D:\"
                 
Position       : At line:10 char:1
                 + Export-AzAutomationDscConfiguration -Name $configurationName -ResourceGroupName $r ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

Message        : Unexpected character encountered while parsing value: C. Path '', line 1, position 1.
StackTrace     :    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
                    at Newtonsoft.Json.JsonTextReader.ReadAsString()
                    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.Automation.DscConfigurationOperations.<GetContentWithHttpMessagesAsync>d__9.MoveNext()
Exception      : Newtonsoft.Json.JsonReaderException
InvocationInfo : {Export-AzAutomationDscConfiguration}
Line           : Export-AzAutomationDscConfiguration -Name $configurationName -ResourceGroupName $resourceGroupName -AutomationAccountName $automationAccountName -OutputFolder 
                 "D:\"
                 
Position       : At line:10 char:1
                 + Export-AzAutomationDscConfiguration -Name $configurationName -ResourceGroupName $r ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 3

**Comment by vladimir-shcherbakov** [comment]
@vrdmr  Could you take a look?

**Comment by lwajswaj** [comment]
Just tried to repro but I cannot reproduce it on AZ.Automation 1.2.1 module:

```powershell
S C:\Users\Leandro> Export-AzAutomationDscConfiguration -Name LinuxConfig -OutputFolder C:\Temp -ResourceGroupName TestAutomation -AutomationAccountName TestAutomation

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
darhsl        31/12/1600    21:00                LinuxConfig.ps1

PS C:\Users\Leandro> Get-Module

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.5.1      Az.Accounts                         {Add-AzEnvironment, …
Script     1.2.1      Az.Automation                       {Export-AzAutomation…
Manifest   6.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-…
Manifest   6.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Typ…
Script     2.0.0      PSReadLine                          {Get-PSReadLineKeyHa…
```

**Comment by robert-hanekom** [comment]
Hi
Confirmed it's resolved in the latest version.

**Comment by mgreenegit** [comment]
If anyone is still running in to this issue (I experienced it in PWSH 7) an example function using Invoke-RESTMethod is published here.
[AADSCConfigContent module in PowerShell Gallery](https://www.powershellgallery.com/packages/AADSCConfigContent/1.0.0)
