### ISSUE TITLE
 Add-AzureRmAccount  is throwing  PSInvalidOperationException

### ISSUE THREAD

**Issue by Atchub** [Azure/azure-powershell#8924]
## Description
Hi I am from  Azure Automation and we have a customer who is executing the below script and received 
 PSInvalidOperationException.

We suggested the customer to do a module upgrade but customer is really interested in the root cause before doing a module upgrade.

## Steps to reproduce

```powershell
#Create a Variable asset with the name SubscriptionId and put in the subscription id where the VM Exists.

#We are using RunAsConnection/serviceprincipal to authenticate and below is the code:

#----------------------------------------------------------------------------------

$connectionName = "AzureRunAsConnection"
$SubId = Get-AutomationVariable -Name 'SubscriptionId'
try
{
   # Get the connection "AzureRunAsConnection "
   $servicePrincipalConnection=Get-AutomationConnection -Name $connectionName        
      "Logging in to Azure..."
   Add-AzureRmAccount `
     -ServicePrincipal `
     -TenantId $servicePrincipalConnection.TenantId `
     -ApplicationId $servicePrincipalConnection.ApplicationId `
     -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint

   "Setting context to a specific subscription"       

   Set-AzureRmContext -SubscriptionId $SubId                                    
}
catch {
    if (!$servicePrincipalConnection)
    {
       $ErrorMessage = "Connection $connectionName not found."
       throw $ErrorMessage
     } else{
        Write-Error -Message $_.Exception
        throw $_.Exception
     }
}
#----------------------------------------------------------------------------------
```

## Module versions

```powershell
{"Name":"AzureRM.Profile","Version":"1.0.3"}
[AzureRM.Compute][powershellModuleVersion=1.2.1]
```

## Debug output

```
the issue does not reproduce consistently 

```

## Error output

```
 runbookDefinitionKind="PowerShell" runbookName="Start_VM_OpenText" runbookVersionId="8b946050-1293-4859-a606-59dfdd773750" 
exception="System.Management.Automation.RuntimeException: Run Login-AzureRmAccount to login. ---> System.Management.Automation.PSInvalidOperationException: Run Login-AzureRmAccount to login.
   at Microsoft.Azure.Commands.ResourceManager.Common.AzureRMCmdlet.get_DefaultContext()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.DlrScriptCommandProcessor.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeHelper()
   at System.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc()" resourceGroupName="******" runbookTriggerScope="****"


---------------------------------------

"Exception":"System.Net.Http.HttpRequestException: <hidden>\r\n [System.Net.WebException: <hidden>]\r\n  [System.Net.Sockets.SocketException: <hidden>]\r\n   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)\r\n  
 at Microsoft.Azure.Subscriptions.SubscriptionOperationsExtensions.List(ISubscriptionOperations operations)\r\n   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.TryGetTenantSubscription
(IAccessToken accessToken, AzureAccount account, AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, AzureSubscription& subscription, AzureTenant& tenant)\r\n   at 
Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(AzureAccount account, AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password)\r\n   at 
Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.ExecuteCmdlet()\r\n   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()\r\n\r\n   inner exception -> System.Net.WebException: <hidden>\r\n   at 
System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at 
System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n\r\n   inner exception -> System.Net.Sockets.SocketException: <hidden>\r\n   at 
System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at 
.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at 
System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure,
 Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& 
exception)\r\n","FullyQualifiedErrorId":"Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand","InvocationInfo":


{"CommandOrigin":"Internal","InvocationName":"Add-AzureRmAccount","MyCommand":{"Module":
{"Name":"AzureRM.Profile","Version":"1.0.3"},

"ModuleName":"AzureRM.Profile",
"Name":"Add-AzureRmAccount"},"OffsetInLine":4,"ScriptLineNumber":12},"ScriptStackTrace":"at <ScriptBlock>,

{"CategoryInfo":{"Category":"CloseError"},"Exception":"System.Net.Http.HttpRequestException: <hidden>\r\n [System.Net.WebException: <hidden>]\r\n  [System.Net.Sockets.SocketException: <hidden>]\r\n 
  at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)\r\n  
 at Microsoft.Azure.Subscriptions.SubscriptionOperationsExtensions.List(ISubscriptionOperations operations)\r\n   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.TryGetTenantSubscription(IAccessToken accessToken, AzureAccount account, AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, AzureSubscription& subscription, AzureTenant& tenant)\r\n   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.Login(AzureAccount account, AzureEnvironment environment, String tenantId, String subscriptionId, String subscriptionName, SecureString password)\r\n   at Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand.ExecuteCmdlet()\r\n   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()\r\n\r\n   inner exception -> System.Net.WebException: <hidden>\r\n   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)\r\n\r\n   inner exception -> System.Net.Sockets.SocketException: <hidden>\r\n   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)\r\n","FullyQualifiedErrorId":"Microsoft.Azure.Commands.Profile.AddAzureRMAccountCommand","InvocationInfo":{"CommandOrigin":"Internal","InvocationName":"Add-AzureRmAccount","MyCommand":{"Module":file>: line 12"}"	


```

**Comment by cormacpayne** [comment]
@Atchub the root cause of this issue is the default version of Azure PowerShell installed on Azure Automation is an unsupported version. Our advise in this case is to update to the latest version of `AzureRM`, or switch to the new `Az` module, which is now supported in Azure Automation.
