### ISSUE TITLE
Get-AzOperationalInsightsSearchResults : Operation returned an invalid status code 'Gone'

### ISSUE THREAD

**Issue by KrishnaG-MSFT** [Azure/azure-powershell#8993]
## Description

Get-AzOperationalInsightsSearchResults cmdlet execution fails with the error "Operation returned an invalid status code 'Gone'"

## Steps to reproduce

```powershell
PS C:\windows\system32> Get-AzOperationalInsightsSearchResults -ResourceGroupName gttestkrishnacorps -WorkspaceName gttest1loganaworkspace -Query "Type=Event" -Top 10
Get-AzOperationalInsightsSearchResults : Operation returned an invalid status code 'Gone'
At line:1 char:1
+ Get-AzOperationalInsightsSearchResults -ResourceGroupName gttestkrish ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzOperationalInsightsSearchResults], CloudException
    + FullyQualifiedErrorId : Microsoft.Rest.Azure.CloudException,Microsoft.Azure.Commands.OperationalInsights.GetAzureOperationalInsightsSearchResultsCommand
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.5.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.3.1      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}
Script     1.1.0      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}
Script     1.0.2      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServicesServer...}
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-AzApiManagementSystemCertificate...}
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPlan...}
Script     1.2.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...}
Script     1.1.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDscNodeConfiguration...}
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}
Script     1.1.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.0.1      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveServicesAccountType...}
Script     1.7.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.4.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}
Script     1.0.1      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}
Script     1.1.0      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredential, Set-AzDataLakeAnalyticsCatalogCredential...}
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-AzDataLakeStoreTrustedIdProvider...}
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinition...}
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}
Script     1.1.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}
Script     1.0.2      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificateOperation...}
Script     1.2.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl...}
Script     1.2.0      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-AzIntegrationAccountCallbackUrl...}
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmentPlan...}
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability...}
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}
Script     1.6.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzApplication...
Script     1.2.1      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplicationGatewayAuthenticationCertificate, Remove-AzApplication...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNSCredentials...}
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationalInsightsLinuxCustomLogCollection, Disable-AzOperation...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys, Get-AzPowerBIWorkspace...}
Script     1.2.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}
Script     1.0.1      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecoveryServicesVault...}
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSchedule...}
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}
Script     1.3.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.1.3      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate, Add-AzServiceFabricNode...}
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}
Script     1.8.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgradeHint...}
Script     1.3.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseUpgradeHint...}
Script     1.2.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.0.2      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-AzStreamAnalyticsFunction...}
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustomHeaderToProfile, Remove-AzTrafficManagerCustomHeaderFr...
Script     1.1.2      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
Script     1.1.1      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}
```

## Debug output

```
DEBUG: 2:56:18 PM - GetAzureOperationalInsightsSearchResultsCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 2:56:18 PM - using account id 'gtbmkrishna1@outlook.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'gtbmkrishna1@outlook.com', environment: 'AzureCloud', tenant: 'ebb3922d-4260-402c-a9f7-6763686fbe48'
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: c080c264-4507-4efc-baee-7a63e518df48 - AcquireTokenHandlerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/ebb3922d-4260-402c-a9f7-6763686fbe48/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM:  - TokenCache.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 4/12/2019 9:26:18 AM: c080c264-4507-4efc-baee-7a63e518df48 - TokenCache.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: c080c264-4507-4efc-baee-7a63e518df48 - TokenCache.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: c080c264-4507-4efc-baee-7a63e518df48 - TokenCache.cs: 57.0920934933333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: c080c264-4507-4efc-baee-7a63e518df48 - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: c080c264-4507-4efc-baee-7a63e518df48 - AcquireTokenHandlerBase.cs: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: 3e+1pzQw0rkB52zOd53Ou5l/3yOHmoYQo/w4jV9d838=
 Expiration Time: 4/12/2019 10:23:24 AM +00:00
 User Hash: pNX1Drfq3wwkbNbZXdvqr7VBN9R1fGPg0s3Xojl6oiY=

DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: dc960e64-c223-49c5-ac83-4081638bd16f - AcquireTokenHandlerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/ebb3922d-4260-402c-a9f7-6763686fbe48/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM:  - TokenCache.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 4/12/2019 9:26:18 AM: dc960e64-c223-49c5-ac83-4081638bd16f - TokenCache.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: dc960e64-c223-49c5-ac83-4081638bd16f - TokenCache.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: dc960e64-c223-49c5-ac83-4081638bd16f - TokenCache.cs: 57.092009705 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: dc960e64-c223-49c5-ac83-4081638bd16f - TokenCache.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 4/12/2019 9:26:18 AM: dc960e64-c223-49c5-ac83-4081638bd16f - AcquireTokenHandlerBase.cs: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: 3e+1pzQw0rkB52zOd53Ou5l/3yOHmoYQo/w4jV9d838=
 Expiration Time: 4/12/2019 10:23:24 AM +00:00
 User Hash: pNX1Drfq3wwkbNbZXdvqr7VBN9R1fGPg0s3Xojl6oiY=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/a11dc7c8-3220-448a-b894-7481bc50bb9f/resourcegroups/gttestkrishnacorps/providers/Microsoft.OperationalInsights/workspaces/gttest1loganaworkspace/search?api-version=2015-03-20

Headers:
x-ms-client-request-id        : aea2f2fc-09ad-42d1-92fd-f2d67fbce811
accept-language               : en-US

Body:
{
  "top": 10,
  "highlight": {},
  "query": "Type=Event",
  "end": "2019-04-12T09:26:18.8354173Z"
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Gone

Headers:
Pragma                        : no-cache
X-RateLimit-Remaining         : 99
X-RateLimit-Limit             : 100
Request-Context               : appId=cid-v1:3d24a429-e724-4d71-9886-21ad884cf893
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
x-ms-ratelimit-remaining-subscription-resource-requests: 149998
x-ms-request-id               : 0dbac9fa-98a9-4643-bc29-c88e32d9a451
x-ms-correlation-request-id   : 0dbac9fa-98a9-4643-bc29-c88e32d9a451
x-ms-routing-request-id       : SOUTHINDIA:20190412T092619Z:0dbac9fa-98a9-4643-bc29-c88e32d9a451
Cache-Control                 : no-cache
Date                          : Fri, 12 Apr 2019 09:26:19 GMT
Server                        : Microsoft-IIS/10.0
X-Powered-By                  : ASP.NET

Body:
Log Search API is deprecated and has been replaced with the new Azure Log Analytics REST API.
For more information: https://go.microsoft.com/fwlink/?linkid=872656

Get-AzOperationalInsightsSearchResults : Operation returned an invalid status code 'Gone'
At line:1 char:1
+ Get-AzOperationalInsightsSearchResults -ResourceGroupName gttestkrish ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzOperationalInsightsSearchResults], CloudException
    + FullyQualifiedErrorId : Microsoft.Rest.Azure.CloudException,Microsoft.Azure.Commands.OperationalInsights.GetAzureOperationalInsightsSearchResultsCommand

```

## Error output

```
DEBUG: 2:57:07 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 2:57:07 PM - using account id 'gtbmkrishna1@outlook.com'...


   HistoryId: 17


RequestId      : 9bdc9e77-1251-4c5d-95ef-02da7ebe54a6
Message        : Operation returned an invalid status code 'Gone'
ServerMessage  :
ServerResponse : {Gone}
RequestMessage : {POST
                 https://management.azure.com/subscriptions/a11dc7c8-3220-448a-b894-7481bc50bb9f/resourcegroups/gttestkrishnacorps/providers/Microsoft.OperationalInsights/workspaces/gttest1loganaworkspace/search?api-version=2015-03-20}
InvocationInfo : {Get-AzOperationalInsightsSearchResults}
Line           : Get-AzOperationalInsightsSearchResults -ResourceGroupName gttestkrishnacorps -WorkspaceName gttest1loganaworkspace -Query "Type=Event" -Top 10
Position       : At line:1 char:1
                 + Get-AzOperationalInsightsSearchResults -ResourceGroupName gttestkrish ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Management.OperationalInsights.WorkspacesOperations.<BeginGetSearchResultsWithHttpMessagesAsync>d__21.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.OperationalInsights.WorkspacesOperations.<GetSearchResultsWithHttpMessagesAsync>d__18.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.OperationalInsights.WorkspacesOperationsExtensions.<GetSearchResultsAsync>d__27.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Management.OperationalInsights.WorkspacesOperationsExtensions.GetSearchResults(IWorkspacesOperations operations, String resourceGroupName, String workspaceName, SearchParameters parameters)
                    at Microsoft.Azure.Commands.OperationalInsights.Client.OperationalInsightsClient.GetSearchResults(String resourceGroupName, String workspaceName, PSSearchGetSearchResultsParameters psParameters)
                    at Microsoft.Azure.Commands.OperationalInsights.GetAzureOperationalInsightsSearchResultsCommand.ProcessRecord()
                    at System.Management.Automation.CommandProcessor.ProcessRecord()
HistoryId      : 17

```

**Comment by maddieclayton** [comment]
@xizhamsft Can you take a look at this issue?

**Comment by gcarrarom** [comment]
Same issue happening today on a newly created Log Analytics instance. Any news on this issue?

**Comment by KrishnaG-MSFT** [comment]
You may use cmdlet [Invoke-LogAnalyticsQuery](https://dev.loganalytics.io/documentation/Tools/PowerShell-Cmdlets) now which replaced [Get-AzureRmOperationalInsightsSearchResults](https://docs.microsoft.com/en-us/powershell/module/azurerm.operationalinsights/get-azurermoperationalinsightssearchresults?view=azurermps-6.13.0) cmdlet. For more information, you may refer [this](https://azure.microsoft.com/en-in/updates/deprecating-the-log-search-api-for-azure-log-analytics/) update. Alternatively, you may try [this](https://docs.microsoft.com/en-us/cli/azure/ext/log-analytics/monitor/log-analytics?view=azure-cli-latest#ext-log-analytics-az-monitor-log-analytics-query) Az CLI command or [this](https://dev.loganalytics.io/documentation/Using-the-API) REST API as well.

**Comment by VAsHachiRoku** [comment]
Invoke-LogAnalyticsQuery cant seem to find this one and the link above takes to a different cmdlet all together - (Invoke-AzureRmOperationalInsightsQuery). This is also wrong because AzureRm is now just Az so the cmdlet is this - Invoke-AzOperationalInsightsQuery <- This is working!

However there is a problem this cmdlet doesn't work for Saved Search results, the previous cmdlet was - Get-AzOperationalInsightsSavedSearchResult which is returning the "Gone" error as well, when in fact it should return the results of the saved query.

The second issue is there is no cmdlet for Invoke saved search results which I would assume it would look like this - Invoke-AzOperationalInsightsSavedQuery OR Invoke-AzOperationalInsightsSavedSearch would be proper names.

**Comment by yossi-y** [comment]
This API was deprecated on 2017 as Log Analytics upgraded its data store and query engine. This cmdlet will be removed shortly so it won't confuse users.

The way to execute queries is via [invoke-azoperationalinsightsquery ](https://docs.microsoft.com/en-us/powershell/module/az.operationalinsights/invoke-azoperationalinsightsquery?view=azps-4.2.0&viewFallbackFrom=azps-4.1.0)
