### ISSUE TITLE
Please fix -VaultId option support to Restore-AzRecoveryServicesBackupItem

### ISSUE THREAD

**Issue by skmkzyk** [Azure/azure-powershell#9007]
## Description

As far as I tested, most of cmdlets in Az.RecoveryServices supports -ValutId option.
But Restore-AzRecoveryServicesBackupItem doesn't support it.
More accurately, Restore-AzRecoveryServicesBackupItem does receive -ValutId option but seems not recognized.

Since Set-AzRecoveryServicesVaultContext cmdlet is declared as deprecation, please add -VaultId option support to Restore-AzRecoveryServicesBackupItem.

## Steps to reproduce

```powershell
$DebugPreference='Continue' 

$rg = "resize-disk-test"

$sa = Get-AzStorageAccount -ResourceGroupName $rg

$v = Get-AzRecoveryServicesVault

$c = Get-AzRecoveryServicesBackupContainer -ContainerType AzureVM -VaultId $v.id

$i = Get-AzRecoveryServicesBackupItem -Container $c -WorkloadType AzureVM -VaultId $v.id

$rp = (Get-AzRecoveryServicesBackupRecoveryPoint -Item $i -VaultId $v.id)[0]

$job = Restore-AzRecoveryServicesBackupItem -VaultId $v.id -RecoveryPoint $rp -StorageAccountName $sa.StorageAccountName -StorageAccountResourceGroupName $rg
```

## Environment data

```
PS C:\WINDOWS\system32>  $PSVersionTable

Name                           Value                                                                                                                                                 
----                           -----                                                                                                                                                 
PSVersion                      5.1.18875.1000                                                                                                                                        
PSEdition                      Desktop                                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                               
BuildVersion                   10.0.18875.1000                                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                                       
WSManStackVersion              3.0                                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                                   
SerializationVersion           1.1.0.1    
```

## Module versions

```powershell
PS C:\WINDOWS\system32> Get-Module -Name Az.* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                           
---------- -------    ----                                ----------------                                                                                                           
Script     1.5.0      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}                
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove-AzAks, Import-AzAksCredential...}                                                            
Script     1.1.0      Az.AnalysisServices                 {Resume-AzAnalysisServicesServer, Suspend-AzAnalysisServicesServer, Get-AzAnalysisServicesServer, Remove-AzAnalysisServi...
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, Get-AzApiManagementSsoToken, New-AzApiManagementCustomHostnameConfiguration, New-AzApiManage...
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, New-AzApplicationInsights, Remove-AzApplicationInsights, Set-AzApplicationInsightsPricingPla...
Script     1.2.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAuto...
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-AzBatchAccount, Get-AzBatchAccountKeys, New-AzBatchAccount...}                                 
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-AzBillingPeriod, Get-AzEnrollmentAccount, Get-AzConsumptionBudget...}                           
Script     1.1.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnProfileSsoUrl, New-AzCdnProfile, Remove-AzCdnProfile...}                                       
Script     1.0.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccount, Get-AzCognitiveServicesAccountKey, Get-AzCognitiveServicesAccountSkus, Get-AzCognitiveS...
Script     1.7.0      Az.Compute                          {Remove-AzAvailabilitySet, Get-AzAvailabilitySet, New-AzAvailabilitySet, Update-AzAvailabilitySet...}                      
Script     1.0.1      Az.ContainerInstance                {New-AzContainerGroup, Get-AzContainerGroup, Remove-AzContainerGroup, Get-AzContainerInstanceLog}                          
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get-AzContainerRegistry, Update-AzContainerRegistry, Remove-AzContainerRegistry...}              
Script     1.1.0      Az.DataFactory                      {Set-AzDataFactoryV2, Update-AzDataFactoryV2, Get-AzDataFactoryV2, Remove-AzDataFactoryV2...}                              
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataSource, New-AzDataLakeAnalyticsCatalogCredential, Remove-AzDataLakeAnalyticsCatalogCredentia...
Script     1.1.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreTrustedIdProvider, Remove-AzDataLakeStoreFirewallRule, Set-...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolicy, Get-AzDtlAutoShutdownPolicy, Get-AzDtlAutoStartPolicy, Get-AzDtlVMsPerLabPolicy...}        
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDnsRecordConfig, Remove-AzDnsRecordSet, Set-AzDnsRecordSet...}                                  
Script     1.1.0      Az.EventGrid                        {New-AzEventGridTopic, Get-AzEventGridTopic, Set-AzEventGridTopic, New-AzEventGridTopicKey...}                             
Script     1.0.1      Az.EventHub                         {New-AzEventHubNamespace, Get-AzEventHubNamespace, Set-AzEventHubNamespace, Remove-AzEventHubNamespace...}                 
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHDInsightSqoopJobDefinition, Wait-AzHDInsightJob, New-AzHDInsightStreamingMapReduceJobDefinit...
Script     1.0.2      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHubEventHubConsumerGroup, Get-AzIotHubConnectionString, Get-AzIotHubJob...}                     
Script     1.1.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, Update-AzKeyVaultCertificate, Stop-AzKeyVaultCertificateOperation, Get-AzKeyVaultCertificate...
Script     1.2.1      Az.LogicApp                         {Get-AzIntegrationAccountAgreement, Get-AzIntegrationAccountAssembly, Get-AzIntegrationAccountBatchConfiguration, Get-Az...
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociation, Get-AzMlCommitmentAssociation, Get-AzMlCommitmentPlanUsageHistory, Remove-AzMlCommitmen...
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-AzMarketplaceTerms}                                                                           
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKeys, Set-AzMediaServiceKey, Get-AzMediaServiceKeys, Get-AzMediaServiceNameAvailability...}     
Script     1.0.1      Az.Monitor                          {Get-AzMetricDefinition, Get-AzMetric, Remove-AzLogProfile, Get-AzLogProfile...}                                           
Script     1.6.0      Az.Network                          {Add-AzApplicationGatewayAuthenticationCertificate, Get-AzApplicationGatewayAuthenticationCertificate, New-AzApplication...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-AzNotificationHubAuthorizationRules, Get-AzNotificationHubListKeys, Get-AzNotificationHubPNS...
Script     1.1.0      Az.OperationalInsights              {New-AzOperationalInsightsAzureActivityLogDataSource, New-AzOperationalInsightsCustomLogDataSource, Disable-AzOperationa...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPolicyState, Get-AzPolicyStateSummary, Get-AzPolicyRemediation...}                               
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollection, Get-AzPowerBIWorkspaceCollectionAccessKeys, Get-...
Script     1.2.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackupProperty, Get-AzRecoveryServicesVault, Get-AzRecoveryServicesVaultSettingsFile, New-AzRecov...
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSchedule, New-AzRedisCacheScheduleEntry, Get-AzRedisCachePatchSchedule, New-AzRedisCachePatchSc...
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-AzRelayNamespace, Set-AzRelayNamespace, Remove-AzRelayNamespace...}                             
Script     1.3.0      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}                          
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, Get-AzServiceBusNamespace, Set-AzServiceBusNamespace, Remove-AzServiceBusNamespace...}         
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicationCertificate, Add-AzServiceFabricClientCertificate, Add-AzServiceFabricClusterCertificate,...
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR, Get-AzSignalRKey, New-AzSignalRKey...}                                                      
Script     1.8.0      Az.Sql                              {Get-AzSqlDatabaseTransparentDataEncryption, Get-AzSqlDatabaseTransparentDataEncryptionActivity, Set-AzSqlDatabaseTransp...
Script     1.2.0      Az.Storage                          {Get-AzStorageAccount, Get-AzStorageAccountKey, New-AzStorageAccount, New-AzStorageAccountKey...}                          
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunction, Get-AzStreamAnalyticsDefaultFunctionDefinition, New-AzStreamAnalyticsFunction, Remove-Az...
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHeaderToEndpoint, Remove-AzTrafficManagerCustomHeaderFromEndpoint, Add-AzTrafficManagerCustom...
Script     1.1.2      Az.Websites                         {Get-AzAppServicePlan, Set-AzAppServicePlan, New-AzAppServicePlan, Remove-AzAppServicePlan...}                             



```

## Debug output

```
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-reads: 11982
x-ms-request-id               : 0fc12997-f518-4129-a2f7-23fecb794a25
x-ms-correlation-request-id   : 0fc12997-f518-4129-a2f7-23fecb794a25
x-ms-routing-request-id       : EASTASIA:20190415T064915Z:0fc12997-f518-4129-a2f7-23fecb794a25
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 15 Apr 2019 06:49:15 GMT

Body:
{
  "value": [
    {
      "id": "/subscriptions/81d00f63-15dd-4f39-a096-c9386a5355d4/resourceGroups/resize-disk-test/providers/Microsoft.Storage/storageAccounts/bg72fxyveup3ri4um4b3",
      "name": "bg72fxyveup3ri4um4b3",
      "type": "Microsoft.Storage/storageAccounts",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "kind": "StorageV2",
      "location": "southeastasia",
      "tags": {}
    },
    {
      "id": "/subscriptions/81d00f63-15dd-4f39-a096-c9386a5355d4/resourceGroups/sa-test/providers/Microsoft.Storage/storageAccounts/sas7vphtmnkh9d",
      "name": "sas7vphtmnkh9d",
      "type": "Microsoft.Storage/storageAccounts",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "kind": "StorageV2",
      "location": "southeastasia",
      "tags": {}
    }
  ]
}


DEBUG: Caught exception, type: System.ArgumentException
DEBUG: Received ArgumentException
Restore-AzRecoveryServicesBackupItem : Set vault context first using cmdlet Set-AzRecoveryServicesVaultContext
At line:15 char:8
+ $job = Restore-AzRecoveryServicesBackupItem -VaultId $v.id -RecoveryP ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Restore-AzRecoveryServicesBackupItem], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RestoreAzureRmRecoveryServicesBackupItem
 
DEBUG: AzureQoSEvent: CommandName - Restore-AzRecoveryServicesBackupItem; IsSuccess - False; Duration - 00:00:00.4886110; Exception - System.ArgumentException: Set vault context firs
t using cmdlet Set-AzRecoveryServicesVaultContext
   at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.ServiceClientAdapterNS.ClientProxyBase.GetResourceLocation()
   at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.ProviderModel.IaasVmPsBackupProvider.TriggerRestore()
   at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RestoreAzureRmRecoveryServicesBackupItem.<ExecuteCmdlet>b__55_0()
   at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RecoveryServicesBackupCmdletBase.ExecutionBlock(Action action, Boolean shouldProcess);
DEBUG: Finish sending metric.
DEBUG: 3:49:16 PM - RestoreAzureRmRecoveryServicesBackupItem end processing.
DEBUG: 3:49:16 PM - RestoreAzureRmRecoveryServicesBackupItem end processing.

```

## Error output

```
> Resolve-AzError
DEBUG: 3:51:39 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 3:51:39 PM - using account id 'kasakemi@microsoft.com'...


   HistoryId: 4


Message        : Set vault context first using cmdlet Set-AzRecoveryServicesVaultContext
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.ServiceClientAdapterNS.ClientProxyBase.GetResourceLocation()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.ProviderModel.IaasVmPsBackupProvider.TriggerRestore()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RestoreAzureRmRecoveryServicesBackupItem.<ExecuteCmdlet>b__55_0()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RecoveryServicesBackupCmdletBase.ExecutionBlock(Action action, Boolean shouldProcess)
Exception      : System.ArgumentException
InvocationInfo : {Restore-AzRecoveryServicesBackupItem}
Line           : $job = Restore-AzRecoveryServicesBackupItem -VaultId $v.id -RecoveryPoint $rp -StorageAccountName $sa.StorageAccountName -StorageAccountResourceGroupName $rg
Position       : At line:15 char:8
                 + $job = Restore-AzRecoveryServicesBackupItem -VaultId $v.id -RecoveryP ...
                 +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 4



   HistoryId: 2


Message        : The term 'Resolve-AzureRmError' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path 
                 was included, verify that the path is correct and try again.
StackTrace     :    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions 
                 searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
                    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
                    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
                    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, 
                 CommandRedirection[] redirections, ExecutionContext context)
                    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] 
                 pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Exception      : System.Management.Automation.CommandNotFoundException
InvocationInfo : {}
Line           : Resolve-AzureRmError
Position       : At line:1 char:1
                 + Resolve-AzureRmError
                 + ~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2



   HistoryId: 1


Message        : Set vault context first using cmdlet Set-AzRecoveryServicesVaultContext
StackTrace     :    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.ServiceClientAdapterNS.ClientProxyBase.GetResourceLocation()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.ProviderModel.IaasVmPsBackupProvider.TriggerRestore()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RestoreAzureRmRecoveryServicesBackupItem.<ExecuteCmdlet>b__55_0()
                    at Microsoft.Azure.Commands.RecoveryServices.Backup.Cmdlets.RecoveryServicesBackupCmdletBase.ExecutionBlock(Action action, Boolean shouldProcess)
Exception      : System.ArgumentException
InvocationInfo : {Restore-AzRecoveryServicesBackupItem}
Line           : $job = Restore-AzRecoveryServicesBackupItem -VaultId $v.id -RecoveryPoint $rp -StorageAccountName $sa.StorageAccountName -StorageAccountResourceGroupName $rg
Position       : At line:15 char:8
                 + $job = Restore-AzRecoveryServicesBackupItem -VaultId $v.id -RecoveryP ...
                 +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1

DEBUG: AzureQoSEvent: CommandName - Resolve-AzError; IsSuccess - True; Duration - 00:00:00.0871011; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 3:51:39 PM - ResolveError end processing.
DEBUG: 3:51:39 PM - ResolveError end processing.



```

**Comment by maddieclayton** [comment]
@siddharth7 Can you take a look at this issue?

**Comment by siddharth7** [comment]
@skmkzyk You also have to use `VaultLocation` parameter in restore command
