### ISSUE TITLE
Set-AzResource fails  while updating tags for ResourceType Microsoft.OperationsManagement/solutions

### ISSUE THREAD

**Issue by ikanni** [Azure/azure-powershell#9068]
## Description

Set-AzResource fails  while updating tags for ResourceType Microsoft.OperationsManagement/solutions with error Endpoint not found

## Steps to reproduce

```powershell
$SubscriptionId = "d2b38167-d3ca-4d1f-a020-948eee21b6bc"
#Connect-AzAccount

Set $DebugPreference='Continue' 


$Subscription = Select-AzSubscription -SubscriptionId $SubscriptionId

    $rgroup = Get-AzResourceGroup -Name JPE-Test-ikanni-StartStop-VM-RG
    foreach ($group in $rgroup){
    $lock = Get-AzResourceLock -ResourceGroupName $group.ResourceGroupName
    $lockState = $lock.Properties.level    
        if ( ($null -ne $group.Tags) -and ( $lockState -ne "ReadOnly") ) {
            $resources = Get-AzResource -ResourceGroupName $group.ResourceGroupName
            foreach ($r in $resources)
            {
                $resourcetags = (Get-AzResource -ResourceId $r.ResourceId).Tags
                if ($resourcetags)
                {
                    foreach ($key in $group.Tags.Keys)
                    {
                        if (-not($resourcetags.ContainsKey($key)))
                        {
                            $resourcetags.Add($key, $group.Tags[$key])
                        }
                    }
                    if ($r.ResourceType -contains "Microsoft.OperationsManagement/solutions") {
                      Set-AzResource -Tag $resourcetags -ResourceId $r.ResourceId -Force
                    }
                }
                else
                {
                    Set-AzResource -Tag $group.Tags -ResourceId $r.ResourceId -Force
                }
            }
        }
    }  
```

## Environment data

```

PS C:\Users\ikanni>> $PSVersionTable

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
PSVersion                      5.1.14409.1018                                                                                                                                                
PSEdition                      Desktop                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                       
BuildVersion                   10.0.14409.1018                                                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                           
SerializationVersion           1.1.0.1        
```

## Module versions

```powershell
PS C:\Users\ikanni>> Get-Module -Name Az.* -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                                                                                                                   
---------- -------    ----                                ----------------                                                                                                                   
Script     1.5.1      Az.Accounts                         {Disable-AzDataCollection, Disable-AzContextAutosave, Enable-AzDataCollection, Enable-AzContextAutosave...}                        
Script     1.2.1      Az.Automation                       {Get-AzAutomationHybridWorkerGroup, Remove-AzAutomationHybridWorkerGroup, Get-AzAutomationJobOutputRecord, Import-AzAutomationDs...
Script     1.3.1      Az.Resources                        {Get-AzProviderOperation, Remove-AzRoleAssignment, Get-AzRoleAssignment, New-AzRoleAssignment...}                               

Note: This issue is reproduce in AzureRM modules too.

```

## Debug output

```
PS C:\Users\ikanni>> C:\ikanni\ICM-UpdateTags.ps1
Set-AzResource : <?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Service</title>
    <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; padding-bottom: 2em; } 
A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; } A:active { color: #336699; 
font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; font-family: Tahoma; font-size: 26px; font-weight: 
normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; background-color: #e5e5cc; padding: 5px; font-family: Courier New; 
margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: 
Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 
2px white solid; background-color: #e5e5cc;}</style>
  </head>
  <body>
    <div id="content">
      <p class="heading1">Service</p>
      <p>Endpoint not found.</p>
    </div>
  </body>
</html>
At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
+ ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzResource], ErrorResponseMessageException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.SetAzureResourceCmdlet
 

```

## Error output

```
Resolve-AzureRmError : Method 'get_SerializationSettings' in type 'Microsoft.Azure.Management.Internal.Resources.ResourceManagementClient' from assembly 
'Microsoft.Azure.Commands.ResourceManager.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
At line:1 char:1
+ Resolve-AzureRmError
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Resolve-AzureRmError], TypeLoadException
    + FullyQualifiedErrorId : System.TypeLoadException,Microsoft.Azure.Commands.Profile.Errors.ResolveError
 
```

**Comment by ikanni** [comment]
### Correct Error output
PS C:\Users\ikanni> Resolve-AzError


   HistoryId: 2


Message        : <?xml version="1.0" encoding="utf-8"?>
                 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
                 <html xmlns="http://www.w3.org/1999/xhtml">
                   <head>
                     <title>Service</title>
                     <style>BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; } #content { margin-left: 30px; font-size: .70em; 
                 padding-bottom: 2em; } A:link { color: #336699; font-weight: bold; text-decoration: underline; } A:visited { color: #6699cc; font-weight: bold; text-decoration: underline; 
                 } A:active { color: #336699; font-weight: bold; text-decoration: underline; } .heading1 { background-color: #003366; border-bottom: #336699 6px solid; color: #ffffff; 
                 font-family: Tahoma; font-size: 26px; font-weight: normal;margin: 0em 0em 10px -20px; padding-bottom: 8px; padding-left: 30px;padding-top: 16px;} pre { font-size:small; 
                 background-color: #e5e5cc; padding: 5px; font-family: Courier New; margin-top: 0px; border: 1px #f0f0e0 solid; white-space: pre-wrap; white-space: -pre-wrap; word-wrap: 
                 break-word; } table { border-collapse: collapse; border-spacing: 0px; font-family: Verdana;} table th { border-right: 2px white solid; border-bottom: 2px white solid; 
                 font-weight: bold; background-color: #cecf9c;} table td { border-right: 2px white solid; border-bottom: 2px white solid; background-color: #e5e5cc;}</style>
                   </head>
                   <body>
                     <div id="content">
                       <p class="heading1">Service</p>
                       <p>Endpoint not found.</p>
                     </div>
                   </body>
                 </html>
StackTrace     :    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.HandleException(ExceptionDispatchInfo capturedException)
                    at Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.ResourceManagerCmdletBase.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Entities.ErrorResponses.ErrorResponseMessageException
InvocationInfo : {Set-AzResource}
Line           :                       Set-AzResource -Tag $resourcetags -ResourceId $r.ResourceId -Force
                 
Position       : At C:\ikanni\ICM-UpdateTags.ps1:28 char:23
                 + ...             Set-AzResource -Tag $resourcetags -ResourceId $r.Resource ...
                 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

**Comment by cormacpayne** [comment]
@ikanni This looks like an issue with the properties that are being passed in the body of the request. For your scenario above, the request body looks like the following (from my repro):

```
Body:
{
  "tags": {
    "newTestTagKey": "newTestTagValue"
  }
}
```

When I change the call a little bit to include the resource object itself as a part of the cmdlet call, so all other properties are preserved (using `$r |  Set-AzResource -Tag $resourcetags -Force`), the request body changes to the following:

```
Body:
{
  "properties": {
    "workspaceResourceId": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/testrg/providers/Microsoft.OperationalInsights/workspaces/corm-log-analytics-workspace",
    "provisioningState": "Succeeded",
    "creationTime": "Mon, 01 Jan 0001 00:00:00 GMT",
    "lastModifiedTime": "Mon, 01 Jan 0001 00:00:00 GMT",
    "containedResources": [
      "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/testrg/providers/Microsoft.OperationalInsights/workspaces/corm-log-analytics-workspace/views/NetworkMonitoring(corm-log-analytics-workspace)"
    ]
  },
  "location": "West US 2",
  "plan": {
    "name": "NetworkMonitoring(corm-log-analytics-workspace)",
    "promotionCode": "",
    "product": "OMSGallery/NetworkMonitoring",
    "publisher": "Microsoft"
  },
  "tags": {
    "newTestTagKey": "newTestTagValue"
  }
}
```

For cases where you're using `Set-AzResource` and want to preserve the existing values, I recommend piping the resource object to `Set-AzResource`, or providing it as the value to the `-InputObject` parameter.
