### ISSUE TITLE
Couldn't run test in VS.

### ISSUE THREAD

**Issue by ninweninwe** [Azure/azure-powershell#9200]
## Description
Try to run azure powershell test.  But it hits the following issue with vs 2017/2019.  Any help here?

[5/14/2019 10:33:53 AM Error] System.ArgumentException: '' is not a valid version string.
   at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
   at NuGet.PackageManagement.VisualStudio.VsManagedLanguagesProjectSystemServices.ToPackageLibraryDependency(PackageReference reference)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.VisualStudio.VsManagedLanguagesProjectSystemServices.<GetPackageReferencesAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject.<GetPackageSpecAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject.<GetPackageSpecsAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<GetPackagesPathResolverAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass7_0.<<GetInstalledPackages>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages()
   at Microsoft.VisualStudio.TestWindow.VsAdapters.UnitTestExtensionDiscoverer.GetAllEnabledExtensions(ILogger log)
[5/14/2019 10:33:56 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (64-bit .NET Core 4.6.27414.06)
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:01.65]   Discovering: Microsoft.Azure.PowerShell.Cmdlets.Network.Test
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:01.75]   Discovered:  Microsoft.Azure.PowerShell.Cmdlets.Network.Test
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:01.76]   Starting:    Microsoft.Azure.PowerShell.Cmdlets.Network.Test
[5/14/2019 10:33:58 AM Error] [xUnit.net 00:00:02.01]     Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests.VirtualNetworkGatewayVpnclientConnectionHealthTest [FAIL]
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:02.02]       System.ArgumentException : Unable to find recorded mock file 'E:\az-github\azure-powershell\src\Network\Network.Test\bin\Debug\netcoreapp2.1\SessionRecords\Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests\VirtualNetworkGatewayVpnclientConnectionHealthTest.json'.

**Comment by MiYanni** [comment]
@ninweninwe After recording the test, copy the json file from your `bin\Debug\netcoreapp2.1\SessionRecords\` to the SessionRecords folder in the Network.Test project. In the future, please use our Teams channel to ask questions.

**Comment by ninweninwe** [comment]
What is team channel?

The problem is that the test could not be run.

5/14/2019 10:33:53 AM Error] System.ArgumentException: '' is not a valid version string.
at NuGet.Versioning.VersionRange.Parse(String value, Boolean allowFloating)
at NuGet.PackageManagement.VisualStudio.VsManagedLanguagesProjectSystemServices.ToPackageLibraryDependency(PackageReference reference)
at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext() at System.Collections.Generic.List1..ctor(IEnumerable1 collection) at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
at NuGet.PackageManagement.VisualStudio.VsManagedLanguagesProjectSystemServices.d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject.d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.PackageManagement.VisualStudio.LegacyPackageReferenceProject.d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.VisualStudio.VsPackageInstallerServices.d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NuGet.VisualStudio.VsPackageInstallerServices.<>c__DisplayClass7_0.<b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at Microsoft.VisualStudio.Threading.JoinableTask1.CompleteOnCurrentThread() at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func1 asyncMethod, JoinableTaskCreationOptions creationOptions)
at NuGet.VisualStudio.VsPackageInstallerServices.GetInstalledPackages()
at Microsoft.VisualStudio.TestWindow.VsAdapters.UnitTestExtensionDiscoverer.GetAllEnabledExtensions(ILogger log)
[5/14/2019 10:33:56 AM Informational] [xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.0 (64-bit .NET Core 4.6.27414.06)
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:01.65] Discovering: Microsoft.Azure.PowerShell.Cmdlets.Network.Test
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:01.75] Discovered: Microsoft.Azure.PowerShell.Cmdlets.Network.Test
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:01.76] Starting: Microsoft.Azure.PowerShell.Cmdlets.Network.Test
[5/14/2019 10:33:58 AM Error] [xUnit.net 00:00:02.01] Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests.VirtualNetworkGatewayVpnclientConnectionHealthTest [FAIL]
[5/14/2019 10:33:58 AM Informational] [xUnit.net 00:00:02.02] System.ArgumentException : Unable to find recorded mock file 'E:\az-github\azure-powershell\src\Network\Network.Test\bin\Debug\netcoreapp2.1\SessionRecords\Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayTests\VirtualNetworkGatewayVpnclientConnectionHealthTest.json'.
