### ISSUE TITLE
New-AzRedisCache gives confusing exception/error

### ISSUE THREAD

**Issue by lukeb1961** [Azure/azure-powershell#9510]
## Description

If you choose an incorrect -SIZE parameter value, you see  a rather confusing error/exception.

```
New-AzRedisCache : Exception of type 'AzCacheRP.Exceptions.SkuFamilyNotSupportedException' was thrown.
```

What it SHOULD tell me is that the -SIZE value is invalid for the -SKU value entered..

## Steps to reproduce

I enter -SIZE C6, which is an incorrect option if I had also selected -SKU  PREMIUM

```
   New-AzRedisCache -ResourceGroupName $RG -Name $SydREDISname -Location $Sydney `
                    -Sku Premium -Size C6 -SubnetId $SydREDISsubnet.Id -Debug

New-AzRedisCache : Exception of type 'AzCacheRP.Exceptions.SkuFamilyNotSupportedException' was thrown.
RequestID=293ed4c1-a7c4-4107-87d4-951a4a783c45
At line:2 char:4
+    New-AzRedisCache -ResourceGroupName $RG -Name $SydREDISname -Locat ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRedisCache], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RedisCache.NewAzureRedisCache
```

## Environment data

```
PS> $PSVersionTable
Name                             Value                                                                                                                                                           
----                                 -----                                                                                                                                                           
PSVersion                       5.1.18362.145                                                                                                                                                   
PSEdition                        Desktop                                                                                                                                                         
PSCompatibleVersions   {1.0, 2.0, 3.0, 4.0...}                                                                                                                                         
BuildVersion                   10.0.18362.145                                                                                                                                                  
CLRVersion                     4.0.30319.42000                                                                                                                                                 
WSManStackVersion       3.0                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                             
SerializationVersion         1.1.0.1 
```
## Module versions

```
PS> (get-module -name az).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
2      3      2      -1
```

## Debug output

```
PS C:\Users\lukeb.SOUTHPACIFIC>  if (-NOT (Get-AzRedisCache -ResourceGroupName $RG -Name "RedisCache" -EA SilentlyContinue)) {
   New-AzRedisCache -ResourceGroupName $RG -Name $SydREDISname -Location $Sydney `
                    -Sku Premium -Size C6 -SubnetId $SydREDISsubnet.Id -Debug
 }
DEBUG: 11:59:07 - NewAzureRedisCache begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 11:59:09 - using account id 'LukeBrennan@outlook.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'LukeBrennan@outlook.com', environment: 'AzureCloud', tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '1f89577f-4235-4965-83e5-aad1a7e761fc', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-2
27b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/', CorrelationId: '00000000-0000-0000-0000-
000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '1f89577f-4235-4965-83e5-aad1a7e761fc', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a2
58-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8465536Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8465536Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8465536Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8465536Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8465536Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8465536Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 6 items to token cache.

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: 49.68632396 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: 49.68632396 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expir
ation Time: 27/06/2019 02:48:51 +00:00

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8485624Z: 4e765d90-dd1d-471a-893d-cdce3bd9d2e5 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expir
ation Time: 27/06/2019 02:48:51 +00:00Access Token Hash: DxRX7QrG9+H6h90uTOhBLpowkRKyj4m7bVRhk6KrWRc=
	 User id: f224627b-0a9c-46f8-acbb-1a40f09ba505

DEBUG: [Common.Authentication]: Authenticating using Account: 'LukeBrennan@outlook.com', environment: 'AzureCloud', tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '1f89577f-4235-4965-83e5-aad1a7e761fc', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-2
27b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/', CorrelationId: '00000000-0000-0000-0000-
000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '1f89577f-4235-4965-83e5-aad1a7e761fc', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a2
58-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8495715Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8495715Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8495715Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8495715Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8495715Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8495715Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 6 items to token cache.

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: 49.686290535 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: 49.686290535 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expir
ation Time: 27/06/2019 02:48:51 +00:00

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8505679Z: 238d7e59-6c3f-488b-8cfe-eafa9e5b7ef0 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expir
ation Time: 27/06/2019 02:48:51 +00:00Access Token Hash: DxRX7QrG9+H6h90uTOhBLpowkRKyj4m7bVRhk6KrWRc=
	 User id: f224627b-0a9c-46f8-acbb-1a40f09ba505

DEBUG: [Common.Authentication]: Authenticating using Account: 'LukeBrennan@outlook.com', environment: 'AzureCloud', tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: '1f89577f-4235-4965-83e5-aad1a7e761fc', Endpoint: 'https://login.microsoftonline.com/', ClientId: '1950a258-2
27b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri: 'https://management.core.windows.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/', CorrelationId: '00000000-0000-0000-0000-
000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: '1f89577f-4235-4965-83e5-aad1a7e761fc', AdEndpoint: 'https://login.microsoftonline.com/', ClientId: '1950a2
58-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8515621Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8515621Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0
130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8515621Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: === Token Acquisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8515621Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: === Token Acquisition started:
	Authority: https://login.microsoftonline.com/1f89577f-4235-4965-83e5-aad1a7e761fc/
	Resource: https://management.core.windows.net/
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8515621Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8515621Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: Loading from cache.

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8520205Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 6 items to token cache.

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Verbose: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: Looking up cache for a token...

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: An item matching the requested resource was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: 49.6862571383333 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: 49.6862571383333 minutes left until token in cache expires

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expir
ation Time: 27/06/2019 02:48:51 +00:00

DEBUG: [ADAL]: Information: 2019-06-27T01:59:09.8525717Z: bc02c1f0-7406-423a-b22c-1dbde53bb918 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expir
ation Time: 27/06/2019 02:48:51 +00:00Access Token Hash: DxRX7QrG9+H6h90uTOhBLpowkRKyj4m7bVRhk6KrWRc=
	 User id: f224627b-0a9c-46f8-acbb-1a40f09ba505

DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '06/27/2019 02:48:51 +00:00', MultipleResource? 'True', Tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc', UserId: 'Luk
eBrennan@outlook.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'LukeBrennan@outlook.com', Name: Luke Brennan, IdProvider: 'live.com', Uid: 'f224627b-0a9c-46f8-acbb-1a40f09ba505'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '06/27/2019 02:48:51 +00:00' Comparing to '06/27/2019 01:59:09 +00:00' With threshold '00:05:00', calculated time until
 token expiry: '00:49:41.1754283'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/LukeBrennan-AZ-things/providers/Microsoft.Cache/Redis/lukebrennanazsydredis?api-version=2017-10-0
1

Headers:
x-ms-client-request-id        : b78f07e5-8d32-4e6d-9e1a-202d457d3e1e
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NotFound

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 4240dcdf-0fa3-40df-86ec-0f6216ecfd94
x-ms-correlation-request-id   : 4240dcdf-0fa3-40df-86ec-0f6216ecfd94
x-ms-routing-request-id       : AUSTRALIAEAST:20190627T015910Z:4240dcdf-0fa3-40df-86ec-0f6216ecfd94
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 27 Jun 2019 01:59:10 GMT

Body:
{
  "error": {
    "code": "ResourceNotFound",
    "message": "The Resource 'Microsoft.Cache/Redis/lukebrennanazsydredis' under resource group 'LukeBrennan-AZ-things' was not found."
  }
}


DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '06/27/2019 02:48:51 +00:00', MultipleResource? 'True', Tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc', UserId: 'Luk
eBrennan@outlook.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'LukeBrennan@outlook.com', Name: Luke Brennan, IdProvider: 'live.com', Uid: 'f224627b-0a9c-46f8-acbb-1a40f09ba505'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '06/27/2019 02:48:51 +00:00' Comparing to '06/27/2019 01:59:11 +00:00' With threshold '00:05:00', calculated time until
 token expiry: '00:49:39.9068103'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/providers/Microsoft.Cache/register?api-version=2016-09-01

Headers:
x-ms-client-request-id        : 325925cd-7377-4663-a6dd-6c2d8a5361ec
accept-language               : en-US

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Pragma                        : no-cache
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-request-id               : c1fe1a2c-8038-45c8-a4c6-bdb317299a35
x-ms-correlation-request-id   : c1fe1a2c-8038-45c8-a4c6-bdb317299a35
x-ms-routing-request-id       : AUSTRALIAEAST:20190627T015919Z:c1fe1a2c-8038-45c8-a4c6-bdb317299a35
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Thu, 27 Jun 2019 01:59:18 GMT

Body:
{
  "id": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/providers/Microsoft.Cache",
  "namespace": "Microsoft.Cache",
  "authorization": {
    "applicationId": "96231a05-34ce-4eb4-aa6a-70759cbb5e83",
    "roleDefinitionId": "4f731528-ba85-45c7-acfb-cd0a9b3cf31b"
  },
  "resourceTypes": [
    {
      "resourceType": "Redis",
      "locations": [
        "North Central US",
        "South Central US",
        "Central US",
        "West Europe",
        "North Europe",
        "West US",
        "East US",
        "East US 2",
        "Japan East",
        "Japan West",
        "Brazil South",
        "Southeast Asia",
        "East Asia",
        "Australia East",
        "Australia Southeast",
        "Central India",
        "West India",
        "Canada Central",
        "Canada East",
        "UK South",
        "UK West",
        "West US 2",
        "West Central US",
        "South India",
        "Korea Central",
        "Korea South",
        "France Central",
        "South Africa North",
        "UAE North"
      ],
      "apiVersions": [
        "2018-03-01",
        "2017-10-01",
        "2017-02-01",
        "2016-04-01",
        "2015-08-01",
        "2015-03-01",
        "2014-04-01-preview",
        "2014-04-01"
      ],
      "zoneMappings": [
        {
          "location": "East US 2",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "Central US",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "West Europe",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "France Central",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "Southeast Asia",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "West US 2",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "North Europe",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "East US",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "UK South",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "Japan East",
          "zones": [
            "1",
            "2",
            "3"
          ]
        },
        {
          "location": "Australia East",
          "zones": []
        }
      ],
      "capabilities": "CrossResourceGroupResourceMove, CrossSubscriptionResourceMove"
    },
    {
      "resourceType": "locations",
      "locations": [],
      "apiVersions": [
        "2018-03-01",
        "2017-10-01",
        "2017-02-01",
        "2016-04-01",
        "2015-08-01",
        "2015-03-01",
        "2014-04-01-preview",
        "2014-04-01"
      ]
    },
    {
      "resourceType": "locations/operationResults",
      "locations": [
        "North Central US",
        "South Central US",
        "Central US",
        "West Europe",
        "North Europe",
        "West US",
        "East US",
        "East US 2",
        "Japan East",
        "Japan West",
        "Brazil South",
        "Southeast Asia",
        "East Asia",
        "Australia East",
        "Australia Southeast",
        "Central India",
        "West India",
        "South India",
        "Canada Central",
        "Canada East",
        "UK South",
        "UK West",
        "West US 2",
        "West Central US",
        "Korea Central",
        "Korea South",
        "France Central",
        "South Africa North",
        "UAE North"
      ],
      "apiVersions": [
        "2018-03-01",
        "2017-10-01",
        "2017-02-01",
        "2016-04-01",
        "2015-08-01",
        "2015-03-01",
        "2014-04-01-preview",
        "2014-04-01"
      ]
    },
    {
      "resourceType": "checkNameAvailability",
      "locations": [],
      "apiVersions": [
        "2018-03-01",
        "2017-10-01",
        "2017-02-01",
        "2016-04-01",
        "2015-08-01",
        "2015-03-01",
        "2014-04-01-preview",
        "2014-04-01-alpha",
        "2014-04-01"
      ]
    },
    {
      "resourceType": "operations",
      "locations": [],
      "apiVersions": [
        "2018-03-01",
        "2017-10-01",
        "2017-02-01",
        "2016-04-01",
        "2015-08-01",
        "2015-03-01",
        "2014-04-01-preview",
        "2014-04-01-alpha",
        "2014-04-01"
      ]
    },
    {
      "resourceType": "RedisConfigDefinition",
      "locations": [],
      "apiVersions": [
        "2018-03-01",
        "2017-10-01",
        "2017-02-01",
        "2016-04-01",
        "2015-08-01",
        "2015-03-01"
      ]
    }
  ],
  "registrationState": "Registered"
}


DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '06/27/2019 02:48:51 +00:00', MultipleResource? 'True', Tenant: '1f89577f-4235-4965-83e5-aad1a7e761fc', UserId: 'Luk
eBrennan@outlook.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'LukeBrennan@outlook.com', Name: Luke Brennan, IdProvider: 'live.com', Uid: 'f224627b-0a9c-46f8-acbb-1a40f09ba505'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '06/27/2019 02:48:51 +00:00' Comparing to '06/27/2019 01:59:18 +00:00' With threshold '00:05:00', calculated time until
 token expiry: '00:49:32.5951568'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/LukeBrennan-AZ-things/providers/Microsoft.Cache/Redis/lukebrennanazsydredis?api-version=2017-10-0
1

Headers:
x-ms-client-request-id        : b0eef5d6-cbd6-48e9-a5f2-a78aa8943fc5
accept-language               : en-US

Body:
{
  "properties": {
    "sku": {
      "name": "Premium",
      "family": "C",
      "capacity": 6
    },
    "subnetId": "/subscriptions/b8e3a02e-456c-4060-a4fd-4fc9641f301d/resourceGroups/LukeBrennan-AZ-things/providers/Microsoft.Network/virtualNetworks/UNIX-vnet-Sydney/subnets/REDIS-subnet"
  },
  "location": "australiaeast"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : 293ed4c1-a7c4-4107-87d4-951a4a783c45
x-rp-server-mvid              : aa7e9358-75b2-4ed8-bad5-c846f42b664d
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 736950a8-3117-4239-a040-f8f4bbc34da2
x-ms-routing-request-id       : AUSTRALIAEAST:20190627T015920Z:736950a8-3117-4239-a040-f8f4bbc34da2
Cache-Control                 : no-cache
Date                          : Thu, 27 Jun 2019 01:59:20 GMT
Server                        : Microsoft-HTTPAPI/2.0

Body:
{
  "error": {
    "code": "BadRequest",
    "message": "Exception of type 'AzCacheRP.Exceptions.SkuFamilyNotSupportedException' was thrown.\r\nRequestID=293ed4c1-a7c4-4107-87d4-951a4a783c45",
    "target": null
  }
}


New-AzRedisCache : Exception of type 'AzCacheRP.Exceptions.SkuFamilyNotSupportedException' was thrown.
RequestID=293ed4c1-a7c4-4107-87d4-951a4a783c45
At line:2 char:4
+    New-AzRedisCache -ResourceGroupName $RG -Name $SydREDISname -Locat ...
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [New-AzRedisCache], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.RedisCache.NewAzureRedisCache
 
DEBUG: AzureQoSEvent: CommandName - New-AzRedisCache; IsSuccess - False; Duration - 00:00:20.2753893; Exception - Microsoft.Rest.Azure.CloudException: Exception of type 'AzCacheRP.Exceptions.S
kuFamilyNotSupportedException' was thrown.
RequestID=293ed4c1-a7c4-4107-87d4-951a4a783c45
   at Microsoft.Azure.Management.Redis.RedisOperations.<BeginCreateWithHttpMessagesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Redis.RedisOperationsExtensions.<BeginCreateAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Redis.RedisOperationsExtensions.BeginCreate(IRedisOperations operations, String resourceGroupName, String name, RedisCreateParameters parameters)
   at Microsoft.Azure.Commands.RedisCache.RedisCacheClient.CreateCache(String resourceGroupName, String cacheName, String location, String skuFamily, Int32 skuCapacity, String skuName, Hashtab
le redisConfiguration, Nullable`1 enableNonSslPort, Hashtable tenantSettings, Nullable`1 shardCount, String subnetId, String staticIP, Hashtable tags, IList`1 zones)
   at Microsoft.Azure.Commands.RedisCache.NewAzureRedisCache.<>c__DisplayClass52_0.<ExecuteCmdlet>b__0()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
   at Microsoft.Azure.Commands.RedisCache.NewAzureRedisCache.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 11:59:29 - NewAzureRedisCache end processing.
DEBUG: 11:59:29 - NewAzureRedisCache end processing.
```

**Comment by cormacpayne** [comment]
@SiddharthChatrolaMs Hey Siddharth, would you mind taking a look at this issue?

**Comment by lukeb1961** [comment]
could a ParameterSet solve this by not allowing the invalid sizes to even be accepted?
