### ISSUE TITLE
Export-AzAutomationDscNodeReportContent : Unable to deserialize the response.

### ISSUE THREAD

**Issue by sudhakar01** [Azure/azure-powershell#9663]
## Description
I am facing the issue of **Unable to deserialize the response.** while using the **Export-AzAutomationDscNodeReportContent** cmdlet. I even tried to update the AZ module to it's latest version, still facing the same issue.

## Steps to reproduce

```powershell

```

$Node = Get-AzAutomationDscNode -ResourceGroupName "RG01" -AutomationAccountName "AC01" -Name "NA01"
$Report = Get-AzAutomationDscNodeReport -ResourceGroupName "RG01" -AutomationAccountName "AC01" -NodeId "xxxxxxxx-c7d8-11e8-a941-xxxxxxxxx" -Latest
$Report | Export-AzAutomationDscNodeReportContent -OutputFolder "C:\Users\sss\test.txt"

## Module versions

Get-Module Az.Automation -ListAvailable

    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                
---------- -------    ----                                ----------------                
Script     1.3.0      Az.Automation                       {Get-AzAutomationHybridWorker...
Script     1.2.2      Az.Automation                       {Get-AzAutomationHybridWorker...
Script     1.0.0      Az.Automation                       {Get-AzAutomationHybridWorker...

## Error output

Resolve-AzError

   HistoryId: 2

Message        : Unable to deserialize the response.
StackTrace     :    at Microsoft.Azure.Management.Automation.NodeReportsOperations.<GetCon
                 tentWithHttpMessagesAsync>d__7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown 
                 ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebu
                 ggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.NodeReportsOperationsExtensio
                 ns.<GetContentAsync>d__5.MoveNext()
                 --- End of stack trace from previous location where exception was thrown 
                 ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebu
                 ggerNotification(Task task)
                    at Microsoft.Azure.Management.Automation.NodeReportsOperationsExtensio
                 ns.GetContent(INodeReportsOperations operations, String 
                 resourceGroupName, String automationAccountName, String nodeId, String 
                 reportId)
                    at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetDs
                 cNodeReportContent(String resourceGroupName, String 
                 automationAccountName, Guid nodeId, Guid reportId, String outputFolder, 
                 Boolean overwriteExistingFile)
                    at Microsoft.Azure.Commands.Automation.Cmdlet.ExportAzureAutomationDsc
                 NodeReportContent.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.Proc
                 essRecord()
Exception      : Microsoft.Rest.SerializationException
InvocationInfo : {Export-AzAutomationDscNodeReportContent}
Line           : $Report | Export-AzAutomationDscNodeReportContent -OutputFolder 
                 "C:\Users\nh411mf\Desktop"
Position       : At line:3 char:11
                 + $Report | Export-AzAutomationDscNodeReportContent -OutputFolder "C:\U 
                 ...
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

Message        : Additional text encountered after finished reading JSON content: {. Path 
                 '', line 3, position 0.
StackTrace     :    at Newtonsoft.Json.JsonTextReader.Read()
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserial
                 ize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader 
                 reader, Type objectType)
                    at 
                 Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String 
                 json, JsonSerializerSettings settings)
                    at Microsoft.Azure.Management.Automation.NodeReportsOperations.<GetCon
                 tentWithHttpMessagesAsync>d__7.MoveNext()
Exception      : Newtonsoft.Json.JsonReaderException
InvocationInfo : {Export-AzAutomationDscNodeReportContent}
Line           : $Report | Export-AzAutomationDscNodeReportContent -OutputFolder 
                 "C:\Users\nh411mf\Desktop"
Position       : At line:3 char:11
                 + $Report | Export-AzAutomationDscNodeReportContent -OutputFolder "C:\U 
                 ...
                 +           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 2

**Comment by markcowl** [comment]
@sudhakar01 Can you pleqase provide the following information:

(1) The entire moduel layout on your machine `Get-Module -ListAvailable`

(2) The debug trace for the cmdlet failure - this will provide client/server communications that will help the service team pinpoint the issue. execute`$DebugPreference="Continue"` before executing the failing cmdlet

**Comment by sudhakar01** [comment]
```
Get-Module -ListAvailable

    Directory: C:\Users\nh411mf\Documents\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                
---------- -------    ----                                ----------------                
Script     2.3.0      psPAS                               {New-PASSession, Close-PASSes...


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands                
---------- -------    ----                                ----------------                
Script     1.6.0      Az.Accounts                         {Disable-AzDataCollection, Di...
Script     1.5.2      Az.Accounts                         {Disable-AzDataCollection, Di...
Script     1.0.0      Az.Accounts                         {Disable-AzDataCollection, Di...
Script     1.0.0      Az.Advisor                          {Get-AzAdvisorRecommendation,...
Script     1.0.1      Az.Aks                              {Get-AzAks, New-AzAks, Remove...
Script     1.0.0      Az.Aks                              {Get-AzAks, New-AzAks, Remove...
Script     1.1.0      Az.AnalysisServices                 {Resume-AzAnalysisServicesSer...
Script     1.0.0      Az.AnalysisServices                 {Resume-AzAnalysisServicesSer...
Script     1.2.0      Az.ApiManagement                    {Add-AzApiManagementApiToProd...
Script     1.1.0      Az.ApiManagement                    {Add-AzApiManagementApiToProd...
Script     1.0.0      Az.ApiManagement                    {Add-AzApiManagementRegion, G...
Script     1.0.0      Az.ApplicationInsights              {Get-AzApplicationInsights, N...
Script     1.3.0      Az.Automation                       {Get-AzAutomationHybridWorker...
Script     1.2.2      Az.Automation                       {Get-AzAutomationHybridWorker...
Script     1.0.0      Az.Automation                       {Get-AzAutomationHybridWorker...
Script     1.1.0      Az.Batch                            {Remove-AzBatchAccount, Get-A...
Script     1.0.0      Az.Batch                            {Remove-AzBatchAccount, Get-A...
Script     1.0.0      Az.Billing                          {Get-AzBillingInvoice, Get-Az...
Script     1.3.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnP...
Script     1.2.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnP...
Script     1.0.0      Az.Cdn                              {Get-AzCdnProfile, Get-AzCdnP...
Script     1.1.1      Az.CognitiveServices                {Get-AzCognitiveServicesAccou...
Script     1.0.0      Az.CognitiveServices                {Get-AzCognitiveServicesAccou...
Script     2.4.0      Az.Compute                          {Remove-AzAvailabilitySet, Ge...
Script     2.1.0      Az.Compute                          {Remove-AzAvailabilitySet, Ge...
Script     1.0.0      Az.Compute                          {Remove-AzAvailabilitySet, Ge...
Script     1.0.1      Az.ContainerInstance                {New-AzContainerGroup, Get-Az...
Script     1.0.0      Az.ContainerInstance                {New-AzContainerGroup, Get-Az...
Script     1.0.1      Az.ContainerRegistry                {New-AzContainerRegistry, Get...
Script     1.0.0      Az.ContainerRegistry                {New-AzContainerRegistry, Get...
Script     1.1.2      Az.DataFactory                      {Set-AzDataFactoryV2, Update-...
Script     1.1.1      Az.DataFactory                      {Set-AzDataFactoryV2, Update-...
Script     1.0.0      Az.DataFactory                      {Set-AzDataFactoryV2, Update-...
Script     1.0.0      Az.DataLakeAnalytics                {Get-AzDataLakeAnalyticsDataS...
Script     1.2.1      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedId...
Script     1.0.0      Az.DataLakeStore                    {Get-AzDataLakeStoreTrustedId...
Script     1.0.0      Az.DeploymentManager                {Get-AzDeploymentManagerArtif...
Script     1.0.0      Az.DevTestLabs                      {Get-AzDtlAllowedVMSizesPolic...
Script     1.1.1      Az.Dns                              {Get-AzDnsRecordSet, New-AzDn...
Script     1.1.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDn...
Script     1.0.0      Az.Dns                              {Get-AzDnsRecordSet, New-AzDn...
Script     1.2.1      Az.EventGrid                        {New-AzEventGridTopic, Get-Az...
Script     1.1.1      Az.EventGrid                        {New-AzEventGridTopic, Get-Az...
Script     1.0.0      Az.EventGrid                        {New-AzEventGridTopic, Get-Az...
Script     1.2.0      Az.EventHub                         {New-AzEventHubNamespace, Get...
Script     1.1.0      Az.EventHub                         {New-AzEventHubNamespace, Get...
Script     1.0.0      Az.EventHub                         {New-AzEventHubNamespace, Get...
Script     1.1.0      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFront...
Script     1.0.0      Az.FrontDoor                        {New-AzFrontDoor, Get-AzFront...
Script     2.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHD...
Script     1.0.0      Az.HDInsight                        {Get-AzHDInsightJob, New-AzHD...
Script     1.2.0      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHu...
Script     1.1.0      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHu...
Script     1.0.0      Az.IotHub                           {Add-AzIotHubKey, Get-AzIotHu...
Script     1.2.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, U...
Script     1.0.0      Az.KeyVault                         {Add-AzKeyVaultCertificate, U...
Script     1.2.1      Az.LogicApp                         {Get-AzIntegrationAccountAgre...
Script     1.0.0      Az.LogicApp                         {Get-AzIntegrationAccountAgre...
Script     1.1.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociati...
Script     1.0.0      Az.MachineLearning                  {Move-AzMlCommitmentAssociati...
Script     1.0.0      Az.MarketplaceOrdering              {Get-AzMarketplaceTerms, Set-...
Script     1.1.0      Az.Media                            {Sync-AzMediaServiceStorageKe...
Script     1.0.0      Az.Media                            {Sync-AzMediaServiceStorageKe...
Script     1.2.1      Az.Monitor                          {Get-AzMetricDefinition, Get-...
Script     1.0.0      Az.Monitor                          {Get-AzMetricDefinition, Get-...
Script     1.11.0     Az.Network                          {Add-AzApplicationGatewayAuth...
Script     1.8.1      Az.Network                          {Add-AzApplicationGatewayAuth...
Script     1.0.0      Az.Network                          {Add-AzApplicationGatewayAuth...
Script     1.1.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-A...
Script     1.0.0      Az.NotificationHubs                 {Get-AzNotificationHub, Get-A...
Script     1.3.1      Az.OperationalInsights              {New-AzOperationalInsightsAzu...
Script     1.2.0      Az.OperationalInsights              {New-AzOperationalInsightsAzu...
Script     1.0.0      Az.OperationalInsights              {New-AzOperationalInsightsAzu...
Script     1.1.2      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPol...
Script     1.1.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPol...
Script     1.0.0      Az.PolicyInsights                   {Get-AzPolicyEvent, Get-AzPol...
Script     1.1.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCol...
Script     1.0.0      Az.PowerBIEmbedded                  {Remove-AzPowerBIWorkspaceCol...
Script     1.4.2      Az.RecoveryServices                 {Get-AzRecoveryServicesBackup...
Script     1.4.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackup...
Script     1.0.0      Az.RecoveryServices                 {Get-AzRecoveryServicesBackup...
Script     1.1.0      Az.RedisCache                       {Remove-AzRedisCachePatchSche...
Script     1.0.0      Az.RedisCache                       {Remove-AzRedisCachePatchSche...
Script     1.0.1      Az.Relay                            {New-AzRelayNamespace, Get-Az...
Script     1.0.0      Az.Relay                            {New-AzRelayNamespace, Get-Az...
Script     1.6.0      Az.Resources                        {Get-AzProviderOperation, Rem...
Script     1.4.0      Az.Resources                        {Get-AzProviderOperation, Rem...
Script     1.0.0      Az.Resources                        {Get-AzProviderOperation, Rem...
Script     1.2.1      Az.ServiceBus                       {New-AzServiceBusNamespace, G...
Script     1.1.0      Az.ServiceBus                       {New-AzServiceBusNamespace, G...
Script     1.0.0      Az.ServiceBus                       {New-AzServiceBusNamespace, G...
Script     1.1.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicati...
Script     1.0.1      Az.ServiceFabric                    {Add-AzServiceFabricApplicati...
Script     1.0.0      Az.ServiceFabric                    {Add-AzServiceFabricApplicati...
Script     1.0.2      Az.SignalR                          {New-AzSignalR, Get-AzSignalR...
Script     1.0.0      Az.SignalR                          {New-AzSignalR, Get-AzSignalR...
Script     1.13.0     Az.Sql                              {Get-AzSqlDatabaseTransparent...
Script     1.10.0     Az.Sql                              {Get-AzSqlDatabaseTransparent...
Script     1.0.0      Az.Sql                              {Get-AzSqlDatabaseTransparent...
Script     1.5.0      Az.Storage                          {Get-AzStorageAccount, Get-Az...
Script     1.3.0      Az.Storage                          {Get-AzStorageAccount, Get-Az...
Script     1.0.0      Az.Storage                          {Get-AzStorageAccount, Get-Az...
Script     1.1.1      Az.StorageSync                      {Invoke-AzStorageSyncCompatib...
Script     1.0.0      Az.StreamAnalytics                  {Get-AzStreamAnalyticsFunctio...
Script     1.0.1      Az.TrafficManager                   {Add-AzTrafficManagerCustomHe...
Script     1.0.0      Az.TrafficManager                   {Add-AzTrafficManagerCustomHe...
Script     1.3.0      Az.Websites                         {Get-AzAppServicePlan, Set-Az...
Script     1.2.1      Az.Websites                         {Get-AzAppServicePlan, Set-Az...
Script     1.0.0      Az.Websites                         {Get-AzAppServicePlan, Set-Az...
Script     0.5.4      Azure.AnalysisServices              {Add-AzureAnalysisServicesAcc...
Script     4.6.1      Azure.Storage                       {Get-AzureStorageTable, New-A...
Binary     2.0.2.4    AzureAD                             {Add-AzureADApplicationOwner,...
Script     6.13.1     AzureRM                                                             
Script     6.10.0     AzureRM                                                             
Script     0.6.14     AzureRM.AnalysisServices            {Resume-AzureRmAnalysisServic...
Script     6.1.7      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegi...
Script     6.1.5      AzureRM.ApiManagement               {Add-AzureRmApiManagementRegi...
Script     0.1.8      AzureRM.ApplicationInsights         {Get-AzureRmApplicationInsigh...
Script     6.1.1      AzureRM.Automation                  {Get-AzureRMAutomationHybridW...
Script     5.1.1      AzureRM.Automation                  {Get-AzureRMAutomationHybridW...
Script     4.0.11     AzureRM.Backup                      {Backup-AzureRmBackupItem, En...
Script     4.0.10     AzureRM.Backup                      {Backup-AzureRmBackupItem, En...
Script     4.1.5      AzureRM.Batch                       {Remove-AzureRmBatchAccount, ...
Script     0.14.6     AzureRM.Billing                     {Get-AzureRmBillingInvoice, G...
Script     5.0.6      AzureRM.Cdn                         {Get-AzureRmCdnProfile, Get-A...
Script     0.9.12     AzureRM.CognitiveServices           {Get-AzureRmCognitiveServices...
Script     0.9.11     AzureRM.CognitiveServices           {Get-AzureRmCognitiveServices...
Script     5.9.1      AzureRM.Compute                     {Remove-AzureRmAvailabilitySe...
Script     5.7.0      AzureRM.Compute                     {Remove-AzureRmAvailabilitySe...
Script     0.3.7      AzureRM.Consumption                 {Get-AzureRmConsumptionBudget...
Script     0.2.12     AzureRM.ContainerInstance           {New-AzureRmContainerGroup, G...
Script     0.2.10     AzureRM.ContainerInstance           {New-AzureRmContainerGroup, G...
Script     1.0.10     AzureRM.ContainerRegistry           {New-AzureRmContainerRegistry...
Script     5.0.3      AzureRM.DataFactories               {Remove-AzureRmDataFactory, G...
Script     0.5.11     AzureRM.DataFactoryV2               {Set-AzureRmDataFactoryV2, Up...
Script     5.1.4      AzureRM.DataLakeAnalytics           {Get-AzureRmDataLakeAnalytics...
Script     6.2.1      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrus...
Script     6.1.2      AzureRM.DataLakeStore               {Get-AzureRmDataLakeStoreTrus...
Script     4.0.9      AzureRM.DevTestLabs                 {Get-AzureRmDtlAllowedVMSizes...
Script     5.1.0      AzureRM.Dns                         {Get-AzureRmDnsRecordSet, New...
Script     0.3.7      AzureRM.EventGrid                   {New-AzureRmEventGridTopic, G...
Script     0.7.0      AzureRM.EventHub                    {New-AzureRmEventHubNamespace...
Script     0.6.10     AzureRM.EventHub                    {New-AzureRmEventHubNamespace...
Script     4.1.8      AzureRM.HDInsight                   {Get-AzureRmHDInsightJob, New...
Script     5.1.5      AzureRM.Insights                    {Get-AzureRmMetricDefinition,...
Script     5.1.4      AzureRM.Insights                    {Get-AzureRmMetricDefinition,...
Script     3.1.8      AzureRM.IotHub                      {Add-AzureRmIotHubKey, Get-Az...
Script     5.2.1      AzureRM.KeyVault                    {Add-AzureKeyVaultCertificate...
Script     4.1.4      AzureRM.LogicApp                    {Get-AzureRmIntegrationAccoun...
Script     0.18.5     AzureRM.MachineLearning             {Move-AzureRmMlCommitmentAsso...
Script     0.4.8      AzureRM.MachineLearningCompute      {Get-AzureRmMlOpCluster, Get-...
Script     0.2.7      AzureRM.MarketplaceOrdering         {Get-AzureRmMarketplaceTerms,...
Script     0.2.5      AzureRM.MarketplaceOrdering         {Get-AzureRmMarketplaceTerms,...
Script     0.10.4     AzureRM.Media                       {Sync-AzureRmMediaServiceStor...
Script     6.11.1     AzureRM.Network                     {Add-AzureRmApplicationGatewa...
Script     6.9.0      AzureRM.Network                     {Add-AzureRmApplicationGatewa...
Script     5.0.3      AzureRM.NotificationHubs            {Get-AzureRmNotificationHub, ...
Script     5.0.6      AzureRM.OperationalInsights         {New-AzureRmOperationalInsigh...
Script     1.1.0      AzureRM.PolicyInsights              {Get-AzureRmPolicyEvent, Get-...
Script     1.0.4      AzureRM.PolicyInsights              {Get-AzureRmPolicyEvent, Get-...
Script     4.1.10     AzureRM.PowerBIEmbedded             {Remove-AzureRmPowerBIWorkspa...
Script     5.8.2      AzureRM.profile                     {Disable-AzureRmDataCollectio...
Script     5.6.0      AzureRM.profile                     {Disable-AzureRmDataCollectio...
Script     4.1.9      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesB...
Script     4.1.8      AzureRM.RecoveryServices            {Get-AzureRmRecoveryServicesB...
Script     4.5.2      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServic...
Script     4.4.1      AzureRM.RecoveryServices.Backup     {Backup-AzureRmRecoveryServic...
Script     0.2.12     AzureRM.RecoveryServices.SiteRec... {Edit-AzureRmRecoveryServices...
Script     0.2.10     AzureRM.RecoveryServices.SiteRec... {Edit-AzureRmRecoveryServices...
Script     5.1.0      AzureRM.RedisCache                  {Remove-AzureRmRedisCachePatc...
Script     0.3.12     AzureRM.Relay                       {New-AzureRmRelayNamespace, G...
Script     0.3.10     AzureRM.Relay                       {New-AzureRmRelayNamespace, G...
Script     6.7.3      AzureRM.Resources                   {Get-AzureRmProviderOperation...
Script     6.6.0      AzureRM.Resources                   {Get-AzureRmProviderOperation...
Script     0.16.10    AzureRM.Scheduler                   {Disable-AzureRmSchedulerJobC...
Script     0.6.13     AzureRM.ServiceBus                  {New-AzureRmServiceBusNamespa...
Script     0.6.12     AzureRM.ServiceBus                  {New-AzureRmServiceBusNamespa...
Script     0.3.15     AzureRM.ServiceFabric               {Add-AzureRmServiceFabricAppl...
Script     0.3.12     AzureRM.ServiceFabric               {Add-AzureRmServiceFabricAppl...
Script     1.0.0      AzureRM.SignalR                     {New-AzureRmSignalR, Get-Azur...
Script     4.12.1     AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransp...
Script     4.11.5     AzureRM.Sql                         {Get-AzureRmSqlDatabaseTransp...
Script     5.2.0      AzureRM.Storage                     {Get-AzureRmStorageAccount, G...
Script     4.0.10     AzureRM.StreamAnalytics             {Get-AzureRmStreamAnalyticsFu...
Script     4.0.5      AzureRM.Tags                        {Remove-AzureRmTag, Get-Azure...
Script     4.1.3      AzureRM.TrafficManager              {Add-AzureRmTrafficManagerCus...
Script     4.1.1      AzureRM.TrafficManager              {Add-AzureRmTrafficManagerCus...
Script     4.0.5      AzureRM.UsageAggregates             Get-UsageAggregates             
Script     5.2.0      AzureRM.Websites                    {Get-AzureRmAppServicePlan, S...
Script     1.0.1      Microsoft.PowerShell.Operation.V... {Get-OperationValidation, Inv...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Get-Package, G...
Script     3.4.0      Pester                              {Describe, Context, It, Shoul...
Script     1.0.0.1    PowerShellGet                       {Install-Module, Find-Module,...
Script     1.2        PSReadline                          {Get-PSReadlineKeyHandler, Se...


    Directory: C:\Windows\system32\WindowsPowerShell\v1.0\Modules


ModuleType Version    Name                                ExportedCommands                
---------- -------    ----                                ----------------                
Manifest   1.0.0.0    AppBackgroundTask                   {Disable-AppBackgroundTaskDia...
Manifest   2.0.0.0    AppLocker                           {Get-AppLockerFileInformation...
Manifest   1.0.0.0    AppvClient                          {Add-AppvClientConnectionGrou...
Manifest   2.0.0.0    Appx                                {Add-AppxPackage, Get-AppxPac...
Script     1.0.0.0    AssignedAccess                      {Clear-AssignedAccess, Get-As...
Manifest   1.0.0.0    BitLocker                           {Unlock-BitLocker, Suspend-Bi...
Manifest   2.0.0.0    BitsTransfer                        {Add-BitsFile, Complete-BitsT...
Manifest   1.0.0.0    BranchCache                         {Add-BCDataCacheExtension, Cl...
Manifest   1.0.0.0    CimCmdlets                          {Get-CimAssociatedInstance, G...
Manifest   1.0        ConfigCI                            {Get-SystemDriver, New-CIPoli...
Manifest   1.0        Defender                            {Get-MpPreference, Set-MpPref...
Manifest   1.0.0.0    DeliveryOptimization                {Get-DeliveryOptimizationStat...
Manifest   1.0.0.0    DirectAccessClientComponents        {Disable-DAManualEntryPointSe...
Script     3.0        Dism                                {Add-AppxProvisionedPackage, ...
Manifest   1.0.0.0    DnsClient                           {Resolve-DnsName, Clear-DnsCl...
Manifest   1.0.0.0    EventTracingManagement              {Start-EtwTraceSession, New-E...
Manifest   2.0.0.0    International                       {Get-WinDefaultInputMethodOve...
Manifest   1.0.0.0    iSCSI                               {Get-IscsiTargetPortal, New-I...
Script     1.0.0.0    ISE                                 {New-IseSnippet, Import-IseSn...
Manifest   1.0.0.0    Kds                                 {Add-KdsRootKey, Get-KdsRootK...
Manifest   1.0.1.0    Microsoft.PowerShell.Archive        {Compress-Archive, Expand-Arc...
Manifest   3.0.0.0    Microsoft.PowerShell.Diagnostics    {Get-WinEvent, Get-Counter, I...
Manifest   3.0.0.0    Microsoft.PowerShell.Host           {Start-Transcript, Stop-Trans...
Manifest   1.0.0.0    Microsoft.PowerShell.LocalAccounts  {Add-LocalGroupMember, Disabl...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Content, Clear-Content, ...
Script     1.0        Microsoft.PowerShell.ODataUtils     Export-ODataEndpointProxy       
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {Get-Acl, Set-Acl, Get-PfxCer...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Format-List, Format-Custom, ...
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Disable-WSManCredSSP, Enable...
Manifest   1.0        MMAgent                             {Disable-MMAgent, Enable-MMAg...
Manifest   1.0.0.0    MsDtc                               {New-DtcDiagnosticTransaction...
Manifest   2.0.0.0    NetAdapter                          {Disable-NetAdapter, Disable-...
Manifest   1.0.0.0    NetConnection                       {Get-NetConnectionProfile, Se...
Manifest   1.0.0.0    NetEventPacketCapture               {New-NetEventSession, Remove-...
Manifest   2.0.0.0    NetLbfo                             {Add-NetLbfoTeamMember, Add-N...
Manifest   1.0.0.0    NetNat                              {Get-NetNat, Get-NetNatExtern...
Manifest   2.0.0.0    NetQos                              {Get-NetQosPolicy, Set-NetQos...
Manifest   2.0.0.0    NetSecurity                         {Get-DAPolicyChange, New-NetI...
Manifest   1.0.0.0    NetSwitchTeam                       {New-NetSwitchTeam, Remove-Ne...
Manifest   1.0.0.0    NetTCPIP                            {Get-NetIPAddress, Get-NetIPI...
Manifest   1.0.0.0    NetworkConnectivityStatus           {Get-DAConnectionStatus, Get-...
Manifest   1.0.0.0    NetworkSwitchManager                {Disable-NetworkSwitchEtherne...
Manifest   1.0.0.0    NetworkTransition                   {Add-NetIPHttpsCertBinding, D...
Manifest   1.0.0.0    PcsvDevice                          {Get-PcsvDevice, Start-PcsvDe...
Manifest   1.0.0.0    PKI                                 {Add-CertificateEnrollmentPol...
Manifest   1.0.0.0    PnpDevice                           {Get-PnpDevice, Get-PnpDevice...
Manifest   1.1        PrintManagement                     {Add-Printer, Add-PrinterDriv...
Binary     1.0.11     ProcessMitigations                  {Get-ProcessMitigation, Set-P...
Script     3.0        Provisioning                        {Install-ProvisioningPackage,...
Manifest   1.1        PSDesiredStateConfiguration         {Set-DscLocalConfigurationMan...
Script     1.0.0.0    PSDiagnostics                       {Disable-PSTrace, Disable-PSW...
Binary     1.1.0.0    PSScheduledJob                      {New-JobTrigger, Add-JobTrigg...
Manifest   2.0.0.0    PSWorkflow                          {New-PSWorkflowExecutionOptio...
Manifest   1.0.0.0    PSWorkflowUtility                   Invoke-AsWorkflow               
Manifest   1.0.0.0    ScheduledTasks                      {Get-ScheduledTask, Set-Sched...
Manifest   2.0.0.0    SecureBoot                          {Confirm-SecureBootUEFI, Set-...
Manifest   2.0.0.0    SmbShare                            {Get-SmbShare, Remove-SmbShar...
Manifest   2.0.0.0    SmbWitness                          {Get-SmbWitnessClient, Move-S...
Manifest   1.0.0.0    StartLayout                         {Export-StartLayout, Import-S...
Manifest   2.0.0.0    Storage                             {Add-InitiatorIdToMaskingSet,...
Manifest   2.0.0.0    TLS                                 {New-TlsSessionTicketKey, Ena...
Manifest   1.0.0.0    TroubleshootingPack                 {Get-TroubleshootingPack, Inv...
Manifest   2.0.0.0    TrustedPlatformModule               {Get-Tpm, Initialize-Tpm, Cle...
Binary     2.1.639.0  UEV                                 {Clear-UevConfiguration, Clea...
Manifest   2.0.0.0    VpnClient                           {Add-VpnConnection, Set-VpnCo...
Manifest   1.0.0.0    Wdac                                {Get-OdbcDriver, Set-OdbcDriv...
Manifest   1.0.0.0    WindowsDeveloperLicense             {Get-WindowsDeveloperLicense,...
Script     1.0        WindowsErrorReporting               {Enable-WindowsErrorReporting...
Manifest   1.0.0.0    WindowsSearch                       {Get-WindowsSearchSetting, Se...
Manifest   1.0.0.0    WindowsUpdate                       Get-WindowsUpdateLog            
Manifest   1.0.0.2    WindowsUpdateProvider               {Get-WUAVersion, Get-WULastIn...

```

Debug Contents :

```
Export-AzAutomationDscNodeReportContent : Unable to deserialize the response.
At line:1 char:11
+ $Report | Export-AzAutomationDscNodeReportContent -OutputFolder "C:\U ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Export-AzAutomationDscNodeReportContent],  
   SerializationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.ExportAzureAutom 
   ationDscNodeReportContent
 
DEBUG: AzureQoSEvent: CommandName - Export-AzAutomationDscNodeReportContent; IsSuccess - Fa
lse; Duration - 00:00:02.1095754; Exception - Microsoft.Rest.SerializationException: Unable
 to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: Additional text enc
ountered after finished reading JSON content: {. Path '', line 3, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader rea
der, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType
)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSe
rializerSettings settings)
   at Microsoft.Azure.Management.Automation.NodeReportsOperations.<GetContentWithHttpMessag
esAsync>d__7.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Management.Automation.NodeReportsOperations.<GetContentWithHttpMessag
esAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(T
ask task)
   at Microsoft.Azure.Management.Automation.NodeReportsOperationsExtensions.<GetContentAsyn
c>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(T
ask task)
   at Microsoft.Azure.Management.Automation.NodeReportsOperationsExtensions.GetContent(INod
eReportsOperations operations, String resourceGroupName, String automationAccountName, Stri
ng nodeId, String reportId)
   at Microsoft.Azure.Commands.Automation.Common.AutomationPSClient.GetDscNodeReportContent
(String resourceGroupName, String automationAccountName, Guid nodeId, Guid reportId, String
 outputFolder, Boolean overwriteExistingFile)
   at Microsoft.Azure.Commands.Automation.Cmdlet.ExportAzureAutomationDscNodeReportContent.
ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 13:59:07 - ExportAzureAutomationDscNodeReportContent end processing.
DEBUG: 13:59:07 - ExportAzureAutomationDscNodeReportContent end processing.
```

**Comment by andyw248** [comment]
OP - your code says:
$Report | Export-AzAutomationDscNodeReportContent -OutputFolder "C:\Users\sss\test.txt"
Did you try to specify a folder name as the -OutputFolder parameter instead of a file name?

**Comment by vikram-m** [comment]
Product team is aware of this issue, and unfortunately because of other priorities were not able to pick this up. Please expect an update in Q4CY20.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by vikram-m** [comment]
Currently, team is busy with other high priority items and this would be picked up in CY2021 Q1.

**Comment by msft-jasonparker** [comment]
Is there an update on this issue?  This is still occurring in the latest version of Az.Automation

**Comment by robharman** [comment]
Any update on this? Not being able to get the reports makes it hard to use Azure Automation to automate response to issues with machines using ASC.

**Comment by SaurabhSharma-MSFT** [comment]
@vikram-m Any latest updates on this issue ?
