### ISSUE TITLE
Always return to error with Get-AzLogicAppUpgradedDefinition cmdlet

### ISSUE THREAD

**Issue by ToMakeSense** [Azure/azure-powershell#9764]
The documentation I am referencing: [Get-AzLogicAppUpgradedDefinition](https://docs.microsoft.com/en-us/powershell/module/az.logicapp/get-azlogicappupgradeddefinition). whatever value(2016-06-01, 2015-08-01-preview, 2016-04-01-preview) is passed to `TargetSchemaVersion`, it returns to error.

```powershell
PS C:\> Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga" -TargetSchemaVersion 2016-06-01
Get-AzLogicAppUpgradedDefinition : The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-04-01-prev
iew/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'.
At line:1 char:1
+ Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzLogicAppUpgradedDefinition], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand
 

PS C:\> Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga" -TargetSchemaVersion 2015-08-01-preview
Get-AzLogicAppUpgradedDefinition : Target template schema '2015-08-01-preview' is not supported for migration: the supported target versions are '2016-04-01-preview, 2016-06-01'
.
At line:1 char:1
+ Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzLogicAppUpgradedDefinition], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand
 

PS C:\> Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga" -TargetSchemaVersion 2016-04-01-preview
Get-AzLogicAppUpgradedDefinition : The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-04-01-prev
iew/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'.
At line:1 char:1
+ Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzLogicAppUpgradedDefinition], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand
```
You could find the initial issue report here: MicrosoftDocs/azure-docs-powershell/issues/1181

**debug traces attached accordingly**
```powershell
PS C:\> Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga" -TargetSchemaVersion 2016-06-01
DEBUG: 13:40:03 - GetAzureLogicAppUpgradedDefinitionCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 13:40:03 - using account id 'userXXX@xxx.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'userXXX@xxx.com', environment: 'AzureCloud', tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg/providers/Microsoft.Logic/workflows/lga/generateUpgradedDefinition?api-version=2016-06-01

Headers:
x-ms-client-request-id        : 55af9815-f1d8-4854-af3f-4bf627bf01d3
accept-language               : en-US

Body:
{
  "targetSchemaVersion": "2016-06-01"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-request-id               : westeurope:ad624ad8-eb86-45cd-8626-49bd35941c32
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 6e6f26c3-f528-414c-922f-ba3a11f45731
x-ms-routing-request-id       : CANADAEAST:20190807T054005Z:6e6f26c3-f528-414c-922f-ba3a11f45731
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 07 Aug 2019 05:40:05 GMT

Body:
{
  "error": {
    "code": "InvalidTemplate",
    "message": "The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'."
  }
}


Get-AzLogicAppUpgradedDefinition : The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'.
At line:1 char:1
+ Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga"  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzLogicAppUpgradedDefinition], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand
 
DEBUG: AzureQoSEvent: CommandName - Get-AzLogicAppUpgradedDefinition; IsSuccess - False; Duration - 00:00:02.1753639; Exception - Microsoft.Rest.Azure.CloudException: The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'.
   at Microsoft.Azure.Management.Logic.WorkflowsOperations.<GenerateUpgradedDefinitionWithHttpMessagesAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.<GenerateUpgradedDefinitionAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.GenerateUpgradedDefinition(IWorkflowsOperations operations, String resourceGroupName, String workflowName, GenerateUpgradedDefinitionParameters parameters)
   at Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 13:40:07 - GetAzureLogicAppUpgradedDefinitionCommand end processing.
DEBUG: 13:40:07 - GetAzureLogicAppUpgradedDefinitionCommand end processing.

PS C:\> Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga" -TargetSchemaVersion 2016-04-01-preview
DEBUG: 13:40:12 - GetAzureLogicAppUpgradedDefinitionCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 13:40:12 - using account id 'userXXX@xxx.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'userXXX@xxx.com', environment: 'AzureCloud', tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg/providers/Microsoft.Logic/workflows/lga/generateUpgradedDefinition?api-version=2016-06-01

Headers:
x-ms-client-request-id        : d8b1c7a6-5210-4b50-9ed2-7e328794fd9a
accept-language               : en-US

Body:
{
  "targetSchemaVersion": "2016-04-01-preview"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Conflict

Headers:
Pragma                        : no-cache
x-ms-request-id               : westeurope:81915857-5b11-4fb7-8563-f0260e062f5e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : b9cc8b44-2fe7-49ce-b01d-bcde45196e30
x-ms-routing-request-id       : CANADAEAST:20190807T054014Z:b9cc8b44-2fe7-49ce-b01d-bcde45196e30
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 07 Aug 2019 05:40:13 GMT

Body:
{
  "error": {
    "code": "InvalidTemplate",
    "message": "The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'."
  }
}


Get-AzLogicAppUpgradedDefinition : The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'.
At line:1 char:1
+ Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga"  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzLogicAppUpgradedDefinition], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand
 
DEBUG: AzureQoSEvent: CommandName - Get-AzLogicAppUpgradedDefinition; IsSuccess - False; Duration - 00:00:01.7256505; Exception - Microsoft.Rest.Azure.CloudException: The template validation failed: 'Source template schema 'https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#' is not supported for migration: the supported source version is '2015-08-01-preview'.'.
   at Microsoft.Azure.Management.Logic.WorkflowsOperations.<GenerateUpgradedDefinitionWithHttpMessagesAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.<GenerateUpgradedDefinitionAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.GenerateUpgradedDefinition(IWorkflowsOperations operations, String resourceGroupName, String workflowName, GenerateUpgradedDefinitionParameters parameters)
   at Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 13:40:17 - GetAzureLogicAppUpgradedDefinitionCommand end processing.
DEBUG: 13:40:17 - GetAzureLogicAppUpgradedDefinitionCommand end processing.

PS C:\> Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga" -TargetSchemaVersion 2015-08-01-preview
DEBUG: 13:40:22 - GetAzureLogicAppUpgradedDefinitionCommand begin processing with ParameterSet '__AllParameterSets'.
DEBUG: 13:40:22 - using account id 'userXXX@xxx.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'userXXX@xxx.com', environment: 'AzureCloud', tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://management.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg/providers/Microsoft.Logic/workflows/lga/generateUpgradedDefinition?api-version=2016-06-01

Headers:
x-ms-client-request-id        : d4fabf63-116a-4340-af70-e2d37365cf54
accept-language               : en-US

Body:
{
  "targetSchemaVersion": "2015-08-01-preview"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-request-id               : westeurope:0e07531e-435b-497c-80b1-fdf7b00a325c
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id   : 5c08452e-fa92-4bcd-bfe0-86d116e30a3f
x-ms-routing-request-id       : FRANCECENTRAL:20190807T054023Z:5c08452e-fa92-4bcd-bfe0-86d116e30a3f
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Wed, 07 Aug 2019 05:40:23 GMT

Body:
{
  "error": {
    "code": "InvalidRequestContent",
    "message": "Target template schema '2015-08-01-preview' is not supported for migration: the supported target versions are '2016-04-01-preview, 2016-06-01'."
  }
}


Get-AzLogicAppUpgradedDefinition : Target template schema '2015-08-01-preview' is not supported for migration: the supported target versions are '2016-04-01-preview, 2016-06-01'.
At line:1 char:1
+ Get-AzLogicAppUpgradedDefinition -ResourceGroupName "rg" -Name "lga"  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzLogicAppUpgradedDefinition], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand
 
DEBUG: AzureQoSEvent: CommandName - Get-AzLogicAppUpgradedDefinition; IsSuccess - False; Duration - 00:00:01.4331869; Exception - Microsoft.Rest.Azure.CloudException: Target template schema '2015-08-01-preview' is not supported for migration: the supported target versions are '2016-04-01-preview, 2016-06-01'.
   at Microsoft.Azure.Management.Logic.WorkflowsOperations.<GenerateUpgradedDefinitionWithHttpMessagesAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.<GenerateUpgradedDefinitionAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.GenerateUpgradedDefinition(IWorkflowsOperations operations, String resourceGroupName, String workflowName, GenerateUpgradedDefinitionParameters parameters)
   at Microsoft.Azure.Commands.LogicApp.Cmdlets.GetAzureLogicAppUpgradedDefinitionCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 13:40:25 - GetAzureLogicAppUpgradedDefinitionCommand end processing.
DEBUG: 13:40:25 - GetAzureLogicAppUpgradedDefinitionCommand end processing.

```

**Comment by markcowl** [comment]
@ToMakeSense Can you provide the debug traces when you run one of these cmdlets, that will help to show the actual generated request and response to pinpoint the issue.

To get the debug traces, use:
`$DebugPreference="Continue"`

then run the cmdlet, and paste the output here.

**Comment by ToMakeSense** [comment]
@markcowl Hi Mark, debug traces attached. And It seemed that I figured it out.
The cmdlet **Get-AzLogicAppUpgradedDefinition** is used to upgrade the old version logic app (it should be deployed on a service plan which needs sku, I have no experience about it) to current implementation which uses consumption mode.

![image](https://user-images.githubusercontent.com/6244148/62599377-a0d54680-b91e-11e9-9ff3-54c301f82065.png)

**Comment by ToMakeSense** [comment]
@markcowl and, it seems impossible to create the old version logic app any more even with the [SKU property](https://docs.microsoft.com/en-us/azure/templates/microsoft.logic/2016-06-01/workflows#sku-object) via ARM template.
![image](https://user-images.githubusercontent.com/6244148/62600386-50131d00-b921-11e9-867d-135bddd78f18.png)

**Comment by dingmeng-xue** [comment]
@ToMakeSense , thanks for your sharing. If no further question, we will close this issue soon due to inactivity.

**Comment by ToMakeSense** [comment]
@dingmeng-xue Before closing the issue, could you give any updates regarding the issue? is it a bug or something else? It's not good to close the issue due to inactivity, I think.

**Comment by dingmeng-xue** [comment]
Hi, @ToMakeSense , we cannot create the same legacy object. If currently it is still block you, could you share your environment to us?

**Comment by ToMakeSense** [comment]
@dingmeng-xue  I can't created it either, now.

**Comment by dingmeng-xue** [comment]
Is it block your current work? Since it is server side validation, we cannot provide further investigation if we cannot produce it.

**Comment by ToMakeSense** [comment]
@dingmeng-xue No, we don't have old version logic apps any more.

**Comment by ToMakeSense** [comment]
Well, I'll turn this off, but I still feel that Microsoft should try to fix the existing problem as much/fast as possible.
