### ISSUE TITLE
Get-AzBlueprint does not work with national clouds

### ISSUE THREAD

**Issue by milope** [Azure/azure-powershell#9799]
## Description

The Get-AzBlueprint cmdlet does not appear to work with national clouds. 

## Steps to reproduce

```powershell

Connect-AzAccount -EnvironmentName AzureUSGovernment

Get-AzBlueprint 
```

## Environment data

```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
#[redacted for now]
Script     0.2.3      Az.Blueprint                        {Get-AzBlueprint, Get-AzBlueprintAssignment, New-AzBluepri...
```

## Debug output

```
DEBUG: 2:33:44 PM - GetAzureRmBlueprint begin processing with ParameterSet 'SubscriptionScope'.
DEBUG: 2:33:44 PM - using account id 'username@azuregovsupport.onmicrosoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'username@azuregovsupport.onmicrosoft.com', environment: 'AzureUSGovernment', tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', Endpoint: 'https://login.microsoftonline.us/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob',
ResourceClientUri: 'https://management.core.usgovcloudapi.net/', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority 'https://login.microsoftonline.us/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/', CorrelationId: '00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', AdEndpoint: 'https://login.microsoftonline.us/', ClientId: '1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3802788Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is
running...
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3802788Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: ADAL PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is
running...
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3802788Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: === Token Acquisition started:
 CacheType: null
 Authentication Target: User
 , Authority Host: login.microsoftonline.us
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3802788Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: === Token Acquisition started:
 Authority: https://login.microsoftonline.us/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/
 Resource: https://management.core.usgovcloudapi.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Verbose: 2019-08-08T19:33:44.3802788Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Verbose: 2019-08-08T19:33:44.3802788Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: Loading from cache.
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3842796Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Deserialized 4 items to token cache.
DEBUG: [ADAL]: Verbose: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Verbose: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: Looking up cache for a token...
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: An item matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: 50.1918120066667 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: 50.1918120066667 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3842796Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: A matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3853130Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 8/8/2019 8:23:55 PM +00:00
DEBUG: [ADAL]: Information: 2019-08-08T19:33:44.3853130Z: 2395446f-c026-4563-9043-522d7abbce65 - LoggerBase.cs: === Token Acquisition finished successfully. An access token was returned: Expiration Time: 8/8/2019 8:23:55 PM +00:00Access Token Hash:
9zzYhBePwkkrjWY0SUnXusBmBEOXAHBnasMYoKY+iiM=
  User id: 3c2ad3e6-92ef-4027-9213-258a86adb5ef
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '08/08/2019 20:23:55 +00:00', MultipleResource? 'True', Tenant: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', UserId: 'username@azuregovsupport.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'username@azuregovsupport.onmicrosoft.com', Name:  , IdProvider: 'https://sts.windows.net/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/', Uid: '3c2ad3e6-92ef-4027-9213-258a86adb5ef'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '08/08/2019 20:23:55 +00:00' Comparing to '08/08/2019 19:33:44 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:50:11.5076870'
Get-AzBlueprint : Subscription Id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found in current tenant.
At line:1 char:1
+ Get-AzBlueprint
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzBlueprint], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Blueprint.Cmdlets.GetAzureRmBlueprint

DEBUG: AzureQoSEvent: CommandName - Get-AzBlueprint; IsSuccess - False; Duration - 00:00:00.5766471; Exception - Microsoft.Rest.Azure.CloudException: Subscription Id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found in current tenant.
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintDefinitionCmdletBase.<GetManagementGroupAncestorsAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintDefinitionCmdletBase.GetManagementGroupAncestorsForSubscription(String subscriptionId)
   at Microsoft.Azure.Commands.Blueprint.Cmdlets.GetAzureRmBlueprint.ExecuteCmdlet();
DEBUG: Finish sending metric.
DEBUG: 2:33:45 PM - GetAzureRmBlueprint end processing.
DEBUG: 2:33:45 PM - GetAzureRmBlueprint end processing.
```

## Error output

```
   HistoryId: 12


RequestId      :
Message        : Subscription Id 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' could not be found in current tenant.
ServerMessage  :
ServerResponse :
RequestMessage :
InvocationInfo : {Get-AzBlueprint}
Line           : Get-AzBlueprint
Position       : At line:1 char:1
                 + Get-AzBlueprint
                 + ~~~~~~~~~~~~~~~
StackTrace     :    at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintDefinitionCmdletBase.<GetManagementGroupAncestorsAsync>d__1.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.Commands.Blueprint.Cmdlets.BlueprintDefinitionCmdletBase.GetManagementGroupAncestorsForSubscription(String subscriptionId)
                    at Microsoft.Azure.Commands.Blueprint.Cmdlets.GetAzureRmBlueprint.ExecuteCmdlet()
```

Reviewing the source code [here](https://github.com/Azure/azure-powershell/blob/24dead871fd1d1f7c9e4b7049a496f98c7f66b6a/src/Blueprint/Blueprint/Cmdlets/BlueprintDefinition/BlueprintDefinitionCmdletBase.cs#L71), it appears that it hard-codes the URL based on the BlueprintConstants.MgAncestorsRequestUrlTemplate constant. Which is shown to be defined [here](https://github.com/Azure/azure-powershell/blob/baf2737708f0b6a76e45375a55c7d0811691da7c/src/Blueprint/Blueprint/Common/BlueprintConstants.cs#L24).

`public const string MgAncestorsRequestUrlTemplate = "https://management.azure.com/subscriptions/{0}?api-version=2018-11-01&$expand=ancestors";`

I've sent the same web request as above with the correct endpoint (management.usgovcloudapi.net) and it responds successfully (see below):

`{"id":"/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","subscriptionId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","tenantId":"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx","displayName":"Microsoft Azure Internal Offer - US Government","state":"Enabled","subscriptionPolicies":{"locationPlacementId":"Internal_2014-09-01","quotaId":"Internal_2014-09-01","spendingLimit":"Off"},"authorizationSource":"Legacy","managementGroupAncestors":[]}`

**Comment by filizt** [comment]
Looking.

**Comment by milope** [comment]
Hello, at least for me it's not longer throwing errors after updating. Thank you for the help!

**Comment by alex-frankel** [comment]
Closing this - thanks for the quick turnaround Filiz!
