### ISSUE TITLE
Reset-AzStorageSyncServerCertificate results in error

### ISSUE THREAD

**Issue by TEKAzure** [Azure/azure-powershell#9810]
## Description
Hello, 
trying to run Reset-AzStorageSyncServerCertificate results in one of two errors, depending on where it is run from:

From CloudShell:
"Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported)."

From local PowerShell:
"Input string was not in a correct format."

## Steps to reproduce
- Create an Azure FileSync Service, complete with cloud and server endpoints
- Attempt to reset the certificate, using Reset-AzStorageSyncServerCertificate

```powershell
Reset-AzStorageSyncServerCertificate -ResourceGroupName "myResourceGroup" -Name "myStorageSyncServiceName"
```

## Environment data

I have tested this with Azure CloudShell, as well as PS versions 5.1 and 7.0.0-preview.2.
It is reproducible on all 3 versions.

Cloudshell:
```
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 4.15.0-1052-azure #57-Ubuntu SMP Tue Jul 23 19:07:16 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

PS 5.1:
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.2828
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.2828
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

PS 7.0.0.2:
```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.2
PSEdition                      Core
GitCommitId                    7.0.0-preview.2
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

## Module versions

```powershell
Version              Name                                Repository           Description
-------              ----                                ----------           -----------
2.5.0                Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with WindowsPowerShell and PowerShell Core.…
1.6.1                Az.Accounts                         PSGallery            Microsoft Azure PowerShell - Accounts credential management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.0                Az.Advisor                          PSGallery            Microsoft Azure PowerShell - Azure Advisor Cmdlets for Advisor in Windows PowerShell and PowerShell Core. Get Advisor recommendations, Manage Advisor configu…
1.0.1                Az.Aks                              PSGallery            Microsoft Azure PowerShell - Azure managed Kubernetes cmdlets for Windows PowerShell and PowerShell Core.…
1.1.0                Az.AnalysisServices                 PSGallery            Microsoft Azure PowerShell - Analysis Services cmdlets for Windows PowerShell and PowerShell Core.…
1.2.0                Az.ApiManagement                    PSGallery            Microsoft Azure PowerShell - Api Management service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.1                Az.ApplicationInsights              PSGallery            Microsoft Azure PowerShell - Application Insights management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Creates and manag…
1.3.1                Az.Automation                       PSGallery            Microsoft Azure PowerShell - Automation service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.0                Az.Batch                            PSGallery            Microsoft Azure PowerShell - Batch service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.0                Az.Billing                          PSGallery            Microsoft Azure PowerShell - Billing service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.3.0                Az.Cdn                              PSGallery            Microsoft Azure PowerShell - CDN service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.2.0                Az.CognitiveServices                PSGallery            Microsoft Azure PowerShell - Cognitive Services management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core. Creates and manages …
2.4.1                Az.Compute                          PSGallery            Microsoft Azure PowerShell - Compute service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Manages virtual machines, hosted …
1.0.1                Az.ContainerInstance                PSGallery            Microsoft Azure PowerShell - Container Instance cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.0                Az.ContainerRegistry                PSGallery            Microsoft Azure PowerShell - Container Registry service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.3                Az.DataFactory                      PSGallery            Microsoft Azure PowerShell - Data Factory service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.0                Az.DataLakeAnalytics                PSGallery            Microsoft Azure PowerShell - Data Lake Analytics in Windows PowerShell and PowerShell Core.…
1.2.1                Az.DataLakeStore                    PSGallery            Microsoft Azure PowerShell - Azure Data Lake Store cmdlets in Windows PowerShell and PowerShell Core.…
1.0.0                Az.DeploymentManager                PSGallery            PowerShell .Net Core Microsoft Azure PowerShell - Deployment Manager cmdlets for Azure Resource Manager.…
1.0.0                Az.DevTestLabs                      PSGallery            Microsoft Azure PowerShell - DevTest Labs service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.1                Az.Dns                              PSGallery            Microsoft Azure PowerShell - DNS service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.2.1                Az.EventGrid                        PSGallery            Microsoft Azure PowerShell - Event Grid service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.3.0                Az.EventHub                         PSGallery            Microsoft Azure PowerShell - Event Hubs service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.0                Az.FrontDoor                        PSGallery            Microsoft Azure PowerShell - Front Door service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
2.0.0                Az.HDInsight                        PSGallery            Microsoft Azure PowerShell - HDInsight service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.2.0                Az.IotHub                           PSGallery            Microsoft Azure PowerShell - IoT Hub service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.3.0                Az.KeyVault                         PSGallery            Microsoft Azure PowerShell - Key Vault service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.3.0                Az.LogicApp                         PSGallery            Microsoft Azure PowerShell - Logic Apps cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.0                Az.MachineLearning                  PSGallery            Microsoft Azure PowerShell - Machine Learning Web Services cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.0                Az.ManagedServices                  PSGallery            Microsoft Azure PowerShell - ManagedServices cmdlets for Azure Resource Manager
1.0.0                Az.MarketplaceOrdering              PSGallery            Microsoft Azure PowerShell - Marketplace Ordering agreements service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.0                Az.Media                            PSGallery            Microsoft Azure PowerShell - Media service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.2.1                Az.Monitor                          PSGallery            Microsoft Azure PowerShell - Monitor service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.12.0               Az.Network                          PSGallery            Microsoft Azure PowerShell - Networking service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.0                Az.NotificationHubs                 PSGallery            Microsoft Azure PowerShell - Notification Hubs cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.3.2                Az.OperationalInsights              PSGallery            Microsoft Azure PowerShell - Operational Insights service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.
1.1.2                Az.PolicyInsights                   PSGallery            Microsoft Azure PowerShell - Azure Policy Insights cmdlets for Windows PowerShell and PowerShell Core. Allows querying policy evaluation events and complianc…
1.1.0                Az.PowerBIEmbedded                  PSGallery            Microsoft Azure PowerShell - Power BI Embedded service management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Creates and …
1.4.3                Az.RecoveryServices                 PSGallery            Microsoft Azure PowerShell - Recovery Services cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.0                Az.RedisCache                       PSGallery            Microsoft Azure PowerShell - Redis Cache service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.1                Az.Relay                            PSGallery            Microsoft Azure PowerShell - Relay service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.6.1                Az.Resources                        PSGallery            Microsoft Azure PowerShell - Azure Resource Manager and Active Directory cmdlets in Windows PowerShell and PowerShell Core.  Manages subscriptions, tenants, …
1.3.0                Az.ServiceBus                       PSGallery            Microsoft Azure PowerShell - Service Bus service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.1.1                Az.ServiceFabric                    PSGallery            Microsoft Azure PowerShell - Service Fabric cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.2                Az.SignalR                          PSGallery            Microsoft Azure PowerShell - Azure SignalR service commands for Windows PowerShell and PowerShell Core.…
1.13.1               Az.Sql                              PSGallery            Microsoft Azure PowerShell - SQL service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.5.1                Az.Storage                          PSGallery            Microsoft Azure PowerShell - Storage service data plane and management cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.  Creates…
1.2.0                Az.StorageSync                      PSGallery            Microsoft Azure PowerShell - Storage Sync cmdlets in Windows PowerShell and PowerShell Core. Manages operations pertaining to Azure File Sync in PowerShell.
1.0.0                Az.StreamAnalytics                  PSGallery            Microsoft Azure PowerShell - Stream Analytics service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.0.1                Az.TrafficManager                   PSGallery            Microsoft Azure PowerShell - Traffic Manager service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
1.4.0                Az.Websites                         PSGallery            Microsoft Azure PowerShell - App Service (Web Apps) service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.…
```

## Debug output

From CloudShell:
```
PS Azure:\> Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXX -StorageSyncServiceName XXXXXX
DEBUG: >> MakePath([Az.StorageSync, Reset-AzStorageSyncServerCertificate])
DEBUG: << MakePath([Az.StorageSync, Reset-AzStorageSyncServerCertificate])
DEBUG: 2:53:05 PM - ResetServerCertificateCommand begin processing with ParameterSet 'StringParameterSet'.
DEBUG: 2:53:05 PM - using account id 'MSI@XXXXX'...
Reset-AzStorageSyncServerCertificate : Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported).
At line:1 char:1
+ Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXXX - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Reset-AzStorageSyncServerCertificate], MarshalDirectiveException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand

DEBUG: AzureQoSEvent: CommandName - Reset-AzStorageSyncServerCertificate; IsSuccess - False; Duration - 00:00:00.0109758; Exception - System.Runtime.InteropServices.MarshalDirectiveException: Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported).
   at Commands.StorageSync.Interop.DataObjects.Win32Helper.CoCreateInstance(Guid& clsid, Object inner, UInt32 context, Guid& uuid, IntPtr& rReturnedComObject)
   at Commands.StorageSync.Interop.Clients.EcsManagementInteropClient.Initialize()
   at Commands.StorageSync.Interop.Clients.EcsManagementInteropClient..ctor()
   at Microsoft.Azure.Commands.StorageSync.Common.StorageSyncResourceManager.CreateEcsManagement()
   at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.TriggerCertificateRollover(String resourceGroupName, Guid subscriptionId, String storageSyncServiceName)
   at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.<ExecuteCmdlet>b__24_0()
   at Microsoft.Azure.Commands.StorageSync.Common.StorageSyncClientCmdletBase.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 2:53:05 PM - ResetServerCertificateCommand end processing.
DEBUG: 2:53:05 PM - ResetServerCertificateCommand end processing.
```

From PowerShell:
```
PS C:\Program Files\PowerShell\7-preview> Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXXXXX -StorageSyncServiceName XXXXXXXX
DEBUG: 2:52:14 PM - ResetServerCertificateCommand begin processing with ParameterSet 'StringParameterSet'.
DEBUG: 2:52:14 PM - using account id 'XXXXX@XXXXXX'...
Reset-AzStorageSyncServerCertificate : Input string was not in a correct format.
At line:1 char:1
+ Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXXXX - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Reset-AzStorageSyncServerCertificate], FormatException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand

DEBUG: AzureQoSEvent: CommandName - Reset-AzStorageSyncServerCertificate; IsSuccess - False; Duration - 00:00:00.0772194; Exception - System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object arg0)
   at Commands.StorageSync.Interop.Clients.SyncServerCertificateRolloverClient.RolloverSecondaryCertificate(Action`1 verboseLogger, Guid& serverId)
   at Commands.StorageSync.Interop.Clients.SyncServerCertificateRolloverClient.RolloverServerCertificate(String certificateProviderName, String certificateHashAlgorithm, UInt32 certificateKeyLength, Action`2 triggerServiceRollover, Action`1 verboseLogger)
   at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.TriggerCertificateRollover(String resourceGroupName, Guid subscriptionId, String storageSyncServiceName)
   at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.<ExecuteCmdlet>b__24_0()
   at Microsoft.Azure.Commands.StorageSync.Common.StorageSyncClientCmdletBase.ExecuteClientAction(Action action)
   at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 2:52:15 PM - ResetServerCertificateCommand end processing.
DEBUG: 2:52:15 PM - ResetServerCertificateCommand end processing.
```
## Error output

From CloudShell:
```
Message        : Cannot marshal 'parameter #2': Invalid managed/unmanaged type combination (Marshaling to and from COM interface pointers isn't supported).
StackTrace     :    at Commands.StorageSync.Interop.DataObjects.Win32Helper.CoCreateInstance(Guid& clsid, Object inner, UInt32 context, Guid& uuid, IntPtr& rReturnedComObject)
                    at Commands.StorageSync.Interop.Clients.EcsManagementInteropClient.Initialize()
                    at Commands.StorageSync.Interop.Clients.EcsManagementInteropClient..ctor()
                    at Microsoft.Azure.Commands.StorageSync.Common.StorageSyncResourceManager.CreateEcsManagement()
                    at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.TriggerCertificateRollover(String resourceGroupName, Guid subscriptionId, String
                 storageSyncServiceName)
                    at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.<ExecuteCmdlet>b__24_0()
                    at Microsoft.Azure.Commands.StorageSync.Common.StorageSyncClientCmdletBase.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.Runtime.InteropServices.MarshalDirectiveException
InvocationInfo : {Reset-AzStorageSyncServerCertificate}
Line           : Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXXX -StorageSyncServiceName XXXXXXX
Position       : At line:1 char:1
                 + Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXXXX - ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

From PowerShell:
```
Message        : Input string was not in a correct format.
StackTrace     :    at System.Text.StringBuilder.FormatError()
                    at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
                    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
                    at System.String.Format(String format, Object arg0)
                    at Commands.StorageSync.Interop.Clients.SyncServerCertificateRolloverClient.RolloverSecondaryCertificate(Action`1 verboseLogger, Guid& serverId)
                    at Commands.StorageSync.Interop.Clients.SyncServerCertificateRolloverClient.RolloverServerCertificate(String certificateProviderName, String certificateHashAlgorithm, UInt32 certificateKeyLength, Action`2
                 triggerServiceRollover, Action`1 verboseLogger)
                    at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.TriggerCertificateRollover(String resourceGroupName, Guid subscriptionId, String storageSyncServiceName)
                    at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.<ExecuteCmdlet>b__24_0()
                    at Microsoft.Azure.Commands.StorageSync.Common.StorageSyncClientCmdletBase.ExecuteClientAction(Action action)
                    at Microsoft.Azure.Commands.StorageSync.Cmdlets.ResetServerCertificateCommand.ExecuteCmdlet()
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.<>c__3`1.<ExecuteSynchronouslyOrAsJob>b__3_0(T c)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet, Action`1 executor)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.CmdletExtensions.ExecuteSynchronouslyOrAsJob[T](T cmdlet)
                    at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
Exception      : System.FormatException
InvocationInfo : {Reset-AzStorageSyncServerCertificate}
Line           : Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXXXX -StorageSyncServiceName XXXXXX
Position       : At line:1 char:1
                 + Reset-AzStorageSyncServerCertificate -ResourceGroupName XXXXXX - ...
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by markcowl** [comment]
@ankushbindlish2 @fedyashov Can you take a look?

**Comment by Solidshadow** [comment]
We just worked around this with the help of azure techsupport

It seems only one magical combination of commands works so far:

The paramaters you need are the following:
SubscriptionId{guid}  (get-azsubscription)
TenantID{guid} (get-azsubscription)
ResourceGroupName{string} 
StorageSyncServiceName{string}

1. Import-Module "C:\Program Files\Azure\StorageSyncAgent\StorageSync.Management.PowerShell.Cmdlets.dll"
2. Login-AzureRmStorageSync -SubscriptionID <guid> -TenantID <guid>
3. Reset-AzureRmStorageSyncServerCertificate -SubscriptionId <guid> -ResourceGroupName <string> -StorageSyncServiceName <string>

4. go to services.msc and restart the "Storage Sync Agent"  service

**Comment by ankushbindlish2** [comment]
This command has to be run on the server itself.
