### ISSUE TITLE
Az module: Request headers composed with two ?? before api-version 

### ISSUE THREAD

**Issue by viananth** [Azure/azure-powershell#9921]
## Description
With the new Az modules, any http call made is composed with two ?? which results in 400-Bad request.

**GET https://adminmanagement.local.azurestack.external/subscriptions/d169f47f-1b48-4871-8193-42429cc55d44/providers/Microsoft.Compute/virtualMachines??api-version=2017-12-01 HTTP/1.1**
x-ms-unique-id: 2, 3
User-Agent: PSVersion/v5.1.17763.592
Authorization: Bearer [Redacted]
Host: adminmanagement.local.azurestack.external
Connection: Keep-Alive

> 
> `HTTP/1.1 400 Bad Request
> Cache-Control: no-cache
> Pragma: no-cache
> Content-Type: application/json; charset=utf-8
> Expires: -1
> x-ms-failure-cause: gateway
> x-ms-request-id: 0c0bbaf9-30aa-42bf-ad85-9b710b35bd83
> x-ms-correlation-request-id: 0c0bbaf9-30aa-42bf-ad85-9b710b35bd83
> x-ms-routing-request-id: LOCAL:20190827T201619Z:0c0bbaf9-30aa-42bf-ad85-9b710b35bd83
> Strict-Transport-Security: max-age=31536000; includeSubDomains
> X-Content-Type-Options: nosniff
> Date: Tue, 27 Aug 2019 20:16:19 GMT
> Content-Length: 137
> 
> {"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

## Steps to reproduce

Import the latest nightly builds from Az powershell 

```powershell
Get-AzVm
get-azvm : The server responded with a Request Error, Status: BadRequest
At line:1 char:1
+ get-azvm
+ ~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SubscriptionId = System.String[] }:<>f__AnonymousType7`1) [Get-AzVM_List 
   2], UndeclaredResponseException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.PowerShell.Cmdlets.Compute.Cmdlets.GetAzVM_List2


```

## Environment data

```
PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.17763.592                                                                                
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.17763.592                                                                               
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1       
```

## Module versions

```powershell
PS C:\Windows\system32> gmo

ModuleType Version    Name                                ExportedCommands                                                  
---------- -------    ----                                ----------------                                                  
Script     1.6.0      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Connect-A...
Script     0.0.1      Az.Compute                          {ConvertTo-AzVMManagedDisk, Export-AzLogAnalyticRequestRateByIn...
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet, New-IseSnippet}               
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpoint-Computer, Clear-Content...}
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertTo-SecureString, Get-Acl, Get...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Object...}         
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSSP, Disconnect-WSMan, Enable-...
Binary     1.0.0.1    PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package, Get-PackagePr...
Script     1.0.0.1    PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Find-RoleCapabili...

```

## Debug output

```

PS C:\Windows\system32> get-azvm
DEBUG: 1:24:44 PM - GetAzureRMContextCommand begin processing with ParameterSet 'GetSingleContext'.
DEBUG: 1:24:44 PM - using account id 'ciserviceadmin@msazurestack.onmicrosoft.com'...
DEBUG: 1:24:44 PM - GetAzureRMContextCommand end processing.
DEBUG: 1:24:44 PM - GetAzureRMContextCommand end processing.
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: [CmdletProcessRecordAsyncStart]: Created new QosEvent for command 'Get-AzVM_List2': AzureQoSEvent: CommandName - Get-A
zVM_List2; IsSuccess - False; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://management.azure.com/subscriptions/d169f47f-1b48-4871-8193-42429cc55d44/providers/Microsoft.Comput
e/virtualMachines?api-version=2017-12-01
DEBUG: RequestCreated: https://management.azure.com/subscriptions/d169f47f-1b48-4871-8193-42429cc55d44/providers/Microsoft.Co
mpute/virtualMachines?api-version=2017-12-01
DEBUG: HeaderParametersAdded: https://management.azure.com/subscriptions/d169f47f-1b48-4871-8193-42429cc55d44/providers/Micro
soft.Compute/virtualMachines?api-version=2017-12-01
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://management.azure.com/subscriptions/d169f47f-1b48-4871-8193-42429cc55d44/providers/Microsoft.Compute/virtualMachines?a
pi-version=2017-12-01

Headers:

Body:



DEBUG: BeforeCall: 
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: ADAL PCL.Desk
top with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bd
c3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: ADAL PCL.Desk
top with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version '2a8bec6c4c76d0c1ef819b55bd
c3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: === Token Acq
uisition started: 
	CacheType: null
	Authentication Target: User
	, Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: === Token Acq
uisition started:
	Authority: https://login.microsoftonline.com/d9b782d5-d098-4374-8f2c-3907cc34611c/
	Resource: https://adminmanagement.azurestackci11.onmicrosoft.com/1827da87-0543-432a-94d5-6f3befa90333
	ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
	CacheType: null
	Authentication Target: User
	
DEBUG: [ADAL]: Verbose: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: Loading from cach
e.
DEBUG: [ADAL]: Verbose: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: Loading from cach
e.
DEBUG: [ADAL]: Verbose: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: Looking up cache 
for a token...
DEBUG: [ADAL]: Verbose: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: Looking up cache 
for a token...
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: An item match
ing the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: An item match
ing the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: 49.8849614633
333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: 49.8849614633
333 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: A matching it
em (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: A matching it
em (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: === Token Acq
uisition finished successfully. An access token was returned: Expiration Time: 8/27/2019 9:14:37 PM +00:00
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: ffa1211a-e665-4e41-838f-fa53effedded - LoggerBase.cs: === Token Acq
uisition finished successfully. An access token was returned: Expiration Time: 8/27/2019 9:14:37 PM +00:00Access Token Hash: 
8KwUfqzHzrnhfGv1h9Jab0t7cMz68oojYoD2JpkGExk=
	 User id: 24fd748b-2d15-430f-b0d1-3e7e452346d8
DEBUG: [ADAL]: Information: 2019-08-27T20:24:44.6520079Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs: Serializing t
oken cache with 1 items.
DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 32df3a39-f5aa-4fbb-9e5d-89aa63d08b87
x-ms-correlation-request-id   : 32df3a39-f5aa-4fbb-9e5d-89aa63d08b87
x-ms-routing-request-id       : LOCAL:20190827T202444Z:32df3a39-f5aa-4fbb-9e5d-89aa63d08b87
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Tue, 27 Aug 2019 20:24:44 GMT

Body:
{
  "error": {
    "code": "MissingApiVersionParameter",
    "message": "The api-version query parameter (?api-version=) is required for all requests."
  }
}


DEBUG: ResponseCreated: 
DEBUG: Finally: 
get-azvm : The server responded with a Request Error, Status: BadRequest
At line:1 char:1
+ get-azvm
+ ~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ SubscriptionId = System.String[] }:<>f__AnonymousType7`1) [Get-AzVM_List 
   2], UndeclaredResponseException
    + FullyQualifiedErrorId : BadRequest,Microsoft.Azure.PowerShell.Cmdlets.Compute.Cmdlets.GetAzVM_List2
 
DEBUG: [CmdletProcessRecordAsyncEnd]: Sending new QosEvent for command 'Get-AzVM_List2': AzureQoSEvent: CommandName - Get-AzV
M_List2; IsSuccess - True; Duration - 00:00:00; Exception - ;
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing: 

PS C:\Windows\system32> 
```

## Error output

```
PS C:\Windows\system32>  Resolve-AzError
DEBUG: 1:25:10 PM - ResolveError begin processing with ParameterSet 'AnyErrorParameterSet'.
DEBUG: 1:25:10 PM - using account id 'ciserviceadmin@msazurestack.onmicrosoft.com'...


   HistoryId: 17


Message        : The server responded with a Request Error, Status: BadRequest
StackTrace     :    at Microsoft.Azure.PowerShell.Cmdlets.Compute.ComputeManagementClient.<VirtualMachinesListAll_Call>d__82
                 7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Azure.PowerShell.Cmdlets.Compute.ComputeManagementClient.<VirtualMachinesListAll_Call>d__82
                 7.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.PowerShell.Cmdlets.Compute.ComputeManagementClient.<VirtualMachinesListAll>d__821.Mov
                 eNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Azure.PowerShell.Cmdlets.Compute.Cmdlets.GetAzVM_List2.<ProcessRecordAsync>d__55.MoveNext()
Exception      : Microsoft.Azure.PowerShell.Cmdlets.Compute.Runtime.UndeclaredResponseException
InvocationInfo : {Get-AzVM_List2}
Line           : get-azvm
Position       : At line:1 char:1
                 + get-azvm
                 + ~~~~~~~~
HistoryId      : 17
```

**Comment by markcowl** [comment]
Fix for this issue building here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/526/

**Comment by viananth** [comment]
Mark, the above build fixed "??" issue. But with the right profile (2019-03-01-hybrid) selected, the modules make rest calls to the latest api versions and it fails against azure stack.

Fiddler: GET /subscriptions/f05e2fce-6ade-452c-a34e-fb62af806e38/resourcegroups?api-version=2019-05-10 HTTP/1.1

PowerShell:

```
`
PS C:\Users\Administrator> Select-AzProfile -Name 2019-03-01-hybrid
PS C:\Users\Administrator> get-azprofile

Name              Description
----              -----------
2019-03-01-hybrid A snapshot of the Service API versions in AzureStack, Azure Sovereign clouds, and the Azure Global...



PS C:\Users\Administrator> Get-AzResourceGroup | fl
DEBUG: 3:46:59 PM - GetAzureResourceGroupCmdlet begin processing with ParameterSet 'GetByResourceGroupName'.
DEBUG: 3:46:59 PM - using account id 'ciserviceadmin@msazurestack.onmicrosoft.com'...
DEBUG: [Common.Authentication]: Authenticating using Account: 'ciserviceadmin@msazurestack.onmicrosoft.com',
environment: 'AzureStackAdmin', tenant: '76440dfb-c97c-4fee-8f6c-dff8ddbe816f'
DEBUG: [Common.Authentication]: Authenticating using configuration values: Domain:
'76440dfb-c97c-4fee-8f6c-dff8ddbe816f', Endpoint: 'https://login.microsoftonline.com/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirect: 'urn:ietf:wg:oauth:2.0:oob', ResourceClientUri:
'https://adminmanagement.azurestackci09.onmicrosoft.com/cb0a4667-d698-458e-91a0-77f3b6419281', ValidateAuthority:
'True'
DEBUG: [Common.Authentication]: Acquiring token using context with Authority
'https://login.microsoftonline.com/76440dfb-c97c-4fee-8f6c-dff8ddbe816f/', CorrelationId:
'00000000-0000-0000-0000-000000000000', ValidateAuthority: 'True'
DEBUG: [Common.Authentication]: Acquiring token using AdalConfiguration with Domain:
'76440dfb-c97c-4fee-8f6c-dff8ddbe816f', AdEndpoint: 'https://login.microsoftonline.com/', ClientId:
'1950a258-227b-4e31-a9cf-717495945fc2', ClientRedirectUri: urn:ietf:wg:oauth:2.0:oob
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: ADAL
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: ADAL
PCL.Desktop with assembly version '3.19.2.6005', file version '3.19.50302.0130' and informational version
'2a8bec6c4c76d0c1ef819b55bdc3cda2d2605056' is running...
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: ===
Token Acquisition started:
 CacheType: null
 Authentication Target: User
 , Authority Host: login.microsoftonline.com
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: ===
Token Acquisition started:
 Authority: https://login.microsoftonline.com/76440dfb-c97c-4fee-8f6c-dff8ddbe816f/
 Resource: https://adminmanagement.azurestackci09.onmicrosoft.com/cb0a4667-d698-458e-91a0-77f3b6419281
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: null
 Authentication Target: User

DEBUG: [ADAL]: Verbose: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: Loading
from cache.
DEBUG: [ADAL]: Verbose: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: Loading
from cache.
DEBUG: [ADAL]: Verbose: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: Looking up
cache for a token...
DEBUG: [ADAL]: Verbose: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: Looking up
cache for a token...
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: An item
 matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: An item
 matching the requested resource was found in the cache
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs:
57.72012069 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs:
57.72012069 minutes left until token in cache expires
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: A
matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: A
matching item (access token or refresh token or both) was found in the cache
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: ===
Token Acquisition finished successfully. An access token was returned: Expiration Time: 9/23/2019 11:44:42 PM +00:00
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 81b24a2a-b9bc-474b-9325-c704657138d0 - LoggerBase.cs: ===
Token Acquisition finished successfully. An access token was returned: Expiration Time: 9/23/2019 11:44:42 PM
+00:00Access Token Hash: 0b0ZkIfhd9Byvd+QSuTdHo8OhwnwjS6R7yMHMTZ22o8=
  User id: 49b6cee4-e62f-4f9c-99e2-4c4f29036593
DEBUG: [ADAL]: Information: 2019-09-23T22:46:59.0438293Z: 00000000-0000-0000-0000-000000000000 - LoggerBase.cs:
Serializing token cache with 1 items.
DEBUG: [Common.Authentication]: Renewing Token with Type: 'Bearer', Expiry: '09/23/2019 23:44:42 +00:00',
MultipleResource? 'True', Tenant: '76440dfb-c97c-4fee-8f6c-dff8ddbe816f', UserId:
'ciserviceadmin@msazurestack.onmicrosoft.com'
DEBUG: [Common.Authentication]: User info for token DisplayId: 'ciserviceadmin@msazurestack.onmicrosoft.com', Name:
Service Admin CI, IdProvider: 'https://sts.windows.net/5454420b-2e38-4b9e-8b56-1712d321cf33/', Uid:
'49b6cee4-e62f-4f9c-99e2-4c4f29036593'
DEBUG: [Common.Authentication]: Checking token expiration, token expires '09/23/2019 23:44:42 +00:00' Comparing to
'09/23/2019 22:46:59 +00:00' With threshold '00:05:00', calculated time until token expiry: '00:57:43.2072414'
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
GET

Absolute Uri:
https://adminmanagement.local.azurestack.external/subscriptions/f05e2fce-6ade-452c-a34e-fb62af806e38/resourcegroups?api
-version=2019-05-10

Headers:
x-ms-client-request-id        : 803bc3a4-2054-4a1b-8e02-61aaeb819391
accept-language               : en-US

Body:


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Pragma                        : no-cache
x-ms-failure-cause            : gateway
x-ms-request-id               : 364f9a58-43f5-4c74-9aa8-79eed3edf46e
x-ms-correlation-request-id   : 364f9a58-43f5-4c74-9aa8-79eed3edf46e
x-ms-routing-request-id       : LOCAL:20190923T224659Z:364f9a58-43f5-4c74-9aa8-79eed3edf46e
Strict-Transport-Security     : max-age=31536000; includeSubDomains
X-Content-Type-Options        : nosniff
Cache-Control                 : no-cache
Date                          : Mon, 23 Sep 2019 22:46:59 GMT

Body:
{
  "error": {
    "code": "InvalidApiVersionParameter",
    "message": "The api-version '2019-05-10' is invalid. The supported versions are
'2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-
10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-0
1,2014-01-01,2013-03-01,2014-02-26,2014-04'."
  }
}

Get-AzResourceGroup : The api-version '2019-05-10' is invalid. The supported versions are '2018-09-01,2018-08-01,2018-0
7-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016
-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-
02-26,2014-04'.
At line:1 char:1
+ Get-AzResourceGroup | fl
+ ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzResourceGroup], CloudException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureResourceGroupCmd
   let

DEBUG: 3:46:59 PM - GetAzureResourceGroupCmdlet end processing.
DEBUG: 3:46:59 PM - GetAzureResourceGroupCmdlet end processing.
`
```

**Comment by markcowl** [comment]
Fixed
